### ISSUE TITLE
Room Editor: Duplicate of child room has layer inheritance enabled even if it was disabled because duplicating

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1045]
GM-4658

"Description: If you duplicate a child room, and that room has inherit deselected on a layer, that trait is not duplicated, but is instead it's set to the parents inherited value.
Note I recorded the example on the prior Beta version, IDE 46, but noticed a new version was available, so downloaded that and tested it on IDE 71 and it did the same thing."

 

Steps:
 - Import attached project
 - Go to rm_07 and notice that layer Tile_100 has inheritance disabled
 - Duplicate rm_07
 - Notice that the inheritance on Tile_100 on new room is enabled

Repro: 100%

**Comment by Emc1923** [comment]
This is no longer happening as of  IDE v2024.800.0.607  Runtime v2024.800.0.631.
