### ISSUE TITLE
Building Projects: [Mac IDE] Larger projects can give massive increase in time required to build versus Windows IDE

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1053]
GM-4521
Steps
- import and run the project,  targeting Windows and notice the build time
- Import and run on the mac version or targeting Mac os
- notice the project keeps building if left to attempt building for over an hour

**Comment by sanbox-irl** [comment]
Hi, I'd like to re-up how important this is -- on Fields of Mistria, this has caused large problems for the few of us who use macOS

**Comment by sanbox-irl** [comment]
yup looks fixed. thanks @rwkay !
