### ISSUE TITLE
Image Editor: Cannot import colors from sprite

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1058]
GM-4309
Bug Type: Bug in the UI or IDE functionality
Ide: 2022.3.0.625
Runtime: 2022.3.0.497
Os: Windows 10
Platforms: Windows
Components: Sprite Editor,Image Editor

Description: Steps to reproduce :
- Make a new sprite
- Click on Edit Sprite
- In the Colors Tab on the side, select the Hamburger menu and click on the "Import colours from sprite"
- Choose a sprite to import colors from

Expected Result :
- Colors are imported

Actual Result :
- Nothing happens

**Comment by YYDan** [comment]
This one has been quietly fixed at some point prior to 2023.8 - however, the original report is still open and so the fix was never in the old release notes. Closing now.
