### ISSUE TITLE
Mac - redefine keys - setting run or  debug as current key starts action

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1067]
GM-4096

If a user is in the key redefine and goes to redefine keys and then tries restting run or debug as the current value (f5 f6) then the project will do this action

Steps
-Open a project on mac
- open pref - key redefine
- go to run or debug and click the key in the tab so it clears
-  now press f5/f6 and this action will be carried out

**Comment by SmithTom6304** [comment]
Fixed - this seems to have been fixed as part of the hotkeys refactor last year.

**Comment by SamTHodson** [comment]
Verified in IDE v2024.400.0.518  Runtime v2024.400.0.539
