### ISSUE TITLE
DPI Issues on Macbook Pro

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1085]
GM-3685

I opened up GMS2 on a MacBook Pro for the first time and immediately noticed that everything was scaled up dramatically.

The screenshots are straight out the box on my default screen resolution settings at: (3024 × 1964).This is overall a bad experience.

*Users most likely do not know about DPI issues*
 * Users might think this is how GMS2 is normally, use it like this and have a poor experience and give up.
 * They may use the tool with extremely small workspaces (see room & game options screenshot) and pixelated imagery.
 * If users look for tutorials or screenshots and they see their IDE looks different they may assume theirs is broken.

*Changing DPI settings*
 * If the user is more advanced they may realise the IDE is not supposed to act/look like this and change the settings - this is not easy to find/do
 * Initially the cog icon on the top bar is visible however this opens GAME OPTIONS and DPI settings cannot be found.
 * The DPI settings are in GENERAL of file > preferences at the bottom - difficult to spot (user may be looking for "display" tab or similar).
 * The terminology of DPI may not be familiar to a lot of users.
 * Trial and error slider - User has to tweak the slider - restart the IDE and see if the percentage they chose worked. For my laptop I have to set to 63%.

Every other tool I have used responds to the screen and resolution - whatever the user is presented with should be right for them.

In general this looks poor and immediately creates a UX issue - that we force users to solve themselves in a convoluted way.

This has potentially put off new users/developers.

**Comment by YYDan** [comment]
"Duplicate" of https://github.com/YoYoGames/GameMaker-Bugs/issues/3196
