### ISSUE TITLE
Audio/Texture Groups Editor: [Mac IDE] Move To arrow overlaps text

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1097]
GM-3415

In both the Audio and Texture Groups Editor right-click menu, the Move To text is slightly overlapped by the arrow to expand it.

This appears the same on multiple DPI settings.

![image-2022-01-25-10-52-44-253](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/4664b022-3263-4f81-9708-f3e615cf7609)

*Steps:*
 - Start GMS2 on Mac and open/create a project
 - Create a Sound
 - Go to Tools > Audio Groups
 - Right-click the new Sound
 - Observe the issue

*Repro:* 100%

**Comment by toby-yoyo** [comment]
This no longer seems to be an issue. See the images below:

**Audio Groups**

![Image](https://github.com/user-attachments/assets/7ce3769b-2ee9-4ec9-b95e-f71ef8a126c2)

**Texture Groups**

![Image](https://github.com/user-attachments/assets/c8b7c779-a606-4e49-a765-dd8db1f23d13)
