### ISSUE TITLE
Startup: [Mac IDE] GMS2 crashes and blames permissions error for Windows filepath when failing to find a matching runtime on the current RSS feed (only affects staff?)

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1121]
GM-2783

Since the latest update,2.3.7.600, if a user tries to open the gms2 either from icon bar or via right click open with, gms2 will start to load then close half way through the loading screen. Yet on initial update the program and start page opened as expected.

Steps
 - Update to the 2.3.7.600 build
 - the start page will show as expected
 - close and click the gms2 icon in the program bar
 - the loading banner will show then close half way through
 - find an existing project and open with "right click open with" and choose gms2
 - the above will happen

**Comment by YYDan** [comment]
Super-old version and very little info here, so just closing.

If still an issue in current/future releases, we should re-report using the current bug report standards, etc.
