### ISSUE TITLE
sound mixer, play/pause button based on shortest audio

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1144]
GM-2466

In the sound mixed, if there are multiple tracks, then the play/pause button's functionality is based on the shortest track. This means if tracks are still playing the user cannot pause the current selection of audio.

!image-2021-10-26-11-22-44-292.png!

*Steps*
 - Open a project with several audio files
 - Open a sound file
 - Open the sound mixer
 - Have multiple tracks in the one list as above
 - make sure one of the tracks is noticeably shorter than the rest
 - press play
 - notice the pause button changes to play once the shortest has played meaning the user cannot stop the other audio without closing the mixer

*Expected*

There should be the ability to pause and or stop the all the audio that is still playing for these circumstances

**Comment by mgeddesGM** [comment]
still present in  IDE v2024.8.1.170  Runtime v2024.8.1.217

**Comment by toby-yoyo** [comment]
The group play button should now revert from the pause icon to play icon only after all sounds in the group have finished playing.

Example project: [gmb-1144-x.zip](https://github.com/user-attachments/files/18115197/gmb-1144-x.zip)

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
