### ISSUE TITLE
Jenkins Feature Builds don't handle Linux properly

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1156]
GM-2275

The Zeus-Feature-IDE builds generate Windows, macOS and Linux builds properly, however the full Zeus-Feature builds only do Windows and macOS - but did have a build step for Linux that could fail.

Additionally, there are oddities with how it's looking for Linux packages, as dashes can be missing, causing build fails at the last stage - and as this builds a runtime as well, it is not a quick process.

**Comment by rwkay** [comment]
we have not used Jenkins in a long time... I presume you mean GitHub Actions?
