### ISSUE TITLE
Included Files: zip_unzip function leaves out 0 byte files in Included Files

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1208]
GM-1524

The function "zip_unzip" does not extract a 0 byte file from Included Files.

*Steps:*
 - Start GMS2 and open/create a project
 - Open "nobytes.zip" in included files
 - Notice two text files
 - Run project
 - Go to "Users/USERNAME/AppData/Local/ZeroByteExtraction/extracted"
 - Notice only one file present

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1700
