### ISSUE TITLE
Preferences: Default "My Projects" directory is created on IDE start

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1232]
GM-1380

Issue:
 After setting a new path for the My Projects preferences entry, a new IDE start will create a directory in the old Default location

Repro:
- Open Preferences > General > Paths
- Change the 'My Projects' directory entry to something other than the Default value
- Click Apply/OK and Close
- Rename or delete the default My Project location (C:\Users\UserName\Documents\GameMakerStudio2)
- Restart the IDE
- Observe that the Default directory is created

**Comment by YYDan** [comment]
Closing as "duplicate" of https://github.com/YoYoGames/GameMaker-Bugs/issues/4620
