### ISSUE TITLE
Search and Replace : Cannot press Enter to search when window is docked

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1250]
GM-1332

When using Search & Replace while docked, the user cannot press Enter to start the search. This works when the window is undocked. 

*Steps to reproduce:*
 - Create a project
 - Create a script
 - Open Search and Replace 
 - Dock the Search and Replace window
 - Type "function" into the search box
 - Press Enter 
 - Observe that the search does not start

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/854
