### ISSUE TITLE
Workspaces [macOS] : CTRL + Tab does not work correctly on macOS

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1268]
GM-1243

Using CTRL + Tab on macOS opens the navigation window for only a second before circling between the recent windows.

*Steps to reproduce:*
 - Launch the IDE on macOS
 - Open a project and some resources
 - Press CTRL + Tab
 - Observe the issue

*Notes:*

Please see the video attached.

**Comment by Emc1923** [comment]
No longer an issue as of  IDE v2024.800.0.611  Runtime v2024.800.0.635. Closing.
