### ISSUE TITLE
Sequence Editor: "Position" parameter for audio tracks does nothing

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1327]
GM-974

Audio tracks have a "position" parameter, but when set this does not change the position of the audio within the listener space... From what I can see it does nothing at all! I would expect it to pan the sound around the default listener position (which I'd assume is the origin of the sequence). Note that even when added to a room and the project it is run, I don't notice any panning.

IDE 23.1.1.69

Runtime: 23.1.1.61

**Comment by toby-yoyo** [comment]
This seems to no longer be an issue. I'll be closing this alongside https://github.com/YoYoGames/GameMaker-Bugs/issues/4578, whose test project should be able to verify this.

**Comment by toby-yoyo** [comment]
Resolved by #4578.

**Comment by Emc1923** [comment]
Verified as of Beta IDE v2024.600.0.562 Beta Runtime v2024.600.0.580
