### ISSUE TITLE
Sequences Editor: Pitch change on audio tracks not working

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1328]
GM-973

I have a test project with an audio track and various pitch changes on a parameter track. However, when I play the track, I don't hear any changes.

IDE 23.1.1.69

EDIT: Note that this is in the IDE. When the sequence is added to a room, and then the project is run, the pitch is changed as expected.

**Comment by toby-yoyo** [comment]
Linking to https://github.com/YoYoGames/GameMaker-Bugs/issues/4578, which will add this as well.

**Comment by toby-yoyo** [comment]
Resolved by #4578.

Test project: [gmb-1328-x.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15276511/gmb-1328-x.zip)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.580
