### ISSUE TITLE
When using a spine sprite, path deform tracks do not play when doing a collision check in between two skin changes

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1485]
#Description
I previously reported a very similar issue related to doing collision checks inbetween skin swaps, and it's been mostly fixed but another issue has popped up in it's place. Now, the animation doesn't play the path deform track at all when doing a collision check inbetween two skeleton_skin_set calls, regardless of if the collision is true or not. For this particular sprite, both skins contain bounding box elements, don't know if that has an effect or not.

#Steps
Call skeleton_skin_set, call place_meeting, and then call skeleton_skin_set again. The place_meeting does not need to be attached to any statements. There's a couple things specific to the sprite I used that may be relevant, as mentioned in the description:
- The part of the animation that doesn't play correctly is the path deform track. Other parts of the animation with no path deform play just fine.
- The skins used both have a bounding box element attached, since the goal of this code is to use different spine-defined collision masks for different collision checks.

[0c07dde3-46cb-45cc-951b-0c19b8d2149b](https://api.gamemaker.io/api/github/downloads/0c07dde3-46cb-45cc-951b-0c19b8d2149b)

**Comment by yoyo-danielc** [comment]
Hi @KormexGit,

It looks like the sample project didn't get uploaded correctly when you submitted this bug before. Would you be able to add a sample project to this ticket?

Thanks
Daniel

**Comment by KormexGit** [comment]
@yoyo-danielc 

Here's a project, had to do a zip since github doesn't let me attach a yyz directly. While re-creating it I realized I missed mentioning a step that the object that the spine object is checking for collision with must exist in the room, even if the collision isn't happening. I also determined that the path deform track is just straight up not playing at all, I tried removing it from my original animation and it looked like the bugged version here.

[Spine Skin Bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13876463/Spine.Skin.Bug.zip)

**Comment by yoyo-danielc** [comment]
@KormexGit

Thanks for the sample. Just to confirm I'm debugging the right thing, the observable effect of this bug is the tail on the upper sprite not wiggling back and forth as much as the lower one as shown in this video, right?

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/eff2ff1d-247c-409f-a62e-578cd1dd0443

**Comment by KormexGit** [comment]
@yoyo-danielc 
Yes, the bottom one is what it's supposed to look like, the upper one is the bug. Both are using the same animation, the only difference is that the upper one is doing a collision check in between two skin changes.

**Comment by KormexGit** [comment]
The only attachments inside skin placeholders in the source project are bounding box attachments, the path and all of the visuals aren't connected to any particular skin at all

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/87a26350-9537-465f-a114-aef063e62466)

Does it reset everything that's a child of the same bone?

**Comment by KormexGit** [comment]
[Spine Bug Test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13887731/Spine.Bug.Test.zip)
Here's another test project with original spine project included. I made a new spine project with a bare minimum of one animated path and two skins with nothing attached to them, and it still prevents the path deform from animating.

**Comment by yoyo-danielc** [comment]
Thanks for the Spine project - that clears things up.

Some of the state of attachments NOT being replaced when switching skin is being reset after the skin is changed, which we can't find a good reason for at this time, so fix is queued up for the beta branch.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.463  Runtime v2024.200.0.479 for both projects.

Thank you.
