### ISSUE TITLE
In-Game: time_source_start() execution time increases with additional time sources

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1491]
GM-8187

When a user has a lot of time sources running in their project at once, the time_source_start() function takes longer to execute than if there are fewer time sources. The more time sources present, the longer the execution time for the function. If a new time source is started, this time increases even more. A user reports that when there are a few thousand sources, this can even lead to freezes.

*Expected*
It is expected that time source functions will take the same time to execute no matter the number of other time sources present and running.

*Steps*
- Open attached project
- Run game
- Press Space to start a time source
- Observe time increasing
- Press Space 5 more times to start more time sources
- Observe that time increases exponentially
Repro: 100%

**Comment by toby-yoyo** [comment]
- Optimised the matching of time source IDs to their objects
- Optimised memory usage of time sources.
- Optimised iteration in time source functions.
- Optimised counting of time sources (for `debug_event("ResourceCounts")`)

**Comment by sihammill** [comment]
Fix verified IDE v2023.1100.0.418  Runtime v2023.1100.0.438
