### ISSUE TITLE
Startup: Splash screen looks 'framed' in 2023.800 Betas

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1493]
GM-8185

When launching GM on recent betas the loading screen has a darker surrounding border that disappears once reaching the start page.

*Steps*

- Launch the Beta ( IDE v2023.800.0.400  Runtime v2023.800.0.419)
- Observe the issue as described above

Beta:
 !image-2023-08-15-15-16-09-132.png|width=850|height=600|thumbnail! 

Stable: 

 !image-2023-08-15-15-16-27-203.png|width=850|height=600|thumbnail! 

*Repro*: 100%

**Comment by scott-dunbar** [comment]
Verified fixed in IDE v2024.600.0.557  Runtime v2024.600.0.572
