### ISSUE TITLE
In-Game: Calling event_perform_object with "noone" as the object_index causes error in HTML5

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#150]
GM-3411

 Calling event_perform_object with "noone" as the object_index causes an error in HTML5.

"Error: undefined object id passed to event_perform_object: -4"

Steps:
 # Load attached project
 # Run in Windows
 # Notice how it runs properly
 # Run in HTML5
 # Open developer console
 # Notice the error message

Repro: 100%

**Comment by gnysek** [comment]
Related to https://github.com/YoYoGames/GameMaker-Bugs/issues/1703 ?
