### ISSUE TITLE
Start Page: Template title and default name are not capitalised

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1506]
GM-8155

On the start page, the title and default name of a selected official template are not capitalised

Steps
- Open the latest Beta
- Press "New" then "Game"
- Select an official template e.g. "Brick Breaker"
- Click this
- On the RHS the title will be "Brick Breaker" and the default file name will be the same, this should be capitalised

**Comment by YYDan** [comment]
From Alan S: "The project title comes from the data provided from server ( "info_title" field ) and should be changed there"

**Comment by YYDan** [comment]
Looks fixed to me already, despite the Jira still being open.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/7aec4b08-cba9-4ee7-893e-23efe98b3f83)

Closing.
