### ISSUE TITLE
In-Game: [HTML5] Various ..._exists() functions incorrectly return "true" for invalid references in 2023.8/800s

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1510]
When targeting HTML5 with a project using the _exists() functions on various different asset types, many incorrectly return true when passed invalid references, e.g. passing an object into sprite_exists(). Other than instance_exists(), these all return false as expected on VM target.

[Typed Handles HTML5.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12686851/Typed.Handles.HTML5.zip)

The following functions are affected:
* sprite_exists()
* instance_exists()
* object_exists()
* room_exists()
* script_exists()

*Expected*
It is expected that all of the above functions return false when passed invalid references.

*Steps*
- Open attached project
- Set target to HTML5
- Run game using debugger
- In Debug Output, observe that the above functions all return true
Repro: 100%

**Comment by jackerley** [comment]
References aren't fully supported in html5, so we have no way of distinguishing between assets whose indices overlap
