### ISSUE TITLE
Code Editor: [Feather] F3 brings up both Search and Replace and Goto next usage

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1518]
GM-8112

When in the code editor with feather enabled, if you use CTRL+F and then press F3, Goto next usage ALSO appears.

*Expected:* Find and Replace should take priority over Goto next usage.

*Steps:*
1. Open GM and create or import a script.
2. Go into the code editor and use CTRL+F to bring up Find and Replace.
3. Search any letter and then press F3.
4. Notice how the Goto next usage pops up.

**Comment by gnysek** [comment]
I just thought that with Feather, old `F3` functionality was removed... glad to see it as bug.

**Comment by SmithTom6304** [comment]
Has been fixed by shortcut refactor, so Find Replace window should now always take priority over Feather

**Comment by alicemoretti** [comment]
Verified fixed on  IDE v2023.1100.0.437  Runtime v2023.1100.0.450. Thank you
