### ISSUE TITLE
Debuger not show instance name like old versions

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#1533]
### Description
When you use a breakpoint on a instance and you check it "id" value you get only the ref value
in previus versions you get the id reference and the name (object_name) of the instance.

### Steps To Reproduce
Check the images provided.
but its basically 
1. use debuger
2. breakpoint where you can see a "id" ref value
3. see that there is not object_name like older versions

[1cf4f853-c318-46a2-b9d2-9de27cb90977](https://api.gamemaker.io/api/github/downloads/1cf4f853-c318-46a2-b9d2-9de27cb90977)

**Comment by gnysek** [comment]
My similar ticket: https://github.com/YoYoGames/GameMaker-Bugs/issues/1549

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.418  Runtime v2023.1100.0.438
