### ISSUE TITLE
Custom emitter presets aren't shown in the library

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-Bugs#1536]
### Description
Currently, you can't choose a custom preset in the IDE particle editor neither in Library nor in the Subparticles' On Death and On Update.

Presets are actually saved and can be located in `particlelib` subfolder and you can set them by directly changing the .yy file of the particle system they are just not shown in the library view, there are only built-in particle presets.

### Steps To Reproduce
1. Create a particle system
2. Save its emitter as a new preset
3. Create another particle system
4. Locating the preset saved in step 2 in the preset library is not possible, there are only built-in `GM_` presets

[2bc45a9d-bd9b-4f58-9c8a-22b9f6dfa419](https://api.gamemaker.io/api/github/downloads/2bc45a9d-bd9b-4f58-9c8a-22b9f6dfa419)

**Comment by pkraif** [comment]
Already fixed by @yyalansavage in 55e3e939b7fc907ebbf6abd8e953b6a396c5d66e, issue GM-8176.
