### ISSUE TITLE
circular static chain causes debugger to detach, and program to hang

### ISSUE THREAD

**Issue by AtlaStar** [YoYoGames/GameMaker-Bugs#1537]
### Description
If one were to accidentally create a circular static chain, attempting to print that static by using static get on any part of the chain will cause a hard crash. Not only this, but evaluating the struct in the debugger's variables window also causes the debugger to detach and an obvious hang of the program

### Steps To Reproduce
static_set struct A and struct B, then static_set struct B and struct A. Use static_get on either and set a breakpoint after assigning its result to a variable.

[85df1db4-1be6-40bc-a1c6-75a231ea3a52](https://api.gamemaker.io/api/github/downloads/85df1db4-1be6-40bc-a1c6-75a231ea3a52)

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
