### ISSUE TITLE
Invalid dbg ref silent crash

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#1540]
### Description
If you create a scalar variable such as "crash_variable = 777;" and you try to create a debug reference, your game will siliently crash with out an error, or feather warning

### Steps To Reproduce
crash_variable = 777;
rid = ref_create(crash_variable, "testing");

// nothing runs after this

[15906d05-459c-4d47-8ad4-86aabecdbb5f](https://api.gamemaker.io/api/github/downloads/15906d05-459c-4d47-8ad4-86aabecdbb5f)

**Comment by rwkay** [comment]
Fixed (see above)
