### ISSUE TITLE
In-Game: [GX.games] video_pause() results in different status than other platforms when a video is paused 

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#1544]
### Description

When using video_pause() to pause videos using the GX.games platform, it returns a different status of -1 rather than 0 on other platforms. 

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/a20d0778-24cc-42b0-aecb-7dd730450894)

https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FVideos%2Fvideo_draw.htm states that -1 is an error code so GX.games returning this doesn't seem to be correct.

https://drive.google.com/file/d/1-D1Khr6L6UQzbz71MBOYxx-Wx3bXs1Zd/view?usp=sharing

### Expected Change

video_pause() should return a status of 0 on GX.games similarly to other platforms

### Steps To Reproduce

1. Start GameMaker and import attached project.
2. Run game on GX.games platform.
3. Press spacebar and see that the status returns -1 error.
4. (Optional) Repeat on Windows and observe that pressing spacebar simply pauses video.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

GX.games

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.418  Runtime v2023.1100.0.438
