### ISSUE TITLE
Tile Set Inspector: 'Disable source Sprite Export' checkbox hides the text for Japanese

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#1546]
### Description

When the IDE is set to Japanese (only) the text for the option to 'Disable source Sprite Export' is not wrapped up correctly, hiding the option, unless the inspector window is stretched.
![8204](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/4f981b10-4937-4924-82b4-8f9383582f3f)

### Steps To Reproduce

1. Start GameMaker
2. Open any project that with Tile Sets
3. Select a Tile Set from the Asset Browser
4. From Preferences >General Settings - set the IDE to Japanese
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), 2022.0.1 (LTS), Beta (Beta IDE v2023.800.0.402 Beta Runtime v2023.800.0.423)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by yyalansavage** [comment]
already fixed and verified here - https://bugs.opera.com/browse/GM-8204

**Comment by mgeddesGM** [comment]
verified in Verified in IDE v2023.8.0.94 Runtime v2023.8.0.140
