### ISSUE TITLE
Tileset collisions are working only up to cell = 16, 16

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1548]
### Description
In my example projects, tileset collisions are reported only in a square equal to 16x16 tiles from top left corner.
Beyond that - they reutrn false.

I'm not sure if this is hardcoded to support only first 16 grid cells, or is connected with tile size (16px), but for sure there's some bug here.

### Steps To Reproduce
Run attache project. Move cursor to blue/yellow/green squares further than 16 cells from left and top.

[b24cc541-9acb-47b7-9c76-2b1315a9ef8f](https://api.gamemaker.io/api/github/downloads/b24cc541-9acb-47b7-9c76-2b1315a9ef8f)

**Comment by jackerley** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.427  Runtime v2023.1100.0.441
