### ISSUE TITLE
Debugger: when setting variable to sprite or "id" it's hard to tell what's there, getting random hex number

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1549]
### Description
Since "ref"erences/handles are introduced in 2023.8, debugger wasn't able to display any of those values. From what I see now it support `ds_xxx` things, and is able to show `self`, but when setting variable to `id` or sprite, it's hard to tell what sits under those values.

For `value = id` I would expect to get same result as for `value = self` and being able to see object/instance name, values like x, y, direction etc.
For `value = Sprite1` I would expect to see sprite name in debugger.

That's what was possible for long long time.

### Steps To Reproduce
Run attached project, put breakpoint on line 8 in Object1, check values in debugger.

[47e58473-4e01-4630-b5c6-9e854502ef47](https://api.gamemaker.io/api/github/downloads/47e58473-4e01-4630-b5c6-9e854502ef47)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.420  Runtime v2023.1100.0.438

**Comment by gnysek** [comment]
Confirmed that it works:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/1f98307e-4784-4823-96bb-82ef2f8ec4ff)
