### ISSUE TITLE
Using ++ or -- on an array element inside an array that was passed as an argument to a function crashes the game

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1556]
### Description
As the title says, if you use the ++ or -- operator on an array element inside an array that was passed as an argument to a function, the game will crash with a variable not set error, saying that the argument was not set, even if you already used that same argument earlier in the function without issue. This does not occur if you use += 1 or -= 1 instead, nor does it happen if you use them on the same array outside of a function.

### Steps To Reproduce
function array_test(arr) {
	show_debug_message(arr[0]); //this debug message will appear without issue.
	arr[0]++; //this line will crash the game, saying arr was not set before reading it.
}
Then in an object
array = [1];
array_test(array);

This will cause the game to crash. Included project has this example. The length of the array, index being accessed, or exact number inside does not appear to make a difference.

ERROR!!! :: ############################################################################################
ERROR in
action number 1
of Create Event
for object oArrayTest:

Variable oArrayTest.arr(100011, 0) not set before reading it.
 at gml_Script_array_test (line 3) - 	arr[0]++;
############################################################################################
gml_Script_array_test (line 3)
gml_Object_oArrayTest_Create_0 (line 2) - array_test(array);

[b5bbd274-912b-4772-88c1-a111575b005e](https://api.gamemaker.io/api/github/downloads/b5bbd274-912b-4772-88c1-a111575b005e)

**Comment by rwkay** [comment]
Fixed in 2023.11
