### ISSUE TITLE
Creating new project or opening very old one causes "Output" window to be nearly hidden

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1566]
### Description
When creating new project, or opening one older than 5-6 months in Beta IDE v2023.800.0.402 Beta Runtime v2023.800.0.423,
Output window is so small, that it's nearly not visible at all.

### Steps To Reproduce
Create new project in Beta IDE v2023.800.0.402 Beta Runtime v2023.800.0.423.

[d9131021-d94a-4b63-8d39-98067f3d8d1f](https://api.gamemaker.io/api/github/downloads/d9131021-d94a-4b63-8d39-98067f3d8d1f)

**Comment by gnysek** [comment]
![Zrzut ekranu 2023-08-22 000352](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/60e6b574-682b-48c4-95aa-505aad27f3fd)

**Comment by YYDan** [comment]
Has been reported internally and indeed fixed already, so that fix will be in this week's Beta.

Thanks!
