### ISSUE TITLE
GX.games is default target in new project desptie selecting different one in settings

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1567]
### Description
I've set "Windows" as default target in "General Settings > Default Target", however when creating new project, GX.games is selected as default one.

### Steps To Reproduce
1. Be logged in on subscription account
2. Set "Default Target" to other than GX.games
3. Create new project

( Beta IDE v2023.800.0.402 Beta Runtime v2023.800.0.423 )

[fedb23e5-d157-4e69-9457-ce67c7acbbd7](https://api.gamemaker.io/api/github/downloads/fedb23e5-d157-4e69-9457-ce67c7acbbd7)

**Comment by YYDan** [comment]
Yeah, we filed a related issue for this ourselves yesterday. Will close this Issue, as we already have a report in the internal DB, but this bug is tagged for Aug and so should be fixed soon. Thanks!
