### ISSUE TITLE
Startup: "mySQL Font" virus crash should now be turned into a proper error dialog so unnecessary bugs are not filed

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#1568]
### Description

For a long time, the Helpdesk have handled an issue where during startup GameMaker will fail to start if a user's PC is infected with a virus which creates a hidden, locked "mySQL" Font in their system folder. We would then send a macro informing the user about the virus and how to resolve the situation properly.

However, now that users can submit this to GitHub and bypass the Helpdesk, this crash should now be turned into a proper error dialog shown on startup which links to a support guide (and then we may wish to continue loading GM normally), so that unnecessary bugs are not filed.

### Expected Change

An error dialog is shown on startup, saying what the issue is and linking to a Helpdesk FAQ with more info.

### Steps To Reproduce

1. Start GameMaker on an infected/previously-infected machine
2. Observe GM crashes
3. Open the ui.log and find the error message says what the problem is
Repro: We have never reproduced internally, as you need an infected machine... 

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), 2022.0.1 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10, Windows 7/8

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
For anyone reading this issue and who might be affected, the ui.log always says:

> IDE Exception: System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\Fonts\Mysql' is denied.
> at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
> at System.IO.FileSystemEnumerableIterator`1.MoveNext()
> at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
> at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
> at YoYoStudio.Graphics.FontManager.ValidateFontFolder(String _folderpath)
> at YoYoStudio.IDE.Initialise(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
> at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)

So you can easily tell if that's your problem.

And the fix (as far as GameMaker is concerned!) is simply to find and delete that C:\WINDOWS\Fonts\Mysql' folder. You should of course run your antivirus client across your whole system in order to confirm you have no other issues.

**Comment by YYDan** [comment]
FAQ is now written and published: https://help.gamemaker.io/hc/en-us/articles/14837145219485

**Comment by CalumLaverock** [comment]
I've detected when the Mysql folder exists in the fonts directory and will show an error dialog upon the IDE finishing loading which will link to the above guide. This will also skip the loading of some system fonts as to not attempt to load the broken Mysql directory; normal GameMaker function should still be fine. The error dialog will show every time the IDE is started while the Mysql directory exists.

**Comment by stuckie** [comment]
Looks like this has reappeared: https://github.com/YoYoGames/GameMaker-Bugs/issues/4693
