### ISSUE TITLE
Building Projects: GameMaker won't update the SSH data and will use stale information if PPK file is deleted

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#1571]
### Description

When creating a key to use pubkey authentication over SSH to a Linux target, if the yoyo.ppk file is deleted, it will generate a new key file and send the public key over to the target's authorized_keys file, as expected. However, it does not update the "yoyo" file holding the private key. Gamemaker will continue to try to authenticate with the stale key, causing the authentication to fail. 
Note - In order to bypass this issue you will need to delete the file generated manually.

### Expected Change

The file holding the public key should be updated automatically

### Steps To Reproduce

1. Start GameMaker on Windows
2. Build any project targeting Ubuntu
3. Go to the directory where yoyo.ppk is stored on Windows (C:\Users\<username>\AppData\Roaming/GameMakerStudio2\<GMaccountuser>\yoyo.ppk by default)
4. Delete the file
5. Run the project again
6. From the same directory observe that file containing the key has not been updated and still contains the old key
![image_2023-08-23_110133685](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/f0ccc762-9b62-483b-9f79-1117e23a9958)
[211711.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12417931/211711.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), Beta ( IDE v2023.800.0.402  Runtime v2023.800.0.423)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed in 2024.08 branch.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.598  Runtime v2024.800.0.621
