### ISSUE TITLE
Tile collisions are 1px off for flipped/rotated pixels in 800.0.425

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1572]
### Description
When checking for tile collisions, if tile is flipped or rotated, collision is reported to happen on "edge" of precise collision tile, but only on part which is inside cell. Seems that pixels which are `+1` on `x` or `y` or both `x & y` from last sprite collision, are reporting collision.

Edit: also, it seems that first row and column of sprite returns NO collision  (check picture in comment - blue are pixels which returns no collision but they should, red are pixels which returns collision, but they should not).

If wrong pixel is outside of cell, then no collision is reported (properly) so it seems that first it's checked if current cell have any tile at all.

### Steps To Reproduce
1. Create tileset which have rectangular triangle as one of tiles (so half of cell is diagonally empty)
2. Use rotate/flip settings in room editor to place it
3. Run game and check - on pixels which are 1px off from edge of filled part of tile, collision will be reported for rotated tiles, but it works ok for non-rotated cell

(you can check that all using attached example)

[eddc3063-80a3-462a-82e2-03df41f57948](https://api.gamemaker.io/api/github/downloads/eddc3063-80a3-462a-82e2-03df41f57948)

**Comment by gnysek** [comment]
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/998d5612-12c0-4637-87c6-a4551b7f1585)

**Comment by jackerley** [comment]
Fixed 249d9ed514ce6978e64f5a918907ee1a92a1ed9f
