### ISSUE TITLE
In-Game: Memory leak when storing a built-in function in a variable and then calling that variable

### ISSUE THREAD

**Issue by KormexGameMaker** [YoYoGames/GameMaker-Bugs#1581]
### Description
This only happens with built in functions (not user defined ones), and only happens if the function is stored in a variable first, then called through that variable. It does not happen if the function is called directly instead of storing it in a variable first. It happens for all variable types I tried: local, instance, global, inside a struct, possibly more.

### Steps To Reproduce
if keyboard_check_pressed(vk_space) {
    //this function can be any built in function, not just lengthdir_x. I tried about a dozen, and it happened for all of them.
	var built_in_function = lengthdir_x;
	repeat(1000000) {
		built_in_function(0, 0);
	}
}
Watch memory usage in the task manager before and after pressing space. Memory usage will increase drastically. For me, it went from 20 mb to 460 mb. It also increases in the debugger, but only for a moment, before falling back to a smaller number (but one that's still higher than the memory before running the code)

[dbc79312-a9d0-4d9d-8e46-a48e3d30e923](https://api.gamemaker.io/api/github/downloads/dbc79312-a9d0-4d9d-8e46-a48e3d30e923)

**Comment by AtlaStar** [comment]
doing something like this
```GML
var built_in_function = method(self, lengthdir_x);
repeat(1000000) {
    built_in_function(0, 0);
}```
appears to prevent the memory bloat, suggesting that built-ins are having the behavior applied to them that is supposed to occur with script functions; they are getting bound as methods _per call_ if you do not wrap them in a method first. I do not suspect that this is something that should really be occurring with the built ins as afaik the dispatch mechanisms are different anyway and get called using the top-level object instance and are _never_ called within the context of a struct or something where method bindings matter.
