### ISSUE TITLE
Report a bug: placeholder text is displayed under filled data if there's scrollbar.

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1583]
### Description
In new bug reporting tool in IDE, if one gonna put enough description for a bug long enogh to fit in few lines (8+), so we'll see VERTICAL scrollbar, then navigating to another field than Descrption causes "Placeholder" text to display under it.
This happens only if "Description" is scrolled to bottom of it's content.

### Steps To Reproduce
Put a text which have at least 8 lines, and scroll to bottom of it (this is crucial). Then click into "Steps to reproduce" or "Title".

[190c84ab-92cb-4fd4-81c5-c54c70e54264](https://api.gamemaker.io/api/github/downloads/190c84ab-92cb-4fd4-81c5-c54c70e54264)

**Comment by gnysek** [comment]
![Zrzut ekranu 2023-08-25 003127](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/321b972c-40fe-4493-9a57-534a4c495ae5)

**Comment by YYDan** [comment]
Has now been fixed ahead of Aug23 Beta 8.
