### ISSUE TITLE
Building Projects: [GX.games YYC] Compiling will fail when used on a ARM64 mac with emsdk 3.1.9

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#1587]
### Description

Compiling GX.games YYC using mac ARM64 is currently failing when used along the SDKs suggested in the help guides. 

While this is not a bug related to GameMaker itself, but an emscripten known issue - https://github.com/emscripten-core/emscripten/issues/16826 will affect all the ARM64 Mac users trying to compile to the target. 

Note: At the moment testing using emsdk 3.1.10 on an M2 chip mac does not present this issue, for example.

### Expected Change

Update/add support to a newer version of emsdk that works for all platforms

### Steps To Reproduce

1. Start GameMaker on a M1/M2 mac
2. Open any project or create a new one
3. Edit the necessary game options for GX.games
4. Select GX.games YYC and Create Exe
5. Observe the upload will fail and the compilation error in the Output window

emsdk 3.1.9 [outputlogyyc.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/12438374/outputlogyyc.txt)

emsdk 3.1.10 [3110log.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/12438451/3110log.txt)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), Beta (Beta IDE v2023.800.0.404 Beta Runtime v2023.800.0.425)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Required SDKs FAQ now says:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/7221311f-4ca7-4a91-882e-58d149e1e758)

And the GX setup FAQ already (repeatedly) says to check that bit of text for the version number you need rather than using any of the example versions we show or the "latest" keyword, so no change required to that doc.

**Comment by Emc1923** [comment]
I'm setting this issue now as obsolete/Closed, the fix given for emsdk 3.1.18 was that if the SDK installation was affected to update and reinstall - doing this will currently fix emsdk 3.1.9 retroactively as well. For reference:  https://github.com/emscripten-core/emsdk/pull/1083 Thanks!
