### ISSUE TITLE
In-Game: When timeline_speed is set to zero, changing timeline_position produces unexpected results

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#1596]
### Description

Wanting to use timelines at zero speed and just increment through the moments at my own pace. Timelines are clean and easily readable so I thought it would be nice to use as a sort of dialog system. However, when trying to skip over moments using timeline_position, all moments that are skipped over end up getting run simultaneously. I've added some debug messages to show what I mean:

Timelines position is @ 1 //output at the start of each moment
Run Moment 1 Code
Timelines position is @ 2
Run Moment 2 Code // sets timeline_position to 4
Timelines position is @ 4
Run Moment 3 Code

Timelines position is @ 4
Run Moment 4 Code

As shown from the output above, even though timeline_position 3 was skipped, the code for that moment is still run. If speed is set to 1 instead, the code runs as intended, and the moment 3 code is properly skipped. It seems like a lot of the functionalities of timelines don't work as expected when running at 0 speed. Trying to change timeline_index creates unexpected results as well but I'd assume it's for the same reason why the timeline_position is acting up.

Contact us Package:
[Timeline Bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12477502/Timeline.Bug.zip)

### Steps To Reproduce

1. Start GameMaker and load attached project
2. Run project
3. Observe all Timeline moments have fired when timeline speed is set to zero

100% Repro

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
This is by design, otherwise you don't get moments happening if you are controlling the timeline position yourself. I think what you are after is a jump to timeline position function?
