### ISSUE TITLE
Collapsing dbg_view doesn't work

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#1597]
### Description
Latest version (IDE v2023.800.0.406 Beta Runtime v2023.800.0.429) happily fixes most of dbg_xxx regressions, but seems that there's still one - Views created using `dbg_view` aren't collapsing when pressing that little arrow in circle in top left of view' topbar.
From my tests it seems that it works for `dbg_section` as it should.

### Steps To Reproduce
1. Create debug view using `dbg_view`
2. Try pressing top-left arrow inside circle to minimize it.
3. It would collapse but then immediately expand on next frame.

[a261da41-2fa7-4186-a718-468aad1ef360](https://api.gamemaker.io/api/github/downloads/a261da41-2fa7-4186-a718-468aad1ef360)

**Comment by gnysek** [comment]
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/2445b252-74de-40aa-98d4-438de9aa2a4d)

**Comment by rwkay** [comment]
This is fixed (see above)
