### ISSUE TITLE
Install: [Mac IDE] Rosetta installation is still required when installing on M Series Macs

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#1599]
### Description

When installing GameMaker on an M2 Mac, the user will be prompted to install Rosetta before being able to install GameMaker.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/2e73585b-66f6-4987-82a0-98136d417bb7)

Tested using Beta IDE v2023.800.0.406 Beta Runtime v2023.800.0.429.

[Contact Us Package](https://drive.google.com/file/d/1p2wzh77hHToirugq8G6AuL-grB-8NyNW/view?usp=sharing)

### Expected Change

GameMaker should be able to be installed on M series devices without requiring Rosetta to be installed.

### Steps To Reproduce

Note: Requires a fresh-install of GameMaker on an M series Mac without Rosetta installed

1. Download the latest Beta version of GameMaker
2. Launch the installer 
3. Observe the Rosetta installation dialogue appears over the GameMaker installer

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by LukeBrownYoYoGames** [comment]
Possibly related to this: https://developer.apple.com/forums/thread/667672

**Comment by AToska21** [comment]
As said by @LukeBrownYoYoGames, changing hostArchitectures in the PKG file to `x86_64,arm64` would no longer prompt the user to install Rosetta. I'll try to do a little tweaking to the latest beta installer and see where that goes.

**Comment by LukeBrownYoYoGames** [comment]
This should be fixed in the next Beta. Changed the distribution profile to add arm64 as mentioned above

**Comment by stuckie** [comment]
Closing as the initial fix is working, just that #2592 needs fixed as well.
