### ISSUE TITLE
Alt+F4 won't end the game

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#1601]
### Description
Normally the alt+f4 key combination automatically closes the game, without the user having to code that behavior themselves; it no longer does this, and that should probably be fixed

### Steps To Reproduce
Run the game
Hit alt+f4
Nothing happens

[ddbaf93d-c1ef-48aa-8c8b-aa875141b48e](https://api.gamemaker.io/api/github/downloads/ddbaf93d-c1ef-48aa-8c8b-aa875141b48e)

**Comment by gnysek** [comment]
It's in wrong milestone. Should be https://github.com/YoYoGames/GameMaker-Bugs/milestone/6 rather than https://github.com/YoYoGames/GameMaker-Bugs/milestone/3 .
