### ISSUE TITLE
Debugger: Does not break on points placed inside instance creation code

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#1605]
### Description
if you try to do debug an instance creation code it will NOT show in the debugger. 
See the example attached.

### Steps To Reproduce
- Make a instance creation code in a instance of some room.
- Put a breakpoint in that instance.
- See how the debugger not show that code executing, but its executing in the game.

SAD

[9d6476fd-d825-4bc6-9e56-288bd631f5b7](https://api.gamemaker.io/api/github/downloads/9d6476fd-d825-4bc6-9e56-288bd631f5b7)

**Comment by yyalansavage** [comment]
Debugger appears to be breaking in instance creation code breakpoints without issue in general, so likely something specific to the code arrangement in this case; unfortunately I've not been able to get the provided project to execute the problem code without having a game save file. If you can provide a game save or some other means (eg small sample project which reproduces the issue) by which I can get the offending code to execute, I can investigate further.

**Comment by Totobal5** [comment]
Ok where i can upload my full game where this bug is show multiples times?

**Comment by gnysek** [comment]
@Totobal5 old good helpdesk probably

**Comment by YYDan** [comment]
Hehe, all the instructions are right here on the Readme for this repository - which we link directly to on the bug-reporter and asked you to review before posting any issues ;)    [](https://github.com/YoYoGames/GameMaker-Bugs) - See section 2b.

But actually Alan is just asking for a save file and/more detailed steps to recreate the issue straight away, rather than for you to send the full game project again (he has the original upload already). Please reply here with extra info on how to create the issue and if you're able to give us a save file to jump straight to a suitable point in the game, then you can attach files directly onto the text box when you reply. 

You might need to put the file in a .zip first, as only certain filetypes are allowed.

**Comment by Totobal5** [comment]
Okay, i can put instructions to make that proyect to send you to a test room where is very easy to test and see the problem (i just finish doing it)

1. on ___GameConfig script change the _BEFORE_START_MENU_ to _rWorldTest_
2. Select _uiTitleScreen_ and set _toCinematica_ to false and _ignoreTransition_ to true (Variables of the instance)
3. Put breakpoints on _oInteractive_ and _oChangeRoom_ that is in the room.

I am sure that i send the example proyect with that exact changes u.u
mp4 when enter the room

https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/8c5ca8fa-70e3-45e4-ab05-44ffe94ae0dc

(You will notice that the debugger stop correctly on oChangeRoom, but not execute oInteractive breakpoints)

mp4 when you interact with the objects (z or enter)

https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/a53c6df0-9e41-4651-8ce5-3d7e07c07f5c

(You can notice that the debugger stop on oChangeRoom again but start inspecting the wrong scripts and methods, it too crash on the execution on some script on oInteractive but again it only show oChangeRoom)

mp4 on more test in the same room

https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/35362430-547d-46fe-b5ed-7ac62fcabd08


mp4 where i delete oChangeRoom and add a new instance

https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/9a4a6d26-fd4f-45f8-8cfa-819f1ab84cc1


I hope that the videos help for my poor english u.u

**Comment by yyalansavage** [comment]
Fixed issue where instance object variables were interfering with script lookup/breakpoint setting; now hitting break points correctly in instance creation code in above rWorldTest example

**Comment by Emc1923** [comment]
Verified in Beta IDE v2023.1100.0.425 Beta Runtime v2023.1100.0.439
