### ISSUE TITLE
In-Game: [Windows] audio_get_recorder_info() silently crashes game when no input device connected

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#1608]
### Description

When there are no input devices enabled or connected in Windows, the audio_recorder_info() function causes a silent crash. In June release, this returns an error message instead.

The error from previous releases looks like this:
<img width="450" alt="Runner_V0qeByGdnB" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/128076091/34c2acdf-faff-400a-8916-5af15a350069">

This issue occurs in both Beta IDE v2023.800.0.406  Runtime v2023.800.0.429 and IDE v2023.8.0.97  Runtime v2023.8.0.143.

[audio_get_recorder_info.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12513450/audio_get_recorder_info.zip)

### Expected Change

It is expected that the audio_recorder_info() function should return an error when there are no input devices enabled or connected.

### Steps To Reproduce

1. Open attached project
2. Right-click Speakers in Windows toolbar
3. Select 'Sounds'
4. Select 'Recording' tab
5. Right-click any currently enabled input devices
6. Select Disabled for all currently enabled input devices
7. In GM, run game
8. Observe crash
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
- Fixed a crash in `audio_get_recorder_info` caused by no input devices being available.

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.418  Runtime v2023.1100.0.438
