### ISSUE TITLE
Passing mask_index as the argument to one of the sprite_get_... functions when the calling object has "same as sprite" mask mode crashes the game

### ISSUE THREAD

**Issue by KormexGameMaker** [YoYoGames/GameMaker-Bugs#1609]
### Description
With the ref changes, when an object is using "Same As Sprite" for it's collision mask, mask_index is "ref sprite -1". This apparently is not a valid argument for many of the various sprite_get_... functions, causing the game to crash. This causes problems when doing mask_index info checks for objects where some have a mask directly assigned and others are getting their mask from their sprite_index.
My ideal would be that doing something like sprite_get_xoffset(mask_index) when the object is using Same As Sprite mode would cause the function to check sprite_index, since that's what the mask effectively is anyways.

### Steps To Reproduce
- Create an object, 
- give it a sprite, and do not change mask_index. 
- Call sprite_get_xoffset(mask_index), or sprite_get_bbox_bottom(mask_index), sprite_get_number(mask_index), etc. and 
- the game will crash.

```
sprite_get_xoffset argument 1 invalid reference to (sprite)
 at gml_Object_Object1_Create_0 (line 1) - show_debug_message(sprite_get_xoffset(mask_index));
############################################################################################
gml_Object_Object1_Create_0 (line 1)
```

[a2072e7f-f13d-403f-9d36-d407b913efff](https://api.gamemaker.io/api/github/downloads/a2072e7f-f13d-403f-9d36-d407b913efff)

**Comment by jackerley** [comment]
This isn't a bug - this is the way that mask_index works in this situation, you would never have returned any sensible information by calling sprite_get_number(mask_index) if the collision was the same as sprite?

**Comment by ParodyKnaveBob** [comment]
How's it not a bug? Pass a sprite asset reference into the sprite function -- in this case, tell it to use the reference for the current sprite found in the default "same as" captured mask aka the current sprite_index -- and return sensible information on that sprite.

**If** KormexGit did this in the past, pretty semantically all said and done, then one would always (not never) have returned such info -- until the recent type/ref improvements.
