### ISSUE TITLE
In-Game: Async sprites are not being drawn at the correct size

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#1610]
### Description

Issue:
 When drawing a sprite loaded through sprite_add_ext, it is being drawn at the incorrect size, causing a 1 pixel gap around the right and bottom edges
 
 Issue present in 2023.6 and 2023.8
 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/96c5af5a-f08e-4329-999e-5b9f3ed5c6cc)
[AsyncSprite.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12520947/AsyncSprite.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import attached project
3. Run project
4. Observe Lime Green borders
5. Press space to toggle drawing the sprite not loaded asynchronously

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yymrennie** [comment]
This was an issue on all sprites loaded using sprite_add_ext() (not just when loading from a URL) and has been fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
