### ISSUE TITLE
In-Game: "room = [new room]" attempting to change room does nothing in 2023.8

### ISSUE THREAD

**Issue by KormexGameMaker** [YoYoGames/GameMaker-Bugs#1639]
### Description
In previous versions, you could set the room variable directly to the room you want to change to, and it worked. As of 2023.8, it no longer works, and running the code appears to do nothing at all. If this breaking is intended, then the documentation should be updated, as the page on rooms still says this should work.

### Steps To Reproduce
room = //any room asset here

Nothing will happen when running this code

[60ef1ced-b129-4ea3-ace9-8a85e711fc97](https://api.gamemaker.io/api/github/downloads/60ef1ced-b129-4ea3-ace9-8a85e711fc97)

**Comment by jackerley** [comment]
Fixed

**Comment by YYDan** [comment]
Works correctly now in IDE v2023.8.1.102 Runtime v2023.8.1.148

Edited the sample:
[ChangingRooms.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12609727/ChangingRooms.zip)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/21925d42-8d9d-4126-a9e9-33097094674a)

No manual change required, so Verifying.

**Comment by YYDan** [comment]
Just realised I made a typo in my space event and so it always changes to Room2, so the results above ARE correct and the sample is very easily fixed ;)
