### ISSUE TITLE
array_unique is weirdly slow

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#1640]
### Description
Calling array_unique on an array of structs is significantly slower than on an array of numbers, and it's not clear why (one would imagine that identifying unique struct pointers would be pretty much the same as any other number).

This only seems to be a problem on desktop; HTML5 uses the JS Set module for this and is fine.

It's also not a problem on New Runtime, only the current runtime.

### Steps To Reproduce
Run the example project, look at the timings in the console

[01e4b09e-fd70-43c4-b20f-d7259d9c793c](https://api.gamemaker.io/api/github/downloads/01e4b09e-fd70-43c4-b20f-d7259d9c793c)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.432  Runtime v2023.1100.0.446
