### ISSUE TITLE
Enable copy on write for array not working on VM

### ISSUE THREAD

**Issue by Ttanasart-pt** [YoYoGames/GameMaker-Bugs#1642]
### Description

Runtime 2023.8.0.145

Enable "Copy On Write Behaviour for Arrays" not create new array in VM target.

Example code:
```
arr1 = [ 0, 1 ];
arr2 = arr1;

arr2[0] = 10;

show_debug_message(arr1);
show_debug_message(arr2); 
```

VM result: 
```
[ 10,1 ]
[ 10,1 ]
```

YYC/expected result: 
```
[ 0,1 ]
[ 10,1 ]
``` 
[Array copy bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12565556/Array.copy.bug.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create an array `a`
3. Create another variable `b` equal to `a`
4. Modify `b`
5. The issue above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
We are deprecating the Copy On Write behaviour and have no plans to fix ongoing problems with the feature
