### ISSUE TITLE
60FPS game runs at 90Hz (50ish FPS) instead of 60Hz (60FPS) on an Android device that supports 60Hz/90Hz

### ISSUE THREAD

**Issue by Olfdev** [YoYoGames/GameMaker-Bugs#1644]
### Description

60FPS game runs at 90Hz (50ish FPS) instead of 60Hz (60FPS) on an Android device that supports 60Hz/90Hz.

With Gamemaker **2023.4.0.113**, the game is switching the device refresh rate to 60Hz and plays at 60FPS.
With Gamemaker **2023.8.0.98** , the game does not switch the device refresh rate to 60Hz, it stays at 90Hz and plays at 50ish FPS.

Tested on a Pixel 6 phone with Android 13 build TQ3A.230805.001

### Expected Change

The 60FPS game should change the device refresh rate to 60Hz.

### Steps To Reproduce

1. Start GameMaker 2023.8.0.98
2. Set your Android Settings FPS to 60.
3. Build your APK.
4. Start your APK on a 60Hz/90Hz device (ie: Pixel 6). You can display the phone's refresh rate in the phone's Developers Settings.
5. See the issue where the refresh rate stays at 90Hz instead of switching to 60Hz and the game stuttering because it runs at 50ish FPS instead of 60FPS.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Olfdev** [comment]
Hello again,

I did some digging for you by rolling back runtimes. The latest working runtime that properly switches the display refresh rate to 60Hz is **v2023.4.0.113** from the 2nd of May 2023.

After this one, the refresh rate doesn't switch to 60Hz anymore and stays on the max available (90Hz in my Pixel 6 case).

Thanks!

**Comment by jackerley** [comment]
Hi @Olfdev , could you try in the latest November beta?

**Comment by Bulletech** [comment]
Hi @jackerley I have just now downloaded the November Beta and tested on a Pixel 7 running at 90Hz and unfortunately still experiencing the same issue of 50 fps avg (/ GameMaker doesn't set the device refresh rate to 60Hz anymore).

**Comment by jackerley** [comment]
@Bulletech thanks for the feedback, I think I see what the issue is, can you recheck in the next beta as I've put a fix in?

**Comment by Bulletech** [comment]
thank you, can do
