### ISSUE TITLE
DELETE word doesn't works

### ISSUE THREAD

**Issue by JosensGames** [YoYoGames/GameMaker-Bugs#1657]
### Description
When I use the delete word for destroy a struct, memory instead clean up, it accumulates more and more garbage.

### Steps To Reproduce
First you need to create a constructor

function foo() constructor {
    self.myvar = []
}

Now, we made a array containing all the constructors
FooList = []

So, we do it...
repeat(1000) {
    var obj = new foo()
    array_insert(FooList, 0, obj)
}

Now the part that doesn't works
for(var index=0; i<array_length(FooList); i++) {
    var obj = FooList[i]
    delete obj
}

To see the bug, you need to run the game in debug mode and check the memory using.
So, when the program tries to delete an object using delete obj, the memory begins to collect garbage, it doesn't destroy it.

[c6905f46-db95-4849-915d-f260f6c80d21](https://api.gamemaker.io/api/github/downloads/c6905f46-db95-4849-915d-f260f6c80d21)

**Comment by jackerley** [comment]
The memory is marked for garbage collection so won't show as being freed immediately

**Comment by JosensGames** [comment]
Thanks a lot, so, how the program works? I mean, when GameMaker do a clean up? Can we check for this event? or its in second plane/backround process?

**Comment by YYDan** [comment]
That's already covered in the manual [https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2Fdelete.htm&rhsearch=delete&rhhlterm=delete](https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2Fdelete.htm&rhsearch=delete&rhhlterm=delete)

**Comment by YYDan** [comment]
I note that your original report kind of disagrees with what the manual says, so if you have an actual small sample project which shows this, then please upload the project and we can reopen the issue.

Please note that the memory graph in the debugger would show the memory still in the pool and ready for re-use the application, so you might want to confirm Task Manager/your OSes equivalent and see if that shows the same rise in memory before worrying about this.
