### ISSUE TITLE
Object Editor: "Edit Image" button does not respect any external editor Preference which has been set

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#1664]
### Description
Object inspector's edit image and sprite inspector edit image are showing different results, object editor opens built-in image editor but sprite's opens an external editor like it should, so I am pretty sure that one was missed the eye.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/74ee670f-929c-4d2c-a467-97c39bf5c451)

### Steps To Reproduce
1. Start GameMaker and open Preferences > General > Paths
2. Set your Bitmap editor path to an external application (e.g. C:\Windows\System32\mspaint.exe )
3. Create a new blank sprite
4. In the Sprite Editor, click its Edit Image button and observe this open the external editor.
5. Now open/create an Object and drag the sprite onto it to set it as used
6. Click the pen icon to edit the image
7. Observe GameMaker's own image editor opens

[c44c3dfc-7f40-4bc7-a1dc-70d0e8be4173](https://api.gamemaker.io/api/github/downloads/c44c3dfc-7f40-4bc7-a1dc-70d0e8be4173)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.426  Runtime v2023.1100.0.440
