### ISSUE TITLE
effect_create_above does not create an effect first time it's called

### ISSUE THREAD

**Issue by UltraMKF12** [YoYoGames/GameMaker-Bugs#1688]
### Description
Windows -> GMS2 VM
OS: Windows 10

I was following the official game maker Space Rocks tutorial, the code is the same as there.
When creating an effect with effect_create_above, the effect does not appear the first time the function is called after running a game.
After the first call, everything works as normal (When the game is restarted from obj_game everything works as normal also).
Cleaning cache did not solve the problem.

### Steps To Reproduce
With the arrow keys run into an asteroid, or shoot towards an asteroid with the left mouse button.

[7e2508bc-562c-4422-9698-70dcd853582b](https://api.gamemaker.io/api/github/downloads/7e2508bc-562c-4422-9698-70dcd853582b)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.414  Runtime v2023.1100.0.435. 

Thank you.
