### ISSUE TITLE
Feather: Newly-created projects in 2023.8.0 will display an empty redundant Syntax Error tab alongside Feather Messages

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#1693]
### Description

When creating a new project in IDE v2023.8.0.98 Runtime v2023.8.0.145 with feather enabled, an empty syntax error tab will appear along feather. Disabling feather in the same project will display two syntax error tabs.

Creating a new project with feather disabled will work as expected - also changing to feather will exchange tabs as intended.

Feather enabled (new project):
![image](https://github.com/YoYoGames/Incoming-Bugs/assets/105791928/6890d59e-2a8b-410e-b64e-d3409da45101)
Feather disabled (previous project):
![image](https://github.com/YoYoGames/Incoming-Bugs/assets/105791928/f2543544-6667-4a99-862d-72f61ba81af3)

Note: Resetting layout does not fix the issue once a project is affected.
[feathersyntaxtab.zip](https://github.com/YoYoGames/Incoming-Bugs/files/12595679/feathersyntaxtab.zip)

### Steps To Reproduce

1. Start GameMaker
2. Make sure feather is enabled in preferences
3. Observe the empty syntax error tab new to the the feather tab at the bottom of the IDE
4. Disable feather
5. Observe the two syntax error tabs

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly (2023.08), Other

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by YYDan** [comment]
Works correctly now in IDE v2023.8.1.102 Runtime v2023.8.1.148

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/fdb7739f-3044-4c0e-87fc-ba895f57ccf9)

No manual change required, so Verifying.
