### ISSUE TITLE
Debugger: Instance refs in the variable inspectors can't be expanded in 2023.8.0

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#1698]
### Description
When running the game in the debugger, you can't expand a value containing an instance reference the way you can with arrays or structs

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/3441ba91-c871-41a5-9cc2-c3f6c0098652)

### Steps To Reproduce
Run the game in the debugger
Pause the game
Look at the instance of obj_urgh in the All Instances list
the variable containing a reference to the other object just says "### ref," without the ability to expand it to see its contents

[412de680-460f-4c55-975a-ffaf02e28a40](https://api.gamemaker.io/api/github/downloads/412de680-460f-4c55-975a-ffaf02e28a40)

**Comment by YYDan** [comment]
Works correctly now in  IDE v2023.8.1.102  Runtime v2023.8.1.148

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/dcd0f734-b601-4cbd-8648-c55073748dcc)

Verifying.
