### ISSUE TITLE
UI scale is set to really small on first start

### ISSUE THREAD

**Issue by vvvvvvitor** [YoYoGames/GameMaker-Bugs#1712]
### Description

The window's UI scale will be set to a really small value when booting.

![Captura de tela de 2023-09-14 21-04-55](https://github.com/YoYoGames/GameMaker-Bugs/assets/119557151/df00e3c4-fbdb-4160-ad0c-96b9048deda1)
to really small

[contact.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12614428/contact.zip)

v2023.800.0.406

### Steps To Reproduce

1. Start GameMaker
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Issue was resolved when they created a dpi_override.json file.
The ui.log indicated that the IDE saw a very large resolution of 19,156px wide...
They indicated that they had a dual monitor setup with display 2 mirroring 1. I suspect that resolution query was thrown off by this for some reason.
