### ISSUE TITLE
Disable Source Sprite Export messes up Particle Graphics on HTML5

### ISSUE THREAD

**Issue by ShivaSouza** [YoYoGames/GameMaker-Bugs#1718]
### Description

This is a old bug, first reported here: [Game Maker Forums](https://forum.gamemaker.io/index.php?threads/particle-editor-wont-display-correct-sprites-in-game.102868/post-625993)

I **think** it was fixed somewhere this year, but the issue returns in 8.1 and 8.0.

The issue is simple:
If any of your Tilesets has "Disable Source Sprite Export" enabled, there is a chance your particles created in the IDE will display the wrong sprite in-game.

### Steps To Reproduce

1. Start GameMaker
2. Add a Tileset
3. Add a custom Particle Sprite
4. Play your particle in-game using code (not the drag and drop on the room editor)
5. There is a chance you'll get the wrong particle graphics.

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.426  Runtime v2023.1100.0.440
