### ISSUE TITLE
In-Game: [Windows] Click/Tap input on touchscreen devices requires two taps to register a single click

### ISSUE THREAD

**Issue by MilkTeaCat52** [YoYoGames/GameMaker-Bugs#1720]
### Description

When testing on Windows, games don't register input via the touchscreen correctly. Single-taps don't register at all, double-taps are registered single-taps. Dragging and flicking are registered correctly.

### Expected Change

Have single taps on windows register as single taps/clicks and double taps as double taps/clicks

### Steps To Reproduce

1. Start GameMaker
2. Add Click/Tap event or use the functions
3. Run game and try to use touchscreen for input
4. See the issue

[TOUCHSCREENBUG.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12620844/TOUCHSCREENBUG.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), 2022.0.1 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.418  Runtime v2023.1100.0.438, thanks.
