### ISSUE TITLE
In-Game: path_start() and path() cause a silent crash if called outside the scope of an instance, should show an error instead

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#1722]
### Description

When trying to call a method within a script that contains the mp_grid_path() function, the game will silently crash. When this method is placed inside of the object's Step event, the game will no longer crash.
[silentcrash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12621232/silentcrash.zip)

### Expected Change

It is expected that no silent crashes will occur when mp_grid_path() is called from a method within a script

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Run game
4. Drag cursor over a unit to select it
5. Left click somewhere else on the map
6. Observe silent crash
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
This is not a problem with the `mp_grid_path` function call. The problem is that the function path_start is being called from outside the scope of an instance (it's being called from a struct). This is still an issue and the solution is to provide propert error explaining that path_start as well as path_end should not be called from outside the scope of an instance.

**Comment by YYBartT** [comment]
Warning notes added to the manual pages of `path_start` and `path_end`.

**Comment by YYBartT** [comment]
Manual commit: YoYoGames/GameMaker-Manual@65b996d

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.436  Runtime v2023.1100.0.449

**Comment by cameron-home** [comment]
Appropriate error verified in IDE v2023.1100.0.436  Runtime v2023.1100.0.449, as well as warning notes now verified in the manual.
