### ISSUE TITLE
Sequence Editor: GM crashes when zooming all the way out via the zoom bar

### ISSUE THREAD

**Issue by EL0FBRsENO** [YoYoGames/GameMaker-Bugs#1735]
### Description
When trying to edit a Sequence, if I zoom so much, my GameMaker just crashes (but the project saves). And that's annoying, I basically can't edit my sequences correctly 😞

### Steps To Reproduce
1. Create a Sequence
2. Problably put some things inside it (like sprites, sounds, etc)
3. Zoom as much as you can in the bottom bar (the sequence editor)
4. It crashes

[c03e4d21-75c5-4658-8c85-fcd5abbc2a3d](https://api.gamemaker.io/api/github/downloads/c03e4d21-75c5-4658-8c85-fcd5abbc2a3d)

**Comment by mgeddesGM** [comment]
@EL0FBRsENO i have not been able to replicate this issue. I have used different populated sequences.

Would you be able to upload a project with a sequence that is giving you this issue? And possibly the level of zoom just before GM crashes?

**Comment by yyalansavage** [comment]
Also not able to reproduce, it looks like a very old gfx card so that is likely a factor. I think this commit may address the problem however-
https://github.com/YoYoGames/YoYoStudio/commit/c748a4ffef4084098bdb4791b3aac59dc416ebb2

**Comment by Emc1923** [comment]
Verified as per the above comment.
