### ISSUE TITLE
In-Game: Automatic string-to-real conversion causes memory leak

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#1742]
### Description
It has been found that automatic string to real conversion causes memory leak

### Steps To Reproduce
1. import the attached project
2. run using the debugger
3. notice the memeory leak
4. rerun the project but with only one line within the for statement uncommented
5. notice each line causes a memory leak

[46aa6f56-905d-49c4-9cd1-3f85944545d7](https://api.gamemaker.io/api/github/downloads/46aa6f56-905d-49c4-9cd1-3f85944545d7)

**Comment by rwkay** [comment]
Fix merged into 2023.11

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.417  Runtime v2023.1100.0.437
