### ISSUE TITLE
In-Game: Inconsistency when performing maths between strings and reals

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#1744]
### Description
It has been found that a subtraction or division can be applied to a number as a string but not an addition or a multiplcation.

### Steps To Reproduce
1. import the attched project
2. Notice the first two operations, lines 18 and 20  are sucessful
3. Notice the error for line 23, comment this out and rerun
4. notice the error for line 26

[a5bf0351-0241-4570-8ba5-4c70589394d9](https://api.gamemaker.io/api/github/downloads/a5bf0351-0241-4570-8ba5-4c70589394d9)

**Comment by rwkay** [comment]
This is because addition and multiplication are already defined for strings (addition will concatenate strings together and multiplication will perform multiple concatenations of the same string). This is not a bug
