### ISSUE TITLE
In-Game: Network packets being sent/received in 2023.8 games causes multiple silent crashes

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1754]
### Description

There appear to be 3 (possibly more) distinct silent crashes which log no issues. None of these crashes happened in previous versions of gamemaker and no changes were made to the extensions leading me to believe it was some internal changes to the runner which causes these issues.
 - At game init, you will see a black window appear as the library is initialized, then a second window will pop up. When this happens the main window should appear in the foreground once more, but the application crashes at this moment leading to only the control panel window being left. No error messages are listed, and this also does not happen every time it appears to be random.
  - If the main window correctly initialized and is set to the foreground as expected, The control Panel window will rarely instantly crash silently. This particular crash only appears to happen 1/200 times, I am not actually sure what causes this one to crash, though the only thing that would be happening is that the main process has connected with the Control Panel process, and a single packet is sent over for connection validation. This could be related to the following crash event
   - When a packet is sent or received there is a high chance of a silent crash. You can replicate this consistently by setting the Main Process to have focus and pressing spacebar, this will build a package and send it out to the child process.

Please note this started occurring with `IDE v2023.6.0.92  Runtime v2023.6.0.139` and new versions of Monthly builds have their own issues from the runner changes preventing from testing on more up to date version.

Included Project:
[bug report project.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12676419/bug.report.project.zip)

### Expected Change

The main process launches, then inits the control panel process, main process grabs focus once more, then when you press space it shoudl send out a packet to the control panel process to expand it's control panel to include a new folder.

### Steps To Reproduce

1. Start GameMaker
2. Compile supplied project
3. This is where the first two silent crashes will occur
4. If both windows randomly initialize, press space to send a packet from the main process crashing it
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Hello,

I've tried your project under a few of the past releases of GM and I'm not able to reproduce the crashes you describe. On versions prior to 2023.8, the application starts, both windows appear and pressing space on the main window does not cause a crash. As of 2023.8, the first window appears, then disappears when the main window is set up. Pressing spacebar still does not cause a crash.

I did notice a couple of points while trying to debug the project:

- When attaching to the running game with the Visual Studio debugger, one of the `libxprocess.dll` threads constantly raised array access out of bounds checks - I had to disable debugging on that thread to actually get it running.

- It appears your GML code is establishing a connection and then attempting to connect the socket a second time, which is failing with error 10056 ("A connect request was made on an already connected socket.").

To the best of my knowledge there is no way to create a second window through GameMaker APIs, so I can only assume that is all handled by your extension DLL. We did some refactoring of how we process window messages in 2023.8 but without knowing how your extension functions I can't guess why that would have any impact.

Could you provide more details, and ideally some minimal projects which reproduce *specific* crashes under the current version of GameMaker?

Best regards
Daniel

**Comment by time-killer-games** [comment]
I did want to mention the DLL has source code which included with the project itself, it should be in a zip folder named "libxprocess.zip" under the extensions subfolder of the project. That may shed some further light on the matter. Though it is not my job to debug GM as I dobt have access to the source and I do not work for YYG, and in a similar way, it is not YYG's job to debug my extension as they are not the creators of it, thus there remains a level of disconnect neither me or YYG can really do anything about. YYG arent paid to provide support for third party extensions.

**Comment by tinkerer-red** [comment]
Once the new monthly comes out which handles the issue #1673 I would be happy to refine the project down to a simpler example project, which can better log exactly which steps are occurring and might help dictate where exactly the crashes are happening. Will return to this again soon.

**Comment by tinkerer-red** [comment]
Closing this request as the multiple issues here are represented by #1790 and #2253
If the two bugs above don't fix the silent crash I will reopen and edit.
