### ISSUE TITLE
In-Game: Spine sprites used as particles animate too quickly because the frame is advanced by integer amounts

### ISSUE THREAD

**Issue by CameronAyling** [YoYoGames/GameMaker-Bugs#1760]
### Description

Spine uses seconds to advance animation but particle systems use integer frames so when it updates, instead of advancing by the time between frames, it advances by a whole second which is far too fast.

[Spine Particles.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12684042/Spine.Particles.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Create a Particle System
4. Import a Spine sprite
5. Assign the sprite to the Particle System
6. Set the sprite to animate and not stretch
8. Create the particle system in the middle of the default room
9. Run the game
10. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.415  Runtime v2023.1100.0.436.

Thank you
