### ISSUE TITLE
Particle Editor: Systems using Spine sprites as particles are not animating in the preview window

### ISSUE THREAD

**Issue by CameronAyling** [YoYoGames/GameMaker-Bugs#1761]
### Description

Spine animated particles do not animate when previewing them in the particle system editing window. They just appear as static images.

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Import a sprite animated in Spine
4. Create a new particle system
5. Assign the spine sprite to the particle system as the sprite
6. Set the flag to animate
7. Look at the preview window
8. See the issue
[Spine Particles.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12684079/Spine.Particles.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
We don't currently preview Spine sprites in the IDE so this won't work, you will only see the single frame
