### ISSUE TITLE
Building Projects: [iOS] Xcode 15 causes fails if trying to build projects containing cocoapods due to "DT_TOOLCHAIN_DIR cannot be used ..."

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#1771]
### Description

Attempting to build a project that uses podfiles on iOS using Xcode 15 will throw an error 

" DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead"

### Steps To Reproduce

1. Start GameMaker
2. Use a project that has Cocoapods in it, eg Firebase extension demo project
3. Attempt to build for iOS in Xcode
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
In workaround this problem in your podfile in the section
post_install do |installer|

you can add the following:

 installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end

**Comment by YYDan** [comment]
Closing per that fix above having gone in.

**Comment by YYDan** [comment]
Actually, this is not in the Aug branch yet, so reopening for now.

**Comment by DiasFranciscoA** [comment]
Ported back to Aug23 with commit:
* https://github.com/YoYoGames/GameMaker/pull/2915

**Comment by YYDan** [comment]
All fine on 2 Macs in Xcode 14 and 15 and when using 2023.8.2. Closing.
