### ISSUE TITLE
In-Game: Submitting a vertex buffer when the game window is minimized silently crashes the runner

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#1774]
### Description
Minimizing the game and bringing it back silently crashes the game.
The issue seems to be with a frozen vertex buffer being submitted. 
There is no change in logic with the surrounding code when the game is minimized or out of focus.

### Steps To Reproduce
- Download the project from https://drive.google.com/file/d/1AHlJMYwKna9zJa1JAYueffyVhjfps-vE/view?usp=sharing (1.6GB)
- Place the attached files in AppData/Local/Chronique_des_Silencieux
- Launch the game
- Click inside the game window to be sure it has focus
- Minimize the window by clicking the icon in the taskbar
- Click again on the icon and it should silently crash.

Additionnal behaviour notes :

- It can crash when minimizing if line 3 of the Draw event for "obj_isoWriting" is commented out
- The vertex buffer being submitted when crashing is built and frozen on line 12 of the Draw event for "obj_isoWriting"
- Comment out the vertex submitting on line 601 of the "Graphics" script and it should no longer crash.
- Alternatively putting a break point on that line and doing F5 to run the game frame by frame doesn't seem to trigger the silent crash. 
- But removing the breakpoint a few frames after the game is brought back up still triggers the crash

[bf6d8ba3-2c2c-4c26-ac6b-410be54222d3](https://api.gamemaker.io/api/github/downloads/bf6d8ba3-2c2c-4c26-ac6b-410be54222d3)

**Comment by patchuby** [comment]
Bug report files failed to upload, I will submit another private ticket referencing this issue with an cloud link to download the files.

Also this issue has been confirmed on another system.

**Comment by YYDan** [comment]
Have uploaded that full-game project to our Samples drive now and put the link in the steps. (That link will only work for us internally.)

**Comment by pkraif** [comment]
The problem with the following code from `obj_isoWriting`'s Draw event is:

* first you create a surface inside of the `if` statement with `canvas.GetSurfaceID()`,
* then you use `surface_get_texture` inside of `build_surface_pos` and store it into a struct that the function returns
* and function `draw_surface_pos_ext` is called without checking if the surface exists,
* but when minimizing the window, the surface is freed and the stored texture becomes invalid, which causes the crash in `vertex_submit`.

We can do a slight change in the runner to avoid the crash and use a `NULL` texture instead, but you will still need to fix your code - use `surface_exists` first and then `surface_get_texture`, if it returns `true`.

**Comment by cameron-home** [comment]
Testing blocked by https://github.com/YoYoGames/GameMaker/issues/3261

**Comment by patchuby** [comment]
@cameron-home @pkraif I'm still on 2023.8 but the issue was correctly identified by @pkraif , there was a problem with my code, everything is fine on my end. The only remaining issue was for GM to display an error when using a vertex_submit with a non-existent texture, but it seems that has been added as well so as far as I'm concerned, this can be closed 👍

**Comment by cameron-home** [comment]
@patchuby Wonderful, thank you!
