### ISSUE TITLE
Manual Content: display_get_gui_height() page needs to clarify this can return incorrect values if used prior to the room starting

### ISSUE THREAD

**Issue by AtlaStar** [YoYoGames/GameMaker-Bugs#1777]
### Description

If you have multiple views enabled (issue also likely to exist for single views that are exceptionally large as well), and the positioning and size of the views exceeds the size of your display height, the `display_get_gui_height` function will return the same result as a call to `window_get_x` prior to the first frame. Afterwards it will properly return the calculated bounding rect for all of the drawn views.

This leads to more subtle bugs that pop up if you attempt to cache the results that you may use to do something like create a surface that should draw during a GUI event. That issue is due to the view matrix automatically scaling the surface verts so that it renders in the display, but since the surface was created using incorrect values such a surface will render incorrectly.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/3477783/49581d0f-afec-40ff-b356-8d6a47ebd1c3)

This is what it should look like
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/3477783/50da2e22-3ad4-46bd-a395-a2a0aa1226f2)

My best guess for this behavior is that the function itself uses a cached value that is updated when views get enabled and a recalc of the gui area occurs (which otherwise uses the app surface size as a default), which isn't occurring until sometime after rooms create their objects, run their creation code, and are fully finished.

[contact_package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12707520/contact_package.zip)
included project is sidestepping the issue by resizing the surface on draw begin since it also clears the surface, and it itself may not show issues even with the problem introduced since it is dependent on the users system settings.

### Expected Change

`display_get_gui_height` should return the calculated view area for all views that are enabled in the IDE prior to the game starting.

### Steps To Reproduce

1. Find your system display resolutions y value
2. Start GameMaker
3. Enable views
4. Turn on view 0 and view 1
5. Change the y position for _one_ of the viewports so that its position plus it's height is _greater_ than your system resolutions y value
6. Set a global to the result of `display_get_gui_height()` in some room creation code
7. Compare the previously set global to `display_get_gui_height()` in some objects step event
8. Note that the values differ

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Each room can have a different view setup, so it is not guaranteed that cached view data is going to be valid; especially as it can be set in the first creation of a room.

**Comment by alicemoretti** [comment]
A clarification has been added to the Beta Manual. Thank you.
