### ISSUE TITLE
Feather reports error on audio_free_buffer_sound() taking the correct variable type instead of 'Real'

### ISSUE THREAD

**Issue by BPzeBanshee** [YoYoGames/GameMaker-Bugs#1778]
### Description
Feather gives a GM1041 'error' indicating improper variable type being used in the function `audio_free_buffer_sound`, despite being correctly used, and using the code given in the manual's example.

### Steps To Reproduce
Simply look at the Clean Up event in object1.

[21af76da-c02c-4d36-8017-1d39075477eb](https://api.gamemaker.io/api/github/downloads/21af76da-c02c-4d36-8017-1d39075477eb)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.420  Runtime v2023.1100.0.438
