### ISSUE TITLE
Building Projects: "global" struct is missing its correct kind value and so causes build errors if used with the struct accessor

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1779]
### Description

```
var _is_struct = is_struct(global);
//returns false
var _str = string(global);
//returns -5
var _type = typeof(global);
//returns number
```

struct_get_names still works. but it seems to have unexpected behavior from the above.
Also `global[$ _key]` will prevent the IDE from building
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/a1598ee5-aff9-4273-aa11-007ec952c727)

"file a bug on that one - it just means the kind is not set on global - it is a struct" -Russel

### Expected Change

global should be universally referenced as a struct and not a number

### Steps To Reproduce

see desc.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by cameron-home** [comment]
Global being referenced as a number has been verified fixed in IDE v2023.1100.0.443  Runtime v2023.1100.0.454.

The `global[$ _key]` issue can be found here: https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/400, to be verified later in 2024.2.
