### ISSUE TITLE
Sequence scale option is moving so slow

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#1796]
### Description
Sequences scale option on top right when selected it allows to change the scale, but other options were fast and responsive but that option in particular is slow and my mouse actually touches my screens edges and still its only 1-2 value different then its original scale. My screen is not big enough to change a scale...

### Steps To Reproduce
Make Sequence
Put a sprite or anything
Pick the top right panel's scale option
try to change a scale of that asset

[16094ab1-0367-40e4-9e16-58050ed6e5e3](https://api.gamemaker.io/api/github/downloads/16094ab1-0367-40e4-9e16-58050ed6e5e3)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.425  Runtime v2023.1100.0.439
