### ISSUE TITLE
Select colour doesn't get updated

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#1797]
### Description
I've occurred this while inside a sequence put I guess this would occur inside room editor too. Whenever you change an asset's color via color picker inside the inspector, the inspector color and color picker's color changes. But if I select another object while the color picker still open, the color that shows will be the same color before but the inspector shows the color of that new asset I've picked

### Steps To Reproduce
Open sequences or a room editor
Click an object to change its color via color picker inside the inspector
Change an objects color picker but don't close the color picker
Click another object

[9c02faf7-9b96-426e-9559-a646c9fe843d](https://api.gamemaker.io/api/github/downloads/9c02faf7-9b96-426e-9559-a646c9fe843d)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.420  Runtime v2023.1100.0.438
