### ISSUE TITLE
Particle Editor: IDE and runtime are inconsistent when emitter delay/interval min/max are inverted

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#1799]
### Description
The IDE Particle Editor treats emitter Delay and Interval min/max as a range and the order does not matter (so min can be more than max)
At runtime, the particles do not appear the same as in IDE if min > max for either interval or delay

### Steps To Reproduce
1. Create a new particle system, set the interval min =1 and max = 0; observe the particles are emitted intermittently
2. add the particle system to the room asset layer and run the game; observe the particles are emitted constantly
(see attached project for example)

Expected: IDE and runtime should be consistent - either IDE or runtime should be changed to match the other...

[ce9de900-0fad-49be-bc0b-3b4ab0309488](https://api.gamemaker.io/api/github/downloads/ce9de900-0fad-49be-bc0b-3b4ab0309488)

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.426  Runtime v2023.1100.0.440
