### ISSUE TITLE
Calling some_inst.name_of_script_asset inside a with statement will, depending on the type of instance value used, start an infinite loop or silently crash the game

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1802]
### Description
First up, there appears to be an issue where doing other.any_script_name(); will run the code inside the actual script asset itself, even if you have a function inside with the same name.
For the issue I'm describing, having a function of the same name or not makes no difference.
The problem gets extra cursed once you call the script using other inside a with statement, as it then triggers an infinite loop. The code inside will run forever, but in the scope of the instance the script was called for.
As I was typing this report, I discovered that swapping out other.Script1() for id.Script1() causes the game to silent crash at the start of the 2nd iteration of the with.

ETA: It appears using an actual instance id causes the silent crash, while the infinite loop is caused by things that are technically structs, like self or other

### Steps To Reproduce
1. Create 2 objects
2. Place both in a room
3. Create a script. Having a function inside or not makes no difference. Having any other code inside or not makes no difference.

4a. with (Object2) { other.Script1()};
5a. Game is now stuck in an infinite loop

4b. with (Object2) { id.Script1()};
5b. Game will crash with no error

[9c204e44-78e4-4687-885d-7b78652e47cc](https://api.gamemaker.io/api/github/downloads/9c204e44-78e4-4687-885d-7b78652e47cc)

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.420  Runtime v2023.1100.0.438
