### ISSUE TITLE
There is no way to access the id of emitters and types, when using the particle emitter.

### ISSUE THREAD

**Issue by AeternumGames** [YoYoGames/GameMaker-Bugs#1806]
### Description

In the particle editor you can create multiple emitters per particle system, but there is no way to get the emitter ID if one is using the particle editor. To address the correct emitter through code (burst, etc...), one has to guess which ID the emitter has been given. In addition, the emitters do not get their numbers by the respective particle system, but independently. So they get consecutive numbers as IDs, even if it's a whole new particle system asset. This is quite a mess and it is hardly possible to use the editor properly as soon as one wants to use more than one particle. Therefore I submit this as a bug and not as a feature request. (Also, by code it is possible to setup an emitter with multiple types of particles. In the editor you can only create one type per emitter, which might be more of a feature request, though)

### Expected Change

A way to reference the emitter. Either by using their names, as set up in the editor. Or by a function that returns all of the emitter IDs bound to the respective particle system. But for that, the emitters would have to be linked to their ps asset.

### Steps To Reproduce

1. Start GameMaker
2. Create two ps assets, with two emitters each.
3. Try to burst one specific emitter out of these four. 
4. Now, what is the id of that specific emitter?
5. Also first argument of part_emitter_burst() is irrelevant, as the id of the emitter is not dependent to the particle system.[
[contact_us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12750081/contact_us.zip)
](url)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
you can use the `particle_get_info()` to get the information that you are looking for

**Comment by AeternumGames** [comment]
Thanks Russel! I missed that one...
Although, the particle editor is still very confusing, to me. One first has to understand that the emitters and types are merged in the editor. So as far as I'm concerned, the issue can be closed.
Although, I would still say that the problem with the emitters not being tied to their particle system remains. But maybe you want it that way, I don't know....   🤷‍♂️
Thanks again for the quick reply!

**Comment by almo2001** [comment]
I am not seeing the Emitter ID here. Only its name and other parameters. I need the id for the burst function.
