### ISSUE TITLE
Room Editor: "Gradient" filter's "Mode" dropdown has inconsistent title case for the word "Conic" in some of the entries

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1809]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/924b16b8-e82c-4c19-a900-9c3456f48ec8)

note: the feather issue is a joke, but the naming convention is not contiguous.
yes I realize this is the lowest priority ticket you'll get all year

### Expected Change

Conic

### Steps To Reproduce

1. Start GameMaker
2. navigate to room
3. add gradient filter
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified in  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
