### ISSUE TITLE
Documentation: string_trim* functions don't have their second arguments documented

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1812]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/ba99f613-6535-4e4c-a9d4-7f931d08d56b)
The dock says it takes a string, but it takes an array of strings instead. This is also backed up by feather having the correct information for the function.

### Steps To Reproduce

https://manual-en.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Fstring_trim_end.htm

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
@gurpreetsinghmatharoo One for the manual also

**Comment by gurpreetsinghmatharoo** [comment]
Added the second argument for the three string_trim functions to the manual.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.454  Runtime v2024.200.0.466
