### ISSUE TITLE
unable to string `_GMFUNCTION_`

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1813]
### Description

`_GMFUNCTION_` already creates a string. but it is not possible to do `"_GMFUNCTION_"` this will simply return the same thing as `_GMFUNCTION_`

example:
```gml
show_debug_message(["_GMFUNCTION_", _GMFUNCTION_])
```

### Steps To Reproduce

1. Start GameMaker
2. paste code
3. compile
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
This is already fixed in #36

**Comment by rwkay** [comment]
I fixed this issue in the commit for #36 as I had noticed it at the same time...

**Comment by cameron-home** [comment]
Verified fixed in IDE v2023.1100.0.420  Runtime v2023.1100.0.438
