### ISSUE TITLE
In-Game: dbg_..._delete() will crash the game if that view/section contains a dbg_drop_down() instance

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#1814]
### Description

Call `dbg_view_delete` or `dbg_section_delete` crash if has nested `dbg_drop_down`.

### Steps To Reproduce

[dbg_view_delete-DropdownSilentCrash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12783563/dbg_view_delete-DropdownSilentCrash.zip)

1. Start GM and import the project.
2. Run it (e.g., Windows VM)
3. Wait a few seconds while the orange-y ball flies down and hits the pipe.
4. Observe the game immediately closes itself with no error.
5. (Optional) Comment-out ObjPlayer's Game End line 15 and observe this stops the crash.
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS
Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.418  Runtime v2023.1100.0.438, thanks.
