### ISSUE TITLE
`audio_get_name` returning string lowercased

### ISSUE THREAD

**Issue by danieltjewett** [YoYoGames/GameMaker-Bugs#1824]
### Description

`audio_get_name` is returning the string as a all lowercased string, instead of what is defined in the asset browser.

After further examination, it seems to be returning the key in the `.yy` file called `soundFile` for existing sounds.  When I add a new sound effect, this doesn't happen.

### Steps To Reproduce

1. Start GameMaker
2. Create an object that has a create event
3. Add in the create event `show_debug_message(audio_get_name(snd_ExistingSoundWithUppercaseInIt))`
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by colinator27** [comment]
Discovered an additional consequence of this bug: `asset_get_index` with an uppercase name will return -1, while a lowercase name will work. This is definitely new behavior, as this did not previously occur.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
