### ISSUE TITLE
[ISSUE] [DS_GRID] Grids of negative size can be created but crash if you try to do things with them

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#1827]
### Description
You're allowed to create grids of negative size, but ds_grid_copying them will hard-crash the runner

Enabling gml release mode will increase the number of grid operations that will hard-crash the runner, but honestly it should probably error if you try to create a grid of negative size in either mode

### Steps To Reproduce
Run the project

If you uncomment the gml release mode line, it'll crash earlier

[c86a84c1-5b35-4536-86aa-41e58a50e142](https://api.gamemaker.io/api/github/downloads/c86a84c1-5b35-4536-86aa-41e58a50e142)

**Comment by DragoniteSpam** [comment]
Yes I had to edit the title because I didn't realize how bad it sounds until after I filed the bug

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.417  Runtime v2023.1100.0.437
