### ISSUE TITLE
`@""` does not allow for escape quotes `\"`

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1828]
### Description

The following code will not compile despite having escape declaration.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/2a5131a9-48fb-45ca-b41e-544f9285388a)

### Expected Change

`\"` should work inside multi line strings

### Steps To Reproduce

1. Start GameMaker
2. Paste

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
The @ means that the string is treated as verbatim, so the \" are going to be treated as non-escaped.
