### ISSUE TITLE
Building Projects: [Windows NSIS] Uninstaller icon is missing from Add/Remove Programs list, Windows Store subscriptions get rejected

### ISSUE THREAD

**Issue by aliustaoglu** [YoYoGames/GameMaker-Bugs#1839]
### Description

The title is self-explanatory. When I package the game as an installer and install it, the uninstaller icon is missing. This leads to Windows Store submissions getting rejected.

As a workaround, I package it as a zip file and generate an installer via Inno Setup manually. After I did this my Windows Store submission got accepted. But it would be just good to use the default GameMaker installer directly.,

### Expected Change

Uninstaller icon to show up in Add/Remove Programs list

### Steps To Reproduce

1. Start GameMaker
2. Create an executable (for Windows) - even an empty template is fine
3. Package as installer
4. Install the game
5. See uninstaller icon 
6. This is unacceptable by Windows Store

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15793376/d4973b84-5fd0-4dbd-b0b6-76647f2c3950)

I have added my own icon files into `Game Options>Windows>Images` but the uninstaller icon does not change.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
The uninstaller icon is only missing from Add/Remove programs as far as I can tell.

The installation directory shows an icon 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/a1fc6357-1b22-4d69-8021-fb15b0922dd3)


But the Add Remove Programs does not
https://files.slack.com/files-pri/T02AA1BK1-F05UX043MC2/image.png


Can you confirm this is what you are seeing also?

**Comment by aliustaoglu** [comment]
> Can you confirm this is what you are seeing also?

@scott-dunbar Yes that is correct and it's the reason for their rejection. Their official rejection reason directly mentioned that icon in Add/Remove programs.

I also tried adding `MUI_UNICON` in NSIS script in the Installer setting. But that didn't help either. Then I decided to use Inno Setup and it worked and the submission got accepted.

**Comment by stuckie** [comment]
This should be easy enough to do according to: https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs#:~:text=Create%20a%20key%20with%20your,section%20in%20the%20Control%20Panel

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.420  Runtime v2023.1100.0.438
