### ISSUE TITLE
Building Project: Windows NSIS is missing the Header and Banner images

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#1841]
### Description

Setting the Header and Banner images for Windows and creating the NSIS installer will not display those images in the installer (they are blank)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/b7323551-599f-4ef7-a93e-d6e91ac52cdd)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/12859765-04d5-4d0e-ac86-2a525adb0aac)

[commandq.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12805442/commandq.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import attached project
3. Create a windows NSIS
4. Run the installer
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
The selector flags should be set for 24bit BMP

**Comment by CalumLaverock** [comment]
The header and finished images need to be 24bit so I've added an error dialog when 32bit images are used

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.434  Runtime v2023.1100.0.447. 

The IDE now returns an error when the wrong format image is selected. Thank you.
