### ISSUE TITLE
In-Game: [YYC] In-built instance variables used in room creation Try calls are now un-Catchable in 2023.8

### ISSUE THREAD

**Issue by LDinos** [YoYoGames/GameMaker-Bugs#1843]
### Description

Since recently, inbuilt variables such as x, y, depth, layer.... etc. are unusable in room creation code since they are unset variables. While this behaviour sounds correct, it is weird how if they are being used in a try-catch block, the unset error won't be caught there. Instead, the UNSET variable error will appear with a different line of code when the error appears, and it won't be because of the try-catch block.

### Expected Change

Make unset/unusable variables catchable in try-catch

### Steps To Reproduce

1. Start GameMaker and import the attached project
2. Run it in VM and observe the problem is caught and the depth is set to -200.
3. Run in YYC and observe the problem is not caught and so you get a code error

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Turned this one into a proper sample project and confirmed the issue now.

[testYYCTryCatchIssue.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12801680/testYYCTryCatchIssue.zip)

Aug23 YYC:
![Aug23YYC](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/600a7421-8817-47de-bf0b-bd99c011387c)

Aug23 VM:
![Aug23VM](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/7208e5c4-f9ee-42fc-94cb-f39394ab4d80)

LTSr2  (VM or YYC - doesn't matter):
![LTRSr2Result (VM or YYC - doesn't matter)](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/f211c30b-4c2f-491c-906f-84cc794cd98e)

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2023.1100.0.430  Runtime v2023.1100.0.444
