### ISSUE TITLE
Calling sprite_get_info() on an unpacked sprite causes a crash without error message

### ISSUE THREAD

**Issue by JujuAdams** [YoYoGames/GameMaker-Bugs#1846]
### Description

Calling sprite_get_info() on a sprite set to a texture group that is not packed for a given target platform causes a crash without an error message.

[sprite_get_info crash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12805760/sprite_get_info.crash.zip)

### Steps To Reproduce

1. Load attached project
2. Note that `sprNotPacked` is in a texture group that is not packed for any platform
3. Boot project
4. Observe crash when `sprite_get_info()` is called for `sprNotPacked`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.1 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package
**N.B.** As I am reporting for LTS, it is not possible to perform this step.

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yymrennie** [comment]
In the case where a sprite's images are on a texture page which isn't selected for export for the target platform sprite_get_info() now returns that the sprite has zero frames.

**Comment by cameron-home** [comment]
Verified in IDE v2023.1100.0.420  Runtime v2023.1100.0.438
