### ISSUE TITLE
Function to return array of texture group names

### ISSUE THREAD

**Issue by JujuAdams** [YoYoGames/GameMaker-Bugs#1847]
### Is your feature request related to a problem?

There are many texture group-related functions in the runtime, but no function to actually enumerate the texture groups that are available. Having some way to iterate over those texture groups leads to the ability to automatically manage those texture groups.

### Describe the solution you'd like

Function in a similar vein to the new `asset_get_ids()`. Something like  `texturegroup_get_all()` which returns an array of strings, each being the name of a texture group.

### Describe alternatives you've considered

Parsing the .win file myself, which is both slow and brittle.

### Additional context

Needed this one since 2017.

**Comment by rwkay** [comment]
Fixed in 2023.11 - new function `texturegroup_get_names()` added returns an array of all the texture group names that the runner knows about - empty texture groups are filtered by the asset compiler so may not be present

**Comment by scott-dunbar** [comment]
Verified in  IDE v2023.1100.0.430  Runtime v2023.1100.0.444
