### ISSUE TITLE
In-Game: [iOS] ProMotion changes cause rendering to not be correct on 120hz-capable devices in 2023.6 and 2023.8

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1851]
It says in the release notes fixes that "In-Game: [iOS] ProMotion changes cause rendering to happen only every other frame in 2023.6, so games appear to run slow". Sure, the frames do not get skipped but neither is the FPS 120 when you set it to be such. The movement just happens at half speed with the game thinking it's running at 120 FPS but 17ms passes between frames being drawn.

This is all perfectly evident in the same TestProjectiOSProMotion3.yyz I've sent you.

The value "Millisec: " being drawn on the screen is the current_time minus the last frame's current_time and it stays at 17 all the time. When you tap the screen to switch to running the game at 60 FPS, the speed of the moving square being drawn on the screen doubles.

I tested on the most recent iOS version 16.5.1 and the one before it.

Here are several forum links to other users reporting the issue as well:
1. https://forum.gamemaker.io/index.php?threads/ios-frame-rate-issues-with-newer-gm-ide-and-runtime.104571/
2. https://forum.gamemaker.io/index.php?threads/2023-6-release-thread.104420/post-631377
3. https://forum.gamemaker.io/index.php?threads/2023-6-release-thread.104420/post-631651
4. https://forum.gamemaker.io/index.php?threads/2023-6-release-thread.104420/post-629442

### Steps

1. Start GM and import the attached sample.
2. Run the project on a selection of ProMotion AND non-ProMotion devices
3. Ensure you tap the screen to change the refresh rate (assuming the phone obeys the request)
4. Confirm that the framerate is correct for all

[TestProjectiOSProMotion3.zip](https://github.com/YoYoGames/bugimport/files/12688822/TestProjectiOSProMotion3.zip)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.427  Runtime v2023.1100.0.441, thanks.
