### ISSUE TITLE
Room Editor : Adding an instance will trigger Feather to analyse the project

### ISSUE THREAD

**Issue by stuckie** [YoYoGames/GameMaker-Bugs#1857]
### Description

When adding a new instance to the room, Feather is triggering a full analysis of the project.
This can take an increasingly longer amount of time as project complexity increases and although the input is not blocked, the busy cursor is present and it is generally accepted to wait until the processing is over before continuing.

We should not need to do this as the name is auto-generated and is guaranteed to be unique, so we know that it is not yet being used in scripts.
In addition to this, most users will rename the instance to something more suitable before they reference it in code, so we should:

1. Add a preference to not track instance names entirely
2. Add a preference to only track non-default instance names
3. Don't analyse the project when adding an instance

This should reduce both the initial friction in using the room editor, as well as the overall parsing time as it can be configured to ignore instance names as required.

### Steps To Reproduce

1. Start GameMaker
2. Open an existing project - the more complex the better
3. Open a room and add an instance
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Additionally to this, we should reparse if an instance name is renamed and that name matches the aforementioned rules.

**Comment by WangleLine** [comment]
This is genuinely massively slowing down all level design in my games

**Comment by Totobal5** [comment]
me too please fix u.u

**Comment by alicemoretti** [comment]
One issue found and reported here: https://github.com/YoYoGames/YoYoStudio/issues/8928

Thank you.

**Comment by alicemoretti** [comment]
Connected issue has been verified fixed. 

Closing this issue too. Thank you.
