### ISSUE TITLE
IDE load crash - version 2023.8.2.106

### ISSUE THREAD

**Issue by CrysalisWare** [YoYoGames/GameMaker-Bugs#1862]
### Description

2023.8.2.106 update, unable to get past the loading screen when opening up gamemaker studio,
confirmed this has happened to another person as well. Rolling back to 2023.8.1.102 fixes the issue for me but was unable to find a way to get through on the new update. This is on Windows 10, .

(attached 'Contact Us Package' had to be done with 1.102 version because of the nature of the issue.)
[bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12834915/bug.zip)

### Steps To Reproduce

1. Start GameMaker after downloading the 2023.8.2.106 update.
2. IDE closes by itself, usually on RSS loading line.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by oldbomb** [comment]
I have the exact same issue on Windows 11 and also know from one other person.

**Comment by douwinga** [comment]
Had the same problem on Windows and have seen others posting about the issue as well in discord. It started happening immediately after updating to 2023.8.2.106. It is something to do with a file or files in %APPDATA%/GameMakerStudio2 or %ProgramData%/GameMakerStudio2 because if you uninstall gamemaker, delete those 2 folders, and reinstall 2023.8.2.106, it starts up fine on the latest version.

**Comment by rwkay** [comment]
This has been fixed and we are going to release an update to 2023.8.2 (fix also applied to 2023.11) - see https://github.com/YoYoGames/YoYoStudio/pull/8876

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/1874
