### ISSUE TITLE
feather thinks tileset_get_texture returns an Id.Texture instead of a Pointer.Texture

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#1866]
### Description
feather thinks tileset_get_texture returns an Id.Texture instead of a Pointer.Texture

[ebe7fb32-324d-44bf-9157-20e081761f4f](https://api.gamemaker.io/api/github/downloads/ebe7fb32-324d-44bf-9157-20e081761f4f)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.420  Runtime v2023.1100.0.438
