### ISSUE TITLE
Licensing: 2023.8.2.106 can crash on launch if the um.json file contains stale SSO information

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#1874]
### Description
Launching the IDE both on Mac and Windows today the IDE crashed upon launch.

Did happen in different internal GM versions. with the following error:

```
[09:19:03:562(cd14)] --------------------------------------------------------------------------------
[09:19:03:563(cd14)] IDE Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at A.d.R()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at A.d.D(Boolean )
   at YoYoStudio.SplashScreen.SplashTick()
   at YoYoStudio.Plugins.MethodContainer.Call(Object[] _args)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[09:19:03:563(cd14)] --------------------------------------------------------------------------------
[09:19:03:563(cd14)] ####################################
[09:19:03:563(cd14)] Break in FatalErrorWarning (IDE:4506)
[09:19:03:564(cd14)] ####################################
```

Was fixed by deleting the corrupted um.json manually.

Attached the the um.json with the stale information that caused the crash and the corrected file

### Expected Change

The file shouldn't make the IDE crash, and rather it should refresh its keys successfully

### Steps To Reproduce

1. Start GameMaker
2. Wait for the splash screen to reach the "Checking RSS..." phase
3. See GM closes

### How reliably can you recreate this issue using your steps above?

Always (if using bad um,json files)

### Which version of GameMaker are you reporting this issue for?

Other Release (IDE 2023.8.2.105/6)

### Which operating system(s) are you seeing the problem on?

Windows 10, MacOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by YYDan** [comment]
Okay, looks like this is an issue where I had stale/unwanted SSO keys in my um.json, as removing them/deleting the entire file fixes the issue.

[BAD-um.txt](https://github.com/YoYoGames/Incoming-Bugs/files/12832789/BAD-um.txt)

Removing these two lines from that um.json will fix the issue:
"useOperaSSO": "True",
"SSO_userCode": "48",

A verbose log shows also that the internal runtime feed IS able to be downloaded and read just fine, but then the runtime error is shown.

[ui.log](https://github.com/YoYoGames/Incoming-Bugs/files/12832784/ui.log)

**Comment by YYDan** [comment]
For anyone who has this issue, simply delete your um.json file entirely and then start GameMaker again. (You will need to login before you do any builds, but the file being wrong meant you were going to need to do that anyway...)

**Comment by YYDan** [comment]
There will be a tiny further updated .8.2 release coming soon to fix this one issue.

**Comment by YYDan** [comment]
Works fine now in IDE v2023.8.2.108. Closing.

**Comment by mbalandis** [comment]
@YYDan It may or not be resolved on direct version, however, issue persists on steam version. 

Steps to reproduce:
- Launch -> crash (User processing...)
- Delete um.json
- Launch -> works
- Log in 
- Exit 
- Launch -> crash (User processing...)

So basically you cannot log in or it will crash on next start. Tried verifying cache, tried deleting entire cache. 
Workaround is to not login but this is a bug nonetheless.

Screenshot:
![HrK5o43](https://github.com/YoYoGames/GameMaker-Bugs/assets/18264973/5cf4ba73-c6f4-401b-93f7-06ec28aed672)

**Comment by Emc1923** [comment]
@mbalandis, we are sorry to hear that you are still having issues. Could you please provide us with your ui.log to be able to investigate further? Does the issue persist after a [fresh install](https://help.gamemaker.io/hc/en-us/articles/115002062812-How-to-perform-a-fresh-install-of-GameMaker)? Thank you!

**Comment by mbalandis** [comment]
@Emc1923

Thank you for response.

Here is a ui.log after starting -> logging in -> quitting -> and starting (crash) 
[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/12959454/ui.log)

Still crashes after reinstall.
