### ISSUE TITLE
App does not seem to work on iPhone and iPad with OS version: iOS 17.1

### ISSUE THREAD

**Issue by MHG-Works** [YoYoGames/GameMaker-Bugs#1878]
### Description

I submitted my app on the App Store. However, it was rejected due to a crash experienced during app store review. The app did not crash on my end when I compiled it using xcode. The app employs cocoapods. Some additional details:

Device app was tested on: iPhone 13, iOS 16.6.1 (no update is available to 17.1 so I can't test it on that version on my end).
GameMaker version: IDE: 2023.8.2.106 (latest), Runtime: 2023.8.2.152 (latest).
xcode: 15.0

I have attached a zip file containing the crash logs that the app store review process supplied to me. You can obtain the zip file through the URL weblink I've added to this ticket. The app name is "_GomN".

LINK: https://www.dropbox.com/scl/fi/gwsmao9la0ip0sc09hofe/app_store_crash.zip?rlkey=52itrrvwvf9iczqswvj9y8d5p&dl=0

Please let me know if I should provide other details. Please let me know if there is a fix available. 

Thanks.

### Steps To Reproduce

Test if it builds correctly on iPhone + iPad, iOS 17.1 and iPhone model 14+. If possible, send to app store for review (if you have something like that).

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Which platform(s) are you having trouble building this project for?

iOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by MHG-Works** [comment]
Hi,

Just to add to this issue, I'm wondering if this is due to the Apple Game Center extension. I seem to recall that previous versions of the extension, or in a previous version of the Runner/IDE, I was able to inject the package name into the extension. However, I can't see this option anywhere if I open the Game Center extension file inside the IDE, or click on the "Manage extension options" gear icon. For Google Play Services extension, we have the AppID we can insert, but there is no equivalent in the Game Center extension (not necessarily AppId, but if I recall, the ability to insert the package name). Not sure if I'm misremembering, but just something that might help.

**Comment by ezekiel-hls** [comment]
Someone already posted a bug report regarding iOS builds crashes there's also comments on how to "fix" it if you want to use the latest runtime. The easiest workaround is downgrading your runtime version to 2023.6.x. This is how I get around the issue for the meantime since I am not using any new features from the latest runtime version

**Comment by Schwarzgamescom** [comment]
I face the same issue right now. Installng the iOS app locally works fine, but after uploading and testing via testflight the app crashes immediately. 
When I install Gamemaker IDE v2023.2.1.75 Runtime v2023.2.1.90 it works via testflight, but in Gamemaker IDE v2023.4.0.84 Runtime v2023.4.0.113 I get a black screen, in later versions the crash happens. So I guess after version 2023.2 something changed.

**Comment by MHG-Works** [comment]
After updating to the latest release of the runner, app review accepted the submission. Closing this ticket.
