### ISSUE TITLE
Empty events with a comment inside still run, causing a small amount of overhead. Overriden events inherited from a parent will still run even with no code inside.

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1887]
### Description
By running the profiler, you can see that events on an object that have no code but do have a comment will still run, using a small amount of processor time. An empty event with no comment will not run.
Additionally, if a child object overrides a parent event and the event has nothing (no comment) the event will also run, but will show up in the profiler as the parent object.

If it's expected that overriding a parent event with an empty event still has some overhead, then the bug there is that having or not having a comment affects what the object appears as in the profiler.

### Steps To Reproduce
Create an object. Add an event that runs every frame, like step or draw. 
Create another object, add the same event, and put a comment inside.
Place both in the room, run the debugger, and then run the profiler.
The event of the object with the comment will appear, the event of the object without the comment will not appear. 

Now, make the objects children of an object that has the same event. Both children will appear in the profiler, with the comment-less one appearing as the parent object itself.

[165b2d2c-122c-4fa9-bf15-cf6d075e863f](https://api.gamemaker.io/api/github/downloads/165b2d2c-122c-4fa9-bf15-cf6d075e863f)

**Comment by rwkay** [comment]
We have added an optimisation that removes empty events so that it will act like they are not there (but it still acts like they are there from an inheritance point of view) we are working through any issues that has brought up as well - you should see this in the initial 2023.1100 betas.

**Comment by gnysek** [comment]
@rwkay what with cases, where for example object should be only drawn on GUI, so current (probably undocumented) behaviour was to add any comment to draw event, and then use `draw_self();` plus any other wanted code? I understand that this fix means end of such solution, and it would require adding `exit;` or `return false;` in Draw event, when we want to draw object only on GUI?

**Comment by rwkay** [comment]
It only removes the event if the code is completely empty (but at runtime we know that it was there) so it just does not incur the overhead of entering the Execution Engine and then immediately returning because there is nothing. Everything else works as it should do (so inheritance and drawing etc)... We are watching for issues but it seems fairly stable at the moment.

**Comment by stuckie** [comment]
We believe this is fixed 2023.11

**Comment by YYDan** [comment]
Fixing the values, as this is in 2023.11 (as mentioned above), rather than "not planned".

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.443  Runtime v2023.1100.0.454. 

Thank you.
