### ISSUE TITLE
GameMaker closes upon opening

### ISSUE THREAD

**Issue by Drillimation** [YoYoGames/GameMaker-Bugs#1889]
### Description

When attempting to open GameMaker, the program closes instead of loading the project screen. I tried reinstalling the program, same issue.

### Steps To Reproduce

1. Start GameMaker

### How reliably can you recreate this issue using your steps above?

Only Ever Happened Once

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Drillimation** [comment]
[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/12870616/ui.log)

**Comment by YYDan** [comment]
This is a temp Web issue, but unfortunately that outage causes the very issue we were just about to release a fix for - #1884 

I will close this report just now, as it's a duplicate already, but there will be a fixed GameMaker release coming out as soon as the Web issue is resolved.
