### ISSUE TITLE
Audio filters become unstable if the cutoff/centre frequency is half the device sample rate

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#1897]
### Description

The maximum cutoff/centre frequency for the audio filters depends on the current device's sample rate.

The maximum is the lower of 20kHz or `fs/2`, where `fs` is the current device's sample rate. The device-based maximum should actually be just under `fs/2,` as the filter will begin to become unstable around that frequency (exactly when depends on the q parameter).

Only devices that run at 40kHz or lower will be affected by this - higher rate devices will be capped at 20kHz (as above).

### Expected Change

Users should not be able to make the filter unstable

### Steps To Reproduce

1. Go to the Windows sound settings (Settings -> System -> Sound).
2. Go to the properties for your current device.
3. Lower its sample rate to below 40kHz.
4. Start GameMaker.
5. Run this example project: [ghb-1897.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12874846/ghb-1897.zip)
6. You'll hear music for a short time but it will fade and a click will be heard before it stops entirely.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment]
Capped the maximum frequency of audio filters to 45% of the device sample rate. The 20kHz cap mentioned in the description has been removed, so for devices running at 48kHz the max has gone up, whereas for lower rate devices the max has gone down.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.6.0.157  Runtime v2024.6.0.205 (tested with sample rate of 36k Hz cutoff 14400 Hz)
