### ISSUE TITLE
In-Game: audio group is not loaded in 2023.8, when it worked in 2023.6

### ISSUE THREAD

**Issue by dev816** [YoYoGames/GameMaker-Bugs#1898]
### Description
audio groups are loaded but no sounds are played during the game, this bug appears from versions 2023.8+ in 2023.6 is missing

### Steps To Reproduce
Run for Windows VM using 2023.8.2
load any audiogroup, and audio not work

[4b0382e5-2b3e-4bd0-8cbd-927aaba3feec](https://api.gamemaker.io/api/github/downloads/4b0382e5-2b3e-4bd0-8cbd-927aaba3feec)

**Comment by stuckie** [comment]
We would need a project to verify against.

**Comment by YYDan** [comment]
Log shows that the audio group is unloaded:

```
object_variables_from_struct(merge_struct(data.from, data.to, 1), id);
click
Audio group 61 -> Unloading...
room_menu
Audio group 61 -> Unloaded
###game_end###254
```

Can't see any actual errors.

**Comment by stuckie** [comment]
If you are able to provide a project, feel free to reopen the ticket. Thanks.
