### ISSUE TITLE
`nameof(_GMFUNCTION_)` fails to compile.

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#1900]
### Description

logically it would just return the same thing as `_GMFUNCTION_` would, though it throws an internal error.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/8d512296-a1cf-49c8-97ba-542bf9125858)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Unable to replicate on 2023.11 - I think earlier changes with `_GMFUNCTION_` handling has fixed this.
