### ISSUE TITLE
In-Game: Silent crash when setting "room" to be a string value in 2023.8

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1912]
### Description
As the title says, setting the room variable to a string silent crashes the game with no error message. room_goto("string"); gives an error message as expected, no problem there

Notably, feather also does not give any warning for trying to set it to a string, while it does give a warning for using room_goto with a string

### Steps To Reproduce
room = "This string can be anything"

[7bf17a97-a68a-45c3-8afc-a3bbc78c55f0](https://api.gamemaker.io/api/github/downloads/7bf17a97-a68a-45c3-8afc-a3bbc78c55f0)

**Comment by KormexGit** [comment]
possibly related to #1910 but I don't know what their exact cause is

**Comment by Emc1923** [comment]
Verified as of  IDE v2023.1100.0.417  Runtime v2023.1100.0.437.
