### ISSUE TITLE
Extremely long call stack names when nesting functions

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#192]
GM-2337

Description: When you nest more than 4 functions or so (such as anonymous ones), the names that appear in the call stack in the debugger and in code errors/exceptions (and debug_get_callstack) become extraordinarily long. This poses some problems for working on code that involves multiple callbacks inside of each other, as the names become so long it becomes difficult to debug errors, and the debugger inside of the IDE itself begins to lag from the amount of text. For reference, in the example project, with about 8 nested functions, one entry can reach over 6 thousand characters. I believe most of the information in these very long names is unnecessary (portions are duplicated many times), but please correct me if that isn't the case.

*Steps*
 - Download and run the attached program
 - Notice the length of the warning message based on the error message from the code in Script1

*Expected*

The error message displayed should be more readable and concise if possible

**Comment by Totobal5** [comment]
please fix...

**Comment by rwkay** [comment]
Original project dialog looked like this
![image-2021-10-14-16-53-43-725](https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/030db332-8cfd-4ffa-9510-fbc903430c26)

**Comment by rwkay** [comment]
Fixed in 2023.11 new dialog looks like 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/b622e954-6bce-4e89-93a1-acf678e671dd)

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2023.1100.0.441 Beta Runtime v2023.1100.0.453
