### ISSUE TITLE
show_debug_log overlay doesn't scroll to the latest log line

### ISSUE THREAD

**Issue by prtksxna** [YoYoGames/GameMaker-Bugs#1922]
### Description
Its almost like it scrolls half of what is needed. Like when two lines are added it only scrolls to the second last one.

When things are being added to fast, like from a step event, it isn't able to keep up.

On MacOS IDE v2023.8.1.102 Runtime v2023.8.1.148

### Steps To Reproduce
Put some show_debug_messages in a step function and open the debug log overlay.

[0fa81d08-be51-47fd-9b3e-bd2491653eee](https://api.gamemaker.io/api/github/downloads/0fa81d08-be51-47fd-9b3e-bd2491653eee)

**Comment by rwkay** [comment]
I am not able to reproduce this at all - if it is still happening then please file with a project that shows it happening.

Note: If the window is scrolled then it will not be showing the most recent messages, you need to scroll it back to the bottom
