### ISSUE TITLE
In-Game: [HTML5] audio_play_sound() crash on old Safari versions (before macOS 14.1 and iOS 14.5), as AudioBufferSoundNode was only introduced then

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1925]
### Description

audio_play_sound() causes a game crash on Safari versions older than 14.5 (iOS) / 14.1 (Desktop), as the AudioBufferSoundNode constructor we use was only introduced in those versions, as can be seen on https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/AudioBufferSourceNode#browser_compatibility

Accordingly, iPhones up until 7 and many older Macs are not able to download a suitable version of Safari for running GM games.

Seems very similar to https://github.com/YoYoGames/GameMaker-HTML5/pull/216 (which was part of GM-7598)

![image](https://github.com/YoYoGames/bugimport/assets/131007845/53c4ca03-ff1f-4eeb-a070-5013aa86ae20)

Toby kindly reproduced this one for me using his old iOS emulator setup.

### Steps To Reproduce

1. Open the example project [GM-8079.yyz](https://drive.google.com/file/d/1PdFp4uvIQA6oTnC1OFBjeV6AOm55-c63/view?usp=sharing).
2. Run it for HTML5.
3. Connect to the microwebserver URL using your old iPhone/iPhone emulator.
4. Tap the screen to start the audio engine and trigger the sound playing.
5. Observe the game crashes.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Jun 23

### Which platform(s) are you seeing the problem on?

HTML5

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by OneOnlineShow** [comment]
Please fix this asap, my game doesn't work on any new iOS or any browser because of audio_play_sound... because of this I will have to switch from gms to another engine which is a waste of time...

**Comment by rwkay** [comment]
According to caniuse website it has been available a lot longer than what mozilla website says see https://caniuse.com/mdn-api_audiobuffersourcenode since 2013 ios on mobile and 2012 on desktop...

**Comment by OneOnlineShow** [comment]
Hello, any news?

**Comment by YYDan** [comment]
@OneOnlineShow Hi - can you confirm that all is well on your setup now, please? It's actually quite tricky to get such old versions off Apple now, so it would be great if you could confirm for us ;)
