### ISSUE TITLE
Code Editor: F1 always opens the manual, ignoring the Redefine Keys value

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1933]
### Description

In the code editor, if you press F1 the manual will always be opened even if you have already redefined this command to be a different key/combination. (There is a hardcoded F1 somewhere.)

### Expected Change

Preferences > Redefine Keys values for opening the manual should be respected in the Code Editor.

### Steps To Reproduce

1. Open GM and create/open any project.
2. Go to Preferences > Redefine Keys and search for "F1".
3. Change the open manual key for the code editor to something else and Apply your change.
5. Create/open any Object event or Script
6. Press F1
7. Observe the manual still opens in the browser.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Jun 23

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by SmithTom6304** [comment]
Will take a look at getting this in for 2024.04.

**Comment by SmithTom6304** [comment]
Shortcut was still hardcoded. We now use the hotkey as expected.
This was also the case with "Toggle Breakpoint" and `F9` - which should now be remappable as well.
Note this doesn't apply to CodeEditor2, which doesn't have "Open Manual" functionality yet (although it does have breakpoint functionality, which [should be remappable](https://github.com/YoYoGames/YoYoStudio/pull/9446)).

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.519  Runtime v2024.400.0.540, thanks.
