### ISSUE TITLE
'self' keyword incorrect for nested structure 

### ISSUE THREAD

**Issue by zzhamzz** [YoYoGames/GameMaker-Bugs#1955]
### Description

When defining nested structs the 'self' keyword is inconsistent when creating method.

Attached project demonstrates. All code is in a single script and the creation event of the first room. Debug output shows the inconsistency.

Project Link: https://drive.google.com/file/d/1k2v2e2KnaXR7ZR6zJYN10tzeGA0I42KV/view?usp=share_link

Code:

`function Foo() {show_debug_message(myName);}`

`function S1() constructor {`
`   myName = "S1";`
`   mySelf = self;`
`   myMethod = method(self, Foo);`
`   s2 = {`
`      myName = "S2";`
`      mySelf = self;`
`      myMethod = method(self, Foo); `
`   }`
`}`

`s1 = new S1();`

`show_debug_message(s1.myName);`
`show_debug_message(s1.mySelf.myName);`
`s1.myMethod();`

`show_debug_message(s1.s2.myName);`
`show_debug_message(s1.s2.mySelf.myName);`
`s1.s2.myMethod();`

The output should be:

S1
S1
S1
S2
S2
S2

but is instead

S1
S1
S1
S2
S2
S1 <--- INCORRECT

Within the nested struct the first to uses of 'self' are crrect, but the third use is incorrect when creating the method.

### Expected Change

self keyword is consistent in all uses and behaves as documented

### Steps To Reproduce

1. Start GameMaker
2. Run attached project
3. view debug output
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zzhamzz** [comment]
Other than waiting till after construction then how could you assign a script function as a method to a nested struct?

Obviously we can do this with anonymous function inside the construction. But a script function would require the 'method' routine which needs access to self.

**Comment by zzhamzz** [comment]
Additionally, can you give an example of self working at all useful in a nested struct.

e.g.

`s1 = {`
`  myName : "s1",`
`  s2 : {`
`     myName : "s2",`
`     myNameAgain : self.myName`
`  }`
`}`

If we do `show_debug_message(s1.s2.myNameAgain)` it will output incorrectly "s1".

**Comment by rwkay** [comment]
to setup a local method then simple do

```
s1 = {
 myFunc : function() { ... insert code here },
}
```

myFunc will be bound to s1 at that point

if you are looking to hook up another function then you will need to do it in 2 steps

```
s1 = { /* other definitions */
}
s1.myFunc = method( s1, MyFunc );
```

for your nested definitions then you should use

```
s1 = {
 myName : "s1",
 s2 : {
   myName : "s2",
   myNameAgain : myName,
 }
}
```

I think...

**Comment by zzhamzz** [comment]
Just so you know

s1 = {
 myName : "s1",
 s2 : {
   myName : "s2",
   myNameAgain : myName,
 }
}

That doesn't work either.
