### ISSUE TITLE
Catastrophic failure when swapping parents and then deleting an event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#1963]
### Description
By following a few specific steps on this one test project of mine, I've been able to reliably cause GameMaker to go unresponsive and then crash with no error message.
I submitted a report through the automatic crash reporter as well, but since I've been able to reliably reproduce the issue I'm submitting this report with project attached. I checked my dump folder for the file the window claimed it was generating, but don't see any sign of it.

### Steps To Reproduce
- Open up the objects parenttest and parenttestchild
- In the parent window for parenttest, remove parenttest's parent (which is parenttestchild)
- In parenttestchild's parent window, set it's parent to be parenttest
- Open up parenttestchild's draw event
- Attempt to delete the draw event
A command line looking window will pop up, GameMaker will go unresponsive, and then close itself with no error message.

[97b84943-53d7-4c8a-a967-fe85b7b09663](https://api.gamemaker.io/api/github/downloads/97b84943-53d7-4c8a-a967-fe85b7b09663)

**Comment by zreedy** [comment]
For QA, please try a non-direct cyclic dependency. parent -> child -> grandchild -> parent.
The fix for this was done on direct parents and I suspect that it might be possible to trigger this with indirect cyclic dependencies.
