### ISSUE TITLE
Sequence Editor: Certain colours on the colour picker don't show on the preview correctly when SDF fonts enabled

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#1966]
### Description

When enabling SDF fonts in the Sequence editor and using the colour picker, certain colours don't appear correctly on the preview. I noticed this with white and sky blue (FFFFFF, 00FFFF)

https://drive.google.com/file/d/1IGc5Xqx0gD_bOzk1wHKUfKb8JidhQ2Jp/view?usp=sharing

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/c0e0cfce-aeaa-42a7-8354-c0ea27793a9c)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/dc3a1c7b-8a9b-45ca-878f-d9809f4d550a)

#1104

### Expected Change

The colours shown on the preview should reflect what the user has chosen via the colour picker

### Steps To Reproduce

1. Start GameMaker and import attached project.
2. Go to Sequences and click on one of the text tracks.
3. Click on the Core Colour and choose either the light blue or the whites from the basic colours selection.
4. See the colour on preview is different.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2023.1100.0.410  Runtime v2023.1100.0.433

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by yyalansavage** [comment]
Not a bug - in the sample provided the text track has a non-white colour parameter track which is applied to the SDF effect colours - see the FSD RE "Note that colour values selected here should still be affected by colour tracks associated with the text track - i.e. the colours should multiply together."
