### ISSUE TITLE
array_length on VM still returns undefiend for non arrays

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#1977]
### Description

This was a change made on YYC for performance improvement reasons and should also be applied to VM runner.

### Expected Change

array_length of non arrays should return 0 instead of undefined.

### Steps To Reproduce

1. run the code:
```
a = array_length(12)
show_debug_message(a);
```
2. This should return 0.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2023.8.2.108  Runtime v2023.8.2.152

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.420  Runtime v2023.1100.0.438
