### ISSUE TITLE
Extension inclusion on the project should be controlled by platform selection (not by extension usage)

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#1981]
### Description

Right now unused extensions are not included in the project

### Steps To Reproduce

1. Create an extension
2. add an extension option
3. add a value to the option
4. in the initial room try to get that extension's extension option (extension_option_get_value)
5. it will return undefined
6. This happens because we are not using the extension so it is not being included.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.4 (Monthly), 2022.0.1 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by alicemoretti** [comment]
@DiasFranciscoA 

Can we get a project for this please? Thank you

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.455  Runtime v2024.200.0.467. Tested in this project:

[GM-1981.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13844629/GM-1981.zip)
