### ISSUE TITLE
Extension included folders (dll, dylibs) should be kept case sensitive and not be lowercased

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#1982]
### Description

As the title explains the extension files included in the extension are being systematically lowercased upon compilation since these could be libraries which the app needs to load at runtime those DLLs sometimes depend on other DLLs (GOG, Steam, FMOD, ...) that need to be kept in the same case as they are in the IDE to make these extensions work properly in case sensitive OSes

### Expected Change

Don't change extension files casing

### Steps To Reproduce

1. Create an extension
2. Add a file to it (existing one with lower case and upper case characters, can be a 0Kb dll or dylib)
3. Make sure the extension has functions and you use them so the extension is exported
4. Run the game
5. Go to the TEMP folder and check for the extension file
6. It will be all lowercased

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker?

2023.8, 2022.0.1, Internal Monthly Build, Beta Public

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Which platform(s) are you having trouble building this project for?

macOS, Android

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package/Logs Attached?

- [ ] I have attached my evidence

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
@DiasFranciscoA  
Could we get a project for this please? Thank you
