### ISSUE TITLE
Live wallpaper using spine sprites as particles behaves different between desktop and opera gx

### ISSUE THREAD

**Issue by patrickrocheyoyo** [YoYoGames/GameMaker-Bugs#1989]
### Description

If the user runs the attached project in gx.games they will notice that the opera logo spine sprite files are not showing. If the user runs it on windows they will notice that the opera logos are showing correctly. 
[Opera Colours (1).zip](https://github.com/YoYoGames/Incoming-Bugs/files/12729828/Opera.Colours.1.zip)

 IDE v2023.8.1.102  Runtime v2023.8.1.148

### Expected Change

For GX and Windows to have behavior's parity in favor of both showing the sprites.

### Steps To Reproduce

1. Start GameMaker
2. Load the attached project
3. Run the project targeting windows
4. Notice sprites
5. Run the project again targeting GX
6. Notice the lack of sprites

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2023.1100.0.435  Runtime v2023.1100.0.448
