### ISSUE TITLE
Constructors Defined within Objects Auto Fills with Invalid GML

### ISSUE THREAD

**Issue by bfrymire** [YoYoGames/GameMaker-Bugs#2009]
### Description

When creating a new constructor that was defined within an object, the code editor's auto fill feature will output code that is not valid GML code.

The auto fill formatting will be like `<OBJECT_NAME>_<EVENT_NAME>$$<CONSTRUCTOR_NAME>()`.

![GameMaker_iessHnZjub](https://github.com/YoYoGames/GameMaker-Bugs/assets/20096702/98ee3974-e374-459d-a760-af76a242c279)

[test_new_constructor_autofill.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13061162/test_new_constructor_autofill.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. In the Create Event of the object, define a constructor
4. After the constructor definition, create a new constructor, but allow auto fill to complete the name of the constructor
5. Notice the name of the constructor in the auto fill
6. Click or press enter to allow the auto fill to complete the constructor

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. I've added a string trim so that the namespace delimiter $$ is always stripped. Aside from Lint Messages (and even here, it's not ideal) users should never see the $$ delimiter as it's an implementation detail to keep symbols from conflicting.
