### ISSUE TITLE
Using `string()` on a struct returns an empty string in 2022.0.2.49, used to return a JSON string in 2022.0.1.30

### ISSUE THREAD

**Issue by JujuAdams** [YoYoGames/GameMaker-Bugs#2014]
### Description

```
array = [];
struct = {};
arrayRoot = [{}];
structRoot = {a: []};

show_debug_message("Expect \"[  ]\"");
show_debug_message(string(array)); //Shows "[  ]"

show_debug_message("Expect \"{  }\"");
show_debug_message(string(struct)); //Shows ""

show_debug_message("Expect \"[ {  } ]\"");
show_debug_message(string(arrayRoot)); //Shows "[  ]"

show_debug_message("Expect \"{ a : [  ] }\"");
show_debug_message(string(structRoot)); //Shows ""
```

### Expected Change

Return behaviour of `string()` to GM LTS 2022.0.1.30 behaviour

### Steps To Reproduce

1. Start GameMaker LTS 2022.0.2.49
2. Copy-paste above code into a new script
3. Run the game
4. Check the output log and observe expected and actual values do not correlate for structs

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.1 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JujuAdams** [comment]
P.S.  Bug reporter version uses 2022.0.1 for LTS, this should be updated to 2022.0.2.

**Comment by CarloCasa** [comment]
Hi, apologize for the silly question, but 2023.11 it means that will be fixed also for the LS version?

**Comment by JujuAdams** [comment]
I'd like to see a hotfix for this too.

**Comment by rwkay** [comment]
It will be a candidate for the next LTS update (not sure when that will be)
