### ISSUE TITLE
Xnput Gamepad triggers and axes cannot give the full range of 0..1 (for triggers) or -1..1 (for axes)

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#2016]
### Description

XInput Gamepad triggers and axes cannot give the full range of 0..1 (for triggers) or -1..1 (for axes)

* for triggers we are dividing by 256 for a byte (should be 255) to ensure that we get the full range
* for axes we are dividing by 32767 which means we never get the full -1 value

### Expected Change

Improve the conversions to give the full range

### Steps To Reproduce

* Plugin XInput gamepad
* Load and Run the attached project (for Windows)
* check trigger values 
* check axes values
[GamepadRemap_v4.yyz.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13070841/GamepadRemap_v4.yyz.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11 see commit https://github.com/YoYoGames/GameMaker/commit/559e824142f278c87e84ae1043627d13e1c51226

**Comment by seqadstudios** [comment]
gp_axislh : now reports as -1 (stick max left) to 0 (stick max right)
gp_axislv : now reports as 0 (stick max up) to 1 (stick max down)
gp_axisrh : now reports as -1 (stick max left) to 0 (stick max right)
gp_axisrv : now reports as 0 (stick max up) to 1 (stick max down)

The old ranges was -1 to 1 on all axis.

The new range will break old game controller input code.

Tested on IDE V2023.1100.0.425, runtime: V2023.1100.439

**Comment by cameron-home** [comment]
Verified fixed in IDE v2023.1100.0.436  Runtime v2023.1100.0.449
