### ISSUE TITLE
LiveWallpaper Security changes

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#2017]
### Description

Currently Windows based LiveWallpapers are not sandboxed any more than a standard Windows game, we need to introduce a more stringent sandbox for LiveWallpapers as follows.

* File access - use the standard file sandbox and disallow any access outside the File Bundle and the standard Save Area
* Network - for the moment disallow all network access (TCP/UDP or HTTP)
* Microphone - never allow any microphone access when running as a LiveWallpaper
* DLL - do not allow any DLL calls (any DLL extensions or external_call or external_define)

We may relax this restriction in the future but we will put these limits in place ASAP.

### Expected Change

See above.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by gurpreetsinghmatharoo** [comment]
Do these restrictions also apply to LWs running on Opera GX, where applicable?
