### ISSUE TITLE
Error when trying to call function using its index stored in an instance array and accessed with self

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#2019]
### Description

(Sorry for the somewhat involved title)

**Description**

This is a fairly specific bug that occurs when one has a function index stored in an array (for example, this happens in my UI library, *gooey*, where the user specifies callback functions that get called whenever a certain interaction event happens, such as a left mouse released event). When said array is then referenced using `self` and then called in the same line, it throws an error.

The built-in function can have 0 or more arguments (with 1 or more arguments, one would obviously need to specify them in the function calls below):

```
self.func = window_center;
```

Code:

```
self.arr = [];
array_push(self.arr, self.func);
arr[0]();						// works
self.arr[0]();						// Error: Unable to get object for index XXXXX
```

It's noteworthy that assigning the (index) value contained in the array to a local variable and then calling the corresponding function, works:

```
var _arr = self.arr[0];
_arr();							// works
```

Also, this behavior does not happen when the index is stored inside an instance or local variable instead of an array:

```
func()							// works
self.func();						// works
```

Lastly, none of this happens either when using a custom function:

```
function test() {
	show_debug_message("TEST at {0}", current_time);
}

self.func = test;

self.arr = [];
array_push(self.arr, self.func);
arr[0]();						// works
self.arr[0]();						// works as well!
```

The code shown is included in the YYZ attached below for easy replicability
[Function calling bug with self.zip](https://github.com/YoYoGames/GameMaker-HTML5/files/13079404/Function.calling.bug.with.self.zip)

### Steps To Reproduce

1. Start GameMaker
2. Load the sample project
3. Hit F5 / run

[Function calling bug with self - Contact Us package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13079462/Function.calling.bug.with.self.-.Contact.Us.package.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), 2022.0.1 (LTS), Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Unable to replicate in 2023.11 - I think earlier fixes may have already addressed this issue.

**Comment by biyectivo** [comment]
Err, nope, at least not in the public Beta. I just updated to the latest Beta and ran the project and the error persists...

<img width="978" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/e21b1930-63a2-4969-b924-1f8ab1fc8837">

**Comment by YYDan** [comment]
Flattened all the content here into your own https://github.com/YoYoGames/GameMaker-Bugs/issues/2065 so we don't have 3 issues to track for this 1 problem ;)
