### ISSUE TITLE
Repository/Project feature request: Documentation Issue

### ISSUE THREAD

**Issue by zzhamzz** [YoYoGames/GameMaker-Bugs#2022]
### Description

This is a feature request for this repo 'GameMaker-Bugs'.

Currently there is no category for documentation issues.  Please add the ability to report documentation issues.

At the user level, the only way the user knows if something is 'working as intended' is via the documentation. If the intented behavior or runtime behavior differs from documented behavior then it is a BUG for the user.  Either the runtime behavior or documentation must change.

This relates to two bug reports: #1955, #2020

Both of which have been closed as 'working as intended.'  

However, currentl runtime behavior contradicts documented behavior.  And there is no way to officially report documentation issues via this repo.

If #1955 and #2020 are working as intended then a documentation issue remains.

Please add a category to report documentation issues.

### Expected Change

Add category 'Documentation Issue' to this repos labels for issues.

### Steps To Reproduce

N/A

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
This should be added now.

**Comment by YYDan** [comment]
As an aside, we already have a task for the in-IDE reporter to gain a "Manual Content" category in forthcoming November releases, so what's been done for this specific issue is to add the corresponding web template onto this repository:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/6c906def-a182-4473-ad1b-f81f0a182d5f)
