### ISSUE TITLE
Updating Broke Tileset Collision

### ISSUE THREAD

**Issue by tsunnui** [YoYoGames/GameMaker-Bugs#2024]
### Description

I opened up Gamemaker Studio 2 2023.8.2.106 when it prompted me to update my engine. I updated, and upon updating, I could no longer open any of my projects. It would give me an error saying my Windows runtime was not downloaded, and then crash when it tried to update it. Trying to update the runtime before opening the project did not work either. A reinstall didn't work, so then I tried a fresh install. This work! However, upon opening my project all of my tileset collisions didn't work, when they previously did. The code runs, but my object passes through walls now. I created a new sample project with a simplified version of my collision code, just to see if it was project-specific. It was not. I tested to see if object-to-object collision would work instead, and it did. It's as if tileset collision just wasn't valid anymore. I tried on both the Windows platform and the IDE. Wanting to check if it was my computer or not, I asked my friend to download the engine on his computer and copy my code. The code works on his computer with no changes at all. Upon figuring this out, I tried another fresh install, this time also manually deleting any remnants from Gamemaker Studio 1.4 in case that was causing issues. This also didn't work, and so I can no longer perform tileset collision in my version of Gamemaker. Any assistance would be appreciated. This issue has me paranoid, as I do not know if whatever broke my tileset collision also broke something else and I just haven't encountered it yet.

I followed this guide to fresh install my Gamemaker Studio:

https://help.gamemaker.io/hc/en-us/articles/115002062812-How-to-perform-a-fresh-install-of-GameMaker
[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13160545/ui.log)
![whymustisuffer](https://github.com/YoYoGames/GameMaker-Bugs/assets/148926393/22dc401f-214b-4c11-a8da-1578bb9674ed)
[Output Log.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/13160546/Output.Log.txt)
![Step](https://github.com/YoYoGames/GameMaker-Bugs/assets/148926393/71739b45-e9e7-4160-ae96-e575811d66f0)
![Create](https://github.com/YoYoGames/GameMaker-Bugs/assets/148926393/47f20ddd-b3b0-499a-884f-d01569dc8af4)
[ContactUsPackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13160649/ContactUsPackage.zip)
[SampleProject.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13160651/SampleProject.zip)

### Steps To Reproduce

1. Start GameMaker
2. Start A New Project
3. Recreate Create Code
4. Recreate Step Code
5. See the issue

The main problem is I have been unable to recreate this issue on another machine. Following the same steps and recreating the same code on the same version, the code works as expected. However, I have not failed to recreate this issue once on my old machine.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by tsunnui** [comment]
Update: I opened up gamemaker today and it prompted me to update my runtimes. Upon doing so, the code that previously wasn't working started working. I've been having this issue since the release of 2023.8.2.108 and I've been working on my projects in spite of the issue since then, and it did not prompt me to update my runtimes till now. I am unsure as to what caused the original issue, or what prompted the runtime update after so long of not doing so.

**Comment by jackerley** [comment]
Hi, let us know if you manage to work out what the problem with your runtimes was. I'll close this now tho'
