### ISSUE TITLE
Feather: Deleting a Script/Object which contained directives doesn't automatically refresh the messages window

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2026]
### Description

When deleting directly a script or object with feather directives without editing it first, feather messages won't appear again until the project is reload.

### Expected Change

Feather messages should reappear directly without the need of reloading a project

### Steps To Reproduce

1. Start GameMaker
2. Import the attached project
3. Delete the 'Ignoreall' script
4. See the issue
[featherdirectivesbug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13164752/featherdirectivesbug.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly), Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Contexts were deleted, but messages were not being cleared which is required for project-wide directives to be updated. Differences in code path required for Discovery/Compiler passes to play nicely.

**Comment by Emc1923** [comment]
Verified fixed in IDE v2023.1100.0.434  Runtime v2023.1100.0.447
