### ISSUE TITLE
In-Game: [iOS] Games using broadcast need support for reacting to the com.apple.developer.networking.multicast entitlement being present or not

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#2027]
### Description

Broadcast discovery for LAN games does not work on *some* iOS and tvOS devices. This is because the app requires a special entitlement to be set in its plist.

[https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast)

says the following:

```
Your app must have this entitlement to send or receive IP multicast or broadcast on iOS. It also allows your app to browse and advertise arbitrary Bonjour service types.

This entitlement requires permission from Apple before you can use it in your app. Request permission from the [Multicast Networking Entitlement Request](https://developer.apple.com/contact/request/networking-multicast) page.
```

However, in our internal developer testing, it has been found that despite what that page says, only *some* iOS/tvOS devices actually *require* the entitlement.

### Expected Change

This functionality should be supported / our functions should handle the entitlement being there AND not being there.

**Comment by YYDan** [comment]
Sounds like this one is not actually verifiable by us either, as we would have the same store permissions issue as Dan documented above. Closing now, and will reopen if we get reports from customers suggesting that this does not work once that permission has been granted.
