### ISSUE TITLE
In-Game: [PS4] Scribble's shaders throw unexpected shader_set_uniform_f_array error

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#2029]
### Description

Scribble's shaders throw an unexpected shader_set_uniform_f_array error when a project is run on PS4. The code error dialog says the following:

```
ERROR in
action number 1
of Draw Event
for object oTutorialTexts:

shader_set_uniform_f_array: Array too large for shader
at gml_Script_anon49372___scribble_class_element___scribble_class_element (line 1609)
- shader_set_uniform_f_array(_u_aDataFields, _anim_properties_array);
```

### Steps

1. Run this project https://drive.google.com/file/d/16rwtg3v5vOlHLOtwPU9MahU_TXS89Md1/view?usp=sharing on PS4
2. Witness error once level is selected

**Comment by cameron-home** [comment]
Looks like this project cannot be tested in LTS so leaving as picked.
