### ISSUE TITLE
Docs: `string_trim` doesn't have `substr` argument

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#2030]
### Description

`string_trim` contains an optional `substr` argument which is not reflected in [the docs](https://manual-en.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Fstring_trim.htm).
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/f5330f0a-405c-45bd-82f9-9208a31b7aed)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/9790fe61-04e4-4640-9465-783129b5bd87)

### Expected Change

`substr` should be list in the docs

### Link

https://manual-en.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Fstring_trim.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed in https://github.com/YoYoGames/GameMaker-Bugs/issues/1812
Closing as duplicate
