### ISSUE TITLE
script_get_name for ref script 100000 returns "<unknown>"

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#2035]
### Description
I've been testing asset_get_ids, so I made functions some_func/other_func/whatever in Script 1, and lorem_ipsum in Script 2.

I then tried using asset_get_ids(asset_script) to print names of the found script assets and see if both script functions and script assets are included.

It listed the scripts mostly correctly, but the ref script 100000 got \<unknown\> for a name instead (which apparently should be Script2). It happened earlier with just Script1, so it may have something to do with the first script of the bunch, rather than any script in particular.

### Steps To Reproduce
- create new project
- add a bunch of scripts with a bunch of script functions
- loop over `asset_get_ids(asset_script)` and print `script_get_name(...)` for each received asset ID
- run the game and see that the first asset has "\<unknown\>" name

[9bd734f8-afbf-407f-b7c5-55032c6551fe](https://api.gamemaker.io/api/github/downloads/9bd734f8-afbf-407f-b7c5-55032c6551fe)

**Comment by mgeddesGM** [comment]
verified in  IDE v2023.1100.0.426  Runtime v2023.1100.0.440
