### ISSUE TITLE
GM crashes for no apparent reason

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#2038]
### Description
I was minding my own business and writing some code to see if I could map static structs to constructor, and suddenly a console window appeared and the IDE crashed.
Just in case, I attached the related project. It crashed for me when I started typing some string, maybe it's related to string parsing?

### Steps to reproduce

I've found that I can get the crash pretty consistently if I try to type `static name = "CtorA";` into the CtorA function from the attached project.
I couldn't reproduce it when adding a static variable to a constructor in an otherwise blank project, though.

[97e7b4da-c44e-42ac-ad2a-16f8f9fff3e3](https://api.gamemaker.io/api/github/downloads/97e7b4da-c44e-42ac-ad2a-16f8f9fff3e3)

**Comment by gnysek** [comment]
Might be connected to #2038 .

**Comment by stuckie** [comment]
Fixed as part of https://github.com/YoYoGames/YoYoStudio/pull/8995

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.438  Runtime v2023.1100.0.451. 

Thank you
