### ISSUE TITLE
GM Unstabilize when paste an img to sprite editor

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2040]
### Description
In the newest IDE 2023.1100.0.425 this bug occurs. When I paste an image to a sprite editor, it will unstabilize GM, and won't even show the image I paste in there, and if I look inside image editor, it will only show a lost texture.
Sometimes it even hard crashes GM.

### Steps To Reproduce
*Open sprite editor
*Paste an image to it

[9610d02f-f87c-494a-b075-b2d91dafcd30](https://api.gamemaker.io/api/github/downloads/9610d02f-f87c-494a-b075-b2d91dafcd30)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.437  Runtime v2023.1100.0.450. Thank you
