### ISSUE TITLE
Can't invoke creation_code and pre_creation_code from room_get_info

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#2045]
### Description
I was trying out room_get_info, so for testing I put three instances in Room1 - one with creation code - and I made Room2 with Creation Code testing Room1 information.

creation_code and pre_creation_code had values of 0,1/2,3/4,5. Trying to call these functions tried to call built-in functions instead. I've been suggested adding 100000 to these, but I ended up calling unrelated scripts instead.

Thus, I can't find a way to actually use the creation_code or pre_creation_code anyhow.

[bac81017-59f3-4b72-8218-3d01d726b44c](https://api.gamemaker.io/api/github/downloads/bac81017-59f3-4b72-8218-3d01d726b44c)

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by scott-dunbar** [comment]
Verified as all fixed and working in IDE v2023.11.0.120  Runtime v2023.11.0.157.

**Comment by danieltjewett** [comment]
@Alphish
> Thus, I can't find a way to actually use the creation_code or pre_creation_code anyhow.
How were you able to make use of these?  I understand to call `script_execute(index)`, but the point of these scripts are to be called before the instance is created (e.g. `instance_create_*`).  The best we can do is pass a var struct in, but `creation_code` and `pre_creation_code` are functions, not structs.

**Comment by danieltjewett** [comment]
`pre_creation_code` essentially contains variable declarations which will be in scope of the instance that it is called on. Our instance isn't created yet (i.e. the instance we'd create through `instance_create_*`) and if we did a `with` after it was created, it would defeat the purpose of it being a `pre_creation_code` call.

I did come up with a workaround last night, though:
```
var data = instances[i];

var struct = {
    image_xscale: data.xscale,
    image_yscale: data.yscale,
    image_angle: data.angle,
    image_index: data.image_index,
    image_speed: data.image_speed,
    image_blend: data.colour,
};
    
if (data.pre_creation_code != -1)
{
    var __inst = instance_create(x, y, oEmpty);
    with (__inst)
    {
	    script_execute(data.pre_creation_code);
	    
	    var names = variable_instance_get_names(id);
	    var length = array_length(names);
	    for (var j=0; j<length; j++)
	    {
		    struct[$ names[j]] = variable_instance_get(id, names);
	    }
    }
    instance_destroy(__inst);
}
    
instance_create_depth(data.x, data.y, 0, asset_get_index(data.object_index), struct);
```

Essentially, we have an object called `oEmpty`, which is literally just an object in the asset browser that has nothing in it.  If there is `pre_creation_code` for a given instance, we execute the code in the `oEmpty` instance's scope, get the variable names and values in the `pre_creation_code`, and then inject it into our var_struct, which we can pass into `instance_create_*` functions.  It's a bit hacky, but does work.

I'd be curious if there is a more elegant way of doing this, as it requires use of creating and destroying an extra instance, as well as having an extra object in the asset browser on hand.

**Comment by danieltjewett** [comment]
Now that I am actually awake, and not trying to figure out something before I go to sleep, I realized we don't need to make use of an `oEmpty` object whatsoever:
```
var data = instances[i];

var struct = {
    image_xscale: data.xscale,
    image_yscale: data.yscale,
    image_angle: data.angle,
    image_index: data.image_index,
    image_speed: data.image_speed,
    image_blend: data.colour,
};
    
if (data.pre_creation_code != -1)
{
    with (struct)
    {
	    script_execute(data.pre_creation_code);
    }
}
    
instance_create_depth(data.x, data.y, 0, asset_get_index(data.object_index), struct);
```
This is elegant enough for me.  It _might_ be useful to document how to utilize `pre_creation_code` properly.
