### ISSUE TITLE
asset_get_ids(asset_script) yields anonymous functions and room creation code

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#2046]
### Description
Using the same project as #2045.

Trying to diagnose creation_code and pre_creation_code from the aforementioned issue, I tried to print the names of all scripts returned by asset_get_ids(asset_script).

I didn't find instance creation codes in the script, but I found some anonymous function entries and Room2 creation code.

I'd expect most people would expect to get only script assets and script functions, rather than every anonymous/auto-generated function in existence, especially since separating the named functions from anonymous adds extra hassle.

In Room2 Creation Code, I printed other function names and got the following unexpected names:
\<unknown\> (relates to issue #2035)
anon461_anon294_static_get_function_Script3
___struct___0_anon294_static_get_function_Script3
anon294_static_get_function_Script3
___struct___1_gml_Room_Room2_Create

### Steps To Reproduce
Run the example project, Room2 Creation Code will print both the "regular" and anonymous/creation function names.

[1f7d5b42-1041-4375-a4fc-84144f1caea6](https://api.gamemaker.io/api/github/downloads/1f7d5b42-1041-4375-a4fc-84144f1caea6)

**Comment by rwkay** [comment]
This is intentional and not a bug... these can all be called using script_execute.
