### ISSUE TITLE
The sample code for `http_request` is overly complex

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#2047]
### Description

In the example code, there's a lot of unecessary headers passed in and while having some headers passed in is great for illustrative purposes, they can cause a _lot_ of confusion to someone new to the concept of HTTP requests. 

It may be worth mentioning that some headers are included automatically by GameMaker and generally won't need to be attached, such as `Content-Length`, `Accept-Encoding`, and `Host`, and instead just listing the few that are best to explicitly include, such as `Content-Type`, `Authorization`, and `User-Agent`

### Manual Link

https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Asynchronous_Functions/HTTP/http_request.htm

**Comment by YYBartT** [comment]
Removed some of the HTTP headers and added a call to `ds_map_destroy` at the end. Also did some minor changes to the page.
