### ISSUE TITLE
Code Editor: Autocomplete missing function paramaters

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#2048]
### Description

Autocomplete no longer shows the parameters for functions

Beta  IDE v2023.1100.0.426  Runtime v2023.1100.0.440
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/888690e6-bdae-4502-b40f-149dc07ebcad)

Monthly  IDE v2023.8.2.108  Runtime v2023.8.2.152
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/bd52bf21-7041-4349-b754-ce886c2cd51d)

[Buffer.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13190037/Buffer.zip)

### Expected Change

Expected parameters should be shown

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Open a script/event
4. Start typing a function to bring up autocomplete
5. Observe missing parameter information

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Feather needed a Legacy behavior flag to account for running in the new Code Editor vs Legacy Code Editor.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
