### ISSUE TITLE
[Feather] Incorrect GM2016 error says built in variables were not declared in the create event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2055]
### Description
Giving an object a method that contains a with statement and setting some built in variables inside the with statement (such as image_angle, image_xscale) and then calling that method somewhere causes feather to show incorrect warnings. GM2016 Instance variable 'image_xscale' declared outside of Create event, declare with 'var' or move to Create event. 
The warnings will not always be there. Sometimes clicking on the warning in the feather messages window will cause it to disappear, sometimes it won't. Changing the code inside the method, or even unrelated code will cause the error to appear or disappear.

### Steps To Reproduce
Create a method on an object that uses a with on another object, and set a built in variable inside. This is the code I used to get it to happen, but I've had it happen for other methods as well that are using a with statement directly on an object, not on an instance_create_layer call.
test = function() {
	with (instance_create_layer(x, y, "Specials", oTest2)) {
		image_angle = 5;
		image_xscale = other.image_xscale;
		image_yscale = other.image_yscale;
	}	
}
and then call the method somewhere else. The error will not always appear, it will repeatedly appear and disappear as code is changed and feather re-analyzes the project.

[69f2f326-0c36-48f9-9489-be527680757d](https://api.gamemaker.io/api/github/downloads/69f2f326-0c36-48f9-9489-be527680757d)

**Comment by zreedy** [comment]
Two issues identified in the test project:
- image_angle, image_xscale, image_yscale are built-in variables and function calls should not raise GM2016
- image_angle, image_xscale, image_yscale are being set inside of a with statement and are not instance variables local to shootProjectile so there should be no attempt to import in the first place

**Comment by KormexGit** [comment]
While working on my project, I noticed the same error appearing for x and y. I added some more built in instance variables to my test project, and it seems to happen for all of them.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/b683ec59-a5d0-4774-83e3-18c94d6952dc)

**Comment by zreedy** [comment]
Fixed. Issue was with the Discovery pass not accounting for built-in variable visibilities when discovering instance variables. This caused built-in variables to be assigned as instance variables in functions scopes and then imported via function call as an instance variable; circumventing these checks in the Compiler pass.
