### ISSUE TITLE
Preferences [General Settings]: Unwanted preferences for Project Tool in General Settings>Output Windows 

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#2059]
### Description

On IDE v2023.1100.0.426  Runtime v2023.1100.0.440, in Preferences>General Settings>Output Windows at the bottom of the list there is a section called "String Not Found: Project Tool". 

That should not be there.

[protol.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13204378/protol.zip)

### Expected Change

That section in Preferences is not present in 2023.1100 

### Steps To Reproduce

1. Start GameMaker
2. Open Preferences>General Settings>Output Windows
3. Scroll to the bottom of the list 
4. See the issue
![Screenshot 2023-10-30 105044](https://github.com/YoYoGames/GameMaker-Bugs/assets/59605840/e01ce625-c941-4923-91fc-4a5826d8d246)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Related to #2060

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.441  Runtime v2023.1100.0.453
