### ISSUE TITLE
Project Tool: Project Tool  output shows up when using the 'Go To' search window

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2060]
### Description

The option to show the project tool output from the 'Debug' feature is currently showing up when using the Go To search funtion.

### Steps To Reproduce

1.  Start GameMaker
2.  Right Click and select 'Go To..' /Ctrl+T inside the workspace
3.  Search for Project Tool
4.  See the issue

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/ddf6af88-c702-46c4-bbb7-ba17dd7c1e98)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta ( IDE v2023.1100.0.425  Runtime v2023.1100.0.439)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [] I have attached my Contact Us Package - N/A

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Related to #2059
