### ISSUE TITLE
Feather: Feather Messages not highlighting if the Text Editor is scrolled past a collapsed region

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2066]
### Description
In 2023.8 and 2023.1100.0.425 beta there seems to be an issue with Feather, which doesn't add red underline in place of error, in very specific case.

It happens, if script have at least 45-50 lines, and user would collapse part of code.

It might be connected with fact, that by default with my display and font settings, only 43 lines fit by default on screen, so it seems to happen on a line which is out of screen when whole script is expanded and nothing is collapsed.

### Steps To Reproduce
1. Make constructor, which have two functions, one can be short, but second one need to have about 40-50 lines (might be even comment)
2. Make an error in code, in my example it's `;` inside function argument list (line `46` in attached file)
3. Collapse first function in that constructor
4. While error is displayed in Feather tab, and on Hover, red underscore is gone...

[eee728aa-7501-458c-8f72-69444cbd10cd](https://api.gamemaker.io/api/github/downloads/eee728aa-7501-458c-8f72-69444cbd10cd)

**Comment by gnysek** [comment]
When there's no code collapsed:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/e6ad32cc-a557-4392-a758-5b09ac016f8e)

When any part of code is collapsed:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/cbd95eba-5613-4d08-89f7-4803ac0486d1)

**Comment by zreedy** [comment]
Title slightly misdiagnoses the issue.

For the Release Notes:
Feather Messages not highlighting if the Text Editor is scrolled past a collapsed region.

**Comment by gnysek** [comment]
Fixed, in case that someone would just copy-paste it from list not reading comments 😅

**Comment by zreedy** [comment]
Fixed. Due to limitations in the existing Text Editor's gutter implementation an optimization that was intended to draw the squiggles in a singular draw call was errantly calculating the top line index when a region was collapsed and above the view.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.434  Runtime v2023.1100.0.447. 

Thank you.
