### ISSUE TITLE
Feather: Resetting layout gets rid of the Feather Messages tab until a project is relaunched

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2071]
### Description

When resetting layout even if feather is still enabled, the Feather Messages Window will no longer be shown. Any project will reproduce this issue, no matter if it contains feather errors or not. The issue does not affect the Syntax Tab when feather is disabled.

Related issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/959

### Expected Change

Feather messages tab should be reloaded and the project reparsed

### Steps To Reproduce

1.  Start GameMaker
2.  Open any project
3.  From the Layouts menu >Reset Layout
4.  See the issue
5.  Reload the IDE and re-open the project
6.  Observe the feather messages tab is back
[Feathererrortab.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13215670/Feathererrortab.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (Beta IDE v2023.1100.0.425 Beta Runtime v2023.1100.0.439)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. The default layout specified the Syntax Errors module which was redirecting to Feather but there the Feather Lint Message module was not discovering the assigned tab dock so it always added a new dock tab.
