### ISSUE TITLE
Building Projects: [HTML5] 2023.1100.0.439 runtime does not obfuscate correctly and therefore produces invalid JS

### ISSUE THREAD

**Issue by meseta** [YoYoGames/GameMaker-Bugs#2078]
### Description

Beta 2023.1100.0.439 does not obfuscate HTML5 builds, and produces invalid javascript

### Steps To Reproduce

1. Create a new project
2. Create a new script, containing just the line `global.abc = {}`
3. Make an HTML5 build and observe some unusual output lines
```
Obfuscating...
Unknown identifier in compile_if_weak_ref(move_random
Unknown identifier in compile_if_weak_ref(place_free
Unknown identifier in compile_if_weak_ref(place_empty
Unknown identifier in compile_if_weak_ref(place_meeting
Unknown identifier in compile_if_weak_ref(place_snapped
...
```
4. Open browser console and observe that the following line of generated HTML5 is both unobfuscated, and has an error in it

```js
function gml_GlobalScript_Script1(_inst,_other){global.gmlabc=__yy_gml_object_create(_inst,(.prototype.gml___struct___0=__yy_method(_inst,gml_Script____struct___0)));}
```

[bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13225980/bug.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

HTML5

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
This doesn't seem to be obfuscation related, it just seems to be generating the wrong code. The following is generated

function gml_GlobalScript_Script1( _inst, _other ){
global.gmlabc=__yy_gml_object_create( _inst, (.prototype.gml___struct___0 = __yy_method( _inst, gml_Script____struct___0)));
}

the .prototype throws the error. 

Think this one's for you @rwkay 

[h5test24.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13251913/h5test24.zip)

**Comment by rwkay** [comment]
I am unable to reproduce on the internal version (built locally from the `2023.11.0-main` branch

**Comment by Emc1923** [comment]
Unable to repro either using internal build  IDE v2023.1100.0.431  Runtime v2023.1100.0.445, closing.
