### ISSUE TITLE
gamepad_set_vibration() is not resetting after the user disconnects the gamepad

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GameMaker-Bugs#2084]
### Description

gamepad_set_vibration() is not resetting after the user disconnects the gamepad. So the gamepad just continues to vibrate on its own.

### Steps To Reproduce

1. Use gamepad_set_vibration() and vibrate the gamepad
2. Disconnect the gamepad while its vibrating
3. Gamepad just continues to vibrate on its own.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
We wouldn't get a chance to reset this; we only get the event after disconnection.
