### ISSUE TITLE
Optional Parameter in Constructor is Incorrectly a Boolean

### ISSUE THREAD

**Issue by NanoSharkGames** [YoYoGames/GameMaker-Bugs#2086]
### Description
When creating a struct of a constructor that inherits from a child constructor with both their optional parameters assigned, it treats the optional parameter as a boolean even if the value passed in is not a boolean.

### Steps To Reproduce
1. Create a constructor with an optional parameter set to a value

2. Create a child constructor deriving from the constructor created in Step 1.

3. Assign a value to the optional parameters of the new child constructor & its inherited constructor

4. Create a struct of the child constructor class and pass in a value to it.

5. Set a breakpoint to the line that has the child constructor class was created in.

6. Run the game in debug mode & check the optional parameter's value in the child constructor class

[d0829282-f83d-4dc8-b250-9a017bad7c47](https://api.gamemaker.io/api/github/downloads/d0829282-f83d-4dc8-b250-9a017bad7c47)

**Comment by rwkay** [comment]
You cannot have a default value on the call to the inherited constructor like you are trying here... the compiler is interpreting your argument to the inherited constructor as an expression as `_value == 10` which is `false` as the value you have passed in is `5`.

The default parameter can only be set on the actual constructor.

The syntax you are trying here is not supported at all... and I checked the manual quickly I cannot see anything that might lead you to think that it should.
