### ISSUE TITLE
Feather: GM1041 - variables are seen as undefined if constructor is extended

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2090]
### Description
When `constructor` is extended, all variables which are used to read only (not to write), are hightlighted as Errors `GM1041 Type 'Undefined' where type 'Real' Expected`.

Example code (same as in attached project):
```gml
/// @param {Real} _min
/// @param {Real} _max
function qty_selector(_min = 1, _max = 9999) constructor {
	minimum = _min;
	maximum = _max;
	qty = 1;
	
	static step = function(_way = 1) {
		qty = clamp(qty + _way, minimum, maximum);
	}
	
	non_static_step = function(_way = 1) {
		qty = clamp(qty + _way, minimum, maximum);
	}
}
```
`minimum` and `maximum` would be highlighted as code error if `qty_selector` would be extended even by empty constructor, for example:
```gml
/// @param {Real} _min
/// @param {Real} _max
function small_qty_selector(_min = 1, _max = 99) : qty_selector(_min, _max) constructor {}
```
results in:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/0c4f9298-5251-44db-80bb-de70eccf4db7)

(`qty` is nor hightlighted, as there's write operation to that variable done).

### Steps To Reproduce
1. Run above code or attached example
2. Commenting `: qty_selector(_min, _max)` would make error disappear.

[de486ac1-e8e6-4e67-86c0-e4ffd59a2348](https://api.gamemaker.io/api/github/downloads/de486ac1-e8e6-4e67-86c0-e4ffd59a2348)

**Comment by gnysek** [comment]
Still happens in IDE v2023.1100.0.437  Runtime v2023.1100.0.450.

**Comment by zreedy** [comment]
I've incidentally confirmed this appears regressed while fixing https://github.com/YoYoGames/GameMaker-Bugs/issues/2091
Can this be moved from Triage to .11 milestone and assigned to me?

**Comment by zreedy** [comment]
Fixed. In the Compiler, diving into the base ctor function context was taking the "declaration" path instead of the "ownership" path. Meaning the Compiler was not actually parsing the base ctor's code it just knew that variables existed from TopLevel

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.439  Runtime v2023.1100.0.452
