### ISSUE TITLE
Playing sound assets with the attribute 'Uncompress on Load' will crash the runtime

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#2093]
### Description

Attempting to play a sound with the attribute 'Uncompress on Load - Not Streamed' will crash the runtime due to a memory access violation.

[Contact Us Package](https://github.com/YoYoGames/GameMaker-Bugs/files/13241033/ghb-2093.zip)

### Steps To Reproduce

1. Open and run the example project.
2. The game will silently crash.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2023.1100.0.429 Runtime v2023.1100.0.443

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
- Removed a bad deallocation in YYAL which had been enabled by recent changes to preprocessor defs.

**Comment by mgeddesGM** [comment]
verified in  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
