### ISSUE TITLE
Yoyo-Blog "Beginners Guide to Networking" Has a Mistake

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#2095]
### Description

The Yoyo-Blog Entry "Beginners Guide to Networking" has an error in the section "Detect Client Connection". When the code block for handling a disconnection is added the provided code contains an incorrect line:

ds_map_delete(socketlist, sock);

The sockets are stored in a list and not in a map. So this line of code has to read:

ds_list_delete(socketlist, sock);

### Manual Link

https://gamemaker.io/en/blog/beginners-guide-to-networking

**Comment by iampremo** [comment]
I've updated that now
