### ISSUE TITLE
Particle system editor no longer spawns preview bursts repeatedly, instead doing it just once

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2099]
### Description
When editing an emitter that's set to burst mode in the particle system editor, the preview window no longer spawns bursts repeatedly. It spawns a single burst just once when first setting the mode to burst, and then won't spawn another unless you use the restart animation button. I checked, and on 2023.2, it did burst repeatedly. On 2023.8 and 2023.11, it does not. This makes it a lot harder to edit the particle, since you can't see your changes in real time.

### Steps To Reproduce
Create a particle system asset, set the emitter to burst mode. Observe how the burst will appear once, and then the preview window will show nothing from then on.

[e8884159-a63d-44ad-952a-f64d945f5b6f](https://api.gamemaker.io/api/github/downloads/e8884159-a63d-44ad-952a-f64d945f5b6f)

**Comment by stuckie** [comment]
Can we get a project to see what is being done here?

**Comment by stuckie** [comment]
This is not a bug, the button will re-burst the particle system on purpose so as not to confuse users with a continuous burst that may not happen in-game.
