### ISSUE TITLE
instance_place_list incorrectly marked as a pure function, triggering a feather warning

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2101]
### Description
Instance_place_list will trigger a GM2022 feather warning, saying "Return value of a pure function is not being used." instance_place_list is not actually a pure function.

Looking at GmlSpec.xml, there are also a lot of functions that have ReturnType="Undefined" Pure="true" which is contradictory. These functions don't trigger the feather warning, but the data is still incorrect.
I would list them all, but there's a ton of them. They can be found fairly easily with a search.

### Steps To Reproduce
Call instance_place_list without storing the return.

[12671686-a0d2-4201-9c8a-9d16d0eea3b0](https://api.gamemaker.io/api/github/downloads/12671686-a0d2-4201-9c8a-9d16d0eea3b0)

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.436  Runtime v2023.1100.0.449
