### ISSUE TITLE
[Feather] - `sprite_flush` ind parameter inconsistent with documentation and in-game functionality

### ISSUE THREAD

**Issue by yoshikins** [YoYoGames/GameMaker-Bugs#2106]
### Description

`sprite_flush` according to Feather takes in a String type as its first (only) argument, but it actually takes in a sprite asset reference, according to the latest version of manual.

### Steps To Reproduce

N/A

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.436  Runtime v2023.1100.0.449
