### ISSUE TITLE
Feather: Mouse hover tooltips don't work below the point where a struct is defined.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2108]
### Description
The feather tooltip hover feature refuses to work after the point that a struct has been defined in a piece of code.

### Steps To Reproduce
1) Launch GameMaker.
2) Open the attached project.
3) Look at the Create event of object oTest. 
4) Hover over the MyTestFunction definition on line 11 and observe the feather tooltip appear.
5) Notice the same thing with the function call on line 15 and the structure name on line 17.
6) Now try hovering over the function call on line 30 and the 2nd structure definition name on line 32. 
7) Observe no tooltips appear on those.

[c24c4097-d43d-4d46-826e-f720e156392c](https://api.gamemaker.io/api/github/downloads/c24c4097-d43d-4d46-826e-f720e156392c)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.435  Runtime v2023.1100.0.448
