### ISSUE TITLE
Websocket-Handshake Doesn't Work

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#2109]
[Bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13259421/Bug.zip)
### Description

In 2023.8 you cannot establish a connection between client and server on a websocket basis (network_type_ws).

The server console output reads:

Client(1) Connected: ::ffff:127.0.0.1
WARNING: Discarding malformed data on socket 1 - are you mixing raw/non-raw network APIs?

The exact same project works fine in GM 2023.4.

### Steps To Reproduce

1. Start the attached demo project in two IDEs
2. Run the program with the Windows target and start the server (left-click)
3. Run the program with the HTML5 target and start the client (right-click)
4. Watch the console output of the IDE that started the server
5. The connection will not be created and the server output will read "Discarding malformed data".

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by vitawrap** [comment]
still broken in 2023.11.1.129 (same platforms, HTML and Windows)

**Comment by TheGitMagician** [comment]
Can confirm - still broken. Need this fixed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.461  Runtime v2024.200.0.477, thanks.

**Comment by vitawrap** [comment]
It seems an HTML5 app communicating to a native app with websockets hangs the server after an albeit successful handshake now...

**Comment by yoyo-danielc** [comment]
> It seems an HTML5 app communicating to a native app with websockets hangs the server after an albeit successful handshake now...

Can you supply a test project for this? Using the project from https://github.com/YoYoGames/GameMaker-Bugs/issues/4363#issuecomment-1893551189, the HTML5 client connects to the server running under Win32, they exchange a couple of messages and both continue to run - the server can still respond to further connections.

**Comment by vitawrap** [comment]
> > It seems an HTML5 app communicating to a native app with websockets hangs the server after an albeit successful handshake now...
> 
> Can you supply a test project for this? Using the project from [#4363 (comment)](https://github.com/YoYoGames/GameMaker-Bugs/issues/4363#issuecomment-1893551189), the HTML5 client connects to the server running under Win32, they exchange a couple of messages and both continue to run - the server can still respond to further connections.

ah on the test project actually works if i replace all map accesses with `ds_map_find_value`. this was probably a codegen issue.
