### ISSUE TITLE
repeat(-infinity) does 0 iterations on VM, infinite iterations on YYC

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2110]
### Description
While there's never really a reason to do repeat(-infinity) directly, I'm using a collision_line_point function that calls 
```repeat (ceil(log2(point_distance(x1, y1, x2, y2))) + 1)```
Which can sometimes result in -infinity. On VM, my game runs just fine, but on YYC, I get infinite loop freezes when this function is called in situations that can result in -infinity.

### Steps To Reproduce
repeat(-infinity) {}
This will do nothing on VM, and freeze the game in an infinite loop on YYC.

[19b90749-ce59-470e-809e-bee285e82df1](https://api.gamemaker.io/api/github/downloads/19b90749-ce59-470e-809e-bee285e82df1)

**Comment by rwkay** [comment]
Fixed in 2023.11
