### ISSUE TITLE
In-Game: [GX.games] Unable to access Included Files in 2023.1100 Beta 1 runtimes

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#2119]
### Description

Unable to access any Included File on GX.games .

### Steps To Reproduce

1. Start GameMaker
2.  Load the project from https://github.com/YoYoGames/GameMaker-Bugs/issues/1801
3. Target GX.games and Run
4. See the issue - the sprite does not load

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by Emc1923** [comment]
Verified in  IDE v2023.1100.0.434  Runtime v2023.1100.0.447
