### ISSUE TITLE
In-Game: [Switch] Returning to the Home menu causes audio to cut out temporarily when resuming the game

### ISSUE THREAD

**Issue by Dopply** [YoYoGames/GameMaker-Bugs#2130]
### Description
Opening the Switch home menu will consistently cause all audio to cut out/freeze for a period of time before resuming.

This is verified with audio_debug overlay, where the waveforms are frozen for the same amount of time as the audio freeze.

### Steps To Reproduce
Open the home menu anywhere in game, wait one-two seconds, and resume. Audio will cut completely for a few seconds before resuming.

You may also rapidly open the home menu to reproduce this error.

[5ffaeb82-6956-4e78-893a-5ec21cdc8b68](https://api.gamemaker.io/api/github/downloads/5ffaeb82-6956-4e78-893a-5ec21cdc8b68)

**Comment by toby-yoyo** [comment]
Sounds like this might be the same issue as [Nintendo Switch audio hiccups when suspending/resuming](https://github.com/YoYoGames/GameMaker/issues/3030).

**Comment by jackerley** [comment]
@Dopply There is a fix that went in for the linked issue, it will be in the next November beta

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.439  Runtime v2023.1100.0.452, thanks.
