### ISSUE TITLE
Install: [Mac IDE] Unexpected "Application Oven" and "YoYo Runner" icons appear in the LaunchPad app

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#2135]
### Description

After a clean GM (Stable+Beta) install on macOS Monterey I got all of these items added to the App Launcher:

![image](https://github.com/YoYoGames/YoYoStudio/assets/15669932/16a83646-825d-4bb0-883c-c59f929c1e54)

### Expected Change

The YoYo Runner and Application Oven are not added to App Launcher

### Steps To Reproduce

1. Install any recent version of GM on a Mac (this issue has been the case for a long time)
2. Open the system's Launchpad app
3. Observe several GM binaries have been added there as shortcuts

**Comment by SamTHodson** [comment]
Verified in IDE v2023.1100.0.447  Runtime v2023.1100.0.456

**Comment by jmg-duarte** [comment]
As a workaround, the following program (free version) worked for me.
https://launchpadmanager.com/home.php

**Comment by shamusl** [comment]
I am also having this issue on macOS.

**Comment by LukeBrownYoYoGames** [comment]
Adding to pipeline project
