### ISSUE TITLE
gamemaker loses "self" arrays in a constructor

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#2136]
### Description
trying to access an array using "self." in a constructor function causes gamemaker to fail to be able to find the array ("unable to find any instance for object index ...")

this only happens if you prefix the instance variable on Line 11 with "self.", if you omit it it works just fine

i only see one difference in the generated bytecode, in that the working version (without the "self.") generates this:

    000000bc : ffff0f84                 pushi.e   -1
    * 000000c0 : f9ff05c1080000a0         pushl.v   $i$
    000000c8 : 00002507                 conv.v.i
    000000cc : 000005c004000000         push.v    $preset_frame_rates$
    000000d4 : f9ff05c1060000a0         pushl.v   $max_refresh_rate$

but the broken one (with the "self.") generates this:

    000000bc : ffff0f84                 pushi.e   -1
    * 000000c0 : 040005c0080000e0         push.v    $i$
    000000c8 : 00002507                 conv.v.i
    000000cc : 000005c004000000         push.v    $preset_frame_rates$

this broke somewhere between 2023.1100.0.439 and now; in 439 the bytecode looks a little different:

    000000bc : 000002d90b000000         call.i    $@@This@@$
    000000c4 : f7ff0f84                 pushi.e   -9
    000000c8 : f9ff05c1080000a0         pushl.v   $i$
    000000d0 : 00002507                 conv.v.i
    000000d4 : 000005c004000000         push.v    $preset_frame_rates$

on the YYC it fails to compile at all with the "self.", complaining about a malformed variable reference; in GMRT it's fine

i know there were supposed to be some changes made recently regarding optimizing variable lookups, I wonder if this could be a byproduct of that

### Steps To Reproduce
run the example project in VM, it'll crash

run the project in YYC, it wont compile

run the project in GMRT, it'll be fine

[0ff4fdba-abbc-441d-abf3-c3b5f737facd](https://api.gamemaker.io/api/github/downloads/0ff4fdba-abbc-441d-abf3-c3b5f737facd)

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.436  Runtime v2023.1100.0.449
