### ISSUE TITLE
Feather: similar preferences are too far away

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2137]
### Description
There are 2 new settings in 2023.11:

- do not analyze room instances
- do not analyze project for Room Instances with auto-generated names

In previous beta (with missing translations) they were close to each other, but now they are divided by 5 other settings. I believe they should be close to each other.

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/b16da75b-1a5e-4bd3-a084-66dbbc2ab805)

[3f3ac467-4cc1-44de-b9e6-dfff49ec49be](https://api.gamemaker.io/api/github/downloads/3f3ac467-4cc1-44de-b9e6-dfff49ec49be)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.439  Runtime v2023.1100.0.452
