### ISSUE TITLE
Code Editor: Snippets shortcut gets stuck active after using one time in Nov23 Betas

### ISSUE THREAD

**Issue by MissingNoo** [YoYoGames/GameMaker-Bugs#2139]
### Description
after pressing F4 and one of the shortcuts, the desired snippet is added to the code, but it stays stuck in a way that if any other number or shortcut is pressed, another snippet gets added even without opening the snippets menu

### Steps To Reproduce
Press F4, press a snippet hotkey, press it again

[de58dc75-ac0c-44cc-904d-fe88762c2bcd](https://api.gamemaker.io/api/github/downloads/de58dc75-ac0c-44cc-904d-fe88762c2bcd)

**Comment by SmithTom6304** [comment]
Fixed. Hotkeys were not being unregistered properly in the TextEditorManager ContextMenu, and so were persisting after the menu was closed. Hotkeys are now registered when the Menu is opened and unregistered when closed - this applies to submenus as well, so the hotkeys are only activated once the submenu is opened.
