### ISSUE TITLE
Asset Browser: Preview images for Sprites do not update when using the Image Editor in Nov23 Beta

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#2142]
### Description

When editing a Sprite via the Image Editor, the image preview in the Asset Browser will not update following any changes until the Image Editor is closed. This differs from Aug23.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/53d9dfac-d5b5-4639-a0d3-2ccd706d3d29)

Tested using Beta IDE v2023.1100.0.435  Runtime v2023.1100.0.448.

[Contact Us Package](https://drive.google.com/file/d/1WbJgObkJiKIrbcmPeafnoGYafvdgoLT-/view?usp=sharing)

### Expected Change

The image preview should update accordingly with any changes made in the Image Editor.

### Steps To Reproduce

1. Start GM Beta and open/create a project
2. Create/open a Sprite in the Image Editor
3. Have the Sprite visible in the Asset Browser
4. Edit the Sprite in any way
5. Observe the image preview does not update in the Asset Browser
6. Close the Image Editor
7. Observe the image preview has now updated

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11, Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Issue caused by recent optimisation to suppress icon rebuilding while editing image; fixed to only suppress icon regen while actually drawing.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.438  Runtime v2023.1100.0.451, thanks.
