### ISSUE TITLE
Multi-Caret selection doesn't work

### ISSUE THREAD

**Issue by HannulaTero** [YoYoGames/GameMaker-Bugs#2143]
### Description
It seems multi-caret selection and editing doesn't work in the current Beta build _(IDE v2023.1100.0.435, Runtime v2023.1100.0.448)_. This does work in Monthly build _(IDE v2023.8.2.108, Runtime v2023.8.2.152)_.
What I mean, is ability to hold ALT, and select area from multiple lines and edit them at same time. 
So I am asking to return the multi-caret selection and editing in the code editor.

### Steps To Reproduce
1. Open GameMaker code editor
2. Write multiple lines of code
3. Hold ALT and try select area.
4. See the issue

[c98334fe-9fca-4629-8953-3cc09a592734](https://api.gamemaker.io/api/github/downloads/c98334fe-9fca-4629-8953-3cc09a592734)

**Comment by SmithTom6304** [comment]
Fixed. Mouse button modifiers weren't being applied correctly since we started storing Key events as their left/right versions.
