### ISSUE TITLE
Feather box or auto correction don't work correctly inside functions

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2145]
### Description
I have a state systems that uses local constructors so I'm using a lot of calls inside the functions, 
but feather has an issue of not showing correct info box of variables outside of functions,
current beta kinda fixed that issue but its still bugged.

When I try to edit my local constructors inside my object via function the auto correction nor feather doesn't work, it just shows wrong info.
But if I summon that constructor outside of the function, or sometimes inside the function works as well, it really is just bizarre.
Auto correction and feather will work just correctly... It is so bothersome.

These images shows, what feather shows me when I hover over my constructor variable.
The first image is the wrong one, second one is what feather actually is supposed to do.

[a65235c9-a74d-42e8-b079-95b4d1577e11](https://api.gamemaker.io/api/github/downloads/a65235c9-a74d-42e8-b079-95b4d1577e11)

**Comment by zreedy** [comment]
Would you be able to attach a project file to this? I think I understand the issue with the provided screenshots but I cannot debug this without the associated project files.

**Comment by Koyan61** [comment]
Sorry late I didn't see it sooner. Here is the updated version of my report with the attached project.
https://github.com/YoYoGames/GameMaker-Bugs/issues/2360

**Comment by YYDan** [comment]
As mentioned above, a new copy of this report was filed, so closing this one.

Thanks!
