### ISSUE TITLE
Asset Browser: [Windows IDE] When duplicating an imported sprite the image preview won't appear until clicking on the duplicated sprite

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2147]
### Description

When duplicating an imported sprite from the Asset Browser the preview won't appear until clicking on the duplicated sprite. This doesn't seem to be happening with sprites created inside GameMaker, only imported. 

Additionally, observe that in Stable (v2023.8.2.108)  the new sprites take a while to be saved (this issue is not present on 2023.11 Betas).
[duplicatesprite.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13309027/duplicatesprite.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create or open any project
3. Create a new sprite
4. Import an existing image using the file explorer
5. Duplicate the sprite created from Asset Browser using Ctrl+D / right-clicking on it and selecting 'Duplicate'
6. Observe the preview won't appear until clicking on the duplicate sprite

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/d0d313b7-d54d-4269-8741-bb2ff8b91642)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (Beta IDE v2023.1100.0.435 Beta Runtime v2023.1100.0.448)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Icon should now update in the asset browser without having to click away

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.439  Runtime v2023.1100.0.452
