### ISSUE TITLE
Output Window: Incorrect Page Up/Down behaviour

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2150]
### Description

In Beta IDE v2023.1100.0.435 Beta Runtime v2023.1100.0.448, page up / page down is not working correctly in the Output Window.
- With the Find and Replace window closed, Page Up correctly moves the cursor to the beginning of the document, but Page Down has no effect.
- With the Find and Replace window open and focused, neither page up or page down have any effect on the Output Window - they are both swallowed by the Find and Replace text box.

### Expected Change

Page Up / Page Down should move the cursor to the beginning / end of the Output Window document. The Find and Replace textbox should not consume the Page Up / Page Down shortcut.

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Begin building and then stop, to generate some text in the Output Window
4. Place your cursor in the window and ensure Find and Replace is not open
5. Press Page Up. Observe the cursor correctly moves to the start of the text.
6. Press Page Down. Observe the cursor does not move.
7. Open the Find and Replace window, default Control + F.
8. Make sure the Find and Replace window is focused.
9. Press Page Up. Observe nothing happens.
10. Press Page Down. Observe nothing happens.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Contact us package - [page_up_page_down.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13311038/page_up_page_down.zip)

**Comment by SmithTom6304** [comment]
Fixed issue with Page Down and Page Up + Select having incorrect modifiers.
Passing PageUp/PageDown commands through to the Output Window isn't possible with the current TextEditor setup, but may be possible with the upcoming text editor update.

**Comment by sihammill** [comment]
Fix verified in IDE v2023.1100.0.440  Runtime v2023.1100.0.453
