### ISSUE TITLE
Engine stuck in "Analyzing Project" mode

### ISSUE THREAD

**Issue by xandersauce** [YoYoGames/GameMaker-Bugs#2152]
### Description

The IDE crashed. When I opened it back up, it asked me to send a crash report, so I did. Once I opened my project, the IDE was locked in "Analyzing Project" mode. The progress bar fills up to about 30% and stops there.

I can click to run the game, but after waiting for 02:11:03, I don't think it's ever going to run. I tried restarting my computer, redownloading the engine, and duplicating the project, but the problem is still there. if I Frankenstein the files to a new project, it does the same thing.

After more experimentation, I have found that one of three things can happen now if I open **any** of my game maker projects:
1. it runs the "analyzing project" routine and completes
2. it runs the "analyzing project" routine and crashes
3. it runs the "analyzing project" routine and softlocks

-- project added to internal drive - https://drive.google.com/file/d/1hSmsGDb8efsMMW6K_zg6nv1JA6TQn3F7/view?usp=drive_link --

### Steps To Reproduce

I do not know how to replicate the bug. 

### How reliably can you recreate this issue using your steps above?

Only Ever Happened Once

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This was caused by both objects in that project referencing themselves in it's parentObjectId somehow.
The project is also incomplete as it references many other resources that are not there, but assume this is because it is a cut-down sample project.

**Comment by cameron-home** [comment]
Project opens without issue in IDE v2023.11.0.120  Runtime v2023.11.0.157 so closing.
