### ISSUE TITLE
application_surface resizing based on gui size

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2155]
### Description

On `application_surface` manual page, example says:

```gml
surface_resize(application_surface, display_get_gui_width(), display_get_gui_height());
```

But that's not best example, as even same page says:
> Other Draw events (like Pre/Post Draw and Draw GUI) do not draw on the application surface.

So why would anyone want to set surface to same size as GUI, rather than view/camera/window ?

### Manual Link

https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Drawing/Surfaces/application_surface.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed. Thanks for the report :)
