### ISSUE TITLE
shift+click doesn't work in the IDE anymore

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#2156]
### Description
in the asset browser and code editor, clicking on something and then shift+clicking something else used to select the entire range between the previous and current selections; it no longer does this

i've also observed this in a few other places, such as in the text entry boxes in this bug reporter, so it probably also affects a lot of other areas in the IDE where shift+click used to do things

### Steps To Reproduce
open any project, shift+click anywhere you would expect the standard UI navigation features to work

[ee506513-b149-4002-adb4-501c7af1069d](https://api.gamemaker.io/api/github/downloads/ee506513-b149-4002-adb4-501c7af1069d)

**Comment by SmithTom6304** [comment]
Fixed. Mouse button modifiers weren't being applied correctly since we started storing Key events as their left/right versions.
