### ISSUE TITLE
Debugger: Watch list does not match Room Editor inst_* values on subsequent runs

### ISSUE THREAD

**Issue by ParodyKnaveBob** [YoYoGames/GameMaker-Bugs#2166]
### Description
Instances placed in the Room Editor have listed names which can be used for reference throughout code with consistent results.

The Debugger, however, when testing a game more than once, reads these names with changed values, disrupting the Variables Watch list.

To demonstrate, I've attached a sample project and three sequenced screenshots.

The sample has one object with two instances placed by hand into one room, renamed `inst_left` and `inst_right`. The room's creation code creates two more instances a little lower on the screen. Each instance draws the ID of `inst_left` and `inst_right` plus its own id, demonstrating the runner gets it all correct. However, upon test-running more than once, you can observe the numbers stay the same in the runner but advance in the Debugger.

My screenshots show the consequences in the Debugger:
1st. `inst_left` and `inst_right` test normally
2nd. `inst_right` now reads from a different instance altogether
*(not pictured, but `inst_left` reads from no instance and thus claims to be invalid)*
3rd. neither `inst_left` nor `inst_right` read from a valid instance anymore

Upon closing the project/IDE and reopening, the Debugger resets this unexpected tallying.

### Steps To Reproduce
1. Start GameMaker.
2. Open a new project (or use an old one) with an instance placed by hand into a room.
3. Run it in Debug Mode.
4. Watch an instance in the Debugger via its Room Editor name.
5. Quit test game normally.
6. Run it in Debug Mode again.
7. See issue.

[931a5234-58d3-4381-9677-dae421ac00de](https://api.gamemaker.io/api/github/downloads/931a5234-58d3-4381-9677-dae421ac00de)

**Comment by ParodyKnaveBob** [comment]
GMC thread - currently **probably** no extra info that's relevant
https://forum.gamemaker.io/index.php?threads/debugger-watch-list-unable-to-evaluate.106918/

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.451  Runtime v2024.200.0.461. 

Thank you
