### ISSUE TITLE
In-Game: sprite_collision_mask() on a sprite added via sprite_add() causes crashes on Android 12+

### ISSUE THREAD

**Issue by COWCATGames** [YoYoGames/GameMaker-Bugs#2168]
### Description

Using sprite_collision_mask() on an external (datafile) loaded file via sprite_add() or a duplicated sprite, to set the sprite with precise collisions, always crashes when using an Android device with version 12 or more (I think it also happens on Android 11, but not on older versions)

Checked with LTS 2022.0.2.51 and the latest Beta (I need this fixed for the LTS), tested with several Android devices.

Test project attached
[TestAndroidCrash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13325193/TestAndroidCrash.zip)

### Expected Change

No crash

### Steps To Reproduce

These two lines:

var spr = sprite_add("spriteext.png", 1, false, false, 0, 0);
sprite_collision_mask(spr, false, 1, 0, 0, 0, 0, 0, 0);

Result in a crash.

[TestAndroidCrash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13325194/TestAndroidCrash.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS), Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by COWCATGames** [comment]
Thanks for fixing it (apparently), will it be added to the next batch of fixes for the next LTS version though?
Best

**Comment by jackerley** [comment]
@COWCATGames  It has been tagged for the next LTS release, as a workaround I think you won't have any problems if your sprites width is a multiple of 8

**Comment by mgeddesGM** [comment]
verified as of IDE v2023.1100.0.439  Runtime v2023.1100.0.452
