### ISSUE TITLE
Google Dynamic Asset Delivery (PAD) Not Works For Dynamic Texture Pages Black Screen AAB

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GameMaker-Bugs#2171]
### Description

When I enabled the Google Dynamic Asset Delivery (PAD) and uploaded AAB to play store, users who downloaded the game from the play store saw just a flickering black screen after the splash screen.

I debugged the issue and found that the game was still running under the black screen. So Play Asset Delivery works as intended but something is preventing things to draw. Then I tried setting dynamic texture pages to default again. The problem solved.

So *dynamic texture pages* are not loading when we use Play Asset Delivery.

(Sorry for the multiple bug reports, I was struggling with this issue for days. I just found the reason. I deleted my old bug reports because they were misleading. Thank you for reading this.)

### Expected Change

Google Dynamic Asset Delivery (PAD) Work Again For Dynamic Texture Pages Too

### Steps To Reproduce

1. Enable Google Dynamic Asset Delivery (PAD)
2. Make texture page types to dynamic
3. Export AAB
4. Upload it to the Play Store (Optional)
5. Download it from the Play Store or use BundleTool
6. See the flickering black screen

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.11.0.120  Runtime v2023.11.0.157

**Comment by mgeddesGM** [comment]
verified as of lts  IDE v2022.0.3.65  Runtime v2022.0.3.78
