### ISSUE TITLE
Using | to set multiple types for a function argument with JSdoc is not mentioned in the manual 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2174]
### Description
It's possible to use | to set multiple types for a function argument in JSdoc, such as
```/// @param {String|Array} ```
However, this is not mentioned in the manual page for JSdoc script comments.
https://manual.yoyogames.com/index.htm#t=The_Asset_Editors%2FCode_Editor_Properties%2FJSDoc_Script_Comments.htm

### Steps To Reproduce
I read the manual page for JSdoc script comments carefully, and saw no mention of this functionality.

[b40f55bd-0312-4447-a64c-d435456512a4](https://api.gamemaker.io/api/github/downloads/b40f55bd-0312-4447-a64c-d435456512a4)

**Comment by yoshikins** [comment]
Noticed this too. I didn't know you could use a pipe for multiple types for a function parameter/return value. Commas work too as that's what I use, I think that should also be mentioned. There may even be more ways to define these, that aren't mentioned in the manual

**Comment by PrismaticRealms** [comment]
Yes, I learned about using the pipe character to define multiple param types in JSDocs from other resources on the web.  Not sure if the fact that this is missing from the GM docs means that it isn't officially supported.  The pipe character does introduce a conflict with the custom snippet system as the pipe characters are used there to define the text that will be selected once the snippet is inserted into your code.  I'll open a separate bug for this.

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
