### ISSUE TITLE
Network data events do not set buffer correctly in 2023.1100.x

### ISSUE THREAD

**Issue by yoyo-danielc** [YoYoGames/GameMaker-Bugs#2175]
### Description

The buffer in the async event is always zero, no matter what buffer was actually allocated internally to hold the data. This leads to several issues:

- "Illegal Buffer Index 0" crashes when handling the event.
- Accessing the wrong buffer when handling the event.
- Memory corruption from buffer 0 being free'd multiple times.
- Memory leaking from the actual allocated buffer not being destroyed.

[message_crash.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13328462/message_crash.zip)

### Steps To Reproduce

To reproduce, either receive data when a buffer already exists (so the next buffer isn't zero), or receive several messages in the same tick. Attached sample should print "Received message: Message {1,2,3}" to the console, but crashes in the beta.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows, Ubuntu

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.443  Runtime v2023.1100.0.454

**Comment by kenan238** [comment]
This also happens to me as of IDE v2023.8.2.108 Runtime v2023.8.2.152
