### ISSUE TITLE
Strange but "intended" string template behavior

### ISSUE THREAD

**Issue by coyo-t** [YoYoGames/GameMaker-Bugs#2178]
### Description

String templates (IE `$"{var1} {var2}"`) are syntactic sugar boiled down to `string("{0} {1}", var1, var2)`, the syntax within the braces taken verbatim

However, this means bizzare-seeming behavior such as *this* can occur:
`show_debug_message($"{pi, tau} {1}")` will result in `3.14 6.28 ` being printed, as the former is translated into `show_debug_message(string("{0} {1}", pi, tau, 1))` (extranious arguments to `string` are ignored, but still included)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/22027276/df182b6d-af08-4e7b-826c-c2a50d5833f2)
(Code from decompilation of the above)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/22027276/05e5d853-5f08-4a37-806b-b68da0720f88)

I'm not even sure if this counts as a bug? It *is* the language working as "intended". I've just filed this under "IDE Bug Report" because I can't figure out where this should fit otherwise.

It at the very least should be clarified that this is what happens under the hood for string templates in the documentation.

(Required Contact Us Package)
[pk.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13331541/pk.zip)

### Steps To Reproduce

See above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.11
