### ISSUE TITLE
Select text in the IDE using shift+click

### ISSUE THREAD

**Issue by solemnwarning** [YoYoGames/GameMaker-Bugs#2183]
### Is your feature request related to a problem?

In pretty much all text editors and input fields, clicking a point while holding shift moves the cursor and also selects any text between the original cursor position and the new cursor position, in the GM IDE it just moves the cursor. Its useful to be able to select a block of text like that and in my muscle memory of "how text input works".

### Describe the solution you'd like

Select the applicable text when shift is held.

**Comment by SmithTom6304** [comment]
Issue was likely caused by a previous Keyboard Shortcut Refactor bug - Shift + Click selection is working again since at least IDE v2023.1100.0.438  Runtime v2023.1100.0.451

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.439  Runtime v2023.1100.0.452.

Thank you

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2156
