### ISSUE TITLE
Errors in the correct code

### ISSUE THREAD

**Issue by MainPlay-YT** [YoYoGames/GameMaker-Bugs#2185]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/73584843/02d88e58-8252-4ff2-ae6f-55fa861bb416)

### Steps To Reproduce

1. Start GameMaker
2. Open project [Mine-imator-1.2.9](https://github.com/stuffbydavid/Mine-imator/archive/refs/heads/1.2.9.zip) 
3. Run project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
All feedback will always be here, not on other social medias.

**Comment by MainPlay-YT** [comment]
Okay, I'll remove the links now
How to solve this problem?

**Comment by rwkay** [comment]
The problem is that your code was correct in older versions of GameMaker but it uses a function called `new` and that is now a reserved keyword (since v2.3 when functions and other modern idioms were introduced), the errors are to do with the expected syntax for the `new` keyword.

**Comment by MainPlay-YT** [comment]
> ошибки связаны с ожидаемым синтаксисом для `new` ключевого слова.
И на что его заменить? Или может скачать старую версию GMS?

**Comment by rwkay** [comment]
just rename your function `new` to something else and fixup that calls for it.

**Comment by MainPlay-YT** [comment]
> just rename your function `new` to something else and fixup that calls for it.

Fine. Although I don’t know this programming language at all, I think my experience in Python will help me. Almost all programming languages ​​are somewhat similar to each other
