### ISSUE TITLE
variable_clone mutates strings

### ISSUE THREAD

**Issue by Vanderslice** [YoYoGames/GameMaker-Bugs#2192]
### Description

IDE Version: v2023.4.0.84
Runtime Version: v2023.4.113

Note: Can't update versions on this machine to test due to a version restriction on my main project but I wasn't able to find an open or closed bug referring to this issue or mention of it being fixed in the patch notes.

Description:
- Using variable_clone on a string or on a struct containing a string value mutates the string.

Expected Results:
- String should be the same as before using variable clone on it.

Actual Results:
- String will now be different and generally include encoding errors

### Steps To Reproduce

From Scratch:
1. Start GameMaker
2. Create an object
3. Add an instance variable in the Create of the object that contains a string
4. variable_clone the string and assign it to the previously created variable (It can actually be any variable)
5. Put an instance of the object in the Room 0
6. Debug and inspect the variable containing the string's value

From Test Project:
1. Start GameMaker
2. Open the variable_clone_test project
3. Run the game
4. You'll see the string and the string from a struct printed in the upper left hand of the gui
5. Press "T" to variable clone the string
6. The string values will be updated and draw_text will now be drawing the new mutated string (Possibly nothing because of the encoding errors)

[variable_clone_test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13340929/variable_clone_test.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Couldn't reproduce!! (this was a bug back in v2023.4.113 that has been fixed for quite some time now)
