### ISSUE TITLE
In-Game: variable_clone() turns methods in an array into structs, which can crash games

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#2195]
### Description
variable_clone() on an array that contains any methods, seems to just turn them into a struct. 
Whereas it should just carry over/create a new method with a different scope.

### Steps To Reproduce
1. Download and run project
2. See output, starting from `===START===` for all of the checks. (`typeof` + `is_method`)

[f304ef73-7e39-4936-8a33-218dedfb2258](https://api.gamemaker.io/api/github/downloads/f304ef73-7e39-4936-8a33-218dedfb2258)

**Comment by tabularelf** [comment]
Should also note: Calling these *will* cause the game to crash as well, so these are definitely considered as structs.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.443  Runtime v2023.1100.0.454
