### ISSUE TITLE
Sprite Editor: Spine previews have inverted colours in Nov23 Betas

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2198]
### Description
This is a new bug on Beta, the colors are not inverted on stable. The colors also appear correctly at runtime, it's only wrong for the preview.

On beta (2023.11), IDE:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/333e119d-64e0-45bd-8fa5-9d400672ebc6)

On beta, when running the game:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/81a3dd95-0d68-4aba-be79-12892f755a12)

On stable (2023.8), IDE:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/736cce71-7b58-4e9b-bb3e-ea181ec5bbd6)

### Steps To Reproduce
Import a spine sprite, see that the colors are inverted in the IDE. Run the game and see the colors displaying correctly.

[b485cfa6-9560-48f3-9c4c-2cadf041a9e3](https://api.gamemaker.io/api/github/downloads/b485cfa6-9560-48f3-9c4c-2cadf041a9e3)

**Comment by yymrennie** [comment]
Fixed in 2023.11

**Comment by YYDan** [comment]
To be clear, this does not work correctly in 2022.8 either:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/d2771d97-3fb3-45db-8a58-b678a4a1bfd0)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.439  Runtime v2023.1100.0.452, thanks.
