### ISSUE TITLE
Can't download manual

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#2203]
### Description
Middle mouse clicking on a GM function to bring up the GM manual prompts me to download it and then fails to do so.

### Steps To Reproduce
- Middle mouse click on a GM function
- Accept to download GM manual
- Witness failure

[28c44812-6c85-450a-b2dc-b6a7d5a34d94](https://api.gamemaker.io/api/github/downloads/28c44812-6c85-450a-b2dc-b6a7d5a34d94)

**Comment by LukeBrownYoYoGames** [comment]
Fixed in Manual-Release: 890102267175c4b8d2867c02b07cebdf7ebc5481
