### ISSUE TITLE
One command used for building the Linux AppImage is missing a path, leading to build failure.

### ISSUE THREAD

**Issue by vypxl** [YoYoGames/GameMaker-Bugs#2204]
### Description

GameMaker Beta 2023.1100.0.435-1

Just trying to build any project, even an empty one leads to this.

I am trying to use the GameMaker Beta on Arch Linux (I know it's not a supported platform). After a lot of trial and error, I got it to run and compile an empty project. I followed the [guide](https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu) on installing for Ubuntu. 
This issue could also happen on Ubuntu systems, given that, for some reason, they do not have `/bin/` in their `PATH`.

During building, I encountered that one command used throws the error `chroot: failed to run command ‘sh’: No such file or directory`.

The problem I found lies in the command that invokes `linuxdeploy`. 
The command GMS runs is:

```bash
/bin/bash -c 'unshare -mUprf sh -c \'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin:/tmp/squashfs-root/usr/bin/" NO_STRIP=1 chroot "$2" sh -c "cd /tmp/ && linuxdeploy -v0 --appdir=AppDir/"\'  -- /home/user/GameMakerStudio2/vm/Game /opt/steam-runtime'
```

This fails at two different points. First, it can't find `sh` in the chroot, then linuxdeploy tries to invoke `lld`, which invokes `cat`, which is not found, leading to failure. Both of these programs are found in `/opt/steam-runtime/bin/`, however, this path is **not** included in the `PATH=` segment of the command above.

I understand that the command works on the specific version of Ubuntu that it was tested on and developed for. However, I think adding the path is a simple change that would allow people to run GMS on other Linux distributions, making it more platform agnostic.

The updated command would look like this:

```bash
/bin/bash -c 'unshare -mUprf sh -c \'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin:/bin/:/tmp/squashfs-root/usr/bin/" NO_STRIP=1 chroot "$2" sh -c "cd /tmp/ && linuxdeploy -v0 --appdir=AppDir/"\'  -- /home/user/GameMakerStudio2/vm/Game /opt/steam-runtime'
```

A possible workaround is modifying the steam runtime.
Just copying `sh` and `cat` into `sbin` works.

```bash
sudo cp /opt/steam-runtime/bin/sh /opt/steam-runtime/sbin/
sudo cp /opt/steam-runtime/bin/cat /opt/steam-runtime/sbin/
```

Another workaround is just adding `/bin` to the global `PATH` or just to the environment for GameMaker.

### Steps To Reproduce

1. Remove `/bin/` from your `PATH` environment variable
2. Start GameMaker
3. Try to run any project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Going from the commit message, we now explicitly use /bin/sh for the entry point into the chroot and set up an appropriate PATH inside that shell. We still add sbin directories to the PATH outside of the chroot in the hope of finding the host chroot binary.

**Comment by expected-ingot** [comment]
Still a problem on latest (2024.1100.0.654) Ubuntu beta:
```

/bin/bash DONE (0)
/bin/bash -c 'unshare -mUprf sh -c '\''mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" NO_STRIP=1 chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'\''  -- /home/user/GameMakerStudio2/vm/ccc_GM2 /opt/steam-runtime'

chroot: failed to run command ‘/bin/sh’: No such file or directory

System.Exception: command 'unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" NO_STRIP=1 chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'  -- /home/user/GameMakerStudio2/vm/ccc /opt/steam-runtime' failed with exit status 127
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.BuildAppImage(String work_dir, String exe_path, String assets_zip_path, String projectName, Boolean package)
   at Igor.LinuxBuilder.Run()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Igor complete.
elapsed time 00:01:13.1678339s for command "/home/user/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1100.0.680/bin/igor/linux/x64/Igor" -j=8  -options="/tmp/GameMakerStudio2-Beta/GMS2TEMP/build.bff" -v -- Linux Run started at 10/27/2024 21:11:49
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.```

I also use Arch Linux.

**Comment by expected-ingot** [comment]
Fixed it! Just run this https://forum.gamemaker.io/index.php?threads/tl-dr-the-easy-way-to-install-runtime-dependencies-for-ubuntu.97868/ (or get the steam runtime)
