### ISSUE TITLE
Room Editor: Some Tile Layer shortcuts are not working

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2209]
### Description

In beta IDE v2023.1100.0.438  Runtime v2023.1100.0.451, some toolbar shortcuts in tile layers have stopped working. While some display a combo and can be triggered via shortcut, others have no combo and also cannot be triggered.

The following tools have no shortcut:
- Pen
- Eraser
- Fill
- Line
- Autotile
- Flip
- Mirror
- Rotate

The following tools have shortcuts and are working correctly:
- Rectangle
- Select Tiles
- Tile Inheritance

[TileLayerShortcuts.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13362827/TileLayerShortcuts.zip)

### Expected Change

All tools should have their combos appear on hover, and trigger when the correct hotkey is pressed.

### Steps To Reproduce

1. Start GameMaker
2. Open a tile layer in the room editor
3. Focus the tile layer view by selecting the pan area
4. Hover over the Eraser tool in the toolbar
5. Observe there is no hotkey listed
6. Press the default hotkey to select the eraser (E)
7. Observe nothing happens
8. Hover over the Rectangle tool
9. Observe the default hotkey is listed (R)
10. Press R And observe the Rectangle tool is selected

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Fixed - some old hotkeys were using raw strings rather than the `HotkeyNames` class. Have fixed those hotkeys up now.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.450  Runtime v2023.1100.0.459
