### ISSUE TITLE
In-Game: part_particles_create_color() fails to overwrite particle color

### ISSUE THREAD

**Issue by yoshikins** [YoYoGames/GameMaker-Bugs#2217]
### Description

Duplicate of GameMaker-Bugs/155 but I haven't seen anyone talk about it since the carryover, so I decided to add some screenshots and a project to hopefully bring some light to it. The bug description is in the title, and it's visible in the attatched project and screenshots.

I am aware that `part_system_color` exists, however this function does fundamanetally a different thing.

### Expected Change

The particle color to actually get overwritten by calling the function

### Steps To Reproduce

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/61922976/4ea199fa-73ad-4573-ae94-72ba0e9b0752)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/61922976/3b437202-7e72-4408-8b9c-9e08c285dca3)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/61922976/9e593430-523f-42b5-802a-24005cf31cd9)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/61922976/e028201b-88a2-4d7d-86cc-2b67554ae9e2)

Sample Project:
[particle-bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13371063/particle-bug.zip)

[Particle bug report.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13376380/Particle.bug.report.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2.3.7.606/476
2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Removed the old version now and added its missing sample here also.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.571  Runtime v2024.600.0.597
