### ISSUE TITLE
In-Game: [HTML5] Issue with defining nested structs as of 2023.4

### ISSUE THREAD

**Issue by MatthewStone218** [YoYoGames/GameMaker-Bugs#2221]
### Description

As of IDE v2023.4.0.84 Runtime v2023.4.0.113

`struct = {
	a1:
	{
		b1: 1,
		b2: 2
	},
	a2:
	{
		b1: 1,
		b2: 2
	}
}`

defining struct like above results as this on HTML5:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/645c7cb6-b172-49d2-9890-b4ab96be4105)

Whereas this on Windows and other platforms you will get the correct:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/8949fbb2-de00-4ecd-bf6e-86fad0782e1b)

### Expected Change

HTML5 to give the same results as Windows.

### Steps To Reproduce

1. Start GameMaker and import [nestedStructsOnHTML5.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13377209/nestedStructsOnHTML5.zip)
2. Set target to HTML5
3. Run the project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.4
2023.8

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Have you confirmed this issue still exists in 2023.8?

**Comment by MatthewStone218** [comment]
> Have you confirmed this issue still exists in 2023.8?

yes

**Comment by MatthewStone218** [comment]
> Have you confirmed this issue still exists in 2023.8?
I need to fix it now so fixed code like this:

`struct_JSON = '{ "a1": { "b1": 1, "b2": 2 }, "a2": { "b1": 1, "b2": 2 } }'`

Now it works but it still have problem.
I can't define the element like spr_pizza_1 but "spr_pizza_1" and use asset_get_index.

When this bug is resolved, will it also apply to version 2023.4? For stability and compatibility, our company uses 2023.4 version.

**Comment by YYDan** [comment]
No. You will need to update to whichever version the fix is available in. Fixes do not go back into older releases.

**Comment by YYDan** [comment]
Added a sample project and screenshots using 2023.8.

**Comment by rwkay** [comment]
Unable to reproduce in 2023.11 latest on 24/11/2023

**Comment by YYDan** [comment]
Yes, as mentioned above, this was quietly fixed at some point and so is already in 2023.11.0:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/be9de6a2-85b0-45a4-b1f9-8e5b4036855f)

Fixing the milestone now.
