### ISSUE TITLE
Room Editor: [Mac IDE] Precise Item Placement shortcut is incorrect in Beta  IDE v2023.1100.0.441  Runtime v2023.1100.0.453

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2222]
### Description

Currently there's a couple of issues to be aware on Beta  IDE v2023.1100.0.441  Runtime v2023.1100.0.453  only present on the Mac IDE. These have already been fixed ahead of the next release.

- The correct combination for Precise Item Placement in the Room Editor should be Command + Option, and not Control + Option.
- There's a duplicate entry with just a command key that can be seen in redefine keys with 2 missing strings for the hotkey and the command. These will disappear once the fix is in, leaving only the correct entry in the Room Editor section.

![keys](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/77e94b44-c772-4288-b74c-f4c4da0202ad)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma, macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Fixed. Mac hotkey hadn't been updated with change after YoYoGames/YoYoStudio#8978

**Comment by SmithTom6304** [comment]
YoYoGames/YoYoStudio@b85e3d86c14c2fc8821c66e603b9c89db7de6644
