### ISSUE TITLE
Feather: Nested constructors with methods in an Object code event can cause Feather to fail to work when that project is reopened

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2227]
### Description
This is the same bug as #2224, but I got it to happen with different code so I wanted to report it as well so I can attach a project.

### Steps To Reproduce
```
//in an object create event
function popup_create() constructor {
	draw = function() {}
}

function popup_turnin() : popup_create() constructor {
}
```
Create a constructor, give it a method, and then create a child constructor. Define them both in an object rather than in a script. Feather will crash when the project is loaded and fail to initialize.

[6501b631-b89b-4b80-830f-0a7a3857714f](https://api.gamemaker.io/api/github/downloads/6501b631-b89b-4b80-830f-0a7a3857714f)

**Comment by alicemoretti** [comment]
Linking to #2091

**Comment by YYDan** [comment]
As an aside, you could have added a comment onto the original issue and attached your project as part of your comment  - nothing stops you from doing that.

**Comment by zreedy** [comment]
I'm moving this to In Progress and assigning myself the ticket since this is directly linked to #2224 which cleared Triage and is assigned to me.

**Comment by zreedy** [comment]
Fixed, see https://github.com/YoYoGames/GameMaker-Bugs/issues/2224 for details.
