### ISSUE TITLE
Keyboard Shortcuts: New "Open Included Files" hotkey doesn't open the included files window

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2228]
### Description

On beta IDE v2023.1100.0.441 Beta Runtime v2023.1100.0.453, the "Alt + I" hotkey "Open included files" doesn't open the included files window.

[Contact us package](https://github.com/YoYoGames/GameMaker-Bugs/files/13390344/IncludedFilesHotkey.zip)

### Expected Change

Pressing "Alt + I" should open the included files window

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Press "Alt + I"
4. Observe nothing happens

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This is a new hotkey post the shortcut refactor YoYoGames/YoYoStudio#8731, so we've not lost any new functionality here

**Comment by SmithTom6304** [comment]
Fixed. Shortcut wasn't being created.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.448  Runtime v2023.1100.0.457
