### ISSUE TITLE
Keyboard Shortcuts: Open Workspace Overview and Workspace Overview Flow Backwards are incorrectly listed

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2229]
### Description

In Beta IDE v2023.1100.0.441 Beta Runtime v2023.1100.0.453, the Open Workspace Overview and Workspace Overview Flow Backwards hotkeys are listed in Redefine Keys when they should not be, as remapping them causes the Workspace Overview module behaviour to break.

[Contact us package](https://github.com/YoYoGames/GameMaker-Bugs/files/13390560/WorkspaceOverview.zip)

### Expected Change

Open Workspace Overview and Workspace Overview Flow Backwards should not appear in Redefine Keys

### Steps To Reproduce

1. Start GameMaker
2. Open Redefine Keys
3. Observe the Open Workspace Overview and Workspace Overview Flow Backwards hotkeys are listed

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
See YoYoGames/YoYoStudio#9067 for info regarding remap support in the Workspace Overview

**Comment by mgeddesGM** [comment]
IDE v2023.1100.0.450  Runtime v2023.1100.0.459
