### ISSUE TITLE
[IDE] pressing F12 do not Collapse/Expand dock panels

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2240]
### Description
In previous version the F12 key collapse or expand the dock panels, in the latest beta this no happen.

this appear on my UI.log 

Error performing Key lookup - 125 was not found in the lookup
Error performing Key lookup - 123 was not found in the lookup

### Steps To Reproduce
1. press F12 in the IDE

[0b217339-58a7-4603-930c-7bb0440af717](https://api.gamemaker.io/api/github/downloads/0b217339-58a7-4603-930c-7bb0440af717)

**Comment by SmithTom6304** [comment]
Fixed. Have added a hotkey and shortcut for "Expand/Collapse Docks".
I've added a new localisation entry for this shortcut in RedefineKeys. The old localisation was "Ide Toolbar Collapsedocks", which isn't great. The new localisation is "Expand/Collapse Docks".

As with any new localisation entry, this means we won't have translated versions of this string until a translation is added.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.449  Runtime v2023.1100.0.458
