### ISSUE TITLE
Feather: Does not work for some projects in Beta IDE 2023.1100.0.441

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2241]
### Description
That is Feather refuse to start in the last beta on my proyect. See the UI.log attached!

### Steps To Reproduce
1. Open my proyect attached
2. Try to use feather

[1e6a5d77-4f2b-4cce-a1c0-c0a3c6ee85ec](https://api.gamemaker.io/api/github/downloads/1e6a5d77-4f2b-4cce-a1c0-c0a3c6ee85ec)

**Comment by gnysek** [comment]
Refusing to start sounds similar to both issues mentioned here: https://github.com/YoYoGames/GameMaker-Bugs/issues/2224

**Comment by zreedy** [comment]
Appears fixed when verified against #2224 and #2091

**Comment by cameron-home** [comment]
Verified when following the steps of #2224 and #2091 in Beta IDE v2023.1100.0.450  Runtime v2023.1100.0.459 with the attached project. No crash or UI errors occur.
