### ISSUE TITLE
With Statement of Object Index Intermittently Gets Wrong Instances

### ISSUE THREAD

**Issue by danieltjewett** [YoYoGames/GameMaker-Bugs#2256]
### Description

Given this code:

```
with (obj_Buildingable)
{
    try
    {
	if (buildingVisibilityFunc == undefined)
	{
		continue;
	}
    }
    catch (e)
    {
	log("Crashing", object_get_name(object_get_parent(object_index)), object_get_name(object_index));
	throw e;
    }

    ...
}
```

Eventually, I get a crash like so:

```
[118904]   Crashing obj_HelperDialog obj_HelperBottomButton 

___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event1
for object obj_Global:


Variable obj_HelperBottomButton.buildingVisibilityFunc(100338, -2147483648) not set before reading it.
 at gml_Object_obj_Global_Step_1 (line 210) - 			if (buildingVisibilityFunc == undefined)

############################################################################################
```

This is because the instance that is being iterated over doesn't have a `buildingVisibilityFunc` variable.  However, in the log, this particular object, `obj_HelperBottomButton` parent is `obj_HelperDialog`, which has a parent of `obj_Core`, which has no parent.  There is nothing in `obj_HelperBottomButton`'s ancestry that defines `obj_Buildingable`, and should not be called with this `with` statement.  Yet, intermittently, I get this issue.

I don't have a good way to reproduce, nor am I uploading my game publicly.  I am more curious if there have been any other issues / reports with the `with` statement, or anything that will be fixed in upcoming versions of Game Maker?

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by stuckie** [comment]
Just a reminder that submitting a project through the IDE will upload it privately.

**Comment by danieltjewett** [comment]
> Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

I understand the need for an easy to reproduce project.

> I am more curious if there have been any other issues / reports with the with statement, or anything that will be fixed in upcoming versions of Game Maker?

As stated, I am more curious if there were any issues related to this.  For anyone else having similar issues, I linked the only issue that I could find, publicly, that maybe related:

https://github.com/YoYoGames/GameMaker-Bugs/issues/1802

I am hoping that this linked issue is related and that this indeed is no longer an issue in the next runtime release of Game Maker.  If for some reason there are still problems, I will try to figure out a way to reproduce without uploading my entire game.

I should also note, for my future self, that the only "out-of-the-ordinary" thing I have recently added was an `instance_change` for the first time a month or so ago.  But the `instance_change` I am using seems pretty guarded, and unrelated to the instances / object indexes described in the original crash mentioned above.

**Comment by danieltjewett** [comment]
I also found this: https://forum.gamemaker.io/index.php?threads/solved-with-statement-issue.55361/

Perhaps there is something happening internally with Game Maker and the `with` statement with `instance_change`.

**Comment by danieltjewett** [comment]
I recently removed `instance_change` in favor of destroying the instance, recreating another instance, and updating the properties necessary to change.  There have been no issues since.  There is something internally happening with the `with` statement and `instance_change` after hours of playing.

It seems like the link above has not been resolved since 2018.
