### ISSUE TITLE
Feather: GM1064 message now says "String not found" in Nov23 Beta IDE 444

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2260]
### Description
GM1064's message is supposed to say that a global function was redeclared, but instead it says 
"GM1064 String not found: Feather_GM1064"

### Steps To Reproduce
Copy paste a function to another script to trigger the message, and see that it's showing String not found instead of the expected message.

[0f5d5e70-b26a-4ff0-89b3-aad1a0e2dd6d](https://api.gamemaker.io/api/github/downloads/0f5d5e70-b26a-4ff0-89b3-aad1a0e2dd6d)

**Comment by zreedy** [comment]
Fixed, added to the english.csv
