### ISSUE TITLE
Feather: GM freezes when typing args for a function called inside a static function which is itself inside a constructor

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2264]
### Description
When defining static function inside constructor, pressing backspace inside function call causes IDE to freeze / crash.

### Steps To Reproduce
1. Open attached project
2. Go to script `list`, into `static draw = function`
3. add `draw_sprite(0,0,`
4. press backspace
5. sorry, I didn't wanted to crash it again...

[e2c2213d-ec09-4cf6-b66b-8943c0dcfd79](https://api.gamemaker.io/api/github/downloads/e2c2213d-ec09-4cf6-b66b-8943c0dcfd79)

**Comment by YYDan** [comment]
From our testing the backspace is after the hang has occurred - typing the "(0,0," bit is enough to cause the issue (so, only up to step 3 above).

**Comment by zreedy** [comment]
Fixed with an arbitrary max dive depth of 16 instead of "until the bottom of the scope stack". Yielding Quick Fixes and Resolve Context at Line/Column required diving scope ranges and since the changes to Recursive Ctor Functions it's possible for a scope to contain itself now...

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.11.0.120  Runtime v2023.11.0.157
