### ISSUE TITLE
Feather: mp_potential_path() gives incorrect "type 'Id.MpGrid' is expected" for the path argument

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2268]
### Description
Feather shows "GM1041 The type 'Asset.GMPath' appears where the type 'Id.MpGrid' is expected." When passing a path as the first argument for mp_potential_path. The first argument is definitely supposed to be a path, not a mp grid.

mp_potential_path_object does not give a warning for the same argument, so that one is working correctly.

### Steps To Reproduce
```
path = path_add();

mp_potential_path(path, x, y, 2, 2, false)
//the error also happens when passing a pre-existing path asset 
```

[e726652c-b089-48a5-88e1-0fd85e29c246](https://api.gamemaker.io/api/github/downloads/e726652c-b089-48a5-88e1-0fd85e29c246)

**Comment by cameron-home** [comment]
Verified fixed in Beta IDE v2024.200.0.475  Runtime v2024.200.0.490
