### ISSUE TITLE
In-Game: [YYC] Creating a nested struct causes a crash in runtime 2023.1100.0.455

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#2276]
### Description
Attempting to create a struct in a struct causes a crash on YYC. (Tested with Windows/MacOS/iOS)
Using this exact snippet
```gml
struct = {
    struct2: {
        struct3: {}
    }
}
```

### Steps To Reproduce
1. Download and boot up project
2. Run project on iOS YYC
3. Tap on the screen to create a struct within a struct in a struct (see Step event)

[73cc6772-9bf0-4a4d-bbbe-29012f6e4381](https://api.gamemaker.io/api/github/downloads/73cc6772-9bf0-4a4d-bbbe-29012f6e4381)

**Comment by rwkay** [comment]
Hmm I cannot get it to crash on my local build (made from `2023.11.0-main`), this may have been fixed with recent changes

**Comment by tabularelf** [comment]
Well, hopefully it's all fine on release

**Comment by YYDan** [comment]
Yeah, we reproduced the crash in the original runtime, but all is fixed already (as mentioned above), so closing now.
