### ISSUE TITLE
In-Game: [HTML5] Game doesn't run if a nested function is called in runtime 2023.1100.0.455

### ISSUE THREAD

**Issue by sohomsahaun** [YoYoGames/GameMaker-Bugs#2277]
### Description
When a global function (function declaring like "function function_name() {}") is declared inside another function, calling the nested function throws an error.

The generated code looks something like this on the console:
gml_Script_object_global_func@gml_Object_oBug_Create_0(_inst,_other);

### Steps To Reproduce
1. Open the included project
2. Uncomment one of the lines commented with "Uncommenting this line throws error"
3. Run the game on the HTML5 platform

[15c2d671-88c1-4c9a-bab9-f2d6c4bc87f0](https://api.gamemaker.io/api/github/downloads/15c2d671-88c1-4c9a-bab9-f2d6c4bc87f0)

**Comment by YYDan** [comment]
Sounds very similar to #2276

**Comment by cameron-home** [comment]
Verified in IDE v2023.1100.0.450  Runtime v2023.1100.0.459
