### ISSUE TITLE
Code Snippets: Keybindings on custom code snippets aren't being used in 2023.11

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2284]
### Description

In Beta IDE v2023.1100.0.444 Beta Runtime v2023.1100.0.455, custom code snippets aren't being loaded with their supplied hotkey. Default code snippets are loaded correctly.

[Contact Us Package](https://github.com/YoYoGames/GameMaker-Bugs/files/13457888/CustomSnippet.zip)

### Expected Change

Custom code snippets should have a default keybinding that matches the key specified in the snippets file

### Steps To Reproduce

1. Create a custom code snippets file following the [provided steps](https://manual.yoyogames.com/The_Asset_Editors/Code_Editor_Properties/Code_Snippets.htm)
2. Paste the following snippet in the file: `I - Instance Create:instance_create_layer(x, y, |layer|, object);`.
3. Note the snippet starts with an `I` - this should be the default keybinding
4. Open GameMaker
5. Open a text editor
6. Press F4 to open the snippets menu
7. Observe the `Instance Create` snippet appears without it's provided hotkey
8. Press `I` to insert the snippet
9. Observe nothing happens

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Since the snippets format will change, this will require different steps to verify. We'll also need to verify remapping custom snippets works correctly. I'll provide verification steps for the new format once it's been decided on.

**Comment by dicksonlaw583** [comment]
@SmithTom6304 

Do you have information on how the new hotkey names work? I don't have access to that `YoYoGames/YoYoStudio` project from your previous reply, but I would love to try the new format just to get it working again.

**Comment by SmithTom6304** [comment]
Proper support for defining custom code snippet mappings will be available in 2024.2.
However, there is a workaround for now:

1. Create a custom code snippet in your `snippets.txt` file. ie. `I - Instance Create:instance_create_layer(x, y, |layer|, object);`
2. Note that the name of the snippet here is just `Instance Create` - the leading `I` key will be ignored by the new system, and has no effect.
3. Navigate to the `default_hotkeys.json` file included with your IDE install. 
3.1 On Windows, this is in `%programfiles%\GameMaker Studio 2[-Beta/etc..]`. You should be able to find the `default_hotkeys.json` file from there - I don't have access to a Windows PC right now, so I can't give you the exact path.
3.2 On mac this is `/Applications/GameMaker.app/Contents/MacOS/{arch}/default_hotkeys.json`.
5. Insert a new hotkey JSON entry:
```json
{
    "Name": "Insert Instance Create Snippet",
    "Description": "",
    "Combo": {
      "Modifier": "None",
      "Keys": "I"
    },
    "Location": "Text Editor"
},
```
5. There are a couple things to note here:
5.1. The `Name` property should be of the format `"Insert {Snippet Name} Snippet"`. Since this example is for the `Instance Create` snippet (see step 2), this is `"Insert Instance Create Snippet"`
5.2 The `"Keys"` and `"Modifiers"` properties specify the combo, and doesn't necessarily match up with the code snippet format. See the other hotkeys in this file for examples.
5.3 The `"Location"` and `"Localisation"` fields are used in the `Redefine Keys` menu. I've omitted the `"Localisation"` field for this example, as there will not be a localisation value for you to use in our localisation files.
5.4 Finally - **this file is included with the IDE, and will be replaced if you update GameMaker.** **! IF YOU UPDATE GAMEMAKER, THIS FILE WILL BE OVERWRITTEN !** 

I'm away on holiday for the remainder of the year, so I won't be around to answer any questions - hopefully these instructions are clear enough, and you're able to figure anything out I've missed. And just to be clear, this _is_ a workaround. You're on your own if anything goes wrong, make sure to back things up that you don't want to lose. Proper support will be included in the 2024.2 release.

**Comment by SmithTom6304** [comment]
@dicksonlaw583 See above - hopefully this should get you running again, and apologies for not having proper support in for 2023.11.

**Comment by muddrox** [comment]
I have been staring at my snippets file for the past hour and a half trying to figure out why it no longer works.  Glad I stumbled upon this because I thought I was going crazy.

**Comment by SmithTom6304** [comment]
Support for creating empty hotkeys from custom snippets has been implemented.
Still need to add a conversion step from existing keybinds to our new hotkey format. This will require modifying users snippets file in place (to remove the leading character), and so will need a dialog warning.

**Comment by mgeddesGM** [comment]
verified for win on  IDE v2024.200.0.476  Runtime v2024.200.0.491. Issue can be verified once Mac is tested

**Comment by Emc1923** [comment]
Verified also for Mac. Thanks!

**Comment by SmithTom6304** [comment]
For any users wondering how to remap a snippet after the conversion has taken place: this should now be done via the `Preferences -> Redefine Keys` menu.
