### ISSUE TITLE
Sequence Editor/Inspector: The settings for 'Backdrop Image' are named different in the Canvas Toolbox and the Inspector

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2286]
### Description

When opening the Canvas Toolbox the image used to guide the positioning of the assets within the sequence is called 'Reference Image' but when opening the Inspector this is called 'Backdrop Image'. As they're are affecting the same setting they should be called the same for clarity.

See images for reference:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/94de10ff-3362-4da2-a5ad-8ba9de96e02f)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/bb427e4d-c798-493e-8331-e3199acc4f2d)

### Steps To Reproduce

1. Start GameMaker
2. Open a project and create a new Sequence
3. Inspect the Sequence
4. Open the Canvas Toolbox inside the Canvas
5. See the difference

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
-updated to use same field names in inspector and canvas toolbox
