### ISSUE TITLE
Device Manager: Existing devices are not immediately reloaded when signing-in, requires an IDE restart

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#2287]
### Description

When signing out, restarting GameMaker IDE v2023.11.0.118  Runtime v2023.11.0.155, and signing back into the same account, any existing devices within the Device Manager are not retained. If GameMaker is restarted in this state while the user is still signed in, then the devices are returned. It appears that the sign-in operation is not reading the 'devices.json' file correctly.

### Expected Change

It is expected that any existing devices listed in the device manager should always be saved and present, even when signing back into an account.

### Steps To Reproduce

1. Start GameMaker
2. Add a device to the Android/iOS/Ubuntu/tvOS platform
3. Sign out of GameMaker
4. Restart GameMaker
5. Sign back into GameMaker
6. Select the target with the added device
7. Observe that saved device is not present
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of   IDE v2024.200.0.483  Runtime v2024.200.0.499
