### ISSUE TITLE
Sequence Editor: Creating a new Text Track by dragging a font asset from the Asset Browser in the Track Panel is no longer possible

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2288]
### Description

When trying to create a new Text Track directly by dragging an existing Font Asset from the Asset Browser is no longer possible, as it is in LTS  IDE v2022.0.2.51  Runtime v2022.0.2.49. You will be left with the option to use the Canvas Toolbox only for creating Text Tracks. 

_Note as well that in LTS you won't be able to select a Font Asset to create a new track from inside the Track Panel, but you still will be able to drag it in._

### Steps To Reproduce

1. Start GameMaker
2. Open any project
3. Create a Font asset and Sequence
4. Open the Sequence in the Sequence Editor
5. Attempt to drag the font from the Asset Browser to the track panel
6. Observe that the action is not permitted (red cross appears)
7. [Optional] Attempt the previous steps in LTS, observe that a new Text Track is created

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly), Beta (IDE v2023.1100.0.447  Runtime v2023.1100.0.456)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Text track can now be created by dragging a font from the asset browser, or using + Add Resource in track panel.

**Comment by mgeddesGM** [comment]
verified in win as of  IDE v2024.200.0.459  Runtime v2024.200.0.477

**Comment by SamTHodson** [comment]
Verified on Mac in IDE v2024.200.0.459  Runtime v2024.200.0.477
