### ISSUE TITLE
Adding arrays to another array via array_set() or array_insert() overwrites the whole array

### ISSUE THREAD

**Issue by Seirei3D** [YoYoGames/GameMaker-Bugs#2294]
### Description
I was trying to create a 2D array to map get an array representations of my tilemap.

With a nested look I created an array for the individual rows that I filled with 0's and 1's.
In the outer loop I added the first array to the current index in another array.

The idea was to fill one array with info and then fill the other array with that, to create a 2D array.

### Steps To Reproduce
Here's a small version of the function I used that should run without any external variables.
The Output log will show that at each step the "tileIndexArrayRow" has a different value, but every time it get's added to the "tileIndexArray" it overwrites every index instead of just the one specified.
This happens for "array_set()" and "array_insert()".

```
function arrayBreaker(){
	var tileIndexArray = [];
	var tileIndexArrayRow =[];
	
	for (i = 0; i <= 10; i++) {
		for (j = 0; j <= 10; j++) {
			array_set(tileIndexArrayRow,j, random_range(0,1));
		}
		array_set(tileIndexArray, i, tileIndexArrayRow)
		show_debug_message(tileIndexArrayRow);
	}
	show_debug_message(tileIndexArray);
}
```
Added a video that shows this while stepping through in debug mode:
https://github.com/YoYoGames/GameMaker-Bugs/assets/13433349/0f9e0449-ceb5-4e93-8ecc-f5229bcd54b4

[e8991573-cdda-41aa-af66-c50c28d41aa5](https://api.gamemaker.io/api/github/downloads/e8991573-cdda-41aa-af66-c50c28d41aa5)

**Comment by tabularelf** [comment]
This isn't really a bug. You're passing in an array reference.
You need to create a *new* empty array.

```gml
function arrayBreaker(){
	var tileIndexArray = [];
	
	for (i = 0; i <= 10; i++) {
               	var tileIndexArrayRow =[];
		for (j = 0; j <= 10; j++) {
			array_set(tileIndexArrayRow,j, random_range(0,1));
		}
		array_set(tileIndexArray, i, tileIndexArrayRow)
		show_debug_message(tileIndexArrayRow);
	}
	show_debug_message(tileIndexArray);
}
```

**Comment by Seirei3D** [comment]
Well that's embarrassing, I swear I've showed this to others and they were just as stumped as I was.
But yeah I see the error now and it totally makes sense. So sorry for that!

**Comment by tabularelf** [comment]
Happens to the best of us. Sometimes we need one, two, ten eyes!
