### ISSUE TITLE
Effect Layer - Mask effect broken

### ISSUE THREAD

**Issue by ListonC** [YoYoGames/GameMaker-Bugs#2297]
### Description
I am making a Tetris Attack / Panel De Pon match-3 game. I want to show colored 
blocks inside two rectangles and mask out everything else. I use an Effect Layer
over the Instances layer where the blocks will be. I use a custom sprite designed 
and measured specfically to show only the contents of the rectangles. 
PROBLEM: The alignment of the mask is offset, and imprecise. See attached
images.

### Steps To Reproduce
Simply create a Mask Layer with the objective of trying to mask out a specific 
rectangle in your room.

[7c5558c0-6a06-47d8-9fd0-ca4baa29b734](https://api.gamemaker.io/api/github/downloads/7c5558c0-6a06-47d8-9fd0-ca4baa29b734)

**Comment by JonnoRobson** [comment]
There seems to have been problems with the upload of associated files for this issue. Several of the attached images have failed to upload successfully. Additionally the project has errors when running and does not match in the IDE with what is described in the issue or depicted in the attached reference image. 
I'm going to close this issue for now - could you submit a new issue with a working project and images attached clearly demonstrating the issue you have described?
