### ISSUE TITLE
In-Game: [HTML5] Sprites drawn during Post Draw event are being stretched as the browser window is resized

### ISSUE THREAD

**Issue by sp202** [YoYoGames/GameMaker-Bugs#2301]
### Description

Under specific conditions, it appears that anything drawn in the Post Draw event becomes stretched, proportional to the scaling of the application_surface size relative to its original size at room start.

The conditions as demonstrated in the example project attached seem to involve setting/resetting a surface target in the Post Draw event. The expected result can be seen by pressing space to toggle the "fix", which demonstrates the expected behaviour where the size of the rendered sprite remains constant regardless of window size - this is how it behaves on LTS.

[postdraw_bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13470560/postdraw_bug.zip)

### Steps To Reproduce

1. Run the example project in HTML5
2. Resize the browser window  (however you wish) and notice how the rendered sprite stretches
3. Press spacebar to toggle the fix ON
4. Now resize your browser window more (however you wish) and observe that the sprite stays at the correct scaling always

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8
Beta IDE v2023.1100.0.444 Beta Runtime v2023.1100.0.455

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Fixed
