### ISSUE TITLE
Ubuntu build fails to make TCP connection

### ISSUE THREAD

**Issue by meseta** [YoYoGames/GameMaker-Bugs#2303]
### Description

In Beta Runtime v2023.1100.0.455, building with Ubuntu VM, running on Ubuntu 20, the gamemaker server is unable to make an outgoing TCP connection, and produces the error "Socket ConnectWrap failed error:-2"

It's a little hard to provide details for this bug report, as we encounter this error in a headless linux build. The build is automated, and so there isn't actually an IDE on a linux machine I can go play around with, so unfortunately I can't include the Contact Us Package from a representative machine that this would repro on

Here's a screenshot of server logs when this happens
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/930832/9d381b0a-c366-4271-beb3-d17f6e4e9714)

For comparison, here's server logs using an earlier runtime (IDE v2022.11.1.56  Runtime v2022.9.1.66), on the same OS, hardware, etc.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/930832/6581f478-c839-48f5-b9de-97407b74dc38)

### Steps To Reproduce

1. Make a build that does an outgoing non-raw TCP connection to localhost
```
client = network_create_socket(network_socket_tcp);
network_connect(client, "localhost", 6510);
```
2. try to run it with or without a TCP server there
3. observe a "Socket Connectwrap failed error:-2" error

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Ubuntu

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
It appears this error happens when you try making a TCP connection from a Linux machine that doesn't have any IPv6 addresses assigned (even link-local is enough; it doesn't have to be a globally routable address). Could you confirm whether this is the case on the servers where you're running it?

**Comment by meseta** [comment]
oh very interesting, thanks. I can look into that. It would seem that by default kubernetes, and in particular GKE, by default does IPv4 internal networking only, and so it would seem any workloads run with an IPv4 stack. However it looks like they released IPv4/IPv6 dual stack recently, I will investigate

**Comment by meseta** [comment]
oh very interesting, thanks. Here's the output of `ip a` on the container running the GM server

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/930832/bd5b9b9c-4be2-4f5b-9dfa-d378929326b9)

According to googling, there should have been an `inet6 ::1/128` entry alongside `inet 127.0.0.1/8` for localhost. I will see about enabling that

**Comment by yoyo-danielc** [comment]
Hi @meseta,

Thanks for confirming the networking configuration where the servers are running. A fix for the connection failing when no IPv6 addresses are present is queued up to go out in the 2024.02 release.

In the meantime, you _might_ be able to work around it by running the following commands in a container (I haven't been able to test this):

```
ip link add type veth

# After running the above, "ip link" should show a pair of new veth devices (e.g. veth0 and veth1)

ip link set veth0 up
ip link set veth1 up
```

Once that is done, the veth interfaces should get an autoconfigured IPv6 address after a few moments. If it doesn't, you can check if IPv6 has been disabled at an interface level with `cat /proc/sys/net/ipv6/conf/vethX/disable_ipv6` and enable it with `echo 0 >/proc/sys/net/ipv6/conf/vethX/disable_ipv6`

**Comment by meseta** [comment]
thanks @yoyo-danielc, that workaround unfortunately doesn't work inside kubernetes clusters as the container has no ability to change the network (same `RNETLINK answers: Operation not permitted` error)

However, I've finished doing the migration, and have enabled ipv6 across our staging GKE cluster and it is now working! Thanks for the help

**Comment by YYDan** [comment]
Just realised this was recently picked to LTSr3, so have updated the report now.
