### ISSUE TITLE
In-Game: [Android VM] "NaN" is equal to "true", differs from other platforms

### ISSUE THREAD

**Issue by Anumania** [YoYoGames/GameMaker-Bugs#2309]
### Description

On Android comparison to NaN returns true, it should not do this.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13481779/contactus.zip)

### Steps To Reproduce

1. Start GameMaker and import [AndroidNANComparisonIsWrong.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13487753/AndroidNANComparisonIsWrong.zip)
2. Run it for Android VM specifically
4. See the text says they match (which is incorrect/unexpected)
5. (Optional) Run the project for Android YYC, Windows VM/YYC or HTML5 and observe this time the text says they do not match (correct/expected)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2
Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Confirmed the issue and added a proper sample project now. Expanded the steps to match.

**Comment by YYDan** [comment]
August monthly is the same, so this is nothing new in the Nov Betas. Have edited the report accordingly.

**Comment by YYDan** [comment]
Of the various targets I have checked, it's only Android VM which does this - not even Android YYC.

**Comment by rwkay** [comment]
Fixed in 2024.2
