### ISSUE TITLE
Feather - Return type not correct when using anon struct

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2310]
### Description
if i return a anon struct while on a with expression feather will return the wrong type.
see images.

### Steps To Reproduce
try to write something like the code of the images.

[e12b4042-a2c7-41cb-b5dc-2d6e59df7900](https://api.gamemaker.io/api/github/downloads/e12b4042-a2c7-41cb-b5dc-2d6e59df7900)

**Comment by Totobal5** [comment]
![GameMaker-Beta_A0SWihLeS9](https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/baec4e59-0ec5-4079-926c-745699eb080d)

What feather show

![GameMaker-Beta_TJktJl1793](https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/e763e437-2fca-47cd-b8de-96f7fbac161a)

i think it need to show "Struct"

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
