### ISSUE TITLE
Bug with _filter_underwater

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#2321]
### Description

Helo

Good morning,

I'm having problems with the effects (underwater...) selectable from the editor.
These start to malfunction after a certain time of display on console.

So I try to create them by programming to try to avoid this problem

I tried to reproduce the underwater effect

Here is my code

var _fx_underwater = fx_create("_filter_underwater");
fx_set_parameter(_fx_underwater, "g_Distort1Speed",0.01);
fx_set_parameter(_fx_underwater, "g_Distort2Speed",0.025);
fx_set_parameter(_fx_underwater, "g_Distort1Scale",[20,2]);
fx_set_parameter(_fx_underwater, "g_Distort2Scale",[100,10]);
fx_set_parameter(_fx_underwater, "g_Distort1Amount",3);
fx_set_parameter(_fx_underwater, "g_Distort2Amount",6);
fx_set_parameter(_fx_underwater, "g_ChromaSpreadAmount",1);
fx_set_parameter(_fx_underwater, "g_CamOffsetScale",1);

**fx_set_parameter(_fx_underwater, "g_GlintCol",[25,25,25, 1]);
fx_set_parameter(_fx_underwater, "g_TintCol",[127,204,255, 1]);
fx_set_parameter(_fx_underwater, "g_AddCol",[0,25,51, 1]);**

layer_set_fx("Instances", _fx_underwater);

I'm having a problem with the 3 bold lines. The color does not match what is in the editor. My effect is all white! If I delete these 3 lines, my effect works but I do not have the desired color

I don't understand, did I set the correct values ​​for the color? (attached screenshot for “TintColor”

fx_set_parameter(_fx_underwater, "g_TintCol",**[127,204,255, 1]**);

![Capture d'écran 2023-11-29 112629](https://github.com/YoYoGames/GameMaker-Bugs/assets/152379397/75240964-7f8f-4bfb-9d38-c523daa083bf)

Do you have an idea of ​​the problem, what value should I pass for the colors?

Thanks

### Steps To Reproduce

1. Start GameMaker
2 copy this code
var _fx_underwater = fx_create("_filter_underwater");
fx_set_parameter(_fx_underwater, "g_Distort1Speed",0.01);
fx_set_parameter(_fx_underwater, "g_Distort2Speed",0.025);
fx_set_parameter(_fx_underwater, "g_Distort1Scale",[20,2]);
fx_set_parameter(_fx_underwater, "g_Distort2Scale",[100,10]);
fx_set_parameter(_fx_underwater, "g_Distort1Amount",3);
fx_set_parameter(_fx_underwater, "g_Distort2Amount",6);
fx_set_parameter(_fx_underwater, "g_ChromaSpreadAmount",1);
fx_set_parameter(_fx_underwater, "g_CamOffsetScale",1);

**fx_set_parameter(_fx_underwater, "g_GlintCol",[25,25,25, 1]);
fx_set_parameter(_fx_underwater, "g_TintCol",[127,204,255, 1]);
fx_set_parameter(_fx_underwater, "g_AddCol",[0,25,51, 1]);**

layer_set_fx("Instances", _fx_underwater);
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by ringotf** [comment]
Yo, posting reply here rather than on the other issue... as the parameters are just being passed through to a shader, I think the rgba needs to be in floating point not 255 ints. Just tried this and seems to set a more water-like color! (I think the clue was in the alpha being 1)

i.e. try:
```
	fx_set_parameter(_fx_underwater, "g_GlintCol",[0.01, 0.01, 0.01, 1]);
	fx_set_parameter(_fx_underwater, "g_TintCol",[0.5, 0.8, 1, 1]);
	fx_set_parameter(_fx_underwater, "g_AddCol",[0, 0.01, 0.2, 1]);
```

**Comment by galban83** [comment]
It works
I don't know this way to pass RGB values, thank you very much you helped me a lot !

**Comment by ringotf** [comment]
> It works I don't know this way to pass RGB values, thank you very much you helped me a lot !

No worries! It's not too clear from the documentation and applying colors seems a little inconsistent through out gml... but whilst I'm here I'd suggest closing this particular issue if its now solved, and the the GM discord is great for help, lots of people on there that can either point in the right direction or confirm bugs to be reported.
