### ISSUE TITLE
"cannot use a function/script name for a variable" compile error when re-defining a parameter as a local variable

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#2331]
### Description
When you try to compile something like

    function f(a, b, c) {
        var a = 10;
    }

GameMaker doesn't like it because you're trying to re-`var` a symbol that's already been defined as a function argument.

But the error message says "cannot use a function/script name for a variable," which makes it sound like there's a name collision elsewhere in the project. I assume it's like this because it's the same error that you'd get if you actually did what it said, but the error message should probably be re-worded for this case.

### Steps To Reproduce
Run the sample project (or attempt to)

[f7b89ed4-b270-4a11-ac48-b9f6ae1d6398](https://api.gamemaker.io/api/github/downloads/f7b89ed4-b270-4a11-ac48-b9f6ae1d6398)

**Comment by rwkay** [comment]
Fixed in 2024.6

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.600.0.562  Runtime v2024.600.0.580, thanks.
