### ISSUE TITLE
Debugger: [Mac IDE] Unable to use F11 to 'Step into function call' as it is overridden by the system hotkey default

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2337]
### Description

In debug runs currently the F11 hotkey used inside the Debugger to step into a function call is overridden by system defaults to 'Show Desktop' instead.

### Steps To Reproduce

1. Start GameMaker on Mac
2. Open any project
3. Debug the project
4. Press Break
5. Attempt to Step into function call by pressing F11
6. Observe that the IDE will be hidden instead

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Changed the default to Command + F11

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.478  Runtime v2024.200.0.493
