### ISSUE TITLE
There are significant bugs on the "Filter layer" effects

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#2339]
### Description
There are significant bugs on the "Filter layer" effects

watch the attached video, I simply launched the "Windy Woods" project on switch and waited next to the moving water. Well after half an hour of waiting, she no longer moves. The effect is completely bugged and stops by itself.

### Steps To Reproduce
run the “Windy Woods” project on switch and wait half an hour next to the water. It will move less and less quickly until it stops. and the bug persists if you reload the room!

You see in the video that the water is no longer moving, which is not normal.

[860c5d9f-8f7b-4a75-a1aa-e996985f6874](https://api.gamemaker.io/api/github/downloads/860c5d9f-8f7b-4a75-a1aa-e996985f6874)

**Comment by galban83** [comment]
I don't understand why this post is closed, the bug is still present, the latest version of game maker studio 2 does not correct it.
 I sent several emails with videos proving the bug, with no response.

THE UNDERWATER EFFECT DOES NOT WORK ON SWITCH, just launch the Windy Woods project and wait 5 minutes next to the water. The latter moves less and less until it stops. For my part, this completely blocks the publication of my game on switch

This seems to me to be a very serious bug since this effect is still used a lot. Furthermore, even if we reload the room, the bug is still present (the water no longer moves at all)

**Comment by jackerley** [comment]
Hi @galban83  a fix has just gone in, which is why the issue has been closed. They will be available in the February release

**Comment by galban83** [comment]
Thanks but I can't delay the release of my game on switch for 2-3 months. This bug is very serious and I committed to publishing it before the end of the year

**Comment by jackerley** [comment]
Ok, one workaround that you can do in the meantime is to open C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2023.11.0.157\bin\FiltersAndEffects\_filter_underwater\project\shaders\_filter_underwater_shader\_filter_underwater_shader.fsh (or the equivalent for the runtime that you are using) and add the line 

precision highp float; 

your shader will work as expected.

**Comment by galban83** [comment]
Thanks, in the main procedure or before?

**Comment by jackerley** [comment]
Right at the top should work fine iirc

**Comment by galban83** [comment]
Thank you very much, I just tested by leaving my switch on for 1/2 hour and it works

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.461  Runtime v2024.200.0.477, thanks.

**Comment by galban83** [comment]
Yes, the latest version fixes this bug
