### ISSUE TITLE
The more you call fx_create, the slower your game will become, even if you change rooms

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#2340]
### Description
There is a significant problem with the management of filters on game maker

1/ Read my previous email, where the underwater effect stops on its own after about ten minutes

2/ I noticed that if you place this code in the creation of an object in a room
myEffect = fx_create("_filter_twirl_distort");
and you call the room several times, your game will lose more and more performance, until it becomes unplayable

### Steps To Reproduce
For the first problem you just have to wait next to the water. After a while she doesn't move anymore.
I don't have this problem on PC, only on SWITCH.  As a result, it is impossible to use the effects on SWITCH

For the 2nd bug, the only solution I found was to place myEffect = fx_create("_filter_twirl_distort"); in a global script in order to avoid calling it several times.
To my knowledge, there is no function to delete the filter and it is not reset when you change rooms
I have this problem on PC and SWITCH

[5a4d855a-b477-43e1-bf46-12d7debec413](https://api.gamemaker.io/api/github/downloads/5a4d855a-b477-43e1-bf46-12d7debec413)

**Comment by yymrennie** [comment]
The bug with the underwater filter not working after a while on Switch was fixed for https://github.com/YoYoGames/GameMaker-Bugs/issues/2339. 

To answer your question there isn't a way to manually destroy filter\effects objects as the garbage collector should clean them up when they are no longer referenced in code or assigned to a room layer.

However an issue was found where they weren't being cleaned up properly in some circumstances and this has been fixed.

**Comment by yymrennie** [comment]
[gh-gmb-2340_fx_create_testproject.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13975271/gh-gmb-2340_fx_create_testproject.zip)

I've attached a sample project to show the issue - in the current version of GameMaker holding down the space bar to switch rooms will cause a gradual performance degradation (you will see large spikes in the timing bar which will get longer and longer). When the space bar is released performance should return to what it was when the project was first run but this doesn't happen. Commenting out the fx_create() line in Object1's Create event will cause the spikes to no longer occur. In a version of GameMaker which has the fix, even with the fx_create() line present performance will not degrade and the frame time spikes won't happen.

**Comment by cameron-home** [comment]
Performance verified returning to what it was in Mike's project above in IDE v2024.200.0.486  Runtime v2024.200.0.502. Closing.
