### ISSUE TITLE
Building Projects: [Xbox YYC] Does not obey the "Use Subst" Preference if that is on

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#2342]
### Description
As you can see from the attached compiler log, Xbox YYC building will fail if the paths to project assets are too long, despite the Preference being enabled t use subst.

Windy Woods is a good example project, as it uses the windblown effect filter out of the runtime install folders.

You will need to manually change your IDE/Asset cache paths in Preferences in order to fix your builds.

### Steps To Reproduce
1. Start GM and download a fresh copy of Windy Woods (code) off the Start Page
2. Open your Preferences > Platform Settings > Xbox and ensure subst is enabled
3. Then view Preferences > General Settings > Paths and ensure you're using the default values GM supplies
4. OK/Apply the Preferences changes
5. Try to build the project for Xbox YYC
6. Observe it fails and that the Visual Studio project continues to have full paths in it, rather than subst mappings
7. (Optional) Change your Paths preferences to something nice and short, then try building again and observe it will likely work with no other changes

[b1102a78-ecfd-4521-a774-ca2580bf06cb](https://api.gamemaker.io/api/github/downloads/b1102a78-ecfd-4521-a774-ca2580bf06cb)

**Comment by yymrennie** [comment]
Fixed in 2024.2
