### ISSUE TITLE
General: Errors accessing resources because the texture/audio group is disabled should be made clearer

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#235]
GM-1577

If you attempt to draw a sprite which is on a disabled texture page you will simply get "Error attempting to draw sprite sprite0", which doesn't help identify the cause of this error or what the user needs to do to resolve.

Doing this with a sound, you get a more informative but inconsistent: "sndMusic2: Audio Group 1 is not loaded"

*Expected:* For Sprites you get "Unable to draw [resource name] because its texture group is disabled on this platform" and for Sounds you get "Unable to play [resource name] because its audio group is disabled on this platform"

*Steps:*
 # Start GMS2 and open the attached project
 # Run it for Windows
 # Observe the output log

**Comment by toby-yoyo** [comment]
The runtime cannot infer why the audio/texture group is not present - only that it is not.

A sprite drawn from a unloaded texture group will now print:
```
Error: Texture page for <sprite_name> is not loaded
```

A sound played from a unloaded audio group will now print:
```
Error: Audio group for <sound_name> (<audio_group_index>) is not loaded
```

**Comment by YYBartT** [comment]
Added note to the Audio Groups manual page. A similar line of text for texture groups is already on the Dynamic Textures page.

**Comment by Emc1923** [comment]
Verified changes in  IDE v2024.1300.0.718  Runtime v2024.1300.0.730
