### ISSUE TITLE
Live wallpaper not loaded after restart

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#2350]
### Description

Bug posted here but making a ticket on github since cant find https://bugs.opera.com/browse/DNA-113407

### Expected Change

Wallpaper would load as expected

### Steps To Reproduce

Steps to reproduce
– Install live wallpaper mod https://store.gx.me/mods/kb3klj/halloween-2023/ or https://play.gxc.gg/mods/432ddf9d-bf07-42c3-bfea-f4dbbf3dd6ae/cfa57bc7-cf92-4080-a9fc-b5bb46b4bd8f/5f50426e-352e-478a-b7e6-fe881af9c95c/mod.crx?1f346a17a7ac3dc225f39e2b208350b6
– Check SD page if it's loaded
– Go to opera://settings/early_bird
– enable it and trigger restart
OR
– just trigger few restarts opera:restart
– observe live wallpaper

Actual result
Live wallpaper not loaded, black screen

IDE v2023.8.2.108  Runtime v2023.8.2.152
Contact Us Package too Large

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by ash0verride** [comment]
Issue will happen with any projects setup using the the live wallpaper template when using its obj_camera object within the main room

**Comment by rwkay** [comment]
Fixed in 2024.2
