### ISSUE TITLE
Room Editor: Smart guide snapping in room is unreliable

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#2358]
### Description
Smart guide snapping in the room editor is unreliable for items with fractional sizes or rotated items.  The guides function correctly in the sequence editor.

### Steps To Reproduce
- Import the attached project
- Open the room and ensure grid snapping is turned off, and smart guides are enabled.
- Drag the unrotated item to the edges of the room; notice it will snap to left and top fine, but fails to snap to bottom or right, guide may not show at all or it may flicker of judder.
- Drag the rotated item and observe failure to snap effectively to most guides

[569b4464-8f4f-4856-b5e5-ee058c8763dc](https://api.gamemaker.io/api/github/downloads/569b4464-8f4f-4856-b5e5-ee058c8763dc)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.200.0.451  Runtime v2024.200.0.461, thanks.
