### ISSUE TITLE
Spine animation time/frame rate is not handled consistently

### ISSUE THREAD

**Issue by yoyo-danielc** [YoYoGames/GameMaker-Bugs#2375]
### Description

This is going to be a long one to explain.

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/5b547c1d-791a-4192-b269-fe50119f368e

In the video above there is a Spine animation which displays through the numbers 0-4 (looping). At the normal frame rate of 30fps in the Spine editor, it advances one number per second. The game speed is 60fps (default) and the speed in the GM sprite editor is set to 30fps (default).

When drawing the sprite by assigning it to an object's `sprite_index` and calling `draw_self()` (or not overriding the draw event), the sprite will animate at the expected frame rate. One tick in GameMaker corresponds to one frame in Spine (note `image_number` corresponds to the 149 frames defined in the Spine editor), and `image_index` is advanced by 0.5 per tick to keep the animation speed correct.

The `draw_sprite()` and `draw_sprite_ext()` calls are advancing their `subimg` parameter at 1/tick, leading to most of them running the animation at double speed so far... still making sense.

In the case of Spine sprites places on a room asset layer, or being drawn by `draw_sprite_ext()` when `image_index` is **NOT** set to the sprite in question, the animation time is being multiplied by the game tick rate (again, 60 in this case), which is why they are running very fast.

Now repeating the above experiment with the speed in the GM sprite editor set to 60fps:

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/76971ade-7492-4a61-b0aa-e37ec6a0c9bf

The object's `image_number` has been doubled to 298, `image_index` is now advanced at 1 per tick to keep the speed consistent with the 30fps used in the Spine editor.

The `draw_sprite()` family of functions now advance at the same rate, which makes some sense, although arguably changing the fps in the sprite editor should affect how fast sprites attached to an object are drawn too.

And again, with the sprite frame rate set to 1fps:

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/2854cd35-0098-4f51-a2df-beb52e9b8915

Now the sprites placed on the asset layer are finally running at the speed intended in the Spine editor. The object sprite continues to be drawn correctly as `image_number` and the advancement of `image_index` are automatically scaled to match the frame rate defined in the sprite editor.

I'm not entirely sure what's going on with the `sprite_draw()` calls in this case - the top two and bottom `draw_sprite_ext()` make sense, since they are now running at 60x speed, however _something_ is scaling the subimg parameter of `draw_sprite()` in the "`sprite_index` is not the sprite" case to run at normal speed.

Finally, we have the "x Frames per game frame" timing option in the sprite editor, which introduces a completely different set of behaviours!

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/4845b59e-8958-488d-b0fb-d17d50b20656

In this video, the sprite is set to 1 frame per game frame.

We can see the object's `image_numer` is now 298, this appears to be scaled by the game frame rate alone (30fps = 149, 60fps = 298, etc). The `image_index` is advanced at 1 per game tick and like the `draw_sprite()` calls which advance their `subimg` at that same rate, run at the correct speed.

Changing the frame per game frame value in the editor causes the object sprite to speed up, the `image_number` remains unchanged and as such, the `draw_sprite()` calls continue to run at the normal speed:

https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/47a2519b-f438-4448-86ef-ccac99d540c8

Here is my test project if you want to experiment for yourself and try any other combinations:

[timetest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13545917/timetest.zip)

### Expected Change

Yes

### Steps To Reproduce

N/A

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
I'm calling this done, at least as far as 2024.02 (and probably the GMS2 runtime) is concerned.

The frame rate of Spine sprites on an asset layer is now handled correctly and `draw_sprite_ext()` doesn't behave weirdly depending on the calling instance's `image_index`.

It would be nice to get some more sensible behavior from the FPS setting in the sprite editor, but I don't think there's any change I can make here that isn't likely to either break a lot of projects, or potentially break other parts of GM in general.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.476  Runtime v2024.200.0.491.

Thank you
