### ISSUE TITLE
Unique struct keys cause memory leaks and slowdowns, and the GC doesn't clean them up.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#2378]
### Description

**IDE 2023.1100.0.49
Runtime 2023.1100.0.458**

In a recent playtest of Crashlands 2, we had several users on lower-end devices experience silent crashes after long play sessions. We believe a memory leak in Structs is the culprit.

Each new variable added to a struct will take longer than the last. The memory and caching associated with each struct variable **never goes away**, resulting in increased RAM usage and decreased performance for the game over time, until it silently crashes. Even if you remove variables from a struct, and no other struct is using those variable names, it will forever add overhead and slowdowns to the game until the game is rebooted.

In the attached test project, we have a struct that gets 10,000 random keys added to it every step. Those keys are removed from the struct at the end of that same step.

- The first time we do this, it takes 93 milliseconds.
- By the 10th time, it takes 605 milliseconds. (6.5x longer)
- By the 50th time, it takes over 4000 milliseconds (43x longer)

There is no way to bust this cache, and the garbage collector doesn't seem to free up information about keys once they are no longer in use, regardless of how long ago they were last used. Although we can take steps to reduce the number of unique keys we are adding to structs to mitigate this effect, or even use ds_maps, this is an optimization that the engine should be handling on its own.

[StructVarLeak.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13549292/StructVarLeak.zip)

### Expected Change

The garbage collector should free up caching for struct variables that are no longer used.

### Steps To Reproduce

1. Start GameMaker
2. Load the test project
3. Run the test project and observe the debug output

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows, Android, iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by shichen85** [comment]
Can confirm this is fixed in 2024.2 Windows VM runs. Still gathering data for YYC and other platforms.
