### ISSUE TITLE
GameMaker Android Build Error

### ISSUE THREAD

**Issue by Mank1941** [YoYoGames/GameMaker-Bugs#2381]
### Description

I want to try Android development on gamemaker, Android Studio works fine with other apps.
I get this error when i try to run the project on Android
Execution failed for task ':com.company.game:lintRelease'.

I also get this
 Error: Google Play requires that apps target API level 31 or higher.
Which is difficult to do cause i cant change the gradle version on GameMaker, i had to download an older jdk just to match the gradle but it brought in new problems. I do have the latest gradle but it wont let me switch to that

### Expected Change

The Project to run on Android

### Steps To Reproduce

1. Start GameMaker
2. Run Game on Android VM or YYC
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Just to be clear, you need to have Target SDK set to at least 31 to be compliant with that Google error message
