### ISSUE TITLE
Code Editor (Visual): "Assign Variable" and "Declare Temp" nodes do not link to their correct manual pages

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#2386]
### Description

In Beta IDE v2023.1100.0.444 Beta Runtime v2023.1100.0.455, the "Assign Variable" and "Declare Temp" GMLVisual nodes don't take you to the correct manual page.
The two correct pages are [Assign Variable](https://beta-manual-en.yoyogames.com/Drag_And_Drop/Drag_And_Drop_Reference/Common/Assign_Variable.htm) and [Declare Temp](https://beta-manual-en.yoyogames.com/Drag_And_Drop/Drag_And_Drop_Reference/Common/Declare_Temporary_Variable.htm) respectively. Assign variable currently takes you to [the Declare Temp page](https://beta-manual-en.yoyogames.com/Drag_And_Drop/Drag_And_Drop_Reference/Common/Declare_Temporary_Variable.htm), and Declare Temp currently takes you to [the homepage](https://beta-manual-en.yoyogames.com/#t=Content.htm).
Note that these links are for the beta manual, and will depend on which version of GameMaker is being tested.

[ManualLinks.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13563203/ManualLinks.zip)

### Expected Change

Both GMLVisual nodes should take you to the correct manual page - see description.

### Steps To Reproduce

1. Start GameMaker
2. Create a new GMLVisual script
3. Create an `Assign Variable` node and a `Declare Temp` node
4. Right click -> Show help on `Assign Variable`
5. Observe it takes you to the `Declare Temp` page
6. Right click -> Show help on `Declare Temp`
7. Observe it takes you to the manual home page.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gurpreetsinghmatharoo** [comment]
Tags were assigned wrong in the manual (which is what connects these pages to the IDE). That is fixed now.

The tag for Declare Temp is: **action_variable_temp**
The tag for Assign Variable is: **action_variable** (this should be in the IDE already, so giving this for verification)

These tags now need to be set in the IDE for both actions.

**Comment by SmithTom6304** [comment]
IDE tags are generated automatically from the manual via RoboHelpTool.exe, so should be working as of next beta.

**Comment by alicemoretti** [comment]
On  IDE v2024.200.0.483  Runtime v2024.200.0.499, Assigned Variable not opens the correct page of the Manual. 

However, Declare Variable open the front page of the manual. 

Reopening the bug. Thank you.

**Comment by SmithTom6304** [comment]
Tag in manual was `action_variable_temp`, but was `action_temp_variable` IDE side. Gurpreet has changed the manual tag to match the IDE, and should now be fixed in the next beta build. Thanks

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.485  Runtime v2024.200.0.501
