### ISSUE TITLE
In-Game: [iOS] device_mouse_x_to_gui() values are offset when running on iPhones

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#2389]
### Description
device_mouse_x_to_gui()  somehow returns value that are slightly offset when running on iPhone 13 Mini but not on other iPhone models.

The sample project has a room that is 1920 x 1080. When tapping on top right corner red dot, iPhone 13 mini's device_mouse_x_to_gui() returns 1999 instead of 1920 as on other devices or iPhone 13 mini emulator.

This is replicated on iPhone 13 Mini running OS 16.6, 15.3.1, and 15.0.2, so it is probably OS agnostic.

### Steps To Reproduce
1. Run the project for iOS vm export on a non iPhone 13 Mini device. Tap the top right corner red dot and see the X  reading is supposed to be roughly 1920.
2. Run the same export on actual iPhone 13 Mini and see the the X reading is roughly 1999.

iPhone 13 Mini running OS 16.6 and 15.3.1 can be accessed from AWS device farm https://aws.amazon.com/device-farm/device-list/

[f41330ff-4ef1-412a-b154-41883556bed0](https://api.gamemaker.io/api/github/downloads/f41330ff-4ef1-412a-b154-41883556bed0)

**Comment by shichen85** [comment]
<img width="1346" alt="Screenshot_2023-12-05_at_12 31 29_PM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/1aed371a-3360-416a-93a3-f0e3d9aced3a">
![Simulator_Screenshot_-_iPhone_13_mini_-_2023-12-05_at_17 12 52](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/6de5ca41-b44d-41ba-848d-6fc42cdcfb41)

**Comment by shichen85** [comment]
![Simulator_Screenshot_-_iPhone_13_mini_-_2023-12-05_at_17 12 52](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/8197e740-6c36-4479-b679-793a56cbee66)

**Comment by searoopy** [comment]
i have same issue

**Comment by searoopy** [comment]
When will this bug be fixed?

**Comment by searoopy** [comment]
There is also a problem with device_mouse_y_to_gui() when in portrait mode

Occurs on iPhone 12,13 mini

**Comment by searoopy** [comment]
ide 23.8 ,runtime 23.8 works fine, but the
but since 23.11, I've been experiencing this problem

**Comment by YYDan** [comment]
Note that the other duplicate reports say that this is not specific to the iPhone 13 mini, and indeed that all iPhones back to 6 show this issue when in _portrait_ mode specifically.

I have amended the title again to show we have received this message and do not need a fourth report over the holiday period...

**Comment by searoopy** [comment]
This is a problem in gamemaker since runtime 23.11, as it worked fine in gamemaker runtime 23.8.

Not an ios issue

**Comment by searoopy** [comment]
If you use device_mouse_y_to_gui, you can use the
the return value is appended with an offset value.

**Comment by shamusl** [comment]
Also having this problem. Tested in virtual devices as well as real physical devices. All iOS builds experiencing this problem in portrait. Does anyone know a workaround? I need this issue fixed to hit a deadline.

**Comment by jackerley** [comment]
@shichen85 I haven't been able to confirm on an iPhone 13 Mini, but I have found and fixed what looks like a related issue with zoom, I'm fairly certain it'll be the same root cause. Could you check in the next beta and confirm that this is fixed?

**Comment by shichen85** [comment]
@jackerley Just tested and can confirm that 2024.200.0.486 fixed this issue on iPhone 13 mini

**Comment by YYDan** [comment]
The zoom fix mentioned above is https://github.com/YoYoGames/GameMaker-Bugs/issues/4304
