### ISSUE TITLE
The audio emitter count returned by debug_event("ResourceCounts") includes deactivated emitters

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#2395]
### Description

Run the included project, press space to change room, press tab to display resource counts, there will be 3 audio emitters, press space to return to the first room. Press tab again and the emitter count will still be at 3 despite the emitters having been freed.

Red runtime 9.9.1.642
[incfilestest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13600994/incfilestest.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in IDE v2024.200.0.451  Runtime v2024.200.0.461
