### ISSUE TITLE
User script assets are still numbers, not refs

### ISSUE THREAD

**Issue by BackYard321** [YoYoGames/GameMaker-Bugs#2397]
### Description

As of 2023.8, user scripts are supposed to appear as refs, rather than numbers, but still appear as numbers even as of 2023.11. 

According to #1105 (typed handles p1):

> This affects DS structs, Objects, Sprites, Sounds, Rooms, Backgrounds (tilemaps), Paths, **Scripts**, Fonts, Timelines, Tiles (tilesets), Shaders, Sequences, AnimCurves, Instances and Particle Systems, so please be aware that your code may now need fixes before it will work in 2023.8 if you have actually had invalid function calls all along and old versions didn’t tell you

I've previously brought this bug to light, filed a bug as requested, and have been told multiple times that it has already been fixed/will be fixed in this version. However, I'm worried that it's gotten lost in the shuffle, as it isn't. It's been raised and responded to [here](https://forum.gamemaker.io/index.php?threads/2023-8-release-thread.105622/page-3#post-637330), [here](https://github.com/YoYoGames/GameMaker-Bugs/issues/1695), and [here](https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1112#issuecomment-1809835481). 

### Steps To Reproduce

1. Start GameMaker
2. Create a script (`Script1`)
3. In the script asset, write `show_message(Script1)`
4. The script will appear as a number, not a ref. `asset_get_type(Script1)` will also return `-1`, not `asset_script`.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

This is present in 2023.11.0.157 and all earlier versions of GM.

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project
[script refs.ZIP](https://github.com/YoYoGames/GameMaker-Bugs/files/13602147/script.refs.ZIP)

**Comment by rwkay** [comment]
OK the issue here is that the script has not been parsed fully and it is not recognised.... if you had a second script file (and that came second in the YYP list) then it works...

I will revisit this for 2024.2 so that ALL script references are found correctly

**Comment by BackYard321** [comment]
> OK the issue here is that the script has not been parsed fully and it is not recognised.... if you had a second script file (and that came second in the YYP list) then it works...
> 
> I will revisit this for 2024.2 so that ALL script references are found correctly

Hm, I'm trying to reproduce what you're talking about with the second script file, but I still see the scripts I try it with showing up as numbers. I _can_ pass a string with a script name into `asset_get_type()` and it will return `6` (corresponding to the constant `asset_script`), but obviously no such luck with the script itself.

**Comment by BackYard321** [comment]
> [Fixed-script-refs.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13619089/Fixed-script-refs.zip)
> 
> This project has been hand crafted and works on 2023.11 as released... but there is an issue as it relies on the fact that Script1 has been parsed first in a separate file from the reference... I will keep this bug here so that it gets fixed in2024.2

Ah I see, yeah I can recreate this in my project and I get the same result as you!

Looking forward to this, as I'd like to create a helper script that uses `is_callable()` but specifically excludes numbers, to differentiate methods/script refs from numbers that only _correspond_ to scripts.

**Comment by rwkay** [comment]
Fixed for 2024.2 - I think I have sorted it now so that no matter the parsing order then the script is recognised and turned into a handle.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.200.0.451  Runtime v2024.200.0.461

**Comment by backYard321** [comment]
> Fixed for 2024.2 - I think I have sorted it now so that no matter the parsing order then the script is recognised and turned into a handle.

I'm seeing this cropping up again as of the 2024.4 monthly
