### ISSUE TITLE
In-Game: Left and right mouse buttons cannot always be pressed at the same time in 2023.11.0

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2400]
### Description
As of 2023.11, GameMaker can no longer detect the left and right mouse buttons being pressed simultaneously. Having the left mouse button pressed will cause the right mouse button to always count as not being pressed. The issue is only for right + left, the middle mouse button and other mouse button combinations have no issue.
This issue does not happen in 2023.8, so it's a new problem. Also not a problem with my mouse, since the same issue exists for two others that I've talked to.

### Steps To Reproduce
Add this code and try pressing both mouse buttons at once
```
if mouse_check_button(mb_right) and mouse_check_button(mb_left) {
    show_message("This message cannot appear");
}
```
The message will not appear.

[d18e2e1d-b44d-47c9-9275-7c87887fa071](https://api.gamemaker.io/api/github/downloads/d18e2e1d-b44d-47c9-9275-7c87887fa071)

**Comment by Motivaetdclock** [comment]
patient zero of this issue going through

**Comment by scott-dunbar** [comment]
[mouse_woes.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13612805/mouse_woes.zip)
Complete sample showing issue with events and mouse states
