### ISSUE TITLE
UI/UX: Shortcut commands are still activated when renaming assets or image layers in 2023.11.0

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#2413]
### Is your feature request related to a problem?

Yes, currently in the latest version if you create a new asset and you name it anywhere with a capitol O, it will immediately stop naming your asset and open explorer.

### Describe the solution you'd like

The default should have followed the rest of the short cut keys to be `ctrl` + `shift` + `o`

### Describe alternatives you've considered

I myself have done this, but not everyone will know how

### Additional context

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/811123/0798b1bc-34de-413a-bf85-371585b426b5)

**Comment by SmithTom6304** [comment]
The underlying problem that Dan mentioned has now been fixed. We've added a property to the shortcut system to track when the user is editing text, and we disable any shortcuts that may interfere with text editing when that property is set. Any shortcuts with either no modifier, or just shift as a modifier, should now not execute when editing a label in place (such as renaming a resource).
This property is currently only being set when editing a label. We'll want to set this property for other parts of the IDE (such as text boxes or the Code Editor), but as those gadgets don't have any default shortcuts that will cause this problem we've decided to leave those until 2024.2, so as to reduce the scope of this hotfix.

**Comment by scott-dunbar** [comment]
This issue still occurs as described, tested in  IDE v2023.11.1.122  Runtime v2023.11.1.158

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.11.1.123  Runtime v2023.11.1.159, thanks.

**Comment by michael-mcmullen** [comment]
@YYDan @caitlinrmcintyre could you also ensure the context of the shortcut `shift` + `A` when naming a sprite has been fixed.. If you are naming a sprite and you have the sprite window up and name it `spr_Apple` it will create a frame even though it should not.

**Comment by YYDan** [comment]
Hi @michael-mcmullen - as per Tom's comment above, the fix in 11.1 only applies to renaming via editing a label gadget, in response to a couple of very specific circumstances that were reported to us last week.

We can confirm that your issue still happens even with this fix, so we have reopened this one now. Will get another fix added for renaming via text boxes.
