### ISSUE TITLE
Room Editor: Using ALT+RMB to place multiples of an instance in the room does not work when other instances are on the same space

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#2414]
### Description
On IDE v2023.11.0.121  Runtime v2023.11.0.157. 

In the room editor, it should be possible to position multiple instances of an asset by dragging the asset into the appropriate layer, holding ALT and then clicking the RMB to position the instance. 
However, when doing this, if there is another instance in the same space where we want to position the new instance, on clicking the older instance gets selected instead. 

Please see the video attached. 

This does not happen in the LTS version.

### Steps To Reproduce
1-Import the project attached
2-Open the room
3-While holding ALT, drag one of the objects into the room editor
4-Try to position the object on top of an instance that's already in the room
5-Observe the issue

[b1e4b844-e2ba-48db-a8bf-6f7ec807e0d3](https://api.gamemaker.io/api/github/downloads/b1e4b844-e2ba-48db-a8bf-6f7ec807e0d3)

**Comment by SmithTom6304** [comment]
Fixed - an extra check for the Paint With Resource shortcut had been removed. The check has been added back, which has fixed the problem.
