### ISSUE TITLE
Inspector resizable panels are not working properly in monthly version

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2416]
### Description

I've used GameMaker 2023.11 latest beta .450 version and in that version if you have a for example long variable definition list, when opened it will drag your view to its latest entry so it will be at the bottom with full display, like in this image.
![Adsız](https://github.com/YoYoGames/GameMaker-Bugs/assets/90388654/25cbe644-bbb5-4104-82a8-59deb0fd7c24)

But in the monthly versions of GameMaker, when I repeat the same action it will not drag your view, just simply opens and goes below without the automatic drag, like in this image.
![resim_2023-12-08_163105997](https://github.com/YoYoGames/GameMaker-Bugs/assets/90388654/1331236d-9dcd-4602-97d2-52b39f8cb5f2)

Attached project with "o_kamera"
[inspector issue.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13614547/inspector.issue.zip)

### Expected Change

Automatic view drag when interaction with inspector panels

### Steps To Reproduce

1. Start GameMaker
2. Open inspector with a lot of variable definition items, like my "o_kamera"
3. Open the variable definition panel
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by yyalansavage** [comment]
Hi, looks like you just need to check Preferences->Inspector->Scroll category into view on expand  (this defaults to unchecked at present). ( Should also mention, there is a bug where the scroll-expand does not work if you have Preferences->General Settings-> Disable IDE transition animations checked - although default is checked for this)

**Comment by yyalansavage** [comment]
above commit fixes scroll-expand not working when IDE transition animations are disabled

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.460  Runtime v2024.200.0.477, thanks.
