### ISSUE TITLE
Android system back button not registering anymore

### ISSUE THREAD

**Issue by Bulletech** [YoYoGames/GameMaker-Bugs#2425]
### Description

The new monthly (IDE v2023.11.0.121 Runtime v2023.11.0.157) has broken checking for the Android system back button.

Code in a Key Press - Backspace event is not run, nor code in a Step event within `if (keyboard_check_pressed(vk_backspace)) {`

[package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13621540/package.zip)

### Steps To Reproduce

1. Start GameMaker
2. Target Android
3. Check for Backspace key press
4. Run the game
5. Note tapping system back button does nothing

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2023.11.1.123  Runtime v2023.11.1.159
