### ISSUE TITLE
Expression `(a ? b : c).id` work for desktop but crash on html5 plarform

### ISSUE THREAD

**Issue by ze0nni** [YoYoGames/GameMaker-Bugs#2426]
### Description

```
var __items_0 = { id: 42 }
var __items_1 = { id: 9001 }
show_debug_message(((random(10) == 0 ? __items_0 : __items_1)).id);
```

Runtime version: v2023.11.0.157
[Contact Us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13621614/Contact.Us.zip)

### Expected Change

Same behavior for all platforms

### Steps To Reproduce

- Put code in room creation code
- Run desktop
- Get debug message
- Run browser
- Get error

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2
