### ISSUE TITLE
Feather Reports Globals are Undefined When They Aren't

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#2434]
### Description

Feather reports things like:  
E GM1041 The type 'Undefined' appears where the type 'Real' is expected. obj_VolumeButtonPARENT : Step 33:46

However, when you track the error down, it's a global (in this case, global.MasterVolume) that is initialized immediately at the start of the game, in the Room Start, through a function called globals_ONE_TIME_INITIALIZE. It's about as explicit of an initialization as I can get, and it's been working for years now.

globals_ONE_TIME_INITIALIZE at line 355: 	global.MasterVolume = 0.25;

Also, I get "errors" from Feather for any globals that are initialized by Functions in said base Function, i.e.:

globals_ONE_TIME_INITIALIZE(){
  <does a bunch of Globals>
  _initializeABunchOfGlobals();_ -->causes false errors
}

Also, it apparently gives false-positive errors for Object variables that are set in a Parent's Create Event, if the chain of Parents is long enough. Opening the source of this "error" and going to the Create function often makes this "error" go away; I presume that triggers something in Feather that allows it to fully recurse.

I'd appreciate an option for Feather where I can turn it off, but use a hotkey or menu command for a deep-dive check of variables and other issues that takes real time but is _fully recursive_. 

I understand that Feather's probably working well for shallow-depth projects, but I make very heavy use of Parents, globals are initialized in nested functions, etc., and Feather doesn't work very well for my project's needs.

### Expected Change

Make Feather handle globals by presuming they're initialized, or fully-recurse them at startup. Object variables should be recursed to Ultimate Parents and failing before being marked as an error.

### Steps To Reproduce

1. Start GameMaker
2. Make globals that are initialized in Room Start through a Script that calls other Scripts, and also initialize some globals in the Scripts that are called. Make Object Parent chain > (6, I think- maybe 7-8) with an Object variable defined in Create and restart GMS.
3. Write code in that Object that's the child of many Parents that references the Globals and the Object variable.
4. See the issue
[yoyo_contact_us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13625299/yoyo_contact_us.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by mistletoe** [comment]
I'll see what I can do there, to provide you a simple example. I'm definitely not making this up, lol. Feather's utility is kind of borderline useless for me atm, because I have to wade through so many false-positives to actually see valid errors.
