### ISSUE TITLE
Manual Content: Pipe "|" character support as a JSDoc types-separation character is not documented

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2439]
### Description
JSDocs supports the concept of defining multiple types for a given parameter by listing the types separated by a pipe character, as in:

/// @param    {real|string}      val1      A real or a string.

This feature does seem to be fully supported by the GameMaker code editor even though it isn't documented in the manual.

This opens up a conflict with the snippet system that uses pipe characters to identify the range of text that is selected when a snippet is inserted into the code editor, as in:

Z - MyParamSnippet: /// @param    {real|string|bool}    val1    A string, a real or a bool.

When this snippet is inserted into the code editor, the word "string" will end up being highlighted and the pipe characters will not be part of the inserted text.

### Steps To Reproduce
(1) Add the following snippet to the snippets.txt file:
Z - MyParamSnippet: /// @param    {real|string|bool}    val1    A string, a real or a bool.

(2) Launch GameMaker
(3) In the code editor, hit F4 to bring up the snippets and click on MyParamSnippet.
(4) Observe how, in the newly inserted text, the word "string" ends up getting highlighted and the pipe characters are not there.

[7494c987-a51e-4498-85c6-dc63aeff046b](https://api.gamemaker.io/api/github/downloads/7494c987-a51e-4498-85c6-dc63aeff046b)

**Comment by gurpreetsinghmatharoo** [comment]
To comment on part of this ticket, the | pipe feature has been added to the manual, so it will be documented with the next manual release

**Comment by gurpreetsinghmatharoo** [comment]
Comma can be used in place of pipe | for multiple arguments in a JSdoc comment, so please use that in your snippet and it should work (i.e. real,string,bool instead of real|string|bool)

**Comment by gurpreetsinghmatharoo** [comment]
@YYDan it's in the beta manual until the monthly release: https://manual.gamemaker.io/beta/en/#t=The_Asset_Editors%2FCode_Editor_Properties%2FJSDoc_Script_Comments.htm
