### ISSUE TITLE
Error : Extension *nameOfExtension* file does not exist

### ISSUE THREAD

**Issue by pixpnd** [YoYoGames/GameMaker-Bugs#2440]
### Description

Extensions are broken on 2023.11
IDE v2023.11.0.121
Runtime v2023.11.0.157

Adding any extensions cause "Error : Extension *nameOfExtension* file does not exist". Used GDKExtension as example. Projects with already added extensions also don't work. Everything is fine on older versions

[ExtensionBugTest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13627062/ExtensionBugTest.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create new project
3. Add any existing extension
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.455  Runtime v2024.200.0.467, thanks.

**Comment by 1-800-thewolf** [comment]
When is this patched version of Game Maker expected to be available for download?

> Verified fix in IDE v2024.200.0.455 Runtime v2024.200.0.467, thanks.

**Comment by caitlinrmcintyre** [comment]
@1-800-thewolf It should be in the current beta
