### ISSUE TITLE
Mac IDE: Suggest changing the keyboard shortcut for GameMaker→Settings... to Command-, as is expected for all macOS apps.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2450]
### Is your feature request related to a problem?

I often find myself hitting Command-, (comma) to try to open up the GameMaker Setting window.  This, of course, does not work with the GameMaker application because the keyboard shortcut assigned to the Settings... menu option is currently Shift-Command-P.  

Command-, is the expected keyboard combination to bring up the Preferences (i.e. settings) window in most if not all macOS desktop applications.

### Describe the solution you'd like

I suggest that this tradition be followed for the GameMaker application.  i.e. the keyboard shortcut for the GameMaker→Settings... menu option should be changed from Shift-Command-P to Command-, to stay within expected macOS norms.

### Describe alternatives you've considered

I've tried using the macOS keyboard shortcut system settings feature to change it, but that didn't work as I believe this feature only works on menu items that don't currently have an assigned shortcut.

**Comment by SmithTom6304** [comment]
Set the default preferences key to `⌘,` on Mac.
Also updated how `,` is displayed on mac - would previously be shown as `Comma`.

**Comment by alicemoretti** [comment]
Verified fixed onBeta IDE v2024.200.0.502 Beta Runtime v2024.200.0.519

Thank you.
