### ISSUE TITLE
Room Editor: Selecting and dragging multiple layers into a layer folder, moves only one layer

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#2452]
### Description
In the room editor, if multiple layers are selected in the layers panel and dragged into a layer folder, only one layer is moved into the folder.

### Steps To Reproduce
- open/create a room with a few layers
- create a new layer folder
- select multiple layers by shift/ctrl click, drag selection into the folder
- only one layer is moved into the folder
Note this is not a recent issue, also occurs in LTS v2022.0.1.31

[2711db2c-ed94-4fb0-9660-ed7c6d46acec](https://api.gamemaker.io/api/github/downloads/2711db2c-ed94-4fb0-9660-ed7c6d46acec)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.200.0.451  Runtime v2024.200.0.461, thanks.
