### ISSUE TITLE
Clean up xboxseriesxs GML Spec files and remove functions that are moved into extensions

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#2454]
### Which Extension are you reporting this issue for?

Steamworks

### Description

The xboxone_* functions defined in runtime-*/xboxseriesxs/GmlSpec.xml are now moved to [the GDK extension](https://github.com/YoYoGames/GDKExtension). Please consider removing them from the Spec file.

### Steps To Reproduce

1. Inspect the `runtime-*/xboxseriesxs/GmlSpec.xml` file
2. Search `xboxone_` and see that there are still function defintions

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Xbox (GDK)

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
The GDK Extension is windows only, it aims to allow exporting for the windows store. When selecting windows as export there shouldn't be a function collision because you are "disabling" the Xbox GML spec and vice versa 🤔

**Comment by shichen85** [comment]
> The GDK Extension is windows only, it aims to allow exporting for the windows store. When selecting windows as export there shouldn't be a function collision because you are "disabling" the Xbox GML spec and vice versa 🤔 in other words the functions were not moved to the extension, the windows version of the API (extension) is mimicking the Xbox one (Xbox runner), so porting is easier.
> 
> Unless I'm misunderstanding the problem

I see. Thanks for the clarification! Closing this ticket.

**Comment by YYDan** [comment]
Closing as No Change Required, given the conversation above.
