### ISSUE TITLE
Extension issue report template does not include the GDK extension

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#2455]
### Description

When creating issues for extension related topics, I cannot select the GDK extension. 

See: https://github.com/YoYoGames/GameMaker-Bugs/blob/07df4db349684da851c3b98984831450a2838f05/.github/ISSUE_TEMPLATE/extension_bug_report.yml?plain=1#L22

#2454

**Comment by YYDan** [comment]
Updated the contents of the dropdown now - as well as GDK, there were a few others we have published recently and so were not  listed in the template.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/545b490b-2ced-47ca-958c-a31c4edfdfa5)
