### ISSUE TITLE
In-Game: Disconnecting PS4 gamepad when another is connected disconnects both pads

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#2459]
### Description

When a second PS4 gamepad is connected while another is already in use, and the first one is then disconnected, both gamepads will be disconnected instead of only the first gamepad.

[input_test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13647943/input_test.zip)

### Expected Change

It is expected that only the first gamepad will be disconnected when the second one is.

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Connect PS4 gamepad
4. Connect a second PS4 gamepad
5. Disconnect the first PS4 gamepad
6. Scroll up console output until section on controllers disconnected is reached
7. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Unable to replicate on 2024.200 - I had 2 PS4 Controllers attaches and removing one of the devices only lost the single gamepad not both
