### ISSUE TITLE
Room Editor: Shift-clicking cancels "select from any layer" mode every time you do the command

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2463]
### Description
When trying to select and move around multiple instances on multiple layers in a row, shift click canceling select from any layer mode gets rather annoying, since you have to keep re-enabling it.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/56d39964-b098-495f-aa5a-08443658249d

### Steps To Reproduce
Click the select from any layer button in the room editor, then shift click anywhere in the room window. Select from any layer mode will get cancelled.

[e9f9d225-1388-48ec-a83e-001cbba256d4](https://api.gamemaker.io/api/github/downloads/e9f9d225-1388-48ec-a83e-001cbba256d4)

**Comment by nullbunny** [comment]
Any chance to get this bug added to milestone 2024.2 again? It adds a lot of friction to level production.

**Comment by SmithTom6304** [comment]
Should now be fixed. There was also an issue with multi-select not working on mac, which should also now be fixed.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.541  Runtime v2024.400.0.560. 

Thank you.

**Comment by KormexGit** [comment]
This was not actually fixed (or if it was fixed it got un-fixed again), see #5605

**Comment by SmithTom6304** [comment]
A fix has gone in for #5605, so this can be closed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.4.0.135  Runtime v2024.4.0.167, thanks.

**Comment by mmMarzban** [comment]
It is not fixed completely. After a few times of shift-selecting, it randomly gets disabled at some point.
