### ISSUE TITLE
Android project targetting API 16 will fail to compile if lint checking is turned on

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#2466]
### Description

The error comes from 596                 case MotionEvent.ACTION_BUTTON_RELEASE:
 597                     int button = event.getActionButton();    

![Screenshot_20](https://github.com/YoYoGames/GameMaker-Bugs/assets/1914610/f7418374-f6b1-49dd-8979-be374482e2ca)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.200.0.451  Runtime v2024.200.0.461
