### ISSUE TITLE
Room Editor: Multiple bugs introduced by the 2023.11.0 release

### ISSUE THREAD

**Issue by HugoBDesigner** [YoYoGames/GameMaker-Bugs#2469]
### Description

This last update (IDE v2023.11.0.121) introduced many issues to the Room Editor that just weren't present in the previous version. My best guess is that some sort of revamp or reworking of the Room Editor is taking place, especially with regards to user input (keyboard and mouse), since a lot of the mentioned issues seem to relate to it.

Some issues include:
## 1. Using Ctrl+Arrow keys for pixel-perfect object manipulation is no longer functional
When placing objects in a room, it used to be possible to hold the Ctrl key, and using the arrow keys, manipulate an object's position pixel by pixel. That is no longer the case: the object is simply moved within its layer's grid units. The only alternatives are to either Ctrl+Mouse drag the object into position (which is fiddly and unwieldy), or manually tweak the object's X/Y coordinates in its properties.

https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/5304482b-30fd-41e1-a7a9-a6ede7d36db5

## 2. Using Alt+Click to place an object will select an object instead
If trying to place an object in a room via Alt+Clicking, and there happens to be another object in that position, the editor will instead select that object. In previous versions, it just let you place the object on top of the previous one, which was especially useful when handling multiple decorations and mechanics occupying the same region.

https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/fb126dd7-398a-4a57-b23a-78438768b261

## 3. Tile rotation/flipping does not happen unless the Room Editor tab is highlighted
In the past, selecting a tile or group of tiles from the Tiles tab, then moving your cursor over to the room editor and then applying a transformation (flipping horizontally with X, vertically with Y, or rotating with Z) would behave as expected. In the current version, you need to click somewhere in the room's tab first, before rotating. This is somewhat manageable when I middle click with my mouse (which doesn't add or remove tiles), but when working on my laptop's touchpad, this becomes an issue (it lacks scroll wheel features).

https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/7459d36f-1e66-4928-b37f-95911d4c2aec

### On occasion, the Rectangle tile tool will not work
I have not managed to find a reliable way to reproduce this bug, but the Rectangle tile tool simply did not function until GameMaker was restarted. This happened right after updating the IDE and after importing a project.

https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/d5c7bb1b-e61f-4f9d-b48b-34dc493620e0

### "Fatal Error: GameMaker has become unstable."
After working for a while, especially on large rooms and projects, GameMaker gives a warning regarding the program becoming unstable and needing to be restarted. This hasn't caused any issues yet (beyond losing a few seconds to restart the program), but it has become a workflow problem when it happens too often. I had never encountered this error before the latest update.

![GameMaker_2023-12-13_10-53-47](https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/64e3cae7-3e18-45a1-9c50-0a939e272cf9)

### Tile selection becomes impossibly laggy
Much like the previous bug, this one happens only after having a large room/project open for a while. GameMaker will take longer and longer to process tile selection, until it straight up freezes the program. Restarting GameMaker fixes the issue for the following few minutes. This issue has existed before this update.

https://github.com/YoYoGames/GameMaker-Bugs/assets/6296061/e7f8b44e-7b87-4b63-aef8-cf55331ac5c6

### Tile/object placement might skip a click
This is a very minor issue and doesn't happen often, but on occasion, placing a tile/object will not happen unless you click twice. Especially with tile placement, it'll only skip the first tile you try to place, but maintaining the mouse button pressed will place all other tiles normally. My best guess is that this is an issue of window/tab focus.

<hr>

If it's easier/better for the team, I can split this issue into individual ones.  

### Steps To Reproduce

Details on how to reproduce each issue are described above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by L-Clouds** [comment]
Some of your many listed issues are already accounted for: #2410 #2414 #2464 #2129

The others might be new to this report.

**Comment by iampremo** [comment]
In the future please only report one bug per report

**Comment by stuckie** [comment]
I've taken the contact-us package off the original description and uploaded it to our private drive here:
https://drive.google.com/file/d/1B8tQRyLAppRJ_3WgPu-Dt4YmtJ70KRKN/view?usp=drive_link

If you need to send us projects and want to keep them private, you can set it up to request authorisation, and you can approve our access when required.

**Comment by nullbunny** [comment]
Regarding the unstable message, I ran into this problem too. My project has been around for a bunch of versions, yours looks like it might have too. What solved it for me was this:

1. I deleted the GameMaker files from AppData/Local(Low) and /Roaming.. I had to set up configs and stuff again but getting rid of the issue was worth it.
2. I deleted all files from my project (using Git) and then checked using VSCode - a bunch of old, orphaned files were left. I undid the changes via Git and then manually deleted the orphans from my project. Not sure how much this contributed to it, but I guess it was a simple way to clean up any potential issues.

Ever since the Room Editor hasn't caused my project to go unstable anymore.

**Comment by stuckie** [comment]
I'm going to tentatively close this off now, as it seems that all issues in here have been fixed now ( at least from the testing I've just done )
It's hard to get a good gauge of this though as this issue has multiple bugs within, so if there are still issues, please keep to a one issue per ticket as it makes it much easier to fix and verify against.

Thanks.

**Comment by caitlinrmcintyre** [comment]
Verified fixes in IDE v2024.400.0.544  Runtime v2024.400.0.563, thank you.
