### ISSUE TITLE
Can Not import an image to a sprite

### ISSUE THREAD

**Issue by xieyunbin** [YoYoGames/GameMaker-Bugs#2476]
### Description
I have update to the lastest stable version. 
The image is PNG. After I upload a trail to git and try to download an older version of my project, the importing image function is failed. 
And I have try to restore to another version on git but the bug is still here.
I have try to restart to project and computer.
I have delete the project and download it cleanly from git,
But all I do is useless.

Please tell me how to fix the bug. Thanks

[1aba4a6c-d965-4a55-a1fc-18cf61269fce](https://api.gamemaker.io/api/github/downloads/1aba4a6c-d965-4a55-a1fc-18cf61269fce)

**Comment by stuckie** [comment]
If you have downloaded a previous version of your project over the existing one, then it will have correctly overwritten your changes.
If you are needing to compare the versions, you will need to clone your project to another directory.

Should you still have issues, can you please resubmit the bug report with clear reproduction steps and a project, so we can see where it is failing.
