### ISSUE TITLE
Building Projects: [Android] Default icon still used after Game Options values changed manually or by Generate Project Images

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#2486]
### Description

If a user uses the "generate project images" tool or sets all of a project's android icon images to new images, upon running the project the default icon images are still used. This is even though the user can see the generated images in the "..options\android\icons" folder for the project

This was found on an up to date Pixel 7 Pro then was also found to be an issue using the emulator

### Expected Change

android icon images set

### Steps To Reproduce

1. Start GameMaker
2. create a brand new project
3. go to "tools -> generate project images"
4. upload images for icon and images and press generate
5. go to "game setting -> Android - Icons"
6. the newly generated images can be seen
7. go to the project direct and look for the "..options\android\icons" folder
8. there will be a rand of images sizes all using the new icon image
9. run the project targeting either an android device or emulator
10. once the game has ran go to the home page and the list of installed apps
11. the icon will be the original default gamemaker image
12. uninstall the app on the device/emulator
13. go to "game setting -> Android - Icons" and manually change the images
14. clean the project and rerun
15. find the app on the device/emulator icon again, it will still be default

contact us package - [iconimageissue.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13675321/iconimageissue.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly), 2022.0.2 (LTS), Beta (Beta IDE v2023.1100.0.450  Runtime v2023.1100.0.459)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
possibly linked to #1082

**Comment by mgeddesGM** [comment]
after reading the manual this was found to be as expected.
Latest android uses the images in the adaptive icons section. Either by adding manually or using the generate tool there

https://manual.gamemaker.io/monthly/en/#t=Settings%2FGame_Options%2FAndroid.htm&rhsearch=%22adaptive%20icons%22

**Comment by jackerley** [comment]
as above
