### ISSUE TITLE
I Cant Run My Project

### ISSUE THREAD

**Issue by Sui091** [YoYoGames/GameMaker-Bugs#2487]
### Description

I cant run (test) my project. Same problem occurs in all projects (even in an empty project). I have been using Gamemaker Studio for a long time, I was working on a project and when I clicked run to test it, it suddenly did not run and the output said FAILED: Run Program Complete. Since that moment, I have not been able to test any of my projects. I am using the latest version of gamemaker. I tried change the runtime, reinstall the game, delete my virus program but its still dont working. 

### Expected Change

I will be able to run my projects

### Steps To Reproduce

1. open gamemaker studio
2. choose the latest runtime
3. try to run anyproject
4. see this issue 

[a.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13677655/a.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

**Comment by Sui091** [comment]
> It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

I did everything on your guide its still not working
