### ISSUE TITLE
Run or debugger doesn't work on Switch

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#2488]
### Description
Hi,
if i create a build all is fine but if i try to run from the ide or using the debugger the ide return a failed.

### Steps To Reproduce
7 Compressing texture... writing texture Default_0.yytex... 
8 Compressing texture... writing texture Default_1.yytex... 
9 Compressing texture... writing texture Default_2.yytex... 
10 Compressing texture... writing texture Default_3.yytex... 
11 Compressing texture... writing texture Dungeons_0.yytex... 
12 Compressing texture... writing texture House_0.yytex... 
13 Compressing texture... writing texture Menus_0.yytex... 
14 Compressing texture... writing texture Menus_1.yytex... 
15 Compressing texture... writing texture Mountains_0.yytex... 
16 Compressing texture... writing texture Mystic_0.yytex... 
17 Compressing texture... writing texture UI_0.yytex... 
18 Compressing texture... writing texture WaterRuins_0.yytex... 
J:\GMS2_Projects\SVN_CONSOLE_MONSTER_TRIBE\Monster Tribe\extensions\libWebMPlayer\iOSSource\..\post_textures.bat
Writing Chunk... AUDO size ... 3.65 MB
Writing Chunk... SCPT size ... -0.00 MB
Writing Chunk... DBGI size ... 0.05 MB
Writing Chunk... INST size ... 1.95 MB
Writing Chunk... LOCL size ... 0.03 MB
Writing Chunk... DFNC size ... 0.12 MB
Writing Chunk... STRG size ... 0.02 MB
Writing Audio Group audio_gameSFX
Writing Audio Group audio_Music
Writing Audio Group audio_menuSFX
Stats : GMA : Elapsed=8924.322
Stats : GMA : sp=982,au=83,bk=71,pt=0,sc=1134,sh=9,fo=1,tl=0,ob=655,ro=119,da=2,ex=1,ma=51458,fm=0xD840B39D7D6E2BB4
8
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\ImportNintendoSdk.props to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\ImportNintendoSdk.props...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\NexVcProjectSettings.local.props to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NexVcProjectSettings.local.props...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\NplnVcProjectSettings.props to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NplnVcProjectSettings.props...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\Source.cpp to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\Source.cpp...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\VCTemplate.nnsdk.xml to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.nnsdk.xml...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\VCTemplate.sln to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.sln...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\VCTemplate.vcxproj to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.vcxproj...
Copying C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389\switch\VCTemplate\VCTemplate.vcxproj.filters to J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.vcxproj.filters...
C:\Windows\system32\cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" && J: && cd "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch" && msbuild /m:%NUMBER_OF_PROCESSORS% "VCTemplate.sln" /p:Configuration=Release /p:Platform=NX64 /t:build /verbosity:normal"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.32
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
Microsoft (R) Build Engine versione 16.11.2+f32259642 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

Compilazione avviata 15/12/2023 03:14:01.
     1>Progetto "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.sln" sul nodo 1 (destinazioni: build).
     1>ValidateSolutionConfiguration:
         Compilazione della configurazione di soluzione "Release|NX64" in corso.
     1>Compilazione di "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.vcxproj" (2) dal progetto "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.sln" (1) sul nodo 1 (destinazioni predefinite).
     2>PrepareForBuild:
         Creazione directory "NX64\Release\".
         Creazione directory "NX64\Release\VCTemplate.tlog\".
       InitializeBuildStatus:
         Creazione di "NX64\Release\VCTemplate.tlog\unsuccessfulbuild". � stato specificato "AlwaysCreate".
       ClCompile:
         C:\Nintendo\NintendoSDK\NintendoSDK\\Compilers\NX\nx\aarch64\bin\clang++.exe 
         Source.cpp
       Link:
         C:\Nintendo\NintendoSDK\NintendoSDK\\Compilers\NX\nx\aarch64\bin\clang++.exe -nostartfiles -Wl,--gc-sections -Wl,-init=_init,-fini=_fini -Wl,-pie -Wl,-z,combreloc,-z,relro,--enable-new-dtags -LJ:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch -LC:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release -Wl,--start-group C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/rocrt.o C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/nnApplication.o  NX64/Release/Source.o C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/libopenssl.a C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/libcurl.a J:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch/YYSwitchNEXLibStub.a J:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch/YYSwitchNPLNLibStub.a J:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch/SwitchRunner.a C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/libnn_init_memory.a C:/Nintendo/NintendoSDK/Nintendo
SDK/Libraries/NX-NXFP2-a64/Release/libnn_gfx.a -Wl,--end-group -Wl,--build-id=sha1 -Wl,-T C:/Nintendo/NintendoSDK/NintendoSDK/Resources/SpecFiles/Application.aarch64.lp64.ldscript  -Wl,--start-group C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/opengl.nss C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/multimedia.nss C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/nnSdk.nss -Wl,--end-group C:/Nintendo/NintendoSDK/NintendoSDK/Libraries/NX-NXFP2-a64/Release/crtend.o -fuse-ld=lld.exe -Wl,-Map=J:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch/NX64/Release/VCTemplate.map -Wl,--dynamic-list=C:/Nintendo/NintendoSDK/NintendoSDK/Resources/SpecFiles/ExportDynamicSymbol.lst -o J:/GMS2_Temp/GMS2TEMP/Monster_Tribe_17AED85D_VM/switch/NX64/Release/VCTemplate.nss -fdiagnostics-format=msvc
       MakeNso:
         MakeNso J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nss J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nso
         VCTemplate.vcxproj -> J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nso
       MakeMeta:
         C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\MakeMeta\MakeMeta.exe --desc C:\Nintendo\NintendoSDK\NintendoSDK\Resources\SpecFiles\Desc\NX-NXFP2-a64\Application.autogen.desc --meta C:\Nintendo\NintendoSDK\NintendoSDK\Resources\SpecFiles\Application.aarch64.lp64.nmeta -o J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.npdm -d DefaultIs64BitInstruction=True -d DefaultProcessAddressSpace=AddressSpace64Bit
         VCTemplate.vcxproj -> J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.npdm
       ExeDeploy:
         Finalize 
         Unable to create hard link for C:\Nintendo\NintendoSDK\NintendoSDK\Libraries\NX-NXFP2-a64\Release\nnSdk.nso, so copied it instead.
         Unable to create hard link for C:\Nintendo\NintendoSDK\NintendoSDK\Libraries\NX-NXFP2-a64\Release\nnrtld.nso, so copied it instead.
         VCTemplate.vcxproj -> J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd_root
       FinalizeBuildStatus:
         Eliminazione del file "NX64\Release\VCTemplate.tlog\unsuccessfulbuild" in corso.
         Aggiornamento timestamp di "NX64\Release\VCTemplate.tlog\VCTemplate.lastbuildstate".
     2>Compilazione progetto "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.vcxproj" (destinazioni predefinite) completata.
     1>Compilazione progetto "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\VCTemplate.sln" (destinazioni: build) completata.

Compilazione completata.
    Avvisi: 0
    Errori: 0

Tempo trascorso 00:00:02.33

C:\Windows\system32\cmd.exe DONE (0)
C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\MakeMeta\MakeMeta.exe --desc C:\Nintendo\NintendoSDK\NintendoSDK/Resources/SpecFiles/Application.desc --meta "J:\GMS2_Projects\SVN_CONSOLE_MONSTER_TRIBE\Monster Tribe\options/switch/application.nmeta" -o "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd\program0.ncd\code\main.npdm"

C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\MakeMeta\MakeMeta.exe DONE (0)
C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\AuthoringTool\AuthoringTool.exe createnspmeta -o "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd" --meta "J:\GMS2_Projects\SVN_CONSOLE_MONSTER_TRIBE\Monster Tribe\options/switch/application.nmeta" --type Application

C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\AuthoringTool\AuthoringTool.exe DONE (0)
C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\AuthoringTool\AuthoringTool.exe createnspd -o "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd" --meta "J:\GMS2_Projects\SVN_CONSOLE_MONSTER_TRIBE\Monster Tribe\options/switch/application.nmeta" --type Application --desc C:\Nintendo\NintendoSDK\NintendoSDK/Resources/SpecFiles/Application.desc --program "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd\program0.ncd\code" "J:\GMS2_Temp\GMS2TEMP\Monster_Tribe_17AED85D_VM\switch\NX64\Release\VCTemplate.nspd\program0.ncd\data"

C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\AuthoringTool\AuthoringTool.exe DONE (0)
Igor complete.
C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\RunOnTarget.exe "C:\Nintendo\NintendoSDK\NintendoSDK\TargetTools\NX-NXFP2-a64\DevMenuCommand\Release\DevMenuCommand.nsp" -- debug set-fs-access-log-mode log+sdcard
[ERROR] Failed to execute command.
[ERROR]    Command(LaunchApplicationCommand) failed(nn::Result=0x001FD602)
Exit( Result: Failure, ExitKind: FailedToControlTarget , ErrorName: FailedToCommand, Message: Command(LaunchApplicationCommand) failed(nn::Result=0x001FD602) )

C:\Nintendo\NintendoSDK\NintendoSDK\Tools\CommandLineTools\RunOnTarget.exe exited with non-zero status (1)
elapsed time 00:00:32.1754046s for command "C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.600.0.389/bin/igor/windows/x64/Igor.exe" -j=8  -options="J:\GMS2_Temp\GMS2TEMP\build.bff" -v -- Switch Run started at 12/15/2023 03:13:36
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

[fa9ad50e-e19d-4473-b73f-c182c7f90516](https://api.gamemaker.io/api/github/downloads/fa9ad50e-e19d-4473-b73f-c182c7f90516)

**Comment by jackerley** [comment]
Can you try updating the firmware on your Switch? From checking that error code on the forums, it would seem that that is the likely cause.

Thanks,
Fritz

**Comment by batblaster** [comment]
The switch firmware is at the same as the SDK required by GMS that is 16, to update to 17 i need to change SDK too i guess do you think it will work ?

**Comment by jackerley** [comment]
Hmm, if it's the one that is included with the SDK that should be ok, can you run one of the Nintendo samples on your Switch from the Visual Studio .sln?

**Comment by batblaster** [comment]
OK i updated the SDK creating a new environment and now i have updated the switch. It seems to work.
Fritz always thanks for your amazing support.
Francesco

**Comment by jackerley** [comment]
Happy to help!
