### ISSUE TITLE
mouse_clear() seems like not working properly

### ISSUE THREAD

**Issue by SussyGuy35** [YoYoGames/GameMaker-Bugs#2497]
### Description
as the title say

[6585196f-415e-47c6-b769-253552838735](https://api.gamemaker.io/api/github/downloads/6585196f-415e-47c6-b769-253552838735)

**Comment by SussyGuy35** [comment]
also io_clear() i think
have not test keyboard_clear()

**Comment by SuperHebbe** [comment]
I think mouse_clear() is working as it should. It sets the button state to 0 as normal.
Seems more like the mouse_check_button_pressed() forgets to check the state of the mouse button, or some other stuff.

Hope this will be fixed soon :)

**Comment by Luxorix** [comment]
A new release has been released, but the mouse still doesn’t work. When can we expect a solution to this mega-important problem?

**Comment by yoyo-danielc** [comment]
Fix merged into 2024.04 branch.

For QA:

Test project attached, would probably be worth someone with a (multi)touch-capable Windows device giving it a quick test to make sure it works as it should.

[input_mouse.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14571835/input_mouse.zip)

**Comment by cameron-home** [comment]
Verified fixed in Windows in IDE v2024.400.0.539  Runtime v2024.400.0.558

**Comment by jackerley** [comment]
GMRT: mouse_clear doesn't appear to do anything. I'm not 100% sure how the sample project is supposed to work but if you hold down left mouse until mouse_clear call on GMS2 runtime then it stops generating events, on GMRT it continues generating events
