### ISSUE TITLE
Estou com problemas de executar o jogo

### ISSUE THREAD

**Issue by Quinn109** [YoYoGames/GameMaker-Bugs#2505]
### Description

quando eu clico em "executar" a janela do jogo nn abre

### Expected Change

q eu consiga executar o jogo

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Unfortunately, without the contact-us package (which was not attached, despite the box being ticked), there's nothing we can look into for you.

However, if clicking Run inside GameMaker does nothing, then this is almost certainly an antivirus or OS permissions issue for you to fix in your machine setup - please see [our permissions guide](https://help.yoyogames.com/hc/en-us/articles/360022953052#_ga=2.234191582.1130865552.1702899449-261290497.1702899449) for the information you will require.
