### ISSUE TITLE
Code Editor: GM crash when pasting text with Shift+Insert after using Shift+Delete to cut it

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#2509]
### Description
Just happened twice in a row.
I am in a code editor, hit Shift+Delete to cut a line, and then Shift+Insert to paste it back a few lines below.

A command window pops up for a fraction of a second saying something like "Writing..." (too fast to read) and then gamemaker crashed.

### Steps To Reproduce
edit a script file
select an entire line by having cursor at the left edge, select with shift+arrowDown
hit shift+delete to cut a line
move some lines up or down
hit shift+insert to paste the line
crash!

[114396d5-b321-400d-afeb-059b9b3ff719](https://api.gamemaker.io/api/github/downloads/114396d5-b321-400d-afeb-059b9b3ff719)

**Comment by YYDan** [comment]
This is probably due to Shift+Delete not actually copying anything during those repro steps (see the linked issue above) - guessing some bad memory was attempted to be pasted and that's what caused the crash.

**Comment by Grisgram** [comment]
Thanks for trying - i can confirm what you say. it pastes _something_ 

When i opened the issue i tried it several times in a row, crashed every time. but maybe i didn't refresh the clipboard, so yes, maybe i just had garbage (an image?`) in the clipboard.

**Comment by YYDan** [comment]
Oh, most definitely ;)

**Comment by SmithTom6304** [comment]
Fixed the underlying issue with `Shift + Delete` not cutting anything (see #2593). For now I've wrapped our CodeEditor paste logic in a try catch block which should hopefully shed some light on the actual crash, as like Dan I wasn't able to reproduce the crash itself.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.481  Runtime v2024.2.0.498.

Thank you.
