### ISSUE TITLE
Sequence Moments need clarification

### ISSUE THREAD

**Issue by tgalluzzo** [YoYoGames/GameMaker-Bugs#2513]
### Description

This page describes the various types of events, moments, etc. for Sequences. 
However, it isn't clear which object is in-scope when a moment script is called. Which object or instance is calling the moment? Which variables are in-scope? It would be helpful to clarify. 

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Sequences/Sequence_Events_Moments_Broadcast.htm

**Comment by gurpreetsinghmatharoo** [comment]
Just as a note here, the scope is the current Sequence Instance struct. Will be added to the docs soon.
