### ISSUE TITLE
Physics demos broken

### ISSUE THREAD

**Issue by peardox** [YoYoGames/GameMaker-Bugs#2531]
### Description
The Physics demo tutorials (apart from #3) all spawn way too many objects all at the same point - at least on a decent machine under Windows

HTML sorta worked
GXC complete failure

### Steps To Reproduce
Download demo code linked at end of tutorials....

https://gamemaker.io/en/tutorials/physics-in-gamemaker-studio-2-part-1
https://gamemaker.io/en/tutorials/physics-in-gamemaker-studio-2-part-2
https://gamemaker.io/en/tutorials/physics-in-gamemaker-studio-2-part-4

[25c62836-d6eb-40c3-9578-188cd4338f0c](https://api.gamemaker.io/api/github/downloads/25c62836-d6eb-40c3-9578-188cd4338f0c)

**Comment by jackerley** [comment]
option_game_speed is getting set to 0 when importing this .yyz, in the projects options/main/inherited/options_main.inherited.yy this is set to 60, think this is one for @stuckie

**Comment by peardox** [comment]
Trying a work-around by setting the speed in obj_Control like this...

```
show_debug_message(string("Speed = " + string(game_get_speed(gamespeed_fps))));
game_set_speed(60, gamespeed_fps);
show_debug_message(string("Speed = " + string(game_get_speed(gamespeed_fps))));
```
Output is....

Speed = 0
Speed = 60

but still no physics (well, gravity)

**Comment by jackerley** [comment]
Hi @peardox try setting it in Game Options->Main the project should start working then?

**Comment by peardox** [comment]
Yep - that fixes it

I'll go and update forum post in case anyone wants to know

https://forum.gamemaker.io/index.php?threads/physics-demos-broken.107829/

**Comment by stuckie** [comment]
A fix has been added to ProjectTool so that subsequent imports will work correctly.
