### ISSUE TITLE
camera_get_view_border_x and camera_get_view_border_y manual entries

### ISSUE THREAD

**Issue by quattj** [YoYoGames/GameMaker-Bugs#2534]
### Description

The manual entries for camera_get_view_border_x and camera_get_view_border_y are confusing.  They state
"This function can be used to retrieve the border value for object/instance following of the given camera along the y axis (vertical border)."
This sentence is poorly worded and does not make sense.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Cameras_And_Display/Cameras_And_Viewports/camera_get_view_border_x.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
