### ISSUE TITLE
Room Editor: Clicking an already selected instance does not bring it up in the inspector

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2535]
### Description
If you click an instance to select it in the room editor, it pops up in the inspector. However, if the inspector switches to something else while that instance is still selected, you can't bring the instance back into the inspector without de-selecting it or selecting something else first.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/31e6e7f9-b215-48ea-82d9-d59d37c17aeb

This is an annoyance when you're going back and forth between the room editor and code tabs, since clicking back to the room will always focus the inspector on the room itself, and you need to re-select the instance to bring it back into the inspector.

### Steps To Reproduce
Click an instance in the room editor. Click on something else, like the room tab, so the inspector swaps to that. Try to click the instance again, and it will not refocus the inspector to it until you de-select it and select it again.

[a0b3c72a-63ba-4a5d-a6ec-874709f24cc9](https://api.gamemaker.io/api/github/downloads/a0b3c72a-63ba-4a5d-a6ec-874709f24cc9)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.451  Runtime v2024.200.0.461, thanks.
