### ISSUE TITLE
Room Editor: Can't shift-click to select multiple instances with select from any layer mode enabled if on a tile layer

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2540]
### Description
Select from any layer mode does still work while a tile layer is selected, however shift + click + drag to select multiple instances does not work in this situation. I've had several times where I was very confused why it wasn't working until I realized I was on a tile layer. You also can't draw any tiles while select from any layer is enabled on a tile layer, which makes it easy to miss.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8c339aff-38ba-4f8f-ae2f-eeae6e89c34d

### Steps To Reproduce
In the room editor, select a tile layer. Enable select from any layer mode using the button in the top right of the room editor. Attempt to shift + click + drag. Nothing will happen.

[83f4822b-3bee-4aaf-b5aa-be8aef200d62](https://api.gamemaker.io/api/github/downloads/83f4822b-3bee-4aaf-b5aa-be8aef200d62)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.451  Runtime v2024.200.0.461, thanks.
