### ISSUE TITLE
Attempting to define a method in variable definitions results in a compile error

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2542]
### Description
If you try to set a variable in the variable definitions window to a newly declared method function, GameMaker gives a compile error, saying "Undefined variable 'function' referenced in Object's variable 'variable_name'"
Happens in every platform I tried (Windows and GX VM and YYC)

### Steps To Reproduce
Add a variable to the variable definitions window of any object. Select any type (I used expression, but same error for any other type). Set the value of the variable to something like function() {return true;}. Contents of the function doesn't matter. Attempt to run the game and you will get a compile error.

[4d605bbc-24cd-4e9f-a3a7-30b7e1b7e35d](https://api.gamemaker.io/api/github/downloads/4d605bbc-24cd-4e9f-a3a7-30b7e1b7e35d)

**Comment by thennothinghappened** [comment]
Bump :)

**Comment by rwkay** [comment]
Fixed in 2024.8 - excluded keywords from Object variable check

**Comment by cameron-home** [comment]
Verified fixed in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
