### ISSUE TITLE
Surface from video_draw is typeof "number" while regular surfaces are typeof "ref"

### ISSUE THREAD

**Issue by Alkapivo** [YoYoGames/GameMaker-Bugs#2543]
### Description

From version 2023.11 onward, the `typeof` function for a resource created by `surface_create` now returns String `ref` (previously it was `number`). In the case of a surface created by `video_draw()`, the `typeof` function returns String `number`.

I believe that a surface should always return the `ref` type, and the implementation of the surface created by `video_draw()` should be corrected.

### Expected Change

Surface from `video_draw` should be typeof "ref".

### Steps To Reproduce

[bug_video_surface_typeof.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13724692/bug_video_surface_typeof.zip)

1. Download `bug_video_surface_typeof.zip`
2. Unpack `bug_video_surface_typeof.zip`
3. Open `bug_video_surface_typeof.yyz`
4. Build & run project
5. Results should be visible on screen: Left side is rendering video and text with `typeof` video surface. Right side is rendering regular surface and text with `typeof` surface

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.200.0.451  Runtime v2024.200.0.461

**Comment by jackerley** [comment]
GMRT: video surface is returned as a number, surface is returned as an int32. Seems to be a problem across a number of asset creation functions - layer_create, surface_create etc
