### ISSUE TITLE
GX.Games: Attempting to access Included Files inside subfolders gives a JS exception

### ISSUE THREAD

**Issue by ringotf** [YoYoGames/GameMaker-Bugs#2560]
### Description
When using subfolders in the included files "datafiles" the gx.games runner throws a fatal exception in the browser console.

```
runner.js:4 Uncaught (in promise) TypeError: h.FS_createPath is not a function
    at d (runner.js:4:375)
    at Lb (runner.js:70:270)
    at Pm (runner.js:350:238)
    at Om (runner.js:347:478)
    at tb (runner.js:28:246)
    at a (runner.js:298:135)
    at runner.js:298:351
```

Example project attached. 
Works ok in windows and html5 but the GX.Games runner throws the error when trying to load the game.

### Steps To Reproduce
1. Start GameMaker, Select the GX.Games runtime, and run.
2. Wait for the browser window to open.
3. The game will fail to load correctly, open browser developer tools to see the exception.

[d9260d53-2363-4316-ae93-55c48ef7e881](https://api.gamemaker.io/api/github/downloads/d9260d53-2363-4316-ae93-55c48ef7e881)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.467  Runtime v2024.200.0.483
