### ISSUE TITLE
Enum example code in manual not following recommended naming rules.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2571]
### Description
According to the naming rules defined in Feather, enum names and members should be in all caps.  The enum example code shown in the manual show enum names and member variables in lowercase.  Recommend they be changed to uppercase to match standard Feather naming conventions.

Example manual page reference:
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FVariables%2FConstants.htm

[d0c96964-6274-4029-8156-eba99c790e4e](https://api.gamemaker.io/api/github/downloads/d0c96964-6274-4029-8156-eba99c790e4e)

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
