### ISSUE TITLE
Mouse stops functioning when unfocusing window.

### ISSUE THREAD

**Issue by Hmmmpf** [YoYoGames/GameMaker-Bugs#2581]
### Description

If you unfocus the window (minimization, tabbing out), while left mouse button is held down, the mouse update functions (except display_mouse_get_x/y) will stop functioning upon tabbing back in and using left click once. Once that click has been performed they will only work while left mouse button is held. This state can seemingly not be restored to normal without relaunching of the game.

A video of the bug can be found here https://www.youtube.com/watch?v=iyPTdXd9WQk
[mouseFailure.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13759849/mouseFailure.zip)

### Expected Change

Prevent the mouse from arbitrarily not working unless left mouse button is held if you tab out of the game while left mouse button is held.

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Hold left mouse button
4. Tab out
5. Tab back in
6. Click left mouse button once

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by KormexGit** [comment]
Just had a tester run into this one and also confirmed it myself, just tabbed out while holding left click, and after tabbing back in and clicking again the mouse would no longer move

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.200.0.454  Runtime v2024.200.0.466, thanks.
