### ISSUE TITLE
Some Events Stop Firing after Interacting with Dialog Extension

### ISSUE THREAD

**Issue by time-killer-games** [YoYoGames/GameMaker-Bugs#2586]
### Description

To quote my client:
```
i replaced 2023.11's runner with 2023.8's one
it worked fine
pretty sure this is a bug with gamemaker
```
So this is a recent problem created by 2023.11.x runtimes, and does not happen in older runtimes.

Basically, after creating a dialog with my dialog module extension, and going through a series of specific steps, some events, such as the right mouse button event, stop firing all together, for seemingly no reason.

### Expected Change

Events should always fire as intended.

### Steps To Reproduce

1. Start GameMaker
2. Open project: https://drive.google.com/file/d/1uhx4YU9kvbNa7n-vywjQeyX96kfzJVK8/view?usp=sharing
3. Left-click the window. Color picker dialog should open.
4. Right-click the window. Message box dialog should open.
5. Left-click again, no dialog opens, though this is intended behavior due the boolean variable you can see in the code.
6. Right-click again. No more message box opens, no matter how many times you right click. Seems the event is permanently disabled for no correct reason. As you see from the GML and C++ code in the DLL, nothing on my end is causing this.
7. Test the same above steps with a runtime older than 2023.11.x, for example, 2023.8.x, and notice the issue go away.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Same root cause as https://github.com/YoYoGames/GameMaker-Bugs/issues/2581 - fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.454  Runtime v2024.200.0.466

**Comment by time-killer-games** [comment]
Thank you for everything you all do every day for your customers! We really appreciate it!
