### ISSUE TITLE
`buffer_create` downconverts `int64` size argument, preventing creating large buffers >2Gb

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#2590]
### Description
As in the title, it doesn't seem possible to create buffers greater in size than the 32-bit signed integer limit.

Tested on Latest, and Beta Runtime `v2023.1100.0.459`.

### Steps To Reproduce
Example code:
```gml
var i32 = 2_147_483_647;
show_debug_message(i32);

// ok
var b1 = buffer_create(i32, buffer_fixed, 1);
buffer_delete(b1);

var i64 = int64(2_147_483_648);
show_debug_message(i64);

// buffer_create: Illegal size -2147483648
var b2 = buffer_create(i64, buffer_fixed, 1);
buffer_delete(b2);
```

[1038296e-ab94-4081-828c-a8c69f8c7525](https://api.gamemaker.io/api/github/downloads/1038296e-ab94-4081-828c-a8c69f8c7525)

**Comment by thennothinghappened** [comment]
whoops, would've made more sense to check if GM was happy handling buffers that size first anyway :P

GM seems to completely fail loading anything above that size, it returns a totally empty buffer, but still says the buffer exists, so that's probably its own issue to report.

**Comment by gurpreetsinghmatharoo** [comment]
Documented that buffers that are 2 Gibibytes or more cannot be created
