### ISSUE TITLE
Sound Editor: [Mac IDE] GM crashes on M-series Macs when creating/opening sounds if Rosetta is not installed

### ISSUE THREAD

**Issue by Schwarzgamescom** [YoYoGames/GameMaker-Bugs#2592]
### Description
I installed the latest version of Gamemaker on a new Mac Mini (2023) with MacOs 14.2.1. 
When I will load a sound file into an old or a new empty project Gamemaker immediately crashes. And after importing a project from another device when I open the already existing sound files in the resource tree Gamemaker crashes as well.

### Steps To Reproduce
Create a new sound asset and load a sound file.

[ec5aa162-5acd-4a6d-92a0-01b6e8fcb263](https://api.gamemaker.io/api/github/downloads/ec5aa162-5acd-4a6d-92a0-01b6e8fcb263)

**Comment by Schwarzgamescom** [comment]
I found the cause of the bug. It's the lack of Rosetta.
I installed Gamemaker 2023.6.0.92 to test and I was asked to install Rosetta for compatibility, which wasn't installed before. After installing Rosetta the sound works on 2023.6 and on the latest version 2023.11. 
So the sound system in Gamemaker somehow is not working on newer macs with Apple chips without Rosetta even though GM2023.11 thinks it doesn't need Rosetta.

**Comment by toby-yoyo** [comment]
Tested this on Beta IDE v2024.200.0.461 Beta Runtime v2024.200.0.477 having removed Rosetta from my machine. Attempting to load a sound file via the sound editor did indeed crash the IDE as described.

I got the following crash report out of it: [2592-crash-report.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14014415/2592-crash-report.txt)

I re-enabled the prompt for Rosetta installation in [this feature build](https://github.com/YoYoGames/YoYoStudio/actions/runs/7615237701). Installing that IDE (including Rosetta when prompted) seemed to resolve the issue.

**Comment by LukeBrownYoYoGames** [comment]
Ah, cool, so it was that. The quest is then, whether to fix the sound editor so it doesnt crash when this happens, change the IDE back so that it forces rosetta to be installed (as it did before), or change the sound editor so it triggers the rosetta installation when needed

**Comment by rwkay** [comment]
I think it must be that we are just not shipping ARM versions of the ffmpeg dylibs are they universal binaries?

**Comment by LukeBrownYoYoGames** [comment]
Was just speaking to Toby about the same thing. I'm assuming this is the fork here https://github.com/YoYoGames/FFmpeg but there arent any build pipelines like there is for our other forks like freetype so I dont know what was built.

I'm gunna assume probably not and that we need to make one.

I'll see if I can put together a quick pipeline for building them today

**Comment by toby-yoyo** [comment]
Changing milestone to 2024.4 as discussed internally.

**Comment by YYDan** [comment]
Be aware that for 2024.200 Beta 3 onwards, Rosetta is now marked as required again, so that no-one else starts getting this issue.

**Comment by toby-yoyo** [comment]
- Rebuilt ffmpeg and required libs as universal binaries.
- Removed the user prompt to install Rosetta on arm64 macOS once again.

**Comment by toby-yoyo** [comment]
Some issues (one of which is https://github.com/YoYoGames/YoYoStudio/issues/10100) have been found with the new ffmpeg build.

Changes to the installer/ffmpeg have been reverted on the 2024.6 branch only (see https://github.com/YoYoGames/GameMaker/pull/4122), but not elsewhere, so the effect of that is that this issue will be released for 2024.8.

For 2024.6, Rosetta installation will still be prompted.

Changing milestone to reflect this.

**Comment by NanoSharkGames** [comment]
The latest Beta still requires Rosetta installation on a new install of macOS.

**Comment by SamTHodson** [comment]
The Rosetta prompt is still appearing on IDE v2024.8.0.168  Runtime v2024.8.0.215, so reopening the issue

![image](https://github.com/user-attachments/assets/48ed714f-1a34-411e-ae94-2cccc4e670e4)

**Comment by toby-yoyo** [comment]
Added `arm64` to the IDE's host architectures once again, which should remove the Rosetta prompt during installation.

The `ffmpeg` binaries being shipped on macOS are already `arm64` compatible, so there were no further changes made in that area.

I was able to remove Rosetta from my system and import, play and compile both new and existing sounds on my currently-installed red build.

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.1100.0.631  Runtime v2024.1100.0.656
