### ISSUE TITLE
UI/UX: Shift+Delete command does not actually "Cut" text

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#2593]
### Description
In addition to my report #2509 (https://github.com/YoYoGames/GameMaker-Bugs/issues/2509),
I want to add, that GameMaker also does not cut the text to the clipboard when pressing Shift+Delete.

As there are more-than-one problems with the alternative cut/copy/paste functionality currently, allow me to list the "how-it-should-be" states:

Ctrl+Insert = Copy = Ctrl+C (currently works as fas as i can tell)
Shift+Delete = Cut = Ctrl+X (currently cuts the text but not to the clipboard)
Shift+Insert = Paste = Ctrl+V (currently crashes GameMaker)

Thanks for reading!
Cheers, Gris

### Steps To Reproduce
1. Start GameMaker and import [ShiftDelDoesNotWork.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13778464/ShiftDelDoesNotWork.zip)
2. Open the object's Create event in the Code Editor
3. Follow the steps in the comments
4. Observe you end up with the incorrect result shown in Dan's comment below

[136df9bd-1c75-49d6-a923-98db63498167](https://api.gamemaker.io/api/github/downloads/136df9bd-1c75-49d6-a923-98db63498167)

**Comment by YYDan** [comment]
Confirmed in IDE v2023.11.1.129  Runtime v2023.11.1.160 - Ctrl+C/X work just fine, but Shift+Delete just removes the line and does not actually update the clipboard contents.

**Comment by SmithTom6304** [comment]
Related to #2509

**Comment by SmithTom6304** [comment]
Fixed - was conflicting with the `Text Editor Delete` shortcut, which also used `Shift + Delete`.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.476  Runtime v2024.200.0.491
