### ISSUE TITLE
In-Game: keyboard_string appends some of its initial value again after typing a new value via virtual keyboard

### ISSUE THREAD

**Issue by tristannottelman** [YoYoGames/GameMaker-Bugs#2604]
### Description
Updating the keyboard_string after opening a virtual keyboard leads to peculiar behavior. I want to implement filtering while the user is typing. However, when I modify the keyboard_string and the user enters a random letter, the first letter of the keyboard_string is appended instead. This issue also occurs when the backspace key is pressed.

### Steps To Reproduce
Prerequisite:
Make sure keyboard_string is shown on the screen

1) Set keyboard string to ""
2) Open virtual keyboard
3) Set keyboard_string to "Test"
4) Press a random letter
5) A "T" will show instead of the chosen letter

[9fbd0e3e-95b8-4291-8f34-8b704146026c](https://api.gamemaker.io/api/github/downloads/9fbd0e3e-95b8-4291-8f34-8b704146026c)

**Comment by yoyo-danielc** [comment]
Fix merged into 2024.08 branch.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625.

Thank you.
