### ISSUE TITLE
Sprite Editor: "Sprite Playback mode" has no effect in-game

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#2605]
### Description
Hey there,

in the sprite editor, we have a button "change playback mode" for a sprite, with three useful states:
* loop
* ping-pong
* once

however, this has no effect when the game runs.
i couldn't find any built-in (green) variable, like `sprite_playback_mode` to change the "loop" behavior.

Please add a built-in variable `sprite_playback_mode` according to the other green variables, like
sprite_index, image_index, image_speed, etc... that lets us control, how the sprite shall be animated.

The default value of this variable should be what we set in the sprite editor, I mean...
the playback speed (fps) has effect in the game, the origin has effect, why not the playback mode?

Thanks for reading
Cheers, Gris

### Steps To Reproduce
* Edit any multiframe sprite in sprite editor
* Set the playback mode to anything except "loop"
* run the game
* the sprite still loops

[35272961-3f74-4bde-adef-b8c013b92ff5](https://api.gamemaker.io/api/github/downloads/35272961-3f74-4bde-adef-b8c013b92ff5)

**Comment by Totobal5** [comment]
This would be great !!!

**Comment by jackerley** [comment]
This is as designed

**Comment by Grisgram** [comment]
This is not a very helpful answer, sorry.
we _can_ implement that on our side with a view lines of code by attaching the _animation_end_ event and either multiplying image_speed with -1 or setting it to zero.

So it can't be much of a deal, implementing that in the engine.
if the designer supports it, it is beyond any logic why the runtime should ignore it.

i see "not planned" as the closing reason but it's hard to accept for me, honestly.
maybe at least in the new runtime? i mean... this is not a gamechanging feature and it would align the designer with the runtime...
