### ISSUE TITLE
Feather: GM2000 message text refers to "draw_set_blend_mode", but this should be "gpu_set_blendmode" instead

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#2609]
### Description

The message for GM2000 says: "Not all code paths call draw_set_blend_mode(bm_normal) before the end of the script."
Though the function to set the blendmode is now `gpu_set_blendmode`.

### Steps To Reproduce

/

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2023.1100.0.450 Beta Runtime v2023.1100.0.459

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.200.0.494  Runtime v2024.200.0.511
