### ISSUE TITLE
[YYC] Garbage collector causes silent crash with access violation (-1073741819) and variable dissapearing from the struct

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-Bugs#2626]
### Description
I am not sure if these two bugs are related, but taking into account the similarity of their conditions and the fact that they happen on the same project (so no need to send it two times) I posted them in one issue.
Sorry for possible inconvinience in future tracking.

There are occasional silent crashes and struct corruptions in my project. I wasn't able to reproduce them on a smaller project so I had to sent the full game instead.

The silent crash happens after going into the level room from the level selection menu. 
It yields the `-1073741819` status error in Output without any exceptions. After debugging in Visual Studio I concluded that it's related to garbage collector, specifically to the `MarkAndSweepGen` function. The issue is not observed with the `gc_enable(false)` and manual `gc_collect`s.
More info: https://forum.gamemaker.io/index.php?threads/2023-11-release-thread.107587/post-649403

The secund bug is causing a static method variable to "dissapear" from the constructor. After re-entering the room (if the first crash hasn't happened) an exception will be raised with the "Unable to get variable setRGB from object ..." although the variable is definetely should be in that object.
It's most certanly not a coding mistake and possily also related to garbage collector because it's not observed in VM and dissapears with the GC disabled in the same fasion as the issue above.

Possible relation to #1910, #1617, #2253, https://forum.gamemaker.io/index.php?threads/how-to-debug-a-crash-that-doesnt-leave-an-error.101560/post-613634,

### Steps To Reproduce
1. Compile the game with YYC
2. Press the play button in the center
3. Choose a level by pressing a button with a letter (A for example)
4. Expect a crash
    a. Crash isn't 100% reproducible and you may need to close the game and re-run it again for it to eventually happen
5. Regarding the second bug, if the first crash hasn't happened you can try to raise the second one which seems to be more frequent:
    a. Press Escape to pause the game
    b. Choose "Quit" option
    c. Start the game again on any level
    d. Get the exception "Unable to get variable setRGB from object ..."

[3bb73e3b-db7b-4d0b-b4bd-128a8b663c53](https://api.gamemaker.io/api/github/downloads/3bb73e3b-db7b-4d0b-b4bd-128a8b663c53)

**Comment by KeeVeeGames** [comment]
The project file failed to load the first time.

**Comment by rwkay** [comment]
did you mean to close this bug?
