### ISSUE TITLE
My antivirus saying the "igor.dll" is a Trojan

### ISSUE THREAD

**Issue by Limonka121** [YoYoGames/GameMaker-Bugs#2628]
### Description

after installing the 2023-11-1-129 version, when it asked me to update, game maker stopped running my game saying that the file "igor.dll" is not existent, because I've already encountered this issue before and fixed it, I've tried to do the same thing, and take it out of quarantine and exclude from scanning in my antivirus. but as I clicked to exclude it it disallowed:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/80058392/b6738d25-122b-4b40-badd-df16567adb05)

[contactpackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13801994/contactpackage.zip)

### Expected Change

this not occuring

### Steps To Reproduce

 I'm not sure if it will work for anyone else
1. Start GameMaker
2. run my game
3. antivirus warns me
4. I try to add the file to excluded
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.
