### ISSUE TITLE
Feather docs for function 'string_ext' should have square brackets around optional values param.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2629]
### Description
According to the GM manual, the string_ext function has an optional parameter 'values'. But Feather's hover documentation does not show that parameter as optional and complains if that parameter is missing in code.  The Feather docs should be updated to mark 'values' as an optional parameter.

### Steps To Reproduce
See screenshot.

[23d80082-4607-4a9b-bcc5-235e652b58ab](https://api.gamemaker.io/api/github/downloads/23d80082-4607-4a9b-bcc5-235e652b58ab)

**Comment by DiasFranciscoA** [comment]
The manual is incorrect the second element is not optional and the first should be a formatted string, using the string_ext implies you will be doing placeholder replacement if you don't want to (or you are doing some kind of dynamic call) you should be passing an empty array.

The function will be updated to reflect that information: https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Strings/string_ext.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed :+1:
