### ISSUE TITLE
"argument" is described as an array, with no mention of being special/"not a GML array"

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#2631]
### Description

GameMaker lets you access "index-based arguments" via an array-like interface, `argument`.  The manual just calls it an array, even linking to the manual page about arrays.

However, if you actually try to use it as an array in any way other than merely accessing a specific index, like if you try to do `array_contains(argument, "test")`, you receive a compiler error stating: "argument cannot be used without an array index, it is not a GML array"

This seems like something that ought to be documented.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Overview/Variables/Builtin_Global_Variables/argument.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
