### ISSUE TITLE
Project Saving: Extensions should not include local timezone information in their .yy "date" value

### ISSUE THREAD

**Issue by spacebake** [YoYoGames/GameMaker-Bugs#2641]
### Description

When opening a project in the IDE, .yy timestamps are being automatically changed to accommodate the user's local timezone.

This results in a bunch of automatic changes which is a nightmare for git when working on a project with people in multiple timezones. everyone has to take care to remove all these changes from staging before they commit anything.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17294327/1dd4a4bc-077b-4c07-aa72-8f89602bbb60)

It seems like this issue is only affecting .yy files for extensions (probably becuase they're the only asset-type i can find which has a "date" format in its .yy file.

### Expected Change

change the date format to not care about user timezones

### Steps To Reproduce

1. make a project that has an extension
2. check the date in the yy file
3. note that it has a timezone associated
4. open the same project in another timezone and note that gamemaker automatically changes these yy files
5. do the hokey cokey 
6. turn around

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.483  Runtime v2024.200.0.499. 
"date" is not present in the .yy file for Extensions anymore. 
Thank you.
