### ISSUE TITLE
Functions in constructor not defined with inbuilt names

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#2644]
### Description
When a function in a constructor shares its name with a built-in function, it is not found on any instances of that struct. Functions declared in static variables are unaffected by this. 
The attached project has a constructor defined in `constructor_test`, with two functions defined. `randomise` is eclared as a static function, and `get_timer` as a non-static function.

### Steps To Reproduce
1. Open attached project
2. Inspect script `constructor_test`, see how the `randomise()` and `get_timer` functions are declared
3. Run the project, observe the issue.

[51f43710-3967-4610-8f6b-f915c9331a53](https://api.gamemaker.io/api/github/downloads/51f43710-3967-4610-8f6b-f915c9331a53)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
