### ISSUE TITLE
Unable to compile large project in the YYC

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#2645]
### Description

A large project cannot finish compiling in the YYC on current Runtime and IDE version. YoyoGames has access to the repository with the project and should be able to test building it themselves.

The specific error we get varies per compile, but generally looks like so:

```
some-script.cpp(1316): fatal error C1001: Internal compiler error. 
```

I suspect it's actually an OOM problem though.

### Steps To Reproduce

1. Start GameMaker
2. Clone the repository of Fields of Mistria which you have access to.
3. Compile the game in the IDE
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by sanbox-irl** [comment]
@jackerley done

**Comment by sanbox-irl** [comment]
@jackerley we have a reasonably complex build system -- if you'd like to reach out on Discord to me, my username is `jack_irl` -- Russell can get you in touch. Simply loading the project in the GMS2 IDE won't successfully get it to run, unfortunately!

**Comment by jackerley** [comment]
This was found to be a problem with the use of  gml_pragma("forceinline") which causes any the C++ version of the script containing this pragma to be #included by every other script, massively bloating the amount of compiled code. @gurpreetsinghmatharoo could we add to the docs a comment that using forceinline within a large gml script will have a disastrous effect on compile times?
