### ISSUE TITLE
Instance "names" assigned in room editor are numbers, not instance refs

### ISSUE THREAD

**Issue by BackYard321** [YoYoGames/GameMaker-Bugs#2646]
### Description

When referencing instance names assigned in the room editor, (eg: `inst_66FC2204`), it will be treated as a number (eg: `100000`), as opposed to an instance ref (eg: `ref instance 100000`, such as `id` or what is returned by built-in functions such as `instance_place()`).

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Create an object and place it in the default room
5. Copy its name (eg: `inst_66FC2204`) and add a create event with `show_message(inst_66FC2204)`
6. Run the game

[ref numbers.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13832387/ref.numbers.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.468  Runtime v2024.200.0.484
