### ISSUE TITLE
Online manual + F1 does not open the correct page, but the home page...

### ISSUE THREAD

**Issue by DaveInDev** [YoYoGames/GameMaker-Bugs#2660]
### Description

Hi,
when using the online manual, with the F1 key on a keyword in the script editor, the IDE opens the manual home page, and not the correct article.
Example : F1 on instance_create_depth keyword generates this link, which display the home page... 
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FInstances%2Finstance_create_depth.htm

Note that there was an issue in september about this problem that should have been corrected :
https://github.com/YoYoGames/GameMaker-Bugs/issues/2406

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FInstances%2Finstance_create_depth.htm

**Comment by LukeBrownYoYoGames** [comment]
This appears to be fixed now. Closing

**Comment by Emc1923** [comment]
Verified with monthly and beta, closing.
