### ISSUE TITLE
Changes to various "speed" variables affect "direction" inconsistantly

### ISSUE THREAD

**Issue by quattj** [YoYoGames/GameMaker-Bugs#2663]
### Description

When an object is set in motion using direction and speed, and the motion is stopped by setting various speed values to 0 (speed, hspeed, vspeed), the direction of the object is affected inconsistently, in cases where it should not be modified.

Given an object with a collision event, in the collision event, with all speed values being modified in the same step/event
`move_contact_solid(direction, 12);
vspeed = 0;
hspeed = 0;
speed = 0;
gravity = 0;`

In the combinations listed below, this is what happens:
speed = 0 by itself does NOT change direction
- direction after stopping remains set properly, so object can continue moving in the same trajectory when speed is set to a positive value afterwards

hspeed = 0 by itself will set direction = 90 if 0 <= direction < 180, even if vspeed is already 0 and the resulting total speed is 0, or speed = 0 occurs immediately afterwards
hspeed = 0 by itself will set direction = 270 if 180 <= direction < 360, even if vspeed is already 0 and the resulting total speed is 0, or speed = 0 occurs immediately afterwards
- direction after stopping will cause object to move straight up or down when speed is set to a positive value after this step

vspeed = 0 will set direction = 0 if 180 <= direction < 90, even if hspeed is already 0 and the resulting total speed is 0, or speed = 0 occurs immediately afterwards
vspeed = 0 will set direction = 180 if 90 <= direction < 180, even if hspeed is already 0 and the resulting total speed is 0, or speed = 0 occurs immediately afterwards
- direction after stopping will cause object to move straight left or right when speed is set to a positive value after this step

hspeed = 0 AND vspeed = 0 will always set direction to 0
- direction after stopping will cause object to move straight right when speed is set to a positive value after this step

if speed = 0 occurs AFTER hspeed or vspeed = 0
- direction is affected according to the hspeed/vspeed effects listed above
 
if speed = 0 occurs BEFORE hspeed or vspeed = 0
- direction after stopping remains set properly, so object can continue moving in the same trajectory when speed is set to a positive value afterwards

The direction is immediately being modified when any hspeed or vspeed is set to 0, rather than when the final speed of the object is calculated.

### Expected Change

Expect that a total speed of 0 in any given step does not modify direction.  Older versions of GMS do not exhibit this behaviour..

### Steps To Reproduce

1. Start GameMaker
2. Create an object, set straight line motion using speed, direction, gravity, etc.
3. In collision or other event, set various speed values to 0 in combination.
4. See the issue
Sample file attached.  See object Obj_mover.  Various keys have been assigned to stop and start motion.

[DirectionIssues.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13851999/DirectionIssues.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Hi, I can't change the behaviour when setting hspeed, then vspeed as I don't know that you're about to do that. In that situation you should be using speed. I do agree that direction shouldn't be overwritten if the total speed is 0, so I have added a fix for that, but the rest is working as intended.

**Comment by mgeddesGM** [comment]
verified as of IDE v2026.0.0.16 Runtime v2026.0.0.23
