### ISSUE TITLE
Passing a value of -57 or lower as the map argument for skeleton_bone_state_set or skeleton_bone_data_set causes a silent crash

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2671]
### Description
Accidentally passed a number instead of my map variable and discovered this silent crash. skeleton_bone_data_set and skeleton_bone_state_set will both crash the game with no error message if you pass a number of -57 or lower as the map argument. -1 through -56 do not crash.
-57 isn't a valid map ID of course, but I figure all silent crashes are bugs since it should either not crash or give an error message.

### Steps To Reproduce
skeleton_bone_state_set("bone", -57); 
Running this code will cause the game to crash with no error message. Any number lower than -57 will also cause the crash.

[fb683631-8cf6-428b-9b65-b86137e69f25](https://api.gamemaker.io/api/github/downloads/fb683631-8cf6-428b-9b65-b86137e69f25)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.463  Runtime v2024.200.0.479, thanks.
