### ISSUE TITLE
Variable Definitions of other objects not always available at Create Event

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#2672]
### Description

I have run into this issue a couple of times now and I think it didn't use to be an issue:

I have an object that is mostly there to carry some data for scene setup, such as target positions for other objects to use etc.

obj_target has some variable definitions.

In my obj_room_controller object, during the create event, none of these variable definitions are available and I am forced to split up my initiation into Create and Room Start, which is rather ugly.

I would expect variable definitions to be known at that point.

I suspect the PreCreate event is executed together with the Create event of every instance.

I think it would make more sense to run the PreCreate events of all instances first, and then all Create events.
[VarDefBug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13856985/VarDefBug.zip)

### Expected Change

Variable definitions of all instances should be known at the time Create events get called.

### Steps To Reproduce

1. Start GameMaker
2. Create an object "room_controller" and have it create a map of all obj_targets in the room, indexed by name.
3. Place it in the room
4. Create an object "obj_target" and give it the variable definition for a name and some standard data for it
5. Place them in the room
6. Make sure the room_controller is the first instance in the room
7. Run the game and see the error: 

```
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_room_controller:

Variable obj_target.name(100943, -2147483648) not set before reading it.
 at gml_Object_obj_room_controller_Create_0 (line 303) -        other.targets[$ name] ??= {
############################################################################################
gml_Object_obj_room_controller_Create_0 (line 303)

```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
This is as-designed.
You cannot rely on creation order outside of the instance creation order in the current running room.
Use either a persistent object or an alarm.
