### ISSUE TITLE
Menu Bar: [Mac IDE] Menu Bar entry for 'Windows' is called 'Window' on macOS

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#2676]
### Description

The Menu Bar entry for 'Windows' is called 'Window' on Mac - the name title is different from Ubuntu/Windows.

Windows/Ubuntu:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/5a993c67-7cbc-49ab-8bcd-68df6a2d95ca)

Mac:

<img width="768" alt="Screenshot 2024-01-08 at 11 38 19" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/eb73941f-76f0-4d23-a444-a532f96e37e9">

### Expected Change

Menu Bar entries should be the same across platforms

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), 2022.0.2 (LTS), 2023.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Is this perhaps a macOS system menu?

**Comment by SmithTom6304** [comment]
Yeah, this is a macOS system menu and is working as intended. From the [What’s in the menu bar on Mac? macOS user guide](https://support.apple.com/en-gb/guide/mac-help/mchlp1446/mac):
> The name of the app you’re using appears in bold, followed by other menus, often with standard names such as File, Edit, Format or **Window**.

I've attached some examples from other applications:
<img width="589" alt="Screenshot 2024-01-15 at 09 13 38" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/310e7b45-a11c-483f-b402-9232e4b9d82f">
<img width="391" alt="Screenshot 2024-01-15 at 09 13 48" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/8fadd808-515c-4639-9f78-8cfc629c1ec6">
<img width="449" alt="Screenshot 2024-01-15 at 09 13 58" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/d65a8e9e-f493-4b3e-9f89-ab058741f38f">
