### ISSUE TITLE
The `ds_stack_push()` issues.

### ISSUE THREAD

**Issue by VladiStep** [YoYoGames/GameMaker-Bugs#2678]
### Description

1) The optional arguments count mismatch - in the "Syntax" it's `[, val2, ... val15]`, but in the table below, it's `[val2, ... val13]` (which seems correct).
2) The example misses a space before `+`: "ds_stack_push(move_stack, x, y, x, y + 200, x + 200, y + 200, x **+2**00, y);"

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Data_Structures/DS_Stacks/ds_stack_push.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, thanks so much for reporting!
