### ISSUE TITLE
Building Projects: Compiler should enforce when code contains too-few arguments for functions being called

### ISSUE THREAD

**Issue by VladiStep** [YoYoGames/GameMaker-Bugs#2680]
### Description

In the documentation, it's stated that the minimal argument count of `ds_stack_push()` is 2, but you can write `ds_stack_push(a)`, and it will even compile?

[report.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13862889/report.zip)

### Expected Change

IDE should expect at least two arguments for `ds_stack_push()`

### Steps To Reproduce

1. Start GameMaker
2. Open a project.
3. Write this in any code that will be executed:
```gml
a = ds_stack_create()
ds_stack_push(a)
```
4. See the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
We won't be doing this.

**Comment by VladiStep** [comment]
What? Why?
Is it too difficult, or is it "by design"?
@DiasFranciscoA

**Comment by rwkay** [comment]
This should be checked and fixed for Feather and New Code Editor

**Comment by scott-dunbar** [comment]
This issue persists in  IDE v2024.200.0.478  Runtime v2024.200.0.493

Neither feather alerts you or during compile. It is not obvious from the comments here what the outcome should actually be so please be specific to the changes when re-closing this issue.

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/103ee14a-8264-492c-8a9f-805af1e8dd30)

**Comment by DiasFranciscoA** [comment]
This should now be fixed multiple function were touched by this update, all the function in the list below will require a minimum number or arguments:

* `choose(val1, val2, ...)` : requires 2 args
* `max(val1, val2, ...)` : requires 2 args
* `min(val1, val2, ...)` : requires 2 args
* `mean(val1, val2, ...)` : requires 2 args
* `array_insert(array, index, val1...)` : requires 3 args
* `array_push(array, val1, ...)` : requires 2 args
* `array_concat(val1, val2, ...)` : requires 2 args
* `array_union(val1, val2, ...)` : requires 2 args
* `array_intersection(val1, val2, ...)` : requires 2 args
* `ds_stack_push(stack, val1, ...)` : requires 2 args

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.481  Runtime v2024.200.0.496 for all of the functions mentioned above.

Plus note that this is only fixed for Feathers (as per comment), no error is reported when feather is off.
