### ISSUE TITLE
In-Game: [iOS] DS_Map can be overwritten with Null Pointer in 2023.11.1

### ISSUE THREAD

**Issue by jbonesy** [YoYoGames/GameMaker-Bugs#2681]
### Description

There's a bug we found for iOS recently that seems platform specific as we haven't experienced this on Android. This seems to be a very specific bug which happens only under some circumstances; these seem weirdly unrelated to anything material within the project, so we're assuming this is specifically a runtime problem.
Essentially, we noticed that on iOS, saving offline and utilizing a ds_map for doing so, then immediatedly saving online (or vice-versa) will cause type of null pointer issue where despite clearly existing the pointer attached to the ds_map in the script will always be 0. We've debugged this and the pointer assigned to the ds_map in the script will always be 0 even if it is literally created the line before.
As a note, we first thought this was related to the GC extension's cloud saving, but even upon disabling all GC functionality (cloud save or otherwise), this is still occurring, so we think this is actually an iOS runtime issue.
We have discussed this with the team on Slack, this exists within a specific project and we can give access directly to our Git to replicate.

### Steps To Reproduce

1. Open GMS2
2. In order to quickly reproduce this, modify code to instantly load the game near a save point: 
_In the below image (line 2625) of event "Step" of object "obj_MenuScreanCont" change "rOnscreenKeyboard2" to "rStart22"_
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/21029130/11e85a80-1164-4633-849b-d624d27970ea)
3. Run the game on iOS, with the device offline 
4. Start a new game, which will now load you to a room for quick testing
5. Save the game at the save point (the globe) and finish related dialogue
6. Switch the device online
7. Save the game again at the save point
8. Observe the ds_map null pointer crash in script Saving()

Note that for steps 3 & 6, you can start offline/online then switch to online/offline respectively interchangeably so long as it is switched at these respective points (i.e. starting online then going offline, or starting offline then going online).

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Resolved by re-installing XCode, no change necessary

**Comment by YYDan** [comment]
Nothing for us to verify.
