### ISSUE TITLE
Standalone ternary operations don't work despite manual claiming otherwise

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Bugs#2682]
### Description

On the gml manual page '**_if / else and Conditional Operators_**', the example shows a ternary operation being used without being part of a variable assignment.

The specific example is the third line of code here:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/109584258/8b86e3f4-28e4-4a64-9c85-45c5b3a5c267)

That line implies that it's possible to use ternary operators for standalone 'if-else' shortcuts (as is standard for many languages).

However when copy/pasting that line in, or trying any other variation, for example:
`(instance_exists(obj)) ? instance_destroy() : instance_create_depth(x, y, 0, obj);`

You are just met with this feather error `GM1007 Left-hand side of an assignment must be a variable.`, which prevents compiling the game.

### Steps To Reproduce

Copy & paste in the code from the manual: `(--hp <= 0) ? instance_destroy() : score += 10;` into a project.

Gamemaker will then prevent compiling.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
ternary operators cannot be used as statements they are part of an expression.
