### ISSUE TITLE
Bottom dock panel constantly reopens automatically after being closed during code edits.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#2687]
### Description
The dock panel at the bottom of the IDE, which normally houses the feather messages and compile errors output windows, consistenly opens up after having been physically closed and reclosed by hitting the F12 key, or dragging the panel's edge all the way down, etc.  If I close that panel, it means I don't want to see it until I reopen the panel myself, and it's usually because I want to focus on cleaning up or refactoring my code and having that panel popping up automatically all the time kind of detracts from that.

Workaround: If I drag the panel edge ALMOST all the way down to the point where it doesn't qualify as "being closed", then it stays mostly out of the way.

Would be nice for that panel to stay closed when I close it.

### Steps To Reproduce
1 - Start a new project
2 - Create a new object and event and enter the code editor.
3 - Hit F12 to close all the dock panels.
4 - Start typing some code, purposefully causing an error.
5 - Observe the bottom panel appear.
6 - Close it again.
7 - Goto to step 4.

[a3d01c3b-36b2-4873-8697-cb29cdaa7b90](https://api.gamemaker.io/api/github/downloads/a3d01c3b-36b2-4873-8697-cb29cdaa7b90)

**Comment by YYDan** [comment]
Hello,

This would be a new feature request anyway, not a "bug", but to be clear this setting already exists in Preferences:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/b33cfe32-d3a5-4fcc-a869-c19d2290fb63)

If you deselect the Preference (as shown above), then your steps will no longer show any error information until you next try to build the game.
