### ISSUE TITLE
Need a way to prevent clicking through the new debug overlay.

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Bugs#2699]
### Is your feature request related to a problem?

As the developer of a game that makes extensive use of the mouse (targeting NPCs/objects etc.), it's very frustrating to use the debug overlay when I'm constantly selecting game objects/clicking GUI elements through it.

I've been able to hack together workarounds to prevent clicking anything while it's open but then I need to be constantly toggling it on/off to use it effectively.

### Describe the solution you'd like

I'm not looking for built-in support to prevent clicking through, but rather a simple function that returns a true/false if the cursor is anywhere over the debug overlay.

Eg.
`debug_overlay_get_mouseover`

**Comment by scott-dunbar** [comment]
Verified in  IDE v2024.200.0.478  Runtime v2024.200.0.493
