### ISSUE TITLE
dbg_sprite should have optional width and height parameter

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#2706]
### Is your feature request related to a problem?

when using `dbg_sprite` with a large sprite, it renders at full resolution which may use lots of unnecessary space when only a small preview is needed
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/15136382/88bd225e-652e-4d99-bbbc-1b7fc6f76a4c)
(also, if the `ref_create` tries to create a ref to an undefined sprite, the runner will crash with an inscrutable error message)

### Describe the solution you'd like

`dbg_sprite` should accept optional width and height parameters.

Ideally, if either value is provided, the whole sprite should be scaled accordingly, e.g. if a sprite is 400 wide by 200 high, passing `100` for width and `undefined` for height should scale the sprite to 100 x 50 (and vice versa for only specifying width). This is useful as it allows having a standard 'sprite size' when showing sprites in a debug overlay without the developer having to do scaling math per image.

### Describe alternatives you've considered

Only alternative I can think of is manually creating a preview-sized sprite whenever displaying a sprite in a debug view

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.469  Runtime v2024.200.0.485
