### ISSUE TITLE
dbg_section() should have parameter for controlling whether it's expanded or collapsed

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#2707]
### Is your feature request related to a problem?

If I want to make a debug overlay with lots of data (such as for my UI system), it's natural to put chunks of data in sections to manage complexity. However, debug sections are expanded by default and can only be collapsed manually one at a time, so making all that data useful to the user is challenging

### Describe the solution you'd like

dbg_section should have a parameter to control whether it is expanded or not. Ideally this can either be `true`, `false`, or a `ref` to a boolean variable (this would allow the user to add their own buttons to 'Collapse All', for example).

### Describe alternatives you've considered

the only alternative I can think of is to mimic our own sections with buttons (which then involves manually implementing fake section expand/collapse logic)

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.469  Runtime v2024.200.0.485
