### ISSUE TITLE
Included Files Refresh Button

### ISSUE THREAD

**Issue by thatsmytrunks** [YoYoGames/GameMaker-Bugs#2729]
### Is your feature request related to a problem?

I've found that in different versions of Game Maker the IDE does not always properly refresh the included files list, leaving me to have to edit the project YYP to remove missing or duplicate entries.

### Describe the solution you'd like

I'd love a little button next to "Open in Explorer" on the Included Files browser that checks for missing files in the datafiles directory and removes them from the included files list, and adds any new ones it finds.

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/9100011/d9886142-751d-4f76-a8cf-e4eead11c8f3)

**Comment by stuckie** [comment]
It's actually ended up on the other side, but the button is now in.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/795290/584d2a02-6076-431e-853e-5e4c911621de)
