### ISSUE TITLE
GM_is_sandboxed constant to detect whether the game is running in sandboxed mode

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#2736]
### Is your feature request related to a problem?

Recently we got GM_project_filename which is very useful for finding the GM project folder to support live editing/reload functions, however a related problem is detecting whether the game is running in sandboxed mode, as if it is then we won't be able to access those project files anyway. Currently I use a script which detects sandbox mode by attempting to write a file outside the sandbox directory and checking for success, but this is obviously hacky.

### Describe the solution you'd like

GM_is_sandboxed constant to detect whether the game is running in sandboxed mode

### Describe alternatives you've considered

Continuing to use the hacky script mentioned above

**Comment by cameron-home** [comment]
Verified present in Windows using IDE v2024.200.0.465  Runtime v2024.200.0.481

**Comment by cameron-home** [comment]
Verified present and working on macOS and Ubuntu as well.
