### ISSUE TITLE
buffer_sizeof can (sometimes) be a compile-time value

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#2743]
### Is your feature request related to a problem?

My username on the GameMaker discord is "don't pre-emptively worry about performance issues," and yet here I am.

The `buffer_sizeof` function is used for getting the byte width of one of the buffer datatypes, analogous to the `sizeof()` macro in C. In GML it's a regular function call:

    var size = buffer_sizeof(buffer_f32);

    00000000 : 08000f84                 pushi.e   8
    00000004 : 00005207                 conv.i.v
    00000008 : 010002d903000000         call.i    $buffer_sizeof$
    00000010 : f9ff5545040000a0         pop.v.v   $size$

rather than

    00000000 : 04000f84                 pushi.e   4
    00000004 : f9ff2545030000a0         pop.v.i   $size$

Naturally this can't always been done since you're also allowed to write code like this:

    var type = choose(buffer_f32, buffer_s8, buffer_f16, buffer_u64);
    var size = buffer_sizeof(type);

though I have a feeling most of the time when people use buffer_sizeof they're using it on a fixed value.

### Describe the solution you'd like

Yeeeeeeeeeah...

### Additional context

There's a whole slough of other functions (most of the pure math variety) that could also do this - `sin(0)`, etc. But since I don't know what's involved in adding these functions to GameMaker's pre-processor other than that there are a few functions that do it, I probably won't file any others after this.

Also, `sin(0)` isn't really something that serious people ever write in their code.

(For anyone wondering, in YYC it doesn't get literally translated into `sizeof()`, since there's still the layer or two of GameMaker runtime between your code and C++.)

    YYGML_CallLegacyFunction(pSelf, pOther, __ret1__, 1, g_FUNC_buffer_sizeof.val, &__pArgs__[0]);

**Comment by sihammill** [comment]
FR verified in IDE v2024.200.0.463  Runtime v2024.200.0.479
