### ISSUE TITLE
JSON - loading null as undefined, so saved struct/array would have same values as when saving

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2749]
### Is your feature request related to a problem?

Gamemaker have inconsistency in `json_parse()` and `json_stringify()` functions.

- `json_stringify()` saves GML `undefined` as JSON `null`
- `json_parse()` loads JSON `null` as `pointer_null`

This means, that when we're saving struct in which some values are `undefined` because they are either not set, or developer marks some variable as "not set" in this way, on loading it back, we need to pass it to convert all `pointer_null`s back to `undefined`s.
This is not that easy and time consuming in case of nested structures and arrays.

I understand that GML saves `undefined` as `null` because JSON doesn't offer `undefined` (while JS does), so there's no other value, but I don't understand why it reads it back as different value (indeed `pointer_null` is maybe more close to JSON `null`, but generally `pointer_null` is rather not often used for storing empty values in structs/lists/maps/arrays in favour of `undefined`).

It's rather usual, that GM developers are using `undefined` in GML to mark "not set" things, like:
```gml
data = {
  x: 5,
  y: 10,
  last_clicked: undefined,
}
```
and it's rather expected, that after saving and loading such struct, `last_clicked` would be still `undefined` not `pointer_null`.

### Describe the solution you'd like

As changing `json_parse()` so it gives `undefined` instead `pointer_null` could break existing code, my proposal is to add additional argument, how `null` should be treated:

```gml
json_parse(string [, undefined_instead_of_pointer = false])
```

In that case:
```gml
json_parse("{\"x\": 5,\"y\": 10,\"last_clicked\":null}");
json_parse("{\"x\": 5,\"y\": 10,\"last_clicked\":null}", false);
```
would result in:
```gml
{
  x: 5,
  y: 10,
  last_clicked: pointer_null,
}
```
while:
```gml
json_parse("{\"x\": 5,\"y\": 10,\"last_clicked\":null}", true);
```
would result in:
```gml
{
  x: 5,
  y: 10,
  last_clicked: undefined,
}
```

### Describe alternatives you've considered

We already have special prefixes/suffixes for some values for json_stringify:
- int64 is saved as `@i64@<NUMBER>$i64$`
- `infinity` is saved as `@@infinity$$` / `@@-infinity$$`
- `NaN` is saved as `@@nan$$`

So, `undefined` could be saved as:
- `@@undefined$$`

However, this again could break existing code and existing functionality, so that would require:
```gml
json_stringify(struct_array [, pretty_print = false, undefined_gml_compatible = false])
```

This way, saving data which contains `undefined` that can be read back as `undefined` would look this way:

```gml
json_stringify(data, , true); // skipping pretty_print arg
json_stringify(data, true, true); // in case we want pretty print
```

**Comment by sihammill** [comment]
Feature verified in IDE v2024.200.0.472  Runtime v2024.200.0.488
