### ISSUE TITLE
Function to convert string of a handle into a handle

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#2753]
### Is your feature request related to a problem?

Prior to 2023.11, one way to pass a surface around was through a string of it's ID, then back into a reference with the `real()` function. (e.g, in Juju's Scribble)

Now that surfaces are typed references, this option no longer works, and as best I can tell, there's no way to convert a string of a handle back into a handle.

### Describe the solution you'd like

add a function (e.g. `handle("ref surface 1")`) that can convert a string of a handle back into a handle 

### Describe alternatives you've considered

if it needs to be more complex, e.g. `handle_create(ref_type_surface, 1)` (which would then require parsing the handle string to extract the id integer) that would be fine with me. But any other alternative would mean refactoring for anyone that passes references like this, which is a bummer for solutions like Scribble that are centered around parsing strings to extract data. 

Specific to Scribble, Juju is currently talking about adding a `.bind_surface()` method to scribble as a workaround to attach/pass any surfaces that are needed in a scribble element.

**Comment by YYDan** [comment]
Has now been renamed to "handle_parse()" so @YYBartT you might need to review the docs, so setting this back to Done, but if all is okay just send it back again ;)

**Comment by YYDan** [comment]
Looks like you got it already, seeing the comment and subsequent commit on https://github.com/YoYoGames/GameMaker-Bugs/issues/4338

**Comment by scott-dunbar** [comment]
The function exists and works in  IDE v2024.200.0.476  Runtime v2024.200.0.491

but has syntax highlighting issues https://github.com/YoYoGames/GameMaker-Bugs/issues/4562
