### ISSUE TITLE
Add `vertex_submit_ext` which takes a known amount of Vertexes

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#2754]
### Is your feature request related to a problem?

Having a vertex buffer which contains more bytes than vertexes you want to actually render is now trivially possible since `vertex_update_buffer_from_buffer`. This is good and useful, but `vertex_submit` will still try to draw everything.

### Describe the solution you'd like

I'd love a `vertex_submit_ext(vtx_buf, pr_trianglelist, -1, NUMBER_OF_VERTEXES_TO_DRAW)`. The only difference is that it takes a NUMBER_OF_VERTEXES_TO_DRAW.

**Comment by pkraif** [comment]
Added new function `vertex_submit_ext(buffer, primtype, texture, offset, number)`, which submits a portion of a vertex buffer to the graphics pipeline. Argument `offset` is the index of the first vertex to draw (cannot be less than 0!), `number` is the number of vertices to draw. Use -1 to submit all vertices after given offset. `number` is also automatically clamped to the size of the vertex buffer based on given `offset`.

I'm attaching a basic project on which this new feature can be tested. There's a vertex buffer containing 4 points, drawn using `pr_trianglestrip`, `offset` changes with time between 0 and 1 and `number` is set to 3. This means it switches between rendering one of the two triangles that make up the rectangle. This is what it should look like: 
![00](https://github.com/YoYoGames/GameMaker-Bugs/assets/103570506/ddf43677-69b5-4e67-88be-f2bc806b6fcd) ![01](https://github.com/YoYoGames/GameMaker-Bugs/assets/103570506/80b244fc-104c-40d2-b7c5-8b038db3942d)


[VertexSubmitExt.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14028076/VertexSubmitExt.zip)

**Comment by sanbox-irl** [comment]
@pkraif our frame rate thanks you!

**Comment by YYBartT** [comment]
Also linking https://github.com/YoYoGames/GameMaker-Manual/commit/a22c65764cb3efc8f8427b6e1f82733914ba25ae, which I accidentally wrongly linked to another issue (Vertex buffer update functions)

**Comment by sihammill** [comment]
Feature verified in IDE v2024.200.0.492  Runtime v2024.200.0.508
