### ISSUE TITLE
In-Game: Add support for raycasting within the physics/Box2D functionality

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#2762]
### Is your feature request related to a problem?

Problem: Box2D has had raycasts (simple tests of line segments vs. Fixtures) for ages. Having this available would _massively_ impact game design with GameMaker and hugely optimize a lot of game designs. For example, it's almost certainly a lot cheaper to raycast in most situations than to run Precise collisions, but makers can build their physics via Chain etc. to get a "close-enough" approximation of the Sprite.
This is one of those big things that GameMaker has been missing for a decade, and it's a big deal... but it's not hard to implement.

### Describe the solution you'd like

Essentially, implement a call to this:  https://www.iforce2d.net/b2dtut/raycasting

In GML, this would be something like this:

physics_raycast(xStart,yStart,xEnd,yEnd, <instance id, object id, or array, same as line_collision(), ds_list_to_use)

Would return a ds_list or a struct, whichever is faster.

If returning a ds_list, the first value of list should be either noone (nothing hit- **fraction** value returned by Box2D > 1) or closest hit Instance. Second and third values should be the XY position of the hit (the _normal_ in Box2D), and fourth value should be the fraction value.

If returning a struct, then it'd be:

testStruct = physics_raycast(xStart,yStart,xEnd,yEnd, <instance id, object id, or array, same as line_collision());

testStruct.hitID would be the id, or noone.
testStruct.normalX would be the normal's X.
testStruct.normalY would be the normal's Y.
testStruct.fraction would be the fraction value.

Personally, I'd prefer the struct version, because then you could extend this into physics_raycast_list() which would return a ds_list of structs with all the data a developer needs, rather than how it works with line_collision_list(), where it merely returns a list of Instance IDs, which typically requires further processing to arrive at a good result.

### Describe alternatives you've considered

The only real alternative is using scr_rangeFinderExact(), which is a well-known, brute-force script for getting these kinds of collisions in GameMaker. While it works... it's slow and inefficient, it doesn't work on anything in Physics World that doesn't have a sprite, it can't deal with something whose Physics World presence is considerably different than the sprite, etc. 

We cannot write good alternatives, because we cannot get access to the Physics Body's polylines in GameMaker, etc., etc. 

About the only way a workaround might be built is storing the polylines of a Physics Fixture as point data, doing rotations during testing, etc., etc. But that defeats the whole purpose- the data is _already there..._ we just need a GML function.

### Additional context

It's literally a feature that would transform a lot of my project and hugely impact a lot of others' as well. This is one of those mundane-looking things that's very important in real-world game-dev.

**Comment by Glim888** [comment]
@rwkay You also could provide us a pointer to the Box2D, LiquidFun variable. So we could implement some missing features ourself.

Moe Box2D and LiquidFun features would be great, but pls keep compatibility. Thanks

**Comment by rwkay** [comment]
Project for testing new function [PhysicsRaycast.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15048641/PhysicsRaycast.zip)

**Comment by Glim888** [comment]
@rwkay In case of updating box2d, I would like to help you with testing, discussion of features etc. 

I have pushed GMS Box2D and liquidFun features to the limits. I have done multiple games with over 8 mio downloads based on GMS Box2D. Feel free to contact me. Thanks =)

**Comment by rwkay** [comment]
Feature Added in 2024.6 - 

`physics_raycast(xStart,yStart,xEnd,yEnd,ids,[all_hits],[max_fraction],...)`

This function checks the physics fixtures of the objects given against the ray specified, it will return an array of structures that will give the hitPointX, hitPointY (the room coordinates of the intersection), normalX, normalY (the normal of the intersection), fraction (the normalised distance down the ray of the intersection)

* xStart - x position of the start of the ray.
* yStart - y position of the start of the ray.
* xEnd - x position of the start of the ray.
* yEnd - y position of the start of the ray.
* ids - instance or object id (or an array of instance or object ids) to check the ray against, these should have physics fixtures
* all_hits - set to true if you want all hits returned, false if you want the closest hit only - defaults to false
* max_fraction - proportion of the ray to check, defaults to 1.0, can be set to be smaller or larger

**Comment by YYBartT** [comment]
Added function reference page for `physics_raycast()` to the manual.

**Comment by cameron-home** [comment]
Verified in IDE v2024.600.0.563  Runtime v2024.600.0.580
