### ISSUE TITLE
Texture pages: Update sprites in-place during compilation

### ISSUE THREAD

**Issue by WangleLine** [YoYoGames/GameMaker-Bugs#2772]
### Is your feature request related to a problem?

It's always nice to cut down on compilation times - It breaks development flow less and, well, saves time.
I had brought up a similar, but different request in YoYoGames/GameMaker-Bugs#2814 which was already implemented. This one's different.

### Describe the solution you'd like

When the contents of sprites are updated, instead of completely rebuilding their corresponding texture page(s), gamemaker could keep the atlas and replace the pixels in-place, on the texture page, if some conditions are met.

- If the sprites' contents are different, but the crop/scale is unchanged, great!
- If the crop/scale is smaller, replace the sprite(s) in-place and don't worry about the small amount of temporarily wasted texture page space.
- If the crop/scale is larger than before, rebuild the texture page as usual.
- On exporting/building the game, always completely rebuild texture pages/atlases (I assume gamemaker already forces this)

**Comment by rwkay** [comment]
I have been investigating this and in the current asset compiler this is not going to be possible.
