### ISSUE TITLE
"with global"

### ISSUE THREAD

**Issue by BackYard321** [YoYoGames/GameMaker-Bugs#2783]
### Is your feature request related to a problem?

There are cases where, when referencing several global variables using dot notation, code becomes harder to read. EG:

```gml
if global.levelComplete
{
    global.level = global.levelArray[global.levelIndex]
}
```

However, attempting to use `with global` gives you the error `Cannot use global in with statement`. 

### Describe the solution you'd like

Given that YoYoGames/GameMaker-Feature-Requests#400 ("Allow accessors natively for global") will be implemented in 2024.2, and the way `global` is now usable in other contexts where structs/instance id's would normally be used, `with global` seems like another natural step in this direction. And according to [#issuecomment-1818958610](https://github.com/YoYoGames/GameMaker-Bugs/issues/1779#issuecomment-1818958610), `global` is no longer a number in 2023.11, which might help facilitate this.

Also, the above could be written as:
```gml
with global
{
    if levelComplete
    {
        level = levelArray[levelIndex]
    }
}
```

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.469  Runtime v2024.200.0.485
