### ISSUE TITLE
Add the Garbage Collector stats to `show_debug_overlay` as an official view.

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#2800]
### Is your feature request related to a problem?

In a big project of mine, I have the garbage collector built up as a basic view. Providing me with enough statistics that I can at least narrow down certain issues. Something that the debug profiler alone won't show. Including a way to turn it off, adjust how frequently it updates and to force a collection.

However, it'd be kind of nice to have this built in, instead of having to drag a whole object + code every time.

### Describe the solution you'd like

By providing a view directly built in, it'll give developers a better way of accessing information about the garbage collector, without having to manually put together something. Included is a zip of a project with an example, including a randomizer struct generator via space key, and structs that randomly get yeeted after sometime. This is to simulate a project that may be allocating and deallocating structs immediately, and a little bit later on in the game.

[Garbage Collector Debug View.zip](https://github.com/YoYoGames/GameMaker-Feature-Requests/files/13412582/Garbage.Collector.Debug.View.zip)

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.469  Runtime v2024.200.0.485
