### ISSUE TITLE
[WEB PAGE] Add RSS to game maker blog page

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#2803]
### Is your feature request related to a problem?

Many times i miss blogs, news, tips and more on the game maker blog page. 

### Describe the solution you'd like

please add a RSS feed so i can get the news on my RSS app

### Describe alternatives you've considered

email subscription?

**Comment by Totobal5** [comment]
This will be added someday ?

**Comment by patrickrocheyoyo** [comment]
Added to internal task sheet for further discussion. This'd be neat to have.

**Comment by Totobal5** [comment]
would make me very happy. Since I did this issue until now I think I've missed half of the blog posts, interviews and many more. Having the ability to add the Game Maker Blog page to my FreshRSS app will be great!
