### ISSUE TITLE
String Literal Hash Optimization

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#2804]
### Is your feature request related to a problem?

![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/3cf01664-d6ae-4a0f-95f1-b9af7597bef3)

This is the sister request to [this feature request](https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1465).

Currently string literals inside the hashing function are not done at compile time.

### Describe the solution you'd like

Ideally this would generate the string and hash, for the internal hash table, so `struct_get_names` would still work as expected. But it would convert that particular line into a hash literal/real.

### Describe alternatives you've considered

using a static `variable_get_hash` or pre hashing.

### Additional context

This may have already been optimized when the sister function was optimized.

**Comment by yerumaku** [comment]
> Added in 2024.2 - now `variable_get_hash` calls with a constant argument are optimised at load time to just be a constant so `variable_get_hash( "Hello" )` will be compiled to the hash code value for the variable called "Hello"

If I pass a function there that takes the name of the resource/constructor as an argument, will I also get optimization?

```gml
static hash_key = variable_get_hash(to_snake_case(TestConstructor));
```

**Comment by rwkay** [comment]
No it will only be optimised if the values are constants at compile time
