### ISSUE TITLE
JSON Asset/Object/SFX/Sprite To String 

### ISSUE THREAD

**Issue by skyelynwaddell** [YoYoGames/GameMaker-Bugs#2808]
### Is your feature request related to a problem?

Hey So I find it bothersome that I have to save the String of the sprite to JSON and then convert it to an asset and then have to reference that instead.

### Describe the solution you'd like

When I save a sprite inside a JSON file it should automatically save it as a string of that sprite and convert it upon load to the asset i had originally said to save. Make it detect im saving a sprite and save its name instead of just being saved as a reference to that sprite.
Thank you.

**Comment by JujuAdams** [comment]
@rwkay I note this has been added for 2024.2. How does this feature work at the moment?

**Comment by rwkay** [comment]
Any reference is written as a string with format `"@ref <ref-type> (<type-specific-info>)"` where `<ref-type>` is a string for the type (see table below)

```
	{	"instance", REFID_INSTANCE },
	{	"ds_list",	REFID_DS_LIST },
	{	"ds_map", REFID_DS_MAP},
	{	"ds_grid", REFID_DS_GRID},
	{	"ds_queue", REFID_DS_QUEUE},
	{	"ds_stack", REFID_DS_STACK},
	{	"ds_priority", REFID_DS_PRIORITY},
	{	"object", REFID_OBJECT},
	{	"sprite", REFID_SPRITE},
	{	"sound", REFID_SOUND},
	{	"room", REFID_ROOM},
	{	"background", REFID_BACKGROUND},
	{	"path", REFID_PATH},
	{	"script", REFID_SCRIPT},
	{	"font", REFID_FONT},
	{	"timeline", REFID_TIMELINE},
	{	"tiles", REFID_TILES},
	{	"shader", REFID_SHADER},
	{	"sequence", REFID_SEQUENCE},
	{   "animcurve", REFID_ANIMCURVE},
	{	"particle system resource", REFID_PARTICLESYSTEM},
	{	"dbgref", REFID_DBG},
	{	"particle system instance", REFID_PART_SYSTEM},
	{	"particle emitter",REFID_PART_EMITTER},
	{	"particle type", REFID_PART_TYPE},
	{	"buffer", REFID_BUFFER},
	{	"vertex buffer", REFID_VERTEX_BUFFER},
	{	"vertex format", REFID_VERTEX_FORMAT},
	{	"surface", REFID_SURFACE},
	{	"time source", REFID_TIME_SOURCE},
```

then the type specific info varies depending on the type. (for resources it  is the name of the resource)

Minimal validation is done on import to check that the info is valid.

**Comment by rwkay** [comment]
There is still a problem here as the ref parsing is in the wrong code path.

**Comment by Alphish** [comment]
I tried the following round-trip example, representing a typical use-case of saving the player location with the room (in a project with only rm_Grassland room):
```gml
var _player_location = {
    x: 160,
    y: 512,
    room: rm_Grassland,
};

show_debug_message("Raw:");
show_debug_message(_player_location);

var _json = json_stringify(_player_location);
show_debug_message("Saved:");
show_debug_message(_json);

var _loaded = json_parse(_json);
show_debug_message("Loaded:");
show_debug_message(_loaded);
```

The output I got was the following:
```gml
Raw:
{ x : 160, y : 512, room : ref room 0 }
Saved:
{"x":160.0,"y":512.0,"room":"@ref room(rm_Grassland)"}
Loaded:
{ x : 160, y : 512, room : "@ref room(rm_Grassland)" }
```

The Loaded struct has `"@ref room(rm_Grassland)"` string as room, whereas it should contain the `ref room 0` handle instead (like Raw).

**Comment by JujuAdams** [comment]
Intrigued to learn how this behaves with global functions. Does it export references?

**Comment by rwkay** [comment]
I would not rely on it at present as it stores a number (not the name) and between builds of the game that number would be unreliable... it will have similar issues to `game_save` in that regard

**Comment by rwkay** [comment]
Issue with handles being read in is now Fixed in 2024.2

**Comment by thennothinghappened** [comment]
What happens if you save some JSON including unsanitized user input? Otherwise this would be fine and apologies if I haven't read up on this properly - just saw it in the issue list and jumped in - but couldn't you use that implicit behaviour to crash the game, or worse, mess with a server receiving said JSON?

**Comment by sihammill** [comment]
Feature verified in IDE v2024.200.0.472  Runtime v2024.200.0.488
