### ISSUE TITLE
Preferences: Add ability to define the default Animation Speed value for Sprites on an Asset layer in a room

### ISSUE THREAD

**Issue by jorvidthegame** [YoYoGames/GameMaker-Bugs#2831]
### Is your feature request related to a problem?

It would be very nice to be able to set the default animation speed for sprites added to an asset layer.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/b945dd86-ec49-41f9-8880-748f7b1ef96d)

Right now it defaults to 1, so if you want to add a lot of static sprites you have to set it to 0 for each sprite added, which can get very tedious. Being able to set the default value would save so much time and effort.

Note that this new Preference would be distinct from the existing Preference to set the default speed of the sprite itself, as these two values are not the same thing:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/de5c97f4-fe49-4e26-b83f-2a974687b681)

### Describe the solution you'd like

An option in preferences to define the default animation speed for sprites when adding them to an asset layer.

### Describe alternatives you've considered

An alternative would be to add this option to the properties of the asset layer itself.

**Comment by YYDan** [comment]
Added a screenshot to clear up any confusion.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.529  Runtime v2024.400.0.550. 

The new preference has been added to Preferences>Sprite Editor. Thank you. 



![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59605840/cb62817e-6bcc-4af1-9769-d881d28e15c3)
