### ISSUE TITLE
Bug Reporter: Check for expired GitHub authorisation and warn if link has been lost

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2860]
### Is your feature request related to a problem?

While user fills bug report form, IDE could use API to check if current user account is (still) authoruzed on github, by calling `/user`, checking if any username/user id is returned, and informing about that on Bug Report form.

If authorisation with github account would stop to work because of _any_ reason (both on YYG side, or because user rejected authorisation), it should inform user that he need to do it again, and allow "refreshing" linking status before submitting a bug (so refresh button should be available at end of line for example).

### Describe the solution you'd like

Linking status below authorisation link on top of bug report form: 

![obraz](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/524094/7ad3a46c-e8f6-4561-9154-32597c01d5cb)

**Comment by yyalansavage** [comment]
Hi and thanks for your suggestion. I've implemented a simpler solution for the time being which is to show a dialog requesting re-authorisation if the post fails because a previously authorised token is invalid for whatever reason. 
![GitHubAuthFailDialog](https://github.com/YoYoGames/GameMaker-Bugs/assets/8818217/64748052-136f-4591-8cb5-af3b6813ff1f)

**Comment by gnysek** [comment]
I like this solution, it also solves this issue!

**Comment by YYDan** [comment]
This works fine in IDE v2024.200.0.483 when sending public reports (which is the only route that uses a user's GitHub account), so closing.

_There is a separate-but-related issue when sending a **private** report and results in a different dialog being shown, but that's reported elsewhere._
