### ISSUE TITLE
Project Load: Add warning on detecting that the project .yyp file was incorrectly tampered with outside GameMaker

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#2890]
### Is your feature request related to a problem?

A problem I have to help beginners with not infrequently is when they attempt to rename their project by changing the name of the .yyp file directly in the file browser. This causes the project to do all sorts of weird things when next opened, like objects placed in the room editor turning into completely different objects, and new code added to the project not being compiled at all. The problem happens even if gamemaker is closed at the time of renaming.

Another common cause of this sort of project corruption is having the project stored in a folder being backed up by Microsoft Onedrive (or other cloud backup services). Onedrive does all sorts of horrible nasty things to the project, since it likes to replace the files with dummy files of sorts.

### Describe the solution you'd like

Give a warning in the IDE when first opening a project that has had it's .yyp renamed, or that has had it's files tampered with incorrectly in some other way (like if Onedrive did it's thing). The problems can usually be fixed by doing a save as of the project, so perhaps it could suggest that to the user.

**Comment by stuckie** [comment]
The OneDrive portion has been actioned as of #2859

**Comment by stuckie** [comment]
This should now be fixed so that we do not tie the project name to the project file name... which'll allow you to rename the .yyp as necessary.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.541  Runtime v2024.400.0.560. 

Renaming the .yyp does not corrupt the project. Thank you.
