### ISSUE TITLE
Ability to switch the current audio output device

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#2895]
### Is your feature request related to a problem?

Sometimes when streaming a game you may want it to output to a particular audio device (for example a virtual speaker of sorts) for later muxing. Or if you're playing a game on a laptop you may want to force the game to play through speakers when you have headphones connected (or an HDMI projector with built-in audio which won't be the default device).

Currently GameMaker only allows playback through the "default" audio device on Windows, if that device is lost sound won't be recovered (to be fixed in 2023.11?), but even 2023.11 won't allow output device selection.
I assume 2023.11 will call wasapi `GetDefaultAudioEndpoint` in a loop to obtain a default device if it got lost, which is a good solution but that still doesn't allow to choose a custom device which this FR is about.

### Describe the solution you'd like

`audio_get_listener_count` to obtain the count of devices,

`audio_get_listener_info` to obtain information about a specific device,

and `audio_set_listener_mask` to force a particular device globally.

I'm aware that listeners aren't devices, but on some target platforms (consoles) this is the case (1 Listener == 1 Device).

### Describe alternatives you've considered

Hooking into GameMaker's internal ALCcontext -> ALCdevice variables to manually restart the playback thread, oh and also hook wasapi `GetDefaultAudioEndpoint` so that GameMaker always receives the device I want.

This isn't a pretty solution.

**Comment by YYDan** [comment]
"Duplicate", yes, as this one came first ;)
