### ISSUE TITLE
Start new projects with a seed .gitignore and .gitattributes file

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#2922]
### Is your feature request related to a problem?

Following the 2023.1 update, `.resource_order` and `.old` files began appearing in projects, which should not be checked into source control by default. If someone sets up Git but isn't aware of this change (especially if they are using a source control tutorial), they may accidentally add these files to their repository, resulting in constant "file modified" issues and merge conflicts from regular use.

Also, historically GM projects on GitHub had been mistakenly identified as about 20%+ YACC because of the `.yy` files ([example](https://github.com/dicksonlaw583/GMChameleon)). That false detection can be turned off by adding a `.gitattributes` file, but there has been little community awareness of the issue.

GM projects should be source-control-friendly by default, but these issues get in the way of that.

### Describe the solution you'd like

I would like new projects to be created with a default `.gitignore` and `.gitattributes` file that covers current use cases.

`.gitignore`:

```
# Windows

# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk

# Mac

## General
.DS_Store
.AppleDouble
.LSOverride

## Icon must end with two \r
Icon

## Thumbnails
._*

## Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

## Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

# GameMaker temporary files
*.resource_order
*.old
```

`.gitattributes`:

```
# Ignore .yy files for language statistics 
*.yy linguist-generated=true
```

### Describe alternatives you've considered

I have been gradually adding these to my existing projects as I migrate them to the 2023 format, but going forward, I would like to see new projects start with them.

**Comment by CalumLaverock** [comment]
A preference has been added into Plugin -> Source Control (Git) -> Add skeleton .git defaults which, when checked, will automatically add default .gitignore and .gitattributes files as described in the issue here (as well as in https://github.com/YoYoGames/GameMaker-Bugs/issues/4820) into the project folder when the project is created.

**Comment by Emc1923** [comment]
Reopening as neither Mac or Ubuntu generate the files on new projects.

**Comment by CalumLaverock** [comment]
This seems to be more due to mac very thoroughly hiding files beginning with a dot, these can be shown by doing cmd+shift+dot but the files do seem to actually be there on mac as well.

**Comment by Emc1923** [comment]
Verified done as per comment. Thanks!

**Comment by YYBartT** [comment]
Moving this ticket back to "Done" since documentation still needs to be added.

**Comment by YYBartT** [comment]
The contents of the default `.gitignore` and `.gitattributes` files have been documented on the manual's Project Format page. The new preferences have been added to the Plugin Preferences page and the screenshot has been updated.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.550  Runtime v2024.400.0.567
