### ISSUE TITLE
Update OpenSSL

### ISSUE THREAD

**Issue by adam-coster** [YoYoGames/GameMaker-Bugs#2933]
### Is your feature request related to a problem?

Our publisher runs security scans on our builds, and informed us of the following security issue **on Android**:

> The App embeds an outdated version of OpenSSL, which may be vulnerable to security issues:
yoyo.so--1.0.2f or earlier

Which, if I'm understanding correctly, means that the OpenSSL version shipped on Android is from 2015 or earlier.

I'm assuming that OpenSSL is used to mediate HTTPS and other secure connections, so having a more recent version would be good for security!

### Describe the solution you'd like

Have OpenSSL bumped to 3.0.0 (2021 LTS) or 3.1.0 (2023 LTS)

### Describe alternatives you've considered

I'm not actually sure how OpenSSL ends up in the build, so it could be something that we could resolve ourselves or that doesn't actually matter. I'm not sure how to figure that out!

**Comment by adam-coster** [comment]
@FrancisCoulombe I never did find out. @shichen85 -- can you look into this? It's not urgent, but it'd be nice to be able to give a confident answer about the security audit!

**Comment by shichen85** [comment]
None of the extensions we use directly mentions OpenSSL, so I am at loss here too. @FrancisCoulombe Which version of the GameMaker runtime are you using?

**Comment by FrancisCoulombe** [comment]
@shichen85 Im currently on v2023.11.1.160 . Only extension we are using is a wrapper for the SDK of the publisher whose security scan gave this error. Maybe one of the implementations of that extension trips the security scan?

**Comment by shichen85** [comment]
> @shichen85 Im currently on v2023.11.1.160 . Only extension we are using is a wrapper for the SDK of the publisher whose security scan gave this error. Maybe one of the implementations of that extension trips the security scan?

Thanks for the info. Yes we use v2023.11.1.160 as well and only has a wrapper extension for the SDK. It is the strange that the security scan mentions `yoyo.so--1.0.2f or earlier` specifically, but if the GameMaker runtime uses LibreSSL instead, then the only possible origin is the extension. Our extension has the following dependencies, but I have not found a way to see whether any of them embeds OpenSSL or not:

```gradle
<YYAndroidGradleAndroid>
    compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
    }


    buildFeatures {
    viewBinding true
    }
</YYAndroidGradleAndroid>

<YYAndroidGradleDependencies>
    implementation 'com.github.backtrace-labs.backtrace-android:backtrace-library:3.7.5'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'iy
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'

    implementation 'androidx.security:security-crypto:1.0.0'
    implementation 'com.bugsnag:bugsnag-android:5.8.0'
    implementation 'com.apollographql.apollo3:apollo-runtime:3.1.0'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'net.zetetic:android-database-sqlcipher:4.5.3'
    implementation 'androidx.room:room-ktx:2.4.3'

    implementation 'com.google.android.gms:play-services-recaptcha:16.0.1'
    implementation 'com.google.android.gms:play-services-base:18.0.1'

    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'com.google.code.gson:gson:2.8.0'

    implementation 'com.fasterxml.jackson.core:jackson-core:2.10.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.10.1'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.10.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.10.1'
    implementation 'org.slf4j:slf4j-nop:1.5.8'

    implementation 'com.google.android.play:feature-delivery-ktx:2.0.0'

    //Publisher SDK

</YYAndroidGradleDependencies>
```

That being said, does your game actually use any networking/http functions? If not, I heard from other devs that you can just tell the publisher that the engine uses LibreSSL on version 3.5.3, and that your game does not use any networking/http functions, which they supposedly will be OK with.

**Comment by FrancisCoulombe** [comment]
Cross-referenced with my own implementations, and unfortunately it doesn't narrow it down at all, I have all of these as well.
And yes, after I told them the engine uses LibreSSL 3.5.3 they said it was probably a warning we can ignore.
