### ISSUE TITLE
Supply server socket ID in async load

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#2936]
### Is your feature request related to a problem?

In Async - Networking events, you don't get supplied a server ID at all in a server's Data event. While having multiple servers may not be a common usecase, this can happen, 

### Describe the solution you'd like

Having the server socket ID passed in through `async_load` would be very handy

### Describe alternatives you've considered

There's no solution to this, outside of just having one server at a time

**Comment by yoyo-danielc** [comment]
Implemented in 2024.08 - data events for sockets attached to a server have a `server` field in the `async_load` map.

**Comment by YYBartT** [comment]
Added the new `"server"` key under "Receiving Data" on the [Networking Async Event page](https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Object_Properties/Async_Events/Networking.htm).

**Comment by cameron-home** [comment]
@yoyo-danielc Do you have a test project for this?

**Comment by cameron-home** [comment]
Verified working using the attached project in IDE v2024.800.0.604  Runtime v2024.800.0.627:
[server.zip](https://github.com/user-attachments/files/16529665/server.zip)
