### ISSUE TITLE
matrix_inverse (and other matrix functions, if you're feeling ambitious)

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#2960]
### Is your feature request related to a problem?

Implementing matrix_inverse in gml is slow

### Describe the solution you'd like

A runtime function to invert a matrix

### Describe alternatives you've considered

[Doing it yourself](https://github.com/DragoniteSpam-GameMaker-Tutorials/3DCollisions/blob/fd1ee8bc3d090d1d5119e390acfdf6b993b1a2cd/scripts/Col_Matrix/Col_Matrix.gml#L114) (or pilfering snidr's code for it, anyway), which is slow

### Additional context

I think I submitted this in the old feature request form, but apparently it didn't get migrated.

[There are a bunch of other matrix functions which a game dev might conceivably want to use](https://github.com/gszauer/GamePhysicsCookbook/blob/master/Code/matrices.cpp) but inverse is probably the most commonly requested one.

See also my other old request YoYoGames/GameMaker-Bugs#4205 for letting the user pass an existing matrix to contain the output instead of having to allocate a new one.

**Comment by yymrennie** [comment]
A native matrix_inverse() function has now been added in 2024.11

**Comment by YYDan** [comment]
Removed the additional content for things which have not been done as part of this change

**Comment by YYBartT** [comment]
Added a new function page for `matrix_inverse()` to the manual as well as other improvements and additions to the matrix function pages, including the storage order of matrices in arrays and the order of matrix multiplication. Also added additional code examples to a few function pages.

**Comment by alicemoretti** [comment]
Verified that the function has been added to  IDE v2024.1100.0.685  Runtime v2024.1100.0.707 and it works as intended. 

Waiting on the documentation being released before setting the status as verified.

**Comment by alicemoretti** [comment]
Verified that a page for matrix_inverse has added to Manual Beta build #412 and is correct. Thank you
