### ISSUE TITLE
Automatically Remove the `_stripN` from Sprite Assets when Drag and Dropping Sprite Strips into GameMaker

### ISSUE THREAD

**Issue by theinfamousmrmeow** [YoYoGames/GameMaker-Bugs#2963]
### Is your feature request related to a problem?

It is frustrating to try to manage sprite asset changes in game maker.
In our workflow, we generate sprites in Asepsrite, export them to something like `spr_character_action_strip6`, and drag them into Game Maker.
This can add a bulk load of sprites easily, but then we still have to go touch each one and remove the `_strip6` from them and this can be quite time consuming.

### Describe the solution you'd like

Game Maker should have a setting, or perhaps even the default behavior, to automatically remove the `_strip6` from the ends of sprite strips it successfully imports.

So for example, if I import `spr_character_action_strip6`, the resultant Sprite in game maker's asset browser would be `spr_character_action`.

### Describe alternatives you've considered

People have written other tools for managing sprite assets in GM, but none are convenient, easy to use, or officially supported.

Renaming by hand is fine when you have 20 Sprites, but if you want to change the palette of 400 sprites that is a lot of mouse clicks.

**Comment by DragoniteSpam** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/fef26506-c67d-4881-a0b3-b11e23120dff)

day 4,000 of wishing the IDE would trim the name for me: fighting the IDE lag to rename them manually feels like climbing a mountain with boots made out of cement

**Comment by tabularelf** [comment]
+1 would be a nice small QoL on the users end

**Comment by Totobal5** [comment]
+1

**Comment by rwkay** [comment]
Fixed in 2024.4

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.531  Runtime v2024.400.0.551 and changes are in the manual, thanks.
