### ISSUE TITLE
Add an option to specify "step" in the ImGUI slider control

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#2971]
### Is your feature request related to a problem?

Currently, there's no way to specify how precise the slider should be; `dbg_slider` only allows specifying minimum and maximum values, not the step between them. It means we can't easily make a slider that e.g. operates on integers only.

### Describe the solution you'd like

Allow specifying the `dbg_slider` step. One option could be adding a step-specific argument after label, though it breaks the convention of label argument always being last.

Another possibility would be passing additional configuration as struct, so that any additional configurations would only require expanding the struct, while keeping the function signature the same. Though it still is tricky with minimum and maximum arguments already being there.

### Additional context

Original suggestion appeared here: https://forum.gamemaker.io/index.php?threads/dbg_slider-missing-step-size-argument.105748/#post-637205

**Comment by rwkay** [comment]
> Can this also be done to the Drag control?

what do you mean Drag control?

**Comment by rwkay** [comment]
Fixed in 2024.6 - I have added a new (optional) parameter to both `dbg_slider` and `dbg_slider_int` where a step value can be given (note this value should be non-negative and >0),

**Comment by YYBartT** [comment]
Documented the step size as an optional parameter on both the `dbg_slider()` and `dbg_slider_int()` page.

**Comment by mgeddesGM** [comment]
tested in  IDE v2024.600.0.557  Runtime v2024.600.0.572 and  IDE v9.9.1.677  Runtime v9.9.1.818

@gurpreetsinghmatharoo dbg_slider and dbg_slider_int work as expected but the step example in the beta manual, [here](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FDebugging%2Fdbg_slider.htm&rhsearch=dbg_slider_int&rhhlterm=dbg_slider_int) and [here](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FDebugging%2Fdbg_slider_int.htm&rhsearch=dbg_slider_int&rhhlterm=dbg_slider_int), are missing a label value so send up displaying the expected step value

**Comment by YYBartT** [comment]
@mgeddesGM That should be changed now in the `develop.bart` branch

**Comment by mgeddesGM** [comment]
verified on latest beta manual

**Comment by sihammill** [comment]
It appears to work in GMRT but the visual side of it needs some work.

GMS2
<img width="595" height="295" alt="Image" src="https://github.com/user-attachments/assets/ebd0ce25-d260-4587-800a-d5836c761b11" />

GMRT
<img width="324" height="254" alt="Image" src="https://github.com/user-attachments/assets/8988df8a-88fd-4673-bdf1-a1f5fba8a334" />
