### ISSUE TITLE
Make the various ..._exists functions return false instead of giving an exception when passing values such as undefined

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#3034]
### Is your feature request related to a problem?

Right now, if you do something like`a = undefined;
if sprite_exists(a) {...}` The game will crash. This makes the function much less useful than it could be, and is also rather unintuitive. The same sort of issue is true with things like object_exists and surface_exists. 

### Describe the solution you'd like

I think these functions should return false for any invalid value, rather than giving an exception. The whole point of these functions is to check if a value is the correct type to prevent crashes, so if the crash prevention tool causes crashes, that's not super useful.

This is especially true with the upcoming ref changes in beta, where various indexes are getting changed to refs. Using -1 as a placeholder for a ref isn't intuitive, and you won't be able to do something like `if (is_real(value) and sprite_exists(value))` to prevent the crash anymore (plus that solution didn't feel great already). 

If this change was implemented, undefined would become a much more universally useful default value for variables.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.468  Runtime v2024.200.0.484
