### ISSUE TITLE
sprite_get_info does not contain info whether sprite is on a separate page

### ISSUE THREAD

**Issue by MeliusCZ** [YoYoGames/GameMaker-Bugs#3035]
### Is your feature request related to a problem?

Function sprite_get_info already contains quite a few useful things but does not include whether sprite is on separated texture page.

### Describe the solution you'd like

Just add information about whether the sprite is on a separate texture page or not.

**Comment by stuckie** [comment]
There should be a texture page entry for each sprite frame.
Is this what you are looking for?

**Comment by stuckie** [comment]
Closing for now.
If there is still an issue, feel free to log another ticket with additional information.
