### ISSUE TITLE
Exclude particle built-in sprites from the project texture page when they aren't used in the project

### ISSUE THREAD

**Issue by Dudeidu** [YoYoGames/GameMaker-Bugs#3056]
### Is your feature request related to a problem?

The particle sprites that come included with the engine (star shape, snowflake, etc...) automatically gets added to the "Default" texture page, even if they are never used in the project.
Even if they are used, since you can't control which texture page it gets added to It might cause an unnecessary texture swap.

### Describe the solution you'd like

They should not be included at all if none of the "Constant.ParticleShape" ("pt_shape_*") constants are found in the game code.

### Describe alternatives you've considered

An alternative would be to somehow allow assigning them to a different texture page, like the rest of the sprites.

**Comment by stuckie** [comment]
Closing as this should be fixed.
