### ISSUE TITLE
Ticket: #184305 - Get sequence ID, object ID, text ID, etc. via room editor asset name

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#308]
GM-1124

*Description:* Please see the forum link, but I would like to be able to grab a sequence ID via the asset name in the room editor as I can do with a sprite. I would like to be able to do the same with objects and text as well.

*Benefit:* I can place sequences using the room instead of using GML to create the sequence instance and then move it to where I want. I want to be able to use the room editor more for placing objects, sequences, and text. Right now, I am noticing that I mostly code my game via GML for positions and having to do calculations to place sequences, text, and objects. My room editor looks empty before starting, then is populated when the game is running. I think GameMaker should use more of the GUI to make programming initial positions easier. Especially when creating a GUI on the GUI layer. It should be an easy drag and drop process for GUIs (text and buttons).

**Comment by ParodyKnaveBob** [comment]
One can currently grab **and** rename IDs for instances of objects (`inst_*`), sprites (`graphic_*`), and sequences (`graphic_*`) placed into a room via the room editor.

**Comment by YYDan** [comment]
Closing as per above, now that I see this was updated ages ago ;) - thanks for commenting!
