### ISSUE TITLE
[Sequences] Some way to get the ids of instances created by a sequence

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#3090]
### Is your feature request related to a problem?

I was trying to help someone with a situation where they were handling hitboxes for attacks inside sequences. The hitbox instance track was only active for part of the sequence, but the way sequences work, instances are created immediately as soon as the sequence is created, even if they are not part of any active tracks yet. Visibility is disabled while the instance track isn't active, but this meant that the hitbox objects were still running code and being collidable even while their track was inactive.
My first thought to solve this issue was to add a moment to the sequence to destroy the hitbox objects manually or perhaps change a variable on them, but I searched and searched and could not find any way at all to get the instance ids of the instances in the sequence. Even digging through the sequence instance struct only yielded a track name and an object_index, neither of which could be used to get the specific id of the instance created in the sequence.

There are possible workarounds, but all of them feel janky. 
You could create the instances separately before creating the sequence and use sequence_instance_override_object, but that would add a ton of extra code and complexity if the sequence had many objects in it.
You could also add a check in the object itself for something like `if (in_sequence and !visible)`, but that makes it so you can no longer use visible for anything else, and moves behavior directly related to a sequence outside of the sequence itself, which could get pretty spaghetti.

### Describe the solution you'd like

At the very least, I'd like to see instance ids added to the sequence instance struct. Ideally though, I'd like to see something more intuitive, since sequence structs are a bit of a nightmare to navigate.
Perhaps `layer_sequence_get_instance_ids(sequence_element_id)` which would return an array or struct of instance ids for every instance track in the sequence.

This still wouldn't allow you to easily reference the instances in a moment, so another option would be to allow sequences to directly refer to track names as if they're a variables when running code in the scope of the sequence (like when running code in moments), and doing so would give you the instance id of the instance on the track. Other kinds of tracks, like sprite tracks, could give an asset ID instead.

A combination of the two could be something like `layer_sequence_get_track_instance_id(sequence_element_id, track_name)` which would give you the instance id of the instance on that specific track. 
The issues with this solution and the previous one are that tracks have the same name as the object placed on them by default, and multiple tracks can have the same name. However, having a way to directly refer to the instances in a sequence via moments would make a lot of things easier to do, and make sequences much more powerful as a tool for running custom code at specific times.

### Describe alternatives you've considered

Issues like the hitbox one I described could also be solved if there was some sort of option you could toggle for a sequence instance that lets you choose whether objects inside are all created up front and destroyed at the end (like it works now), or if they instead are created or destroyed when their track starts or ends.

**Comment by jackerley** [comment]
Duplicate
