### ISSUE TITLE
FMOD

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3133]

**Comment by JellyTale** [comment]
Why was this moved to feature requests? 😭 Please tell me this hasn't been shelved?

**Comment by gnysek** [comment]
@JellyTale It's "In Progress" in Team Workflow ( https://github.com/orgs/YoYoGames/projects/17/views/7 ). They are cleaning Bugs and FRs issues a bit today, so don't worry about adding tags/labels.

**Comment by DiasFranciscoA** [comment]
https://github.com/YoYoGames/GMEXT-FMOD/releases
