### ISSUE TITLE
Keyboard information for Key State And events

### ISSUE THREAD

**Issue by Dibbenator** [YoYoGames/GameMaker-Bugs#3136]
### Is your feature request related to a problem?

I am using a Keyboard Controller and the "Key Down - Any",  "Key Press - Any" and  "Key Up - Any" events, rather than creating key events for every single key used in the game.

I have been mostly successful with this for the Key Down and Key Press events, but whilst debugging some issues today found that the Key Up function was not working as intended. The reason for this turned out to be because the functions I found where I could identify which keys had been used were keyboard_key and keyboard_lastkey, which are not the actual keys that led to the event being run.

These were particularly unsuitable for the "Key Up" function. Using keyboard_key or keyboard_lastkey,, the key reported can both be completely different than the key that led to the event.

### Describe the solution you'd like

A function or functions where it is possible to read the status of the key that actually led to the function being called.
E.g., 

CurrentKey = keyboard_key_event
Returning [Virtual Key Constant (vk_*)]   as the key that was pressed to lead to the event being called

### Describe alternatives you've considered

As a GameMaker feature;
A variable available in the event that stores the key that led to the event (I checked and this doesn't exist

What I am currently doing;
Storing the state of every key that has been pressed and checking if each one is the key that has been replaced (this is a very nasty solution, hence making the feature request)

**Comment by ParodyKnaveBob** [comment]
It sounds to me like all this user could really use -- and I agree as a new general-purpose functionality -- is a new `keyboard_lastreleased` to go with the extant `keyboard_lastkey` and `keyboard_lastchar`. Could this be reopened as such?
