### ISSUE TITLE
Audio FX Parameter Tracks

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3162]
Adds the ability to manipulate Audio effects properties within a sequence, so those properties can be manipulated over time.

**Comment by alicemoretti** [comment]
Tested the IDE side on the current Beta. Bugs have been entered separately.

**Comment by sihammill** [comment]
verified in Beta IDE v2024.200.0.494 Beta Runtime v2024.200.0.511
