### ISSUE TITLE
IDE Plugins

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3199]
Add backend architecture for the IDE to have elements that are 'plugins'.

These will be able to be updated outside of regular full IDE updates via GMPM.

Initial plugins will include, but not limited to:
- Project Tool
- IDE Localisation

**Comment by stuckie** [comment]
The architectural changes are now in.

**Comment by sihammill** [comment]
I can see both plugins are there in GMPM and I have verified that both can be updated via this method in IDE v2024.1100.0.688  Runtime v2024.1100.0.709
