### ISSUE TITLE
Private Variables

### ISSUE THREAD

**Issue by LesserGoldfish** [YoYoGames/GameMaker-Bugs#3205]
### Is your feature request related to a problem?

By default, game maker does not have an easy way of encapsulating code, requring messy work arounds such as putting private varaibles and methods into a struct. While having every instance variable exposed by default is simpler for newer programmers, it would be nice to have a way to keep varaibles which rarely, or never, interact outside of their instance hidden.

### Describe the solution you'd like

A new keyword "private" would be added which would be used in a similar way to "static", added before the variable name to make it private to the instance it was created in. This means that, by default, instance variables remain exposed to keep things simple for never developers but can be used by those more advanced

### Describe alternatives you've considered

Another possible impelmentation is through jsdoc comments, which would indicate to feather to hide a varaible or method from the auto complete and throw an error if a user does attempt to access a private variable outside of its scope

**Comment by Gamer-XP** [comment]
I think there is no need for real "private" variables in GML. But it may be good to have some sort of hint for Code Editor to just not show variable in auto-complete if you're accessing it from the outer scope.
