### ISSUE TITLE
Prefabs Phase 1

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3218]
Prefabs are the ability to reference one project from another, and only the assets used by the main project will be included in the game.

Any asset types will be allowed (though rooms may complicate this).

Prefabs may reference other prefabs (allowing for nested prefabs) but loops of dependencies are not allowed.

Phase 1 for prefabs will be the initial release with
* Tooling for adding prefabs into projects and only including the assets used.
* Integration with the Package Manager (which will deliver all prefabs to the system)
* ~~Tools for adding prefab assets into your project within Room Editor / Sequence Editor.~~ moved to #4681 
* Working with early adopters to create local packages (invite only)

New format brief explanation
---------------------------------

Example excerpt:

```
{
  "$GMProject": "",
  "%Name": "23_01_2024-game",
  "AudioGroups": [
    {"$GMAudioGroup":"","%Name":"audiogroup_default","targets":-1,},
  ],
  "configs": {
    "children": [],
    "name": "Default",
  },
  "defaultScriptType": 0,
  "Folders": [
    {"$GMFolder":"","%Name":"Sprites","folderPath":"folders/Sprites.yy",},
    {"$GMFolder":"","%Name":"Tile Sets","folderPath":"folders/Tile Sets.yy",},
    {"$GMFolder":"","%Name":"Sounds","folderPath":"folders/Sounds.yy",},
    {"$GMFolder":"","%Name":"Paths","folderPath":"folders/Paths.yy",},
```

All records are in ALPHA SORTED order, which is a requirement.

Typed records are indicated with a leading TYPE TAG and space for a VERSION.
The version will be "" until we start using revisions, then it will be v1 v2 v3 etc
These will always be first in a JSON record (they must be!):

```
  "$GMProject": "",
```

Objects with names will have a name field that is now called %Name to cause it to appear at the top
after the type tag:

```
  "%Name": "23_01_2024-game",
```

The formatting is better, and should give a better Git Merge experience.

Git Merge MIGHT become a support issue because the fields DO NOW NEED TO REMAIN IN ORDER.
But actually that might help!

Compatibility
----------------

To keep some compatibility with previous IDEs, we have reinstated the following fields
**resourceVersion** - will be pinned to 2.0; please use the TypeTag if you are requiring to operate on a specific version.
**resourceType** - tracks the same as the TypeTag; GMSprite, GMProject, GMObject, etc..
**name** - tracks the same as the NameTag

This allows older IDEs to open the projects in *read-only* mode, but support will start to deteriorate as new resources and changes are made, so you should make use of ProjectTool ( Tools->Project Tool from the IDE ) to fully downgrade projects to an older version if required.

For the sake of clarity, this covers:
- YYP projects
- YYZ archived projects
- YYMPS Marketplace and Local packages

**Comment by stuckie** [comment]
Is there anything else that your tools would need/like that we could change just now?
We will likely split the resource tag back out again, and we don't really want to change format output again - at least not for a long while!

**Comment by stuckie** [comment]
We have added resourceVersion and resourceType back in.

The resourceType field will track the same as it always did - GMSprite, GMAudioGroup, etc..
The resourceVersion field will always be 2.0 - this stops previous over eager IDEs from trying to load it and making a mess.

So, because the versioning has changed, if you do need to rely on what version a resource is, you are best parsing the new top tag.

**Comment by stuckie** [comment]
Just to keep the chain updated, we've re-added the name field too, and I've added a Compatibility set at the bottom of the original ticket to explain this.

**Comment by adam-coster** [comment]
@stuckie I wrote up a separate issue asking for some guidance on formatting:https://github.com/YoYoGames/GameMaker-Bugs/issues/4713

**Comment by backYard321** [comment]
Can't wait for this!

**Comment by Emc1923** [comment]
Verified support added internally.
