### ISSUE TITLE
New Code Editor

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3219]
Complete reworking and architecting of the whole Code Editor within GameMaker.

**Teaser Section** 

Multiple events in one place, plus adding, removing and editing events in one place.

![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/3646448/d8b6bd90-c2b7-45fe-9420-2470dda21f5f)

Markdown is now supported in Notes Editor.

![Image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/3646448/3536f6f2-c037-498b-a53a-3048f3d14654)

**Comment by kt-altyn** [comment]
could you also add SVG support in addition to PNG?

**Comment by iampremo** [comment]
> SHIFT + ALT + Up or Down to duplicate line or section of code... 
That's what Ctrl + D is for, which you can also rebind if you want ;)

**Comment by michael-mcmullen** [comment]
Technically CTRL + D should be used to find the next duplicate ;)  Would be helpful if you had code and you highlighted a variable, and hit CTRL + D so that it takes you down to where that variable is found next in the file. (A-la VSCODE/JETBRAINS)

**Comment by rwkay** [comment]
Hmmm I would have used F3 to go to the next thing... never used CTRL+D for this myself...

**Comment by XanthorXIII** [comment]
Please add a section for variable definitions above create so we can do away with having to open and close a window for variable definitions all the time. Otherwise looks pretty good.

**Comment by rwkay** [comment]
> Please add a section for variable definitions above create so we can do away with having to open and close a window for variable definitions all the time. Otherwise looks pretty good.

You can already use the Inspector to do this... that is the intended workflow

**Comment by thennothinghappened** [comment]
> Can you ensure that we can add "events" by just typing them and not having to use a mouse? Eg:
> 
> ```
> #event step
> 
> or
> 
> #step
> ```
> 
> This is what gmedit allows

Seconding this, hoping the new editor to be completely functional by keyboard alone

**Comment by thennothinghappened** [comment]
I'd really like to see non-mouse-based multi-line selections

**Comment by matrugdev** [comment]
Not sure if this is the right place for this, but could there be a way to search for event types? For example search and show all objects with Draw Normal Events, or Step Begin Events.

**Comment by ParodyKnaveBob** [comment]
Those different levels of colored brackets look like a lovely QOL addition, ty.

**Comment by ParodyKnaveBob** [comment]
@rwkay:
> > Please add a section for variable definitions above create so we can do away with having to open and close a window for variable definitions all the time. Otherwise looks pretty good.
> You can already use the Inspector to do this... that is the intended workflow

When selecting an object from the Asset Browser or Recent Windows, the Inspector shows it, yes. When selecting an object from sliding a Workspace around, the Inspector needs to get a clue. $;^ ]

**Comment by AvioxArcade** [comment]
> I'd really like to see non-mouse-based multi-line selections

Shift + Alt + Arrow keys.

That? or wdym by "multi-line selections"?

**Comment by flashice2030** [comment]
when will release the next new IDEs?



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/09/2024 23:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [YoYoGames/GameMaker-Bugs] New Code Editor (Issue #3219) |

I'd really like to see non-mouse-based multi-line selections

Shift + Alt + Arrow keys.

That? or wdym by "multi-line selections"?

**Comment by TheGitMagician** [comment]
> When selecting an object from the Asset Browser or Recent Windows, the Inspector shows it, yes. When selecting an object from sliding a Workspace around, the Inspector has no clue.

This really needs to be implemented - if not as standard then at least as an option. Right now, if you switch between objects via the Workspace or even different script tabs the Inspector has no idea and always displays the Object that is selected in the Asset Browser.

**Comment by 8BitKing** [comment]
while you people are at it could you please make it so pressing escape returns focus back to the text editor when in the search and replace dialog?
![grafik](https://github.com/YoYoGames/GameMaker-Bugs/assets/64686498/8b052b3f-caa9-4648-a934-7c5afa701366)

I cannot find a way to return focus without use of my mouse

**Comment by thennothinghappened** [comment]
> Please add a section for variable definitions above create so we can do away with having to open and close a window for variable definitions all the time. Otherwise looks pretty good.

GMEdit has something similar to this in a sense that I think would be a really nice way to interact with variable definitions:
<img width="843" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/b9b03643-1551-45bb-ac63-76f03d10061d">

Above Create there's another code block which is essentially a "stricter" block that you can only make assignments in the form `variable = value;`. Representing variable definitions this way would be really, really nice, especially in the theme of moving more functionality to the code editor away from workspaces!

The inspector is alright but it tends to feel a bit cramped, and the fact that variable definitions are a distinctly different section than writing regular code disrupts the flow of things a bit.

**Comment by thennothinghappened** [comment]
Also like to reiterate that I'd really like to see a fully keyboard-driven workflow supported - just like GMEdit's system of creating new events via `#event <event name>` seamlessly creates a new block, which is very friendly if you like going all in on keyboard.
<img width="573" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/700094a7-edd2-47b8-aff3-f26c817f211b">

**Comment by ILP17** [comment]
> > Please add a section for variable definitions above create so we can do away with having to open and close a window for variable definitions all the time. Otherwise looks pretty good.
> 
> GMEdit has something similar to this in a sense that I think would be a really nice way to interact with variable definitions: <img alt="image" width="843" src="https://private-user-images.githubusercontent.com/35243139/313855468-b9b03643-1551-45bb-ac63-76f03d10061d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjUxOTksIm5iZiI6MTcxMDg2NDg5OSwicGF0aCI6Ii8zNTI0MzEzOS8zMTM4NTU0NjgtYjliMDM2NDMtMTU1MS00NWJiLWFjNjMtNzZmMDNkMTAwNjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE2MTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDRlOTJjNWQ1NTBkZjU5N2Q2ZDY5MjE2ZGQ5M2RlYjkyZmY1NDU5ZDBiMjljMTdlMmM5MzhjOGQwNDkxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6vWJ1NnrAvqXmj8t43LyxjL74ap8g0yoXsZB8w7S-3g">
> 
> Above Create there's another code block which is essentially a "stricter" block that you can only make assignments in the form `variable = value;`. Representing variable definitions this way would be really, really nice, especially in the theme of moving more functionality to the code editor away from workspaces!
> 
> The inspector is alright but it tends to feel a bit cramped, and the fact that variable definitions are a distinctly different section than writing regular code disrupts the flow of things a bit.

Honestly, I'd love to have a code editor section for variable definitions. I don't like having to switch between windows so much.

**Comment by JustMegaAlex** [comment]
Yeah, basically bringing all beloved features from popular programming IDEs like VSCode. That would be a blast
(I'm currently using VSCode a lot but it's not super convenient to constantly switch between GM and VSCode)

**Comment by oldtimerza** [comment]
Love the look and feel of the new Code editor. 

However one issue is making it impossible to use, backspace on laptop keyboard doesn't work in the code editor.

**Comment by hasnogame** [comment]
@oldtimerza I would recommend downgrading to Beta IDE [2024.400.0.543](https://gms.yoyogames.com/GameMaker-Installer-2024.400.0.556.exe) until a new beta is released. I believe the April betas are now considered [closed](https://forum.gamemaker.io/index.php?threads/2024-400-betas-release-thread.110443/post-668781) due to the release of [2024.4](https://releases.gamemaker.io/release-notes/2024/400).

It seems this issue was introduced in Beta IDE 2024.400.0.549 as the last version without this issue is Beta IDE 2024.400.0.543.

**Comment by oldtimerza** [comment]
Thank you @hasnogame . Will give that a try :)

**Comment by hasnogame** [comment]
@oldtimerza Happy to let you know the [new June beta](https://releases.gamemaker.io/release-notes/2024/600) does not have this issue either. :D

**Comment by oldtimerza** [comment]
Speak about timing. That's fantastic!

**Comment by flashice2030** [comment]
It would be even better if the functionality of debugging code at run time were also made available.

**Comment by stuckie** [comment]
This will be available in monthly, but is still a beta feature ( and is off by default )

**Comment by thennothinghappened** [comment]
> I still see problems in the latest Beta versions, if I close the IDE with several (large: 30+) open scripts, then the IDE with the code editor 2 enabled cannot start the project and freezes.
> 
> Turning off CE2 and starting the project resets the open tabs, which allows you to turn on CE2 and start the project.
> 
> It is also noticed that each file opens for a few seconds and disappears 200 MB of memory with each open script (scripts are not large).

File a bug report. This issue tracked getting CE2 mostly there and into monthly.
