### ISSUE TITLE
Auto-Indentation Feature for Code Editor in GameMaker

### ISSUE THREAD

**Issue by nuevocharrua** [YoYoGames/GameMaker-Bugs#3247]
### Is your feature request related to a problem?

Yes, when working with large amounts of code in GameMaker, it becomes time-consuming and difficult to manually ensure that the code is properly indented. Poor indentation can make code harder to read and understand, which impacts both the speed and quality of development.

### Describe the solution you'd like

I propose the implementation of an integrated auto-indentation feature in the GameMaker code editor. This feature would automatically format the code according to established conventions, making it more readable and manageable. This not only increases efficiency but also reduces the likelihood of errors, making code easier to debug. An auto-indentation feature would greatly improve the workflow and experience for all GameMaker developers.

**Comment by YYDan** [comment]
This one has clearly been missed, but just to say that this feature is already in 2024.400 Betas which contain the new code editor - there are some open bugs with it just now, but this feature does now exist and you're welcome to try it now in the Beta IDEs, so closing off this feature request.
