### ISSUE TITLE
In-Game: asset_has_tags() always returns "true" if the object has any tag

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#335]
GM-757

Issue:
 asset_has_tags function is returning true incorrectly when the input does not match the tag

Repro:
# Import attached project
# Run project
# Observe in output:

obj_NoTags asset_has_tags(RandomTag): 0 should be 0
objTags asset_has_tags(RandomTag): 1 should be 1
objTags asset_has_tags(INVALIDTAG): 1 should be 0
objTags asset_has_tags(THEREISNOTAG): 1 should be 0

The object only has the tag "RandomTag"

**Comment by ParodyKnaveBob** [comment]
Duplicate: https://github.com/YoYoGames/GameMaker-Bugs/issues/145

**Comment by JonnoRobson** [comment]
I'm no longer able to reproduce this issue in an up to date version. Output is:

obj_NoTags asset_has_tags(RandomTag): 0 should be 0
objTags asset_has_tags(RandomTag): 1 should be 1
objTags asset_has_tags(INVALIDTAG): 0 should be 0
objTags asset_has_tags(THEREISNOTAG): 0 should be 0
