### ISSUE TITLE
Add tooltip when hovering cursor over a macro or enum showing its value

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3398]
*Customer's description:*

_It would be great that when you put the mouse over a macro (or enum, if you have set specific values to it) for some time a tooltip box showing its value appears._

*Customer's benefit:*

_I use plenty of macros and enums to define constants in my games and I have to middle click on them to fly to their declaration codes many times to check their values. A tooltip box with their values would be really helpful._

**Comment by YYDan** [comment]
This was fixed for macros ages ago and enums are covered in https://github.com/YoYoGames/GameMaker-Bugs/issues/6632, so closing this super-old minimalist report ;)
