### ISSUE TITLE
Allow import of sprites from packages popular with our users (ASESprite + Photoshop + Texture Packers)

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3431]
NOTE : From discussion with Krystian Kolondra

Provide an interface to import from different file formats easily this is 2 fold

1) Import a single image from a file format (this is similar to using ImageMagick to do the import)

2) Import a sprite sheet (or texture packed image) from popular formats - this will need to allow importing multiple sprites at once rather than just a single sprite (like we currently allow using the Convert To Frames dialog)

 

!image-2021-05-05-10-59-26-299.png|width=455,height=251!

**Comment by stuckie** [comment]
Duplicate of #3197
