### ISSUE TITLE
In-Game: Rotated instances can cause off by one collisions on the top or left side

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#345]
GM-692

Issue:
 Rotated instances can cause off by one collisions on the top or left side

The attached project has a sprite that is 32x32 with precise collision mask, when the object is rotated it can cause the object to preceded 1 pixel further than its non-rotated version. This only occurs when going up or left

Standard:
 !image-2021-04-07-11-48-55-590.png|thumbnail! 

Rotated:
 !image-2021-04-07-11-49-15-395.png|thumbnail! 

Repro:
# Import attached project
# Run project
# Use arrow keys to move the purple object around to the top and left and observe pixel-perfect collision
# press A on the keyboard
# use the arrow keys to continue to move up or left and observe you will go 1 pixel further than you previously could

**Comment by jackerley** [comment]
Can't access the project anymore, closing
