### ISSUE TITLE
Compile-time optimizations for make_colour_* functions

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3450]
*Customer's description:*

_Similar to how the "ord" function is optimized at compile-time, I think that the make_colour_rgb and make_colour_hsv functions could benefit from this same functionality. More often than not, I find myself passing static arguments into these functions; which could be optimized into "pushi" instructions rather than having the function be called at runtime. This could provide considerable performance improvements for games, especially when the make_colour_rgb function is assigned to a macro and is called numerous times per frame._

*Customer's benefit:*

_It could improve performance greatly, reducing VM instruction counts from 7 instructions to just a single pushi instruction._

**Comment by YYDan** [comment]
Has been done as part of https://github.com/YoYoGames/GameMaker-Bugs/issues/5688, so closing this old report now.
