### ISSUE TITLE
Improvements to Code Folding

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3486]
Spawned from [https://help.yoyogames.com/hc/en-us/community/posts/360010836958--Suggestion-Code-folding-improvements-JSDoc-curly-brace-position-]

 

The user would like to have Code Folding enabled for comments and for the function to fold on the line of the function definition instead of the bracket.

 

Please follow the link for the original suggestion.

**Comment by YYDan** [comment]
"Duplicate" obviously.
