### ISSUE TITLE
In Game: Sprites drawn with draw_sprite_general using negative xscale/yscale will be clipped from the view prematurely

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#353]
GM-645

Issue:
  When drawing a sprite with a negative image_xscale and/or image_yscale, using draw_sprite_general, the image will disappear if the camera is positioned certain ways, with the sprites close to the edge of the view

The attached project is drawing 4 sprites, only the darkgrey one does not have negative scaling

Repro:
1. Import attached project
2. run project
3. use arrow keys to move the camera around
4. move sprites close to edge or overlapping (but not completely off) of the screen
5. observe that the sprites with negative scaling will stop being drawn before they are off the screen

**Comment by JonnoRobson** [comment]
I have not been able to reproduce this issue in an up to date version. Sprites drawn using draw_sprite_general with a negative image_xscale and/or image_yscale can be moved all the way off the edge of the screen without ever stopping being drawn.
