### ISSUE TITLE
new spine update 4.0

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3685]
User request message on ticket [Ticket #185566]

 

Feature Type: feat_change_ingame
Description: Hello!

I'd like to inform you that Spine has been updated to 4.0.

I heard that you have a plan to update the spa in September 2020, but I am contacting you because I was wondering if you have an update plan this time or next quarter.

Also, I would like to ask if it is possible to add functional expansion such as easy change of textures when updating.

For example, you need the ability to replace attachments (the "regions" in spines) that have already been created in spines.

The current method is too inefficient when many variable parts and attachments occur.

I'm sending you an example code below that I would like to add and present.

I hope it will be added.

old code :
Event animation update -

if(blade_load_0 != -1){
switch(skeleton_attachment_get("wpnBlade"))

{ case "front": skeleton_attachment_set("wpnBlade", "blade_front_new"); break; case "rear": skeleton_attachment_set("wpnBlade", "blade_back_new"); break; }

}

new code(It doesn't have to be exactly the same as the code in the example.) :
Event create or trigger everything -

skeleton_region_replace(slot, region, sprite, sprite_frame);
 - or -
skeleton_region_replace("slot/region", sprite, sprite_frame);

 - and add ext -
skeleton_region_replace_ext(slot, region, sprite, sprite_frame, offsetx, offsety, scalex, scaley, angle, color, blend);
Benefit: Since the project is currently being planned as a long-term live service game, many attachments changes such as avatar and equipment are needed.

For your information, we link you to our project video where many "sprite attachment" changes occur.
This game is being developed as Gamemaker Studio 2.
[https://youtu.be/IHqN598xtQs]

Thank you for read long request.
I'll be waiting for the reply.
Link: [http://esotericsoftware.com/blog/Spine-4.0-is-here]

**Comment by rwkay** [comment]
This was done a long long time ago...
