### ISSUE TITLE
In-Game: Audio queues with no queued buffers will remain in a 'playing' state if played.

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#37]
GM-7894

This seems to be due to checks on whether there is a buffer attached to a source when considering whether or not to mix and advance it. The source corresponding to the audio queue will thus never transition to a stopped state, despite it not actually playing anything.

*Reproduction*
* Open and run the example project [^GM-7894.yyz] 
* Press '1' to create and load up a queue.
* Press '3' to play the queue - wait for it to finish playing. 
* When the queue has finished playing, you'll notice that the playing flag has transitioned to '0'.
* Press '3' to play the (now empty) queue again - nothing will play, but the playing flag will remain at '1'.

**Comment by YYBartT** [comment]
Added a note to the Audio Buffers page mentioning that the `audio_play_sound*` functions return -1 when passed a sound that refers to an - at that time - empty audio queue and added the same info to the function pages.

**Comment by cameron-home** [comment]
Re-opening as the function does not seem to be working in HTML5 when built from IDE v2024.1300.0.715  Runtime v2024.1300.0.728 with the following settings:
![Image](https://github.com/user-attachments/assets/2c3fcbf1-0740-43f9-abf0-4a625e90cb28)

![Image](https://github.com/user-attachments/assets/72365053-a214-41f9-aeac-720cea00d19d)

**Comment by cameron-home** [comment]
Issue in previous comment bugged by Esther: https://github.com/YoYoGames/GameMaker/issues/4630

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1300.0.718  Runtime v2024.1300.0.730
