### ISSUE TITLE
The ability to check references like you could in GMS 1

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3783]
[Ticket #190010]

Feature Type: feat_addition_ide
Description: In GMS 1 I could easily check where any instances are placed in a room by right clicking an object and selecting check references. Right now in GMS 2, that function is mysteriously gone. It is a huge annoyance to have to look through every single room and layer of a project to see if there are any that need to be moved or removed for various reasons. The info is already stored, because when I delete an object it will ask "are you sure you want to delete this, it is used in room x and room y and room z, etc." if there are not other warnings that supersede this one.
I would ask that you please bring back this feature, it's absence has been a real nuisance since my work has switched to GMS 2.
Benefit: This would save me tens of hours of time in the near future, and who knows how much in the long term, likely hundreds. It would also prevent mistakes from being made in our games.
Link:

**Comment by YYDan** [comment]
"Duplicate" of https://github.com/YoYoGames/GameMaker-Bugs/issues/3065
