### ISSUE TITLE
Extensions: [AdMob] Support merging of SKAdNetworkItems arraies before passed to the iOS plist

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#3804]
Currently when using AdMob as a mediation platform, all required SKAdNetworkItems need to be injected to AdMob.yy, under:
```
<YYIosPlist>
<key>SKAdNetworkItems</key>
<array></array>
</YYIosPlist>
```
Otherwise, the SKAdNetworkItems values will be overwritten by the last extension. This makes separation of ad networks (e.g. AdMobMeta, AdMobUnityAds) less meaningful. 

Please support merging of injection plist values if they're arrays, so we can split required SKAdNetworkItems to each ad source's .yy file.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.494  Runtime v2024.200.0.511
