### ISSUE TITLE
Room Editor: Arrow keys no longer work as expected when navigating through layers

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#3805]
### Description

When in the Room Editor, the user can no longer use the arrow keys to navigate through the layers. It appears that pressing the down arrow key when on the bottom layer, it moves to the top layer and then stops working. Similarly, using the up arrow key on the layers navigates through easily but as soon as you press the down arrow key, it breaks again.

[RoomEditor_ArrowKeyBug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13875363/RoomEditor_ArrowKeyBug.zip)

### Expected Change

All arrow keys should navigate through layers as expected

### Steps To Reproduce

1. Start GameMaker and create/import project.
2. Go to Room Editor and create multiple layers in the room.
3. Press the Up arrow key and notice it navigates through the layers easily.
4. Press the Down arrow key and see the issue.
5. Click on the last layer and press the Down arrow key and notice it navigates to the top layer and stops working again.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by SmithTom6304** [comment]
This affects Tab / Shift + Tab navigation as well (with Tab behaving like Down Arrow and Shift + Tab behaving like Up Arrow). Wonder if this is being caused by bad flow values.

**Comment by SmithTom6304** [comment]
Fixed - Up/Down arrows now work correctly and loop around at bottom/top of list. Flow keys also work correctly, and continue past end/start of list when reached.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
