### ISSUE TITLE
Allow accessors natively for global

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3890]
[Ticket #194462]

Feature Type: feat_change_ingame
Description: Allow global to natively support an accessor, similar to structs where you can do global[$ variable] = "value". This is already possible with the workaround:
var _g = global;
_g[$ variable] = "value";

however the following will not even compile:
global[$ variable] = "value";
Benefit: This will allow for clean, non-convoluted code.
Link:

**Comment by YYBartT** [comment]
Documented this in the linked issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/2783

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.469  Runtime v2024.200.0.485
