### ISSUE TITLE
Change the minimum value of physics_world_update_speed() to a fixed lower bound independent of the room speed

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3919]
Requested in ticket Ticket #195279

 

Feature Type: feat_change_ide
Description: Currently, physics_world_update_speed()'s lower bound is tied to the room speed. If you were to have a room at a higher value, say 120 instead of a more commonly used value such as 30 or 60, you'd be forced to have the update speed at 120.
Benefit: This change will allow more flexibility with the physics system, and allow the physics accuracy tradeoff for performance on some of my projects more focused on higher room speeds.

**Comment by YYDan** [comment]
Closing as "duplicate" of a new request for this: https://github.com/YoYoGames/GameMaker-Bugs/issues/7664
