### ISSUE TITLE
Multiple Configs based #macro definition.

### ISSUE THREAD

**Issue by Callsign54** [YoYoGames/GameMaker-Bugs#3930]
### Is your feature request related to a problem?

It'd be useful to have a simple and neat #macro definition for macros that are shared by multiple configurations.

### Describe the solution you'd like

For all configs to share the same #macro
**AndroidFree, AndroidTrial, AndroidTrialX**:ENABLE_ADS true

**Comment by rwkay** [comment]
No we are not going to do this, but when we fix https://github.com/YoYoGames/GameMaker-Bugs/issues/3935 then you will be able to use config hierarchies to do this.
