### ISSUE TITLE
weakref cloned with variable_clone() returns non-weakref struct

### ISSUE THREAD

**Issue by sixesixesixe** [YoYoGames/GameMaker-Bugs#3933]
### Description
_weakref=weak_ref_create({});
_weakref_is_weakref=instanceof(_weakref)=="weakref";
_weakref_clone=variable_clone(_weakref);
_weakref_clone_is_weakref=instanceof(_weakref_clone)=="weakref";

_weakref_is_weakref is true
_weakref_clone_is_weakref is false

furthermore, _weakref_clone contains a ref to a junk struct

[c2e53a16-599e-48eb-9c5d-581d83440d07](https://api.gamemaker.io/api/github/downloads/c2e53a16-599e-48eb-9c5d-581d83440d07)

**Comment by stuckie** [comment]
This is not a bug.
variable_clone is copying the structure as intended.
