### ISSUE TITLE
SDF fonts do not render certain unicode characters

### ISSUE THREAD

**Issue by ShadauxCat** [YoYoGames/GameMaker-Bugs#3934]
### Description
I have a font that does not include any unicode characters in the font. I added ▼ to the character range.

If I generate the texture from this font without SDF enabled, it (presumably) uses a fallback font and generates a glyph for ▼.

When using SDF, the ▼ character is just omitted completely.

### Steps To Reproduce
- Create a font using the Nasalization font (https://www.dafont.com/nasalization.font)
- Click "Add" to add a new range
- Add ▼
- Click "Regenerate"
- Click Game Preview
- Note that the glyph is not present

[1dac7d7a-7dcc-4784-9188-a8a7fdd61fee](https://api.gamemaker.io/api/github/downloads/1dac7d7a-7dcc-4784-9188-a8a7fdd61fee)

**Comment by yymrennie** [comment]
It was actually a bug that the triangle character was being included in the non-SDF version of the font - the results of doing this replacement aren't guaranteed and so the behaviour has been changed to exclude any replacement characters from being used in font textures used by the game (for both SDF and non-SDF fonts). This change has been made in 2024.4.
