### ISSUE TITLE
Asset/folder colours  reseting after a few days

### ISSUE THREAD

**Issue by WoNkY11** [YoYoGames/GameMaker-Bugs#3936]
### Description

This has happened continuously to me over the last few years over multiple releases. It's a minor annoying bug as I do find the feature useful. Searching I find one similar report in Oct'23 so I suspect it's rare occurrence and thus not really a priority.

Still annoying though!. Cheers. 

### Steps To Reproduce

1. Start GameMaker
2.  After a few days (depending on usage). 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Closing as duplicate
