### ISSUE TITLE
Cursor tracking in code editor not right after selecting command from code completion dropdown.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#3937]
### Description
After selecting an item from the code completion dropdown, and then navigating the cursor either up or down to the previous or next line, the cursor's x position jumps to what it was before selecting the item from the code completion dropdown rather than the new x position after choosing the code completion item.

### Steps To Reproduce
1) Paste the following text into the code editor at line 1:
show_debug_message("Hello")

2) Then, on the line below it, start typing this:
show

3) In the code completion window, select the show_debug_message command.
4) Note the current x position of the cursor.
5) Press the up arrow key.
6) Note that the x position of the cursor on line 1 jumped back to just after "show" rather than staying at the x position that it was at when the cursor was on line 2.

[3c87b8dd-9b03-431e-a499-8fec1611e6a6](https://api.gamemaker.io/api/github/downloads/3c87b8dd-9b03-431e-a499-8fec1611e6a6)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.466  Runtime v2024.200.0.482.

Thank you.
