### ISSUE TITLE
collision_rectangle_list etc. take "undefined" as list parameter, so they can be used for counting only

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#3938]
### Is your feature request related to a problem?

Sometimes all you need to know is the number of instances within a specific area. You can use collision_rectangle_list and co. for that but right now you have to create a throwaway list to avoid errors.

### Describe the solution you'd like

Either modify collision_rectangle_list to take "undefined" or -1 for the list parameter to put it into count-only mode or introduce similar functions that are meant for only counting.

### Describe alternatives you've considered

Creating a ds_list and throwing it away without really using it.

**Comment by stuckie** [comment]
We do not think this is a good idea, as it would change what the return value is depending on what it is doing, which could create confusion.

**Comment by nullbunny** [comment]
@stuckie  How would it change the return value? The return value of collision_rectangle_list is the number of items in the list it populates.
