### ISSUE TITLE
Allow physics world updates be triggered manually

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3957]
Requested in ticket [Ticket #196180]

 

Feature Type: feat_addition_ingame
Description: Similar to how the particle system can be toggled to work in a manual mode, make the physics system manually steppable. For example:

// Disable automatic physics
physics_system_automatic_update(false);

// Update physics
var delta = 1/20;
physics_system_update(delta);
Benefit: Currently the Box2D world.Step() command seems to be strictly tied to the room_speed in GMS. This makes it impossible to implement any framerate independent games with the physics system. If the physics system could be manually stepped, then it could be running at fixed rate, say 20Hz, when the game is running at 60 or 120 fps.

Doing this requires advanced frame skipping techniques to be utilized in the game project's code, but making the manual physics update an option (and keeping the current way of working as default), this would open up the possibility to more experienced developers.

**Comment by Limekys** [comment]
Yes! That's exactly what I need for my game too! Please add this feature!

**Comment by YYDan** [comment]
Yes... Closing as "duplicate" of your new request for this: https://github.com/YoYoGames/GameMaker-Bugs/issues/7664
