### ISSUE TITLE
Mouse back and forward buttons for user function navigation

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4065]
Ticket #200951
Feature Type: feat_addition_ide
Description: When you middle click a user function you are taken to the function. If the workspace was in fullscreen, it can be time consuming, and sometimes difficult, to find your way back to where you originally clicked the function. Instead, can we please have the mouse back button return us to where we were before, just like how a bookmark works. Then you could also have the forward mouse button move to the function.
Benefit: Even if this is an option in the menus, the time it would save on large projects would be so beneficial. Currently mouse back and forward do nothing while editing code, so adding this would speed up productivity, and be a really useful feature.
Link:

**Comment by zreedy** [comment]
This is now implemented in CE2. `F1` will navigate to a user-defined function, `Ctrl+Minus` will navigate backwards, `Ctrl+Shift+Minus` will navigate forward once more.

**Comment by zreedy** [comment]
To clarify, this feature was included in the design documents for CE2 and was implemented as apart of its core development. This ticket was missed in the shuffle. Closed now after discovery.
