### ISSUE TITLE
In-Game: Add 'compressor' audio effect type

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4221]
Created as a result of: https://forum.gamemaker.io/index.php?threads/audio-effects-wishlist.100986/

An audio compressor effect reduces the dynamic range of audio going into it, resulting in an output with smaller level differences. This then allows for the overall level of the signal to be increased, having reduced the impact of level spikes.

Compressors are generally parameterised as below:
* *Threshold* - an amplitude level beyond which the level is reduced by the compression ratio.
* *Ratio* - the ratio by which audio that exceeds the threshold is reduced.
* *Input gain* - this allows audio to be pushed into the compression threshold.
* *Output gain* - this compensates for the overall level reduction caused by the compression process.
* *Attack* - defines the responsiveness of the compressor in compressing audio above the threshold.
* *Release* - defines the responsiveness of the compressor in stopping compressing audio below the threshold.

**Comment by toby-yoyo** [comment]
Closing as above. The [compressor effect](https://github.com/YoYoGames/GameMaker-Bugs/issues/3171) was added in the 2023.8 release.
