### ISSUE TITLE
GameMaker IDE isn't accessible using screen readers

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4230]
Ticket #206349

Feature Type: feat_addition_functionality
Description: User has gotten in touch to let us know that GM8 and GM:S1.x were accessible using a screen reader called [NVDA|https://www.nvaccess.org/download/] but GameMaker is not. 
Benefit: accessibility for the visually impaired.

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3727
