### ISSUE TITLE
Allow network_set_timeout() to affect http_...() requests

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4289]
Ticket #206021

I'm programming a tool for my work to automatically set up one of our products. I know I could go multiple different ways with programming this tool, but I decided to use Game Maker Studio 2 due to the power the IDE holds and the type of tasks being performed. The tool connects to a meshnet wifi, using http post and get functions. Everything is working great, until I wait for the final config. The final config sometimes takes a while to respond, making the connection timeout too quickly, causing the whole system to no longer work.

Is there a way/could there be a new function to change the amount of time before a timeout error is to occur? I'm NOT talking about "network_config_connect_timeout." That doesn't change the timeout time for HTTP requests. I'm talking about changing the timeout time for HTTP requests. 30 seconds is too short for what I want my program to do.

**Comment by YYDan** [comment]
Replaced by https://github.com/YoYoGames/GameMaker-Bugs/issues/5744
