### ISSUE TITLE
[Regular Priority] Ensure that bugfixes are published to both public and beta RSS feeds

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#4292]
Ticket #209125

Feature Type: feat_change_ide
Description: As of 5/9, we noticed that in the beta runtime RSS feed http://gms.yoyogames.com/Zeus-Runtime-NuBeta.rss, the latest update was published on 4/25 for version 2023.400.0.342. In the public RSS feed http://gms.yoyogames.com/Zeus-Runtime.rss, the latest update was published on 5/2 for version 2023.4.0.113, which contains a bug fix for struct_foreach().

We would like this bugfix to also be published to the beta RSS feeds.
Benefit: All of our developers use the beta IDE, and if bug fixes is only published to the public IDE, we all have to switch over to use the public beta IDE. This involves re-authentication and re-configuring the beta IDE preferences. We would like to stay in the beta IDE and not having to switch between beta and public IDEs.

Correction on the benefit:

Benefit: All of our developers use the beta IDE, and if bug fixes is only published to the public IDE, we all have to switch over to use the public IDE. This involves re-authentication and re-configuring the IDE preferences. We would like to stay in the beta IDE and not having to switch between beta and public IDEs.

**Comment by YYDan** [comment]
When sensible to do this, we will (Betas would typically be updated very soon after anyway, as we start the next round, so there is little need to force an update when doing the monthly release). The aim is/has always been that the final Beta is the same content as goes out in the Monthly, but sometimes something urgent crops up.
