### ISSUE TITLE
In-Game: Instance Draw order incorrect on returning to persistant room

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#43]
GM-7773

"... the order in which objects are drawn when exiting and returning to the persistent room.
Assets retain their order, but the order of the instances is broken.

In the attached example, you need to press Space to go to room #2, and then press Space again to return to room #1."

Using this sample and investigating, it was found that when targeting Windows, OperaGX or Android the instance order on returning to the first was incorrect but not when targeting HTML5

Steps:
# Import the attached project and open Room1
# Notice the order for both instances and Assets is the same, cloud then Ninja in front
# Run the project targeting Windows
# Notice the order is the same for both and matches the layout in the room editor
# press the Space bar, the room will be black
# press Space bar again as the room says
# Room1 will be displayed again, but this time only the Assets are in the correct order. The Instance of Ninja will be behind the cloud instance
# Rerun targeting OperaGX and the same issue occurs
# rerun targeting HTML5 and the issue does not occur

**Comment by mgeddesGM** [comment]
verified as of  Beta IDE v2023.1100.0.425  Runtime v2023.1100.0.439
