### ISSUE TITLE
Add support for enabling borderless fullscreen window mode on Windows

### ISSUE THREAD

**Issue by yymrennie** [YoYoGames/GameMaker-Bugs#4303]
### Description

Add a GML function for enabling/disabling the ability to make fullscreen mode (when triggered using window_set_fullscreen() or Alt-Enter) use a borderless fullscreen window rather than use exclusive fullscreen mode. This is primarily to make game switching using game_change() more seamless when running in fullscreen.

### Steps To Reproduce

N/A

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yymrennie** [comment]
Two new GML functions have been added to support this:
- window_enable_borderless_fullscreen(enable) - this enables or disables the use of a fullscreen borderless window when window_set_fullscreen() is called, or the Alt-Enter key combination is used to switch to fullscreen. The default value is false (the old behaviour).
- window_get_borderless_fullscreen() - this returns true if the usage of a borderless window for fullscreen mode has been specified.

**Comment by cameron-home** [comment]
Verified implemented in IDE v2024.200.0.486  Runtime v2024.200.0.502
