### ISSUE TITLE
mouse_x and mouse_y offset when using iOS Zoomed mode

### ISSUE THREAD

**Issue by Jerome-Labbe-RedArtGames** [YoYoGames/GameMaker-Bugs#4304]
### Description

On iOS, if you set your phone to the "Zoomed" mode (Settings > Display & Brightness > Display Zoom View > Zoomed), the mouse_x and mouse_y position will be wrong and will have an offset.
I created a sample project to reproduce this issue.
[iOSZoomedBug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13888864/iOSZoomedBug.zip)

On this screen, you can see the white square drawn on the mouse_x, mouse_y position, while I'm holding my finger on the bottom right of the screen:

![File](https://github.com/YoYoGames/GameMaker-Bugs/assets/82050873/919b7be9-9316-4e80-aaf1-7e5026fa42e3)

### Expected Change

The mouse_x and mouse_y position should work properly in Zoomed mode

### Steps To Reproduce

1. Start GameMaker
2. Set your iPhone to the "Zoomed" mode (Settings > Display & Brightness > Display Zoom View > Zoomed)
3. Launch the project on a real iDevice (not simulator)
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by TaylorDale** [comment]
Any timeline on this one? We are receiving a lot of reviews complaining about this issue

**Comment by jackerley** [comment]
@TaylorDale it is fixed in the latest beta

**Comment by YYDan** [comment]
Note that the issue linked above indicates this has indeed been fixed for a while.

**Comment by TaylorDale** [comment]
> Note that the issue linked above indicates this has indeed been fixed for a while.

Is it fixed in a release build, though? Have been looking through the trackers and appears like no, until the first 2024 release. Not sure how wise it is for us to release a beta gm compiled app to the store?
