### ISSUE TITLE
array_unique_ext behaves inconsistently compared to array_unique

### ISSUE THREAD

**Issue by mstop4** [YoYoGames/GameMaker-Bugs#4307]
### Description

`array_unique_ext` is giving different results compared to `array_unique`, aside from which array each function outputs their results in. 

`array_unique` behaves as expected:
```
original_array = [1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9];
test_array_1 = array_unique(original_array);
test_array_2 = array_unique(original_array, 3, 6);

show_debug_message(test_array_1);
// Expected output: [1, 2, 3, 4, 5, 6, 7, 8, 9]
// Actual output: [1, 2, 3, 4, 5, 6, 7, 8, 9]

show_debug_message(test_array_2);
// Expected output: [4, 5, 6]
// Actual output: [4, 5, 6]
``` 

`array_unique_ext` technically does give the correct results, but doesn't trim the size of the original array to only include the results, leaving a lot of the original values in the array:
```
original_array_1 = [1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9];
original_array_2 = [1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9];
array_unique_ext(original_array_1);
array_unique_ext(original_array_2, 3, 6);

show_debug_message(original_array_1);
// Expected output: [1, 2, 3, 4, 5, 6, 7, 8, 9]
// Actual output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9]

show_debug_message(original_array_2);
// Expected output: [4, 5, 6]
// Actual output: [1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9]
``` 

### Expected Change

`array_unique_ext` should give the same results as `array_unique`.

### Steps To Reproduce

1. Start GameMaker
2. Run attached test project: [contactUs.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13893842/contactUs.zip)
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, macOS, Ubuntu, GX.games, HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
This how the function is intended to work, the function returns the number of valid processed entries. The array is not trimmed and that's the whole point the `array_*_ext` functions are meant to be faster and don't do allocation or deallocations of any data.

**Comment by mstop4** [comment]
OK, thanks for the clarification.
