### ISSUE TITLE
Typos on gamepad_is_connected docs page

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#4308]
### Description

- "NOTE: On some platfroms" misspelled, should be "platforms"
- "Syntax: gamepad_is_connected(numb);" argument "numb" should be "device", per the argument table just below it (and to match other gamepad documentation pages)
- At the bottom of the page: "... for a connected gamepad. the returned value is ..." should be initial capital "The"

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_is_connected.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, thanks for the report
