### ISSUE TITLE
Frequent silent crashes with exit code -1073741819 (memory allocation error).

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#4314]
### Description

For several months, we have been experiencing sporadic silent crashes in Crashlands 2. Sometimes they happen within minutes of playing the game, and sometimes hours. When these occur while we have logging output, we are getting the exit code `-1073741819`, which is a memory allocation error. This memory allocation exit code has appeared in several other tickets, but I am not sure if they are related.

As we have been attempting to track down the source of the crash, we compiled a document with a timeline of the crashes we have experienced and the potentially relevant bits of information. The document can be found here:
https://bscotch.notion.site/GameMaker-Silent-Crash-Analysis-96d7d72d73ff42f7b7d523560c0836e6

I spoke with Russell, who said he believes something about the function `_update_pixels_from_content()` is responsible for the silent crashes.

Since the code in that function is valid GML, and since this is an engine-level problem with memory allocation, he requested that I submit a ticket here with the relevant info. I can't provide a sample project here, but I can give your team access to our repository so you can replicate the issue and do deeper logging.

### Steps To Reproduce

We will deliver replication info and repository access privately. Thanks!

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by BscotchSeth** [comment]
Heyo! Just checking in for next steps. How can we move this forward?

**Comment by jackerley** [comment]
Hi Seth, could you add me on to the repo?

**Comment by BscotchSeth** [comment]
Done! I'll have Shi send an email with info on the testing.

**Comment by YYDan** [comment]
Has been superseded/replaced by the linked issue above, so will close this one now to avoid any confusion/duplication.

**Comment by BscotchSeth** [comment]
@YYDan Request to reopen this issue. The super-frequent silent crashes from https://github.com/YoYoGames/GameMaker-Bugs/issues/4760 have been resolved, but the more sparse ones mentioned in this ticket are still occurring with regularity.

**Comment by BscotchSeth** [comment]
Has this been resolved in a recent runtime?

**Comment by rwkay** [comment]
It should have been

**Comment by jackerley** [comment]
Hi Seth, I believe this should be fixed following the fixes that went in for https://github.com/YoYoGames/GameMaker-Bugs/issues/4760 let us know if you're still seeing any issues, I will close for now.

Thanks,
Fritz

**Comment by BscotchSeth** [comment]
So far we haven't seen any silent crashes since updating. Will comment if they appear!

**Comment by BscotchSeth** [comment]
We just got a silent crash this morning. They _seem_ to be less frequent now, as this is the first one we've had since updating runtimes a few days ago. Same error code, same "nearly impossible to replicate" situation.
