### ISSUE TITLE
Make `event_` functions actually return values

### ISSUE THREAD

**Issue by BackYard321** [YoYoGames/GameMaker-Bugs#4315]
### Is your feature request related to a problem?

At the moment, using `return` in an object event is the equivalent of `exit`, ending the event prematurely. However, it can't be used to actually return a value - calling events using functions like `event_user(0)`, `event_inherited()`, or `event_perform_object()` will always return `undefined`, even if the event being called contains `return true` or something similar.

### Describe the solution you'd like

Having events actually return a value when called would really expand the utility of these functions, particularly for user events.

**Comment by stuckie** [comment]
This is not something we are planning.
It is not an event at this point, so there is nothing to return.

**Comment by BackYard321** [comment]
> This is not something we are planning. It is not an event at this point, so there is nothing to return.

I don't understand what you mean by the second part - are you saying that it would no longer be an event if this were added?

**Comment by rwkay** [comment]
We are saying we have no plans to allow events to return anything... they are not events at that point (events are asynchronous and do not return anything).

**Comment by BackYard321** [comment]
I got that you're not planning on adding them, I was just asking for clarification because evidently I don't understand the particulars. But also, in retrospect, I imagine inheriting events that `return` values could end up being a total nightmare.
