### ISSUE TITLE
Struct key as function name causes compiler error

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#4316]
### Description
In previous versions, you could setup a struct like
```gml
global.struct = {
	"myFunc": undefined
}
```
While also having a function called `myFunc`. As of IDE v2024.200.0.461 Beta Runtime v2024.200.0.477, it seems throw an error with `Cannot set a constant ("myFunc") to a value`.

### Steps To Reproduce
1. Load up project.
2. Compile project
3. See Compiler Errors

[7eab6ed4-fb87-4c0d-9092-099ce26d14fb](https://api.gamemaker.io/api/github/downloads/7eab6ed4-fb87-4c0d-9092-099ce26d14fb)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.468  Runtime v2024.200.0.484
