### ISSUE TITLE
Nullish Operators Missing From Manual's Alphabetized Index Tab

### ISSUE THREAD

**Issue by ParodyKnaveBob** [YoYoGames/GameMaker-Bugs#4318]
### Description
Neither `??` nor `??=` appears in the index.

### Steps To Reproduce
1. Open GM Manual.
2. Select second tab for the index.
3. Type `?`.
4. Observe issue.

[67ca64fe-83eb-4702-ae49-fdb79153e69e](https://api.gamemaker.io/api/github/downloads/67ca64fe-83eb-4702-ae49-fdb79153e69e)

**Comment by gurpreetsinghmatharoo** [comment]
Fixied
