### ISSUE TITLE
the return of typeof() for undefined struct value changed from ptr to undefined

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4319]
### Description
For a struct with undefined value in it, the return of  typeof() for that value changed between runtime 2023.11.1.160 and 2024.200.0.477.

### Steps To Reproduce
1. Run the sample in 2023.11.1.160 windows export and see the return to be "ptr"
2. Repeat in  2024.200.0.477 and see the return to be "undefined"

[ae9c7d30-c0e1-48d9-8957-4bd2699cde79](https://api.gamemaker.io/api/github/downloads/ae9c7d30-c0e1-48d9-8957-4bd2699cde79)

**Comment by rwkay** [comment]
This is not a bug, we have changed how `undefined` is handled in JSON if you require the old behaviour then you can use the filter functions to implement the old behaviour.

```
var _i_want_pointer_nulls = json_parse(_content, function(_key, _value) {
    return _value ?? pointer_null;
});
```

**Comment by shichen85** [comment]
I was wondering if this is intended. Thanks for the confirmation and recommendation.
If you haven't already planned it, please consider mentioning this in release notes so users are aware of the change and can adjust accordingly.

**Comment by rwkay** [comment]
it is mentioned in the detail on the bugs that are linked on the release notes... but take your point that it is a fundamental change and should probably be called out.

**Comment by gnysek** [comment]
@shichen85 it's already there:

https://github.com/YoYoGames/GameMaker-Bugs/milestone/7

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/6c6e4aec-dc3f-4651-bbca-047f0a38a645)

**Comment by mgeddesGM** [comment]
closing as not a bug as per comments above
