### ISSUE TITLE
Code Editor: Reusing method names in multiple objects and pressing F1 opens the first object, not the correct one for the selected line of code

### ISSUE THREAD

**Issue by DaveInDev** [YoYoGames/GameMaker-Bugs#4322]
### Description

You have 2 objects, and each object has a method with the same name defined in the Create event (for example function init() ).
If in a script you have calls to these methods : 
Object1.init()
Object2.init()

when you press F1 on any of the init name, the IDE always jump to Object1.init() definition, never to Object2.init().

You'll find a simple project enclosed, with this example.
[TestInit.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13908697/TestInit.zip)

### Expected Change

F1 jumping to the correct function.

### Steps To Reproduce

1. Start GameMaker
2. Open the enclosed project
3. go into  Script1
4. double click on init in the Object2 call.
5. the IDE jumps in Object1.init(), not Obejct2.init()

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Note this works fine in Code Editor 2

**Comment by yyalansavage** [comment]
Fixed this particular case for Code Editor 1

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.565  Runtime v2024.600.0.585
