### ISSUE TITLE
Feather Bug (potentially dangerous declaration)

### ISSUE THREAD

**Issue by XorDev** [YoYoGames/GameMaker-Bugs#4324]
### Description
I'm getting a GM2018 warning for a potentially dangerous variable declaration, when setting a local var inside a with statement

### Steps To Reproduce
Paste this code in any event to see the warning:

with(id)
{
	var _x;
	_x = 0;
}

[0779ef75-631d-4091-8caf-48c4f93de2ca](https://api.gamemaker.io/api/github/downloads/0779ef75-631d-4091-8caf-48c4f93de2ca)

**Comment by stuckie** [comment]
Duplicate of #2305
