### ISSUE TITLE
[Pi 5] Booting up GameMaker with HDMI plugged in breaks IDE

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#4327]
### Description

For some reason, booting up GameMaker with HDMI plugged into the Pi 5, causes the whole IDE to break in all matters. Including most file menu options being broken. It's technically usable via keyboard shortcuts, but it is otherwise impossible to see or work on anything. If I have no HDMI plugged in and use VNC instead, the IDE works perfectly fine. Even if I plug in the HDMI afterwards, so it seems to only be affecting it on booting up GameMaker. 

**Note:** HDMI output resolution is set to 1920x1080.

Included  is a Contact Us package, which I've managed to create from a bunch of keyboard navigation.

![20240112_16h27m43s_grim](https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/2c759224-80e4-4850-b061-bd6507bb1b8c)

[Pi 5.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13914969/Pi.5.zip)

### Steps To Reproduce

1. Start GameMaker on Raspberry Pi 5 with HDMI cable plugged in
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This is a DPI issue. For some reason we are detecting a scale of 0.

As a workaround for anyone else while we investigate further, you can create a ~/.local/share/GameMakerStudio2-Beta/dpi_override.json with:
`[{"Key":"is_enabled","Value":true},{"Key":"value","Value":92}]`
And it should behave from there.

**Comment by YYDan** [comment]
Unsupported OS/device - ultimately this is waiting on https://github.com/YoYoGames/GameMaker-Bugs/issues/3196 so closing.
