### ISSUE TITLE
SSL connection cant be made on Game Maker start

### ISSUE THREAD

**Issue by Arturlearningphp** [YoYoGames/GameMaker-Bugs#4329]
### Description

I start Game Maker and I get prompted with something like "SSL connection cannot be made". After logging in 3 or 4 times into my Opera account that is connected to Yoyo Games it usually starts to work again and I can see my two projects again.

Version is 2023.11.1.129
[ssl-issue-contact-us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13917184/ssl-issue-contact-us.zip)

### Expected Change

The SSL connection can immediately made after starting Game Maker

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This looks like the SSO server was having issues at this point.
Is this a recurring issue, or more of a once off?
In amongst the logs there's a 400 Bad Request, and various Connection Closed by Host errors.. so I'm hoping it was just a hiccup on our end and it's resolved itself.
I'll keep the ticket open just now, so please let us know if it has resolved itself or not!

**Comment by Arturlearningphp** [comment]
hello

it hasnt been resolved,it just happens less often. i dont know what else
information to send you.

have a good day

Am Di., 23. Jan. 2024 um 16:01 Uhr schrieb Steven Campbell <
***@***.***>:
