### ISSUE TITLE
[Android] android:allowBackup Bug

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#4333]
### Description
There is something wrong with android:allowBackup attribute. (Game Options: Android -> Permissions -> allowBackup Checkbox)

If I use YYC and do not set this checkbox to true, then my game still uses allowBackup.
I think you guys forgot to set it explicit to false for YYC and the default value of allowBackup is true. (Read here: https://developer.android.com/guide/topics/manifest/application-element#allowbackup)

As workaround I can set -->android:allowBackup="false"<-- myself in the "injection to android application tag" field above: , but this works only for YYC, for VM I get an error, that this attribute is still set. So it seems like there is something missing for YYC

Please check this checkbox for VM and for YYC, because there is some error. I cant tell u exactly what is wrong, but there is something wrong and VM & YYC do not have the same behavior. I am also not sure if VM works correctly, I did not test VM as much as YYC

### Steps To Reproduce
allowBackup="false" --> After reinstalling an app there must NOT be any userdata from when the app was installed last time. [for VM and YYC]
allowBackup="true" --> After reinstalling an app there MUST be the userdata from when the app was installed last time. [for VM and YYC]

[90a93e5f-7d08-4cd5-a755-784163053d2e](https://api.gamemaker.io/api/github/downloads/90a93e5f-7d08-4cd5-a755-784163053d2e)

**Comment by Glim888** [comment]
Hi, it seems like the allowBackup flag is t the wrong position in the manifest.

https://cdn.discordapp.com/attachments/1045313460734545963/1284522449748234354/image.png?ex=66ee3081&is=66ecdf01&hm=b20c44851e8a30c33ada48d0901c6b41c8c281fd924acd7cbc7757b6597c4511&

**Comment by Glim888** [comment]
@stuckie Its seems like this is not fixed. Please reopen.

Thanks

**Comment by stuckie** [comment]
Unfortunately, that discord link no longer works; can we get confirmation on what is wrong so we can have a look at it?

Thanks.

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.647  Runtime v2024.1100.0.667.
