### ISSUE TITLE
Small typo in GM Manual for the gp_select text.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4340]
### Description
Link:
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FGame_Input%2FGamePad_Input%2FGamepad_Input.htm

Says "DS4" instead of "PS4" in the text next to the gp_select constant on the Gamepad Input page.

### Steps To Reproduce
N/A

[c633bbd0-34b3-4c02-a47d-671ead4e87e7](https://api.gamemaker.io/api/github/downloads/c633bbd0-34b3-4c02-a47d-671ead4e87e7)

**Comment by rwkay** [comment]
DS4 is the DualShock 4 which is the name of the PS4 gamepad... it is not a bug

**Comment by PrismaticRealms** [comment]
Ah!  Don’t think I’ve ever seen it abbreviated like that before! On another part of the page it’s referenced as a PS4 controller so I thought somebody made a typo! My apologies.

**Comment by gurpreetsinghmatharoo** [comment]
Still good to have it changed to PS4 anyway, to not cause confusion. Will be changed.

**Comment by gurpreetsinghmatharoo** [comment]
Doooone
