### ISSUE TITLE
Typos in How To Use System Metrics In Live Wallpapers help centre article

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#4341]
### Description

Misspellings:
- Under the heading "Updates to the Handler Object", in the bullet list: "Changing State" is written but should be "Charging State"
- Under the heading "Audio Visualiser", step 12: "id of the individual var" should be "id of the individual bar"

General language correctness:
- Under the heading "Audio Visualiser", step 12:
  - "the bars position, width and height" should be "the bar's position, width and height"
  - "the wallpapers width" should be "the wallpaper's width"
  - "the wallpapers position" should be "the wallpaper's position"
- Under the heading "Custom Water Visualiser": "The vertex’s are drawn" should be "The vertices are drawn"
  - Also, the associated diagram contains black lines with transparent background; the page's background is dark gray, making the diagram hard to see.  I'd suggest updating the diagram with a solid background.
- Under the heading "Particle Intensity":
  - "in the handler"s Destroy event" should be "in the handler's Destroy event"
  - "to the GPUs temperature" should be "to the GPU's temperature"

For these, you can use find/replace all (no false results are present):
- One case of "wont" should be "won't"
- One case of "isnt" should be "isn't"
- Two cases of "hasnt" should be "hasn't"
- Two cases of "dont" should be "don't"

I did not perform an exhaustive proofreading; these may not be all the revisions warranted.

P.S. This isn't part of the manual, but the GitHub issue template does not have a more relevant category than that.  The older [Contact Us](https://contact.gamemaker.io/en/contact-us) form has "Report a Website issue" in its drop-down; for future reference, is it preferred that issues like this one go though the Contact Us form rather than GitHub?

### Manual Link

https://help.gamemaker.io/hc/en-us/articles/15176025039901-How-To-Use-System-Metrics-In-Live-Wallpapers

**Comment by gurpreetsinghmatharoo** [comment]
Thanks, all issues have been fixed.
