### ISSUE TITLE
IDE runs slow

### ISSUE THREAD

**Issue by DogKiss** [YoYoGames/GameMaker-Bugs#4349]
### Description

IDE stutters, stalls, lags, after a few hours of use. 

Not project-related. I have 5000+ hours in GMS, and this only started happening since the last update. It's rather frustrating.

### Expected Change

The IDE running as smooth as it used to.

### Steps To Reproduce

1. Start GameMaker
2. Develop a game for a couple of hours in a medium-sized project.
3. Get frustrated
[GMSContactUs.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13929446/GMSContactUs.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Retrific** [comment]
Maybe related: https://github.com/YoYoGames/GameMaker-Bugs/issues/2528

**Comment by YYDan** [comment]
Yeah, as mentioned above, this issue is being tracked in https://github.com/YoYoGames/GameMaker-Bugs/issues/2528 - we'll of course check your logs here as part of investigating that one, but I will go ahead and tidy this one up just now so we can focus the conversation on that one issue.

Thanks!
