### ISSUE TITLE
Incorrect key combo shown on Bookmarks page in manual.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4351]
### Description
On the bookmarks page of the manual, it says the keyboard shortcut to create a bookmark on macOS is Ctrl + Command + NumberKey.  This is incorrect.  The correct key combo here is Command + Shift + NumberKey. Correction needed on this page.

### Steps To Reproduce
N/A

[f526c261-f599-4da3-9a59-0fff92a9fc0a](https://api.gamemaker.io/api/github/downloads/f526c261-f599-4da3-9a59-0fff92a9fc0a)

**Comment by stuckie** [comment]
Just to double check that is what is supposed to be set before updating the manual.

**Comment by gurpreetsinghmatharoo** [comment]
Done
