### ISSUE TITLE
Lag when using the code editor in last beta

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#4357]
### Description
Like the title says. After 20-40 min of use of game maker an ONLY using the code editor the IDE is gonna to slow down.

You can see this problem on the proyect atached on script dark_database.

### Steps To Reproduce
1) Just use the IDE and program in the code editor.

[a53306b7-9945-4a77-b79c-ae7f1967136e](https://api.gamemaker.io/api/github/downloads/a53306b7-9945-4a77-b79c-ae7f1967136e)

**Comment by YYDan** [comment]
This issue is being tracked in https://github.com/YoYoGames/GameMaker-Bugs/issues/2528 - we'll of course check your logs here as part of investigating that one, but I will go ahead and tidy this one up just now so we can focus the conversation on that one issue.

Thanks!
