### ISSUE TITLE
Manual Content: "Code Snippets" page does not contain the paths for the Ubuntu IDE in Betas

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4364]
### Description

The "Code Snippets" page does not contain the paths for the Ubuntu IDE in Betas alongside the ones we have for Windows and Mac IDEs. This affects two places on that page:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/02859f5c-eb4f-455d-ad42-841037747693)
and
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/090d4ec5-163b-413e-baa1-0db4793349fb)

### Expected Change

The Ubuntu Paths are added as a third bullet point in each of the two sections shown above, These are:

`./var/opt/GameMakerStudio2/ OR some newer Ubuntu versions put it into ~/.local/share/GameMakerStudio2`
and
`/opt/GameMaker-Beta/x86_64/TextEditor/snippets.txt`

### Manual Link

https://manual.gamemaker.io/beta/en/The_Asset_Editors/Code_Editor_Properties/Code_Snippets.htm

**Comment by gurpreetsinghmatharoo** [comment]
don
