### ISSUE TITLE
Game Options: GX.games status stuck on "Fetching profile info" or uses incorrect stale data if you sign out inside GM

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4366]
### Description
Within Game Options -> GX.games the status label can get stuck on "Fetching profile info" if you sign out inside GM while that window is open, and there is no instruction on how to resolve this,

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/ae2ae20a-bd1b-4674-b21e-13e82bf93780)

This wording implies if you just wait long enough, the situation might resolve itself. (It won't.) Clicking the actual refresh button also does nothing while you are in this state.

However, if you close and reopen the window at this time, then Game Options acts as if all is well:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/d3ad4650-34de-454f-a1ea-67e82042ce8f)

_Affects 2023.11.1 as well as 2024.200 - have not checked older releases._

### Expected Change

Exactly the same as what happens if you open the project when not signed-in - different text and the refresh button is disabled:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/6ca1aee2-cba3-4260-b988-7fedece3d8a5)

Also, that we do not (falsely?) claim to have found your old details if the window is reopened.

### Steps To Reproduce
1. Start GM as a signed-in user
2. Create/open any project
3. Open Game Options -> GX.games
4. Sign-out in the GM account panel
5. Observe the label text at the top of the main panel detects your sign-out, but then immediately shows this incorrect info
6. Close Game Options -> GX.games
7. Open Game Options -> GX.games again
8. Observe the label text at the top of the main panel is now back to saying your original user account is logged-in and all is well (even though you're still logged-out inside GM)

[e961e9b2-32ee-4497-906a-5d970f4c2a6e](https://api.gamemaker.io/api/github/downloads/e961e9b2-32ee-4497-906a-5d970f4c2a6e)

**Comment by YYDan** [comment]
Edited the report.

Realised that there is already a different message and we do disable the button if you are a guest, so my issue is only when signing-out in that current project session.

Also, realised that closing and reopening the game options at this time implies we found your old account info and will use that, despite you still being a guest.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.562  Runtime v2024.600.0.580, thanks.
