### ISSUE TITLE
Shortcut shift+delete doesnt work in IDE Script editor

### ISSUE THREAD

**Issue by millansoft** [YoYoGames/GameMaker-Bugs#4367]
### Description

Before lastest update, it was able in the script editor, to press shift+delete and it deleted the full line, now its gone.

### Steps To Reproduce

1. Start GameMaker
2. Go to the script editor
3. Press shift+delete in some line
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Assume you closed this yourself as you realised it's a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/2593
