### ISSUE TITLE
[YYC] Null coalescence allows you to change the value of `undefined`

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#4369]
### Description

```gml
function this_poisons_undefined(v) {
	v ??= 1;
	
	return v;
}
this_poisons_undefined();

show_debug_message(string(undefined)); // this prints "1"
```

This only happens with `??=` operators on a parameter -- I do not believe this is a runtime error (per se), but rather a compiler error -- in the generated CPP for `this_poisons_undefined`, we do NOT get:

```cpp
int argSpace = (1 > _count) ? 1 : _count;
YYLocalArgs yylocal_args( _count, 1, _args );
_count = yylocal_args.m_count;
_args = yylocal_args.m_args;
```
I'll call this block above the `yy_local_args` code.

The `yy_local_args` code IS made by this function:

```gml
function this_is_fine(v) {
	// it's also fine if you do this as ternary like `v = v == undefined ? 2 : v;`
	if v == undefined {
		v = 2;
	} else {
		v = v;
	}
}
```

However, if `v ??= foo` is present (seemingly regardless of what else is in the function) the compiler stops emitting the `yy_local_args` function.

As to why the runtime's `YY_GET_ARG` returns a pointer to the global undefined right hand value, rather than just throw, I cannot say.

### Steps To Reproduce

I have included a link to a repo with the issue on display. Run that project in the YYC and press F1 to see undefined's value change. Press F2 to test the other function.

Repository here: https://github.com/NPC-Studio/yyc-undefined-parameter-repro

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment]
Of all the bug reports I've ever seen, this sure is one of them.

**Comment by attic-stuff** [comment]
this one is fun. looks like its tied up in being a method for some reason. like if you make a regular ass global function its fine, but once it becomes an instance method it does the poisoning.

![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/a3ba5c40-4239-4163-824b-7458012b5347)

![littleguy](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/ec446987-6e7e-4369-a4c8-60024ec74b63)

**Comment by rwkay** [comment]
Unable to reproduce with current Beta HEAD - I have changed how some of this is handled within 2024.2 it looks like this has already been fixed... NOTE: I checked with 2023.11 and it is definitely happening there...

**Comment by scott-dunbar** [comment]
Im also unable to repro in  IDE v2024.200.0.478  Runtime v2024.200.0.493 so closing as fixed.
