### ISSUE TITLE
Switch game won't run if your temp directory has spaces in its path

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4377]
### Description

as title

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Switch

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.489  Runtime v2024.200.0.505, thanks.
