### ISSUE TITLE
[YYC] Null Coaelesence on Struct Fields Does Not Work

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#4378]
### Description

```
var foo = {
    a: undefined,
};

foo.a ??= "a";

show_debug_message("foo.a = " + string(foo.a)); // prints `foo.a = undefined`
```

Doing the above on a local variable directly (ie not on a struct field) does not do anything. Additionally, it works as you'd expect on the YYC

### Steps To Reproduce

1. Start GameMaker
2. Run the above code
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Unable to reproduce on HEAD of current `2024.2.0-main` branch
