### ISSUE TITLE
`path_add()` doesn't return a handle, or set `path_index` when passed into `path_start()`

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4381]
### Description

`path_add()` is supposed to return a path asset handle, however it still returns a number. As well, when that returned index is passed into `path_start()`, it doesn't change the calling instance's `path_index` - rather, that stays as `ref path -1`.

### Steps To Reproduce

1. Start GameMaker
2. Create an object with a create event in the starting room
3. Write the following code:
```gml
var _path = path_add() // returns index 0
path_start(_path, 0, path_action_stop, false)
show_message($"path_index: {path_index}")
show_message($"_path: {_path}")
```
4. See the issue - `_path` will be the correct index but expressed as a number (`0`), and `path_index` will be `ref path -1`

[paths.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13954625/paths.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
[path_add.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14329394/path_add.zip)

The enclosed project still fails when the fix is in as it doesn't add a valid path, you have to add some points to it in order for it to be settable as path_index. Modified sample enclosed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.521  Runtime v2024.400.0.542
