### ISSUE TITLE
Sprite Editor - "Apply to Origin" checkbox doesn't work when enlarging canvas

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#4384]
### Description
When using the "Resize all frames" tool, enlarging a canvas with the "Resize Canvas" option doesn't apply the change to the origin, regarless of the "Apply to Origin" checkbox being ticked. It does seem, however that using this tool to shrink a canvas, does apply the change to the origin correctly.

### Steps To Reproduce
- Create a sprite of some size with a single pixel somewhere near the middle
- move the origin of that sprite to the pixel
- use "Image > Resize all frames >  Resize Canvas" to enlarge the canvas by two pixels in each dimension.
- ensure the center box is selected for resize direction
- ensure "Apply to Origin" is checked and click "Apply"
- note the origin of the sprite is now off of that pixel.
- replace the origin on the pixel
- use the same steps shrink the canvas by two pixels in each direction
- note the origin did stay on the correct pixel.

[51f6e7f1-7294-430e-924a-6d7bec3afa2c](https://api.gamemaker.io/api/github/downloads/51f6e7f1-7294-430e-924a-6d7bec3afa2c)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.529  Runtime v2024.400.0.550, thanks.
