### ISSUE TITLE
Textures that are resized to fit a texture page size end up on a texture page of a smaller size

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#4386]
### Description

With the texture page size to 256x256, a sprite of size 512x512 is resized and ends up on a texture page of 128x128, while it could go on a page of size 256x256.

This at least happens on the Windows and GX.games target and occurs in version: Beta IDE v2024.200.0.461 Beta Runtime v2024.200.0.477. The preview image dimensions are also 128x128 when you preview them from within the IDE.

Additionally, the Debug Overlay's new Texture view shows the same values for width/height and actual width/actual height.

Sample project: [test_texture_actual_width_height.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13962899/test_texture_actual_width_height.zip)

### Expected Change

The sprite is placed on a texture page of the maximum defined size and actual width and height correctly show the image's original dimensions.

### Steps To Reproduce

1. Open the sample project
2. Run the game and check the texture dimensions in the Debug Overlay, or use the texture preview button in the Game Options
4. The texture dimensions are 128x128, while 256x256 is set as the texture page size

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2.... well I say fixed - I have removed the `actual  width` and `actual height` from the Texture Viewer as they are internal and mean nothing to the user - we do not actually use those values internally for textures any more and they are legacy from early implementations.

**Comment by alicemoretti** [comment]
On IDE v2024.200.0.478  Runtime v2024.200.0.493, the actual_width and actual_height do not appear in the texture view in the in-game  debug anymore. 

However, when generation and opening the texture pages preview via Game Options those are still the wrong size (128x128 instead of 256x256). Is this intended?

**Comment by rwkay** [comment]
Fixed in 2024.2 - rescaling was not working when the width and height were an exact power of 2 (it would also take it to a level one lower than it could have).

**Comment by YYBartT** [comment]
No further changes to the manual needed for this.

**Comment by YYDan** [comment]
Preview files and in-game values are all correctly 256 now for both sprites in IDE v2024.2.0.132  Runtime v2024.2.0.163

E.g.:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/6f49d4ab-8217-4706-971a-ce51d80959b2)
and 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/6abaa353-874f-44e8-9b49-436c0ed81a93)
(although, Windows won't keep the tooltip there for my screenshot).

Verifying.
