### ISSUE TITLE
If options.ini is deleted or not generated game will crash

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4388]
### Description

Run a game on Windows, delete the options.ini and attempt to re-run the game. Witness a crash. (This will happen on other platforms but is easier to reproduce on Windows) This matches a crash callstack reported by ButterScotch

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.480  Runtime v2024.200.0.495
