### ISSUE TITLE
On Mac IDE, the "Open Search In Script Replace" hotkey is hard-coded and doesn't turn Find into Replace

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#4389]
### Description

This is a follow-up to #899 . Upon further testing of the new Cmd+Shift+H hotkey for bringing up the Replace pane on the Mac IDE, I noticed 2 issues:

1. It is hard-coded to Cmd+Shift+H. If it is changed to anything else in Redefine Keys (e.g. Cmd+R), the new hotkey will only bring up Find, and the Replace field would still be hidden.
2. The hotkey doesn't turn the Find pane into the Replace pane, which is a behaviour that exists in the Windows IDE.

### Expected Change

The hotkey should still work even if it is remapped to another combination. It should also turn the Find pane into the Replace pane if already opened.

### Steps To Reproduce

Contact-us package: 
[MacIDEHardcodedReplace.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13967475/MacIDEHardcodedReplace.zip)

Reproduction (hard-coded hotkey):
- Open the project in Mac IDE
- Go to Preferences > Redefine Keys and set "Open Search In Script Replace" 
to Cmd+R
- Come back here and press Cmd+R. The Replace pane should appear, but only the
Find pane appears.
- Go to Preferences > Redefine Keys and set "Open Search In Script Replace" 
back to Cmd+Shift+H
- Come back here and press Cmd+Shift+H. Only then does the Replace pane appear.

Reproduction (hotkey doesn't turn Find into Replace)
- Open the project in Mac IDE
- Go to Preferences > Redefine Keys and set "Open Search In Script Replace" 
to Cmd+Shift+H
- Come back here and press Cmd+F, then Cmd+Shift+H. The Find pane should change
to Replace, but it is still Find.
- Close the Find pane and press Cmd+Shift+H. Only then does the Replace pane 
appear.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), 2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Made the following changes:
- `Open Search In Script Replace` now works correctly when remapped to contain something other than the `H` key.
- Pressing the `Open Search In Script Replace` hotkey with the `Find` window open will now expand the `Replace` pane, if it was not already open.
- Added the `Open Search In Script Replace` hotkey as a hover caption to the `Replace Next` button, which uses the same binding.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.478  Runtime v2024.200.0.493
