### ISSUE TITLE
No compile error is generated when using a function name as an array index, but error will be thrown at runtime

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4401]
### Description

Error is different in YYC and VM, in VM you get Variable Object1.enemyState_2_alert(100004, -2147483648) not set before reading it. In YYC you get 

I32 argument is unset############################################################################################
gml_Object_Object1_Create_0 (line 3)
[arrayfunctiontest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13978267/arrayfunctiontest.zip)

### Expected Change

Compile error to be thrown

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2 - unable to add a compile error for this as its not really an error (though I cannot think why you would want to do this, user functions all start at 100000 and so you get a very very big array with nothing in it for the most part) it is a Code Smell though so we may add a Feather check for it.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.471  Runtime v2024.200.0.487. As per Russell's comment, there is no compile error returned and the game just builds as expected.
