### ISSUE TITLE
Should the "Texture Group" or "Audio Group" field of an asset be dependant on a config?

### ISSUE THREAD

**Issue by vitawrap** [YoYoGames/GameMaker-Bugs#4402]
### Is your feature request related to a problem?

It's very annoying having to cycle between configs to check if each of my assets correctly belongs to its group, especially when those groups have per-config settings already which is redundant.

### Describe the solution you'd like

Assets groups should be invariable between configs (or an IDE option to invariably store a group field in Default).
Furthermore it would be nice to have an indicator on things that are config dependent.

### Describe alternatives you've considered

Going on each config and checking if my assets are correctly assigned to their respective texture/audio groups

**Comment by dt-universe** [comment]
Agree, I removed config with specific tool for development, because of assigning Texture Group for sprites.

**Comment by stuckie** [comment]
The configs are hierarchical so you can set your options in a parent config and it'll bubble down.
If this is not working, then that is a bug and if so, please provide a project so we can check what is going on.
