### ISSUE TITLE
Variable description for layer_force_draw_depth() missing end parenthesis

### ISSUE THREAD

**Issue by Arena78** [YoYoGames/GameMaker-Bugs#4404]
### Description

In the manuals description for layer_force_draw_depth() the "force" variables description is: 
"Whether to enable (set to true or disable (set to false) Z depth forcing", when it should be: 
"Whether to enable (set to true) or disable (set to false) Z depth forcing".

I know its a super small issue and (admittedly) kind of petty, but its still wrong.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/General_Layer_Functions/layer_force_draw_depth.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed :+1:
