### ISSUE TITLE
Forever stuck on "Building" when try to run a game.

### ISSUE THREAD

**Issue by rafaellima83** [YoYoGames/GameMaker-Bugs#4406]
### Description

When I try to run a project, it gets stuck on "Building" forever. It started happening out of nowhere.

This is happening with any project. It started to happen after I updated Gamemaker, though I managed to run a game twice before this actually started happening.

I've tried turning off Windows Anti-Virus, running it as administrator, restarting the computer, uninstalling and installing GameMaker again, changing Runtime version to an older one (tried a few different ones), logoff and login again, Delete Temp Folder, Asset Cache" and Delete IDE Cache nothing worked.

Output is showing nothing. If I try to stop the building process, Output shows " -- STOPPING --", but it doesn't stop it. I have to close the application. I can't clean any of the projects (when I click on Clean, nothing happens) and Gamemaker just "freezes".

I "show compiler commands in compile output" and "show verbose compiler output" turned on, and still the Output window is showing nothing while building it.

[I_am_forced_to_create_this_even_though_it_makes_no_sense_its_just_a_room_and_four_sprites.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13981672/I_am_forced_to_create_this_even_though_it_makes_no_sense_its_just_a_room_and_four_sprites.zip)

EDIT: I just installed Gamemaker LTS  and it worked. No problems with the LTS version This is a clue.

EDIT 2: It's on the Runtime. So now I think it's indeed a bug. I don't know if I was doing something wrong before, but after uninstall - reinstalling many times, I accidentally installed 2023.11.0.157, and it suddenly worked. Changed it to 2023.11.1.129, it didn't. 

### Steps To Reproduce

1. Start GameMaker
2. Run Project

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rafaellima83** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/146400458/dd3fdf99-b434-4505-9d21-09d180ce562d)
![image1](https://github.com/YoYoGames/GameMaker-Bugs/assets/146400458/702d7c88-1a46-4b19-9975-a8cf45829ad9)

I've attached 2 images so you can see what's happening. Again, it's happening with any project.

**Comment by stuckie** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.
