### ISSUE TITLE
In-Game: [IOS][PS4/5] http_request() can cause a freeze when the async event fires because data is returned

### ISSUE THREAD

**Issue by jbonesy** [YoYoGames/GameMaker-Bugs#4407]
### Description

In the latest runtime, HTTP Requests appear to be broken on both iOS & PS4/5 (we found this first on PS4/5). Sending a HTTP request causes the game to freeze up once data is received from the server, regardless of what handling is done within the async event. 

This did not occur in past runtimes and only surfaced recently - this has a 100% reproduction rate so long as a HTTP request is submitted, seems to happen regardless of data.

This does not happen on any other platforms besides iOS, PS4, and PS5 (native builds for PS4 and PS5 respectively).

This was mentioned in Slack and the team is already added to the Github for this title. 

### Steps To Reproduce

1. Start GameMaker
2. Run for PS5, PS4, or iOS (VM is fine, but also occurs on YYC)
3. Load into main menu.
4. Select "Rhapsodies" from the main menu.
5. Wait a few seconds
6. Observe the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS, PlayStation 4, PlayStation 5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jbonesy** [comment]
Appears to be fixed in latest beta 2024.200.0.487 for PS4/5 - checking iOS. May still be worthwhile to look into regardless unless this was actively fixed between the latest runtime and this beta, as it could be a vestigial issue.

**Comment by jbonesy** [comment]
Confirmed fixed on iOS now in latest beta

**Comment by npapalia** [comment]
Just to reiterate, when building off of the newest beta LOCALLY the issue does NOT happen - but when archiving and uploading the app to testflight through Xcode, the issue happens across multiple tester devices. The newest beta has not fixed this issue just to clarify

**Comment by rwkay** [comment]
would you be able to share an example of the json that is being passed back that it is failing with?

**Comment by jbonesy** [comment]
[example.json](https://github.com/YoYoGames/GameMaker-Bugs/files/14085573/example.json)

Attached is an example of the JSON data. Obviously when coming in through an async request however this would be wrapped with the HTTP header/wrapper, so this would be inside of the "Data" entry in the DS_MAP. In the project your team has access to, enabling the DEBUG_ONLINE macro will print out all debug info from Playfab when connecting online (including all received JSON if applicable).

**Comment by jackerley** [comment]
Hi @jbonesy could you try using the latest beta release? We have put a fix for a crash in that I believe may well have been the root cause of the issue that you were seeing? Any runtime after 2024.200.0.515 will have the fix in.
