### ISSUE TITLE
Shorten Constant Naming for Time Source Constants

### ISSUE THREAD

**Issue by XanthorXIII** [YoYoGames/GameMaker-Bugs#4409]
### Is your feature request related to a problem?

This is not related to a current problem

### Describe the solution you'd like

When Time Sources were introduced there were several new constants that were introduced to use for these as well. It is appreciated that there was some thought put into naming the constants to be self explanatory, however the names seem to be a little long. I'm proposing the following changes to the names to shorten them by at least 8 characters to conserve on horizontal space to help coders write short and concise code. We like having all the room we can to make our code look elegant ;)

Original					|	Replacement
time_source_game			|	ts_game
time_source_global		|	ts_global
time_source_expire_nearest	|	ts_expire_nearest
time_source_expire_after	|	ts_expire_after
time_source_state_initial	|	ts_state_initial
time_source_state_active	|	ts_state_active
time_source_state_paused	|	ts_state_paused
time_source_state_stopped	|	ts_state_stopped
time_source_units_seconds	|	ts_seconds
time_source_units_frames	| 	ts_frames
*If I missed one my apologies.

I understand that I can create my own to use in place of these however some coders may not realize they can do this. I would just like to make this available for everyone to use.

**Comment by stuckie** [comment]
This is not something we are planning on doing, as it would affect projects already using these function.
