### ISSUE TITLE
Additional Code Injection tags for Android

### ISSUE THREAD

**Issue by silengames** [YoYoGames/GameMaker-Bugs#4414]
### Is your feature request related to a problem?

I would like to request additional Code Injection tags for Android. It required for extensions using plugins.

${YYAndroidTopLevelGradlePlugins}
In RootFiles/build.gradle
Between "buildscript" and "allprojects" tags

${YYAndroidGradlePlugins}
In ProjectFiles/build.gradle
In the first string before "apply plugin" tag

Example of changed files are attached.

### Describe the solution you'd like

[InjectionTags.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13987769/InjectionTags.zip)

**Comment by DiasFranciscoA** [comment]
@silengames Hello, according to previous feature request we would like to inform that plugins are already available to the developers using already existing tags:

## **[TOP LEVEL GRADLE]**

According to the Android documentation plugins should be added as dependencies in the buildscript tag:

```
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'

        classpath 'com.example.pluginA:version'
        classpath 'com.example.pluginB:version'
    }
}
```

This is already possible if you use the `<YYAndroidTopLevelGradleBuildscriptDependencies>` tag.

## **[MODULE GRADLE]**

According to the Android documentation plugins should be added to the top of the module gradle file:

```
apply plugin: 'com.android.application'

// Apply other plugins by ID
apply plugin: 'com.example.pluginA'
apply plugin: 'com.example.pluginB'
```

This is also already possible if you use the `<YYAndroidGradle>` tag.

**Comment by silengames** [comment]
Hi DiasFranciscoA,

Thank you very much for your answer! You are absolutely right. The <plugins> tag can be replaced with "apply plugin"

Thanks,
Vitaliy
