### ISSUE TITLE
Manual+In-Game: Feather/Manual info for audio_destroy_stream() is incorrect, and the function does not return its intended value correctly

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#4415]
### Description

There are several things wrong with `audio_destroy_stream`:
- Feather/The manual suggests that function takes a string as an argument, when it actually takes a sound asset.
- Feather/The manual suggests that the return value of the function is undefined when it is actually a real.
- In the runner, the value type is set as int32. This means the function always returns '0'.
- Feather/The manual should reflect that the value '1' is returned if the stream was successfully destroyed, and '-1' if it wasn't.

### Expected Change

- The return value of the function at runtime should be fixed (as above).
- Feather/The manual should reflect the correct argument and return value type.

### Steps To Reproduce

1. Open the attached project: [ghb-4415.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13988928/ghb-4415.zip)
2. Open the Create event of `obj_run`.
3. Observe that feather complains about a sound asset being passed to `audio_destroy_stream`.
4. Observe that feather suggests that the return type of `audio_destroy_stream` is undefined.
5. Run the project on Windows and observe that the returned value is 0 regardless of whether the stream was successfully destroyed.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), Beta IDE v2024.200.0.461 Runtime v2024.200.0.485

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
Updated runtime behaviour and feather info:
- Argument is now named `sound` and is of type `Asset.GMSound`.
- Return value is now of type `Real` and will be `1` if successful and `-1` if not.

Note:
- The HTML5 version of the function was also fixed by this.
- I also found and fixed https://github.com/YoYoGames/GameMaker-Bugs/issues/4464 during work on this task.

**Comment by cameron-home** [comment]
Verified fixed for HTML5 in IDE v2024.200.0.472  Runtime v2024.200.0.488. To be verified in Windows in next beta build.
