### ISSUE TITLE
In-Game: [HTML5] Passing an invalid sound asset to audio_sound_get_gain, audio_sound_get_track_position and audio_sound_set_track_position will generate an unhandled exception.

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#4416]
### Description

Passing an invalid sound asset to `audio_sound_get_gain`, `audio_sound_get_track_position` and `audio_sound_set_track_position` will crash the HTML5 runtime.

The behaviour in the main runtime is as follows:
- `audio_sound_get_gain` returns 0.
- `audio_sound_get_track_position` returns 0.
- `audio_sound_set_track_position` returns undefined.

### Expected Change

The HTML5 runtime should match the main runtime's behaviour.

### Steps To Reproduce

1. Open the attached example project: [ghb-4416.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13989173/ghb-4416.zip)
2. Look at the code in the create event of `obj_run`. Note that there are three function calls here.
3. Run on HTML5 and observe that the runner crashes due to an unhandled exception.
4. Comment out the first function call and run to test the second function.
5. Comment out the second function call as well, and run to test the third function.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), Beta IDE v2024.200.0.461 Runtime v2024.200.0.485

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.523  Runtime v2024.400.0.544, thanks.
