### ISSUE TITLE
Cannot create local packages while logged out 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4417]
### Description
Creating local packages used to require a subscription, but with the license changes no longer does. However, it still requires being logged in, like creating an exe does. Russell told me this isn't intentional, so I'm reporting it.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/4ffb410d-77b0-4bd9-8340-cf6b892d683e

### Steps To Reproduce
Log out, see that "Create local package" is greyed out under the tools menu.

[36a9ac45-2df3-4297-ae96-48a095e1cc03](https://api.gamemaker.io/api/github/downloads/36a9ac45-2df3-4297-ae96-48a095e1cc03)

**Comment by tabularelf** [comment]
You also can't access certain platform settings under preferences. For instance, trying to change Android settings results in a completely blank Window screen. 
<img width="613" alt="2024-02-04_08-19-58" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/a83fdac7-eec8-4baa-ade6-fb1daa97bcd4">

**Comment by YYDan** [comment]
@tabularelf That one is more likely that you do not/did not have the Android (for example) runtime installed at that time. The sheer fact that you could see the platform in the Preferences sidebar and can reach that blank screen means the licensing check was not the problem ;)

Regardless, to be clear: that would be a separate, second issue (if it was a problem) and so is not part of this fix.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.522  Runtime v2024.400.0.543, thanks.
