### ISSUE TITLE
Compiler doesn't respect local variable that has same name as a script function in latest Beta

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4418]
### Description

Run the enclosed project. Error is thrown doing ds_map_copy as it is using the script function map not the local variable map
[nametest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13991035/nametest.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by YYDan** [comment]
Sample works now using  IDE v2024.200.0.470  Runtime v2024.200.0.486. Closing.
