### ISSUE TITLE
Building Projects: [HTML5] Durations of streamed sounds are not found during compilation if the project name has a space

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#4419]
### Description

When compiling for HTML5, the durations of streamed sounds are written into the WAD.

However the subprocess by which the duration is found fails if the project name has spaces in it. The project path is parsed incorrectly as it is not quoted.

This then leads to the default value of 0 being written to the WAD, which can lead to divide-by-zero errors at runtime.

### Expected Change

The duration of streamed sounds should be written into the WAD correctly regardless of the project name

### Steps To Reproduce

1. Open the attached project: [spaced title.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13992359/spaced.title.zip)
2. Run on HTML5.
3. Observe that the displayed duration is 0 instead of the actual value of 20.
4. Re-save the project with a name that doesn't contain a space.
5. Run the project again - observe that the displayed duration is now correct.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.200.0.461  Runtime v2024.200.0.485

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

HTML5

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
Blocks https://github.com/YoYoGames/GameMaker-HTML5/issues/411

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.472  Runtime v2024.200.0.488
