### ISSUE TITLE
[Switch] Compiled NSP Breaks Textures

### ISSUE THREAD

**Issue by jbonesy** [YoYoGames/GameMaker-Bugs#4420]
### Description

Due to Nintendo NDA I can't mention more specific information but I can follow-up in Slack Channel as requested besides current information there. 

Essentially, textures are broken in-game but only when running from a compiled NSP (build package). Running from the editor (YYC or VM) does not produce this error, and the game runs normally/expected. However upon compiling and entering the game (once again VM or YYC), almost all textures from outside the Default texture group fail to load through texturegroup_ functions. We've confirmed this only happens on Switch in the current runtime, but we know that in past runtimes this was an issue with Android Bundles breaking textures in a very similar manner.

Images of this and more details are posted on the Slack and once again the team has access to the Git for this title.

### Steps To Reproduce

1. Start GameMaker
2. Open the project from the GIT
3. Build a package/Create Executable, with Switch as the target and GMS2 VM or GMS2 YYC as the Output
4. Run the exported NSP on Devkit
5. From the main menu, select new game, then finish the introductory quiz segment (just keep pressing A and enter arbitrary text when prompted)
6. Once transitioned to the 1st room with the player character, notice that all textures are broken
7. See the issue

Similarly, you skip steps 3-4 and simply build from editor directly to devkit with nspd_root, notice step 6 does not occur.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Switch

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Modified Windy Woods to show the issue https://drive.google.com/file/d/1xnGiv-f2eGSI_xcXUcQJgExvGUpkkfcZ/view?usp=sharing run an installed .nsp and see the problem

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.489  Runtime v2024.200.0.505, thanks.

**Comment by cameron-home** [comment]
Verified fixed in LTS IDE v2022.0.3.82  Runtime v2022.0.3.97
