### ISSUE TITLE
construction script for instances in the room editor, when instance variables change

### ISSUE THREAD

**Issue by jack27121** [YoYoGames/GameMaker-Bugs#4436]
### Is your feature request related to a problem?

When placing objects in your room, it is very often helpful to make special sprites and icons to make it clear what those objects do. But some objects also have instance variables set, and you can't know what their settings are unless you open up the instance to check.

This is not an intuitive way to build levels in a game, especially not if you hand off a room to someone else, who doesn't know what each object in the room are set to

### Describe the solution you'd like

I'll here use an example from a different popular engine, UE5, without going into too much detail, they offer construction scripts.
Which is a script that runs whenever you change an objects position/rotation/ect or it's instance variables in the level editor, not during runtime.

So if a special event was added to objects called construction scripts (or whatever else)
You could have simple code change the instance's image rotation, image sprite, color and so on. To make it much clearer for the level builder what settings are applied. It should be used mainly as a cosmetic for the room editor.

### An example:
I have a special collision object, with an instance variable drop down, saying if it's solid, or oneway. Then when changing this variable the construction script can automatically change the sprite to be that of a
solid blue (indicating solid)
or green arrow pointing up (indicating one way)

![GameMaker_lbeC4SkvTJ](https://github.com/YoYoGames/GameMaker-Bugs/assets/46312671/c4130eae-f089-4f43-82b8-82ede916e975)

![GameMaker_VoLKFO8MAY](https://github.com/YoYoGames/GameMaker-Bugs/assets/46312671/9b2de379-7b82-474c-a34a-905d8fc687cf)

### Describe alternatives you've considered

you can either just get used to opening up instance's variables to double check whenever you need to

or instead of even using instances, you can make child objects, that have specific different properties and sprites, so it's easier to place in the room. The later i've resorted to many times for clarity in the room editor. But it's not ideal.

**Comment by stuckie** [comment]
We are not currently planning on allowing code to be run in the Room Editor.
You can also set sprite_index in your global variables, it just won't be reflected in the Room Editor.
