### ISSUE TITLE
Macros in a config cause an error to be thrown

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4439]
### Description

Run enclosed project in NewConfig1 configuration, see error is thrown
[macrotest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14007895/macrotest.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2
