### ISSUE TITLE
Repeated calls to audio_load_group during room load cause memory leak

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4440]
### Description

Run the enclosed project, press spacebar, see that with every press (which causes a room load) the reported memory usage (displayed in the output) increases 
[audiogroupleak.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14008197/audiogroupleak.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
- Group loading for non-GX targets no longer has a one frame delay before starting.
- Fixed a leak caused by attempting to load a group that was currently unloading.
- Adds a debug message for calls to `audio_group_load` that fail due to the group not being in an unloaded state.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
