### ISSUE TITLE
Add to sprite_get_uvs info about trimmed right and bottom pixels

### ISSUE THREAD

**Issue by dt-universe** [YoYoGames/GameMaker-Bugs#4443]
### Is your feature request related to a problem?

sprite_get_uvs returns info about how much pixels were trimmed on left / top side, but we should calculate right and bottom from percent and left / top data.

### Describe the solution you'd like

sprite_get_uvs should return data about trimmed pixels from right and bottom sides too.

### Describe alternatives you've considered

I can calculate this by myself, but better will be if GM will return this data too. To calculate right / bottom side I do:

```
var _width = sprite_get_width(sprite);
var _height = sprite_get_height(sprite);

var _uvs = sprite_get_uvs(sprite, 0);

var _trimLeft = _uvs[4];
var _trimTop = _uvs[5];

var _trimPercentX = _uvs[6];
var _trimPercentY = _uvs[7];

var _trimRight = _width - (_width * _trimPercentX) - _trimLeft;
var _trimBottom = _height - (_height * _trimPercentY) - _trimTop;
```

**Comment by rwkay** [comment]
you get this information from `sprite_get_info` - it will return all the information that you want above. see https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Sprite_Information/sprite_get_info.htm

**Comment by dt-universe** [comment]
But it's too much...? I don't need a whole info about sprite, if sprite_get_uvs returns info about trimming, why just part of it? And as I can see you have there x_offset, y_offset, same as left / top side, but still no right / bottom side info.

**Comment by rwkay** [comment]
well the bound box gives you the logical width and height of the sprite and the offset x and y give you the amount to add onto the x and y of the sprite while the position on the texture page give you the amount to actually render... all of those give you the info you need.

Russell

**Comment by stuckie** [comment]
Closing as above
