### ISSUE TITLE
Websocket Re-Connection Fails on HTML5

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#4447]
### Description

You have a Websocket server and client.

The client is programmed with a re-connection cycle so that when the connection to the
server is lost it tries to connect again in regular intervals (using the normal netwerk_connect_async() function).

If both server and client run on the Windows target the re-connection works correctly (meaning: when you close the server and re-open it again, the client will connect again).

If you run the server on the Windows target and the client in HTML5 then the re-connection doesn't work (meaning: the first connection works but after the server is closed and re-started the HTML5 client doesn't connect again).

See supplied simple example projects for server and client.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14016054/contactus.zip)
[Websocket_Server+Client.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14016055/Websocket_Server%2BClient.zip)

### Steps To Reproduce

1. Load the supplied example project (server and client)
2. Start both in Windows target. Watch client connection succeed.
3. Close server and wait for client connection to register the disconnect.
4. Re-Open server and wait for client to reconnect successfully.
5. Now do the same steps but with the client running on HTML5.
6. After closing and re-starting the server the HTML5 client doesn't connect again.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by TheGitMagician** [comment]
@yoyo-danielc: Is there any update on this? I need this for a web app I'm working on. As soon as the HTML5 app loses the (websocket) connection to the server it can't re-establish the connection once the server (Windows) is back online.

**Comment by yoyo-danielc** [comment]
Hi @TheGitMagician,

Apologies for the delay on this issue.

Calling `network_connect()` (or any of the other `network_connect_XXX()`) functions more than once on the same socket isn't supported on all platforms, and may not be feasible to fix on all platforms due to how the underlying socket APIs work.

For compatibility's sake, I suggest making your code destroy the old socket and create a new one each time you start a new connection attempt. The sample you provided seems to work fine if I add appropriate calls to `network_destroy()` and `network_create_socket()` into the Alarm 1 event before calling `network_connect_async()`.

**Comment by TheGitMagician** [comment]
@yoyo-danielc: Thank you for taking the time to answer!

Your solution works! Thank you very much! I only have one question about it: The manual entry for `network_destroy()` mentions: "NOTE: This function will not work when used in a project running on the HTML5 target." Would you say that it is fine to just override the previous socket with the new socket or is this a potential memory leak?

If the implementation is not planned then its fine if you close this bug report.

**Comment by yoyo-danielc** [comment]
I'm not sure why the manual says that... might be outdated, there shouldn't be any problems calling `network_destroy()` on HTML5, if there are, then that _is_ a bug IMO. If you don't call `network_destroy()` then yes, it will be leaking those connections until the page is reloaded and you might run into some limit in the browser.

**Comment by TheGitMagician** [comment]
Got it, thanks!
