### ISSUE TITLE
In-Game: HTML5 parsing JSON "null" in a struct as undefined

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#4452]
### Description
The HTML5 runner is  parsing "null" in a struct as undefined where as "null" is directly parsed as null

### Steps To Reproduce
1. import the attached project
2. Run targeting windows
3. notice the top two outputs are null
4. rerun targeting html5
5. notice the outputs are { nada : undefined } and null

[659f01f2-668f-48bd-aa4a-f42b693de515](https://api.gamemaker.io/api/github/downloads/659f01f2-668f-48bd-aa4a-f42b693de515)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.200.0.475  Runtime v2024.200.0.490
