### ISSUE TITLE
Silent crash when room transition

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#4461]
### Description
New beta is looking good and gives no error for now. When I try to transition to another room via my teleporter though, it crashes instantly with no message. It didn't do this before...

### Steps To Reproduce
*Open game
*Collide with teleporter (o_door) object "blue box sprite" 
*Transition is happening inside the (o_transition)
*Observe

[e8ccf872-bbbd-49f7-a207-7f63de9add07](https://api.gamemaker.io/api/github/downloads/e8ccf872-bbbd-49f7-a207-7f63de9add07)

**Comment by jackerley** [comment]
Hi, I've checked your project and I notice you're getting the line size mismatch got 521 expected 510 - sz=-11 in your output. This bug is now fixed and your project should run as expected in the next beta. https://github.com/YoYoGames/GameMaker/issues/3434

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
