### ISSUE TITLE
Duplicate case statement Error given in VM 

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#4462]
### Description

Compile error when compiling for VM with [scrpttest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14024819/scrpttest.zip)

### Expected Change

No Compile Error

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by scott-dunbar** [comment]
Project no longer throws compile error - closing  IDE v2024.200.0.476  Runtime v2024.200.0.491
