### ISSUE TITLE
In-Game: [HTML5] Successfully destroying a stream with audio_destroy_stream() will cause asset gain updates to throw an unhandled exception

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#4464]
### Description

`audio_destroy_stream` nulls an audio asset, which we fail to consider for when updating asset gains.

Note: This was already fixed during work on https://github.com/YoYoGames/GameMaker-Bugs/issues/4415 and is just being logged.

### Expected Change

An exception should not be thrown.

### Steps To Reproduce

1. Open the attached example project: [ghb-4464.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14025485/ghb-4464.zip)
2. Run on HTML5.
3. Observe the exception in the console `Unhandled Exception - TypeError: --- is null`.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.200.0.471 Runtime v2024.200.0.487

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
As above, this was fixed during work on https://github.com/YoYoGames/GameMaker-Bugs/issues/4415.

**Comment by cameron-home** [comment]
No error thrown in Beta IDE v2024.200.0.475  Runtime v2024.200.0.490, so marking as verified.
