### ISSUE TITLE
Re-imported room moves to the bottom of the room order

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4465]
### Description

Any time a room is imported from a local package, it will be placed last in the room order even if the room is already present in the project file. This causes problems for rooms that need to appear earlier in order to init variables/create objects.

### Expected Change

If the room asset is already present in the project file, have the imported version retain that asset's room order.

### Steps To Reproduce

1. Create new GM project
2. Create a room (`Room2`)
3. Click tools -> create local package
4. Add `Room1` to the local package, name it and click "okay"
5. Click tools -> import local package, select the file and click "add all" -> "import", and "replace all"
6. See the issue - `Room1` is now second in the room order

[Room order.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14026821/Room.order.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment]
Fixed to preserve room order when replacing existing room

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.522  Runtime v2024.400.0.543
