### ISSUE TITLE
UI/UX: One user cannot type Shift+L anywhere in Beta IDE v2024.200.0.471 or 472 

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4469]
### Description
I cannot type Shift+L anywhere in Beta IDE v2024.200.0.472 (or 471) - however, all other keys work just fine, including a lowercase l.

My keyboard has no issues typing a capitol L in any other application at the same time as GM won't allow it.

Can see that my current ui.log is saying that a duplicate redefine key entry was found:

```
[17:18:52:198(474f)] Warning loading hotkeys from file ./default_hotkeys.json - the following hotkeys had multiple entries:
[17:18:52:199(474f)] 	- 'Select Rotate Tool'
[17:18:52:199(474f)] 	Duplicate entries will not be loaded
```

And also a previous IDE run (when I first noticed this) began spewing this silent error:

`[17:09:45:629(9578)] Error performing Key lookup - 35 was not found in the lookup`

However, my current run of the IDE is not logging any errors and yet I still cannot type a capitol l.

Restarting the IDE several times has not helped, nor has updating to a different version.

_In case it matters, I am using a full-size UK layout Razer Huntsman V2._

### Steps To Reproduce
1. Start GM and import the attached project
2. Open the object and then open its Create event in the Code Editor
3. Try to type a capitol L
4. Observe the IDE does not add the expected character
5. Open the IDE bug reporter and try to type a L there also

[f70151bc-fd9f-481d-b9f3-dc9ebf7d82f6](https://api.gamemaker.io/api/github/downloads/f70151bc-fd9f-481d-b9f3-dc9ebf7d82f6)

**Comment by YYDan** [comment]
GM was fine again this morning, but I think this must come from triggering IDE lag - via reproducing either #1935 or #4472 - as I have managed to temporarily recreate this again today. However, GM then fixed the issue after I had been idle for a while.

Note: this time, I could not type L or J, so it's not always limited to just L. (I did not check all keys, only a few in that area of the keyboard, so others may have also been affected.)

Need to work out what the precise repro steps are and then ensure others get the same results.

**Comment by caitlinrmcintyre** [comment]
I'm getting this same issue but with Shift+G 
[caitlinui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14223565/caitlinui.log)

**Comment by caitlinrmcintyre** [comment]
So we've realized that there was a remap file for Shift + G in  %appdata%\GameMakerStudio2-Beta\<User> which was causing the issue, but when trying to delete it and restart the IDE, the file was being rewritten as there was also a remaps.json file in the same folder. When deleting these both and restarting the IDE, Shift + G was working as expected (although I am certain I haven't remapped Shift + G and this has only been an issue today)

**Comment by stuckie** [comment]
We think this has been fixed in the interim with various updates to the keybinding system, as well as the SDL2 update.

**Comment by YYDan** [comment]
Yeah, we no longer appear to create the old/original Redefine Keys' "remaps.json" file which was causing the problem here. Have not managed to recreate now, so will mark as verified.

Note, however, that I did see a second issue. where if someone has an old copy of the newer-format remapped_hotkeys.json file from when it was incorrectly in ProgramData for a bit, then we do leave that file alone, which can cause a little confusion. Anyone with this file can just delete it.
