### ISSUE TITLE
image index (frame) on objects

### ISSUE THREAD

**Issue by Shibohi** [YoYoGames/GameMaker-Bugs#4476]
### Is your feature request related to a problem?

no, it would just be a quality of life thing

### Describe the solution you'd like

i want to set the image_index (called "frame" in instance editor?) for objects. currently we only can set it for instances.
if we could set the image_index of an object we could use one sprite strip for the gamemangers etc. 
no need of many single sprites for all the managers or other "global" objects. 
also parent and child nodes could use 1 sprite instead of many single ones.

### Describe alternatives you've considered

use single sprites

**Comment by stuckie** [comment]
If you mean to change the image representation in the Room Editor, we have a feature request for this already.
However, as you have stated, image_index is an instance level variable, and we are not intending on bringing it up to the object level.
