### ISSUE TITLE
variable_get_hash() has undocumented behavior

### ISSUE THREAD

**Issue by VacantShade** [YoYoGames/GameMaker-Bugs#4478]
### Description

I was informed by user **dragonitespam** the following undocumented behavor.
variable_get_hash() will, if used on a struct or array, stringify the contents before generating a hash.

This can be observed by the following code:

```
var a = {};
a.test = [ 5 , 13 , 24 , true ];
a.sub = { x: 23 , y: 42 };

show_debug_message( variable_get_hash(a) );// 113234

var b = {};
b.sub = { x: 23 , y: 42 };
b.test = [ 5 , 13 , 24 , true ];

show_debug_message( variable_get_hash(b) );// 113234

b.extra = 53;

show_debug_message( variable_get_hash(b) );// 113235
```

I was additionally informed by the user **mesetatron** that because HTML5 internal system is different, that the stringify step is not always consistent in the order of nested elements. Therefore hashing identical structs/arrays may produce different hashes, whereas Windows and perhaps others will return an identical hash. I have not tested this on HTML5 myself.

### Manual Link

http://127.0.0.1:51290/index.htm#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Fvariable_get_hash.htm

**Comment by attic-stuff** [comment]
you should not expect the hash for b to be the same after you add a new member to it: it is not the same struct after you give it a new member therefore it will have a different hash.

that being said, structs are unordered and that is documented so you should not be relying on structs getting the same stringified order and producing the same hash on any platform, much less cross platform. if you're trying to use hashing to see if two structs have equal values that would not be a very reliable test.

**Comment by stuckie** [comment]
This is not a bug - this is how the hash works.

**Comment by rwkay** [comment]
This function takes a string and not a struct or array - the code is just converting whatever you pass in to a string first and then using the hash logic for that.
