### ISSUE TITLE
Debugger: [CE2] New code is ignored when added in the active debugger tab and also not added to the object code

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#4483]
### Description

 if I run the debugger which opens the debugger tab, then stop it, add some code in the debugger tab, which used to then also add it to the object, now it doesn't. In fact the debugger will totally ignore the new code.

NOTE: You must have CE2 enabled

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Add an object and a bit of code
4. Run the debugger
5. With the debugger open, add some more code with a breakpoint
6. Run the debugger again
7. Observe the break point is not and code ignored
8. Check the code editor for said object and notice no new code has been added

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
We will need to set the debugger as readonly for now as the debugger is using CE1 and CE2 cannot share it's view buffers with it.

**Comment by yyalansavage** [comment]
Made debugger code tabs read-only when using CE2

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
