### ISSUE TITLE
`draw_sprite_ext()` - use optional arguments defaulting to instance variables

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4485]
### Is your feature request related to a problem?

Frequently, when using `draw_sprite()`, I want to take into account the instance variables that `draw_self()` would use.  `draw_sprite()` always uses a scale of 1, angle of 0, `c_white`, and 1 alpha, so natural solution is to use `draw_sprite_ext()`.

However - you have to write out every value each time, which is cluttered and feels unnecessary:

```gml
draw_sprite_ext(sAlert, 0, x, y, image_xscale, image_yscale, image_angle, image_blend, image_alpha)
```

### Describe the solution you'd like

Have `draw_sprite_ext()`'s parameters default to their corresponding instance variables(`sprite_index`, `image_index`, `x`, `y`, `image_xscale`, `image_yscale`, `image_angle`, `image_blend`, and `image_alpha`). The above could be written as:

```gml
draw_sprite_ext(sAlert, 0)
```

Furthermore, a lot of programmers tend to pass in arguments that hard code values when they should be referencing that instance's variables instead (such as using `c_white` when they should be using `image_blend`). Having logical default values like this could cut down on those cases.

### Describe alternatives you've considered

I use a helper script.

**Comment by stuckie** [comment]
This would break many projects, so it is not something we are planning.

**Comment by backYard321** [comment]
> This would break many projects, so it is not something we are planning.

Not to be argumentative, but unless I'm misunderstanding: wouldn't making an argument optional only affect code where those arguments weren't provided in the first place, which would error out anyway? So the projects affected wouldn't actually be functional to begin with.
