### ISSUE TITLE
`room_get_info()`: incorrect name for Tile Map data's `tileset_index`.

### ISSUE THREAD

**Issue by glebtsereteli** [YoYoGames/GameMaker-Bugs#4486]
### Description

When loading room info with `room_get_info()`, Tile Map data's [supposed](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/room_get_info.htm) `tileset_index` variable is named `background_index`.

Quote from Russell:
> ok in the C++ it refers to background index and I think I was just mixed up when writing the code... please file a bug on that and I will change it to tileset_index so the documentation is correct

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/50461722/6644d8c2-71f8-4f95-8664-f627255ca45f)
[room_get_info() Tilemap Data Bug Package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14041617/room_get_info.Tilemap.Data.Bug.Package.zip)

### Expected Change

Correct the variable name to match the documentation.

### Steps To Reproduce

1. Start GameMaker
2. Create a new project.
3. Create a tileset.
4. Create a Tile layer in a room.
5. Fetch that room's data with `room_get_info()`.
6. Display the info.
7. See the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by YYBartT** [comment]
No change needed to documentation

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.200.0.475  Runtime v2024.200.0.490
