### ISSUE TITLE
is_instanceof incorrectly identifies global as a instance

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#4504]
### Description
In previous versions, `is_instanceof` would return `false` if you were to call a constructor that checked for `is_instanceof` like it were an ordinary function. The benefit of doing it this way was it made it possible to make a constructor be both a constructor, but also execute some custom code alongside depending whether it was a constructor or not.

This also causes a discrepancy since `self` in the script on the first call is actually `global`, so therefore it should return `false`!

Note: This happens only on VM, YYC works as intended.

### Steps To Reproduce
1. Download and import project
2. Run game
3. See output log for `==Script==` and `==Object==`.

[8974c689-0651-4704-b58f-b8d5e28317a7](https://api.gamemaker.io/api/github/downloads/8974c689-0651-4704-b58f-b8d5e28317a7)

**Comment by rwkay** [comment]
Fixed in 2024.2 - Ensure global prototype is not overwritten when constructor called as a function
* YYC was OK so only VM and HTML5 are fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
