### ISSUE TITLE
Silent crash occurs when the ds_map for an http request stops existing.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#4505]
### Description

When you perform an http request, a ds_map gets automatically created. This map is used as the `async_load` map in the HTTP Async event.

If that ds_map gets destroyed before the HTTP Async event gets processed, the game will silently crash instead of showing an error message explaining that its ds_map stopped existing.

[DSMapVanish.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14056725/DSMapVanish.zip)

### Expected Change

If the ds_map for an async event stops existing before the async event occurs, the game should show an error message instead of silently crashing.

### Steps To Reproduce

1. Run the test project.
2. Observe the silent crash.
3. Enjoy a snack

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by shichen85** [comment]
For regression testing purpose, the replication step can be simplified to just running:
```gml
var map_count = debug_event("ResourceCounts", true).mapCount;
show_debug_message("Num ds_maps: " + string(map_count));
http_get("https://www.bscotch.net/api/dummy/headers");
var new_map_count = debug_event("ResourceCounts", true).mapCount;
show_debug_message("Num ds_maps: " + string(new_map_count));
var new_map_index = new_map_count-1
ds_map_destroy(new_map_index);
```

**Comment by jackerley** [comment]
GMRT didn't like debug_event("ResourceCounts", true).mapCount and struggled with globalvar MAP_A but crash appears not to occur once these are avoided.
