### ISSUE TITLE
Virtual key codes for F11 and F12 are incorrect.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4512]
### Description
The keyboard_lastkey variable returns key codes 128 and 129 for the F11 and F12 keys, respectively. However, the vk_f11 and vk_f12 constants are equal to 122 and 123, respectively.  So either the VK constants are incorrect, or the keyboard_lastkey variable is returning the incorrect values.  See attached project for a demo.

Note: Only tested on the macOS platform.

### Steps To Reproduce
1) Load the attached project.
2) Run the project.
3) Hit F11 or F12 on your keyboard and observe how the lastkey results (shown in the game window) don't match the constants.

[d38a9773-60a0-4640-86c1-294ac08a0ff2](https://api.gamemaker.io/api/github/downloads/d38a9773-60a0-4640-86c1-294ac08a0ff2)

**Comment by yoyo-danielc** [comment]
Can't reproduce this on Windows or macOS with IDE v2024.2.0.132  Runtime v2024.2.0.163.
