### ISSUE TITLE
Project Load: "Resources" section of project .yyp file is not in a fixed order, causes issues with source control

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#4520]
### Description
In the YYP file, "resources" list is sorted pretty randomly, without any apparent pattern of alphabetical order or similar. It makes it harder to find specific entries in the file and may sometimes result in entries moving around in relation to others, both of which make it harder to manage the YYP in version control.

Please have the project resources sorted in an alphabetic similar for easier management.

[119a7c46-aee3-41c0-976f-d7638d3c153e](https://api.gamemaker.io/api/github/downloads/119a7c46-aee3-41c0-976f-d7638d3c153e)

**Comment by stuckie** [comment]
The "Folders" list were similarly out of order, so these have been fixed too.

**Comment by Alphish** [comment]
I opened a pre-format changes project in .499 Beta, project conversion to the new format on its own didn't sort the resources, but subsequently adding an asset and saving the project did.

I'll leave it up to you to decide whether lack of sorting just after conversion is a problem or not (it'll gradually solve itself, as more projects are made in the new format to begin with).
