### ISSUE TITLE
phy_collision_x/y is marked as real, but is an array

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#4532]
### Description
phy_collision_x/y is marked as real, but is an array

[3a03bac0-6116-42d3-bc57-5f4a87cbc4d9](https://api.gamemaker.io/api/github/downloads/3a03bac0-6116-42d3-bc57-5f4a87cbc4d9)

**Comment by Appley-Apple** [comment]
I don't know how the GML type system works exactly but this appears to be more than just a documentation issue. On the current beta version I am unable to use array functions on `phy_collision_x` or `phy_collision_y`, however I can still index them as if they are arrays. Also, `typeof(phy_collision_x)` returns `"number"`, not `"array"` (same for `phy_collision_y`).

**Comment by Glim888** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/30154346/497b0b30-8f7f-4d2c-9faa-42b4566bf7b0)


This is how I use it in RT v2023.11.1.160

**Comment by Glim888** [comment]
I would like to add an additional error about the phy_collision_points.

If you destroy the instance in the same collision step. Then the phy_collision_points became null (silent crash)

**Comment by Appley-Apple** [comment]
> ![image](https://private-user-images.githubusercontent.com/30154346/303916771-497b0b30-8f7f-4d2c-9faa-42b4566bf7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTMyNTEsIm5iZiI6MTcwNzY1Mjk1MSwicGF0aCI6Ii8zMDE1NDM0Ni8zMDM5MTY3NzEtNDk3YjBiMzAtOGY3Zi00ZDJjLTlmYWEtNDJiNDU2NmJmN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyMDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZGQzMzM0MDYzN2ZhZGUxZTcwMDIwYjA5OTQ2ZGIzNGNlN2Q1OWZmMzdlMTA4NDI0ZjBiZGQ0ZDkyNDgzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x4WKav3m8fOOEdzt0ujeas8WBp3MWum9YrOC4QQR-XQ)
> 
> This is how I use it in RT v2023.11.1.160 to avoid crashes.

Is there a way to handle multiple collision points? Sometimes I get 2 collision points and I'd like to know where both of them are, currently `phy_collision_x` and `phy_collision_y` are just numbers so they only tell you about a single point.

**Comment by Glim888** [comment]
Nah it's an array, but you need to check how long the array is.

**Comment by alicemoretti** [comment]
Verified fixed in the current Beta version of the Manual. 

Thank you.
