### ISSUE TITLE
Bug in sequence audio filters: Toggle button not working

### ISSUE THREAD

**Issue by mmMarzban** [YoYoGames/GameMaker-Bugs#4537]
### Description

For audio filters in sequence, the toggle key doesn't work and you have to change the values manually or adjust it in the inspector to insert a keyframe.

### Expected Change

The toggle button to add a keyframe should also work for audio filters.

### Steps To Reproduce

1. Start GameMaker
2. Create a sequence.
3. Add a sound asset into the sequence.
4. add some random audio filter to it (e.g Delay)
5. Try to use toggle button to add a keyframe to the audio track.
6. Sadly you fail :)
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.483  Runtime v2024.200.0.499.
Thank you.

**Comment by mmMarzban** [comment]
> Verified fixed on IDE v2024.200.0.483 Runtime v2024.200.0.499. Thank you.

Is it intended behavior that the mere addition of an audio filter track to the sequence, (without inserting any keyframe), applies the effect.

**Comment by toby-yoyo** [comment]
Yes, that is intended behaviour. When no keyframe is on the track, the parameter evaluates to a default value. For parameters like gain and pitch, the defaults are such that they have no perceivable effect, but that's not possible to achieve for all audio effects. So audio effect tracks will have the same default values as uninitialised effect structs returned by `audio_effect_create`.
