### ISSUE TITLE
[Urgent] Where is Spine 4.1 Support!

### ISSUE THREAD

**Issue by ghost** [YoYoGames/GameMaker-Bugs#4540]
### Is your feature request related to a problem?

If you guys are gonna support a Spine you should keep it updated for every release. It'll be 2 years since 4.1 came out, July of this year.

I really really really don't want to use Unity.

### Describe the solution you'd like

It's be nice to get it updated ASAP. If the team is backed up, maybe contact Esoteric Software for some help.

### Describe alternatives you've considered

Switching Engines, but only option is Unity. Please not Unity.

**Comment by iampremo** [comment]
Duplicate #2815

**Comment by rwkay** [comment]
We are not planning to support Spine 4.1 but go directly to 4.2

**Comment by rwkay** [comment]
We will schedule it when we have a clear idea when 4.2 may come out of Beta - if you have any links that may give an indication on when that will happen then please let us know.

**Comment by Shavv** [comment]
> We will schedule it when we have a clear idea when 4.2 may come out of Beta - if you have any links that may give an indication on when that will happen then please let us know.

https://en.esotericsoftware.com/blog/Spine-4.2-The-physics-revolution

Spine 4.2 has been out since 16 Apr 2024. Is there any update planned for this?

**Comment by Brick2892** [comment]
@rwkay Is there any update on when Spine 4.2 support will be added?
