### ISSUE TITLE
Beta: animation curve editor is completely busted

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4541]
### Description
Not sure how to describe the issue other than editing the actual curve just kinda doesn't work at all.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/fa88c691-4d8f-4c0c-bd61-371ec43eefa0

### Steps To Reproduce
Make an animation curve, try to edit it.

[ddaffc74-1498-45a7-848e-93d38739cee5](https://api.gamemaker.io/api/github/downloads/ddaffc74-1498-45a7-848e-93d38739cee5)

**Comment by yyalansavage** [comment]
Fixed for Beta IDE v2024.200.0.476+; note the issue only occurs for a newly created animation curve, not those loaded from an existing project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
