### ISSUE TITLE
In-Game: Layer effect Gaussian Blur crashes when used with room_restart

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#4546]
### Description
In the attached project if a player wins a game the room is restarted using room_restart. In the level there is a Gaussian blur applied using a filter/effect layer. On restarting the room there is an error. If this effect is changed to recursive blur then there is no error.

The error mentioned below is shown.

ERROR in
action number 1
of Draw Event
for object <undefined>:

Trying to set a surface target that does not exist.
 at gml_Script_anon@3780@_effect_gaussian_blur__effect_gaussian_blur_script (line 172) -                             surface_set_target(surfaces[i * 2]);
############################################################################################
gml_Script_anon@3780@_effect_gaussian_blur__effect_gaussian_blur_script (line 172)

### Steps To Reproduce
1. import the attached project
2. run targeting windows
3. click the green button
4. the image numbers is printed in the output. Look for two matching number and click the relevant boxes. The numbering starts top left.
5. A win alert will show, then the error will show
6. go to Room1 and change the layer_gauss setting to recursive blur
7. rerun the project and win a game
8. notice no error

[21a88c4a-02f9-4a6f-b08d-5c5a8a79ede0](https://api.gamemaker.io/api/github/downloads/21a88c4a-02f9-4a6f-b08d-5c5a8a79ede0)

**Comment by JonnoRobson** [comment]
The issue was caused by the Gaussian blur effect not recreating surfaces after a room restart. I've made sure the `resources_initialised` flag in the script is reset on room_end so that the resources will be recreated correctly.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
