### ISSUE TITLE
Bug Reporter: Expose the GM version number and OS automatically in the resulting report

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4549]
### Description
The in-IDE Bug Reporter should expose the GM version numbers and the current OS automatically in the resulting report - complete with formatting, so it matches a web-submitted report.

We collect this information already, but exposing it as part of the issue content would speed up reviewing issues and clear up any confusion.

### Steps To Reproduce
1. Start GameMaker
2. Open the IDE bug reporter
3. Submit any report
4. Notice that the version number is not called out, nor is the host OS/IDE

[94cb71d2-9e5f-4663-968c-4607058def14](https://api.gamemaker.io/api/github/downloads/94cb71d2-9e5f-4663-968c-4607058def14)

**Comment by YYDan** [comment]
Compare the description above versus e.g. https://github.com/YoYoGames/YoYoStudio/issues/9253

Note that the other one has two dedicated sections after the repro steps:

### Which version of GameMaker are you reporting this issue for?
IDE v2023.9.0.213 Runtime v2023.0.9.192

### Which operating system(s) are you seeing the problem on?
Windows 11

**Comment by Emc1923** [comment]
Verified done. Example [issue](https://github.com/YoYoGames/Incoming-Bugs/issues/231) can be deleted
