### ISSUE TITLE
Game Options: GX.games missing string for its title bar in Feb24 Beta

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#4553]
### Description

GX.games is missing its title string inside Game Options and under Game Options inside the Asset Browser.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/c7b97615-ec28-4576-b77a-882b903c27cc)

Tested using Beta IDE v2024.200.0.475  Runtime v2024.200.0.490

[Contact Us Package](https://drive.google.com/file/d/15XWS5Gn0lbgufWOLU-yA6gCSyh1Bjy73/view?usp=sharing)

### Steps To Reproduce

1. Start GameMaker Beta and open/create a project
2. In the Asset Browser, expand Game Options
3. Observe the missing string for GX.games

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by CalumLaverock** [comment]
I've updated the default name for the GX.Games settings in a project to be correct for newly created projects however old projects will still be missing. The name can be updated by going to the {Project Folder}/options/operagx and opening the options_operagx.yy file in a text editor. The "%Name" entry should have a value of "", changing this to "Opera GX" will result in the correct name being used for the settings heading in older projects.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.483  Runtime v2024.200.0.499
