### ISSUE TITLE
Various HTML5 constants & global variables are undefined, like room_width

### ISSUE THREAD

**Issue by flori9** [YoYoGames/GameMaker-Bugs#4555]
### Description
At least the following global variables and constants are undefined on the HTML5 export in the latest beta (.200.0.490), using default runtime:
- room_width
- room_height
- webgl_enabled
- room_first
- room_last
There are probably more but this were the ones I ran into while trying to run my project, before having enough of trying to work around issues.

### Steps To Reproduce
1: open the newest GameMaker beta
2:  run any code with room_width, or anything else above, in it on the HTML5 platform, e.g. put it in the create event of an instance
3: note that these return undefined

[68aa9265-de40-4f37-97d3-f4a814440fed](https://api.gamemaker.io/api/github/downloads/68aa9265-de40-4f37-97d3-f4a814440fed)

**Comment by toby-yoyo** [comment]
This may be a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/4482, which is fixed internally (in the asset compiler), but got merged after Beta Runtime 2024.200.0.490 was built.

Using a compiler built from our 2024.2 head, I get the following for the constants above:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/f8510b14-1985-41ec-8d2d-ce917e8023b1)

**Comment by flori9** [comment]
I missed that issue, looks like it is resolved then, thanks!
