### ISSUE TITLE
In-Game: collision_rectangle() does not correctly report child collisions if not_me is true and if called from an internal constructor method

### ISSUE THREAD

**Issue by matthavik** [YoYoGames/GameMaker-Bugs#4558]
### Description

Calling collision rectangle (and its variants like _list) from within a constructor's method does not report any collisions with any child instance unless 'not me' is set to false. I'd guess it's failing since instances are structs under the hood? But this seems wrong!

The title is a bit of a mouthful - check the example project, that should make it clear. 

There are two child objects in the room (oEnemy and oEnemy2, both children of oParEnemy).

Run the game, hold space to toggle 'not_me'. 
- collision_circle is fine
- collision_rectangle/_list with oEnemy (child) is fine
- collision_rectangle/_list with oParEnemy (parent) is reporting incorrectly.

[collision_rectangle constructor method child object.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14096216/collision_rectangle.constructor.method.child.object.zip)
(Edit: Removed plist file... it's got my personal email address in it for all to see / account / licenses!)

I have selected windows for the platform as I can reproduce it 100% on there. I have had reports from a team member that this also happens on HTML5 - although I can't reproduce it on HTML5 personally.

### Expected Change

collision rectangle should be reporting the same as collision circle

### Steps To Reproduce

1. Start GameMaker
2. Create a parent object (C)
3. Give it two children
4. Add these two children (A and B) to a room
5. Create another object (D)
6. Add this object (D) to the room
7. The parent object (C) should not be in the room
8. In object (D), create a constructor, give it a tick method
9. In this tick method, do a collision rectangle for the parent object (C) for the entire room and print out the result
10. Initialise this constructor in the create event `test = new Test();`
11. Run the tick method in the step event `test.tick();`
12. Run the game - note the incorrect reporting

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by sihammill** [comment]
Verified in IDE v2024.200.0.497  Runtime v2024.200.0.514
