### ISSUE TITLE
Code Editor: handle_parse() is not coloured as a function in 2024.200 Betas

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#4562]
### Description

Since the change to make handle() into handle_parse(), the function is no longer being colour coded as a function. 

This affects both feather and non-feather

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/ac28101e-bc3c-4be9-a0d6-a8da06c33205)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/2e3a78ae-7513-4fa5-b244-840b34ce4e5c)

[handle_parse.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14097098/handle_parse.zip)

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Open a code editor
4. Add a call to handle_parse() 
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by CalumLaverock** [comment]
This appears to have already been fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.200.0.494  Runtime v2024.200.0.511, thanks.
