### ISSUE TITLE
HTML5 Farm Survivor Template did not work beyond title screen

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#4572]
### Description

Farm Survivor does not work on HTML5 with Beta version

incorrectly compiles `delta_time` references as instance variable rather than built ins.

### Expected Change

It should work

### Steps To Reproduce

1. Start GameMaker
2. Make a new game from the Farm Survivor Template
3. Compile for HTML5
4. Click PLAY on the title screen
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.478  Runtime v2024.200.0.493
