### ISSUE TITLE
Local Package Integration: Packages made in 2024.200 cannot be imported into earlier IDEs

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4574]
### Description
If you create a local package in 2024.2 and attempt to import it into 2023.11, the package resources don't appear and you can't attempt to import. I don't know if this is a bug or intended to be a compatibility cutoff, but I'm reporting it just in case it is a bug.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a8b52609-d853-45d7-8790-5260043556d0)

### Steps To Reproduce
Create a local package in 2024.2, and attempt to import it in 2023.11 or any earlier version.

[a0bdd64c-ea50-4f1f-8bfa-bdc342322ee7](https://api.gamemaker.io/api/github/downloads/a0bdd64c-ea50-4f1f-8bfa-bdc342322ee7)

**Comment by stuckie** [comment]
The Package Importer seems to skip the verification checks entirely, so doesn't even warn the user that it's a new format.

**Comment by stuckie** [comment]
With the resource tag fields coming back in, this is worse in that the resources "load" without names...
That could be "resolved" with adding an empty resources list, and changing the new one to "Resources" .. but that's another format change with a leftover field to keep compatibility.

**Comment by stuckie** [comment]
Have added the "name" field back in to continue compatibility for a little longer.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.11.1.129  Runtime v2023.11.1.160
