### ISSUE TITLE
In YYC export, struct variables become corrupted

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4575]
### Description
When parsing a json string into a struct in YYC, the variables can become corrupted.

### Steps To Reproduce
1. Run the sample in VM, see that the variables are read correctly.
2. Run in YYC, see that the variable is corrupted.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.476 Runtime v2024.200.0.491

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[384c8b5b-e0d3-491d-a226-7637092d9713](https://api.gamemaker.io/api/github/downloads/384c8b5b-e0d3-491d-a226-7637092d9713)

**Comment by rwkay** [comment]
Fixed in 2024.2 - the issue was the new optimisation for constant struct accessors only works if the constant string is a valid ID on both YYC and HTML5 so the optimisation only happens now when the constant string is a valid ID

**Comment by mgeddesGM** [comment]
verified as of IDE v2024.200.0.483  Runtime v2024.200.0.499
