### ISSUE TITLE
`sprite_duplicate` takes an inordinate amount of time to run on Android compared to Windows.

### ISSUE THREAD

**Issue by toarch7** [YoYoGames/GameMaker-Bugs#4576]
### Description

As the title says, for some unknown reason running `sprite_duplicate` on Android takes way too much time compared to the Desktop export. 
I have a decent mobile device with 6GB of RAM and an Octa-Core MAX 2.05ghz CPU.

![code](https://github.com/YoYoGames/GameMaker-Bugs/assets/69200110/8b4c288a-89df-4050-8a15-ae442ff60570)
![desktop](https://github.com/YoYoGames/GameMaker-Bugs/assets/69200110/548c14c4-75ba-496e-a795-b5cc7993c0f6)
![mobile](https://github.com/YoYoGames/GameMaker-Bugs/assets/69200110/1e845eab-6a77-4fae-8986-be08b227aca3)

In both cases I'm duplicating several sprites, each with a different number of frames (4-26) and each is 45x45 in size.

[project_example.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14114661/example.zip)
(attached zip file doesn't include the `license.plist` file because it contains my personal info such as email and license token)

### Steps To Reproduce

1. Start GameMaker
2. Attempt to duplicate a 45x45 sprite which has 10 or so frames.
3. Measure execution time on both Desktop (Windows) and Android export targets
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
This is going to be much slower on Android just due to architecture and platform differences to PC.
