### ISSUE TITLE
Compile error with multiple use of same name in Enum, static function and global function

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4577]
### Description

Extracted from Zu's project, which throws a compile error in the latest Feb beta. Attempt to run enclosed project, see compile error
[staticnameproblem.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14115158/staticnameproblem.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by cameron-home** [comment]
Verified in IDE v2024.200.0.483  Runtime v2024.200.0.499
