### ISSUE TITLE
`layer_background_index()` function behaves differently on Windows and HTML5 

### ISSUE THREAD

**Issue by willowitzy** [YoYoGames/GameMaker-Bugs#4580]
### Description
Here to report an issue related to the `layer_background_index()` native function. Apparently, this function behaves differently in the Windows target compared to the HTML5 target, and this inconsistency has led to unpredictable behavior, particularly in HTML5.

In my current project, the `layer_background_index()` function does not work as expected in the HTML5 target, despite functioning correctly in the Windows target.

Upon further investigation, I discovered that when drawing the background's index to the screen using `layer_background_get_index()`, the returned value appears to be a floating-point number ranging from 0 to (total number of frames - 1). For example, if a sprite has 2 frames, the index starts from 0 and increments until it reaches 1. Afterwards, at least in the Windows target, it wraps back to 0.

However, in the HTML5 target, the number continues to increment indefinitely, only resetting to 0 when explicitly forced, such as using `layer_background_index()`. This behavior can be tested by adjusting the `image_speed` of the background image in the project (e.g., setting it to 1 instead of 0) in the sprite editor.

The problem lies when the background's `image_speed` is 0, at least in my current project.

When I create a project from scratch and try to recreate the issue, I'm never able to. I've also attached a minimum project that succesfully works in both Windows and HTML5, though I have no idea why. I'm providing it here because I think it could help to compare both projects to check what works in one that doesn't work on the other.

Which is why I chose to get my original project and shrink it down to a few objects and sprites, as it's the one where `layer_background_index()` doesn't work. This indicates the problem is unique to my project's specificities, I believe. I can't even start to imagine why, as I haven't dive into the runtime's code. Maybe it's more of a back end of it or how the `.yyp` maps asset files?

### Steps To Reproduce
Check the project file I used to submit this issue. Execute the game in the html5 target, press "space" and notice how the background index doesn't change. Now, execute the game in the Windows target and notice that it does indeed work.

[49cabd57-27d1-4826-bad4-9300771aff17](https://api.gamemaker.io/api/github/downloads/49cabd57-27d1-4826-bad4-9300771aff17)

**Comment by willowitzy** [comment]
Ty!!

**Comment by Emc1923** [comment]
Verified done, closing.
