### ISSUE TITLE
Missing info on pr_trianglefan in docs

### ISSUE THREAD

**Issue by Appsurdgames** [YoYoGames/GameMaker-Bugs#4586]
### Description

On the manuel page about [`draw_primitive_begin`](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FPrimitives%2Fdraw_primitive_begin.htm&rhsearch=draw_primitive_begin&rhhlterm=draw_primitive_begin), the constant `pr_trianglefan` is mentioned in the table, but the corresponding picture doesn't show what it does.

On the manual page about [`vertex_submit`](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FPrimitives%2Fvertex_submit.htm&rhsearch=vertex_submit&rhhlterm=vertex_submit), the constant `pr_trianglefan` is again not shown in the picture, but it is also missing in the table.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FPrimitives%2Fdraw_primitive_begin.htm&rhsearch=pr_trianglefan&ux=search

**Comment by ParodyKnaveBob** [comment]
Also, `draw_primitive_begin` lists the limitations of Windows, Xbox, and HTML5, but `vertex_submit` and [`draw_primitive_begin_texture`](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FPrimitives%2Fdraw_primitive_begin_texture.htm) don't. The manual ought to mention the same limits -- or the difference if there is one -- on the corresponding pages.

**Comment by attic-stuff** [comment]
triangle fans look like triangle strips but each triangle share the first vertex vertex. but trianglefans are a pretty unsupported primitive type all over the place—if gm gets a full implementation of webgpu for gmrt then there wont even be a trianglefan option cause its not in the spec at all. if i were gm i would update the manual to suggest those people looking to make a fan get comfy with a strip or list instead

**Comment by YYBartT** [comment]
Added an example of `pr_trianglefan` to the picture. Also added a warning note to `pr_trianglefan` in the Primitive Type Constant table to mention that it may not be supported on some platforms as well as a note on the `vertex_submit` and `vertex_submit_ext` pages to explain that these functions will convert the data in the vertex buffer if the submit is done using the `pr_trianglefan` primitive type (i.e. `vertex_submit(vb, pr_trianglefan, tex)`).
