### ISSUE TITLE
implement an int32() function, pretty please

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#4590]
### Is your feature request related to a problem?

not a particularly pressing problem—as it were—but it is a bit of a tragedy that we can waltz around shifting bits here and there but don't receive the benefit of using smaller numbers when it concerns the footprint of our games' memory use.

for example if you are implementing nodes for custom pathfinding, its cheaper and faster to cast the position and weight of that node into a single integer rather than using a struct or object for each node. but! when you mask out a 16bit or 32bit number they are still 64bit values, and it would be nice if we could magic-missile an int32() on those nodes.

as it stands now, the only way to keep those values as int32 rather than int64 is to stuff them into a buffer, but peeking and poking around a the place is not as convenient as an array, which has all the fun accommodations for filtering and sorting and whatnot. and also once you pull a 32bit value out of a buffer it becomes a 64bit value.

### Describe the solution you'd like

i would like to see an int32() function to cast a 64 bit value down to a 32 bit value. (it would not be the end of the world to have an int16() function either, truth be told)

### Describe alternatives you've considered

there is not an alternative right now, as all non-built-in values are 64bit doubles if i recall.

**Comment by rwkay** [comment]
All variables take up 16 bytes of memory on the current runtime of GM no matter what the type is that is stored in there... introducing an `int32()` function would do nothing for memory size.

**Comment by stuckie** [comment]
Closing as above
