### ISSUE TITLE
In-Game: Calling audio_start_recording with no attached input devices will crash the game

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#4591]
### Description

As in the title, calling `audio_start_recording(0)` with no available input devices will crash the game.

### Expected Change

The function should return -1.

### Steps To Reproduce

1. Disable/Disconnect all audio input devices. On Windows, you can do this in Control Panel -> Hardware and Sound -> Manage audio devices -> Recording -> Right-click a device -> Disable.
2. Open and run the attached example project: [ghb-4591.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14129987/ghb-4591.zip)
3. If input devices can still be seen, the game will flag this. Close the game and begin from step 1 again.
4. Press space to attempt to record.
5. Observe that the game crashes.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.200.0.475 Beta Runtime v2024.200.0.490

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.483  Runtime v2024.200.0.499
