### ISSUE TITLE
Potential Functions and Linear Functions with tile collision support

### ISSUE THREAD

**Issue by lordcyber12** [YoYoGames/GameMaker-Bugs#4592]
### Is your feature request related to a problem?

Potential and linear functions are good functions for AI motion in certain scenario , but they depend with solid objects that in high quantity , can leave a reasonable FPS drops, and don't have support to consider tile collision.

### Describe the solution you'd like

If potential/linear functions already used somehow place_meeting() or instance_place_meeting() in "their codes", and these functions already have support to tile collisions , my guess that some internal tweaks can implement this feature.

### Describe alternatives you've considered

My initial solution was ,from HTML5 open sourced version, pick the potential/linear source codes , and adapt it as functions created in GML code. That means too adapt the helper functions TestFree() and TryDir() . And change the part "place_meeting()" / "instance_place" with a piece of code that perform tile collisions.
But I don't know if a built-in function will perform better than my handcrafted functions.

**Comment by stuckie** [comment]
We have no plans to implement this at this time.
