### ISSUE TITLE
Local Package Integration: Imported room assets have their instance variables reset to defaults

### ISSUE THREAD

**Issue by lordcyber12** [YoYoGames/GameMaker-Bugs#4593]
### Description

The problem occur when I change a object variable (let's call "test") from a instance inside of a room, and create a local package with this room asset , and import in another project (or reimport in the same project) . If check the same instance in the room , his variable "test" is reset to 0 (his default value).
[bugFile.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14131891/bugFile.zip)

### Expected Change

I expected that "object variables" values shouldn't be reset when import from a local package

### Steps To Reproduce

1. Start GameMaker
2. Create an object oA
3. Set at variable definition , a variable called "test"
4. Place oA at Room1, and change variable "test" to any value (100, 200 or anything)
5. Create a local package containing Room1
6. rename Room1 to Room2
7. import local package , and import room asset Room1
8. check the value of variable "test" you can see that is reset to 0

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.498  Runtime v2024.200.0.515
