### ISSUE TITLE
Potential Request for Tilemap Compression (Related to new Beta)

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4594]
### Is your feature request related to a problem?

I read in the change log for the milestone that tilemap data is getting compressed.

During production at least I need the old format (which was run-length encoded) because I programmed some external tools to help me with auto-tiling and other things.

Since I can't load my main project in the beta right now, I made a test project but from what I could gather, the compressed tilemap data is still the run-length encoded format that it used to be.

I am writing this in case there is a different compression that GameMaker might switch to at a certain file size threshold or something.

If that is the case please make it an optional setting so during my productions I can keep using external tools to help me with decorating levels and such.

If I misread, please disregard this if the compression didn't change from what it used to be.

### Describe the solution you'd like

Add an option to the project settings to save tilemap data the way it used to be.

**Comment by stuckie** [comment]
If you are meaning the .YY format, it is still the same RLE as we introduced a few months ago. This has not changed.
