### ISSUE TITLE
Cannot upgrade project from IDE 2024.200.0.478 to 2024.200.0.479+

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4597]
### Description
The project can open in IDE 2024.200.0.478 but failed to load in 2024.200.0.479 or 2024.200.0.480.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.478 Runtime v2024.200.0.493

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[68e05066-b9dc-46d5-8625-69771bcfd2a3](https://api.gamemaker.io/api/github/downloads/68e05066-b9dc-46d5-8625-69771bcfd2a3)

**Comment by shichen85** [comment]
When updating the project from its IDE 2023.11.1.129 format to 2024.200.0.480, the failure message is:

Project Load Error:
*.yyp(2,3): GMSC Error: File parsing failed: Type tag missing when parsing slot of type YoYoStudio.Resources.ResourceBase

**Comment by stuckie** [comment]
I am pretty sure this will be fixed in IDE 481/ Runtime 496

**Comment by shichen85** [comment]
Indeed. Closing the thread.

**Comment by stuckie** [comment]
Woohoo, thanks for confirming quickly!
