### ISSUE TITLE
Using collision_line() with Tilemap collision fails to detect collision at the edges of mirrored/flipped tiles

### ISSUE THREAD

**Issue by vermillion-nera** [YoYoGames/GameMaker-Bugs#4613]
### Description
When trying to use collision_line() as the foundation for my project's collision system, I tried to save time while creating the level geometry by creating one version of the ramps that I could flip and mirror to give me any other orientation of ramp I needed. However, while testing out running over those tiles, I noticed that the floor detection kept phasing through the ramps but only while running over ramps that had been mirrored before being placed down. I created a second set of ramp tiles that were mirrored in the sprite itself rather than in the Room Editor, and placed those down and found that the issue was solved. I've created the attached project here to reproduce the issue and it's remained consistent. Hopefully it helps you diagnose the issue.

### Steps To Reproduce
- Create a Tilemap layer in a room and place some flipped/mirrored tiles down
- Attempt to use collision_line() with a line that goes vertically or horizontally through the edges of any of the flipped/mirrored tiles

[34b43f45-44cd-4d19-869c-6ef0601bb3df](https://api.gamemaker.io/api/github/downloads/34b43f45-44cd-4d19-869c-6ef0601bb3df)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
