### ISSUE TITLE
Sprites loaded using sprite_add_ext() cause the game to hard crash if sprite_collision_mask() is used on the loaded sprite.

### ISSUE THREAD

**Issue by IndianaBones** [YoYoGames/GameMaker-Bugs#4614]
### Description

 The game/runner hard crashes when attempting to call sprite_collision_mask(_c_sprite, true, 0, 0, 0,0,0,bboxkind_precise, 128) where _c_sprite is a sprite that was loaded using sprite_add_ext()

"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.1.160/windows/x64/Runner.exe exited with non-zero status (-1073741819)"

The issue happens whether or not I use sprite_collision_mask() immediately in the Async Load event or later during a normal step event.

Note: I previously logged this in the helpdesk system on August 23rd, 2023, when I was using version (2023.6.0.89). Here is the link for reference : http://help.yoyogames.com/hc/requests/211741

I have searched the github bug lists for open and closed cases of this issue but have not been able to find any reference to it.

I would like an update on the progress of this issue please.

### Steps To Reproduce

1. Start GameMaker
2. Run game
3. load a sprite using sprite_add_ext()
4. try to use sprite_collision_mask() on the sprite that was loaded in step 3
5. See the issue - runner hard crashes "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.1.160/windows/x64/Runner.exe exited with non-zero status (-1073741819)"
[contactUsPackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14155332/contactUsPackage.zip)
[SpriteErrorExt-ExampleProject.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14155341/SpriteErrorExt-ExampleProject.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yymrennie** [comment]
Fixed in 2024.4

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.534  Runtime v2024.400.0.553. 

Thank you.
