### ISSUE TITLE
Paths added through code are closed by default, leading to confusion

### ISSUE THREAD

**Issue by bartteunis** [YoYoGames/GameMaker-Bugs#4616]
### Description

The same [path](https://manual.gamemaker.io/monthly/en/Setting_Up_And_Version_Information/IDE_Preferences/General/Paths.htm) added in the IDE and in code turns out different in-game (both when getting points on it using the functions `path_get_x` & `path_get_y` and when drawing it using `draw_path`).
After a bit of testing, it turns out this is caused by a different default setting of the path's "closed" parameter ([path_get_closed](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Paths/path_get_closed.htm)).

For example, the following path created in the Path Editor is drawn as expected: 

![afbeelding](https://github.com/YoYoGames/GameMaker-Bugs/assets/24955219/109bac18-5fd5-464a-91cf-a4051114733c)

The exact same path defined in GML doesn't draw as expected: 

```gml
pth_2 = path_add();
path_set_kind(pth_2, 1);           // Smooth
// path_set_closed(pth_2, false);  // Uncomment this line to fix the issue
path_add_point(pth_2, 0, 0, 0);
path_add_point(pth_2, 96, 0, 0);
path_add_point(pth_2, 160, -32, 0);
path_add_point(pth_2, 224, -32, 0);
path_add_point(pth_2, 320, -32, 0);
```

A visual comparison: 

![afbeelding](https://github.com/YoYoGames/GameMaker-Bugs/assets/24955219/43d95526-4525-4e5f-95e1-316f223d2b09)

A call to [path_set_closed(path, false)](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Paths/Path_Manipulation/path_set_closed.htm) fixes the issue. It is this value that causes the confusion.
Two things could be changed here: 
- The default "closed" value for paths created in code is changed to `false` (identical to paths created in the IDE)
- The manual pages for [path_get_closed](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Paths/path_get_closed.htm) and [path_set_closed](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Paths/Path_Manipulation/path_set_closed.htm) mention the default value.

### Expected Change

The setting is identical for assets created in IDE and code and the manual mentions the default value

### Steps To Reproduce

1. Start GameMaker
2. Create the same (smooth) path in the Path Editor and in GML
3. Draw the paths and/or get (x, y) positions on them using `path_get_x` and `path_get_y`
4. The paths are different

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, GX.games, HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gurpreetsinghmatharoo** [comment]
Documented that new paths are created closed
