### ISSUE TITLE
video_resume() is broken

### ISSUE THREAD

**Issue by Mattie19** [YoYoGames/GameMaker-Bugs#4634]
### Which Extension are you reporting this issue for?

App Tracking Transparency

### Description

The video_resume() function seems currently broken. It doesn't resume after the video has been paused, and pauses the video when it's still running. It seems to behave exactly like video_pause(). 

zip: https://we.tl/t-gQAHZItgBg

There is also a typo in the manual. The code says status instead of _status.  https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/Videos/video_resume.htm

### Steps To Reproduce

var _status = video_get_status();

if (keyboard_check_pressed(vk_space))
{
    if (_status == video_status_playing)
    {
        video_pause();
    }
    else if (_status == video_status_paused)
    {
        video_resume();
    }
}

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Hi @Mattie19 your project works fine for me here, the selected video pauses and resumes as you press the spacebar, can you give more details as to your setup and what is failing for you? 

Thanks,
Fritz
