### ISSUE TITLE
Feather: mp_potential_step_object() gives unexpected GM1041 error if you use an object asset as fourth arg

### ISSUE THREAD

**Issue by EncodedNovus** [YoYoGames/GameMaker-Bugs#4649]
### Description

`Version(latest): ide: 2023.11.1.129; runtime: 2023.11.1.160`

Feather hasn't been updated to include object assets as a possible parameter for mp_potential_step_object(x,y,speed,object). At the moment it's asking for an instance ID, but the GameMaker Manual states you can use an object asset. The function will still run correctly, but feather will underline the object asset with a red underline & you will get this error in the debug log:

`Error: "E GM1041 The type 'Asset.GMObject' appears where the type 'Id.Instance' is expected. obj_enemy : Step 29:65"`

The object I'm checking for is a parent object for solid checking.
Example project:
[feather_mp_potential_step_object.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14187148/feather_mp_potential_step_object.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. Open a new script
4. type: mp_potential_step_object(x,y,speed,"your object's name");
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed as of Beta IDE v2024.400.0.532 Runtime v2024.400.0.551
