### ISSUE TITLE
Sequence Editor: Dragging sound into track panel while using specific project causes fatal error

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#4654]
### Description

When using [yys-9302.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14193438/yys-9302.zip) and dragging the sound into the Sequence Editor, the IDE crashes and the ui log shows a break in fatal error warning.

This doesn't happen when following steps with a new blank project or Windy Woods template.

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14193443/ui.log)

IDE v2024.200.0.486  Runtime v2024.200.0.502

### Steps To Reproduce

1. Start GameMaker and import attached project.
2. Open seq_1 and drag snd_1 over to the track panel.
3. See crash.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
This looks to be a project that was used for the Audio Parameter tracks before it got merged in to 2024.02.0-main, would that be correct?

If so, there shouldn't be any user-facing projects where this will be a problem, as this format did not go out - this is NOV-23 + Audio Parameters, which only existed on a feature build.

**Comment by caitlinrmcintyre** [comment]
@stuckie yes that's correct

**Comment by stuckie** [comment]
Closing as above; project was for verifying against in-development work.
