### ISSUE TITLE
Steam: "GameMaker" product now shows Steam's overlay when pressing Shift+Tab inside GameMaker

### ISSUE THREAD

**Issue by WangleLine** [YoYoGames/GameMaker-Bugs#4655]
### Description

A few weeks ago, GameMaker was moved to a new application (depot?) on Steam to accommodate some changes in the updated license. Since then, the IDE opens up the steam overlay whenever I try to reduce tabs in the code editor via shift+tab. The previous steam IDE had the steam overlay disabled, I believe.

### Steps To Reproduce

1. Start GameMaker on steam using new IDE branch/depot/application
2. Press shift+tab
[pack.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14194991/pack.zip)

3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by iampremo** [comment]
Looks like this is an issue on Steams side, all software applications should have the overlay disabled by default but it seems that this is no longer the case and publishers can no longer disable, I've sent them a message about it but in the mean time you should be able to disable it for yourself within the settings for GM

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16644676/bb38bfb8-6d36-4618-8969-e9ef1c15f0ea)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16644676/b2609249-c53e-496f-a78b-e1f35cba0dae)

**Comment by WangleLine** [comment]
Oh shoot! Thank you so much, I wasn't aware steam had a per-app setting for the overlay - Thought there was only a toggle for all games & apps as a whole.

Cheers

**Comment by stuckie** [comment]
This is a Steam client issue.

**Comment by YYDan** [comment]
Verifying per the above comment (which came after communications from Steam themselves directly).
