### ISSUE TITLE
Room Editor: Minor UI draw issue where the View Rectangle isn't draw in the right place.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4659]
### Description
Sometimes, when opening the Room Editor for a room that has viewport(s) defined, the white View Rectangle that is drawn isn't initially positioned correctly and is actually draw mostly off-screen.  This is a minor issue as the smallest action taken by the user (such as panning the room with the mouse) will cause the view rectangle to be drawn where it's supposed to be from that point on (until the room editor is closed and re-opened again, that is.)

### Steps To Reproduce
1) Open the attached project.
2) Double click on Room1 to open the room editor for that room.
3) Note that the position of the white view rectangle covers the entire room and is positioned on the top-left corner of the room.
4) Double click on Room2 to open the room editor.
5) Note that the position of the view rectangle for this room is off-screen in the upper-left corner of the room editor. This needs to be fixed.

[62732e2d-b4f8-4511-8ac2-313494f6a47c](https://api.gamemaker.io/api/github/downloads/62732e2d-b4f8-4511-8ac2-313494f6a47c)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.523  Runtime v2024.400.0.544, thanks.
