### ISSUE TITLE
Asset Browser: Opening any project following a project load failure will cause additional asset browsers to be shown

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#4668]
### Description

Opening any project following a project load failure will cause a second asset browser to be shown

https://github.com/YoYoGames/YoYoStudio/assets/48513045/04a284ce-cb02-467b-8fca-f49b809449a2

A s

### Steps To Reproduce

1. Start GameMaker
2. First open the survival game template (it should fail - though this may get fixed before this issue is addressed)
3. then this: https://drive.google.com/file/d/1QJ81A3m_Kqhkw0kawrwEEUtHKpiWhQ-e/view?usp=drive_link

### How reliably can you recreate this issue using your steps above?

None

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.200.0.480  Runtime v2024.200.0.495

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by Emc1923** [comment]
Issue still presents as of Beta IDE v2024.400.0.532 Beta Runtime v2024.400.0.551

**Comment by stuckie** [comment]
The layout was still trying to open before the project had successfully ( or unsuccessfully, in this case ) loaded.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.600.0.579  Runtime v2024.600.0.605, thanks.
