### ISSUE TITLE
Cannot run windows YYC while VM succeeds

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4671]
### Description
The attached project can run for Windows VM, but when YYC export would fail during building with error LNK2001: unresolved external symbol

### Steps To Reproduce
1. Select the "dev" config
2. Build for YYC Windows export, see the building failure 
3. Build for VM export, see no problem

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.487 Runtime v2024.200.0.503

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[3af12cf4-7dd9-45c6-8906-a4a4a80d17da](https://api.gamemaker.io/api/github/downloads/3af12cf4-7dd9-45c6-8906-a4a4a80d17da)

**Comment by shichen85** [comment]
This is related to #4672. I have replicated with a small sample that fails YYC windows compile with the same error. However, I did not get the compile error as #4672 did. Maybe it is because he is on v2024.200.0.502 and I am on v2024.200.0.503?
[Script_function_cross_naming.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14217389/Script_function_cross_naming.zip)

**Comment by rwkay** [comment]
I fixed this earlier today with the commit https://github.com/YoYoGames/GameMaker/pull/3567 that resolves the script vs global script precedence problem (which this is an example of) - so this appears to be fixed in 2024.2

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.200.0.492  Runtime v2024.200.0.508 - projects compile and run
