### ISSUE TITLE
Chained accessor for ds_map throws error in YYC

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4674]
### Description
When accessing a value in a ds_map, using ds_map_find_value() succeeds but using the accessor notation throws an error:

ds_map_find_value argument 1 incorrect type (array) expecting a Number (YYGI32)

Please use the attached project as it is a different version from my previous issues.

### Steps To Reproduce
1. Select the config gamepipe_test_dev
2. Run the project in Windows YYC
3. Notice the error

Line 476 uses ds_map_find_value() and does not throw an error.
Line 478 uses accessor and throws the error.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.487 Runtime v2024.200.0.503

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[4bb99734-2922-4495-93fc-9c3a672b3bd4](https://api.gamemaker.io/api/github/downloads/4bb99734-2922-4495-93fc-9c3a672b3bd4)

**Comment by rwkay** [comment]
I have created a smaller sample to work with - 
[BUG-4674.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14222071/BUG-4674.zip)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.494  Runtime v2024.200.0.511
