### ISSUE TITLE
precision lost early when creating a large bitfield from constant values

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#4680]
### Description

before describing the bug i would just like to meander a smidge and explain that i understand why precision is lost when it is, thanks russell!, but and however there is still something silly going on here and i was asked to file a buggin' about it.

when creating a large bitfield by adding together constant values, precision is lost if you use bits 54 through 62. when adding together values stored in variables, the precision is not lost regardless of which bits you are shoving around.

this only happens when dealing with those specific bits. when creating a bitfield with 63 bits it does not loose precision at all, but creating a bitfield with 54 bits to 62 bits does. this also only happens with a vm build to windows, not yyc.

there is a project attached here where you can see it in action, with instructions for how to run the tests: compile the project in vm and look at the output, you will see that creating the identity bitfield from 63 bits is successful using stored values and constant values. comment the **working** script out. then uncomment the **notworking** script, and run it. creating an identity mask from 62 bits fails when using constant values. fun!

you can then comment out the notworking script, uncomment the **workingagain** script, and see that an identity bitfield with 54 bits begins working again. then if you comment that one out and uncomment **shouldntworkbutdoes** and run it, you will see that for some reason there are situations where the precision is not lost on a 62 bit identity bitfield?

good luck with this one homies: [pact up.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14223938/pact.up.zip)

### Steps To Reproduce

1. Start GameMaker
2. not smart enough to explain this part
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
OK there is no fix required here it works just as I said on the Discord you need to ensure that everything is int64 so if you modified the code like this it will work.

```
#macro shift_a	0
#macro shift_b	1
#macro shift_c	2
#macro shift_d	3
#macro shift_e	4
#macro shift_f	5
#macro shift_g	6
#macro shift_h	7
#macro shift_i	11
#macro shift_j	17
#macro shift_k	23
#macro shift_l	28
#macro shift_m	29
#macro shift_n	30
#macro shift_o	33
#macro shift_p	43
#macro shift_q	53

#macro L1		int64(1)
#macro L7		int64(7)
#macro L15		int64(15)
#macro L31		int64(31)
#macro L63		int64(63)
#macro L511		int64(511)
#macro L1023	        int64(1023)

#macro identity 0b0011111111111111111111111111111111111111111111111111111111111111

function pack_constant() {
	return (L1 << shift_a) + (L1 << shift_b) + (L1 << shift_c) + (L1 << shift_d) + (L1 << shift_e) + 
			(L1 << shift_f) + (L1 << shift_g) + (L15 << shift_h) + (L63 << shift_i) + (L63 << shift_j) + 
			(L31 << shift_k)  + (L1 << shift_l) + (L1 << shift_m) + (L7 << shift_n) + (L1023 << shift_o) + 
			(L1023 << shift_p) + (L511 << shift_q);
}

show_debug_message($"constant: {identity == pack_constant() == true ? "true" : "false"}");

```

**Comment by mgeddesGM** [comment]
verified as per above comments
