### ISSUE TITLE
HTML5 texture page size

### ISSUE THREAD

**Issue by nicolaigd** [YoYoGames/GameMaker-Bugs#4685]
### Description

Texture pages take up a lot more space in recent versions of GameMaker in the HTML5 export. It might be that it's missing a compression step after packing the textures, or that it's otherwise less efficient in how it stores the data than previously.

If I build with the newest runtime (v2023.11.1.160) I get a texture of 2.54 MB.

If I build with runtime v2023.6.0.139 that same texture page is only 270 KB.

This is really significant, as most browser game hosts have requirements for keeping game sizes small, usually <8 MB, which is almost impossible to hit with the texture sizes of the newest runtimes. Using thirdparty tools to losslessly compress the texture pages makes the texture sizes similar to what they used to be. The problem seems to be less apparent for other export targets, although I haven't tested that much.

[contactuspackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14229108/contactuspackage.zip)

### Expected Change

Add lossless compression to texture pages (for HTML5)

### Steps To Reproduce

1. Start GameMaker in runtime 2023.6.0.139
2. Export to HTML5 and unzip to check the texture size
3. Switch to any later runtime, like v2023.11.1.160
4. Export to HTML5 and unzip again
5. Compare texture sizes between the two builds

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

HTML5

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by nicolaigd** [comment]
Sure, I have made a test project for you now, but it happens in any project AFAIK. Here is the new issue I created: https://github.com/YoYoGames/GameMaker-Bugs/issues/4695

I will close this issue and you can take care of the new one instead. Thank you.
