### ISSUE TITLE
Error messages when trying to access the private static variables in an instance method could be more helpful

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4686]
### Is your feature request related to a problem?

When trying to access a private member in a struct  (like the static variables in an instance method) via a dot accessor, it just gives the standard "variable not set before reading" message which is neither accurate nor helpful to understand the issue. 

Same with the fact that static_get on an instance method returns an seemingly empty struct is confusing before realizing it's full of private variables not showing).

### Describe the solution you'd like

When used with an instance method, static_get should return undefined or give a more specific error message.
Using a dot accessor to read or write a private member should explicitly state reading private members not allowed.
Doing both would improve accessibility and usability of methods and statics which can often be confusing at first to use.

### Additional context

Linked to issue https://github.com/YoYoGames/GameMaker-Bugs/issues/4687

**Comment by rwkay** [comment]
`static_get` gives you access to the static chain, any struct can have a static struct each of those may have a static as well so to iterate over all the static structs you need to keep calling `static_get` until you get `undefined` as a return.

So to get access to all the properties on a struct (including the static values you need to iterate through them all)

```
var curr = _struct;
while( curr != undefined )
{
   show_debug_message( curr );
   curr = static_get( curr );
}
```

**Comment by patchuby** [comment]
Ah thanks for the clarification, super helpful, hope this information gets added to the manual in some form
