### ISSUE TITLE
Resource optimization - a new method of programming on GM

### ISSUE THREAD

**Issue by NLisicyn** [YoYoGames/GameMaker-Bugs#4691]
### Is your feature request related to a problem?

There is a major problem in Game Maker Studio that forces developers to go to the tricks associated with total code optimization. This is due to the presence of situationally unnecessary variables and functions in the background. Objects themselves have too many variables that often remain unused, which is why people have to write their own systems for storing and processing game data

In addition to simple game optimization, this development method will help developers write game servers directly in the IDE itself, without using third-party programming languages, since the load on the device will noticeably decrease

In addition, it will be more convenient for developers to write their own development tools and even entire programs.

### Describe the solution you'd like

This problem can be solved in the following way: before starting work on a new project, the user is asked if he wants to use the standard GM template (all global variables and functions are already built into the project) or a clean template, where the user will have to call the necessary functions and libraries as needed, and the developer must declare and process all object variables on your own

**Comment by stuckie** [comment]
This is not planned with the current runtime.
