### ISSUE TITLE
F4 Snippets context menu highlight acting weird.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4692]
### Description
After hitting F4 to bring up the snippets context menu, and then using the up/down cursor keys to try to select one, we find that there is an issue with the currently selected highlighted snippet menu item.  It seems that there are 2 independently active menu items, instead of one.  Furthermore, the down cursor key will move one of the highlighted items while the up cursor key will move the other, until both highlighted items eventually meet each other.  When that happens, they will begin travelling together in the same direction, one following the other a step behind.  This can affect which snippet is ultimately selected when the enter key is hit. See attached video for a demonstration.

### Steps To Reproduce
1) Move the mouse cursor to a line in your script and click to position caret. Leave mouse where it is.
2) Hit F4.
3) Hit Up Arrow a couple of times.  Note the selected menu item moving.
4) Hit the Down Arrow a couple of times. Note ANOTHER selected menu item moving instead of the first.

There should not be 2 highlighted menu items.

[4019bc5b-fd50-48ef-a08e-52eac166a11b](https://api.gamemaker.io/api/github/downloads/4019bc5b-fd50-48ef-a08e-52eac166a11b)

**Comment by SmithTom6304** [comment]
Fixed - we weren't handling the case where a menu entry is already highlighted when the menu is first opened.
Cursor key navigation should now work as follows:
- If an entry is highlighted when the menu is first opened, up/down navigation should begin from this position
- If an entry is not highlighted, pressing `Down` should initially highlight the first entry (as before). Pressing `Up` should now highlight the _last_ entry.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.521  Runtime v2024.400.0.540
