### ISSUE TITLE
Hitbox disappearance issue after adding animation with sprite_add function runtime 2023.8.2.152

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#4696]
### Description

After update runtime from 2.3.5.458 to 2023.8.2.152, the collision mask of the spine animation was broken, before that i am converting animation from spine v.2 to spine v.4. After adding a sprite using the sprite_add function, hitboxes disappear in the animation. But when adding animation to the project assets, everything works correctly.

Example project: [Collision_bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14237495/Collision_bug.zip)
[collision.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14237634/collision.zip)

### Expected Change

To ensure that the hitbox does not disappear when loading Spine animation via sprite_add, so everything works as when adding animation to assets

### Steps To Reproduce

1. Start GameMaker
2. Add animation in datafiles
3. Load animation with **sprite_add**
4. Draw bbox
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which platform(s) are you seeing the problem on?

Windows, Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yevhenii-sir** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/36339434/f1b20fd2-5731-4903-acf6-782811a3e722)

**Comment by stuckie** [comment]
There have been many fixes since that version to now as well.
Please try in an updated version and resubmit if you still think there is a problem.
