### ISSUE TITLE
Manual Integration: Pressing F1 to open the Manual does not work when selecting nodes via the GmlVisual "Node Stories" menu

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#4697]
### Description

In GmlVisual, pressing F1 does not open the Manual if the nodes have been selected via the left-hand-side "node stories" menu. If nodes are selected in the pan area, F1 works as expected.

[Contact us package](https://github.com/YoYoGames/GameMaker-Bugs/files/14238159/F1ManualNodeStories.zip)

### Expected Change

F1 should open the manual page for all nodes selected via the left-side menu.

### Steps To Reproduce

1. Open or create a project
2. Open or create a GMLVisual script with a node
3. Select the node in the left-side "Node stories" menu
4. Press F1
5. Observe nothing happens
6. Select the node in the pan-area instead
7. Press F1
8. Observe the manual page opens as expected

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), 2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This will require a fix that will require testing of various input gadgets, so going to target this for 2024.04

**Comment by SmithTom6304** [comment]
Shortcut was being ignored for this specific gadget, due to a hack determining how input gadgets interfered with text entry. I've added a proper fix for this now, with a property which gives these gadgets a bit more control over how they handle this.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.525  Runtime v2024.400.0.546
