### ISSUE TITLE
When importing new sprites via drag/drop, the assets are no longer created in the selected folder, but added to the root

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4701]
### Description
When creating assets any other way, for example, via short cuts, they get created within the folder or group you currently have selected. The same used to be true for dragging/dropping strip PNGs from outside into the IDE. Since a few versions they get put into the root folder. This introduces a bunch of unnecessary friction because you have to select them, use the mousewheel to scroll to the right folder and drop them in there again.

### Steps To Reproduce
1. Select a folder you want to add new sprites to
2. Select a strip file from the desktop or a folder and drag them into the IDE
3. The new sprite gets created but added to the bottom of the resource tree in the root.

[b5cecb2b-9625-4d9e-a401-c5cc57cfe314](https://api.gamemaker.io/api/github/downloads/b5cecb2b-9625-4d9e-a401-c5cc57cfe314)

**Comment by yyalansavage** [comment]
Dragging to IDE workspace should now drop into selected folder in asset browser (note you can also drag and drop directly onto the desired folder location in asset browser, this is unchanged)

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.519  Runtime v2024.400.0.540
