### ISSUE TITLE
Building Projects: Create Executable and Launch creates installers but does not launch them

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#4704]
### Description

When creating and launching an executable and selecting 'Package as Installer', the installer is packaged but the executable is not launched. This occurs for both VM and YYC. When selecting 'Package as Zip', the executable is launched as expected.

If the user manually launches the packaged installer, everything works as expected; the issue shown is that 'Create Executable and Launch' is behaving identically to 'Create Executable' when 'Package as Installer' is selected.

This issue was found using IDE v2024.200.0.493  Runtime v2024.200.0.509.

[Create and Launch.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14261258/Create.and.Launch.zip)

### Expected Change

It is expected that the created executable will launch automatically when using 'Create Executable and Launch'

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Press 'Create Executable and Launch' icon
4. Select 'Package as Installer'
5. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by cameron-home** [comment]
Closing as this sounds like it is not an issue.

**Comment by yoyo-danielc** [comment]
Fixed on 2024.06 branch.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.557  Runtime v2024.600.0.572
