### ISSUE TITLE
Manual Content: Build Menu page should specify that 'Create Executable and Launch' will not launch executables packaged as installers

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#4706]
### Description

The Build Menu manual page's section on 'Create Executable and Launch' should specify that if executables are packaged as installers, the installer will be created but the executable will not be launched. It should be specified that using 'Create Executable and Launch' is the same as using 'Create Executable' when specifically selecting 'Package as Installer'.

It is suggested that the section could be rephrased to something like this:
"This will create an executable, just like the option above, and if it's a suitable package format that the game can be run without an installer to follow first, it will launch the game automatically on the target platform. This command is the same as pressing the Create Executable and Launch button in the IDE. If there is an installer to follow first, the game will not launch automatically and the command will be the same as pressing the Create Executable button in the IDE."

### Manual Link

https://manual.gamemaker.io/beta/en/IDE_Navigation/Menus/The_Build_Menu.htm

**Comment by stuckie** [comment]
We will change it so that the Windows installer is invoked.
