### ISSUE TITLE
Room Editor: Layer label remains in previous language after changing IDE language in preferences until clicking off layer

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#4707]
### Description

When in one of the layers in the Room Editor and going into preferences to change IDE language (from Russian to Spanish for example), I noticed that the layer label in the inspector was the only bit of text that didn't automatically change language and remained in Russian. When clicking onto another layer the label finally changed to Spanish.

![Screenshot 2024-02-13 145152](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/218661e9-17da-4012-b3d6-f05ad17bf921)

[language_check.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14268273/language_check.zip)

### Expected Change

Changing IDE language should automatically update everything

### Steps To Reproduce

1. Start GameMaker and import attached project/create new project.
2. Go to Room Editor and click on a layer (eg. Background).
3. Go into Preferences and change IDE language to any other language.
4. See that it doesn't update the label as shown in screenshot.
5. Click onto another layer (eg. Instances) and see that the text updates to new IDE language.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly), 2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Note: This issue affects all inspector assets. E.g.: 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/86ba96d8-9875-4d5b-ab18-786398e90e36)

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.526  Runtime v2024.400.0.547
