### ISSUE TITLE
if `event_perform(ev_draw,[...])` is called with no draw event, `draw_self()` 

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4709]
### Is your feature request related to a problem?

I have a few scripts for visual effects which rely on referencing how different instances are drawn, and the most reliable way I've found to ensure that they're drawn accurately is to use `event_perform()` to call their draw events. However, if an object _doesn't_ contain a draw event (that is, it draws its own sprite normally, similar to `draw_self()`), then this will do nothing rather than drawing its sprite.

### Describe the solution you'd like

Calling `event_perform()` using `ev_draw`, should, in my opinion, still draw the corresponding object/instance if there isn't a draw event. To me this is intuitive, since this is basically how the event works - no event means `draw_self()`, and you can override this by creating a blank event.

Other potential solutions could be a separate function for "drawing" an object based on this information, or the ability to check whether or not an event exists (`event_exists()` and `event_exists_object()` maybe?)

### Describe alternatives you've considered

My current workaround is ensuring that anything that MIGHT be affected by these scripts already contains a draw event (with `draw_self()` at minimum). However, this is another thing that I have to remember to do each time.

**Comment by rwkay** [comment]
This would not be possible as there are many other things that have to be setup for drawing to happen (i.e. viewports, matrices and other parts of the setup of GM). The rendering is optimised and not routed through the Event system so in the current runtime this would not be possible.

Even if we only allowed this within the context of another draw_event we would not be in a position to render the default `draw_self()` in a simple way through the event mechanism.

**Comment by backYard321** [comment]
> This would not be possible as there are many other things that have to be setup for drawing to happen (i.e. viewports, matrices and other parts of the setup of GM). The rendering is optimised and not routed through the Event system so in the current runtime this would not be possible.
> 
> Even if we only allowed this within the context of another draw_event we would not be in a position to render the default `draw_self()` in a simple way through the event mechanism.

Interesting, okay! Yeah I remember a previous discussion about how events are handled on the backend, where something changed recently for those. So I'll assume that it's more complicated than I can understand!

Re: one of my alternatives, is checking whether or not an event exists possible? If so, I can put that as a separate request.

**Comment by stuckie** [comment]
Closing as above
