### ISSUE TITLE
Importing: Importing a .yy file from another project can show incorrect "referenced by" dialog on delete

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#4710]
### Description
After importing a .yy file (by dragging onto the workspace) from another project, attempting to delete the new asset can show incorrect "referenced by" dialog (see attached pic)

### Steps To Reproduce
Create a new project A, create a sprite and add it to the room.  Rename the room to eg "Room1_projectA"  (not necessary to repro, but helps to illustrate the issue)
Create another new project B, drag the sprite.yy file from project A onto the workspace.  
Delete the new sprite asset in the asset browser; observe incorrect "referenced by Room1_projectA"  message

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.493 Runtime v2024.200.0.509

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[4363b143-9b8f-43ce-8ed3-47fb6df8dccb](https://api.gamemaker.io/api/github/downloads/4363b143-9b8f-43ce-8ed3-47fb6df8dccb)
![badRef](https://github.com/YoYoGames/GameMaker-Bugs/assets/8818217/2c303728-f3e0-4a21-aaa6-a7345c98060b)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.499  Runtime v2024.200.0.516
