### ISSUE TITLE
Extension GDKExtension file does not exist

### ISSUE THREAD

**Issue by Kev-Brown** [YoYoGames/GameMaker-Bugs#4711]
### Which Extension are you reporting this issue for?

GDK

### Description

Hi,

We are having dififculties making a windows build when the GDKExtentions
is enabled.
We get the following error in the 'Compile Errors' section when we
build.

Error : Extension GDKExtension file does not exist

The game continues to build and then will eventually fail.

I believe we may be getting this issue.
https://github.com/YoYoGames/GameMaker-Bugs/issues/2440. Would there be
any workaround for the version we are using?
IDE v2023.11.1.129 Runtime v2023.11.1.160

I have attached [BuildLogs.txt](https://github.com/YoYoGames/YoYoStudio/files/14259847/BuildLogs.txt)

### Expected Change

A workaround that allows us to stay on v2023.11 instead of updating to v2024.200 (or February build)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
If you double click the extension asset on the IDE you should see this:

BEFORE:
<img width="856" alt="image" src="https://github.com/YoYoGames/YoYoStudio/assets/85873067/c36d9cbb-585e-472f-85a2-3a23676bcd08">

Please change it to become:

AFTER:
<img width="832" alt="image" src="https://github.com/YoYoGames/YoYoStudio/assets/85873067/dd31d7cd-49c0-4759-a362-1f437594a577">

This should solve the problem. This was introduced somewhere around the Nov23 release and is now fixed in the Feb2024 beta.

**Comment by rangerstein24** [comment]
Hi, could you please attach your before- and after pictures once again or better give a short text description - because I cannot watch/open these images ?  Thanks in advance !

**Comment by 1-800-thewolf** [comment]
@DiasFranciscoA 

> BEFORE: <img alt="image" width="856" src="https://github.com/YoYoGames/YoYoStudio/assets/85873067/c36d9cbb-585e-472f-85a2-3a23676bcd08">
> 
> Please change it to become:
> 
> AFTER: <img alt="image" width="832" src="https://github.com/YoYoGames/YoYoStudio/assets/85873067/dd31d7cd-49c0-4759-a362-1f437594a577">

I also can not see these images. They fail to load with a 404 error. Are your images set to be publicly visible?
