### ISSUE TITLE
sprite_collision_mask(), when used with sprite_add(), doesn't use tolerance properly.

### ISSUE THREAD

**Issue by chimericgames** [YoYoGames/GameMaker-Bugs#4714]
### Description

It seems that sprite_collision_mask() isn't working as expected when used with a sprite loaded by sprite_add(). As a result, there is a large "buffer" around the object that can be collided with. Here is an example of code that results in imprecise collision:
```
var spr = sprite_add("testSprite.png", 1, false, false, 0, 0);
sprite_collision_mask(spr, false, 0, 0, 0, sprite_get_width(spr), sprite_get_height(spr), bboxkind_precise, 240);
sprite_index = spr;
```
The tolerance of 240 doesn't seem to be applied with the precise collision. In the case of the attached sprite, there's some glow around the object, so I think what's happening is that some or all of it is colliding. I can confirm that 240 tolerance excludes almost all of the alpha when used in the sprite editor.

Attached is an example sprite for which this method doesn't work.
![testSprite](https://github.com/YoYoGames/GameMaker-Bugs/assets/47785803/2fcdf838-3946-4e2c-8c8e-63ce7b25be14)

Here is a test project that shows the issue:
[PreciseCollisionToleranceTest.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14269345/PreciseCollisionToleranceTest.zip)

Here is my Contact Us package:
[PreciseCollisionToleranceTestReport.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14271060/PreciseCollisionToleranceTestReport.zip)

### Expected Change

Tolerance and precise collisions should work the same in sprite_collision_mask as it works with the sprite editor.

### Steps To Reproduce

1. Start GameMaker.
2. Unzip my attached test project.
3. Run the test project in game maker for windows.
4. Note that the cursor follows your mouse, and draws text displaying whether or not the cursor is colliding with the ship.
5. Observe that the collision for the ship is not precise.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Fix will be in April build
