### ISSUE TITLE
Fatal Error while compiling - bailing detals below

### ISSUE THREAD

**Issue by Shiraga12** [YoYoGames/GameMaker-Bugs#4718]
### Description
Everytime I start a project I already made on the base Gamemaker IDE, it keeps crashing saying the following error, "Fatal Error while compiling - bailing detals below"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.486 Runtime v2024.200.0.502

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[073bbcf8-ca88-4118-bbc4-b53019172894](https://api.gamemaker.io/api/github/downloads/073bbcf8-ca88-4118-bbc4-b53019172894)

**Comment by stuckie** [comment]
If you update it should be fine.
If there is still an issue, please submit a project as well.
