### ISSUE TITLE
Inconsistent Behavior of collision_line()

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#4731]
### Description

Very simply, I'm not seeing 100% consistent behavior with this function. The majority of the time, it works properly, but the exceptions can cause major issues with my game's logic. This is one of the (many) reasons why I'd prefer having a raycast vs. Physics World or a better collision system in general, but it's also a functional issue with GMS that is almost certainly causing problems for other users.

Let's take a typical use case. Here, I have a "guided missile seeker" logic, that needs to:

1. Check for objects of a certain type, within 45 degrees of the missile's current direction.
2. Not select any objects that are blocked by walls and other obstacles.
The logic looks like this:

`	
	var _list = ds_list_create();
	var _num = collision_circle_list(x, y, 300, obj_Enemies, false, true, _list, false);
	if (_num > 0)
	{
	    for (var i = 0; i < _num; ++i;)
	    {		
			var posTarget = ds_list_find_value(_list,i);
			if(!instance_exists(posTarget) or posTarget.myTeam = myTeam){
				ds_list_delete(_list,i);	
				i = max(0,i-1);
				_num--;
			} else {
				var angleToTarget = point_direction(x,y,posTarget.x,posTarget.y);
				var angleDifference = abs(angle_difference(angleToTarget,-phy_rotation));		
				if(angleDifference > 45 or collision_line(x,y,posTarget.x,posTarget.y,obj_Aura_ShadowCaster_Parent,true,true) != noone){
					ds_list_delete(_list,i);	
					i = max(0,i-1);
					_num--;
				}
			}
		}
	    
	}
	if(_num > 0 and !ds_list_empty(_list)){
		target = ds_list_find_value(_list,irandom_range(0,ds_list_size(_list)-1));	
	}
	ds_list_destroy(_list);	
`

So, basically, this does the following:

1. Gets possible valid targets within range.
2. Checks for instance_exists() because otherwise it can and does crash- apparently Instances can _quit existing_ during the middle of this operation (I know this is a side issue, but why is this a thing? Shouldn't Instances marked for Destroy() be handled by the core thread before Step() is called? This feels like a Concurrent Modification Exception problem, where a pointer is destroyed out of sequence, and the best answer is to have a nice, safe queue that executes that stage only when it's thread-safe.).
3. If the target's myTeam variable is identical to the launching Instance, it's cut.
4. If neither condition is true, it's checking the angle, and finally (because it's by far the most expensive operation) then it's performing collision_line().

That's where the problems are seen. Sometimes everything works just fine, and the behavior's as expected. Sometimes the "seeker" code picks a target on the other side of a wall or other obstacle. Clearly, collision_line() is failing.

Why? I don't know. Somebody at YYG needs to set up scenarios in a Room with a few thousand Instances, most of them Disabled, and see if they can replicate this problem. I know you're going to say, "send us a way to replicate this", and my answer to that is, "I know this is happening and it's been happening for several years, but this is a case that's simple-enough for you to test in-house and frankly, you need to stare at collision_line() and figure out why it's failing at all.

How collision_line() should be operating under the hood (imo)

1. Perform a simple square-check. Is either point of the line segment within max(sprite_width*image_xscale,sprite_height*image_yscale), with the Instance's collision sprite as the basis. If no, then no collision is possible.
2. Perform a test vs. a rotated rectangle, whereby any line-segment intercept allows the operation to continue.
3. Ideally, do a line-segment collision test vs only the edge of the collision sprite, by building a series of line segments from the edge pixels (ideally, this is pre-computed when the Instance is spawned and stored in the Instance, eating memory but making the handling of this a relatively straightforward bit of trig, whereby the line segment to be tested against is rotated vs. the Instance's rotation before trying the test so that Instance's line segments don't require rotation).

No pixel scan is required, if the above is the way this functions. It's all line-segment intercept solutions and it can halt the first time it gets a hit. There are a couple of ways to speed it up; for example, checking a rough version that's a better approximation than a rectangle first (or better yet, let users design their own line-segment collision objects).

To sum up... I don't know how the actual code in GMS works, but I see it missing collision_line() intercepts with the code above when used. It's simply not 100% consistent. 

I've run tests here, and if I run something like:

if(collision_line(x,y,posTarget.x,posTarget.y,obj_Aura_ShadowCaster_Parent,true,true) = noone){
 target = noone; 
 runSeekerAgain = true;
}

Then it corrects mistakes after a few frames. But that's hideously expensive; collision_line() is one of the worst costs I deal with on a regular basis.

Does this destroy my game? No, but it's a constant inconvenience, largely because I can't know when it'll fail, and in the case of the "guided missile" logic, above, it produces failures that players will definitely notice. I think that some of the cases that are causing failure are:

1. Near-parallel line-segment intercepts.
2. Thin (less than 8 pixels from edge to edge) colliders often fail.
3. collision_line() without Precise set to true doesn't appear to take Instance rotations or scales into account properly. I've practically always had to set Precise to true in practice, even with literal walls that are just rectangles.

### Expected Change

collision_line() should never fail when using Precise with a line segment that crosses a tested Instance. Ideally, I'd like an alternative collision system that used line segment tests and could provide hit location and normal.

### Steps To Reproduce

1. Start GameMaker
2. Build a world with 5K Instances of several different types, spawned by procedures and mostly Disabled, and run something heavy on multiple Instances to simulate a realistic load for a complex game, where framerates are < 300. Some Instances should be arbitrarily scaled to small widths vs. heights or heights vs. widths (a square that's been stretched a bunch in one dimension, for example). Some Instances should not have Precise collisions on, but be tested vs. having the parameter true, to see what it's really testing then, etc.
3. Run a procedure to test against a particular Instance type as outlined above and record successes and failures, preferably with a way to see where, exactly, it generated a hit.
4. See the issue happen. It may take a few dozen checks a frame from/to random locations, but you will definitely see it fail.
5. Review the code for pixel-perfect collisions (all of the public information I've read about your implementation indicates it's doing a [scan like this](https://www.youtube.com/watch?v=9pnEBa4cy5w&ab_channel=NickWalton).
6. The line-segment test as proposed above, especially if the end-user can make their own, is going to be cheaper 90% of the time, I suspect, because it can halt after fewer operations, at the cost of additional memory and occasional situations where two Instances are very close to each other, but do not quite actually collide. But it should be a win, especially if we're considering the costs of rotation, which requires rebuilding the mask to do it, taking the rotation into account).

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by attic-stuff** [comment]
i want to set a project up to see if i can reproduce this and refile a smaller bug report with an example, because otherwise this is probably gunna get closed for length and not having a project attached. (also buddy you will catch more flies with honey)

before i set this up: did you test this using rotated rectangle collision masks instead of precise masks? because if you give an instance a rectangular collision type, and you rotate it, the mask doesn't rotate as well unless you have rotated rectangle set to true. this would cause the kind of error you are describing. (this kind of question is why they need projects submitted, btw)

regarding instance destruction: this is not a concurrency issue because the step and destroy logic are on the same thread (as is like 99% of everything in gm), but also the process is well documented and predictable. be sure to consult the manual on the event order and instance destroy

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by mistletoe** [comment]
I've got a good idea of how to prove this one; I'll do that.

**Comment by mistletoe** [comment]
OK... here's the deal.

1. I did _not_ prove my case for collision_line(). In static test cases, it works.
2. I _did_ find something _even more bizarre_, that probably explains what's up in my game. It'll be obvious when you run it and review the code, but for everybody in the peanut gallery: some weird things happen when you move Instances.
3. Project is attached.
[COLLISION FAIL TEST.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14300662/COLLISION.FAIL.TEST.zip)
