### ISSUE TITLE
[MacOS] Steam SDK could not copy libsteam_api.dy

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4732]
### Description
Trying to build on YYC from the Windows IDE on a separate Mac machine (Mac Mini with M1 chip). I can build fine on Windows and Linux with the Steamworks integration.
I get this output error that instructs me to report this as a bug :

```
At line:1 char:1
+ Copy-Item -Path 'C:\Steam SDK\redistributable_bin\osx\libsteam_api.dy ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand
 
[STEAMWORKS] Error: Failed to copy file 'C:\Steam SDK\redistributable_bin\osx\libsteam_api.dylib' to 'Chronique des Silencieux\Chronique des Silencieux\Supporting Files\libsteam_api.dylib' (please file a bug on this issue).
```

[f1c3f4e6-7fe5-43a3-8439-e20fd40917a3](https://api.gamemaker.io/api/github/downloads/f1c3f4e6-7fe5-43a3-8439-e20fd40917a3)

**Comment by patchuby** [comment]
@DiasFranciscoA I need to make this build quickly, any chance there is a workaround to make it work or something to do on my end ?

**Comment by DiasFranciscoA** [comment]
If this is still a problem please reopen the issue.
