### ISSUE TITLE
Better Vertex Corner ID support

### ISSUE THREAD

**Issue by HannulaTero** [YoYoGames/GameMaker-Bugs#4744]
### Is your feature request related to a problem?

Not all drawing functions support vertex corner id, `shader_enable_corner_id(true);`

### Describe the solution you'd like

More drawing functions support using vertex corner id.
- Drawing physics particles
- Drawing surfaces (_regular works_).

Correct vertex corner id order.
- draw_sprite_part & _ext
- draw_sprite_tiled & _ext

### Additional context

Here is example project where I tested different drawing functions. 
[VertexCornerId.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14301469/VertexCornerId.zip)

Here is example where I utilize vertex corner id, collision detection with drawn quads. This allows collisions with things which otherwise have no collision detection, such as particle system and texts.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/73119568/f52cd7e7-baa5-4a0d-95bf-d438eaa97811)

[Youtube Link](https://youtu.be/ADULH6x2QuA?si=f3g3_ja6naeYVj4X)

**Comment by JonnoRobson** [comment]
Support for `shader_enable_corner_id` was inconsistent across drawing functions. In some cases it was not implemented and in other cases where it was the corner IDs were not correct for the vertices. I've fixed and/or added support for `shader_enable_corner_id` in the draw functions outlined in the attached project as well as the functions `draw_tile` and `draw_tilemap`. These changes should be available in the April release, but will not be present in the upcoming February release.

**Comment by danieltjewett** [comment]
Any idea when https://github.com/YoYoGames/GameMaker-Bugs/issues/136 and https://github.com/YoYoGames/GameMaker-Bugs/issues/3482 are being worked on?  FWIW, I think those are duplicates of each other.  I'm pretty sure #136 was something I created in the old system, but #3482 has a little more information to it.
