### ISSUE TITLE
Timelines : Duplicating a moment triggers a resource load error

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#4747]
### Description

On Beta IDE v2024.200.0.494 Beta Runtime v2024.200.0.511, when duplicating a moment in a timeline, the IDE returns the following error: 

![Screenshot 2024-02-16 153651](https://github.com/YoYoGames/GameMaker-Bugs/assets/59605840/c9ada537-2989-494c-bfa2-b1684068b354)

[timeline.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14313025/timeline.zip)

### Steps To Reproduce

1. Create a Timeline
2. Create a moment in the timeline
3. Duplicate the moment
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Note I did find and fix a problem, but did not see the "Resource load failures" dialog unless I also modified a timeline moment.gml file externally, after duplicating a moment

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.200.0.498  Runtime v2024.200.0.515, thanks.
