### ISSUE TITLE
Pressing F2 with a layer selected renames the inspector tab instead of the layer

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4754]
### Description
Pressing F2 with a layer selected used to rename the layer, now it renames the inspector tab the room tabs are in.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/4077ff04-7068-49a7-bdde-9f11521f3776

### Steps To Reproduce
Open up a room, click on a layer, press F2. The inspector window will get renamed instead of the layer.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.494 Runtime v2024.200.0.511

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[647c3e1e-537f-4890-8c24-39f53958e5a1](https://api.gamemaker.io/api/github/downloads/647c3e1e-537f-4890-8c24-39f53958e5a1)

**Comment by L-Clouds** [comment]
Duplicate of #2665 (but good to know it still happens in the latest beta)

**Comment by KormexGit** [comment]
Oops, missed that the bug was already reported, I'll go ahead and close this one
