### ISSUE TITLE
In a project converted from 2023.11 to 2024.2, adding a new layer to a parent room and then adding an object to it will crash the compiler

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4755]
### Description
There appears to be an issue with converting parent rooms to 2024.2. In a project converted from 2023.11, adding a new layer to a parent room and then placing an object on it will make the compiler crash on next attempted run.
Restarting the project will make project tool re-convert the entire project again, and then the game will compile again. However, if another new layer is added to the parent room and an object placed on it again, the compile issue will return and the project will have to re-convert again on next start.
This issue does not appear to happen if the same steps are taken with rooms that were created in 2024.2.

I've attached a yyz of the original 2023.11 version of the project in case it's needed. If the automatically attached converted project doesn't have the issue, try converting that yyz.

### Steps To Reproduce
Create a project in 2023.11. Create an object, and two rooms. Make one of the rooms a child of the other. Close it.
Open the same project in 2024.2. Open up the parent room, and add a new layer to it. Place the object on this layer. Try to run the game, compilation will fail.
Restart the project, and the project tool will convert the entire project again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.494 Runtime v2024.200.0.511

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[8871e08a-f11d-41c2-9c68-2659d446449b](https://api.gamemaker.io/api/github/downloads/8871e08a-f11d-41c2-9c68-2659d446449b)

**Comment by stuckie** [comment]
Was due to duplicating "missing" resources before the project had fully loaded due to room inheritance

**Comment by alicemoretti** [comment]
Verified fixed on Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516.

Thank you
