### ISSUE TITLE
Asset Browser: Duplicated assets should be sorted underneath the source asset

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4756]
### Description
In the asset browser, when you duplicate an asset, it gets added all the way to the bottom of the resource tree, which feels a bit unintuitive compared to how other software handles this.

It would be nicer and save a bit of reorganizing and scrolling if duplicated assets were put next to the one you created it from.

### Steps To Reproduce
1. Have asset browser in custom view
2. Duplicate an asset
3. It gets added to the very bottom of the list.

[221b5083-953e-4377-bc6b-291f8401337b](https://api.gamemaker.io/api/github/downloads/221b5083-953e-4377-bc6b-291f8401337b)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
