### ISSUE TITLE
os_get_info doesn'r return a ref

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#4757]
### Description

Right now os_get_info is returning an index for a DSMap

### Expected Change

This should be returning a ref

### Steps To Reproduce

1. Start GameMaker
2. call os_get_info
3. Print the return value (show_debug_message)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v9.9.1.568  Runtime v9.9.1.704

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
