### ISSUE TITLE
Access violation reading location 0x0000000000000000

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4760]
### Description
This is a follow-up to #4314 with an updated project that has more consistent replication and an automated gameplay loop when running in  the config "gamepipe_test_dev".

The loop will:
1. Log the user in to Rumpus to have access to Game Changer, if there was no previous logged in Rumpus user
2. Enter the Game Changer interface, which has a lot of Struct operations
3. Exit the Game Changer interface, which also has a lot of Struct operations
4. Repeat step 2 and 3 until the game eventually crashes

When we export for YYC and run the game in Visual Studio, the error stack changes frequently but always throws the exception 0xC0000005. In the fastest case, the game crashes after 1 loop of going in and out of Game Changer interface, but even in slower cases where several loops were run (in about 5 minutes), the game still eventually crashes.

### Steps To Reproduce
1. Open the project the IDE. Select the config "gamepipe_test_dev"
2. Run the project for Windows VM, which will start an automated loop
3. Do not lose focus of the game window until the automatic Rumpus login completes 
4. Let the automated loop run until the game silently crashes with the exit code -1073741819
5. Run the project for Windows YYC and open the .sln in Visual Studio
6. Run the project from Visual Studio and let the automatic loop run until it throws the exception 0xC0000005: Access violation reading location 0x0000000000000000.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.496 Runtime v2024.200.0.513

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[a091522f-ef07-4be8-944d-ad454a6e5d9b](https://api.gamemaker.io/api/github/downloads/a091522f-ef07-4be8-944d-ad454a6e5d9b)

**Comment by Emc1923** [comment]
Verified in Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516
