### ISSUE TITLE
Manual Content: collision_point() page shows inconsistent argument names

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4761]
### Description
Minor doc inconsistency for the collision_point() page. The text refers to arguments x1 and y1 but the arguments are actually named x and y.

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FMovement_And_Collisions%2FCollisions%2Fcollision_point.htm

[27bd09c9-abc8-47dd-94ef-02189a02d242](https://api.gamemaker.io/api/github/downloads/27bd09c9-abc8-47dd-94ef-02189a02d242)

**Comment by YYDan** [comment]
Two bugs, so I split your Feather stuff off into https://github.com/YoYoGames/GameMaker-Bugs/issues/4762

**Comment by gurpreetsinghmatharoo** [comment]
Changed description to use x,y instead of x1,y1
