### ISSUE TITLE
Feather: collision_point() page shows inconsistent argument names

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4762]
### Description

Minor doc inconsistency for collision_point() in Feather's autocomplete window. The text refers to arguments x1 and y1 but the arguments are actually named x and y.

[27bd09c9-abc8-47dd-94ef-02189a02d242](https://api.gamemaker.io/api/github/downloads/27bd09c9-abc8-47dd-94ef-02189a02d242)

### Expected Change

Feather has the correct argument names

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Create a script
4. Start typing the function name, then pause until the autocomplete appears
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
@gurpreetsinghmatharoo there is a little typo on the manual too:

* https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Movement_And_Collisions/Collisions/collision_point.htm

Should be change:

<img width="503" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/85873067/b04ec871-e5d8-4db5-a9c3-dc379f873c12">

to be **x, y** 

This was already solved on feather end

**Comment by gurpreetsinghmatharoo** [comment]
Fixed on manual end in #4761

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
