### ISSUE TITLE
Snippets: The format shown in the manual causes an old format detected popup

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4766]
### Description

Copy and pasting the exact example used in the manual
```
I - Instance Create:instance_create_layer(x, y, |layer|, object);
```
will cause this to pop up when GM is started:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6d2f4ec1-2ea1-4277-a05d-eed333f5a1f7)

Checking the text file again after hitting yes, it will show this
```
Instance Create:instance_create_layer(x, y, |layer|, object);
```
The snippet will still be linked to the I key properly in the IDE, but there's now no clear way to edit what key the snippet is bound to. Whatever the new way is, it should be in the documentation.

In addition, the location listed in the manual to create the text file is %ProgramData%\GameMaker\User\, but the folder is actually called GameMakerStudio2 instead of just GameMaker.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=The_Asset_Editors%2FCode_Editor_Properties%2FCode_Snippets.htm

**Comment by SmithTom6304** [comment]
@gurpreetsinghmatharoo We'll need to update the manual page with the following changes:
- Remove the binding from the snippets example, in this case the leading `I - `
- Mention that any custom snippets added will have an unbound hotkey created for them
- Mention that these hotkeys can be remapped like any other through the `Preferences -> Redefine Keys` menu
- Replace the example screenshot at the bottom, which contains out-of-date default snippets. These snippets no longer have bindings, as they are specified through the usual hotkeys files
