### ISSUE TITLE
Struct addtition assignment not working

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4769]
### Description
Struct addtion assignment used to work in 2023.11 runtime, but it is broken in 2024.2. 

An example is as below:
```
#macro rumpus_perkchange_set "set"
var s = {
	rumpus_perkchange_set: 1
}

s[$ rumpus_perkchange_set] += 2;
show_debug_message("Should be 3");
show_debug_message(string(s[$ rumpus_perkchange_set]));

s[$ rumpus_perkchange_set] = s[$ rumpus_perkchange_set] + 2;
show_debug_message("Should be 3");
show_debug_message(string(s[$ rumpus_perkchange_set]));
```

### Steps To Reproduce
1. Run the code in 2023.11 runtime, see that the assignment is correct
2. Run the code in 2024.2 runtime, see that assignment is not complete

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.495 Runtime v2024.200.0.512

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[1501e2a8-febc-4f56-bb87-43371796c63d](https://api.gamemaker.io/api/github/downloads/1501e2a8-febc-4f56-bb87-43371796c63d)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.200.0.498  Runtime v2024.200.0.515
