### ISSUE TITLE
Silent crash when using audio_play_sound 

### ISSUE THREAD

**Issue by JeffersonJales** [YoYoGames/GameMaker-Bugs#4770]
### Description

Occasionally, when utilizing the audio_play_sound function with the optional gain argument, the game crashes silently. To address this issue, I initially set the gain to zero and then adjusted it gradually to achieve a fade-in effect for the music. This setup occurs within a Room Start Event.

Below, I have included some images illustrating instances where the silent crashes occurred. The 'printd()' function is utilized to display the arguments on the console if debug mode is enabled. 

![old_code](https://github.com/YoYoGames/GameMaker-Bugs/assets/21230463/b3cab948-8faa-45d0-997e-5b3c3adf5869)

Notably, during silent crashes, only the message above the audio_play_sound function (Line 12) is printed, while the message from Line 14 is omitted.
![log_on_cosole](https://github.com/YoYoGames/GameMaker-Bugs/assets/21230463/72d2e3e1-99e6-4687-84ac-d5aaba339429)

After identifying this issue as the cause of the crashes, I have made necessary adjustments to the code, effectively preventing further crashes. I will monitor the situation closely and update this report if any further crashes occur.
![new_code](https://github.com/YoYoGames/GameMaker-Bugs/assets/21230463/6be2497d-7d96-4e5e-b1c0-42728b97b871)

LTS dont have the "Create Your Contact Us Package", so I create a zip with some files from GameMaker Log.
[ui.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14349047/ui.zip)
-Bugs/assets/21230463/8bf7007a-0459-47c9-b0f8-aae0cd4f9406)

### Steps To Reproduce

1. Start GameMaker
2. Start a sound with: audio_play_sound(sound_asset_id, 100, true, 0);
3. See the issue, probably.

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Alternatively, manually zip up the project and attach it.
