### ISSUE TITLE
Add extra parameter to `json_parse` to inhibit the automatic string conversion

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#4776]
### Description

Add an extra optional parameter to `json_parse` to inhibit the automatic string conversion, that will convert strings to `handles`, `int64`, `nan` and `infinity` - these will just become strings.

This will allow users to sanitise things themselves easily when they cannot trust the source of the JSON string.

Some test code

```
show_debug_message(json_parse("\"@whatever\"",,true)); // prints "@whatever"
show_debug_message(json_parse("\"@ref room(rm_Test)\"",,true)); // prints "@ref room(rm_Test)"
show_debug_message(json_parse("\"@i64@7fffffffffffffff$i64$\"",,true)); // prints "@i64@7fffffffffffffff$i64$"
show_debug_message(json_parse("\"@@@@@I love @\"")); // prints "@@@@@I love @"
show_debug_message(json_parse("\"@ref room(Room1)\"")); // prints "ref room 0", as it receives the asset reference
```

Project [JsonParseInhibitStringConvert.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14358176/JsonParseInhibitStringConvert.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Added on 2024.2 - new optional parameter added to `json_parse` see https://github.com/YoYoGames/GameMaker-Bugs/blob/main/GMLSpecChanges/2024.2.md for more details on the changes to the function signature.

**Comment by Emc1923** [comment]
Verified optional parameter working as of Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516

**Comment by jackerley** [comment]
GMRT gives 
```
@whatever
@ref room(rm_Test)
@i64@7fffffffffffffff$i64$
@@@@@I love @
-1
```
Current runtime gives 
```
@whatever
@ref room(rm_Test)
@i64@7fffffffffffffff$i64$
@@@@@I love @
ref room Room1
```
Seems to be a problem with ref resolution?
