### ISSUE TITLE
Vertex Shader Texture fetching

### ISSUE THREAD

**Issue by Shirhix** [YoYoGames/GameMaker-Bugs#4777]
### Is your feature request related to a problem?

I wanted to make a Minecraft clone and for my format I split information into per-vertex and per-block (as in per minecraft block) so to not waste any memory by sending duplicate data in the vertices. Like this:
per block:
- block id, block substate (orientation)
- lighting, neighbours

per vertex:
- block xyz, which point to a translated position in the sent in texture that holds per-block data
- vertex index (so I can just send block coords then distribute vertex coords in the shader)

Then **send the per block information as a surface in gm_BaseTexture and fetch this data in the vertex shader.**
Another texture (as a sampler uniform) which was supposed to hold the vertex coordinates via indexing so I can build cuboids and other geometry in the vertex shader just by sending a couple of dead vertices (this cannot be done in the fragment shader).

This approach would be very memory friendly and performant.
But the vertex shader does not recognize textures and they're seen as empty.

### Describe the solution you'd like

I'd like to be able to send textures into the vertex shader. Ones that come by vertex_submit as gm_BaseTexture and/or ones by sampler uniform. Or even a special uniform to not confuse them with fragment-only textures. 
Sorry if this sounds dumb, my understanding of shaders is very shallow.

### Describe alternatives you've considered

Anything that's not a texture that can use an index (array) but those fill the uniform slots and I'd need 4096 per vertex submit. 
There seems to be no way to declare const arrays either.

**Comment by DragoniteSpam** [comment]
this is a fairly popular request, it'll be in eventually: #3250

**Comment by stuckie** [comment]
Closing as duplicate as above
