### ISSUE TITLE
Constructor function syntax improvements

### ISSUE THREAD

**Issue by coyo-t** [YoYoGames/GameMaker-Bugs#4779]
### Is your feature request related to a problem?

Cognitive load from constructors is exhausting due to their scattered syntax

The keywords & symbols are all over the place, making it not immediately obvious what something is until you're near the end of the line.
`function Something ()...` "This is a function."
`function Something () constructor {` "Nevermind, it's a constructor."

`static name = ...` "This is a static variable."
`static name = function ()` "Nevermind, it's a static method."

the worst one possible being
`static name = function () constructor {}`

The idiom `static name = function ()` also makes intent ambiguous as to whether this is a variable that will be changed at a later time or not, compared to `function name () {}` (even if technically you can still reassign the latter, the intent is well communicated).
99% of times, static variables and methods in constructor functions are never changed, but the parser/compiler/highlighter doesn't know that, and neither do you when quickly scanning a file for something specific.

### Describe the solution you'd like

Firstly: `constructor` should be allowed in-place of `function`
```gml
// current:
function Vec2 () constructor { }
function Vec3 () : Vec2() constructor {}
// improved:
constructor Vec2 () {}
constructor Vec3 () : Vec2() {}
```
And secondly: static functions should be the default
```gml
// current:
static method = function () {}
// improved:
function method () {}

// if a variable with a function is desired, you can still do
self.function_in_a_variable = function () {}
```
GML doesn't have closures so I don't know why they aren't static to begin with (I know why mechanically, `function foo () {}` gets boiled down to `foo = function () {}`, but I don't know why design wise).

The current syntax should still a valid option alongside these for compatibility.

### Describe alternatives you've considered

None. Macro support in GML being incredibly primitive combined with the ordering of keywords/symbols for constructors & static methods being all over the place doesn't make it possible to create any useable shorthand with macros
(macro abuse like this, were it possible, makes code less reusable across projects anyhow)

### Additional context

Currently, constructor functions are better than the old Javascript/Actionscript prototype noise they undeniably resemble (`Thing.prototype.method = function () {}` vs `static method = function () {}`), but could still be improved nonetheless.

**Comment by stuckie** [comment]
Closing as not planned
