### ISSUE TITLE
gml_pragma("optimise", "js_pre_post_no_long", "push, on") is broken

### ISSUE THREAD

**Issue by sp202** [YoYoGames/GameMaker-Bugs#4781]
### Description

The compiler is leaving behind an open bracket

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/39699602/faa20764-d641-41c7-a558-401af0379376)

### Steps To Reproduce

Use the above gml_pragma with any variable incrementing/decrementing

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

HTML5

[js_pre_post_no_long_bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14372541/js_pre_post_no_long_bug.zip)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.200.0.503  Runtime v2024.200.0.520
