### ISSUE TITLE
In-Game: Nullish operator on a "self" struct value causes a crash in 2024.200 Beta 6

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4785]
### Description
This line causes the game to crash - it worked fine before to initialize variables with default values if they have not been assigned otherwise:

self[$ "initial_state"] ??= "idle"

Error: Variable obj_enemy_kaha_elevator_boss.initial_state(101590, -2147483648) not set before reading it.

### Steps To Reproduce
1. Try to initialize the self struct using the nullish operator.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.499 Runtime v2024.200.0.516

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5ec6187e-1a2c-4cb2-9591-5d51f9bdfe4f](https://api.gamemaker.io/api/github/downloads/5ec6187e-1a2c-4cb2-9591-5d51f9bdfe4f)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.504  Runtime v2024.200.0.519
