### ISSUE TITLE
Room Editor: Copy and Paste of Instances and Assets not working 99% of the time in 2024.200 Beta 6

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4786]
### Description
Loaded my long-term project in the latest beta and I could not consistently copy and paste instances and sprite assets in the room editor.

I attached a video - I need to paste multiple times before one attempt eventually goes through.

I can tell that GameMaker is doing something with each try because the IDE flickers in the upper right corner where the progress bar is (I guess it shows up and disappears immediately)

### Steps To Reproduce
I recorded a video of the bug and attached it

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.499 Runtime v2024.200.0.516

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[2c8a1624-8501-4a1d-96d2-fcf940850e6e](https://api.gamemaker.io/api/github/downloads/2c8a1624-8501-4a1d-96d2-fcf940850e6e)

**Comment by YYDan** [comment]
Probably related to the underlying change for https://github.com/YoYoGames/GameMaker-Bugs/issues/2365 (which we have already reopened ourselves in that Beta)

**Comment by SmithTom6304** [comment]
Looking at the ui.log, seems like the Copy operation is failing due to a file not found issue:
```
[11:09:45:275(d799)] Loading project layout from: ***users file path***
[11:09:54:800(d799)] file not found
[11:09:58:812(d799)] file not found
[11:10:15:929(d799)] file not found
[11:10:15:930(d799)] file not found
[11:10:22:661(d799)] file not found
[11:10:22:661(d799)] file not found
[11:10:34:449(d799)] file not found
[11:10:55:919(d799)] DoUndoableAction: 'Delete room item(s)'
[11:11:05:358(d799)] file not found
[11:11:05:358(d799)] file not found
[11:11:07:407(d799)] DoUndoableAction: 'Paste Room Item(s)'
[11:11:08:117(d799)] DoUndoableAction: 'Paste Room Item(s)'
[11:11:15:368(d799)] file not found
[11:11:15:368(d799)] file not found
[11:11:18:382(d799)] DoUndoableAction: 'Paste Room Item(s)'
[11:11:23:112(d799)] file not found
[11:11:23:112(d799)] file not found
[11:11:25:249(d799)] DoUndoableAction: 'Paste Room Item(s)'
```

**Comment by stuckie** [comment]
We will need a project to be able to debug this, especially if the IDE is complaining about missing files.

**Comment by nullbunny** [comment]
It's a rather big project, what is the best way to send it privately?

**Comment by nullbunny** [comment]
@stuckie It's a rather big project, what is the best way to send it privately?

**Comment by stuckie** [comment]
If it can't be attached to GitHub, then a private Google Drive is an option and we can request access to download it.

**Comment by nullbunny** [comment]
Still happening in the latest Beta. I will try to get the upload ready sometime next week.

**Comment by nullbunny** [comment]
@SmithTom6304 Hi sorry for the ping. Just wanted to make sure my project has been received and is helpful in fixing this. Since it was a private ticket I am not able to check the status.

**Comment by Dyviik** [comment]
This happens to me as well on the 2024.2 release when I use my long term project. The room editor is literally unusable. 

However I still found a way to consistently copy and paste my selection:
1. Select assets I want to copy
2. ctrl + c
3. click anywhere in the room so my selection isent selected anymore.
4. ctrl + v

Step 2 and 4 freezes the IDE for about 30 seconds.

This was not a problem in Version 2023.11.1.129, and copy pasting happened almost instantly, even with large selections.

**Comment by SmithTom6304** [comment]
Hi @nullbunny, thanks for sending it in - we've recieved your project although I haven't had a chance to take a look at it yet. I'll make sure to update the status here when we find a fix.

**Comment by stuckie** [comment]
I wonder if this was partly related to #5320

**Comment by SantiFerre** [comment]
> I wonder if this was partly related to #5320

I would say that it is related, as the actions described by @nullbunny, on the top right bar mean that the project is being saved, if I am not mistaken.

**Comment by nullbunny** [comment]
I don't know if this has been addressed with any of the recent bug fixes, but I cannot copy/paste instances in the room editor in the freshly released version still. Also tested this on a separate computer with a fresh install.

**Comment by nullbunny** [comment]
Hi GM Team! Sorry to bother. I was just curious if this is still being worked on or if there is any additional information I can help with? I'd really like to move to a newer GM version sometime this year as the one I am stuck on also has some bugs still that make it hard to work around sometimes.

**Comment by stuckie** [comment]
Looks like GitHub lost this from the workload project.. I've readded it for August, but there has been work done throughout the IDE in handling shortcuts and saving issues, so it might be already fixed in the latest June betas.

**Comment by nullbunny** [comment]
Can confirm that this is fixed in the most recent beta!

**Comment by YYDan** [comment]
Closing per the above comment, so we know to verify.

Have left for Aug right now, but from the sounds of the above we should try verifying in June monthly first, as the Milestone value may well be wrong just now.

**Comment by caitlinrmcintyre** [comment]
Appears to work fine in IDE v2024.6.2.162  Runtime v2024.6.1.208. Marking as verified, thanks.
