### ISSUE TITLE
Manual Content: sprite_index page needs to say setting a new sprite with fewer frames causes image_index to reset to 0

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4787]
### Description

If you do something like this
```
image_index = 3;
show_debug_message(image_index);
sprite_index = spr_has_two_frames;
show_debug_message(image_index);
sprite_index = spr_has_ten_frames;
show_debug_message(image_index);
```
This will show 
3
0
0

In practical situations, swapping sprite_index multiple times a frame will make image_index loop based on the one with the fewest frames since it loops instantly on swap. This can catch people off-guard and be very difficult to debug if you don't know this behavior exists. 

I was not able to find any place that this is documented, since the current sprite_index page says:
"Changing the sprite does not change the index of the currently visible frame, so if you change the sprite on frame number 3, the new sprite will be drawn with that frame visible (assuming it has the same number of frames)."
But doesn't say what happens if the new sprite does NOT have the same number of frames, and instead has less frames.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSprites%2FSprite_Instance_Variables%2Fsprite_index.htm

**Comment by backYard321** [comment]
> ### Description
> 
> If you do something like this
> 
> ```
> 
> image_index = 3;
> 
> show_debug_message(image_index);
> 
> sprite_index = spr_has_two_frames;
> 
> show_debug_message(image_index);
> 
> sprite_index = spr_has_ten_frames;
> 
> show_debug_message(image_index);
> 
> ```
> 
> This will show 
> 
> 3
> 
> 0
> 
> 0
> 
> 
> 
> In practical situations, swapping sprite_index multiple times a frame will make image_index loop based on the one with the fewest frames since it loops instantly on swap. This can catch people off-guard and be very difficult to debug if you don't know this behavior exists. 
> 
> 
> 
> I was not able to find any place that this is documented, since the current sprite_index page says:
> 
> "Changing the sprite does not change the index of the currently visible frame, so if you change the sprite on frame number 3, the new sprite will be drawn with that frame visible (assuming it has the same number of frames)."
> 
> But doesn't say what happens if the new sprite does NOT have the same number of frames, and instead has less frames.
> 
> ### Manual Link
> 
> https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSprites%2FSprite_Instance_Variables%2Fsprite_index.htm

Absolutely - I've seen a few people get tripped up by this (including myself lol) so it would be a major help.
