### ISSUE TITLE
Methods/Functions declartions of an object be on a separate object editor window

### ISSUE THREAD

**Issue by FunnyGames** [YoYoGames/GameMaker-Bugs#4789]
### Is your feature request related to a problem?

It's really inconvenient to create object functions. Usually they will be declared in "Create" event and it becomes messy and inconvenient to look for them.

### Describe the solution you'd like

Having a new button in the object editor "Functions" which are declarations of all functions of the object, and it will look the same as objects events.
This will create an easy way to find and organize them.
![Screen Shot 2024-02-22 at 22 22 34](https://github.com/YoYoGames/GameMaker-Bugs/assets/12968098/aff3a0f3-cde3-4ce9-9207-30547240420b)

### Describe alternatives you've considered

Using scripts are also inconvenient.

### Additional context

From a look at the new editor, everything seems to be in 1 page (all events), which kinda does the opposite of my request, having long codes will make it harder to search for code.
My idea comes to try organize every piece of code and make it easier to access it.
Thanks.

**Comment by stuckie** [comment]
This is not something we are planning.
