### ISSUE TITLE
Passing a struct into a function and then using certain chained accessor sequences will cause a crash.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#4790]
### Description

This snippet of code will crash. See the comments for explanations.

```js
// Create a nested struct.
var _struct = { outer : { inner : 5 } };

// ✅ Retrieve the value using chained accessors this way, without passing the _struct into a function. This works as expected.
var _thing = _struct[$ "outer"].inner;

function _get_chained_value(_nested_struct) {
	// ✅ This works, as expected.
	var _inner = _nested_struct.outer.inner;

	// ✅ The crash will not occur when retrieving the values one at a time, like this:
	var _outer = _nested_struct[$ "outer"];
	var _inner = _outer.inner;

	// ✅ The crash will not occur when chaining string accessors, like this:
	var _inner = _nested_struct[$ "outer"][$ "inner"];

	// ✅ The crash will not occur when chaining a string accessor after a dot accessor, like this:
	var _inner = _nested_struct.outer[$ "inner"];

	// 💥 Using a string accessor followed by a dot accessor causes this crash 💥
	// Variable <unknown_object>._nested_struct(116729, -2147483648) not set before reading it.
	var _inner = _nested_struct[$ "outer"].inner;
}

_get_chained_value(_struct);
```

### Expected Change

Game Maker should not crash when performing regular accessor operations.

### Steps To Reproduce

1. Start GameMaker.
2. Run the code above.
3. Observe the crash and feel panic rising in your soul.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by ParodyKnaveBob** [comment]
Is it a matter of using [dot notation on an entity that doesn't support the syntax](https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Overview%2FAddressing_Variables_In_Other_Instances.htm&rhhlterm=assignment)? Does `var _inner = (_nested_struct[$ "outer"]).inner;` work without error for you?

**Comment by Alphish** [comment]
Confirmed it on the latest Beta (and it wasn't in a Beta I've installed earlier, so it must be a recent change), in GameMaker Windows VM.

In the YYC, I got the following error on the same line (commenting it out removed the error); maybe it's related to struct hash optimisations?
```
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object <undefined>:

struct_get_from_hash argument 1 incorrect type (unknown) expecting a Number (YYGI32)############################################################################################
gml_Script__get_chained_value (line 23)
gml_GlobalScript_CtorTest (line 27)
```

**Comment by FoxyOfJungle** [comment]
This is a bit worrying, I often use this behavior 😬

**Comment by mgeddesGM** [comment]
verified as of   IDE v2024.2.0.131  Runtime v2023.11.1.159
