### ISSUE TITLE
Tooltips for display_get_gui_width and display_get_gui_height are wrong

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#4804]
### Description
The tooltip for display_get_gui_width shows help text for display_get_gui_height, and the tooltip for display_get_gui_height doens't show anything

### Steps To Reproduce
1. Open Object1 in the attached project
2. Hover over the listed functions
3. See the issue

[367a60f7-261d-4fab-85e7-acb4e22ba88a](https://api.gamemaker.io/api/github/downloads/367a60f7-261d-4fab-85e7-acb4e22ba88a)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
