### ISSUE TITLE
Documentation for Runtime Functions seems to have some stray test code

### ISSUE THREAD

**Issue by Macj0rdan** [YoYoGames/GameMaker-Bugs#4817]
### Description

It is possible that I am just misreading the manual here but in the documentation for "Runtime Functions" at the bottom after mentioning that `instance_nearest(x, y, obj).speed = 0;` is incorrect, the code field that describes how to do it correctly has some unrelated code in it:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/28456060/e372b50d-7d24-403a-8268-598fa37a7227)

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FRuntime_Functions.htm

**Comment by gurpreetsinghmatharoo** [comment]
OMG fixed

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
