### ISSUE TITLE
`repeat infinity` does not loop

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4818]
### Description

Using a `repeat` loop with the number `infinity`, I would expect to work the same way as `while true` - that is, it would loop repeatedly until the loop is broken in some way. However, it doesn't execute at all - it basically acts as though you've written `repeat 0`.

(obviously this is a sketchy practice and should generally be avoided since there are usually better alternatives, but I still think this is worth pointing out. if `while true` works, IMO this should also work.)

### Steps To Reproduce

1. Start GameMaker and create a new project
2. In Room1, add the following to the creation code:
```gml
repeat infinity
	show_message("this is working")
```
3. See the issue (no message is shown)
[repeat infinity.ZIP](https://github.com/YoYoGames/GameMaker-Bugs/files/14407079/repeat.infinity.ZIP)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
repeat only takes integer values (you can only repeat a whole amount of time) and converting `infinity` to integer is undefined and coming out to zero so nothing is done... in fact the optimiser may be removing the code completely. I will check it out later but this will be getting short shrift.

**Comment by backYard321** [comment]
> repeat only takes integer values (you can only repeat a whole amount of time) and converting `infinity` to integer is undefined and coming out to zero so nothing is done... in fact the optimiser may be removing the code completely. I will check it out later but this will be getting short shrift.

Makes sense! I'll keep in mind that `infinity` shouldn't be used in this way.

**Comment by stuckie** [comment]
Closing as above
