### ISSUE TITLE
Redefine Keys: "Open Prefs Tree" entry refers to an internal technical term

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#4823]
### Description

The entry in Redefine Keys to open Settings/Preferences is listed as "Open Prefs Tree" . The "Tree" here refers to the internal structure of how the preferences are stored, and so isn't appropriate for a user facing name.

<img width="977" alt="Screenshot 2024-02-27 at 09 45 08" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/ba89c98b-4331-45a9-ad06-d7eeff969c9f">

### Expected Change

The "Open Prefs Tree" entry should be renamed to "Open Preferences". Localisations for other languages will need to be removed.

### Steps To Reproduce

1. Start GameMaker
2. Open Preferences -> Redefine Keys
3. Search for "pref"
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.400.0.526  Runtime v2024.400.0.547, thanks.
