### ISSUE TITLE
Android export: provide access to modify the generated android project before gradlew is run

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4825]
### Is your feature request related to a problem?

We are implementing a SDK for a very popular Android publishing platform, and the SDK requires a certain file to be at the exported aab's `base/assets` directory, and the file's name contains both upper cases and lower cases. There is no way to achieve this with GameMaker's Included Files or Extension features, as the file will either be renamed to lower cases or be put in `DynamicAssetDeliveryFiles/assets/assets` instead of `base/assets` when the Dynamic Asset Delivery option is enabled. 

### Describe the solution you'd like

Ideally, GameMaker can provide a way to let developers specify the desired file structure of the exported aab without renaming any files, but that seems to be a pretty big feature to implement. So we suggest a more versatile and low-cost solution:

GameMaker generates an Android project and then call gradlew to build it. We think that if we can access the generated project before gradlew is called, we can modify the project ourselves and then call gradlew. This feature can be implemented in the following ways: 

1. In local_settings.json, provide a setting similar to iOS's Suppress Build and Run, which stops the compiling process after the android project is generated and let the user run gradlew themselves.
2. Provide a pre-gradle hook similar to pre_package_step.bat where users can modify the Android project before gradlew is executed

**Comment by jackerley** [comment]
Hi @shichen85 I've added a pre_gradle_step which should allow you to do what you need

**Comment by shichen85** [comment]
Woohoo! Thank you.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.541  Runtime v2024.400.0.560

**Comment by shichen85** [comment]
In case this is relevant to anyone, our `pre_gradle_step.sh` looks like this:
```sh
#!/bin/bash
# Uncomment to read all the environment variables
# env

# This script assumes that the file needed to be copied is at `extensions/$YourExtension/AndroidSource/ProjectFiles/$YourFileName`

# If $YYAndroidPackageName is not set, set it with YYPLATFORM_option_android_package_*
if [ -z "$YYAndroidPackageName" ]; then
YYAndroidPackageName=$YYPLATFORM_option_android_package_domain.$YYPLATFORM_option_android_package_company.$YYPLATFORM_option_android_package_product
fi

project_dir=$YYtempFolder/android/$YYconfig/$YYAndroidPackageName
dest_dir=$project_dir/src/main/assets/$YourFileName
source_dir=$project_dir/$YourFileName
echo "Copying $YourFileName from $source_dir to $dest_dir"
# Make the directory if it doesn't exist
mkdir -p $project_dir/src/main/assets
# Copy the $YourFileName file to the correct location
cp $source_dir $dest_dir
```

**Comment by shichen85** [comment]
Thanks to [Frankie](https://twitter.com/FrancisCoulombe), a more elegant solution using Gradle code injection can also solve this issue:
In the android extension's code injection, you can add:
```
<YYAndroidGradleAndroid>
aaptOptions {
     additionalParameters "-A", "com.company.game/$YourFileName"
}
</YYAndroidGradleAndroid>
```
The file needed to be copied should still be at  `extensions/$YourExtension/AndroidSource/ProjectFiles/$YourFileName`.
