### ISSUE TITLE
Error thrown attempting to return struct that could have been a static. (Changed since November stable) 

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#4826]
### Description

Run the enclosed project, see error, run in November no error is thrown. (Extracted from a project that was using Juju's Input lib (I think))
[staticconfusion.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14423516/staticconfusion.zip)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024,2 - the issue was that the optimiser was removing a section of code from the `if...else` but the compiler thought the local variable was still present, since the name of the static and the local were the same it erroneously thought the variable was a local (not the static).

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.200.0.504  Runtime v2024.200.0.522.

Thank you.
