### ISSUE TITLE
The following functions don't have any documentation in feather.

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#4831]
### Description

physics_get_friction
physics_particle_group_get_mass
shader_set_uniform_i_array
skeleton_animation_get_event_frames
draw_enable_skeleton_blendmodes
draw_get_enable_skeleton_blendmodes
layer_get_forced_depth
layer_background_change
weak_ref_alive

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.400.0.526  Runtime v2024.400.0.547
