### ISSUE TITLE
Go To: Redefine Keys entries don't use localisations

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#4832]
### Description

In the Go To menu (`Ctrl + T` / `Command + T`), Redefine Keys entries don't use their localisations for both displaying and searching.
Beta IDE v2024.200.0.499 Beta Runtime v2024.200.0.516

### Expected Change

Entries should be listed using their localisation values, and be searchable by both the localisation value and the english value

### Steps To Reproduce

1. Start GameMaker
2. Set the language to French
3. Open any project
4. Open the GoTo menu (`Ctrl + T` / `Command + T`)
5. Search for "Copy"
6. Observe the "Copy" entry appears in English
7. Search for "Copier" (French for "Copy")
8. Observe no entry appears
9. Observe that other entries in the GoTo menu are localised

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.400.0.521  Runtime v2024.400.0.540, thanks.
