### ISSUE TITLE
error: Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by EsteveMatteo** [YoYoGames/GameMaker-Bugs#4834]
### Description

When I build my game on an IOS device, this error appears : 

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS, id:00008110-000605880240401E }
	Ineligible destinations for the "square_watermelon" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 17.2 is not installed. To use with Xcode, first download and install the platform }

I searched but didn't find any help for that bug.

### Steps To Reproduce

1. Start GameMaker
2. Target my IOS device 
3. Build
4. See the issue

[Untitled.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14438036/Untitled.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Which platform(s) are you having trouble building this project for?

iOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Hi - that error message already tells you the problem and the fix:

"error:iOS 17.2 is not installed. To use with Xcode, first download and install the platform"

Your Mac must not have the correct Xcode version or iOS SDK package installed to match the iOS device you're trying to use, so please open Xcode and log into your Apple Developer account and fix the installation there.

This is not a bug or anything we can fix for you.

I'll link you to our iOS setup guide, but (as the guide says) much of the Xcode setup is actually in the macOS guide this one will ask you to follow first:
[https://help.gamemaker.io/hc/en-us/articles/115001368747-Setting-Up-For-iOS-Including-iPadOS](https://help.gamemaker.io/hc/en-us/articles/115001368747-Setting-Up-For-iOS-Including-iPadOS)
