### ISSUE TITLE
(Igor, not in IDE) `Igor runtime Install` and `Igor runtime Verify` fail with error about extra files.

### ISSUE THREAD

**Issue by OmegaMetor** [YoYoGames/GameMaker-Bugs#4835]
### Description

When using `Igor runtime Install` to install a runtime, it will fully download the runtime as expected. After this, it verifies the runtime, i assume with the same functionality as `Igor runtime Verify`. When either of these happen, the command fails, saying there are over a thousand extra files. This does not effect downloading it through the ide, as that seems to not use igor for this.

This happens with every version of igor and every runtime that I have tested it with, including 2023.11.1.160, and multiple from 2022. Package isn't attached since it's not through the ide but i didn't know what category to use.

### Expected Change

No longer erroring when downloading a perfectly fine runtime.

### Steps To Reproduce

1. Get license file for use with igor
2. `Igor runtime Install -lf (path to license file)`
3. It fails, even if it downloaded properly.
4. `Igor runtime Verify (path to runtime folder, usually similar to runtime-2023.11.1.160`
5. It fails with the same error

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Which platform(s) are you having trouble building this project for?

Windows, macOS, Ubuntu, Android, GX.games, HTML5, iOS, PlayStation 4, PlayStation 5, Switch, tvOS, Xbox (GDK)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by shichen85** [comment]
Yep, also having this problem.

**Comment by rwkay** [comment]
What is the error that you are seeing... I do not get an error on the `runtime Install` (it does say `Verification Inconclusive no manifest found`) but it is not erroring

**Comment by OmegaMetor** [comment]
Odd, here's the full log (which i thought i had included initially, my bad)
[error.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14461008/error.txt)

**Comment by OmegaMetor** [comment]
I just realized, this is running igor on linux, which doesn't exist in the most recent runtime version. The one i've found that does have igor for linux (without testing windows ones on linux, though they'd probably work because of dotnet?) is the 2022.11.1.75, i've not been able to test it on windows so i'm not sure if recent windows versions of igor have this fixed.
