### ISSUE TITLE
Redefine Keys: Add Save/Load functionality for saving out user remaps

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#4838]
### Is your feature request related to a problem?

Currently users cannot save/load their remaps to file. This leads to the following problems:
- Remaps cannot be shared across GameMaker builds (monthly/LTS/beta). A user will have to re-create their desired remaps each time they want to try out a new build type.
- Users may want different remaps on Windows vs macOS. If a user has two machines they swap between, keybinds may not always be appropriate for that system

### Describe the solution you'd like

We should add Save/Load buttons to the Redefine Keys menu. 
- When Save is pressed, a file dialog should appear allowing the user to save their remaps to a file. This will copy the contents of their `remaps.json` file out to the file they specify.
- When Load is pressed, a file dialog should appear allowing the user to select a remaps file to load from. This will copy the contents of that file into the users `remaps.json`

**Comment by YYBartT** [comment]
Updated the screenshots on the "Redefine Keys Preferences" manual page and added a section on the new functionality.

**Comment by mgeddesGM** [comment]
@SmithTom6304 

when you press export both file name and type are blank.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/f117f85b-3931-4bed-ba57-5cb568ef37b6)

on import, since no filter i can select any format
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/e1f8ce79-698b-4fb5-9d2e-b0f514d40443)

**Comment by mgeddesGM** [comment]
@YYBartT when will this [beta manual page](https://manual.gamemaker.io/beta/en/#t=Setting_Up_And_Version_Information%2FIDE_Preferences%2FRedefine_Keys_Preferences.htm&rhsearch=Redefine%20Keys%20Preferences&rhhlterm=Redefine%20Keys%20Preferences) be updated?

Also the page may need to have updates depending on on what @SmithTom6304 does

**Comment by SmithTom6304** [comment]
Exporting should now default to "exported_remaps.json"
Importing should now filter to just .json files

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.595  Runtime v2024.800.0.619
