### ISSUE TITLE
sprite_add load only first frame of gif

### ISSUE THREAD

**Issue by Alkapivo** [YoYoGames/GameMaker-Bugs#4839]
### Description

According to the documentation when I want to load external gif with `sprite_add` or `sprite_add_ext` then I should set `imgnum` param with value `1.0`.
Well, It's not working :(, created sprite_index contains only one frame according to `sprite_get_number`.

### Expected Change

All frames should be imported with sprite_add and sprite_add_ext

### Steps To Reproduce

 @@
[bug_sprite_add_gif.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14449370/bug_sprite_add_gif.zip)
[contact-us-package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14449371/contact-us-package.zip)

1. Start GameMaker
2. Open `bug_sprite_add_gif.yyz` project (file is located inside bug_sprite_add_gif.zip)
3. Build & run project
4. See the issue in game window and in output read lines with `[DEBUG]` prefix
```
[DEBUG] sprite_add: speed 30
[DEBUG] sprite_add: frames 1
Total memory used = 11910218 (0x00b5bc4a) bytes 11.36MB
Free memory = 6179888 (0x005e4c30) bytes 5.89MB
Peak memory used = 14828132 (0x00e24264) bytes 14.14MB
**********************************.
Entering main loop.
**********************************.
[DEBUG] sprite_add_ext: speed 30
[DEBUG] sprite_add_ext: frames 1
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by attic-stuff** [comment]
this should be a feature request not a bug, as its documented and expected behavior. from the manual: "If you are adding a *.gif format image, then you only need to specify the filename and image number (which should be 1 for the first frame) and can leave all the other arguments as 0, noting that only the first image of the GIF will be loaded."

**Comment by YYDan** [comment]
Yeah, as mentioned above, you've misunderstood what that line of the manual says. (It would be a bit odd anyway to specify "1" for the image number parameter and then _not_ get 1 frame ;) )
