### ISSUE TITLE
Object Editor/Code Editor 2: Parent's new events don't automatically appear in the Child if their editor is open 

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#4841]
### Description
On  IDE v2024.200.0.505  Runtime v2024.200.0.523. 

When the user creates a new event in a Parent object and its Children's event window in the object editor is open, the new event does not appear in the Children. The user needs to close and re-open the Children's object editor for the new event to appear.

### Steps To Reproduce
1. Start GameMaker
2. Create a Parent object
3. Create a Child object and open its object editor and events window
4. Add an event to the Parent object
5. See the issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.505 Runtime v2024.200.0.523

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[eb32893b-754d-465e-8c58-43df7acdfe15](https://api.gamemaker.io/api/github/downloads/eb32893b-754d-465e-8c58-43df7acdfe15)

**Comment by YYDan** [comment]
CE2 has inherited the same situation in 2024.400 Betas, but obviously the issue manifests inside the editor, rather than the Events window.

**Comment by YYDan** [comment]
"Duplicate" of https://github.com/YoYoGames/GameMaker-Bugs/issues/5608 so just swapped this one for that one
