### ISSUE TITLE
Room Editor: using select from any layer mode to swap from a tile layer to an instance layer will make the resizing cursor only appear when clicking

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4842]
### Description
If you swap to an instance layer from a tile layer using select from any layer mode, hovering your cursor over the edge of any object will no longer show the resizing (or rotating) cursor, instead only showing the regular cursor. The resizing cursor will appear if you click on the edge, but disappear again as soon as you release the mouse button. The problem will persist for all objects untill the project is reopened or GameMaker is restarted.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6533c89d-a6df-4a40-8595-c9d7b75ee754

### Steps To Reproduce
Place an object on an instances layer. Create a tile layer. While the tile layer is selected, enable select from any layer mode, and then click on the object. Hovering over the edges of the object and see the resize cursor not appearing.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.505 Runtime v2024.200.0.523

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[ea8bf8e6-b1ec-495f-85ad-a6185013247c](https://api.gamemaker.io/api/github/downloads/ea8bf8e6-b1ec-495f-85ad-a6185013247c)

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.400.0.526  Runtime v2024.400.0.547
