### ISSUE TITLE
`instance_exists(variable)` returns false positive if "variable" is a "self" containing the id of a separate, active instance

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4851]
### Description

Sorry in advance if this requires more clarification later. 

If you use a persistent object to store a non-persistent instance's "self" in a variable (eg: `storedInstance`), and then call `room_restart()`, `instance_exists(storedInstance)` will return "true" even though the "self"s instance no longer exists. `storedInstance.id`'s "self" will not match `storedInstance` after the restart, even when both "self"s are stored in variables to avoid #4788.

I believe the reason for this is that the "self" being checked stores the id of an instance that MATCHES an existing instance, but doesn't refer to the SAME instance. 

[persistent self.ZIP](https://github.com/YoYoGames/GameMaker-Bugs/files/14464512/persistent.self.ZIP)

### Expected Change

`instance_exists(variable)` should return false if "variable" is a self not belonging to an existing instance

### Steps To Reproduce

1. Run included project
2. When first running, `ObjectPersistent`'s variable "storedInstance" will correspond to an existing instance (of Object2).
3. After pressing "R", the game will still recognize `storedInstance` as active, even though it isn't. `storedInstance.id`'s "self" will not match `storedInstance`, likely because the game is recognizing a new instance with the same id, rather than the instance containing the original self.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by attic-stuff** [comment]
feels like the real bug here is instance_exists() not throwing an exception for being passed a struct instead of a instance id or an object index haha. what i **think** is happening here is that you're storing the self struct in a variable, which keeps a reference to that struct alive. so instance_exists() for that struct reference IS true even tho the instance is gone, because the struct is not (keeping a reference to a struct keeps it alive).

but the reason the id doesnt match is because when you stored a reference to the first instance's self struct, it contains that instances id, and after the restart the newly made instance has a different id because they are not recycled. curious to see how this one plays out!

**Comment by backYard321** [comment]
> feels like the real bug here is instance_exists() not throwing an exception for being passed a struct instead of a instance id or an object index haha. what i **think** is happening here is that you're storing the self struct in a variable, which keeps a reference to that struct alive. so instance_exists() for that struct reference IS true even tho the instance is gone, because the struct is not dereferenced (keeping a reference to a struct keeps it alive).
> 
> but the reason the id doesnt match is because when you stored a reference to the first instance's self struct, it contains that instance's id, and after the restart the newly made instance has a different id because instance id is not recycled.
> 
> curious to see how this one plays out haha

Yeah so the `self` is still alive, which I would expect, since a `self` that's been stored will persist even after the corresponding instance is destroyed. However, checking `instance_exists()` on the self of a destroyed instance WILL return false, so it's not returning whether the struct is still alive. As I said, I suspect it's checking the id stored in the struct.

But the id's of the two instances ARE the same, which you can verify in the code. It's their "self"s that don't match - one self belongs to the destroyed instance, and the other to an active instance. The expected behaviour to me would be that checking `instance_exists()` on the nonexistent instance's self should return false, regardless of whether there's an existing instance that uses the same id. And the id IS recycled on room_restart(), which would make sense because the instance was placed in the room editor.

**Comment by backYard321** [comment]
Not 100% sure i'm correctly diagnosing the issue or even understanding what's happening here, and I don't think i'm doing an effective job of explaining it, so i'm going to close this for the time being.

**Comment by rwkay** [comment]
This is not a bug... the `self` of an instance (even a persistent one) is not guaranteed to be the same between rooms only the `id` is going to be invariant.

For legacy reasons and how the current runner is constructed (and for ancient arcane reasons) a persistent object is serialised from the pervious room, completely destroyed and then restored in the new room and this can mean that the underlying `struct` that the `self` refers to can change between rooms.

This is not something that is going to change in the current runtime.

**Comment by backYard321** [comment]
> This is not a bug... the `self` of an instance (even a persistent one) is not guaranteed to be the same between rooms only the `id` is going to be invariant.
> 
> For legacy reasons and how the current runner is constructed (and for ancient arcane reasons) a persistent object is serialised from the pervious room, completely destroyed and then restored in the new room and this can mean that the underlying `struct` that the `self` refers to can change between rooms.
> 
> This is not something that is going to change in the current runtime.

For the record, what you're referring to isn't the bug I'm talking about - I'd totally expect the selfs to be different and change between rooms, AND for the ref to stay alive, so that's definitely not a bug.
