### ISSUE TITLE
Manual Content: "Twitter" mentions should be changed to "X" branding (blogs also?)

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4854]
### Description
Hey there,
just read through an article about nine-slicing and found, that "Twitter" is mentioned there, the author's bio contains also Twitter links, even with the old blue bird logo...

If you find the time, please search&replace all the twitter references in the entire manual as this name no longer exists and it creates the impression, that the manuals are "outdated", when they still refer to a no-longer-existing message service, especially with a so well-known name, as twitter was.

(Even your page-footer contains the bird instead of the X as logo in the "Social Media" column and i guess, this footer is used in many places).

In case, you are still hoping, like many others, that Mr. E.M. will leave tw...X for good and the old service might come back, then ignore this message :-)

```
Let us know what you think of this feature on Twitter  @YoYoGames, and you can also use the #GameMakerStudio2 hashtag when sharing your creations with the world.

Written by Gurpreet S. Matharoo

Lead Technical Writer at GameMaker, Gurpreet creates documentation and tutorials to make game making easier for you. He loves using the computer to bring new things to life, whether it's games, digital art, or Metal music.


Twitter YouTube LinkedIn
```

[db6f7253-8639-41b7-a384-dd73a77b9a19](https://api.gamemaker.io/api/github/downloads/db6f7253-8639-41b7-a384-dd73a77b9a19)

**Comment by gurpreetsinghmatharoo** [comment]
no
