### ISSUE TITLE
CMD-F does not search in room creation code window

### ISSUE THREAD

**Issue by bsabiston** [YoYoGames/GameMaker-Bugs#4857]
### Description

Usually pressing CMD-F does a search for text in an IDE window.  At some point in recent releases, pressing CMD-F while in a room's creation code window no longer does this.  It makes a Folder in the layers window.  This is so confusing! Is it like this for everyone or has my configuration just gotten messed up.  Several times an hour I make this mistake and create folders in my room creation code when I am trying to search the code.   I don't see any report of this bug in the existing bugs list.  Is it possible I have messed things up via ice customization?  I don't remember changing anything.
[BugReport.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14469559/BugReport.zip)

### Expected Change

CMD-F should search when in an IDE code window, no matter where you are in the IDE

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This should now be fixed.

**Comment by SmithTom6304** [comment]
This has now gone back into April, and should be in beta version IDE v2024.400.0.542

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.544  Runtime v2024.400.0.563.
