### ISSUE TITLE
Make parts of the legacy project import code conversion optional

### ISSUE THREAD

**Issue by BPzeBanshee** [YoYoGames/GameMaker-Bugs#4858]
### Is your feature request related to a problem?

I've been involved in several projects that have involved transitioning from legacy GM versions to the modern one, and as much as the auto-generated conversion code has been helpful in most instances, there are cases where I believe it would be better for parts of it to be left as-is to be fixed by hand. 
I've had to triage a number of issues that were compounded by errors in the machine-generated conversion code, off-by-ones with layer calls resulting in breakages of background behaviour in what should've be simple cases. 
I believe those specific issues have since been reported but I did not see a fix for these at the time, and even if they were, I think having an option to *not* convert those code lines would be convenient. The machine-generated scripts also generate Feather errors which don't help the cleanup process.

### Describe the solution you'd like

Most of the process is already transparent, the main area where the machine code makes areas more difficult to deal with is the changed view functions/variables and room info. 
With an option to allow or disallow the automatic mangling of room-related variables, a professional user can manually batch-replace any other function calls themselves to fix project issues and have a better experience in fixing room issues without having to de-mangle scripts that make CPU-heavy script calls.

### Describe alternatives you've considered

A menu similar to the extension import process that flags converting/leaving particular resource types might be better than a yes/no option, but I can't think of much to have as separate allow/disallow apart from the view/room code. Maybe a naming convention option for layer names? I'm open to alternative suggestions here.

**Comment by stuckie** [comment]
This is not something we are planning.
