### ISSUE TITLE
Room Editor: Clicking an already selected instance using select from any layer mode while a tile layer is selected disables some keyboard shortcuts

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4866]
### Description
If you click on an instance to select it and bring it up in the inspector, then click on a tile layer, then use select from any layer mode to select the instance again, some keyboard shortcuts will not work until the instance is de-selected and selected again. This includes things like delete, ctrl + c/ctrl+v, and probably more. I suspect this may be related to my previous report #2535, which did get fixed, as well as #4842

At the end of this video, I'm hitting the delete key as well as ctrl+c/ctrl+v, but nothing is happening.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/d3760fab-ae3c-4869-9f0d-192f056ab20f

### Steps To Reproduce
Place an instance on an instance layer. Click the object to select it. Select a tile layer. Enable select from any layer mode. Click the instance again to swap back to it. Try to use a shortcut like the delete key, and see that nothing happens, even though the instance is selected and appears in the inspector as being selected.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.505 Runtime v2024.200.0.523

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[c066e4d9-930d-4a38-82df-8031d967e600](https://api.gamemaker.io/api/github/downloads/c066e4d9-930d-4a38-82df-8031d967e600)

**Comment by alicemoretti** [comment]
Verified on IDE v2024.400.0.526  Runtime v2024.400.0.547. Thank you.
