### ISSUE TITLE
array _pop, _shift, and _delete should fail with an exception

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#4867]
### Is your feature request related to a problem?

hello neighbors, if you array_shift() or array_pop() an array with a length of 0, then it just returns undefined. if you array_delete() an array that is empty, you get no error at all! it would be nice if these functions threw out of bounds exceptions!

### Describe the solution you'd like

i would like to see out of bounds problems be respected by the runner with exceptions if gml_release_mode() is true.

thank you for reading.

**Comment by stuckie** [comment]
This is not something we are planning.
