### ISSUE TITLE
Add Setting to change color/font of method variables

### ISSUE THREAD

**Issue by Funcestor** [YoYoGames/GameMaker-Bugs#4868]
### Is your feature request related to a problem?

When using/calling method variables they easily blend in together with normal variables which affects readability of the code. It would be helpful if we could change the color of method variables so that they are more noticeable.

### Describe the solution you'd like

Add a Setting in Preferences -> Text Editors -> Code Editor to change color/font of method variables

**Comment by stuckie** [comment]
This is not something we are planning, as a method variable is just a variable.
