### ISSUE TITLE
audio_group_set_gain causes memory leak when called before a previous call is finished

### ISSUE THREAD

**Issue by Journoid** [YoYoGames/GameMaker-Bugs#4869]
### Description
When audio_group_set_gain is called multiple times in succession (like in the step event) AND the time argument is greater than the time between calls: it will continually raise the used memory of the game.  

Target platform: Windows GMS2 VM

The discovery of this bug was due to using a for-loop to iterate over multiple audio groups and adjust their volume to a specificed value over the course of 500 milliseconds. This code executed every step, and looped over ~15 audio groups.

### Steps To Reproduce
1. Create an audio group with atleast one sound that must be loaded (for example, Uncompress on load)

2. Have the audio group load in-game

3. execute audio_group_set_gain() on your audio group with a high time argument (>500)

4. Watch the memory usage increase in either the in-game debug menu or an external resource monitor

The example project attached creates a unrealistic scenario with the function executing 10,000 times per step if the space bar is held.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.505 Runtime v2024.200.0.523

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[75690d6d-a248-4194-8c33-402d3b9771c6](https://api.gamemaker.io/api/github/downloads/75690d6d-a248-4194-8c33-402d3b9771c6)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
