### ISSUE TITLE
effect create depth with gray color turns blue for no reason

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#4871]
### Description
Hello

I use the following code in my game to create a gray explosion effect

After a while, the explosion turns blue (and that's good by the way)

How is it possible ? Is it a mix of memory with a particle effect or another gamemakerstudio effect?

		effect_create_depth(DepthSprite,ef_smoke,x+val,y,1,c_dkgray);
		effect_create_depth(DepthSprite,ef_explosion,x+val,y,10,c_dkgray);

### Steps To Reproduce
effect_create_depth(DepthSprite,ef_smoke,x+val,y,1,c_dkgray);
effect_create_depth(DepthSprite,ef_explosion,x+val,y,10,c_dkgray);

[8f1d476a-fca0-41b6-a784-e9a37e4081a0](https://api.gamemaker.io/api/github/downloads/8f1d476a-fca0-41b6-a784-e9a37e4081a0)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by galban83** [comment]
I can't provide a project, because this is happening on my full game. I've tried for hours to isolate the problem, but I can't find any logic to this problem.
In any case, it happens completely randomly and I have reproduced the problem several times (on PC and switch).

**Comment by stuckie** [comment]
All projects sent in are kept private.. you can either upload via the form in the IDE, or upload to something like Google Drive and we can request access.
However, if you cannot reproduce it yourself in a smaller project, it does sound like it is something to do with your game, so you may also want to seek help via the community, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Comment by galban83** [comment]
The bug is very complicated to reproduce, it occurs after hours of play and completely randomly (sometimes never).
My project will bring you nothing, you would have to spend countless hours on it

But I think there is really a problem, I had thought of a mixture with a particle effect, but the latter are not at the same depth.

Additionally there is only one place in my code where I use

effect_create_depth(DepthSprite,ef_smoke,x+val,y,1,c_dkgray);
effect_create_depth(DepthSprite,ef_explosion,x+val,y,10,c_dkgray);

So this cannot come from a programming error, because there is no condition.
Finally I checked the c_dkgray value, it always remains the same

For my part I think there is a problem with an effect. I had already reported several proven problems with the effects (problem freeing memory, problem with the underwater effect which gets stuck on switch)


On the other hand, I find that particle effects are complicated to manage.

Let me explain, these are resource-intensive. So you have to delete them and re-create them dynamically when they are not visible on the screen. This destruction sometimes produces bizarre effects. I think we should add a function to say that an effect is active only when it is visible. This would avoid having to dynamically create and delete them constantly

And the same goes for objects

**Comment by stuckie** [comment]
We're still going to need a project to try and track this down, or better yet a small 100% reproducible project that we can also use to verify against.

There are almost 3,000 issues in this repository alone to try and get through, so we simply do not have the time to create a new project for each one that requires it, then try to set it up to reproduce the same issues that are reported, to then fix it, and then verify against it. We may also miss a step, or get different results from you when creating the project, which adds additional confusion to what is going on, so we are starting to get more stringent on requiring a project to fix issues; to ensure everyone is working from the same base of understanding.

In terms of this issue alone, there could well be an issue with an interaction with other layers, surfaces, or anything else. There's a wide range of things that could cause a graphical glitch that can come about simply from rendering things in a different order, so we need a project to understand the flow, and see which combination is problematic.

We're not saying this may not be a legitimate issue, we're asking for help to diagnose it quicker. There's enough unknowns here, that we could go down a rabbit hole and completely miss the issue you are seeing.
