### ISSUE TITLE
An option to disable exporting for sprites on HTML5 export

### ISSUE THREAD

**Issue by RowanFuture** [YoYoGames/GameMaker-Bugs#4872]
### Is your feature request related to a problem?

I'm developing extremely minimal HTML5 games, and I store the collision data as a sprite with precise collisions, the actual collision code is stored in GM's exported JS file but there's a big texture page with all the collision sprites that players have to load, which adds a lot to loading times.

### Describe the solution you'd like

Add an option to sprites to not export the sprite image only the sprite collision for HTML5 platform.

### Describe alternatives you've considered

When I delete the texture pages used for the sprites on a HTML5 export, the game still runs and the collisions still work, only the sprite texture isn't imported. I'm developing a workaround for HTML5 that will just ignore importing the unused texture pages.

An alternative solution would be to associate texture pages with not being exported.

**Comment by tabularelf** [comment]
I haven't particularly tried it on HTML5, but with texture groups you can actually choose to not export them instead, and still be able to retrieve relevant collision data from them.

**Comment by RowanFuture** [comment]
> I haven't particularly tried it on HTML5, but with texture groups you can actually choose to not export them instead, and still be able to retrieve relevant collision data from them.

omg I had no idea, I tried looking for an option but maybe I missed it
