### ISSUE TITLE
optional async loading for audio files so that they don't cause long HTML5 loading times

### ISSUE THREAD

**Issue by RowanFuture** [YoYoGames/GameMaker-Bugs#4882]
### Is your feature request related to a problem?

My game's loading time is really long on bad wifi, mainly because all audio has to be loaded before the game can start.

### Describe the solution you'd like

An option for HTML5 to make all audio file loading happen async.

**Comment by toby-yoyo** [comment]
There are already two features available that offer this.

**Audio Groups**
Assets in audio groups are not preloaded but instead await a call to `audio_group_load` from the game during runtime. Requests for assets in the group and any necessary decoding is performed asynchronously.

**Streaming**
Streamed sounds are those with the "Compressed - Streamed" attribute set in the sound editor. These assets are also not preloaded at game start, but are requested and decoded asynchronously when needed to satisfy a call to `audio_play_sound` or similar.

As these features already provide the functionality requested, I'm going to close this as not planned. If you feel that the current feature set has a blind spot, then please detail what that is in a new feature request.

**Comment by RowanFuture** [comment]
the files in audio groups are still downloaded at the start of the game, this is my issue, their file size is the problem
