### ISSUE TITLE
json_parse() filter function giving array indices as strings and not reals

### ISSUE THREAD

**Issue by apathyhill** [YoYoGames/GameMaker-Bugs#4883]
### Description

When using a custom filter function with `json_parse()`, the index given when parsing an array is a string.
The [wiki says](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFile_Handling%2FEncoding_And_Hashing%2Fjson_parse.htm) it should be a real.

![2024-03-04 17-07-57 GameMaker](https://github.com/YoYoGames/GameMaker-Bugs/assets/161617485/5b049fff-8efa-4e42-85b9-928ed9c253a4)
![2024-03-04 17-08-37 GameMaker](https://github.com/YoYoGames/GameMaker-Bugs/assets/161617485/fdb2ddcb-2cc4-4997-9511-6dbd436c5386)
[JsonParse.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14487788/JsonParse.zip)

### Steps To Reproduce

1. Make a string representing a JSON file, containing an array. `"[\"@ref object(Object1)\", \"Hello, World!\", 123]"`
2. Add a boilerplate filter function that prints out the type of the "key" / index.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
This is not a bug - the key is always given as a string - this is consistent with the equivalent JS behaviour. see https://jsfiddle.net/gc8x2dz7/

**Comment by sihammill** [comment]
Not a bug as detailed above by @rwkay, verified as working correctly in IDE v2024.400.0.513  Runtime v2024.400.0.533
