### ISSUE TITLE
Performance: [Mac IDE] IDE lags and slows down significantly when picking a Sprite for an Object

### ISSUE THREAD

**Issue by davidkarbo97** [YoYoGames/GameMaker-Bugs#4887]
### Description

The slow-down persists until Gamemaker is closed and reopened.

Link to zip: https://drive.google.com/file/d/1xTHIqdk6JMLWHOWqdgTqMbEtNN7Zs9LJ/view?usp=sharing

### Steps To Reproduce

1. Start GameMaker
2. Open an object editor
3. Open the sprite selection window from the object editor
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment]
Above commit should help considerably (caused by various issues with generating thumbnail icons for sprites); there may still be a little stutter due to those very large (16k) background images, but now should be relatively minor, hopefully!

**Comment by davidkarbo97** [comment]
Sorry, what do you mean by "above commit?"

**Comment by yyalansavage** [comment]
Hi, I am just referring to the commit/Pull Request links which appear above the comment (maybe you can't see those?)

**Comment by davidkarbo97** [comment]
I don't think I can see them on my end, unless I'm missing something. The only link I see is the original Google Drive link that I shared.
