### ISSUE TITLE
Local Packages#2 - Sprites get modified

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4888]
### Description
Hello again,

there is another new problem with local packages:
When you add "sprites" to a package and import them in another project, from a GIT point of view, the sprites are not identical and now show a difference!

See attached an image of a sprites-folder of a project, where you can see, that TortoiseGit shows **all** sprites as modified.
What did I do to create this?
* I exported ALL those sprites to a local package
* And re-imported them TO THE SAME PROJECT a few minutes later
By any logical means, the files must be identical, export and import location are the same, they ARE just imported over their originals.

As an example, I picked one of those files for you and show you, what went wrong:

Here is the content of a 1-pixel-black png image, which contains this data (from notepad++) in the ORIGINAL (where I created the package)
```
‰PNG

   
IHDR         Ä‰    cHRM  z&  €„  ú   €è  u0  ê`  :˜  pœºQ<   bKGD ÿ ÿ ÿ ½§“   
IDAT×c```ø  ¤à¬1   %tEXtdate:create 2024-03-05T04:28:25+00:00-4   %tEXtdate:modify 2024-03-05T04:28:25+00:00cp­ˆ   (tEXtdate:timestamp 2024-03-05T04:28:25+00:004eŒW    IEND®B`‚
```

This is the file after being imported a few minutes later (time stamp changes by about 6 minutes - see close to the end of the file):
```
‰PNG

   
IHDR         Ä‰    cHRM  z&  €„  ú   €è  u0  ê`  :˜  pœºQ<   bKGD ÿ ÿ ÿ ½§“   
IDAT×c```ø  ¤à¬1   %tEXtdate:create 2024-03-05T04:34:10+00:00(>   %tEXtdate:modify 2024-03-05T04:34:10+00:00duº‚   (tEXtdate:timestamp 2024-03-05T04:34:10+00:003`›]    IEND®B`‚
```

What I interpret here is, that, for some reason, you do not simply unzip the file from the package but kind-of "re-create" the image and write the file through some png-creation library, which creates a new timestamp in the file, as if it were newly created and not simply copied from A-to-B

From the release notes I could read, that with resources there's lots of new code that shall guarantee stable order of things and that we now should have way less diff-problems in git.
for png's, unfortunately, the opposite is true. Now we have ALL differences that are possible. Maximum diff-count.

See attached a screen shot from a re-import of sprites to the same project, where I exported them. ALL are modified!

One question: If you really re-create those files through some library... I did not test that, but what about jpgs? do you also re-create them, and if yes, with which quality-settings? I hope, you save them with 100% quality as this is the only way to re-create a jpg with the quality it had when the original was created, and that you do not write with some defaults like 90%. In a 90% case, with every export-import-cycle, the quality of the image would be reduced by another 10% for each cycle.

Thanks for reading
Cheers
Gris

### Steps To Reproduce
* You need a project with at least one sprite under source control (git)
* Make sure, your working copy is "green" (no modified files)
* Open that project
* Create a local package with only a sprite in it
* wait 2-3 minutes (this step is important!!!)
* import the package to the same project
* Do a "git diff"
* you see, the files are not identical but they should be

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[3d0e0ec2-c05f-402c-b99f-eafaeb318066](https://api.gamemaker.io/api/github/downloads/3d0e0ec2-c05f-402c-b99f-eafaeb318066)

**Comment by stuckie** [comment]
Hello,

When we load the sprites in, we recomposite them so that they can be rendered, build a thumbnail, and so on... this is so that we can ensure that the images can actually be loaded, and because we don't know if you have edited the sprites outwith the IDE at that point.

As you've noticed the difference in this case is just the timestamp, but the actual data itself should be the same. If there were any issues we'd have been able to highlight these on load, and the save also ensures that we have permissions to save back out into the folder.

So, yes.. there are reasons that we resave on import, and this isn't likely to change.

**Comment by Grisgram** [comment]
Thanks for the detailled reply! 
I can understand that, but this makes it impossible on a git commit to distinguish between "real changed sprites" and "just rewritten sprites"

So, from a git point of view, this creates (in a bigger game) hundreds or more entries in the history and enormous change-lists for each commit, if a package is distributed between projects.

In addition, when using a diff tool like winmerge, it is absolutely impossible from the diff-list to find the real changed sprites. Please find another way to solve the requirements on your side.
PLEASE rethink.

Thanks, Gris
