### ISSUE TITLE
UI/UX: [Mac IDE] Command-and-ArrowKeys no longer work during text entry in 2024.2 IDE

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4889]
### Description
The frollowing no longer works in the new version of the IDE (v2024.2.0.132):

Command-LeftArrow
Command-RightArrow
Command-Shift-LeftArrow
Command-Shift-RightArrow

These keyboard shortcuts should be moving the caret to the beginning/end of line (similar to Home and End keys).  Holding shift during these combos should extend the selection when moving the caret.  This was working in the previous version of the IDE.

Could be related to Issue #2438 in which the Shift-Option-ArrowKeys weren't working (but are now in this new version of the IDE.)

### Steps To Reproduce
1. Open a project, and open the code editor or any window in trhe IDE that requires text input.

2. Hit the aforementioned key combos to move the text input caret and see that the caret doesn't move at all.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Mac 14.3.1

[84a853a7-df2f-4e5f-971b-c2d808a696c0](https://api.gamemaker.io/api/github/downloads/84a853a7-df2f-4e5f-971b-c2d808a696c0)

**Comment by SmithTom6304** [comment]
This seems to now be working for CE1 as of IDE v2024.400.0.539  Runtime v2024.400.0.558. CE2 still has issues on mac, but [have created a new ticket](https://github.com/YoYoGames/YoYoStudio/issues/9871) as it has a different approach.

**Comment by SamTHodson** [comment]
Verifying, as Tom says, the issue is no longer present in IDE v2024.400.0.539  Runtime v2024.400.0.558 for CE1

**Comment by alicemoretti** [comment]
Verified fixed for CE2 on  IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
