### ISSUE TITLE
In-Game: [HTML5] Bottom-right tile slot on a room layer is not rendered

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4890]
### Description
Hello again,

in the current HTML5 runtime, the "last tile" (bottom right corner) of a tiles-layer is not rendered, there's only a black square on the screen.

Please see the attached image

Kind regards,
Gris

### Steps To Reproduce
* Create a room of 1920x940
* Use a tileset of 64x64 - I used the one from your "World Tilesets" Bundle and attached it here
* Fill the room with a background tile, as shown in the picture
* Start the game in HTML
* you should see a black square in the bottom right corner - the last tile is not rendered

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[3ec12e88-e06d-4a7f-ac38-8d68a59a07d4](https://api.gamemaker.io/api/github/downloads/3ec12e88-e06d-4a7f-ac38-8d68a59a07d4)

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
