### ISSUE TITLE
Package Export: Show dependent resources that will be added to the package

### ISSUE THREAD

**Issue by stuckie** [YoYoGames/GameMaker-Bugs#4897]
### Is your feature request related to a problem?

Following on from https://github.com/YoYoGames/GameMaker-Bugs/issues/4875 it has been pointed out that we do not show the dependent resources that are automatically being added to a local package, based on the selected resources that a user has chosen.

We should show these so that the user is fully aware of what is being pulled into their local package, as this will allow them to make a more informed decision on what they are including.

### Describe the solution you'd like

We should additionally show dependent resources in the package exporter for all resources the user has explicitly selected.
These should not be allowed to be removed, so as not to break the package from being able to be loaded.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.533  Runtime v2024.400.0.552. 

When select to add an object with a parent to a local package in the Local Package Creation Tool, both the child and the parent are added to the list of resources in the package, with the parent being greyed out in the list. 

Thank you.
