### ISSUE TITLE
In-Game: Various layer functions return error when using references in 2024.400 runtimes

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#4902]
### Description

When using any of the various layer functions in the list below in IDE v2024.400.0.508  Runtime v2024.400.0.527, the following runtime error is returned:
<img width="433" alt="Runner_yKvIHbupvx" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/128076091/18803a5d-7a7a-4b27-afc6-e70d93415794">

The layer functions that return this error:
- layer_sequence_create()
- layer_get_depth()
- layer_get_x()
- layer_get_y()
- layer_get_hspeed()
- layer_get_yspeed()
- layer_destroy()
- layer_x()
- layer_y()
- layer_hspeed()
- layer_vspeed()
- layer_add_instance()
- layer_get_instance()
- layer_destroy_instances()
- layer_set_visible()
- layer_get_visible()
- layer_depth()
- layer_shader()
- layer_get_script_begin()
- layer_get_script_end()
- layer_get_shader()

This did not occur for any of these functions in IDE v2024.200.0.506  Runtime v2024.200.0.524, nor does it occur in IDE v2024.2.0.132  Runtime v2024.2.0.163.

[layer functions error.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14499268/layer.functions.error.zip)

### Expected Change

It is expected that the above layer functions will accept references, and the game runs without a runtime error being returned, to match the behaviour in IDE v2024.2.0.132  Runtime v2024.2.0.163.

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Open obj_test
4. Uncomment one of the functions marked as causing the error
5. Run game
6. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rikman81** [comment]
Can also confirm this bug when using IDE 2024.200.0.505 and Runtime 2024.400.0.527.

Rolling the runtime back to 2024.400.0.526 allows things to work as expected.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.400.0.510  Runtime v2024.400.0.529
