### ISSUE TITLE
Disabling particle system automatic draw and manually call it makes changes to rotation not apply

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#4903]
### Description

As you can see from the attached project it the particle system moves fine but the rotation that is being applied in the step event doesn't reflect in the draw call.

[Particle.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14498969/Particle.zip)

### Expected Change

manually calling draw on the particle system should keep all the updated properties

### Steps To Reproduce

1. Start GameMaker
2. Run the attached game
3. The particle system will move but not rotate

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by cameron-home** [comment]
Verified fixed in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
