### ISSUE TITLE
Switch to the docking branch of imgui

### ISSUE THREAD

**Issue by OmegaMetor** [YoYoGames/GameMaker-Bugs#4905]
### Is your feature request related to a problem?

No, I think the docking branch is better.

### Describe the solution you'd like

Switching from the main branch/release of imgui to the docking one

### Additional context

Imgui's docking branch is as far as I know pretty much a direct replacement, that adds the ability for the player to pull tabs out of the window, which is very nice to use.

**Comment by rwkay** [comment]
Fixed in 2024.6 - only enabled the basic docking behaviour just now so windows can be docked to each other (or put into tabs).

**Comment by YYBartT** [comment]
Added the new functionality under a new section on the Debug Overlay page.

**Comment by alicemoretti** [comment]
Verified done on  IDE v9.9.1.673  Runtime v9.9.1.815. 

Thank you.
