### ISSUE TITLE
Texture Groups: GM crash when assigning a texture group in a config other than "Default" in 2024.2

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#4906]
### Description
I have no idea how reproducible it is but when I re-opened the IDE it kindly suggested submitting a bug report so who am I to decline?

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[f477ae71-c6b4-41d4-892c-240909c52d5e](https://api.gamemaker.io/api/github/downloads/f477ae71-c6b4-41d4-892c-240909c52d5e)

**Comment by DragoniteSpam** [comment]
Update: it looks like it's 100% reproducible, and the UI log isn't very interesting. This is the last thing in it before the IDE dies:

    [16:15:24:864(2be0)] TextureGroup missing for Sprite - spr_boulder729 - resetting to Default Texture Group

**Comment by DragoniteSpam** [comment]
looked at the sprite.yy file and compared it to the source sprite that was duplicated, and the only meaningful change i see (ie not related to the sprite name or whatever) is this:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/e569e1b3-5bd1-40e9-86b3-6779a60ac2f5)

which feels like a problem in and of itself because the texture settings should be preserved when you do this, but when i manually edit the .yy file it still crashes when i open it

**Comment by DragoniteSpam** [comment]
aha, the issue seems to be that GM crashes whenever you (or it) try to assign a texture group to something. well, that would seem to narrow it down

**Comment by DragoniteSpam** [comment]
okay i figured it out: the crash only happens if you assign a texture group when you're in a non-`Default` config

[gamemaker dies if you assign a texture group on a non-default config.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14503051/gamemaker.dies.if.you.assign.a.texture.group.on.a.non-default.config.zip)

that was exciting. i need a vacation

**Comment by jonathan-markland** [comment]
@YYDan  I have a handle on this bug.

I like it when customers send cute bunnies for me to test with, this should be encouraged.

**Comment by Emc1923** [comment]
Verified fixed as of Beta IDE v2024.400.0.526 Beta Runtime v2024.400.0.547
