### ISSUE TITLE
Gaussian Blur Feedback

### ISSUE THREAD

**Issue by XorDev** [YoYoGames/GameMaker-Bugs#4912]
### Is your feature request related to a problem?

Hi,

I was taking a look at the Gaussian Blur filter code in C:\ProgramData\GameMakerStudio2 and I see a few areas that are of concern.

### Describe the solution you'd like

 Overall, the filter is decent for mobile devices. The multipass setup, downscaling, separable blur and use of texture interpolation are good, but I think a few small changes can significantly improve it with little effort:

1. **Too many surfaces**: This effect creates two surfaces for every downsample, for a maximum of 16 additional surfaces. You only need two full res surfaces and [ping-pong](https://mini.gmshaders.com/p/gm-shaders-mini-recursive-shaders-1308459) between them. The shader only needs to be applied to the scaled part of the surface, so you aren't even drawing additional pixels. Just saving VRAM by using fewer surfaces.
2. **Too many passes**: At 8 downsamples, 64 passes and both horizontal and vertical blurs, you get a maximum of 1024 draw calls and shader passes! This seems way too high.
3. **No need for the 2-9 cameras**: They are applied outside the surface targets, so they appear to be having no effect. All blurring can occur in screen space, so no camera work should be needed (except to draw to the surface in the first place).
4. **Downscaling should round up**: `_draw_width = floor(_draw_width / 2)` should use ceil instead. It's easier to see the problem when working with smaller values. If the width was 3, cutting it down to floor(3/2) == 1, which means one pixel is completely ignored. ceil(3/2) == 2, which gives a little padding around the edges to include the full image.
5. **g_sampledTextureDimensions is actually texel size**:  While not functionally important, texture dimensions implies resolution as opposed to texel size. Something like `g_sampledTexelSize ` seems more appropriate.
6. **Increase offsets with each pass**: Rather than blur a 7 texel area with each pass, you can progressively increase the offset distance to cover a larger area with fewer samples. Something like `shader_set_uniform_f(u_blurDirection, j, 0.0)` should do the trick.
7. **Blur radius control would be nice**: Setting a blur radius with this sort of multipass system can be a bit tricky, but it would allow for smoothly transitioning between blur levels (good for cutscenes or pause menus). The easiest way would be to allow for fractional g_numPasses values and multiplying the final pass blurDirection vector by the remainder. So the final pass of a 1.5 pass blur would be 0.5 distance. This way, you can smoothly transition between blur intensities without additional blur passes or variables.

Here are some additional resources on this topic:
[Kawase Blur](https://www.intel.com/content/www/us/en/developer/articles/technical/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html) - An extremely efficient blur that only uses 4 texture samples per pass for both horizontal and vertical blurring.
[Dual Kawase Blur](https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_slides.pdf) - A variant of the Kawase blur which utilizes downscaling and upscaling for rich, mobile friendly Gaussian blurring (locked to power of 2 blurs though).
[My implementation of Dual Kawase](https://github.com/XorDev/Dual-Kawase/wiki) - Already went through the trouble of porting it to GameMaker, so this is a good place to start.
[Blur Philosophy 1](https://mini.gmshaders.com/p/blur-philosophy) - The principles behind optimized blurring.
[Blur Philosophy 2](https://mini.gmshaders.com/p/blur2-draft) - Further improvements for blur shaders.

**Comment by JonnoRobson** [comment]
Thanks for the feedback on the new effect! I've addressed several of the points in some way and in the course of doing so also fixed some edge case crashes when minimising, resizing etc. The maximum number of passes that can be set has been reduced since the previous maximum was much higher than necessary and could cause noticeable performance issues. There is a new effect parameter "Intensity" that can be set between 0.0 and 1.0 which can be used to smoothly transition the blur intensity.
