### ISSUE TITLE
sprite_create_from_surface still returns a real instead of a ref

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4913]
### Description
The return of sprite_create_from_surface is still a real, not a ref. Using it works, but it's a little inconsistent with other sprites.

### Steps To Reproduce
```
var spr = sprite_create_from_surface(application_surface, 1, 1, 5, 5, false, true, 0, 0)
show_debug_message("Sprite created from surface:" + string(spr)); //shows a number, not a ref
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[793963b2-49d6-47d2-8f0a-9b5c89a78ab1](https://api.gamemaker.io/api/github/downloads/793963b2-49d6-47d2-8f0a-9b5c89a78ab1)

**Comment by rwkay** [comment]
looking at the code I think `sprite_replace` and `sprite_duplicate` also need to have the return value made into a handle.
