### ISSUE TITLE
 Extremely slow opening/closing of asset picker window

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4915]
### Description
Whenever I try to change an object with the small asset picker window it takes multiple seconds to open and close. I attached a recording. The project and the IDE are both on a SSD and I have no performance issues with other programs and this problem didn't show up in older versions of GameMaker.

At first I thought it might be caching related but multiple times of opening and closing didn't affect the amount of time it took.

I also just did a fresh reinstall of GameMaker following this guide: https://help.gamemaker.io/hc/en-us/articles/115002062812-How-to-perform-a-fresh-install-of-GameMaker

I was hoping to get rid of the sluggishness of the IDE as reported here: #2528

If you need the project files, I submitted them in a private ticket yesterday (it had a Dropbox DL link)

### Steps To Reproduce
1. Open the sprite picker of an object window.

[93438de0-122b-40b0-9aba-a442e63028cc](https://api.gamemaker.io/api/github/downloads/93438de0-122b-40b0-9aba-a442e63028cc)

**Comment by yyalansavage** [comment]
This should have been largely addressed by fix for this issue https://github.com/YoYoGames/GameMaker-Bugs/issues/2503 which went into February release.
Above commit makes some further improvements which may also have been a factor in this particular issue.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
