### ISSUE TITLE
game_restart does not clean up debug overlay

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4916]
### Description
I created a custom debug view to try out different sprites for in-game currency. This is the code I used:

ref = ref_create(self, "current_currency_sprite");
dbg_view("Currency", true);
dbg_slider(ref, 0, array_length(currency_sprites)-1);

When I restart the game using game_restart the debug view just gets more and more sliders added.

### Steps To Reproduce
1. Call game_restart
2. Check any custom debug views

[433f1942-86ff-4d31-8ab8-0065aad92e31](https://api.gamemaker.io/api/github/downloads/433f1942-86ff-4d31-8ab8-0065aad92e31)

**Comment by stuckie** [comment]
This is by design.
