### ISSUE TITLE
CLI exemples incorrectly use Mac Package instead of Mac PackageDMG or PackageZip

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4917]
### Description

CLI exemples incorrectly use Mac Package instead of Mac PackageDMG or PackageZip

### Manual Link

https://manual.gamemaker.io/monthly/en/Settings/Building_via_Command_Line.htm

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
