### ISSUE TITLE
Silent Crash when using `struct_remove` with a built in name.

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#4922]
### Description

The attached project will crash within a few iterations, it is adding and removing elements to a struct

The crash only happens when builtin names are used in the struct

[StructRemoveBuiltIns.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14512232/StructRemoveBuiltIns.zip)

### Expected Change

Not Crash

### Steps To Reproduce

1. Start GameMaker
2. Import attached project
3. Run the project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.4

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.523  Runtime v2024.400.0.544, thanks.
