### ISSUE TITLE
Release Notes: Go back to manually-written pages which summarise the content in the milestone, rather than adding this content into the milestone description

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#4923]
### Is your feature request related to a problem?

I just made this request #4921, but it's a bit of a half measure that doesn't really solve the problem. So, I'm also making this request to go back to what we had before that did work. I've talked to many people who don't read the release notes at all with the swap to having it all on github, or people who do try to read it but end up missing things due to the confusing format.

### Describe the solution you'd like

Go back to having manually written release notes on the main release notes page, or at least have the link from GM take you directly to a page that lists out the changes at the top. Requiring users to dig through a bunch of different links and hundreds of github issues just leads to people not reading anything and having no idea what changes happened.

**Comment by gnysek** [comment]
Seems to be related to https://github.com/YoYoGames/GameMaker-Bugs/issues/4506

**Comment by YYDan** [comment]
This is being discussed already.

**Comment by YYDan** [comment]
That last bit, we're not doing, as that would mean the release notes could never be edited to fix things post-release. You will continue to be offered a website to read the current content of the notes.

**Comment by gnysek** [comment]
Btw.: https://releases.gamemaker.io/

**Comment by YYDan** [comment]
Hehe, yes, that page is live already and was announced a little while back, but we have been playing around with a few more additions/changes there before I claimed this one to be Done and closed the issue; however, those fixes are in place now and working properly in the current version of the published pages, so Closing.

(We are yet to make the IDE send you to the new page by default, but that's being tracked for another issue - this one about moving the info to a consolidated place and more readable pages is done.)

**Comment by Emc1923** [comment]
Closing this one as well, as now the IDE takes you to the new release pages site: https://github.com/YoYoGames/GameMaker-Bugs/issues/5204
