### ISSUE TITLE
In-Game: [HTM;5] HTTP Async event is broken in LTSr1 and r2

### ISSUE THREAD

**Issue by sp202** [YoYoGames/GameMaker-Bugs#4925]
### Description

HTTP async event doesn't run at all on latest LTS (2022.0.2), bug originally introduced in 2022.0.1

Example project:
[http_async_bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14514732/http_async_bug.zip)

### Steps To Reproduce

1. Make a GET request for example
2. Async event won't run

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

HTML5

**Comment by mgeddesGM** [comment]
verified in  IDE v2022.0.3.65  Runtime v2022.0.3.78
