### ISSUE TITLE
Make stack traces unambiguously parsable via non-`_` separators

### ISSUE THREAD

**Issue by adam-coster** [YoYoGames/GameMaker-Bugs#4927]
### Is your feature request related to a problem?

Let's say I've got a script called `My_Script`, inside of which is a constructor called `My_Constructor`, inside of which is a function called `my_function`.

If I look at a stack trace that includes it, or look at the debugger data, that location is represented by the string:

`gml_Script_my_function@My_Script_My_Constructor`

This string is **not** unambiguously parseable due to the use of `_` to separate the components, since that character is also valid in resource/variable names.

The right side of the `@` above could be interpreted as any of:

- `Script_My_Constructor` inside of `My`
- `My_Constructor` inside of `My_Script`
- `Constructor` inside of `My_Sript_My`

For projects of any significant size and complexity, these identifiers quickly become nearly useless for both human- and machine-parsing.

### Describe the solution you'd like

This would be easily fixed for the typical use-case by using a separator that *isn't* allowed in variable names (I know there's still some weirdness since struct variables can be nearly any string, but that's at least pretty easy to avoid).

Ideally there would be a different separator character for each kind of separation to make it *really* unambiguous and easy to machine-parse, but even just replacing the `_` with `:`, `|`, `>` or *something* would be a huge improvement.

**Comment by adam-coster** [comment]
Note that thing that matters most here is being able to unambiguously identify the *file*, since that in combo with the line number makes it trivial to go from a log/trace to the corresponding code.

**Comment by gnysek** [comment]
`/` could also be used there, as that's also forbidden character in script names.

**Comment by rwkay** [comment]
Fixed in 2024.4 - User can split on '@' and will get distinct components - each '@' indicates a containing relationship from the inside out
So the name gml_Script_bar@my_function@My_Constructor@My_Script indicates a function called bar inside a function called my_function inside a function called My_Constructor inside a script asset called My_Script

**Comment by adam-coster** [comment]
@rwkay amazing, thank you!
