### ISSUE TITLE
Feature: add a function to check if dbg_view exists

### ISSUE THREAD

**Issue by blaiddx64** [YoYoGames/GameMaker-Bugs#4931]
### Is your feature request related to a problem?

Add a function to check if a given dbg_view exists.

### Describe the solution you'd like

Something like is_debug_overlay_open() or instance_exists(), but for debug views.

**Comment by rwkay** [comment]
Functions added in 2024.4 - Added `dbg_view_exists` and `dbg_section_exists`. 

Test project for the new functions - 
[DebugViewSectionExists.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14560050/DebugViewSectionExists.zip)

**Comment by YYBartT** [comment]
Documented the new functions `dbg_view_exists()` and `dbg_section_exists()`.

**Comment by alicemoretti** [comment]
Verified done in the project attached on IDE v2024.4.0.137  Runtime v2024.4.0.168.

Thank you.
