### ISSUE TITLE
In-Game: [HTML5] Bottom-right tile slot on a room layer is not rendered (now with project)

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#4933]
### Description
Hey there,

re-post of #4890, where you asked me to attach a project.
In the current HTML5 runtime, the "last tile" (bottom right corner) of a tiles-layer is not rendered, there's only a black square on the screen.

So, here we are, project attached

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/9bb73d6c-8e66-46df-991b-77beb955873d)

kind regards,
Gris

### Steps To Reproduce
* Create a room of 1920x940
* Use a tileset of 64x64 - I used the one from your "World Tilesets" Bundle and attached it here
* Fill the room with a background tile, as shown in the picture
* Start the game in HTML
* you should see a black square in the bottom right corner - the last tile is not rendered

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[baf371d5-e153-43c2-8e2b-94df724b0bda](https://api.gamemaker.io/api/github/downloads/baf371d5-e153-43c2-8e2b-94df724b0bda)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.519  Runtime v2024.400.0.540, thanks.
