### ISSUE TITLE
Debugger disconnects when hovering an enum in the debugger code window.

### ISSUE THREAD

**Issue by FrancisCoulombe** [YoYoGames/GameMaker-Bugs#4935]
### Description
On the attached project, the debugger disconnects from the game during a playtest if, while execution is paused at a breakpoint, the user mouses over an enum in the debugger code window.

Extra details:

As far as I can tell, this has been an issue for about one year, it is not a recent problem.
This happens anywhere in the games' logic past a certain point in the games' initial loading sequence. (the obj_gameinit step event in the attached project)
The reproducing steps are based on the earliest moment where I could reliably reproduce the issue, which is right after the game is done loading a set of CSV files containing dialogue.
if you place a break point earlier in that step event, the debugger does not disconnect, but when hovering an enum the pop-up window that says "unable to evaluate" takes a few seconds to appear, and the runner appears to stop responding during that moment.
If you place the break point even higher in the script, the pop-up appears faster. At the top of the script, it seems to appear immediately.

I tried trimming as much as I could from the project to isolate the issue, but it seems the issue disappears if I remove too many scripts from the game.
Deleting many of the scripts in the FighterDB folder or the ItemDB folder makes the issue go away, even if those scripts were not run at any point in the test.
Maybe the issue is tied somehow to the number of symbols the runner needs to keep track of?

### Steps To Reproduce
Place a break point in the step event of obj_gameInit, on line 175.
Run the game in debug mode.
The game will begin setting up and loading csv language files, then will pause execution when it reaches the break point.
While execution is paused, hover the mouse cursor over eStat.s_acc on line 174. You should notice the pop-up window  meant to show the symbols value will not appear.
After a few seconds, the debugger disconnects from the game, and game execution resumes. The green light that indicates the debugger is connected to the game turns red.

[9c97e612-7909-490c-9e0f-21d1ae6cd867](https://api.gamemaker.io/api/github/downloads/9c97e612-7909-490c-9e0f-21d1ae6cd867)

**Comment by yyalansavage** [comment]
Fixed to prevent the disconnect (this only happens for larger projects); note the debugger is still unable to evaluate the value of an an enum constant

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.525  Runtime v2024.400.0.546
Ensure the file **_post_build_step.bat_** is removed from the project root in order for the project to run
