### ISSUE TITLE
Project Save: Manually changing the Save As filter to the ".yyp" entry stops most files being written-out to the new location

### ISSUE THREAD

**Issue by Pictogram23** [YoYoGames/GameMaker-Bugs#4939]
### Is your feature request related to a problem?

When opening .yyz and resaving as .yyp we have a option, `Project Name (*.*)` or `GameMaker Project (*.yyp)`.

But, if we choose `GameMaker Project (*.yyp)` GameMaker will only write out 2 files to the new location - the main project .yyp and the resource_order file.

<img width="473" alt="report" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/78887244/2bb4ee99-7fe0-4075-a8f9-1b27ced23c8d">

(The language in this picture is Japanese, not English. I'm sorry.)

### Expected Change

Remove the filter option "GameMaker Project (*.yyp)", so that this issue cannot be created

**Comment by scott-dunbar** [comment]
This is using Save As from File menu.

1. Open any project
2. Click File -> Save Project As
3. Select Save As Type and change from Project Name (*.*) to  GameMaker Project (*.yyp)
4. Click Save
5. Open the directory of save location
6. Observe only yyp and resource_order file are saved

**Comment by YYDan** [comment]
Changed this one to be a bug, as we have now confirmed the issue and that it affects any usage of the Save As window (which is all that the .yyz example is doing).
