### ISSUE TITLE
Code Editor: Still possible to get dropped keystrokes when typing

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4941]
### Description
Sometimes, the code editor drops keystrokes.  Meaning that when I hit several keystrokes in a row, usually involving cursor movement and typed characters, sometimes a keystroke doesn't register at all.  See attached video for demonstration.

In the video, I repeat the following keystrokes several times to add a character in the same position on each line:

Up Arrow - Left Arrow - x

In this case, I am trying to insert an "x" in the same column in each row of text, resulting in a straight column of x's amidst the dots.  But you will see that sometimes the "x" keyhit doesn't register, and other times it's one of the arrow keyhits that don't register due to the fact that some of the rows are missing x's and one of the rows ends up with an x in the wrong column because arrow keyhits were dropped along the way.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Mac 14.3.1

[513049a9-29c1-466c-8f6f-aae7f58abee0](https://api.gamemaker.io/api/github/downloads/513049a9-29c1-466c-8f6f-aae7f58abee0)

**Comment by PrismaticRealms** [comment]
This is the same issue that I reported back in bug #2545

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.4.0.137  Runtime v2024.4.0.168 on both Mac and Windows, thanks.
