### ISSUE TITLE
Feather incorrectly reports that texturegroup_set_mode needs at least 3 arguments when it needs only one

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4945]
### Description

Feather incorrectly reports that texturegroup_set_mode needs at least 3 arguments when it needs only one 

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/Textures/texturegroup_set_mode.htm

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.513  Runtime v2024.400.0.533
