### ISSUE TITLE
Adding resources[In this case sprites] bricks some of the games programming

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#4957]
### Description

Basically i had some gimmicks and bug fixes that bricked once i added sprite

### Steps To Reproduce

Video is over 10 megs, so here's the link of the video i posted in GameMaker discord server, it shows how i reproduce it: https://cdn.discordapp.com/attachments/801143023894396962/1215823907014316142/2024-03-09_01-41-581.mp4?ex=65fe2740&is=65ebb240&hm=2ac6001b122a7aa6186eff65bbfb231f04cc6afcd5c50d9a974240b72746e929&

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

Additionally, we would need a ui.log to see if there are any issues the IDE has reported as well.

**Comment by DarkD04** [comment]
Hey sorry for late response, i will provide UI log but i also noticed whole YYP shuffles resources when they get added as evident in this screenshot, left is unmodified after conversion and right is modified after conversion
![slika](https://github.com/YoYoGames/GameMaker-Bugs/assets/68426621/ad5e57b5-d2b9-4230-bbe4-7c6de459a769)

Is there a way i could send my source code privately because i wasn't able to replicate this bug again, seems like it might be only my game specific issue.
[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14615896/ui.log)
