### ISSUE TITLE
Importing an object crashes GameMaker.

### ISSUE THREAD

**Issue by PrismaticRealms** [YoYoGames/GameMaker-Bugs#4968]
### Description
I am attempting to import an object into my project from another project and the process ends up crashing GameMaker.

The project I am importing from was just created yesterday.  The project I am importing to is a couple of months old (previous GM version) but has since been converted into the new GM file format.  The crash also occurs if I export my project to a new YYZ, open that as a new project and wipeout most of the assets in the project (which is what is being attached to this issue now) prior to importing the object.

See attached zip file for crash report, screenshot of crash and project to import object from.

### Steps To Reproduce
(1) In the attached zip file, extract the ImportFrom YYZ and open it to install the project.
(2) Close that project, and open the project that is attached to this bug report.
(3) In the Asset Browser, right click and choose Add Existing and navigate to the ImportFrom project and try to import the object named oSpaceman.yy. 
(4) This is where GameMaker crashes.  There is the odd time in which GameMaker just hangs there forever trying to import the object, but 9 times out of 10, the app just crashes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Mac 14.3.1

[cebe85c0-8d5c-4019-b5b8-db3b53646ec4](https://api.gamemaker.io/api/github/downloads/cebe85c0-8d5c-4019-b5b8-db3b53646ec4)

**Comment by stuckie** [comment]
Fixed as part of https://github.com/YoYoGames/YoYoStudio/issues/9510

**Comment by sihammill** [comment]
Verified in IDE v2024.400.0.533  Runtime v2024.400.0.552
