### ISSUE TITLE
Code Editor: array_contains_ext()'s "matchall" is optional in documentation, but GM expects it

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#4973]
### Description

The page for `array_contains_ext()` lists the "matchall" argument as optional, but GM will show a warning if it's not included. The game will still work even without it though!

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/af2bff1a-e551-48fe-8275-4e04c4690aa2)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/15b498cd-ffad-4907-8f34-ba1357bac761)

The documentation also doesn't specify the default value of "matchall" if it's not included:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/27ae642d-74df-43d8-86cf-f868f63c55c8)

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Variable_Functions/array_contains.htm

**Comment by YYDan** [comment]
The manual is correct and the GMLSpec file for Feather appears correct also. However, the fnames file used by Syntax Errors (if Feather is disabled) does not think it's optional, so we'll fix that.

**Comment by YYDan** [comment]
Hmmm... Okay, so Feather has mixed messages also:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/a980f9c1-6065-4df4-bba0-e36ad75e459c)
vs
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/b9b50725-fe03-4809-bb59-76009d7f339a)

**Comment by DiasFranciscoA** [comment]
The problem is in `fnames` (as mentioned). Feather is not responsible for generation the bottom-of-the-window suggestion.. that suggestion depends only on `fnames`. Fixing `fnames` vs `gmlspec` mismatch.

**Comment by backYard321** [comment]
@YYDan thanks! I still think it should be specified in the documentation whether `matchall` is true or false by default though.

**Comment by YYBartT** [comment]
Documented the default value of `false` of the `matchAll` parameter in the manual.

**Comment by backYard321** [comment]
> Documented the default value of `false` of the `matchAll` parameter in the manual.

Thank you!

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
