### ISSUE TITLE
Skeleton animation query functions may not return correct state (part of #1895)

### ISSUE THREAD

**Issue by yoyo-danielc** [YoYoGames/GameMaker-Bugs#4974]
### Description

When calling a skeleton animation query function (i.e. `skeleton_animation_is_finished()`, `skeleton_animation_get_frame()` or `skeleton_animation_get_position()`), the return value may not reflect the actual current state of the object - it actually reflects whatever last updated the instance's animation state, which may have been a draw call, collision check or possibly other things I'm forgetting. If the instance is never drawn/collided then the status is never updated.

This has been split out of #1895 to disambiguate the two bugs.

### Steps To Reproduce

1. Start GameMaker
2. Run the attached project
3. Observe the animation stops after a while at 24 FPS, draw_mode = "draw_sprite_ext"
4. Observe the animation stops with draw_mode = "none"

[SpineLowFPS2024_draw_ext.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14559827/SpineLowFPS2024_draw_ext.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.521  Runtime v2024.400.0.542.

Thank you.
