### ISSUE TITLE
Preferences: Shortcut key for opening Prefs requires clicking elsewhere before it will work again after closing Preferences

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#4975]
### Description

When using the shortcut keys to open the Preferences window, it will work the first time but fail to work after closing the window. 
Clicking elsewhere in the IDE is required before the shortcut will start working again.

https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/6e4d343c-cb9d-44ce-a28c-ba3619ba3b6b

Tested using IDE v2024.400.0.512  Runtime v2024.400.0.530

[Contact Us Package](https://drive.google.com/file/d/1vqlz4VxkRNgb1fYUQzbtVZTIFKy4Kaym/view?usp=sharing)

### Expected Change

Preferences window opens consistently like it did in previous IDE versions

### Steps To Reproduce

1. Start GameMaker Beta
2. Use 'Ctrl+Shift+P' to open the Preferences window
3. Close the window
4. Attempt to open the window again via 'Ctrl+Shift+P'
5. Observe the issue
6. Click anywhere on the IDE
7. Observe Preferences will now open when using the shortcut

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Seems to have been fixed by the hotkey fixes from a while back.
