### ISSUE TITLE
CLI doesn't produce a valid zip for Igor's Mac PackageZip

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4982]
### Description
This is on Windows IDE, to a Mac Mini machine.
Packaging the zip through the IDE doesn't produce errors as far as I can see.

Windows Explorer cannot extract the file (invalid) and while 7zip can it produces the following warning : `There are some data after the end of the payload data`
Comparing in WinMerge an IDE produced zip build and a CLI one reveals some differences in binaries/images and text files though no missing/extra files (I've attached both zips)

Here is the Igor command used : 
`Igor.exe /uf=%_gm_user_folder% /rp=%_gm_runtime_folder% /project=%_gm_project_folder% /cache=%_gm_cache_folder% /lf=%_gm_licence_plist% /runtime=YYC /of="%_gm_build_folder%\Mac\Chronique des Silencieux.app" /tf="%_gm_build_folder%\Mac.zip" /config=Release_Steam  /device="Mac Mini" /df=%_gm_device_json% -- Mac PackageZip`

Not sure if it's related but I get the following message at the end of the `-- Mac Clean` output :

```Options: C:\GMBuildCache\PlatformOptions.json
No target options set, build will fail!
Options: C:\GMBuildCache\ExtensionOptions.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at Igor.MacBuilder.Clean()
 ```

### Steps To Reproduce
Build the game via CLI on Mac

[12a95000-2c56-4954-a537-12daa8ef600d](https://api.gamemaker.io/api/github/downloads/12a95000-2c56-4954-a537-12daa8ef600d)

**Comment by DiasFranciscoA** [comment]
Hello @patchuby, we have attempted to reproduce the reported issue but have been unsuccessful thus far. Could you please confirm whether you are still experiencing this problem with the latest version of the Steamworks extension?

> [!NOTE] 
> If you include the `/uf` argument in the CLI, you won't need to specify paths for the license file (`/lf`) or the devices file (`/df`).

**Comment by patchuby** [comment]
Hey @DiasFranciscoA , after updating the Steamworks Extension the build just fails with the following message : 
```[STEAMWORKS] INIT: Script initialization succeeded (v1.6.3 :: 1).
Resolve-Path : Cannot find path 'C:\GMS\redistributable_bin\osx\libsteam_api.dylib' because it does not exist.
At 
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:110 
char:36
+                 $pathsToProcess += Resolve-Path $Path | Foreach-Objec ...
+                                    ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\GMS\redistri...steam_api.dylib:String) [Resolve-Path], ItemNotFoundE 
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
 
[STEAMWORKS] ERROR: Invalid Steam SDK version, sha256 hash mismatch (expected v1.55).


C:\GMS\extensions\Steamworks\post_build_step.bat exited with non-zero status (1)```

`C:\GMS` is the project folder. Also don't know why it's saying invalid Steam SDK version, I have not touched it.

**Comment by patchuby** [comment]
@DiasFranciscoA Tried with updated extension, same message from explorer and same warning from 7zip : 

```
Stats : GMA : sp=891,au=351,bk=0,pt=3,sc=5166,sh=50,fo=6,tl=0,ob=54,ro=2,da=441,ex=3,ma=1127,fm=0xDA40B3BF7FFE7FB4
Options: C:\GMBuildCache\MainOptions.json
[STEAMWORKS] INIT: Script initialization succeeded (v1.6.3 :: 1).
"Copying macOS (64 bit) dependencies"


mkdir -p "/Users/tomallibert/GameMakerStudio2/Mac/GM_MAC/Chronique_des_Silencieux/Chronique_des_Silencieux"
mkdir -p "/Users/tomallibert/GameMakerStudio2/Mac/GM_MAC/Chronique_des_Silencieux/Chronique_des_SilencieuxFromPC"
pscp C:\CDS-Builds\Mac\Chronique_des_Silencieux/ /Users/tomallibert/GameMakerStudio2/Mac/GM_MAC/Chronique_des_Silencieux/Chronique_des_SilencieuxFromPC/

7-Zip (a) 23.01 (x86) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 859925481 bytes (821 MiB)

Extracting archive: C:\CDS-Builds\Mac.zip

WARNINGS:
There are data after the end of archive

--
Path = C:\CDS-Builds\Mac.zip
Type = zip
WARNINGS:
There are data after the end of archive
Physical Size = 859924544
Tail Size = 937
Characteristics = Local Central

Everything is Ok

Archives with Warnings: 1

Warnings: 1
Folders: 16
Files: 825
Size:       971993740
Compressed: 859925481
```

**Comment by patchuby** [comment]
For posterity, the issue was likely with using the /df and /lf arguments in combination with the /uf argument, as @DiasFranciscoA mentionned, only /uf is necessary.
