### ISSUE TITLE
Video Player not working in macOS but works in windows. 

### ISSUE THREAD

**Issue by hamsandvich** [YoYoGames/GameMaker-Bugs#4984]
### Description
I upgraded my project to 2024 and it broke the way the video player works in macOS 

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_backgroundVideo:

Trying to use non-existing surface.
 at gml_Object_obj_backgroundVideo_Draw_0 (line 10) -     draw_surface(_surface, _vx, _vy); 
############################################################################################
gml_Object_obj_backgroundVideo_Draw_0 (line 10)

### Steps To Reproduce
open the porject on mac os upgrade it to 2023 and run it on a mac. 

There seem to be issues with the runtime.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Mac 14.2.1

[c87c15a6-d348-4fa3-b0a1-2245d2d026bd](https://api.gamemaker.io/api/github/downloads/c87c15a6-d348-4fa3-b0a1-2245d2d026bd)

**Comment by hamsandvich** [comment]
so i also tried it on tvOS, iOS the its the same issue there. 

If i downgrade the runtime i don't have that issue anymore
<img width="1728" alt="Screenshot 2024-03-11 at 7 53 19 PM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/72324766/5fa6b2b3-ae44-4e90-b2e7-58a6f9c64083">

**Comment by jackerley** [comment]
The project is working fine on Mac for me in runtime 2024.400.0.551 Can you try in a Beta release and confirm if you still have an issue? Please reopen the issue if you are still having problems

**Comment by KNGKRMSN** [comment]
Same problem for me, Runtime 2024.2.0.163
