### ISSUE TITLE
`handle_parse()` doesn't work on time sources

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#4985]
### Description
As the title suggests, using `handle_parse()` on a time source results in `ref unknown 0`.

### Steps To Reproduce
Example code (as in submitted project):
```js
var ts = time_source_create(time_source_game, 20, time_source_units_frames, function() {
	show_debug_message("hi");
})

time_source_start(ts);

show_message($"the time source: {handle_parse(string(ts))}");
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[88426073-b258-4b86-b4f6-6cd75878a579](https://api.gamemaker.io/api/github/downloads/88426073-b258-4b86-b4f6-6cd75878a579)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.400.0.526  Runtime v2024.400.0.547
