### ISSUE TITLE
The order of instance execution events has changed to sort by the name of the object

### ISSUE THREAD

**Issue by RidleyHungerZ** [YoYoGames/GameMaker-Bugs#4991]
### Description

In the past, the execution order of instance events was sorted by instance ID, but after the update, the execution order of instances became sorted by objectname, which caused a huge problem in my project design logic and forced me to change the name of objects in a messy manner to achieve the original design effect. 
Please change the order of instance event execution back

### Expected Change

The order of instance execution events is sorted by instance ID as usual

### Steps To Reproduce

1. Start GameMaker
2. Create objects obj_A, obj_B, obj_C
3. Place obj_C in the room, create obj_B in the create event of obj_C, and then create obj_A in the create event of obj_B
4. Print the object name of each of the three objects in the step event
5. As a result, obj_A will be executed first, followed by obj_B and obj_C
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by backYard321** [comment]
Not a major fan of this either!

**Comment by RidleyHungerZ** [comment]
I just discussed with other users and found that it may be in the order of object_index, and when importing the 2024 version of the old project, it may have been regenerated based on the name of the object.

**Comment by attic-stuff** [comment]
> I just discussed with other users and found that it may be in the order of object_index, and when importing the 2024 version of the old project, it may have been regenerated based on the name of the object.

not sure if you are the same person as the person reporting this on discord, but just in case: the order in which objects execute their step events is not to be relied upon. it changed recently, it has changed in the past, and it will change again. this is deliberate, and it is the reason that the order is not documented in the manual. if you need obejcts to execute their step events in a specific order, you should be using the begin step, step, and end step events to achieve the goal OR you should be using your own manager object that calls each object's logic as an ordered function.

**Comment by attic-stuff** [comment]
> The previous execution order can be restored using the old resource_order file

you should not do this; you should not be relying on the order in which instances execute their step events. it is not a bug that the order is not predictable or that the order changes, that is by design.
