### ISSUE TITLE
Feature: Accept multiple refs on dbg_slider and dbg_checkbox functions

### ISSUE THREAD

**Issue by blaiddx64** [YoYoGames/GameMaker-Bugs#4997]
### Is your feature request related to a problem?

When a developer have a list of variables that needs to have the same value and it needs to create a dbg_slider/dbg_checkbox, at the moment, the developer needs to update each one manually to same value.

### Describe the solution you'd like

Add the option to pass an array of refs on ref parameter, and update all refs when change the slider/checkbox value.

Example:
```gml

var test1 = ref_create(self, "test1");
var test2 = ref_create(self, "test2");
var test3 = ref_create(self, "test3");

dbg_slider([test1, test2, test3], 0, 10);
```

Also, the value showed on first time can be the index 0 from the array, case values are different when passed to dbg_slider/dbg_checkbox.

**Comment by rwkay** [comment]
I am thinking that we could do that with all these functions

```
dbg_slider(dbgRef,[minimum],[maximum],[label],...)
dbg_slider_int(dbgRef,[minimum],[maximum],[label],...)
dbg_drop_down(dbgRef,specifierOrArrayValues,[labelOrArrayLabels],[label]...)
dbg_watch(dbgRef,[label],...)
dbg_text(dbgRefOrString)
dbg_sprite(dbgRefSprite,dbgRefSpriteIndex,[label],[width],[height]...)
dbg_text_input(dbgRef,[label],[type]...)
dbg_checkbox(dbgRef,[label],...)
dbg_colour(dbgRef,[label],...)
```

**Comment by cameron-home** [comment]
Verified in IDE v2024.600.0.563  Runtime v2024.600.0.580
