### ISSUE TITLE
Feature: Add imgui TextSeparator option on debug views

### ISSUE THREAD

**Issue by blaiddx64** [YoYoGames/GameMaker-Bugs#4998]
### Is your feature request related to a problem?

imgui have the text separator feature that helps to organize things, it would be really useful on debug views.

Example:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103244351/55965754-9f55-4b7e-8fc7-8cdc5e404968)

### Describe the solution you'd like

add TextSeparator function:

```gml

dbg_text_separator("General"); // this
dbg_checkbox(ref_create(self, "test1"), "test1");
dbg_checkbox(ref_create(self, "test2"), "test2");

dbg_text_separator("Widgets"); // this
dbg_checkbox(ref_create(self, "test3"), "test3");
dbg_checkbox(ref_create(self, "test4"), "test4");

```

**Comment by rwkay** [comment]
Added feature in 2024.6

new function `dbg_text_separator(dbgRefOrString)` added 

Creates a text separator entry (from a variable) within the current debug section, this text can be multiline and is not split into 2 columns but shown in a single column. NOTE: if no section is declared a "Default" section will be created.

**Comment by YYBartT** [comment]
Added new function reference page for `dbg_text_separator`.

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.672  Runtime v9.9.1.814
