### ISSUE TITLE
"If Object At Place" tutorial seems to have a wrong example description.

### ISSUE THREAD

**Issue by Alexoridk** [YoYoGames/GameMaker-Bugs#5013]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/106972719/392b1c35-3614-4705-b486-7cdeb8e1f3ed)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/106972719/5c990217-da1b-4f7f-af76-d026e5363ddd)

### Manual Link

http://127.0.0.1:51290/index.htm#t=Drag_And_Drop%2FDrag_And_Drop_Reference%2FCollisions%2FIf_Object_At_Place.htm&rhsearch=if%20object%20at%20place&rhhlterm=if%20object%20place

**Comment by gurpreetsinghmatharoo** [comment]
Thanks, it's fixed now

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
