### ISSUE TITLE
Layer_get_id inconsistent documentation re: result when non-existent layer as input.

### ISSUE THREAD

**Issue by judacraz** [YoYoGames/GameMaker-Bugs#5014]
### Description

Documentation says "Note that if you give the name of a layer that does not exist in the current room, then you will get an error and the project will crash.", which is contradictory to the returns section stating "Layer ID or -1 (if the layer specified doesn't exist)"

Tested, and the actual result is -1 with no crash.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/General_Layer_Functions/layer_get_id.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
