### ISSUE TITLE
Specify behaviour of time_source_destroy for built-in time sources

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#5015]
### Description

Apparently, you can't destroy built-in time sources with `time_source_destroy` (i.e. `time_source_game` and `time_source_global`). However, you can still destroy all the descendant sources.

Here's what fujj said on GameMaker Discord, in the beta channel:
> Yes, time_source_destroy won't destroy a built-in time source but [time_source_destroy(time_source_game, true);] can be used as a shortcut to destroy all of its children.

So I suggest that the documentation:
- specifies that neither of built-in time sources can be destroyed
- mentions that you can still use this function with built-in time sources to destroy descendants (by setting "destroy_tree" argument to true)

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FTime_Sources%2Ftime_source_destroy.htm

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
