### ISSUE TITLE
SDF font characters can become vertically offset if they are accented.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#5020]
### Description

When displaying large characters with accents using an SDF font, the characters become offset vertically, as shown in the screenshot. I have also included un-accented characters for comparison.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/26627245/a82b20f4-bbcb-45f3-b7ba-4dc534b2c1a5)

The font I am seeing this issue with is called "[Bungee](https://fonts.google.com/specimen/Bungee?preview.text=%C3%84l%C3%A4%20sy%C3%B6%20%C3%A4yri%C3%A4isi%C3%A4%20%C3%B6isin.)". This font doesn't have any vertical offset issues when displayed in other programs. I am unsure if this issue is present when using other fonts, but it definitely exists for this one!

Here is how the same phrase is shown on the Google Fonts page, which is how I would expect it to look in-game:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/26627245/dd84c3f7-8108-4fb9-9543-da2240ba3aad)

I have included a sample project that shows the issue:
[SDFOffsetPackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14594202/SDFOffsetPackage.zip)

### Expected Change

Fonts should draw their characters vertically aligned with one another.

### Steps To Reproduce

1. Start GameMaker
2. Open the sample project.
3. Run the project.
4. Observe that accented characters are vertically offset.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by BscotchSeth** [comment]
We're getting nearer to launch and our fonts are still out of whack. Any way we can bump up the priority on this?

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
