### ISSUE TITLE
Manual: Show Virtual Keyboard's GML Visual Action's Example Is Incongruous

### ISSUE THREAD

**Issue by ParodyKnaveBob** [YoYoGames/GameMaker-Bugs#5023]
### Description

The manual page for Show Virtual Keyboard (GML Visual) has the following example:

> Example:
> ![Show Virtual Keyboard action alone with default settings](https://manual.gamemaker.io/monthly/en/assets/Images/Scripting_Reference/Drag_And_Drop/Reference/Mouse_And_Keyboard/a_VirtualKeyboard_Show.png)
> The above action block code checks for a mouse down action, and if one is detected, then a check is performed to see if the OS virtual keyboard is showing. If it isn't then it is set to show - using a numeric keypad type - and if is already showing then it is hidden.

The above action block code *does nothing of the sort*. $E^ b The image uses `a_VirtualKeyboard_Show.png` instead of `e_VirtualKeyboard_Show.png`, but even then, the real example image doesn't match the example text:

![Show Virtual Keyboard (GML Visual) example but with default settings instead of using the numeric keypad type](https://manual.gamemaker.io/monthly/en/assets/Images/Scripting_Reference/Drag_And_Drop/Reference/Mouse_And_Keyboard/e_VirtualKeyboard_Show.png)

This uses a **generic** type instead of **numeric** type. $;^ J The `kbv_type_default` entry should be `kbv_type_numbers` instead.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=Drag_And_Drop%2FDrag_And_Drop_Reference%2FMouse_And_Keyboard%2FShow_Virtual_Keyboard.htm

**Comment by gurpreetsinghmatharoo** [comment]
Learned a new word today. $B-)

Fixed, thank you for the report
