### ISSUE TITLE
Explicitly state the order of objects within an event is unspecified

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#5029]
### Description

This problem happens every once in a while, when developers rely on a certain order of objects executing their events, then GM changes it, then people complain the code stops working in the newer version. In particular, I've heard of the following orders used as a proxy for in-event execution order:
- according to the drawing layer order
- according to the instance creation order

In the Event Order page, please add a note like the following or similar:
> NOTE: Within the same event, the order of execution among objects with that event is unspecified and subject to change between GameMaker versions and/or platforms. Don't rely on e.g. obj_Enemy executing its Step event before obj_Player Step event. If you need to guarantee such an order, put the obj_Enemy logic in an earlier event such as Begin Step, or put the player logic in the later event such as End Step.

It might not make people stop abusing unspecified in-event order, but at least it'll be a good piece of documentation to point to when people eventually run into problems with the event order.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=The_Asset_Editors%2FObject_Properties%2FEvent_Order.htm

**Comment by gnysek** [comment]
Yeah, would be good to add few words, that while for few events order is consistent, order in which all instances perform each of those event still isn't.

**Comment by Alphish** [comment]
Ah, and one more thing regarding Draw events:

I guess it should be safe to state that Draw events execute from the deepest layer objects to the shallowest layer objects (but the order is still unspecified within same depth layers)? I mean, that's the whole point of layers, to make sure that shallower layers are drawn on top of the deeper ones.

Not sure about the Pre-Draw and Post-Draw events (since they draw to back buffer, so maybe they act differently), but from what I can tell, it generally goes like:
- Pre-Draw (from deepest to shallowest, or completely unspecified)
- Draw Begin (from deepest to shallowest)
- Draw (from deepest to shallowest)
- Draw End (from deepest to shallowest)
- Post-Draw (from deepest to shallowest, or completely unspecified)
- Draw GUI Begin (from deepest to shallowest)
- Draw GUI (from deepest to shallowest)
- Draw GUI End (from deepest to shallowest)

Hopefully my understanding is correct here.

**Comment by gurpreetsinghmatharoo** [comment]
Thanks, fixed

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
