### ISSUE TITLE
Allow static_get to take a method

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#5030]
### Is your feature request related to a problem?

Creating this ticket as requested by @rwkay, after checking a couple of things for the following ticket: https://github.com/YoYoGames/GameMaker-Bugs/issues/4687

You might want to access a static variable of the function bound to an instance as a method.
`static_get` can be used for this, though it only takes a function index, which you can get for the method with `method_get_index`: 
```gml
var _s = static_get(method_get_index(my_method));
```
This could be done more conveniently by allowing `static_get` to take a method: 
```gml
var _s = static_get(my_method);
```

### Describe the solution you'd like

`static_get` should be able to take a method, in which case it returns the static struct of the method's function: 
```gml
/// Script Asset
function func()
{
    static func_var = 2;
    // Etc.
}
```
```gml
/// Create Event
my_method = method(self, func);
var _s = static_get(my_method);
show_debug_message(_s.func_var);  // 2
```

### Describe alternatives you've considered

This is already possible, though currently you first need to get the method's function index using `method_get_index` and pass that to `static_get`: 
```gml
var _my_index = method_get_index(my_method);
var _s = static_get(my_index);
show_debug_message(_s.func_var);  // 2
```

**Comment by tabularelf** [comment]
It makes me think about case scenarios like this, and how this'll be impacted. Since you can apply statics onto methods as well, since they are their own kind of struct.
```gml
my_method = function() {};

var struct = {
   time: function() {return current_time;}
}

static_set(my_method, struct);

// Getting the static struct later
var struct = static_get(my_method);
show_message(struct.time());
```

**Comment by rwkay** [comment]
Fixed in 2024.4

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.541  Runtime v2024.400.0.560.

**Comment by sihammill** [comment]
Tested on both GMS2 and GMRT and there is and there appears to be an issue accessing the functions static variable.
