### ISSUE TITLE
Renamed resources aren't sorted alphabetically in 2024.2

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5035]
### Description
2024.2 project format changes introduced a change, in which all resources in .yyp should be sorted alphabetically, so for those who use git files won't change from time to time.

However, seems that this functionality isn't working as it should.
In attached example, I have 3 scripts: `A`, `M` and `Z`.

By adding another script, let's name it `aaa`, it would be sorted between M and Z. My suspicion is that it's because at beggining it's named `Script4`, and it's not sorted again on rename.

### Steps To Reproduce
1. Create 3 resources (scripts for example), name them `A`, `M` and `Z`.
2. Preview .yyp
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/318c12b7-fcc9-4d97-a0b3-afd7a7b97130)
3. Add another resource, name it `aaa`.
4. Preview .yyp, notice that `aaa` is between `M` and `Z`.
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/06fc5a38-084e-41c0-a519-4bd284f6d522)
5. add another script. Previous one will be sorted, but new one would again be sorted under `ScriptX` name. However, duplicating sorts both resources.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3d2afdfb-f7eb-439f-9ee8-3dd0671ecd16](https://api.gamemaker.io/api/github/downloads/3d2afdfb-f7eb-439f-9ee8-3dd0671ecd16)

**Comment by stuckie** [comment]
Fixed as part of https://github.com/YoYoGames/CoreResources/pull/229

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.519  Runtime v2024.400.0.540
