### ISSUE TITLE
Compiler Optimization: Hash Literals

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5039]
### Is your feature request related to a problem?

Relating to a [recent change](https://github.com/YoYoGames/GameMaker-Bugs/issues/2821).

Hashes are not optimized at compile time.

For instance the return of `variable_get_hash("a")` is `101200`. However this is not resolved by the compiler, but done during runtime. here is some test code for use with GM Benchmark.

```gml
	new Benchmark("Hash Optimizations", [
			new TestCase("Hash Literal", function(iterations) {
				repeat (iterations) {
					var _test = struct_get_from_hash(struct, 101200); //variable_get_hash("a")
				}
			},
			function(iterations) {
				struct = {a:"a"};
				//note: variable_get_hash("a") = 101200
			}),
			new TestCase("variable_get_hash(<String literal>)", function(iterations) {
				repeat (iterations) {
					var _test = struct_get_from_hash(struct, variable_get_hash("a"));
				}
			},
			function(iterations) {
				struct = {a:"a"};
			}),
			new TestCase("variable_struct_get(<String literal>)", function(iterations) {
				repeat (iterations) {
					var _test = variable_struct_get(struct, "a");
				}
			},
			function(iterations) {
				struct = {a:"a"};
			}),
		]),
```

### Describe the solution you'd like

in theory all of these should be compiled down directly into `struct_get_from_hash(struct, 101200)` since they are literals in literals.
`variable_struct_get(struct, "a")` currently gets changed into `struct_get_from_hash(struct, variable_get_hash("a"))`
`struct_get_from_hash(struct, variable_get_hash("a"))` should then get changed into `struct_get_from_hash(struct, 101200)`

### Describe alternatives you've considered

Honestly just dealing with it, it's not much of an optimization. Only about 1.31x faster when compiled as a real.
It could save a ton of time for some projects like component systems, but generally this only directly effects literal use cases.

### Additional context

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/2fc4af5f-670c-41ab-a073-1fb08e306be6)

**Comment by rwkay** [comment]
This is already done...  it has been in since the start of the year...

**Comment by YYBartT** [comment]
Updated the manual page of `variable_get_hash()` and the other functions that make use of hashes a bit and referred to the [Compiler Optimisations](https://manual.gamemaker.io/monthly/en/Settings/Runner_Details/Compiler_Optimisations.htm) page on those pages.
