### ISSUE TITLE
phy_particle_data_flag_color is not defined

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#5044]
### Description
If I use phy_particle_data_flag_colour, then I get an error.

It should be defined as 8

### Steps To Reproduce
show_debug_message(phy_particle_data_flag_colour)

[8d2b33e8-a5be-4aa8-86ef-cc7fadaec6d0](https://api.gamemaker.io/api/github/downloads/8d2b33e8-a5be-4aa8-86ef-cc7fadaec6d0)

**Comment by Glim888** [comment]
phy_particle_data_flag_colour WORKS
phy_particle_data_flag_color CRASHES

**Seems like a manual bug**

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
