### ISSUE TITLE
physics_particle_get_data_particle(x, y, phy_particle_data_flag_colour) returns garbish

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#5045]
### Description
physics_particle_get_data_particle(x, y, phy_particle_data_flag_colour)

returns always the same number and not the color of the particle.

The same problem exists for the other get_data functions like: physics_particle_get_data()

### Steps To Reproduce
Create different colored particles and check via 
physics_particle_get_data_particle(x, y, phy_particle_data_flag_colour)
the color it returns. Its always the same.

[94456cd9-928a-4f05-b980-1dd4157b051a](https://api.gamemaker.io/api/github/downloads/94456cd9-928a-4f05-b980-1dd4157b051a)

**Comment by Glim888** [comment]
It does not return garbish, BUT the manual is wrong.

The manual says it returns a buffer_f32, but thats wrong. It returns a buffer_u32

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
