### ISSUE TITLE
More built-in functions

### ISSUE THREAD

**Issue by FieldCodeFarmer** [YoYoGames/GameMaker-Bugs#5055]
### Is your feature request related to a problem?

More built-in functions make it easier to write code

### Describe the solution you'd like

string_is_real(str,real_16=0)//Whether the string is a number or not, whether it is hexadecimal
string_is_char (str) //Whether the string is 26 letters in English
stringmap_split_grid(grid,column="|n",row="|t")//The content of the column string is grid
list_stransform_array(list,array)//The list becomes an array
array_stransform_list(list,array)//array becomes a list
array_copy_not_repeat(array1,array2)//replication is not duplicated
array_push_not_repeat(array,value)//Added without duplicates
array_delete_array_repeat(array1,array2)// Delete the contents of array 2
array_find_delete(array,value)//Look for the same deletion
ds_list_find_delete(array,value)//Look for the same deletion
array_exists(array,value)// Returns -1 if it does not exist, and returns a subscript if it exists
ds_list_exists(array,value)// Returns -1 if it does not exist, and returns a subscript if it exists
array_mirror (array) // Mirror subscript
ds_list_mirror (array) // Mirror subscript
draw_text_align(x,y,str,halign,valign)//Draw the align parameter string
draw_grid(x,y,width,height,size,alpha=1,text=1,posx=0,posy=0,gap_txt=1)//posx=start x, posy=start y, gap_txt=how many lines to draw the subscript text at a time
draw_array(x,y,array,width,height)//Draw a vertical array
draw_struct (x, y, struct,width,height)// Draw a structure
ds_list_draw(x,y,array,width,height)//Draw a vertical list
ds_grid_draw(grid,x,y,width,height)//Draw a grid
draw_rectangle(x1,y1,x2,y2,outline)//outline to draw the border thickness，0 is the internal fill, 1 is the border of 1 thickness, 2 is the border of 2 thickness.... And so on
draw_bar(x,y,width,height,point,up_sprite=undefined,down_sprite=undefined)//Draw a progress bar ,point=0~1,or draw sprite
draw_surface_ext_offset(surface, x,y,xscale,yscale,angle,blend,alpha,center_x,center_y) // Surface with center point

**Comment by LukeBrownYoYoGames** [comment]
You would need to request each of these as their own feature request with a detailed description of what you would expected to see and why for each one.
