### ISSUE TITLE
Building Projects: Switch SDK path cannot be found by 2024.400 Beta 1 when starting a build

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#5056]
### Description

The beta 400 of the IDE when i try to build a Nintendo Switch project return an error saying the path is not correct:
`Configuration Problem : The path for the Nintendo Switch SDK is misconfigured`

The path is correct because the SDK is recognized by the stable without problems and from the older beta versions.

My path:
C:\Nintendo\NintendoSDK\NintendoSDK

### Expected Change

The SDK folder is found and the build works

### Steps To Reproduce

1. Start GameMaker using an account which has Nintendo Switch access
2. Ensure your Preferences are set correctly
3. Try running any project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Switch

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Confirmed on my machine.

**Comment by YYDan** [comment]
Okay, that's the setup guide updated to document a change of required SDK version. Can't give more info on a public issue, but if you go see the guide now you will be able to fix your 400 Beta setup.

Apologies the doc was not updated prior to the release last week.
