### ISSUE TITLE
Postfix increments being converted to prefix increments on HTML5

### ISSUE THREAD

**Issue by sp202** [YoYoGames/GameMaker-Bugs#5061]
### Description

This is an issue particularly when using the `gml_pragma("optimise", "js_pre_post_no_long", "push, on")` pragma as it breaks cases where an array is being accessed using a variable that is being incremented

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/39699602/fbbb7b06-b9be-4354-b244-4fc990e02970)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/39699602/f9e180c7-3b83-4c5d-b644-2084ae34a01a)

### Steps To Reproduce

1. Use a postfix increment
2. Note that the transpiled JS contains a prefix increment instead

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

HTML5

Example project:
[broken_postfix_html5.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14637441/broken_postfix_html5.zip)

**Comment by rwkay** [comment]
Fixed in 2024.4

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.542  Runtime v2024.400.0.561, thanks.
