### ISSUE TITLE
Add audio_exists_stream function

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#5064]
### Is your feature request related to a problem?

Please add a function to check if an audio stream exists. On some Android devices, the game occasionally crashes at the engine level due to a simple stream deletion, even though the stream was not deleted previously. As a workaround, we have to avoid deleting streams altogether, which leads to a slight memory leak.

### Describe the solution you'd like

Add audio_exists_stream function

**Comment by toby-yoyo** [comment]
`audio_exists` can check the existence of streams created at runtime. If you are experiencing a crash when deleting streams on Android, please submit that as a bug and attach a project that reproduces the issue.
