### ISSUE TITLE
GameMaker creates UTF-8 files, not ANSI

### ISSUE THREAD

**Issue by zakhar9lov** [YoYoGames/GameMaker-Bugs#5065]
### Description

The GameMaker documentation, on the text file information page, states that the file system functions produce ANSI-encoded text files, and that non-Latin characters should not appear in them:

> Please note that for games with localizations it is very important that accented letters can be read from external files. This means that you should create the txt file in UTF8 format first and then add it into GameMaker as an included file so that it is exported on running the game and used instead of the default ANSI format txt file that is created by the GameMaker file functions when no file is previously supplied. In this way, you can read and write to it correctly with all accents and non-roman letters being maintained.

But when I create a text file, it is created in UTF-8 encoding, all characters are displayed correctly:
```
ansi_file = file_text_open_write(working_directory + "testfiles/ANSI_text.txt")
file_text_write_string(ansi_file, "ñøt süppôrt accents")
file_text_close(ansi_file)
```

The `ANSI_text.txt` file is not included in the project and is created at runtime

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/141114085/5ac3d792-c6b8-473f-9c65-d69e25b1de23)

Runtime v2024.2.0.163
Windows 11

### Manual Link

http://127.0.0.1:51290/index.htm#t=GameMaker_Language%2FGML_Reference%2FFile_Handling%2FText_Files%2FText_Files.htm

**Comment by gnysek** [comment]
Seems it's mentioned i more places:

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FFile_Handling%2FText_Files%2FText_Files.htm&rhsearch=ANSI&rhhlterm=ANSI

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FFile_Handling%2FIni_Files%2FIni_Files.htm&rhsearch=ANSI&rhhlterm=ANSI

https://manual.gamemaker.io/monthly/en/index.htm#t=Drag_And_Drop%2FDrag_And_Drop_Reference%2FFiles%2FFile_Actions.htm&rhsearch=ANSI&rhhlterm=ANSI

**Comment by zakhar9lov** [comment]
> Seems it's mentioned in more places:

The documentation says that the GM file functions create ANSI files, but this does not happen.
When I create a file, GameMaker creates UTF-8 files, not ANSI as stated in the documentation

**Comment by thennothinghappened** [comment]
I'd imagine that was probably silently changed at some point or other since there isn't really any reason for GM to write ANSI, plus the `file_text_*` functions are pretty unused nowadays in favour of the `buffer_` functions which give a lot more flexibility and are supported on all platforms.

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
