### ISSUE TITLE
AppImage built with 2024.2.0.132 segfaults due to libpulse

### ISSUE THREAD

**Issue by krukai** [YoYoGames/GameMaker-Bugs#5070]
### Description

I am running 2024.2.0.132 on Arch Linux (w/ PipeWire), having followed the steps from https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu to install the Steam Runtime. As a project, I am using the Fire Jump template.

I can run the game fine in the VM. Exporting the game as a zip and running it from there works, too. However, with YYC the AppImage segfaults (curiously, this is reported as a `kill` call missing a parameter, but I am not going to focus on that here).

Running the AppImage manually with `LD_DEBUG=libs` from a terminal yields the following (shortened):

```
(...)
    715349:
    715349:	find library=libopenal.so.1 [0]; searching
    715349:	 search path=/tmp/.mount_Fire JobUE0V/usr/bin/../lib		(RUNPATH from file ./Fire Jump Template.AppImage)
    715349:	  trying file=/tmp/.mount_Fire JobUE0V/usr/bin/../lib/libopenal.so.1
    715349:
    715349:	find library=libpulse.so.0 [0]; searchingnitialize program:
    715349:	 search path=/tmp/.mount_Fire JobUE0V/usr/bin/../lib		(RUNPATH from file ./Fire Jump Template.AppImage)
    715349:	  trying file=/tmp/.mount_Fire JobUE0V/usr/bin/../lib/libpulse.so.0
(...)
    715349:
    715349:	calling init: /tmp/.mount_Fire JobUE0V/usr/bin/../lib/libpulse.so.0
    715349:
    715349:
    715349:	calling init: /tmp/.mount_Fire JobUE0V/usr/bin/../lib/libopenal.so.1
(...)
    715349:	initialize program: ./Fire Jump Template.AppImage
    715349:
    715349:	find library=libopenal.so [0]; searching
    715349:	 search path=/tmp/.mount_Fire JobUE0V/usr/bin/../lib		(RUNPATH from file ./Fire Jump Template.AppImage)
    715349:	  trying file=/tmp/.mount_Fire JobUE0V/usr/bin/../lib/libopenal.so
    715349:	 search cache=/etc/ld.so.cache
    715349:	  trying file=/usr/lib/libopenal.so
    715349:
    715349:
    715349:	calling init: /usr/lib/libopenal.so
    715349:
    715349:	find library=libpulse.so [0]; searching
    715349:	 search path=/tmp/.mount_Fire JobUE0V/usr/bin/../lib		(RUNPATH from file ./Fire Jump Template.AppImage)
    715349:	  trying file=/tmp/.mount_Fire JobUE0V/usr/bin/../lib/libpulse.so
    715349:	 search cache=/etc/ld.so.cache
    715349:	  trying file=/usr/lib/libpulse.so
    715349:
    715349:	find library=libpulsecommon-17.0.so [0]; searching
    715349:	 search path=/usr/lib/pulseaudio/glibc-hwcaps/x86-64-v3:/usr/lib/pulseaudio/glibc-hwcaps/x86-64-v2:/usr/lib/pulseaudio		(RUNPATH from file /usr/lib/libpulse.so)
    715349:	  trying file=/usr/lib/pulseaudio/glibc-hwcaps/x86-64-v3/libpulsecommon-17.0.so
    715349:	  trying file=/usr/lib/pulseaudio/glibc-hwcaps/x86-64-v2/libpulsecommon-17.0.so
    715349:	  trying file=/usr/lib/pulseaudio/libpulsecommon-17.0.so
    715349:
(...)
    715349:	calling init: /usr/lib/pulseaudio/libpulsecommon-17.0.so
    715349:
    715349:
    715349:	calling init: /usr/lib/libpulse.so
    715349:
zsh: segmentation fault (core dumped)  LD_DEBUG=libs ./Fire\ Jump\ Template.AppImage
```

It seems that multiple versions of some libraries get loaded, probably due to how different suffixes are prioritised and whether they can be found. There might be more than shown above, but the point is it segfaults when my system's libpulse is loaded, after the one from the AppImage already was.

I had someone else test the same AppImage on Steam Deck, where it also segfaults. It runs fine on Ubuntu 22 LTS, where it also looks for but fails to find `libpulse.so` (Ubuntu does not ship it, but Arch provides `libpulse.so` as a symlink to `libpulse.so.0`). Thus, there is no second "calling init", which is why I assume this issue went unnoticed.

Fortunately, there are two ways to fix this after extracting the AppImage's files:

1. I remove `squashfs-root/usr/lib/libpulse.so.0`, forcing the game to **only** load my system's `libpulse.so`.
2. I leave it in but add `squashfs-root/usr/lib/libpulse.so` as a symlink, ensuring the system lib is not loaded.

So, while I believe what I described above is an issue with the AppImage's libraries, this still leaves at least two different approaches to fix this.
On Ubuntu and Arch, the package providing `libpulse.so.0` is a hard requirement for both PulseAudio and PipeWire. So if the user's system cannot supply it, there's not going to be any audio, anyway. While I admit I am not familiar with the Linux multimedia systems at a lower level, it seems reasonable to draw the line there. As a result, my suggestion would be to zap `lib/libpulse.so.0` from the AppImage instead of including another symlink.

There are more libraries (`libopenal` and `libpulsecommon-*`, for starters) that get loaded twice in a similar fashion and might require a closer look, but at least these don't seem to cause a crash, at least on my end.

Cheers!

### Expected Change

AppImage is adapted to prevent segfault.

### Steps To Reproduce

1. Build AppImage (export or run with YYC).
2. Run AppImage on an Arch-based system (Arch, Steam Deck, ...). Potentially any other distro that ships `libpulse.so` as well (Fedora apparently does, but I did not test it).

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Arch Linux

### Which platform(s) are you having trouble building this project for?

Arch-based distros, including Steam Deck

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [output.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14643321/output.txt)

### Sample Project Added?

- I am using the Fire Jump template
- [AppImage (zipped)](https://github.com/YoYoGames/GameMaker-Bugs/files/14643328/Fire.Jump.Template.zip)

**Comment by yoyo-danielc** [comment]
Fix merged onto April branch.

**Comment by yoyo-danielc** [comment]
A bit of background on what the problem was and what exactly has changed:

The **x64 VM** runtime wasn't linked against libopenal or libpulse and both were loaded at runtime using `dlopen()`, so the AppImage didn't include either in the bundle and they would be loaded from the host (if available).

The **x64 YYC** build process linked against libopenal and libpulse from the Steam Runtime, causing them to be included in the AppImage bundle, **however** we still loaded them at runtime through `dlopen()` (preferentially using a different library name), which could lead to two versions of libopenal and/or libpulse being loaded, depending on what libraries/symlinks were present on the host, and that was causing a crash within libpulse on Arch here.

**ARM VM** and **ARM YYC** were much the same as x64, except AppImage isn't used, which would just lead to **ARM YYC** builds unnecessarily failing to launch on systems without libopenal and libpulse installed.

After these changes:

**x64 VM** and **x64 YYC** are both linked against libpulse and libopenal and the symbols provided by the dynamic loader are used rather than loading them at runtime, we can rely on these libraries being present on x64 either through the AppImage bundle including them, or the runtime provided by Steam when being distributed that way.

**ARM YYC** no longer links against libpulse or libopenal, so it will now launch on a system where they aren't installed and gracefully fail to have audio, the same as **ARM VM** did.

**Comment by krukai** [comment]
@yoyo-danielc Thank you for the fix and explanation! Looking forward to give this a spin once it's released.
