### ISSUE TITLE
audio_play_sound Unable to play sound

### ISSUE THREAD

**Issue by yunzlp** [YoYoGames/GameMaker-Bugs#5071]
### Description

The project was made at runtime 2024.200 and was running well

### Expected Change

can play

### Steps To Reproduce

1. Start GameMaker
2. [demo.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14644482/demo.zip)
3. run it
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.400.0.525  Runtime v2024.400.0.546
