### ISSUE TITLE
Manual Content: audio_play_sound() example incorrectly uses audio_pause_sound() twice rather than audio_resume_sound()

### ISSUE THREAD

**Issue by jwithano** [YoYoGames/GameMaker-Bugs#5077]
### Description

In the example for [audio_play_sound](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAudio%2Faudio_pause_sound.htm) the function called in the else statement should be audio_resume_sound rather than audio_pause_sound.

if keyboard_check_pressed(ord("P"))
{
    global.Pause = !global.Pause;
    if global.Pause
    {
        audio_pause_sound(snd_Waterfall);
    }
    else
    {
        **audio_pause_sound(snd_Waterfall);**
    }
}

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAudio%2Faudio_pause_sound.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
