### ISSUE TITLE
In-Game: [HTML5] event_perform_async() doesn't perform the Social async event, differs from Windows

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#5078]
### Description
As above - `event_perform_async` does not run the social async event in HTML5, while it does on Windows

### Steps To Reproduce
1. Run attached project in the Windows export, and press space to observe the async event triggering correctly
2. Run attached project in HTML5, and press space and watch as nothing happens

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22635.0

[79e041c4-1096-4cc1-86d1-a7e1378ae327](https://api.gamemaker.io/api/github/downloads/79e041c4-1096-4cc1-86d1-a7e1378ae327)

**Comment by Sidorakh** [comment]
Had a go at fixing this myself here after narrowing the issue down: https://github.com/YoYoGames/GameMaker-HTML5/pull/455

**Comment by jackerley** [comment]
Nice! I've accepted your PR, thank you!

**Comment by Sidorakh** [comment]
As of Beta Runtime v2024.400.0.547, the bug does not appear to be fixed despite the release notes stating it is. Confirmed by looking at the generated output, this is what's included in the runner as of right now
This block was from a game ran from the IDE in the latest beta version, that should have the fix. 
```js
function event_perform_async(_vm,_dy,_H2,_jy)
{
	var _ky=g_pBuiltIn.async_load_H2=yyGetInt32(_H2);
	_jy=yyGetInt32(_jy);
	g_pBuiltIn.async_load=_jy;
	_L2._M2(_ly,_H2);
	ds_map_destroy(_jy);
	g_pBuiltIn.async_load=_ky;
}
```
For comparison, this is from the HTML5 repo before this fix was added
```js
function event_perform_async(_pInst, _pOther, _event, _ds_map)
{
    var current_async_map = g_pBuiltIn.async_load	
    _event = yyGetInt32(_event);
    _ds_map = yyGetInt32(_ds_map);
    g_pBuiltIn.async_load = _ds_map;
    g_pObjectManager.ThrowEvent(EVENT_OTHER,_event);	
    ds_map_destroy(_ds_map);	
    g_pBuiltIn.async_load = current_async_map;
}
```
