### ISSUE TITLE
Skeleton animations not loading without the default skin

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#5079]
### Description

Animations do not load without the default skin. If you add an animation to the project, you need to additionally specify the skin setup. If you don't specify it, nothing will be rendered.

When loading animations without the default skin using **sprite_add**, the application simply closes without any errors. If you load animations using **sprite_add_ext**, the result is similar to adding an animation through the project _(you will need to additionally specify the skin setup)._

Contact package: [ContactPackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14691390/ContactPackage.zip)

### Expected Change

The game should not crash without an error when calling sprite_add, and it should set the first available skin for the animation.

### Steps To Reproduce

1. Start GameMaker
2. Add json animation (without **default** skin) to datafiles
3. Load sprite with sprite_add
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2022.0.2 (LTS), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
@yevhenii-sir You closed this as not planned - you realised it was a mistake in your setup, or something?

**Comment by yevhenii-sir** [comment]
> @yevhenii-sir You closed this as not planned - you realised it was a mistake in your setup, or something?

This problem was in all other versions as well. You could never use animations without a DEFAULT skin.
When converting to a new version of Spine, the Default skin was lost and the animation stopped loading. I thought it was due to a bug in the new GMS, but as it turned out it is normal.
