### ISSUE TITLE
Debugger: F2 to rename a watch instead renames the "Variables" dock tab

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5080]
### Description

When pressing F2 in Debug run, on `Variables` tab, in `Watch` panel, instead of renaming/editing watched variable, it renames title of tab.

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/9b083e9c-bde2-42f0-a29f-2efa3d41fe58)

This seems to be very similar issue to:
- https://github.com/YoYoGames/GameMaker-Bugs/issues/4796
- https://github.com/YoYoGames/GameMaker-Bugs/issues/4855
- https://github.com/YoYoGames/GameMaker-Bugs/issues/2665

### Steps To Reproduce

1. Start GameMaker
2. Run Game in debug mode, put breakpoint
3. Add variable to Variables / Watched
4. Press `F2` to rename it
5. it would rename `Variables` tab rather than watched var.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

**Comment by SmithTom6304** [comment]
Fixed - selected watch variable will now be renamed when F2 is pressed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.534  Runtime v2024.400.0.553
