### ISSUE TITLE
[HTML5] crash: "arguments.slice" is not a function (fx_structs)

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5096]
### Description
Hey there,

in HTML5 you may not do this:
```
fx_set_parameter(fx_tint, "g_TintCol", v,v,v,1);
```
it crashes with 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/16e4e9f8-23ec-4d0a-93c4-032b476a831d)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/19487451/7651a7a1-0a79-4b9d-b8bc-0a410ce5580d)

...but if you supply the values as an array, where the `(arguments.length == 3)` hits, all is good.
```
fx_set_parameter(fx_tint, "g_TintCol", [v,v,v,1]);
```

### Steps To Reproduce
* Just start the attached project in windows -> all is good
* Start it in HTML -> crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[d724b97e-ee60-48b4-a51c-7411e95d14b6](https://api.gamemaker.io/api/github/downloads/d724b97e-ee60-48b4-a51c-7411e95d14b6)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.400.0.526  Runtime v2024.400.0.547
