### ISSUE TITLE
Add way to close FPS Window in Debug View

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#5097]
### Is your feature request related to a problem?

I really like the new debug view and made a bunch of my own custom views. But when using the Debug View, the FPS is always visible and there is no way to change that.

### Describe the solution you'd like

Best option: GameMaker remembers the views that were open last, as well as their positions and sizes when they come back on into existence.

Second best option: Give us a way to open/close FPS window, or add additional arguments to show_debug_overlay() to modify the default behavior.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by rwkay** [comment]
You can already close the FPS window by going to the Debug menu item and selecting the FPS item - or clicking the X on the right hand side of the window (if minimised or not)

**Comment by nullbunny** [comment]
I was just interested in a way where this doesn't show up at the start so I
don't have to click it every time I don't want the visual clutter.
