### ISSUE TITLE
In-Game: sprite_get_nineslice's toString empty

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#51]
GM-7567

"Description: The following code will return nothing. It doesnt throw any errors and it does return a string. But the internal toString is just returning "". The struct's data all exists too, it's simply the the toString which is effected.

var _info = sprite_get_nineslice(self.image_index)
show_debug_message(_info)"

Steps
# import the attached project and run
# look at the output
# notice that the structure has been created but toString or simply outputting the struct returns a blank. Yet if any of the   struct's variables are output then they exist and have default values

**Comment by rwkay** [comment]
closed as above
