### ISSUE TITLE
rectangle_in_triangle gives incorrect results with high decimal precision number values

### ISSUE THREAD

**Issue by xeneder** [YoYoGames/GameMaker-Bugs#5105]
### Description

I used this function to detect collision in my game and it used very high decimal precision numbers in the game to determine collision coordinates and it occasionally (very rarely) comes with an incorrect result.

### Expected Change

rectangle_in_triangle gives the correct result with any precision

### Steps To Reproduce

1. Create a Project in GameMaker that uses a function with coordinates that clearly do not intersect, for example:
2. `rectangle_in_triangle(114.2063980102539, 96.70489501953125, 120.2063980102539, 102.70489501953125, 49, 44.94294357299805, 50.20213305500853, 45.968420446638284, 51.158809557293125, 46.78451604992992)`
3. See that the function outputs 2 instead of 0
4. Change the precision of some of the values (for example, i changed precision to 2 decimal digits for the first four values)
5. See that the function returns a correct output of 0

Contact Us Package:
[bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14736360/bug.zip)

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.529  Runtime v2024.400.0.550
