### ISSUE TITLE
[HTML] ptr function not working correctly

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5108]
### Description
Hey there,

attached project only has a few lines of code to demonstrate.
```
something = {
	someval: 42
};


show_debug_message("-------------");
show_debug_message(ptr(something));
show_debug_message("-------------");
```

run on windows and you get something like this in the log:
```
-------------
0000000003152400
-------------
```

run on html (with F6 for console!) and you get
```
-------------
{  }
-------------
```

I am using sha1 hashing for now in html, but this is way slower than just getting the ptr.
please fix.

thanks for reading
cheers, 
Gris

### Steps To Reproduce
* run the attached project in windows
* run the attached project in html
* examine the differences in the log output

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[284ccd9c-c27a-4f01-a7fb-81baa5b89551](https://api.gamemaker.io/api/github/downloads/284ccd9c-c27a-4f01-a7fb-81baa5b89551)

**Comment by stuckie** [comment]
JavaScript does not technically have a pointer construct, so this isn't something we are able to fix at this time.
