### ISSUE TITLE
Building Projects: Errors in post_build_step.bat say to edit a text file which says you should not edit 

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#5111]
### Description
When building projects which use Steamworks, (any?) errors in post_build_step.bat phase say to edit the text file on disk; however, when opening that file, in equally distinct formatting, the text clearly says you should not edit the text file directly and instead do everything inside the IDE.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/1dd948b3-7039-4814-9a2b-b13bfd68dfe5)

### Expected Change

We make the wording consistent so that both locations help users fix their issue as easily as possible.

There are some typos which need to be fixed also.

### Steps To Reproduce
1. Start GameMaker 2024.2
2. Attempt to open and run the large, Steamworks-enabled project attached to https://github.com/YoYoGames/GameMaker-Bugs/issues/5102  for Windows VM
3. See that it fails with a message to edit the file
4. Open the text file on disk (outside GameMaker)
5. See that it tells you to not edit the file and to go back to the IDE

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[21381d15-d663-4124-ba82-9521005e7de7](https://api.gamemaker.io/api/github/downloads/21381d15-d663-4124-ba82-9521005e7de7)

**Comment by DiasFranciscoA** [comment]
Upon investigation, we've found that this issue relates to an older version of the extension (Nov 22). During the transition to integrating extension options into the project build process, some outdated error messages were inadvertently retained.

It's important to note that despite these error messages, the extension continues to function properly when configured through the IDE. As such, while this issue may initially appear to be a GameMaker-related bug, it is more accurately categorized as a bug within the extension itself, particularly in terms of outdated messaging.

> [!NOTE]
> This is not a problem anymore in more recent versions of the extension. Please make sure you always use up-to-date version of the extensions both for compatibility and bug fixes.
