### ISSUE TITLE
draw_self() handles negative image_index values differently than everything else

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5112]
### Description

this ones a bit of silly guy to explain! given the same exact equation for cycling through *negative* image index, the sprite shown is the same using all draw methods except draw_self().

here, this object has no draw event. notice that as the image_index goes from -1 to -.9 the index changes to the next frame.
https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/e31dd218-c14f-4c20-92bb-5c2c67b9093a

but here, this time we're using draw self and going from -1 to -.9 creates no change.
https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/04cf2af2-1b6d-4074-aef7-1bce669d2ed9

this seems to only effect draw self, as other draw calls produce the same results as having no draw event. here draw sprite yields the same goodtimes as no draw event at all.
https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/7e9ba3bf-dd52-4205-9756-42ed81c53365

here is a project to play with! run the game, press space to decrement image_index, notice the change from -1 to .9 with no draw event. then give it a draw event with draw self and notice a different change!
[cooks bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14744181/cooks.bug.zip)

### Expected Change

draw self should handle negative image index the same as anything else

### Steps To Reproduce

1. give an object a way to decrease image index using a negative number
2. log where it crosses from -1 to the next value, below -1
3. give that object a draw event with draw self
4. notice the frame change is not the same as before

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
I extended the sample a bit so you can see all the various draw_* functions and also using Nine Slices where possible, I've made all the functions consistent across VM, YYC & HTML5 so any negative image_index passed to a draw_* function will use the instance image index and the handling of negative image_index from an instance is consistent. @gurpreetsinghmatharoo  it would be good to update the manual to clarify this behaviour. 
[cooks bug2.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14762247/cooks.bug2.zip)
