### ISSUE TITLE
Sprite Editor: CTRL+Z to undo after resizing an image doesn't work until you click somewhere on the IDE

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#5114]
### Description

When verifying https://github.com/YoYoGames/GameMaker-Bugs/issues/4514 I noticed that pressing CTRL+Z to undo didn't work and I had to go to edit > undo instead. It happens any time you resize an image and try to use CTRL+Z after, and clicking somewhere on the IDE appears to fix the issue.

 IDE v2024.400.0.525  Runtime v2024.400.0.546
 
[CtrlZbug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14745647/CtrlZbug.zip)

### Expected Change

CTRL+Z should work immediately after resizing an image

### Steps To Reproduce

1. Start GameMaker and create new project.
2. Create a sprite, go into the image editor and scale the image, then apply.
3. Press CTRL+Z and notice nothing happens.
4. Click somewhere on the IDE and then CTRL+Z to see it undo.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This seems to have been fixed by the hotkey fixes a while back.

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.600.0.571  Runtime v2024.600.0.597, thanks.
