### ISSUE TITLE
Manual Content: asset_get_index() page's example has its arguments in the wrong order

### ISSUE THREAD

**Issue by KungFuChowder** [YoYoGames/GameMaker-Bugs#5118]
### Description

The function instance_create_layer() used in the example at the bottom of the page is using arguments in the wrong place.
![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/76659326/32a726b0-bf27-421a-a5a3-358bdc6cde1b)

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAssets_And_Tags%2Fasset_get_index.htm&rhsearch=asset_get_index&rhhlterm=asset_get_index

**Comment by sihammill** [comment]
Fix verified
