### ISSUE TITLE
Building Projects: Add support for complying with Apple's new privacy requirement (ITMS-91053) through PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5122]
### Description
We are getting the `ITMS-91053: Missing API declaration` warning when submitting builds to AppStore Connect, where Apple requires the app to ship a PrivacyInfo.xcprivacy file that describes API usage: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

An example of the warning looks like this: https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy

I see that the file is already included in the `runtime\ios\TemplateProject\${YYXCodeProjName}\Supporting Files\PrivacyInfo.xcprivacy`, but it is not targeting the app, so it is not included in `project.pbxproj`.

We would like to suggest that:
1. Please set `PrivacyInfo.xcprivacy` to target the app by default.
2. Document how to replace the content of the file through the `YYIosPrivacyManifest` tag in an iOS extension to address the ITMS-91053 warning
3. Or any other solutions that complies with Apple's requirement

### Steps To Reproduce
1. Compile any project for iOS export
2. Open the XCode project and check the PrivacyInfo file, see that its Target Membership does not check the app's target.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.524 Runtime v2024.400.0.545

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[92cc506c-9971-45e3-b4d9-b3b71ad00bc6](https://api.gamemaker.io/api/github/downloads/92cc506c-9971-45e3-b4d9-b3b71ad00bc6)

**Comment by jzavala-YYG** [comment]
Hello @shichen85 

The attached extension insert the PrivacyInfo.xprivacy file to the root of the Xcode project, the content of the file it's:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

	${YYiOSNSPrivacyTracking}

</dict>
</plist>


So you can edit the content of the file in the iOS extensions injector inserting text in the key **_YYiOSNSPrivacyTracking_**

<img width="425" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/114691457/abd0c558-b07d-4dac-a78b-a778709bda18">

Please let us if this help you and which content you inserted, we are interested in know how users will use this extension.

Regards


[iOSPrivacyExt.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14769543/iOSPrivacyExt.zip)

**Comment by shichen85** [comment]
@jzavala-YYG Thanks for the reply! I did not know that the extension's `iOSProjectFiles` folder can be copied to the XCode project root. I don't think this is mentioned in the manual. Is there any where this feature is documented? 

We submitted a build and haven't received the warning email yet, so I believe this solutions is working for us. Here is our declartion:

```xml
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryDiskSpace</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>E174.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>CA92.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>C617.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategorySystemBootTime</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>8FFB.1</string>
			</array>
		</dict>
	</array>
```
Other project's use cases might be different, but they should be able to look up the `NSPrivacyAccessedAPIType` and `NSPrivacyAccessedAPITypeReasons` choices at https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc according to the warnings they receive.

**Comment by DiasFranciscoA** [comment]
> [!NOTE]
> the folder structure added to the `iOSProjectFiles` will be copied into the project root folder. And that any variable placeholders `${xxx}` used in that structure are expanded during build time. 

> [!NOTE]
> Custom code injection tags can be added to the extension panel for example:
> 
> ```html
> <YYIosMyCodeInjectionTag>
> Text to expand!!
> </YYIosMyCodeInjectionTag>
> ```
> 
> will expand the placeholder `${YYIosMyCodeInjectionTag}` in that structure. Note that this is true for all custom code injection tags that start with `YYIos` and `YYTvos` (for iOS and tvOS respectively). If 2 or more extension use the same tag the text will be concatenated (with newline character). In the case of special tags like `YYIosPlist` and `YYIosPrivacyManifest` (and respective `YYTvos` version) the plist data will be merged.

> [!TIP]
> We actually suggest you use the `<YYIosPrivacyManifest>` and `<YYTvosPrivacyManifest>` code injection tags (for iOS and tvOS respectively). The file will automatically be added to your project (right now they are not automatically added to target build application we will solve the issue in next beta). The reason why we suggest this approach is due to the fact that if you have multiple extensions that require data to be added to the `PrivacyInfo.xprivacy` file the various code injection from all the extensions will be correctly merged.

**Comment by shichen85** [comment]
Good to know! Thanks for the explanation, and yes I can confirm that we stopped getting the warnings after using this solution.

**Comment by Macj0rdan** [comment]
I am running into the same issue on my iOS app.
But I am not sure I understand everything correctly here.
I need to add an extension to my game that exports to iOS and use the code injection tags <YYIosPrivacyManifest> to add the declarations that I need to the game

**Comment by YYDan** [comment]
> I am running into the same issue on my iOS app. But I am not sure I understand everything correctly here. I need to add an extension to my game that exports to iOS and use the code injection tags to add the declarations that I need to the game?

Yes, as explained in [the first comment above](https://github.com/YoYoGames/GameMaker-Bugs/issues/5122#issuecomment-2022117849 ). Download the extension from the link and then use the injection values shown in the screenshot.

**Comment by Macj0rdan** [comment]
> > I am running into the same issue on my iOS app. But I am not sure I understand everything correctly here. I need to add an extension to my game that exports to iOS and use the code injection tags to add the declarations that I need to the game?
> 
> Yes, as explained in [the first comment above](https://github.com/YoYoGames/GameMaker-Bugs/issues/5122#issuecomment-2022117849). Download the extension from the link and then use the injection values shown in the screenshot.

Okay thank you! I wasn't sure if I understood it right.

**Comment by shichen85** [comment]
Sharing this `PrivacyInfo.xprivacy` generation tool here: https://wemakeapps.net/manifest-maker (thanks to @JujuAdams for finding it in the first place) in case anyone finds it helpful.

**Comment by YYDan** [comment]
The IDE has been changed ahead of Beta 5/the monthly release to simplify the process and remove the need to use this extension and manually add the injection lines.

**Comment by gurpreetsinghmatharoo** [comment]
Added `YYIosPrivacyManifest`/`YYTvosPrivacyManifest` to the manual. Documented injecting tag contents into extension files. Changes will be available with the next beta & monthly manual release.

Added a helpdesk article to cover this specific issue: https://help.gamemaker.io/hc/en-us/articles/18420470290589-iOS-and-tvOS-Providing-API-Access-Reasons-in-a-Privacy-Manifest
