### ISSUE TITLE
GM stopped remembering grid settings

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#5129]
### Description
GM stopped remembering the show/hide grid setting.

I am unsure if this is related to this version or something that started to happen in the middle of using it.

Closing and restarting GameMaker doesn't remedy the issue - it is permanent

This is on version 2023.11.1.60 - because of other bugs I can't test if this also happens in the most recent version, but I thought i would report the bug anyway in case it is still an issue.

### Steps To Reproduce
1. Open up a room.
2. Toggle  grid shown/not shown
3. Do some edits
4. Close the room
5. Open the room back up
6. Grid settings were not remembered

[248f470c-3e1f-4435-b653-bb8bf7a14602](https://api.gamemaker.io/api/github/downloads/248f470c-3e1f-4435-b653-bb8bf7a14602)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.571  Runtime v2024.600.0.597
