### ISSUE TITLE
Local arrays cannot be declared and have an index set at the same time

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5131]
### Description
This works:
```
array[0] = 1;
```
But this does not, giving a compile error:
```
var _array[0] = 1;
```
Object: Object1 Event: Create at line 6 : unexpected symbol "=" in expression
Object: Object1 Event: Create at line 6 : malformed assignment

### Steps To Reproduce
```
var _array[0] = 1;
```
This gives a compile error.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.526 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b149c920-7dca-464f-bf00-8a8220ad5ce5](https://api.gamemaker.io/api/github/downloads/b149c920-7dca-464f-bf00-8a8220ad5ce5)

**Comment by rwkay** [comment]
This is not a bug it is as designed.

`var` declares a variable (and for convenience allows a user to assign a value to that variable.

` var array[0]` is nonsense as it is not declaring a variable, it would appear to be declaring the first entry of an array (with the array called `array`) - it is not valid GML - hence the error.
