### ISSUE TITLE
Mac IDE's Menu Bar Frozen After Multiple Tab Clicks

### ISSUE THREAD

**Issue by NanoSharkGames** [YoYoGames/GameMaker-Bugs#5137]
### Description

After the Room tab in the Menu Bar on MacOS appears and is clicked on multiple times, the Room dropdown menu remains stuck & unresponsive, & I am unable to click or focus on a different tab in the Menu Bar when the IDE is in focus. Closing the IDE is the only way to get rid of the Room dropdown menu.

Screen recording demonstrating the issue: [RoomMenuBarVideo.mkv.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14798587/RoomMenuBarVideo.mkv.zip)

[ContactUsPackage.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14798635/ContactUsPackage.zip)

### Expected Change

Menu Bar no longer gets stuck when IDE is in focus.

### Steps To Reproduce

1. Open a room
2. Get the Room tab to appear in the Menu Bar
3. Click on the Room tab in the Menu Bar until its dropdown menu is stuck

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by NanoSharkGames** [comment]
I have also attached a zip folder with a screen recording which demonstrates the issue.

**Comment by NanoSharkGames** [comment]
I updated to 2024.4 & this same issue now applies to all GameMaker tabs in the Menu Bar. I then reverted back to 2024.2 & the issue does not apply to those same tabs (other than the Room tab).

**Comment by SmithTom6304** [comment]
Have reproduced the issue. Note that the issue seems to have been introduced with macOS Sonoma - I was not able to reproduce the issue with Ventura.

**Comment by SmithTom6304** [comment]
This should now be fixed. A localisation was causing the Room Editor menu to be recreated every time it was opened, causing the `NsMenuDelegate` handler to break. The Room Editor menu is now only recreated when this localisation is updated.
The issue only seemed to occur with the Room menu on the current build, rather than all menus. Let us know if you still see any issues with menus other than the Room Editor.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
