### ISSUE TITLE
Android export: video_get_duration() returns 0

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5145]
### Description
video_get_duration() works on iOS and Windows, but always returns 0 when loading a mp4 video file.

### Steps To Reproduce
1. Run the sample in the "dev" config for android export
2. See that it fails the "video_function_test_headless" test's assertion, where video_get_duration() should return 1000
3. Run for the windows export, see test passes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.527 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[f0d17593-24cc-4af1-a29f-c36f654864a1](https://api.gamemaker.io/api/github/downloads/f0d17593-24cc-4af1-a29f-c36f654864a1)

**Comment by jzavala-YYG** [comment]
Hi @shichen85,

After call video_open() you need wait for the async call **_{"type":"video_start"}_** in the async social event to start reading the correct value from video_get_duration()

Regards
