### ISSUE TITLE
Possibility to change audio session on iOS

### ISSUE THREAD

**Issue by RickardPaulsson** [YoYoGames/GameMaker-Bugs#5146]
### Is your feature request related to a problem?

People are refunding my iOS game because "the audio isn't working". In reality the audio is working but their devices are in Silent Mode. 

### Describe the solution you'd like

Possibility to change audio session in iOS games, to allow for audio even when device is in Silent Mode. Many other apps have sound while device is in Silent Mode.

https://developer.apple.com/documentation/avfaudio/avaudiosession

### Describe alternatives you've considered

Adding a text explaining that "Sound is muted in Silent Mode" after the splash screen of my game. But it gives an amateurish impression, and not everyone understands what this means.

**Comment by toby-yoyo** [comment]
Allowed in-game audio to override the ring/silent switch found on some iOS devices.

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.6.0.157  Runtime v2024.6.0.205
