### ISSUE TITLE
Macros should support unclosed strings

### ISSUE THREAD

**Issue by Furkan-Karabudak** [YoYoGames/GameMaker-Bugs#5148]
### Is your feature request related to a problem?

If you don't close a string at the end of a macro definiton, you get a compiler error. It seems it is not allowed to do that currently.
This is just an example, the content doesn't matter you can not do that in any way:
```gml
#macro as      global.libraries[$ "
#macro import  "] = new 
as math import Mathlib()
```

### Describe the solution you'd like

Macros should allow for unclosed strings at the end of the definition. So we don't have to use quotes every time for any reference or variable name when using with macros. For example I've written a foreach system works with both arrays and structs but I can't use it without double-quotes:
```gml
foreach "i" in MyStruct do_this
{
    i.value = "varname is: " + i.key;
}
```

### Describe alternatives you've considered

`nameof()` seems like a usable alternative for that, but it is not. There is only one specific possible way I could find that it works with macros, but it has problems too. I'm opening a different issue for using `nameof()` with macros: #5158 

### IDE Version
Beta IDE v2024.400.0.526
### Runtime Version
Beta Runtime v2024.400.0.547

**Comment by YellowAfterlife** [comment]
GameMaker macros are slightly unlikely to support unclosed strings because they work at token level, not with text.

For the same reason, having a comment at the end of your macro will not ruin any code you use it in.

For macro-based tricks that do work, you might be interested in [this post](https://www.katsaii.com/content/blog/post/gml+syntax+extensions.html)

**Comment by stuckie** [comment]
This is not something we are planning.

**Comment by Furkan-Karabudak** [comment]
> GameMaker macros are slightly unlikely to support unclosed strings because they work at token level, not with text.
> 
> For the same reason, having a comment at the end of your macro will not ruin any code you use it in.
> 
> For macro-based tricks that do work, you might be interested in [this post](https://www.katsaii.com/content/blog/post/gml+syntax+extensions.html)

Thank you for these information and resource :)
