### ISSUE TITLE
int64 function weird behavior

### ISSUE THREAD

**Issue by HoyongNyong** [YoYoGames/GameMaker-Bugs#5154]
### Description
I was playing with numbers, then I noticed really weird behavior of int64 function.

I wanted to reproduce it, so I created a new blank project and I made a function called 'toint' which get one argument 'n' and this function just returns int64(n). 

then I compared results of int64 and toint, surprisingly, the output was different. 
the output was -2 for int64 function and -1 for toint function...
(tried both show_debug_message and draw_text to check output )

I'm using M1 macbook and I tested it with target platform as macOS and Opera.GX. using vm for build.

here's some picture 
<img width="360" alt="create_event_screenshot" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/0a4b4467-9a9c-4a7c-bd5a-1ef1c6ad2969">
<img width="193" alt="show_debug_message_output_screenshot" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/aa0634a6-a2c0-4bc1-b3c4-b707deca542d">

I tried it with different inputs

<img width="407" alt="스크린샷 2024-03-31 오전 1 22 09" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/f2955baf-9193-41f1-ab3a-7cf27e0235d5">
<img width="342" alt="스크린샷 2024-03-31 오전 1 22 22" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/473a37b9-7b19-4d74-8080-4fe274b99af5">

<img width="381" alt="스크린샷 2024-03-31 오전 1 30 26" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/a0c0c0ac-2d0d-4a40-91b6-8a9b3a83e005">
<img width="164" alt="스크린샷 2024-03-31 오전 1 30 46" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/8f828887-5c53-4590-bddc-67f03b79bd3c">

<img width="348" alt="스크린샷 2024-03-31 오전 1 32 44" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/c7d2f33c-7b86-42a2-bd55-b1ba4914e4b2">
<img width="200" alt="스크린샷 2024-03-31 오전 1 32 56" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/52103489/9d0721f1-87ed-4db5-a4d1-eb35ae60b393">

### Steps To Reproduce
1. Open Gamemaker
2. Create new blank project
3. Create an Object
4. Put this code below in create event.

function toint(n){
	return int64(n);
}

show_debug_message(int64(-1.10010001));
show_debug_message(toint(-1.10010001));

5. Place the object in room and Run Project.
6. Output shows different results.
( for me, it was -2 for int64 and -1 for toint function)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Mac 14.2.1

[a9d0cc86-f4bc-4a86-9709-74d36d10e31e](https://api.gamemaker.io/api/github/downloads/a9d0cc86-f4bc-4a86-9709-74d36d10e31e)

**Comment by YellowAfterlife** [comment]
What's happening here is that doing int64(constant value) will have the _compiler_ evaluate and truncate the number, which can be different from how the runtime works. There are likely a few more edge cases like this.

**Comment by thennothinghappened** [comment]
> What's happening here is that doing int64(constant value) will have the _compiler_ evaluate and truncate the number, which can be different from how the runtime works. There are likely a few more edge cases like this.

I wonder if checking this on YYC with `gml_pragma("forceinline")` would show the same compiler behaviour

**Comment by YellowAfterlife** [comment]
> I wonder if checking this on YYC with `gml_pragma("forceinline")` would show the same compiler behaviour

No, because that one is performed by the C++ compiler rather than GameMaker compiler, which has its own logic.

**Comment by rwkay** [comment]
Fixed in 2024.4 - used C# `long` cast rather than the `Convert.ToInt64( double )` which for some reason does a bankers round, and previous fix to stop that did not work for -'ve numbers correctly... the C++ code at runtime is just doing the cast from `double` to `int64`
