### ISSUE TITLE
Using nameof() inside macro definitions causes wrong results or compile/runtime errors

### ISSUE THREAD

**Issue by Furkan-Karabudak** [YoYoGames/GameMaker-Bugs#5158]
### Description
Attached a project file, which covers several cases that I can think of. Each gives different results or errors.

**Summary:**
- Macro names with 5 or 6 characters works as expected with `nameof()`
- If the macro name is less than 5 chars or more than 6 chars, `nameof()` gives wrong results
- Opening parenthesis "(" in macro definitions generally cause compile or runtime errors depending on the situation. This not just applies for when using `nameof()` but when using other functions too. But gives different errors with `nameof()` and other functions.

### Expected Change
Using `nameof()` or open paranthesis `(` in macro definitions should give consistent results.

### Steps To Reproduce
1- Open the project attached and test / Or create a new project
2- Define macros that have definiton of `nameof` like this `#macro example nameof` with the rules below:
- 2.a - macro names less than 5 characters - The first problem
- 2.b - macro names more than 6 characters - The second problem

3- Use the macros to print outputs like this `show_debug_message(MACRONAME(1234567890));` and see the problems.
4- Define multiple macro combinations for nameof, open parenthesis and close parenthesis like this:
- 4.a - `#macro NAME1 nameof(`
- 4.b - `#macro NAME2 nameof(`  `#macro END_2 )`
- 4.c - `#macro NAME3 nameof`   `#macro END_3 )`
- 4.d - `#macro NAME4 nameof`   `#macro STRT4 (`   `#macro END_4 )`
- 4.e - `#macro NAME5 nameof`   `#macro STRT5 (`

5- Print all of them seperately to the output, for example: `show_debug_message(NAME4 STRT4 1234567890 END_4);`
Some of them will result in a compile error, while some give runtime errors.
6- Try the same of 4th article but this time with a different function instead of `nameof()`, it will give different errors than `nameof()`

### How reliably can you recreate this issue using your steps above?
Always

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.526 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22635.0
(Well actually it's Windows 11 22635.3350)

### Contact Us Package With Project File:
[f3bdd0f7-5835-4853-b1e3-040e914b136f](https://api.gamemaker.io/api/github/downloads/f3bdd0f7-5835-4853-b1e3-040e914b136f)

### Public Project File:
[nameof_with_macros_PROJECT.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14813527/nameof_with_macros_PROJECT.zip)

### Images Showing The Test Code And Issues:
![nmof1](https://github.com/YoYoGames/GameMaker-Bugs/assets/72013055/0015f943-fbb7-42d3-b0bb-0f43891b3856)
![nmof2](https://github.com/YoYoGames/GameMaker-Bugs/assets/72013055/1c5eb511-c339-4fbb-b8dd-d227712a598e)

**Comment by Furkan-Karabudak** [comment]
As of new beta version IDE v2024.400.0.532 Runtime v2024.400.0.551 behaviours have changed:
-
- Section 1: Macro names with 5 or 6 chars still work, but less than 5 chars now results in a compile error, rather than a wrong output like before.
- Section 2: Macro names with more than 6 chars gives wrong results exactly the same as before.
- 3rd Part of Section 2: If you add another string at the end & your macro name is 5 or 6 chars, it works correct, like before. But if your macro name is more than 6 chars, adding another string at the end now results in a compile error, rather than wrong outputs as before.
- Section 3: No change

**Comment by Furkan-Karabudak** [comment]
Well this is weird, I reinstalled 526 instead of 532, switched back to the runtime 547 too, but still not getting the old results, I'm still getting the results after the new update. Cleaned the project cache too. When I go back to the previous version, doesn't the compiler go back to the old version too? There is something I don't understand here.

**Comment by rwkay** [comment]
Fixed in 2024.6

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.561  Runtime v2024.600.0.579
