### ISSUE TITLE
Game Maker 2 stucks on Checking RSS

### ISSUE THREAD

**Issue by STRAY-blup** [YoYoGames/GameMaker-Bugs#5165]
### Description

I have Game Maker 2 from Steam. The Internet speed is 700-1000 Mbps (both incoming and outgoing).

At startup, it freezes at the Checking Network point for 10-15 seconds. Then it comes to Checking RSS and freezes for a minute or two. Then the message comes out:
_Could not reach the RSS feed: the operation is timed out_
If you click OK, the loading will continue, and everything seems to be working, but when you try to log into the Opera account, Game maker freezes and nothing happens, and when you try to log into the legacy account, it gives an error
_Unable to sign in - Cannot reach https://accounts.yoyogames.com
and asks to attach the [ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/14819826/ui.log)

contact us package
[contact us.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14819829/cotact.us.zip)

### Expected Change

Loading become fast and i can log in

### Steps To Reproduce

1. Start GameMaker
2. Wait loading
3. See the issue
4. Click "OK" in message "Could not reach the RSS feed: the operation is timed out"
5. Try to log in with legacy or Opera account
6. See the issue

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by stuckie** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.
