### ISSUE TITLE
Extensions in Different Timezone Cause Spurious Git Diffs

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#5171]
### Description

We get a lot of spurious diffs updating different extensions in different timezones. We have a distributed team, so basically anytime a teammate opens the IDE who *doesn't* live on the east coast of north america, they get a diff like this:

```diff
- "date": "2021-03-04T18:31:00.1566041-05:00",
+ "date": "2021-03-04T17:31:00.1566041-06:00",
```

Notice how it's just backshifting the timezone and forward shifting the time

### Steps To Reproduce

Open the Fields of Mistria repo in a non-UTC-5 timezone. Note: it's DST right now in America, and that definitely could be figuring into this.

That being said, I'm not sure why there's a date field at all, but i'm sure there's some particular reason.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Big Sur

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This is fixed in the April betas already, it had just missed the February cut-off.
