### ISSUE TITLE
Problem with audio_create_stream on Nintendo Switch in GameMaker Beta v2024.400 | Error (thread index 0): ov_open turned -128 -> A read from media returned an error.

### ISSUE THREAD

**Issue by Jonnil** [YoYoGames/GameMaker-Bugs#5174]
### Description

I'm using GameMaker Beta v2024.400.0.526

I'm using the function audio_create_stream to load music and voice clip audio from Included Files/Datafiles.
I have code that looks like this for loading voice clips, for example:
`voice = audio_create_stream(file_path);`

This works as intended on PC, but it can't play any sounds loaded using audio_create_stream on Nintendo Switch.

When I'm playing my game on Nintendo Switch, I'm getting this error every time the game tries to play audio that has been loaded using audio_create_stream:
`Error (thread index 0): ov_open returned -128 -> A read from media returned an error.`
[
![Error (thread index 0) ov_open returned -128 - A read from media returned an error](https://github.com/YoYoGames/GameMaker-Bugs/assets/9497588/8d42c2d6-0938-482d-a2af-b9b5464d7d87)
](url)

This error I'm experiencing never happened in versions before GameMaker Beta v2024.400. audio_create_stream worked on both PC and Nintendo Switch for a long time, until now. I don't have an easy way to prove this without having to reformat the NintendoSDK Firmware to run on something before Firmware for NX 17.0.1, and I had recent trouble with updating to that Firmware to properly work with the latest GameMaker Beta versions, so I don't want to mess with that right now.
I'm certain audio_create_stream worked for both PC and Switch in GameMaker Beta v2024.200.0.505

This error is consistently reproducible in my game project when playing on Nintendo Switch specifically.

___

I temporarily put the voice clips from Included Files/Datafiles into another file in the asset tree, that is played using audio_play_sound(), and the voice clip plays perfectly then. Not using audio_create_stream, just playing the sound directly from the asset tree.

I wrote debug code after trying to play a sound effect (like a voice clip for jumping), so we can see what value voice_jump has.

First, the audio is loaded using audio_create_stream() into the voice_jump variable, whenever the player object is initialized. That code is found in the Alarm0 Event, which runs when the player object is first created.

If voice_jump isn't holding any value, the variable just returns -4, and the error code doesn't appear at all.
Here is what that looks like, I temporarily commented out the code to load sound files from Included Files/Datafiles:
![when voice_jump variable is set to noone instead of loading in audio using audio_create_stream](https://github.com/YoYoGames/GameMaker-Bugs/assets/9497588/3fc73e0b-b6e5-4ca9-b5db-cfe6c65d7e8b)

Then, audio_play_sound() is trying to play voice_jump. Usually, if voice_jump isn't holding any value, it would return -4
But in this screenshot here, it does have a reference number for the variable, alongside the error message:
![voice_jump does have a ref sound value](https://github.com/YoYoGames/GameMaker-Bugs/assets/9497588/560bad4d-f3eb-40ac-b1a9-a26a34cbb5e5)

I only see the ov_open error whenever the game is trying to play a sound that has been loaded in using audio_create_stream(), it never seems to appear from just loading in the sound file, only when I try to play that sound file using audio_play_sound()

This does seem to be a bug within GameMaker itself.

___

I have recorded a video of the issue I'm experiencing, and I explain in more detail what is going on. I encourage you to please take a look:
https://www.youtube.com/watch?v=r23Wmdm0uJI

Here is a Google Drive link to the video recording as well, just in case:
https://drive.google.com/file/d/1XgKtIEubAuYKQW7ycIWN3IyrEj047aZv/view?usp=sharing

Here is my game project on GitHub, if you want to test for yourself if you get the same issues as I do: https://github.com/Jonnil/Sticky-Paws-DX

Here is the Google Drive link to my "Contact Us Package", the file was too big to attach in this description: https://drive.google.com/file/d/14JjyTBJSwYv2P16y2dnPcrRR25jNbo53/view?usp=sharing

Thank you for taking the time to read this!

### Expected Change

Would like some help resolving this issue so audio can be played from Included Files/Datafiles again on Nintendo Switch.

### Steps To Reproduce

1. Open GameMaker Beta v2024.400.0.526.
2. Load a project that utilizes audio assets.
3. Utilize the function audio_create_stream() to load music or voice clip audio from Included Files/Datafiles. For example:
`voice = audio_create_stream(file_path);`
4. Run the project on Nintendo Switch.
5. Attempt to trigger the playback of audio loaded using `audio_create_stream()`.
6. Observe that the audio fails to play and the following error message is displayed:
`Error (thread index 0): ov_open returned -128 -> A read from media returned an error.`

Additional testing:
1. Note the consistent reproducibility of this error when running the game on Nintendo Switch.
2. Temporarily relocate the audio files from Included Files/Datafiles to another location in the asset tree.
3. Use `audio_play_sound()` to play the audio files directly from the asset tree, bypassing `audio_create_stream()`.
4. Observe that the audio plays without error when bypassing `audio_create_stream()`.
5. Debug by checking the variable's value holding the audio stream (e.g., `voice_jump`) after loading with `audio_create_stream()` and before playback.
6. Note that the error message occurs only when attempting to play audio loaded using `audio_create_stream()` and not when loading the audio files directly from the asset tree.
7. Refer to screenshots and video recordings for further details and context. (https://www.youtube.com/watch?v=r23Wmdm0uJI)
8. Optionally, clone the game project from GitHub (https://github.com/Jonnil/Sticky-Paws-DX) for testing purposes.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Switch

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Also reported on zendesk ticket https://gamemaker.zendesk.com/agent/tickets/215736

**Comment by toby-yoyo** [comment]
Thank you for the detail in the bug report.

This is reproducible using this small test project: [gmb-5174.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14871995/gmb-5174.zip).

There was indeed a bug in the runtime relating to how streaming functions were being set up for Switch, which came about following some recent internal changes. This should now be fixed.
