### ISSUE TITLE
Code Editor 2: [Mac IDE]  Hovering over a GML function name does not render the name of the function or its arguments

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5206]
### Description

When CE2 is enabled hovering over a function won't render the function or argument names and types.

Diagnostics tooltips on Windows:
![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/c4d6bba8-708f-442b-a61a-a36bbed7ba0e)
Diagnostics tooltips on Mac:

https://github.com/YoYoGames/YoYoStudio/assets/105791928/15c7fd17-b3df-4424-bb47-b07ec6753cee

### Steps To Reproduce

1. Start GameMaker on Mac
2. Enable CE2
3. Open an asset with some code
4. Hover over a GML function and see the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.532  Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
The monospace font 'Consolas' is incorrectly selected on Mac OS X, the fallback to 'Open Sans' does not function in the new font renderer. These two bugs are manifesting as https://github.com/YoYoGames/GameMaker-Bugs/issues/5206, https://github.com/YoYoGames/GameMaker-Bugs/issues/5208, https://github.com/YoYoGames/GameMaker-Bugs/issues/6204

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
