### ISSUE TITLE
Code Editor 2: feather panel is not reinstated when CE2 is disabled and feather is enabled

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5207]
### Description

With feather is enabled in the prefs, if the user disables CE2, the feather tab is not reinstated unless GM is relaunched.

### Expected Change

The feather tab or Syntax Errors tab should be displayed depending if feather is enabled or not

### Steps To Reproduce

1. Start GameMaker
2. Ensure CE2 and Feather are both enabled
3. Disabled CE2
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.532  Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.534  Runtime v2024.400.0.553. 

Thank you.
