### ISSUE TITLE
Code Editor 2: Hovering over a custom function name displays an empty tooltip

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#5208]
### Description

When using Code Editor 2, hovering over a script function name will display an empty tooltip.

![CE2EmptyTooltipBug](https://github.com/YoYoGames/YoYoStudio/assets/87641114/d780f5b3-55b8-474a-b228-11aed8e9068a)

### Expected Change

The tooltip should show the function signature.

### Steps To Reproduce

1. Start GameMaker
2. Open a script with CE2 enabled
3. Hover over a script function name (not a GML function)
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.526 Beta Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
The monospace font 'Consolas' is incorrectly selected on Mac OS X, the fallback to 'Open Sans' does not function in the new font renderer. These two bugs are manifesting as https://github.com/YoYoGames/GameMaker-Bugs/issues/5206, https://github.com/YoYoGames/GameMaker-Bugs/issues/5208, https://github.com/YoYoGames/GameMaker-Bugs/issues/6204

**Comment by zreedy** [comment]
Fixed
