### ISSUE TITLE
Code Editor 2: Shader icons incorrect 

### ISSUE THREAD

**Issue by skud92** [YoYoGames/GameMaker-Bugs#5209]
### Description

<img width="420" alt="image" src="https://github.com/YoYoGames/YoYoStudio/assets/42850338/b8db4131-8e5f-4ff9-965d-8f476dda6d3d">

The shader icons are incorrect and need to be switched

### Expected Change

Icons to be swapped

### Steps To Reproduce

1. Start GameMaker
2. open shader asset in code editor 2
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

None

### Which version of GameMaker are you reporting this issue for?

 IDE v9.9.1.641  Runtime v9.9.1.758

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
This has been fixed for some time but this appears to have not been closed yet. Closing now.

**Comment by YYDan** [comment]
Yes, all looks fine in  IDE v2024.800.0.600  Runtime v2024.800.0.623

![image](https://github.com/user-attachments/assets/a01dfe0b-cae0-4d25-85a7-dedfc7466d7b)

Not sure if the manual needs any screenshots updated, etc., so will leave as Done just now.

**Comment by Emc1923** [comment]
Verified fixed, closing.
