### ISSUE TITLE
Code Editor 2: Minimap is very inaccurate when either hovering over it or click within it

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5212]
### Description

I know the FSD for the minimap states that the y-scale is not accurate but it really isn't accurate at all, to the point where it makes it rather unusable. I can see the coloured bars that represent the text but hovering over a particular coloured bar that you know represents a particular piece of code or click in the minimap on a part that you know is a particular piece of code, either displays the wrong code offset by a huge distance or jumps you to the wrong code entirely. 

Please see the below video

https://github.com/YoYoGames/YoYoStudio/assets/101252654/58ab943e-b640-4eaa-92ed-519d90d4cb59

When users get their hands on this they will without a doubt complain about this.

### Expected Change

Display the correct code

### Steps To Reproduce

1. Start GameMaker
2. Create a project with an object
3. Add a bunch of code
4. Hover over the minimap
5. See the issue
6. over over the minimap and click a location
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.400.0.526 Beta Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
What's your DPI? I think this might be DPI related.

**Comment by yyalansavage** [comment]
Fixed RE https://github.com/YoYoGames/GameMaker-Bugs/issues/5265
