### ISSUE TITLE
Code Editor 2: Multiple line selection box causes multiple text carets

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5213]
### Description

When attempting to use the multiple line selection box using SHIFT + ALT + ARROW KEYS the caret multiplies when you then use the arrow key to navigate out of the selection box as per the below video.

There is **_no_** information in the ui.log

Linked to bug: https://github.com/YoYoGames/YoYoStudio/issues/9655

https://github.com/YoYoGames/YoYoStudio/assets/101252654/c07c9613-a561-42ef-a53f-b89bb517688f

[emptyBetaProject.zip](https://github.com/YoYoGames/YoYoStudio/files/14776410/emptyBetaProject.zip)

### Expected Change

The selection box to end and the caret to return to normal (single caret)

### Steps To Reproduce

1. Start GameMaker
2. Load attached project and open Object1
3. Ensure CE2 is enabled
4. Place your caret somewhere in the code
5. SHIFT + ALT + RIGHT ARROW (a few times),
6. SHIFT + ALT + DOWN ARROW (a few times),
7. Just press the down arrow once
8. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.400.0.526 Beta Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by zreedy** [comment]
This is expected and documented behavior. Closing.
