### ISSUE TITLE
Code Editor 2:  Errors are not displayed if located inside a function

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5218]
### Description

When typing code that contains errors/ functions with missing arguments, the error warnings and underlining are never shown if located inside function brackets.

### Steps To Reproduce

1. Start GameMaker
2. Create a new object or script and try typing out some code inside a function while CE2 is enabled
3. See the issue

![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/051fa2f6-d548-455d-8dbf-3bba913effa1)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.520  Runtime v2024.400.0.540

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
This has been fixed for a while but this ticket was missed and not closed. Closing.
