### ISSUE TITLE
Code Editor 2: [Mac IDE] Asset name in navigation bar dropdown is always cut-off

### ISSUE THREAD

**Issue by skud92** [YoYoGames/GameMaker-Bugs#5220]
### Description

The asset title in the navigation is cut off in the first tab.

I've tried on multiple DPI settings and still seeing the same.

I'm using Mac.

<img width="392" alt="image" src="https://github.com/YoYoGames/YoYoStudio/assets/42850338/b4595f73-0751-4dda-bee8-91f02c7c3286">

<img width="364" alt="image" src="https://github.com/YoYoGames/YoYoStudio/assets/42850338/e260f0ea-f1f3-4faf-a6b0-c6294b5a762b">

### Expected Change

Title should be fully visible

### Steps To Reproduce

1. Start GameMaker
2. open code editor 2
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v9.9.1.628  Runtime v9.9.1.746

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
This should be fixed in the latest Beta

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.534  Runtime v2024.400.0.553.
