### ISSUE TITLE
Code Editor 2: Zoom controls should have more choices added so the jumps are not as large

### ISSUE THREAD

**Issue by skud92** [YoYoGames/GameMaker-Bugs#5224]
### Description

Dropdown is limited but for now we should go up in 25% increments, we should have 125% and 175% as options in here

![image](https://github.com/YoYoGames/YoYoStudio/assets/42850338/1af48ffa-a688-4b8c-8e5e-b181d7c90d80)

### Expected Change

Missing zoom settings added

### Steps To Reproduce

1. Start GameMaker
2. Open code editor 2
3. Select zoom controls bottom left corner of editor
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v9.9.1.555  Runtime v9.9.1.681

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by stuckie** [comment]
Closing in favour of https://github.com/YoYoGames/YoYoStudio/issues/9730

**Comment by sihammill** [comment]
Verified in IDE v2024.400.0.533  Runtime v2024.400.0.552
