### ISSUE TITLE
Code Editor 2: comment slashes in text files are a little awkward

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5228]
### Description

When you open a text file in the new code editor, it gets markdown formatting by default. This is usually okay but there are some cases where the line break rules make things a little ridiculous, such as in this license file.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/24aa5b5d-5295-4907-ab17-82d515d5a84d)

### Steps To Reproduce

1. Start GameMaker
2. open any non-code file
3. look for weirdness
4. see the weirdness

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment]
this is the file in question btw:

https://github.com/offalynne/Input/blob/master/datafiles/input_license.txt

**Comment by zreedy** [comment]
The rendered Markdown result shown is accurate. Markdown does not respect single new lines as a line break, it only recognizes double new lines as a line break.

**Comment by DragoniteSpam** [comment]
I know that, but this isn't a markdown file, nor does it have a markdown file extension. At minimum, plain text files like this shouldn't get any formatting, and it would be ideal if you could override the default formatting of a file with something else when appropriate.

**Comment by zreedy** [comment]
Text Files are rendered as Markdown now, so this is a markdown file in the Editor's eyes and as such is rendering correctly.

**Comment by mgeddesGM** [comment]
verified of  IDE v2024.800.0.590  Runtime v2024.800.0.614 as per previous comment
