### ISSUE TITLE
Code editor 2: Structs are colored as locals, and methods belonging to structs are colored grey, when calling a struct method inside another method

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5229]
### Description
Structs will be colored yellow, and methods belonging to the struct grey, when calling a struct method inside another method.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6378034f-2666-4789-bd62-25fea96b5a3f)

### Steps To Reproduce
```
testStructLiteral = {
    func : function(){}
}
testMethod = function() {
    testStructLiteral.func(); //shows as yellow and grey
}
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[feb6b2e5-8e1a-4c68-a9a8-9a63a01e2e5f](https://api.gamemaker.io/api/github/downloads/feb6b2e5-8e1a-4c68-a9a8-9a63a01e2e5f)

**Comment by KormexGit** [comment]
Found another similar case, it happens for accessing instance variables inside a method as well
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/306ac8d2-2d68-4884-afc1-d7bf90d9d217)

**Comment by KormexGit** [comment]
Actually, it seems to happen for every instance variable used inside a method
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/873b3edb-71dc-4ada-b058-59eeb06b72bc)

**Comment by zreedy** [comment]
Technically a Feather bug as Feather is not resolving the Self Context of anonymous functions assigned to an instance variable. Fixed for Scripts, pending fix for Events. Full fix might have knock on fixes for other Feather bugs.

**Comment by zreedy** [comment]
Fixed for Events now too. In addition a Feather bug where functions declared inside of Events did not resolve their Self Context correctly.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.580
