### ISSUE TITLE
Code editor 2: constructor methods will initially be yellow on the line they are called, and then change to orange if any edit is made on that line

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5230]
### Description
Constructor methods will be yellow when the project is first loaded, then turn proper orange after making any edit to the line.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/90761859-33fa-4fc2-8a36-1c48189f6016

### Steps To Reproduce
Create a constructor that has method variables inside. Call that constructor and store it in a function. Call one of the methods through that variable. Reload the project, and see that the method is yellow. Type anything else on that line, see it turn orange.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b3388f97-961c-4edf-94ec-a88978b2d99d](https://api.gamemaker.io/api/github/downloads/b3388f97-961c-4edf-94ec-a88978b2d99d)

**Comment by zreedy** [comment]
Appears fixed now, I suspect that one of the fixes to https://github.com/YoYoGames/GameMaker-Bugs/issues/5347 has fixed this issue.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.590  Runtime v2024.800.0.614, thanks.
