### ISSUE TITLE
Feather: Ctrl+Q "Create JSDoc Header" command only adds a @desc, none of the other information

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5232]
### Description

Feather sometimes has some helpful tooltips.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/f451d0f6-f336-41d0-a850-23c9cde19000)

But when you click on it, this is about as far as it gets before it makes like me on the US History AP exam and gives up like 25% of the way through:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/07ec4e09-419f-40a5-9c67-06cddc49a40f)

Using the fancy `///` auto-jsdoc feature in Code Editor 2, fortunately, gets a 5 on the AP Feather exam, and that's probably what I'm going to be doing most of the time anyway.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/891acad4-f592-49a0-a606-e4b245b418b2)

There probably a few other silly bugs in it. For example, one time when I clicked the icon it just went and deleted the whole function header:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/5c589f4f-176f-4b6c-8579-6147ea9cc265)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Would you be able to provide the function contents of the function shown in your ticket description? I'm unable to reproduce locally.

**Comment by zreedy** [comment]
Fixed

**Comment by alicemoretti** [comment]
On IDE v2024.400.0.543  Runtime v2024.400.0.562 when clicking on Create JSDoc Header nothing happens. 

I've tried this with both the function from the screenshots and my own functions and the result is the same. 

Reopening the bug. 

Could we please also get the code that this has been tested on originally? 

Thank you.

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified in IDE v2024.800.0.595  Runtime v2024.800.0.619, thanks.
