### ISSUE TITLE
Code Editor 2: Can't save JSON files (or any files from included files)

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#5233]
### Description
Seems to be bugged where I can edit JSON files, but I cannot save them. Not under any circumstance.

### Steps To Reproduce
1. Open up project
2. Open up Included Files from Hamburger menu
3. Open test.json in Script Editor
4. Try to edit/add/remove an entry
5. Try to save the normal way (ctrl + s), then try saving by closing and pressing "YES" to save.
6. Reopen test.json.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[fe9cea17-c007-4850-94d5-d86632041bfe](https://api.gamemaker.io/api/github/downloads/fe9cea17-c007-4850-94d5-d86632041bfe)

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.400.0.534  Runtime v2024.400.0.553.
