### ISSUE TITLE
please revert code editor 2 saving back to code editor 1 saving

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5237]
### Is your feature request related to a problem?

in code editor 1, the prequel, when you type type typed some fun code and then closed the editor it just saved the file. no popup, no warning, nothing. now in code editor 2, when you do a 'lil coding and then go to close the editor it asks you if you want to save.

this is polite, but, its gunna get people in trouble. i am going to accidentally click the wrong button, and i might even accidentally make the wrong option the default. i know i'm going to do this, because i've seen me do it a billion times before no matter how slow i am going, no matter how much i read. some people are going to accidentally go right no matter how slowly and carefully you tell them to turn left.

there should be no reason to give the user the option to semi-permanently never save their code again either, which is what happens if you select "dont show this again" and then hit "no" when it asks you to save. this is especially concerning given how gm saves assets straight to disc.

![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/223e4a1f-6ccf-4d6c-a04e-eb6b9835d7dd)

### Describe the solution you'd like

please revert code editor saving in code editor 2 to how it worked in code editor 1.

**Comment by stuckie** [comment]
We should fix the logic of "do not show this again" and No/Cancel.

**Comment by yyalansavage** [comment]
Dialog removed and now always saves changes, as code editor 1

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.541  Runtime v2024.400.0.560
