### ISSUE TITLE
Code editor 2: Breakpoints are added when releasing the mouse over the breakpoint area regardless of where the mouse was first clicked

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5238]
### Description
Breakpoints get added when the mouse is released over the breakpoint area, regardless of where the mouse was when you pressed the mouse button. I keep accidentally adding breakpoints while selecting things

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/47c090d3-0114-4975-a8c7-2b678059af4a

### Steps To Reproduce
Drag click to select some code, and release your mouse over the breakpoint column area.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[dbede126-b255-4160-88ef-dbc320831f31](https://api.gamemaker.io/api/github/downloads/dbede126-b255-4160-88ef-dbc320831f31)

**Comment by stuckie** [comment]
The mouse up/down should be in the same line to place the breakpoint

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.400.0.535  Runtime v2024.400.0.554
