### ISSUE TITLE
Inspector Add Event Shortcut

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5239]
### Description
The shortcut to add event is no longer work in the inspector. (CTRL+A)

### Steps To Reproduce
Open object in new code editor, click in the events and use the shortcut, it will open the "create new asset" window instead of the event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[387c32dd-18a9-49ff-bbb7-c7dfbb785d8d](https://api.gamemaker.io/api/github/downloads/387c32dd-18a9-49ff-bbb7-c7dfbb785d8d)

**Comment by SmithTom6304** [comment]
Should now be fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
