### ISSUE TITLE
Code editor 2: Using the ctrl + Q context menu to add a comment to ignore a feather message deletes code without adding the comment 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5241]
### Description
After seeing the comment on my FR I went to test out this feature, and discovered that it deletes code instead of adding a comment in the new code editor.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/845c2e74-40d3-4954-bc24-05a83f8d43b8

### Steps To Reproduce
Type any code that triggers a feather message. Click on the underlined code, hit ctrl + Q, and navigate the menu to do "disable once with comment". Instead of adding the comment, the selected code will be deleted.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[748c7eca-46c7-47fc-9f3e-460e3503473a](https://api.gamemaker.io/api/github/downloads/748c7eca-46c7-47fc-9f3e-460e3503473a)

**Comment by zreedy** [comment]
Partial fix as part of #5275

**Comment by zreedy** [comment]
This is now fixed. The following now fixed sub issues contributed to this ticket:
 - Client's line feed tracking did not handle Workspace Edits correctly resulting in a phantom line join, desyncing client and server and corrupting the file on close. This also corrupted color coding.
 - Deleting the final line feed was impossible for the server to interpret, leading to desync. When Workspace Edits were dispatched the desync would lead to corruption.
 - Bad Workspace Edits would throw unhandled exceptions.

In some cases these desyncs would result in the server issuing illegal edits which modified non-existent text outside of the buffer.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.538  Runtime v2024.400.0.557.
