### ISSUE TITLE
Code editor 2: Enter key does not work while holding a modifier key or after releasing the modifier if nothing else has been pressed inbetween

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5244]
### Description
Enter doesn't work while holding shift, alt, or ctrl, and will continue to do nothing even after the modifier key is released, until another key is pressed.
This seems to be a new code editor specific incarnation of a previous report I made that got fixed, #2161

### Steps To Reproduce
Hold shift, alt, or ctrl, and hit the enter key. No line break will be added. Release the key and hit enter again, the line break will still not be added.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[1d9819ca-1a51-492d-b3e8-6388a0f7cc06](https://api.gamemaker.io/api/github/downloads/1d9819ca-1a51-492d-b3e8-6388a0f7cc06)

**Comment by JonathanHackerCG** [comment]
This is also true of backspace and delete.

**Comment by zreedy** [comment]
@SmithTom6304 We need to add the `Any` keyword to the hotkey spec to address this.

**Comment by SmithTom6304** [comment]
`Any` modifier functionality has been added. Closing.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.538  Runtime v2024.400.0.557
