### ISSUE TITLE
Code Editor 2: Auto-Indenting Doesn't Support Allman Style

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#5245]
### Description
Auto-Indenting will not indent correctly with Allman indenting style (when the opening brace is on line after the condition).

### Steps To Reproduce
Type a condition and add braces.
1) If the first brace is on the same line as the condition, pressing enter will correctly add the closing brace and the necessary intendation.
2) If the first brace is on the line *after* the condition, pressing enter will not add the expected indentation. See image.

EDIT: This happens with every setting for Auto Indent Mode, including "None" which implies a secondary bug that the Auto Indent Mode options aren't applying in the first place.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5558c9c4-1d13-4dad-8890-7e5eed99ae07](https://api.gamemaker.io/api/github/downloads/5558c9c4-1d13-4dad-8890-7e5eed99ae07)

**Comment by JonathanHackerCG** [comment]
One more follow-up, I've now tested more carefully with all the Auto Indent Modes.

None: Does nothing (correct).
Keep and Full: Incorrect behavior for Allman style (shown above).

Braces: Incorrect behavior for Allman AND K&R, shown in this screenshot. This one is extra weird, I am unconfident with my testing for this mode but whatever it's doing is definitely not intuitive or correct.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/49505360/e7e3dd05-0db3-4ba8-8720-6001ac645a66)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
