### ISSUE TITLE
Code Editor 2: Changing Auto-Indent Mode Requires IDE Restart

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#5246]
### Description
Auto-Indent Mode preferences do not apply until after an IDE Restart. This may be intended, in which case the IDE should prompt a restart like it does for other such preferences.

### Steps To Reproduce
Change Auto Indent Mode to "None" and see that the Code Editor 2 is still auto indentin. Or, visa versa.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[489fd532-3ee2-416b-9431-3c0f8668f3b6](https://api.gamemaker.io/api/github/downloads/489fd532-3ee2-416b-9431-3c0f8668f3b6)

**Comment by zreedy** [comment]
Fixed, all brace modes behave as expected without restarting the IDE now.
