### ISSUE TITLE
Code Editor 2: Deleting a line with "Delete" will insert phantom spaces.

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#5248]
### Description
Pressing delete with the cursor at the end of a line will insert a space after the cursor.

Putting cursor here and pressing "Delete":
```
//A|
//B
```

Results in this:
```
//A| //B
```

This also seems to mess up syntax highlighting under some conditions, but I cannot reliably replicate.

### Steps To Reproduce
Put cursor at end of a line and press "Delete".

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[1477be83-91fe-42c4-ae10-b863a91d9ab0](https://api.gamemaker.io/api/github/downloads/1477be83-91fe-42c4-ae10-b863a91d9ab0)

**Comment by zreedy** [comment]
This is by design, except that comments should not have this behavior as whitespace is not significant in this way.

**Comment by zreedy** [comment]
Fixed the unexpected behavior of whitespace being added inside of comments or strings. The whitespace is still added between statements and experssions.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
