### ISSUE TITLE
Code Editor 2: F1 not opening manual

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5249]
### Description
If you are sitting on a blank line, or #endregion and hit F1 the manual isn't being opened. You have to be on an actual function that is built in to gamemake like asset_get_index

### Steps To Reproduce
1. open gamemaker
2. create new object
3. add event
4. hit f1

No manual opens and it should

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b71bf248-0176-4a48-9a73-b9137fffae52](https://api.gamemaker.io/api/github/downloads/b71bf248-0176-4a48-9a73-b9137fffae52)

**Comment by gnysek** [comment]
`F1` in code editor is `Go to Declaration`:

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/124c4624-fd06-47b7-9c5a-128e55468824)

Old `F1` still works as expected outside of Code Editor 2.

**Comment by stuckie** [comment]
Likely related to #5642

**Comment by yyalansavage** [comment]
F1 will now open the manual home page when cursor is on a blank line. After discussion with Zach, the manual home page will not show when the cursor is over some text and there is no manual page or code declaration to navigate to for that symbol.

**Comment by caitlinrmcintyre** [comment]
Reopening as this is still broken for me in IDE v2024.600.0.558  Runtime v2024.400.0.571.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.560  Runtime v2024.600.0.577, thanks.
