### ISSUE TITLE
Code Editor 2: Frequent LSP errors on opening new project

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5251]
### Description
Opening a new blank project prompts the LSP error:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/9e321615-069a-4101-bb49-3a6772a23844)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[8c5ffa1b-a21f-48c7-b52b-6895e49545f7](https://api.gamemaker.io/api/github/downloads/8c5ffa1b-a21f-48c7-b52b-6895e49545f7)

**Comment by zreedy** [comment]
Essentially the same ticket as https://github.com/YoYoGames/GameMaker-Bugs/issues/6701 which is fixed.

**Comment by scott-dunbar** [comment]
No longer able to repro linked issue or this one in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664
Closing
