### ISSUE TITLE
[Code Editor 2] Shown whitespace is duplicated from above line

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5252]
### Description
With the option **Show whitespace** enabled, the whitespace indicators for a line are duplicated for every empty line below.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/98053cd6-1c44-4c57-b7fd-5c6d232d6dee)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[ba921db7-972a-4771-935d-f8775dcb3d4b](https://api.gamemaker.io/api/github/downloads/ba921db7-972a-4771-935d-f8775dcb3d4b)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.577  Runtime v2024.600.0.603
