### ISSUE TITLE
[Code Editor 2] Clicking a search result doesn't jump to line

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5253]
### Description
When using **Ctrl+Shift+F** to search the whole project, clicking a result in CE1 jumps to the line in the given file. In CE2 it only jumps to the file, but not the line.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[ff8b3579-f8cd-4fcc-ac3d-093b0373f9be](https://api.gamemaker.io/api/github/downloads/ff8b3579-f8cd-4fcc-ac3d-093b0373f9be)

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.541  Runtime v2024.400.0.560
