### ISSUE TITLE
[Code Editor 2] Enabling ligatures severely breaks tabs

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5254]
### Description
With ligatures enabled, tab indentation causes the visible code to completely misalign with the actual selectable/editable code.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/a5288ae8-c7ca-495f-8b61-fb5f5214344e)

### Steps To Reproduce
Enable ligatures and indent some code with tabs.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[291892ec-9817-476d-8cda-6751d62dd675](https://api.gamemaker.io/api/github/downloads/291892ec-9817-476d-8cda-6751d62dd675)

**Comment by thennothinghappened** [comment]
I also accidentally got it to make my comment italic:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/c5c76750-98fb-4952-b3f3-937b9c95530b)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
