### ISSUE TITLE
Code Editor 2: Tab indentation becomes incorrect when there are multiple indent levels in your code

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5256]
### Description
With the editor set to use tabs instead of spaces, the actual size of the Tab characters becomes completely incorrect - you can also enable ligatures to make this even more broken :P
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/4b46be3f-7d8a-4c90-9c36-3047b0da44b1)

### Steps To Reproduce
Indent some code multiple levels with tabs instead of spaces, and note that the selected size of the tabs seems totally wrong.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[e80e281a-d7ea-4883-b544-32fbb8d0fa8f](https://api.gamemaker.io/api/github/downloads/e80e281a-d7ea-4883-b544-32fbb8d0fa8f)

**Comment by zreedy** [comment]
This appears fixed in the current public Beta. This would have been fixed as part of the changes to the new font renderer, but was missed in the search for tickets related to those bugs.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.581
