### ISSUE TITLE
[Code Editor 2] Renaming a script while it is open loses your work!!!

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5257]
### Description
When you create a new script, CE2 immediately opens. However, you can still rename the script. Doing so will rename the new CE2 tab, but will *not* change the file it is trying to write with. Code written in this phantom window cannot be saved - pressing **Ctrl+S** will still show the \*, and closing and reopening the file will show it only contains the default content.

I originally thought this was only related to renaming files on creation, but on further inspection it seems to occur any time you rename a file that is currently open.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[4bf2fb6c-a285-4d1d-87a4-16d2d2e36a8c](https://api.gamemaker.io/api/github/downloads/4bf2fb6c-a285-4d1d-87a4-16d2d2e36a8c)

**Comment by zreedy** [comment]
Partial fix addresses the ticket, pending restoration of LSP services to the renamed file to close.
This ticket had issues on both the client and server which manifested across multiple features:
 - Server - Possible for multiple resources of the same name to be added to storage, preventing documents from being relinked correctly when renamed.
 - Server - While assets were deleted, they were not removed from Project storage resulting in incorrect Feather behavior.
 - Client - Cached path in Document was not updated causing the adapters to fail a find for the renamed document while attempting to save.

The issue in the Client's cache also resulted in improper Workspace Editor behavior as the path lookup is done for modifying not-in-memory Documents.

**Comment by zreedy** [comment]
Fixed. Language Services are restored to the renamed asset as the old Document is Closed and new Document is Opened.
Additionally, another fix for the the `DocumentLinks` property has been applied which was attempting to reopen a document on the server every time any property changed. This probably impacted performance and behavior over a session.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.539  Runtime v2024.400.0.558
