### ISSUE TITLE
[Code Editor 2] Ability to toggle Markdown preview

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5258]
### Is your feature request related to a problem?

As cool as the preview is to have now, it doesn't seem to have a way to turn it off for when you want a fullscreen editor window.

### Describe the solution you'd like

A button to toggle the preview would be nice :)

### Describe alternatives you've considered

Not having said button.

**Comment by yyalansavage** [comment]
Added a close markdown preview option in right-click context menu, when markdown preview is already open

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.581
