### ISSUE TITLE
CodeEditor2: The minimap does not show all the lines of code when scrolled

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5259]
### Description
There is a bug with the mini editor viewer where some lines of code are not showed.

### Steps To Reproduce
1) See the uiMenu code object
2) Use the mini-editor to move the editor
3) see how there is not some lines of code showed.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[54a632fd-cca9-4d31-8efc-7e6cde7e644b](https://api.gamemaker.io/api/github/downloads/54a632fd-cca9-4d31-8efc-7e6cde7e644b)

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.400.0.541  Runtime v2024.400.0.560.
