### ISSUE TITLE
[Code Editor 2] Markdown code block doesn't respect newlines

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5261]
### Description
In the markdown preview, multiple newlines aren't respected and it only shows one newline max:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/fdb8eae3-1808-4c81-a3eb-f3dda3001dd8)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[6779d11d-19b5-4c87-8509-6ad0fa171f9c](https://api.gamemaker.io/api/github/downloads/6779d11d-19b5-4c87-8509-6ad0fa171f9c)

**Comment by zreedy** [comment]
This is fixed now.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
