### ISSUE TITLE
Code Editor 2: Deleting a character will delete 2 characters instead

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5262]
### Description
dunno about this one, but if you try to delete a character it will delete 2 characters and not 1.

weird.

### Steps To Reproduce
open the uiMenu objetct of the attached proyect

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[7ed9fed0-254e-4bca-aa8a-8a87448fbf41](https://api.gamemaker.io/api/github/downloads/7ed9fed0-254e-4bca-aa8a-8a87448fbf41)

**Comment by zreedy** [comment]
Fixed. Verified against FireCode with Ligatures Enabled.
This bug was related to the Font Rendering bugs that were fixed last month and was missed while closing those tickets out.

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.571  Runtime v2024.600.0.597
