### ISSUE TITLE
[Code Editor 2] Autofilling `function` keyword puts cursor in wrong place

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5263]
### Description
Sometimes, accepting autocomplete for the `function` keyword when writing a method causes the cursor to jump backwards, and inserts brackets in the wrong place.

### Steps To Reproduce
Take the following code:
```gml
function Blah() constructor {
	
	self.idk = func
	
	
}
```
...and finish writing the word `function` there, autocompleting the suggestion. The cursor will jump backwards to before the equals.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[2f98b0ec-8468-4fc2-ba74-8da7ad53c16b](https://api.gamemaker.io/api/github/downloads/2f98b0ec-8468-4fc2-ba74-8da7ad53c16b)

**Comment by KormexGit** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f4743dbb-0857-49d1-bf52-28c1783ecebe

Also happens for the constructor keyword

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1151  Runtime v2026.100.0.1101
