### ISSUE TITLE
Code Editor 2: Various ways to still open CE1 windows when CE2 is enabled, causes saving fails

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5271]
### Description
If you have the new code editor enabled, right clicking an object in the asset browser and hitting "open all event scripts" will still open the old code editor. This old code editor window will be broken, with no variable colours, and no edits made can be saved. It will also not reflect changes made in the new code editor window.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f5a14138-b53d-4f31-9771-138a877a4ecf

### Steps To Reproduce

```
1. Enable the new code editor
2. Right click an object in the asset browser and hit "open all event scripts"
3. Observe the issue
Repro: 100%
```

```
1. Start GM and reach the Start Page
2. Enable Preferences > Asset Browser > "Object double click opens all object events"
3. Enable Preferences > Code Editor 2 >"Enabled"
4. Open any project
6. Double-click an object in the Asset Browser
7. Observe CE1 is opened
Repro: 100%
```

```
1. Start GM with CE2 disabled or enabled (either)
2. Open a project and then open some events/scripts
3. Close that project and open/create a second project
4. In this second project, flip your CE2 status and then open some events/scripts
5. Observe you can edit them and they save correctly, etc.
6. Close project2 and reopen project1
7. Observe that the old windows already open in the project layout remain using the _other_ code editor
8. Observe that whilst you can visibly edit these windows, nothing will save
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d1d04211-e993-4e5e-a90b-553ea5012f5a](https://api.gamemaker.io/api/github/downloads/d1d04211-e993-4e5e-a90b-553ea5012f5a)

**Comment by KormexGit** [comment]
You can also get this broken old editor open by enabling the new code editor in one project, and then swapping to another project that had windows with the old editor open. Toggling the new code editor normally clears all open tabs, but it doesn't when swapping to another project that had the different setting before. 
You can also do the reverse, and get a broken version of the new code editor by disabling the new code editor in a different project and then swapping back.

**Comment by alicemoretti** [comment]
Hi @KormexGit , thank you for your report. 

We were able to reproduce your initial issue but we didn't see any issues when trying the other 2 ways of reproducing it (the ones in the comment). 
Could you provide more info about those please? Does it happen for every project? What type of assets do you have open (objects, scripts...) ? 
Could you attach a video of the issues please? 

Many thanks.

**Comment by KormexGit** [comment]
@alicemoretti here's a video:
https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8738e3d6-bdd3-41ac-8dbf-28491a8a3979

It happens any time you change having the new code editor enabled or not in one project, and then swap to a different project that had the opposite setting, in this case use old code editor, swap to a different project, enable new code editor, swap back to original project. In the video I'm hitting ctrl+S to save after adding the space in both cases, but the * to indicate unsaved changes isn't going away.

**Comment by YYDan** [comment]
I've now confirmed and brought in the repro steps from https://github.com/YoYoGames/GameMaker-Bugs/issues/5288, plus added steps for the comments above.

(They're in code blocks as GitHub apparently does not like multiple numbered lists in one issue...)

**Comment by zreedy** [comment]
This option should not be available when CE2 is enabled as it's redundant. The fix is to remove this entry from the context menu when CE2 is enabled.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.539  Runtime v2024.400.0.558
