### ISSUE TITLE
Code Editor 2: Caret position goes always back to column 0 outside of statements, rather than maintaining current tab level

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5272]
### Description

When having part of code which is indented by tab, CE2 automatically goes back to column 0 instead to keep that tab in next line if not inside (`if`) statement. Auto-indent mode seems to not have any impact on that setting.

https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/933704e4-aef2-4e9c-a3cc-7a55a3768246

### Steps To Reproduce

1. Put at least one tab before line of code
2. press enter
3. It goes back to column 0, not keeping indent in code

### How reliably can you recreate this issue using your steps above?

Always

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.571  Runtime v2024.600.0.597
