### ISSUE TITLE
Code Editor 2: Possible to have multiple autocomplete windows open at once

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5276]
### Description
You don't need to be super quick, but if you start typing something in one event, and then click to the other event before the intelesense takes place, you will end up with multiple intelesense windows opened.

### Steps To Reproduce
1. create two events
2. start typing # in the first event
3. click to the 2nd event before intelesense takes over
4. profit.. i mean now you have two windows.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a923883d-f524-42b7-b8c6-866a9295c95e](https://api.gamemaker.io/api/github/downloads/a923883d-f524-42b7-b8c6-866a9295c95e)

**Comment by michael-mcmullen** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/811123/9705ab9d-240b-4ddc-940e-22535328d0c3)

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.400.0.534  Runtime v2024.400.0.553
