### ISSUE TITLE
Code Editor 2: numbers are replaced to variables when pressing enter

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5277]
### Description

When writing things like `x+=4` and pressing enter, alphabetically first variable is entered in place of `4` in code editor instead of going to newline. This happens only if:
- there's no semicolon
- code completion window was shown.

https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/dad25448-b6e8-4701-8c3f-43a285676e7e

### Steps To Reproduce

1. Write `x+=4` (without semicolon), press enter
2. It would replace `4` to first variable that was an option in code completion.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

**Comment by zreedy** [comment]
Fixed. Improvements to Code Completion Candidate Window prompting:
 - Only prompts for alphanumeric_ symbols which do not begin with numbers
 - Candidate Window follows cursor when typing space
 - Changed automatic prompting to only trigger when `(` is typed for statements or function calls

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.557  Runtime v2024.600.0.572
