### ISSUE TITLE
Code Editor 2: Split document view does not update when I change asset

### ISSUE THREAD

**Issue by skud92** [YoYoGames/GameMaker-Bugs#5279]
### Description

I split my document horizontally to view different parts of the same document
When I changed asset via the nav bar the top section changed to the new asset code
The bottom section still showed the previous asset code.

This is not intentional and can be confusing for users. (It gives the impression they can switch assets in both panels - more like the window paradigm design)

https://github.com/YoYoGames/GameMaker-Bugs/assets/42850338/df11d7cf-1f04-45de-b755-c95ffe10f80a

Suggestion:
1. We remove split when asset is changed
2. We keep split and show the new asset at the top of both documents

I can see pros and cons for both, I think option one is less confusing for beginner users?

### Expected Change

Document splitter removes if user changes asset when it is applied

### Steps To Reproduce

1. Start GameMaker
2. open code editor 2
3. Drag document splitter down
4. change asset via nav bar
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.400.0.534  Runtime v2024.400.0.553
