### ISSUE TITLE
Code Editor 2 - Fonts are not alphabetically ordered

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5280]
### Description
There are some fonts that are missing in the Code Editor 2 but exists in the original code editor (space mono is one of them)

### Steps To Reproduce
Preferences - > Code Editor 2 -> Font Drop Down

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[656c6dea-056e-4e5f-b9de-f3cfb9c847b8](https://api.gamemaker.io/api/github/downloads/656c6dea-056e-4e5f-b9de-f3cfb9c847b8)

**Comment by michael-mcmullen** [comment]
Sorry finally took another look, they aren't missing but the font list isn't ordered causing the fonts I was expecting to be at the very bottom of the drop down instead of in alphabetical order

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/811123/cba86586-1555-4779-a14c-ec84ce63e022)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/811123/d1aef3db-2250-4bc7-9f3a-2e9e1ffc5cba)

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.672  Runtime v9.9.1.814
