### ISSUE TITLE
Building Projects: [HTML5] Sound assets are not exported on Beta Runtimes 2024.400.0.550+

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#5283]
### Description

This issue is not present in Beta Runtime 2024.400.0.549 - the only change between the two is a fix for https://github.com/YoYoGames/GameMaker/issues/3803, so that might be a good place to start looking for the root cause.

**Example game directory (2024.400.0.549)**
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/9fb5005a-352d-4dcf-9ffd-5168019d110e)

**Example game directory (2024.400.0.550)**
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/98745055/eb7f76ad-09ba-41dc-a416-b3cae6df21ee)

### Steps To Reproduce

1. Open and run the example project on HTML5: [gmb-5283.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14855237/gmb-5283.zip)
2. Click the page when prompted.
3. Observe that no sound plays.
4. Open the browser console.
5. Observe that various errors such as:
```
error decoding audio data:EncodingError: The buffer passed to decodeAudioData contains an unknown content type. 
Unhandled Rejection - undefined
Uncaught (in promise) DOMException: The buffer passed to decodeAudioData contains an unknown content type.
...
Unhandled Rejection - undefined
Uncaught (in promise) TypeError: BaseAudioContext.decodeAudioData: Buffer argument can't be a detached buffer
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

HTML5

### Are you running GameMaker from inside your Steam library?

No

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
