### ISSUE TITLE
With CE2 is enabled the old code editor doesn't save changes anymore

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5288]
### Description

When CE2 is enabled you can still access the old code editor if you have the preference "Object double click opens all object events" (in the category "Asset Browser") selected. 

If you then open an object via a double click from the Asset Browser it opens all events in script tabs with the old editor.

Any changes you now make in the scripts cannot be saved - even if you press Ctrl+S or using the file menu. The project itself is saved but the changes to the script aren't.

Apart from this bug the question is whether the option "Object double click opens all object events" should actually open the old code editor even if CE2 is enabled? 

### Expected Change

Make old code editor save changes when new code editor is enabled.

### Steps To Reproduce

1. Enable new code editor
2. Enable Preference "Object double click opens all object events" in category "Asset Browser"
3. Open an object with events via double click from the asset browser
4. Make changes to an event script in the old editor
5. Try to save the project - the script changes won't be saved
[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858298/contactus.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
To be clear: "CE1" is genuinely disabled when "CE2" is enabled, so it's actually known/expected that it's not saving... However, the actual problem here is that you're able to see a CE1 window at all, so _that's_ the bit we're going to fix ;)

**Comment by YYDan** [comment]
Your steps are ultimately the same as https://github.com/YoYoGames/GameMaker-Bugs/issues/5271 but just a different Preference being enabled, so I have confirmed it and added all the info into that other issue.
