### ISSUE TITLE
CE2: Markup "Horizontal Line" appears incorrectly after @object or #color entries

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5289]
### Description

When using the @object or #color notation in CE2 and immediately afterwards add a horizontal line (---) then the line is not displayed _below_ the object or color representation but next to it (see attached screenshot).

![horizontalline](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/2cf119ce-a1a3-4e4f-a699-6e0feb74603f)

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858394/contactus.zip)

### Expected Change

The horizontal line should always appear beneath the content that came before it, not next to it.

### Steps To Reproduce

1. Open a note in CE2
2. Add an @object or #color element 
3. Add a horizontal line (---)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
