### ISSUE TITLE
CE2: Minimap code preview shows wrong position

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5290]
### Description

When using the code preview while hovering over the minimap in CE2 the preview window often shows content that is offset vertically. The offset gets worse when you scroll the code window down.

See the two attached screenshots. The red cross marks the position where the mouse cursor was located at the  time of the screenshot. In the first image you can see a code preview in an area where there is no code in the minimap. In the second image you can see an empty preview window even though the mouse hovers over an area with code in the minimap.

![map01](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/e9a81bf3-1305-4876-adc6-80bd7fb04ebd)
![map02](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/fb26677b-a48b-4237-a8b1-8229ef8ef7a4)

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858490/contactus.zip)

### Expected Change

Minimap preview always shows the correct section that the mouse currently hovers over.

### Steps To Reproduce

1. Enable CE2 and the Minimap code preview
2. Create a long piece of code
3. Scroll around in it
4. Hover your mouse over the minimap and check the preview window. It's content is offset and doesn't show the content you are currently hovering over with your mouse in the minimap.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.541  Runtime v2024.400.0.560
