### ISSUE TITLE
Code Editor 2: Default behaviour for Ctrl+Home/End keys should be to go to the end of the Editor View, not the current Document

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5292]
### Description
The default for using the home/edit keys should be changed. You have given us a full editor with out the ability to quickly go through the code.

If I am at the top of the code and I press ctrl + end, I should go to the end of my code, not the end of my function.

Why does Page Up / Page Down allow me to travserse this but the home / end keys do not.

### Steps To Reproduce
Open a large object with code and press the home / end keys with the ctrl

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3cf5c3c5-c753-4103-beac-54555e04d03b](https://api.gamemaker.io/api/github/downloads/3cf5c3c5-c753-4103-beac-54555e04d03b)

**Comment by zreedy** [comment]
Conferred with UI/UX and determined that the current behavior is expected and should stay. However, a new hotkey for going to the start/end of all Documents in the Editor View will be added to fulfill this Feature Request.
- Ctrl+Home/End -- Move to the first/last line of the active Document
- Ctrl+Alt+Home/End -- Move to the first/last line of all Documents in the Editor View

**Comment by zreedy** [comment]
Fixed.

**Comment by alicemoretti** [comment]
Verified fixed on Beta IDE v2024.800.0.593 Beta Runtime v2024.800.0.617.

Thank you.
