### ISSUE TITLE
Code Editor 2 - Multicursor doesn't work

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#5293]
### Description
Using the multicursor the cursor dissapears as soon as you try to change something.

### Steps To Reproduce
Write something like

cursor_x = x + lengthdir_x(cursor_length, rotation);
cursor_y = y + lengthdir_y(cursor_length, rotation);

Now select both rotation variables; try to change and it will fail

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[724ea9e3-e85f-4853-89b7-72d2856e7a05](https://api.gamemaker.io/api/github/downloads/724ea9e3-e85f-4853-89b7-72d2856e7a05)

**Comment by zreedy** [comment]
Fixed

**Comment by cameron-home** [comment]
@zreedy Do you have a test project for this?

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.604  Runtime v2024.800.0.627
