### ISSUE TITLE
CE2: Tab size preference doesn't have an effect when using tabs

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5295]
### Description

Settings the "Tab size" preference in combination with using "tabs" as tab type for indentation doesn't take effect - it always uses a tab size of 4.

(When using "space" as the tab type then the "tab size" settings is taken into account correctly)

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858814/contactus.zip)

### Expected Change

Make the "tab size" preference take effect when using "tabs" as "tab type"

### Steps To Reproduce

1. Set "tab size" in CE2 preferences to anything other than 4 and use "tabs" as "tab type"
2. Type some code and indent it using tab. It will not use the new setting but always use 4.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.568  Runtime v2024.600.0.595
