### ISSUE TITLE
CE2: Code folding destroys usability

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5296]
### Description

Creating a region when using CE2 and then collapsing it destroys the editor's usability. The editor doesn't seem to recognize correctly that the region is collapsed. It leads to all sorts of visual artefacts.

The same is true for collapsing functions but it's even more extreme with regions.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858844/contactus.zip)

### Expected Change

Make code folding work correctly.

### Steps To Reproduce

See above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Retrific** [comment]
Related https://github.com/YoYoGames/GameMaker-Bugs/issues/5267
