### ISSUE TITLE
CE2: Clicking in empty space below code in one event jumps to another event

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5298]
### Description

This only occurs if the preference "Show all documents in a single view" is **unchecked**.

If you have an object with multiple events and one of them is open in CE2 then if the code in that event doesn't fill the whole screen and you click somewhere **below** the last line of the code then the editor changes to another event (acutally to the last event in the list).

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858875/contactus.zip)

### Expected Change

Stay in the current event even if you click below the code.

### Steps To Reproduce

1. Enable CE2 and disable the preference to "Show all documents in a single view"
2. Create an object with a Create Event and a Step Event. Add three lines of code to each.
3. Open the Create Event.
4. Click somewhere **below** the three lines of code -> The editor changes to the Step Event.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
