### ISSUE TITLE
In-Game: [Windows] Using an IME whilst game is fullscreen will cause the window to become distorted and not have the titlebar

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#53]
GM-7561

When using an IME on Windows whilst running an executable of a game will cause the game to become windowed and stretched. The game can only be restored to normal by toggling fullscreen off and on again. 

The game also remains in fullscreen mode after becoming distorted, despite now being windowed, with window_get_fullscreen() returning as true. See image below.

*Steps:*

# Set-up an IME in Windows Settings > Language, for example Chinese
# Launch any project with where fullscreen is enabled/ Starts fulscreen
# Swap your keyboard input to Chinese/Japanese/Other and ensure it's on Chinese/Japanese/Other mode    !screenshot-1.png|thumbnail! 
# Start the project
# Begin typing using any keys
# Observe the issue
# Toggle fullscreen
# Observe the game is restored

*Repro:* 100%

**Comment by YYDan** [comment]
Effectively fixed by the changes in https://github.com/YoYoGames/GameMaker-Bugs/issues/5524

Closing.
