### ISSUE TITLE
CE2: Note Editor: ä,ö,ü,ß destroy the editor

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5300]
### Description

Using characters like ö ä ü ß in the new notes editor causes lots of glitches. Text appears shifted and overlayed on top of itself. But even more dramatic, when you continue typing, some letters are replaced by others and the whole thing gets unstable until you restart GM.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14858975/contactus.zip)

### Expected Change

Make the node editor accept special characters.

### Steps To Reproduce

See above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gnysek** [comment]
Same issue with Polish language, font becomes smaller by 1-2px, but selecting is still working for original font, so cursor, selections and all stuff gets in wrong place.

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/7de59d50-69ef-4da8-9dfe-12c81d8e12cb)

(lower line have character `ź` instead of `z`)

**Comment by stuckie** [comment]
We are pretty sure this is actually all in, just that GitHub did some weirdness with the PRs so these were cherry-picked manually.

**Comment by gnysek** [comment]
I think this was resolved when font renderer was updated in some of recent versions. I would confirm when .800 beta is officially out.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
