### ISSUE TITLE
CE2: Code minimap shows all the events even if only a single event is viewed

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5302]
### Description

This only happens if the preference "Show all documents in single view" is **unchecked**.

If you have the code minimap enabled it shows an overview over **all events** of an object even if you only view the script for a single event.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14859056/contactus.zip)

### Expected Change

Minimap should show only the event script that is currently selected.

### Steps To Reproduce

1. Enable CE2 and disable "Show all documents in single view"
2. Create an object with a couple of events and add some placeholder code
3. Open one of the events in the new code editor.
4. Look at the minimap: it shows an overview over all the events of the object below each other instead of only the currently active event.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.400.0.541  Runtime v2024.400.0.560.
