### ISSUE TITLE
[Code Editor 2] Buggy double-click selection behaviour

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5306]
### Description

This one's a little hard to describe, so I've attached a video:

https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/ad17e17a-c484-47c0-bd4e-126790051551

In essence though, when double clicking to select words, CE2 seems to really want to select the entire line if your cursor is over the edge between words, or over some kind of punctuation - such as `(),.` etc - or whitespace.

I use this functionality a *lot* in editors and this issue makes about half my quick selections in CE2 incorrect.

### Steps To Reproduce

Take a line of code in CE2, and double click a word. Drag your selection across the line, and on encountering the listed symbols the selection will randomly flicker to the entire line. If you now release your click there's a chance it'll have either selected what you intended, or has selected to the end of the line.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Ventura

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. This was fixed as apart of the Font Rendering/Ligature fixes in May.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.600.0.585  Runtime v2024.600.0.609, thanks.
