### ISSUE TITLE
Code editor 2: Typing an apostrophe in a comment adds a 2nd apostrophe, as if it's a quote

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5311]
### Description
When typing comments, using an apostrophe adds another one. While this makes sense for quote marks ", apostrophes are used in lots of actual words. I noticed this while reporting my previous bug, when typing a comment I ended up with:
```
//this code won't save'
``` 
The ' in won't got duplicated

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a24304da-2699-493f-87b0-8c4b843695ec

### Steps To Reproduce
type this:
```
//it's a comment
```
and it will appear as 
```
//it's a comment'
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[fdc02e8b-c165-4898-bc34-dc5ac791da45](https://api.gamemaker.io/api/github/downloads/fdc02e8b-c165-4898-bc34-dc5ac791da45)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
