### ISSUE TITLE
Code editor 2: When editing a theme, changing a color does not change the colors of the preview

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5314]
### Description
If you change a color in the theme editor, the preview text stays the default colors.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/c782e5c5-0907-4c29-8f13-9db2f4139988

Edit: it looks like the colors will update if you close the preferences window and reopen it

### Steps To Reproduce
Create a new theme in preferences, and change some colors.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[1cef9c3a-e95b-4ac2-b9aa-13c9dd23786b](https://api.gamemaker.io/api/github/downloads/1cef9c3a-e95b-4ac2-b9aa-13c9dd23786b)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.400.0.540  Runtime v2024.400.0.559, thanks.
