### ISSUE TITLE
Code editor 2: Theme editor can't apply multiple changes in a row

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5315]
### Description
After making a change to a color in a theme and hitting apply, making any additional changes will have the apply button stay greyed out. Re-opening the preferences menu will allow you to make another change, but the change won't be reflected in actual code in the IDE. The only way I found to fix it is to swap to a different theme and back again.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a95a583b-7860-496a-9196-5e2c2b5d7a58

### Steps To Reproduce
In the theme editor window in preferences, create a new theme. Change a color, and hit apply. Change another color, and see that apply is still greyed out. Close the window and open it again. Change the color again, and hit apply. It will show as changed in the editor, but not be changed in actual code. Select a different theme and then swap back to the broken theme, and the changes will finally show up.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b7bba616-fc88-4d1a-8ed9-68b11edc4433](https://api.gamemaker.io/api/github/downloads/b7bba616-fc88-4d1a-8ed9-68b11edc4433)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.542  Runtime v2024.400.0.561
