### ISSUE TITLE
Code editor 2: No way to delete themes from the IDE

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5316]
### Description
I created a bunch of themes while testing, and now don't see any way to get rid of them.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/48f642d2-d84c-473d-a117-737a31b04682)

There's no way to rename the themes either

### Steps To Reproduce
Create a theme, see there's no delete button anywhere

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[46c997ad-642b-411b-805a-7b5d7b3522f1](https://api.gamemaker.io/api/github/downloads/46c997ad-642b-411b-805a-7b5d7b3522f1)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.400.0.544  Runtime v2024.400.0.563, thanks.

**Comment by caitlinrmcintyre** [comment]
To delete the themes, there will now be an X beside the theme on the drop down in Preferences > CE2 > Theme.

**Comment by caitlinrmcintyre** [comment]
I've created a new FR for renaming themes #5561.
