### ISSUE TITLE
Code editor 2: Creating a copy of a theme and keeping the default name will swap to an existing copy instead of making a new copy

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5317]
### Description
When copying a theme, the default name of the copy is always the name of the copied theme plus " - Copy" at the end, regardless of if a copy with that name already exists. This means that copying a theme multiple times without changing the name will swap you to the existing copy instead of making another copy. 

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/1857427f-7747-4289-873c-030e49dcbf3a

When duplicating something like an asset, an extra number is added to the end so that the duplicates don't share a name, so perhaps something similar could be done here.

### Steps To Reproduce
Create a copy of a theme, and don't change the default name. Create another copy of the same theme, and see that since it used the same name, it swaps to the existing theme instead of making another copy.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b9fd3b98-6888-437b-97a2-131095fe0bf6](https://api.gamemaker.io/api/github/downloads/b9fd3b98-6888-437b-97a2-131095fe0bf6)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.400.0.541  Runtime v2024.400.0.560, thanks.
