### ISSUE TITLE
Game silently crashes when json_decode is passed a value that's not a string

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#5319]
### Description

When `json_decode` is passed a value that's not a string the game crashes. For example, the following line of code: 

```gml
val = json_decode(5);
```
Will result in a silent crash with the following output: 
```
Runner.exe exited with non-zero status (-1073741819)
```

No error message is shown.

### Expected Change

The function shows an error message on invalid input, the same as json_parse

### Steps To Reproduce

1. In a project, call `json_decode` and pass a value that's not a string.
2. Run the game.
3. The game crashes.
4. Do the same with `json_parse` instead.
5. The game shows a type error: "json_parse : expects a string argument".

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.534  Runtime v2024.400.0.553
