### ISSUE TITLE
Room Editor: Unexpected extra project autosaves whenever pressing "delete" and "copy" shortcuts

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GameMaker-Bugs#5320]
### Description

I'm having a pretty big problem with the room editor, every time I make a change, like copy (ctrl+c) or delete (del) any instance, my project is automatically saved. It makes it work very slow as my project is quite large and also has source control. On the other hand, this also often causes the undo key combination (ctrl+z) to stop working.

I've tried:
- GM LTS (only saves when I delete an instance)
- IDE v2023.8.2.108 (only saves when I delete an instance)
- IDE v2024.2.0.132 (saves when I copy or delete an instance)
- IDE v2024.400.0.532 (saves when I copy or delete an instance)

https://github.com/YoYoGames/GameMaker-Bugs/assets/32647282/37e47f36-64cd-41e4-91b9-ec9e2d8501f4
PS: In the video I never save, I only use the key combinations copy, paste, undo and delete.

Report file: [report.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14873008/report.zip)

### Expected Change

Don't automatically save any changes made in the room editor

### Steps To Reproduce

1. Start GameMaker
2. Open a room
3. Place any instance
4. Select it
5. Copy it (ctrl+c)
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2022.0.2 (LTS), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.539  Runtime v2024.400.0.558.
