### ISSUE TITLE
Code Editor 2: Hotkeys not remappable for Document Navigation

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5323]
### Description

The following hotkeys are missing
 - Collapse all Documents - Alt+Shift+M
 - Expand all Documents - Alt+Shift+U
 - Collapse current Document - Alt+M
 - Expand current Document - Alt+U
 - Toggle Asset Navigation - Alt+1
 - Toggle Document Navigation - Alt+2
 - Toggle Symbol Navigation - Alt+3
 - Show Create Asset - Alt+Shift+1
 - Show Create Document - Alt+Shift+2 and Alt+Shift+N

### Steps To Reproduce

1. Start GameMaker
2. Open Preferences -> Remap Key Bindings
3. Observe the aforementioned hotkeys are not displayed in Text Editor 2
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed, logged for tracking

**Comment by mgeddesGM** [comment]
@zreedy is the list of commands supposed to have "Show Create Document" twice?

**Comment by mgeddesGM** [comment]
both of these work but only the first is shown for "Show Create Document"

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.542  Runtime v2024.400.0.561
