### ISSUE TITLE
Gamepad is not found in 2024.400 betas.

### ISSUE THREAD

**Issue by seqadstudios** [YoYoGames/GameMaker-Bugs#5327]
### Description
Gamepad is not found in 2024.400 betas.

Attached project runs fine on 2024.2.0.132 - runtime: 2024.2.0.163
I have a standard XBOX one controller and it is reported as "XInput STANDARD GAMEPAD" (in 2024.2.0.132)

In v2024.400.0.532 with runtime 2024.400.0.551, the gamepad is not found at all...

### Steps To Reproduce
Run the project. For me no gamepad is found in V2024.400 betas

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22635.0

[be4103fc-f290-4b47-a32e-eee2e96e66a7](https://api.gamemaker.io/api/github/downloads/be4103fc-f290-4b47-a32e-eee2e96e66a7)

**Comment by attic-stuff** [comment]
seconding this emotion; no gamepad functions are working for me using the same gamepad

**Comment by seqadstudios** [comment]
If i remove the gampad USB while the program is running and then plug in the gamepad USB again it pops up in v2024.400

**Comment by cameron-home** [comment]
I have reproduced this on Windows in IDE v2024.400.0.533  Runtime v2024.400.0.552, but not on consoles. Once fix is ready to test, I'll take another look on all targets.

**Comment by shichen85** [comment]
@BscotchSeth

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.400.0.537  Runtime v2024.400.0.556

**Comment by YYDan** [comment]
Verified in https://github.com/YoYoGames/GameMaker-Bugs/issues/8350
