### ISSUE TITLE
[Android] Connected controllers/devices do not update until the app is re-focused

### ISSUE THREAD

**Issue by itsCruiseElroy** [YoYoGames/GameMaker-Bugs#5329]
### Description

When connecting, turning on, or turning off a controller or other Bluetooth device to an Android device, GameMaker is only able to accurately update the list whenever the game loses and regains focus (such as when going to the home screen and re-opening the game from the background apps); the list does not update in real time. This makes controller disconnections impossible to detect, for instance.

This affects both VM and YYC compiling. The sample project was tested on Google Pixel 5A and Samsung Galaxy S22, but the general issue seems to affect most, if not all, Android devices.

Sample project with contact us package: [Controller Test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14877092/Controller.Test.zip)

### Expected Change

Android games are able to detect when a controller connects or disconnects to the device in real time.

### Steps To Reproduce

1. Connect a controller to the Android device
2. Start GameMaker and open the attached project
3. Compile and run for Android, with the controller still turned on
4. Take note of the name of the connected device
5. Turn the controller off without putting the game in the background (this can usually be done by holding the home button for a few seconds)
6. Notice that the list of connected devices has not updated
7. Put the game in the background, then open it back up from the background
8. After the game loses focus, the device list now updates properly
9. Turn the controller back on, notice that it doesn't update the list
10. Repeat steps 7 and 8

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYBartT** [comment]
Documented the function `gamepad_enumerate()` in the manual.
