### ISSUE TITLE
[YYC] [Always] Silent crash when trying to access a class variable

### ISSUE THREAD

**Issue by SilentPhil** [YoYoGames/GameMaker-Bugs#5336]
### Description

[Download Package](https://drive.google.com/file/d/1V40CpCQZPFBBqdwY5qc34dkNRoq_4WqS/view?usp=drive_link)
[Exception Analysis (Windbg)](https://pastebin.com/raw/yN9M16Tj)

A silent crash occurs when trying to access a field in a class, the access to which is obtained through a method of another class. The error only occurs if there were two accesses to the same method in "one line" (for example, if both accesses are arguments of a single max function).
Moreover, the crash does not occur if access to the class with the structure is obtained through the get_1 method, but it occurs if access is obtained through the get_2.

```
function TestClass() constructor {
	__test_class = new TestClassWithStruct();
	
	static get_1 = function() {
		return __test_class;
	}
	
	static get_2 = function() {
		return __test_class;
	}
}
```

```
function TestClassWithStruct() constructor {
	//__struct = {};
	//__arr = [];
	__var = "Foo";
	
	// You can try to read any type of variable - structs, arrays, strings etc. 
	// Just try to change __var to __struct in try_to_read variable below.

	static func = function() {
		var try_to_read = __var; // <- SILENT CRASH HERE
		show_debug_message("func: " + string(try_to_read));
		
		return 0;
	}
}
```

```
#event create

test_class_in_self = new TestClass();
```

```
#event step
// get_1 and get_2 returns same variable. 
// get_1 in not crashed, but get_2 is crashed

if (keyboard_check_pressed(ord("Q"))) { // NOT crashed
	some_function(test_class_in_self.get_1().func(), test_class_in_self.get_1().func());
}

if (keyboard_check_pressed(ord("W"))) { // crashed
	some_function(test_class_in_self.get_2().func(), test_class_in_self.get_2().func());
}

if (keyboard_check_pressed(ord("E"))) { // NOT crashed
	var func_1 = test_class_in_self.get_2().func();
	var func_2 = test_class_in_self.get_2().func();
	some_function(func_1, func_2);
}


// Instead some_function can be any function with two or more arguments - clamp, max, etc
if (keyboard_check_pressed(ord("R"))) { // crashed
	max(test_class_in_self.get_2().func(), test_class_in_self.get_2().func());
}

if (keyboard_check_pressed(ord("T"))) { // NOT crashed
	some_function(test_class_in_self.__test_class.func(), test_class_in_self.__test_class.func());
}
```

### Expected Change

The runner should not crash.

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Start the game
4. Press W to crash

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Unable to reproduce on the current 2024.400 HEAD - please check on the latest Beta 4 when it is released

**Comment by SilentPhil** [comment]
Still crashes on v2024.400.0.562
