### ISSUE TITLE
Code editor 2: Adding tabs in front of an automatically added tab creates broken tabs

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5337]
### Description
When using tabs as the tab type, adding a tab after an automatically added tab works fine. However, adding your own tabs before the automatically added tab creates broken tabs with incorrect spacing.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/088da11d-1ab9-4387-aeda-7bc84d31f0ea

### Steps To Reproduce
```
if true {
//typing tabs here breaks 
}
if true {
        //typing tabs here is fine
}

```
 See video above for clearer steps

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e4834609-8be2-4250-9ad5-45ce663788ad](https://api.gamemaker.io/api/github/downloads/e4834609-8be2-4250-9ad5-45ce663788ad)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.565  Runtime v2024.600.0.585
