### ISSUE TITLE
Code editor 2: Variables that haven't been set to anything appear in local variable color

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5338]
### Description
If you try to use a variable that hasn't been set to anything (or one that GM thinks hasn't been, even if it has), it appears in local variable color. This can be confusing since it makes it seem like the unset variable is a local even though it isn't.

### Steps To Reproduce
```
if unsetVar == 0 { //will be yellow
	
}
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e32846d3-e3e0-446f-80ea-5d461e016703](https://api.gamemaker.io/api/github/downloads/e32846d3-e3e0-446f-80ea-5d461e016703)

**Comment by mgeddesGM** [comment]
the variable is still yellow in  IDE v2024.600.0.558  Runtime v2024.600.0.573

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
