### ISSUE TITLE
Live Wallpapers Templates that use mouse position don't work since new subscription system

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5341]
### Description

(I'm sorry, this is not really an in-game "bug" - it's just a mistake in the code of the template projects - I didn't know where to file it)

The Live Wallpaper templates that use the mouse position (e.g. "Fairy Flocking Live Wallpaper Template") don't work anymore since the switch to the new subscription system for mouse input, since they don't contain the necessary code.

[contactus.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14884080/contactus.zip)

### Expected Change

Update the Live Wallpaper Templates so that mouse input works correctly again.

### Steps To Reproduce

1. Load one of the Live Wallpaper templates with mouse input like "Fairy Flocking Live Wallpaper Template"
2. Start it in the OperaGX Windows Companion app
3. Try to use mouse input. It will not work.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by patrickrocheyoyo** [comment]
All template wallpapers should be fixed now. Thank you for reporting this issue :)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.400.0.534  Runtime v2024.400.0.553, thanks.

**Comment by Emc1923** [comment]
Verified done as of  IDE v2024.400.0.534  Runtime v2024.400.0.553.
