### ISSUE TITLE
New Live Wallpaper Subscription Tutorials - mouse input setting in example projects has no effect

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5342]
### Description

The new Knowledge Base article on Live Wallpapers with subscriptions contains two example projects to showcase the features. In both these projects the setting "Allow Mouse Data" doesn't have any effect. Even if you switch it off the mouse position is still being tracked.

I think the reason is that the subscription to the "desktop_mouse" happens in the Create Event of obj_camera and this event is never triggered again when the configuration is changed.

### Manual Link

https://help.gamemaker.io/hc/en-us/articles/15176025039901-How-To-Use-System-Metrics-In-Live-Wallpapers

**Comment by gurpreetsinghmatharoo** [comment]
The projects are correct, it is a runner issue that desktop_mouse cannot be disabled once it's enabled. I have opened an issue for that: see #5400.

I'll close this one.

Thank you

**Comment by Emc1923** [comment]
Verified, I got this issue too when testing metrics - leaving the new bug to be looked at.
