### ISSUE TITLE
Live Wallpaper: Windows fullscreen setting has negative effect on Companion App

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5343]
### Description

When you create a Live Wallpaper and want to use it in the OperaGX Windows Companion App then the following setting in the Windows Game Options has an adverse on the app:

Game Options -> Windows -> Graphics -> Start fullscreen

When you set this and then start the wallpaper in the Companion App then the wallpaper is overlayed over the complete desktop (not behind it but in front of it). All icons / menu bars are hidden behind the wallpaper. Any click on the wallpaper then makes it disappear and a blank black background is shown (until you disable the wallpaper from the Companion App menu).

### Expected Change

Don't let the fullscreen setting affect how the wallpaper is displayed

### Steps To Reproduce

1. Open "Blank Live Wallpaper Template"
2. Go to Game Options - Windows - Graphics - Start fullscreen
3. Compile the game for the Windows target
4. Close the game
5. Use the OperaGX Companion App to load the wallpaper --> it will be shown in front of the complete desktop

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.400.0.537  Runtime v2024.400.0.556
