### ISSUE TITLE
Live Wallpaper: configuration cannot be changed in Opera.GX

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5344]
### Description

I assume that this is more a bug on the side of the Opera team. However, with the new Live Wallpaper jam coming up I think it is important that this is sorted out:

Currently you cannot change the configuration of any Live Wallpaper within the Opera browser.

Usually you right click on the Live Wallpaper and select "Configure live wallpaper". This still brings up the configuration menu with all the settings. However, you cannot click on any settings. It's as if mouse clicks aren't registered on the interface.

### Expected Change

Make the Live Wallpaper configuration interface in Opera.GX functional again.

### Steps To Reproduce

1. Load any Live Wallpaper as a mod in Opera.GX
2. Create a new tab to load the wallpaper
3. Right click on the wallpaper and select "Configure live wallpaper"
4. Try clicking on any of the settings. They will not respond.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Please ensure that you are on a GX version that is at least 107 below is a snapshot of my version number on local GX installation

<img width="789" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/ef2e955e-ca6f-40cf-8387-41f8fcaabe8a">

You should probably be on the early bird channel see https://www.trishtech.com/2022/08/how-to-enable-early-bird-in-opera-gx-browser/

**Comment by TheGitMagician** [comment]
Thank you for having a look at it.

Very strange - today it works....    I had tested it on two different machines - same version as you have, Earlybird enabled ... tried it on multiple occasions and it didn't work. Today it just works. .... Ghost in the Machine.

This can be closed.

**Comment by rwkay** [comment]
closed as above
