### ISSUE TITLE
Code Editor 2: Debugger still uses CE1 when CE2 is enabled

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5348]
### Description
When the new code editor is enabled, pausing in the debugger or using a breakpoint will still display the code using the old code editor. This means that if you make changes to the code while the debugger tab is open, the debugger won't have the updated code when you run the game.

### Steps To Reproduce
Run in debug mode, and hit pause in the debugger.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c341a89b-c6a7-4ce7-92e0-fe8aa6bd0f72](https://api.gamemaker.io/api/github/downloads/c341a89b-c6a7-4ce7-92e0-fe8aa6bd0f72)

**Comment by YYDan** [comment]
Is quietly already in 2024.1100 Beta 1, but the issue was never tagged or updated properly. Have done so now.

**Comment by KormexGit** [comment]
It did get marked as done in #5578, I believe that ended up becoming the main ticket rather than this one

**Comment by cameron-home** [comment]
Already verified in #5578.
