### ISSUE TITLE
Code editor 2: When "Show all documents in single view" is disabled, clicking in empty space below code will change the event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5349]
### Description
If you disable "Show all documents in single view" in preferences, then clicking in the blank space below code will take you to whichever event is last in the event list.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9d85ca13-232e-42f8-9457-a386bc17c722

### Steps To Reproduce
Disable "Show all documents in single view", add several events to an object, and then click in the empty space below your code.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[84b25c1e-24b4-4fe4-8ec9-fc036f80423c](https://api.gamemaker.io/api/github/downloads/84b25c1e-24b4-4fe4-8ec9-fc036f80423c)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
