### ISSUE TITLE
Code editor 2: Alt select doesn't work if selecting past the end of the code line

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5350]
### Description
Alt select works when selecting fully vertically, but instead only types on one line if you select too far to the right.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/ac9a6c4f-1a9d-4a89-8ecd-fdfa7c3bce16

### Steps To Reproduce
Alt + drag to select multiple lines, selecting past the end of the code, and type something.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[98d3360e-8565-49d8-b910-e560120c4c00](https://api.gamemaker.io/api/github/downloads/98d3360e-8565-49d8-b910-e560120c4c00)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
