### ISSUE TITLE
buffer_delete_async

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#5351]
### Is your feature request related to a problem?

The function is missing and could be useful.

### Describe the solution you'd like

If you use the async save/load you can use buffer_load_async and buffer_save_async where you load a file or save a file but there is no way to delete the file because the buffer_delete is used to delete a buffer in memory not a file.

**Comment by attic-stuff** [comment]
you would use file_delete for this, there is no need for an async function here.

**Comment by stuckie** [comment]
Closing as above.
