### ISSUE TITLE
Code Editor 2: "auto-indent clipboard content" Preference makes braces indent incorrectly when pasting code

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5356]
### Description

When you activate the option "Auto-indent clipboard content" and copy a part of your code then curly braces get indented too much. In the video below they should be on the same level as the if-statement but they are one level further in.

![autoindent](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/b60cb436-bfaa-4f25-b781-046807a58afb)

### Expected Change

Make "auto-indent clipboard content" get the correct indentation

### Steps To Reproduce

See above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Reopening as I'm still seeing the issue with the first curly brace being indented incorrectly 

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/72e232f7-ca64-49b1-a184-17239751b4e5)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified in  IDE v2024.800.0.601  Runtime v2024.800.0.624, thanks.
