### ISSUE TITLE
Code Editor 2: No equivalent of CE1's "Auto-Indent After Brace" Preference, so auto-indenting of braces assumes a specific style for everyone

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5358]
### Description

It feels to me like CE2's indentation system is optimized for this style of writing the curly braces:

if (test == 0) {
  //do something
}

However, another style that you often find is this:

if (test == 0)
{
  //do something
}

I have tried all options for auto-indentation but I wasn't able to make the code indent correctly after the opening curly brace. It always stays at the level of the brace:

![indent](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/1c78f8c3-0efc-401a-92d9-b41578c924ea)

In the old code editor this was possible using the setting "auto indent after brace":

![indent_old](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/9ac05116-9347-48b4-9527-8457ad279e97)

### Expected Change

Enable auto-indentation for this style of coding

### Steps To Reproduce

See above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
The functionality for different indentation styles has moved into "Auto Indent Mode", the "Braces" mode is the CE1 behavior you describe. However, the video does show a bug that auto-indent is not applied after `{` is typed. This should happen regardless of brace style used (K&R, or Allman). This has been fixed now.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.600.0.579  Runtime v2024.600.0.605, thanks.
