### ISSUE TITLE
Code editor 2: Mass commenting code with ctrl + k messes up coloring

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5359]
### Description
Using ctrl+k to comment multiple lines of code makes the coloring go weird instead of all being comment color. Uncommenting again with ctrl + shift + k makes it continue to be messed up, just in a slightly different way. It will continue to be messed up until some sort of edit is made to the line or the project is reloaded.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/1782c1e9-8983-44cf-87f6-f622a0a22943

### Steps To Reproduce
Select multiple lines of code, including some indented if statements, and hit ctrl + k to comment all of them at once.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[973af841-66ec-4d7a-8866-e97e7f70ffd2](https://api.gamemaker.io/api/github/downloads/973af841-66ec-4d7a-8866-e97e7f70ffd2)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.558  Runtime v2024.400.0.571, thanks.
