### ISSUE TITLE
Code editor 2: Deleting part of a line that contains an operator causes the line to briefly show the wrong thing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5361]
### Description
When deleting just part of a line and the part contains an operator, the line will stutter and show the wrong thing for just a moment. It's a short stutter in this empty sample project, but the duration is longer in my large project with lots in it.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/09a0f3d9-fc17-4a2b-95a2-bb92265c0139

### Steps To Reproduce
```
variable = variable2 + variable3;
```
Select and delete just ` + variable3`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[24dd61b6-b743-4f73-9a87-1e0f74259e81](https://api.gamemaker.io/api/github/downloads/24dd61b6-b743-4f73-9a87-1e0f74259e81)

**Comment by zreedy** [comment]
Fixed as part of a fix for https://github.com/YoYoGames/GameMaker-Bugs/issues/5360

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
