### ISSUE TITLE
Code editor 2: Selecting some code, dragging it to a new location, and then undoing it does not return it to what it was before

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5362]
### Description
You can select code and drag it to a new location in the new code editor. However, if you do this on accident and undo it (I keep doing it on accident) the undone version is different from what it was before, with the tabs and whitespacing all messed up. It's not even the same code functionally, as you can see one of the brackets is in a different spot after in this video.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/3199077a-ee46-47f8-aa5f-c102466d6883

### Steps To Reproduce
Select some tabbed/nested code and move it elsewhere. Then, ctrl+z to undo it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c06b3649-6a6c-400d-90cf-6d2dde4ff527](https://api.gamemaker.io/api/github/downloads/c06b3649-6a6c-400d-90cf-6d2dde4ff527)

**Comment by zreedy** [comment]
Fixed, many issues with the logic for this operation.
In addition the following has also been fixed:
 - New lines mangled when undoing multi-line insert operations

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.558  Runtime v2024.400.0.571, thanks.
