### ISSUE TITLE
Code editor 2: Make selecting and dragging code to move it an optional feature that can be disabled

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5363]
### Is your feature request related to a problem?

I keep trying to change my selection and accidentally dragging the code elsewhere instead.

### Describe the solution you'd like

Make the select code --> drag it to move it feature optional, and possible to disable in preferences.

**Comment by zreedy** [comment]
Fixed. When the new preference `Preferences -> Code Editor 2 -> Editing -> Allow selected text to be dragged and dropped` is checked off this feature will not be active.

**Comment by mgeddesGM** [comment]
verified in Beta IDE v2024.800.0.618 Beta Runtime v2024.800.0.642
