### ISSUE TITLE
Code editor 2: Brackets at the end of a comment are still used for determining whitespacing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5364]
### Description
Brackets from comments are taken into account when determining the automatic tab spacing.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/2d2ab729-43e8-4c98-8e9f-af6de82e95d4

### Steps To Reproduce
```
func1 = function() {
	if condition1 == noone {//a comment with a bracket {
	}
}
	
func2 = function() { 
	if condition 2 == noone {
	}
	} //try to move this bracket to the proper space, it will keep getting automatically put to 1 tab of indent to match the comment
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[390a0028-a814-4108-8b91-4cb62dd2e4df](https://api.gamemaker.io/api/github/downloads/390a0028-a814-4108-8b91-4cb62dd2e4df)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.584  Runtime v2024.600.0.608, thanks.
