### ISSUE TITLE
functions related to microphones are doesn't work

### ISSUE THREAD

**Issue by ABER1047** [YoYoGames/GameMaker-Bugs#5368]
### Description

![3465456y6](https://github.com/YoYoGames/GameMaker-Bugs/assets/78880883/59976d3a-fa17-4555-bb06-7503130f3e01)

### I tried to do like [this guideline](https://github.com/YoYoGames/GameMaker-Bugs/issues/5124) guide but it actually doesn't work as you can see this screenshot.

I have tried with my two of microphones which changed name to english and japanese
(Logitech G430 microphone, マイクロフォン)

Of course, I've tried same steps after restarting pc but it didn't work too.

</br>

### Steps To Reproduce

1. connect two microphones which have named to english and japanese
2. run "gamemaker" with turning on "administrator" and "Run this program in compatible mode for windows 7"
3. run the [_input file](https://github.com/YoYoGames/GameMaker-Bugs/files/14839289/_input.zip) which is included in [that guideline](https://github.com/YoYoGames/GameMaker-Bugs/issues/5124)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
While https://github.com/YoYoGames/GameMaker-Bugs/issues/5124 has been fixed, it is still pending internal testing and has not yet been released. The fix will first appear in an upcoming 2024.400 beta release, and then later in the 2024.4 monthly release.
