### ISSUE TITLE
Code editor 2: Tooltip sometimes gets stuck on screen 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5371]
### Description
This seems to only happen in my large project, and only sometimes. I believe it has to do with the delay on things like colors and feather messages loading in fully that happens in large projects, since the tooltip appears right as everything finishes loading in, and the bug doesn't happen in any smaller sample projects I've made.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/348d9589-4fc5-44d5-830a-cb45e35abd2c)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8cf213a1-1e2c-4491-90df-aefed1345126)

The tooltip will even stay through loading up a completely different project.

### Steps To Reproduce
Unfortunately I don't really have consistent steps since it doesn't happen in any smaller sample projects, but here's the approximate steps that I usually do when it happens:
1. Have a large project with enough things in it to make feather and the syntax coloring take several seconds to load in after the project opens.
2. Have at least 2 object tabs already open prior to opening the project, all featuring objects with at least a few hundred lines of code.
3. Before the syntax coloring loads in, change your tab to a different object than the one the project had open by default at the start.
4. Sometimes, a tooltip from that default object will appear once the highlighting loads, even though you're now on a tab for a different object. This tooltip won't go away until you navigate back to the source line and mouseover it again, or restart GM. Making another tooltip in the tab you've swapped to doesn't overwrite it, both can be visible at the same time.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e856507b-1d62-4361-a552-aa20504fb2ec](https://api.gamemaker.io/api/github/downloads/e856507b-1d62-4361-a552-aa20504fb2ec)

**Comment by KormexGit** [comment]
The video I attached to #5630 also shows the tooltip bug

**Comment by alicemoretti** [comment]
@KormexGit 

I was unable to reproduce this issue in my own projects but there have been a number of fixes to the Code Editor 2 and the tooltips in particular in the latest Betas. 

Could you please check if you are still reproducing the issue on your project in the latest Beta (IDE v2024.600.0.583  Runtime v2024.600.0.607) and let us know? Thank you

**Comment by KormexGit** [comment]
@alicemoretti 
It's not happening in a bit of testing I just did, I also don't recall it happening in recent times I've used CE2

**Comment by alicemoretti** [comment]
Awesome! Thank you very much for confirming it. 

I'll close and verify this bug just now, but if it does happen again please do re-open it and comment so we can investigate the issue again.
