### ISSUE TITLE
UI/UX: Pressing 'Tab' on any gadget will cause the press to be registered multiple times

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#5388]
### Description

Anywhere in the IDE,  pressing 'tab' will cause multiple inputs to register, meaning that several buttons will be tabbed over.

https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/d404a12d-391d-4033-8a33-21e58fe1a1c9

Tested using IDE v2024.400.0.533  Runtime v2024.400.0.552

[Contact Us Package](https://drive.google.com/file/d/1OoMmRpcKv162in4AyqR5CvHHCowONh4c/view?usp=sharing)

### Steps To Reproduce

1. Start GameMaker
2. Open the Sign In menu via the accounts button
3. Open the Legacy Sign In via 'Sign in here'
4. Select one of the text boxes in the dialog
5. Press 'tab'
6. Observe multiple inputs are registered

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Updated issue - this problem exists everywhere in the IDE.
![tab](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/49ae918e-0645-41db-aada-006bd92b948e)

**Comment by SmithTom6304** [comment]
This should now be fixed.

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.400.0.544  Runtime v2024.400.0.563
