### ISSUE TITLE
Code editor 2: When event selection bar is set to be on the side, it is possible to get it to disappear entirely

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5390]
### Description
Normally when using a split code view, getting rid of the view that the event/declarations panel is in will make it pop back up in another one of the views. However, I discovered that if the panel is set to be on a side,  you can get it to disappear by creating one horizontal split view, then a vertical split view, then dragging the vertical split all the way up.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/61388b85-82d8-4abc-bf02-71048a980d08

### Steps To Reproduce
Set the event/declaration panel to be on the side. Create a horizontal split. Create a vertical split. Drag the vertical split all the way up.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3374f527-3264-4a2e-a931-23334793b130](https://api.gamemaker.io/api/github/downloads/3374f527-3264-4a2e-a931-23334793b130)

**Comment by skud92** [comment]
This is a layout bug. The Nav panel should not be affected by the split view, if it is docked to the side it should always remain 100vh of the editor.  

This is the same if a user has the nav bar set to the top and splits vertically - the nav bar should always remain 100% width of the editor.

Split view should only split the code section, nav bar should remain full height or width depending on the users set up.

**Comment by KormexGit** [comment]
Looks to be fixed in 2024.11, navigation panel is no longer affected by splits and doesn't disappear when closing splits

https://github.com/user-attachments/assets/768bb412-7019-446c-8a48-981c9a2deacc
