### ISSUE TITLE
Code editor 2: Dragging to create a split view and then dragging it closed again makes the split handle unresponsive

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5391]
### Description
Dragging to create a split view, and then dragging it back again makes it so you can't do any more splits, due to the drag handle becoming unresponsive. Closing the object and opening it again fixes it.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/91ef9ce4-1cfd-4996-8823-735a70cc2300

### Steps To Reproduce
Drag to create a split view, then drag it back again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[27ef1b1d-c468-40b0-95fe-369acbb6cc22](https://api.gamemaker.io/api/github/downloads/27ef1b1d-c468-40b0-95fe-369acbb6cc22)

**Comment by KormexGit** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/2c66c80b-4be3-4bc9-b74c-7f1bf7067b83
 
 Looks like it also goes unresponsive after changing the position of the event panel thingy

**Comment by yyalansavage** [comment]
Fixed; also fixes similar issue where drag handle becomes unresponsive after changing orientation
