### ISSUE TITLE
Code editor 2: If "Show all documents in single view" is disabled, the code minimap  shows all events at once, overlapping eachother

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5393]
### Description
When "show all documents in single view" is disabled, the minimap shows every event instead of just the currently selected one. Every event will be overlapping, making it unreadable.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/2748654a-ff23-4f67-878c-cf2ec5a1e271)

### Steps To Reproduce
Disable "show all documents in single view" in preferences, then hover the mouse over the code minimap.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[46c4f16d-76c0-4c69-870b-25908f778b73](https://api.gamemaker.io/api/github/downloads/46c4f16d-76c0-4c69-870b-25908f778b73)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.559  Runtime v2024.600.0.574, thanks.
