### ISSUE TITLE
Code editor 2: ctrl + middle click on event_inherited does not jump to parent event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5396]
### Description
In the old code editor, you could hold ctrl while middle clicking event_inherted() to jump to the parent event instead of opening the manual page for event_inherited. This does not work in the new code editor.

### Steps To Reproduce
Add event_inherted to a child object, and then ctrl + middle click it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e1623402-717a-4501-84f9-78a331448284](https://api.gamemaker.io/api/github/downloads/e1623402-717a-4501-84f9-78a331448284)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
