### ISSUE TITLE
Object Inspector: Event shortcuts don't work correctly

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5397]
### Description
When right clicking an event in the inspector, the menu says that the delete key is a shortcut for deleting an event, but pressing delete doesn't actually do anything. I initially thought this was a code editor 2 bug, but it doesn't work with code editor 2 disabled either.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/66c341a3-6c3a-492b-b37f-52ae77558344)

### Steps To Reproduce
Select an event in the inspector and hit the delete key.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0aac8e6d-cf2b-4268-a417-b9639aca529a](https://api.gamemaker.io/api/github/downloads/0aac8e6d-cf2b-4268-a417-b9639aca529a)

**Comment by SmithTom6304** [comment]
Note that this applies to every shortcut bar the Add Event shortcut.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.800.0.599  Runtime v2024.800.0.622
