### ISSUE TITLE
Code editor 2: No way to delete events from within the editor when "show all documents in single view" is disabled

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5398]
### Description
When "show all documents in single view" is enabled, you can delete events by right clicking on the event header. This header does not exist when the setting is disabled, and the event selecting menu has no right click menu. The only other way I found was to do it through the inspector, but it feels like there should be a way to do it from within the editor itself, ideally from the event selection menu since that's the most intuitive place for it to be. Having an option there would be more intuitive for when all documents in single view is enabled as well.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/ee8ed990-ee54-4a94-a7d5-fab5b997d7ad

### Steps To Reproduce
Enable "show all documents in single view"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5650c4d3-9ca5-4d82-95ff-5842baacf6e7](https://api.gamemaker.io/api/github/downloads/5650c4d3-9ca5-4d82-95ff-5842baacf6e7)

**Comment by KormexGit** [comment]
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f2933c21-94fd-418e-abef-ee1f3c34f509)
Turns out you can delete events from the event list, but the X only appears if you hover over it. There was talk in discord about making it appear when hovering anywhere on that event row, but personally I'd prefer if it was always visible. I originally reported this bug because me and 2 others all looked for a way to delete events and couldn't find this way since it's so hidden.

**Comment by tabularelf** [comment]
I'm going to note for whoever reads this.
Given that there's no other buttons here whatsoever, it makes no sense to have it hidden unless hovered. Even if the whole event just needs to be hovered down the line.

Unless there's a certain specific issue that you can narrow down, like adding more buttons or a genuine cause of event names somehow taking over the whole menu (and with sufficient evidence), feel free to tell me that. But from where it stands, it's a stupid design decision.

**Comment by stuckie** [comment]
The x should appear when hovering over the event.

**Comment by yyalansavage** [comment]
X appears when hovering over the event as requested above

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.555  Runtime v2024.400.0.569
