### ISSUE TITLE
In-Game: audio_exists will crash the runtime if called on a destroyed streamed asset

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#5402]
### Description

A bad assertion is hit if `audio_exists` is called on a destroyed streamed asset. 

### Steps To Reproduce

1. Open and run the attached example project: [gmb-5402.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14920043/gmb-5402.zip)
2. Observe that the game crashes.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.400.0.532 Beta Runtime v2024.400.0.551

### Which platform(s) are you seeing the problem on?

Windows

### Sample Project Added?

- [X] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Still experiencing the crash in IDE v2024.400.0.539  Runtime v2024.400.0.558

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.540  Runtime v2024.400.0.559, thanks.
