### ISSUE TITLE
One spine sprite in our project won't fire its events.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#5404]
### Description

I've created a ticket in the Crashlands 2 repository for Fritz and am creating this ticket here as per Russell's request, so you guys can link it into your system.

My initial comment to Russell:

We've got a REAL WEIRD spine problem that I can't replicate in a test project. Was wondering if you had some insights or things we could to do replicate.

We have *one* Spine sprite in Crashlands 2 whose spine events won't fire -- as in, the `Animation Event` object event shows nothing happening. This issue appeared when we updated to the latest beta runtime. As far as we can tell, all other spine sprites work just fine and their events fire as intended. We aren't playing this spine animation any differently than any others in the project. Here are the things we tried to get the event to fire:

* We printed out the animation event frames to make sure Game Maker knows they exist. It does.
* We added more events to the animation to see if they would fire. None of them did.
* We exported the spine animation under a different name so we could import it as a fully new sprite. This had no effect.
* We changed the animation duration and timings to see if there was some kind of weird rounding error. This had no effect.
* We cut out all of our own code and just played the spine animation using `skeleton_animation_set()` and `image_speed`. This had no effect.
* We tried playing the spine animation from a different object, in different rooms, etc... The event still did not fire.

I made a test project (attached) and imported that spine sprite into the test project. In the test project, the event fires. So... we can't replicate this in a small way that we can send to you guys, because the small test project somehow doesn't have this issue.

Here's the test project that shows the event firing:
[SpineEventMissing.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14921053/SpineEventMissing.zip)

### Expected Change

Spine events should always fire as intended.

### Steps To Reproduce

Replication steps listed in the Crashlands 2 repository for Fritz.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
I believe this fix should be the same as for https://github.com/YoYoGames/GameMaker-Bugs/issues/5410

**Comment by BscotchSeth** [comment]
Yep, it's the same issue. Looks resolved in CL2. Thanks!
