### ISSUE TITLE
Code Editor 2: Rebind navigate to Events/Declarations

### ISSUE THREAD

**Issue by christianMeurrens** [YoYoGames/GameMaker-Bugs#5411]
### Description
I use a bépo keyboard layout (french dvorak) and symbols < > are typed by the combination of right ALT/Option + Numbers 2-3
https://kbdlayout.info/kbdfrnb/overview%2Bvirtualkeys

In the new code editor they are configured as shortcuts to navigate to events and declarations, making the typing of <> impossible in the editor.

Please add the possibility to rebind those shortcuts in Preferences-Redefine keys.

### Steps To Reproduce
Open the new code editor and use ALT/Option + number2/3
It will navigate to Events/Declaration with no key rebind possible.

Optionaly Install the keyboard layout from 
https://bepo.fr/wiki/Installation (sorry french only)
but it should not be necessary

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Mac 14.4.1

[585ec322-a4cf-4167-b8ea-b6a41a018413](https://api.gamemaker.io/api/github/downloads/585ec322-a4cf-4167-b8ea-b6a41a018413)

**Comment by zreedy** [comment]
This is now in the current Beta. Sorry, this ticket was missed at the time!

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.800.0.590  Runtime v2024.800.0.614
