### ISSUE TITLE
Open manual in a workspace tab, rather than in a separate browser

### ISSUE THREAD

**Issue by JamesC01** [YoYoGames/GameMaker-Bugs#5414]
### Is your feature request related to a problem?

Kind of. It's a bit annoying to have to use a separate browser for the manual.

### Describe the solution you'd like

Having a built-in manual that opens in a tab at the top, where the workspace tabs are would be very nice in my opinion. Godot has a built-in manual, and it's very nice and quick to work with. I think this would be useful for gamemaker to have, too.

**Comment by stuckie** [comment]
This is not something we are planning.
