### ISSUE TITLE
Code Editor 2: Preferences values are not checked on change of user or before displaying CE2 windows which are in the project layout on load

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5419]
### Description

Preferences for CE2 won't be kept between accounts. If changing from an account with CE2 enabled to one with CE2 disabled - like guest for example where CE2 is disabled by default - all the CE2 windows will remain in place and CE2 will still be enabled until reapplying the preference (restarting the IDE won't fix it).

![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/a39b93c3-72fd-4027-8e3f-67f197c39177)

### Steps To Reproduce

1. Start GameMaker logged with an account with CE2 enabled
2.  Open a project (preferably with CE2 windows opened)
3.  Log out
4. See the issue
5. Close the IDE
6. Reopen the project
7. Observe that the issue persists
[ui.log](https://github.com/YoYoGames/YoYoStudio/files/14917676/ui.log)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.534  Runtime v2024.400.0.553

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by stuckie** [comment]
Not rechecking the preferences on a user change.
Nor is it checking that CE2 is enabled when loading a project layout with CE2 windows.

**Comment by zreedy** [comment]
CE2 Enable/Disable requires a restart now, so this should not be an issue. Closing.
