### ISSUE TITLE
Code Editor 2: Diagnostics tab displays slits sections both names 'Diagnostics'

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5420]
### Description

On the very first load of Beta IDE v2024.400.0.534  Runtime v2024.400.0.553 with CE2 enabled, the Diagnostic tab was displaying a split section both named Diagnostics. Disabling CE2 and re-enabling it resolved the issue but clearly there is a bug there.

![image](https://github.com/YoYoGames/YoYoStudio/assets/101252654/09c540bb-6ee1-42e4-b539-bb3543d46236)

### Expected Change

On one section under the Diagnostics tab should be displayed

### Steps To Reproduce

1. Start GameMaker
2. Ensure CE2 is enabled
3. Open any project
4. Click on the Diagnostics tab
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.534  Runtime v2024.400.0.553

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by stuckie** [comment]
Cannot reproduce any longer.. if this still occurs, can the project layout xml be attached, please.
