### ISSUE TITLE
Code Editor 2: F7 and F8 to zoom in/out do nothing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5425]
### Description
In the old code editor, you can "zoom" the code by pressing the F7 and F8 keys. In the new code editor, F7 and F8 do nothing.

### Steps To Reproduce
Press F7 or F8 while using the new code editor

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[38df0937-e95c-4f8a-8d35-edbcb5a0a188](https://api.gamemaker.io/api/github/downloads/38df0937-e95c-4f8a-8d35-edbcb5a0a188)

**Comment by zreedy** [comment]
The hotkeys for CE1 are not used in CE2. Instead this functionality is superseded by https://github.com/YoYoGames/GameMaker-Bugs/issues/5225

**Comment by mgeddesGM** [comment]
verified as superseded based on previous comment
