### ISSUE TITLE
[IDE] The IDE does not respect MacOS text movement keybinds

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5427]
### Description
On Windows and Linux, **Control** allows moving by one word at a time with the arrow keys, deleting one word at a time in combination with backspace or delete, and selecting one word at a time with Shift. The **Home** and **End** keys allow you to seek to the start or end of a line.

On MacOS, **Alt/Option** takes the place of Control to seek between words. For Home and End, **Command+Left/Right arrows**.

The GameMaker IDE does not respect this behaviour correctly on MacOS - Alt correctly allows seeking one word at a time, but doesn't work in combination with Shift or Backspace to select or delete per-word.

The IDE also does not allow seeking whole lines with Command at all.

These little text navigation shortcuts are features I use constantly when editing any text as they give an incredible speed boost to editing of any kind - not to mention writing code - and in the current state, the GM IDE is not enjoyable to use on MacOS due to the current behaviour.

### Steps To Reproduce
In a native MacOS application, edit text using the Alt and Command shortcuts for navigation, selection, and deletion. Now, enter the GameMaker IDE and attempt the same navigation - you'll quickly notice a lot of them are only half-functional or don't work consistently with how you'd expect.

This is true of the IDE's text boxes, and of the current code editor. I'll make a second issue for CE2, as it has a *different* set of incorrect behaviour.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Mac 13.5

[b26e968e-c487-445a-8af9-5f5cef3eaf77](https://api.gamemaker.io/api/github/downloads/b26e968e-c487-445a-8af9-5f5cef3eaf77)

**Comment by SmithTom6304** [comment]
Wonder if this was broken with the hotkeys issues a while back. It seems to now be working as expected (excluding CE2, which like mentioned above is a separate issue).

**Comment by Emc1923** [comment]
Verified working across the IDE and CE1 as of  IDE v2024.600.0.563  Runtime v2024.600.0.582.
