### ISSUE TITLE
Code Editor 2: [Mac IDE] OS-standard text navigation hotkeys for selecting words/lines are not respected and also not offered as Redefine Keys entries

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5428]
### Description
This issue is directly related to #5427, but CE2 has a different set of behaviour from the rest of the IDE in this regard, so I'm reporting it separately.

To briefly echo what I explained there, on MacOS the expectation for navigation keybinds are that **Alt/Option** serves the purpose that Control does on Windows - **Alt+Left/Right Arrows** jumps back or forward a word, Alt+Backspace deletes the last word, Alt+Delete deletes the next word, etc.

MacOS also replaces Home and End with **Command+Left/Right Arrows** jumps to the beginning or end of a line - and again, in combination with Shift selects from the caret to the respective side of the line, and Backspace or Delete remove the respective side of the line.

### Steps To Reproduce
CE2 doesn't respect this control scheme, and assigns Command to select words - which I assume is because Control usually maps to Command when porting to OSX. Alt seems to do something entirely incorrect and enters a block selection mode.

There are *some* keybinds that should fix this in the Code Editor 2 section of the "Rebind Keys" preferences category, but they don't seem to work, nor are extensive enough to rectify this behaviour.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Mac 13.5

[99a0431a-efbf-4f7f-b12b-1146a606fb63](https://api.gamemaker.io/api/github/downloads/99a0431a-efbf-4f7f-b12b-1146a606fb63)

**Comment by zreedy** [comment]
The default hotkeys file should have overrides per platform and MacOSX entries should be added for CE2 entries as they are for CE1 entries.

**Comment by SmithTom6304** [comment]
Per platform overrides will be added for 2024.08 - see YoYoGames/YoYoStudio#10141

**Comment by SmithTom6304** [comment]
These should now all be working correctly, with the exception of `Command`+`BackSpace`/`Delete` deleting to the start/end of the line. This functionality needs to be added to CE2, as it doesn't exist on Windows. This should go in for 2024.08.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.586  Runtime v2024.800.0.610
