### ISSUE TITLE
9 Slice error in Editor and In-Game

### ISSUE THREAD

**Issue by FoxieGames1** [YoYoGames/GameMaker-Bugs#5429]
### Description

How in the Editor looks this problem:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/84648789/76b36c68-c09f-497f-9653-152d4a711b41)

How in game looks this problem:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/84648789/16cc6a10-e21e-4893-8550-bb45a7fc50b3)

### Steps To Reproduce

1. Start GameMaker 2024.2.0.132.
2. Open any project that you have.
3. Open an sprite and see the 9-Slice Option and crop your sprite.
4. See the issue.

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
