### ISSUE TITLE
gif_add_surface does not function in HTML5

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#5436]
### Description
When attempting to use `gif_add_surface` in the HTML5 runtime, data does not appear to be added to the gif and `Please set the correct size: ImageData length mismatch` is printed out in the console

Functions work as expected in Windows and GX.Games

### Steps To Reproduce
1. Run the attached project in HTML5
2. Open the Javascript console
3. Press 1 in the project to start recording a gif
4. Observe the erorr in the console
5. press 2 to try and save the gif to a buffer (this prints out the buffers size)
6. Observe the size being far smaller than expected

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22635.0

[305ff885-aa58-4703-9495-a584b14d50ad](https://api.gamemaker.io/api/github/downloads/305ff885-aa58-4703-9495-a584b14d50ad)

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.672  Runtime v9.9.1.814
