### ISSUE TITLE
Code editor 2 : Some bugs when using Chinese input method

### ISSUE THREAD

**Issue by MagicShiba** [YoYoGames/GameMaker-Bugs#5440]
### Description

1.When using the input method, the input content will be repeated several times.
For example, if you input ime when there is an input method, the actual output is iccc. When you press shift, the output becomes iccciime
![gxb1](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/bbcaca42-e75d-40de-9c6f-a7c77b34080d)
![gxb4](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/731ccbad-93c6-467b-a261-555eba7ffb80)

2.Deleting characters still results in duplicate input
For example, enter imetest
![gxb2](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/5a5652a8-e19c-4975-8bde-abf676e775d2)

3.Deleting ime characters will result in the inability to delete other characters
![gxbwsc](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/e8539cd3-6089-4dc0-96a9-98404fbd5b55)

4.As the window changes, the position of the input method is often wrong, affecting the input
![gxb3](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/755fb95c-72c6-4f58-a4f4-61dbb4346445)

5.Swallowing words. Sometimes the input characters are invalid and do not match the actual number of input characters.
As shown in the picture, enter 6/only 3, and the same is true for other characters.
![gxgb](https://github.com/YoYoGames/GameMaker-Bugs/assets/118909774/90b0c9f6-24e1-4b27-b150-19f2e8f6f404)

The above problems used to exist in the old code editor, but basically do not exist now. Similar problems occurred in 2.3.x. You can refer to the repair methods at that time.
(machine translation)

### Expected Change

Refer to other text editors，For example vscode.

### Steps To Reproduce

1. Start GameMaker
2. Open windows Settings, Region and Language and add Microsoft Pinyin input method
3. Switch to Pinyin input method and type something
4. See the issue
[bugpack.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14947912/bugpack.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
All issues above are fixed for me on IDE v2024.600.0.585  Runtime v2024.600.0.609 (latest Beta). 

However, I am using a laptop so the input may be slightly different. 

@MagicShiba could you please check that the issues are fixed on your set-up too? 

Many thanks
