### ISSUE TITLE
start app crash on android 

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GameMaker-Bugs#5441]
### Description

 Game Crashes on start

https://forum.gamemaker.io/index.php?threads/game-crashes-on-start.111240/

https://forum.gamemaker.io/index.php?threads/android-yyc-or-mv-useless.111194/#post-665320

all same issue

It's very urgent

Google Play is not updating (reject)

Please find the cause and hurry up to update the hotfix

### Steps To Reproduce

1. Start GameMaker
2. build android
3. app start on android phone
4. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by searoopy** [comment]
Buildchecking Armv7 often results in rejected Google Play updates After
unchecking it, the update should have proceeded normally.




GuRis (game dev studio)
Lee sanghyun (ceo,dev)
homepage : Guris (webflow.io) <https://guris-game.webflow.io/>
mobile : +821032796789


2024년 4월 12일 (금) 오후 5:37, Steven Campbell ***@***.***>님이 작성:
