### ISSUE TITLE
`json_encode()` page mentions accepting arrays

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#5442]
### Description

The page for `json_encode()` mentions:
```
json_encode() takes a DS map or array that you have previously created and encodes it as a JSON string[...]
```
However, it doesn't take an array, only a map _containing_ an array. This makes other language on the page confusing, such as:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/40671879/1077f8cf-09d0-4731-bb06-b4e7a8c53a5e)

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/Encoding_And_Hashing/json_encode.htm

**Comment by DiasFranciscoA** [comment]
Hello @backYard321,

Thank you for bringing this error to our attention. It appears to be a documentation inconsistency, which we have already corrected internally. The update will be included in the manual for the next beta release.

> [!WARNING]
> Arrays are not supported as input for the `json_encode` function. It exclusively accepts `ds_map` references as input.

**Comment by YYBartT** [comment]
The changes for this are in the linked PR, which will go into the next manual build once it is merged. The new page no longer mentions that arrays can be passed to the function (only that they can be a nested element and will be converted to JSON as well).

**Comment by mgeddesGM** [comment]
verified with manual build on 25/04/24
