### ISSUE TITLE
bm_max issue: no longer respects alpha, and VM/YYC divergence

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#5447]
### Description

We updated to Runtime 2024.400.0.556 from runtime 2024.400.0.547, and our lighting in Crashlands 2 appears to be broken somehow. The lighting system relies on using `bm_max` blend mode. In this newer runtime, all of the lights are all turbo bright -- I believe it's at least partially because bm_max no longer respects the alpha channel. It also appears as though bm_max is behaving differently in YYC than in VM.

We are also using a shader to interpret the output of the blend modes and applying a color change, so it's possible something has changed with how shaders are interpreting colors as well. Not sure on that one.

Here is a screenshot of the player standing near some glowing plants in YYC in runtime 556:
![](https://i.imgur.com/bymQd0C.png)

Here are those same glowing plants in VM in runtime 556:
![](https://i.imgur.com/VJv1Vbp.png)

And here's how it looked in runtime 547, which is what is intended:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/26627245/183f416e-2bff-4855-8734-a6ef55051106)

### Expected Change

Blend modes should behave as they did before.

### Steps To Reproduce

1. Toggle between the two runtimes and observe that bm_max no longer functions as it once did.
2. Compile in YYC and VM on the newest runtime and observe that bm_max behaves differently between the two compile methods.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by shichen85** [comment]
Might relate to this https://github.com/YoYoGames/GameMaker-Bugs/issues/4859

**Comment by JonnoRobson** [comment]
The behaviour of `gpu_set_blendmode(bm_max)` had been updated to more closely match normal Max blending. Unfortunately this issue cropped up since Source and Destination blend factors are not applied when doing Min/Max blending, meaning alpha blending was not being applied. I've reverted the blending behaviour when set using `gpu_set_blendmode(bm_max)` to match with previous versions, which should fix this issue. With these changes I am also not locally seeing any discrepancies in blending between GML and YYC builds.

**Comment by BscotchSeth** [comment]
Thanks for the quick fix, @JonnoRobson !

**Comment by gurpreetsinghmatharoo** [comment]
Manual updated.

**Comment by caitlinrmcintyre** [comment]
Verified fix as per the comment above from 3 weeks ago, thanks.
