### ISSUE TITLE
Code editor 2: Auto complete does not suggest constructors after typing new

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5448]
### Description
In the old code editor, if you type new, auto complete will suggest all of your constructors. This does not work in the new code editor, typing new will give no suggestions. Typing the start of the constructor name still won't suggest the constructor.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/70e8bd30-c649-4284-b8f2-e28fde99a5ab

Note: it appears constructors don't appear in autocomplete at all, regardless of if you type new first or not.

### Steps To Reproduce
Define some constructors, then type `new` somewhere and look at the auto complete window.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7483c408-af61-46a2-89c7-b8df874aff58](https://api.gamemaker.io/api/github/downloads/7483c408-af61-46a2-89c7-b8df874aff58)

**Comment by zreedy** [comment]
Fixed

**Comment by KormexGit** [comment]
https://github.com/user-attachments/assets/924b2a3b-6201-4109-b6a4-2e29eea28cad

It does suggest constructors after you type `new` now, but stops suggesting them as soon as you type a letter
