### ISSUE TITLE
Code editor 2: Code window splits are not saved between loads of the project

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5449]
### Description
If you split your code windows at all and then reload the project, all of the splits will be gone.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e3105f51-7e2b-43b9-8391-12d9cc770aec

### Steps To Reproduce
Split up some of your code windows, and then reload the project.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3454a4dc-62b1-4cb4-8d8b-bb4ec7827850](https://api.gamemaker.io/api/github/downloads/3454a4dc-62b1-4cb4-8d8b-bb4ec7827850)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.800.0.602  Runtime v2024.800.0.624, thanks.
