### ISSUE TITLE
Code editor 2: Hitting enter inside brackets attached to a with statement doesn't automatically indent

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5450]
### Description
When typing a with statement, hitting enter inside the brackets attached to it will not add an indent.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e0851b05-93f6-444d-8b17-196e488891c9

### Steps To Reproduce
```
with (Object1) {//hit enter here instead of this comment}
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[f03fc658-eb9c-4f7e-b3de-b8c48a95599a](https://api.gamemaker.io/api/github/downloads/f03fc658-eb9c-4f7e-b3de-b8c48a95599a)

**Comment by KormexGit** [comment]
This looks to be fixed in today's public beta!

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625 (and as per comments). 

Thank you.
