### ISSUE TITLE
Surfaces documentation needs clean-up and usage steps

### ISSUE THREAD

**Issue by gurpreetsinghmatharoo** [YoYoGames/GameMaker-Bugs#5452]
### Description

_Note: This is actually in the works, just creating this ticket for tracking work._

The page on Surfaces does not give a beginner a concise introduction to using Surfaces.

Make sure it has:
(1) Simple explanations for Surfaces
(2) Step-by-step instructions on using Surfaces

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/Surfaces/Surfaces.htm

**Comment by gurpreetsinghmatharoo** [comment]
Change can be seen here: https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Drawing/Surfaces/Surfaces.htm

**Comment by attic-stuff** [comment]
looks pretty great at a glance; one thing i would add is that you do not need to calculate the camera offset the long way, since you can just apply the view to the surface with camera_apply()
