### ISSUE TITLE
Boolean subtraction inconsistent between VM and YCC 

### ISSUE THREAD

**Issue by JustFredrik** [YoYoGames/GameMaker-Bugs#5457]
### Description

# Issue
Concider this expression `A - B`.

Having a `keyboard_check` evaluation returned from a function in position A while trying to subtract a boolean expression will result in inconsistent results between YYC and VM (`input() - true`). 

> YYC will evaluate this to `1`, while VM will evaluate it to `-1`

Having the keyboard_check directly in the expression (`keyboard_check(vk_space) - true`), does not result in any issues. The keyboard_check evaluation must be from a function return to reproduce the issue.

If the input function instead is in position `B`, the issue does not occur.

```gml
input = function() {
	return keyboard_check(vk_space);
}

// Issue
alice = input() - true; // inconsistent behaviour
alice_fix = (input()? 1. : 0.) - true // Work around for inconsistent behaviour
fred = false - true; // Example of expected output
bob = keyboard_check(ord("A")) - input(); // Expression works if input() is the one being subtracted from a bool

show_debug_message($"alice (broken):  {alice}");
show_debug_message($"alice (evaluation):  {alice}");
show_debug_message($"alice (fix):  {alice_fix}");
show_debug_message($"fred:  {fred}");
show_debug_message($"bob:  {bob}");

```
**VM Output:**
(input: `false`) >> alice  (broken): -1
(input: `true`) >> alice  (broken): 0

**YYC Output:**
(input: `false`) >> alice  (broken): 1
(input: `false`) >> alice  (broken): 0

Printing `alice` from the code example above results in `1` as output in YYC and `-1` in VM. Interestingly, the comparison `alice == -1` evaluates to true in both cases. So in this specific scenario, the engine reports the variable to be 1 but also equal to -1 in YYC.

## How it was found
I used similar logic in my platformer to derive player direction. I used a comparison such as `alice > 0` to see if the local player was facing left, due to doing this comparison the behaviour was consistent between YYC and VM. But, when I serialized the direction variable `alice` to send to other players in a multiplayer session, the player directions broke in YYC since it got converted to to 1 or 0 not -1, 0 or 1. This resulted in players running YYC builds showed up as always facing right on other clients screens.

[Contact Us Package with code example](https://github.com/YoYoGames/GameMaker-Bugs/files/14957817/wonky_boolean_expression.zip)

### Expected Change

The subtraction operation should yield consistent results across both YYC and VM environments.

### Steps To Reproduce

1. Define a function input that returns the result of `keyboard_check(vk_space)`. 
2. Perform a subtraction operation where the function's return value is subtracted by `true`.
3. Observe the output in both YYC and VM.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by thennothinghappened** [comment]
I can only think there's some weird optimisation that's going wrong on the YYC side during compilation - especially given it is dependent on whether the value is returned from a function or not.

**Comment by rwkay** [comment]
Fixed in 2024.6

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.557  Runtime v2024.600.0.572

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.557  Runtime v2024.600.0.572
