### ISSUE TITLE
Redefine Keys: [Mac IDE] Some of the Code Editor 2 commands are listed in a wrong location

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5458]
### Description

When opening redefine keys some of the commands for Code Editor 2 appear in the wrong section at the bottom of the list:

![Screenshot 2024-04-12 at 12 14 33](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/a251529c-d17e-4bda-abe8-3a43b5aa31e9)

### Expected Change

The commands should be listed under CE2

### Steps To Reproduce

1. Start GameMaker on a Mac
2. Open Redefine Keys in preferences
3. Scroll down to the bottom of the window
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This has now gone back into April, and should be in beta version IDE v2024.400.0.542

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.400.0.544  Runtime v2024.400.0.563/
