### ISSUE TITLE
Code Editor 2: Issues with autocomplete loading very slowly or not at all in large projects

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5463]
### Description
Another bug that I haven't been able to reproduce in a smaller project. In my main project, autocomplete is often very very slow, or doesn't work at all. Sometimes it only autocompletes when typing up to a certain number of characters.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/311055e7-38be-4f88-8c07-c81d5a702de8

### Steps To Reproduce
Start typing any variable or function that exists in the current scope, one character at a time, and watch the autocomplete window.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5ce49f93-7cc6-4a45-9377-5955fdc8e28a](https://api.gamemaker.io/api/github/downloads/5ce49f93-7cc6-4a45-9377-5955fdc8e28a)

**Comment by sixesixesixe** [comment]
i can confirm that autocomplete is functionally nonresponsive for sufficiently large projects. on my project, it fails to find anything whatsoever after the first use

i'd like to add that the large project does NOT need to be currently open for this to happen. you can open a large project, then open another small project (like the platformer example project) in its stead, and the issue will persist on the small project

https://github.com/YoYoGames/GameMaker-Bugs/issues/6447 also exhibits this 'previously opened large project' peculiarity

**Comment by zreedy** [comment]
Related to https://github.com/YoYoGames/YoYoStudio/issues/9899

**Comment by scott-dunbar** [comment]
Ive been unable to reproduce this using the suggested larger projects and even some others we had to hand. Im going to close this as verified in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649

For affected users, should you continue to encounter this please do report back
