### ISSUE TITLE
Project Saving: GML Visual scripts containing Execute Code node log lots of "Duplicate argument tag name code in DnD node Execute_Code" lines

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5464]
### Description
I was messing around with converting to visual and back, and noticed that my output tab is full of this message. "Duplicate argument tag name code in DnD node Execute_Code" appears every time an edit is made to an execute code block.

Edit: I originally reported this as a new code editor bug, but it's happening with the old code editor too

### Steps To Reproduce
Write some code, then convert it to visual. Type some random things in the block, then check output.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e69c1835-2c4c-4436-adf5-e558d5298be5](https://api.gamemaker.io/api/github/downloads/e69c1835-2c4c-4436-adf5-e558d5298be5)

**Comment by yyalansavage** [comment]
Other than spamming the log I think this was essentially harmless; fixed now in any case

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.400.0.543  Runtime v2024.400.0.562.

Thank you.
