### ISSUE TITLE
Code editor 2: Instance creation code button in inspector still opens old code editor

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5469]
### Description
Opening up an instance's creation code from the instance window in the room editor correctly opens up the new code editor, but the creation code button in the inspector still opens the old code editor.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/7c2b5436-ae72-40c2-9bb7-afbe4e2b4ea0

### Steps To Reproduce
Place an instance in the room, bring it up in the inspector, and then click the edit creation code button.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[39c5dd53-8302-44ff-9d42-4ebd17e95006](https://api.gamemaker.io/api/github/downloads/39c5dd53-8302-44ff-9d42-4ebd17e95006)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
