### ISSUE TITLE
Make the frame number visible inside the Sprite Editor

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#5474]
### Is your feature request related to a problem?

Not a bug but it's super frustrating that, when editing a multi-frame image via the built-in Sprite Editor, you cannot actually see what frame are you on. For that you have to go to the workspace and manually move to the frame you are editing and check the number.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/6c422f99-5b1b-4725-aad6-70200607ebe0)

### Describe the solution you'd like

Just a simple text in the status bar of the image that shows the frame number you're in:

![Sprite Editor with frame number](https://github.com/YoYoGames/GameMaker-Bugs/assets/28306587/9da61703-d869-4a4f-94d2-eaebdf7207ba)

**Comment by Totobal5** [comment]
Consider please.

**Comment by rwkay** [comment]
Feature Added in 2025.1

**Comment by YYBartT** [comment]
Updated the screenshot and description on the manual page.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
