### ISSUE TITLE
Handle xcframeworks in iOS Extensions

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#5478]
### Is your feature request related to a problem?

.xcframeworks are remplacing .frameworks in some extensions updates, GameMaker at the moment can't attach the mentionent files.

### Describe the solution you'd like

Be able of attach .xcframeworks as .frameworks on extensions settings.

### Describe alternatives you've considered

At the moment .xcframeworks are attached via Cocoapods.

**Comment by cameron-home** [comment]
@jzavala-YYG Do you have a sample project which contains a working extension with an .xcframework attached that I can test just to confirm this is working?
