### ISSUE TITLE
[HTML5] `static_get(self)` points to shared struct for ALL objects

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5486]
### Description
I was doing some testing on the weird way that `self` behaves (like how `typeof(self) == "struct"` but `self` is also not a struct) and found some strange behaviour with `static_get(self)`.

Essentially, on the current runner calling `static_get(self)` on an object returns a blank struct that seems to co-exist with the instance for its lifetime.

On HTML5 though, it seems to return some secret shared inherited struct between ALL objects in the game.

### Steps To Reproduce
In one object, do something like this:
```gml
var self_static = static_get(self);
self_static.a = 2;

// Ensuring we run first before the one that accesses it.
instance_create_depth(0, 0, 0, oSomeOtherObject);
```

And in `oSomeOtherObject`:
```gml
show_message(self.a);
```

On the current runner, this will crash as `self.a` is not defined. On HTML5, this will display `2`... so I seem to have found a way to pollute the `self` scope of every game object lol.

The code used verbatim to find this originally is below, as I was originally testing to see if this was object-specific (thus would mean HTML5 would secretly be capable of object-scope statics which I've wanted forever):

```gml
/// `oTest` Create Event
if (instance_number(oTest) == 1) {    
    var self_static = static_get(self);
    self_static.a = 2;
    
    instance_create_depth(0, 0, 0, oTest);
    instance_create_depth(0, 0, 0, oOtherThing);
    
    exit;
}

show_message(self.a);

/// `oSomeOtherObject` Create Event
show_message(self.a);
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Mac 13.5

[1e0a61d9-75cc-4c25-a292-85ae798fcbb9](https://api.gamemaker.io/api/github/downloads/1e0a61d9-75cc-4c25-a292-85ae798fcbb9)

**Comment by rwkay** [comment]
Implementations on C++ and Javascript will vary - do not rely on these underlying implementations, we do not document them for a reason (because they have to be different).
