### ISSUE TITLE
Asset browser/Inspector: assets should only open in the inspector after the click is released, rather than pressed

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5490]
### Is your feature request related to a problem?

This has been an annoyance for a while in places like the room editor but now that CE2 is designed around the use of inspector windows full-stop, it's become even more of a problem.

A number of properties in GameMaker (object sprite indices, asset variable definitions, things in the room editor, etc) allow having an asset assigned to them by clicking and dragging something from the Asset Browser. This is a big time-saver over clicking on the menu and searching for the asset yourself, but it doesn't work in inspectors because as soon as you click on an asset, it opens in the inspector instead.

You can get around this by locking the inspector, but locking the inspector every time you want to assign something and unlocking it when you're done is really annoying.

Live footage of me trying to assign a sprite to an object:

![asset browser and inspector](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/9b58129f-cc49-4008-8931-9132bd37bcff)

The most common way for UI to deal with this kind of thing is to only open something for selection after the left mouse button has been released (or to double-click to open, the way we did in workspaces). For example, this is how it works in Unity:

![inspector in unity](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/44d95e37-f77b-4566-801d-2e221b01f97f)

### Describe the solution you'd like

\*holds nose\* the way Unity does it

### Additional context

This also happens all over the place in the room editor inspector

**Comment by KormexGit** [comment]
Yes please, I had been thinking about requesting exactly this. If it doesn't change until the mouse is released, then the dragging to assign workflow works a lot better.

**Comment by YYDan** [comment]
We should verify that this fixes 5846 also

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v9.9.1.673  Runtime v9.9.1.815, thanks.
