### ISSUE TITLE
Code Editor 2: Show Parent Event/Open Parent Event doesn't do anything

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5491]
### Description

When you right-click an event header in CE2, the "show parent event" and "open parent event" options don't do anything.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/f2c59b86-517d-427f-97b1-c8c2763cbc11)

This is probably related to #[5396](https://github.com/YoYoGames/GameMaker-Bugs/issues/5396).

### Expected Change

"show parent event" to show the parent event

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Additionally, "Show Parent Event" was removed because it doesn't do anything different from "Open Parent Event" in CE2.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.599  Runtime v2024.800.0.622
