### ISSUE TITLE
Code Editor 2: Tab key always adds [4] spaces instead of aligning to the nearest indentation size

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5492]
### Description

When you hit the Tab key (and when you have tabs set to, we'll assume, 4 spaces) the code editor is supposed to first insert the number of spaces that would align the caret with the next level of indentation if the caret isn't already aligned to the tab size, like it does in CE1:

![ce1 tabs](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/23212aaa-4ac6-4eaa-9228-1d1a7df6c303)

But in CE2 the Tab key will always add [4] spaces, and it won't ever attempt to align:

![ce2 tabs](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/9e97d3d9-f318-4d89-b702-be1ebd8317bc)

This may or may not be related to #5295 and/or #5337.

### Expected Change

CE1 tab behavior

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed, with and without Ligatures enabled.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.565  Runtime v2024.600.0.585
