### ISSUE TITLE
Cannot select Test as Default Build Target when not logged in

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#5493]
### Description
Bug investigation and report prompted by a GameMaker Community status update.

When you're logged out, you can only choose GX.games as a Default Build Target even though Test is available for not logged in users as well. This might also apply to logged in users without any license or only with the old perpetual license, but I can't tell since I've got Professional license myself.

Since Test target is available to logged out users, I'd expect it to be available on the dropdown. Ideally it would be the default Default Build Target as well, since newcomers make lots of errors at the beginning, and from my experience Test target is generally better at showing the errors than GX.games (it's more of an opinion).

Also, when I checked an earlier stable version, it didn't show the Default Build Target dropdown, but it was 2023.8 so a lot might have changed since then. Still mentioning it, since the GMC member who posted the original status update might have seen no dropdown at all on the stable release.

### Steps To Reproduce
1. Open GameMaker IDE
2. Logout if you aren't logged in already
3. Open File >> Preferences >> General Settings
4. See that only "GX.games" is available from the Default Build Target dropdown

### Additional Context
The status update in question:
https://forum.gamemaker.io/index.php?members/yaazarai.890/#profile-post-55997

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[159063c2-7f8c-4227-8df5-323d866e41d2](https://api.gamemaker.io/api/github/downloads/159063c2-7f8c-4227-8df5-323d866e41d2)

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.600.0.569  Runtime v2024.600.0.596, thanks.
