### ISSUE TITLE
In-Game: bm_subtract creates a different end result than expected in 2024.400 runtimes

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#5496]
### Description

Tested in runtime 2024.400.0.559

`gpu_set_blendmode(bm_subtract)` no longer draws the way it did in prior runtimes. It now draws with a much more amplified effect, making things darker than in earlier runtimes.

It also now creates a different effect from `gpu_set_blendmode_ext(bm_zero, bm_inv_src_colour)` , which still behaves as it used to.

Currently, `gpu_set_blendmode_ext(bm_zero, bm_inv_src_colour)` still renders as intended, so we were able to replace all instances of `gpu_set_blendmode(bm_subtract)` with it and still have our game look as before. However, it is concerning that a change like this would be made without a regression test.

When making changes to blend mode functionality, regression tests should be used to ensure they produce the same visual effects as before. Game devs will have created the visuals for their games contingent upon how these blend modes interact with color channels, so the blend modes should produce identical results across runtime versions.

### Expected Change

`bm_subtract` should draw the same as it did in prior runtimes.

### Steps To Reproduce

1. Start GameMaker
2. Draw a sprite using `gpu_set_blendmode(bm_subtract)` 
3. Draw a sprite using `gpu_set_blendmode_ext(bm_zero, bm_inv_src_colour)`
4. Notice that these look different.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yymrennie** [comment]
Fixed in 2024.4

**Comment by mgeddesGM** [comment]
sample project [blend_subtract_test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15132856/blend_subtract_test.zip)

**Comment by mgeddesGM** [comment]
verified in  IDE v2024.4.0.134  Runtime v2024.4.0.166 for win, operagx and android

waiting for testing on a mac to change status

**Comment by Emc1923** [comment]
Verified on Mac as of  IDE v2024.400.0.555  Runtime v2024.400.0.569, closing.
