### ISSUE TITLE
Code Editor 2: feather tooltips can spill over the top of the screen

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5497]
### Description

If you have a large tooltip box and/or the cursor is close to the top of the code editor window, the feather tooltip can spill out of the window.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/e523238a-d8a7-4b5d-9035-068bcc2eb6f4)

I'm pretty sure this is only an issue in CE2. In the old code editor, tooltips will appear beneath the cursor if they're too close to the top of the window.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/4f2b7d20-3520-4a0c-8fe6-26edcd1f09aa)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.562  Runtime v2024.600.0.580, thanks.
