### ISSUE TITLE
HTML export should have a webassembly option.

### ISSUE THREAD

**Issue by TheRealJeku** [YoYoGames/GameMaker-Bugs#5498]
### Is your feature request related to a problem?

When I export my game for HTML, it is currently showing just a white screen and not any useful way for me to figure out what the problem is.  In the past there were typically scaling issues in that everything was appearing larger than the window size.  

### Describe the solution you'd like

When I export my game for gx.games it is, as I understand it, compiled using webassembly and is almost exactly the same as it would have been compiled to the native platform.  My game runs PERFECTLY.  I would like the option of selecting the HTML export and selecting the webassembly option so I can host it on my own site.

### Additional context

As far as I can see, I can probably grab the gx.games version of my game when I do that export and use that version on my own personal site.  However I'm not sure if that's legal or if will even work.  Can you provide steps to do that or have the webassembly option as part of the HTML export?  Because currently HTML exporting doesn't work for my project.  Thanks!

**Comment by stuckie** [comment]
This is not currently planned.

**Comment by TheRealJeku** [comment]
So what are the legalities of me using the exported gx.games version of my game on my own website?

**Comment by YYDan** [comment]
FYI, this discussion has moved on in https://github.com/YoYoGames/GameMaker-Bugs/issues/7454

**Comment by TS-DEV-DEBUG-V2** [comment]
just like add some GX GAME api stubs (or just add it to your site and hide all gx game stuff with CSS) (thats what i do)
