### ISSUE TITLE
In-Game: phy_particle_flag_wall() does not work correctly

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#5499]
### Description

If I set physics_particles from phy_particle_flag_water to phy_particle_flag_wall and then back to phy_particle_flag_water,

then the particles do not collide correctly anymore. The problem is, if I convert particles to phy_particle_flag_wall, then the collisions stop to work correctly.

See video

https://github.com/YoYoGames/GameMaker-Bugs/assets/30154346/8e70e4f1-e501-4131-b6d3-2e3273c76602

### Expected Change

The particles should not lose their collision-ability after being converted from phy_particle_flag_wall back to any other flag

### Steps To Reproduce

1. Start GameMaker
2. Water particles get created
3. Water particles get converted to wall particles
4. Wall particls get converted back to water particles and then the lose their collisions
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2022.0.2 (LTS), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Glim888** [comment]
[phy_particle_flag_wall_bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14999661/phy_particle_flag_wall_bug.zip)

**Comment by Glim888** [comment]
I am wondering, if you guys could fix this, because I need it pretty bad for my game, which is a water simulator with more than 10mio downloads on all platforms:

https://play.google.com/store/apps/details?id=com.gaming_apps.water_physics_simulation

**Comment by Glim888** [comment]
The bug seems easy to fix, because I figured out, when this happens:

As you can see in the video below, the particles stop to collide with the terrain, if I add the phy_particle_flag_wall flag to a particle, that touches the terrain.


https://github.com/YoYoGames/GameMaker-Bugs/assets/30154346/7e3fac9f-d74b-4bc6-84f3-92be1cc41917

**Comment by Glim888** [comment]
@jackerley thanks for self-assigning this. This will help me with my game, I appreciate this a lot. :)

If you need any help or more hints, then let me know.

**Comment by Foxtrio** [comment]
Any updates in this issue? I'm observing the same problems.

**Comment by brankoblazevic** [comment]
Hi Yoyo,
I kindly ask that this bug gets fixed as soon as possible. It's quite unfair that a developer with over 10 million downloads is facing this issue. This should be treated as a high-priority fix to ensure we keep supporting great GameMaker projects like this one.

We need to give professional developers the attention they deserve. I know you have a lot on your plate, but maintaining a reliable engine is key to long-term success.

Thanks in advance for addressing this!

**Comment by Glim888** [comment]
@stuckie any news on this?

**Comment by stuckie** [comment]
It looks like this lost some status settings on GitHub, so I've reset it for Triage to bring it back in focus.

**Comment by Glim888** [comment]
Thanks. I really need it and I still wait for 6 months now. 

I hope resetting it to TRIAGE from TODO does not mean it will be lose the TODO status longterm.

:)

**Comment by Glim888** [comment]
Thanks @jackerley @stuckie @mgeddesGM
