### ISSUE TITLE
Code Editor 2: Selected theme appears blank after creating a new theme until you select the drop down

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#5504]
### Description

When creating a new CE2 theme, the selected theme appears blank until you select the drop down.

https://github.com/YoYoGames/YoYoStudio/assets/131007845/f0e1e9be-7ce4-435a-9b97-c01dac641eeb

### Steps To Reproduce

1. Start GameMaker and go to preferences > CE2 > Theme.
2. Click "New..." and "from Copy of Selected".
3. Press OK and see that the selected theme is blank.
4. Click the drop down and see that it appears.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.400.0.541  Runtime v2024.400.0.560

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.558  Runtime v2024.600.0.573
