### ISSUE TITLE
CE2 - Hotkey Chords - Not working in several areas

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#5505]
### Description

Some Global Hotkey chords are not working in one area but do in another. Or in some areas local chords do not work 

This is related to YoYoGames/YoYoStudio#8701 

### Expected Change

chords will work everywhere

### Steps To Reproduce

1. Start GameMaker and log in with an account that has CE2 access
2. go to Code Editor 2 and set to enabled
3. go to preferences - Redefine Keys
4. change undo to the chord "ctrl+l => ctrl+o"
5. create a note and type some text
6. press "ctrl+l => ctrl+o", the text will remain
7. create a script and add some text
8. press "ctrl+l => ctrl+o", the text will remain
9. create an object with an event and add some text.
10. press "ctrl+l => ctrl+o", the text will remain
11. Create an animation curve and add a new curve
12. press "ctrl+l => ctrl+o", the new curve will be gone
13. create a sequence, add a sprite then add a broadcast
14. press "ctrl+l => ctrl+o", the broadcast will be gone
15. press "ctrl+l => ctrl+o", the sprite will be gone
16. go to preferences - Redefine Keys
17. change CE2 - convert to lower case to the chord "ctrl+l => ctrl+o"
18.  go to the object and type "Bob = 123"
19. press "ctrl+l => ctrl+o" the text will remain in the same case
20. right click and choose convert to lower case, the text will be all lower Case

### How reliably can you recreate this issue using your steps above?

None

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.540  Runtime v2024.400.0.559

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by SmithTom6304** [comment]
These should now all be fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1151  Runtime v2026.100.0.1101
