### ISSUE TITLE
Preferences - Redefine Keys - Key Search text box being filled with previously pressed keys

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#5506]
### Description

If a user goes to Preferences - Redefine Keys - Key Search and tries to find a key, then extra key presses from previous uses since IDE was restarted

### Expected Change

The keys shown will be the same the user presses

### Steps To Reproduce

1. Start GameMaker
2. go to Preferences - Redefine Keys  and press Key Search
3. press F
4. notice the correct keys are in the text box and correct results show
5. delete P and press F
6. both these will show and the key presses in between
![image](https://github.com/YoYoGames/YoYoStudio/assets/103565197/f77f3fbd-62f1-4363-bc01-2fc66c88a2a6)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.539  Runtime v2024.400.0.558

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by SmithTom6304** [comment]
Believe this has since been fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.580
