### ISSUE TITLE
Inspector: Cannot drag a Sprite onto an already-open Object in the Inspector, as the Inspector changes focus too quickly

### ISSUE THREAD

**Issue by skud92** [YoYoGames/GameMaker-Bugs#5507]
### Description

The inspector works as expected however after using the object editor for so long I instinctively went to drag my sprite over from the asset browser onto the inspector to set it.

![image](https://github.com/YoYoGames/YoYoStudio/assets/42850338/5f131b05-0df0-4394-8136-775a60216753)

I didn't realise that upon selecting the sprite the inspector changed because of the selected state.

This was jarring the first time and took me a second to work out what was actually going on. Some users might not notice  until they are trying to drag their sprite onto their sprite in the inspector - its confusing and isn't expected from a legacy pov.

This now results in only being able to set sprites on objects through the asset explorer which is clunky especially if the project is med/large in size. Users rely on the search and becomes tiring if you set lots of objects at once.

![image](https://github.com/YoYoGames/YoYoStudio/assets/42850338/b487ce35-bd3c-4ffc-8b04-3c27a05fd129)

**Suggestion**

We allow for a modifier when selecting assets from the asset browser to disable the updating information in the inspector. For example ctrl+click & drag, will allow users to drag the sprite from the asset browser leaving the inspector showing the object.

We could also allow for a **pick whip** which is something common in anim/editing tools. This is an icon we can add to the selector in the inspector and allows users to click and drag onto the sprite and select this way. This was something that was in and working way back in the start of sequences.

![12-Pickwhip](https://github.com/YoYoGames/YoYoStudio/assets/42850338/091af134-bd8c-4f9c-9342-293cdcfa94a3)

I think this is pretty key in improving the inspector UX and returning the drag and drop functionality to sprites onto objects

### Expected Change

Improved sprite setting UX

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

None

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by yyalansavage** [comment]
Asset browser now inspects on mouse release, when node was not dragged

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v9.9.1.673  Runtime v9.9.1.815, thanks.
