### ISSUE TITLE
gpu_get_fog()[1] will not equal the colour fog was set to

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#5509]
### Description

`gpu_get_fog()[1]` will not return the colour value that was initially passed in to `gpu_set_fog()`. If fog was set to `c_red` using `gpu_set_fog(true, c_red, 0,1)`, `gpu_get_fog()[1] == c_red` will be false.

[fog issue.ZIP](https://github.com/YoYoGames/GameMaker-Bugs/files/14998093/fog.issue.ZIP)

### Steps To Reproduce

1. Create a new project
2. In the room creation code, type:
```gml
gpu_set_fog(true, c_red, 0,1)
show_message(gpu_get_fog()[1] == c_red)
```
3. See the issue - the message shown is "false", even though fog is set to c_red.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
gpu_get_fog()[1] returns the fog colour with the alpha in it, so you get 4278190335 or FF0000FF in hex back, alpha 1, red 255

**Comment by backYard321** [comment]
> gpu_get_fog()[1] returns the fog colour with the alpha in it, so you get 4278190335 or FF0000FF in hex back, alpha 1, red 255

ohhh okay, how would you go about finding the value without the alpha?
