### ISSUE TITLE
[YYC] array_get :: Index [-1] out of range error

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5514]
### Description
We are getting this error for YYC only and not VM when accessing array elements.

### Steps To Reproduce
1. Pull the CL2 repo from the `develop` branch
1. Open the CL2 YYP project and run  for YYC Windows with the `dev` config
2. Log as mentioned in https://github.com/bscotch/crashlands-2/issues/89
3. Click on the Workshop button (the 3rd one) on the right
4. Go to `My Worlds` and `Create New World`, which brings you to a tile editiing interface
5. Click on the tile and see the error:

```

___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event0
for object o_editor:

array_get :: Index [-1] out of range [0]############################################################################################
gml_Script_zone_tile_get_at_coords (line 212)
gml_Script_zone_tile_exists_at_coords (line 237)
gml_Script_zone_tile_get_top_layer (line 246)
gml_Script_editor_perform_placement (line 147)
gml_Object_o_editor_Step_0 (line 92)
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.540 Runtime v2024.400.0.559

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android, Windows

[92d40a0d-984c-47a0-91e8-31d909504dc9](https://api.gamemaker.io/api/github/downloads/92d40a0d-984c-47a0-91e8-31d909504dc9)

**Comment by shichen85** [comment]
@rwkay @jackerley should have access to the repo

**Comment by shichen85** [comment]
@BscotchSeth

**Comment by shichen85** [comment]
Sample code for replication:
```gml
var existing_arr = array_create(1, "value");
show_debug_message("Should be able to access values with accessor, no accessor, and the function");
for (var i = 0; i < array_length(existing_arr); i++){
		show_debug_message("no accessor:" + (existing_arr[i]));
		show_debug_message("accessor:" + (existing_arr[@i]));
		show_debug_message("function:" + (array_get(existing_arr, i)));
}

show_debug_message("Calling ds_map_*_to_array() on an empty map");
var _map = ds_map_create();
ds_map_keys_to_array(_map);
ds_map_values_to_array(_map);

for (var i = 0; i < array_length(existing_arr); i++){
	show_debug_message("no accessor:" + string(existing_arr[i]));
	show_debug_message("accessor:" + string(existing_arr[@i]));
	//Using the function throws an error
	show_debug_message("function:" + string(array_get(existing_arr, i)));
}
ds_map_destroy(_map);
```

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.400.0.544  Runtime v2024.400.0.563

**Comment by jbonesy** [comment]
I still have this occurring in 2024.4.201 as a heads up.

**Comment by BscotchSeth** [comment]
@shichen85 Do we have an automated test for this, and if so, is it still occurring in the latest beta?

**Comment by rwkay** [comment]
The issue can manifest itself in different ways - the issue is that the error flag is being raised somewhere else but is only checked within the array_get function - but because it has happened much earlier then it is trickier to track down.

I can fix it relatively easily by activating the checking code, but this really slows down YYC execution so I do not leave it in.

If you file a bug then I can generally track down (and fix) the issue easily, on YYC it should not be activating this at all but I found corners of the runtime that cause this.

This is usually a symptom of bad array access with the runtime that VM is getting away with, rather than bad user code.

**Comment by shichen85** [comment]
@BscotchSeth Yep, we are testing this in Ganary with the aforementioned replication code at https://github.com/bscotch/ganary/blob/7c2344a0783eff93f617ebbd1f5d4ae5c40b1d0d/Ganary/scripts/grc_register_sync_function_tests/grc_register_sync_function_tests.gml#L12
The latest 600 beta runtimes passed the test.
