### ISSUE TITLE
Code editor 2: Change "Create Event" back to "Add Event" to avoid confusion with the create event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5519]
### Is your feature request related to a problem?

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/aa6c8645-248d-43bb-98c7-1f6b3961f1a9)
In the new code editor, the button to add an event to an object is labeled "Create Event". This is also the name of the event called create, which could cause some confusion, especially for new GM users.

### Describe the solution you'd like

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/bdb1ceb2-b04f-4585-94ac-035bd21b41ba)
In the old code editor the button was labeled "Add Event", so I propose going back to that.

**Comment by DragoniteSpam** [comment]
rip kormex sniped my report

> the text that says "create event" means "create event" in a different lingusitic sense than the "create event" which is the event that runs when the instance is created. also neither the word "create" nor "event" sound like real words anymore

**Comment by thennothinghappened** [comment]
While we're on this I'm hoping that screen might be getting replaced by something more friendly - centred button and text saying "Create Event" especially given that already refers to an event is both not very user friendly via the GUI (given you have to mouse over to this tiny box) nor keyboard friendly (it doesn't have any obvious method of choosing one by keyboard without digging through binds).

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.618  Runtime v2024.800.0.642
