### ISSUE TITLE
In-Game: Desktop platforms should block the use of an IME during gameplay

### ISSUE THREAD

**Issue by offalynne** [YoYoGames/GameMaker-Bugs#5524]
### Description

Windows IME bugs out Runner

### Expected Change

Windows IME should be selectively disabled for the Runner application

### Steps To Reproduce

1. Install support for any language that using Input Method Editor eg. CJK
2. Enable IME from taskbar or hotkey eg. Ctrl+CapsLock
3. Run GM, observe that keyboard input is broken and any key press pops the IME open in the corner of the screen

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by adam-coster** [comment]
@shichen85 if you want to share anything about your solution this would be the place!

**Comment by adam-coster** [comment]
Note that GameMaker receives VK Code `229` when the user tries to input with an IME (at least for Chinese), so in the absence of disabling the IME automatically you can at least detect that it is being used and tell the player to disable it.

**Comment by rwkay** [comment]
Do you have any documentation links on how to disable the IME?

**Comment by shichen85** [comment]
@rwkay You can use this win32 API: https://learn.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immassociatecontext
Examples can be seen here: https://ftp.zx.net.nz/pub/Patches/ftp.microsoft.com/MISC/KB/en-us/171/154.HTM

**Comment by adam-coster** [comment]
Note that the ideal GameMaker behavior for this would be to have functions to enable/disable IME, and check to see if it is active.

That way we can disable it for regular game inputs but re-enable it when we want the user to actually be able to input text.

**Comment by yoyo-danielc** [comment]
This is fixed on the 2024.06 branch.

The key code 229 (`VK_PROCESSKEY`) doesn't get translated into GM now, and it is possible to disable IMEs by calling `keyboard_virtual_hide()` (and `keyboard_virtual_show()` to re-enable them).

**Comment by adam-coster** [comment]
@yoyo-danielc Some follow-ups to the new feature:

- Is there a function or readonly variable for checking if IME is currently active?
- What happens if I call `keyboard_virtual_show()` if it's already active? And the same for `hide`? (I'm hoping it just doesn't do anything, rather than, say, throwing.)

**Comment by yoyo-danielc** [comment]
@adam-coster

* keyboard_virtual_status()
* Yep, no-op

Also FYI, the status reported by `keyboard_virtual_status()` is whether or not IMEs are allowed, not whether the user specifically has one activated at this moment.

**Comment by alicemoretti** [comment]
Can we get a sample project to verify this please?

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.6.1.160  Runtime v2024.6.1.208. 
Thank you/
