### ISSUE TITLE
MacOS virtual keycodes mismatch keyboard layout

### ISSUE THREAD

**Issue by offalynne** [YoYoGames/GameMaker-Bugs#5525]
### Description

MacOS virtual keycodes mismatch keyboard layout

### Expected Change

Keycodes should match active layout instead of QWERTY

### Steps To Reproduce

1. Set up a nonQWERTY keyboard layout variant (eg. French, German)
2. Run GM, observe that VK codes match QWERTY while chars reflect keyboard layout

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed on 2024.06 branch.

The character value now take priority over the keycode when mapping latin alphabet characters on macOS and Linux, the previous keycode mapping is still used for other characters.

non-ASCII characters are now correctly handled and read into `keyboard_string`/`keyboard_lastchar` on macOS.

**Comment by Emc1923** [comment]
Verified as of Beta IDE v2024.600.0.585 Beta Runtime v2024.600.0.609
