### ISSUE TITLE
Variable/Parameters which share a Global Function Name perform incorrectly

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#5530]
### Description

```
/// in some script:
function seconds() {}
function something(seconds=-1) {
    show_debug_message(string(seconds));
}

/// somewhere else
something();
```

I would expect `-1` to be printed, but instead `undefined` is printed. If the `seconds` **function** is removed, then `something()` prints `-1` as expected, so the issue is the overlapping global function and parameters.

I suspect this is related to https://github.com/YoYoGames/GameMaker-Bugs/issues/4885 but didn't see a bug highlighting exactly this and wanted to bring it to your attention

### Steps To Reproduce

Copy the code above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Unable to reproduce - this has been fixed earlier in the Beta cycle

**Comment by sanbox-irl** [comment]
> Unable to reproduce - this has been fixed earlier in the Beta cycle

thanks!
