### ISSUE TITLE
CE2: Feather permanently enabled

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5539]
### Description

In the newest Beta Feather is constantly enabled if you have CE2 enabled. The Feather preference (enabled/disabled) is ignored.

### Expected Change

Make Feather optional again when using CE2.

### Steps To Reproduce

1. Activate CE2 -> See that Feather is active even if you have it disabled

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
This is deliberate and it was the case in the last Beta also - it's not new for this one, btw.

There are already issues filed for various parts of Preferences need to be renamed/changed/reshuffled in order to make clear which relate to CE1/Feather and which relate to CE2/Diagnostics, but I will leave this one open for now while we implement those other ones.

**Comment by rwkay** [comment]
CE2  only has LSP for all syntax and intellisense there is no alternative... you cannot disable it.

Feather is not used for CE2 at all - so it cannot be disabled as such.

**Comment by zreedy** [comment]
CE2 uses Language Server Protocol to provide Language Services such as Code Completion, Color Coding, Hover Tooltips, etc.
As such, we now have a GML Language Server which runs in the background as a separate process with CE2. This server is powered by Feather and it is not possible for us to implement the features of LSP without Feather driving the server.

You should find that `Feather Settings -> Message Severity -> Profile` option does work, if you prefer a more "vanilla" experience you can change this to either `Syntax Errors` or `None`.
