### ISSUE TITLE
CE2: Backspacing to the end of a line highlights the variable name in it

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5540]
### Description

Difficult to describe but watch the GIF. If you backspace to the end of a line in CE2 then the variable highlighter highlights the variable name in that line even though the cursor is not in the variable name.

![backspace_highlight](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/97b1dcc7-5def-4364-800c-a290315270c4)

### Expected Change

Don't highlight the variable name if the cursor is not in it.

### Steps To Reproduce

1. Use backspace in CE2 to move the end of a line with a variable name in it -> The variable name will be highlighted

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Unable to reproduce. Suspect this has long been fixed considering this was reported in April.
