### ISSUE TITLE
CE2: "Highlight selection matches" also highlights a variable if there are no matches

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5541]
### Description

In the old Code Editor when "Highlight selection matches" is active then the variable name that the cursor is in only gets highlighted if there are multiple occurances of that variable name. 

In CE2 the variable name the cursor is in **always** gets highlighted even though there is only a single occurance of it. This can mislead the user into thinking that there must be another occurance of the variable in the script.

### Expected Change

Only highlight the variable name if there actually are matches.

### Steps To Reproduce

1. Activate CE2 and activate "Highlight selection matches"
2. Write a single variable name and click into it -> it will get highlighted even though there are no matches

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed.
Additional issues fixed with the highlight selection matches feature:
 - Selections are off-by-1
 - Highlights appear inside of selection
 - Word boundaries are not respected when doing exact match highlights for the Text Cursor over a symbol. (e.g. Leaving the Text Cursor over a variable `speed` would also highlight `movement_speed` despite not being an exact match).

**Comment by mgeddesGM** [comment]
all pass in  IDE v2024.800.0.591  Runtime v2024.800.0.616 apart from "Word boundaries are not respected when doing exact match highlights for the Text Cursor over a symbol. (e.g. Leaving the Text Cursor over a variable speed would also highlight movement_speed despite not being an exact match)."

I had speed, movement_speed and movement_speed. i clicked "speed" and on all three lines the word "speed" was highlighted

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
