### ISSUE TITLE
Code Editor 2: Delete key to remove an empty line inserts an unwanted space at the start of subsequent lines

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5542]
### Description

If you place the cursor in an empty line in CE2 - right above a line with code in it - and then press 'Del' to move the line up by one, a space is inserted at the beginning of the line.

![del_insert_space](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/2c06f290-89a1-4a98-aed6-c1e43a5335db)

**UPDATE: The bug goes even further:** If there are multiple blank lines from where you press 'Del' to the next line containing code, then all the empty lines in between have a space added.
All I do in the following gif is press 'Del' once while the cursor is in line 2.

![del_inserts_more_spaces](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/972fe072-2b27-418b-9795-7bf10343a90e)

### Expected Change

Don't insert the space.

### Steps To Reproduce

1. See gif.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Please note that it is intended that a single space is added when the delete or backspace keys are pressed and 2 lines of code which both do not contain whitespace are merged.
With this in mind the following bugs have all been fixed to achieve this documented behavior:
 - DEL adds single space when joining a blank line
 - DEL adds a single space when joining a non-blank line onto a blank line
 - Backspace does not trim leading whitespace and replaces with a single space when joining two non-blank lines

**Comment by caitlinrmcintyre** [comment]
Verified in IDE v2024.800.0.593  Runtime v2024.800.0.617, thanks.
