### ISSUE TITLE
Code Editor 2: Removing multiple lines of code at once with Ctrl+X can lead to strange results

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5543]
### Description

In CE2 when using 'Ctrl+X' to remove code from a code block under specific conditions can lead to strange results. The below GIF shows an example and is 100% reproducable. All I do in the GIF is highlight the code and press 'Ctrl+X' once.

![ctrl_x_glitch_01](https://github.com/YoYoGames/GameMaker-Bugs/assets/25714975/ca14b147-1393-4ba3-99f9-0b7b8263354f)

### Steps To Reproduce

1. See example GIF

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Unable to reproduce. This issue was fixed when previous tickets related to color coding and font rendering were fixed.
