### ISSUE TITLE
Code Editor 2: Tabs and erasing text at the end of a line causes the wrong characters to be deleted

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5551]
### Description
see video [included in the .zip attached , there is] nothing more to say.

[From the video, it looks like attempting to delete a tab after a closing } on a code block is ignoring the tab and instead deleting the previous real character, but then this persists for all chars on that line and then that unwanted tab keeps going up onto the line above and yet still CE2 deletes the character on the other side of the tab rather than the tab itself ?]

### Steps To Reproduce
1) Open project attached
2) Go to oPlayer line 47 try to delete some line of code

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[b6cc92d5-05b6-4910-a7b9-61a6f6d9cb12](https://api.gamemaker.io/api/github/downloads/b6cc92d5-05b6-4910-a7b9-61a6f6d9cb12)

**Comment by zreedy** [comment]
The bug shown appears to be related to ligature bugs which have been resolved now. Unable to reproduce when testing along the repro steps.

**Comment by Totobal5** [comment]
Hi, sorry for the late response.
The Font i am using is _Fira Code SemiBold_

the link: https://github.com/tonsky/FiraCode

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.579  Runtime v2024.600.0.605, thanks.
