### ISSUE TITLE
CE2: Fold button make other text to stop appearing

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5552]
### Description
This one is really weird.

### Steps To Reproduce
1) Go to __GameConfig on the proyect attached.
2) Press the fold button on the GameSettings declaration
3) Scroll down

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[b0306ad7-4b96-4044-b6a8-6af691b016cb](https://api.gamemaker.io/api/github/downloads/b0306ad7-4b96-4044-b6a8-6af691b016cb)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.602  Runtime v2024.800.0.624
