### ISSUE TITLE
CE2: Some description appear weird now

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5553]
### Description
In the stable version this function at it description appear normal on the "description" part in the feather tool-box. Now it appear broken

### Steps To Reproduce
1) See input_check in the attached proyect
2) Put mouse above it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[a6538397-e0b8-4f8c-b12f-5c4a7077772c](https://api.gamemaker.io/api/github/downloads/a6538397-e0b8-4f8c-b12f-5c4a7077772c)

**Comment by zreedy** [comment]
The tooltips appears correctly in the latest build. The issues shown in the attached screenshot are not seen in the description.
