### ISSUE TITLE
CE2: Feather think that .function its a separated "variable"

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5554]
### Description
If you have the following:

struct.function_that_return_self()

when passing the mouse above it feather will think that function_that_return_self is a separated variable and not part of the "struct" part.

### Steps To Reproduce
1) Open oPlayer in the attached proyect.
2) go to line 31 of the step event.
3) pass the mouse above the animations.current()

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[d9fe520b-9d26-46b4-af06-cde916aaca19](https://api.gamemaker.io/api/github/downloads/d9fe520b-9d26-46b4-af06-cde916aaca19)

**Comment by stuckie** [comment]
This appears to be working as expected now.
If you still think there is an issue, please create a new issue, with as much information as you can.

Thanks!
