### ISSUE TITLE
CE2: Feather alerts are placed in the wrong place

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5555]
### Description
i have a function that just accept one type of parameter, so when i do wrong and feather tell me it put the yellow line in other part of the same line

see video atached for more.

### Steps To Reproduce
1) go to oPlayer of the attached proyect
2) go to line 89

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[34be4dcd-2b41-4336-b0c2-27fb281b544d](https://api.gamemaker.io/api/github/downloads/34be4dcd-2b41-4336-b0c2-27fb281b544d)

**Comment by zreedy** [comment]
Unable to reproduce. The video demonstrates an issue that has already been fixed regarding macro expansion reporting the ranges in the original source file rather than the reference tokens.
