### ISSUE TITLE
CE2: View scroller does not show some part of the code.

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5556]
### Description
see video

### Steps To Reproduce
1) Go to oPlayer in the attached proyect
2) Use the view scroll.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[22a19e82-65eb-44cf-a30c-28a6649c9047](https://api.gamemaker.io/api/github/downloads/22a19e82-65eb-44cf-a30c-28a6649c9047)

**Comment by stuckie** [comment]
This should be fixed in a later version.
If you still believe this to be broken, please send in a new ticket, with as much information as you can, and we will take a look.

Thanks!
