### ISSUE TITLE
tile data becomes newline separated in 2204.400.0.543

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5559]
### Description

After loading projects in IDE `2204.400.0.543`, in tiledata newlines were added after each comma, making .yy files for rooms very very long (like few hundreds to few thousand lines).

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/42f898af-b4e8-4f3d-bdff-0e068f2eb6d9)
 

### Steps To Reproduce

1. Start GameMaker
2. Open any project with tiledata and under .git
3. Observe diff for rooms

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

**Comment by gnysek** [comment]
Hmm, it's interesting - after adding any new tiles on such modified layer, and then removing it, it seems to fix (but numbers aren't exactly same):

![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/86c1d08e-1303-446a-a30b-6127e147cf9e)

Seems it must be caused by some fix added in 2024.4(00).

As I'm unable to reproduce from smaller project, I'm closing it for now (this can be bypassed, and is not happening to every room).

**Comment by jonathan-markland** [comment]
Hi this is still interesting, and if there is any possibility to reproduce the layout problem I would appreciate seeing that.

The numbers will be somewhat different because it is a compressed data stream.
