### ISSUE TITLE
OLD code editor: Holding down various combinations of keys causes unexpected behavior

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5560]
### Description
This is new to the most recent beta. What I've found so far is:
Holding down shift + enter and then pressing any other key will add two line breaks. (in 2024.2, this ignores the enter key and types whatever key you pressed)
Holding down shift + delete and then pressing any other key deletes the previous two characters. (in 2024.2, this ignores the delete key and types whatever key you pressed)
Holding down alt instead of shift will add 1 line break or remove 1 linebreak instead of 2. (in 2024.2, this does nothing at all)

Note: these issues also apply to the bug reporter fields!

In the new code editor, there is completely different (but possibly still unintended) behavior. Shift + enter + key types the key AND adds a line break, and shift + delete + key deletes and types the key at the same time.

### Steps To Reproduce
Using the OLD code editor, hold down shift + enter, and then press any key. Then, hold down shift + delete, and press any key.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[f2cd8509-ac1e-4f8f-acd9-2e7f68437d98](https://api.gamemaker.io/api/github/downloads/f2cd8509-ac1e-4f8f-acd9-2e7f68437d98)

**Comment by KormexGit** [comment]
Messing around with this more, holding shift isn't actually necessary, it happens just from holding enter or delete and then pressing some other key.

**Comment by KormexGit** [comment]
This also applies to ctrl + x, pressing another key while holding it will trigger it again

**Comment by gnysek** [comment]
Happens for delete/backspace to me. It deletes 2-3 characters sometimes, but I'm not able to find a way to reproduce it other than just writing code and using those keys.

**Comment by SmithTom6304** [comment]
This was occurring when holding a hotkey (ie. `Enter` or `Delete`) and then pressing another key while the hotkey was held, which would re-trigger the hotkey.
The majority of these cases should now be fixed. This issue can still occur in the following cases:
- `Enter` is pressed first (and held), and then `Shift` is pressed. Pressing `Shift` will cause an extra line to be added, which should not occur.
- Pressing and holding`Tab` will cause the next gadget to be selected, but pressing another key after will cause the flow to be moved a second time. This should not occur.

These are going to require more involved fixes, so I'm going to split them into separate tickets.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.551  Runtime v2024.400.0.568, thanks.
