### ISSUE TITLE
Code Editor 2: Problems with existing projects that had CE1 instances open

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#5562]
### Description
When I have a pre-existing project that had CE1 tabs open, then opening that project with CE2 enabled will still open the CE1 tabs. Also, the CE1 tabs won't be able to save anything. I'd need to close and reopen the tabs to use the proper CE2 tabs instead.

Instead, the CE1 tabs should be closed or converted to CE2 tabs.

NOTE: I had "Open scripts in a full screen editor" and "Open linked scripts as tabs of the same window" options enabled in Text Editor preferences.

### Steps To Reproduce
1. Disable Code Editor 2 in Preferences from GM home.
2. Open some project.
3. Open a bunch of script tabs in that project.
4. Close the project.
5. Enable Code Editor 2 in Preferences.
6. Open the same project.
7. See that the old CE1 tabs are still there, and that you can't save any change in them.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[08683fa8-78dc-4640-9ed4-5a9973f0c43f](https://api.gamemaker.io/api/github/downloads/08683fa8-78dc-4640-9ed4-5a9973f0c43f)

**Comment by yyalansavage** [comment]
CE1 tabs from restored layout are closed when CE2 is enabled, and vice versa - as both cases have some issues
