### ISSUE TITLE
IDE: Old layout file being used if new project with same name as a previous project is used

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#5564]
### Description
If a user had assets open in a project, then deleted this one and then at some point creates a new project with the same name, then the IDE will initially open the project with the previous version's layout. This can mean a tab for a script is shown but this is blank and there are no scripts currently in the project.

This can sometimes cause the ide to become stable.

### Steps To Reproduce
1. Create a blank project
2. Add a script
3. close the IDE with this script still open
4. Delete the project
5. create a new blank project with the same name
6. notice the open blank script tab

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[4734e7ba-8198-497c-8284-0c2d184f4dcd](https://api.gamemaker.io/api/github/downloads/4734e7ba-8198-497c-8284-0c2d184f4dcd)

**Comment by yyalansavage** [comment]
I could not reproduce this RE the empty script (no script tab was opened when script was missing, and there is code specifically checking for this). Could you provide an example layout file which will cause the problem? (layout files are in AppData\Roaming\GameMakerStudio2\<user>\Layouts )

**Comment by yyalansavage** [comment]
Fixed some issues - exception in restoring missing script resources with CE2 enabled; close empty workspace tabs which can remain post layout restore (eg with full screen script tabs where script is missing)
