### ISSUE TITLE
Wrong sound play

### ISSUE THREAD

**Issue by fataliti** [YoYoGames/GameMaker-Bugs#5566]
### Description
I cant make small project so i send whole

when i playing in my game sometimes it play wrong sound and always its the same sound
so i find one stable place with the bug

oPunchingBag -> create
 ```
     var _snd = choose(
			sndBagHit1,
			sndBagHit2,
			sndBagHit3
		);
	
		playSFX(_snd, true);
```

AddUtils -> playSFX
```
function playSFX(_soundIndex, _randomPitch = false) {
	if (_soundIndex  == rmCharacterSelect) {
		trace("catch_sound", debug_get_callstack());
		return;
	}
	
	var snd = audio_play_sound(_soundIndex, 0, false);
	audio_sound_gain(snd, SETTINGS.get_sound_gain(), 0);

	if(_randomPitch) {
		audio_sound_pitch(snd, random_range(0.9, 1.1));
	}
}
```

trace message is looks like 
```
catch_sound::[ "gml_Script_playSFX:38","gml_Script_anon@2049@gml_Object_oPunchingBag_Create_0:100","gml_Object_oColliderForHits_Collision_classDMG:2",0 ]
```

### Steps To Reproduce
1. Start GameMaker
2. Run the project
3. Start the game to tutorial (Main menu -> start -> select character -> try to punch bags with QXZ or gamepad
4. See the issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[8af643db-dfb8-43c5-aaad-4a671e56d80c](https://api.gamemaker.io/api/github/downloads/8af643db-dfb8-43c5-aaad-4a671e56d80c)

**Comment by YYDan** [comment]
Guessing you figured out that this was a coding mistake, as you closed it yourself before any of us worked on it ;)
