### ISSUE TITLE
Gamemaker launch error: "unable to access the runtime feed and no local runtime installed."

### ISSUE THREAD

**Issue by MisterMirax** [YoYoGames/GameMaker-Bugs#5568]
### Description

Ever since swapping my OS to a new drive GameMaker does not launch properly. It consistently gives and error window with "Unable to access the runtime Feed and no local runtime installed. Please check your internet connection and start GameMaker again." Once I hit OK GameMaker closes. Behind the error window, the launch screen says "Unable to download RSS Feed and no local runtime installed, unable to continue." I tried installing LTS and it seems to have a similar network connection issue. 

I have tried manually downloading and placing the Runtime files where they need to be. Firewall and Virus protection have been disabled. I can access the RSS feed through Firefox. My network has not changed since the OS transfer. No proxies or VPNs are being used. GameMaker runs fine on other machines on the same network.

Edition	Windows 10 Home
Version	22H2
Installed on	‎4/‎1/‎2024
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0
Processor	AMD Ryzen 5 3600X 6-Core Processor                3.79 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/15032932/ui.log)

I don't have the Contact Us Package because I can't access the Help menu, as GameMaker crashes before the button becomes enabled.

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

**Comment by zombodotcom** [comment]
had this issue from a new install.

Issue was ipv6

turn off IPV6 on your network adapter. If you can't ping google and it tires to go to the ipv6 address thats the issue.

**Comment by spaciousmind** [comment]
> had this issue from a new install.
> 
> Issue was ipv6
> 
> turn off IPV6 on your network adapter. If you can't ping google and it tries to go to the ipv6 address thats the issue.

thanks @zombodotcom 
Had this exact issue. disabling IPV6 worked for me too!!!!

**Comment by legocris** [comment]
> > had this issue from a new install.
> > Issue was ipv6
> > turn off IPV6 on your network adapter. If you can't ping google and it tries to go to the ipv6 address thats the issue.
> 
> thanks [@zombodotcom](https://github.com/zombodotcom) Had this exact issue. disabling IPV6 worked for me too!!!!

For me too en Linux Manjaro 25. Gm beta 785.
