### ISSUE TITLE
Rename "bm_max" to "bm_screen"

### ISSUE THREAD

**Issue by XorDev** [YoYoGames/GameMaker-Bugs#5574]
### Is your feature request related to a problem?

The blendmode "bm_max" implies that it is using the maximum of the source and destination colors, when in fact it's doing a classic [screen blend](https://en.wikipedia.org/wiki/Blend_modes#Screen): `1 - (1-a) * (1-b)` or `a + b - a * b`.
Now that we can set the blend equation to max, min, subtract, etc, this makes bm_max more confusing.
[gpu_set_blendequation()](https://releases.gamemaker.io/release-notes/2024/400)

### Describe the solution you'd like

My suggestion is to rename "bm_max" to "bm_screen".  Screen blending is quite common in photo editing software and should help others immediately understand how this blend mode works.

**Comment by stuckie** [comment]
We cannot rename this due to legacy reasons, and many projects relying on it as it currently is.
