### ISSUE TITLE
In-Game: [iOS] Video can flicker if played too soon after another has ended

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#5575]
### Description

_Split off from https://github.com/YoYoGames/GameMaker-Bugs/issues/5455 (issue VI) and using the original sample project - https://api.gamemaker.io/api/github/downloads/9e9a7933-9f79-4871-9453-0169f9c10444_

The bug below still occurs in Runtime v2024.400.0.562 when testing using an iPhone XR, so updated information is as follows:

### Expected Change

Video playback should not flicker if even another video was recently closed

### Steps To Reproduce

1. Open either A or B
2. Click "Close"
3. Wait for a maximum of 2 seconds
4. Open either A or B
5. Observe that video playback flickers
6. Repeat opening and closing videos until the issue is observed
Reproduction rate: 70%

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Update: I believe 6 should now be fixed (although I was never able to reproduce this ) 8 is now a problem that using the test configuration, the video will never  play. (Running from the IDE uses the Test configuration and you can choose to manually launch it from the Xcode project this way, but all other ways of launching it should now work)

**Comment by Emc1923** [comment]
Unable to reproduce as of  IDE v2024.6.0.156  Runtime v2024.6.0.205. Closing.
