### ISSUE TITLE
"Crop Border" option in texture groups

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#5576]
### Is your feature request related to a problem?

It would be nice if there was a way to leave some "whitespace" on sprites without having to manually crop each one to the desired size. 
One use-case for this is using an outline shader on sprites. I'd like every sprite to be cropped tight, but if it's cropped all the way in, then shaders don't draw outside the size of the sprite being drawn, so I need to manually crop/trim each sprite to make sure there's e.g. 1 pixel of white/transparent space around it.

### Describe the solution you'd like

I'd propose an option to specify "whitespace" (crop border) in Texture Groups connected to the "Automatically Crop" option.

Here's a mock-up:
![crop border option](https://github.com/YoYoGames/GameMaker-Bugs/assets/61194078/19168164-5c33-4b8a-8f55-a3ed6ee4e08e)

### Describe alternatives you've considered

a less helpful, but still nice feature would be an "auto trim" image editor option that allows you to specify a border, so users could do the above manually a little easier.

**Comment by rwkay** [comment]
The border size on the texture group is exactly what you describe - a border around each sprite for exactly this purpose

**Comment by stuckie** [comment]
Closing as above

**Comment by AvioxArcade** [comment]
That's not quite what I meant.

I don't only want to add whitespace to the texture page between sprites, I was looking for a way to automate adding it to the sprite & UV data too, so shaders can utilize that whitespace.

Currently, if you draw a sprite with a shader, the shader can't draw anything outside of the sprite canvas size without using a surface (or maybe draw_sprite_general if that'd work) no matter how big the borders are in the texture page.

Thanks for considering. It's fine if this doesn't fit the paradigm, just reporting a pain point.
