### ISSUE TITLE
Code editor 2: Debugger will not show code changes if it was already open when the changes were made

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5577]
### Description
If you run the game in debug mode to make the debugger tab appear, and then make some changes with CE2 and run the debugger again without closing the tab, the debugger will still show the old code from before the edits.

### Steps To Reproduce
Add a breakpoint to some code. Run the debugger. Close the game, but do not close the debugger tab. Add some more code below the breakpoint. Run the debugger again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6c8ac161-bd7c-4b3d-ab26-44dece4d224d](https://api.gamemaker.io/api/github/downloads/6c8ac161-bd7c-4b3d-ab26-44dece4d224d)

**Comment by KormexGit** [comment]
The IDE gave an error when I first tried to send this report, and said to try again. Looks like it ending up sending this initial report (which it said couldn't send due to a gateway error or something) anyway. That's why there's two of this same report. I see the bot didn't add the ide-bug tag to this one, so something did still go wrong.

**Comment by YYDan** [comment]
No worries - ta!
