### ISSUE TITLE
In-Game: [HTML5] string_split() optional third argument being left empty causes a crash

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5593]
### Description
Execute this line (third argument skipped) in windows:
```
var sa = string_split("0:test", ":", ,1);
```
and all is good, you receive an array with 2 entries.

Run it in HTML and you receive a crash
"Unable to convert undefined to a number"

but when you supply the third argument:
```
var sa = string_split("0:test", ":", false,1);
```
it works in html.

### Steps To Reproduce
* See above

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[070be2a4-6ee6-43d5-ad6b-d92c70bc401b](https://api.gamemaker.io/api/github/downloads/070be2a4-6ee6-43d5-ad6b-d92c70bc401b)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.400.0.556  Runtime v2024.400.0.571
