### ISSUE TITLE
Start Page: Error message shown when a Template fails to download should be more helpful

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#5596]
### Description

On the Start Page, the error message which is shown whenever a Template fails to download should be more helpful in telling users that this is likely a permissions issue that they need to fix themselves. Currently, we show a vague "arithmetic operation" error message, which then makes it look like there is a bug or web server issue that they need to contact us about fixing for them.

![gamemakererror](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/dcfc5c0f-689b-4dd7-9ad9-2322af0f221f)

This is also logged to the ui.log - e.g.:

```
[07:51:01:987(614c)] Download op:5 file url: https://api.yoyogames.com/api/2/download?package_id=com.gamemaker.spacerocks&version=1.0.0&session=
[07:51:04:433(614c)] download failed for https://api.yoyogames.com/api/2/download?package_id=com.gamemaker.spacerocks&version=1.0.0&session=
[07:51:04:434(614c)] Arithmetic operation resulted in an overflow.
```

### Expected Change

That error message should instead say something like "Unable to download the template. Please check your firewall permissions for GameMaker and then try again."

### Steps To Reproduce

Not reproduced, but assume something like the following would be very reliable:

1. Use a firewall to block access to https://api.yoyogames.com/
2. Ensure that you don't have any existing Templates downloaded in ProgramData (of if you do, remember to avoid using them for testing this!)
3. Start GameMaker and reach the Start Page as per normal
4. Try to download any Template off the Start Page as part of creating a new project 
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified done as of Beta IDE v2024.600.0.562 Beta Runtime v2024.600.0.580

![Image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/dcd859a5-b852-4f44-b69c-d102e7ca2151)
