### ISSUE TITLE
Asset Browser: Delete and Rename hotkeys can stop functioning after other inputs

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#5601]
### Description

In the Asset Browser, the delete/rename hotkeys can stop functioning after other inputs or simply over time using the Asset Browser.

It appears duplicating an asset, or creating new ones, can cause the hotkeys to work again but only for one use.

https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/9f097783-916c-48cb-b350-705280506e5d

[Contact Us Package](https://drive.google.com/file/d/125o_x13WOrIYOHruAbPL_Pw2BXkdT1lN/view?usp=sharing)

Tested using IDE v2024.400.0.547  Runtime v2024.400.0.566

### Steps To Reproduce

1. Start GameMaker and create a project
2. Create multiple of an asset via the hotkey for it
3. Delete a few of the newly created assets 
4. Attempt to delete or rename an asset via the hotkey
5. Observe the issue
6. Duplicate one of the assets
7. Attempt to delete or rename an asset via the hotkey and observe that this works
8. Attempt the same again
9. Observe the issue

Repro: Only Sometimes

1. Start GameMaker and create a project
2. Create, delete and duplicate multiple assets in the Asset Browser
3. Attempt to delete or rename an asset via the hotkey
4. Observe the issue

Repro: Only Sometimes

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by SmithTom6304** [comment]
Found a reliable repro for this: if capslock or numlock is enabled, then F2 and Delete on assets will not work until some other hotkey is triggered (like Duplicate). They will then work until capslock/numlock is disabled and re-enabled again.

**Comment by SmithTom6304** [comment]
Fixed - this was occurring because CapsLock / NumLock was mistakenly being used to build a hotkey chord from. We should now be ignoring those modifiers as expected.
