### ISSUE TITLE
Arrow Keys do not work in the Instances list in Inspector for an Instance Layer

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#5602]
### Description
I cannot use the arrowkeys to navigate the the list of instances.

### Steps To Reproduce
1. Click on a layer
2. Pick an instance
3. Try to use up/down keys to skip through them.

[a1a475e2-7590-4327-9497-51fd7bdca3cb](https://api.gamemaker.io/api/github/downloads/a1a475e2-7590-4327-9497-51fd7bdca3cb)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
