### ISSUE TITLE
Texture groups: changing Custom Options won't force the asset compiler to rebuild the textures

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5603]
### Description
When using Custom Options for texture groups (ie with the Texture Compression extension), changing the options won't force the compiler cache to be rebuilt.

Among other things, this means that the default Texture Compression project, which is set to use the ASTC compression, won't work on Windows and will continue not working on Windows even after you change the options to BCN and re-run the game.

### Steps To Reproduce
1. Load the Texture Compession demo on Windows
2. Make sure each group's Custom Options are set to `ASTC something`
3. Run the game
4. It doesn't run
5. Change each group's Custom Options to `BCN something`
6. Run the game
7. It still doesn't run
8. Clear the compiler cache
9. Run the game
10. It runs now
11. Set each group's Custom Options back to `ASTC something`
12. Run the game
13. It still runs, even though it shouldn't

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.547 Runtime v2024.400.0.566

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[522e9232-a936-408b-aa04-5e38b2d2c0db](https://api.gamemaker.io/api/github/downloads/522e9232-a936-408b-aa04-5e38b2d2c0db)

**Comment by stuckie** [comment]
Should use the texture compression name as part of the cache.

**Comment by DragoniteSpam** [comment]
Probably the Texture Group Format option too, because it seems to (intend to) ignore the compression options if you switch it back to BZ2.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/f2eb2697-12a8-492c-b35b-fb3e7db4ebad)

**Comment by stuckie** [comment]
Fixed the original issue ( annoyingly before that extra one above ) however, from the code, it looks like it is handling texture group format changes.. if it is not - outside of the custom options issue - please file a bug and we can address that separately.

Thanks!

**Comment by DragoniteSpam** [comment]
You mean like #5604?

**Comment by stuckie** [comment]
No, that's a different issue; that's the platform not supporting the texture compression options rather than the texture cache not being reset when the texture compression is changed... which I assume is what the additional issue is?

**Comment by DragoniteSpam** [comment]
Yeah, basically. If it's still a problem in the next beta I'll file it separately

**Comment by cameron-home** [comment]
Original issue raised has been verified fixed in IDE v2024.4.0.137  Runtime v2024.4.0.168
