### ISSUE TITLE
Texture compression: running the game with incompatible texture compression settings produces an incomprehensible error message

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5604]
### Description
When you run a game containing textures built with settings that don't work on your target platform (eg ASTC on Windows), the game crashes on start with a generic error message.

    C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.400.0.566/windows/x64/Runner.exe exited with non-zero status (-1073741819)

Having an actual error message would be helpful.

### Steps To Reproduce
1. Open the texture compression demo on Windows
2. Make sure each group's custom options are set to `ASTC something`
3. Run the game
4. -1073741819 (C0000005)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.547 Runtime v2024.400.0.566

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[fbb66b9f-fefb-4c58-ba23-04c1e0c04b5f](https://api.gamemaker.io/api/github/downloads/fbb66b9f-fefb-4c58-ba23-04c1e0c04b5f)

**Comment by YYBartT** [comment]
Added a warning note under the new "Texture Compression" section in the manual that mentions that an error will be shown in the output in case of incorrect settings.

**Comment by cameron-home** [comment]
Verified in IDE v2024.4.0.137  Runtime v2024.4.0.168
