### ISSUE TITLE
Room editor: select from any layer mode is now cancelled every time you select an object in 2024.4 beta

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5605]
### Description
I previously reported #2463 where select from any layer mode would get cancelled when you shift click to select an object. This was supposedly fixed, but it wasn't and it's actually worse now: select from any layer mode will get cancelled every time you select anything with it just by clicking normally. When shift clicking, it now gets cancelled when you release shift instead of cancelling when you select something.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/5b5bd2d7-0c9c-4263-874f-2c686610b047

### Steps To Reproduce
Use select from any layer mode and select any instance.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[48ce373f-ecb2-4874-9594-dedfed74fd72](https://api.gamemaker.io/api/github/downloads/48ce373f-ecb2-4874-9594-dedfed74fd72)

**Comment by SmithTom6304** [comment]
Sorry about that, there was an issue with my previous fix.
SelectFromAnyLayer should no longer cancel after selecting an instance, or after releasing shift.

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.4.0.134  Runtime v2024.4.0.166, thanks.
