### ISSUE TITLE
Variable Definitions: Inherited Asset-type definitions in child objects show their parent's values in 2024.400 if project was imported from 2024.2

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5606]
### Description
There appears to be an issue with inherited variable definition variables, specifically of the "asset" type, only when overwritten on the child object and imported from a project in 2024.2.
The overwritten asset variable will show the parent's value instead of the child's overwritten value. The actual value of the variable is still the child's value from before if you use it in code, even though it displays in the IDE as the parent's value. The screenshots and steps probably explain it better than any description I could write.

On 2024.2:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e1e14ac7-5f03-4204-9540-43ff99aa293a)

Exact same project, opened in 2024.4:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/d26172c6-21df-4733-a737-a6660c3ef827)

### Steps To Reproduce
1. Create a project in 2024.2
2. Create two objects, "Parent" and "Child"
3. Create two sprites,  "parentSprite", and "childSprite".
3. Create a variable in variable definitions on "Parent", and make it the asset type. Assign "parentSprite" to it
4. Make "Child" a child of "Parent"
5. Overwrite the variable on "Child" and assign "childSprite" to it instead
6. Save and close the project
7. Open the project in 2024.4
8. Open up "Child". It's variable will show up as "parentSprite" instead of "childSprite"
9. If you open up the project in 2024.2 again, it will show up as "childSprite" still

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b5f70173-f199-41ab-b192-0e57d77858dd](https://api.gamemaker.io/api/github/downloads/b5f70173-f199-41ab-b192-0e57d77858dd)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.400.0.556  Runtime v2024.400.0.571
