### ISSUE TITLE
Room Editor: Deleting specific pre-2024.400-created child instances and then undoing the delete transforms them into their parent object

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5607]
### Description
This is a really weird one. I have not been able to come up with setup steps that make it start happening in a fresh project, so I instead created a branch of my main project (where it's happening) and deleted as much as I could while still having it happen. A few specific instances of a few objects will, when deleted and them un-deleted with ctrl+z, transform into their parent object. This appears to be related to my previous report #5606, as removing the variable definitions variables from the parent, or deleting the assets used in variable definitions, will make the bug stop happening. Unlike that report however, I am unable to get this one to happen on demand with newly created objects.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/91ce9fa1-dc4b-4d00-804f-7f47f4012863

This issue does not occur in 2024.2.

### Steps To Reproduce
1. Open up the attached project
2. Open up "Testroom"
3. Select all of the objects on the objects layer
4. Delete them
5. Press ctrl+z
6. The instances on the right will get put back as they were before, no problem (these are new instances I just placed, in 2024.4)
7. The instances on the left will transform into their parent, pNPC, instead of getting put back as the instance they were

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b4a16283-ab98-486f-a3ab-bfb8a9769c05](https://api.gamemaker.io/api/github/downloads/b4a16283-ab98-486f-a3ab-bfb8a9769c05)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.400.0.556  Runtime v2024.400.0.571
