### ISSUE TITLE
Start Page: Let's Go button is always highlighted 

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#5616]
### Description

When creating a project on the Start Page, the Let's Go button for creating it is always highlighted like it's being hovered over.

https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/fc6fba0b-d089-408c-93f6-2598f9e3e9bf

[Contact Us Package
](https://drive.google.com/file/d/1W1hEatN-1GFqZLVqdCmYt2vGq3XWkOlj/view?usp=sharing)
Tested using IDE v2024.400.0.549  Runtime v2024.400.0.567

### Expected Change

The button remains unhighlighted until the mouse hovers over it.

### Steps To Reproduce

1. Start GameMaker
2. Select New > Game > Blank Game
3. Observe the issue with the Let's Go button on the right

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
This was intentional to differentiate the "go" button and cancel buttons; updated after discussion with MarkT so go button now has a hover state
![startpage-go-button](https://github.com/YoYoGames/GameMaker-Bugs/assets/8818217/730bbe6e-b92c-4d22-acbb-a4097fa7bdcb)
