### ISSUE TITLE
Code Editor 2: Various issues with local Replace in a script 

### ISSUE THREAD

**Issue by yyalansavage** [YoYoGames/GameMaker-Bugs#5618]
### Description
CTRL+F from a script window opens the local search/replace dialog. 
i) Selecting Replace All icon, does replace all occurences, but if you undo the changes then the text becomes scrambled
ii) Selecting Replace Next icon, will replace the next occurrence *after* the highlighted one; repeatedly pressing will replace every second occurrence.  
Additionally, if there are multiple occurrences on a single line and replaced text is of different length, the replacements occur in the wrong positions and text becomes scrambled; undoing the changes scrambles the text even more.

### Steps To Reproduce
-Open Script1 in the attached project, CTRL+F to open local search/replace window.
-Search for "fishcake" and replace with something of a different length
-i) click Replace All and then undo the change(s)
-or ii) repeatedly click Replace Next to observe various problems

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.656 Runtime v9.9.1.775

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[2e701f90-bb04-4ca6-b18a-aadadbe17770](https://api.gamemaker.io/api/github/downloads/2e701f90-bb04-4ca6-b18a-aadadbe17770)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Reopening as I appear to still be having issues in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617, i.e when replacing "fishcake" with something else and then going to file > undo, it appears to have "fishcake" before the word I replaced it with. See video below:

https://github.com/user-attachments/assets/e931c4e3-4f41-4672-8247-b2110aa36ed5

**Comment by zreedy** [comment]
Fixed once more.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
