### ISSUE TITLE
Code editor 2: Tab key does nothing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5625]
### Description
In the beta that came out today, the tab key appears to do nothing at all in CE2.

### Steps To Reproduce
Press the tab key.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[49cd8073-3f95-4f6b-8b23-86717c65afe0](https://api.gamemaker.io/api/github/downloads/49cd8073-3f95-4f6b-8b23-86717c65afe0)

**Comment by KormexGit** [comment]
I am also having issues with the delete key doing nothing, as well as ctrl+c, ctrl+x, and ctrl+v. These are only not working in my main project though, not in a sample project

**Comment by zreedy** [comment]
This is fixed in the current public Beta. This was missed when closing tickets related to Hotkeys.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.563  Runtime v2024.600.0.580, thanks.
