### ISSUE TITLE
Ctrl + shift + f to bring up search replace now defaults the cursor to "replace" instead of "search"

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5629]
### Description
In the latest beta, ctrl + shift + f now puts the cursor into the replace field instead of the search field by default. This is different from before, and makes the searching workflow awkward.

### Steps To Reproduce
Press ctrl + shift + f, and type something. It will type into the replace field.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[fd045a9d-d523-42e4-a6c4-22f69f9248d1](https://api.gamemaker.io/api/github/downloads/fd045a9d-d523-42e4-a6c4-22f69f9248d1)

**Comment by SmithTom6304** [comment]
Should now be fixed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.4.0.134  Runtime v2024.4.0.166, thanks.
