### ISSUE TITLE
Code editor 2: CE2 can be opened while disabled if turned off during initial project load

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5630]
### Description
With CE2 on a large project, it often takes a while for things to load in. If you do something like middle click a function to jump to definition, it won't do it immediately since it's still backed up trying to load things. If you go into preferences and disable CE2 during this time, it will still pop up the CE2 window after it finishes processing.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e12c05c7-3950-470a-9292-eed85846ac46

### Steps To Reproduce
In a large project, middle click on a function immediately after opening the project. Quickly open up preferences and disable CE2. Wait a while, and a CE2 window will pop up even though it was just disabled.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e734a532-415a-4c7f-9b9f-53e8cae05a7c](https://api.gamemaker.io/api/github/downloads/e734a532-415a-4c7f-9b9f-53e8cae05a7c)

**Comment by KormexGit** [comment]
This one should be fixed by the change in 2024.8 that makes you restart GM when turning CE2 on or off

**Comment by zreedy** [comment]
Unable to reproduce.
