### ISSUE TITLE
Timeline: Delete shortcut key doesn't work to delete moments 

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#5633]
### Description

When trying to delete a timeline moment in the editor using the Delete shortcut key, nothing happens. Confirmed on  Windows and Mac IDEs.

### Expected Change

Delete shortcut should work.

### Steps To Reproduce

1. Start GameMaker and create/import project.
2. Create a Timeline and add a moment.
3. Use the delete shortcut key and see the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Monterey

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.579  Runtime v2024.600.0.605 on win

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.600.0.579 Runtime v2024.600.0.605 on mac. Closing.
