### ISSUE TITLE
Code Editor 1: Pressing a modifier key while `Enter` or `Backspace` is held will cause the hotkey to execute a second time

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#5634]
### Description

**Summary:** In CE1, if `Enter` or `Backspace` is held and then a modifier key is pressed afterwards, the hotkey will execute a second time.

IDE v2024.400.0.543 Runtime v2024.400.0.562

### Expected Change

The hotkey should execute when `Enter` or `Backspace` is pressed, but not again when a modifier is pressed.

### Steps To Reproduce

1. Start GameMaker
2. Open the Code Editor
3. Press and hold enter
4. See a line break is added
5. Quickly press a modifier key, before the enter key starts to repeat
6. See an extra line break is added

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Ventura

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Should now be fixed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.400.0.556  Runtime v2024.400.0.571, thanks.
