### ISSUE TITLE
Hotkeys: Pressing a key while `Tab` is held will cause the flow to move twice

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#5635]
### Description

**Summary:** In IDE v2024.400.0.543 Runtime v2024.400.0.562, pressing any key while `Tab` is held will cause the gadget flow to be moved a second time.

### Expected Change

Nothing should happen when pressing a key while `Tab` is held.

### Steps To Reproduce

1. Start GameMaker
2. Select a gadget
3. Hold tab
4. See the gadet flow is moved
5. Press any other key
6. See the flow is moved again

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.563  Runtime v2024.600.0.580, thanks.
