### ISSUE TITLE
Networking HTML5 

### ISSUE THREAD

**Issue by Stress0hneGrund** [YoYoGames/GameMaker-Bugs#5637]
### Description
hey, i found an issue with the current game maker version (v2024.2.0.132 Runtime v2024.2.0.163)

establishing a network connection to a ws works BUT after the handshake no incoming packets/outgoing packets happen
(the browser tab also freezes kinda after the handshake so reloading doesnt work without doing it in a new tab, even closing the current tab takes seconds to actually close)

### Steps To Reproduce
tried to fix it in every way, it only worked after changing to the current game maker beta version for me (didnt change code just game maker version)
went back to the standard build and it doesnt work again 
back to the beta version and it works again
its definitly not my code, as it works in the beta but not in the standard build 
this bug occours only after you send the handshake from the server to the client

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6b8fde87-daf6-4c03-88b8-0681df362eca](https://api.gamemaker.io/api/github/downloads/6b8fde87-daf6-4c03-88b8-0681df362eca)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
