### ISSUE TITLE
[HTML5] `Clickable` type missed in typed handles overhaul

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5640]
### Description
The HTML5-only type that I didn't know existed until minutes before finding this issue, `Clickable ID`, is still a `number` according to `typeof`.

Of note, this technically is a bug in the regular runtime too since `clickable_add` still returns an (untyped, numerical) index even if it isn't supported.

### Steps To Reproduce
**Example Code:**

```gml
var blah = clickable_add(0, 0, sprite_get_tpe(sTestSprite, 0), "javascript:alert('hi')", "_top", "");

show_message(typeof(blah)); // "number"
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Mac 13.5

### Which platform(s) are you seeing the problem on?
HTML5, macOS

[2ef1a021-2807-4e76-be46-c2ec4ff45a38](https://api.gamemaker.io/api/github/downloads/2ef1a021-2807-4e76-be46-c2ec4ff45a38)

**Comment by stuckie** [comment]
This is not planned.

**Comment by thennothinghappened** [comment]
Is that as this type is so obscure anyway? I could definitely see this functionality being deprecated as it doesn't seem to add much by existing that can't be far better served by an extension
