### ISSUE TITLE
`clickable_add` returns a positive index outside HTML5

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#5641]
### Description
This is directly related to my other report #5640, but on the normal runner trying to use this HTML5-only functionality still returns a postive index (always index `0` though).

When other `_add` functions fail usually they either return index `-1`, or throw. This does neither which seems strange - `clickable_exists(thing)` works too, always returning `false`, so that all leads me to assume they've been implemented as stubs in the normal runner to match the HTML5 one, rather than actively returning some sort of error as they should do.

### Steps To Reproduce
**Example Code:**

```gml
var blah = clickable_add(0, 0, sprite_get_tpe(sTestSprite, 0), "javascript:alert('hi')", "_top", "");

show_message($"Index: {blah}, valid: {clickable_exists(blah)}"); // "Index: 0, valid: 0"
```

Virtually the same as my other report, but also shows `clickable_exists()` here.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.543 Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?
Mac 13.5

[750c636c-cca9-4c6a-a564-7c3439605bbf](https://api.gamemaker.io/api/github/downloads/750c636c-cca9-4c6a-a564-7c3439605bbf)

**Comment by stuckie** [comment]
This is as designed.
