### ISSUE TITLE
Code Editor 2: "Open the Manual" hotkey does not work if caret is on blank space

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#5642]
### Description
If a user uses the default or redefined "open manual" shortcut when a build-in function is highlighted then the expected manual page opens. If a blank link is selected then the manual home page does not happen.

Both work in CE1

### Steps To Reproduce
1. Open the IDE with CE2 enabled
2. Go to redefine keys and change "open manual"
3. Open a project that uses built-in functions or create a new project and script with the word "string" typed
4. highlight the word and press the shortcut, the page will open 
5. select a blank line, repeat, no page opens
6. Switch to CE1 and repeat 4 and 5, they will work as expected

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.550 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[d2b3e741-b4e2-4ad9-950a-2929f1bda998](https://api.gamemaker.io/api/github/downloads/d2b3e741-b4e2-4ad9-950a-2929f1bda998)

**Comment by thennothinghappened** [comment]
You also hit this issue trying to use middle click to bring up the manual or go to definition. If the caret is on whitespace it won't work, and just moves the cursor there, making you have to hit it a second time.

**Comment by caitlinrmcintyre** [comment]
Reopening as this is still broken for me in IDE v2024.600.0.558  Runtime v2024.400.0.571.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.560  Runtime v2024.600.0.577, thanks.
