### ISSUE TITLE
Wrong warning for surface_set_target

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#5647]
### Description

This warning displayed for surface_set_target() is misleading. It looks like a copy/paste from surface_reset_target(). I suggest "this function" to be replaced by "surface_reset_target()" in that specific page to avoid confusing people learning about surfaces.

"If you have not previously set a render target with the function [surface_set_target], using this function will silently (i.e. without any error messages) end all further code execution for the event."

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FSurfaces%2Fsurface_reset_target.htm%23h

**Comment by thennothinghappened** [comment]
I'm a little confused actually here because to me the `surface_reset_target()` warning is actually completely wrong. Attempting to reset the target without one set actually throws an error ("Unbalanced surface stack"), and does _not_ silently end the event like it claims.

**Comment by Patchy-DaYo** [comment]
I agree. It either has to be removed or the wording changed to refer to the example just above it.
