### ISSUE TITLE
Live Wallpaper: Setting Mouse Subscription causes mouse position bugs in Windows target

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#5648]
### Description

As soon as you set `wallpaper_set_subscriptions(["desktop_mouse"]);` when you test your wallpaper in the normal Windows target the normal mouse input and the subscribed mouse input fight with each other and the mouse coordinates become unpredictable. 

You can see this if you use a Draw Event and just write:

draw_circle(mouse_x,mouse_y,10,false);

As you move your mouse around the circle will jump back and forth between two positions. 

### Steps To Reproduce

1. See above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.4.0.134  Runtime v2024.4.0.166.
