### ISSUE TITLE
Ctrl + f does not put cursor into the "find" field unless pressed twice

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5653]
### Description
There's a good chance this is the same source issue as #5629 (and already fixed interally if it is), but I wanted to report it anyway just in case it isn't. When you press ctrl+f to bring up the local find/replace menu, the typing cursor does not go to the find box. It doesn't stay on the code either, so just pressing ctrl+f and typing appears to not type anywhere at all. If you press ctrl+f again while the window is already open, it will move the cursor properly.

### Steps To Reproduce
Press ctrl + f and try to type something.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c1f3ed9c-8d20-4e42-b064-683e428d33a1](https://api.gamemaker.io/api/github/downloads/c1f3ed9c-8d20-4e42-b064-683e428d33a1)

**Comment by SmithTom6304** [comment]
Looks like this hasn't been fixed by https://github.com/YoYoGames/YoYoStudio/commit/755cbfd82e265271fd7e5652243560336d47b949, but I imagine it'll be the same cause.

**Comment by SmithTom6304** [comment]
Fixed - similar to #5629, just needed to apply the same fix in a different place.
