### ISSUE TITLE
Creating a new key in the sequence editor should automatically selected the new key.

### ISSUE THREAD

**Issue by AndRayNow** [YoYoGames/GameMaker-Bugs#5655]
### Is your feature request related to a problem?

This small change increases the speed of work by 1 click and reduces the likelihood of forgetting to allocate a new key.

### Describe the solution you'd like

When a new key is created by clicking “Record a new key” or “Toggle key on”, the newly created key should be _automatically selected_. Now it has to be additionally highlighted after creation, which only increases the probability of forgetting to highlight it and adds one extra action.

**Comment by yyalansavage** [comment]
Added a fix to select the new keys as requested

**Comment by Emc1923** [comment]
Verified as of IDE v2024.600.0.560 Beta Runtime v2024.600.0.577
