### ISSUE TITLE
Code editor 1: Ctrl + Q doesn't work in 2024.4

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5663]
### Description
In the current beta, pressing ctrl + Q doesn't do anything at all. I tried to use it for generating a JSdoc header, and nothing happens. Doing the same thing in 2024.2 works.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/fc420e92-9e77-4653-9a97-0f7313ab62a0)

This only applies to the old code editor. It appears to still work fine for the new code editor.

### Steps To Reproduce
1. Start GM and create a new project using CE2
2. Add a new Object event or Script
3. Type in a new function declaration (doesn't need any content inside the braces
4. Click on the function name to get the Feather prompt in the gutter
5. Press Ctrl+Q and observe the tooltip to generate a JSDoc header will appear
6. Click on the Feather tooltip itself in order to "use it" and observe no JSDoc is actually added to the code

### Expected Result

The command for filling in a JSDoc header is shown:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/91cfa42f-2116-4267-9131-0ddf71d77dac)

Clicking that gives you new JSDoc comments:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/d6a5dbef-499c-4431-a747-1d1908f6a4c9)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.549 Runtime v2024.400.0.567

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[38745c22-5a1d-40d9-96a0-055fa2948be7](https://api.gamemaker.io/api/github/downloads/38745c22-5a1d-40d9-96a0-055fa2948be7)

**Comment by YYDan** [comment]
I get the exact opposite in IDE v2024.400.0.551 Runtime v2024.400.0.568 in that CE1 works and CE2 does not.

**Comment by KormexGit** [comment]
For me on CE1, clicking it does work, but pressing ctrl + Q does not.
Here's a video of me mashing ctrl + Q, then clicking at the end

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e51df777-a9ee-45a4-9b5c-79cfa00ff670

**Comment by YYDan** [comment]
Yeah, okay, so the version I am using has multiple fixes for hotkeys not working properly (not specifically Ctrl+Q - more like "knowing that Ctrl and Q are a hotkey and need to fire together, rather than do Ctrl and then Q" ;) ).

However, yes, this newer Beta I have (and indeed an internal 2024.4) both work exactly for CE1 as IDE v2024.2.0.132 Steam Runtime v2024.2.0.163 does for me right now.

CE2 needs a fix for 2024.6 ;)

**Comment by KormexGit** [comment]
Issue is persisting for me on CE1 in the public beta that was released today 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/82c2ece8-359b-440f-837e-9fa863b38df4)
Menu does not appear when pressing ctrl+Q on a function or on a feather error line, while doing the same thing on 2024.2 with the same code does work

**Comment by SmithTom6304** [comment]
I can reproduce this if CE2 has been enabled previously in the instance. If CE2 is never enabled, this seems to work correctly. I imagine the CE2 shortcuts are not being unregistered when it is disabled, and so they are stealing the input.

**Comment by Emc1923** [comment]
Note on Mac I get this issue with CE1 without having enabled CE2 in the project as of Beta IDE v2024.400.0.556 Beta Runtime v2024.400.0.571.

**Comment by SmithTom6304** [comment]
Was incorrect in my comment above - the shortcut is unregistered when _any_ CE1 text editor panel is closed, and is only registered for the first panel opened.
[I have a potential fix](https://github.com/YoYoGames/YoYoStudio/commit/8f0c55987431f92da1477b9fbc6a60f10028e8eb), although after making it I had the IDE attempt to manipulate the UI on a background thread (I only had this occur the once however - it could be unrelated).
Either way, it needs some more time to investigate so we're not going to risk putting this into the initial 2024.04 release.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.603  Runtime v2024.800.0.625
