### ISSUE TITLE
Startup: "Processing User" stage takes longer than expected, so starting additional IDE instances is also slow

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#5671]
### Is your feature request related to a problem?

The problem is, the "Processing User" step of the startup of GMS takes many seconds (10+), which makes it extremely awkward to work with multiple instances, if you "just want to quickly lookup something in another project"

I have a quite above-average machine (3070RTX, 32GB RAM, Two M.2 disks and a very clean windows installation - i am purist).
My internet line is 500MBit and speedtest reflects exactly that.

Still, it takes so long.

### Describe the solution you'd like

I can understand, the _first_ GMS session takes a bit time for handshake, account login, doing only-god-knows-what with opera and other web destinations, but when i click the `New IDE` menu item, this session token or whatever you use, should be reused and this entire login-step should be skipped.

Please either build some inter-process communication or send a hidden commandline-argument to the new session when launched from "New IDE", so this step can be skipped.

When we are in the course (I hold gamedev courses, with and without raptor library), we have so many breaks in the flow, when the participants need to fire up a second or third GMS, depending on the lecture, we are in.

Please please please speed this up!

Thanks for reading,
Cheers
Gris

### Describe alternatives you've considered

The only alternative is waiting.

**Comment by KormexGit** [comment]
I do feel like this step used to be way faster. I remember it used to only take a second or two, now it takes about 7-10 seconds for me

**Comment by rwkay** [comment]
Fixed in 2024.6

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.568  Runtime v2024.600.0.595
