### ISSUE TITLE
Redefine Keys: Clash message only pops up when editing a command with numlock off

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#5678]
### Description

When looking into #[9952](https://github.com/YoYoGames/YoYoStudio/issues/9952) I noticed that when editing a command and choosing space, a clash message popped up. When turning numlock on and following the same steps, however, the clash message didn't appear.

### Steps To Reproduce

1. Start GameMaker and go to preferences > redefine keys.
2. Make sure numlock is off and double click a command to edit.
3. Choose a key that is used elsewhere (i.e space)
4. See the clash message appear.
5. Turn numlock on and follow the same steps and see there's no clash message.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This should now be fixed.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.400.0.555  Runtime v2024.400.0.569
