### ISSUE TITLE
Building Projects: [iOS] Allow specifying multiple languages to display in store listings

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5683]
### Is your feature request related to a problem?

When publishing iOS apps to the App Store, the store listing shows what languages the app supports. 
![chrome_Ij4ZsMzeLz](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/a86e2452-ebbc-4598-9357-849bbdba9607)

This can be achieved by editing the XCode project per Apple's documentation: https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions

However, this process is extremely tedious, as it is just a series of button clicks that has to be manually performed every time we build the game. We would like GameMaker to support ways to automate this process.

### Describe the solution you'd like

We automated this process by running a custom NodeJS script on our build server: https://forum.gamemaker.io/index.php?threads/ios-multiple-languages-in-store-listing.13584/post-618270

However, this solution requires too much overhead, and we would like a solution that is built-in to GameMaker and easily accessible for all developers.

A solution can look like this:

1. In the GameMaker IDE's iOS Game Options, user can specify the iOS language that their app supports.
2. GameMaker will generate the XCode project that contains the `*.lproj/InfoPlist.strings` file based on the language selected and their corresponding language code https://www.ibabbleon.com/iOS-Language-Codes-ISO-639.html
3. The `*.pbxproj` file should include the  `*.lproj/InfoPlist.strings` files and the `knownRegions` field should also include the language codes

### Describe alternatives you've considered

This can also be achieved through `Compiler Batch Files / Scripts` in an extension, though the script will have to parse the `*.pbxproj` file, which is non-trivial.

**Comment by cameron-home** [comment]
@jackerley Is this still planned for August?

**Comment by jackerley** [comment]
[iOSLanguageTest.zip](https://github.com/user-attachments/files/16469308/iOSLanguageTest.zip)
Test project added that shows how this should be used. The project has two configs Default and AsianConfig, and shows different languages in each plus an overridden English in the AsianConfig. The correct languages should show up in the generated Xcode project and the correct InfoPlist files should be added to the Xcode project

**Comment by cameron-home** [comment]
Correct languages present and InfoPlist working for both configs as expected in IDE v2024.800.0.604  Runtime v2024.800.0.627

**Comment by gurpreetsinghmatharoo** [comment]
This is now documented here: https://help.gamemaker.io/hc/en-us/articles/21004164644509-iOS-Specifying-supported-languages-in-store-listings

**Comment by shichen85** [comment]
TY all for adding this feature!

**Comment by SamTHodson** [comment]
Also verified in Beta IDE v2024.800.0.618  Runtime v2024.800.0.642, alongside the new support guide
