### ISSUE TITLE
[Docs] `struct_remove` incorrect second argument type

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5697]
### Description

Documentation error, see the second arguments type use for both.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/f23c0302-880a-40bc-a541-7c6dbfadfb64)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/38c8a918-1d41-4605-8d6a-6e5462c0384d)

Note this does not mean that 

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Could this be a duplicate? The current internal branch doesn't have this bug in it... this seems to have already been solved.

**Comment by mgeddesGM** [comment]
@gurpreetsinghmatharoo this has not been brought over to B or M
https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Fvariable_struct_remove.htm&rhsearch=struct_remove&rhhlterm=struct_remove

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Fvariable_struct_remove.htm&rhsearch=struct_remove&rhhlterm=struct_remove

**Comment by DiasFranciscoA** [comment]
there was a reason for it to be marked as `Any` because you can actually pass it any type of variable but as the description explains it will all render down to a string... so you can pass it - a string, a real, a struct, an array - whatever you pass to it, it will call string(...) on it (hence the **as a string** note in the description)

**Comment by DiasFranciscoA** [comment]
This got change to String and other `struct_*` got the same fix

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
