### ISSUE TITLE
Inspector: F2 to rename an asset in the panel actually renames the Inspector

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5698]
### Description

Similarly to https://github.com/YoYoGames/GameMaker-Bugs/issues/2665, when opening an asset in the inspector and trying to rename it using F2 the IDE instead focuses on the Tab name and attempts to rename the inspector tab. Will happen with any asset.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/d45e30a9-72f9-47b0-a9d8-64d5303b55b4)

### Steps To Reproduce

1. Start GameMaker
2. Create/open any project with assets
3. Open any asset in the inspector
4. Click select the name field and press F2 to rename
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Fixed - should now always rename the asset

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
