### ISSUE TITLE
Preferences: [Mac/Ubuntu IDE] The default build target for MacOS is set to 'Windows' in preferences

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5703]
### Description

The default build target for MacOS is always set to 'Windows' from Preferences > General Settings. When applying the preference to the project it won't be applied (as Windows is not available from the Mac IDE) - it would run the expected default target.

Selecting any platform not available on the Mac IDE from there (even if included in your license) won't change anything.

### Expected Change

Non-available targets should be removed from Preferences and the default target should be the OS.

### Steps To Reproduce

1.  Start GameMaker on Mac
2.  Log in with an account
3.  Go to  Preferences > General Settings
4.  See the issue

![Screenshot 2024-05-01 at 15 01 09](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/24b258b1-534a-42b1-a021-3470dc8ee5e9)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma, Ubuntu 22.04

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
It'd be worth checking the Ubuntu IDE as well

**Comment by Emc1923** [comment]
Ubuntu is the same as Mac, edited issue above.

**Comment by Emc1923** [comment]
Verified as of Beta IDE v2024.600.0.562 Beta Runtime v2024.600.0.580
