### ISSUE TITLE
Timeline Editor: Hotkey for "Change Moment" (Ctrl+Shift+E) does not work

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#5704]
### Description

In the Timeline Editor, the hotkey for "Change Moment" (Ctrl+Shift+E) does not work.

https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/7cf691f1-ba43-4660-b68d-4556653e41fd

[Contact Us Package](https://drive.google.com/file/d/18PsNV4sBR9NHx3vdeS8VwaXcj90qosUQ/view?usp=sharing)

Tested using Beta IDE v2024.400.0.556  Runtime v2024.400.0.571

### Steps To Reproduce

1. Start GameMaker and open/create a project
2. Create a Timeline
3. Add a Moment
4. Attempt to change its value via the Change Moment hotkey (Ctrl+Shift+E)
5. Observe the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.579  Runtime v2024.600.0.605
