### ISSUE TITLE
`struct_exists_from_hash()`

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5709]
### Is your feature request related to a problem?

Sister request for [struct_remove_from_hash](https://github.com/YoYoGames/GameMaker-Bugs/issues/5694)

### Describe the solution you'd like

`struct_exists_from_hash(struct, hash)`

### Describe alternatives you've considered

`struct_get_from_hash(struct, hash) == undefined`
However this relies on the fact you cant use undefined as an value at all.

**Comment by YYBartT** [comment]
Added function reference page for `struct_exists_from_hash()` to the manual.

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.560  Runtime v2024.600.0.577
