### ISSUE TITLE
Cannot input Japanese across the entire IDE

### ISSUE THREAD

**Issue by gange-satoya** [YoYoGames/GameMaker-Bugs#5711]
### Description
Environment: surface pro 7 Windows 11 Home 23H2, Microsoft IME, English layout keyboard
terget: windows VM
Issue: Cannot input Japanese in Note, Code Editor 2, Asset Names, etc., across the entire IDE.

### Steps To Reproduce
The issue occurs when a new project is created without adding any assets.

*This behavior closely resembles how it was when GM did not support Japanese. I am wondering if the entire IDE supports double-byte characters.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[237ad28c-5eac-4a24-afe8-a1181a841c39](https://api.gamemaker.io/api/github/downloads/237ad28c-5eac-4a24-afe8-a1181a841c39)

**Comment by zreedy** [comment]
Issues with IME in Code Editor 2 (Scripts, Objects, Notes, etc.) have been fixed internally, pending build.
Asset Names do not support non-ASCII-alphanumeric_ characters.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.600.0.584  Runtime v2024.600.0.608. 

Thank you.
