### ISSUE TITLE
Code Editor: Typing an opening brace crashes 2024.2 IDE if 2024.4 runtimes are active at the time

### ISSUE THREAD

**Issue by jack27121** [YoYoGames/GameMaker-Bugs#5712]
### Description
for whatever reason, suddenly when trying to create an if statement within a script crashes gamemaker,
specifically when i add a { i see a brief popup window saying creating dump, before gamemaker crashes

### Steps To Reproduce
go to simple_menu script
go to line 19
write an open curly bracket,
gamemaker crashes

to note, i am using a danish keyboard, in case it's specific to some other shortcut maybe

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[cb1c3eea-f8d6-4e27-bfe6-4454341d39ff](https://api.gamemaker.io/api/github/downloads/cb1c3eea-f8d6-4e27-bfe6-4454341d39ff)

**Comment by rwkay** [comment]
you seem to have a mismatched IDE and runtime - can you upgrade your IDE to 2024.4 and see if this still happens?

**Comment by YYDan** [comment]
The last lines in the log are that a copy/paste operation were performed (but then I can see the log just ends) - unfortunately, there's no crash information.

As you're using 2024.2, then hopefully updating will fix this, as mentioned above.

**Comment by YYDan** [comment]
Ahh, awesome! Thanks for letting us know so quickly.
