### ISSUE TITLE
Feather: skeleton_animation_clear's third parameter is named "track", should be "duration" according to its description

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#5714]
### Description

The description of the parameter name "duration" shown at the bottom is consistent with its description. In Feather, the parameter is shown as "track", however.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/110606193/b4a7a242-5c77-4c34-9ae4-2f115fc99c55)

### Expected Change

Feather lists the third parameter as "duration"

### Steps To Reproduce

1. Start GameMaker
2. Type the function name in a code editor, then show the function info.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.560  Runtime v2024.600.0.577
