### ISSUE TITLE
Performance: [Mac IDE] ProMotion displays ignore the Max FPS value set in Preferences

### ISSUE THREAD

**Issue by NanoSharkGames** [YoYoGames/GameMaker-Bugs#5722]
### Description
The IDE's frame rate remains at 120 fps on a MacBook Pro with a ProMotion display even after decreasing the IDE's maximum frame rate and power saving frame rates. This causes my MacBook to use more power & heat up slightly more.

### Steps To Reproduce
1. Open GameMaker on a ProMotion MacBook Pro
2. Observe that the IDE refreshes at 120 fps no matter what preferences you set

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
macOS Sonoma 14.4.1

[9394e8f3-5344-40d8-83f1-b0326f58e6f9](https://api.gamemaker.io/api/github/downloads/9394e8f3-5344-40d8-83f1-b0326f58e6f9)

**Comment by NanoSharkGames** [comment]
I tried using my device in Low Power Mode to reduce the refresh rate to 60 fps, but that did not improve the issue noticeably. I have reverted back to 2024.2 since this issue would affect my device's battery health & lifespan.

**Comment by NanoSharkGames** [comment]
Even after updating to 2024.4.1 that includes the Mac IDE laptop/battery mode leak fix, this issue sticks out to me as I am experiencing worse battery drain than before this update. Because of this issue & my desire to maintain good battery health on my device, I have to use GameMaker on Low Power Mode when unplugged. When can we expect a fix to be on the horizon?

**Comment by NanoSharkGames** [comment]
Any updates on this issue? No matter what frame rate I set, it still runs at 120 fps, generating more heat & reducing battery life. I did get longer runtimes before 2024.600, when the frame rate was set to the correct value. I hope this will be fixed as soon as possible, especially before the next LTS.

**Comment by NanoSharkGames** [comment]
I tested the latest Beta, & I am happy to report that this issue has been resolved on my machine.

**Comment by stuckie** [comment]
Marking this as complete from comment above.
If anyone else has an issue, please let us know and we'll take another look.
Thanks.

**Comment by Emc1923** [comment]
Closing as per comments, thanks.
