### ISSUE TITLE
Docs Integration: 2024.4 release notes have the wrong info listed for issue 2890, looks a duplicate of 2463

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5733]
### Description

The release notes for 2024.4 have "Shift-clicking no longer cancels “select from any layer” mode every time you do the command" listed twice. The duplicate links to #2890 which is a different change

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9412d27b-45e2-4449-b80b-92388e29bfce)

### Manual Link

https://releases.gamemaker.io/release-notes/2024/4

**Comment by YYDan** [comment]
Has been fixed now - good spot!
