### ISSUE TITLE
ios build fail

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GameMaker-Bugs#5734]
### Description

"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/bin/igor/windows/x64/Igor.exe" -j=10 -options="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- iOS Run

Loaded Macros from C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\macros.json
Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\bin\platform_setting_defaults.json
Options: C:\Users\searo\AppData\Roaming/GameMakerStudio2\searoopy_292940\local_settings.json
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\targetoptions.json
Setting up the Asset compiler
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/bin/assetcompiler/windows/x64/GMAssetCompiler.dll /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=10 /gn="undergroundstation_240503" /td="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168" /zpuf="C:\Users\searo\AppData\Roaming/GameMakerStudio2\searoopy_292940" /prefabs="C:\ProgramData/GameMakerStudio2/Prefabs" /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eA==" /m=llvm-ios /tgt=4 /llvmSource="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/yyc/" /nodnd /cfg="Default" /v /hprt=51269 /o="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC" /sh=True /optionsini="C:\Users\
searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC\options.ini" /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\BaseProject\BaseProject.yyp" "C:\Users\searo\GameMakerProjects\undergroundstation_240503\undergroundstation_240503.yyp" /preprocess="C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB"
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 2832.2179ms
Loaded Project: undergroundstation_240503
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 50.8408ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 23.6819ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 20.3478ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 15.3243ms
Loaded Project: _filter_old_film
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 20.3971ms
Loaded Project: _effect_windblown_particles
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 23.7683ms
Loaded Project: _filter_screenshake
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 9.795ms
Loaded Project: _filter_pixelate
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 28.2924ms
Loaded Project: _filter_heathaze
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 33.0353ms
Loaded Project: _filter_colourise
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 18.707ms
Loaded Project: _filter_posterise
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 24.4376ms
Loaded Project: _filter_tintfilter
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 25.1679ms
Loaded Project: _filter_greyscale
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 24.2767ms
Loaded Project: _filter_zoom_blur
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 10.1097ms
Loaded Project: _filter_underwater
finished.
Found Project Format 2
+++ GMSC serialisation: SUCCESSFUL LOAD AND LINK TIME: 24.7524ms
Loaded Project: GMPresetParticles
finished.
Release build
About to execute:C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\bin\putty\yyputtygen.exe "C:\Users\searo\AppData\Roaming/GameMakerStudio2\searoopy_292940\yoyo.ppk" -O public-openssh
mkdir -p ~/.ssh
cat ~/.ssh/authorized_keys
pwd
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\ExtensionOptions.json
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\PlatformOptions.json
PlatformOptions
RunCommandOnMac bash -l -c "xcode-select -v"
bash -l -c "xcode-select -v"
Options: C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\AdMob\AdMob.yy
RunCommandOnMac bash -l -c "echo ~"
bash -l -c "echo ~"
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\MainOptions.json
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\macros.json
Options: C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB\preferences.json
C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\AdMob\pre_build_step.bat
[ADMOB] INIT: Script initialization succeeded (v1.3.8 :: 0).

C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\AdMob\pre_build_step.bat DONE (0)
C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\AppleIAP\pre_build_step.bat
[APPLEIAP] INIT: Script initialization succeeded (v2.0.0 :: 1).

C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\AppleIAP\pre_build_step.bat DONE (0)
C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\FirebaseSetup\pre_build_step.bat
[FIREBASESETUP] INIT: Script initialization succeeded (v1.2.2 :: 1).
[FIREBASESETUP] WARN: Path 'C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\FirebaseSetup\AndroidSource\ProjectFiles\' does not exist. Skipping deletion.
"Copying iOS Firebase credentials into your project."
1�� ������ ����Ǿ����ϴ�.

C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\FirebaseSetup\pre_build_step.bat DONE (0)
C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\GameCenter\pre_build_step.bat
[GAMECENTER] INIT: Script initialization succeeded (v1.3.0 :: 1).

C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\GameCenter\pre_build_step.bat DONE (0)
C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\GMLive_fallback\pre_build_step.bat

C:\Users\searo\GameMakerProjects\undergroundstation_240503\extensions\GMLive_fallback\pre_build_step.bat DONE (0)
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/bin/assetcompiler/windows/x64/GMAssetCompiler.dll /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=10 /gn="undergroundstation_240503" /td="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\searo\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\undergroun_D71D0DD2_E113A9EB" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168" /zpuf="C:\Users\searo\AppData\Roaming/GameMakerStudio2\searoopy_292940" /prefabs="C:\ProgramData/GameMakerStudio2/Prefabs" /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eA==" /m=llvm-ios /tgt=4 /llvmSource="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/yyc/" /nodnd /cfg="Default" /v /hprt=51269 /o="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC" /sh=True /optionsini="C:\Users\
searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC\options.ini" /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\BaseProject\BaseProject.yyp" "C:\Users\searo\GameMakerProjects\undergroundstation_240503\undergroundstation_240503.yyp" /debug /MacHomeDir="/Users/etguris" /llvmSource="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\yyc" /optionsini="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC\options.ini" /bt=run /rt=yyc
Looking for built-in fallback image in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\bin\BuiltinImages
Compile Constants...finished.
Remove DnD...finished.
Warning : reference to extension macro gpb_store_connect which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_purchase_skutype_inapp which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_store_connect_failed which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_product_data_response which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_purchase_skutype_inapp which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_iap_receipt which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_product_consume_response which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_purchase_skutype_inapp which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_acknowledge_purchase_response which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_purchase_skutype_inapp which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_query_purchase_async which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_no_error which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Compile Scripts...finished.
Compile Rooms...finished..... 1 CC empty
Warning : reference to extension macro gpb_error_unknown which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_error_unknown which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Warning : reference to extension macro gpb_no_error which is not available for this target - macro is in extension GooglePlayBillingExtension and file GooglePlayBillingExtension.ext
Compile Objects...finished.... 376 empty events
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Final Compile...finished.
Looking for built-in particle images in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168\bin\assetcompiler\ParticleImages
saving file C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\undergroundstation_240503_3522EC31_YYC\game.ios
Writing Chunk... GEN8 size ... -0.00 MB
option_game_speed=30
Writing Chunk... OPTN size ... 0.00 MB
Writing Chunk... LANG size ... 0.00 MB
Writing Chunk... EXTN size ... 0.00 MB
Writing Chunk... SOND size ... 0.01 MB
Writing audio file mus_boss.ogg...
Writing audio file mus_dungeon01.ogg...
Writing audio file mus_dungeon02.ogg...
Writing audio file mus_forest01.ogg...
Writing audio file mus_forest02.ogg...
Writing audio file mus_town02.ogg...
Writing audio file snd_bgm_la_la_triroriro.ogg...
Writing audio file snd_ingame1.ogg...
Writing audio file snd_mus_battle.ogg...
Writing audio file snd_pachinko_bgm.ogg...
Writing audio file snd_rock_falling.ogg...
Writing Chunk... AGRP size ... 0.01 MB
Writing Chunk... SPRT size ... 0.00 MB
Writing Chunk... BGND size ... 0.14 MB
Writing Chunk... PATH size ... 0.00 MB
Writing Chunk... SCPT size ... 0.00 MB
Writing Chunk... GLOB size ... 0.06 MB
Writing Chunk... SHDR size ... 0.00 MB
Writing Chunk... FONT size ... 0.01 MB
Writing Chunk... TMLN size ... 0.85 MB
Writing Chunk... OBJT size ... 0.00 MB
Writing Chunk... FEDS size ... 0.40 MB
Writing Chunk... ACRV size ... 0.00 MB
Writing Chunk... SEQN size ... 0.00 MB
Writing Chunk... TAGS size ... 0.09 MB
Writing Chunk... ROOM size ... 0.00 MB
Writing Chunk... DAFL size ... 2.23 MB
Writing Chunk... EMBI size ... 0.00 MB
Writing Chunk... PSEM size ... 0.00 MB
Writing Chunk... PSYS size ... 0.00 MB
Writing Chunk... TPAGE size ... 0.00 MB
Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_
Texture Group - font2
Texture Group - boss_final
Texture Group - cutscene
Texture Group - Default
Texture Group - font2_jp
Texture Group - pinball
Texture Group - font_ch
Texture Group - font_eu
Texture Group - font_th
Texture Group - tile
Texture Group - vending
Texture Group - worm_room
Writing Chunk... TGIN size ... 0.07 MB
Writing Chunk... FEAT size ... 0.01 MB
Writing Chunk... STRG size ... 0.00 MB
Writing Chunk... TXTR size ... 1.06 MB
0 Compressing texture... writing texture __yy__0fallbacktexture.png_yyg_auto_gen_tex_group_name__0.yytex...
1 Compressing texture... writing texture boss_final_0.yytex...
2 Compressing texture... writing texture cutscene_0.yytex...
3 Compressing texture... writing texture default_0.yytex...
4 Compressing texture... writing texture default_1.yytex...
5 Compressing texture... writing texture default_2.yytex...
6 Compressing texture... writing texture default_3.yytex...
7 Compressing texture... writing texture default_4.yytex...
8 Compressing texture... writing texture default_5.yytex...
9 Compressing texture... writing texture default_6.yytex...
10 Compressing texture... writing texture default_7.yytex...
11 Compressing texture... writing texture default_8.yytex...
12 Compressing texture... writing texture default_9.yytex...
13 Compressing texture... writing texture default_10.yytex...
14 Compressing texture... writing texture default_11.yytex...
15 Compressing texture... writing texture default_12.yytex...
16 Compressing texture... writing texture default_13.yytex...
17 Compressing texture... writing texture default_14.yytex...
18 Compressing texture... writing texture default_15.yytex...
19 Compressing texture... writing texture default_16.yytex...
20 Compressing texture... writing texture default_17.yytex...
21 Compressing texture... writing texture default_18.yytex...
22 Compressing texture... writing texture default_19.yytex...
23 Compressing texture... writing texture default_20.yytex...
24 Compressing texture... writing texture default_21.yytex...
25 Compressing texture... writing texture default_22.yytex...
26 Compressing texture... writing texture default_23.yytex...
27 Compressing texture... writing texture default_24.yytex...
28 Compressing texture... writing texture default_25.yytex...
29 Compressing texture... writing texture default_26.yytex...
30 Compressing texture... writing texture default_27.yytex...
31 Compressing texture... writing texture default_28.yytex...
32 Compressing texture... writing texture default_29.yytex...
33 Compressing texture... writing texture default_30.yytex...
34 Compressing texture... writing texture default_31.yytex...
35 Compressing texture... writing texture default_32.yytex...
36 Compressing texture... writing texture font_ch_0.yytex...
37 Compressing texture... writing texture font_ch_1.yytex...
38 Compressing texture... writing texture font_ch_2.yytex...
39 Compressing texture... writing texture font_eu_0.yytex...
40 Compressing texture... writing texture font_th_0.yytex...
41 Compressing texture... writing texture font2_0.yytex...
42 Compressing texture... writing texture font2_1.yytex...
43 Compressing texture... writing texture font2_2.yytex...
44 Compressing texture... writing texture font2_jp_0.yytex...
45 Compressing texture... writing texture font2_jp_1.yytex...
46 Compressing texture... writing texture font2_jp_2.yytex...
47 Compressing texture... writing texture pinball_0.yytex...
48 Compressing texture... writing texture tile_0.yytex...
49 Compressing texture... writing texture vending_0.yytex...
50 Compressing texture... writing texture worm_room_0.yytex...
Writing Chunk... AUDO size ... 6.32 MB
Writing Audio Group minigame2048
Setting up core libraries.. DONE. Base app delegate: iPad_RunnerAppDelegate
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Xml.XmlException: The 'YYIosPBXBuildFileSection' start tag on line 3 position 2 does not match the end tag of 'YYIosPBXBuildFilesection'. Line 5, position 3.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
at System.Xml.XmlTextReaderImpl.ParseEndElement()
at System.Xml.XmlTextReaderImpl.ParseElementContent()
at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
at GMAssetCompiler.CodeInjectionUtils.HandleCodeInjectionTags(String codeInjection, Dictionary`2 env, String tagPrefix, Action`1 codeInjectionHandler, Dictionary`2 xmlNamespaces)
at GMAssetCompiler.Output.LLVM_iOS.AddExtensionCodeInjectionTagsToEnv(Dictionary`2 env, Dictionary`2 plistEnv, GMAssets assets)
at GMAssetCompiler.Output.LLVM_iOS.WriteProject(String _baseName, String _outputDir, List`1 _sourceFiles, List`1 _extraFiles, GMAssets _assets)
at GMAssetCompiler.LLVMSaver.Save(GMAssets _assets, String _name)
at GMAssetCompiler.Program.CompileProject(GMAssets _file)
at GMAssetCompiler.Program.Reentry(String[] _args)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at Igor.Program.ExecuteAssetCompiler(String _args)
at Igor.iOSBuilder.Run()
Igor complete.
elapsed time 00:00:41.2504645s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.4.0.168/bin/igor/windows/x64/Igor.exe" -j=10 -options="C:\Users\searo\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- iOS Run started at 05/03/2024 14:42:55
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

### Steps To Reproduce

1. Start GameMaker
2. ios build
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

iOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by TaylorDale** [comment]
For anyone running into this issue:
Caused by a simple typo in AppleIAP's < 2.0.0 ext.

All you need to do, in iOS settings for extension:
```
<YYIosPBXBuildFileSection>
7AD06C1017A9100F00B37894 /* StoreKit.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 7AD06C0F17A9100F00B37894 /* StoreKit.framework */; };
</YYIosPBXBuildFile**s**ection>
```

Change </YYIosPBXBuildFile**s**ection>  to have a capitalised S, to match the open tag
