### ISSUE TITLE
physics_raycast only returns hitpoints for the first edge of chain shapes

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#5741]
### Description

The function `physics_raycast` appears to check only the first edge of a chain shape. When the ray intersects with the chain's first edge, a hitpoint is included in the returned array. For any other segment of the chain no hitpoint is returned.

[PhysicsRaycast_chain_shapes.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15199179/PhysicsRaycast_chain_shapes.zip)

### Expected Change

All edges of a chain shape fixture are checked for intersection with the ray

### Steps To Reproduce

1. Start GameMaker
2. Import the sample project and run it
3. A circle is drawn when the ray intersects with the chain shape's first edge, not when it intersects any of the other edges.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.567  Runtime v2024.600.0.588
