### ISSUE TITLE
Feather - The type 'Array<Any>' appears where the type 'Id.Socket' is expected.

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#5743]
### Description

As it can be seen from the following image, Feather marks _clientID as an incorret type with the message:
The type 'Array<Any>' appears where the type 'Id.Socket' is expected

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/535b6c59-d4a8-4280-b8d5-c6733e709889)

However, some lines above, the exact same function is used and Feather recognizes it OK.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/b8eddbd3-3df1-4503-ba13-1f820924e774)

Contact Us Package:
[BUG.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15200988/BUG.zip)

### Expected Change

Feather should detect OK for the variable _clientID that it was an Id.Socket, not an 'Array<Any>'

### Steps To Reproduce

See above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Can't reproduce with IDE v2024.400.0.556, please attach a source sample if there is a very specific set of code that makes Feather mis-identify the type.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/74185255/dbca4098-7f85-4dce-9c0d-e3e67b934748)
