### ISSUE TITLE
part_system_create_layer argument 1 invalid reference to (layer) - requested 478 max is -1

### ISSUE THREAD

**Issue by SaeruWatson** [YoYoGames/GameMaker-Bugs#5745]
### Description

Since the last gamemaker update (2024.4) my game gets this error message everywhere and everytime I create a particle system with this function, my player and also some controller objects for UI rooms use a script that creates particles systems this way, also this error hasn't ocurred ever but this update, here's a screenshot of the error message and the attached files that this form ask for
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/135083433/f3977a5c-24ad-4f0e-a77e-25a8c313e37a)

[Example Proyect Contact Us Package File.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15202815/Example.Proyect.Contact.Us.Package.File.zip)

### Expected Change

as this function is just creating the particle system, I would expect to also verify that all the particles functions doesn't get this error

### Steps To Reproduce

1. Start GameMaker
2. Run the game
3. Only press "Z" key on keyboard to get as soon as possible on a room where the player is going to be created
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by afk147** [comment]
This seems to be the same issue tracked in [#5728](https://github.com/YoYoGames/GameMaker-Bugs/issues/5728)
