### ISSUE TITLE
Code Editor 2: While language server launches on Linux, services are not available

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5746]
### Description

The GameMakerLangaugeServer appears to launch on Linux but it does not appropriately respond to requests for any language service pertaining to a file path.

### Steps To Reproduce

1. Start GameMaker on Linux
2. Open a script in CE2
3. Observe that no semantic tokens, document symbols, folding info, or code completion appears/works.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.595  Runtime v2024.800.0.619
