### ISSUE TITLE
Linux: Error while building

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5748]
### Description

Building even an empty game on Ubuntu fails with an error about missing `linuxdeploy` dependency.

### Steps To Reproduce

1. Start GameMaker
2. Create and open an Empty project
3. Hit F5 to run the game
4. See the issue
[build.log](https://github.com/YoYoGames/GameMaker-Bugs/files/15202888/build.log)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
The linuxdeploy tool does not seem to be part of Ubuntu's package repository, so it needs to be installed manually.
See the Ubuntu setup guide: https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu
