### ISSUE TITLE
In-Game: DualShock 4/DualSense pads have "gp_select" and "gp_home" switched and "gp_touchbutton" not working in recent GM releases

### ISSUE THREAD

**Issue by bocoboc** [YoYoGames/GameMaker-Bugs#5754]
### Description
1. Gamepad button constants gp_select and gp_home are switche for both playstation controllers, dualshock 4 and dualsense.

2. gp_touchbutton not correctly mapped for dualshock 4, thus not working at all.

gp_select is wrongly assigned to home button for quite some time and I was hoping last update would fix it with updated gamepad constants.

Touchpad, home and back buttons were present in gamepad database for some time but GameMaker still manages to set the mapping for playstation controllers wrong. (btw GM manual always says gp_select is mapped to touchpad but I don't know if it ever was :D)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[043adcfe-b4f7-4372-ab39-cf3f00385873](https://api.gamemaker.io/api/github/downloads/043adcfe-b4f7-4372-ab39-cf3f00385873)

**Comment by bocoboc** [comment]
I have checked SDL controller database and my DS4 with GUI: 030000004c050000cc09000000000000 does not actually have touchpad assigned there. Don't know why, since its like the newest version but I'm just gonna add it to my gamepad mapping myself.

**Comment by shichen85** [comment]
Also experiencing this

**Comment by KhaoMortadios** [comment]
This has been the case for a long time. Would really appreciate if it was fixed.

**Comment by offalynne** [comment]
@bocoboc @shichen85 @KhaoMortadios can you report your IDE and Runtime versions please to confirm ?

**Comment by bocoboc** [comment]
> @bocoboc @shichen85 @KhaoMortadios can you report your IDE and Runtime versions please to confirm ?
IDE: v2024.4.1.152 Steam, Runtime v2024.4.1.202

**Comment by offalynne** [comment]
Touchpad mappings have been added to the relevant gamecontrollerdb entries. I have confirmed the `gp_select, gp_home` issue with YYG. They will follow up on both issues.

**Comment by shichen85** [comment]
I am on IDE 2024.600.0.563 and runtime 2024.600.0.580.
PS4 Controller GUI ID `030000004c0500 00cc09000000000000`

**Comment by KhaoMortadios** [comment]
I'm on IDE v2024.2.0.132 with Runtime v2024.2.0.163

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.600.0.571  Runtime v2024.600.0.597

**Comment by bocoboc** [comment]
> > I have checked SDL controller database and my DS4 with GUI: 030000004c050000cc09000000000000 does not actually have touchpad assigned there. Don't know why, since its like the newest version but I'm just gonna add it to my gamepad mapping myself.
> 
> @bocoboc We are trying to support PS controllers on older runtimes. Are you using `gamepad_test_mapping()` to add the missing mapping? Can you share the string that you use?

I am using GameMaker mapping and just adding "touchpad:b13" string to it. 

**Older runtimes** do not have `gp_touchbutton` constant though and it does not actually work when you feed it back to GM by `gamepad_test_mapping()` and checking for physical button 13. From my testing I observed that when GM creates d-pad hats it adds new "virtual" buttons to gamepad and all extra buttons after it do not correspond to actual physical buttons provided by mapping.

Because of it I ended up coding my own makeshift input system, using `gamepad_get_mapping()` string, clearing it `gamepad_remove_mapping()` and checking for all physical buttons myself. Similar to "Input" extension by Juju Adams.

My code:
```
var _mapping = gamepad_get_mapping(_device);
		
if(_gamepad.model == gp_model.PS4 && _gamepad.guid == "030000004c050000cc09000000000000") _mapping += "touchpad:b13,";
		
input_gamepad_set_mapping(_device, _mapping);
```

**Comment by rwkay** [comment]
The Beta that was released today has this fixed

**Comment by shichen85** [comment]
> > > I have checked SDL controller database and my DS4 with GUI: 030000004c050000cc09000000000000 does not actually have touchpad assigned there. Don't know why, since its like the newest version but I'm just gonna add it to my gamepad mapping myself.
> > 
> > 
> > @bocoboc We are trying to support PS controllers on older runtimes. Are you using `gamepad_test_mapping()` to add the missing mapping? Can you share the string that you use?
> 
> I am using GameMaker mapping and just adding "touchpad:b13" string to it.
> 
> **Older runtimes** do not have `gp_touchbutton` constant though and it does not actually work when you feed it back to GM by `gamepad_test_mapping()` and checking for physical button 13. From my testing I observed that when GM creates d-pad hats it adds new "virtual" buttons to gamepad and all extra buttons after it do not correspond to actual physical buttons provided by mapping.
> 
> Because of it I ended up coding my own makeshift input system, using `gamepad_get_mapping()` string, clearing it `gamepad_remove_mapping()` and checking for all physical buttons myself. Similar to "Input" extension by Juju Adams.
> 
> My code:
> 
> ```
> var _mapping = gamepad_get_mapping(_device);
> 		
> if(_gamepad.model == gp_model.PS4 && _gamepad.guid == "030000004c050000cc09000000000000") _mapping += "touchpad:b13,";
> 		
> input_gamepad_set_mapping(_device, _mapping);
> ```

Gotcha. Thanks for the reply!
