### ISSUE TITLE
UI/UX: Arrow Key inputs are mutually exclusive in 2024.4

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#5756]
### Description
The arrow keys cannot be pressed if another arrow key is held down. This causes frequent dropped inputs when using the arrow keys to navigate code quickly.

This issue is slowing down my work by an impactful amount.

### Steps To Reproduce
Put the cursor in some code. Press one arrow key and hold it down, then press another arrow key and see that it does nothing.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[807840d2-6145-4c6b-b57d-7b0de371fbbf](https://api.gamemaker.io/api/github/downloads/807840d2-6145-4c6b-b57d-7b0de371fbbf)

**Comment by JonathanHackerCG** [comment]
To facilitate some cross-linkage:
* This issue may be responsible for #5738.
* This issue may be related to or a side effect of #5244.

**Comment by SmithTom6304** [comment]
Side effect of https://github.com/YoYoGames/YoYoStudio/pull/9939

**Comment by JonathanHackerCG** [comment]
Also, Enter and Control cannot be pressed if any (?) other non-combo key is pressed.

This along with the arrow keys fully explains all of the dropped inputs I have experienced.

**Comment by SmithTom6304** [comment]
Should now be fixed - pressing an arrow key will now always perform that action, regardless of what other keys are held with the exception of modifier keys.
If a modifier key is held, it will either:
1) Perform the action assigned to that modifier, ie. Shift + Arrow will move the cursor and select text
2) Do nothing if no action is assigned to that modifier. This matches the behaviour in 2024.02.

**Comment by YYDan** [comment]
Just noticed the comment above, so have returned this one back in case the manual needs any updating now.

**Comment by YYBartT** [comment]
Nothing to be documented for this.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.4.1.140  Runtime v2024.4.1.174. 

Thank you.
