### ISSUE TITLE
Android - Ignores specified build tools and always uses version 30.0.3

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#5760]
### Description

Here is my configuration for the game for Android, as you can see I've indicated to use build tools 34.0.0 which is the version I've installed through Android Studio (using Android Studio Jellyfish but it also happens with older versions).
![BuildTools](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/a524a827-8d62-44c2-b1b4-9a78d2b7ca56)

This is my Android Studio SDK manager before building the Android project:
![Before](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/967fba8c-5874-44e5-bffe-f2509292089f)

During build in the output window I can see that GMS installs 30.0.3 automatically if its not installed (and is the one that uses):
![IncorrectVersion](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/1f0d55bc-6ecb-400f-b947-ab37077bebb1)

If I now go to my Android Studio SDK manager I can see that, indeed, I have 30.0.3 installed:
![After](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/1c9a060e-478e-4f7f-b345-704648c9261d)

GMS will ignore what is in the configuration and always use 30.0.3.

I include the "Contact Us Package": 
[AndroidIssue.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15212180/AndroidIssue.zip)

### Expected Change

GMS when building for Android will use the specified build tools.

### Steps To Reproduce

See above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Hi, the build tools used by gradle are now determined by which API level that you are building for, it does not matter what is set in GM, it is overridden by gradle. (The setting is kept atm for backwards compatibility when using a lower API level that does not set it) In your Android Studio under SDK Platforms do you have Android 14.0 ("UpsideDownCake") installed?

**Comment by AIO1** [comment]
@jackerley 

Yes, I do have Android 14 installed:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/17305493/7575c10b-bb3d-4660-b166-01ba7e885f8e)

**Comment by jackerley** [comment]
Hi, if you update to the latest Beta version of GM, we have updated the Android Gradle Plugin to 8.5 (the latest available) this will force your build tools to 34, note it won't use 35 as it's not yet compatible with that.

**Comment by YYDan** [comment]
In general, your point is valid and also not a bug - the Android tools _will_ download and install components used for older APIs if that's a) what you have set in Game Options, or b) if any extension requests them in its injection values, etc. It's not GameMaker that downloads things during the builds.

This is all correct Android tools behaviour and our setup guide does say this already.
