### ISSUE TITLE
gpu_set_depth still doesn't affect tilemaps

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5766]
### Description
According to #4741 gpu_set_depth should now affect tilemaps, but it does not.

### Steps To Reproduce
Run the sample project, notice the tilemap not cosining up and down in 3D space

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[24309048-56f0-4223-ad95-02505552703e](https://api.gamemaker.io/api/github/downloads/24309048-56f0-4223-ad95-02505552703e)

**Comment by jackerley** [comment]
Hi, you are calling layer_force_draw_depth(true, 0); which forces the tilemap to be drawn at depth 0, removing this call will allow you to render the tilemap at your requested depth.

**Comment by DragoniteSpam** [comment]
That takes precedence over gpu_set_depth? Interesting

**Comment by Emc1923** [comment]
Closing as per the above comment, thanks!
