### ISSUE TITLE
Unable to compile macros that use recently introduced `nameof` feature

### ISSUE THREAD

**Issue by toarch7** [YoYoGames/GameMaker-Bugs#5786]
### Description

Having this line of code `#macro HELLO show_debug_message(nameof(aaa))` breaks the compiler in an unusual way, throwing a C# exception.

[Contact Us Package.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15238003/gyah.zip)

### Expected Change

Make `nameof` collapse after the macros are expanded.

### Steps To Reproduce

1. Start GameMaker
2. Create the following macro somewhere `#macro HELLO show_debug_message(nameof(aaa))`
3. Start Build
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.6

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.561  Runtime v2024.600.0.579

**Comment by YYDan** [comment]
(Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5158)
