### ISSUE TITLE
Code Editor 2: Right-to-Left Language Support is broken

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5787]
### Description

Currently in Code Editor 2 support for Right-to-Left languages such as Arabic, Hebrew, and Persian is broken in a variety of ways. Generally rendering and text manipulation misbehaves in ways that make using these languages in the Editor either cumbersome or impossible.

- Text Manipulation (typing, or deleting text) will corrupt on lines where multi-byte characters are used (emojis, and glyphs for some RTL languages are multi-byte unicode points)
- Text Cursor behavior for LTR -> RTL -> LTR spans does not behave correctly. Expected behavior is that the Text Cursor moves to the right-most character in an RTL span and pressing Right move the Text Cursor Left until the leftmost portion of the span. Pressing right once more should move the text cursor to the first character immediately to the rightmost character of the RTL span.
- Rendering of mixed direction spans is broken in that some characters are dropped, others duplicated.

The following can be used to test against
```
this is left-to-rightمرحبًا! هذا نص عربي.and back to left-to-right
‫דג סקרן שט בים מאוכזב ולפתע מצא לו חברה. איך הקליטה? הלוף מתפןצץ!
AB你好😍CDEF。有り難うございます。
社會科學院語學研究所
```

First line demonstrates behavior for mixed direction spans.
Second line demonstrates behavior for right-to-left with neutral direction characters preceding (whitespace). (expected behavior is to treat otherwise uninfluenced neutral characters as left-to-right)
Third line contains mixed single and multi-byte characters. The Emoji is the first mult-byte character.
The last line is entirely multi-byte characters.

### Steps To Reproduce

1. Start GameMaker
2. Paste in the above sample text
3. Observe various incorrect rendering, text manipulation issues, and text cursor issues.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
in IDE v2024.600.0.565  Runtime v2024.600.0.585, the ide becomes unstable as soon as the test text is pasted in note, script or object
[ui.log](https://github.com/user-attachments/files/15613125/ui.log)

**Comment by zreedy** [comment]
Regression relating to tab support fixed. I no longer observe the Unstable warning.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.595  Runtime v2024.800.0.618
