### ISSUE TITLE
Code Editor 2: Changing font size or face corrupts text shown in editor

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5788]
### Description

If you have a document open and then you were to open Preferences and change the pt size or font face of the font in `Code Editor 2 -> Theme` you may notice that the characters become corrupted. Typically random characters are shown in place of others.

### Steps To Reproduce

1. Start GameMaker
2. Open a code document
3. Open Preferencs and change the font size and face a few times until you see the issue

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
