### ISSUE TITLE
Code Editor 2: Poor support for non-Latin fonts, and fallback fonts

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#5789]
### Description

When using a language that uses non-Latin characters the current behavior of finding fallback fonts and rendering them is lacking in several key ways.
1. The fallback fonts specified by the User through their OS are not used first. This primarily affects Chinese users who rely on this functionality in Windows especially.
2. The replaced glyphs may vary in pt size, making text look sarcastic.
3. The replaced glyphs may vary in baseline, making the text look wobbly
4. Some fonts do not render with anti-aliasing (e.g. Calibri 10pt)

The following text will require fallbacks when using Consolas 10pt on Windows.
```
你好！ 这是一些中文文本。
#	表          CJK_UNIFIED_IDEOGRAPHS (U+8868)
#	ポ          KATAKANA LETTER PO (U+30DD)
#	あ          HIRAGANA LETTER A (U+3042)
#	A           LATIN CAPITAL LETTER A (U+0041)
#	鷗          CJK_UNIFIED_IDEOGRAPHS (U+9DD7)
#	Œ           LATIN SMALL LIGATURE OE (U+0153) 
#	é           LATIN SMALL LETTER E WITH ACUTE (U+00E9)
#	Ｂ           FULLWIDTH LATIN CAPITAL LETTER B (U+FF22)
#	逍          CJK_UNIFIED_IDEOGRAPHS (U+900D)
#	Ü           LATIN SMALL LETTER U WITH DIAERESIS (U+00FC)
#	ß           LATIN SMALL LETTER SHARP S (U+00DF)
#	ª           FEMININE ORDINAL INDICATOR (U+00AA)
#	ą           LATIN SMALL LETTER A WITH OGONEK (U+0105)
#	ñ           LATIN SMALL LETTER N WITH TILDE (U+00F1)
#	丂          CJK_UNIFIED_IDEOGRAPHS (U+4E02)
#	㐀          CJK Ideograph Extension A, First (U+3400)
#	𠀀          CJK Ideograph Extension B, First (U+20000)

表ポあA鷗ŒéＢ逍Üßªąñ丂㐀𠀀
```
Notably `这` tends to not exist first fallback font, requiring a 3rd fallback.

### Steps To Reproduce

1. Start GameMaker
2. Paste text into a new script and observe various rendering issues.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gnysek** [comment]
Seems that even browsers and Notepad have issues with some of UTF characters, and even here monospace fonts get misaligned:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/9f9c0c9b-ccf7-43dd-a5f0-2e828d6fc08b)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
