### ISSUE TITLE
Change in behaviour compared to previous version

### ISSUE THREAD

**Issue by slyddar** [YoYoGames/GameMaker-Bugs#5792]
### Description
The o_game room_start event creates a solid on every wall tile, then cycles through every solid to cull solids which are not needed by adding 1 to the image_xscale of a solid if there is one to the right of it, then deleting the one to the right.  It continues that horizontally as far as it can.  I have commented out lines 30-35, which shows the files are there when xx = 0, but when it processes xx  == 1 they are gone.
This method worked perfectly in every Gamemaker Beta and LTS prior, but in this version it no longer works, so maybe the scaling collisions are different in this version.

### Steps To Reproduce
If this is opened in a previous version all solids will appear correct.  When run in this version, you can see the gaps in the walls where the solids were destroyed and the scaling didn't occur.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[fb3d289a-881a-4bf9-a302-7864d5578a70](https://api.gamemaker.io/api/github/downloads/fb3d289a-881a-4bf9-a302-7864d5578a70)

**Comment by jackerley** [comment]
Hi, changes were made to collision_point, collision_line and collision_rectangle to make them consistent with how sprite collisions work. If you need to still use the previous behaviour you can switch  Collision Compatibility Mode on in Game Options - Main?

**Comment by jackerley** [comment]
Actually, scratch that I've had a look and there is a change that I can make that'll keep this consistent with previous behaviour and still maintain better mathematical correctness, it'll be in the next beta

**Comment by alicemoretti** [comment]
Verified fixed on  IDE v2024.4.1.142  Runtime v2024.4.1.175. 

Thank you.
