### ISSUE TITLE
Code editor 1: Commands like enter, delete, copy/paste, and more do not work while holding other keys

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5798]
### Description
Holding a key like a letter key and then trying to press enter, delete, copy/paste, etc. will do nothing. I suspect this is the source of some of the general unresponsiveness in 2024.4
So far the keys with this issue I've found are:
- Backspace
- Delete
- Enter
- Ctrl+c, ctrl+x, ctrl+v
- Tab
- Arrow keys (not just exclusive with eachother, also exclusive with letter/number/etc. keys)
- Page up/page down

### Steps To Reproduce
Hold a letter key, then try to press enter or delete, or try to copy/cut/paste

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0bafa025-b474-41b4-a295-97965c908b9b](https://api.gamemaker.io/api/github/downloads/0bafa025-b474-41b4-a295-97965c908b9b)

**Comment by SmithTom6304** [comment]
This should now be fixed.
