### ISSUE TITLE
Performance: [Mac IDE] CheckLaptopMode and CheckBatteryCharging cause a memory leak

### ISSUE THREAD

**Issue by stuckie** [YoYoGames/GameMaker-Bugs#5807]
It looks like we are not releasing all Cocoa objects in these functions.
This is causing the memory usage to skyrocket on MacBooks when the IDE is minimised.

**Comment by Emc1923** [comment]
Checked on  IDE v2024.4.1.142  Runtime v2024.4.1.175 on a Macbook and there is no noticeable memory spikes. Closing as fixed.

**Comment by yerumaku** [comment]
Thanks a lot!
