### ISSUE TITLE
Code Editor 2: [Notes] Internal hyperlinks do not work if the destination heading contains spaces

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#5809]
### Description

Notes in CE2 can created using markdown. Internal links where the heading used as a link contains no spaces currently works but those with spaces in their headings do not.

### Expected Change

internal link to headers with spaces work

### Steps To Reproduce

1. Start a Beta version of GameMaker 
2. Enable CE2 in Preferences (if required)
3. create a new project
4. Create a new Note
5. copy and paste the markdown below
6. try the index links 3 and 4
7. the screen will correctly jump for 3 but not 4

````
# Table of Contents
1. [How to Create New Levels](#How-to-Create-New-Levels)
2. [How to Change Important Starting Variables](#How-to-Change-Important-Starting-Variables)
3. [Objects](#Objects)
4. [Fire Tower](#fire-tower)


This note is high-level documentation for the core parts of this template project.
All events in this project are commented, so you can open any event and read the comments to understand what it does, and how it works.


## How to Create New Levels

	To create a new first create a new room that is the same width and height as the current rooms.

	
## How to Change Important Starting Variables

	You can change the starting health and money in the obj_gameplay_manager.
	You can change what the waves look like in obj_wave_level_1 (or any wave objects you create)
	You can change the health and speed of the enemies in obj_zombie and obj_frankenstein
	You can change the cost of the archer tower in obj_button_tower_buy_archer and the cost of the arc tower in obj_button_tower_buy_arc

# Objects
 hello


# Fire Tower
    obj_tower_fireball
	- contains particle definition
	spr_fireball is used to give collision mask from a 2x2 clear pixel
````

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.543  Runtime v2024.400.0.562

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
