### ISSUE TITLE
Sprites disappear when moving their position in the vertex shader

### ISSUE THREAD

**Issue by phablix** [YoYoGames/GameMaker-Bugs#5812]
### Description

When drawing sprites with a perspective camera and updating their position in the vertex shader, the sprite seems to disapear when the camera moves. Their draw events seems to be executed but the sprite is not drawn.

### Steps To Reproduce

1. Put a sprite in the room and a perspective camera (the error seems to happen with all cameras)
2. Apply a shader to it and move all the vertices with a big offset
3. Move the camera far from the sprite 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
