### ISSUE TITLE
Game "Slows Down" after re-focus

### ISSUE THREAD

**Issue by poorlocke** [YoYoGames/GameMaker-Bugs#5813]
### Description
**POSSIBLY MY FAULT but posting in case someone else experiences it. **

During runtime, if you have focused on another application or left the PC to screensaver(in my case it turns the screen off), and you re-focus on the game, it feels like the game is running at a slower speed, like half the room speed or less. 

- It is fixed after a fullscreen toggle. 
- I disable appsurf draw in order to allow for post-processing effects stacking surfaces.
- Have only tried it in one project.
- Didn't happen in previous runtimes or at least I didn't notice.

### Steps To Reproduce
Leave the game running and either switch to another application for 15-20 mins or let the PC turn the screen off for the same amount of time. After you refocus on the game, it will be "slowed-down". 

-Fullscreen toggle fixes it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[e9d90c15-fffe-4e98-8d27-45f58ae7a25c](https://api.gamemaker.io/api/github/downloads/e9d90c15-fffe-4e98-8d27-45f58ae7a25c)

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
