### ISSUE TITLE
In-Game: [Windows] url_open() does not seem to work if Chrome is the default OS browser

### ISSUE THREAD

**Issue by Stress0hneGrund** [YoYoGames/GameMaker-Bugs#5816]
### Description
im using url_open to open any website but instead it tries to open a folder with the link that obviously doesnt exist, so far for opera as standard browser it works, for google chrome it doesnt

### Steps To Reproduce
just use url_open with google chrome as standard browser (on windows)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[654c98be-6c9d-41cb-bab6-2a2adb37ef5f](https://api.gamemaker.io/api/github/downloads/654c98be-6c9d-41cb-bab6-2a2adb37ef5f)

**Comment by YYDan** [comment]
Works just fine in Beta IDE v2024.800.0.609  Runtime v2024.800.0.633 using this little sample: [test-url_open.zip](https://github.com/user-attachments/files/16659080/test-url_open.zip)

![Chrome](https://github.com/user-attachments/assets/5a91cf83-2f2c-422a-b3ee-6f2024c7e83b)

![GX](https://github.com/user-attachments/assets/b41afa24-cd49-4f36-984a-600e2426f1fc)

Can freely modify the Windows default app and re-run the game, and the correct browser is detected each time:
![image](https://github.com/user-attachments/assets/5fe4a855-b500-403d-9d45-abcc5bb1ad7d)

No sample was sent, so there could be some other issue going on here, but I would blame Chrome file associations, or similar. See  https://github.com/YoYoGames/GameMaker-Bugs/issues/243 for that bit.

**Comment by YYDan** [comment]
Actually now suspect, having expanded my test project on the linked issue and confirmed that HTML5 works just fine, the issue is very simply that your Chrome is not allowing the game page to open popup windows, but your Opera GX does.

Note that url_open() would take over the current tab used for the game also, so you should be using the _ext() or _full() versions when working in HTML5,
