### ISSUE TITLE
Documentation: Do / Until example uses instance_count instead of instance_number

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5821]
### Description

The example at the bottom of the do / until page uses this line
```
until (instance_count(obj_Enemy) >= 10);
```
but instance_count is a built in variable, not a function. That should be instance_number instead.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2Fdo___until.htm

**Comment by YYBartT** [comment]
Changed this on the do-until manual page.
