### ISSUE TITLE
Tile collision in new gamemaker update got worse

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#5832]
### Description

After new update of gamemaker came out, tile collision started having some mysterious issues with some shapes, seems like its only collision_line issue. here are some gif examples:

![Runner_iGkU7jTtBH](https://github.com/YoYoGames/GameMaker-Bugs/assets/68426621/51c5ffef-25dc-49de-8ef4-1ad164fe7b3e)

this one is old issue, flipped tiles are weird one some shapes
![Runner_qtHwFysFur](https://github.com/YoYoGames/GameMaker-Bugs/assets/68426621/c846d6ba-a801-4acf-ac46-ff0a0aa139b4)

Here's source for you guys to check out, branch name is april2024-bug-report and it has everything you need in it here, some useful debug keys [TAB: No clip mode and F9 to toggle collision view on and off]
https://github.com/DarkD04/Harmony-Framework/tree/april2024-bug-report

### Expected Change

I expected this to be fixed ASAP

### Steps To Reproduce

1. Just play the game

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.580

**Comment by jackerley** [comment]
Project here https://drive.google.com/file/d/17ElzmEu5YTxG2bJ36356gSLdxEPCqSis/view?usp=sharing
