### ISSUE TITLE
[VM] Turning off garbage collector makes all function returns leak memory

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#5847]
### Description
I've noticed that despite the garbage collector only ever applying to structs, arrays and methods, it seems to cause a massive memory build up overtime even when none of those are being freed by any means.

From further investigation, I've noticed that returning *anything* causes the GC to build up faster and faster. 

I have also included a video demonstrating this issue, but with a repeat loop of 10,000. And it is not nice at all. Keep in mind, this project is completely blank.

For those who which to try it:
```gml
// Script
gc_enable(false);
show_debug_overlay(true);

function a_func() {
	return false;	
}

// Step
repeat(100) { // Can be much higher, but higher == faster memory build up.
	a_func();	
}
```

### Steps To Reproduce
1. Download the project
2. Run it in VM 
3. Pull up the Memory debug view (debug overlay will be automatically enabled as per Script1)
4. Check the memory usage climbing up.
5. Press "Toggle GC" to enable the garbage collector (also disabled via Script1)
6. Watch as the memory usage itself remedies.
7. In Script1, comment out `return false;` and repeat 2-4, and witness the memory usage barely climb up at all.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[2ba7d80b-d646-430e-8f7e-9db1f4578444](https://api.gamemaker.io/api/github/downloads/2ba7d80b-d646-430e-8f7e-9db1f4578444)

**Comment by tabularelf** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/9b1676ac-67e2-4b28-9b0d-a7c49d7d28aa

Here is a video that also showcases it with a repeat loop of 10,000. Just to show the severity of the issue.

**Comment by gnysek** [comment]
As most those who looks here might not seen this comment from Russell on Discord:
> GC switching off is not a bug on VM - the locals in VM is a struct and if you switch the GC off they are not reclaimed
> but this is by design
>in YYC locals are true C++ locals and cleaned up on exit

**Comment by rwkay** [comment]
I have improved the situation in 2024.6 and the local structure is only created when required on VM now... if a function does not use any locals then a struct is not created for it.... 

BUT I have probably made it worse too as I noticed that we were explicitly freeing the locals struct when the `return` instruction was executed, and that would have been bad again for performance... so I may have made the memory / GC situation a bit worse in fixing that.

Swings and roundabouts....
