### ISSUE TITLE
Podfile has encoding issues

### ISSUE THREAD

**Issue by clee2005** [YoYoGames/GameMaker-Bugs#5850]
### Description
My pods are suddently failing with : 

ArgumentError - Illformed requirement `"~&gt; 12.3.0"`

And when I looked into the Podfile all of my '~> 12.3.0' (or other versions) were messed up and had '~&gt; 12.3.0' 

The build fails.

### Steps To Reproduce
Create a project, and include an extension like the Facebook extension for iOS.   

<YYIosCocoaPods>
   pod 'FBSDKCoreKit', '~> 12.3.0'
   pod 'FBSDKShareKit', '~> 12.3.0'
   pod 'FBSDKLoginKit', '~> 12.3.0'
</YYIosCocoaPods>

Then try and build.   You'll see the Podfile has &gt; where a > should be.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
iOS

[36c38af5-20a7-44ae-afb5-8b8b29cc20a2](https://api.gamemaker.io/api/github/downloads/36c38af5-20a7-44ae-afb5-8b8b29cc20a2)

**Comment by YYDan** [comment]
GameMaker/issues/4002 says this also affects the Firebase extension, so that should be checked also when verifying.
