### ISSUE TITLE
Path Ended event with invalid path id

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#5852]
### Description
Sometimes (can't identify a precise reason so far), checking the path_index built-in variable in the "path ended" event returns -1. This is an issue as we need to be able to properly identify the path that just ended to be able to rely on this event for useful purposes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Which platform(s) are you seeing the problem on?
Windows

[f7fecbd0-50af-41a3-a4f6-74cf9f7a0947](https://api.gamemaker.io/api/github/downloads/f7fecbd0-50af-41a3-a4f6-74cf9f7a0947)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.
