### ISSUE TITLE
Feather: Creating an instance inside a method, and then setting a variable on an instance using a with statement, will trigger a GM2016 error even though the variable was declared in create

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5858]
### Description
This is somewhat similar to #2163, but this error is NOT a phantom error (always appears when starting the project, and does not go away when clicked on), and it applies to regular create event variables, not just ones from variable definitions. 

If you create and instance and use a with statement to change one of it's variables inside a method, a GM2016 error will appear wherever that method is called. It says that the variable you assigned in the with statement wasn't declared in create, even though it was. The error does not appear when accessing the instance directly to change the variable instead of using a with statement, like inst.myVar = 0;

### Steps To Reproduce
Object1 create event:
```
create_an_object = function() {
	var inst = instance_create_layer(0, 0, "Instances", Object2);
	with inst {
		myVar = 0;	
	}
}
```
Object1 step:
```
create_an_object(); //feather error here
```

Object2 create:
```
myVar = 5;
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d81386f6-a4f7-46ae-9467-fdde933afc85](https://api.gamemaker.io/api/github/downloads/d81386f6-a4f7-46ae-9467-fdde933afc85)

**Comment by zreedy** [comment]
Pulling into the .10 milestone as this was a 5-minute 4-line fix which also benefits CE2's Code Completion.

**Comment by zreedy** [comment]
Fixed

**Comment by KormexGit** [comment]
#2164 and #2163 are very similar to this one, so it'd be good to check on if those are fixed by the change as well

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.625  Runtime v2024.1100.0.651
