### ISSUE TITLE
[Code Editor 2]  Deleting whitespaces with backspace behaves strangely

### ISSUE THREAD

**Issue by ReeseJones** [YoYoGames/GameMaker-Bugs#5866]
### Description
Whitespaces are shown in the new code editor, but when I try to delete them  (via backspace)  it acts as if they were not there and moves to the line above deleting characters I didnt expect it to.

### Steps To Reproduce
Its hard to capture, and I dont know if it always does this. I am using the latest beta in the new code editor.

In my project:
Open  scr_ui_layout_calculator_test
On line 11 after the closing of the before_each block press enter to make a new line.

It seemingly auto tabs aligning it with the 'it' block below it. The cursor looks lined up with the 'it' code block after that.

When I press backspace to delete the auto tabbed whitespaces, it instead deletes a newline character. The whitespaces dissapear like they were never there.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[c6caa527-95b8-4b67-87f2-931b237e80b2](https://api.gamemaker.io/api/github/downloads/c6caa527-95b8-4b67-87f2-931b237e80b2)

**Comment by zreedy** [comment]
This is working as expected. When "tab mode" is set to "Full" the tab stops are preserved. If you do not want this behavior then switch the "tab mode" to "Braces".

**Comment by zreedy** [comment]
Delaying closing this ticket as there is a related bug https://github.com/YoYoGames/GameMaker-Bugs/issues/5246 which would affect switching tab modes behaving properly here.

**Comment by mgeddesGM** [comment]
closing as per above comments, when pressing delete it acted as expected for both full and braces mode

 IDE v2024.600.0.571  Runtime v2024.600.0.597
