### ISSUE TITLE
Sounds loaded with audio_create_stream crash the game on Mac

### ISSUE THREAD

**Issue by ampersandbear** [YoYoGames/GameMaker-Bugs#5876]
### Description

Sounds loaded using audio_create_stream from the Application Support folder crash the game on Mac. 

Crashlog: [Mac Crashlog.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/15354758/Mac.Crashlog.txt)

I can't disclose the source here due to NDA, please contact me via ampersandbear@gmail.com, and I'd be glad to provide access to our SVN. 

### Steps To Reproduce

1. Subscribe to [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3044781675). 
2. Start GameMaker.
3. Build for Mac YYC.
4. Start Adventure, skip cutscenes, then press Enter - Skip Tutorial.
5. Go into the Mod Portal.
6. Bump into Bard (2nd top row).
7. Leave the Mod Portal.
8. Bump into Shovel Knight near the campfire a couple times.
9. The game hard crashes.

A video of the crash: https://github.com/YoYoGames/GameMaker-Bugs/assets/29552609/5f44dae9-e26f-4ef9-91dd-cc30255145e3

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment]
Waiting on a project from the reporter so putting this back into to-do for now.

**Comment by toby-yoyo** [comment]
The issue here was a historic bug where references held by ogg voices (in this case, to an emitter) were not properly cleaned up before the voice was selected for reuse. This was fixed some time ago in the monthly releases and so that fix has been brought over to the LTS branch.

**Comment by Emc1923** [comment]
@toby-yoyo do you have a sample that reproduced the issue to test this? Thanks!

**Comment by Emc1923** [comment]
Verified fixed with the attached sample as of  IDE v2022.0.3.60  Runtime v2022.0.3.72. Closing.
