### ISSUE TITLE
Runtime 2024.4 breaks my game's layers drawing

### ISSUE THREAD

**Issue by mrdaneeyul** [YoYoGames/GameMaker-Bugs#5877]
### Description
I'm not exactly sure what's going on here, but the latest GameMaker release, 2024.4, breaks my project's layers displaying. It looks like it's attempting to draw a bunch of layers all to the same place, and the player character is being drawn "under" them instead of on top.

I have a "3D" camera test mode for debugging, and things look especially strange there. It looks like it's drawing almost the same thing to all the layers with no, or less, transparency

Switching back to runtime 2024.2 fixes the issue. 

I am manually setting the depth of most of my layers in game on room start event, and I wasn't sure if that was the issue or not.

I dug through the changes that GameMaker made when initially running on the newer version. Nothing in particular stands out to me as a smoking gun, but I did notice the rooms .yy files are changed and something looks really "off" with the TileCompressedData. I don't know if it's related. I'll add a pic of that too.

Note: issue is also present in Beta IDE v2024.400.0.556, Runtime v2024.400.0.571

### Steps To Reproduce
1. First noticed with GameMaker version 2024.4.0.137 install
2. Switched back to runtime 2024.2.0.163, immediately encountered unresolvable compile errors. Something about "resourceType" being missing from the room .yy files.
3. Uninstalled and reinstalled GameMaker using older installer, version 2024.2.0.132, once again using runtime 2024.2.0.163. All compile and layer/display issues were resolved
4. Switched to newer runtime, version 2024.4.0.167, layer/display issue began reoccurring.
5. Switched back to 2024.2.0.163, layer/display issue stopped again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[ca23735c-ad6d-450c-aeed-3f3c4ec0d366](https://api.gamemaker.io/api/github/downloads/ca23735c-ad6d-450c-aeed-3f3c4ec0d366)

**Comment by YYDan** [comment]
Having looked at the linked issue above, that one quotes [one of our tiling blogs](https://gamemaker.io/en/blog/z-tilting-shader-based-2-dot-5d-depth-sorting) - that blog has already been updated to say that you need to change your code in 2024.4:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/bea2eeb3-4fc5-4e47-bdd1-bfbcba9b8377)

**Comment by stuckie** [comment]
Closing as above
