### ISSUE TITLE
SWFs don't play on HTML5 correctly.

### ISSUE THREAD

**Issue by ZGarces98** [YoYoGames/GameMaker-Bugs#5884]
### Description
I noticed that my game suddenly stopped animating when i tested it on html5. Swfs only showed the first frame but pngs were totally fine. This didn't happened from previous versions of gamemaker. 

After checking I realized it had something to do with the visible button on the object and drawing objects using a dedicated drawing object. With the visible button checked, swfs play normally but I see them twice because I use a different object to draw things on screen.

### Steps To Reproduce
1. Create an object with a swf as a sprite (obj_test)
2. DISABLE the visible tag on that object
3. Create a NEW object and create a DRAW EVENT (obj_drawer)
4. Type with(obj_test) { draw_self(); }
5. Check Non html5 to see it animate
6. Check html5 to see it stay on the first frame.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.0.168

### Which operating system(s) are you seeing the problem on?
Mac 14.4.1

### Which platform(s) are you seeing the problem on?
HTML5

[382a6a25-3232-4081-b2a2-c45864d7f055](https://api.gamemaker.io/api/github/downloads/382a6a25-3232-4081-b2a2-c45864d7f055)

**Comment by yoyo-danielc** [comment]
Fix merged into 2024.06 branch.
