### ISSUE TITLE
skeleton_animation_clear has two undocumented optional arguments

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5888]
### Description

I noticed today that skeleton_animation_clear has two optional arguments, reset and duration:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/30ae3099-266e-46aa-b28c-bbb19bc421d0)

However, neither of these arguments are mentioned on the manual page.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSprites%2FSkeletal_Animation%2FAnimation%2Fskeleton_animation_clear.htm

**Comment by YYBartT** [comment]
This was added to the manual in [#1570](https://github.com/YoYoGames/GameMaker-Bugs/issues/1570), the changes are currently in the beta manual ([skeleton_animation_clear](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Skeletal_Animation/Animation/skeleton_animation_clear.htm)). They'll go into the manual once the beta manual's contents are merged.
