### ISSUE TITLE
SVG Image Support

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#5895]
This task is to implement the importing of SVGs and the rendering of them in their native vector form rather than converting them to a bitmap.

They will be supported much like SWFs are currently in that they will not be editable in the IDE apart from a controllable level of detail which will modify how much curves are subdivided.

Unlike the current SWF support, they will be rendered as vectors in the IDE as well as at runtime.

**We will aim to support the most broadly-used SVG features, though initially some supported features may be limited and support will only be added in future releases.**

**Comment by gnysek** [comment]
There was FR for this: https://github.com/YoYoGames/GameMaker-Bugs/issues/3788 .

**Comment by Aqueuse** [comment]
This would be awesome ! The first thing I wanted to make on unity what to use some SVG. Now that I use GameMaker, it make me dreams again about the possibilities 🚀

**Comment by yymrennie** [comment]
Currently supported features in 2024.11 include:
- Common shape types such as: circle, ellipse, polygon, rect and path
- Solid-filled shapes
- Clip paths
- Anti-aliased rendering of shapes - this is controllable with three new GML functions:
  - draw_enable_svg_aa(enable) - this enables\disables anti-aliasing on SVGs.
  - draw_set_svg_aa_level(aalevel) - this sets the 'strength' of the SVG anti-aliasing as a value between 0 and 1.
  - draw_get_svg_aa_level() - this returns the strength of the SVG anti-aliasing.


Not currently supported:
- Gradients or other complex fill styles
- Shape outlines
- Line and polyline elements
- Styles defined as CSS properties
- More complex features such as text rendering, filters or SVG animation.

**Comment by jackerley** [comment]
Closing this as remaining features have been added as new issues.

**Comment by alicemoretti** [comment]
Closing this as verified. The indent functionality for 20244.11 has been in Beta for a few version and additional functionality has been planed and documented for future releases. 

Thank you.

**Comment by GianluigiCelentano** [comment]
Is there any possibility to see even the PSD import support?

**Comment by AshrafHamdi** [comment]
SVG animation is super important

**Comment by kroart** [comment]
Is svg support added in 2024.11? I see that IDE can import svg file but I'm trying to render it - it draws transparent areas with white color.

**Comment by gnysek** [comment]
It's only in beta. They wanted to polish it and add few more features before putting into monthly, but in fact basic functionality was ok.
2024.1300 has been more functionality.
