### ISSUE TITLE
In-Game: buffer_fill() causes hang when filling a buffer unevenly

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5896]
### Description

```
var buffer = buffer_create(3, buffer_fixed, 1);
buffer_fill(buffer, 0, buffer_s16, 0, 3);
```

this should produce an out of bounds error or something, but all it ding-dong-does is freeze the game up with no meaningful warning, error, or even a goodbye!

[bufferproblem.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15376510/bufferproblem.zip)

### Expected Change

it should crash the runner loquaciously

### Steps To Reproduce

1. Start GameMaker
2. make a buffer with a size of any odd number
3. fill it with values using a datatype
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly), 2024.400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.614
