### ISSUE TITLE
In-Game: Periodic slowdown without fps drop for the "step" event if the game speed is set to ~75 on a 75hz monitor

### ISSUE THREAD

**Issue by VladPavAlex** [YoYoGames/GameMaker-Bugs#5898]
### Description

I noticed this problem when I synchronized the game to my monitor frequency (75 Hz).

Occurs depending on the set frame rate of the game and only in full screen mode. At 60 and 120 there is no such problem. This manifests itself in the form of multiple staters, repeated after a certain time, which causes severe discomfort. At the same time, staters do not affect fps in any way. I also discovered that the “Memory Graph” and “GC Graph” graphs behave strangely at such moments:

![0004](https://github.com/YoYoGames/GameMaker-Bugs/assets/146189771/1588dede-fea7-4097-ba7f-9a3d22add07b)

To detect staters on HTML 5, full screen mode is not required.

Sample Project: [https://drive.google.com/file/d/1IhZfzgRYkBGoZwMlVJkRJsRlNXvxHh7W/view?usp=sharing](url)
Package: [https://drive.google.com/file/d/12GLEL2iHesGdbSQzmZLZoDpaKsnmkhq6/view?usp=sharing](url)

### Expected Change

I will be able to implement the technical part as originally planned.

### Steps To Reproduce

1. Create a project.
2. Enable "Start fullscreen" in the settings.
3. Set the "Game frames per second" parameter to 75, for long but rare stutters, with a frequency of 5 - 30 seconds, or to 77, for short but frequent stutters;
4. Create an object with a "Step" event and any code in it (you can add sprite, motion features and place more object instances, say ten, to achieve visual effect).
5. Place the object in the room.
6. Click run.
7. Wait to see the problem by watching the "GC Graph" graph or by watching for moving objects for detect.
8. Thank you!

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, HTML5

### Contact Us Package Attached?

- [x] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Hi, I've tried this on my 75Hz monitor and it runs just fine, I don't see any stuttering. It could be a driver problem with your graphics card or monitor?

<img width="656" alt="Screenshot_27" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/1914610/fc1e0278-906f-47cc-bd2a-6b4d1bac9994">
