### ISSUE TITLE
Can't update runtime

### ISSUE THREAD

**Issue by AdanGamer257** [YoYoGames/GameMaker-Bugs#5900]
### Description

I tried to update my gamemaker app, had issues last time to use that version because had a bug which made unable to run my projects (was a bug pinned here), wait and update like said in the report, tried to update my runtime, but say "Can´t complete  this operation  because this archive contains a virus" and the location of the archive is:
C:ProgramData\GameMakerStudio2\Cache\runtime-2024.4.0.168\bin\igor\windows\x64\Igor.dll

(Sorry bad translate, my app is in spanish)
![Captura de pantalla 2024-05-20 094849](https://github.com/YoYoGames/GameMaker-Bugs/assets/170343083/53d6d3b3-0099-4e54-b966-c49c25029f5e)

![Captura de pantalla 2024-05-20 085834](https://github.com/YoYoGames/GameMaker-Bugs/assets/170343083/a641be06-8e79-457e-9745-f43c72585343)

### Expected Change

I think may give me a solution to update or "delete" this archive to reinstall the runtime

### Steps To Reproduce

1. Start GameMaker
2. Wait the messege "Do you want to change your current runtime to the matching IDE version 2024.4.0.168?
3. If i press "Yes" wait a moment to install, and later show me the message "RuntimeDownloadFailed" and the error which i describe before
3.1 If I press "No" can open the app normally, but not to run my projects

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
You will need to whitelist/allow the runtime install folder inside your antivirus client, so it stops blocking the app - this isn't something we can change for you. Please see the permissions guide and then you will be able to fix this just now yourself: [User-Permissions-and-Internet-Access-Required-by-GameMaker](https://help.gamemaker.io/hc/en-us/articles/360022953052)

Once you have configured your AV settings properly, you should delete the entire runtimes folder and try downloading that set again (just in case other applications had been removed also).
