### ISSUE TITLE
Sequence Editor: Text Alignment cannot be changed if not wrapping text

### ISSUE THREAD

**Issue by gurpreetsinghmatharoo** [YoYoGames/GameMaker-Bugs#5903]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/21360237/f10d7b32-fcb4-41fa-8c49-2b650feb5811)

Alignment options are disabled if Wrap is disabled.

They should be usable, since you can enter multiline text which will need alignment.

[sequenceissue.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15384728/sequenceissue.zip)

### Expected Change

Alignment options are enabled.

### Steps To Reproduce

1. Start GameMaker
2. Create a Sequence
3. Add multiline text
4. Try to change its alignment
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Alignment options remain enabled for unwrapped text in sequence editor (consistent with room editor text items)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.580
