### ISSUE TITLE
Building Projects: [Android] Add Game Options for choosing the Gradle version to use during builds

### ISSUE THREAD

**Issue by kroart** [YoYoGames/GameMaker-Bugs#5905]
### Is your feature request related to a problem?

Currently GameMaker uses an old gradle version. When you build with target SDK 34 then compiller shows the warning:

"This Android Gradle plugin (7.4.0) was tested up to compileSdk = 33
The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34"

Also this leads to build failures with my extension that uses com.google.gms:google-services with version 4.4.+. With 4.3.xx it compiles.

When I edit files
\runtime-2024.4.0.168\android\runner\gradle\gradle\wrapper\gradle-wrapper.properties
\runtime-2024.4.0.168\android\runner\RootFiles\build.gradle
and update gradle version to an actual then it build succesfully (actualy it will fail because of absence of google-services.json file)

You can see the problem in the attached project:

1. Run attached project - it will fail with an error:
Execution failed for task ':com.game.game:mapDebugSourceSetPaths'.
> Querying the mapped value of map(flatmap(provider(task 'processDebugGoogleServices', class com.google.gms.googleservices.GoogleServicesTask))) before task ':com.game.game:processDebugGoogleServices' has completed is not supported

2. Open android extrnsion options.
3. Comment line "classpath 'com.google.gms:google-services:4.4.1'"
4. Uncomment line "//classpath 'com.google.gms:google-services:4.3.15'"
5. Run the project - it will continue compilling and will fail due to absence of file google-services.json. It's OK.

6. Switch back to classpath 'com.google.gms:google-services:4.4.1
7. Open file \runtime-2024.4.0.168\android\runner\gradle\gradle\wrapper\gradle-wrapper.properties
8. Update distributionUrl to dradle version gradle-8.6-bin.zip
9. Open the file \runtime-2024.4.0.168\android\runner\RootFiles\build.gradle
10. Update com.android.tools.build:gradle to version 8.4.1

11. Run the project - it will bypass the error in task ':com.game.game:mapDebugSourceSetPaths'

### Describe the solution you'd like

Add option to update gradle version

**Comment by kroart** [comment]
Example project: https://drive.google.com/file/d/15-1yWF2QuDJmuNk7VH-hSwt4k1KDFjcf/view?usp=sharing

**Comment by YYDan** [comment]
Note that #5906 is a simpler version of this same request and just wants the Gradle version GM relies on to be increased for all projects because extensions which already rely on the latest libraries don't build with the current Gradle GM wants.

**Comment by kroart** [comment]
> Note that #5906 is a simpler version of this same request and just wants the Gradle version GM relies on to be increased for all projects because extensions which already rely on the latest libraries don't build with the current Gradle GM wants.

Yeah. The only thing than it would be nice if next version of GM would have gradle version updated. Because currently I can not build for sdk 34 (Android 14) and google will require targetSdk to be 34 after august 2024 for all new builds.

**Comment by YYDan** [comment]
#5906 has now been done for 2024.800 Beta 3, but unfortunately this one is not possible, so closing now,
