### ISSUE TITLE
Sequence Inspector: Inspector can break when assigning a new font to a text track if there's no other font asset present

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5911]
### Description

When assigning a new font to a text track (when there's no other font present in the project) the inspector can stop displaying the correct information as shown in the clip below:

https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/9a3727e2-45c2-44d6-87b8-d949aab49eb2

### Steps To Reproduce

1. Start GameMaker
2. Open a new project/existing project
3. Create a sequence
4. Add a text track inside the sequence
5. Open the font editor
6. Change the font
7. Click on the text track from the Sequence canvas
8. See the issue

-------------
Simplified steps:

- Create a new project
- Create a new sequence
- Add a text track
- Double-click the Text on the sequence canvas
- See the issue

[sequencetexttrack.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15401727/sequencetexttrack.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.563  Runtime v2024.600.0.581
