### ISSUE TITLE
Building Projects: [Android] AndroidManifest.xml attributes are changed to invalid content in runtime 2024.4.1.201

### ISSUE THREAD

**Issue by Dragonaz** [YoYoGames/GameMaker-Bugs#5914]
### Description

Attributes in the AndroidManifest.xml file are being automatically converted to curly braces. For example `<meta-data>` element  attribute specifications are using curly braces {} around the namespace instead of the correct format. They should be in the form `android:name` but instead they are changed to `{http://schemas.android.com/apk/res/android}name`.

in my case 

```
<meta-data 
    android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" 
    android:value="true" />
```

Change to:

```
<meta-data
   {http://schemas.android.com/apk/res/android}name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" 
   {http://schemas.android.com/apk/res/android}value="true">
</meta-data>
```

And then the build fails due to:

`AndroidManifest.xml; lineNumber: 14; columnNumber: 14; Element type "meta-data" must be followed by either attribute specifications, ">" or "/>".`

[44829b4d-56f9-4ba6-a6bf-44f279691407](https://api.gamemaker.io/api/github/downloads/44829b4d-56f9-4ba6-a6bf-44f279691407)

### Expected Change

The metadata is not unexpectedly edited, therefore the project builds correctly

### Steps To Reproduce

1. Start GameMaker and import the .yyz inside [AdMob.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15404851/AdMob.zip)
2. Run/Create Exe for Android VM
3. Observe the build fails with the error described above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [x] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Hehe, did you duplicate yourself when you saw the formatting of the original report was broken? I had just fixed all of that ;)

**Comment by DiasFranciscoA** [comment]
This was now fixed in both `2024.4.1` and `develop`, please refer to the following project to test the fix:

[AdMob.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15404851/AdMob.zip)

**Comment by YYDan** [comment]
Confirmed and updated the steps, error info above.

**Comment by YYDan** [comment]
Works fine in IDE v2024.4.1.152  Runtime v2024.4.1.202.

**Comment by YYDan** [comment]
That fixed runtime has now been released, so you can update to runtime 202 and get the fix as well.

Restarting GameMaker should give you a little popup notification on the Start Page, or you can refresh Preferences yourself:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/7ec6db9b-1ebf-41a0-83e2-02b5240a4e4c)

**Comment by Dragonaz** [comment]
> That fixed runtime has now been released, so you can update to runtime 202 and get the fix as well.
> 
> Restarting GameMaker should give you a little popup notification on the Start Page, or you can refresh Preferences yourself: ![image](https://private-user-images.githubusercontent.com/15669932/332873679-7ec6db9b-1ebf-41a0-83e2-02b5240a4e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDQ2ODUsIm5iZiI6MTcxNjQwNDM4NSwicGF0aCI6Ii8xNTY2OTkzMi8zMzI4NzM2NzktN2VjNmRiOWItMWViZi00MWEwLTgzZTItMDJiNTI0MGE0ZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE4NTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZmMxYjM5Yjg2Y2U0MGMwM2M4OWY0MjhhMDgxMzMwYTMxOGFjYmYxMDFmYzQ5YTFhYzJhNWE0ZjVkYzRhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gRVKPVTb688ssrYxwaIm6wkF7Gq8-ytfAWfMYtslVl0)

its fixed now thank you for the fast reply and sorry about the duplicate i thought it was a direct report for the devs hehe

**Comment by YYDan** [comment]
All bug reports (regardless of sent inside GameMaker or written here on the website) are "direct to the devs" and go to the same place, so I am not sure what you mean there.

Thanks for confirming in your project(s) also.
