### ISSUE TITLE
"display_reset" causes rendering issues on PS4 if used with a non-zero aa value 

### ISSUE THREAD

**Issue by JonnoRobson** [YoYoGames/GameMaker-Bugs#5915]
### Description

Using `display_reset` to enable MSAA will cause the game to display a black screen on PlayStation 4.

Issue flagged in a [Zendesk ticket](https://gamemaker.zendesk.com/agent/tickets/216335), adding here for QA tracking purposes.

### Expected Change

PS4 should not display black screen when attempting to use MSAA

### Steps To Reproduce

1. Start GameMaker
2. Create an object with a Create event that calls `display_reset` with an aa value of 2
3. Add the object to the default room along with some other assets to render
4. Run the project on the PlayStation 4 target
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

PlayStation 4

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JonnoRobson** [comment]
I've fixed the initialisation of MSAA render target textures as previously the application surface and all other user surfaces were ending up as invalid render targets. I've also improved MSAA handling for PlayStation 4 so that different sample levels can be handled, where the runtime was previously defaulting to 4x samples. These changes fix the black screen issue when enabling MSAA on PlayStation 4

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.585  Runtime v2024.600.0.609
