### ISSUE TITLE
In-Game: buffer_write() being passed "undefined" for any arg will say wrong argument index in the code error message

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5918]
### Description

this bug is orthogonal to issue #5917! in short though: if you pass `undefined` to buffer_write() you're going to get an error, but the exception message has the wrong argument report no matter if you consider the arguments indexed by 1 or by 0.

![Capture](https://github.com/YoYoGames/GameMaker-Bugs/assets/44242527/f3c6a791-ab4e-46e6-9cd1-680637e89dae)

[buffer go bonk.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15404830/buffer.go.bonk.zip)

### Expected Change

it should say argument 2 or 3

### Steps To Reproduce

1. Start GameMaker
2. make a buffer
3. buffer_write() undefined to it
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
