### ISSUE TITLE
In-Game: [YYC] is_bool() still returns true when an expression uses bools as part of the calculation

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#5921]
### Description

given this code:

```
var left = choose(true, false);
var right = choose(true, true);
var up = choose(true, false);
show_message($"{is_bool(left + right * 2 + up * 4)} math {left + right * 2 + up * 4}");
```

in vm the result is that is_bool is false and the mathematical result is a number, in yyc the result is that is_bool is true and the mathematical result is 1

### Expected Change

is_bool() should return false in both vm and yyc

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

**Comment by rwkay** [comment]
YYC and VM give the same answers on the 2024.600.0.580 runtime... I think this is already fixed
