### ISSUE TITLE
Cloud file location dialog

### ISSUE THREAD

**Issue by clee2005** [YoYoGames/GameMaker-Bugs#5922]
### Description
The dialog shows up every time opening a project in a cloud location (Dropbox).   There is no Yes/No option... only OK.

### Steps To Reproduce
Open a project that is saved in a cloud location to get the warning dialog.
Try and change the setting under Preferences->General Settings->Confirm Dialogs.   See image attached.   Should be OK as automatic response, or Show Dialog.... not Yes/No

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7885d486-0701-40e6-b314-75a4d85cdcea](https://api.gamemaker.io/api/github/downloads/7885d486-0701-40e6-b314-75a4d85cdcea)

**Comment by stuckie** [comment]
This warning is there because there are many cases of cloud storage solutions locking files and otherwise getting in the way.
If you want to use this as backup, copy your project after you are finished into the storage solution so that all file locks are released.

**Comment by clee2005** [comment]
Oh is that dialog setting in preferences NOT for the cloud dialog warning
that appears when opening the project?   I was just trying to point out
that it doesn’t have the correct options in preferences as it’s an OK only
dialog, but giving YES and NO under preferences.   Ultimately there is no
control over that dialog which you seem to be confirming?
