### ISSUE TITLE
Android Build fails with AndroidManifest.xml incorrectly formatted

### ISSUE THREAD

**Issue by clee2005** [YoYoGames/GameMaker-Bugs#5936]
### Description
With this latest update there is a build issue with Android. 

with {http://schemas.android.com/apk/res/android} scattered throughout the AndroidManifest.xml file elements.

### Steps To Reproduce
Build  Android with Firebase Analytics extension to see it fail

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5c35c490-b03c-41c7-9f57-af5dbbd65497](https://api.gamemaker.io/api/github/downloads/5c35c490-b03c-41c7-9f57-af5dbbd65497)

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5914

**Comment by YYDan** [comment]
This issue is already addressed in runtime v2024.4.1.202 (it's also a sticky issue here and documented on the release notes as well). 

Please install this newer runtime version.
