### ISSUE TITLE
Diagnostics: Scrollbar allows scrolling way past the end of the messages list

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5947]
### Description
I believe this is new to today's beta. The diagnostics tab has extra empty space at the bottom that you can scroll into.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/0b0eecc1-30fc-43ed-9432-597fdcad74fc

### Steps To Reproduce
In a project with enough messages to be scrollable, scroll all the way to the bottom of the diagnostics tab.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e13dab78-d717-4bd7-8b8c-11af42fab553](https://api.gamemaker.io/api/github/downloads/e13dab78-d717-4bd7-8b8c-11af42fab553)

**Comment by stuckie** [comment]
We can't reproduce this issue on a later version.
If you are still able to reproduce it, please open a new ticket with as much information as you can.

Thanks!
