### ISSUE TITLE
CE2: Trying to write a 3 /// will cause a visual bug.

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5955]
### Description
I think this one is related to ligatures.

### Steps To Reproduce
1) Watch gif
2) Input 3 ///

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[ff366d5d-3611-466f-a8b4-c3a5784ed073](https://api.gamemaker.io/api/github/downloads/ff366d5d-3611-466f-a8b4-c3a5784ed073)

**Comment by zreedy** [comment]
Related to #6301 
Closing as Duplicate
