### ISSUE TITLE
Code Editor 2: Declarations panel does not show the static variables defined in a constructor

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5956]
### Description
I think this one is a bug if not it should be consider as a feature request.

### Steps To Reproduce
1) Open the attached proyect Lens script.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[a94c090d-e528-44a4-9549-f3d2833d6201](https://api.gamemaker.io/api/github/downloads/a94c090d-e528-44a4-9549-f3d2833d6201)

**Comment by YYDan** [comment]
Possibly related to https://github.com/YoYoGames/GameMaker-Bugs/issues/5550

**Comment by zreedy** [comment]
Not a bug, as this is working as intended. However, this ticket does highlight a blind spot.
The issue being raised here is that there is a Constructor Function declared in the script `Lens`, which then has functions and variables declared within. Those symbols are not shown in the Document Symbol Dropdown. There is currently nothing in the FSD that describes how to handle this situation and will require some further discussion before this ticket can be resolved.

**Comment by zreedy** [comment]
Discussed with the UI/UX team and it was determined that the solution to this will be to put nested symbols in the Symbols Dropdown (rightmost combobox), with nested symbols being indented under the parent symbol.

```
[V] wow
[C] Vector3
    [V] X
    [V] Y
    [F] Add
[C] Vector2
    [V] X
    [V] Y
    [F] Add
```

A future solution might be to utilize the Document Dropdown (middle combobox) to specify Constructor Function symbols nested under their respective Documents and then having even further contextual scoping under the Symbols Dropdown.
This requires further discussions, however. Documented for future purposes.

**Comment by zreedy** [comment]
Fixed
