### ISSUE TITLE
Optimize Compile-Time Functions

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5960]
### Is your feature request related to a problem?

relating to a recent addition from #5688 
There are many functions which could be optimized at compile time, which are not. To be fair the vast majority of these I don't actually see a dev needing optimized unless they are making use of macros. But a statement which runs true here "The compiler is smarter then you"

## List of additional functions
```gml
abs
angle_difference
ansi_char
base64_decode
base64_encode
code_is_compiled
color_get_hue
color_get_saturation
color_get_value
colour_get_hue
colour_get_saturation
colour_get_value
dot_product
dot_product_3d
dot_product_3d_normalised
dot_product_normalised
is_array
is_bool
is_callable
is_handle
is_infinity
is_int32
is_nan
is_numeric
is_ptr
is_struct
is_undefined
lengthdir_x
lengthdir_y
md5_string_unicode
md5_string_utf8
object_exists
object_get_name
object_get_parent
object_get_physics
object_is_ancestor
point_direction
point_distance
script_exists
script_get_name
sha1_string_unicode
sha1_string_utf8
string_byte_length
string_char_at
string_concat_ext
string_copy
string_count
string_delete
string_digits
string_ends_with
string_ext
string_format
string_hash_to_newline
string_insert
string_join_ext
string_last_pos
string_last_pos_ext
string_length
string_letters
string_ord_at
string_pos
string_pos_ext
string_repeat
string_replace
string_replace_all
string_set_byte_at
string_starts_with
string_trim
string_trim_end
string_trim_start
```

### Additional context

Feel like there is surely many more declarative functions, and thought including all of them would be best. (though annoying)

**Comment by katsaii** [comment]
Requesting you change the title to "compile-time evaluated functions" instead of "declarative statement," to avoid confusing triage on Monday.

(It's a me! Kat!)

**Comment by tinkerer-red** [comment]
lol i know it's you Kat ^^
Yeah I'll change it over.

Additionally using this comment to share the new beta documentation for compile time optimizations:
https://manual.gamemaker.io/beta/en/Settings/Runner_Details/Compiler_Optimisations.htm

**Comment by gnysek** [comment]
Don't forget: https://github.com/YoYoGames/GameMaker-Bugs/issues/5039 .

**Comment by YYDan** [comment]
From a quick glance, I think a good chunk of that list above got split off into https://github.com/YoYoGames/GameMaker-Bugs/issues/5688 and done already. 

That list at the top should be cleaned up and made accurate again before any further changes are made for _this_ issue in future.

**Comment by rwkay** [comment]
In 2024.8 we have added in 

- `angle_difference`
- `ansi_char`
- `colour_get_hue` and `color_get_hue`
- `colour_get_saturation` and `color_get_saturation`
- `colour_get_value` and `color_get_value`
- `dot_product`
- `dot_product_3d`
- `dot_product_normalized`
- `dot_product_3d_normalized`
- `point_direction`
- `point_distance`
- `lengthdir_x`
-  `lengthdir_y`
- `string_trim`
- `string_trim_end`
- `string_trim_start`
- `string_length`
- `string_byte_length`

Open a new bug for any other functions that you think make sense at compile time

**Comment by YYDan** [comment]
Cleaned the list and updated the report.

**Comment by sihammill** [comment]
After running performance tests on 2 versions of the Beta IDE, I can clearly see there is some improved times when running all of the above functions. Tests were run on the same machine using the GM Benchmark tool

- https://github.com/yoyo-qa/Benchmark-Tool

IDE versions tested were

- 2024.600.0.560
- 2024.800.0.595
