### ISSUE TITLE
Code Editor 2: Globals appear in instance variable color

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5963]
### Description
Globals are now appearing in instance variable color instead of global color

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f22cbee7-d359-4f3e-a64a-f2a20988bc18)

### Steps To Reproduce
Declare a global variable

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[15c52a47-0a9b-4ca0-8ba1-d8c3e4a96aef](https://api.gamemaker.io/api/github/downloads/15c52a47-0a9b-4ca0-8ba1-d8c3e4a96aef)

**Comment by zreedy** [comment]
Fixed

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.592  Runtime v2024.800.0.616
