### ISSUE TITLE
GMLSpec incorrectly uses `audio_3D`

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5966]
### Description

The constant is actually `audio_3d` with a lowercase `D` this causes autocomplete to break, and will fail a compile if used.

### Expected Change

`audio_3d`

### Steps To Reproduce

var _i = audio_3d;
var _j = audio_3D; //crashes on this line

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by tabularelf** [comment]
Manual also states it as `audio_3D`. https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/Audio_Buffers/audio_create_buffer_sound.htm

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
