### ISSUE TITLE
`asset_particlesystem` doesnt highlight

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5967]
### Description

doesn't highlight, but it compiles just fine, and is even included in the gmlspec
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/677b51a3-3fdd-4354-a200-4fd9c7290fb0)

### Expected Change

highlight `asset_particlesystem`

### Steps To Reproduce

type `asset_particlesystem`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.561  Runtime v2024.600.0.579
