### ISSUE TITLE
CE2: Feather simply just not work when using the Match 3 Template

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5969]
### Description
the title say it. 1 minute of use checking the objects.

### Steps To Reproduce
1) Use the Match 3 Template with CE2 editor.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[850e2548-660f-4b26-a87c-76a6d2e0b86a](https://api.gamemaker.io/api/github/downloads/850e2548-660f-4b26-a87c-76a6d2e0b86a)

**Comment by Totobal5** [comment]
It appear that this bug happen when many projects in the template section:

this error appear in the Fire Jump Template

![firefox_BNYAOTlBkA](https://github.com/YoYoGames/GameMaker-Bugs/assets/90012149/2bc3855c-9493-4d46-b883-d37eef48d78c)

**Comment by zreedy** [comment]
Unable to reproduce. Suspected fix via other tickets.
