### ISSUE TITLE
Code Editor 2: Cannot edit any code in a specific "obj_playfield_parent" object in my project using 2024.600 IDEs

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5970]
### Description
I cannot write in the object: obj_playfield_parent. There no appear to be something that block the writing inputs.

I cannot copy/cut and paste in the CE2 trying to edit that object.

### Steps To Reproduce
1) Open Match 3 Template.
2) Try to write code in the obj_playfield_parent.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[05ca2c0b-5369-499b-9d62-855128be9609](https://api.gamemaker.io/api/github/downloads/05ca2c0b-5369-499b-9d62-855128be9609)

**Comment by zreedy** [comment]
Unable to reproduce. I suspect this issue was related to a problem where workspace focus was stolen due to issues in the Hotkey Subsystem which have now been fixed.
