### ISSUE TITLE
HomePage: When trying to create a project using the templates, the scroll bar and "ui box" are out of bound

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5971]
### Description
That its, when trying to create a tempalte project the "box" of the option are out of bound (see image)

### Steps To Reproduce
1) Try to create a new project using the template runner or match 3.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[45ff0fee-50fb-46f5-bc48-db12f5ba439c](https://api.gamemaker.io/api/github/downloads/45ff0fee-50fb-46f5-bc48-db12f5ba439c)

**Comment by yyalansavage** [comment]
Unless I have misunderstood something - this is as-designed, the bottom edge of the green ui-box is deliberately not shown and no actual content is clipped/off-screen. So for the time being I think we will make no changes here; but thank you for taking the time to make a report your feedback is of course much appreciated :)

**Comment by mgeddesGM** [comment]
verified as no change as per @yyalansavage's comment
