### ISSUE TITLE
CE2: Weird interactions when using multi-line function

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#5972]
### Description
if you use the multiline function (shift+arrow keys) it will start working weird using the tab or press keys.

### Steps To Reproduce
1) Watch video.
2) Go to oIchigo_FX_00 object step event line 10.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[cfdbfa90-1a26-44e2-834a-a072ff1d72c2](https://api.gamemaker.io/api/github/downloads/cfdbfa90-1a26-44e2-834a-a072ff1d72c2)

**Comment by zreedy** [comment]
Fixed in .800 beta

**Comment by caitlinrmcintyre** [comment]
Verified in IDE v2024.800.0.602  Runtime v2024.800.0.624, thanks.
