### ISSUE TITLE
CE2 - I greatly miss bundling several scripts in the same tab

### ISSUE THREAD

**Issue by Ailwuful** [YoYoGames/GameMaker-Bugs#5975]
### Is your feature request related to a problem?

I love what the new Code editor is going for, but I severely dislike the workflow of switching between different objects or scripts.
Right now in the new code editor you can select a different script/object in the CE2 selection tab on top (or other positions), or you can just open several tabs for each script/object. Switching between objects or scripts require a lot of clicks, or clicking in specific places. Using ctrl+tab is also much slower than it was before and would take too many tabs open on top. It takes so much time out of my usual workflow.

### Describe the solution you'd like

What I'd love to get is basically like in the screenshot. We had a second header that we can put any object event or script and navigate between them with ctrl+pageUp/Down. Even in the workspace I thought it was quicker to switch between windows with ctrl+tab or just moving around the workspace with the mouse, faster than what we have now with the new code editor. I'd love to still have this second header tab to switch between scripts or objects. This is a pretty big deal to me.
![imagem_2024-05-25_175322674](https://github.com/YoYoGames/GameMaker-Bugs/assets/93070196/4da462f4-8d0e-4c57-bebe-673d13021b6a)

**Comment by stuckie** [comment]
This is not something we are planning at this moment.
The Code Editor 2 is still in beta.
