### ISSUE TITLE
Networking: [Websocket] [Windows] Cannot connect to a websocket server, when specifying a querystring parameter in the URL

### ISSUE THREAD

**Issue by manuel-di-iorio** [YoYoGames/GameMaker-Bugs#5978]
### Description

When appending a querystring parameter in the connection URL, you can't connect to a websocket server with GameMaker. This is something that correctly works by using Postman or another websocket client. 

(Nice to have) There could be also a way to attach connection headers in the request.

```gml
var socket = network_create_socket(network_socket_ws);
network_connect_raw_async(socket, "ws://localhost?something=true", 8080);
```

This is the Node.js server code if you want to test yourself the connection:

```js
// Install 'ws' module from npm
const { WebSocketServer } = require('ws');
const wss = new WebSocketServer({ port: 8080 });
wss.on('connection', async (ws, req) => {
  console.log("Client connected. URL: " + req.url);
});
```

---

Contact Us Package: https://drive.google.com/file/d/1jSy2sgNGiuj9bJOPprfDCsz9bBC1rnw7/view?usp=sharing

### Expected Change

Successfully connect to a websocket server, that includes a querystring in the url

### Steps To Reproduce

1. Start GameMaker
2. Write the code in the description in a Create event of an object
3. Run the game with that object in a room
4. See the issue that you cannot connect

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Well-formed URLs should include a slash between the hostname and query string (e.g. `ws://localhost/?something=true`), which appears to work in GameMaker.
