### ISSUE TITLE
[GLSL ES] Major memory leak for shader function with the same name as a variable

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#5985]
### Description
For some strange reason, the shader compiler doesn't warn me about a name conflict when used with a variable and a function in a shader. And while I cannot definitely tell what is going on, the game hangs up on `DirectX11: Using hardware device` and my RAM utilisation goes through the roof. But, this only really happens on the second run of the game, not the first. And this happens even in a completely blank project

This is 100% reproducible on Windows (I haven't checked the other platforms).

### Steps To Reproduce
1. Pull up task manager, on the performance tab.
2. Run the project *once*.
3. Once the game window pops up, close it and run it again.
4. Witness that the game is now stuck on `DirectX11: Using hardware device`.
5. See RAM utilisation skyrocket. (For me it took about ~3 seconds to skyrocket straight to the remaining 50% of my RAM usage... And that's with 64GB total.)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[5ec10713-6590-4083-ba49-ca330bd60104](https://api.gamemaker.io/api/github/downloads/5ec10713-6590-4083-ba49-ca330bd60104)

**Comment by JonnoRobson** [comment]
This issue was caused by cached shader files from the previous project build that were left over when the original run produced a shader error. I've fixed the issue by ensuring that failed shader files are deleted from the cache after building so that they will be correctly rebuilt the next time the project is run.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.592  Runtime v2024.800.0.616
