### ISSUE TITLE
[Android] compressed streamed audio cannot play when Google Dynamic Asset Delivery is enabled

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5987]
### Description
The attached sample has two audio files with the same source audio, but the attributes are set differently. When exporting for aab with Google Dynamic Asset Delivery enabled, the compressed streamed audio cannot play.

This does not happen on Windows or iOS export.

### Steps To Reproduce
1. Change the Android options setting's Pacakge information to an appid that is publishable on Google Internal App Share https://play.google.com/console/u/0/internal-app-sharing/
2. Build the app for Android aab export
3. Upload to Google Internal App Share and download it on a test device
4. Launch the app
5. Tap the screen to toggle between the 2 audio tracks and observe that the compressed track does not play but the uncompressed track plays fine.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.556 Runtime v2024.400.0.571

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android

[2ba6beb1-4e4b-47cd-a658-9ef2e60d217d](https://api.gamemaker.io/api/github/downloads/2ba6beb1-4e4b-47cd-a658-9ef2e60d217d)

**Comment by shichen85** [comment]
Might be a regression of https://help.yoyogames.com/hc/requests/184173

**Comment by toby-yoyo** [comment]
Fixed an issue where some preconditions to retrieving dynamically delivered assets were failing.

**Comment by mgeddesGM** [comment]
will need to test another time as seems an issue with google's webpage after upload

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.585  Runtime v2024.600.0.609

used this method

1. if you don't already have the Java Development Kit (JDK) then you'll need to install that: https://download.oracle.com/java/22/latest/jdk-22_windows-x64_bin.msi
2. Download bundletool: https://github.com/google/bundletool/releases/download/1.17.0/bundletool-all-1.17.0.jar
3. Uninstall any 'Created with GameMaker' game from your device
4. Export the game as an aab from GM
5. Run java -jar "path\to\bundletool" build-apks --bundle="path\to\aab" --output="\path\to\aab-but-change-the-ext-to-apks"  to extract the apks from the aab
6. Run java -jar "path\to\bundletool" install-apks --apks="path\to\apks" --adb="C:\AndroidSDK\platform-tools\adb.exe"  to deploy to your device
7. The app should appear on your device now so you can run as normal
