### ISSUE TITLE
New Code Editor - Changing event type does not save changes until closing/reopening object

### ISSUE THREAD

**Issue by hasnogame** [YoYoGames/GameMaker-Bugs#5988]
### Description
When changing the event type within an object using the new code editor it will not save changes until the object is closed and then reopened.

### Steps To Reproduce
- Ensure new code editor is enabled
- Create and open an object
- Create an event and add code into it
- Save the object
- Change the event type
- Try to save, the "Pending save" asterisk will stay visible in the object's name in the editor tab
- Close the object
- Reopen the object
- Event type will be changed and any changes made to the event's code will not have been saved

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[f50b1d94-695f-4790-b5f6-13c81d5ea2eb](https://api.gamemaker.io/api/github/downloads/f50b1d94-695f-4790-b5f6-13c81d5ea2eb)

**Comment by zreedy** [comment]
Fixed. The following additional rename operations were also affected by this bug:
- Room Instance Creation Code - Renaming a room instance
- Moments - Changing a moment
- Sequence Events - Changing events

**Comment by caitlinrmcintyre** [comment]
Verified in IDE v2024.800.0.602  Runtime v2024.800.0.624, thanks.
