### ISSUE TITLE
Marketplace Package Import Confuses File Names

### ISSUE THREAD

**Issue by EnderOnryo** [YoYoGames/GameMaker-Bugs#6005]
### Description
When importing the sprites from `Pixel Adventure 1` & `Pixel Adventure 2` the importing tool noticed that some of the sprites shared the same filename, prompting me to keep or replace the old one. However the old sprite was in a different file directory and not related to the new sprite in any way other than name.

### Steps To Reproduce
Import a/an asset(s) from the Marketplace that have the same file name as an asset already present in your project. 

Note: I only tested with this one instance and do not know if it's somehow unique to these specific packages due to something like them sharing a developer or something else.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[79d2418e-fa80-4714-a8b7-6a743a4a1c3f](https://api.gamemaker.io/api/github/downloads/79d2418e-fa80-4714-a8b7-6a743a4a1c3f)

**Comment by stuckie** [comment]
All resources must have unique names across the project, so this is correct.
