### ISSUE TITLE
show_debug_message crashes when printing "% s" on Ubuntu

### ISSUE THREAD

**Issue by realDragon11** [YoYoGames/GameMaker-Bugs#6006]
### Description

`show_debug_message("% s");` crashes the game when run. This character sequence crashes the game even when printed with other text, as long as they are uninterrupted and in order.

No error message is raised, no extra logs are printed, and the non-zero status message 127 is the only evidence anything happened.

[gamemaker_report.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15461750/gamemaker_report.zip)

### Expected Change

The game to not CTD, and print % s to console

### Steps To Reproduce

1. Start GameMaker
2. add `show_debug_message("% s");` to starting room creation code or an object that runs
3. Compile
4. The game with load then immediately CTD

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Ubuntu

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed on 2024.06 branch.

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.600.0.563  Runtime v2024.600.0.582.
