### ISSUE TITLE
Code Editor 2: Keys like enter, backspace, etc. will stop working while holding shift if you type something else without letting go of shift

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6007]
### Description
If you do something like hold shift, press space or a letter key, and then press backspace without letting go of shift, the backspace will not be registered. Pressing backspace while shift is held without typing something else in between will work fine. 

This probably also applies to all the other similar keys that have been affected by these kinds of input bugs recently, like ctrl+c, ctrl+v, ctrl+a, page up, page down, etc. though I can't fully test since some of them are still having other issues.

### Steps To Reproduce
Hold shift, and without releasing it, press backspace or enter (will register), then press space, and then press backspace or enter again (will not register)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c7be4c1d-a2d9-44c4-ba37-73ed5f60533e](https://api.gamemaker.io/api/github/downloads/c7be4c1d-a2d9-44c4-ba37-73ed5f60533e)

**Comment by zreedy** [comment]
@SmithTom6304 Looking into this one it might be a good idea to demote solo SHIFT from being a chord signifier. CTRL, ALT can remain, but SHIFT often times is used in ways which look like chords but are normal text input.

**Comment by zreedy** [comment]
Shift can still be a modifier, just we don't track chords with just shift held.

**Comment by SmithTom6304** [comment]
Solo shift has now been removed as a hotkey chord signifier. So:
`Shift + A => Shift + B` is no longer valid, but `Ctrl + Shift + A => Ctrl + Shift + B` is.

Solo shift is used to modify text input, and there is no way for us to discern between the two.
We'll want to update the manual with this change.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.584  Runtime v2024.600.0.608
