### ISSUE TITLE
Applying a matrix to draw_tilemap to draw it at a reduced scale onto a surface will only draw the top left of the tilemap if it is large

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6008]
### Description
I'm trying to create sprites out of the tilemaps in my rooms, so I can trace over them to create map sprites for my map system. I can't just draw the tilemap on a surface and then sprite_create_from_surface --> sprite_save directly, because some of my rooms are larger than the maximum texture size. So, it was suggested to me to use a matrix to draw the tilemap at a reduced scale. However, doing this will only draw the top left-most portion of the tilemap.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/71a70cec-acd7-475b-ab73-0d03fa6ff52e

The tilemap does not get cut off if the surface itself is the full size of the room, but I cannot do that because surfaces of that size are impossible.

### Steps To Reproduce
In the sample project, add a breakpoint in the draw code of Object1. Run with the debugger, then press space. Use the debugger's surface view to see that the surface only had part of the tilemap drawn on it.
You can also look at the final sprite that is saved, it is cut off in the same way.

You can change this line
```
 testSurf = surface_create(room_width * scale, room_height * scale);
```
to this
```
 testSurf = surface_create(room_width, room_height);
```
and then reduce the room size to 15000, 15000, and then preview the surface again to see the full tilemap being drawn.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e4d3ce61-d088-4b69-9246-1f01038a3a7c](https://api.gamemaker.io/api/github/downloads/e4d3ce61-d088-4b69-9246-1f01038a3a7c)

**Comment by jackerley** [comment]
Hi, if you are using a recent beta and add gpu_set_sprite_cull(false); before drawing your tilemap, you should see the full tilemap rendered 
![mapRoom1 (2)](https://github.com/YoYoGames/GameMaker-Bugs/assets/1914610/3d66abde-3e68-45d8-811a-5143393521f4)
