### ISSUE TITLE
Can't get past this Android Error Message below using Jellyfish, SDK 34 and NDK 26.3

### ISSUE THREAD

**Issue by SBogatz** [YoYoGames/GameMaker-Bugs#6009]
### Description
* What went wrong:
Execution failed for task ':com.bofrogames.aif:generateDebugBuildConfig'.
> Error while evaluating property 'versionCode' of task ':com.bofrogames.aif:generateDebugBuildConfig'
   > Failed to calculate the value of task ':com.bofrogames.aif:generateDebugBuildConfig' property 'versionCode'.
      > org.xml.sax.SAXParseException; systemId: file:/C:/Users/sboga/AppData/Roaming/GameMakerStudio2/Cache/GMS2CACHE/ApolloAnnT_6A572179_E7D6C869/android/Default/com.bofrogames.aif/src/main/AndroidManifest.xml; lineNumber: 13; columnNumber: 14; Element type "meta-data" must be followed by either attribute specifications, ">" or "/>".

### Steps To Reproduce
Trying to build for Android

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Android

[95544636-0617-4930-8660-7459409a3592](https://api.gamemaker.io/api/github/downloads/95544636-0617-4930-8660-7459409a3592)

**Comment by stuckie** [comment]
You will need to use runtime 2024.4.1.202
