### ISSUE TITLE
[iOS] audio_exists() crashes the runner when the sound index is out of range

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6011]
### Description
audio_exists() crashes the runner when the sound index is out of range. On Windows, it does not crash the runner but logs the error `invalid vector subscript`. On iOS, it crashes the runner.

### Steps To Reproduce
1. Run the sample for dev config for iOS export
2. Observe crash
3. The offending line is at https://github.com/bscotch/ganary/blob/7978d928406baa69d0940553c8e7e457eabd600f/Ganary/scripts/grc_register_sync_function_tests/grc_register_sync_function_tests.gml#L204

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
iOS

[5a7092ef-57d9-465f-bcca-56cecf3131d4](https://api.gamemaker.io/api/github/downloads/5a7092ef-57d9-465f-bcca-56cecf3131d4)

**Comment by shichen85** [comment]
Seems to be an regression of https://github.com/YoYoGames/GameMaker-Bugs/issues/1753

**Comment by toby-yoyo** [comment]
This was indeed a regression of #1753, which has now been fixed.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.600.0.584  Runtime v2024.600.0.608.
