### ISSUE TITLE
Building Projects: [HTML5] Having 'Pretty Print' disabled on Platform Settings makes projects crash

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6014]
### Description

On Beta IDE v2024.600.0.560 Beta Runtime v2024.600.0.577 if the 'Pretty Print' option is turned off (off by default) any HTML5 build will fail wit the following error on console:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/6c018777-4468-4992-bdad-ef3ce992615b)

[html5_pp.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15467426/html5_pp.zip)

### Steps To Reproduce

1. Start GameMaker
2. Make sure you have 'Pretty Print' unchecked from HTML5 preferences
3. Build any project targeting HTML5
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Which platform(s) are you having trouble building this project for?

HTML5

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by toby-yoyo** [comment]
I no longer see the error with that fix above, so I'm going to close this as resolved.

**Comment by Emc1923** [comment]
Verified fixed in IDE v2024.600.0.561  Runtime v2024.600.0.579.
