### ISSUE TITLE
Source Control Conflcts window opening when source control is not enabled

### ISSUE THREAD

**Issue by chuuuuuuuck** [YoYoGames/GameMaker-Bugs#6025]
### Description
In my project I'm using github desktop for my source control, and for a while that was working, but now all of a sudden gamemaker keeps popping up this window, telling me that there is a source control conflict. 

It gives me the options to use theirs, use mine, or merge, but no matter what I press nothing happens. Sometimes, but not all the time, it will also create copies of the file with the file extention .theirs,  .mine, or .base. Closing the window works, but it will just reappear the next time I run the game or change something in the project. I've resorted to pulling the source control conflicts window into its own gamemaker instance, so I can just minimize it.

Whats worse, is that it seems to stop github desktop from letting me commit changes, despite having resolved all merge conflicts. The only fix is to discard whatever changes I made to the object that shows up in the source control conflict window, then it'll let me commit/push.

Extremely frustrating.

### Steps To Reproduce
A merge conflict will show up in github desktop. I will then resolve it by opening visual studio code, choosing which version of conflict I want to keep, then saving the file. The file will then show as resolved. Then, whether I reload the project or restart gamemaker entirely, the Source Control Conflict window will pop up and stop me from being able to commit any changes. Source control is disabled on gamemaker, and noone else with source control access has ever enabled it either.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[0d716259-84db-4976-9c98-314255a9c97d](https://api.gamemaker.io/api/github/downloads/0d716259-84db-4976-9c98-314255a9c97d)

**Comment by stuckie** [comment]
I see that there is no project attached here, could you attach an example please? ( or for privacy, upload to Google Drive and let us request access, invite us on GitHub, etc... )
This is to ensure that the source control option in main options is actually off and is represented in the IDE properly, in case it's been corrupted slightly.
The only time where we *force* a check on whether there are conflicts is on importing from another project, and the initial project load - and technically it's done before we attempt to load the project.
All others are guarded against by both Source Control being setup in Preferences and the option enabled in the Project's Main Options.

You can completely disable the Source Control integration in Preferences by setting an empty path for the path to git, if you prefer that as well - which may be wise if you have competing git clients, which is what this sounds like.
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/795290/9193f664-aad9-4eab-bd05-0a31caa68c3f)

**Comment by chuuuuuuuck** [comment]
> I see that there is no project attached here, could you attach an example please? ( or for privacy, upload to Google Drive and let us request access, invite us on GitHub, etc... ) This is to ensure that the source control option in main options is actually off and is represented in the IDE properly, in case it's been corrupted slightly. The only time where we _force_ a check on whether there are conflicts is on importing from another project, and the initial project load - and technically it's done before we attempt to load the project. All others are guarded against by both Source Control being setup in Preferences and the option enabled in the Project's Main Options.
> 
> You can completely disable the Source Control integration in Preferences by setting an empty path for the path to git, if you prefer that as well - which may be wise if you have competing git clients, which is what this sounds like. ![image](https://private-user-images.githubusercontent.com/795290/334838775-9193f664-aad9-4eab-bd05-0a31caa68c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzY5MzgsIm5iZiI6MTcxNzAzNjYzOCwicGF0aCI6Ii83OTUyOTAvMzM0ODM4Nzc1LTkxOTNmNjY0LWFhZDktNGVhYi1iZDA1LTBhMzFjYWE2OGMzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMjM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmIxZjhjZDMwMDNiZjU2OTFiNWRkNjRhN2UwOTRlYzcxMGJkMTY5ZTc5ZjE1MWE5YmQyNDQ4NmRhNzQxZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZB5imH-U1Ve5cSkvTOxbES9HR-XpmfnUtfYr9iXWQ1o)

I've set an empty path in source control preferences and that seems to have worked in disabling the popup. I am also now able to push my changes. 

I've invited you to the repo but, this is the options_main,yy file of the project and it shows source control as disabled.
![Screenshot_41](https://github.com/YoYoGames/GameMaker-Bugs/assets/54994548/fd54863d-41fa-4215-b65b-e006807c7d7c)

Regardless, thank you for the help!

**Comment by stuckie** [comment]
Found it... we trigger a status update on project save that wasn't guarded, which as part of that, we check for conflicts and bring up the conflict window. So, yes, options and project in general was fine as you've shown above.

Will get this fixed.
You can remove me from your repo, thanks!

**Comment by alicemoretti** [comment]
@chuuuuuuuck 

This is issue seems fixed on our end but could you please confirm that is also fixed on your project in the latest version ( IDE v2024.6.0.157 Runtime v2024.6.0.205 ) .

Many thanks

**Comment by sihammill** [comment]
Fix verified in IDE v2024.6.1.160  Runtime v2024.6.1.208
