### ISSUE TITLE
Code Editor 2: Config macros appear grey instead of the expected macro colour

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6032]
### Description
If a macro is set up as a config macro, it will be grey everywhere it is used instead of red.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/34cb81eb-34b5-4d46-ada8-e1436454d67c)

### Steps To Reproduce
```
#macro stuff true
#macro Config1:stuff false
#macro Config2:stuff true
	
	
if stuff { //will be grey
	
}
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[662dee45-7aaa-4c59-9f60-9dad7e183446](https://api.gamemaker.io/api/github/downloads/662dee45-7aaa-4c59-9f60-9dad7e183446)

**Comment by zreedy** [comment]
Fixed.
Two issues comprised this ticket:
- Config and Name tokens of a macro expression were not yielded in the sm token stream as Macro tokens
- BooleanExpressions were not yielded as macro tokens in the sm stream if a MacroReference was set

**Comment by caitlinrmcintyre** [comment]
Verified in IDE v2024.800.0.594  Runtime v2024.800.0.618, thanks.
