### ISSUE TITLE
In-Game: Code error "Attempting to set Instance id with Object Index 19 (obj_bullet) with invalid bound top" when running attached project in 2024.4.1

### ISSUE THREAD

**Issue by Four-amer** [YoYoGames/GameMaker-Bugs#6039]
### Description
After i upgraded from IDE version 2023.11.1.129 to 2024.4.1.152 i get a code error message whenever the shotgun type enemy shoots towards a player character, it does not happen when any other enemy type shoots. Code error appears during the first If statement in the step event in the bullet object. I've tried modifying the If statement and even removed it but it then the error appeared in the next If statement. I'm leaving the project as it was before trying any fixes for this problem/

Here is the code error:
___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_bullet:

Attempting to set Instance id 103841 with Object Index 19 (obj_bullet) with invalid bound top -nan(ind) bottom -nan(ind) left -nan(ind) right -nan(ind)
 at gml_Object_obj_bullet_Step_0 (line 4) - if !bbox_right || !bbox_bottom || (bbox_left>=room_width) || (bbox_top>=room_height)
############################################################################################
gml_Object_obj_bullet_Step_0 (line 4)

### Steps To Reproduce
Navigate in main menu with arrow keys, space for confirm, start the game, then go up (arrow keys). i placed a shotgun enemy there, he shoots and then the code error message appears.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[3f76eb00-fda9-4a21-bb80-e50571b0df6c](https://api.gamemaker.io/api/github/downloads/3f76eb00-fda9-4a21-bb80-e50571b0df6c)

**Comment by KormexGit** [comment]
That error can appear if something like image_angle gets set to NaN, usually due to being divided by 0 on accident somewhere. Probably an error in the code rather than an actual GM bug

**Comment by mgeddesGM** [comment]
relevant error now shows

verified as of  IDE v2024.600.0.584  Runtime v2024.600.0.608
