### ISSUE TITLE
CE2 - Incorrect Indentation

### ISSUE THREAD

**Issue by michael-mcmullen** [YoYoGames/GameMaker-Bugs#6052]
### Description
After creating a new event you are placed beside the gutter, after writing a line you are indented inward

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.562 Runtime v2024.600.0.581

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c72baa60-a09d-4d0f-b7a4-5d1c19174ade](https://api.gamemaker.io/api/github/downloads/c72baa60-a09d-4d0f-b7a4-5d1c19174ade)

**Comment by zreedy** [comment]
Fixed in .800 beta

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.599  Runtime v2024.800.0.622

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.599  Runtime v2024.800.0.622
