### ISSUE TITLE
Constructors can't resolve default variables that reference containing obj.

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#6057]
### Description
It's possible this isn't a bug, and works as intended. but I find it confusing.

a standard method can reference the containing object's variables to pass in default variables.

But if constructors try to do that, they crash.

It would make more sense to me if they worked the same.

### Steps To Reproduce
see attached project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[7f59a04d-3abc-40f7-af12-fda119e5551c](https://api.gamemaker.io/api/github/downloads/7f59a04d-3abc-40f7-af12-fda119e5551c)

**Comment by thennothinghappened** [comment]
I'm assuming you're talking about something like this:

```js
function thing(arg = self.some_value) { // ok!
    // ...
}

function Thing(arg = self.some_value) constructor { // boom
    // ...
}
```

Constructors are just functions that let you use `new`, which basically just binds them to their own struct. `self` always just means the current struct context. When you run a function in an object, it'll automatically run it bound to the object's `self` struct, a bit like this behind the scenes:

```js
method(self, thing)();
```

...But for a constructor, calling new is a bit like this:
```js
method({}, Thing)();
```

So in the context of that constructor, `self` means its own struct - including in the default arguments, which you could see a bit like this behind the scenes too:

```js
function Thing(arg) constructor {
    var arg ??= self.some_value; // boom
    // ...
}
```

This isn't an entirely accurate representation of what's actually going on, but I hope it makes it a bit clearer. Personally I think the current behaviour makes sense - I'd also be avoiding referencing `self` in default arguments, but that's your pick. I'd also bring up the `other` keyword: if you think about the current struct "scope" as a stack, then `self` is the current one, and `other` is the most recent previous scope you've jumped from. In the case of a constructor, `other` will point to the calling object, and should do what you're wanting:

```js
function Thing(arg = other.some_value) constructor { // ok!
    // ...
}
```

**Comment by AvioxArcade** [comment]
That's super helpful clarification, @thennothinghappened 
Thanks for taking time to spell that out for me.

**Comment by rwkay** [comment]
This is intended as the `self` that is in scope at the start of the constructor function is the `self` of the newly constructed thing - not the `self` at the point of the `new` getting called
