### ISSUE TITLE
Code Editor 2: Windowed Workspace view

### ISSUE THREAD

**Issue by Lukanibal** [YoYoGames/GameMaker-Bugs#6060]
### Is your feature request related to a problem?

It's jarring to have thrown away the workspace when object are opening in the new code editor.
I find it hindering my workflow honestly.

### Describe the solution you'd like

I'd suggest something like the new Code Editor having a maximise button like current code windows, and starting them in windowed view on the workspace.
Like imagined here: https://forum.gamemaker.io/index.php?threads/2024-600-betas-release-thread.112784/post-672483

### Describe alternatives you've considered

Not using the new code editor I guess?

**Comment by stuckie** [comment]
We are not yet finished updating how our window system works with Code Editor 2.
