### ISSUE TITLE
physics_particle_group_begin expects wrong parameter type

### ISSUE THREAD

**Issue by old-rob** [YoYoGames/GameMaker-Bugs#6068]
### Description

The function `physics_particle_group_begin` expects the argument "col" to be type "Bool", despite the documentation and description clearly stating that it should be a Colour.

![bool_expected](https://github.com/YoYoGames/GameMaker-Bugs/assets/42311776/0821253a-b42a-446c-bc08-216b1c0eb6b7)
![physics_particle_group_begin](https://github.com/YoYoGames/GameMaker-Bugs/assets/42311776/9d1f79f4-ba7f-4c12-9611-d6d6771a7491)

### Steps To Reproduce

1. Start GameMaker
2. Make an object and edit the create event
3. type 'physics_particle_group_begin(phy_particle_flag_water, phy_particle_group_flag_solid, mouse_x, mouse_y, 0, 0, 0, 1, c_green, 1, 1, 2);'
4. See the issue

[contact.zip](https://github.com/user-attachments/files/15515908/contact.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.569  Runtime v2024.600.0.596
