### ISSUE TITLE
Code Editor (Visual): If Object At Place, If Collision Shape, and If Collision Point all cause in-game memory leaks if their "Free Target" option is checked

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6069]
### Description
If you use a collision block in visual and check both "return list" and "free target", the generated GML code will have a memory leak. This is because it still runs `is_real(list)` before destroying the list, which will never be true due to the recent ref changes.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/ed1235db-056f-4b4d-b399-14bdf2211f32)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/5c5cb7f6-813d-40dd-b011-d582dd882e19)

### Steps To Reproduce
Add the "If object at place" block. Check "return list", set "free target" to true, and set "target" to a variable set in the create event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[ac8b2660-9c6b-4150-87a1-dd721645fb4a](https://api.gamemaker.io/api/github/downloads/ac8b2660-9c6b-4150-87a1-dd721645fb4a)

**Comment by mgeddesGM** [comment]
still present as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605

**Comment by mgeddesGM** [comment]
retested and the issue was gone when new blocks, inc obj +at place, were used in the sample project Beta IDE v2024.600.0.579  Runtime v2024.600.0.605

**Comment by YYDan** [comment]
For anyone who has this issue - you do actually need to delete your existing copies of these Visual nodes and re-add them in order to pick up this fix!
