### ISSUE TITLE
Call of Find and Replace with Ctrl + H deletes selected word

### ISSUE THREAD

**Issue by Notlea** [YoYoGames/GameMaker-Bugs#6074]
### Description
I'm using basic function of Find and Replace with Ctrl + H shortcut. It deletes selected text when used. 
I don't have any modifications to basic IDE shortcuts.

Reproduces on any of mine projects, so shouldn't be project related issue.

### Steps To Reproduce
1. Select any text in code editor 
2. Press Ctrl + H
3. Observe results

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[bdd77caf-69eb-4123-8008-cd70696f3f2c](https://api.gamemaker.io/api/github/downloads/bdd77caf-69eb-4123-8008-cd70696f3f2c)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.565  Runtime v2024.600.0.585
