### ISSUE TITLE
MacOS: Unchecking "Allow fullscreen switching" has no effect

### ISSUE THREAD

**Issue by prtksxna** [YoYoGames/GameMaker-Bugs#6082]
### Description

With the runtime `2023.8.2.152` both on YYC and VM, when you build the game for MacOS with the "Allow fullscreen switching" as unchecked you are still able to switch to non-full screen by pressing <kbd>Cmd</kbd>-<kbd>Control</kbd>-<kbd>F</kbd>.

(not included Contact up package because I can't find how to make it private)

### Expected Change

Toggling fullscreen should be disabled for the user

### Steps To Reproduce

1. Start GameMaker
2. Make a build with the "Allow fullscreen switching" setting switch off
3. Pressing <kbd>Cmd</kbd>-<kbd>Control</kbd>-<kbd>F</kbd>
4. Notice that you can toggle out of full screen

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed in 2024.10 branch.

Test project: [fullscreen_test.yyz.zip](https://github.com/user-attachments/files/16659455/fullscreen_test.yyz.zip)

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.626  Runtime v2024.1100.0.652.
