### ISSUE TITLE
New Timeline function timeline_execute

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#6083]
### Is your feature request related to a problem?

Currently, an object instance in GameMaker can only have one [Timeline](https://manual.gamemaker.io/lts/en/GameMaker_Language/GML_Reference/Asset_Management/Timelines/Timelines.htm) assigned to it.

Timelines are useful for storing logic, which can include behavior or time-based triggers.

However, it's not possible to use multiple timeline instances with a single object instance.

### Describe the solution you'd like

I request adding a function:

```gml
timeline_execute(instance_id, timeline_id, timeline_position);
```

This function will execute the code at `timeline_position` from `timeline_id` in the context of `instance_id` if the specified `timeline_position` exists within `timeline_id`, and do nothing if the position does not exist.

This would allow us to call logic stored in Timelines, control the place of invocation from instance events, and even from other places, such as looping through instances within `with`.

```gml
// use:
with obj_Emeny {
  timeline_execute(id, Timeline_1, timeline_position);
  timeline_execute(id, Timeline_2, timeline_position);
  timeline_execute(id, Timeline_3, timeline_position);
}
```

### Describe alternatives you've considered

An alternative could be a "hash map" (structure), where the key is `timeline_position` and the logic is functions:

```gml
global.timeline_1 = {  };
global.timeline_1[$ 100] = some_function_100;
global.timeline_1[$ 120] = some_function_120;
// TODO: global.timeline_2, global.timeline_3...

// use:
with obj_Emeny {
  
  var fn = global.timeline_1[$ self.timeline_position];
  
  if is_callable(fn) then {
    
    var m = method(fn, id);
    
    m();
  }
  
  // TODO: global.timeline_2, global.timeline_3...
}
```

In this case, we end up with many script functions that can become cluttered and need organizing.

### Additional context

This function could also be used for calls within the context of **Sequences** or **structures**.

Adding this feature would enhance the flexibility and power of Timelines in GameMaker, enabling developers to manage complex behaviors more efficiently and intuitively. Your consideration and support for this feature would greatly benefit the GameMaker community.

**Comment by stuckie** [comment]
This is not something we are planning.
Sequences are the replacement for Timelines.
If there are issues with Sequences, then please file bugs and feature requests so that we can ensure they do as you need.
