### ISSUE TITLE
Code Editor 2 sometimes adds breakpoints in the wrong window

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6089]
### Description
Setting a breakpoint in CE2 (F9) will add the breakpoint to the location of the cursor in the first open CE2 window, rather than the one that's actually active.

This makes debugging a lot of fun.

### Steps To Reproduce
1. Open Script1
2. Open Script2
3. In Script2, add a breakpoint somewhere
4. The breakpoint ends up in Script1 instead

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.563 Runtime v2024.600.0.581

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[114b4c5a-7f89-4e82-919f-0fa434437639](https://api.gamemaker.io/api/github/downloads/114b4c5a-7f89-4e82-919f-0fa434437639)

**Comment by DragoniteSpam** [comment]
this may or may not be related to #5681

**Comment by zreedy** [comment]
Fixed. An additional issue where when a breakpoint was toggled via the F9 hotkey the hotkey icon was incorrectly rendered until cleared and set again.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
