### ISSUE TITLE
YYRunnerInterface: Implement fully the Script_Perform() stub function

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Bugs#6091]
### Is your feature request related to a problem?

I've been making heavy use of DLLs and the YYRunnerInterface for my game which has been fantastic for implementing & extending functionality beyond GameMakers capabilities.

However the lack of an _official_ method to run functions from inside DLLs causes many limitations.

I've noticed the interface already contains a function for this, however it seems to just be an empty placeholder:

![scriptPerform](https://github.com/YoYoGames/GameMaker-Bugs/assets/109584258/fbbdb54c-ea70-42b8-bbb3-97e98f0814db)

Both Code_Find_Function() and Script_Find_ID() already work exactly as intended, only Script_Perform does not.

### Describe the solution you'd like

Just the simple implementation of the already added/documented Script_Perform function.

**Comment by rwkay** [comment]
Fixed in 2024.6 - I have added an initial implementation for this - let me know how you get on with it

**Comment by jarrrodnb** [comment]
> Fixed in 2024.6 - I have added an initial implementation for this - let me know how you get on with it

Hey, I've just spent some time testing this.

I'm not sure if this is intentional, but there appears to be no way to run built-in functions.

Script_Find_Id() works correctly to find & run user functions.

Code_Function_Find() also returns the correct built-in function ID, however attempting to use the ID with Script_Perform will incorrectly run a user function instead.

For example, the function "show_message" has the ID of 891.
If I try to call Script_Perform with that ID, it runs the user function with the ID of 100891.

I feel like Script_Perform has a line of code that looks something like: `if (id < 100000) id += 100000;` which is preventing built-in functions from working.

**Comment by jarrrodnb** [comment]
Here's a small project that uses a DLL to call `Script_Perform()` on a user function & a built-in function.

I've also included the .cpp file to show all code used in the DLL.

[Script_Perform Example.zip](https://github.com/user-attachments/files/15788101/Script_Perform.Example.zip)

**Comment by rwkay** [comment]
Fixed in 2024.6 (once the above PR is merged)

**Comment by YYDan** [comment]
@jarrrodnb The changes 4 days ago to address your comment about in-built functions has now been removed from 2024.6 again, as it has been found to cause issues. I've made you a new FR already for this and assigned it to 2024.8, so I suspect you'll see this in early 800 Betas.

For us verifying _this issue_, there is now no need to do anything with the in-built functions.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.599  Runtime v2024.800.0.622
