### ISSUE TITLE
variable_struct_* functions still referenced

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6105]
### Description
The documentation of json_parse() has an important example that references the function variable_struct_exists(). However, this function can't be found in the documentation. After a couple of searches, I realised that all variable_struct_* functions seem to have been renamed struct_* . The documentation of json_parse() needs to be updated.

### Manual Link
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FFile_Handling%2FEncoding_And_Hashing%2Fjson_parse.htm&rhsearch=json_parse&rhhlterm=json_parse

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[a9d18dd8-029e-47df-baa8-bdf201fc7184](https://api.gamemaker.io/api/github/downloads/a9d18dd8-029e-47df-baa8-bdf201fc7184)

**Comment by ParodyKnaveBob** [comment]
Furthermore, those functions exist in some *Star Trek* half-phased limbo in the manual's indexing. $;^ J

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16678418/70c33e9d-c9bb-4fcd-bce2-8bf3f1725c4b)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/16678418/0f7dc4cb-7855-48b3-9a84-2b9573105634)

**Comment by gnysek** [comment]
While `variable_struct_get_names()` and `struct_get_names()` seems to be same, that's not true for other functions - see: https://github.com/YoYoGames/GameMaker-Bugs/issues/5038 .

**Comment by gurpreetsinghmatharoo** [comment]
Fixed. The old functions will continue to exist in the manual's index for anyone searching for them - as legacy support.
