### ISSUE TITLE
Cannot update certain existing live wallpaper GX.games mods from Gamemaker

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#6115]
### Description
Couldnt find mod previously uploaded onto gx.games within the game options on gamemaker and so couldnt update a live wallpapers project files without creating another new mod with different GUID and then merging mod files manually from 2 different mods.

### Steps To Reproduce
Upload live wallpaper mods to gx.games (many different projects).
Upload this live wallpaper mods to gx.games.
Edit mods manifest to add browser theme colours.
Close and reopen gamemaker and project.
Make changes to project and try to updating existing mod.
Cannot find mod in the GX.games mod game options select mod drop down box.
Cant upload new version of mod through normal means.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e6737c6d-c706-41c3-9674-86f37aa575ab](https://api.gamemaker.io/api/github/downloads/e6737c6d-c706-41c3-9674-86f37aa575ab)

**Comment by yyalansavage** [comment]
The issue here was simply that not all the users created mods were being listed (only occurs with >25 mods)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
