### ISSUE TITLE
In-Game: [Windows] Videos cannot play on devices which do not have a GPU

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6117]
### Description
When running the sample on GitHub Actions Hosted Windows runner, which does not have GPU, the async "video_end" event does not trigger. Query the device's GPU name returns `Microsoft Basic Render Driver`.

### Steps To Reproduce
1. Run the sample for Windows VM on a device with GPU, notice the runner shortly exits after the playing video, and the output message `video finished playing`
2. Repeat on device without GPU, notice the runner only exit after 10 seconds and the output message "Timed out about 10 seconds. Exiting the game"

For an example run in the GitHub Actions hosted runner, see: https://github.com/shichen85/no_gpu_video_play_demo/actions/runs/9370049302/job/25796016438#step:6:129

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.563 Runtime v2024.600.0.580

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[3cdf512d-d6ad-49d6-97b7-9279ac09f9c6](https://api.gamemaker.io/api/github/downloads/3cdf512d-d6ad-49d6-97b7-9279ac09f9c6)

**Comment by shichen85** [comment]
This seemed to be fixed in runtime 2024.1100.0.719 as shown in: https://github.com/bscotch/ganary/actions/runs/12111479624/job/33763411739

The the async "video_end" event now properly triggers. Thanks for the fix!

**Comment by jackerley** [comment]
Ah nice!, I'll close this off.

Thanks for letting me know.

Fritz

**Comment by YYDan** [comment]
Thanks for confirming/verifying.
