### ISSUE TITLE
IDE Installer missing "launch on exit" checkbox

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6120]
### Is your feature request related to a problem?

Many installers tend to have a checkbox on the "Finish" screen on whether or not to launch the software on completion. The IDE's installer lacks this option and opens itself. I often find myself second guessing whether or not it opens automatically because the first run time is quite slow, so end up opening two instances by mistake.

### Describe the solution you'd like

I'd appreciate that checkbox being there :)

### Describe alternatives you've considered

1. Not having it auto-open on finishing the installer.
2. Continuing to deal with this tremendously small inconvenience.

**Comment by stuckie** [comment]
This is intentional to ensure the IDE starts up to download it's first runtime.

**Comment by thennothinghappened** [comment]
> This is intentional to ensure the IDE starts up to download it's first runtime.

So would this issue come under the planned "improved update process" stuff? It does make sense it should get the runtime sorted too, but it still feels non-evident what it's doing. Is it possible a sentence on the last page could be added that just says it'll open the IDE on clicking finish to download the runtime?

**Comment by stuckie** [comment]
Just to finish this off, we've added a specific ticket ( which should be linked above ) for this to add some text to the installer that it's about to launch the IDE.
