### ISSUE TITLE
Code Editor 2: Feather underline appears in the wrong spot when the message is coming from a macro

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6122]
### Description
When feather is underlining an error coming from a macro, the underline is offset to the right instead of being under the macro.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/7a12f34b-6bea-4c73-b6e5-d434b5dced7d)

### Steps To Reproduce
```
secretlyNotAnArray = {}
	
#macro array secretlyNotAnArray
	
array_push(array, 5); //underline here will be under 5 instead of array
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.562 Runtime v2024.600.0.580

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c425d9dc-487f-42af-98f3-22b0b18e9fa2](https://api.gamemaker.io/api/github/downloads/c425d9dc-487f-42af-98f3-22b0b18e9fa2)

**Comment by zreedy** [comment]
Fixed. In addition the following other squiggle rendering issues were fixed:
 - Multi-line squiggles do not render beyond the first line
 - Squiggles that render on empty lines, or are 0 characters long in length do not render (should show 1 space-width squiggle)
 - Squiggles cited on strings or template strings do not fully highlight the affected range
