### ISSUE TITLE
Sequence: No collision is detected in Create Event of an object added inside a sequence

### ISSUE THREAD

**Issue by mmMarzban** [YoYoGames/GameMaker-Bugs#6137]
### Description

As the title says clearly, no collision happens in the Create event of an object which has been placed in a sequence.

### Steps To Reproduce

1. Start GameMaker
2. Create two objects: objA and objB (both have sprites)
3. In the Create Event of objA check the collision with objB. For example : var hit = place_meeting(x, y, objB); show_debug_message(hit);
4. Create a sequence and put objA inside it.
5. Add the sequence to the room.
6. Add objB in the room right in contact with the sequence.
7. Run the project and check the output console.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2024.600 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by mmMarzban** [comment]
OK, I sent another one with a sample project.
