### ISSUE TITLE
Crash: Strip unused assets causes crash when using a struct literal as a constructor argument

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#6139]
### Description
If you have Strip unused assets enabled, pass in a struct literal as a constructors argument but do not reference that object within your game (so it gets stripped out) then the game with crash.

### Steps To Reproduce
Open test project
Run test project
Observe crash
Add object oPanel to room
Run project
Notice no crash

### Which version of GameMaker are you reporting this issue for?
IDE v2023.9.0.298 Runtime v2024.0.9.319

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[de9ac59b-6935-49d0-a3da-75b94b2b7e73](https://api.gamemaker.io/api/github/downloads/de9ac59b-6935-49d0-a3da-75b94b2b7e73)

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
