### ISSUE TITLE
ProjectTool doesn't respect the Paths settings in IDE

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#6144]
### Description

ProjectTool doesn't seem to respect the temp or cache folder paths set in the IDE and instead does all its work in %TEMP% which isn't always good (usually because of low space on the system drive and extremely large projects)

https://nkrapivindev.duckdns.org/static/contactus.zip scroll to the bottom of ui.log, should contain the ProjectTool stuff

### Expected Change

The IDE should pass the temp folder path to ProjectTool, so it does all its stuff there

### Steps To Reproduce

1. Start GameMaker LTS
2. Create a project
3. Close
4. Start GameMaker Monthly
5. Load the LTS project
6. Notice in the ProjectTool log that the project is copied into %TEMP% instead of the chosen temp or cache folder
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
