### ISSUE TITLE
Old Code Editor: Built-In Audio Enum Member Names Highlight Erroneously When Using Non-Enum Dot Notation

### ISSUE THREAD

**Issue by ParodyKnaveBob** [YoYoGames/GameMaker-Bugs#6145]
### Description
Upon typing one of the many audio member names...
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAudio%2FAudio_Effects%2FAudioEffect.htm
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAudio%2FAudio_Effects%2FAudioEffectType.htm
...in dot notation attached to **any** custom variable name, the (old GM 2024.2.x) code editor highlights the stray member name as if it were an enum yet still highliights the variable name as the proper variable name.

It seems the opposite used to be the case?
https://forum.gamemaker.io/index.php?threads/2022-11-release-thread.99843/page-3#post-607990
Typing `AudioEffectType.LPF2` in this version highlights as a proper enum.

### Steps To Reproduce
1. Start GameMaker.
1. Open a project's Room1's Creation Code.
1. If the attached project, observe the names; if a new project, copy/paste what's below.
 1. Observe all the mismatched blue.red (by default) highlighting.

```gml
my_custom_struct = { // the struct doesn't even need to exist for the highlight bug below, but this shows the code runs just fine; prepending with var highlights locally equally
//	foo: 0,
//	bar: 0,
//	type: 0, // the highlight problem occurs whether or not any given name is initialized first
};

my_custom_struct.foo = 0;
my_custom_struct.bar = 0;
my_custom_struct.type = 0; // overridden
my_custom_struct.bypass = 0;
my_custom_struct.size = 0;
my_custom_struct.damp = 0;
my_custom_struct.mix = 0;
my_custom_struct.time = 0;
my_custom_struct.feedback = 0;
my_custom_struct.gain = 0;
my_custom_struct.factor = 0;
my_custom_struct.resolution = 0;
my_custom_struct.cutoff = 0;
my_custom_struct.q = 0;
my_custom_struct.rate = 0;
my_custom_struct.intensity = 0;
my_custom_struct.offset = 0;
my_custom_struct.shape = 0;
my_custom_struct.locut = 0;
my_custom_struct.loshelf = 0;
my_custom_struct.eq1 = 0;
my_custom_struct.eq2 = 0;
my_custom_struct.eq3 = 0;
my_custom_struct.eq4 = 0;
my_custom_struct.hishelf = 0;
my_custom_struct.hicut = 0;
my_custom_struct.freq = 0;
my_custom_struct.ingain = 0;
my_custom_struct.threshold = 0;
my_custom_struct.ratio = 0;
my_custom_struct.attack = 0;
my_custom_struct.release = 0;
my_custom_struct.outgain = 0;
my_custom_struct.baz = 0;
my_custom_struct.Bitcrusher = 0;
my_custom_struct.Delay = 0;
my_custom_struct.Gain = 0;
my_custom_struct.gain = 0; // just a reminder how gain looks
my_custom_struct.GAIN = 0; // members ARE viewed case-sensitive properly

show_debug_message(my_custom_struct); // on running, this shows all member names were indeed treated properly .. right before the expected crash below because HPF2 (etc.) isn't set

my_custom_struct.HPF2.LPF2.Reverb1.Tremolo.EQ.PeakEQ.HiShelf.LoShelf.Compressor = 0; // wow
my_custom_struct.Sine.Square.Triangle.Sawtooth.InvSawtooth.effects = 0;
my_custom_struct.qux = AudioEffectType.LPF2;
```

Just in case these steps do not repro for you, I include a screenshot for comparison.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163
**Note:** I'm on v2024.2.x because v2024.4.x gives me motion sickness, #6108.

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[8ff97a07-4bb6-406f-9b4b-a34f5d0802ba](https://api.gamemaker.io/api/github/downloads/8ff97a07-4bb6-406f-9b4b-a34f5d0802ba)

**Comment by rwkay** [comment]
This is expected, because of the way the old code editor works it does not know the context of the type fully (with or without Feather enabled) so it takes a conservative approach and anything it knows about will be flagged regardless of actual context.

This was deemed to be the best of a bad bunch of options.

The new code editor should be better at handling this as it has been architected in a different way to use the parsing context when syntax colouring.

**Comment by stuckie** [comment]
Closing as above.
