### ISSUE TITLE
Code Editor 2: GM becomes unstable when pasting text into an object, script or note editor

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#6146]
### Description

When trying to verify #5364 I got a fatal error message that GM had become unstable. This happens when pasting any text into the object, script or note editor using Code Editor 2.

 IDE v2024.600.0.568  Runtime v2024.600.0.595

### Steps To Reproduce

1. Start GameMaker and enable CE2.
2. Create/import project and go to object, script or note editor.
3. Paste any text and see issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
I'm no longer getting an unstable message when pasting anywhere unless the "auto indent clipboard contents" is enabled. This seems to happen for me frequently but not every time.

https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/8295594e-a1af-41a1-8c96-dd3b82e84c3a
[caitlin_ui.log](https://github.com/user-attachments/files/15774200/caitlin_ui.log)

1. Go to Preferences > CE2 and ensure "auto indent clipboard contents" is disabled.
2. Create new blank project and an object.
3. Paste some code into the create event, i.e 
```
	case spr_player_fall:
		// This checks if the player is now on the ground
		if (grounded)
		{
			// In that case we change its sprite to the idle sprite.
			sprite_index = spr_player_idle;
		
			// We also reset the animation speed to 1, as it was set to 0 at the end of the fall animation.
			image_speed = 1;
		
			// Play the landing sound effect
			audio_play_sound(snd_land_01, 0, 0);
		}
		break;
```
4. Go to Preferences and enable "auto indent clipboard contents".
5. Try pasting the code again and see the error.

**Comment by yyalansavage** [comment]
repros for me too on IDE v2024.600.0.573 and current develop with auto indent clipboard contents enabled. 100% repro just pasting this with cursor on the last line
```
{

}
```

**Comment by zreedy** [comment]
Fixed for the condition that Alan noted.

**Comment by stuckie** [comment]
Not sure why this was sitting open since it had been verified - closing now.
