### ISSUE TITLE
Generate built-in tags for constructor and function parent-child relationship

### ISSUE THREAD

**Issue by Alphish** [YoYoGames/GameMaker-Bugs#6154]
### Is your feature request related to a problem?

Right now, I don't have `is_constructor` function and I'd like to have one or a way to emulate it: #3055 (without trying to "new" a function and checking that it throws a specific exception)
I also don't have `constructor_get_parent` function, and I'd like to have one or a way to emulate it: #6127

Use-cases for these functions are better described in the respective FRs.

### Describe the solution you'd like

For each constructor, generate a built-in `@@constructor` tag.
For each constructor inheriting from another constructor, generate a built-in `@@parent=<parent_name>` tag.

With this and tag-inspection functions, it will be possible to:
- find all constructors
- check if a given function is a constructor
- find the parent of a given constructor
- find all direct children of a given constructor

### Describe alternatives you've considered

Wait for GMRT/GMLv3, I guess.

### Additional context

The idea came up when discussing potential syntax for tagging functions in GMLv3, and Russell figured current compiler might generate tags for constructors and parent-child relationships as well.

**Comment by rwkay** [comment]
[Bug-6154.zip](https://github.com/user-attachments/files/16120709/Bug-6154.zip)

Added an example project

**Comment by cameron-home** [comment]
Verified in IDE v2024.800.0.602  Runtime v2024.800.0.624

**Comment by Grisgram** [comment]
hm ok from what i can see here, the `is_constructor` is satisfied in a somewhat workaround-like-manner I do not fully understand, but I don't see the `constructor_call` FR being satisfied from #3055 and still 3055 has been closed.

I am in big need of that constructor_call

Would be great to receive a little comment about the future of `constructor_call`

**Comment by Alphish** [comment]
@Grisgram I believe `constructor_call` can be emulated right now with something like this:
```gml
function constructor_call(_ctor, _args) {
    var _result = {};
    static_set(_result, static_get(_ctor));
    var _ctor_method = method_call(_result, _ctor);
    method_call(_ctor_method, _args);
    return _result;
}
```

Would need to test how it behaves with inherited constructors, though.

**Comment by Grisgram** [comment]
Yes that works, thank you - we had a discussion on discord about it.
It seems, my main issue resides less in the absence of a constructor_call function, but more in the corner of "forwarding the argument-array, which is not really an array, as arguments to the next function".
I hope, with GML3/GMRT we see a better implementation here, so we can forward (parts of) the argument array to another function without a switch, checking for "if 1 arg -> do(1), if 2 arg -> do(1,2)..." up to... like 16 arguments
