### ISSUE TITLE
sprite_add_from_surface takes longer based on frame count in the sprite

### ISSUE THREAD

**Issue by YellowAfterlife** [YoYoGames/GameMaker-Bugs#6165]
### Description

While I was recently working my GIF loader, I have noticed a certain detail:

Given the following code,
```gml
var t = get_timer();
if (sprite == -1) {
	sprite = sprite_create_from_surface(surf,
		0, 0, surface_get_width(surf), surface_get_height(surf),
		false, false, 0, 0
	)
} else {
	sprite_add_from_surface(sprite, surf,
		0, 0, surface_get_width(surf), surface_get_height(surf),
		false, false
	);
}
t = (get_timer() - t);
show_debug_message(
	"frame " + string(sprite_get_number(sprite))
	+ " took " + string(t/1000) + "ms"
)
```
The results suggest that whatever the function's doing, it's doing more of that with each added subimage:

<details>

```
frame 1 took 8.86ms
frame 2 took 9.89ms
frame 3 took 15.89ms
frame 4 took 14.56ms
frame 5 took 20.79ms
frame 6 took 21.47ms
...
frame 50 took 118.24ms
...
frame 100 took 252.21ms
...
frame 150 took 370.22ms
...
frame 200 took 537.89ms
...
frame 250 took 669.07ms
```

</details>

Creating N single-frame sprites instead of a sprite with N frames does not suffer from this.

The function seems to have worked like this at least since GM8.1, so I'm not sure if no one really used it for much or if there's more to this than I can think of (my only guess was texture packing, but it doesn't seem to be doing that).

[TestSurface.zip](https://github.com/user-attachments/files/15745500/TestSurface.zip)

### Expected Change

Have a peek at whether this is something that can be improved

### Steps To Reproduce

1. Start GameMaker
2. Open project
3. Run project
4. Hold Left Mouse Button and watch Output
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1100.0.625  Runtime v2024.1100.0.651
