### ISSUE TITLE
Macro Syntax Color

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#6169]
### Description

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/0bae7427-d41a-439d-8da4-6c7a5da5068d)

### Expected Change

the macro should us correct syntax color

### Steps To Reproduce

```gml
#macro TEST abc

var thing = {};
thing.TEST = 2

show_debug_message(["thing", thing]) /// output: [ "thing",{ abc : 2 } ]
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed by another ticket.
