### ISSUE TITLE
In-Game: collision_rectangle() does not work correctly with precise collisions in 2022.0.2 LTS

### ISSUE THREAD

**Issue by Chourando** [YoYoGames/GameMaker-Bugs#6179]
### Description

Collision_rectangle don't collide correctly with precise collision objects. Works good with rectangle collision mask. Place_meeting also works good. Created simple project to reproduce problem. On newer version of GM (tested on 2024.04) no problems.
[Collision_rectangle_problem.zip](https://github.com/user-attachments/files/15753616/Collision_rectangle_problem.zip)
[ui.zip](https://github.com/user-attachments/files/15753654/ui.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create 2 object, one of them with precise collision mask
3. Check collisions with collision_rectangle function
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2022.0.3.67  Runtime v2022.0.3.80
