### ISSUE TITLE
In-Game: Particle Systems in nested Sequences play at faster rate than expected

### ISSUE THREAD

**Issue by drvidek** [YoYoGames/GameMaker-Bugs#6185]
### Description

When you have a particle system as part of a sequence A, the particle system will update at an accelerated rate if you place multiple tracks of sequence A inside another sequence B.
This is ONLY visible at runtime, behaviour appears as expected in Sequence Editor and Room Editor.
This affects a particle's travel distance, lifetime, emit delay, and more, causing particles to spawn and move faster and die sooner. The effect is increased with more tracks - e.g. if you have four tracks of A inside B, the particles in all tracks of A will update 4x as fast.
This only affects matching tracks running concurrently - e.g. if you put the same particle system inside another sequence N, then place one track of N in B, all A tracks will still update 4x fast and N will update normally.
[Bug_Submission.zip](https://github.com/user-attachments/files/15757334/Bug_Submission.zip)

### Expected Change

Particle systems should emit and update at the expected rate

### Steps To Reproduce

1. Start GameMaker, open a new blank project.
2. Create a particle system ParticleSystem1
3. Create a sequence Sequence1 and place ParticleSystem1 in it.
4. Create a sequence Sequence2 and place Sequence1 in it, twice. (Adjust the location of one of them for better visibility)
5. Place Sequence1 and Sequence2 in a blank room. Play the game.
6. See the issue - Sequence1 particles play as expected, but Sequence2 particles play at twice the speed

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by suncymild** [comment]
I'm having the same problem. Is there a solution to this?

**Comment by pkraif** [comment]
Reopening the issue as I've noticed that in-game behavior now doesn't match IDE.

**Comment by pkraif** [comment]
Fixed! Closing
