### ISSUE TITLE
TestFramework: [YYC] Unresolved external symbol error in BasicHandleTestSuite due to handle_testScript in 2024.4.1

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#6188]
Having handle_testScript in the theory inside BasicHandleTestSuite will not build on YYC. Some of the test suites (only the variable test suite right now) include separate tests depending on whether it is being ran on VM or YYC.

Steps to replicate:
1. Open project
2. Run the project on YYC (it will fail to build)
3. Inside BasicHandlesTestSuite, comment out line 9
4. Run the project on YYC (it should succeed to build now)

![image_2024-06-07_134159032](https://github.com/YoYoGames/GM-TestFramework/assets/77988663/28cc322b-47c6-445d-bd93-08f47f23e127)

[xUnit.zip](https://github.com/user-attachments/files/15739244/xUnit.zip)

**Comment by rwkay** [comment]
Unable to reproduce on latest Beta codebase (locally built) - I think I fixed this earlier in the week

**Comment by YYDan** [comment]
Yes - confirmed that 600.0.580 runtime still had the problem, but that it was already fixed by the .597 runtime. Verifying.
