### ISSUE TITLE
Code Editor 2 - Pasting onto final line of event results in a crash as well as immediate removal of pasted content

### ISSUE THREAD

**Issue by hasnogame** [YoYoGames/GameMaker-Bugs#6193]
### Description
Issue occurs upon copying and pasting a multi-line block of code which includes indented code onto the final line of an event. Upon doing so the IDE will paste then immediately remove the code including the newline it was pasted to. The code is confirmed as initially pasted as it is present in the undo trail.

Caveats:
- Issue does not occur if indents are placed *after* lines of code, only before.
- Issue *may* not occur in last event listed in editor, only those which precede the last event. obj_game demonstrates this in the attached project. If you paste indented code into the Draw event (the last listed event) it will paste as expected. However, upon creating a new object in that project I cannot recreate this behavior and all events delete the pasted content regardless of their place in the event hierarchy.

### Steps To Reproduce
- Create an object
- Add an event
- Type in multiple lines of code with at least one indented line
- Copy the code
- Add a newline
- Paste the code
- Press CTRL + Z / select Edit ==> Undo to see pasted code in undo trail

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.580

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[dffe453c-fbf9-41ec-a7f7-b02abc64dd3a](https://api.gamemaker.io/api/github/downloads/dffe453c-fbf9-41ec-a7f7-b02abc64dd3a)

**Comment by zreedy** [comment]
Unable to reproduce, I believe this was fixed recently as apart of another bug fix related to auto-formatting.
