### ISSUE TITLE
Code Editor 2: IDE becomes unstable when attempting to delete selected text by pressing the Enter key

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6194]
### Description

When using Code Editor 2 the IDE will go unstable when attempting to delete any code by selecting the text and pressing the enter key. As shown below:

https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/824ce973-ee30-44c0-a138-114e5d46bf22

[ui.log.txt](https://github.com/user-attachments/files/15775856/ui.log.txt)

### Steps To Reproduce

1. Start GameMaker
2. Enable CE2
3. Open any project
4. Type some code/text into an object, script or note
5. Select the text and press Enter
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.616
