### ISSUE TITLE
Add `gc_leak(struct)`

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#6198]
### Is your feature request related to a problem?

In Fields of Mistria, we have several structs which are loaded *configuration* files. These files are *always* available in the game, are never mutated, and should only be collected when the entire application closes.

These structs are fairly large and numerous, and the performance benefit of stopping the GC from interacting with them, while not massive, could be "free" for us.

### Describe the solution you'd like

I'd like a `gc_leak` function, which would take a struct, and then the GC would no longer track the struct at all. I understand this is simply a caused memory leak, but this a common technique in low-level languages (throwing something up on the heap and then never cleaning it up), and I'd like the perf for it.

**Comment by rwkay** [comment]
OK just do `global.some_name = _struct` and it will never be collected

even better create an array `global.remember_me = [];` and then just do `function gc_leak( _struct ) { global.remember_me.push(_struct); }`

**Comment by sanbox-irl** [comment]
@rwkay the issue with that is that the GC will still perform a mark and sweep on that struct (since it has no idea that some part of the struct COULDN'T have been removed or edited or set to undefined), so it will keep checking it occasionally. This struct is very large and has many sub-structs, so performing that mark and sweep is a waste of time

**Comment by rwkay** [comment]
It would still need to be traversed - the good news is that it will only checked infrequently as it will get into a higher generation very quickly (if it is assigned to global)

**Comment by sanbox-irl** [comment]
Why would it need to be traversed though? If it were instead *leaked*, could we not forgo the traversal in the name of performance?

**Comment by rwkay** [comment]
But this is effectively what happens with the generations already - those in higher generations (the older structs) are seldom visited, it is doing the job of `gc_leak` already

**Comment by sanbox-irl** [comment]
Why accept seldom when I could have none? We often have more than 1 million objects in this final (5th) generation. I know it will only seldom look at them, but this of course has a performance cost

**Comment by JujuAdams** [comment]
Could you provide some numbers on the performance impact you're seeing, if possible? I haven't pushed things this far myself but I do like having big JSON files for config / game data.

**Comment by sanbox-irl** [comment]
@JujuAdams tough to say -- we actually were causing a lot of GC leaks and segfaults, which was fixed in 26-4. I'll see if we still have GC spikes on swapping to the oldest generation

**Comment by gnysek** [comment]
If it causes some frame drop, I would try with `gc_target_frame_time()`, but if the only problem here is that it "waste" time (so it's not affecting game in any way)... I would just ignore it.
Of course it's good to search for a way to optimise things, but having such feature sounds like it could lead to memory leaks or missing data, if something is referenced in wrong way (as I assume you wanted to have that 5 megs JSON loaded on startup read-only and that's a thing you wanted to mark as _leaked_, as it keeps data about game world, which isn't changed at run time).

**Comment by sanbox-irl** [comment]
Read-only, leaked data is quite standard to use -- GM itself uses this tactic multiple times as well. It's nice to leak an allocation and then you have a pointer you know is valid for the program's life -- if you were never gonna dealloc it anyway, why not?

**Comment by gnysek** [comment]
Then maybe some new data type, some kind of custom metadata, could be a better solution? I mean... as this was closed/rejected, it doesn't mean we don't need something close to what you proposed, but maybe it doesn't need to be a part of garbage collecting functionality. Initially it wasn't detailed what it could be used for, but that example with loading big JSON file throw totally new light about what it's all about.

**Comment by JujuAdams** [comment]
The more I think about this the more I like the basic idea of having unswept long term data. It opens up a lot of opportunities for data-driven programming.

**Comment by sanbox-irl** [comment]
It's what powers Fields of Mistria! But that being said, all we're talking about is how every few seconds how long it takes the GC to check over all this data. That's really the "cost"

**Comment by danieltjewett** [comment]
We also use a ton of arrays / structures, many that attached to global.  

> Why accept seldom when I could have none? We often have more than 1 million objects in this final (5th) generation. I know it will only seldom look at them, but this of course has a performance cost

Agreed.  When it is visited, it spikes hard.  Hoping https://github.com/YoYoGames/GameMaker-Bugs/issues/8268 gets fixed soon, as perhaps this could solve some issues.

Long term, it seems like the best course of action is to just use `lists` and `maps`, and forego instance methods until there is more control over garbage collection.

See https://github.com/YoYoGames/GameMaker-Bugs/issues/3271 and https://github.com/YoYoGames/GameMaker-Bugs/issues/3272
