### ISSUE TITLE
[MacOS YYC] "Draw" layer is simply black. Only "Draw GUI" layer displays.

### ISSUE THREAD

**Issue by cauehenrique** [YoYoGames/GameMaker-Bugs#6199]
### Description

Some Mac users of my game reported that their screens were black. Upon investigation, I found that the "Draw" layer isn't being rendered, only the "Draw GUI" layer is being displayed.

All configurations with cameras, views, and surfaces seem to be correct, as other users are not experiencing this issue.

## The game running on Windows:
The buttons and text are all drawn on the GUI layer, while the water background and the island are just a couple of objects with sprites.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/26bb248d-a29b-4772-8595-783a17933b52)

## This is what those users sent me:
Only the stuff being rendered on the Draw GUI is shown.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/6215d2fa-1729-4536-8ee9-83993f4abd85)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/64d1014e-3026-4027-8eb5-62d747d04c85)

Any help or suggestions would be greatly appreciated.

[contact package.zip](https://github.com/user-attachments/files/15778279/contact.package.zip)

### Expected Change

The game should draw, lol.

### Steps To Reproduce

This issue occurs sporadically for a few users and does not replicate on my machine, making it difficult to describe in detail.

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Hi, the enclosed project doesn't seem to work for me, I just get a black screen with a hand icon mouse pointer and some console output of the form [Loader] LEFT: 0 // TOTAL: 362 

Your enclosed screenshots are both showing script errors that would indicate the problem is arising in your scr_bbcode script around line 299, if that version was built with this source code then it would look like your lookup into entry.images may be going wrong. I would recommend adding some logging in here to see what is causing the error.  I would assume you are reading off the end of the entry.images array or that the array doesn't contain what you think it contains. 

Hope this helps,
Fritz

**Comment by cauehenrique** [comment]
> Hi, the enclosed project doesn't seem to work for me, I just get a black screen with a hand icon mouse pointer and some console output of the form [Loader] LEFT: 0 // TOTAL: 362
> 
> Your enclosed screenshots are both showing script errors that would indicate the problem is arising in your scr_bbcode script around line 299, if that version was built with this source code then it would look like your lookup into entry.images may be going wrong. I would recommend adding some logging in here to see what is causing the error. I would assume you are reading off the end of the entry.images array or that the array doesn't contain what you think it contains.
> 
> Hope this helps, Fritz

Oh, that error is actually something I already fixed. It's a peculiar issue that only occurs on Mac. I apologize for the completely black screen; it's due to the fact that this game is a [commercial product](https://store.steampowered.com/app/2464880/Terracards/). I was uncertain about whether I should compile the game with Steamworks before sending it here.

I'm not very comfortable sending the game here since this is a public repo, but yeah... 🤷‍♂️ Here's a version without the anti-piracy lock.

[ctt package 2.zip](https://github.com/user-attachments/files/15808624/ctt.package.2.zip)

**Comment by cauehenrique** [comment]
I'm not sure if my previous comment was deleted because it had a link to the project. Although the issue has been closed, I would appreciate some explanation regarding this.

To answer @jackerley query: the crashes have been fixed, but the black screen issue in the background persists. The game displays a black screen on your machine because it tries to enable the Steamworks extension, and since you don't have the game on Steam, it locks you in the first room.

As shown in the screenshots, the game is running on the buyer's machine. As described in the title, the only elements not being drawn are those on the "Draw" layer.

I understand it might seem like there’s an issue with my code, but I’ve been working with GameMaker for over six years now. This isn't a problem with my code or my project. The game runs perfectly on every other OS.

Thank you for your understanding.

**Comment by jackerley** [comment]
Hi @cauehenrique yes, I deleted the comment as it contained a public link to your project which I didn't want to leave around for anybody to download. I tested the project on my Mac here and it ran fine, there were no issues with missing graphics. Are there any particular reproduction steps? Can you reproduce this issue yourself? Do you have any screenshots of this occurring without the error dialog having been shown? Is there any common factor among the users that are having problems? Location? Type of Mac etc?

**Comment by cauehenrique** [comment]
> Hi @cauehenrique yes, I deleted the comment as it contained a public link to your project which I didn't want to leave around for anybody to download. I tested the project on my Mac here and it ran fine, there were no issues with missing graphics. Are there any particular reproduction steps? Can you reproduce this issue yourself? Do you have any screenshots of this occurring without the error dialog having been shown? Is there any common factor among the users that are having problems? Location? Type of Mac etc?

Hi @jackerley, apologies for the delayed response. I've been quite busy working on the game. To address your questions:

- **Are there reproduction steps?**
  Unfortunately, I haven't identified a reliable way to reproduce the issue. It seems to occur consistently on Macs, but I haven't been able to replicate it myself. The reports started appearing after I enabled "Retina" support in the Mac settings, though I'm not certain if this is related or just a coincidence.

- **Do you have any screenshots of this occurring without the error dialog having been shown?**
  Yes, a buyer recently reported the same issue, and I do have screenshots without any error dialogs:

  ![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/9c07e5a5-d0bb-4900-83dd-3715abfe6d1b)
  ![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/27cbb22f-43b2-4e39-860c-d32c5e43f3f7)

Additionally, I have some information about their Mac setup:

  ![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/43036856/7642c698-65b4-4494-9780-a24e24ef0164)

Please let me know if you need any further information or assistance.
