### ISSUE TITLE
Profiler causes Fields of Mistria to run very slowly

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#6200]
### Description

Running FoM in the profiler causes it to run *extremely* slowly.

In real frames:
running normally with F5 in VM 60fps, performs the test suite in 19 minutes
With the profiler running, 24 fps, performs the test suite in ?? more than 2 hours.

I'm not sure exactly what the source is -- ever since we updated to IDE version 2024.4.1.152 the profiler has not been useful to us.

Anything you can do help speed this up would be appreciated!

### Steps To Reproduce

You have access to FoM, and can run it. First, run `.build.ps1` in FoM's main directory. After that, you can run the game in the IDE any way you'd like

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yyalansavage** [comment]
Hi, have been looking into this but I'm not getting such extreme timing differences. Testing with IDE 2024.4.1.152, windows target, FoM test suite timings for me are 5mins run, 7.5mins debug with no profiling, 8.5mins with debug + profile.
What target platform are you getting those timings on? Would be interested to know what timings you get if you debug-run the test suite without starting the profiler.

**Comment by sanbox-irl** [comment]
@yyalansavage how are you running the test suite? realizing I didn't include instructions on that. With the above timings, that was actually me in Debug running -- I stated that poorly. Regardless of running the profiler or not, the Debug mode performance was poor.

I am not certain though that the test suite is a reasonable performance target on VM for us to look at now though because of <https://github.com/YoYoGames/GameMaker-Bugs/issues/6253>, which is likely straining my system (I only have 16gbs of RAM on my PC). I am wondering if these are the same bugs actually and the overhead in debug mode is just pushing me into a memory starved state...

Regardless, I was able to replicate the poor performance in a non-test-suite setting, just running the game normally and walking around the player's Farm (the room immediately upon exiting the player's house)

**Comment by yyalansavage** [comment]
So just running in debug config with `#macro TEST_SUITE false` ; I seemed to get slightly improved timings when running testsuite with current develop runtime (run 5mins, debug 5.4mins, debug+profile 6.2mins). 16GB RAM on my machine.
On a non-testsuite run i'm not seeing anything alarming, fairly steady at 200+ fps regardless of run or debug/profile. I did not observe RAM increase either but we'll see what the runtime guys find RE #6253.

**Comment by sanbox-irl** [comment]
@yyalansavage I'm not completely following your testing. Do you have a Discord where we could talk in realtime? I'm @jack_irl

**Comment by yyalansavage** [comment]
I sent you a FR (enidXXXX)

**Comment by sanbox-irl** [comment]
Confirmed, fixed in the upcoming beta. Thank you @yyalansavage !

**Comment by caitlinrmcintyre** [comment]
Verified fix as per comment above, thanks.
