### ISSUE TITLE
Code Editor 2 "Go To Declaration" (F1) Issue with JSDocs

### ISSUE THREAD

**Issue by JhOnNeY** [YoYoGames/GameMaker-Bugs#6202]
### Description

Previously, before Code Editor 2, having just a `///@func function_name()` JSDoc comment was enough to allow the `Go To Declaration` (F1) Code Editor function to jump to a method or function.

Additionally, the `Go To Declaration` function only ever worked when used on a reference outside of the event/script file the referenced function/method was declared in.

Now in Code Editor 2, It doesn't seem to work at all, from anywhere.

## Object1
```js
///Create Event ---------------

///@func move_continue()
move_continue = function()
{
	movement_paused = false
	speed = move_speed
	events.move_continued.invoke()
}

///Step Event ------------------

if can_move
{
    move_continue()
}
```

## Object2
```js
///Create Event ---------------
Object1.move_continue()
```
[GMS2 Beta Contact Us Package 2024.600.0.571.zip](https://github.com/user-attachments/files/15783563/GMS2.Beta.Contact.Us.Package.2024.600.0.571.zip)

### Expected Change

The Go To Declaration function would cause the window to jump to the function at the point of declaration or to open a new tab with the file the function is declared in with the function declaration in view.

### Steps To Reproduce

1. Start GameMaker Beta and enable Code Editor 2
2. Create some objects with function and/or method variable declarations (as in the description above)
3. Create Feather compatible JSDoc headers for those variables
4. Use/Reference those function and/or method definitions in other objects or in the same object
5. Attempt to use the "Go To Declaration" by right click context menu or by the F1 keyboard shortcut

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Unable to reproduce, appears functional with the provided snippet.

**Comment by zreedy** [comment]
As an aside, `@func` is deprecated and not considered by CE2.

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.597  Runtime v2024.800.0.620
