### ISSUE TITLE
Code Editor 2 Feather JSDocs tooltip displays incorrectly and/or incomplete.

### ISSUE THREAD

**Issue by JhOnNeY** [YoYoGames/GameMaker-Bugs#6204]
### Description

Similar to https://github.com/YoYoGames/GameMaker-Bugs/issues/5206 with a bit more context and examples.

This seems to be a Mac problem since the only ones reporting similar issues have Macs.

When attempting to view JSDocs for a function being referenced, the on hover tooltip shows up with only an incomplete portion of the function information.
- Little black boxes show up in the tooltip instead of parameter/argument names. 
- Return values don't appear in the tooltip at all
- Displays incorrectly for both function and method definitions
- `@self` context from calling object doesn't show on the tooltip for the first method declaration in a file
- The first declared method/function with a JSDoc tooltip will show the `/// @description` comment from the top of the event's file section (see `Incomplete JSDoc Tooltip` below)

All of the below functions are declared in the `Object1`, called from `Object2`. 
<img width="653" alt="Screenshot 2024-06-11 at 12 38 31 AM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/8714222/d642ac90-e256-470f-b906-ffea62b24c1d">

## Incomplete JSDoc Tooltip
<img width="653" alt="Screenshot 2024-06-11 at 12 19 21 AM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/8714222/26c18aa9-5888-4c41-961a-a80e27fce88f">

## Broken Method Definition JSDoc Tooltip
<img width="653" alt="Screenshot 2024-06-11 at 12 20 55 AM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/8714222/2573110f-ddd9-451d-bd2f-c1d397e13f89">

## Function Definition JSDoc Tooltip
<img width="653" alt="Screenshot 2024-06-11 at 12 33 35 AM" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/8714222/2a28fd15-d560-46a7-8e56-ff012f318e39">

[GMS2 Beta Contact Us Package 2024.600.0.571 (jsdoc tooltips).zip](https://github.com/user-attachments/files/15784087/GMS2.Beta.Contact.Us.Package.2024.600.0.571.jsdoc.tooltips.zip)

### Expected Change

The JSDoc Tooltips for method and function declarations will be displayed correctly and well formatted

### Steps To Reproduce

1. Start GameMaker Beta and create a new GML Code project with Code Editor 2 enabled
2. Create an object with some function and method declarations in the create event with references elsewhere
3. View the JSDoc comment tooltips of those method and function declarations by hovering the mouse over the reference or the declaration itself.
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
The monospace font 'Consolas' is incorrectly selected on Mac OS X, the fallback to 'Open Sans' does not function in the new font renderer. These two bugs are manifesting as https://github.com/YoYoGames/GameMaker-Bugs/issues/5206, https://github.com/YoYoGames/GameMaker-Bugs/issues/5208, https://github.com/YoYoGames/GameMaker-Bugs/issues/6204

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified using Mac and Windows in IDE v2024.800.0.595  Runtime v2024.800.0.619, thanks.
