### ISSUE TITLE
Make an option to let newly create instances spawn in front of older ones

### ISSUE THREAD

**Issue by Haegoe-Haegwe** [YoYoGames/GameMaker-Bugs#6205]
### Is your feature request related to a problem?

This was the norm in older gamemaker, but since gms2 newer object instances are starting to show behind older ones, when they have same depth or layer.
this is a problem because it means for ui object like damage nubmers, newer (and more important) numbers are covered by older ones. Or enemies covering their own projectile and giving you less time to react.

### Describe the solution you'd like

add an option to make a newer instance with same layer or depth as older ones.
if it doesn't affect other event orders it would be better.

### Additional context

workarounds exists, but the fact that I need to make a workaround for what I've taken for granted is annoying, and some of them feels too inefficient.

**Comment by stuckie** [comment]
You should use layers to organise how your items are drawn, this is how the system works.

**Comment by Haegoe-Haegwe** [comment]
I meant when it is created via instance_create_layer() or instance_create_depth()

**Comment by stuckie** [comment]
You need to assign them different layers; draw order is not guaranteed with items within the same layer:

> Note that instances of an object that have the same depth can be drawn above or below each other even when they appear to be placed one on top of the other in [The Room Editor](https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Rooms.htm). If you want to guarantee that something is drawn over or under everything else, you should always set the depth (or layer) explicitly. Also note that there is a minimum (-16000) and maximum (16000) depth value outside of which instances will not be drawn, although they will still exist and process events.

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FInstances%2FInstance_Variables%2Fdepth.htm
