### ISSUE TITLE
Code Editor 2: Incorrect syntax highlighting when skipping an argument with a comma and then dot accessing a long variable name as the next argument

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6211]
### Description
This one is weird, it only happens when the variable name is long. The colors are correct if the variable name is short.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/3e1130cf-29ca-4560-97cb-156c2fa91a25)

### Steps To Reproduce
```
function takes_some_args(arg1, arg2, arg3) {}
```

```
takes_some_args(1, , Object2.longVariableName); //incorrect coloring

takes_some_args(1, , Object2.short); //Correct coloring
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c565bf51-9ac0-4caf-ba9f-59cd1e3dfc0d](https://api.gamemaker.io/api/github/downloads/c565bf51-9ac0-4caf-ba9f-59cd1e3dfc0d)

**Comment by zreedy** [comment]
Fixed. Feather produces pseudo-variables for implicit arguments `$$implicit_argument$$` to track type info, among other purposes. This token was being echoed on the semantic token stream. The Client side gave precedence to the erroneously echoed token resulting in the overlapping tokens from the following arguments being discarded.

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
