### ISSUE TITLE
Bug Reporter: Cannot attach project from  the "Attach Project" Dialog   

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#6217]
### Description
In the Bug Reporter, when selecting the "Issue Category" as  "In-Game (GMS2 Runtime)" and leaving the "Privately attach project" checkbox unchecked, on clicking submit, a dialog pops up advising the user to attach a project. 

However, on clicking "Yes" on the dialog the pop up is dismissed but no project gets attached to the report. 

On clicking "Yes" on the dialog the project should get attached to the report.

### Steps To Reproduce
- Launch the IDE and open a project
- Open the Bug Reporter from the Help dropdown menu
- Fill the necessary information in the report
- Select "In-Game" as the issue category 
- Do not tick the checkbox to attach a project 
- Click on "Submit"
- Observe the pop-up dialog 
- Click "Yes" on the dialog
- Observe the issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.572 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.600.0.579  Runtime v2024.600.0.605, thanks.
