### ISSUE TITLE
Code Editor 2: When show all documents in single view is disabled, the current scroll is carried over between events

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6223]
### Description
If you disable "show all documents in single view", swapping between events will keep the scroll level of the previous event you were looking at, instead of taking you back to where you were last time you looked at the event. This makes the workflow for swapping between events rather awkward.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9dcb25dd-f655-4b2a-a986-121c5cd21335

### Steps To Reproduce
Disable "show all documents in single view", add multiple events to an object, scroll down in one of them, and then swap to another event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b6c57d46-d0fe-42e7-a4a3-89c9b6066ae9](https://api.gamemaker.io/api/github/downloads/b6c57d46-d0fe-42e7-a4a3-89c9b6066ae9)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.601  Runtime v2024.800.0.624
