### ISSUE TITLE
In-Game: Debug console treats double-quoted asset names as their reference types instead of as strings, despite what the manual says

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6225]
### Description
According to the manual page on the [debug console](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDebugging%2FThe_Debug_Overlay.htm):

> Any text surrounded by double quotes "" is treated as a string

but this does not appear to be the case.

### Steps To Reproduce
1. Run the project
2. Open the console
3. `typeof "Room2"`
4. --> `ref`
5. `show_debug_message "Room2"`
6. --> `ref room 1`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[2fb87e5d-2d0a-4c54-a031-0bec8b0650da](https://api.gamemaker.io/api/github/downloads/2fb87e5d-2d0a-4c54-a031-0bec8b0650da)

**Comment by rwkay** [comment]
Fixed in 2024.6 (when the PR above is merged)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.600.0.579  Runtime v2024.600.0.605
