### ISSUE TITLE
In-Game: [YYC] ds_grid_get() is unexpectedly changing numbers saved into the grid in 2024.600 Beta 3

### ISSUE THREAD

**Issue by retupeltonen** [YoYoGames/GameMaker-Bugs#6229]
### Description

When using YYC to build, the data format on numbers being saved into a ds_grid has somehow changed in Beta Runtime v2024.600.0.597, resulting in divisions of such numbers being broken.

Saving two numbers into a ds_grid and dividing one by the other results in 0 when it should not:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/83304801-ab8c-4007-93f7-8142207937a3)

Versus VM:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/b74f1ca8-947c-4e5e-a047-0b065aa3ad38)

### Expected Change

The attached sample should return the same results on YYC as it does when running on VM.

### Steps To Reproduce

1. Start GameMaker and import the attached project: [testDSGridGet.zip](https://github.com/user-attachments/files/15816082/testDSGridGet.zip)
2. Run it for YYC and observe the result is drawn as 0 each time
3. (Optional) Re-run the project for VM and observe the result is the correct each time

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, macOS, iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Turned the code snippet into a proper sample and updated the info/steps.

Windows is exactly the same results, so have added that above as well.

**Comment by rwkay** [comment]
Fixed in 2024.6 (once commit above has been merged)

**Comment by Emc1923** [comment]
Verified on mac as of  Beta IDE v2024.600.0.579 Beta Runtime v2024.600.0.605.
