### ISSUE TITLE
Code Editor 2: Deleting an inherited event on a child will delete the parent's event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6231]
### Description
If you try to delete an event that a child object is inheriting from it's parent, instead of doing nothing, a project directory modified popup will appear and the parent's event will actually get deleted.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/462384f7-ea1b-4207-9919-8c7cada58370

### Steps To Reproduce
Delete an event that a child object is currently inheriting from it's parent.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7c47453e-7a7f-42f5-9ec3-f5d71954057a](https://api.gamemaker.io/api/github/downloads/7c47453e-7a7f-42f5-9ec3-f5d71954057a)

**Comment by zreedy** [comment]
Fixed. To clarify, it was possible to delete a parent's event from a child object.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
