### ISSUE TITLE
Code Editor 2: Deleting an overwriten child event to return to inheriting the parent event will trigger a project directory modified popup and cause different visual errors based on document view setting 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6233]
### Description
If you delete a child object's event when it has overwritten the parent event, you will get a project directory modified popup. In addition, if you are viewing all documents in a single view, it will swap to viewing whatever the last event in this list is, regardless of what event you just deleted:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/53b28068-160e-426e-8d5e-f6f6148bc5ad

If viewing all documents in a single view is disabled, then hitting reload on the popup will make the event code vanish until you select it again:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f4e963a4-5721-42b7-8de3-d72f4347e098

### Steps To Reproduce
Delete a child's overwritten event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[92d18aeb-1c65-46ed-9efd-6fccbcb3c1aa](https://api.gamemaker.io/api/github/downloads/92d18aeb-1c65-46ed-9efd-6fccbcb3c1aa)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
