### ISSUE TITLE
Code Editor 2: Opening a child object's code window prevents the parent's code from being edited

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6234]
### Description
If you have a parent and child's code windows open at the same time, and the child has inherited events that are not overwritten, those events will also be locked for the parent, making the code impossible to edit.

Edit: After finding #6235, I realized that this bug is actually the opposite of that. It happens when opening the parent first, and then opening the child.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/690e9db8-17ff-4008-a0c1-dede32e0ceb4

### Steps To Reproduce
Open a parent object and child object's code windows at the same time, while the child has inherited events that are not overwritten.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5eda6bf3-25f7-4099-ae8c-ed13eb60d54a](https://api.gamemaker.io/api/github/downloads/5eda6bf3-25f7-4099-ae8c-ed13eb60d54a)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.800.0.598  Runtime v2024.800.0.621, thanks.
