### ISSUE TITLE
Code Editor 2: Opening a child object first, then opening a parent object will unlock the inherited events on the child, allowing them to be edited and change the parent code

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6235]
### Description
Normally events that a child has inherited from a parent object will be locked and not possible to edit. However, if you open up a child's code window first, and then open the parent's window, it will become possible to edit the parent event from the child.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/0cb8a2bc-ac10-4075-8400-32492735fea2

### Steps To Reproduce
Have a parent and child object, with the child inheriting events from the parent. Close both of their code windows. Open the child's window first, then open the parent's window. The child's inherited events will become possible to edit.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0cc3edd5-ad39-44c6-adcb-756352be393f](https://api.gamemaker.io/api/github/downloads/0cc3edd5-ad39-44c6-adcb-756352be393f)

**Comment by zreedy** [comment]
Fixed. The underlying `Document` is shared between all `TextEditorPanels` per source file. Depending on focus the readonly flag must be updated.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.598  Runtime v2024.800.0.621, thanks.
