### ISSUE TITLE
Parallax Wallpaper Template: Error for sprite_get_height() argument being incorrect seen when running the project

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#6237]
### Description
The parallax wallpaper template fails when it is ran.

As soon as the project builds the user sees an alert with the following error:

___________________________________________
############################################################################################
ERROR in action number 1
of Create Event for object obj_main:
sprite_get_height argument 1 invalid reference to (sprite) - requested -1 max is 14
 at gml_Script_anon@27890@_effect_windblown_particles@_effect_windblown_particles_script (line 1020) -               sprheight = sprite_get_height(param_sprite);       
############################################################################################
gml_Script_anon@27890@_effect_windblown_particles@_effect_windblown_particles_script (line 1020)

### Steps To Reproduce
1. import attched project or start a new project using the Parallax wallpaper template
2. run the project
3. see the error in the alert

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.573 Runtime v2024.600.0.599

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
GX.games, Windows

[85ec584a-a372-44dc-83fe-b1bf925580d1](https://api.gamemaker.io/api/github/downloads/85ec584a-a372-44dc-83fe-b1bf925580d1)

**Comment by mgeddesGM** [comment]
This also occurred in Green IDE v2024.4.1.153  Runtime v2024.4.1.202

**Comment by jackerley** [comment]
This is a problem with the internal "Automatically remove unused assets when compiling" option, if you unselect this option, the project will work fine. I'll remove from June milestone & give to Russ

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.8.0.168  Runtime v2024.8.0.215, thanks.
