### ISSUE TITLE
Code Editor 2: Review whether global variables should appear in the declarations list for an individual Object

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6241]
### Description
As title, when a global is defined in a instance is added to the declarations panel, when i think that panel should be reserved only for declarations for the instance.

### Steps To Reproduce
1) Open obj_controller_code
2) Line 20.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[84d8b972-cb2b-4fd1-aed4-7885dd362b19](https://api.gamemaker.io/api/github/downloads/84d8b972-cb2b-4fd1-aed4-7885dd362b19)

**Comment by zreedy** [comment]
Yes, it should. This is documented as expected behavior.
