### ISSUE TITLE
Code Editor 2: Shift+End keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6246]
### Description
The Shift+End keyboard shortcut should select everything from the caret to the end of the line, but instead it doesn't do anything.

Similar shortcuts like Shift+Home and Ctrl+Shift+Left work properly, but Shift+End doesn't do anything

### Steps To Reproduce
1. Open something in Ce2
2. Put the cursor in the middle of the line
3. Shift+End
4. Nothing happens

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[8a592715-2c66-4801-9c2d-0ccb4b243ed3](https://api.gamemaker.io/api/github/downloads/8a592715-2c66-4801-9c2d-0ccb4b243ed3)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
