### ISSUE TITLE
In-Game: [iOS] video_end async event is not triggering as of 2024.600 runtime 600

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6247]
### Description

After calling `video_open()`, we noticed that on iOS export only, the `video_end` async event is not triggering starting in runtime 2024.600.0.600, whereas it worked fine in runtime 2024.600.0.597.

### Expected Change

The async event should trigger when the video finished playing.

### Steps To Reproduce

1. Open a blank project and call `video_open()` for an video file.
2. Create an object to detect the `video_end` async event.
3. Run for iOS export and notice that the async event does not trigger.

To see this in our test project:

1. Clone the sample project at https://github.com/bscotch/ganary
4. On[ line 87](https://github.com/bscotch/ganary/blob/fb500ae8965f82ec1b0f5709e03c06e0e0c5a477/Ganary/scripts/grc_register_async_function_tests/grc_register_async_function_tests.gml#L87), add the `.only()` function call to only run that test case. Line 87 should look like this: `	}).only();`
5. Run the project for iOS export with the `dev` config. 
6. Notice that the test timed out because the `video_end` async event does not trigger

Essentially, this test is carried out in the `grc_o_video_end_event_missing` object which performs the replication step mentioned above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Fixed, the problem was coming as the video wasn't being rendered, a situation I hadn't considered

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.586  Runtime v2024.800.0.610
