### ISSUE TITLE
Inversed loop move for audio in sequences

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6254]
### Description
Simple yet problematic bug in the current version of GM. The Loop Mode property specified for audio tracks in sequences is reversed in-game.

In the GameMaker IDE, when working on the project, loop mode works as expected: "play once" only plays the sound once and loop repeats the sound. However, when playing the exact same sequence in the game, the results is inversed. Audio tracks set as "play once" loop automatically and vice-versa.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[ade9bcc9-a935-4acb-9244-be9894589806](https://api.gamemaker.io/api/github/downloads/ade9bcc9-a935-4acb-9244-be9894589806)

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by alicemoretti** [comment]
Moving this back to "Not Planned" since the automation brought it back in.
