### ISSUE TITLE
Resource not indexed in .yyp file can still appear in the Asset Browser

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6255]
### Description
During IDE updates, our project somehow deleted a sprite resource from the yyp file but kept the actual yy file and related resources. In the IDE's Asset Browser, this sprite can be seen and assigned to objects. However, when performing draw events with this sprite, it will fail.

We expect the IDE to be able to warn or correct the situation. Otherwise, it is confusing to see an existing resource not working at runtime.

### Steps To Reproduce
1. Open the sample in IDE
2. See that the resource `grc_o_spine_async_event_test` is visible and assignable to objects.
3. Run the project and see the animation event does not trigger
4. Open the yyp file and see the resource is not indexed

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Mac 12.7.5

[4fefce1d-b78f-45ac-af16-1af2a5dfb7fc](https://api.gamemaker.io/api/github/downloads/4fefce1d-b78f-45ac-af16-1af2a5dfb7fc)

**Comment by shichen85** [comment]
Hello @stuckie, I have attached the project here. However, in case it triggers ProjectTool again,  you can try the following steps:
1. Run the project to confirm that the animation event triggers
2. Close the IDE and edit the yyp file to remove the resource `grc_player_fallfromspace_spine` on line 43
3. Open the project in IDE and run again to see the animation event not triggering
4. See that the resource grc_o_spine_async_event_test is visible in asset browser and assignable to objects. 

[skeleton_animation_.zip](https://github.com/user-attachments/files/15888150/skeleton_animation_.zip)

**Comment by stuckie** [comment]
I don't get the animation playing, at all... even when going back to both the initial version of the bug report, and the one that saved the project.
However, when I remove the line in the yyp, I do still get the object showing up in the project, so I can at least look into why it's doing that now, thanks!

Project is haunted.

**Comment by shichen85** [comment]
> I don't get the animation playing, at all... even when going back to both the initial version of the bug report, and the one that saved the project. However, when I remove the line in the yyp, I do still get the object showing up in the project, so I can at least look into why it's doing that now, thanks!
> 
> Project is haunted.

That sounds like the right problem: the resource is not in the YYP file but still shows up in the project. As long as the IDE can be aware of this discrepancy and handle it properly, it will be an improvement!

**Comment by stuckie** [comment]
This should now be resolved.
The IDE will now heal the project to re-add the missing resources to the project as required, and will tell you on load which lost resources were found.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.599  Runtime v2024.800.0.622.
