### ISSUE TITLE
Sequence Moments in Sprites

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#6256]
### Is your feature request related to a problem?

Sprites already support sequence messages, It would be nice to additionally support sequence moments. Primarily used for state machines to be able to return to the idle state when an attack animations finishes, or conversely to apply the damage on a specific frame, or frame region.
Sequances:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/f469875d-2956-4cfc-9562-a7535c792481)
Sprites:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/c262c477-4e79-45a5-9d6b-a1751fcd5053)

### Describe the solution you'd like

Add moment option in Sprites
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/86778afb-9145-44b2-8cd6-6be7e601374d)

### Describe alternatives you've considered

Either manually injecting it in with code by referencing the internal Sequence used by structs (which im not even sure is possible? unsure haven't tried), or having a frame checker which checks if all objects currently using that sprite are on any of the specified frames, needless to say this is very slow to do.

### Additional context

gimme gimme
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48543299/59f435db-b5b1-4203-8564-692f70aec86c)

**Comment by stuckie** [comment]
This is not something we are currently planning.
You can use them in Sequences.
