### ISSUE TITLE
Variable defintion Asset type values are erased every time you open a project

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6257]
### Description
As far as I'm able to tell, every single Variable Definition of type "Asset" gets reset to `noone` whenever you close and re-open a project in the current beta IDE.

### Steps To Reproduce
1. Open the project
2. Drag something from the asset browser to the variable definition in Object1
3. Close the project
4. Re-open the project
5. https://www.youtube.com/watch?v=sg3UqQZXnBc

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[914e08c3-39b9-4b0e-956b-ed082d1d14a1](https://api.gamemaker.io/api/github/downloads/914e08c3-39b9-4b0e-956b-ed082d1d14a1)

**Comment by DragoniteSpam** [comment]
In case anyone in the audience wants to try it out just to make sure I'm not losing my mind:

[test.zip](https://github.com/user-attachments/files/15830683/test.zip)

**Comment by Hyomoto** [comment]
It's much worse than that, variable definitions are broken period.  They seem to respect a "default" value (the value set when the type is selected), but they do not respect any *set* values, in addition to wiping out any values they might have been.

**Comment by DragoniteSpam** [comment]
it's been a while since i've found a beta containing something this exciting

**Comment by DragoniteSpam** [comment]
Turns out this one has a twin: #6259

**Comment by KormexGit** [comment]
It appears to not actually be changing the variable definitions, since github shows no changes even when the IDE is showing noone and it's not working at runtime as per #6259.

It's also not happening for every variable for me, on beta:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/86c66b7f-d31a-46ce-b619-5224b927523f)

Opening the same project in monthly again after opening it in beta, everything goes back to how it should:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/0e409918-4951-40f6-ae7c-ca6a9fde1d23)

**Comment by KormexGit** [comment]
Ok so it looks like variable definitions of EVERY type are reset:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a964fb22-f677-472c-b6ed-9ca774cb9939)

But only base ones, inherited ones that have been overwritten are not reset:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/ff4971f6-84ba-460c-9ac3-031078c0b52a)

**Comment by KormexGit** [comment]
One more observation, if you change the name of a variable definitions variable in beta, it WILL show up in github as being changed to 0.0 or whatever, and will actually be 0.0 when opened in monthly.

**Comment by YYDan** [comment]
Yes, the runtime and IDE combination is important with this feature, so this is the same as 6257. Be aware you will need to update your IDE and runtime when we release the fix.

**Comment by YYDan** [comment]
Seems all fine in  IDE v2024.600.0.576  Runtime v2024.600.0.602

The test.zip mentioned higher up seems already changed if I open it now, but the version with more content that is attached to 6259 worked just fine.

I then extended it to cover a lot more variable definition types and to check instance-overriding and parent-child overrides:
[test-Dan.zip](https://github.com/user-attachments/files/15838538/test-Dan.zip)

I now get the correct result each time I run the game, even after closing and reopening the project multiple times:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/91242f00-00e2-4bb1-b837-1c0029bc7cb3)

**Comment by YYDan** [comment]
(Just for our own records...) Whereas, yes, changing back to runtime 601 and restarting GM, then running the game shows all the wrong values:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/8040d892-6d99-426e-8389-829267598cfe)
