### ISSUE TITLE
Variable defintion Asset type values are erased every time you RUN a project

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6259]
### Description
Today's Double Feature Friday, apaprently.

This smells a lot like #6257 but I'm reporting it separately because that one was an IDE bug, but this one's a runtime bug.

It's largely the same, but even if you use Beta Runtime 601 with an older IDE that doesn't feature #6257, the runtime will still erase asset reference Variable Definitions.

### Steps To Reproduce
1. Set the asset_ref variable defintion to something
2. Run the game
3. It resolves to -4 at runtime

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.574 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[da9bc949-0e09-465c-ac19-51b33f318d2b](https://api.gamemaker.io/api/github/downloads/da9bc949-0e09-465c-ac19-51b33f318d2b)

**Comment by KormexGit** [comment]
Similar to #6257, this happens to variable definitions of all types, not just assets

**Comment by YYDan** [comment]
Yes, the runtime and IDE combination is important with this feature, so this is the same as 6257. Be aware you will need to update your IDE _and_ runtime when we release the fix.

**Comment by YYDan** [comment]
See my comment on 6257 for verification.
