### ISSUE TITLE
Code Editor 2: Changing the padding lines Preferences do not immediately update currently-open editors

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6265]
### Description
Changing the "Padding lines preceding document" and "Padding lines following document" settings doesn't apply to already open code windows.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8c1e3d5d-0cfe-4296-b16e-159871adfc65

### Steps To Reproduce
Changing the padding settings while a code window is already open

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[bf31447d-c4e1-471d-98aa-e45d88831195](https://api.gamemaker.io/api/github/downloads/bf31447d-c4e1-471d-98aa-e45d88831195)

**Comment by zreedy** [comment]
Fixed.

**Comment by alicemoretti** [comment]
Verified fixed on Beta IDE v2024.800.0.593 Beta Runtime v2024.800.0.617.

Thank you.
