### ISSUE TITLE
Code Editor 2: Color of unset variables not changeable in themes

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6266]
### Description
Right now unset variables are either grey or (incorrectly) yellow. They are not present in the theme settings to change.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/81b55102-8c67-4803-8d39-ef8940f4c601)

### Steps To Reproduce
Use a variable that isn't set to anything, and then look at the theme options.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4fe62a01-d292-4124-bf19-58c742536742](https://api.gamemaker.io/api/github/downloads/4fe62a01-d292-4124-bf19-58c742536742)

**Comment by zreedy** [comment]
"Unset Variables" are not a scope recognized by the Language Server, nor the GML tmLanguage. The color would instead be specified by `General -> Foreground`

**Comment by zreedy** [comment]
Fixed. The Server now marks `variable.parameter` and `variable.unset` appropriately, and the GameMakerDark.tmTheme now includes entries for these. Although the colors selected may change or revert to what was used before.

**Comment by caitlinrmcintyre** [comment]
Verified in  IDE v2024.800.0.595  Runtime v2024.800.0.619, thanks.
