### ISSUE TITLE
Code Editor 2: Function Name - support.function setting in the theme editor appears to do nothing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6269]
### Description
I was told that the difference between "Function Name - entity.name.function" and "Function Name - support.function" is that one is for built in functions and the other is for user defined functions, but the former affects both and the latter doesn't seem to affect anything.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8d68fba5-8b56-4485-96ac-914248dee1fd)

### Steps To Reproduce
Change the "Function Name - support.function" color in the theme editor.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[cd40fd06-a51c-4bc3-aae9-41050f9e5121](https://api.gamemaker.io/api/github/downloads/cd40fd06-a51c-4bc3-aae9-41050f9e5121)

**Comment by zreedy** [comment]
Additionally, "support.function" is incorrectly labeled it should be "Built-in Function".

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.597  Runtime v2024.800.0.620
