### ISSUE TITLE
[Ubuntu] Can't build to Raspi 5 using YYC

### ISSUE THREAD

**Issue by AlexZiska** [YoYoGames/GameMaker-Bugs#6270]
### Description

Using the latest version of Raspberry Pi OS (64-Bit) on a Raspberry Pi 5. I can build using the VM but I can not build using YYC (which I want though in order to hopefully achieve more FPS and therefore smoother gameplay).

There are no errors in the "compile error" window. In the output, the only thing I get, which looks like an error, says:

System.Exception: command 'make -C /home/user/GameMakerStudio2/yyc/SuperShinNeo -j `nproc --all`' failed with exit status 2
at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
at Igor.LinuxBuilder.LinuxSendAndBuildMakefile(String _dir)
at Igor.LinuxBuilder.Run()
Igor complete.

In the forums, DanC suggested the following: 
> "Some errors don't get captured by the console output on the Linux target, what do you get if you run the 'make -C /home/user/GameMakerStudio2/yyc/SuperShinNeo -j `nproc --all`' command in the terminal on the Pi yourself?"

I did so and got this result:

user@devpi5:~ $ sudo make -C /home/user/GameMakerStudio2/yyc/SuperShinNeo -j `nproc --all`

make: Entering directory '/home/user/GameMakerStudio2/yyc/SuperShinNeo'

mkdir -p out

clang -std=c++14 -O3 -Wno-deprecated-writable-strings -I Game -include-pch out/ pch.hpp.pch -lcurl -Wl,-s -I . -o SuperShinNeo out/*.o -DYYLLVM libyoyo_yyc-a rm64.a /usr/lib/aarch64-linux-gnu/libstdc++.so.6 /usr/lib/aarch64-linux-gnu/libz .so /usr/lib/aarch64-linux-gnu/libXxf86vm.so /usr/lib/aarch64-linux-gnu/libGL.so /usr/lib/aarch64-linux-gnu/libm.so /usr/lib/aarch64-linux-gnu/librt.so /usr/lib /aarch64-linux-gnu/libpthread.so /usr/lib/aarch64-linux-gnu/libdl.so /usr/lib/aa rch64-linux-gnu/libcrypto.so /usr/lib/aarch64-linux-gnu/libXext.so /usr/lib/aarc h64-linux-gnu/libX11.so /usr/lib/aarch64-linux-gnu/libXrandr.so /usr/lib/aarch64 -linux-gnu/libGLU.so /usr/lib/aarch64-linux-gnu/libssl.so -Wl,-rpath,\$ORIGIN

clang: error: no such file or directory: '/usr/lib/aarch64-linux-gnu/librt.so'

clang: error: no such file or directory: '/usr/lib/aarch64-linux-gnu/libpthread. so'

clang: error: no such file or directory: '/usr/lib/aarch64-linux-gnu/libdl.so'

make: *** [makefile:32: SuperShinNeo] Error 1

make: Leaving directory '/home/user/GameMakerStudio2/yyc/SuperShinNeo'

DanC then suggested that this might be a bug and I should report it as such.

[SuperShinNeo.zip](https://github.com/user-attachments/files/15838319/SuperShinNeo.zip)

### Steps To Reproduce

1. Start GameMaker
2. Compile to Raspi 5 with latest Raspberry Pi OS 64-Bit using YYC
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10, Ubuntu 20 LTS

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Looks like the libraries have a version appended to them:
https://packages.debian.org/search?suite=bookworm&arch=arm64&mode=filename&searchon=contents&keywords=librt.so
https://packages.debian.org/search?suite=bookworm&arch=arm64&mode=filename&searchon=contents&keywords=libpthread.so
https://packages.debian.org/search?suite=bookworm&arch=arm64&mode=filename&searchon=contents&keywords=libdl.so

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.800.0.613 Beta Runtime v2024.800.0.636.
