### ISSUE TITLE
Manual Content: Snippets page needs to say that Code Editor 2 does not support the F4 key for showing snippets

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6273]
### Description
In CE1, pressing F4 brings up the snippets menu. In CE2, it does nothing.

### Steps To Reproduce
Press F4.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[1620d176-3022-4305-8f8c-6f3ade99585c](https://api.gamemaker.io/api/github/downloads/1620d176-3022-4305-8f8c-6f3ade99585c)

**Comment by zreedy** [comment]
There is no Snippet menu in CE2 as Snippets have moved to the Code Completion Window. There is no way to query for Snippets specifically via LSP, and their implementation is done via the LSP Completion Request API.

In short, this is expected and documented behavior.

**Comment by KormexGit** [comment]
Is it already a known issue that snippets are not appearing in the code completion window?

**Comment by YYDan** [comment]
Yes, https://manual.gamemaker.io/beta/en/The_Asset_Editors/Code_Editor_Properties/Code_Snippets.htm does say this, but in fairness it's a small section somewhat hidden at the bottom of the page (and also is titled "The Code Editor", so someone looking for differences in CE2 and not aware we call CE1 the _script_ editor in the manual now might not even read it.

Suggest we edit the first line of that page to talk about what a snippet is, then move the CE2 paragraph right up near to the top (_above_ the stuff which relates only to CE1), then have a new heading to distinguish CE2 from CE1 behaviours.
