### ISSUE TITLE
Code Editor 2: Manually adding a closing bracket at least 1 line of white space after the opening bracket will not indent to the correct level

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6275]
### Description
See video:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6f8ccdd9-755b-4b61-af09-3f91591cb671

### Steps To Reproduce
Type `if thing{}`, then delete the }, then hit enter twice and re-add the }

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[aef96664-df72-40b9-bbff-b31409ca4356](https://api.gamemaker.io/api/github/downloads/aef96664-df72-40b9-bbff-b31409ca4356)

**Comment by zreedy** [comment]
Fixed.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1000.0.621  Runtime v2024.1000.0.647
