### ISSUE TITLE
Inversed loop move for audio in sequences

### ISSUE THREAD

**Issue by Patchy-DaYo** [YoYoGames/GameMaker-Bugs#6277]
### Description
Simple yet problematic bug in the current version of GM. The Loop Mode property specified for audio tracks in sequences is reversed in-game.

In the GameMaker IDE, when working on the project, loop mode works as expected: "play once" only plays the sound once and loop repeats the sound. However, when playing the exact same sequence in the game, the results is inversed. Audio tracks set as "play once" loop automatically and vice-versa.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Which platform(s) are you seeing the problem on?
Windows

[5d1b65c8-eed6-4ebb-a55d-bbde8df6cfe9](https://api.gamemaker.io/api/github/downloads/5d1b65c8-eed6-4ebb-a55d-bbde8df6cfe9)

**Comment by toby-yoyo** [comment]
Fixed in 2024.8

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.587  Runtime v2024.800.0.611, thanks.
