### ISSUE TITLE
Code Editor 2: Making code edits while syntax highlighting is still loading will prevent all other code in the same event from getting colored

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6280]
### Description
If you have a large project, it takes quite a while for feather messages and syntax highlighting to load in. If you type some code during this loading time, all other code in the event you typed in will not get colored when the loading finishes. 

Another small thing, as seen in the video, is that right as loading finishes, autocomplete will flash for a bunch of the code that was just typed all at once.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/06d164d1-98d1-4218-ade7-5c138f22283d

I've attached my main project, which takes a long time to load, to make it easier to test compared to a sample project that loads quickly.

### Steps To Reproduce
Have a sufficiently large project that loading takes a bit. Type some code during that time.

For the sample project: Open up UseMeToTestTheBug. With the code window is open, reload the project. While things are still loading, type some random stuff into one of UseMeToTestTheBug's events. What exactly is typed doesn't matter.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[bf39a9c9-7a6a-4ff7-a888-34926a7ad851](https://api.gamemaker.io/api/github/downloads/bf39a9c9-7a6a-4ff7-a888-34926a7ad851)

**Comment by zreedy** [comment]
Fixed by other closed tickets.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.594  Runtime v2024.800.0.618
