### ISSUE TITLE
Code Editor 2: Syntax highlighting failed to load on project with only two lines of code

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6284]
### Description
Just opened up a small test project that only had two lines of code, and syntax highlighting for variables and functions doesn't appear to be working at all, for the two existing lines nor newly typed ones. This was the first project launched when I opened GM today, so no reloading of any kind.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/eddceb1b-90c7-42da-8eb8-f0096933a4c2)

Reloading the project after filing this report fixed it.

### Steps To Reproduce
Open a project and get lucky (unlucky?) I guess, I mostly reported this in case the log files were helpful at all

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[38970767-8f1a-42b3-b9d0-64ee6f80d3a7](https://api.gamemaker.io/api/github/downloads/38970767-8f1a-42b3-b9d0-64ee6f80d3a7)

**Comment by zreedy** [comment]
Unable to reproduce. I suspect this has been fixed as apart of other similar issues.
