### ISSUE TITLE
Code Editor 2: Function argument tooltip will disappear if you backspace at any point while typing your arguments

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6286]
### Description
I'm not the best typist, and often have to backspace mistakes I make. But that makes the function argument tooltip disappear :(

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/2c48699b-7828-4203-b971-8c95b27bd89b

### Steps To Reproduce
Type a function, start typing one of the arguments, and then hit backspace.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[f07557fa-4685-416a-afca-4deca7e9300c](https://api.gamemaker.io/api/github/downloads/f07557fa-4685-416a-afca-4deca7e9300c)

**Comment by zreedy** [comment]
Fixed. The dismiss logic did not take into consideration backspace so it saw the boundary of `)` and dismissed assuming the character was typed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.588  Runtime v2024.800.0.612, thanks.
