### ISSUE TITLE
In-Game: [YYC] Throw() dialogs only show the custom message, none of the callstack that VM includes

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6288]
### Description
In the latest 2024.600 beta, as the title explains, errors are now missing all information.

Here's an error on the VM:
```log
ERROR!!! :: ############################################################################################
ERROR in action number 1
of Create Event for object oTest:
Unable to find a handler for exception oh no

 at gml_Script_other_thing (line 7) - 	throw "oh no";
############################################################################################
gml_Script_other_thing (line 7)
gml_Script_blah (line 3) - 	other_thing();
gml_Object_oTest_Create_0 (line 1) - blah();
```
And here's what shows up on YYC:
```log
ERROR!!! :: oh no
```

### Steps To Reproduce
Throw an error somewhere. Compare the text in the Code Error window between VM and YYC.

Quick copy-paste example:
```gml
function blah() {
	other_thing();
}

function other_thing() {
	throw "oh no";
}

blah();
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
GX.games, Ubuntu, Windows

[982b4d20-7374-42e2-a2ee-3eb8035c2dea](https://api.gamemaker.io/api/github/downloads/982b4d20-7374-42e2-a2ee-3eb8035c2dea)

**Comment by YYDan** [comment]
And IDE v2024.2.0.132 Steam  Runtime v2024.2.0.163

**Comment by rwkay** [comment]
this is not a bug - it is throwing exactly what you tell it too... that is what is expected.
