### ISSUE TITLE
Docs: GX.games YYC setup FAQ instructions missing instructions for Binaryen on Windows 

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6289]
### Description

The documentation for setting YYC up for GX.games [here](https://help.gamemaker.io/hc/en-us/articles/4625548722193-Setting-Up-For-GX-games) does not give a working setup. I've not actually used this ever before, but it came up as I wanted to test WASM for completeness for another report about YYC in 2024.600.

The commands provided currently install and activate the Emscripten SDK, but:

1. Running out of the box after this setup and pointing the IDE to the install location, compilation will fail telling you you must generate a `.emscripten` configuration file.
2. Emscripten asks for another dependency, [Binaryen](https://github.com/WebAssembly/binaryen/releases), which is also not mentioned. **The generated config will additionally, on Windows, generate the wrong path.** This then gives an error that `/usr/local\bin\wasm-opt.exe` could not be found. You must actually install from the aforementioned link, and provide its location in the config.

### Manual Link

https://help.gamemaker.io/hc/en-us/articles/4625548722193-Setting-Up-For-GX-games

**Comment by stuckie** [comment]
Can you confirm that you have specifically installed and activated emsdk 3.19 as detailed further down in the install guide?

**Comment by thennothinghappened** [comment]
I do not have 3.19. The guide specifies _3.1.9_, but also says that you should check a different page [here](https://help.gamemaker.io/hc/en-us/articles/227860547-GameMaker-Required-SDKs#h_01GF3MF7FPPX7A3J8RT2253M6G) for the up-to-date version to use, which currently specifies 3.1.47, which I used.

**Comment by YYDan** [comment]
Yes, you are correct that the page says to check the main required SDKs FAQ and that you should be using 3.1.47 in recent versions of GM.

However, I have just realised the path you're saying you need to add the binary into suggests you're using a Linux distro. 

We actually suspect you're hitting this Emscripten bug/known issue: https://github.com/emscripten-core/emscripten/issues/16251

Sounds like you're seeing the problem referred-to this discussion: https://groups.google.com/g/emscripten-discuss/c/a-Ph7m7CXAU?pli=1


Our guide explicitly says it only covers Windows IDE users and to see Emscripten's own docs for Mac/Ubuntu IDE users, but regardless we have now repeated the guide on multiple machines yesterday and today and confirmed that Windows and Mac do not require this configuration file or additional binaries that you have mentioned.

Accordingly, there is no change we need to make to our guide, as we already say to check Emscripten's own setup guide if using a Mac or Ubuntu IDE.

**Comment by thennothinghappened** [comment]
> Yes, you are correct that the page says to check the main required SDKs FAQ and that you should be using 3.1.47 in recent versions of GM.
> 
> However, I have just realised the path you're saying you need to add the binary into suggests you're using a Linux distro. 
> 
> We actually suspect you're hitting this Emscripten bug/known issue: https://github.com/emscripten-core/emscripten/issues/16251
> 
> Sounds like you're seeing the problem referred-to this discussion: https://groups.google.com/g/emscripten-discuss/c/a-Ph7m7CXAU?pli=1
> 
> 
> Our guide explicitly says it only covers Windows IDE users and to see Emscripten's own docs for Mac/Ubuntu IDE users, but regardless we have now repeated the guide on multiple machines yesterday and today and confirmed that Windows and Mac do not require this configuration file or additional binaries that you have mentioned.
> 
> Accordingly, there is no change we need to make to our guide, as we already say to check Emscripten's own setup guide if using a Mac or Ubuntu IDE.

I did say in the original issue but to clarify again I am on Windows, NOT Linux. Emscripten generated a configuration that pointed to a completely invalid path. I had to fix it to point to my C drive and to where I had put Binaryen.

**Comment by thennothinghappened** [comment]
Hey, just bumping this issue again as it's still incorrectly closed as I wasn't on linux

**Comment by stuckie** [comment]
Re-opened and highlighted the note about being on Windows, and it generating a Linux-style path.

**Comment by YYDan** [comment]
"When I have the time I'll see if I can uninstall the SDK and record the process I had to go through a second time, given you were not able to reproduce it."

Tbh, I think we'll need to wait for your feedback there and whether you can identify why you're getting this, as this is the only report I have seen mentioning being asked for this extra stuff and yet the target has been available for ages ;)

We did have a good search around back at the time I replied last and the Linux issue was the only thing which fit.

I would definitely agree with removing everything Emscripten and starting again when you get chance, then let us know how you get on. Thanks!

**Comment by thennothinghappened** [comment]
Will do! - I am quite busy at the moment and it'll be a good while before I can get back to this, but I'll update when so.

**Comment by Lukanibal** [comment]
Hi, I am moving between Windows and Linux a lot right now and noticed some issues with the Windows setup.
Binaryen was not installed and the generated config file points to a Linux filepath even though I'm on Windows.
This seems to be an issue with emscripten's default config file and possibly it's install script, as I am unable to find binaryen anywhere in the installed sdk folder, except for some stub files that contain the name.

Installing binaryen and pointing the config file to the corrected Windows path fixed my build issues.
I accidentally installed a newer version than it expected, but it still works. (it wants version 115)
