### ISSUE TITLE
Code Editor 2: Button to remove an instance's creation code from the list doesn't work

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6291]
### Description
Right now, once you open an instance's creation code, it'll be in the list forever unless you delete the instance itself. This is because the X icon to delete it in the navigation panel currently does nothing. Additionally, if an instance's name is longer than the width of the navigation panel, it can't scroll far enough to the right to see the X for whatever instance has the longest name.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/26e96618-3487-45c5-8e21-ebd902ec0f87

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/d061128b-dbd9-4b0e-8322-e2122557e0ff)

### Steps To Reproduce
Open up an instance's creation code, then try to get rid of the creation code by pressing the X icon.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[cdab4014-a4b0-4c87-85d1-19251ec90491](https://api.gamemaker.io/api/github/downloads/cdab4014-a4b0-4c87-85d1-19251ec90491)

**Comment by zreedy** [comment]
Fixed. Note that the Room Creation Code cannot be deleted.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.595  Runtime v2024.800.0.619
