### ISSUE TITLE
Code Editor 2: Opening an instance's creation code doesn't put the cursor on that instance's code

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6292]
### Description
When you open an instance's creation code, if the room creation code tab was previously not open, the cursor always goes to the room creation code. If the tab was already open, the navigation panel will correctly show the instance you just opened as being selected, but the cursor won't be placed anywhere at all and typing won't do anything until you click somewhere manually.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/75938578-eda4-4a64-a2ea-9d23d340b258

### Steps To Reproduce
Open up an instance's creation code.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[65f13972-fdb6-40ac-8f8b-b8016a1db2fd](https://api.gamemaker.io/api/github/downloads/65f13972-fdb6-40ac-8f8b-b8016a1db2fd)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
the "creation code" button now works as expected  in  IDE v2024.800.0.588  Runtime v2024.800.0.612

but if the user goes via the edit creation code in the inspector, after selecting the same instance, the above issue occurs
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/34f377bd-0fb4-446a-b932-3cd428cd16cf)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/7fbc050c-2395-4c8e-826d-90d91bf4f4aa)
