### ISSUE TITLE
Code Editor 2: Issues with global search/replace when replacing the same thing multiple times on one line

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6293]
### Description
If something appears multiple times on one line and you replace it using the global search replace, it does not replace properly. If the new variable is shorter, it will delete some of the code that follows the 2nd case of it. If the new variable is longer, part of the code that should have gotten replaced will remain.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/52fd3f2a-e2ae-4851-acfa-37427f0a740d

The problem does not occur when using local search replace (ctrl + f) or CE1.

### Steps To Reproduce
```
var replaceMe = {x : x, y : y}


if place_meeting(replaceMe.x, replaceMe.y, Object2) {

}
``` 
Press ctrl + shift + f, and replace "replaceMe" with something else.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[279bf60c-e28b-477f-93fc-c6cd53f68c50](https://api.gamemaker.io/api/github/downloads/279bf60c-e28b-477f-93fc-c6cd53f68c50)

**Comment by thennothinghappened** [comment]
Just adding in an example of replacing space indent with tabs also makes CE2 hungry:

https://github.com/YoYoGames/GameMaker-Bugs/assets/35243139/2bd1df7e-6201-4474-ae59-85af8d6ae125

...also for the record I meant 4 spaces, not 3, 3 space indentation would be evil lol

**Comment by zreedy** [comment]
Only reproducible with the Global Search/Replace functionality. Suspected local search/replace is fixed by other closed tickets.

**Comment by KormexGit** [comment]
This bug actually never happened for local search replace, it's always been global search replace only

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.600  Runtime v2024.800.0.623
