### ISSUE TITLE
Code Editor 2: Using search replace to replace a variable with something longer than before then hitting ctrl+z does not undo it fully 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6294]
### Description
If you search replace and replace a variable with something longer, then hit ctrl+z to undo it, it will put the old variable name back, but not undo adding the new name. Unlike #6293, this applies to both global search replace and local search replace.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/d4d55c66-3ff0-4dd4-aeeb-8a6277bbe122

This issue is not present when using CE1.

### Steps To Reproduce
```
var replaceMe = {x : x, y : y}


if place_meeting(replaceMe.x, replaceMe.y, Object2) {

}
```
Search replace using ctrl + F or ctrl + shift + F, and replace "replaceMe" with something longer. Then, try to undo it using ctrl + z.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[bf93d698-587a-4225-80ac-e5447f3f0723](https://api.gamemaker.io/api/github/downloads/bf93d698-587a-4225-80ac-e5447f3f0723)

**Comment by zreedy** [comment]
Unable to reproduce. Suspected fixed due to other bug fixes.
