### ISSUE TITLE
Code Editor 2: Text cursor acts funky with comments

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#6301]
### Description
Normally I'd give a better description, but I find it somewhat hard to fully describe it. But basically the text cursor seems to overly estimate where it's at and jumps into the wrong position. Everything before and after // works fine, but it's only while you're interacting with the comment slashes themselves.

Font I am using is [Fira Code](https://github.com/tonsky/FiraCode). Happens with ligatures on.

### Steps To Reproduce
See video for demonstration added below as comment (happens in all projects)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[fc323c00-8410-45fa-a006-8c273767ec3c](https://api.gamemaker.io/api/github/downloads/fc323c00-8410-45fa-a006-8c273767ec3c)

**Comment by tabularelf** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/8fb6bd49-03ee-4548-9840-a027d45a1d1a

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.599  Runtime v2024.800.0.622, thanks.
