### ISSUE TITLE
Detached workspace window code loads as blank

### ISSUE THREAD

**Issue by bocoboc** [YoYoGames/GameMaker-Bugs#6307]
### Description
When you have a detached workspace window with any kind of code tab in it (script, object event code, notes) and you save and close the project, it does open separate window with the code after you load it again. But its content is blank.
You can see it in the screenshot.

### Steps To Reproduce
1. Create empty project with any kind of code
2. Click RMB on its tab handle a press detach workspace
3. Save and close project (exit GameMaker or go to home screen)
4. Load the same project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c5c5f5b3-2d47-4866-ac20-e57f81031021](https://api.gamemaker.io/api/github/downloads/c5c5f5b3-2d47-4866-ac20-e57f81031021)

**Comment by bocoboc** [comment]
<img width="700" alt="Screenshot_1" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/8362357/024849f4-4be9-465d-9a2a-21ebffb77ef6">

**Comment by yyalansavage** [comment]
Code tabs will now detach & restore on project load correctly. Note I have removed the "Detach Workspace" option from general tabs as this was not properly supported (would never restore on project reload, and could often fail to populate the content in the new desktop)

**Comment by alicemoretti** [comment]
Verified fixed on Beta IDE v2024.800.0.593 Beta Runtime v2024.800.0.617.

Thank you.
