### ISSUE TITLE
font_get_info() omits kerning information for some glyphs

### ISSUE THREAD

**Issue by Mtax-Development** [YoYoGames/GameMaker-Bugs#6310]
Contains project for #6278
https://github.com/user-attachments/files/15873425/font_get_info.omits.kerning.information.zip

-----
### Description

While attempting to write an equivalent of GameMaker `draw_text()` rendering for use through a Vertex Buffer, it came to my attention that it is impossible to exactly replicate its positioning by basing on data returned by `font_get_info()`, as it omits information that is otherwise available in the `.yy` properties file of the font. This appears to be the case only for some glyphs and it does not appear that using a different configuration for the font affects it.

***

Example below illustrates the difference on the "f" glyph (`ord 102`) information for the font Arial Black:

`"kerningPairs"` property in the `.yy` file:
```
    {"amount":2,"first":102,"second":32,},
    {"amount":4,"first":102,"second":33,},
    {"amount":-2,"first":102,"second":44,},
    {"amount":-3,"first":102,"second":46,},
    {"amount":4,"first":102,"second":63,},
    {"amount":-1,"first":102,"second":101,},
    {"amount":1,"first":102,"second":102,},
    {"amount":-1,"first":102,"second":111,},
    {"amount":4,"first":102,"second":8217,},
    {"amount":4,"first":102,"second":8221,},
```

Data returned by `font_get_info()`:
```
    "f":{
      "x":814.0,
      "y":245.0,
      "char":102.0,
      "w":87.0,
      "kerning":[
        0.0,
        0.0
      ],
      "h":241.0,
      "offset":1.0,
      "shift":67.0
    }
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

**Comment by jackerley** [comment]
Investigating this I did find an error with the reported kerning information which I have fixed, but the enclosed project still won't return the expected values as kerning information is stored in the second glyph as it's when rendering that glyph that it is needed, so the kerning data for f glyph will only contain [102,1] the kerning information for     {"amount":1,"first":102,"second":32,}, will be under space (which you can access via 	glyph_space_info = info.glyphs[$ " "];
