### ISSUE TITLE
blank page when running html5 game

### ISSUE THREAD

**Issue by uyepez** [YoYoGames/GameMaker-Bugs#6328]
### Description

When I run any new or existing game, a blank page appears when the web browser opens, the error appears in the queue: Uncaught ReferenceError: GameMaker_Init is not defined
 at index.html:110:17

### Expected Change

make the html run correctly and show the game

### Steps To Reproduce

1. Start GameMaker
2. create or open an existing game
3. select export in html5 and gamemaker open the web browser
![errorGML](https://github.com/YoYoGames/GameMaker-Bugs/assets/17145757/945ff9e4-27c8-4153-8f12-39ebaaa597e4)
[memoriGame.zip](https://github.com/user-attachments/files/15891506/memoriGame.zip)

4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Hi, you are currently using runtime 2023.8.2.152 I've tried your project in runtime 2024.600.0.605 and it runs without error, I would recommend upgrading the version of GM that you are using as we will not be going back to fix issues in older runtimes
