### ISSUE TITLE
In-Game: Changes new in runtime 2024.600.0.603 make some structs inaccessible

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6332]
### Description
When upgrading from runtime 2024.600.0.602 to 2024.600.0.603, our project started to have issues accessing certain structs in memory. When running in debugger mode, the in-memory struct is displayed as valid in the Watch, but when calling functions like `json_stringify()` on it and storing the returned string to a local variable, we get the error `"local variable * not set before reading it."`

### Steps To Reproduce
1. Put a break point at `BschemaSchemas.gml` line 136
1. Run the project under the `dev` config for windows VM export in debugger mode
2. Inspect in memory that the struct `BSCHEMA` is valid
3. Step over to the next line and see an error is thrown saying that the local varialbe `whole_j` is not set

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.577 Runtime v2024.600.0.603

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[5e8dc13e-22c1-4f69-b87d-582f50474be7](https://api.gamemaker.io/api/github/downloads/5e8dc13e-22c1-4f69-b87d-582f50474be7)

**Comment by shichen85** [comment]
![GameMaker-Beta_2Z4aA42pfx](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/71c5334d-e3e9-478f-a541-d47dcd66772b)

As the screenshot shows, the local var `whole_j` can be seen from the memory but is not shown in the watch or the local scope.

**Comment by YYDan** [comment]
Suspected to be caused by the fix for https://github.com/YoYoGames/GameMaker-Bugs/issues/6190 - will take that one out again just now and investigate a different fix.

**Comment by YYDan** [comment]
Yes, running the project for Win VM debugger using the "dev" config in 603 actually gives me this error straight away:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/31d17944-49b3-45fe-8376-4f64f38ee091)

**Comment by shichen85** [comment]
Hello @YYDan,  I can confirm that 605 fixed the crashing issue. As for repro steps, if you change `BschemaSchema.gml`'s line 134's `_schema_id` to match the error's mentioning of `schema ID`, which is `video` in your run, you should be able to hit the break point.
![chrome_CxDxx6l9jT](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/404c122f-7ea9-4b1f-98f2-acf40c91fb4e)
![chrome_ZKsUSFLNpk](https://github.com/YoYoGames/GameMaker-Bugs/assets/35857473/9ce3f222-ed75-4e53-aaaf-2c7bc1865c40)

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637
