### ISSUE TITLE
The default label for dbg_text_input is "0.00" instead of the name of the variable ref

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6335]
### Description
When you use dbg_text_input in a debug view but don't provide a label, the label comes out as "0.00" instead of the name of the variable it's tracking like the other debug ui elements.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[a15912cf-e2e8-40f9-bacb-55e3cc66359a](https://api.gamemaker.io/api/github/downloads/a15912cf-e2e8-40f9-bacb-55e3cc66359a)

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.588  Runtime v2024.800.0.612
