### ISSUE TITLE
YYRunnerInterface: Extend script_perform() to allow running built-in functions

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#6338]
I'm not sure if this is intentional, but there appears to be no way to run built-in functions.

Script_Find_Id() works correctly to find & run user functions.

Code_Function_Find() also returns the correct built-in function ID, however attempting to use the ID with Script_Perform will incorrectly run a user function instead.

For example, the function "show_message" has the ID of 891. If I try to call Script_Perform with that ID, it runs the user function with the ID of 100891.

It feel like Script_Perform has a line of code that looks something like: `if (id < 100000) id += 100000;` which is preventing built-in functions from working.

### Expected Change

Built-in functions should be callable

Here's a small project that uses a DLL to call Script_Perform() on a user function & a built-in function. I've also included the .cpp file to show all code used in the DLL.

[Script_Perform Example.zip](https://github.com/user-attachments/files/15788101/Script_Perform.Example.zip)

_Originally posted by @jarrrodnb in https://github.com/YoYoGames/GameMaker-Bugs/issues/6091#issuecomment-2159397989_

**Comment by rwkay** [comment]
Fixed in 2024.8 - updated all the usage of Script_Perform in the current runner to ensure they are in the range for user scripts.

**Comment by DiasFranciscoA** [comment]
There is one thing missing: `Script_Perform` always returns false if we are running a built-in function

**Comment by rwkay** [comment]
Fixed in 2024.8 - See PR - https://github.com/YoYoGames/GMS2-Runner-Base/pull/139

**Comment by cameron-home** [comment]
Both projects run without issue in IDE v2024.800.0.599  Runtime v2024.800.0.622 so marking as verified
