### ISSUE TITLE
Tileset Editor: Possible to resize the sprite/tiles for a tileset and cause ! tiles to appear in relevant rooms

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#6343]
### Description
It is possible to resize the images/tiles for a tile set and cause the placed tiles to corrupt and show as a !

### Steps To Reproduce
1. import the attached project or the heros trail demo
2. make a new room and open, or use a pre-exisiting room
3. add a tile layer and place several tiles in the room
4. open the tile set and edit sprite
5. press "resize sprite"
12. an alert at the bottom is given that the sprite is a tile set resource
13. change settings in the resize canvas option, i.e resize canvas or scale, and press apply
18. notice the relevant tiles are now a !
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/72b5be83-33ab-4090-8cfb-8598a01e6de4)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[2923b678-af3c-4d34-8644-ef8fc01af0e1](https://api.gamemaker.io/api/github/downloads/2923b678-af3c-4d34-8644-ef8fc01af0e1)

**Comment by yyalansavage** [comment]
The ! tile simply indicates the tile index is no longer in the set of tiles of defined by the tileset. This will inevitably happen if you change (or at least reduce) the dimensions of the source sprite for a tileset already in use, and is expected behavour. Made a small change to the sprite resize dialog to always warn if the sprite is tileset source in addition to the warning label already present.

**Comment by mgeddesGM** [comment]
verified asof  IDE v2024.800.0.590  Runtime v2024.800.0.614
