### ISSUE TITLE
Bug Reporter: Change the "Privately attach project" from a checkbox to a dropdown and make it mandatory to select a valid choice

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6353]
### Is your feature request related to a problem?

I read the [list of closed bug reports](https://github.com/YoYoGames/GameMaker-Bugs/issues?q=is%3Aissue+is%3Aclosed) like a newspaper pretty much every morning to see what's going on, and on most days a large portion of the closed reports are of the "we can't do anything about this unless you attach a sample project" variety. This doesn't seem like a good use of anyone's time.

Doubtless some people will be antsy about sharing their whole project, because some people are like that, but it probably doesn't help that the "attach project" button is optional, defaults to "off," and is honestly pretty easy to miss.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/316e69bc-c150-4a37-8f15-e4244c323dde)

### Describe the solution you'd like

Something like this would make it harder to forget about.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/beaf8812-3a56-4afe-b250-424d42c2f7ea)

**Comment by DragoniteSpam** [comment]
If I recall in the past it was a radio yes/no checkbox, and I think it was changed to this to make it less confusing in the first place but in retrospect I'm not sure if that was really the best move.

**Comment by gnysek** [comment]
Btw. aren't attached files also private? It could be also added as info, that this files can be only view by YYG team, and won't be visible on github.

**Comment by YYDan** [comment]
That's already written there. (Twice, as if someone hovers over the question mark button it's explained more thoroughly there.)

But we will review the wording as part of making this change.

**Comment by gnysek** [comment]
It could be "private info" section with both items.

**Comment by YYDan** [comment]
Sorry - not sure what you mean there. Could you explain further, please?

**Comment by YYDan** [comment]
We had a similar-intention and related task already in-progress for 2024.8, but it was private, so I have just made it public and also linked it to this one, as this change will now need to be made in two places.

**Comment by gnysek** [comment]
Sth. like this - whole section for private things:
![obraz](https://github.com/YoYoGames/GameMaker-Bugs/assets/524094/4b9df46e-78da-4af4-a258-1cac9e1612c6)

**Comment by YYDan** [comment]
Ahh, so explain that BOTH gadgets are private, rather than only the second one saying this. Got it.

Thanks!

**Comment by YYDan** [comment]
So this: 

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/22c826b2-5b83-4a81-bf41-4bb43689070c)

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
