### ISSUE TITLE
varargs helper variable and/or explicit varargs syntax

### ISSUE THREAD

**Issue by coyo-t** [YoYoGames/GameMaker-Bugs#6355]
### Is your feature request related to a problem?

Currently within the realm of GML itself (excluding JSDoc comments) there is no way to explicitly define a function as having a variable argument count, nor is there a way to get the number of explicit named arguments vs the anonymous arguments you access via `argument[n]`
You either just make a function with *no* named arguments or you just keep track of the named argument count yourself and add it as an offset to `argument[]` (which is so blatantly error prone)

### Describe the solution you'd like

1. a builtin along the lines of `argument_named_count`. for functions without varargs, this will just be the same number as `argument_count`, however it can be used to A: get the number of varargs, and B: be used as an offset into the argument array to the first vararg

and (optionally) 2. syntax for showing a function accepts varargs
there are many ways this could be done, but i think something akin to lua/java is the best
`function f (arg1, arg2, arg3, ...extra)`

### Describe alternatives you've considered

as noted above, just manually keeping track of named argument counts, as annoying and error prone as it is.

### Additional context

i think this is a very important thing to consider since a lot of recent functions added to gml have had vararg suppourt in combination with named arguments, newer users might wonder/be dissuaded by why its so hands-on to do for their own functions/think its not even possible to begin with

**Comment by rwkay** [comment]
All functions in GML are implicitly varargs  (the same as JavaScript) the arguments that you tell us about are just the named arguments.
