### ISSUE TITLE
In-Game: [Spine] Precise touch handling on skeleton animations with two or more bounding boxes does not work

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#6361]
### Description

I tested it on both the release and beta versions.
Before upgrading to Spine 2D version 4, everything worked fine.
Now it is not possible to accurately handle touches for animations with more than one bounding box.

Working in 2.3.5.458:

https://github.com/YoYoGames/GameMaker-Bugs/assets/36339434/9f28a99d-c39c-4bce-984e-a9c13498d729

All affected releases mentioned below, including the new beta runtime 605:

https://github.com/YoYoGames/GameMaker-Bugs/assets/36339434/87c47d7d-2986-4e7a-8eae-613590c788a6

Contact pakage: [BboxIssue.zip](https://github.com/user-attachments/files/15925591/BboxIssue.zip)
Sample project: [TestBboxesNewRuntime.zip](https://github.com/user-attachments/files/15925702/TestBboxesNewRuntime.zip)

### Expected Change

When setting up the Spine mask, touches will be correctly processed according to the bounding box specified in the animation. It might be necessary to add some bounding box like Spine Collision Mesh (precise).

### Steps To Reproduce

1. Start GameMaker
2. Add spine animation.
3. Set bbox "Spine Collision Mesh"
4. Click on the object where there is no animation bounding box.
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2022.0.2 (LTS), 2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, Android, iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Point collisions on Spine collision meshes were broken (probably when I added the option to specifically enable them last year), other collision types (e.g. rectangle and line) still appear to work correctly.

Fixed on 2024.08 branch.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.603  Runtime v2024.800.0.625. 

Thank you.
