### ISSUE TITLE
Help Menu: Change "Create Your Contact Us Package" to upload the zip privately and return a download URL

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#6375]
### Description

It has become clear there is a "hole" in our bug-reporting processes in that if anyone wants to _privately_ add a sample project onto a new report they are currently creating via the website, or if we later want a sample to be added onto any existing bug report regardless of how it was created, the user must upload their project to some other hosting service and then add a download link for the file onto their bug report. However, this then means staff need to request access manually later on and the process is slow for everyone.

Accordingly, we have taken to closing these reports very quickly and asking people to file a replacement bug report with the files already attached - but this itself causes hassle and confusion for all involved and often means important information is spread over separate issues, as in many cases the original description and steps, etc., text is not repeated on the replacement issue.

Far better for all would be if we allowed a system of easily uploading samples privately and then the user can simply add a link onto the initial bug report to show the updated package has been sent.

### Expected Change

Rename "Create Your Contact Us Package" to "Upload a Bug/Ticket Sample" (as it's very rare anyone needs to create a contact-us package nowadays anyway) and modify the tool to show a new dialog that will allow the user to select their files, attach their project if desired, add any extra files they need (e.g., screenshots, videos, or log files), and then submit the upload request.

Note that the user must be logged-in before they can do this, as it needs to contact our server and get authorisation to upload something - we need to add a simple error dialog catching if someone is not logged-in and ask them to log in before showing the new contact-us dialog:
![signin](https://github.com/user-attachments/assets/1f1c6234-4e4f-440d-8a17-c8e2eb4f1642)

This new contact-us dialog should be made up of the same gadgets that the Bug Reporter dialog uses for this functionality. E.g., this mock-up plus a dialog box frame around the outside:
![image](https://github.com/YoYoGames/YoYoStudio/assets/15669932/25dcc378-0382-49a3-9a34-10f515907042)

(Note that the checkbox above being here also means the existing nag dialog for the "Create Your Contact Us Package" functionality that appears when you have a project open at the time would no longer be required.)

Once the user has made their choices and clicked the submit button, we should then automatically upload the file for them and show a progress bar dialog like the bug reporter shows while it is uploading a package.

Once the upload is complete they are returned the URL for the package on our server.

This link would then appear in the same manner as the one the IDE bug-reporter gives - the only difference being that we require an additional "Copy to clipboard" button to be added to the dialog, so that someone can simply click that button and then immediately paste into their browser the pre-formatted piece of text the button added to the system clipboard. 

(We could just add this functionality to the existing dialog the Bug Reporter uses, then use exactly the same dialog for both tools.)

**Comment by YYDan** [comment]
Note that the checkbox should be a dropdown to match https://github.com/YoYoGames/GameMaker-Bugs/issues/6353

**Comment by yyalansavage** [comment]
Feature build available - Zeus-Feature #308 ; note its functional for staging atm

**Comment by tabularelf** [comment]
Couldn’t this also be possible to allow adding to an existing issue optionally (as a comment, possibly) so copying to clipboard isn’t just the only option?

The GitHub API should allow you to search by author in this matter, and at least return a list of issues. (Perhaps alongside a search query).

I’m mostly thinking about easing the end user experience, and I think this would help out a lot! Copy to clipboard would still exist overall as the default option, whether the user has their GitHub account synced or not.

**Comment by tabularelf** [comment]
Also on that note, would it also be possible to add a list of links on the account page, for the user to obtain just in case they closed the window and had issues with copying to clipboard? 

I think having that would also help in cases where one doesn’t have their GitHub account sync, but has a GameMaker account. Giving them a place to copy links again (the list itself can be temporary, and should just mainly contain recent uploaded packages)

**Comment by YYDan** [comment]
The first suggestion would be a lot of work for only one of the use-cases suggested above. It's not a bad idea, but it's not going to be done as part of this issue.

The second one is something entirely separate and something I will propose internally for our Web team, as it's nothing for here ;).

**Comment by YYDan** [comment]
All works correctly in IDE v2024.800.0.600  Runtime v2024.800.0.623, but will leave off verifying until Docs are done reviewing any changes.

**Comment by YYBartT** [comment]
Updated the option on The Help Menu manual page, including its description and the screenshot. Also replaced hyperlinks that were still referring to "yoyogames.com".

**Comment by YYDan** [comment]
Yup, manual all looks good also, so verifying now.

**Comment by Emc1923** [comment]
Verified for LTS  IDE v2022.0.3.64  Runtime v2022.0.3.76
