### ISSUE TITLE
Sequences: Text tracks that use SDF effects in a sequence will be rendered differently in the Runner and IDE

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6378]
### Description

When adding a text track that uses a SDF font to a sequence, when adding some SDF effects the font will render differently within the IDE and the runner.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/105791928/8ab16397-caba-421f-a420-c91e008f908b)
[test_sdf_effects_win.zip](https://github.com/user-attachments/files/15930062/test_sdf_effects_win.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import the attached sample and run
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yymrennie** [comment]
Fixed in 2024.8

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.590  Runtime v2024.800.0.614, thanks.
