### ISSUE TITLE
[Ubuntu] Accessing clipboard crashes the game

### ISSUE THREAD

**Issue by SunCatMC** [YoYoGames/GameMaker-Bugs#6383]
### Description
In my game, on input screen pressing Ctrl+V adds string from clipboard to keyboard_string. On linux trying to use that shortcut crashes the game with an undefined value. If i comment out the line that acesses clipboard, the crash goes away

Have been reproduced on:
compiled on pop-os, ran on pop-os
compiled on ubuntu 24.04, ran on archlinux

### Steps To Reproduce
- Get my project
- Run the game
- Press Ctrl+V - observe the crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 24.04 LTS kernel 6.8.0.35

### Which platform(s) are you seeing the problem on?
Ubuntu

[3729c3af-ba6a-4fad-b49e-b25c9c1d3f97](https://api.gamemaker.io/api/github/downloads/3729c3af-ba6a-4fad-b49e-b25c9c1d3f97)

**Comment by yoyo-danielc** [comment]
Clipboard support added to Linux target on 2024.10 branch.

Test project for copy/paste: 
[clipboard.zip](https://github.com/user-attachments/files/16600362/clipboard.zip)

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.626  Runtime v2024.1100.0.652
