### ISSUE TITLE
[Ubuntu] Pressing Ctrl + any letter key creates an invalid character in keyboard_string

### ISSUE THREAD

**Issue by SunCatMC** [YoYoGames/GameMaker-Bugs#6384]
### Description
In my game keyboard input in shown inside text inputs. Whenever i press a Ctrl+key combination, the text shows invalid character.

Have been reproduced by compiling on ubuntu 24.04, and running on archlinux

### Steps To Reproduce
- Run my project game
- Press Ctrl+A (or any other letter) - see an invalid character appear in text input

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 24.04 LTS kernel 6.8.0.35

### Which platform(s) are you seeing the problem on?
Ubuntu

[e1f69367-5310-40ed-9c4f-5c3bbc40bc5f](https://api.gamemaker.io/api/github/downloads/e1f69367-5310-40ed-9c4f-5c3bbc40bc5f)

**Comment by yoyo-danielc** [comment]
Fixed in 2024.08 branch.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.598  Runtime v2024.800.0.621
