### ISSUE TITLE
[Ubuntu] WebSocket connection closed, error code 1002.

### ISSUE THREAD

**Issue by SunCatMC** [YoYoGames/GameMaker-Bugs#6385]
### Description
My game uses raw connection via websockets to archipelago.gg server. On windows everything works fine, but when compiling the gave on linux beta, and testing the game, after a short while after connecting it encounters 1002 error and disconnects.

Have been reproduced on:
compiled on pop-os, ran on pop-os
compiled on ubuntu 22.04, ran on ubuntu 22.04
compiled on ubuntu 24.04, ran on archlinux
compiled on ubuntu 24.04, ran on Ubuntu 24.04

### Steps To Reproduce
- Open https://archipelago.gg/room/BGTZ_H71RuSt238IHpC6Aw ap server to make sure it's running
- From that website look at the line that looks like `You can connect to this room by using '/connect archipelago.gg:50668' in the client.`. The number after `archipelago:gg:` is the server port that you need to provide the game
- Run Checksfinder
- Input the port into the appropriate text input (it will be saved for any subsequent runs; the save file at `~/.config/ChecksFinder/save_file.ini` can be reused)
- Press Enter to submit the connection data and connect
- Wait until in the game log the 1002 error appears
- You can try to communicate with the server further, by winning a game of minesweeper. The expected behavior when connected to the server is sending a collected check to it, then receiving random item - either board width, board height, or a bomb, which affects the game accordingly. The expected behavior when disconnected is to get a window pop up that says "Disconnected. Close the window to reconnect" - when doing as the window says should reestablish connection. But with our error the game instead receives more errors in log:
```
Client address is ::ffff:45.83.104.96
Socket(0): Connection to archipelago.gg failed: Broken pipe
Socket ConnectWrap failed error:-1
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 24.04 LTS kernel 6.8.0.35

### Which platform(s) are you seeing the problem on?
Ubuntu

[f6b30a2d-1257-4ccb-b17b-a45e7116601a](https://api.gamemaker.io/api/github/downloads/f6b30a2d-1257-4ccb-b17b-a45e7116601a)

**Comment by yoyo-danielc** [comment]
I've taken a look at your project and the issue is that you are calling `network_connect_raw_async()` on the same socket multiple times - this isn't supported and behaves differently on different platforms, once a connection has been lost you should destroy the socket with `network_destroy()` and reconnect using a new one.

Adding this code to the start of obj_tile_controller's Dialog event fixed the issue in the provided project:

```
network_destroy(global.client);
global.client = network_create_socket(network_socket_ws);
```

**Comment by SunCatMC** [comment]
@yoyo-danielc I implemented the fix you suggested in the latest version of my project, but the issue still persists. Same disconnect, same error.
[Checksfinder-project.zip](https://github.com/user-attachments/files/17263348/Checksfinder-project.zip)
