### ISSUE TITLE
part_****_layer doesn't accept layer IDs

### ISSUE THREAD

**Issue by kupo15** [YoYoGames/GameMaker-Bugs#6389]
### Description
Two functions I've been testing so far with particles have been providing me with errors and I figured out with another poster that this function is broken.

part_system_create_layer
effect_create_layer

these two don't accept layer Ids and only work with named strings. I'm not sure if other particle functions have the same bug

### Steps To Reproduce
// example 1 create event
var _layer = layer_create(12);
global.particle_system_ground = part_system_create_layer(_layer,false);

// example 2 step event

if layer_exists(layer)
effect_create_layer(layer,ef_star,x,y,3,c_red);

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7c3fc9e4-133a-4bd1-9f0e-e29802c0cace](https://api.gamemaker.io/api/github/downloads/7c3fc9e4-133a-4bd1-9f0e-e29802c0cace)

**Comment by jackerley** [comment]
Unable to reproduce in runtime 2024.600.0.605

**Comment by YYDan** [comment]
If you can still recreate this issue in Beta IDE v2024.600.0.579 Beta Runtime v2024.600.0.605 or newer, then please submit a new _in-game_ bug report (not an IDE crash again ;) ) and ensure you allow GameMaker to include your project. Thanks.
