### ISSUE TITLE
Code Editor 2: Tab key always adds [4] spaces instead of aligning to the nearest indentation size (Episode 2)

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6390]
### Description

This was marked as "fixed" when I reported it in #5492 but it still happens. Dunno if it's the same bug that has regressed, or if it's a different bug.

![ce2 tabs gif](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/be7c379b-2a37-4475-b16c-1f6cf7e0eac7)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed.

**Comment by zreedy** [comment]
Accidentally closed prior to merge.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
