### ISSUE TITLE
In-Game: Constant names of assets set in the room editor are not found at runtime and give "not set before reading it" errors when used

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6391]
### Description
If you set a custom constant name for an asset on an asset layer, this constant doesn't appear to actually exist at runtime. Using it in any way will trigger a "Variable <unknown_object>.blah not set before reading it." error, even though constants should always exist.

VM:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/087129ac-9441-4445-a846-d853e6638506)

YYC:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/84c90f12-1f62-41d3-b04f-61dcd813dccb)

And both above are despite the IDE working correctly:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/31fcf6b4-ef41-493e-a152-66af351550a3)

_As a note, this exact same issue exists on LTS too, so this issue has been around for a very long time._

### Steps To Reproduce
1. Start GM and import the attached project: [Bug4.zip](https://github.com/user-attachments/files/15954203/Bug4.zip)
2. Open the Object's create event and hover over the two asset names. Observe that the IDE knows that they are legit and that they point to a sprite/sequence correctly.
3. Run the project and observe that you get a code error.
Repro: 100%

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605
2024.4.1 (runtime 202)
LTSr2

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b50b428e-e06a-4ebf-937f-c047e9153001](https://api.gamemaker.io/api/github/downloads/b50b428e-e06a-4ebf-937f-c047e9153001)

**Comment by KormexGit** [comment]
One additional note I forgot to mention, it happens for the names that are assigned automatically as well, changing the name is not a required step. Like graphic_10DA92 or whatever it generates when you first place the sprite has the same problem.

**Comment by rwkay** [comment]
This is not a bug as we have never allowed direct naming of the elements on a layer only the instances that are within the room.

This would be a feature request so that elements on layers could be directly referenced using GML id values - currently they can only be referenced through the layer functions and via strings.

**Comment by KormexGit** [comment]
If them not working is not a bug, then I'd argue that them showing up in constant color in the code editor and being recognized by feather is a bug, since that's what made me believe they were actual values that could be used

**Comment by mgeddesGM** [comment]
manual changes have been verified
