### ISSUE TITLE
In-Game: [iOS] Crashes whenever game is closed or loses focus if using an AppDelegate in an extension

### ISSUE THREAD

**Issue by arashmoknat** [YoYoGames/GameMaker-Bugs#6393]
### Description

If an iOS extension uses an App Delegate the app crashes when closed or if sent to the background.

### Expected Change

No crash!

### Steps To Reproduce

1. Run project
2. Press home button
3. Go back into the game
4. Game restarts or is frozen if debugger is attached

[ios_crash.zip](https://github.com/user-attachments/files/15955442/ios_crash.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by arashmoknat** [comment]
Ok, I think I've further narrowed it down to when you're using the same class in both Class Name and App Delegate Class name in the extension. Knowing that I've worked around it by splitting functionality into two classes. But this should either work, or be documented in the manual or prevent you from using the same class name in both fields in the IDE.

**Comment by SamTHodson** [comment]
Verified fixed in Beta IDE v2024.800.0.597  Runtime v2024.800.0.620
