### ISSUE TITLE
Building Projects: [iOS] Xcode "tests" framework can cause video playback projects to not launch, need to run directly from inside Xcode

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#6394]
### Description

_Split off from https://github.com/YoYoGames/GameMaker-Bugs/issues/5455 (issue VII) and using the original sample project - https://api.gamemaker.io/api/github/downloads/9e9a7933-9f79-4871-9453-0169f9c10444_

Xcode "tests" framework can cause video playback projects to not launch, and therefore users need to run the Xcode project directly from inside Xcode manually as a debug run in order to test their game.

### Expected Change

Projects run correctly when Xcode "tests" is in use, looping on iOS is smooth in all cases

### Steps To Reproduce

1. Run the project from the IDE
2. Open A or B
3. Observe that it takes multiple seconds to open the video
4. Observe that the "video_start" event occurs even though playback has not started
5. If playing A, wait for playback to end and observe that looping isn't smooth and there is a substantial delay between loops
Reproduction rate: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Updated the info above.

**Comment by jackerley** [comment]
Good ole Apple have finally got round to fixing this in Xcode 16.0
