### ISSUE TITLE
Invalid comparision state (stringified number with text is equal to real number)

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#6396]
### Description
There seems to be an oddity where having `"-1 Hello world" == -1` will equal to true, even though one is clearly a string and not a number.

### Steps To Reproduce
1. Boot up project.
2. Run game.
3. See debug messages & Script1 for comparision results. (You can find it under ===DEBUG START===, game will autoclose)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5ef32c1f-33e8-4482-87be-4c820a8e34d8](https://api.gamemaker.io/api/github/downloads/5ef32c1f-33e8-4482-87be-4c820a8e34d8)

**Comment by DragoniteSpam** [comment]
this is apparently working as designed but i really wish it wasn't because it makes debugging a pain in the ass
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/6b86a11f-4a25-4545-8bfe-32200bd31cbe)

**Comment by tabularelf** [comment]
Implicit number conversions is fine for itself, but not when there's literally other text.
If we can't `real("100000 Hello world")` into a real, then this shouldn't be true either.

**Comment by DragoniteSpam** [comment]
In general I don't like permission interpretations of == comparisons. The number of times when you actually want it to work like that is dwarfed by the number of times when you do it by accident and spent 6 hours debugging.

**Comment by stuckie** [comment]
This is by design due to legacy support - it'll find the first number and use that.

**Comment by YellowAfterlife** [comment]
> This is by design due to legacy support - it'll find the first number and use that.

Can the definition of "legacy support" be elaborated here? From testing:

- GM8.1 throws "Cannot compare arguments" when trying to compare a number with a string
- GM:S returns `false`, including for a == b when a = 23, b = "23"

Was this part of the GMS 2.2.5 update with much-loved (not really loved) `"23" - 1 ➜ 22`?

**Comment by tabularelf** [comment]
I do agree that a further clarification should be put here. What "legacy" support?

**Comment by rwkay** [comment]
It has been this way since 2.3 - others have built code that work using this... 2.3 is legacy now...

**Comment by JujuAdams** [comment]
What function in the standard library exists to convert a string into a number in a stricter manner?

**Comment by YellowAfterlife** [comment]
> It has been this way since 2.3 - others have built code that work using this... 2.3 is legacy now...

Could it be a checkbox as it's been with "copy on write"? Neither this or `"4" - 1` are documented in the manual [at all](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FExpressions_And_Operators.htm), so I don't think anyone relied on this except on accident (which is arguably a good reason to remove the behaviour).

**Comment by DragoniteSpam** [comment]
if i had to choose between not having to `real()` my inputs explicitly and spending hours tracking down bugs involving strings being treated as numbers erroneously, i think i'd rather choose having to `real()` my inputs explicitly

if changing it breaks any projects, it'll take like five minutes to track down the offending lines and `real()`ing them explicitly
