### ISSUE TITLE
Building Projects: [Android] Unclear compiling error message when trying to compile using a custom texture group format

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6398]
### Description

When attempting to build a project using a custom build format, the build will fail saying that the use of an extension is required along with the project. The message does not clearly specify the extension that need to be used for the build to work correctly. The message given is the following:

`Error : Texture compression failed for group "Default". Make sure the project includes the TextureEncode extension.`

The extension that needs to be used is located here: https://github.com/YoYoGames/GM-GPUTextureCompression

When displaying this warning in the compile errors log it would be expected to have the exact name of the extension or ideally a GitHub link on where to find the extension, to avoid confusion among users.

### Steps To Reproduce

1. Start GameMaker
2. Open a project that has at least one texture group
3. From _Tools>Texture Groups_ go to 'Texture Group Format' under 'Group Settings' select 'Custom' from the dropdown
4. In custom options input a texture to be used (E.g. ASTC)
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.590  Runtime v2024.800.0.614
