### ISSUE TITLE
iOS runner crash with bluetooth controller and home button

### ISSUE THREAD

**Issue by FrancisCoulombe** [YoYoGames/GameMaker-Bugs#6401]
### Description
Game crashes when the home button of a bluetooth controller is pressed after the game was minimized once. It doesnt crash if the game was never minimized first.
The project this was found in was compiled with YYC - this might be YYC-specific?

Here is the report on the xcode output window: 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[EAGLView pressesBegan:event:]: unrecognized selector sent to instance 0x1521c5e00'
 First throw call stack:
(0x18fa7cf20 0x18792e018 0x18fb86480 0x192b582d0 0x18fa19fb4 0x18fa198d0 0x108ede958 0x191f646b8 0x192b5db48 0x191fb56b4 0x191e369e0 0x191e381d4 0x191e40ecc 0x191d3384c 0x191d3176c 0x191d313b0 0x191d32254 0x18fa4f834 0x18fa4f7c8 0x18fa4d298 0x18fa4c484 0x18fa4bcd8 0x1d48fc1a8 0x19208490c 0x1921389d0 0x10934f874 0x1b30fde4c)
libc++abi: terminating due to uncaught exception of type NSException

### Steps To Reproduce
-Connect a bluetooth controller when playing an iOS game.
-Minimize the game
-Return to the game
-Press the "home" button on the bluetooth controller
-Observe the game crashes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[99968480-71d6-4855-b145-5f5ea552aa15](https://api.gamemaker.io/api/github/downloads/99968480-71d6-4855-b145-5f5ea552aa15)

**Comment by YYDan** [comment]
Can see this is reported against the February release - have you already checked if this still happens in the June Betas? 

You haven't said what make/model of gamepad it is - what is it?

There is no project attached either - do you know if a blank new project gives the same result?

**Comment by yoyo-danielc** [comment]
I can't reproduce this using and Xbox Series controller for VM or YYC on IDE v9.9.1.727  Runtime v9.9.1.900
