### ISSUE TITLE
Manual Content: "The Help Menu" page has all the docs for the bug-reporter dialog, not its own "IDE Error Reporting" page

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#6402]
### Description

There is far more info on how to actually use the in-IDE bug-reporter on "The Help Menu" than there is on the bug-reporter's own page of the manual.

Compare the two images below:

https://manual.gamemaker.io/beta/en/#t=IDE_Navigation%2FMenus%2FThe_Help_Menu.htm
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/2bb6241c-b361-4aad-bc3b-b639bf4750ff)

https://manual.gamemaker.io/beta/en/#t=Setting_Up_And_Version_Information%2FError_Reporting.htm
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/38995c7e-71be-4aa2-af0c-76a6ffda7b78)

### Expected Change

All of that good content on The Help Menu is merged in with the stuff on the bug-reporter's own page, and instead The Help Menu just gives a quick one-liner and then a link to the correct manual page. Save having "The Help Menu" document all of its child tools.

### Manual Link

https://manual.gamemaker.io/beta/en/#t=IDE_Navigation%2FMenus%2FThe_Help_Menu.htm

**Comment by gurpreetsinghmatharoo** [comment]
This was because the "IDE Error Reporting" was originally created to only cover IDE crashes and how they are reported. I have now changed that page to cover error reporting in general. It now describes the Report a Bug window and the Help Menu page now links to this page.
