### ISSUE TITLE
Code Editor 2: GM becomes unstable when moving a closing curly bracket with a comment onto a new line

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#6406]
### Description

While verifying [#5364](https://github.com/YoYoGames/GameMaker-Bugs/issues/5364) I noticed that when pasting the code into CE2, backspacing from the closing curly bracket and then pressing enter that GM became unstable and the text lost its colouring.

This doesn't happen after removing the comment, and seems to happen regardless of auto indent being enabled as I've written in #6146.

https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/f8a8dd2b-40d7-438f-ba04-1f7b2f8a4d68

### Steps To Reproduce

1. Start GameMaker and create new project.
2. Enable CE2 and create an object with any event.
3. Add code with an opening and closing curly bracket, and add a comment after the closing curly bracket.
5. Backspace the closing curly bracket onto the line above and then press enter.
6. See the issue.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Could this be rechecked in Red, please?

**Comment by caitlinrmcintyre** [comment]
@stuckie I appear to get the same result using IDE v9.9.1.709  Runtime v9.9.1.882.

**Comment by stuckie** [comment]
Thanks! Assigning on...

**Comment by zreedy** [comment]
Appears fixed

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
