### ISSUE TITLE
Silent crash when changing rooms

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6414]
### Description
Odds are this is caused by a bug in my code, but no error is produced, which means I can't really do anything about it.

Whatever the problem is, it needs to show an error.

### Steps To Reproduce
You can trigger it during "normal" gameplay but the easiest way to do it is
1. Set the config to "debug"
2. Run the game
3. Open the Teleport debug view
4. Go somewhere (rm_demo_level_1 or rm_demo_level_2 does it pretty regularly)
5. The game crashes with no error about 50% of the time

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[0305ad92-eca1-4cf2-b8aa-59c72f23b155](https://api.gamemaker.io/api/github/downloads/0305ad92-eca1-4cf2-b8aa-59c72f23b155)

**Comment by jackerley** [comment]
The enclosed project calls gml_release_mode(true) which switches off error checking on ds_grid accesses, the project is falling over attempting to index into a grid at (-31250,-31250) which will throw an error when not in release mode. I'd recommend switching release mode off and cleaning up any errors before reenabling it.
