### ISSUE TITLE
Manual Content: Various dev/debug async dialog pages state it shouldn't be used in released games, but this should clarify "on desktop OSes"

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#6419]
Various dev/debug async dialog pages state _that function_ shouldn't be used in released games, but this message should clarify we only mean this for desktop and HTML5 games, as it's fine on consoles & mobiles to bring the system UI up to get their own OS dialogs - it's only on desktops that it brings up our runner dialogs.

**Comment by cameron-home** [comment]
This is how these look on various platforms:
Android:
[Android Screenshots-20240723T140853Z-001.zip](https://github.com/user-attachments/files/16350022/Android.Screenshots-20240723T140853Z-001.zip)

iOS:
[iOS Screenshots-20240723T140855Z-001.zip](https://github.com/user-attachments/files/16350051/iOS.Screenshots-20240723T140855Z-001.zip)

PS4, PS5 and Switch all use their in built UI. I could not build attached project to Xbox, so unsure as to if it does. Xbox compiler error:
[6419XboxCompileErrors.txt](https://github.com/user-attachments/files/16350576/6419XboxCompileErrors.txt)

Testing was done using IDE v2024.800.0.595  Runtime v2024.800.0.617

**Comment by jackerley** [comment]
@cameron-home Xbox error should be fixed in 2024.800.0.619 btw

**Comment by cameron-home** [comment]
@jackerley Ah, thanks! I'll take a look on Xbox when that's ready then, and will update here accordingly with results

**Comment by cameron-home** [comment]
@YYBartT What do the notes look like? Just taking a look at the pages now. I've verified the password encryption warning at least.

**Comment by YYBartT** [comment]
@cameron-home The actual note added to all the async function pages looks like this: 

![image](https://github.com/user-attachments/assets/2a5b675d-9307-4e85-85d8-d04c65afc00b)

**Comment by cameron-home** [comment]
The notes are all verified present and correct in latest manual build so marking as Verified.
