### ISSUE TITLE
In-Game: physics_raycast() "all_hits" argument set to true means no collisions are returned in 2024.600 Betas

### ISSUE THREAD

**Issue by gurpreetsinghmatharoo** [YoYoGames/GameMaker-Bugs#6420]
### Description

[physics_raycast.zip](https://github.com/user-attachments/files/16009651/physics_raycast.zip)

In the attached project, if `all_hits` is set to true, only one hit is found.
If it's set to false, then the function doesn't find any collisions.

obj_player Step Line 16.

This is what happens in the game:
![image](https://github.com/YoYoGames/GameMaker/assets/21360237/52161777-ec65-4a28-8a2e-78d3c82ac748)
![image](https://github.com/YoYoGames/GameMaker/assets/21360237/6d935e16-3b42-4508-a2b2-bc101ef9667f)
All three ships should have been destroyed here.

### Expected Change

When all_hits is true, it should return multiple collisions, when false, return one

### Steps To Reproduce

1. Start GameMaker
2. Load project, run game
3. Use laser to shoot multiple ships
4. See only one is destroyed, even when the laser clearly covers multiple ships

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.600.0.584  Runtime v2024.600.0.608

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.600.0.585  Runtime v2024.600.0.609
