### ISSUE TITLE
In-Game: [macOS] Multiple regressions in video playback behaviour since the fixes for 5455

### ISSUE THREAD

**Issue by JujuAdams** [YoYoGames/GameMaker-Bugs#6421]
### Description
Video playback on MacOS has experienced serious regressions since ticket #5455 was closed. We are experiencing failure to load video, crashes, missing async events, and basic functionality being broken. Recommend that a proper sweep is conducted for video playback on this platform as the issues are crippling.

Repro steps below were obtained by running through the repro steps in #5455 and basic use of the test project in #5455 (reattached here for convenience).

### Steps To Reproduce

Test Case A
1. Open either A or B
2. Wait for playback to begin
3. Observe that the "video_start" event occurs
4. Click "Close"
5. Wait for playback to finish
6. Observe that the "video_end" event does not occur
Expected: "video_end" event occurs when playback finishes in any situation, including via video_close()

Test Case B
1. Open any video
2. Wait for playback to begin
3. Without waiting for playback to finish, open another video
4. Observe that video playback ends
Expected: Consistency with other platforms such that
- Playback of the new video is prevented
- "Please close video player before attempting to play a new one" appears in the debug log

Test Case C
1. Open either A or B
2. Wait for playback to begin
3. Without waiting for playback to finish, open the same video
4. Observe that video playback ends
5. Open the same video
6. Observe that the game locks up
Expected: Consistency with other platforms such that
- Calling video_play() twice in a row does not stop playback
- Calling video_play() twice in a row reports the same error message as on other platforms
- Calling video_play() three times in a row does not crash the app

Test Case D
1. Open any video
2. Click "Pause"
3. Observe that video playback is paused as expected
4. Click "Resume"
5. Observe that the video doesn't resume
Expected: Videos can be resumed

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Mac 12.5

[0437ef68-db72-4cee-9c92-53c3d88f9812](https://api.gamemaker.io/api/github/downloads/0437ef68-db72-4cee-9c92-53c3d88f9812)

**Comment by Emc1923** [comment]
Verified fixes as of  IDE v2024.800.0.598  Runtime v2024.800.0.621
