### ISSUE TITLE
Building Projects: [Ubuntu Target] Building targeting Ubuntu does not execute some compiler scripts

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6424]
### Description

When trying to compile a project that contains compiler scripts at the root directory from the Windows IDE targeting Ubuntu not all the scripts will be executed. The ones that won't run are pre_package_step.sh/post_package_step.sh.

[package_scripts.zip](https://github.com/user-attachments/files/16017628/package_scripts.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import the attached project
3. Create executable (appimage or zip)
4. Observe that the name of the scripts are not printed in the log

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10, MacOS Sonoma

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
> [!IMPORTANT]
> Please note that the "compiler scripts" run on the **local machine** (where the IDE runs from) not the target build machine so in this case the `pre_package_step.sh`|`post_package_step.sh` won't run because you are on Windows you need to provide `pre_package_step.bat`|`post_package_step.bat`.

**EDIT:** However we just observed that the scripts (`pre_package_step.bat`|`post_package_step.bat`) might not be running when creating an AppImage and that needs to be fixed though.
