### ISSUE TITLE
In-Game: Custom shaders show various issues with some built-in uniforms related to alpha-testing and fog

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#6425]
### Description

As brought up in the ticket https://github.com/YoYoGames/GameMaker-Bugs/issues/6380 a number of uniforms listed on the [Shader Constants](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/Shader_Constants.htm) manual page currently don't appear to work when accessed inside a custom shader: 
- Uniforms related to alpha testing: `gm_AlphaTestEnabled` and `gm_AlphaRefValue`

- Uniforms related to fog: `gm_VS_FogEnabled`, `gm_PS_FogEnabled`, `gm_FogColour`, `gm_FogStart` and `gm_RcpFogRange`

It appears that they should work, as confirmed with @yymrennie.

Aside from the above, some of the built-in uniforms aren't highlighted in the Shader Editor: `gm_Lights_Direction`, `gm_Lights_PosRange`, `gm_Lights_Colour`, `gm_AmbientColour`.

The built-in constant `MATRIX_MAX` is called `MATRICES_MAX` in the default shader code. The IDE expects `MATRIX_MAX`, the shader compiler expects the `#define` value `MATRICES_MAX`, leading to the shader to not compile, no matter which of the two variables is used.

The following sample project should show all the alpha testing and fog uniforms: [test_builtin_uniforms.zip](https://github.com/user-attachments/files/16018071/test_builtin_uniforms.zip). `gm_AmbientColour` is output in the first test, though none of the other built-in uniforms in the next tests are.

### Expected Change

All shader constants listed on the manual page work when accessed in shaders and are highlighted in the shader editor

### Steps To Reproduce

1. Start GameMaker
2. Import the sample project
3. Run the sample project
4. Press Space to cycle through the tests
5. The ambient colour is applied correctly, all other uniforms don't appear to do anything.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly), 2022.0.2 (LTS), 2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yymrennie** [comment]
Fixed in 2024.8

**Comment by yymrennie** [comment]
Text highlighting in the shader editor now also fixed in 2024.8

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637
