### ISSUE TITLE
Code Editor 2 New line auto indentation bug

### ISSUE THREAD

**Issue by ReeseJones** [YoYoGames/GameMaker-Bugs#6426]
Possibly related: https://github.com/YoYoGames/GameMaker-Bugs/issues/6390

### Description
When making a new line after a set of braces i often get weird auto indent lengths that dont line up with my settings:

my code editor 2 settings:
tab size: 4
show whitespace: true
show indent guide: true
show rainbow brackets: true
auto fill jsdoc header comments: false
auto extend multiline comments on new line: false
auto insert braces: false
allow overwrite: false
auto indent mode: braces
auto indent clipboard contents: false

From my observations it seemse like its making 4 spaces, and then one more for reach level of indentation.

### Steps To Reproduce
open game maker with code editor 2
in the script named scr_ui_layout_flex_vertical
on line 14 place the caret after the else brace
press enter to make a new line
observe that it makes 6 white spaces. 
That is very odd.
![newline_bug_2](https://github.com/YoYoGames/GameMaker-Bugs/assets/6557783/2088fcde-53a0-46b7-b2b1-469b01b45c67)

in another file scr_ui_layout_calculator
on line 19 after the end of the for loop brace place the caret
press enter to make a new line
observe that 5 white spaces are created.

![newline_bug](https://github.com/YoYoGames/GameMaker-Bugs/assets/6557783/9d4ad477-221e-4551-be2e-3e301d0b8856)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[46269b54-6f08-430f-855d-91e41a4b6e5f](https://api.gamemaker.io/api/github/downloads/46269b54-6f08-430f-855d-91e41a4b6e5f)

**Comment by zreedy** [comment]
Fixed. Duplicate.
