### ISSUE TITLE
Code editor 2: Autocomplete issues with struct literals

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6427]
### Description
When typing a struct literal, autocomplete will suggest variable names if you type a number or a comma, and will only suggest function names that start with a or b.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9a7cd5c2-f425-4ae4-91c8-8f94650036ed

### Steps To Reproduce
Type a struct literal, and look at autocomplete when typing out what each member is set to. See video above for examples.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[feedfee5-1e39-4879-a7ce-e0ed0cb52aae](https://api.gamemaker.io/api/github/downloads/feedfee5-1e39-4879-a7ce-e0ed0cb52aae)

**Comment by zreedy** [comment]
Fixed

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1000.0.621  Runtime v2024.1000.0.647
