### ISSUE TITLE
Code editor 2: Typing an opening bracket { in a string adds a whitespace line

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6428]
### Description
If you type "{" it will turn into
```
              "{
         }"
```
Even though it's inside a string and is not code.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/19eaef03-5969-4f6d-af9d-f93682a3dbb7

Also, if it's not intended for it to automatically add the closing bracket at all in a string, then it's worth noting that it also automatically adds a closing parenthesis when you type an opening one.
### Steps To Reproduce
Type "{

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7e8155f5-b7ce-4992-af7f-88dee1fa3282](https://api.gamemaker.io/api/github/downloads/7e8155f5-b7ce-4992-af7f-88dee1fa3282)

**Comment by zreedy** [comment]
Fixed. Also fixed behavior where typing `{` inside of a template string `$""` was not auto-completing the token pair `}`

**Comment by caitlinrmcintyre** [comment]
Verified fixes in IDE v2024.800.0.592  Runtime v2024.800.0.616, thanks.
