### ISSUE TITLE
Code editor 2: Autocomplete appears when writing a multi-line string

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6430]
### Description
Normally autocomplete does not appear when writing a string, but with a multi-line string using @ it can.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/a6f6dfe4-0332-4099-954e-5bfc9fc0a79d

### Steps To Reproduce
```
a = @"
autocomplete will appear on this line
"
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[795c1e4b-f8d7-4d81-bac1-e365c2ef0c0c](https://api.gamemaker.io/api/github/downloads/795c1e4b-f8d7-4d81-bac1-e365c2ef0c0c)

**Comment by KormexGit** [comment]
Autocomplete also appears when typing comments, but I wasn't sure about reporting that since I don't know if it's intended or not

**Comment by zreedy** [comment]
Fixed for comments and strings.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
