### ISSUE TITLE
In-Game: [VM] Attached project silently crashes when catching an exception struct if built with Beta 2024.600

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-Bugs#6431]
### Description
I attached the project.
Interstingly the game runs on YYC. Also works in 2024.4.

### Steps To Reproduce
Run/Build for VM on Beta IDE 2024.600.0.585, Runtime 2024.600.0.609.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[9ddbb63e-7314-45ac-aaaa-715fe57cb521](https://api.gamemaker.io/api/github/downloads/9ddbb63e-7314-45ac-aaaa-715fe57cb521)

**Comment by YYDan** [comment]
Reproduced the issue here, will investigate the cause of the crash.

**Comment by YYDan** [comment]
Okay, this is _probably_ the same as https://github.com/YoYoGames/GameMaker-Bugs/issues/6190, as it's pretty much identical code at fault.

In your project:

// catch a system runtime exception to get its static struct
try {
    show_error("test", false);
} catch(exception) {
    __YYGMLException_static = static_get(exception);
}
