### ISSUE TITLE
Code editor 2: Pressing up/down arrow keys at the top/bottom of an event with "show all documents in single view" disabled changes the event

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6438]
### Description
If you have "show all documents in single view" disabled, pressing the up arrow at the top of an event or down arrow at the bottom of an event will still swap events, as if you did not have the setting disabled.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/6dc70ca0-e970-44d4-ba0b-068b18dce4c4

### Steps To Reproduce
Disable "show all documents in single view" and then use the up and down arrow keys in an object with at least two events

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[49cedabd-3de6-4fc2-a684-785eecf5eb25](https://api.gamemaker.io/api/github/downloads/49cedabd-3de6-4fc2-a684-785eecf5eb25)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
