### ISSUE TITLE
Code Editor 2: Input in Note Asset crash IDE

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#6444]
### Description
I have attached a screen recording, a broken project and a UI log (everything is in the archive).

There is a problem when rendering the source text of a note in the case when something is entered that seems incorrect to the parser or renderer.

### Steps To Reproduce
Environment: Macbook M3.

Open Note as Screen Video. Select first word on 58 line. Press number 7 (broken view).

Place cursor after first word on 58 line. Press number 7 (crash IDE).

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Mac 14.5

[68f88179-a6c0-430b-8d56-eac083d2eb8d](https://api.gamemaker.io/api/github/downloads/68f88179-a6c0-430b-8d56-eac083d2eb8d)

**Comment by YYDan** [comment]
Merged all the info into the original report and now closing as a dupe/redundant.
