### ISSUE TITLE
Code Editor 2: When "show all documents in single view" is disabled, local find and replace still affects other events

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6446]
### Description
If you press ctrl + f to do a search/replace for just the current document, it ignores "show all documents in single view" mode and always searches for and replaces things in every event as if it was enabled.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/3eae1bcd-ff65-44cb-9776-7051af0a6076

### Steps To Reproduce
Search for something present in multiple events with "show all documents in single view" disabled.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[bcada5aa-adec-4387-9276-14ec1ba13483](https://api.gamemaker.io/api/github/downloads/bcada5aa-adec-4387-9276-14ec1ba13483)

**Comment by zreedy** [comment]
Fixed. Additionally an issue where the selected ranges were incorrect when switching between documents has been fixed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.800.0.594  Runtime v2024.800.0.618, thanks.
