### ISSUE TITLE
CE2: Show whitespace something is above the text

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6451]
### Description
see picture, but when this option is activated some text is below the whitespace line.

### Steps To Reproduce
1) see pic
2) Activate show whitespace option in preferences.
3) Se atached project and go to object Game line 131 in the create event

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[115d0de0-76e6-42c5-90e7-6f6183485034](https://api.gamemaker.io/api/github/downloads/115d0de0-76e6-42c5-90e7-6f6183485034)

**Comment by zreedy** [comment]
This has since been fixed.
