### ISSUE TITLE
CE2: String $"{}" will not colour all the following text correctly

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6456]
### Description
like title say watch gif and use project attached.

### Steps To Reproduce
1) Watch Video
2) Open attached project Cueca in line 63

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[5ffcd016-63d7-4b45-9ffe-d8a05a6b8068](https://api.gamemaker.io/api/github/downloads/5ffcd016-63d7-4b45-9ffe-d8a05a6b8068)

**Comment by zreedy** [comment]
Fixed. These tickets share the same underlying issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/6456 https://github.com/YoYoGames/GameMaker-Bugs/issues/8112 https://github.com/YoYoGames/GameMaker-Bugs/issues/8111

The char offset was converted to a byte offset in the UTF-8 when passed to the Regex library, but was not converted from byte offset to char offset when returned to the TextMate Grammar Tokenizer which caused the tokenizer to incorrectly parse the string by skipping characters.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
