### ISSUE TITLE
Redefine Keys: [Mac IDE] "Duplicate line" hotkey for Code Editor 2 is incorrectly hardcoded as Ctrl+D and not customisable

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#6458]
### Description

In IDE v2024.600.0.585  Runtime v2024.600.0.609, the Text Editor 2 "Duplicate" hotkey has no mac remap. This should instead be `Command + D`.

### Steps To Reproduce

1. Start GameMaker
2. Open Redefine Keys and find the Text Editor 2 "Duplicate" hotkey
4. Observe it is bound to `Ctrl + D`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Currently we have two "Duplicate" hotkeys - a Global one, and a Code Editor 2 one.
The global hotkey should likely not be global, but instead have a list of the (many) locations it is used. Code Editor 2 can then be added to this list.
This would:
1. Make it clearer to users where the Duplicate hotkey can be used
2. Allow for binding other hotkeys to Ctrl/Command + D in locations that _don't_ use the duplicate hotkey
3. Mean we have a single Duplicate hotkey, avoiding issues like this

**Comment by SmithTom6304** [comment]
`Duplicate` hotkey has now been split into multiple location entries (rather than just "Global"), including "Text Editor 2". CE2 no longer has it's own hotkey specified, so will now default to `Command + C` on mac and is remappable.
Locations specified by `Duplicate` are:

"Sequence Editor",
      "Image Editor",
      "Text Editor",
      "Anim Curve Editor",
      "Asset Browser",
      "Object Editor",
      "Particle System Editor",
      "Room Editor",
      "Time Line Editor",
      "Text Editor 2"

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.624  Runtime v2024.1100.0.650.
