### ISSUE TITLE
Manual Content: GLSL ES reference link on Shader Constants page not found

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6460]
### Description

On the Shader Constants/Shader Uniforms page, the OpenGL ES Shading Language (GLSL ES) "Reference Pages" link in the first sentence takes you to a 404 not found page (https://registry.khronos.org/OpenGL/specs/2.0/GLSL_ES_Specification_1.0.17.pdf).

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/ce758707-9dbc-4b53-979a-7f428adad2bf)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/547659f5-0f8e-4bbb-995f-f00533a236d3)

I presume this should link to https://registry.khronos.org/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf , which is linked in the main Shaders page (https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/Shaders.htm) as the main reference to use for the language.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/Shader_Constants.htm

**Comment by YYBartT** [comment]
Changed the link to the correct one. The change will go in the next manual release.
