### ISSUE TITLE
Manual Content: Page for shaders_are_supported function contains no information on which target platforms are supported by shaders

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6461]
### Description

The manual page for the shaders_are_supported function states that it will "do a check to see if the chosen target platform supports shaders" but contains no information on which target platforms are expected to support them. Without this information, the specifics of its expected functionality are unclear, making it hard to determine whether it is working correctly or not.

To solve this, the page should include a reference table containing all targetable platforms and whether or not they support shaders, to indicate when the function is intended to return true and when it is intended to return false.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/shaders_are_supported.htm

**Comment by stuckie** [comment]
HTML5 *Canvas* and very old Android devices would be the only cases where shaders would not work.
