### ISSUE TITLE
In-Game: [Windows] comparing the index of audio groups / audio asset give different results on VM and YYC

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#6462]
### Description

The attached project gets the audio group of a sound, and compares it to the audio group asset. Then it gets the assets from an audio group (which only has one asset), and compares the first one in the array to the audio asset that it should be. Both comparisons will pass on VM, but on YYC both will fail.

[project.zip](https://github.com/user-attachments/files/16053527/Contact.us.zip)

### Expected Change

The comparisons should pass on YYC as well

### Steps To Reproduce

1. Start GameMaker
2. Run the game on VM
3. See output (it should say the audio groups / audio assets match)
4. Run the game on YYC
5. See output (it should say the audio groups / audio assets do NOT match)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.8 - it has been merged into the new GMS2-Runner-Main repo that is not fully integrated yet... so until that is done then this may be in limbo.

**Comment by cameron-home** [comment]
@rwkay Can you let me know please when this repo is fully integrated, and this bug is fully ready to test?

**Comment by rwkay** [comment]
I think it is already check with @ksuchitra532

**Comment by cameron-home** [comment]
Repo appears to be fully integrated, as I have been able to verify the issue fixed using Adam's attached project in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617.
