### ISSUE TITLE
Nothing will compile

### ISSUE THREAD

**Issue by MaxfieldHutton** [YoYoGames/GameMaker-Bugs#6463]
### Description
After updating from runtime 2024.4.1.168 to 2024.4.1.202 I cant run any of my games. I've tried letting things through the firewall, disabling windwosd defender entirely, different projects but the only thing that fixes it is going back to 168. I tried everything for 201 as well.

I never get anything in the output log. it just says building

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.0.137 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[08a4cd47-58fb-4386-8cc4-397571f4dce6](https://api.gamemaker.io/api/github/downloads/08a4cd47-58fb-4386-8cc4-397571f4dce6)

**Comment by YYDan** [comment]
Yes, you will need to update your IDE install to 2024.4.1 also, as the code-signing information on the .4.1 runtimes is different.

We did sort of mention this on https://releases.gamemaker.io/release-notes/2024/4 - but I think I should go make the wording clearer now ;)

**Comment by YYDan** [comment]
Done (and published already):

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/32943f53-9662-4d46-874c-a845c57400a2)

The rest of it was there already, but I just added that info box on the top line.

**Comment by L-Clouds** [comment]
Yet another example demonstrating why #5803 would help.
