### ISSUE TITLE
CE2: Object Editor diagnostics do not appear on macOS

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#6464]
### Description

In Beta IDE v2024.600.0.585 Beta Runtime v2024.600.0.609, diagnostics (ie. warnings and errors) do not appear correctly in the new code editor. See the following screenshots:

<img width="618" alt="Screenshot 2024-07-01 at 16 24 07" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/7bb787cc-d7bd-4b1a-9b5b-90f9642b661f">

Beta IDE v2024.600.0.585 Beta Runtime v2024.600.0.609

<br>

<img width="618" alt="Screenshot 2024-07-01 at 16 21 18" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/87641114/113eeab0-07ba-48c6-ba5a-a6c08ab848a4">

Expected behaviour

### Steps To Reproduce

1. Start GameMaker
2. Open an Object Editor event script in the new Code Editor
3. Add a reference to an unknown function
4. See that no diagnostic is created

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.594  Runtime v2024.800.0.618
