### ISSUE TITLE
Code Editor: gpu_get_stencil_enable() has a typo "retreive" in its GMLSpec info

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#6465]
### Description
As you can see from the screenshot below, gpu_get_stencil_enable() has a typo "retreive" in its GMLSpec info:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/1f148a61-fcba-4372-bc16-24d510da2733)

### Expected Change

The spelling is "retrieve" (i before e...), as we use for all the other new functions in this feature,

### Steps To Reproduce
1. Start GM and create a new project using 2024.600 Betas
2. Add a code event/script and type in the function name
3. Hover your mouse cursor over the function name to see its description
4. Observe the typo

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.156 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[3608159b-369c-4c7e-9227-a63c914ab95f](https://api.gamemaker.io/api/github/downloads/3608159b-369c-4c7e-9227-a63c914ab95f)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.588  Runtime v2024.800.0.612
