### ISSUE TITLE
Building Projects: More than 16 named arguments for a function will cause a build fail

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#6473]
### Description
If you have a function with more than 16 named arguments, GameMaker will refuse to compile outright. Giving "only 16 named arguments supported in a function declaration"

### Steps To Reproduce
1. Run project.
2. See compile errors window

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.579 Runtime v2024.600.0.605

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[e2feaafa-0191-4e60-8c6d-b9cf9538dc59](https://api.gamemaker.io/api/github/downloads/e2feaafa-0191-4e60-8c6d-b9cf9538dc59)

**Comment by tabularelf** [comment]
In a fail attempt to cleaning up the project, I accidentally made it under 16 arguments (Also had an error).
I've corrected it and reuploaded the project. Please use this one instead.
<img width="902" alt="GameMaker-Beta_2024-07-03_00-17-02" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/26135221/e0b71a83-4df7-4721-8d74-0063dabdb4b6">

[argument test.zip](https://github.com/user-attachments/files/16069797/argument.test.zip)

**Comment by GameDevTosh** [comment]
Commenting cause Russell said this could be an easy thing to change, as its probably an artificial compiler limit.

**Comment by mgeddesGM** [comment]
verified as of IDE v2024.800.0.595  Runtime v2024.800.0.619
