### ISSUE TITLE
Manual Content: gm_Lights_Colour[] on Shader Constants manual page is missing "[]"

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6474]
### Description

On the Shader Constants/Shader Uniforms page, there's a small typo within the 3rd table down on the page, that lists pre-defined matrix uniforms and constants for accessing GameMaker specific values - The entry `gm_Lights_Colour` should have "`[]`" at the end of it to indicate that it is an array, like the two constants above it in the table:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/cc1e5da9-f2a8-4b4a-b42f-ddd69a5e9b8a)

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/Shader_Constants.htm

**Comment by YYBartT** [comment]
Fixed as part of https://github.com/YoYoGames/GameMaker-Bugs/issues/6380.
