### ISSUE TITLE
Autocomplete for `function` keyword could include `()`

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6477]
### Is your feature request related to a problem?

Both uses of `function` (declaring a method or user script) necessitate the use of parentheses, either directly after the keyword (`function()`) or after the script name (`function userscript()`). However, typing them yourself isn't as efficient or pleasant as simply having them autocompleted.

Autocomplete for user scripts or built-in functions WILL include parentheses, and even place the text cursor between them - this is a really handy feature, since it not only saves the need to type out both, but positions your cursor for you so that you can immediately include arguments, reducing the amount of keypresses and the need to stretch to different parts of the keyboard.

### Describe the solution you'd like

Either changing the `function` autocomplete to `function()` or having separate dropdown options for the two would generally improve the process of declaring functions while typing out code.

**Comment by stuckie** [comment]
Code Editor 2 should already support this.
