### ISSUE TITLE
Code editor 2: Issues with automatically creating functions for moments and swapping between CE1 and CE2

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6479]
### Description
If you create a sequence and automatically create some functions for moments using CE1, and then swap to CE2 and do the same, all newly created functions will no longer work for moments. These functions will continue to not work even after you swap back to CE1.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9ce52374-e240-4438-866c-275a68abf76e

It still not working after turning CE1 back on:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/0fca0fef-b810-4220-a3e2-1316399eedc5

Closing the sequence and reopening it will not fix it, but reloading the project or restarting GM will.

### Steps To Reproduce
Create a sequence. With CE1, active, add a moment and create a new function for it with the + button. Swap to CE2. Add another moment and press the + button. This moment will show up red. Create a new function in a script. Try to add this function to a moment. It will show up red and not add. Swap back to CE1 and try to add that same function to a moment. It still won't add.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0c2802ae-d2d3-47de-bca3-e5cb69cf7b73](https://api.gamemaker.io/api/github/downloads/0c2802ae-d2d3-47de-bca3-e5cb69cf7b73)

**Comment by zreedy** [comment]
In-Editor Background GML Services are disabled in CE2 which drive these textboxes.

**Comment by stuckie** [comment]
Marking as resolved as part of https://github.com/YoYoGames/YoYoStudio/issues/10272 as we block switching between CE1 and CE2 without a restart.

**Comment by Emc1923** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/issues/7011 has had no effect on reproducing this issue - toggling code editor is not required to reproduce.
