### ISSUE TITLE
Code editor 2: When typing function arguments, description of the last autocomplete suggestion will stay on screen even after autocomplete menu changes to "no suggestions"

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6488]
### Description
If you type something as an argument name that results in no suggestions, the description of the last suggestion shown will stay on screen.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/3d82599b-cb7e-44c3-94b5-a99bfbc80aa0

### Steps To Reproduce
Type any function, and then type gibberish as an argument to make it show "no suggestions"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[92ed755b-1c0b-4c68-b058-1b9a1a6b7a2b](https://api.gamemaker.io/api/github/downloads/92ed755b-1c0b-4c68-b058-1b9a1a6b7a2b)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617, thanks.
