### ISSUE TITLE
ExitAllEvents statement

### ISSUE THREAD

**Issue by d-bacon** [YoYoGames/GameMaker-Bugs#6489]
### Is your feature request related to a problem?

The current statement Exit works great for events, however it'd be good to exit all subsequent events from execution.

### Describe the solution you'd like

What would be good if it's possible to use a new statement: ExitAllEvents.
This would then cause subsequent events not to execute from the given parent or child event it is set at.
I guess another idea would be the event_inherited() returning a status if it had been prematurely exited or perhaps others like skip next, e.g. a parent hitting a piece of code that actually skips the next child SkipNext? but continues after that?

### Describe alternatives you've considered

Once you add multiple parent-child relationships you then need to flag the initial event in some way and exit and then to act on subsequent child events in a similar manner to exit also.  This adds to a bit of extra code and ensuring it's covered in all events which could of course be part of a function at the start of each event instead to set various states via enum e.g. event_parent_check(), it's just some cases I just want to exit everything without the extra code to check.
I've also looked at changing the object to e.g. a dead object passing variables over if needed to respawn for instance, which is ok, but in some cases I just need it to last a short while as the current object to avoid the need to change object.
I've not considered or tried yet but perhaps exceptions possibly to throw at parent then try/catch the event_inherited at the final child too?

**Comment by ParodyKnaveBob** [comment]
Alternative idea: PHP allows an optional numerical argument after `break` to tell how many layers to break out of. OP would likely appreciate having GML allow that with `exit` (not to mention `break` heheh).

```gml
exit; // default
exit 3; // exits three layers on the stack -- functions, events, etc.
exit infinity; // my suggestion for how to say "exit all" without creating a new keyword nor overloading "all" in a confusing manner
```
