### ISSUE TITLE
In-Game: Internal Beta runtime 2024.800.0.610 has a silent crash on game start

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#6491]
### Description

Our project is experiencing silent crashes on boot for Windows, iOS, and Android YYC exports with runtime 2024.800.0.610 but not the June beta runtimes.

### Steps To Reproduce

1. Clone the project at https://github.com/bscotch/ganary
2. Build for Windows, Android, or iOS YYC export with runtime 2024.800.0.610
4. Run the executable and see the issue

Windows build log: https://github.com/bscotch/ganary/actions/runs/9768853639/job/26967171381#step:11:1
Windows runtime log: https://github.com/bscotch/ganary/actions/runs/9768853639/job/26967171381#step:14:78

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, Android, iOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by shichen85** [comment]
I am cross-checking against [GM-TestFramework](https://github.com/YoYoGames/GM-TestFramework), it seems that it has a run for runtime 9.9.1.884 which build successfully but failed to lunch the exe: 
https://github.com/YoYoGames/GM-TestFramework/actions/runs/9763707627/job/26950221696

The GitHub Action run is marked as successful, but the run duration is 3m 55s, whereas the previous runs usually take 11+minutes.

**Comment by YYDan** [comment]
That's not a build that I would recommend you should be using just now - it was a test build for us yesterday. (You probably do not want to watch our internal Betas...)

**Comment by stuckie** [comment]
Closing as above.

As a general observation, please don't rely on internal feeds as they are not ready for public consumption.

**Comment by shichen85** [comment]
Hello @YYDan @stuckie, 

Thanks for the reply, and my apologies if this issue is more noise than useful signal.

We have been watching the `Zeus-Runtime-NuBeta-I` in the hope of giving timely feedback. For example, a few issues that I opened are from the `Zeus-Runtime-NuBeta-I` feed:

2024.600.0.603: https://github.com/YoYoGames/GameMaker-Bugs/issues/6333
2024.600.0.600: https://github.com/YoYoGames/GameMaker-Bugs/issues/6247

Would you prefer these kinds of issues to be submitted as soon as they are discovered in the `Zeus-Runtime-NuBeta-I` feed, or would you prefer us to wait until these issues are discovered in the public beta feed `Zeus-Runtime-NuBeta`?

**Comment by stuckie** [comment]
The message was more for those watching on who may have found access to the internal feeds, and are wanting to submit general bugs against them. ( So, I've removed the feed names from your message so as not to get an over abundance of well meaning people using them, and submitting issues before we are ready for them. )

For the most part, they are what they are - internal builds to test things. However, it can be useful to have external developers such as yourselves to check them for specific things at times, before they do go out in a general release, so we do appreciate you doing so.

This just happened to be the first one for the next milestone to see where we were at, and to gauge what needs to be done for the next public release.
