### ISSUE TITLE
Middle clicking "with" will take you to the front page of the docs instead of the page for with

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6492]
### Description
If you middle click on `with` in code, it doesn't take you to the page for with properly. I checked and other statement keywords appear to work fine, just not with.

### Steps To Reproduce
Middle click with, or press F1 on it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[005350fc-12ef-4e8b-b1ba-ec29e2faaad2](https://api.gamemaker.io/api/github/downloads/005350fc-12ef-4e8b-b1ba-ec29e2faaad2)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
