### ISSUE TITLE
Korean characters are not being entered throughout the IDE.

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#6495]
### Description
Text does not advance to the next after entering Korean characters.
To move on, need to press the spacebar and backspace.

### Steps To Reproduce
As explained above.
and it's easier to understand if you watch the video.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[84ed788f-d5ed-4021-b619-42bbe1735454](https://api.gamemaker.io/api/github/downloads/84ed788f-d5ed-4021-b619-42bbe1735454)

**Comment by YYDan** [comment]
Sorry, they _just_ beat you to it! ;)
