### ISSUE TITLE
Manual Content: Page for draw_light_get function has slight inaccuracy in description of returned values

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6503]
### Description

On the manual page for the draw_light_get function, it lists the [2], [3] and [4] elements of the returned array as containing the x position, y position, and z position of the light. This is true when using it to get the parameters of a point light, but if the light is directional, the [2], [3] and [4] elements actually contain the direction the light is facing, rather than the position.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/ceec8961-9a68-42ac-b2a6-5295a9ac7fe3)

Changing them to something along the lines of "[2] = x position (x direction for directional lights)", "[3] = y position (y direction for directional lights)", "[4] = z position (z direction for directional lights)" would fix this.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/Lighting/draw_light_get.htm

**Comment by stuckie** [comment]
Should just say "value" rather than "position"

**Comment by YYBartT** [comment]
Changed to "value" and added a note to make the difference clear. Also updated all pages related to lighting.
