### ISSUE TITLE
buffer_save_async remove the "default" or explaing better when it is added.

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#6505]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please, it would be awesome to remove the "default" path from the buffer_save_async function, or at least make clear in the documentation where will it be added.
For example, if I disable the system sandbox and use this function, providing the path "program_directory", would my final path be "default\ + program_directory"?

If this is the case, it doesn't make any sense to have it like this...
Maybe an optional argument can be added with a default value of true.
If true it keeps the "default", if false, it doesn't add the "default".

**Comment by Grisgram** [comment]
I was tinkering with async save/load in the last view days too and stumbled across the very same manual page.

However, at least in "load_async" there is no "default" attached to any path, i can load straight paths as I write them.

But all in all I can see no sense and no benefit in adding a hardcoded word like "default" to any path, anywhere at any time. Maybe this has historical reasons and comes from a time long gone.
I totally agree, remove this "default" from save/load async please. Even more so, as in HTML you don't add it. why in other platforms?

**Comment by mgeddesGM** [comment]
changes have been verified
