### ISSUE TITLE
In-Game: nameof() no longer works with enums and macros in 2024.6

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#6506]
### Description
In 2024.4 and beta 2024.6, nameof() worked with both to return the names as strings. Now in 2024.6 monthly, neither seems to work. Several people were told we could use nameof() this way despite the manual saying it can't, which is why I'm reporting it as a bug, considering it still works in beta versions.

![bugged nameof](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/6ef4470f-cd8f-4896-a258-70157d2353a8)

### Steps To Reproduce
1) Create an enum 
2) Try to show_debug_message an enum member with nameof()
3) It will now return the digit the enum represents as a string rather than the enum member name as a string.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[09c2aa55-56d6-468d-a6e5-2f4c5da8ad45](https://api.gamemaker.io/api/github/downloads/09c2aa55-56d6-468d-a6e5-2f4c5da8ad45)

**Comment by gnysek** [comment]
Added pull request for tests for this issue.

**Comment by rwkay** [comment]
Here is the project I was using to test with
[Bug-6506.zip](https://github.com/user-attachments/files/16087930/Bug-6506.zip)

**Comment by rwkay** [comment]
Fixed in 2024.8 - going to discuss 2024.6.1 tomorrow with QA

**Comment by YYDan** [comment]
Reopening, as in IDE v2024.6.1.159  Runtime v2024.6.1.207 I am only getting the first character of each expected answer:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/1ebecf2a-bdd5-4779-897f-4316658df53a)

**Comment by YYDan** [comment]
@gnysek Not sure what mixing up the IDE with the runtime would achieve there, btw, as this is a runtimes issue. We would also certainly never suggest mixing monthly and beta IDEs/runtimes ;)

**Comment by rwkay** [comment]
Fixed in 2024.6.1 - code was not cherry picked over properly

**Comment by YYBartT** [comment]
Updated the manual page of `nameof()`, removing the note since it was outdated and no longer correct.

**Comment by YYDan** [comment]
Working correctly now in IDE v2024.6.1.160  Runtime v2024.6.1.208:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/c28f41c1-6283-4c81-b25c-808530e5a9ac)

Verifying.
