### ISSUE TITLE
Code Editor: draw_light_get()'s GMLSpec info is incomplete and described return type is incorrect

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6508]
### Description

As you can see from the screenshot below, draw_light_get() gets cut off before explaining the elements of the array it returns, and incorrectly states it will return a Real value, when it returns an Array:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/59960214/da7bdf67-fc70-40ff-9987-f015efe1b04e)

[draw_light_get issue.zip](https://github.com/user-attachments/files/16087387/draw_light_get.issue.zip)

### Expected Change

Add the remaining information from the manual relating to the returned array to the GMLSpec info, and correct the return type.

### Steps To Reproduce

1. Start GM and create a new project using 2024.6.0 or 2024.600 Betas
2. Add a code event/script and type in the function name
3. Hover your mouse cursor over the function name to see its description
4. Observe the incomplete description and incorrect return type

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly), 2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
