### ISSUE TITLE
In-Game: Lighting-related built-in uniforms don't work correctly inside custom shaders

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6509]
### Description

as mentioned in https://github.com/YoYoGames/GameMaker-Bugs/issues/6425 a number of uniforms listed on the [Shader Constants](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Shaders/Shader_Constants.htm) manual page currently don't appear to work when accessed inside a custom shader. The `gm_Lights_Direction`, `gm_Lights_PosRange`, `gm_Lights_Colour`, and `gm_AmbientColour` uniforms, aside from having incorrect syntax highlighting as indicated in that issue, also seem to have some incorrect functionality:

 - **gm_Lights_Direction[]** - Each vec4's w value seems to be always be 1, regardless of if the light has been enabled or disabled, despite the manual saying it should be 1 when the light is enabled, and 0 when disabled.
 
  - **gm_Lights_PosRange[]** - Each vec4's w value seems to always contain the light's range, regardless of if the light is enabled or disabled, despite the manual saying it should be 0 when disabled.
 
  - **gm_Lights_Colour[]** - Doesn't seem to work at all, with every vec4 in the array having a value of (0, 0, 0, 0) regardless of what colours the lights have been set to.
  
  - **gm_AmbientColour** - Works correctly, however, the alpha value will always be 0 unless `draw_light_define_ambient()` is provided with a colour in $AABBGGRR format, despite the built-in lighting system not using alpha values for ambient light. Unsure whether this is unintended or undocumented behaviour.
  
Here's an in-development version of the xUnit test framework which includes tests for these uniforms in the BasicShaderTestSuite:
[xUnit Shader Tests.zip](https://github.com/user-attachments/files/16087608/xUnit.Shader.Tests.zip)

### Expected Change

 - The .w values of vec4s in the `gm_Lights_Direction[]` uniform should be 1 when the corresponding light is enabled, and 0 when disabled. 
 - The .w values of vec4s in the `gm_Lights_PosRange[]` uniform should be 0 when disabled. 
 - The `gm_Lights_Colour[]` uniform should contain the colours of all defined lights. 
 - And for `gm_AmbientColour`, it would be more intuative for the alpha value to be 1 when `draw_light_define_ambient()` is provided with a colour in $BBGGRR format, or at least the manual should document the behaviour of the alpha being 0 unless with $BBGGRR values.

### Steps To Reproduce

1. Start GameMaker
2. Run the included version of xUnit: [xUnit Shader Tests.zip](https://github.com/user-attachments/files/16087608/xUnit.Shader.Tests.zip)
3. Check the Output after running to see the tests for gm_lights_direction, gm_pos_range, and gm_lights_colour failing
3. Open Users\(user)\AppData\Local\GameMakerStudio2\GMS2TEMP\xUnit_(numbers)\ShaderTests for the visual test outputs
4. Open the LightsDirection, LightsPosRange and LightsColour folders in that directory and observe the difference between the expected and resultant values for the tests to see the issues. _(note that there is an additional bug causing LightsDirection to fail, mentioned in #6507, causing the direction of the light to be inverted)_

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly), 2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Indibulous** [comment]
Just thought i should add, I initially only tested this in the GLSL/GLSLES shader language, which produces the behaviour described, but after testing in HLSL, found that the mentioned uniforms - as well as the `MATRICIES_MAX` constant, which similarly lacks syntax highlighting - instead just throw an error upon using `shader_set()` with the shader containing them:

![image](https://github.com/user-attachments/assets/8629361e-2100-4843-ab6b-51206bf9649e)

Worth noting that https://github.com/YoYoGames/GameMaker-Bugs/issues/5944 describes a very similar behaviour, but specifically on ubuntu targets.

Wasn't sure if it warranted it's own issue, since it seems like it likely stems from the same origins, but here's a small test project and output log for it:

[HLSL light uniforms issue.zip](https://github.com/user-attachments/files/16346094/HLSL.light.uniforms.issue.zip)

[output log.txt](https://github.com/user-attachments/files/16346095/output.log.txt)

**Comment by yymrennie** [comment]
Most of the suggested changes have now been made in 2024.11:
- the gm_Lights_Direction and gm_Lights_PosRange uniforms now have 0 in their w component when the light is disabled.
- the gm_Lights_Colour uniforms are now not cleared to 0 when their respective light is disabled.

However the gm_AmbientColour uniform has been kept as-is for the moment as some users might be making use of the alpha component if they're using custom lighting code.

**Comment by YYBartT** [comment]
Documented the changes that weren't in the manual yet.

**Comment by scott-dunbar** [comment]
I am reopening this based on the current runs of Testframework failing on these uniforms

https://github.com/YoYoGames/GameMaker-Bugs/issues/8238
https://github.com/YoYoGames/GameMaker-Bugs/issues/8235
https://github.com/YoYoGames/GameMaker-Bugs/issues/8237
https://github.com/YoYoGames/GameMaker-Bugs/issues/8236

I do not know enough about these changes to know if its related to the failure states listed but the tests should be reviewed with the changes from this issue to ensure that the tests are accurate and up to date with these changes

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11775071810 - tetframework ran out of November branch.

**Comment by stuckie** [comment]
Closing since test issues have separate tickets, as they may not necessarily be because of these changes.

**Comment by sihammill** [comment]
Tests are still failing on the Test Framework in the latest Beta builds but as mentioned above, each of the fails have been written up and assigned to the next milestone 2025.1
