### ISSUE TITLE
Unable to detect collision when "precise collision checking" is set on sprite with multiple frames

### ISSUE THREAD

**Issue by cla8194** [YoYoGames/GameMaker-Bugs#6510]
### Description

Game Maker (latest version, IDE v2024.6.0.157 Runtime v2024.6.0.205) won't detect collisions on object with a multi-framed sprite and collision mask "precise per frame" selected:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/3fb8fefc-646e-4db0-ae55-e977b2db022f)

### Expected Change

Collision should always be detected if a sprite is masked correctly

### Steps To Reproduce

1. Start GameMaker and open the attached project
2. Run the game and hover the mouse on the light green border, see the object detection (works)
3. Hover the mouse on the teal colored borders, note that the collision detection is not working
4. In editor you can open the sprite folder and check the sprite, every frame is collision-masked properly

[collision_mask bug.zip](https://github.com/user-attachments/files/16088681/collision_mask.bug.zip)
(bug is probably present on every platform)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, PlayStation 4, PlayStation 5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Finalconsole** [comment]
Same problem here, this is causing big collision problem here.

**Comment by YYDan** [comment]
Already fixed by the pinned known issue https://github.com/YoYoGames/GameMaker-Bugs/issues/6485 in our internal runtime:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/ddb61891-d716-4686-bf8b-11196571d1f3)
