### ISSUE TITLE
Code Editor 2: Underline and BG Color options do not work in Theme Editor

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#6512]
### Description

The Theme Editor exposes the ability to have symbols underlined, and also a background color. These features do not reflect in the Code Editor nor do they reflect in the Theme Editor. Additionally, bold, and italic flags do not render in the Theme Editor's preview.

### Steps To Reproduce

1. Start GameMaker
2. Open Preferences -> Code Editor 2 -> Theme
3. Click on the bold, italic, underline checkboxes, or change the bg color
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. This issue was discovered while working on https://github.com/YoYoGames/GameMaker-Bugs/issues/6267 but no existing ticket seemed filed.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.800.0.593  Runtime v2024.800.0.617, thanks.
