### ISSUE TITLE
`script_execute_ext` crash in .800 beta

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6521]
### Description
In internal 2024.800.0.610 runtime `script_execute_ext()` seems to be crashing, with message:

`camera_create_view() - must have at least 4 arguments`, so it's like instead of executing script/function passed in first arg, it executes some built-in function

_(I know this is from internal beta, but I'm reporting it in advance, to prevent first beta from releasing with such issue)_

### Steps To Reproduce
1. create custom function
2. Call `script_execute_ext(<function name here>, [0]);`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.586 Runtime v2024.800.0.610

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[588393c2-b709-4c52-be2a-e42f4280efde](https://api.gamemaker.io/api/github/downloads/588393c2-b709-4c52-be2a-e42f4280efde)

**Comment by rwkay** [comment]
Fixed in 2024.8
