### ISSUE TITLE
Global permission to use `draw_flush` with `gpu_get/set_scissor` without asking GameMaker Support staff each time.

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6523]
### Is your feature request related to a problem?

Manual page for [draw_flush](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/draw_flush.htm) says:

> This is a debug-only function and in general it should not be used **unless indicated by a member of the GameMaker Support staff**, as indiscriminate use will cause serious performance issues with your game.

However, since introduction of `gpu_get_scissors` and `gpu_set_scissors` in 2024.8, this function is required to make it work, like in below example:

```gml
    var _s = gpu_get_scissor();
    gpu_set_scissor(50, 50, 50, 50);
    
        draw_sprite(spr_0, 0, 0,0);
        draw_flush(); // <-- it's here
        
    gpu_set_scissor(_s);
```
    
Purpose of this feature request is that we don't need to ask GameMaker Support staff every time we want to use `draw_flush()` with `gpu_get/set_scissor`, as that could overfill helpdesk with requests.

### Describe the solution you'd like

Allowing to use `draw_flush()` without being indicated by GameMaker Support staff seems sufficient.

### Additional context

Description in manual was so funny, that I couldn't resist making equally serious Feature Request. Don't take this too serious, but some rewording by manual team might be a good idea ;)

**Comment by YYDan** [comment]
Lol, yeah....... A funny one to discuss tomorrow ;)

**Comment by rwkay** [comment]
Fixed in 2024.8 - `gpu_set_scissor` now implicitly calls `draw_flush` - so you do not need to anymore.

We should leave the documentation as it is.

**Comment by DragoniteSpam** [comment]
> ### Additional context
> Description in manual was so funny, that I couldn't resist making equally serious Feature Request. Don't take this too serious, but some rewording by manual team might be a good idea ;)

the exact wording is "indiscriminate use will cause serious performance issues with your game" and it would probably be a good idea to specify that all it does is end the current batch instead of, for example, flushing all of the textures from memory like `texture_flush` on steroids, which is what i assumed it did

**Comment by YYDan** [comment]
@gurpreetsinghmatharoo I've put this one back for review of the manual content in relation to the above comment. Let us know if you're changing this or not.

**Comment by sihammill** [comment]
Verified in Beta IDE v2024.800.0.597 Beta Runtime v2024.800.0.620
