### ISSUE TITLE
(steamworks sdk) Issues with "steam_ugc_request_item_details()" page

### ISSUE THREAD

**Issue by FollowTheFun** [YoYoGames/GameMaker-Bugs#6527]
### Description

When calling steam_ugc_request_item_details(), the async_load returns lots of stats about an item as shown [here](https://docs.gamebar.me/gmsDocs/source/_build/3_scripting/4_gml_reference/steam%20api/user%20generated%20content/steam_ugc_request_item_details.html).

One of those things is "tags_truncated", which the game maker manual incorrectly states that it contains a "Short version of the tags as an array".

But as you can see in the steamworks docs [here](https://partner.steamgames.com/doc/api/ISteamUGC#SteamUGCDetails_t), (_m_bTagsTruncated_) it actually returns a boolean, as to whether the tags have been truncated or not. 

It should say: "Returns whether the tag list has been truncated in 'tags'"

The game maker manual description for "tags" is wrong also:
It says: "tags" - An array of the tags for the item

But actually it returns a comma separated list (string). 

Finally, about 10% of this page appears to be in Chinese. 

### Manual Link

https://docs.gamebar.me/gmsDocs/source/_build/3_scripting/4_gml_reference/steam%20api/user%20generated%20content/steam_ugc_request_item_details.html

**Comment by FollowTheFun** [comment]
Also "url" claims to be a full URL for the item but it's always empty.

Upon further investigation, this field actually returns the "associated website / youtube link" that a user can link to the workshop item. 

If you need the URL to the workshop item, you can use:
"https://steamcommunity.com/sharedfiles/filedetails/?id=" + published_file_id

**Comment by DiasFranciscoA** [comment]
Hey @FollowTheFun, thank you for reaching out what manual are you using for the extension?
The official documentation is here: [Steamworks Wiki](https://github.com/YoYoGames/GMEXT-Steamworks/wiki) or in the manual included with the extension (datafiles).

Regarding your points we will be updating the `steam_ugc_request_item_details` documentation to match the behavior.

**Comment by FollowTheFun** [comment]
Ah sorry, I didn’t realise that wasn’t the official manual. Not sure where the “Gamebar” one I linked came from.

Though it seems that the issues I mentioned are present in the official one too (except for the Chinese characters).

**Comment by YYBartT** [comment]
The comma-separated list (string) returned in the [SteamUGCDetails_t](https://partner.steamgames.com/doc/api/ISteamUGC#SteamUGCDetails_t)'s `m_rgchTags` member is returned as a GML array in the async event triggered by `steam_ugc_request_item_details()`. Updated the documentation to make this a bit more clear.
