### ISSUE TITLE
Feather: Tooltip for script_execute and script_execute_ext incorrectly says they can take a string

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6531]
### Description
According to the feather tooltip, script_execute and script_execute_ext can take a string as the first argument. This differs from the documentation, which does not say they can take a string, and passing a string causes a runtime error.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/e7812004-f2d8-4e8e-ad77-1f861dded1ac)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/5ae41d78-dc92-458b-837a-538513188da6)

### Steps To Reproduce
Type script_execute or script_execute_ext and look at the feather tooltip for the first argument.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c1069742-2862-47df-93b7-1373ff403602](https://api.gamemaker.io/api/github/downloads/c1069742-2862-47df-93b7-1373ff403602)

**Comment by rwkay** [comment]
Fixed in 2024.8 - removed the `string` type from the `script_execute` and `script_execute_ext`

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
