### ISSUE TITLE
Manual: "License Information" link in the manual leads to a page with outdated information

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6532]
### Description

If you go to the "Licencing & Version Information" page in the manual and then click on the "License Information" link, it takes you to a page with old information from before the recent license changes, even though the text above the link specifically says "For up-to-date information"

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/09e9d4e4-16d9-450b-8089-7b71cd7c3480)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/9b7db3a9-826b-4c06-b0b4-af768f30c082)

This page also says nothing about paid licenses, only the free one. It links to another page at the very bottom which does have up to date information, so maybe that page could be what's linked to in the manual instead.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/7188f796-7af3-4b25-bc83-ea2e4f717e34)
Link takes you here, a page with current info:
https://help.gamemaker.io/hc/en-us/articles/235409387-How-To-Upgrade-Your-GameMaker-Licence

The page linked in the manual:
https://help.gamemaker.io/hc/en-us/articles/230492887-GameMaker-Free-Version

The outdated page is also linked to on this manual page:
https://manual.gamemaker.io/monthly/en/Setting_Up_And_Version_Information/Licencing_Information.htm

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=Setting_Up_And_Version_Information%2FGMS2_Version_Information.htm

**Comment by gurpreetsinghmatharoo** [comment]
The outdated helpdesk page has been updated and the manual page has also been updated to link to both helpdesk pages.

**Comment by mgeddesGM** [comment]
verified on both help and manual pages
