### ISSUE TITLE
Performance: Add a new Preference to toggle VSync within the IDE

### ISSUE THREAD

**Issue by stuckie** [YoYoGames/GameMaker-Bugs#6533]
### Is your feature request related to a problem?

We should expose the ability to toggle VSync on and off as far as the IDE is concerned with rendering.
This should use the same dpi_override.json file we use for DPI Override should a user need to change it for compatibility reasons.

By default, VSync should be on.

### Describe the solution you'd like

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/795290/93926d9a-1134-4e79-876b-f817b6220850)

**Comment by YYDan** [comment]
Spawned out of investigating https://github.com/YoYoGames/GameMaker-Bugs/issues/6515

**Comment by YYBartT** [comment]
Listed the new preference on the General Preferences manual page and updated the screenshot, also made a few changes to the `display_reset()` page.

**Comment by YYDan** [comment]
Preference is there and appears to work correctly in IDE v2024.6.1.160  Runtime v2024.6.1.208:

OFF in Preferences:
[{"Key":"vsync_enabled","Value":false},{"Key":"is_enabled","Value":true},{"Key":"value","Value":96}]

ON in Preferences:
[{"Key":"vsync_enabled","Value":true},{"Key":"is_enabled","Value":true},{"Key":"value","Value":96}]

Note that none of us ever reproduced the original flickering with G-Sync/Freesync, but certainly there are no ill effects we can see from the default being ON again and also if we manually disable Vsync thereafter.
