### ISSUE TITLE
Filters can be changed on locked layers

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6536]
### Description
While locking layer locks most of layer properties, it's possible to change Filters & Effects.

### Steps To Reproduce
Create layer, lock it, notice that everything is grayed out, except Filters & Effects.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.586 Runtime v2024.800.0.611

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d8799f10-8c01-4844-98ab-9372dd7c141b](https://api.gamemaker.io/api/github/downloads/d8799f10-8c01-4844-98ab-9372dd7c141b)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
