### ISSUE TITLE
Manual Content: gpu_set/get_sprite_cull() pages do not document the default values

### ISSUE THREAD

**Issue by JeffJ89** [YoYoGames/GameMaker-Bugs#6537]
### Description

This new page entry on the function gpu_set_sprite_cull is lacking a documented default value.

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Drawing/GPU_Control/gpu_set_sprite_cull.htm?rhsearch=gpu_set_sprite_cull&rhhlterm=gpu_set_sprite_cull

**Comment by attic-stuff** [comment]
the manual should definitely mention the default values, but if anyone is curious its on by default.

**Comment by gurpreetsinghmatharoo** [comment]
This was done earlier however the change didn't make it into the beta manual, it has now been updated
