### ISSUE TITLE
Manual Content: Page for audio_create_play_queue is incorrect about Audio Playback Asynchronous Event

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#6539]
### Description

The page for the function [audio_create_play_queue](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/Audio_Buffers/audio_create_play_queue.htm) states this:

> This function will trigger an Audio Playback Asynchronous Event when the queue has reached the end

To my understanding, in this case, if an audio queue is filled with 2 (or more) audio buffers and then played, the event would trigger when both audio buffers have come to an end. The page for the [Audio Playback Event](https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Object_Properties/Async_Events/Audio_Playback.htm) says :

> The event is triggered by a callback when you have selected an audio queue to playback and a buffer in that audio queue has finished playing.

This is actually what happens in the scenario laid out above.
See the issue in [this](https://github.com/user-attachments/files/16111624/audio_playback_event.zip) test

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/Audio_Buffers/audio_create_play_queue.htm

**Comment by mgeddesGM** [comment]
changes have been verified
