### ISSUE TITLE
sprite_get_info() always returns -1 for frame_type and 1 for frame_speed

### ISSUE THREAD

**Issue by James-Dolinar** [YoYoGames/GameMaker-Bugs#6542]
### Description
When using sprite_get_info() on a sprite the returned struct always holds incorrect values for the attributes frame_type and frame_speed. No matter what the type and speed are set to in the sprite editor, frame_type will always hold -1 and frame_speed will always hold 1.  frame_type should hold a value corresponding to one of the constants spritespeed_framespersecond or spritespeed_framespergameframe (0 or 1).

Note:  I've only tested this issue on the following exports: windows vm, html5, gx.games vm.

### Steps To Reproduce
1. Run the included project and observe the results output to the screen. 
2. The output for each sprite will be the same (frame_type: -1, frame_speed: 1).
 
The output shows the result of using sprite_get_info() on different sprites that have their frame_type and frame_speed all set to different values.

The output text is coming from obj_control's Draw GUI event.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
GX.games, HTML5, Windows

[a373f917-e003-458b-b11d-efb34435f46d](https://api.gamemaker.io/api/github/downloads/a373f917-e003-458b-b11d-efb34435f46d)

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
