### ISSUE TITLE
keyboard_virtual_height() should not be undefined if keyboard_virtual_status()

### ISSUE THREAD

**Issue by flori9** [YoYoGames/GameMaker-Bugs#6549]
### Description
The newest GameMaker update (2024.6) has introduced a double use of the virtual keyboard functions, so they do something completely different on the Windows platform (related to IMEs). This is probably a useful feature and all, but breaks the (I think reasonable) assumption that if keyboard_virtual_status() returns true, keyboard_virtual_height() and keyboard_virtual_width() return a real number, not undefined.
This can cause crashes because of unexpected undefined values. This change in behaviour was not even mentioned in the release notes.
My suggested fix would be to simply make separate functions for the IME functions. If this is not an option, I guess making keyboard_virtual_height() and width() return 0 instead of undefined would also be an option.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.0.205

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[25639e32-5e91-4a7e-b3f9-27e8fc64d0ee](https://api.gamemaker.io/api/github/downloads/25639e32-5e91-4a7e-b3f9-27e8fc64d0ee)

**Comment by yoyo-danielc** [comment]
`keyboard_virtual_height()` now returns zero on platforms that don't have a virtual keyboard for consistency with Android/iOS when the keyboard is either disabled or hidden by the presence of a connected physical keyboard.

**Comment by YYDan** [comment]
(There is no width function, btw.)

**Comment by YYBartT** [comment]
Updated the `keyboard_virtual_height()` manual page to mention that it returns 0 on platforms that don't have a virtual keyboard.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.605  Runtime v2024.800.0.628
