### ISSUE TITLE
Tying the "function" keyword to a macro breaks it.

### ISSUE THREAD

**Issue by Draco1223** [YoYoGames/GameMaker-Bugs#6551]
### Description
As the title suggests, whenever you tie "function" to a macro and use it (for the purpose of assigning a function to a variable), any previously assigned functions using this macro will be overwritten.

### Steps To Reproduce
#macro function() F

var _exampleFunctionA = F { show_debug_message("1"); };
var _exampleFunctionB = F { show_debug_message("2"); };

// This will print "2" to the output console twice
_exampleFunctionA();
_exampleFunctionB();

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

### Which platform(s) are you seeing the problem on?
Windows

[12aec994-9bbc-4a5c-b00f-7d9400c878c5](https://api.gamemaker.io/api/github/downloads/12aec994-9bbc-4a5c-b00f-7d9400c878c5)

**Comment by Draco1223** [comment]
Quick correction: This was intended to be reported for runtime **v2024.6.0.205**, NOT v2024.4.1.202.

I rolled back to the latter after the former rolled out, as it broke plenty of things in the project I had open. Unknowingly, I submitted this bug while I was still on this runtime.

**Comment by BenjaminUrquhart** [comment]
I believe this is a duplicate of #6525

**Comment by Draco1223** [comment]
OH, thank you! I was looking to see if this had already been documented but I don't believe I've seen this one. I'll go ahead and close the issue then.
