### ISSUE TITLE
`window_has_focus()` returns wrong result, if focus was lost when game is starting

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6565]
### Description
`window_has_focus()` wrongly returns true, if window was unfocused while game was building/starting.

### Steps To Reproduce
1. Open attached project, or crate a new one and in draw event add simply `draw_text(10, 10, $"has focus? {window_has_focus() ? "yes" : "no"}");`
2. run a game - while game is building, until it opens, click few times on empty space on windows taskbar (or some other window, but on one-screen configuration taskbar might be easier to click)
3. game will start unfocused (grya titlebar), but `window_has_focus()` would be returning true
4. if you activate window, from now on `window_has_focus()` would be working as expected

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.586 Runtime v2024.800.0.611

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[f9433e08-4f69-4b40-97df-19613b21fabc](https://api.gamemaker.io/api/github/downloads/f9433e08-4f69-4b40-97df-19613b21fabc)

**Comment by yoyo-danielc** [comment]
Fixed in 2024.10

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.625  Runtime v2024.1100.0.651
