### ISSUE TITLE
`sequence_track_new` crashes when `seqtracktype_moment` is used

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6567]
### Description
`sequence_track_new(seqtracktype_moment)` crashes with `Unsupported track type`, however, according to docs, there's no limit in sequence track constants that could be used ( https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Asset_Management/Sequences/sequence_track_new.htm ).

### Steps To Reproduce
1. execute `sequence_track_new(seqtracktype_moment)`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.586 Runtime v2024.800.0.611

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d3087242-d0aa-42e9-bede-6b93b01e5a4d](https://api.gamemaker.io/api/github/downloads/d3087242-d0aa-42e9-bede-6b93b01e5a4d)

**Comment by yerumaku** [comment]
```gml
execute sequence_track_new(seqtracktype_moment); // error
execute sequence_track_new(seqtracktype_message); // error
```

**Comment by mgeddesGM** [comment]
passing as changes can be seen in develope
