### ISSUE TITLE
Live Wallpaper is interactable only on one of the screens when display mode is set to mirror

### ISSUE THREAD

**Issue by jgolembka** [YoYoGames/GameMaker-Bugs#6568]
### Description

When Live Wallpaper is set as a desktop background and in mirror display mode, only one of the instances will react in any way to mouse movement or clicks. The screen on which the wallpaper is interactable can change when reloading the wallpaper.

### Expected Change

Have all instances be interactable 

### Steps To Reproduce

 - have more than one display in use
 - set a Live Wallpaper as a desktop background with display mode set to mirror
You can now see the wallpaper on all screens, but interact with only one of the instances

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
[wallpaper_blank.zip](https://github.com/user-attachments/files/16179037/wallpaper_blank.zip)

Modified sample that demonstrates the issue

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.800.0.595  Runtime v2024.800.0.619, thanks.
