### ISSUE TITLE
Unsandboxed Environment Notification

### ISSUE THREAD

**Issue by mranaglyph** [YoYoGames/GameMaker-Bugs#6577]
### Is your feature request related to a problem?

This could be considered a security feature, or a simple quality of life upgrade. Currently, when a developer makes an app in GMS, they can choose to make it unsandboxed, which has its advantages. However, it can be used to make malicious software as well. I am aware in the past, GM was always unsandboxed, and the sandboxing option, since its creation, has been an improvement on the security. This would simply be a further improvement on the potential issues with misuse of the software.

### Describe the solution you'd like

Basically, the idea is simple (in principle). If a developer has created an executable that is not sandboxed, and therefore can access the end-user's entire system, I think there should be a notification of some kind to that end-user. For example, in the installation package, a README with a notation that the application is 'Unsandboxed' would suffice. At the end of the day, how secure something is comes down to the end-user's habits, but giving them the option to know ahead of time, before running the application, could be beneficial.

### Describe alternatives you've considered

This discussion is currently going on in the GMC Forums (see link below). There have been a few suggestions, such as the README notification (previously mentioned), running the program in a sandboxed environment (VM or Windows Sandbox), and of course, only downloading software from trusted sources. There are a few issues I see with the latter two suggestions. 

First, while extremely useful, VMs and/or Windows Sandbox, might be a valid solution, but the bar for entry might be too high for the average user. Truth be told, I've never used Windows Sandbox, so I'm not sure of its technical difficulty specifically, but I can say I wouldn't wish a VM on a novice. 

Second, the 'trusted sources' argument is good typically, but this feature suggestion would be more an attempt at removing or mitigating 'False Negatives.' There are trusted platforms that can be tricked, just like anything can, but I'm simply saying I don't think the software distribution platforms should bear all the weight here. From what I have seen, GM has done a lot improve security and the overall user experience, this would be another step in that direction.

There are probably many more solutions to implement this type of feature, but I will leave that to the discussion and your thoughts on the topic.

### Additional context

https://forum.gamemaker.io/index.php?threads/ads-potential-issue-my-first-community-post.113795/#post-677021

Thank you for reading!

**Comment by stuckie** [comment]
The sandbox is more for preparation on targeting constrained platforms, rather than anything to do with security.
