### ISSUE TITLE
the footer on the dbg_view page has something funny going on

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6581]
### Description

this seems a little off but I can't quite place what's wrong

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/7a5693a7-8061-428d-adfe-99f232851177)

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDebugging%2Fdbg_view.htm

**Comment by YYBartT** [comment]
This will be fixed in the next manual release.
