### ISSUE TITLE
Google IAP doesn't respect multi-quantity

### ISSUE THREAD

**Issue by clee2005** [YoYoGames/GameMaker-Bugs#6583]
### Description
As of Google Billing 4.0 the default is to support multi-quantity for IAPs.   If a user specifies 2+ of an IAP from the Google Play purchase dialog (after selecting an in game IAP) then they will be billed for it, but the game will only give them 1 of the purchased items as it doesn't respect the 2+ quantity specified.

### Steps To Reproduce
The code in the extension only looks at the length of the array instead of the QUANTITY element in the response JSON.   There is only 1 purchase line, so it always processes just one purchase.   It must look at the QUANTITY.

	case gpb_iap_receipt:
	
		// At this point we just finished a purchase and are now triggering a receipt event.
		
		// We look at the async load for a 'response_json' key and parse the json value.
		var responseData = json_parse(async_load[?"response_json"]);
		if (responseData.success) {
			
			var purchaseTokens = {};
			
			var purchases = responseData.purchases;
			var purchasesCount = array_length(purchases);

### Which version of GameMaker are you reporting this issue for?
IDE v2024.4.1.152 Runtime v2024.4.1.202

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Android

[7327e555-a580-49ec-bb46-e07c69315fc4](https://api.gamemaker.io/api/github/downloads/7327e555-a580-49ec-bb46-e07c69315fc4)

**Comment by gnysek** [comment]
I suspect that this issue should be added here: https://github.com/YoYoGames/GMEXT-GooglePlayBilling

**Comment by clee2005** [comment]
Sure.   I just submitted the bug using the GM IDE.   It didn't ask me where
to send the bug.  I suspect triage will move it where it needs to go.

**Comment by jzavala-YYG** [comment]
Hi @clee2005

I'm a bit confused, are you just requesting an update in GameMaker sample project? and just add a multiplier depending of quantity of items in the purchase?

in the next example I just get the quantity but still using the length of the array to iterate.

```
		// We look at the async load for a 'response_json' key and parse the json value.
		var responseData = json_parse(async_load[?"response_json"]);
		if (responseData.success) {
			
			var purchaseTokens = {};
			
			var purchases = responseData.purchases;
			var purchasesCount = array_length(purchases);
			
			for(var i = 0; i < purchasesCount; i++)
			{
				var purchase = purchases[i];	
					
				var sku = purchase[$ "productId"];
				var token = purchase[$ "purchaseToken"];
				
				show_debug_message($"purchase: {purchase[$ "productId"]}")
				show_debug_message($"quantity: {purchase[$ "quantity"]}")
```

**Comment by clee2005** [comment]
Hi!

So the actual Google IAP extension doesn't handle multi-quantity
purchases.   I was just providing the sample project because that's what I
was looking at.   By iterating on the purchases array_length you'll only
have 1 purchase.   That single line item will have a quantity element in
the json which might be more than 1 (usually it's one, but the user can
change it to be anything).   If they do change it to 2 or more, then you'll
only process the purchase once, and they will have paid for more.

Cheers,
Chris

**Comment by DiasFranciscoA** [comment]
@clee2005 hello,

As @jzavala-YYG explained you should be able to check the `purchase[$ "quantity"]` this should be a property of the purchase being returned. The demo doesn't check it because it doesn't need to.

**Comment by clee2005** [comment]
Yes you’re right.  I was confusing the demo code with the actual extension
as I just used the demo code in my own implementation.

The ticket should be to update the demo code to properly handle
multi-quantity purchases.    I wouldn’t agree that the demo doesn’t NEED to
handle it.   It’d be very useful for other users that might run up against
this.

Thanks,
Chris

**Comment by YYBartT** [comment]
Added the "quantity" member of purchase to the documentation and updated the wiki.
