### ISSUE TITLE
Manual content: Audio buffers main page claims that Game Maker supports recording sounds from the OS

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#6589]
### Description

The main page for audio buffers states:

> Audio buffers will also permit you to record sound from any of the available sources (like microphones or the OS)

Which is not true as of Runtime v2024.600.609. Looping through the available audio recorders on Windows 11 (both VM and YYC) will not list the OS as a recorder.

### Manual Link

https://manual.gamemaker.io/beta/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FAudio%2FAudio_Buffers%2FAudio_Buffers.htm

**Comment by mgeddesGM** [comment]
changes have been verified
