### ISSUE TITLE
Importing project or assets with sound files (.ogg) into Beta show zero length

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#6592]
### Description
Importing asset bundles containing .ogg files show no length when imported into BETA ( IDE v2024.800.0.587  Runtime v2024.800.0.611) while working on GREEN ( IDE v2024.6.0.157  Runtime v2024.6.0.205)

### Steps To Reproduce
Create new project in BETA
Import the Compete Pack Desert Shooter Asset Bundle
(https://gamemaker.io/en/bundles)
Project will not import correctly (Sound Assets)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.587 Runtime v2024.800.0.611

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b2b37493-c8bb-4742-9e72-7b6400a8440d](https://api.gamemaker.io/api/github/downloads/b2b37493-c8bb-4742-9e72-7b6400a8440d)

**Comment by gnysek** [comment]
Existing projects also seems to have issues, but I didn't reported it yet, as .800 was no publicity out.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.590  Runtime v2024.800.0.614
