### ISSUE TITLE
HTML5: Nullish operator crashes js runtime

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6594]
### Description
Using the nullish operator (??) doesn't seem to work in HTML5 anymore.

### Steps To Reproduce
1. Run the sample project on Windows
2. Nullish works fine on Windows (it even works if you stack them together in weird ways!)
3. Run the sample project on HTML5
4. You get a million errors in the console

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.0.157 Runtime v2024.6.1.207

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
HTML5

[d84a07fa-d51d-4c20-8b55-f32cd24c7622](https://api.gamemaker.io/api/github/downloads/d84a07fa-d51d-4c20-8b55-f32cd24c7622)

**Comment by DragoniteSpam** [comment]
For the benefit of those spectating, the sample project is just

    var os_info = os_get_info();
    global.gpu_name = (os_info[? "gl_vendor_string"] ?? "") + (os_info[? "video_adapter_description"] ?? os_info[? "gl_renderer_string"]) ?? "";
    show_message(global.gpu_name)

**Comment by rwkay** [comment]
This is not a bug as the returned os_get_info map is not getting any entries in it so every entry is empty so all of the checked things are being returned as undefined but you have one final entry that is returned as undefined.

The HTML5 compiler will emit a check to ensure that the arguments to the plus operator are not undefined... this is what is causing the failure... 

you will be able to see this if you split the complex expression up into 

```
var os_info = os_get_info();
show_debug_message( json_encode(os_info));
var vendor = os_info[? "gl_vendor_string"] ?? "<unkown vendor>";
var description = os_info[? "video_adapter_description"] ?? "<no description>";
var renderer = os_info[? "gl_renderer_string"] ?? "<no renderer>";
global.gpu_name = vendor + description + renderer; 
show_message(global.gpu_name)
```
