### ISSUE TITLE
Running from command line throws errors even though running from IDE works fine

### ISSUE THREAD

**Issue by Psycho-Male** [YoYoGames/GameMaker-Bugs#6597]
### Description
I'm trying to run the project by calling this batch file, which was fine for a year until first April update I believe(I'm not sure which update broke it exactly unfortunately)

set config=%1
set runtime="2024.6.1.208"

C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-%runtime%\bin\igor\windows\x64\Igor.exe windows Run /rp="C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-%runtime%" /uf="%appdata%\GameMakerStudio2\selassin_68996" /project="%~dp0Secret Secretary.yyp" /config=%config%

I get `Assignment operator expected` when I use this macro
#macro __INPUT_GLOBAL_STATIC_VARIABLE  static __global = __input_global();
__INPUT_GLOBAL_STATIC_VARIABLE  -> Error on this line
I get tons of similar errors since there are lots of similar macros in the Input library.

Similarly, I get an error for Scribble on this macro, this time the error is `got 'break' expected '}'`
#macro __SCRIBBLE_PARSER_INSERT_NUKTA  ds_grid_set_grid_region(_temp_grid, _glyph_grid, _i+1, 0, _glyph_count+3, __SCRIBBLE_GEN_GLYPH.__SIZE, 0, 0);\

Like I said, this never happens when I run from IDE but I can't run any project. I tested on Runtime 2023.11.1.160 and it works fine.

### Steps To Reproduce
Run the project from comman line.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[9f5cf76c-aa45-4467-a83f-5ad021db7d24](https://api.gamemaker.io/api/github/downloads/9f5cf76c-aa45-4467-a83f-5ad021db7d24)

**Comment by rwkay** [comment]
I am only getting this when the config is not passed into the batch file - it takes a second parameter of the config - should be "Default" as that is the only config in the project

I think you need to update your batch file to set that as the config when none is given so change your batch file to be

```
set config=%1
if "%config%" == "" set config=Default
set runtime=2024.6.1.208

C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-%runtime%\bin\igor\windows\x64\Igor.exe windows Run /rp="C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-%runtime%" /uf="%appdata%\GameMakerStudio2\russell_59" /project="%~dp0Secret Secretary.yyp" /config=%config%
```
