### ISSUE TITLE
In-Game: [GX.games VM] All projects error on game start if built with 2024.800.0.611

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#6601]
### Description

As title

### Steps To Reproduce

1. Start GameMaker
2. Run project for GX
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
