### ISSUE TITLE
Code Editor 2: Weird behavior with double and triple click selection

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#6604]
### Description

During normal usage of the Editor it is possible that when trying to de-select a selected bit of text for the whole word, or line to be selected instead of dismissing the text. Additionally, the triple click to select a line behavior misbehaves by only selecting from the start of the word to the end of the line rather than the whole line. Lastly, sometimes the modified selection behavior does not clear on mouse up and can affect the next selection.

### Steps To Reproduce

1. Start GameMaker, open a script in CE2
2. Click and drag from left to right to select only a part of a word
3. Within 1/4th of a second move the cursor slightly to the left and click again
4. See the issue, the whole word was selected
5. Click to dismiss
6. Triple click in the middle of the line to select the whole line
7. See the issue, only part of the line was selected

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed, logged for tracking purposes.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.601  Runtime v2024.800.0.624
