### ISSUE TITLE
Add align option to dbg_text_separator()

### ISSUE THREAD

**Issue by blaiddx64** [YoYoGames/GameMaker-Bugs#6607]
### Is your feature request related to a problem?

The function **dbg_text_separator()** was added in the latest GameMaker update. I want to suggest a flag to control the text align.

### Describe the solution you'd like

```gml
dbg_text_separator("Text string", DBG_TXT_LEFT); // default
dbg_text_separator("Text string", DBG_TXT_MIDDLE); // middle
dbg_text_separator("Text string", DBG_TXT_RIGHT); // right
```

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103244351/7aae62d5-271b-420b-b48b-3ec8d08d190a)

**Comment by rwkay** [comment]
Added in 2024.8

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
