### ISSUE TITLE
Manual Content: Document all available injection strings available for iOS extension devs to use

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#6615]
### Is your feature request related to a problem?

The [current documentation](https://manual.gamemaker.io/monthly/en/#t=The_Asset_Editors%2FExtension_Creation%2FiOS_Extensions.htm) only lists available tags for injection, and not available strings. 
For example, [GMEXT-GameCenter](https://github.com/YoYoGames/GMEXT-GameCenter/blob/main/source/GameCenter_gml/extensions/GameCenter/gamecenter.yy) uses ${YYBundleIdentifier} which was renamed from ${YYPackageName} but there's no documentation. 

Only some of these are mentioned in the doc, for example ${YYXCodeProjName}. These can be very useful when adding project-independent build scripts. 

Related feature request: #2712

### Describe the solution you'd like

In the documentation of native extensions, add a list of available strings. At least the information under Game Options - iOS - General should be available, like the Display Name, Bundle Name, Min Version, etc.

**Comment by YYDan** [comment]
Presumably, we should do Android, macOS, etc., pages at the same time (if these differ at all) / have one page that lists all strings and clarifies any that are OS-specific.

**Comment by mgeddesGM** [comment]
changes have been verified
