### ISSUE TITLE
An unknown JSON key in FlexPanel Debug overlay will cause a hard error

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#6620]
### Description

An unknown JSON key in FlexPanel Debug overlay will cause a hard error

It should not give a hard error but add the error to the status line (along with the normal JSON errors)
The GML call should still display a hard error when used from code.

### Steps To Reproduce

1. Start GameMaker
2. Enable Debug overlay
3. Open the Flex Panel window
4. Edit one of the key names to be an unknown one i.e. "xposition"
6. See the Error Dialog

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.800.0.593  Runtime v2024.800.0.617
