### ISSUE TITLE
Building Projects: Setting a variable to equal "_GMFUNCTION_" inside an event results in a compilation error

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#6630]
### Description

See image below:
![image](https://github.com/user-attachments/assets/b1a4d642-fc65-47aa-a106-7a6d7ae29937)

[gmfunction_compile_error.zip](https://github.com/user-attachments/files/16192538/gmfunction_compile_error.zip)

### Expected Change

This shouldn't fail to compile

### Steps To Reproduce

1. Start GameMaker
2. Open attached project and run
3. See the issue (it will fail to compile)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
