### ISSUE TITLE
MacOS RSS issue

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#6634]
### Description

At open GameMaker stable version I got a popup saying: "RSS operation has timed out"
![Screenshot 2024-07-12 at 7 10 40 a m](https://github.com/user-attachments/assets/374e44c8-d472-40b6-971a-b5f7f748bdd3)
[ui.log](https://github.com/user-attachments/files/16195620/ui.log)

### Expected Change

Fix the RSS issue

### Steps To Reproduce

1. Start GameMaker on MacOS
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Hehe, okay, so your ui.log shows that your Mac has been unable to reach any of our feeds/sites for at least 2 days and the problem started in 2024.4.1 IDE before you updated:

For example (this was in .4.1):
```
[18:36:25:911(4c48)] Checking network....
[18:36:45:931(4c48)] InternalCheckForInternetConnection :: Unable to reach site https://gms.yoyogames.com/ReleaseNotes.html
[18:36:45:931(4c48)] InternalCheckForInternetConnection :: Unable to reach site https://api.gamemaker.io/api/health-check
[18:36:45:931(4c48)] InternalCheckForInternetConnection :: Unable to reach site https://api.gamemaker.io/api/health-check 
[18:36:45:932(4c48)] InternalCheckForInternetConnection :: Unable to reach site https://www.yandex.ru
[18:36:45:932(4c48)] System.AggregateException: One or more errors occurred. (A task was canceled.)

```
(That ui.log only goes back 2 days, so I have no idea when this actually started.)

https://gms.yoyogames.com/update-mac.rss is working just fine for me right now, but I am on Windows, so will double-check on a Mac shortly.

You _sure_ GM is not firewalled on your Mac and your Mac was online at the time? ;)

**Comment by jzavala-YYG** [comment]
It work fine on Windows for me too. 

Tried 2 days ago and I had the same issue all the day. tried yesterday worked fine for one time. and today I'm having the same issue,

**Comment by cameron-home** [comment]
Have not been able to repro on macOS Monterey, and have been able to download the RSS file @YYDan attached in his comment.

**Comment by jzavala-YYG** [comment]
If I try https://gms.yoyogames.com/update-mac.rss from my Mac I can download the file too, but I still seeing the RSS issue

**Comment by jzavala-YYG** [comment]
Ok, exists a way, but I can implement it directly on the extensions, so I will write it here, eventually all the users should use min: 24.

1) Open C:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2024.6.1.208\android\runner\ProjectFiles\build.gradle

2) Insert this code in the line 19 (after **_buildTypes_** finalizes )
```
buildTypes {
        debug {
			signingConfig signingConfigs.release
			minifyEnabled ${YYAndroidProGuardMinifyEnabled}
			shrinkResources ${YYAndroidProGuardShrinkResources}
			getIsDefault().set(true)
			ndk {
                debugSymbolLevel 'FULL'
            }
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro'
			consumerProguardFiles 'proguard-rules.pro'
        }
}
```

3) Check minifyEnabled
<img width="329" alt="image" src="https://github.com/user-attachments/assets/3323ea3b-cf14-4d46-96ee-f8252c10d739">

Let me know if work for you.

**Comment by stuckie** [comment]
I've not been able to reproduce this, but I'm hoping that the various extras added to the later releases - better ipv6 support and caching of the RSS feeds when we do get them - should help here.
There was also a crash issue ( see linked ticket above ) that has been fixed.
Going to preliminarily close this just now...
