### ISSUE TITLE
Binary typo in bit shift example

### ISSUE THREAD

**Issue by notgudman** [YoYoGames/GameMaker-Bugs#6640]
### Description

On the third to last paragraph of the manual page for `tilemap_set_mask` the explanation of the example code writes:
> the bits of _random_value are first shifted left by 8 bits, for example a value of `0b0000000011001111 (207)` becomes `0b1111111100000000 (52992)`

The decimal number of the returned value is correct but the binary is missing the two non-trailing 0 bits from the first number

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FRooms%2FTile_Map_Layers%2Ftilemap_set_mask.htm

**Comment by YYBartT** [comment]
This will be fixed in the next manual release.
