### ISSUE TITLE
Inspector: When viewing an object, checkboxes such as visible and persistent are in the collision mask section

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6645]
### Description
The various checkboxes for objects are inside the collapsible collision mask section in the inspector, even though only solid has anything to do with collision.

https://github.com/user-attachments/assets/b0707d40-666f-4e95-a15e-c01d92dff05b

### Steps To Reproduce
View an object in the inspector.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.583 Runtime v2024.600.0.607

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[bf9b89f0-5101-45ad-9b42-403ee55458cf](https://api.gamemaker.io/api/github/downloads/bf9b89f0-5101-45ad-9b42-403ee55458cf)

**Comment by yyalansavage** [comment]
Updated so hopefully an improvement - 
![inspector-object-collisionmask](https://github.com/user-attachments/assets/31202410-854c-403e-b9bc-777f06beb1e6)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.604  Runtime v2024.800.0.627
