### ISSUE TITLE
Inspector: Tooltips for object checkboxes do not appear

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6653]
### Description
In the workspace object editor, there's tooltips for the various checkboxes. In the inspector, these tooltips do not appear.

https://github.com/user-attachments/assets/93aa5de8-048b-48e2-be62-f0595514118c

### Steps To Reproduce
Hover over a checkbox such as "visible" in the inspector.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.583 Runtime v2024.600.0.607

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[7a042976-561b-46ea-aed1-2a4e3ab0d258](https://api.gamemaker.io/api/github/downloads/7a042976-561b-46ea-aed1-2a4e3ab0d258)

**Comment by yyalansavage** [comment]
tooltips added

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.592  Runtime v2024.800.0.616
