### ISSUE TITLE
Calling string function on a string within toString method includes quotes

### ISSUE THREAD

**Issue by nommiin** [YoYoGames/GameMaker-Bugs#6661]
### Description

When using `string` on a class that has a `toString` method, subsequent `string` calls for variables/properties will include quotes in the returned string

![image](https://github.com/user-attachments/assets/20f2056c-8fbf-44d9-9eab-19d96a5af4e8)

This behaviour ***does not*** occur when explicitly calling `toString`

### Expected Change

string should not include quotes for string values

### Steps To Reproduce

1. Start GameMaker
2. Create a constructor that implements a `toString` method
3. Create a local variable/class property that is a string
4. Within `toString`, use the `string` function on the given variable and return it
5. Implicitly call `toString` by using `string` on the class, explicitly call `toString` as well
6. Observe outputs, the implicit call will include quotes whereas the explicit call does not
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project
[tostring.zip](https://github.com/user-attachments/files/16202575/tostring.zip)

**Comment by rwkay** [comment]
Fixed in 2024.8
