### ISSUE TITLE
layer_get_all() returns numbers, not layer ref IDs.

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#6662]
### Description
``layer_get_all()`` returns an array of numerical IDs, instead of layer references.

### Steps To Reproduce
1) Make a room with some layers.
2) ``show_debug_message(layer_get_all())``

Current Output: [ 58,73,59, ... ]
Expected Output: [ ref layer 58, ref layer 73, ref layer 59, ... ]

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[96398cca-be11-4317-8739-aa2344a44c51](https://api.gamemaker.io/api/github/downloads/96398cca-be11-4317-8739-aa2344a44c51)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
