### ISSUE TITLE
`room_get_info` Instances Array Returning Extremely Large instance Ids

### ISSUE THREAD

**Issue by danieltjewett** [YoYoGames/GameMaker-Bugs#6663]
### Description

When using `room_get_info(roomIndex, false, true, true, true)`, we get extremely large instance ids, as shown below:

![image](https://github.com/user-attachments/assets/bfb7eac1-e030-415a-967d-c830660623a6)

The element array which references the instance also contains this large, incorrect id (but at least they are referencing each other).  Scrolling through some of the data, I noticed that there were some other large ids (like Shader on the layer), but that info isn't pertinent to our needs, and haven't verified this one way or another.

### Expected Change

The ids should be correct references to the instance names in the room editor.

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. In the create event, add the code:
```
var data = room_get_info(room, false, true, true, true);
var dog = 5;
```
4. Add a breakpoint to that line 1
7. Add the object to the instances layer
8. Run the game in debug mode
9. See the issue

[room_get_info_error.zip](https://github.com/user-attachments/files/16203612/room_get_info_error.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.601  Runtime v2024.800.0.624

**Comment by danieltjewett** [comment]
Also, I realized the title has been changed with `Debugger`.  Sure, we're using the debugger to see what is going on.  But the issue is not just in the debugger.  These values are incorrect everywhere.
