### ISSUE TITLE
feather: matrix_transform_vertex documentation is off

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6668]
### Description

this is one of those things that makes me wish feather would be open sourced already because it would take like ten seconds to make a PR to fix

![image](https://github.com/user-attachments/assets/a992bf11-904e-4916-b033-d4d6117d12ea)

### Expected Change

xyzw

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly), 2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
The problem here seems to be that documentation gets cut at first "." which means this is a problem with the actual Feather system, not the GMLSpec. @zreedy ?

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.591  Runtime v2024.800.0.615
