### ISSUE TITLE
a syntax error in the sample code in the "Evaluation Order" in manual

### ISSUE THREAD

**Issue by UTF00** [YoYoGames/GameMaker-Bugs#6671]
### Description

The sample code here has a syntax error.
![218386ce33f0a61e82b932d5f2c9d10](https://github.com/user-attachments/assets/c71546f7-5849-42f6-8068-b4be76f20a0f)
It should be changed to:
```gml
var val = [];
val[0] = buffer_read(buff, buffer_s8);
val[1] = buffer_read(buff, buffer_s16);
val[2] = buffer_read(buff, buffer_s16);
buffer_get_info(val[0], val[1], val[2]);
```

### Manual Link

http://127.0.0.1:51290/index.htm#t=GameMaker_Language%2FGML_Overview%2FEvaluation_Order.htm

**Comment by mgeddesGM** [comment]
changes have been verified
