### ISSUE TITLE
Creating an asset with alt + letter, deselecting it, and then hitting alt + letter two more times closes the IDE

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6678]
### Description
I've reproduced the issue with alt + o to create new objects and alt + s to create new sprites, and alt + j to create new animation curves. It probably happens for other assets too, but it's annoying to test them all since GM closes every time.

https://github.com/user-attachments/assets/34de8874-bc23-4522-871d-9943bb239851

### Steps To Reproduce
Create an asset with something like alt + o. De-select it by clicking on a different asset or in empty space in the asset browser. Hit alt + o two more times. The IDE will instantly close itself.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c327bac0-2820-4333-95d4-495ca56c7bc1](https://api.gamemaker.io/api/github/downloads/c327bac0-2820-4333-95d4-495ca56c7bc1)

**Comment by SmithTom6304** [comment]
Fixed - this could occur any time the active gadget was null.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.6.2.162  Runtime v2024.6.1.208. 

Thank you.
