### ISSUE TITLE
Code Editor 2: Hitting "Enter" on the @ description line causes the next line to start with "///" 

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#6680]
### Description

Hitting "Enter" on the @ description line causes the next line to start with "///". 

![image](https://github.com/user-attachments/assets/4c8122f0-2350-4b8c-b315-7b3ca9044cd3)

Tested using IDE v2024.800.0.589  Runtime v2024.800.0.612

[Contact Us Package](https://drive.google.com/file/d/166yrLaR5IuzXXhSK9LIoOaiRqVH3wIu2/view?usp=sharing)

### Expected Change

This differs from CE1 which would just create a blank new line, however this change for CE2 could be intentional.

### Steps To Reproduce

1. Start GameMaker
2. Enable Code Editor 2
3. Create a Script
4. Add any Event to the Script
5. Select the description line and press Enter to create a new line below it
7. See the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
This is a feature, disable `Code Editor 2 -> Auto extend multiline comments` if you do not desire this functionality.
