### ISSUE TITLE
"collapse/expand dock panels" doesn't collapse the new "instances" panel in room editor

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6683]
### Description

Pressing F12 or clicking "collapse/expand dock panels" doesn't collapse the room editor's instances panel that was added in 2024.6

### Steps To Reproduce

1. Start GameMaker
2. Create new project
3. Create a new room and open it
4. Press F12
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This is not a dock.
There is an icon on the top right of the panel that you can use to move it around as required.
