### ISSUE TITLE
With statement passes for obj checks that haven't had their create event called yet.

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#6691]
### Description

* Imagine you have - `obj_A` and `obj_B` in a room.
* Inside `obj_A` create event you do `with(obj_B)` and check a variable inside it
* This will crash because the `with` statement passes (object exists) but the `obj_B` create (and pre-create) event didn't execute yet.

### Expected Change

The with(X) statement shouldn't pass before the instance create event runs.

### Steps To Reproduce

1. Start GameMaker.
2. Run the DEMO game.
3. See the issue.

[BLANK GAME.zip](https://github.com/user-attachments/files/16245705/BLANK.GAME.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by scott-dunbar** [comment]
The issue as described here no longer occurs, however a new issue has come in that I believe is a result of this change https://github.com/YoYoGames/GameMaker-Bugs/issues/6765

Awaiting a resolution to the linked issue to verify this issue

**Comment by JordOfTheFlies** [comment]
Finding that with() in the create event of an instance created at the same time (in my case using a with() statement to a collect a bunch of objects into a single vertex buffer) can't correctly run in 2024.8 even if instance_count(obj) still correctly sees the instances.

**Comment by rwkay** [comment]
This is fixed on an internal build....

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.595  Runtime v2024.800.0.619
