### ISSUE TITLE
Erroneous text in diagram in Collision Mask section of The Sprite Editor manual page

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#6694]
### Description

In the Collision Mask section of The Sprite Editor manual page, there is a diagram showing several pairs of circles to explain how the different collision settings interact.  Next to these are the words "precise" "rectangle / rotated rectangle" "ellipse" "diamond" but these do not seem relevant to the diagram.

It looks like "precise", "ellipse", and "diamond" should be outright deleted, and it looks like "rectangle / rotated rectangle" should instead say "precise" because there is a line leading from that text to the circle which has precise collisions.

### Manual Link

https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Sprites.htm

**Comment by mgeddesGM** [comment]
changes have been verified
