### ISSUE TITLE
Syntax parser crash when using #endregion inside switch without starting #region tag

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#6699]
### Description

![image](https://github.com/user-attachments/assets/b59395d2-d525-408f-81b1-f1f99615ad80)

When attempting to use the #endregion directive inside a switch block without a corresponding starting #region tag, the syntax parser crashes with a System.InvalidOperationException: Stack empty exception. This occurs because the parser does not expect the #endregion directive in this context, leading to a stack handling error.

[Contact package](https://github.com/user-attachments/files/16250659/ContactPackageEndRegion.zip)

### Expected Change

The syntax parser should either correctly handle the #endregion directive inside the switch block or provide a clear error message indicating that the #endregion directive is used without a corresponding starting #region tag.

### Steps To Reproduce

1. Start GameMaker
2. Create a new object or script in the development environment.
3. Add the following code:
```gml
switch (1) {
    case 1: break;
    #endregion
}
```
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2022.0.2 (LTS), 2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
