### ISSUE TITLE
Incorrect function array_length_id used in debug_get_callstack example instead of array_length

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#6700]
### Description

![image](https://github.com/user-attachments/assets/c58c9eae-ddbb-44e8-af75-9bbfb21415d8)

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDebugging%2Fdebug_get_callstack.htm

**Comment by mgeddesGM** [comment]
changes have been verified
