### ISSUE TITLE
Empty NOTE section in Expressions And Operators page

### ISSUE THREAD

**Issue by misternebula** [YoYoGames/GameMaker-Bugs#6706]
### Description

In "_**Expressions And Operators**_", under the "_**Comparing (<, <=, ==, !=, >, >=)**_" subtitle, there is an empty NOTE section. Is this meant to say something?

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Overview/Expressions_And_Operators.htm#

**Comment by mgeddesGM** [comment]
changes have been verified
