### ISSUE TITLE
Copy IDE and Runtime Versions to Clipboard

### ISSUE THREAD

**Issue by bfrymire** [YoYoGames/GameMaker-Bugs#6711]
### Is your feature request related to a problem?

When assisting users of GameMaker with issues, a common question is, "What IDE and Runtime are you using?" This often leads to users sharing cropped screenshots of their IDE to show the versions. While this is acceptable, it could be more efficient.

### Describe the solution you'd like

A feature that allows users to click on the IDE and Runtime versions, which are always displayed on the IDE. When the versions are clicked, a small dropdown box appears with a button that says "Copy to clipboard". When the "Copy to clipboard" button is pressed, it copies the IDE and Runtime versions to the clipboard as text.

For example:

```txt
IDE v<IDE_VERSION> | Runtime v<RUNTIME_VERSION>
```

Where <IDE_VERSION> and <RUNTIME_VERSION> are variable placeholders for the actual IDE and Runtime versions.

### Additional context

Below is an example screenshot of the area the user will click to get the dropdown box:

![GameMaker_WiDNpWZ5JS](https://github.com/user-attachments/assets/ef557e32-ba20-453d-82b4-acc5fd6acdd1)

**Comment by L-Clouds** [comment]
This is already implemented, minus a dropdown or button.  When you click that text, it is copied to the clipboard, unprompted.

(Or at least it used to; I'm not running an up-to-date version so if that feature was removed or has broken, I wouldn't know.)

**Comment by bfrymire** [comment]
> This is already implemented, minus a dropdown or button. When you click that text, it is copied to the clipboard, unprompted.
> 
> (Or at least it used to; I'm not running an up-to-date version so if that feature was removed or has broken, I wouldn't know.)

Thanks for bringing this to my attention. It is implemented in ` IDE v2024.6.1.160  Runtime v2024.6.1.208`. *(Yes, that was copied from the IDE using the feature, and yes it does come with a leading space.)*
