### ISSUE TITLE
Code Editor 2: Tab/Untab Selection does not update Selection Range appropriately

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6712]
### Description

Indentation in CE2 needs a hug

![ce2 tab selected region is haunted](https://github.com/user-attachments/assets/351e49d6-9323-4357-a3b5-e12bb2e7f95c)

See also #5492 for Episode 1 and #6390 for Episode 2

 IDE v2024.800.0.591  Runtime v2024.800.0.615 (this admittedly might be one of those "stop using unreleased betas" moments)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
