### ISSUE TITLE
Fix ASAP: Opening up GameMaker in newest version freezes at User Processing

### ISSUE THREAD

**Issue by xhixzi** [YoYoGames/GameMaker-Bugs#6717]
### Description

 IDE v2024.6.1.160 Runtime 2024.06.2.162 - Windows 11. When I launch GameMaker, I open it up, and it just stops at "User Processing..." nothing else loads, so I can't even use the program... needs to be fixed ASAP

### Expected Change

User being able to be processed so GameMaker can be used

### Steps To Reproduce

1. Start GameMaker
2. Network is checked
3. Languages are loaded
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by xhixzi** [comment]
login is glitched https://drive.google.com/file/d/1ol0UA-j_xDMI6ewWpFx5TnvdvlFSaInT/view?usp=sharing

**Comment by gnysek** [comment]
> IDE v2024.6.1.160

Newest version is 2024.6.2.162 .

**Comment by L-Clouds** [comment]
> > IDE v2024.6.1.160
> 
> Newest version is 2024.6.2.162 .

Probably just a typo, looks like they reversed version numbers for IDE and runtime.

**Comment by gnysek** [comment]
Still, both should have .2 in it's name, and 162/208 as build numbers. ( IDE: 2024.6.2.162 / Runtime: 2024.6.1.208)

**Comment by xhixzi** [comment]
I am running IDE: 2024.6.2.162 and still getting the "User Processing" error.

**Comment by xhixzi** [comment]
I DIAGNOSED THE ISSUE -- When I decided to delete all of the files in my cache folder, in GameMaker's program files, and reinstalled latest version once again (IDE v2024.6.2.162  Runtime v2024.6.1.208) somehow everything seems to be working now. There should be a warning to clear the cache whenever a new update should be installed or have the cache cleared automatically. Glad I found the problem though

**Comment by gnysek** [comment]
I never cleaned this directory, while I'm installing 5-10 GM updates per month, so this is not a good advice. However there's a chance that you've deleted too many files if you meant ProgramData folder. If you need to delete runtimes to save space on disk, delete folders in runtimes directory only.

**Comment by stuckie** [comment]
Hello.

I am glad you managed to resolve it, as I only just noticed that there was no contact us package included originally, so we would have had no logs to go on to help.

As clearing the cache helped, it could have been any number of issues from a partial runtime install, bad data in the preferences or cached login information, or any other number of things.

If it happens again, please ensure that the contact us package is included so we can trace what happened.

Thanks!
