### ISSUE TITLE
[YYC] Silent crash when finally is executed in specific scenarios

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#6729]
### Description
I tend to try and replicate problematic issues in a library by trying to replicate parts of the core library, but I've been unable to successfully reproduce this issue. Though I do know what causes it exactly, so I've removed everything that's not super relevant for the project to run (just the bare basics and a singular test case that demonstrates the problem)

Running in VM works perfectly fine, with no issues whatsoever.

### Steps To Reproduce
1. Download the project
2. Find `scr_testing_environment`, line 23 has a method called `func` that gets called. (This is bounded to the function `__catspeak_function__`)
3. Run the game in YYC, see crash. 
4. Commenting out the `finally` block and rerunning the project in YYC, does not crash.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[1be6d090-6767-463d-bba7-9fe783ab6c28](https://api.gamemaker.io/api/github/downloads/1be6d090-6767-463d-bba7-9fe783ab6c28)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.600  Runtime v2024.800.0.623
