### ISSUE TITLE
Problem with Xbox controller on Mac M2

### ISSUE THREAD

**Issue by Badkaas** [YoYoGames/GameMaker-Bugs#6739]
### Description

Hello,

I bought a Mac M2, I'm running Mac OS 14.5. I have an Xbox ONE S controller (the white one), and not all the buttons work. The joysticks and the A button work, but not the X button or the start button.

Best regards,

### Steps To Reproduce

1. Start GameMaker
2. if gamepad_button_check_pressed(0, gp_start){ ... }

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
We would need the model number off of the controller to verify this.
However the controller itself may also need it's firmware updated, as there was an issue with this previously.

**Comment by Badkaas** [comment]
Hello
It's the model 1708
I updated the controller but I will check this evening.

Best regard.

Le jeu. 18 juil. 2024 à 10:49, Steven Campbell ***@***.***> a
écrit :

**Comment by rwkay** [comment]
Unable to replicate I have a macOS M1 with Sonoma myself and the 1708 XBox One Controller working wirelessly worked fine and I have just checked that wired controller works as well.

**Comment by Badkaas** [comment]
Hello
The controller was update and the model is 1708. It's thé Xbox one S
controller.
Best regard.


Le jeu. 18 juil. 2024 à 10:49, Steven Campbell ***@***.***> a
écrit :
