### ISSUE TITLE
Resource load failures encountered

### ISSUE THREAD

**Issue by noobiusfool** [YoYoGames/GameMaker-Bugs#6742]
### Description

After installation I get 
Resource load failures encountered
C:\Users\ictra\GameMakerProjects\Space Rocks\Template_Space_Rocks.yyp(2,3): GMSC Error: File parsing failed: Type tag missing when parsing slot of type YoYoStudio.Resources.ResourceBase
If I create a project, all the files are created, but it wont open and I get the same message. This happens with the tutorials or a blank game. I have uninstalled/reinstalled, I have tried the version on Steam. When I first downloaded yesterday it worked, but since then......

### Steps To Reproduce

1. Start GameMaker
2. Create a project
[space rocks error.zip](https://gi
[Space Rocks.zip](https://github.com/user-attachments/files/16281206/Space.Rocks.zip)
thub.com/user-attachments/files/16281193/space.rocks.error.zip)

3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
There doesn't appear to be any logs attached here to know why it has failed.

An initial thought would be to ensure the IDE and Runtime versions match, as well as to check permissions.
 I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

If that doesn't work, please submit a new report with the contact-us package so we have more logs to go on.
