### ISSUE TITLE
Start Page: Remembering the last valid mouse hover position causes confusion when attempting to create projects from Templates

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#6745]
### Description

When you click on a template icon in the list of templates the panel to the right populates with the description (in a badly sized text box) and a section below which it tells you the Scripting Language that it is available in. You have to then click again on the icon in the left panel for the Scripting Language choice to be made into a selectable dialog and the options for Project Name/Location to appear.  

After first click:
![Screenshot 2024-07-18 at 11 16 00](https://github.com/user-attachments/assets/44d94384-16cf-41a8-914e-2811c187d3f4)
After second click:
![Screenshot 2024-07-18 at 11 16 05](https://github.com/user-attachments/assets/78748efc-ed8d-4500-9c23-0ae887e05190)

### Expected Change

Options for selecting Scripting Language & where to download should always be active, not needing a second click OR we don't show them until you have actually selected a Template and instead we show a line of text saying to select the template

### Steps To Reproduce

1. Start GameMaker
2. Reach the Start Page normally
3. Select New > Game
4. Move your mouse over any of the templates (do not click anything) and observe the right-hand panel updates to show the details for this Template even though you have not selected it
5. Move your mouse anywhere else (e.g., over into the right-hand panel) and observe the Start Page continues to show the unselected template
6. Try clicking the language selector and observe it is not responsive (because at this point it's a text label, not a radiobox)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Can only assume there was some IDE lag as you clicking, as I don't reproduce this issue if I click - but it's 100% if you hover the mouse without clicking.

Think part of it is that the styling for the unselected/selected "Scripting Language" section is identical to the "Selected" one, rather than just being part of the description text,

**Comment by yyalansavage** [comment]
Changing it so a single click selects the template (instead of only de-selected currently selected one)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.604  Runtime v2024.800.0.627
