### ISSUE TITLE
Image Editor: [Mac IDE] GM unstable when attempting to edit a sprite that has previously failed to load

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#6747]
### Description

When attempting to edit a sprite that has been removed, the GameMaker has become unstable message appears, if you click ok, it just comes 
[physicsbeta1.zip](https://github.com/user-attachments/files/16281648/physicsbeta1.zip)
up again and you have to Force Quit the IDE.

### Steps To Reproduce

1. Start GameMaker
2. Open the attached project, note the correct failed to load message appears when loading the project (the project comes from when the serialiser was broken)
3. Attempt to edit the image for Sprite1
4. Observe the GameMaker has become unstable message, click ok, see the unstable message re-appears

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.600 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/issues/6749#issuecomment-2273249433
Behaviour on project load now seems to match windows (with no warning shown). We now just get the red cross error image rather than an unstable message, so nothing to do for this ticket.

**Comment by Emc1923** [comment]
Closing as per comment above, thanks.
