### ISSUE TITLE
Code Editor 2: Global variables appear bold even when bold setting is disabled in themes

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6750]
### Description
In the new beta that just came out, global variables are appearing bold at all times, even though the bold setting in themes is disabled.

![image](https://github.com/user-attachments/assets/67b29451-deab-42cd-92e4-61ab8887fc82)

### Steps To Reproduce
Declare a global variable

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.600.0.607

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[2875f319-db7d-40f7-a0f9-592f25cea361](https://api.gamemaker.io/api/github/downloads/2875f319-db7d-40f7-a0f9-592f25cea361)

**Comment by zreedy** [comment]
Fixed. The tmTheme had an override for the parent scope `storage.modifier`, which is masked by the specific scope `storage.modifier.global` which does not set a Bold flag. Perhaps some UI change should be introduced to indicate that some flag is overridden by a parent class.

**Comment by zreedy** [comment]
Fixed + Merged
