### ISSUE TITLE
Code Editor 2: Arguments in function declarations always appear in unset color

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6751]
### Description
Arguments are always appearing in unset color instead of local color:
![image](https://github.com/user-attachments/assets/a5183306-a06f-45c4-857f-f891c82d5775)

### Steps To Reproduce
Declare a function with some arguments

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.600.0.607

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b16698b0-fb5f-433a-b196-716bd176c440](https://api.gamemaker.io/api/github/downloads/b16698b0-fb5f-433a-b196-716bd176c440)

**Comment by stuckie** [comment]
This is due to an outdated colour theme.
We should ensure that we layer them from our defaults, then onto the user colours.

**Comment by stuckie** [comment]
In the CE2 theme editor, clicking Restore Default Colours at least sets the defaults until restarting the IDE.
Setting the colour manually does not seem to work either.

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1100.0.685  Runtime v2024.1100.0.707

![Image](https://github.com/user-attachments/assets/f20aa09b-2579-49ba-9d1d-53f36b0f152d)
