### ISSUE TITLE
GmlSpecChanges aren't up to date

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6753]
### Description

There's special directory in `GameMaker-Bugs` repo which lists new functions/variables in GML. However, it's missing 2024.4, 2024.6 and 2024.8 changes:

https://github.com/YoYoGames/GameMaker-Bugs/tree/main/GMLSpecChanges

### Manual Link

https://github.com/YoYoGames/GameMaker-Bugs/tree/main/GMLSpecChanges

**Comment by iampremo** [comment]
Fixed - Removed the folder
