### ISSUE TITLE
Code editor 2: Rainbow brackets sometimes fail to color in specific combinations of nested brackets/parenthesis

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6754]
### Description
It seems that some specific combinations of brackets can cause rainbow brackets that should be orange to show up grey instead. Enjoy the most cursed example code I've ever included. This was originally real code, I just realized I could remove all the actual code, leaving just the brackets, and still have the problem happen lol

![image](https://github.com/user-attachments/assets/0cf58bcf-6542-4018-9ed6-366ae536d631)

### Steps To Reproduce
```
(){[$()]{()(()){[$[]]}}} //the [] after the $ will be grey

{()(()){[$[]]{{()()}}}} //the ()() in the middle will be grey
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d06578ba-8ae0-4a65-bcab-152768fe7a4d](https://api.gamemaker.io/api/github/downloads/d06578ba-8ae0-4a65-bcab-152768fe7a4d)

**Comment by zreedy** [comment]
This is working as intended, what's happening here is that you've exceeded the number of rainbow colors that are defined so it's looped back to the 0th color. This color is the default color defined for that token type. If you were to replace these with `{}` you would see a bold orange as this is the theming for braces.

**Comment by scott-dunbar** [comment]
Closing as per comment
