### ISSUE TITLE
Error "OpenAL error: 40963 (After playing sound)" appears repeatedly, and some sounds stop playing.

### ISSUE THREAD

**Issue by BscotchSeth** [YoYoGames/GameMaker-Bugs#6755]
### Description

Runtime 2024.600.0.607 (VM Windows)

In Crashlands 2 this week, we began experiencing random failures of sounds to play. Upon boot-up, the game runs normally and plays sounds normally. But at some point -- sometimes within a few minutes, or much longer -- a sound effect will fail to play when called, and then this message appears in the console:

`OpenAL error: 40963 (After playing sound)`

This will happen repeatedly throughout a game session, and at increasing frequency after it happens the first time. Whenever we attempt to play a sound that triggers that error message, that sound will never be playable again for the duration of the game session. Each time a sound fails to play, we get another instance of the error message. Over time, more and more sounds stop being playable, and the console just fills up with these messages, like this:

![image](https://github.com/user-attachments/assets/050dc410-7cd8-44dd-8806-7bb5f2109383)

We have been unable to replicate this in other contexts because it happens at random during normal gameplay. Googling shows that nobody else on the whole internet has posted this error message in any forums, Reddit, github, or anywhere else. Some guidance on potential ways to replicate (or resolve) would be appreciated.

### Steps To Reproduce

1. Boot up Crashlands 2.
2. Play for a while.
3. Sounds *may* stop playing.

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by EddyMRA** [comment]
Hi everyone, our team has also begun experiencing these same issues with sound beginning to drop at random. When we began experiencing audio drops, we also got the `OpenAL error: 40963 (After playing sound` message in the IDE console.

Here's another visual aid that we think may be helpful to figure this issue out. We went into the Debug interface in-game by pressing F12, then looking at the Audio debug window. It shows one audio source (here as number 124) that stay active even without a sound playing. This audio source never frees up, nor does it ever get used again. It just stays stuck and cuts off audio that are meant to use this audio source number, it seems.

![image](https://github.com/user-attachments/assets/683543d8-2d94-48eb-a9c6-e25c9a35abc4)

**Comment by toby-yoyo** [comment]
This could potentially be the same underlying issue as in https://github.com/YoYoGames/GameMaker-Bugs/issues/6727

**Comment by EddyMRA** [comment]
> This could potentially be the same underlying issue as in #6727

My workaround for this issue is to roll back to Runtime version 2024.4.1.202, the latest version of the GM Runtimes before the 2024.6 versions

**Comment by toby-yoyo** [comment]
Thanks for the info all. I believe that this should be resolved by https://github.com/YoYoGames/GameMaker-Bugs/issues/6727.

Raised https://github.com/YoYoGames/GameMaker-Bugs/issues/6839 to improve reporting of OpenAL errors as the message seen in this particular issue turned out to be misleading.
