### ISSUE TITLE
Code editor 2: Autocomplete sometimes will disappear when backspacing 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6756]
### Description
Autocomplete will disappear if you backspace while typing, but only if backspacing leaves a small number of characters remaining. The exact number seems to vary, with 1-2 characters remaining being the most common.

https://github.com/user-attachments/assets/2e4ef330-176c-4eb4-a99d-fc57ded15e44

### Steps To Reproduce
Type something that brings up autocomplete, and then backspace until autocomplete disappears.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[9fe9711b-88ac-4c63-8013-bbc57dbadf67](https://api.gamemaker.io/api/github/downloads/9fe9711b-88ac-4c63-8013-bbc57dbadf67)

**Comment by zreedy** [comment]
This is now fixed

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
