### ISSUE TITLE
Code editor 2: Various macro contents show up as the grey unset color

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6757]
### Description
Functions, globals, and other macros are all showing up in the grey unset color when used in a macro definition. There might be other things that show up in grey as well but I haven't tested every possible thing.

![image](https://github.com/user-attachments/assets/a3ecb790-d33d-4075-a02c-e5f63a74124d)

### Steps To Reproduce
Define a macro that contains a function, global, or another macro.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a02b9d6b-072a-492d-bc19-07b24616d7dc](https://api.gamemaker.io/api/github/downloads/a02b9d6b-072a-492d-bc19-07b24616d7dc)

**Comment by rendadongdong** [comment]
same problem.

**Comment by zreedy** [comment]
Fixed and merged.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
