### ISSUE TITLE
Code editor 2: Issues with deleting local package files and then re-importing

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6763]
### Description
If you have some local package files and then delete them and re-import them (such as when updating a library), the re-imported files will not process correctly, with missing syntax highlighting and middle clicking to jump to definition won't work. Additionally, if you reload CE2 by doing something like disabling it and reenabling it, you can then middle click the functions but it will open up bugged code tabs that will not save changes.

https://github.com/user-attachments/assets/d5a709ef-0c83-40e4-bf59-4df98e70cf29

### Steps To Reproduce
1. Import a local package with script files. 
2. Open up the scripts in CE2.
3. Delete the scripts
4. Import the local package again
5. Open up the scripts again
6. Syntax highlighting will be broken, and jump to definition won't work
7. Reload CE2 by disabling it and reenabling it in preferences
8. Jump to definition will work again, except it will open bugged code tabs that cannot save changes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files:
Bug Test.yymps

[08660e00-9e46-432b-8589-27ee521cf1ba](https://api.gamemaker.io/api/github/downloads/08660e00-9e46-432b-8589-27ee521cf1ba)

**Comment by zreedy** [comment]
Fixed. URI Cache was stale.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1100.0.624  Runtime v2024.1100.0.650
