### ISSUE TITLE
Flex Panels: C++ Runtime Library error if trying to connect already connected node

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6768]
### Description
When first argument of `flexpanel_node_insert_child` is a node, which was already added to something, there's `Microsoft Visual C++ Runtime Library` error shown, instead of normal GM Error Window.

It probably still should throw an error, but maybe it could have GM customized one, that this node was already connected to something, instead of throwing underlying C++ runtime error.

### Steps To Reproduce
1. Run code attached to this issue (or copy it from below):
```gml
	a = flexpanel_create_node({});
	b = flexpanel_create_node({});
	c = flexpanel_create_node({});
	
	flexpanel_node_insert_child(a, b, 0);
	flexpanel_node_insert_child(c, a, 0);
	flexpanel_node_insert_child(c, b, 0);
```

This will result in
![obraz](https://github.com/user-attachments/assets/7244c7b7-ae51-486d-9fce-cc8333d8e20a)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[e124938e-9872-4e68-95b5-36a07e04bb28](https://api.gamemaker.io/api/github/downloads/e124938e-9872-4e68-95b5-36a07e04bb28)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.595  Runtime v2024.800.0.619
