### ISSUE TITLE
In-Game: audio_sound_get_track_position will incorrectly print an error message if called at the start of a compressed sound

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#6775]
### Description
If `audio_sound_get_track_position` is called on a compressed sound before any buffers have been queued, it will incorrectly print the error message "Failed to determine playback position", but will correctly return the position of 0.

### Steps To Reproduce
- Open and run the example project
- Observe the message being printed in the console

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[e95c3b22-d566-488b-a269-3bbb6f24096b](https://api.gamemaker.io/api/github/downloads/e95c3b22-d566-488b-a269-3bbb6f24096b)

**Comment by toby-yoyo** [comment]
Removed the error message, which shouldn't have been there in the first place - everything was fine!

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.599  Runtime v2024.800.0.622
