### ISSUE TITLE
In-Game: Calling asset_get_index with an non-existent asset will print a message from the audio library to the console

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#6776]
### Description
Calling `asset_get_index` with an invalid asset will cause the following message to be printed to the console: `Name did not map to an existing audio asset`.

### Steps To Reproduce
- Open and run the example project.
- Observe the messages bring printed to the console.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[ed2d53fa-cbf5-4c0a-8c27-76365d0ab8ee](https://api.gamemaker.io/api/github/downloads/ed2d53fa-cbf5-4c0a-8c27-76365d0ab8ee)

**Comment by toby-yoyo** [comment]
Prevented the message from appearing.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.603  Runtime v2024.800.0.625.
