### ISSUE TITLE
List of code editor 2 bugs, Freezing and bugs

### ISSUE THREAD

**Issue by bookmint** [YoYoGames/GameMaker-Bugs#6779]
### Description

Freezing and Lag Bugs: Using GameMaker for a while longers the freezing and lagging
https://github.com/user-attachments/assets/812a5fbe-6de8-4710-a6f8-eea611f63569

Copying and pasting fabricates lines
https://github.com/user-attachments/assets/3220b74b-17ad-42bf-9afc-227019c78a53

Top down menu for code editor 2 disappeared:
![Screenshot 2024-07-19 122056](https://github.com/user-attachments/assets/dfa7a503-8942-4199-8e29-1512931e60de)

### Steps To Reproduce

1. Start GameMaker
2. Use gamemaker for a couple of hours, code editor 2
3. Freezing
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by iampremo** [comment]
Your navigation menu for the code editor is snapped to the bottom of the window, you can move it using the drop down on the right side of the bar 


![Image](https://github.com/user-attachments/assets/4adad512-fac1-42d4-85e1-03ecee0b2c55)

**Comment by stuckie** [comment]
These are already reported... and please submit one bug per ticket so that both we and you can track them.
