### ISSUE TITLE
TypeGML

### ISSUE THREAD

**Issue by peardox** [YoYoGames/GameMaker-Bugs#6781]
### Is your feature request related to a problem?

GML is an untyped language

### Describe the solution you'd like

In the JavaScript world TypeScript is a popular option. Typescript compiles to Javascript but adds type safety ands other additional features such as objects (more advanced structs) and namespaces etc. A Javascript program is valid Typescript but the reverse is not always the case.

It would be beneficial if there was optional syntax in GML that added type safety but could be used only if desired by the developer. Similar to Typescript this could compile to GML (or possibly a stricter form of it)

As a simple example a lot GML makes extensive use of Integers (e.g. for loops) it would be nice to at least check the variable being used didn't get assigned a float

### Describe alternatives you've considered

N/A

**Comment by DragoniteSpam** [comment]
Theoretically, this is what feather is for. We'll see how that goes in practice.

**Comment by stuckie** [comment]
Closing as not planned.
