### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#6782]
### Description
TEST

### Steps To Reproduce
TEST

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Mac 13.5.1

### Which platform(s) are you seeing the problem on?
macOS

### Attached Files:
01a0d4b5-562d-477f-863f-56daa38100d30.png, 225Oneofeach.yymp, 225oneofeachGML.yyz

[e515e303-f4b7-442c-a4e2-ebabe636b059](https://api.gamemaker.io/api/github/downloads/e515e303-f4b7-442c-a4e2-ebabe636b059)

**Comment by scott-dunbar** [comment]
Closing as Test
