### ISSUE TITLE
Older Runtime not on list, fails to install when downloaded manually

### ISSUE THREAD

**Issue by KamiSquadX** [YoYoGames/GameMaker-Bugs#6792]
### Description

Downloaded Runtime 2.2.3.344 from https://gamemaker.io/account/runtimes/version followed the instructions (added the zip to %programdata%\GameMakerStudio2\Cache\runtimes\runtime-2.2.3.344\download) started GM, it said new runtime available, clicked that notification, but the runtime still is not listed (stops at 2.3.0.401) and the downloaded runtime isn't installed either (at %programdata%\GameMakerStudio2\Cache\runtimes\runtime-2.2.3.344\)

Is there a way to make GM search for older runtimes? Or is there a way to manually make GM install a downloaded runtime?

-Running: GameMaker 2023.6.0.92 
(I don't know if this is a Monthly, LTS, or Beta)
[Contact Us.zip](https://github.com/user-attachments/files/16318106/Contact.Us.zip)

### Steps To Reproduce

1. Download Runtime 2.2.3.344
2. Move the zip to %programdata%\GameMakerStudio2\Cache\runtimes\runtime-2.2.3.344\download
3. Start GameMaker
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
That runtime is no longer supported.
If you are having trouble bringing in an older project, please let us know and attach the project so we can take a look.
