### ISSUE TITLE
Stability: GM crash on startup due to cryptography "Access Denied" exception when starting MQTT

### ISSUE THREAD

**Issue by VeryLowPoly** [YoYoGames/GameMaker-Bugs#6794]
### Description

When I go to launch the game, the splash screen comes up describing what it's loading and when that screen goes away, I'm met with just a blank grey screen. The project selection screen does not appear, and when clicking on the screen it begins Not Responding. Unable to load into the IDE through opening project files as well. Since I can't get into GMS2 itself and create a contact package, I'm unable to provide that below, but have attached the ui log in hopes that the issue can be found there

[ui.log](https://github.com/user-attachments/files/16318505/ui.log) shows lots of successive cryptography exceptions:

```
[22:03:50:517(f45c)] MQTT - System.AggregateException: One or more errors occurred. (Access denied.)
 ---> System.Security.Cryptography.CryptographicException: Access denied.
   at System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan`1 data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at MQTTnet.Certificates.BlobCertificateProvider.GetCertificate()
   at MQTTnet.Implementations.MqttTcpServerAdapter.StartAsync(IMqttServerOptions options)
   at MQTTnet.Server.MqttServer.StartAsync(IMqttServerOptions options)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at YoYoStudio.IDE.MqttInitialise()
```

### Expected Change

GameMaker should still start successfully and then warn more effectively about this error and how to fix

### Steps To Reproduce

1. Start GameMaker
2. Load splash screen
3. Cannot continue
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Judging from that error, this is an issue with the OS account permissions, antivirus/firewall settings or other security products on your machine or network, rather than a GameMaker bug or something we could fix _fully/properly_ for you (we will of course look into stopping the crash and instead show you a dialog that you need to check the guide below).

You need to review our [Permissions FAQ](https://help.gamemaker.io/hc/en-us/articles/360022953052) and follow the steps there, and I suspect this will allow you to fix your existing GM install right away. Note that we always link to this guide on the release notes page, as many users need to review their protection settings every time they install a new version of GameMaker, so this may be something you need to do also in future.

**Comment by VeryLowPoly** [comment]
I appreciate the response! After allowing write access to this folder, I
was able to open it up again and recover my project! Thank you so much for
the help and support! I was just really confused because the Long Term
Stable version was working just fine, right? But when I upgraded to this
version of GMS2 after the last I only saw the screen halt before showing
the load project screen

This is excellent news! I'm very grateful you guys could help me out (:

**Comment by stuckie** [comment]
Excellent!

Glad you got it working, and thanks for letting us know.

**Comment by VeryLowPoly** [comment]
for sure! And thank you guys for being an awesome team

**Comment by stuckie** [comment]
Should now catch the exception and just stop MQTT from starting up and blocking the rest of the IDE flow.
The exception will be logged to the ui.log as normal.

**Comment by VeryLowPoly** [comment]
You guys are so on top of it! Thank you so much for your help and support(:

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Emc1923** [comment]
Verified as of Beta IDE v2024.800.0.613 Beta Runtime v2024.800.0.636
