### ISSUE TITLE
Code editor 2 + Feather: Deleting the last line of a document when it has a feather error will cause the error to stick around in diagnostics until reload

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6798]
### Description
This feather issue only happens when CE2 is being used, it does not happen with CE1. If you type some code that causes a feather error on the last line of a document and then quickly delete it, the error will stick around in the diagnostics window until the project is reloaded.

https://github.com/user-attachments/assets/b8ddfc13-f415-4b61-b83d-eaea00c7cb2d

### Steps To Reproduce
While CE2 is active, type some code that causes feather errors on the last line of the document. Delete this code, including the newline, and see that the diagnostics window still shows the error. Select and delete multiple lines at once to make it easier to reproduce.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5a13ae7f-4e79-442e-8595-99989e045ec2](https://api.gamemaker.io/api/github/downloads/5a13ae7f-4e79-442e-8595-99989e045ec2)

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
