### ISSUE TITLE
Manual: call_later page doesn't mention that the returned time source doesn't need to be manually destroyed

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6802]
### Description

The page for call_later indirectly implies that the time source it uses doesn't need to be cleaned up by not saying anything about destroying it, but this isn't the most clear. I think it'd be better if it specifically said that it doesn't need to be cleaned up, unlike a regular time source. It'd be easy to assume it does still need to be cleaned up since it uses a time source.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Reference%2FTime_Sources%2Fcall_later.htm

**Comment by alicemoretti** [comment]
Verified fixed on the latest build of the Beta Manual build. Thank you.
