### ISSUE TITLE
Enabling mipmaps with an unlimited frame rate makes my computer make a weird noise

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6803]
### Description
When I uncap the frame rate and turn mipmapping on my GPU fan gets squeaky

When I turn mipmapping off (but the game is still running with an uncapped frame rate) it stops

GTX 1060 3GB

Watch to the end to see what the spectrograph looks like, it's honestly really cool

https://github.com/user-attachments/assets/89cfda98-e57f-4b39-bf2e-487e7e986e0f

See if it makes your GPU squeak

[3DTutorial78Mipmapping - Lesson Plan.zip](https://github.com/user-attachments/files/16319906/3DTutorial78Mipmapping.-.Lesson.Plan.zip)

### Steps To Reproduce
if it helps I guess I could mail you my computer or something?

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[eaa1cd42-f148-42aa-b6b8-8a1349ba4263](https://api.gamemaker.io/api/github/downloads/eaa1cd42-f148-42aa-b6b8-8a1349ba4263)

**Comment by DragoniteSpam** [comment]
This is (mostly) a joke, this GPU is more than 7 years old and i'm sure the fan is as cheap as they come. But this whole thing is too funny not to share

![image](https://github.com/user-attachments/assets/8fab0a74-9dce-41d1-8277-33d3cb95822c)

**Comment by DragoniteSpam** [comment]
I just found a way to make it even worse: the squeaky noise it makes is different depending on whether the filter setting is Linear or Anisotropic

**Comment by JordOfTheFlies** [comment]
That's definitely coil whine from 1000+ fps. This kind of highlights that GM could really use a true frame rate display that doesn't simply base its result off of CPU load. Display a heavy enough shader at you can make the game visibly run at 10 FPS (also reflected through gamebar and any other frame rate monitors) while GM still displays (through all available FPS variables and displays) it's running at 60. Currently estimating GPU load / 'actual' performance requires external tools.

**Comment by DragoniteSpam** [comment]
Someone else suggested coil whine too. Actual `fps` variable will show 10 if it's GPU bottlenecked to 10 though, it's `fps_real` that's the lie.

**Comment by stuckie** [comment]
This is likely just different load on the GPU causing the fan to speed up/down and resonate weirdly within the case.
