### ISSUE TITLE
Code editor 2: Autocomplete doesn't work properly inside methods in a large project

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6804]
### Description
When writing code inside a method, autocomplete won't load the majority of things in global scope, including functions, globals, macros, and even keywords. The project has to have a lot of code in it for the problem to happen. I added a bunch of libraries to the sample project to reproduce the issue. It does not happen in an empty project. It only happens inside methods, not when typing code in an event directly.
With all these conditions met, autocomplete works when you've only written a single character, but as soon as you write a 2nd character it only shows a tiny selection of irrelevant options, or nothing at all.

https://github.com/user-attachments/assets/b894a5d0-3256-4a0c-9a29-3fa37e8b929c

### Steps To Reproduce
1. Download a bunch of big libraries to make a project with a lot of code (or download the attached sample project)
2. Define a method on an object
3. Try to type function, macro, global, or keyword names, and watch autocomplete.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[99c7004c-0519-401d-b361-fa0881ce7ea9](https://api.gamemaker.io/api/github/downloads/99c7004c-0519-401d-b361-fa0881ce7ea9)

**Comment by zreedy** [comment]
Fixed

**Comment by cameron-home** [comment]
Verified fixed using the attached project in IDE v2024.1100.0.623  Runtime v2024.1100.0.649
