### ISSUE TITLE
EXC_BAD_ACCESS When running on IOS 17.5 Simulator (ipad)

### ISSUE THREAD

**Issue by hamsandvich** [YoYoGames/GameMaker-Bugs#6806]
### Description
When trying to run the runtime in IOS 17.5 Simulator (ipad) it will crash and throw an error in xcode.

The same xcode project that is produced will run on the physical device just not in sim.

### Steps To Reproduce
Run the xcode build produced by gamemaker in Ipad sim with 17.5

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.4.1.201

### Which operating system(s) are you seeing the problem on?
Mac 14.5

### Which platform(s) are you seeing the problem on?
iOS

[4cd37732-1507-423c-8a37-ec838df25566](https://api.gamemaker.io/api/github/downloads/4cd37732-1507-423c-8a37-ec838df25566)

**Comment by stuckie** [comment]
Your runtime is out of date from the IDE, could you ensure that your runtime matches?
There is also a known issue for iOS Simulator 17.5 - you may want to try 17.2 instead.

**Comment by stuckie** [comment]
Your runtime is out of date from the IDE, could you ensure that your runtime matches?
There is also a known issue for iOS Simulator 17.5 - you may want to try 17.2 instead.
