### ISSUE TITLE
CE2 function hints disappear or do not show at all under expected circumstances

### ISSUE THREAD

**Issue by Hyomoto** [YoYoGames/GameMaker-Bugs#6811]
### Description
While typing the CE2 will only show function hints under very specific circumstances.  For built-in functions it will show while typing, after the brace and once you press comma.  Methods hints are shown while typing, but usually immediately once the brace is added.  Lastly, hints for constructors do not show at all.  If the hints are shown, they disappear once backspace is pressed and do not reappear if the function is re-entered.  For comparison, in the original code editor a function hint is shown in the gutter any time the cursor is between the ()'s and not inside a nested function, and while it didn't work for methods it did show constructor hints.

### Steps To Reproduce
Try to get hints for constructors, details for methods, or return to a function.  In all cases the only way to get details is to hover over the function with the mouse which will also disappear once you start typing.  Also, pressing backspace while a hint *is* shown will cause it to disappear.  The behavior is not consistent enough and each one could probably be its own bug report but it all falls under the heading of "hinting is not working right."

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22621.0

[74180717-41c2-4752-9442-7162367c5861](https://api.gamemaker.io/api/github/downloads/74180717-41c2-4752-9442-7162367c5861)

**Comment by zreedy** [comment]
Fixed
