### ISSUE TITLE
No output when building game

### ISSUE THREAD

**Issue by Lumina652** [YoYoGames/GameMaker-Bugs#6820]
### Description

Didn't open any projects on gamemaker for a month. Opened my game yesterday and today and no matter what I do, when I try to build a game or debug or even make an executable, there is no output at all, it just loads endlessly and I can't even stop the loading process. Tried to verify steam files, uninstall and reinstall, nothing is working for me. Even on blank projects it just doesn't wanna build and shows no output.

### Steps To Reproduce

1. Start GameMaker
2. Open a new project/existing one
3. Run the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
Uploaded contact-us package to internal drive: https://drive.google.com/file/d/18KpHGNh-2KFb6thui3RQrYi7qnVUVOy1/view?usp=drive_link

**Comment by stuckie** [comment]
From a look at your logs, you are using a really old runtime - 2.3.6 - with a newer IDE.
This won't work.
You will need to ensure your runtime and IDE match up.
