### ISSUE TITLE
Debugger: RAM usage remains very high after viewing large surfaces, even after closing the debugger

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6821]
### Description
While doing some limit testing on surfaces in GM, I noticed that viewing the surfaces in the debugger caused the IDE's memory usage to go extremely high. This is probably expected, since it has to load images of all those big surfaces into memory so you can preview them. However, while closing the game and the debugger will cause memory usage to slowly come back down, it will not go all the way back to normal IDE memory usage levels. If I get the IDE's memory usage to go to 20 GB while viewing the surfaces, closing the game and the debugger will only bring the memory usage back down to 8 GB, even after waiting for a long time. As I'm writing this, it's been sitting at about 8 GB for over 10 minutes.

https://github.com/user-attachments/assets/24c7eb60-7fec-4d0e-ae21-b9a57deb56ff

What memory settled at a couple minutes after the end of the video:
![image](https://github.com/user-attachments/assets/ff5fd773-1d85-4168-8907-391e7b552b73)
It stayed at about this amount for 20 minutes, and then I closed the IDE.

Edit: I just tried it on beta too, and it was actually worse, with memory settling at about 17 GB instead of 8
![image](https://github.com/user-attachments/assets/11a11835-78f7-4fa8-a529-fd5300e5021b)

### Steps To Reproduce
Create multiple very large surfaces. Run the debugger, and pause it. View the surfaces in the graphics tab of the debugger. Watch the task manager, and close the game + the debugger after memory maxes out. Continue watching the task manager, and memory usage will slowly come back down, but stop going down once it gets to around 8 GB. It will remain around 8 GB seemingly forever, even if you do things like run the game again or run the debugger again without viewing the surfaces.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[176933b0-3901-40ee-8b37-b78507d90d4d](https://api.gamemaker.io/api/github/downloads/176933b0-3901-40ee-8b37-b78507d90d4d)

**Comment by yyalansavage** [comment]
Fixed a leak which prevented the surface memory being freed; it is now being collected although it can still take a while for this to happen so memory in task manager can remain high for a while, may be room for further improvement here.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.600  Runtime v2024.800.0.623
