### ISSUE TITLE
Code Editor 2: Pasting code sometimes unindents the line and makes the caret wander off randomly

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6827]
### Description

It doesn't do this all the time and I'm not sure what triggers it.

![CE2 pasting unindents line](https://github.com/user-attachments/assets/24f67999-9f95-4d9a-935a-a7a1c4a4d7a1)

### Expected Change

The text should sit and stay

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment]
> Please provide the code snippet that demonstrates this issue.

This seems to do it 100% of the time:

    // pie <- copy this
    
    duck_wake = new CharacterSpriteCollection()
        .SetAlphaQueue(true),       // <- paste in here

**Comment by zreedy** [comment]
Fixed. See https://github.com/YoYoGames/GameMaker-Bugs/issues/6243 for details

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
