### ISSUE TITLE
Code Editor 2: Breakpoints do not maintain their correct position when you add/remove other lines of code

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6831]
### Description

In Code Editor 1, breakpoints stick to the line they were originally created on if you add/remove stuff up above, and they go away completely if you delete the line. This is incredibly useful.

![ce1 breakpoints move](https://github.com/user-attachments/assets/85a746e1-0ad8-4879-a914-b6bba15a4ced)

In Code Editor 2 they don't do that.

![ce2 breakpoints dont move](https://github.com/user-attachments/assets/fcdfe891-7c50-455a-8800-e87cce296ea6)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649
