### ISSUE TITLE
Code Editor: Bookmarks do not maintain their correct position when you add/remove other lines of code

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6834]
### Description

This is a lot like #6831, except it was like this in the old code editor too.

![bookmarks dont move when you add lines](https://github.com/user-attachments/assets/49d7fa31-4a18-4a78-9fae-fca209671ad7)

I suspect a lot more people would use bookmarks if they were more user-friendly. I frequently make a lot of noise about how breakpoints are better "bookmarks" because they stick to the line they were assigned to (or at least they did in the old code editor).

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment]
The line between "bug" and "feature request" in UX is very blurry, but if it's a UX problem that prevents people from doing something I've decided I'm going to call it a "bug."

**Comment by YYDan** [comment]
Assuming the functionality exists already and can be reasonably argued to be working incorrectly for most people, then "yes, largely that's correct" - we can always change it later anyway.

It would _not_ be a bug to say "because _this_ bit of functionality I want does not currently exist, then I cannot do _that_" ;)

**Comment by zreedy** [comment]
Fixed.
