### ISSUE TITLE
Bug Reporter: Improve PrivateIssueError message to something more informative

### ISSUE THREAD

**Issue by batblaster** [YoYoGames/GameMaker-Bugs#6836]
### Description
When i try to create a bug report and mark it as private i receive an error message.

![image](https://github.com/user-attachments/assets/00258423-6fb5-4d5a-badd-2cb495b34d6e)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[56ad1e69-93c5-435e-b147-34bebcee15af](https://api.gamemaker.io/api/github/downloads/56ad1e69-93c5-435e-b147-34bebcee15af)

**Comment by iampremo** [comment]
Update the error message of this to be:

> There was a problem submitting your bug report.
> Please re-authenticate your GitHub account before resubmitting.
> The report has been saved and you can try again later.

**Comment by yyalansavage** [comment]
added private issue dialog - 
![private-issue-dialog](https://github.com/user-attachments/assets/34982a6e-dd67-40b6-aca4-f047513e10b1)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.603  Runtime v2024.800.0.625

**Comment by mgeddesGM** [comment]
to test this I:

1. created a new account
2. set account to have xbox and enterprise but  was not github authorised
3. I then set an xbox bug report to private
4. the above error alert is shown

**Comment by mgeddesGM** [comment]
verified in LTS IDE v2022.0.3.67  Runtime v2022.0.3.80
