### ISSUE TITLE
Improve reporting of OpenAL errors

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#6839]
### Description
Raised as a response to https://github.com/YoYoGames/GameMaker-Bugs/issues/6755.

OpenAL has a global error state, which should be checked after each library function call. At present, most library calls are not followed by error checks, which leads to the ones that are often reporting misleading errors that originated from previous calls.

We should improve the reporting of OpenAL errors so that:
- All library calls check for errors.
- The meanings of error codes are conveyed where necessary.
- The source of the function calls are better identified (e.g. with filenames/line numbers)

There isn't a real need to make these errors user-friendly as they are indicative of runtime bugs - users should not be able to generate these errors from GML. However, when users do see and report these issues, we should make sure that enough information is provided to understand what went wrong and where.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a55cbc6f-d987-43bd-89c2-c3f2afcfa5e0](https://api.gamemaker.io/api/github/downloads/a55cbc6f-d987-43bd-89c2-c3f2afcfa5e0)

**Comment by toby-yoyo** [comment]
- Added checks to all OpenAL functions that can change the global error state.
- Improved logging when errors occur, giving the meaning of the error code, context, function name, filename and line number.

No example project for this one as it isn't really a user-facing change. These errors cannot normally be generated from GML.

**Comment by sihammill** [comment]
This can't really be tested as verified with Toby. You shouldn't really see those errors unless there's a bug in the audio engine.
