### ISSUE TITLE
In-Game: Using built-in `gm_Lights_` uniforms in HLSL shader throws "Array too large for shader" errors/fails to build

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#6840]
### Description

Using the built in shader uniforms, `gm_lights_pos_range`, `gm_lights_colour`, or `gm_ambient_colour` will result in an "Array too large for shader" error being thrown upon using `shader_set()` with the shader containing them:

![image](https://github.com/user-attachments/assets/8629361e-2100-4843-ab6b-51206bf9649e)

https://github.com/YoYoGames/GameMaker-Bugs/issues/5944 describes a very similar behaviour, but specifically on ubuntu targets.

interestingly, `gm_lights_direction` will also not work, but instead fails to build, after getting stuck at "DirectX11: Using hardware device".

Here's a small test project and the output logs for it:

[HLSL light uniforms issue.zip](https://github.com/user-attachments/files/16351170/HLSL.light.uniforms.issue.zip)
[HLSL light uniforms issue contact us package.zip](https://github.com/user-attachments/files/16351242/HLSL.light.uniforms.issue.contact.us.package.zip)

[output log.txt](https://github.com/user-attachments/files/16346095/output.log.txt)
[output log for gm_lights_direction.txt](https://github.com/user-attachments/files/16351172/output.log.for.gm_lights_direction.txt)

### Expected Change

These built-in shader uniforms/constants should be usable without throwing errors.

### Steps To Reproduce

1. Start GameMaker
2. Open the sample project: [HLSL light uniforms issue.zip](https://github.com/user-attachments/files/16351170/HLSL.light.uniforms.issue.zip)
3. This project features a room with a single object that will attempt to set the current shader to one with `gm_Lights_Colour` in it
4. Run it and observe the error
5. uncomment each `shader_set()` line in obj_shader_test to observe how they each fail

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.607  Runtime v2024.800.0.631
