### ISSUE TITLE
Tileset edges creating visual borders when game is converted to 3D

### ISSUE THREAD

**Issue by JosephDoubleYou** [YoYoGames/GameMaker-Bugs#6844]
### Description

When using camera_set_view_mat and camera_set_proj_mat, the tileset that was previously seamless now has flickering edges at the border of each tile. Gamemaker discord helpers confirmed that this was an issue they had never seen before with tilesets in 3d.

### Expected Change

Tiles should be seamless, even when the camera perspective changes to 3d.

### Steps To Reproduce

1. Start GameMaker
2. Start the game
3. Move using wasd to better see the issue

[3D_TILEMAP_ISSUE.zip](https://drive.google.com/file/d/1HoSmy_FBjB__43Ii7IrlMUJZzpoTPOGw/view?usp=drive_link)
*edit* replaced link to internal drive - please use the Bug Reporter in future as this will keep your information private *edit*

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by JosephDoubleYou** [comment]
https://github.com/user-attachments/assets/96dbe7ed-33d3-440c-8430-a57a3e137620

Hey, here is a video ref of the issue. That is odd, because I sent a project file to members of the Gamemaker discord, and they confirmed that they saw it as well. I am on a mac, and they confirmed that they were on a pc when they checked.

**Comment by jackerley** [comment]
That looks like you have interpolation on - if you go to Options->macOS->Graphics and deselect Interpolate colours between pixels does this fix it?
