### ISSUE TITLE
Code Editor 2: Document Search/Replace: Clicking the Prev/Next Buttons does not focus the Editor panel

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6854]
### Description
If you search for something with local search/replace with ctrl + f, the text you search for does not get selected when cycling through options. It does work when using global search replace, and also works in CE1.

https://github.com/user-attachments/assets/6a4d48fe-ec85-48c0-95b1-0051b187d47f

### Steps To Reproduce
Press ctrl + f, search for something, and then try to type without clicking to select the text manually.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[2cbe656c-dd12-4bb1-90d7-b57dc1cfd71e](https://api.gamemaker.io/api/github/downloads/2cbe656c-dd12-4bb1-90d7-b57dc1cfd71e)

**Comment by zreedy** [comment]
The video does not demonstrate the bug, the text is indeed being selected as you cycle through the next/previous entries.
The text is additionally highlighted to show all occurrences which does obscure the visibility of the selection however.

**Comment by KormexGit** [comment]
It looks like the text is being selected, but it's not actually being selected, I'm doing the same thing as I do with the global search of pressing space after each time I press next, but the space is not being typed and the selected text not being overwritten.

**Comment by zreedy** [comment]
So the issue isn't that the text isn't selected but rather that keyboard focus isn't returned to the Editor?

**Comment by KormexGit** [comment]
Yes, that makes more sense as being the issue now that you've said it

**Comment by zreedy** [comment]
Updated the title to reflect the issue

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
Verified in   IDE v2024.1000.0.621  Runtime v2024.1000.0.647.
