### ISSUE TITLE
Manual Content: Pages for gamepads should not use examples which show looping over gamepad_get_device_count()

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#6861]
### Description

Many gamepad-related entries in the Manual recommend looping over `gamepad_get_device_count()` or 1-4 ranges in their examples, which is inappropriate because gamepad IDs aren't always contiguous and should be detected over Async - System instead.

- https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_get_device_count.htm
- https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_get_description.htm
- https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_is_connected.htm
- https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_set_axis_deadzone.htm

Please come up with new examples for these entries.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Game_Input/GamePad_Input/gamepad_get_device_count.htm

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
