### ISSUE TITLE
In-Game: Specific project fails to run in latest beta IDE v2024.800.0.596  Runtime v2024.800.0.620 but works in June monthly

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#6864]
### Description

When verifying #5853, I noticed that the attached project failed to run in the latest beta. It appears that there are issues within the code in the object's draw event, and can be fixed by replacing the code there. 

This same project runs without the edit in  IDE v2024.6.2.162  Runtime v2024.6.1.208 but not in IDE v2024.800.0.596  Runtime v2024.800.0.620.

[caitlinoutput.txt](https://github.com/user-attachments/files/16374495/caitlinoutput.txt)
[2789a0a2-50d8-4580-a39c-a4d71747d98f.zip](https://github.com/user-attachments/files/16374497/2789a0a2-50d8-4580-a39c-a4d71747d98f.zip)

### Expected Change

Project should run without edit in latest beta as it does in the June monthly

### Steps To Reproduce

1. Start GameMaker in the latest beta and import attached project.
2. Run the game and see that it fails.
3. Go to obj_test's Draw event and replace the code with [5853fix.txt](https://github.com/user-attachments/files/16374671/5853fix.txt).
4. See that the project runs as expected.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2024.800.0.602  Runtime v2024.800.0.624
