### ISSUE TITLE
Bug Reporter: Add warning about mismatched IDE/runtime combinations

### ISSUE THREAD

**Issue by stuckie** [YoYoGames/GameMaker-Bugs#6866]
Due to potential RSS issues (and, more probably, users firewalling GameMaker and so not able to access the RSS feeds at all), there has been a recent rise in redundant/unwanted bug reports where users have mismatched IDEs and runtimes.

Sometimes these runtimes can be years out of date (recent reports have for some reason still been using 2.2.x!), despite the fact that 2024.x IDEs are not meant to show any runtimes in Preferences that are older than 2024.2 or allow their use - and that all of these users _should_ be seeing a warning every IDE startup that they are not on the correct runtime and asking do they want to automatically fix this now, but if GameMaker is firewalled and never able to get the matching runtime this does not happen: 

And on the flip side, we have had recent reports from users trying to use older IDEs (typically Steam Desktop/Web/Mobile users stuck on 2023.11.1 because they have not read the release notes) with the latest runtimes. Note that this scenario would not trigger any warnings inside the IDE.

This rise in users reporting problems with their setups has also been noticed on the GMC: https://forum.gamemaker.io/index.php?threads/important-getting-type-tag-missing-errors-dont-mix-2024-ides-and-runtimes-with-other-versions.114332/

### Expected Change

We should have the bug reporter check before displaying the bug reporter dialog if the runtime matches what the IDE expects and warn users that any bugs may be because their runtime and IDE are not the expected combination, and that the install should be set to use the correct values first and then they need to confirm the issue still exists before they send the report.

The warning should contain a button to open Preferences > Runtime Feeds > Master, along with some text about if the correct runtime cannot be seen, then the user should check the permissions guide and ensure they are not firewalling GameMaker.

If this discrepancy is more than one major version in difference, then _additionally_ the bug reporter should not open and no report should be allowed to be sent. 

E.g...

2024.8.0 IDE:
- Warn first, but allow to send a report if using any 2024.6 runtime
- Warn first, but allow to send a report if using any 2024.10 runtime
- Warn and block the bug reporter from opening if using any runtime from 2024.4 or older
- Warn and block the bug reporter from opening if using any runtime from 2024.11 or newer
- No warning if using any 2024.8 runtime

_This would also have the additional benefit of blocking reports from users trying to force Beta runtimes with Monthly/LTS IDEs, etc._

**Comment by YYDan** [comment]
```
Your {0} IDE and currently-active runtime {1} are from very different GameMaker releases, so this alone may be the cause of your issue.

(This IDE expects runtime {2}, but any newer {3} runtime will do.)

Please ensure the first two parts of your IDE and runtime versions match and then confirm the issue still occurs before you report any bugs.

If this IDE and runtime are also not the current releases, we do recommend updating your GameMaker install, as the issue may also have been fixed already.
```

Where 0 is the current IDE version number (the one showing in the to-right corner of the IDE), 1 is the currently-active runtime version number (the one showing in the top-right corner of the IDE), 2 is the runtime version the IDE looks for in the RSS feed (the one saved to a file on disk and checked during startup), and 3 is just the first two parts of 2.

E.g.

```
Your 2024.6.2.162 IDE and currently-active runtime 2024.2.0.nnn are from very different GameMaker releases, so this alone may be the cause of your issue.

(This IDE expects runtime 2024.6.1.208, but any newer 2024.6 runtime will do.)

Please ensure the first two parts of your IDE and runtime versions match and then confirm the issue still occurs before you report any bugs.

If this IDE and runtime are also not the current releases, we recommend updating your GameMaker install, as the bug may also have been fixed already.
```

**Comment by L-Clouds** [comment]
The bug reporter is certainly NOT where effort should be made to check for this.  If the GameMaker IDE has allowed itself to be configured in a state where an incompatible runtime version is trying to be used, and has actually caused a user issues to the point they'd be trying to report a bug, then GameMaker has already failed the user.

**Comment by stuckie** [comment]
There are legitimate cases where a user can be on an older runtime. While this is a special use-case, this is partly to remind them if they have forgotten they had set an older runtime.
We are also looking into why the runtime and IDE has started to get out of sync so easily for ordinary users separately.

**Comment by YYDan** [comment]
Working fine in Beta IDE v2024.800.0.618 with a variety of 800/600/400 runtimes to see the three different outcomes detailed here.
