### ISSUE TITLE
GMRT: Cannot compile any project with a tileset

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6867]
### Description
Having a project with a tileset makes GMRT not compile.

### Steps To Reproduce
Create a tileset and then try to compile in GMRT.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a253065d-bf15-4976-8243-09e0772824ed](https://api.gamemaker.io/api/github/downloads/a253065d-bf15-4976-8243-09e0772824ed)

**Comment by LukeBrownYoYoGames** [comment]
This should now be fixed in GMRT milestone 0.12.0

**Comment by LukeBrownYoYoGames** [comment]
Also, for some reason this project had a tileset with no sprite associated. I fixed GMRT to handle that but im not entirely sure if that was intentional
