### ISSUE TITLE
Manual Content: Add hint onto Windows's Game Options - Images page that icon is only shown when Create Exe

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#6870]
### Description

The section "Images" in the "Windows Game Options" page explains the use of an icon for the game as well as the splash screen.

I suggest to add a sentence like the following to make it clear when and where the icon is displayed:

The icon will be shown in the title bar of the window when the game is displayed in windowed mode. Note, that the icon isn't displayed when testing the game but only when the game has been built and has been started from the executable.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=Settings%2FGame_Options%2FWindows.htm&rhsearch=windows&rhhlterm=windows

**Comment by alicemoretti** [comment]
Verified that the information has been added to the page about Game Options for Windows in the newest Beta Manual. 
Thank you.
