### ISSUE TITLE
CE1 Parser: Unexpected error message still shown in 2024.800 Betas when using more than 16 named arguments

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#6873]
### Description
Newest beta does seem to have the argument limit fixed, which is this ticket here https://github.com/YoYoGames/GameMaker-Bugs/issues/6473 but feather still thinks its illegal, shows a red bar in the script, and won't color variables properly.
![image](https://github.com/user-attachments/assets/0e99b10d-e7cc-4303-8223-4722ee2d8025)

Projects run normally. Included project shows this issue. Please ignore the project name as it was also used for a GMRT bug report.

### Steps To Reproduce
- Make a function with over 16 arguments
- Script will show a red bar at the bottom and won't color variables correctly
- Call the function in-game; it should work properly

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[a02b4fb9-3776-4939-8753-7111ff69e70b](https://api.gamemaker.io/api/github/downloads/a02b4fb9-3776-4939-8753-7111ff69e70b)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.599  Runtime v2024.800.0.622
