### ISSUE TITLE
GMRT: Warnings about deprecated things in output even when compiling empty project

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6875]
### Description
When running any project, even an empty one, I get these warnings in output:
```
Warning: SetDeviceLostCallback is deprecated. Pass the callback in the device descriptor instead.
Warning: SetUncapturedErrorCallback is deprecated. Pass the callback in the device descriptor instead.
Warning: The explicit creation of a SwapChain object is deprecated and should be replaced by Surface configuration.
Warning: Old MapAsync APIs are deprecated. If using C please pass a CallbackInfo struct that has two userdatas. Otherwise, if using C++, please use templated helpers.
```

### Steps To Reproduce
Run an empty project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[de4f6da3-cc98-4607-8d88-fd44e7508664](https://api.gamemaker.io/api/github/downloads/de4f6da3-cc98-4607-8d88-fd44e7508664)

**Comment by JonnoRobson** [comment]
I've updated our WebGPU API usage in these cases, plus when using `MapAsync ` to read the contents of a texture on the CPU, to fix the warnings coming in from depreciated functions. There may be other cases where we're still producing similar warnings but for now there are no warnings produced by an empty GMRT project.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.719  Runtime v2024.1300.0.731 using v15.7
