### ISSUE TITLE
GMRT: Project with only an empty room and two sprites silent crashes on launch

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6876]
### Description
Deleting one or the other of the sprites makes it no longer crash. If I delete the two sprites and create two new sprites and import the same images, it doesn't crash. Somehow this specific combo of two sprites is cursed. Importing them into a fresh project via a local package still crashes, I've attached the package along with the project.

### Steps To Reproduce
Download the sample project and run it with GMRT or GMRT VM. The game will compile and a window will pop up, but then will silent crash after a couple seconds.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files:
PackageOfDoom.yymps

[4129661b-4742-489c-b6e5-1287cf8b061d](https://api.gamemaker.io/api/github/downloads/4129661b-4742-489c-b6e5-1287cf8b061d)

**Comment by LukeBrownYoYoGames** [comment]
Seems as though its failing because the sprites are supposedly spine animations with no skeletons. Will investigate further

**Comment by KormexGit** [comment]
I thought it might be spine related, but what's confusing is the red arrow sprite isn't a spine sprite and deleting it stops it from crashing, with the spine sprite untouched. The spine sprite does definitely have a skeleton, so if it's showing up as not having one then something's weird there

**Comment by LukeBrownYoYoGames** [comment]
Additional files in https://github.com/YoYoGames/GameMaker-Bugs/issues/6900

**Comment by LukeBrownYoYoGames** [comment]
This was actually a bit more of a subtle issue and was down to wad alignment. We were writing the spine data with a specific alignment which wasn't being honoured when reading back the data, meaning no spine data was being loaded since it didnt not know what version of spine data was being used.

This should be fixed in 0.12.0
