### ISSUE TITLE
Code Editor 2: Match 3 Template does not trigger Diagnostics correctly during loading the project

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6881]
### Description
like tilte say

### Steps To Reproduce
1) Open the Match 3 template is not working

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[651a1310-e362-49e6-9546-e5411f9c605c](https://api.gamemaker.io/api/github/downloads/651a1310-e362-49e6-9546-e5411f9c605c)

**Comment by zreedy** [comment]
Appears fixed now.

**Comment by scott-dunbar** [comment]
Unable to reproduce in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664

Closing as fixed
