### ISSUE TITLE
Code Editor 2: Deleting a tab will incorrectly move the caret 1 line up

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#6885]
### Description
like test say see video.

### Steps To Reproduce
1) Open attached project
2) Open __GameMedia line 25

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files:
GameMaker-Beta_QjWC13IQQ1.mp4

[2b8e7abd-0711-43b0-8181-97b77cdc44a7](https://api.gamemaker.io/api/github/downloads/2b8e7abd-0711-43b0-8181-97b77cdc44a7)

**Comment by zreedy** [comment]
To clarify, this is intended and expected behavior.
However, Preferences to toggle this behavior have been added for those who wish to disable it:
 - Insert separating whitespace when joining lines
 - Trim leading whitespace on backspace

**Comment by Emc1923** [comment]
Verified preferences added in  IDE v2024.1000.0.621  Runtime v2024.1000.0.647
