### ISSUE TITLE
Package Manager: Menu item becomes disabled on closing a project and returning to the Start Page

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#6898]
### Description

When in the start page, if the user attempts to open the package manager from 'Tools', the option is greyed out and unselectable. This means that the package manager can only be opened within a project. This was found in IDE v2024.800.0.597  Runtime v2024.800.0.620.

### Expected Change

It is expected that the package manager should be accessible from the start page

### Steps To Reproduce

1. Start GameMaker and reach the Start Page normally
2. Tools > observe the Package Manager entry is enabled
3. Open a Project
4. Tools > observe the Package Manager entry is still enabled
5. Click the Home button on the toolbar and close your project, so that you're back on the Start Page
6. Tools > observe the Package Manager entry is now disabled
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by LukeBrownYoYoGames** [comment]
I'm also having issues reproducing this on 2024.800.0.597
It could be a license issue, but as far as I can tell this should be updating properly as the license is updated

**Comment by LukeBrownYoYoGames** [comment]
Ah, I think I might have found a valid repro for it:

* Start GameMaker
* Open a Project
* Select 'Tools'
* See that the package manager is NOT greyed out
* Go Back to Main Page
* Select 'Tools'
* See the issue

**Comment by YYDan** [comment]
Confirmed Luke's steps above. Updated the title and original repro steps.

**Comment by LukeBrownYoYoGames** [comment]
Issue should now be fixed in 89d10a6526193b74bd97f0ed41ac5adad2a210c8
Note: This was unrelated to feature flags for the package manager but we do want to remove those. the feature flag for the package manager will be removed in a later change

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.603  Runtime v2024.800.0.625
