### ISSUE TITLE
Building Projects: [HTML5] Builds fail in 800 Betas due to comma missing before TPageEntries

### ISSUE THREAD

**Issue by pkraif** [YoYoGames/GameMaker-Bugs#6902]
### Description

Asset compiler seems to generate invalid WAD (JSON) for some HTML5 projects - there's a missing comma before `TPageEntries`, which causes the game not start. I've encountered this issue while fixing this bug: https://github.com/YoYoGames/GameMaker-Bugs/issues/6738. Please download the sample project attached there.

### Expected Change

Fixed in asset compiler

### Steps To Reproduce

1. Start GameMaker
2. Open given project
3. Run in HTML5
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by pkraif** [comment]
I'm testing this again in Beta IDE v2024.800.0.597  Runtime v2024.800.0.624 and the fix works! Only if you run the project from the IDE it gives you errors because it needs the modified index.html file to run properly, but that's not related to the issue. It can be also easily worked around by commenting out all calls to `jsExecute()` from the project 👍

**Comment by mgeddesGM** [comment]
verified as per developers comment
