### ISSUE TITLE
Bugs Repo: Give some sort of way for the community to mark older bugs/feature requests that are duplicates or already resolved

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6907]
### Is your feature request related to a problem?

If a new issue is made that is either a duplicate or something that's already fixed/added, we can leave a comment that gets seen during triage. However, there are thousands of older reports that don't get looked at very often, and going through them all is a big task. If it were possible for anyone looking at older reports to somehow inform you guys if there's a duplicate or already resolved issue, then we could help with clearing out some of the extra issues clogging things up.
I've tried leaving comments on them before, but since the tickets are already out of triage and often not assigned to anyone, the comments don't get seen.

### Describe the solution you'd like

Give some sort of way for community members to flag an older ticket as a duplicate or already resolved, so it can be reviewed and then closed. I'm not sure what the best way would be, since I don't know how things are usually handled internally. 

### Describe alternatives you've considered

Keep leaving comments and they'll get seen eventually I guess

**Comment by stuckie** [comment]
This would need support in GitHub to do something - perhaps a feature request for them?
Beyond that, a comment and we'll see it at some point.

Thanks.

**Comment by YYDan** [comment]
As long as your comment contains "duplicate of", then we can easily search for all reports that are open but that also contain that comment.

Thanks again,

**Comment by KormexGit** [comment]
Is there some specific phrase like "duplicate of" that could be used for tickets for things that already got fixed or added?

**Comment by iampremo** [comment]
Added a trail of using `/duplicate` at the start of a comment that will add a label and flag it for internal review
