### ISSUE TITLE
In-Game: [GMRT] Camera zoom makes the parallax background disappear

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#6925]
### Description
When the camera zooms in during cutscenes in my game, the backgrounds disappear. It looks almost as if they get squished to the side. My hunch is that some internal 3D maths have been changed.

For the camera zoom I use camera_set_view_size.

### Steps To Reproduce
Possible to reproduce with the privately shared project from a while ago.

New Game -> Start from the beginning

The opening cutscene is missing the background and it comes back in after the zoom.

A second time you can watch it disappear if from the starting room you go: Left and then left again using the room exit just to the left of where you enter the room. A second cutscene will start shortly after you enter that room.

Camera code is in the End Step of obj_camera

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[60a64660-d9fc-4761-ad9e-4ab375be253a](https://api.gamemaker.io/api/github/downloads/60a64660-d9fc-4761-ad9e-4ab375be253a)

**Comment by LukeBrownYoYoGames** [comment]
There doesnt seem to be a project attached to this issue. Please resubmit a ticket with the full project if possible or a small example case

**Comment by nullbunny** [comment]
@LukeBrownYoYoGames Hiya! Thanks for checking out my ticket. As written in the description, the project has been shared privately before. Can you ask your colleagues for the private project submitted by me? Thanks!
