### ISSUE TITLE
Code editor 2: Argument tooltip does not appear for constructors

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6927]
### Description
When calling constructors, there is no argument tooltip at all. You cannot even make it appear manually with ctrl + space.

https://github.com/user-attachments/assets/3824add0-fadd-42ab-a6f1-105d43aaadb8

### Steps To Reproduce
Make a constructor with arguments, and then type it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[9a17e840-23df-4d24-8f2d-41704287c0a1](https://api.gamemaker.io/api/github/downloads/9a17e840-23df-4d24-8f2d-41704287c0a1)

**Comment by zreedy** [comment]
Fixed
