### ISSUE TITLE
Code editor 2: Jumping to a global search result with "Find Previous" or "Find Next" will not jump to the searched item if a new document is opened in the process

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6931]
### Description

When doing a global search with ctrl + shift + f, double clicking on a result in the search results window will take you right to the thing you searched for. However, if you instead use the "Find Previous" and "Find Next" buttons, clicking them will not take you to the searched code if it has to open a new script/object tab. Instead, the new tab will be opened and it will leave you at the top. If the relevant script/object is already open, it will take you to the correct line as expected.

https://github.com/user-attachments/assets/968b301f-d405-43e4-94a7-c91f5b63bfe3

For comparison, it does work on first try when double clicking search results:

https://github.com/user-attachments/assets/d89bb5cd-37b6-432a-82ad-a9d63b959b43

### Expected Change

Using the find next and find previous buttons should jump to the proper line on first click.

### Steps To Reproduce

Using ctrl + shift + f, search for something that is not in any currently open documents (or close all tabs first). Hitting find next or find previous will open the document the thing you searched for is in, but not jump to the line.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1000.0.621  Runtime v2024.1000.0.647.
