### ISSUE TITLE
variable_clone() doc omits that cloned methods are bound to "undefined"

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6936]
### Description

Using `variable_clone()` to clone a method, eg:
```gml
var _function = function(){}
var _clone = variable_clone(_function, 1)
return method_get_self(_clone)
```
will return `undefined`, as opposed to the `self` the function was declared in. I think this is intuitive, but it should be mentioned in the manual.

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Variable_Functions/variable_clone.htm

**Comment by alicemoretti** [comment]
Verified that a note has been added to the newest Beta Manual. Thank you/
