### ISSUE TITLE
method_get_self() returns a number instead of a handle reference

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6937]
### Description

Using `method_get_self()` on a function declared in an object instance will return a number, not a handle reference.

### Steps To Reproduce

(included in sample project) In a new project, make an object, place it in the room, and in a create event write:
```gml
var _method = function() {}
var _self = method_get_self(_method)
show_message(typeof(_self))
```

The message shows the value returned is a number, not a ref.

[BLANK GAME_5.zip](https://github.com/user-attachments/files/16406514/BLANK.GAME_5.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by kat-fl** [comment]
Cannot reproduce this on GMRT. `typeof(_self)` returns `struct` rather than `number`.

**Comment by mgeddesGM** [comment]
@LukeBrownYoYoGames does this pass since gmrt returns a struct and not a number and possibly this is how gmrt works?

**Comment by LukeBrownYoYoGames** [comment]
Yeah, we would expect a struct from this

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1110  Runtime v2026.100.0.1075 gmrt 0.22.31

struct returned on gmrt is as expected
