### ISSUE TITLE
method_get_self() page mentions returning "pointer_null", but it won't 

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6938]
### Description

The page for `method_get_self()` says:
```
Please note that the function may also return the constant pointer_null, in which case the current self is being used at the time of the call.
```
However, I can't produce a single situation where it returns `pointer_null`, no matter how I interpret this sentence. I'm assuming that this section of the manual just no longer applies, rather than it being a larger bug.

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Variable_Functions/method_get_self.htm

**Comment by jackerley** [comment]
I've checked the code and I can confirm this can't happen. The comment should just be removed. @gurpreetsinghmatharoo

**Comment by alicemoretti** [comment]
Verified that the comments has been removed from the Manual in the newest Beta version. Thank you.
