### ISSUE TITLE
Wrong function used in example code for gpu_set_texrepeat_ext

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#6939]
### Description

The manual page for gpu_set_texrepeat_ext() instead has gpu_get_texfilter_ext()/gpu_set_texfilter_ext() in the sample code.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Drawing/GPU_Control/gpu_set_texrepeat_ext.htm

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
