### ISSUE TITLE
Code Editor 2: Selecting an autocomplete entry via mouse makes the caret disappear from the editor

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6941]
### Description
If you click an autocomplete option instead of using the arrow keys +  enter, the text cursor will disappear, and you can't type anything else until you manually click somewhere to being the cursor back.

https://github.com/user-attachments/assets/1ac56e69-8595-4f6b-b112-9fc95b0361b2

### Steps To Reproduce
Type a letter and then click on something in autocomplete. The text cursor will vanish and you'll be unable to type anything until clicking somewhere in the document again.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[da88cd02-574f-46e8-a3eb-d30ce88c93bd](https://api.gamemaker.io/api/github/downloads/da88cd02-574f-46e8-a3eb-d30ce88c93bd)

**Comment by YYDan** [comment]
Confirmed a few Beta IDE versions between IDE v2024.1100.0.675 / IDE v2024.1100.0.693 and yes, all seems fixed already, so have fixed the resolution and added the milestone.
