### ISSUE TITLE
GMRT: room_get_info() hasn't been added yet 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6943]
### Description

room_get_info is a very handy function that doesn't exist in GMRT yet

### Expected Change

Add room_get_info

### Steps To Reproduce

Try to use room_get_info in GMRT

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by LukeBrownYoYoGames** [comment]
Closing this as room_get_info is now added
