### ISSUE TITLE
`mask_index` cannot be changed after game starts

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6945]
### Description

In 0.11, after game starts, `mask_index` cannot be updated (by either changing sprite nor calling mask_index manually). One that was set when game was build remains forever.

Example:
[gmrt_mask_index.yyz.zip](https://github.com/user-attachments/files/16368452/gmrt_mask_index.yyz.zip)

### Steps To Reproduce

1. Start GameMaker
2. Create object with no sprite
3. Assign sprite in GML using `sprite_index = Sprite1` in Create event
4. Check for collisions in game, and they won't work

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in 13.8
