### ISSUE TITLE
In-Game: `other` used to obtain caller ignores calling struct and points to calling object/`global`

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6946]
### Steps To Reproduce

See project:
[other-points-to-owner-object-not-constructor.zip](https://github.com/user-attachments/files/16368310/other-points-to-owner-object-not-constructor.zip)

...Or the same code sample from the script:
```gml

function Owner() constructor {
	owned = new Owned();
}

function Owned() constructor {
	owner = other;
}

var owner = new Owner();

show_message(owner.owned.owner);

```

In the current runtime, you see this:
![image](https://github.com/user-attachments/assets/f3abe1eb-9fb3-4009-a6a0-182dc3cb3f5b)

In GMRT:
![image](https://github.com/user-attachments/assets/02c69de5-e724-44fe-9032-ab2f433ff0d7)

[Collage](https://github.com/tabularelf/Collage) relies on the current behaviour to implicitly set the owner for an owned "batching/builder" struct, owned by an image page, which is how I found this.

### How reliably can you recreate this issue using your steps above?

Always

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by mgeddesGM** [comment]
verified in  IDE v2024.1300.0.719  Runtime v2024.1300.0.731 using v15.7
