### ISSUE TITLE
In-Game: some special combination of using `struct_get_names` in weird conditions causes `"string too long"`

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6947]
### Description

I'd intended to report this one many months ago but it kept slipping through as I didn't have the energy to track it down further, as there would always be other issues blocking it first.

Anyway, for some reason, something about these lines in my project crash on both Native and Interpreter:
![image](https://github.com/user-attachments/assets/261b73f6-860e-46c3-86df-d5423870a083)
![image](https://github.com/user-attachments/assets/71c3a786-77a2-4acc-9fac-bed7f736e7b6)

### Steps To Reproduce

1. Boot my [attached project](https://github.com/user-attachments/files/16368181/slimy.zip) - this is an earlier build of my main project as I couldn't reproduce it elsewhere.
2. See error.

The line causing the crash is some combination of lines 54 and 56 of `oGame`'s `Create` event.
`struct_get_names(addonManager.failed_addons)` doesn't seem to be relevant - I think it's something up with `string_join_ext`.

### How reliably can you recreate this issue using your steps above?

Always

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1300.0.719  Runtime v2024.1300.0.731 using GMRTv15.7
