### ISSUE TITLE
In-Game: Attached project shows corrupted textures

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#6958]
### Description

Split from https://github.com/GMExternal/NewRuntimeBeta/issues/117

The attached project will not show the correct textures

Incorrect:
![image](https://github.com/GMExternal/NewRuntimeBeta/assets/48513045/49e51dd9-a872-4a07-a31f-82960da2a3cd)

Correct:
![image](https://github.com/GMExternal/NewRuntimeBeta/assets/48513045/c16e8c8b-bfb3-4407-a9a4-2dea92353c14)

Project
[works.donut.zip](https://github.com/user-attachments/files/15902509/works.donut.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import project
3. Run project 
4. See the issue

### How reliably can you recreate this issue using your steps above?

None

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by JonnoRobson** [comment]
The GMRT asset compiler was not correctly setting up the repeating border around individual sprites in a texture page. The sprites would always be surrounded by a black, zero alpha border. I've added a fix for this behaviour so the borders around sprites in a texture page should match with a texture page output by the GMS2 asset compiler. This fixes the the rendering issues in the project mentioned in [this issue](https://github.com/YoYoGames/GMRT-Beta/issues/117).
