### ISSUE TITLE
surface_save doesn't work all the way and cannot handle surface sizes that are not multiple of 256

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#6963]
### Description

right now there is no way to save surfaces in gmrt, sprite_save is unimplemented and surface_save has some problemos:
- big one is that if you try to surface_save a surface whose size is not a multiple of 256x256, you get this in the output:
```
[VALIDATION ERROR][CopyTextureToBuffer]: bytesPerRow (128) is not a multiple of 256.
 - While encoding [CommandEncoder].CopyTextureToBuffer([Texture], [Buffer], [Extent3D width:32, height:32, depthOrArrayLayers:1]).
```
- next big one is that if you do use a multiple of 256, it doesnt actually save anything

i attached a project; if you comment out the code in the object's draw event labeled A you will get the 256 error. if you comment out section B you will get no saved surface.

[BLANK GAME_10.zip](https://github.com/GMExternal/NewRuntimeBeta/files/15359637/BLANK.GAME_10.zip)

**Comment by pkraif** [comment]
Textures with `bytesPerRow` not aligned to 256 do work now in `develop`, but the project attached still doesn't work properly - pixels drawn into the 256x256 surface aren't visible in the first frame (and become visible since the second frame). We need to investigate this.

**Comment by mgeddesGM** [comment]
IDE v2026.100.0.1151  Runtime v2026.100.0.1101 gmrt 0.22.77
