### ISSUE TITLE
In-Game: Windy Woods template shows graphical artefact at top of screen

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#6974]
### Description

On the windy woods template, there is a graphical artefact at the top of the screen

The bottom is GMRT 
![image](https://github.com/GMExternal/NewRuntimeBeta/assets/48513045/a6bab393-3a9f-4140-a69f-7861270de7b9)

Tested with package 0.7.2

### Steps To Reproduce

1. Start GameMaker
2.  Import the Platformer Template
3. Run for GMRT
4. See the issue at top of screen

### How reliably can you recreate this issue using your steps above?

Always

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by pkraif** [comment]
Fixed in https://github.com/YoYoGames/GMRT/pull/1850
