### ISSUE TITLE
display_reset() does not work

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#6977]
### Description

![image](https://github.com/GMExternal/NewRuntimeBeta/assets/30154346/0f879a31-7002-4136-a332-b99fe0044f8b)

### How reliably can you recreate this issue using your steps above?

None

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by pkraif** [comment]
Did some investigation and multisample count 2 is not supported by WebGPU: https://www.w3.org/TR/webgpu/#dom-gpumultisamplestate-count. Possible values are 1 or 4. But either way, we're not taking sampleCount properly into account, so even using 4 causes errors.
