### ISSUE TITLE
Custom vertex format seems to fail

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Bugs#6983]
### Description

real simple project to look at; i was testing a custom vertex format that does a bilinear interpolation of colors on rectangles. when submitting the vertex buffer with a custom vertex format the log fills up with a invalid buffer error and nothing draws

[we got a problem bubs.zip](https://github.com/GMExternal/NewRuntimeBeta/files/14425708/we.got.a.problem.bubs.zip)

### Steps To Reproduce

1. Start GameMaker
2. make a very fancy custom vertex format
3. try to make a game with it
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description), Other Release (Please put the exact version number in your Description)

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1112  Runtime v2026.100.0.1076 gmrt 0.
