### ISSUE TITLE
Android API 34 support on LTS

### ISSUE THREAD

**Issue by brankoblazevic** [YoYoGames/GameMaker-Bugs#7002]
### Is your feature request related to a problem?

Yes, the current LTS version of Game Maker does not support Android API 34, which limits compatibility with newer devices and features.

### Describe the solution you'd like

I would like the LTS version of Game Maker to include support for Android API 34, allowing developers to use the latest Android features and ensure compatibility with new devices.

**Comment by L-Clouds** [comment]
It was [mentioned in the GMC forum thread](https://forum.gamemaker.io/index.php?threads/2022-0-2-lts-release-thread.106465/post-679577) that Google's deadline for this is August 31, 2024.

**Comment by Emc1923** [comment]
Verified in LTS IDE v2022.0.3.64  Runtime v2022.0.3.76
