### ISSUE TITLE
Code Editor 2: Backspace doesn't work in CE2 New theme name dialogue

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7004]
### Description

When making a new theme for Code Editor 2 by going to File>Preferences>Code Editor 2>Theme, pressing the "New..." button, then "from Copy of Selected", it will bring up a dialogue box prompting the user to name the new theme. While inputting text into this dialogue box, backspace does nothing.

![image](https://github.com/user-attachments/assets/c490d2dc-bd0e-4f10-8fc5-271c1688f257)
![image](https://github.com/user-attachments/assets/981c995b-9afa-4601-bed6-7227854fe458)

[Contact Us Package.zip](https://github.com/user-attachments/files/16424674/Contact.Us.Package.zip)

### Expected Change

Backspace should be usable in the CE2 New theme name dialogue.

### Steps To Reproduce

1. Start GameMaker
2. Go to File>Preferences>Code Editor 2>Theme
3. press the  "New..." button next to the theme selection dropdown menu
4. Select "from Copy of Selected" in the dropdown menu that appears after pressing the button
5. In the dialogue box that appears, click on the right hand side of the text in the box and press backspace to try to remove some characters
6. Observe the lack of change to the text

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.661  Runtime v2024.1100.0.687
