### ISSUE TITLE
Preferences: Show the expected runtime for this IDE on the Runtime Feeds page

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#7008]
### Is your feature request related to a problem?

We should show the expected runtime for this IDE on the Runtime Feeds page, so that it's very easy to know which runtime is the one that this IDE expects to be installed.

This will help communicate when someone is on the wrong version, and so issues may arise from mismatched tools, but it also helps clarify which runtime the IDE is going to reinstall on startup if it detects there is a problem with the installation.

### Describe the solution you'd like

We add a bit of blank space in between the current runtime install info and the table below it, and then add an "Expected Runtime: _number_" line there.

![image](https://github.com/user-attachments/assets/88fb8c84-849e-494f-9b27-de30e8103fed)

Ideally/as a stretch goal, the version could also be highlighted in some way in the table, so it's easier to identify when scrolling or managing your runtimes.

**Comment by scott-dunbar** [comment]
Issue found https://github.com/YoYoGames/YoYoStudio/issues/10610

**Comment by scott-dunbar** [comment]
Though issue found closing this ticket as the feature is present
