### ISSUE TITLE
A AI Tool that analyzes our projects (.yyg, .yy, .gml) to help us

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#7019]
### Is your feature request related to a problem?

It would be better and faster if I would have an AI, which helps me with basic tasks, which are specific to my project.

### Describe the solution you'd like

This tool should understand our projects and help us:

It could help us with:

- questions we have about our own project
- visualize inheritances
- visualize references
- refactoring

It could be a better CTRL+F...

I guess you understand what I mean.

**Comment by L-Clouds** [comment]
Duplicate of #3175

**Comment by YYDan** [comment]
(As you knew already, as you have commented _on_ that other issue in the past ;) )
