### ISSUE TITLE
`window_has_focus` misreports on MacOS

### ISSUE THREAD

**Issue by offalynne** [YoYoGames/GameMaker-Bugs#7020]
### Description

`window_has_focus()` always returns `true` on MacOS

Per https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Cameras_And_Display/The_Game_Window/window_has_focus.htm

> This function is only valid for the (sic) HTML5, Windows, and **_MacOS_**

### Expected Change

`window_has_focus()` returns windows focus state

### Steps To Reproduce

1. Start GameMaker
2. Print `window_has_focus()`
3. Focus/unfocus app
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by offalynne** [comment]
cc @tthrelfo

**Comment by yoyo-danielc** [comment]
Fixed in 2024.10 branch.

**Comment by YYDan** [comment]
I do note that Ubuntu is not part of that fix, so we should check whether an identical report should now be filed for that OS also ;)

**Comment by Emc1923** [comment]
Verified fixed on mac as of Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652.
