### ISSUE TITLE
In-Game: [HTML5] Failed requests for streamed sounds will cause games to crash

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7024]
### Description
Note: This is already fixed.

Requests for streamed sounds which fail in some way will crash the game as the response does not contain audio data that can be decoded. We should fail more gracefully if we run into this situation.

Raised while looking at https://github.com/YoYoGames/GameMaker-Bugs/issues/6904.

### Steps To Reproduce
- Open and run the example project. Don't interact with it just yet.
- Go into the game folder (e.g. `C:\Users\fujj\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\gmb-6904-x_53F61E2E_Javascript`) and delete `GameDir/snd_1.ogg`.
- Back in the browser, open the console and then follow the instructions on screen.
- The game will crash - note the 404 error in the console.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.598 Runtime v2024.800.0.621

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[bc2ce07d-eebc-415e-a7df-3490b50e0b9c](https://api.gamemaker.io/api/github/downloads/bc2ce07d-eebc-415e-a7df-3490b50e0b9c)

**Comment by toby-yoyo** [comment]
Added a check of the status for completed audio stream requests. If a stream fails to be retrieved then we will simply stop the voice that was assigned to play it and print a message in the console to complement the request failure message that the browser should have already printed (as below):

![image](https://github.com/user-attachments/assets/2489b5f9-a302-4d86-8099-259b4ad7ceb0)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.603  Runtime v2024.800.0.625
