### ISSUE TITLE
In-Game: audio_is_playing() will return 'true' for compressed sounds which were stopped by audio_stop_sound()

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7026]
### Description
If a compressed sound is explicitly stopped using `audio_stop_sound`, then `audio_is_playing` will appear to return `false` for a very short time until it begins to return `true` once again.

### Steps To Reproduce
- Open and run the example project.
- A sound will play for 2 seconds.
- Observe that the on-screen text does will state 'Audio is playing', even after the audio has finished playing.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.598 Runtime v2024.800.0.621

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[3a63b884-78c2-4c64-948d-3630d88ffe9a](https://api.gamemaker.io/api/github/downloads/3a63b884-78c2-4c64-948d-3630d88ffe9a)

**Comment by toby-yoyo** [comment]
Fixed an issue where terminated ogg voices were not notifying of their readiness to be deactivated.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.604  Runtime v2024.800.0.627
