### ISSUE TITLE
Manual Content: "visible" page should state that the variable is read-only during Draw-type events

### ISSUE THREAD

**Issue by dicksonlaw583** [YoYoGames/GameMaker-Bugs#7032]
### Description

This issue originated in a GMC thread: [Pop :: Execution Error - Variable set failed visible - read only variable?](https://forum.gamemaker.io/index.php?threads/pop-execution-error-variable-set-failed-visible-read-only-variable.113426/)

It is reasonable for `visible` to be read-only in Draw-type events (since it determines whether those events should run in the first place), but this behaviour should be documented.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Instances/Instance_Variables/visible.htm

**Comment by alicemoretti** [comment]
Verified a note has been added to the manual page in the newest Beta Manual. Thank you.
