### ISSUE TITLE
[iOS] video is paused after going to iOS home or another app

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7035]
### Description
The sample project plays a video, and the video is paused when going to the iOS home or another app and then coming back to the game.

When testing against older runtimes, we see that:
1. For beta runtime 2024.400.0.571, the video correctly resumes
2. For beta runtime 2024.600.0.607, the video also pauses, but it shows the following output message:
```
Session interrupted > --- Begin Interruption ---
Suspending Audio...
Audio Suspended
AudioPauseAll
Pause event has been registered for this frame
Pause event has been unregistered
Session interrupted > --- End Interruption ---
AudioResumeAll
```
3. For the current beta runtime 2024.800.0.620, the logs above are not shown

### Steps To Reproduce
1. Run the project for iOS VM export
2. See that the app launches and starts playing a video
3. Go to the iOS home or another app and come back to the game
4. See the video is paused

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
iOS

### Attached Files:
runtime_607.log

[2ac5d021-bb70-4754-9333-8d0882ad5a9a](https://api.gamemaker.io/api/github/downloads/2ac5d021-bb70-4754-9333-8d0882ad5a9a)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1100.0.681  Runtime v2024.1100.0.703.

Thank you.
