### ISSUE TITLE
Sprite Editor: GM unstable when moving multiple frames at once in the preview bar

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7041]
### Description
Selecting and moving multiple frames in a sprite at once causes a "GameMaker has become unstable" popup, and also creates weird non-existent frames in the middle of the sprite.

https://github.com/user-attachments/assets/2276276f-e912-4c07-aea1-a912092d94dd

### Steps To Reproduce
Create a new sprite. Add some frames to it. Go back to the workspace sprite editor. Select multiple frames with shift click, then drag them past the last frames of the animation.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.597 Runtime v2024.800.0.620

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[fc0f5c3c-d48c-4c93-b076-5f1fc913779f](https://api.gamemaker.io/api/github/downloads/fc0f5c3c-d48c-4c93-b076-5f1fc913779f)

**Comment by YYDan** [comment]
Works fine in IDE v2024.800.0.611  Runtime v2024.800.0.635 now - you're no longer able to drag the frames out to create the extra gaps (and also the selection boxes are much more reliable now, as in that earlier version it looked like your selection was changed as you dragged). I have not been able to recreate the instability either.

**Comment by alicemoretti** [comment]
Verified picked to LTS on both Windows and mac on IDE v2022.0.3.74  Runtime v2022.0.3.85
