### ISSUE TITLE
Importing an Extension just doesn't work in my case.

### ISSUE THREAD

**Issue by IceCapZone** [YoYoGames/GameMaker-Bugs#7042]
### Which Extension are you reporting this issue for?

App Tracking Transparency

### Description

![errormsg](https://github.com/user-attachments/assets/761b2753-9afd-41b3-ad67-4f8f53a53d40)
I'd like to report an issue to Gamemaker Studio 2's Latest version.

I've tried to import an asset extension (Local Package) called xProcess, but to no success. I don't know if anybody is experiencing the same issue as me?
I discussed this with the creator of the extension, and it's not the extensions fault. This is a pretty much a major bug asset wise, considering if anybody can't import any assets (Local Packages) in this version, it's pretty bad.

I'm sorry if I made it seem like a joke.
[importing bug.zip](https://github.com/user-attachments/files/16449347/importing.bug.zip)

### Expected Change

I expect to import assets (Local Packages) without any errors.

### Steps To Reproduce

1. Start GameMaker
2. Open a folder with the extension
3. Attempt to import it to GameMaker.
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
From the ui.log, I can see that your IDE and runtime versions do not match. Please first of all update your GameMaker install fully and then review [the permissions guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) (which you can always find on the Help menu inside GameMaker and on the release notes page). This should solve your issue right away.
Please do always check that you have updated both parts and reviewed that guide every time you change your GameMaker version - at least, if you get any problems building your projects after updating GameMaker this should be the first thing you do.
(If updating and reviewing the guide does not fix this, please file a new bug report and ensure you allow GameMaker to include your currently-open project that's still showing the problem at that time, and we will of course see if something extra is going on.)
