### ISSUE TITLE
Remove the now redundant "Generate mipmaps for separate texture pages" Game Option

### ISSUE THREAD

**Issue by JonnoRobson** [YoYoGames/GameMaker-Bugs#7045]
### Is your feature request related to a problem?

Within "Game Options > Main Options > General" there is a checkbox for "Generate mipmaps for separate texture pages". This option was added in the past when sprites with the option "Separate Texture Page" checked were not considered part of a specific texture group. The option previously allowed users to enable mipmaps on sprites with the option enabled as otherwise only parent texture groups could have mipmaps enabled. 

In more recent versions of GameMaker sprites with "Separate Texture Page" enabled are now still assigned to a specific texture group and so can inherit the mipmap settings of their parent texture group. This means that the Game Option in question is no longer necessary. In fact the option no longer actually has any effect whatsoever - sprites with "Separate Texture Page" enabled will use their parent texture group's mipmap settings regardless of whether or not the option is enabled. To avoid future confusion the option should be removed from the Game Options.

### Describe the solution you'd like

The option "Generate mipmaps for separate texture pages" should be removed from "Game Options > Main Options > General". The description of the option should also be removed from the manual (https://manual.gamemaker.io/monthly/en/#t=Settings%2FGame_Options.htm) to avoid referring to removed features.

**Comment by JonnoRobson** [comment]
The checkbox option for "Generate mipmaps for separate texture pages" has now been removed from the editor. The underlying data member still exists for project compatibility but is no longer connected to any other code and so should not have any effect on projects.

**Comment by YYBartT** [comment]
Removed the option on the Game Options page and references to it on the Mipmapping and Texture Groups page.

**Comment by sihammill** [comment]
Verified in IDE v2024.1100.0.675  Runtime v2024.1100.0.701
