### ISSUE TITLE
Install: Silent Installation flag does not work for the LTS installer on Windows

### ISSUE THREAD

**Issue by gary-dsb1** [YoYoGames/GameMaker-Bugs#7046]
### Description

When trying to do a silent install of the current monthly gamemaker program, or even the LTS version, it ignores the /s parameter.  I tried several other parameters to see what might work, and nothing works.  When running with any parameter, it still prompts.  I need to install this app silently for several computers in an educational facility for students.  I followed your documentation for silent install to make sure I knew the procedure, but it didn't work.

It isn't necessary to upload a Contact Us package as it has nothing to do with the functionality of the software once installed.  It has to do with installation of the software.

### Expected Change

Silent install functions

### Steps To Reproduce

1. run the following GameMaker-Installer-2022.0.2.51.exe /s 

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Hello - the issue there is you're using lowercase s as the flag. If you change to uppercase S then I have just confirmed this works fine for me.

In a non-elevated CMD window UAC is still triggered and you need to accept the installer being allowed to start, yes. The installer's splash screen still pops up and then fades away with no need to interact, but the installation happens just fine in the background and eventually you get a desktop shortcut for the new LTS install.

I have also confirmed that https://help.gamemaker.io/hc/en-us/articles/12662937120797-GameMaker-Silent-Installation guide already uses capitol S for the flag, so nothing needs to change there.

**Comment by gary-dsb1** [comment]
Hi,

Just tried it a few minutes with some testing before you emailed and realized it is the uppercase “S”.  Thank you for your help and time.


Gary

Gary Belanger
Information Services Technician
Timmins High and Vocational School
451 Theriault Boulevard
PO Bag 2011, Timmins, ON P4N 8B2
(705) 360-1411 ext. 30325
thvs.dsb1.ca<https://thvs.dsb1.ca/> | Facebook<https://www.facebook.com/timminshigh.ca> | Instagram<https://www.instagram.com/timmins_high/>

[A black background with red text  Description automatically generated]

**Comment by YYDan** [comment]
Lovely - thanks for confirming you got it all working.

I did just tweak the guide to say this explicitly anyway, so that should clear it all up now:
![image](https://github.com/user-attachments/assets/2472afaf-3e89-4fdc-bf86-e57aea57414e)

Thanks!

**Comment by L-Clouds** [comment]
> I did just tweak the guide to say this explicitly anyway, so that should clear it all up now:
FYI: the spelling should be "capital" with an "a", not an "o", when referring to letters as opposed to government cities.
