### ISSUE TITLE
Code editor 2: When "Show all documents in single view" is disabled, cannot change the currently viewed event if an object's code tab was already open when the project is loaded

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7062]
### Description
I believe this is new to today's beta. I now can't change the event of any object that already had it's tab open at the time I load the project. Closing the tab and re-opening it fixes the issue, until next project load when it breaks again. It appears having "Show all documents in single view" enabled, and then disabling it will also make all currently open code tabs not able to change event.

### Steps To Reproduce
With "Show all documents in single view" disabled, open up an object with multiple events. Close the project. Open it again. Try to change the selected event on that object.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[098da724-deb1-46b6-a8cf-cb2f751ea8e7](https://api.gamemaker.io/api/github/downloads/098da724-deb1-46b6-a8cf-cb2f751ea8e7)

**Comment by zreedy** [comment]
Unable to reproduce.
