### ISSUE TITLE
YYC only: Silent crash when calling collision_line

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7063]
### Description
There does not appear to be anything special required for the crash, you just call collision_line and the game closes with no error message. It happens no matter what I enter for the arguments.

### Steps To Reproduce
Call collision_line after building with YYC. Or, open the sample project, run the game, and press space.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[e63c969e-4550-4f1e-ab74-a10bc4098767](https://api.gamemaker.io/api/github/downloads/e63c969e-4550-4f1e-ab74-a10bc4098767)

**Comment by cameron-home** [comment]
Verified fixed in YYC in IDE v2024.800.0.605  Runtime v2024.800.0.628
