### ISSUE TITLE
Preferences: Typing in "Paths" values to be folders that do not already exist silently reverts your change when you click Apply

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#7066]
### Description

Typing in "Paths" values to be folders that do not already exist silently reverts your change when you click Apply.

All of these are affected:
![image](https://github.com/user-attachments/assets/b01268a8-93f6-4255-b065-9f3cfa06c64f)

### Expected Change

Previously it would just create the directory when it was needed, but at the very least an error dialog should have been shown after clicking Apply alerting to the revert.

### Steps To Reproduce

1. Start GameMaker
2. Go to Preferences->General Settings->Paths
3. For any/all of the paths shown above, type in a path to a folder which does not already exist - e.g., _c:\thisdirdoesntexist_
4. Hit Apply
5. Observe the path string will be silently reset to what it was set to previously.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6 (Monthly)
2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This was due to verification code being moved elsewhere and an earlier check disallowing the correct creation of the folder.

If an illegal path is sent in that cannot be created, it will still set it back to the default as per previous behaviour.

**Comment by stuckie** [comment]
This was due to verification code being moved elsewhere and an earlier check disallowing the correct creation of the folder.

If an illegal path is sent in that cannot be created, it will still set it back to the default as per previous behaviour.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.800.0.613  Runtime v2024.800.0.636, thanks.
