### ISSUE TITLE
Manual Content: Macros page could use a couple of clarifications to help new users

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#7072]
### Description

Hi. This is a really minor thing in the current documentation I'd like cleaned up. Points not explicitly covered [in the documentation](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Overview/Variables/Constants.htm):

1. Constants defined via **#macro nameOfConstant** statement are _global_ in scope, not local to a script, etc. This is known in the GML community, but not explained in the documentation.

2. Macros may be used _like an invocation of a statement_, but, in certain contexts, cannot be considered to be "true constants", in the sense that when they're done, that operation is finished for all time.

For example:

#macro setUpATextureStage texture_set_stage(textureStageWeWantToWrite,pointerToTexture)

This will set up a _pointer_ to texture_set_stage(textureStageWeWantToWrite,pointerToTexture) but it doesn't ensure this operation is performed, in the context of sending pre-rendering instructions to the GPU, because texture_set_stage() is dealing with volatile VRAM. This is fine, but it's one of the things where "constant" gets a bit tricky. It'd be awfully nice to have a way to permanently set a texture stage for a given shader, btw., so that it's a do-once operation and the shader, when invoked through shader_set(), would automatically perform that operation.

However:

shader_set(sh_ShaderWeWantToRun);
setUpATextureStage; _note it's being used like a statement here_

That works! It's not a documented feature, though. I presume it's functionally identical to getting a pointer to and invoking:

function doMyShaderSetup(){
    texture_set_stage(textureStageWeWantToWrite,pointerToTexture);
}

Anyhow, sorry if this all seems a bit needlessly fussy, but especially the global scope of Constants in general needs to be clarified for most new users. I'm in the process of using macros to set all of the set-once variables for shaders in my game, so they're going straight to the pointers, rather than asking GMS where the pointer is over and over again. 

Figuring out that they can be used like invoking a function was just a happy experiment ;-)

**Comment by tabularelf** [comment]
The link in the issue is incorrect (points to localhost, not online for anyone whose reading)
You can [click here](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Overview/Variables/Constants.htm) instead.

**Comment by mistletoe** [comment]
Oops, sorry! Fixed.

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
