### ISSUE TITLE
I can't install GameMaker

### ISSUE THREAD

**Issue by HappyFace4** [YoYoGames/GameMaker-Bugs#7073]
### Description

I'm trying to install gamemaker in my new PC, but everytime i try this error displays. Idk if it has something to do with drivers
![imagen_2024-08-02_183001630](https://github.com/user-attachments/assets/aaa10fea-d7c7-4ba4-beb0-12e1ad09dfc9)

### Steps To Reproduce

1. Start GameMaker
2. Wait around 10 seconds
3. The error displays

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.
