### ISSUE TITLE
Debugger: Game silently crashes before hitting the first breakpoint if using German locale and running the attached project

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#7080]
### Description
Hey there, 
a bit a tricky one.

**The effect described here does NOT occur in a blank project**, so it must have to do something with deeper inheritence  (I think...)

The project attached is more than an empty test project, but you don't need to investigate all the sources, only the test-objects I prepared for you, that make the effect visible
.
In the attached project, you find this section, I prepared for you, to have something to test.\
![image](https://github.com/user-attachments/assets/ff5754d9-bf50-4aab-a396-4995980a117a)

This is the Create event of `TestObject`, you see the three lines, where I tried to attach a breakpoint - please do the same!\
![image](https://github.com/user-attachments/assets/9dda37f9-e4ea-4799-9b68-bf356ac1bdbb)

Before starting, please verify, that you have these settings for runtime, vm and _configuration_ (`mike`), to have the effect occur:\
![image](https://github.com/user-attachments/assets/c988789a-670d-4093-bde6-a8b201f67724)

Now hit F6 and you will see, that the debugger crashes before reaching the first breakpoint, with the well known message

```
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.6.1.208/windows/x64/Runner.exe exited with non-zero status (-1073741819)
elapsed time 00:00:06.5793138s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.6.1.208/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\mikeb\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 08/03/2024 10:46:49
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.
```

As I said, this does not happen in a blank project, but as I can not even reach the breakpoint in the _first line_ (event_inherited), I can not tell, why it does not work in this project.

Anyways, neither the log nor the Output window give me any information about what's happening, so I hope, you see in the debugger on your side a bit more and can find the reason for the debugger crash and can fix it.

Any solution appreciated, thanks for reading!
Kind regards, Gris

### Steps To Reproduce
* Open attached project
* Open the Create Event of the object shown in the screenshot above
* Set the breakpoints as shown in the picture
* Hit F6
* ... Find out, what's going on ...

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[8ad51864-d9a0-4723-8abb-ae4ef722d9a1](https://api.gamemaker.io/api/github/downloads/8ad51864-d9a0-4723-8abb-ae4ef722d9a1)

**Comment by yyalansavage** [comment]
I cannot seem to reproduce this on IDE v2024.6.2.162  Runtime v2024.6.1.208 , (or on internal beta IDE v2024.800.0.603  Runtime v2024.800.0.625) . Does the issue occur only on debug or on run/F5 also?

**Comment by Grisgram** [comment]
only on debug/F6, when I have breakpoints set as shown above

On your end, the debugger stops at the first breakpoint correctly?

**Comment by yyalansavage** [comment]
yes for me it will break, step in the debugger correctly and no issues are observed. So this is something of a mystery.
If possible can you attach your local_settings.json from C:\Users\asavage\AppData\Roaming\GameMakerStudio2\<user> ? in case there is a local preference that can somehow cause this.
Also a bit of a long shot, i notice some german language output in the ui.log and wonder if your locale/language settings could be making a difference 
![2024-08-06 12_10_49-Settings](https://github.com/user-attachments/assets/bfa92112-ab36-4316-af1b-5371d7cd4a03)

**Comment by Grisgram** [comment]
I just tried to reproduce on a second PC here at work (which never had this project checked out so far) - and yes, you are right. No issues.
So it must be something in the cache on my main machine.
In the evening when I get home, I will try to clean all gms-caches for the project and retry.

Your answer was indeed very helpful - I will send another message here as soon as I had the chance to try in an all-new-cloned project with all caches cleaned on the pc which had the issues.

Thank you very much so far!
I come back with new results.

**Comment by Grisgram** [comment]
Ok, I tried again here on my main machine after deleting all caches and cloning the project under a new name and yes, it is 100% reproducible on this machine.
It crashes.

So, let's find out, where the differences are.
You said, you wanted the local settings and my locale settings. Ok, let's start with that, json and screenshot:

[local_settings.json](https://github.com/user-attachments/files/16512542/local_settings.json)

![image](https://github.com/user-attachments/assets/91539c49-cb47-4afb-b71b-8af294b77beb)

![image](https://github.com/user-attachments/assets/b2c8e06c-8eba-42e4-aab2-2e4d2e1e76a7)

![image](https://github.com/user-attachments/assets/8b1ed9ce-a8cd-4d16-8d42-4a28b7403a5b)

**Comment by sihammill** [comment]
Tried to repro this with all the information above and no luck.

**Comment by Grisgram** [comment]
it is very dissatisfying if a bug can not be reproduced... i've been in that corner myself too often  :(
I am willing to help finding the root cause in any way possible. 
what about a discord call with screen share, so you see it live? I could act as long arm and you tell me where to look or click, whatever.
Just let me know how we can try to track that down, because i can't debug my project, which is a very bad situation for me.

**Comment by Grisgram** [comment]
@jackerley 
A small update on this one. 
The reason for the debugger crash was an invalid "Watch" set in the debug window, i.e. a watch of an object that no longer exists in the project.

I deleted the %APPDATA%/Gamemaker/<myaccount>/cache/<project>/debugger.json file and now i can debug normally again.

So, even when the op post does not show the bug - there IS a bug, when a watch is declared to an object that gets removed from the project.
then the debugger crashes when it tries to stop at the breakpoint (and update the watches)

### How to fix
* Make sure, the code, that updates the watches can not crash - catch it, remove the watches, show "<invalid object>" in the value column of the watch, whatever - just keep it alive


Hope this helps!

Cheers, Gris

**Comment by yyalansavage** [comment]
Many thanks for the update, most useful! If you happen to remember what your problem watch was or get this problem again then please let me know - so far I've not been able to crash the runner in this way, watches I've tried for missing classes or objects etc just fail to evaluate. Glad you are able to debug again anyway!

**Comment by Grisgram** [comment]
@yyalansavage Hey :-) - Thank you very much for the kind reply!

I am one step further - please find attached a small project plus my debugger.json file and the ui.log (but i doubt, the latter contains useful information)

it has something to do with watching global.xxx

In this attached project, the debugger does not crash, but it can't continue. Neither F10 nor the toolbar button (step over) works.
Maybe this already guides you to the point, where the debugger starts to stumble. I send this to you now, and keep on trying to crash it -- but the current state here already demonstrates a false behavior.

### How to set up to reproduce:
* Unzip and simply start the project with F5 to create all the cache folders etc
* Then, copy the debugger.json file I attached here to your cache, so you can mirror my watches
* In the Create event of the `Child` object, set a breakpoint at line 4, as shown here: 
![image](https://github.com/user-attachments/assets/c9021fc7-2938-4a30-a44d-7a29581aadab)
* Now start with F6

Your watches should look like this, when the debugger stops:
![image](https://github.com/user-attachments/assets/8519d9bb-6f48-4bdf-bb0a-a48a6d462d48)

In this state, I can not press F10 or click the toolbar button, the debugger is frozen at this line, it refuses to advance by 1 line. Hit F5 and the program continues normally.

I hope this is a first step of guidance to the source of the problem!

kind regards, Gris


[ui_log.zip](https://github.com/user-attachments/files/16677782/ui_log.zip)
[debugger.json](https://github.com/user-attachments/files/16677791/debugger.json)
[debugger-crash.zip](https://github.com/user-attachments/files/16677795/debugger-crash.zip)

**Comment by Grisgram** [comment]
@stuckie Seems to be gone in 2408 -- issue did not occur since the update, maybe implicitly fixed through other changes in the new version

**Comment by stuckie** [comment]
Lovely!

Thanks for letting us know.

**Comment by sihammill** [comment]
Verified that the issue no longer appears to be there in IDE v2024.8.1.171  Runtime v2024.8.1.218
