### ISSUE TITLE
Can't open project files or import local asset packages from GameMaker 2023.11.0.121 (and possibly other versions from around that time period)

### ISSUE THREAD

**Issue by time-killer-games** [YoYoGames/GameMaker-Bugs#7085]
### Description

Can't open project files or import local asset packages from GameMaker 2023.11.0.121 (and possibly other versions from around that time period). This used to work in very recent versions of GameMaker Monthly releases. However as of the most recent Monthly release at the time of writing, both opening a GameMaker 2023.11.0.121 *.yyp project or local *.yymps asset package results in an error. It refuses to open or import. I'm away from my Windows machine right now but I can switch to it to provide a screenshot of the error if you are unable to reproduce this on your end. It has been reported that all my GameMaker extensions do not open in the latest GameMaker Monthly release because they were all made in this version.

It's also important to note this problem is very desirable to have fixed because I'd like my projects to continue working in the older versions of GM it currently supports and not break that by adding support for newer or future versions. Needing to constantly update all my projects and extensions within every year or so to prevent them breaking is a lot of maintenance to undergo, and I'd like to avoid needing to do it that often when possible, because nothing has changed on my code's end which should actually need changing, in my honest opinion.

### Expected Change

Have projects and local asset packages load from GameMaker 2023.11.0.121 in latest GameMaker Monthly release

### Steps To Reproduce

1. Start GameMaker
2. Open a *.yyp project file (and also try importing a local *.yymps asset package, both provided in each zip) from any one of the zip downloads available here: https://samuel-venable.itch.io/gamemaker-extension-collection
3. See the issue. Error loading project / local asset package.
4. I am not able to provide a Contact Us package for the version of GameMaker this bug actually applies to because the project and asset package won't even open / import into it

I've had this problem only happen on the Windows IDE. I can't seem to reproduce it on the macOS IDE (though my memory could be wrong, and I might have just tested the Mac IDE with the wrong GM version, one that worked), and I have yet to test the Ubuntu IDE, but upon request I will retest on Mac, and test on Linux, just let me know.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
They appear to work fine in 2024.6.2.162 and Runtime 2024.6.1.208 ... as you have provided no logs, which runtime you were on, or any other information I can only assume that you were hit with the runtime feed issue, whereby your runtime is likely old and not compatible with the IDE version you are using.

This would cause problems with loading older projects, as ProjectTool is currently a part of the runtime; and as this is what handles project conversions, if it doesn't match with the IDE's project format, it's not going to be able to successfully convert the project.

If you are still having issues, please submit your ui.log and a copy of the ProjectTool output ( see: Windows -> Project Tool Output within the IDE after trying to load a project ) and we will take another look.

Thanks.

**Comment by time-killer-games** [comment]
> They appear to work fine in 2024.6.2.162 and Runtime 2024.6.1.208 ... as you have provided no logs, which runtime you were on, or any other information I can only assume that you were hit with the runtime feed issue, whereby your runtime is likely old and not compatible with the IDE version you are using.
> 
> This would cause problems with loading older projects, as ProjectTool is currently a part of the runtime; and as this is what handles project conversions, if it doesn't match with the IDE's project format, it's not going to be able to successfully convert the project.
> 
> If you are still having issues, please submit your ui.log and a copy of the ProjectTool output ( see: Windows -> Project Tool Output within the IDE after trying to load a project ) and we will take another look.
> 
> Thanks.

It's impossible to provide anything in relation to something which requires loading the projects first, because the projects do not load to begin with. I'll try deleting the old runtimes and see if that fixes it.

**Comment by time-killer-games** [comment]
Deleting the old runtimes fixed it! Thank you so much!!! :D

**Comment by stuckie** [comment]
Thanks for letting us know!

Your ui.log should actually tell you if the project it's trying to load is not in the format it expects, if it's trying to launch ProjectTool, and whether that was successful... so if something like this happens again, that will give you a rough idea of what's going on.
