### ISSUE TITLE
Code Editor: flexpanel_node_style_set_..._height/width() variant parameter orders are not consistent and do not match the current Beta manual content

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7086]
### Description

Applies to all the width and height functions:
[flexpanel_node_style_set_width](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_width.htm)
[flexpanel_node_style_set_height](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_height.htm)
[flexpanel_node_style_set_min_width](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_min_width.htm)
[flexpanel_node_style_set_max_width](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_max_width.htm)
[flexpanel_node_style_set_max_width](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_max_width.htm)
[flexpanel_node_style_set_max_height](https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_max_height.htm)

The manual lists parameter order as node, value, unit:
![image](https://github.com/user-attachments/assets/66b34d1d-abec-42c3-8bcc-b3d4b6a4e01a)

But IDE lists parameter order as node, unit, value:
![image](https://github.com/user-attachments/assets/45e21900-09f0-4774-baef-529e2115b125)

I believe the IDE is incorrect as node, value, unit is what is usedused in the blog post:
https://gamemaker.io/en/blog/flex-panel-functions

That said, it would be much preferable for the order of the parameters to be consistent across functions, so all function should be node, value, unit OR node, unit, value but NOT a mix of orders.

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_width.htm

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by gurpreetsinghmatharoo** [comment]
`flexpanel_node_style_set_flex_basis` and `flexpanel_node_style_set_position` pages updated as per Russell's changes above. Will be available with the next beta release.

**Comment by Emc1923** [comment]
Verified parameter order changes in  IDE v2024.800.0.605  Runtime v2024.800.0.628.

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, syntax for set_position was wrong as well so that is also fixed now.

Thank you

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.614  Runtime v2024.800.0.638
