### ISSUE TITLE
[Steam Deck] DPI issues on opening IDE for the first time

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7098]
### Description
Although not an officially supported IDE platform, like my Pi DPI issues from last time, I'm once again occurring an issue. https://github.com/YoYoGames/GameMaker-Bugs/issues/4327 I'll be applying the workaround as described last time, but I wanted to report this prior to applying said workaround.

See attached screenshot for a demonstration (captured via elgato capture card 4K, confirmed via unplugging that it does not remedy the issue). Steam Deck is in portrait mode (90 counterclockwise), according to my display settings.
<img width="1040" alt="4KCaptureUtility_2024-08-04_19-38-58" src="https://github.com/user-attachments/assets/0640680e-bc12-4ac5-987d-4b08da549b8f">

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Linux SteamOS Holo kernel 6.1.52.16

[02232185-c160-496e-99ec-fdb42f38de69](https://api.gamemaker.io/api/github/downloads/02232185-c160-496e-99ec-fdb42f38de69)

**Comment by tabularelf** [comment]
I should mention that it did take me a few tries to getting the IDE in a state where I could access the bug report option directly (which I am glad)
<img width="629" alt="4KCaptureUtility_2024-08-04_19-08-03" src="https://github.com/user-attachments/assets/017e9d77-77b1-46ce-b9e3-8267dcf70c0c">

**Comment by YYDan** [comment]
Unsupported OS/device - ultimately this is waiting on https://github.com/YoYoGames/GameMaker-Bugs/issues/3196 so closing.
