### ISSUE TITLE
In-Game: [HTML5] surface_set_target() can return "Cannot read properties of null" error when targeting a struct variable

### ISSUE THREAD

**Issue by FoxyOfJungle** [YoYoGames/GameMaker-Bugs#7100]
### Description
I can't tell exactly where the problem is, but I managed to isolate it successfully. In HTML5 I get a message saying "Cannot read properties of null" when I try to use surface_set_target on a variable that is inside a struct. I think it might be because the variable is in the struct. The project compiles normally on Windows and other platforms (GX.Games and Android). The bug only occurs in HTML5. This problem affected my Post-Processing FX library and the lighting system I'm creating (Crystal).

### Steps To Reproduce
Just press F5 and the error message will appear in the Console (in the browser). There is only 1 object and 1 room in the project, so it should be easy to identify the problem

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
HTML5

[5dffe19f-51f3-4ee6-aae5-30d416da7c04](https://api.gamemaker.io/api/github/downloads/5dffe19f-51f3-4ee6-aae5-30d416da7c04)

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.892  Runtime v9.9.1.1037
