### ISSUE TITLE
In-Game: Add functions to minimize/restore game windows on desktop platforms

### ISSUE THREAD

**Issue by KingDevyn** [YoYoGames/GameMaker-Bugs#7102]
### Is your feature request related to a problem?

Making the game window botderless keeps the aesthetic clean. Making a custom bar lets you maintain color pallet/ graphical style while still giving the player control over the game window, however, there is no function to minimize the screen in gml.

### Describe the solution you'd like

A function that minimizes the game window on Windows/mac and possibly other devices with similar functionality.

**Comment by yoyo-danielc** [comment]
`window_minimise()` and `window_restore()` functions have been added to the 2024.10 branch, test project:

[window_minimise.zip](https://github.com/user-attachments/files/16964427/window_minimise.zip)

NOTE: The game won't auto-restore on macOS as games stop running when minimised.

**Comment by mgeddesGM** [comment]
As of  IDE v2024.1000.0.623  Runtime v2024.800.0.642 the above the sample does not run and both give the same kind of error upon further investigation

![image](https://github.com/user-attachments/assets/f4453f86-1392-492e-bc6b-9cfc37c2590d)

**Comment by mgeddesGM** [comment]
sorry due failed by mistake. retested in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649 and passes for ce1 and 2 using win vm and yyc

**Comment by FoxyOfJungle** [comment]
Since this was added, they could have added a **window_maximize** too ^^', since it is part of the window commands. 

Unfortunately I only saw this now. Either way, I appreciate the addition of these two new features!
