### ISSUE TITLE
Delta Time and Multithreads

### ISSUE THREAD

**Issue by JohnyCoolHD** [YoYoGames/GameMaker-Bugs#7105]
### Is your feature request related to a problem?

I'm pretty sure that my game will get performance isues on low-end hardware if a add lighting. That would be very bad because then the physics in my game would be completely broken. The current delta time is complecated to setup and this is why my game only runs at 60 fps normally. 

### Describe the solution you'd like

That's why I want multithreads and a better delta_time integration. That would help for better performance on low-end hardware and people with 120hz monitors or more could use the refreshrate for a better gameplay experience.

### Describe alternatives you've considered

I wish that at least one of these things will be added to gamemaker.

**Comment by stuckie** [comment]
This is not planned for current runtime
