### ISSUE TITLE
flexpanel_node_style_set_align_content parameter description links to wrong constant type

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7109]
### Description

The link to the alignment constant doc links to justify constant doc instead
![image](https://github.com/user-attachments/assets/b2c3b256-e7e1-4e21-bd63-3035c3c60638)

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/Styling_Functions/flexpanel_node_style_set_align_content.htm

**Comment by gurpreetsinghmatharoo** [comment]
This is correct because that's the family of constants it takes.
