### ISSUE TITLE
flexpanel alignment functions support "baseline" but there is no explanation of how to set baselines

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7110]
### Description

The manual page describes a `"baseline"` option for alignment:
![image](https://github.com/user-attachments/assets/8dc73153-d66e-4e55-b0de-032e7173ae3a)
But there is no explanation of where this 'reference baseline' comes from or how to modify it

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFlex_Panels_Styling.htm&rhsearch=baseline

**Comment by gurpreetsinghmatharoo** [comment]
The flex panel functions wrap around the Yoga layout library. The docs for Yoga layout do not describe the baseline beyond the mentioned line and I wasn't able to figure out exactly what it does through testing.

Will revisit this when UI Layers are added.

Closing
