### ISSUE TITLE
flexpanel documentation does not explain whether nodes need to be garbage collected

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7118]
### Description

This page says removing a node does not delete it:
https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/flexpanel_node_remove_child.htm
Deleting it is described here:
https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/flexpanel_delete_node.htm

What is not clear is whether you *have* to delete a node if you remove it and then have no more references.

For example, consider you have nodes A and B. You set A as the parent of B. Later you create a new node C that you want to replace B. So you remove B from A's children, and set A as the parent of C. B is no longer referenced anywhere.

Does B get deleted automatically by the garbage collector now that there are no references to it? Or do we need to manually ensure we clean up any nodes we remove and no longer reference?

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Flex_Panels/Function_Reference/flexpanel_node_remove_child.htm

**Comment by stuckie** [comment]
These are not garbage collected.

**Comment by alicemoretti** [comment]
Verified done in the latest Beta Manual . 

Thank you.
