### ISSUE TITLE
Functions declared in an object as function name() could be treated as global functions

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7125]
### Description
Sometimes a user may wish to declare functions within an object, which does work. Though referring that same function in another object yields an error, as they are not considered global:
![image](https://github.com/user-attachments/assets/020f4095-ef81-4b99-b777-27b2c01086b7)

In a discussion with Russell on Discord, this turns out to be a possible compiler bug.

Meaning that this declared in any object
```gml
function name() {
    // code
 }
```
Should be accessible by any other object, with or without the existence of said object.

### Steps To Reproduce
1. Run project
2. See error

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[1c586a63-88af-46a6-8b1e-9cb7751cabbc](https://api.gamemaker.io/api/github/downloads/1c586a63-88af-46a6-8b1e-9cb7751cabbc)

**Comment by KormexGit** [comment]
Something else I've noticed when declaring functions in a create event this way is that what the function's id is seems to be different in the create event vs other events:
![image](https://github.com/user-attachments/assets/2d604991-b02e-4a69-83cc-19ba16026ad8)

Not sure if this is related but figured I'd point it out in case it is 

[FunctionThing.zip](https://github.com/user-attachments/files/16501499/FunctionThing.zip)

**Comment by rwkay** [comment]
I have updated this now for 2024.10 - any function that is declared in an event with the syntax 
```
function FUNCNAME( /* args */ )
{
 /* function body */
}
```

will now be accessible as a function name everywhere... This will need to be checked on early Betas for issues... I am thinking that we may change this to require that the function has to be scoped i.e. if `FUNCNAME` is declared in `oPlayer` then you would need to use `oPlayer.FUNCNAME` to call it as this may be a better idea...

**Comment by yerumaku** [comment]
> will now be accessible as a function name everywhere... This will need to be checked on early Betas for issues... I am thinking that we may change this to require that the function has to be scoped i.e. if `FUNCNAME` is declared in `oPlayer` then you would need to use `oPlayer.FUNCNAME` to call it as this may be a better idea...

Does it appear in the documentation? 

Will this also work with prefab naming chaining? 
```gml
Prefab1.objPlayer.functionDefinedInObjectEvent(); // example dot chaining
```

**Comment by gnysek** [comment]
In "squirrel" betas, `Object1.function` doesn't work for me if instance of object doesn't exists. However, if instance exists, I can assign function to global variable and re-use it, so it's globally available after having handler. Same I can see them with `asset_get_ids(asset_scripts);` but assumption from first comment, that:

> Should be accessible by any other object, with or without the existence of said object.

Doesn't seem to apply for me.

I would check it again after proper public beta release, and if still doesn't work, I would create separate ticket - I'm leaving this comment only as informational (or maybe to correct me if I'm wrong).

**Comment by rwkay** [comment]
You will always need to have an instance of the object existing.

We have tried various routes to implementing this but there are various edge cases and how `self` and `other` would be handled in this situation. For current gml we have decided to disallow the calling of the function with no instance available as this distorts the `self` and `other` handling in that case.

**Comment by gnysek** [comment]
Can we get issue description of this issue and release notes fixed then? Release notes are referencing that details are in this ticket:
![obraz](https://github.com/user-attachments/assets/d4e97c7a-e373-4d34-8513-99f6584e14f8)
And this ticket says:

> Should be accessible by any other object, with or without the existence of said object.

Which is not true.

IMO, I would change it to:
> **Functions declared in an Object event are now treated as global functions.**
> - Any function that is declared in an event with the syntax `function NAME(){ ... }` will now be accessible everywhere, if at least one instance of that object exists, or if function handler is set to variable

But I'm sure that better wording could be used here

**Comment by scott-dunbar** [comment]
Yes, i agree - this issue needs updated for clarification before it can be closed.

From what i can tell based on the information provided in the description and comments there is a disconnect.

"You will always need to have an instance of the object existing." is a contradiction to the actual bug report so im not sure what was done to this issue or what state it should be in now.

Passing back to triage for an update.

**Comment by YYDan** [comment]
Yes, the original sample project still gives the same error in IDE v2024.1100.0.629  Runtime v2024.1100.0.654 as it did in 2024.8.1 (and that I added into the Description already):

![image](https://github.com/user-attachments/assets/429ab688-ca90-454f-902f-eef6e6991efe)

Note that the sample project already has an instance of each object in the room, so presumably is not even hitting the issue identified in the new comments.

**Comment by YYDan** [comment]
Release notes have now been updated similar to what was suggested above, as we have now realised https://github.com/YoYoGames/GameMaker/issues/4377 does say about this change/limitation, but was not linked to here.

**Comment by YYDan** [comment]
However, the change above does mean that there is no difference in practical results between 2024.8.1 and 2024.800 Beta 1 - both versions of GameMaker can call functions declared in a different object's event if using the format objectName.functionName() and instance of both objects exist in the room at the time.

A tweaked version of the original sample to show the issue:
[GMB7125-Dan.zip](https://github.com/user-attachments/files/17192258/GMB7125-Dan.zip)

All works perfectly until you remove object1 from the room, at which point this will error the same in 2024.1100 as it does in 204.8.1:
![image](https://github.com/user-attachments/assets/e01bccc6-4fdc-4e75-ad8c-d99f570b1c3d)

**Comment by Alphish** [comment]
@YYDan For the record, while I haven't found differences in behaviour when it comes to availability or lack thereof of the function via `objectName.functionName()` syntax, I did notice some important differences related to how object-bound script functions are organised now. In particular:
- function seems to be no longer assigned to the object's variable (which can be checked with `variable_instance_get_names` after the function declaration)
- function is available to the object regardless of where it's declared - in particular, the event with the function might never run and the function will still be runnable from the object

More details in [my GMC post](https://forum.gamemaker.io/index.php?threads/2024-1100-betas-thread.115648/post-686124).

So while it doesn't quite achieve the desired effects as described in the FR, there are important under-the-hood changes that make object-bound script functions easier and potentially more memory-efficient to work with.

**Comment by shichen85** [comment]
> @YYDan For the record, while I haven't found differences in behaviour when it comes to availability or lack thereof of the function via `objectName.functionName()` syntax, I did notice some important differences related to how object-bound script functions are organised now. In particular:
> 
> * function seems to be no longer assigned to the object's variable (which can be checked with `variable_instance_get_names` after the function declaration)
> * function is available to the object regardless of where it's declared - in particular, the event with the function might never run and the function will still be runnable from the object
> 
> More details in [my GMC post](https://forum.gamemaker.io/index.php?threads/2024-1100-betas-thread.115648/post-686124).
> 
> So while it doesn't quite achieve the desired effects as described in the FR, there are important under-the-hood changes that make object-bound script functions easier and potentially more memory-efficient to work with.

TY Alice for mentioning that object variables being no longer assigned to the function. This is also what we are experiencing.

**Comment by gnysek** [comment]
What I found, is:
- functions in objects seems to be pseudo static, so they're same handle in each instance and you can assign that handle to variable and use it even when no instances exists
- they seem to be compiled with game, and get be get with `asset_get_type(asset_script)` - so they already exists before any first instance is created. 

But this was true in first beta, might be not true if any other changes were made.

**Comment by YYDan** [comment]
Yes, as mentioned above, the actual change here is that _within the same object_ you're now using a more efficient system when calling a function declared in one event when inside a different event, and that _between different objects_ nothing has changed.

This is actually covered better in the newly-public https://github.com/YoYoGames/GameMaker-Bugs/issues/7865 so I am actually going to tidy this FR up as "Not Planned", as we have not done what this one requested, and I will edit the release notes to point at that other issue instead ;)

**Comment by rwkay** [comment]
**** IMPORTANT ****

Most of this feature has been backed out from 2024.11 as we have discovered - functions that are declared within an event will still be available through the `asset_` functions, but the optimisation that meant they were called directly (like a function) which would speed up execution as this only worked in cases where object inheritance had been used, and the method for the function was being relied upon.

This was incompatible with the optimisation and so reluctantly we have removed this - we will revisit how this works in GMRT and look to improve the performance of these types of function calls at that point.

**** IMPORTANT ****
