### ISSUE TITLE
Feather tooltip disappears when you type

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7133]
### Description

It's like playing one of those memory games where you have 10 seconds to memorize the contents of the screen before everything gets obscured, which I was never very good at

![feather tooltip disappears when you type](https://github.com/user-attachments/assets/d3325482-69d3-4a0c-85ff-d286ebb2a97d)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DragoniteSpam** [comment]
This includes pressing \*any\* key btw, including the PrintScreen key, which makes taking screenshots of bugs in Feather rather difficult

Interestingly it doesn't happen if another window on the desktop has focus

https://github.com/user-attachments/assets/cead77c4-e826-4283-bb46-4968eec8a80a

**Comment by caitlinrmcintyre** [comment]
Verified fix for Parameter Tooltip in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649, thanks.
