### ISSUE TITLE
Upgrade to gradle 8

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#7134]
### Is your feature request related to a problem?

Newer Google libraries are moving on to require gradle 8 [*]. Please upgrade and test android runtime to use newer Android Gradle Plugin (AGP) and gradle pairs [**].

[*] [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/upgrade-to-crashlytics-gradle-plugin-v3#groovy)
[**] [Updating Gradle] https://developer.android.com/build/releases/gradle-plugin?buildsystem=ndk-build#updating-gradle
[AGP Compatibility] https://developer.android.com/build/releases/gradle-plugin#compatibility

### Describe the solution you'd like

Update AGP/Gradle pair in GM runtimes, and add information about them to the Android setup guide/required SDKs page.

**Comment by YYDan** [comment]
Already done in 2024.800 Betas, so you can install that just now if you wish.
