### ISSUE TITLE
Document that disabling application surface or depth buffer generation will stop Clipping Masks from working

### ISSUE THREAD

**Issue by harpwood** [YoYoGames/GameMaker-Bugs#7139]
### Description
When application_surface_enable is set to false, sequences' clipping masks do not function as expected. This occurs both when a sequence is manually placed in a room's asset layer and when a sequence is instantiated programmatically.

### Steps To Reproduce
1. Start with a new, empty project.
2. Set application_surface_enable(false); in the game's initialization code.
Place a sequence in a room's asset layer or instantiate it using the following code:

    layer_sequence_create("Instances", room_width / 2, room_height / 2, Sequence1);

3. Run the game and observe the sequence's clipping mask.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5, Windows

[552bd6f9-aba7-4208-a3f0-00f717d41618](https://api.gamemaker.io/api/github/downloads/552bd6f9-aba7-4208-a3f0-00f717d41618)

**Comment by stuckie** [comment]
Clipping requires the stencil buffer.

**Comment by harpwood** [comment]
> Clipping requires the stencil buffer.

It was working fine when I last updated the project. The last time I updated the game was at 23 February 2024 with the latest, back then IDE and Runtime. For more context about this issue please [refer to my forum post](https://forum.gamemaker.io/index.php?threads/clipping-mask-in-sequences-broke-after-gamemaker-update.114662/#post-680484)

**Comment by harpwood** [comment]
According to Mr Russel, this is an intended behavior ([source](https://forum.gamemaker.io/index.php?threads/clipping-mask-in-sequences-broke-after-gamemaker-update.114662/#post-680619)), so I am closing this issue.

**Comment by L-Clouds** [comment]
> According to Mr Russel, this is an intended behavior ([source](https://forum.gamemaker.io/index.php?threads/clipping-mask-in-sequences-broke-after-gamemaker-update.114662/#post-680619)), so I am closing this issue.

It should be reopened, because it is not documented that sequence clipping masks depend on any other setting to function.  Indeed, stuckie had labeled this as "docs-bug"

**Comment by harpwood** [comment]
> > According to Mr Russel, this is an intended behavior ([source](https://forum.gamemaker.io/index.php?threads/clipping-mask-in-sequences-broke-after-gamemaker-update.114662/#post-680619)), so I am closing this issue.
> 
> It should be reopened, because it is not documented that sequence clipping masks depend on any other setting to function. Indeed, stuckie had labeled this as "docs-bug"

OK then, I reopen it...

**Comment by YYDan** [comment]
> OK then, I reopen it...

To be honest, you probably want to avoid closing issues unless in the one _specific_ circumstance where you realised it was a coding mistake on your part and so you want to avoid someone here taking time to look into your project.

As happened in this instance, sometimes we determine that a problem needs better manual content or a support FAQ, or a different type of fix, or whatever - so, just because we may not fix the original report exactly as written, does not mean we don't need to discuss and track an issue. So it's usually safer to just leave issues for us to close - and we're all set up for this anyway, so it's no hassle ;)

**Comment by alicemoretti** [comment]
Note added to the manual pages for application_surface_enable and Clipping Masks in the newest Beta Manual. 

Thank you.
