### ISSUE TITLE
In-Game: debug_event("DumpMemory") causes games to freeze

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7146]
### Description
As above, calling `debug_event("DumpMemory")` will cause the game to become unresponsive.

### Steps To Reproduce
- Open and run the example project, in which a time source is set up to call the function every 5 secs.
- When the timer reaches ~0 for the first time, observe that the game freezes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[a706433e-83b9-4935-afb8-22a5ab1e0520](https://api.gamemaker.io/api/github/downloads/a706433e-83b9-4935-afb8-22a5ab1e0520)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.605  Runtime v2024.800.0.628
