### ISSUE TITLE
Need to create an extension for the Netflix SDK

### ISSUE THREAD

**Issue by FrancisCoulombe** [YoYoGames/GameMaker-Bugs#7147]
### Which Extension are you reporting this issue for?

App Tracking Transparency

### Description

I would need help to create a Game Maker extension for the latest version of the netflix SDK for both Android and iOS. I can't share the details publicly.

### Steps To Reproduce

n/a

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Unfortunately, we are not responsible for the Netflix SDK - you will have to speak to them to get in contact with us, so we can resolve any issues with them.
