### ISSUE TITLE
Code Editor 2: Middle-clicking keywords does not open their manual page

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7150]
### Description
In CE1, middle clicking a keyword like for, with, repeat, etc. will open the corresponding manual page. In CE2, middle clicking them instead does nothing.

Edit: This applies to sprite_index as well, does nothing when middle clicked. I've tried a variety of other built in variables and they all worked, so not sure if it's just sprite_index or there's others that don't work.

### Steps To Reproduce
Type any keyword, and then middle click it/press F1 on it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[1a996419-2f47-4952-a723-c0c7d3aecae8](https://api.gamemaker.io/api/github/downloads/1a996419-2f47-4952-a723-c0c7d3aecae8)

**Comment by tinkerer-red** [comment]
As an update to this, middle clicking anywhere just opens a blank page to the docs, so it appears that the root of the issue may be different
https://gyazo.com/66877ce95699f7927be7029a55f56927.mp4
https://github.com/user-attachments/assets/c2c95d47-b390-4547-a2a0-14a8d9d691de


` IDE v2024.1100.0.659 Beta Runtime v2024.1100.0.685`

**Comment by KormexGit** [comment]
I believe middle clicking anywhere opening a blank docs page is new to the latest beta, since it wasn't doing that before

**Comment by KormexGit** [comment]
Looks like this also applies to `enum` and `macro`. Middle clicking #macro actually doesn't work in CE1 either, since it takes you to the manual front page instead of the page for constants.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.682  Runtime v2024.1100.0.704
