### ISSUE TITLE
In-Game: Sequence in attached project hangs after drawing its first frame

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#7154]
### Description
The sequence asset used as the front end animation is hanging after its first frame:
![image](https://github.com/user-attachments/assets/3aa27e73-af0c-42b2-a55a-7e505dae509c)

Appears to be caused by particle systems which use custom sprites as their particle being used within that sequence that's trying to load, as any of the three characters which use custom particles will cause this hang, but the one character which uses GM's in-built particle sprites does not cause the hang.

### Steps To Reproduce
1. Start GM and import this project (not the one in the sample package, as that newer version does not actually show any problem): https://drive.google.com/file/d/1w1wCynzvWQOd2bxp4o791ZBR-aaILXZF/view?usp=drive_link
2. Run the game for Win VM
3. Observe the GM logo splash is fine, but then there is a noticeable pause with just the background drawn (as shown above) before the rest of the sequence loads in and the main menu is ready
4. (Optional) Open the sequence asset "seq_splash_screen" and disable the 3 characters apart from "Lucy", then run the game again and observe the hang is gone

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[32ceaccc-3e77-430b-9b37-2129d65e42ab](https://api.gamemaker.io/api/github/downloads/32ceaccc-3e77-430b-9b37-2129d65e42ab)

**Comment by YYDan** [comment]
The problem does indeed appear to come from all the particle effects attached as tracks to to the characters the menu is trying to draw to a 4K room size.

The "Lucy" asset shows no issues:
![image](https://github.com/user-attachments/assets/f3ecb4d1-f7b5-42b1-91ab-4a158a0caf08)

But if any 1 of the other 3 are enabled (even if "Lucy" is disabled), then the issue occurs.

Disabling the other items, like the 25 logo and the buttons, makes no difference, nor does commenting-out all the audiogroup loading checks in the menu controller object that spawns this sequence.

**Comment by YYDan** [comment]
Still the same results in Beta IDE v2024.800.0.602  Runtime v2024.800.0.624
