### ISSUE TITLE
Manual Content: Consolidate the content for differences between passing an Object index vs Instance id to other functions

### ISSUE THREAD

**Issue by zzhamzz** [YoYoGames/GameMaker-Bugs#7155]
### Description

Not a bug really but a request for additional/clarified/consilidated documentation on a specific topic.

On the GMC it is common problem that users don't understand the difference between using and passing object indices vs instance ids.

The best current manual page(s) to explain this is spread out across:
- addressing variables in other instances:
-https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FAddressing_Variables_In_Other_Instances.htm
- with -https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2Fwith.htm
- The various pages for function that can accept an object index or an instance id

While those explain some of the differences and uses in specific context it they don't explain the difference in general. And the information is spread out across a few pages. Specifically that if you pass an object index into a function it will typically result in operating on 'any' instance of that object or 'all' of the instances of the object.  

Addtionally while most pages for specific functions that can take an object index or instance id, will state what the difference is I think it would be good to have a single source to point to that covers the general differences.

While the 'addressing variables in other instances' does alot of this I feel the name it, and its name, is a bit specific.

I am requesting a page, named appropriately, that gives a solid overview on the general uses/results of using object indices vs instance id in varying context.

Something that covers the general concepts that will be encountered and then potentially link to the various places that discuss them in more detail: e.g. `Adressing Variables` and `with` pages

Thanks

**Comment by gurpreetsinghmatharoo** [comment]
Added a new page under Additional Information called 'Objects vs. Instances'
