### ISSUE TITLE
Saved Workspaces

### ISSUE THREAD

**Issue by davidkarbo97** [YoYoGames/GameMaker-Bugs#7158]
### Is your feature request related to a problem?

Whenever I open a new workspace tab to clean things up, I wish I could open all objects, sprites, and scripts related to my current task at once. For example, if I'm working on my game's player, I could open a saved workspace that automatically lays out my player object, player sprites, and player scripts all with one click.

### Describe the solution you'd like

It would be nice to be able to open a saved workspace that remembered the exact combination and layout of assets that should be opened, so you can open them in one click.

**Comment by YYDan** [comment]
You can already do this - its the Layouts menu at the top of GM. Just open and position whatever windows you want, save and name your layout, then you can load that layout at any time.
