### ISSUE TITLE
Release Notes: Please add the date of release to each version

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#7159]
### Is your feature request related to a problem?

The new standalone release notes website is missing timestamps information. 

### Describe the solution you'd like

Add timestamps to the top of pages and patch sections for [https://releases.gamemaker.io/](https://releases.gamemaker.io/)
For example, on this page:
https://releases.gamemaker.io/release-notes/2024/6
Both "Changes In The .2 Update" and "Changes In The .1 Update" should be accompanied by their release timestamps (yyyy/mm/dd).

This is especially important to LTS releases, since the version numbers don't match the release years.
https://releases.gamemaker.io/release-notes/2022/0

Google's release notes are good references:
[Firebase release notes](https://firebase.google.com/support/releases)
[Google Play Services release notes](https://developers.google.com/android/guides/releases)
[AdMob release notes](https://developers.google.com/admob/android/rel-notes)

### Describe alternatives you've considered

Alternatively, static documentation website pages can be open sourced, so changes can be automatically timestamped by external version system, and easily tracked later.

**Comment by YYDan** [comment]
Yeah, I was thinking this myself the other day - will see about adding them.

**Comment by YYDan** [comment]
Have now added the dates into each of the "current" releases and published the updated pages:
https://releases.gamemaker.io/release-notes/2024/6
https://releases.gamemaker.io/release-notes/2024/800
https://releases.gamemaker.io/release-notes/2022/0

Will do this for future releases also.
