### ISSUE TITLE
In-Game: [GX.games] Included Files for OGGs are missing if the .ogg is in a subdirectory, when using LTSr2

### ISSUE THREAD

**Issue by RobertCordingly** [YoYoGames/GameMaker-Bugs#7162]
### Description

When an ogg file is in a directory GameMaker is unable to find it (file_exists fails) on GX Games but can find it on other platforms.

Example project: https://www.dropbox.com/scl/fi/4c2yvjlear9gcciq83dlc/OGGBUG.yyz?rlkey=xu1t1fy5o8lptra7ttaxdqjl0&dl=0

Contact Us Package: I could not find this option under the Help menu in GameMaker LTS

### Expected Change

Game maker should be able to utilize OGG files in directories

### Steps To Reproduce

1. Start GameMaker
2. Open example project
3. Run on MacOS or Windows, see the 3 messages saying that the ogg file is there.
4. Run on GX Games, see 2 out of 3 messages saying the ogg file is not there. :(

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

GX.games

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.613  Runtime v2024.800.0.636

**Comment by alicemoretti** [comment]
Verified fixed for on GX.Games on LTS IDE v2022.0.3.75  Runtime v2022.0.3.87. 

Thank you.

**Comment by alicemoretti** [comment]
Reopening for LTS as I did not check the fix on GX YYC as it's not working on LTS IDE v2022.0.3.75 Runtime v2022.0.3.87.

**Comment by alicemoretti** [comment]
Verified fixed on both GX VM and YYC on IDE v2022.0.3.77  Runtime v2022.0.3.88. 

Thank you.
