### ISSUE TITLE
Code Editor: GMLSpec info for `buffer_peek()` describes the functionality of the `buffer_read()` function, and GMLSpec info for `buffer_read()` is lacking info

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7164]
### Description

The GMLSpec info for the `buffer_peek()` function instead describes the functionality of the `buffer_read()` function:

![image](https://github.com/user-attachments/assets/456b4008-e101-49f9-acf9-4211248b2f1f)

Additionally, the GMLSpec info for `buffer_read()` seems to be lacking some of this info:

![image](https://github.com/user-attachments/assets/8ebdbbf2-4719-4f35-b46f-f9c67a1c7444)

[Bug Report Package](https://api.gamemaker.io/api/github/downloads/d63d86eb-b102-4570-9181-757ede9a16f0)

### Steps To Reproduce

1. Start GameMaker
2. Create a new script
3. Type `buffer_peek()` into the script
4. Hover over it and observe the GMLSpec typo
5. Type `buffer_read()` into the script
6. Hover over it and observe the lack of info in the GMLSpec description

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Issue still present as described in  IDE v2024.800.0.611  Runtime v2024.800.0.635



![Image](https://github.com/user-attachments/assets/b0a32c78-7cbe-4d56-a1c1-3ccf24bb8e6b)

**Comment by DiasFranciscoA** [comment]
Cherrypicked to Aug24

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637
