### ISSUE TITLE
In-Game: [HTML5] sprite_delete() causes crash if using LTS runtimes

### ISSUE THREAD

**Issue by spacebake** [YoYoGames/GameMaker-Bugs#7177]
### Description

on LTS, html export calling sprite delete will cause the game to crash 100% of the time. no matter what, even in an empty project.

[sprite_delte_broken_example.zip](https://github.com/user-attachments/files/16553299/sprite_delte_broken_example.zip)

Please note: i cannot add a contanct-us package because it seemingly doesn't exist in LTS yet.

### Expected Change

The game continues to run correctly after deleting the sprite

### Steps To Reproduce

1. Start GM and import the attached sample
2. Run the game for HTML5
3. Move the mouse cursor and observe the white circle sprite shows fine
4. Press spacebar to delete the sprite created from a surface
5. Observe that the game has errored (and the white circle has stopped drawing)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GMRT are you reporting this issue for?

LTS (IDE v2022.0.2.51 / Runtime v2022.0.2.49)

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Works just fine in the current release (2024.6).

Does not work in the internal LTS.

**Comment by Emc1923** [comment]
Verified working in LTS  IDE v2022.0.3.62  Runtime v2022.0.3.74
