### ISSUE TITLE
Release Notes: Layout means text overlaps at specific browser page-zoom levels

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7178]
### Description

When I zoom the release notes page to specific zoom levels, the text overlaps. I'm using Firefox.

https://github.com/user-attachments/assets/7f6bb930-adee-4500-8e5e-9a2c8f80a5c1

### Manual Link

https://releases.gamemaker.io/

**Comment by YYDan** [comment]
Doubt this is anything to do with yesterday's styling tweak - more likely always been this way, but will investigate.

For me:

On a 1080p screen and a page zoom of specifically 125% the sidebar clips into the main body content. It's fine again at 150%. Then once you get past 200% the page will only show either the sidebar or the main body, but not both.

On a 4k screen, all is well up until 250% before the clipping begins and at 400% you can only see the sidebar.

**Comment by YYDan** [comment]
Verifying the fix is already out.

On my 4k screen at specifically 300% just the "TM" bit in the sidebar overlaps a tiny bit, but not enough to cause any issues. Values higher than 300% are fine again.

On my 1080p screen it never overlaps now.
