### ISSUE TITLE
Code Editor 2: Colouring does not work for certain flexpanel functions

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#7181]
### Description

 On CE2, the flex panel functions in the screenshot will all be greyed out and won't show up in the autocomplete:
 
![349057324-681c091c-208b-4da4-928d-f6dbf98f6c83](https://github.com/user-attachments/assets/710fb223-7a7b-4b8c-bbd7-34377d74f113)

This is related to [#4226](https://github.com/YoYoGames/GameMaker/issues/4226)

[flexpanel_runtime.zip](https://github.com/user-attachments/files/16262827/flexpanel_runtime.zip)

### Steps To Reproduce

1. Start GameMaker
2. Import the project attached
3. Open any object with CE2
4. See the issue

### How reliably can you recreate this issue using your steps above?

None

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by zreedy** [comment]
Appears fixed.
