### ISSUE TITLE
Package Manager: Move the default install path out of 'My Documents', match the other changes in 2024.4

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7182]
Currently the default Install directory path for the Package Manager and GMRT is still `C:\Users\<user>\Documents\gmpm` for Windows.

### Expected Change

As the "OneDrive is now in My Documents" default Preferences paths changes have been done in 2024.4 already, this setting should be moved elsewhere also.

It should presumably be based off the existing IDE Preference also?

**Comment by alicemoretti** [comment]
Verified that the screenshots in the Manual pages for GMRT Preferences and Package Manager Preferences have been updated in the newest Beta manual. Thank you.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.618  Runtime v2024.800.0.642
