### ISSUE TITLE
"Failed to convert audio file" compile errors + inifinty loop in 2024.800

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7184]
### Description
In 2024.800, for GMS2 and GMRT runtime I'm getting error
`Error : Failed to convert audio file '_039'. Check source file`
for many audio files, which were converting properly in all previous GameMaker versions, so <= 2024.6 runtime (and it includes pre-GMS2 versions too).

What's worse, it's entering infinity loop of showing this compile error, which leads to hanging up IDE.

### Steps To Reproduce
1. Run attached project with only one audio file.
2. Observe tons of `Error : Failed to convert audio file '_039'. Check source file`
3. Check it in 2024.6 or earlier versions, and it will work

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[4d781716-aeb9-4ac4-8615-26338f699252](https://api.gamemaker.io/api/github/downloads/4d781716-aeb9-4ac4-8615-26338f699252)

**Comment by stuckie** [comment]
Our ffmpeg was missing adpcm_ms; it should now be included.

**Comment by gnysek** [comment]
I've added #7291 as this is also happening in GMRT and I'm not sure if it was fixed there too until 0.13 comes out.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637 current runtime only. Will keep 7291 as an open separate issue for GMRT to be fixed

**Comment by gnysek** [comment]
It's not working on Mac in 2024.8 - #7531 .
