### ISSUE TITLE
UI/UX: [Mac IDE] Menubar interactions become unreliable after opening the Source Control menu multiple times in an IDE session

### ISSUE THREAD

**Issue by hegner123** [YoYoGames/GameMaker-Bugs#7192]
### Description
After working in game maker for several hours it is common for the Menu Bar to stop function as expected. 

This became much more common after enabling Source Control for my project.

bugs include:
 - Being unable to select menu items from Menu Bar menus.
 |- noticed that when trying to select menu items from dopdown that overlap with IDE Text editor, Gamemaker captures those click events to move focus to the IDE and move the cursor etc.

- Menu Bar dropdowns remaining open when focus is moved from the menus to the IDE.

- Menu bar dropdowns remain open when clicking the Menu Bar menu label of the open dropdown. eg: click source control -> source control dropdown opens -> clicking source control again doesn't close open dropdown.

- Unable to tab through menu items.

### Steps To Reproduce
In a small sized project with Objects, Notes, Rooms, Scripts, Sprites, TileMaps  with source control enabled, make changes  in  assets totaling 5+ changes to stage. Editing images is more likley to reproduce this issue.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Mac 14.6.1

[1d082107-52ba-4221-8cee-83e0aa6a4d7f](https://api.gamemaker.io/api/github/downloads/1d082107-52ba-4221-8cee-83e0aa6a4d7f)

**Comment by SmithTom6304** [comment]
Have managed to reproduce this following the given steps.

**Comment by SmithTom6304** [comment]
Minimum repro:
1. Create a new empty project
2. Create and open a sprite
3. Edit the image and save the project
4. Open the source control menu
5. Repeat steps 3 & 4 a handful of times, observe everything works correctly
6. Enable source control on the project
7. Create the project repository
8. Repeat steps 3 & 4 a handful of times, observe the menu gets stuck

This only seems to occur with the source control menu.

**Comment by hegner123** [comment]
Thanks for fixing this. You guys rock!

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.614  Runtime v2024.800.0.637.
