### ISSUE TITLE
Exporting to GX Games doesn't work

### ISSUE THREAD

**Issue by samuelmacari** [YoYoGames/GameMaker-Bugs#7197]
### Description

So, I have some issues with GameMaker & GX.Games:

1. I've uploaded several games months ago, and one of them now for some reason, I cannot update it from GameMaker, it fails to "sync" with it on GX, asking me to create a new game, yet the name is already taken and I want to update it.
2. I've tried to upload a new game (brand new) today, and after registering it from the Game Options, it "lost" it immediately, asking me to create a new game (which is impossible because name already exist bla bla bla)

### Expected Change

For GX.Games to properly work

### Steps To Reproduce

1. Start GameMaker
2. Export a game to GX.Games
3. It won't work because of "Incorrect data"
[contactuspackage.zip](https://github.com/user-attachments/files/16563835/contactuspackage.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Can see you closed it yourself, so good to hear you got it all sorted.
