### ISSUE TITLE
In-Game: Alarm event not triggering after switching room in HTML5 but does trigger in Win

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#72]
GM-7100

Description:
there appears to be a bug in the HTML build when
triggering an alarm event after switching rooms.

the create event in obj_test triggers alarm 1,
but this is done after a call to room_goto.

note that obj_test is flagged persistent.

in a Windows builds, execution is correct:

CREATE EVENT START
ALARM EVENT START
USER EVENT
ALARM EVENT DONE
CREATE EVENT DONE

in an HTML5 build, the alarm does not trigger:

CREATE EVENT START
CREATE EVENT DONE

obviously an easy work around is to trigger the
alarm before switching room, so I am going to
do that, but I am reporting the bug nonetheless.

Steps
- download and extract the project from the zip and open in IDE
- run in Win, notice the 5 outputs
- rerun in html5 and notice only the start and finish outputs

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.410  Runtime v2023.1100.0.433
