### ISSUE TITLE
Building Projects: Dot notation for certain macros which are expressions causes a compile error

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#7202]
### Description
Related to #2864: while macros that use expressions representing variables will now work with dot notation (eg `instance.ME` for `#macro ME  id`), macros with other expressions will not work, even though the expressions themselves would work if they weren't represented by a macro.

These examples:
```gml
#macro bbox bbox_right - 1
#macro variable id[$ "thing"]

show_message(self.variable)
show_message(self.bbox)
```
Will create the compile errors `[...] is a macro and cannot be used as an instance variable`

### Steps To Reproduce
^put the above into an instance's create event and place it in a room - it will not work.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[4398434b-7e63-4cfa-aba0-278ecd2bc934](https://api.gamemaker.io/api/github/downloads/4398434b-7e63-4cfa-aba0-278ecd2bc934)

**Comment by rwkay** [comment]
This is intentional a macro should not be abused in this way as a partial part of a variable reference
