### ISSUE TITLE
Stability: Any crashes/errors with the LSP server should result in it being restarted automatically

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7205]
### Description
I was just putting together a sample project for a different bug, and while clicking some stuff in the inspector, GM suddenly froze and then went unresponsive. It stayed unresponsive for maybe 10-20 seconds before finally unfreezing, and then I noticed that the CE2 language server seems to not be loaded anymore, as no highlighting, autocomplete, tooltips, etc. were working. I don't know if the freeze is actually CE2's fault, I'm just guessing based on the language server going byebye.

![image](https://github.com/user-attachments/assets/2cb01b8e-77a7-4c40-9876-76bcdbde2efc)

After it unfroze, language server gave up and went home:

https://github.com/user-attachments/assets/c6d5b8be-f00b-48dd-ac07-a252034640e9

Unlike #7161, the language server was not completely gone, as reloading the project without restarting GM made things work again.

### Steps To Reproduce
I have no idea, it just kind of happened :( What I did prior to it happening was I deleted some old assets, I don't remember what exactly they were. Then I created 3 new objects, oTest, oTest2, and oTest3. I went into the inspector for oTest, and accidentally clicked on the physics dropdown while trying to click the parent dropdown. After opening the physics dropdown, GM froze and went unresponsive. I clicked on the parent dropdown right as it started being frozen, and the dropdown was open when it unfroze.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[ca11c740-281b-4a4a-9dab-3fd5449ae5cd](https://api.gamemaker.io/api/github/downloads/ca11c740-281b-4a4a-9dab-3fd5449ae5cd)

**Comment by zreedy** [comment]
The `ui.log` does not indicate anything as to what happened here. It's possible that some operation timed out due to the server crashing and thereafter no services would be available.
As such, this ticket is not really addressable currently. However, if a Language Server crashes, it should automatically be restarted which is not currently done. This should be fixed as apart of marking this ticket as complete.

**Comment by zreedy** [comment]
LSP Servers are now restarted a maximum of 3 times per session. If a Server crashes more than this limit then it will remain disabled until the User restarts the IDE. Notifications are toasted to indicate if a server has been restarted after a crash, or if it no longer will be restarted and remain unavailable for the rest of the IDE session.

**Comment by sihammill** [comment]
Tested as per the repro steps and all appears to working as expected in IDE v2024.1100.0.646  Runtime v2024.1100.0.666
