### ISSUE TITLE
Building Projects: [Android] Also force-stop all Gradle daemons when doing a Clean

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#7209]
### Is your feature request related to a problem?

OpenJDK Platform binary sometimes doesn't stop execution after building for Android.
When trying to clean up the build, clean up will also fail due to OpenJDK Platform binary process is still using the build folder and files. Users would have to launch Windows task manager and kill the OpenJDK Platform binary process manually.

It seems that this behavior can be avoided if the clean build button also force stops the gradle daemon.
[Reference](https://stackoverflow.com/questions/68287913/why-does-openjdk-platform-binary-stucks-open-and-use-too-much-ram)

### Describe the solution you'd like

I don't really know what the gradle daemon is, so just please handle it gracefully so the clean build button doesn't fail to execute.

**Comment by caroparo** [comment]
More specifically, the error on clean build is:

> System.IO.IOException: The process cannot access the file 'classes2.dex' because it is being used by another process.
>    at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
>    at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
>    at System.IO.Directory.Delete(String path, Boolean recursive)
>    at Igor.Utils.CleanDirectory(String directoryPath)
>    at Igor.BaseTargetBuilder.CleanCacheDirectory(String subdir)
>    at Igor.BaseTargetBuilder.Clean()

**Comment by mgeddesGM** [comment]
as of Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652, OpenJDK  is cleared on clean but remains on build fail

**Comment by mgeddesGM** [comment]
verified as of Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652
