### ISSUE TITLE
Manual Content: Pages for phy_position_xprevious/yprevious incorrectly say they can be set manually, but these are read-only

### ISSUE THREAD

**Issue by Glim888** [YoYoGames/GameMaker-Bugs#7210]
### Description

phy_position_xprevious / phy_position_yprevious is readonly (but docs say it can be set)

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FPhysics%2FPhysics_Variables%2Fphy_position_xprevious.htm

**Comment by gurpreetsinghmatharoo** [comment]
Thank you!

**Comment by alicemoretti** [comment]
Verified fixed in the latest Manual Beta build. Thank you.
