### ISSUE TITLE
GMRT: upper limit to vertex buffer size

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7219]
### Description
There's no upper limit to vertex buffer size (within reason)in current runtime, but in GMRT it appears to be around 2^28 (256 MB).

I'm not sure if this is a "bug" or just a limitation of the newer graphics api. A quarter gigabyte isn't an unreasonable limitation, and if that's how things work from now on it should probably be documented somewhere.

### Steps To Reproduce
1. Run the sample project on GMRT (yes it's the same as all the other samples i've sent in this weekend)
2. it's fine
3. Change the TREE_COUNT macro (Camera Create line 57) to 6800
4. Run the project on current runtime
5. it's fine
6. Run the project on GMRT
7. It's no longer fine

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.606 Runtime v2024.800.0.630

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[c3890fc4-8cde-41ad-9d43-223d9170c8ca](https://api.gamemaker.io/api/github/downloads/c3890fc4-8cde-41ad-9d43-223d9170c8ca)

**Comment by scott-dunbar** [comment]
Verified fixed as per this commit 

"Maximum size of created vertex buffer is no longer 256MB, instead it's determined automatically by maximum supported limits of user's HW."

13.8
