### ISSUE TITLE
Manual Content: flexpanel_node_get_child/struct() pages each have a small spelling error

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#7221]
### Description

On the page: flexpanel_node_get_child():

> The function will return**ed** undefined

On the page: flexpanel_node_get_struct():

> This struct follows the structure**d** described here

**Comment by gurpreetsinghmatharoo** [comment]
Thank you

**Comment by alicemoretti** [comment]
Verified fixed on the newest Manual Beta build. Thank you.
