### ISSUE TITLE
In-Game: Repeatedly reusing surfaces containing alpha as the basis for new surfaces creates distortion on the resulting images

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#7223]
### Description

When a image from a sprite or surface it's draw on a surface and image contains alpha the image get color distortion, and get more evident if you repeat the process more than one time.

In this image you can see the original sprite at the left, this sprite contains columns of red color with alpha = 255,200,150,100. each image at the right it's a cycle drawing in a surface. easy to see the distortion.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/3c2388ea-f5b8-4b59-8e6f-057908730c0e">

Project attached:
[Surfaces Bug.zip](https://github.com/user-attachments/files/16579525/Surfaces.Bug.zip)

### Steps To Reproduce

1. Start GameMaker
2. Run the project
3. Focus in the colors
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, macOS, Ubuntu, Android, GX.games, HTML5, iOS, PlayStation 4, PlayStation 5, Switch, tvOS, Xbox (GDK)

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
For documentation purposes, we have the following guide which should explain what is going on: https://gamemaker.io/en/blog/alpha-and-surfaces
