### ISSUE TITLE
In-Game: [Ubuntu] Does not support the "-game" launch parameter

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#7225]
### Description
Due to a quirk in the Linux runner, it is impossible to use the `-game` launch parameter like on Windows to override the working directory and the path to the WAD.
The Linux runner will always append `" -game game.unx"` at the end of the command line buffer thus negating any previous usages of the `-game` parameter.
Even if one were to patch the check, the function that returns the current directory in the LoadSave class always allocates an empty string on Linux, thus the runner will always read from the current directory which is not desirable if `-game` was used.

Expected Change:
Make the -game launch parameter work exactly like on Windows

### Steps To Reproduce
1. Start GameMaker
2. Create any project and build it into a Linux zip
3. Extract the zip on a Linux machine, move the runner executable somewhere else
4. Try to run the game via `./runner -game /path/to/the/assets/game.unx` (assuming you've also set LD libs properly, or doing this on an ARM device where this is not necessary)
5. See the issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Ubuntu

[6264ea5f-fb25-4624-af02-e4a216881ef5](https://api.gamemaker.io/api/github/downloads/6264ea5f-fb25-4624-af02-e4a216881ef5)

**Comment by yoyo-danielc** [comment]
Fixed on 2024.010 branch.

QA Note: The (bundle) path handling on the Linux runner has been refactored, I've given it a cursory retest of loading assets from the bundle (using `sprite_add()`), but would probably be worth some further testing here.

**Comment by Emc1923** [comment]
Verified done as of  IDE v2024.1100.0.626  Runtime v2024.1100.0.652 (libssl1.0-dev needed)
