### ISSUE TITLE
In-Game: [Ubuntu] window_center() causes a memory leak each time it is called

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7231]
### Description
As per a recent discovery, it has been noted that window_center() seems to be leaking memory. I threw together a small sample project to check, with a repeat loop of 100. And it was indeed building up in memory. I've tested this on a few linux devices, including Ubuntu on WSL2.

### Steps To Reproduce
1. Run project
2. Check memory usage

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.1.160 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Ubuntu

[8cf93f0a-b616-40cb-9716-9e091c65e242](https://api.gamemaker.io/api/github/downloads/8cf93f0a-b616-40cb-9716-9e091c65e242)

**Comment by rwkay** [comment]
Fixed in 2024.8
