### ISSUE TITLE
Sequence Editor: Hotkeys for editing a curve do not work

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#7233]
### Description

In the Sequence Editor, when editing curves via Curve Mode, the hotkeys for renaming (F2), copying (Ctrl+C) and pasting (Ctrl+V) do not work. 

https://github.com/user-attachments/assets/1290f75e-3a3a-4e71-b21e-63fe77694aa3

Tested using IDE v2024.800.0.607  Runtime v2024.800.0.631

[Contact Us Package](https://api.gamemaker.io/api/github/downloads/5844f9dc-ad9f-4811-ad52-e7979c211bb3)

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Create a Sequence and a Sprite
4. Drop the Sprite into the Sequence and add a paramter track (such as Position)
5. Right-click the track and select "Convert to Curve", and then double-click it to edit it
6. Attempt to use any of the context menu hotkeys on either the X or Y curve
7. Observe the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708. Awaiting docs.

**Comment by YYBartT** [comment]
No changes should be needed to the manual for this, as confirmed with @SmithTom6304.
