### ISSUE TITLE
In-Game: [Ubuntu] Projects crash during startup in 2024.800 runtimes if the machine does not have PulseAudio installed

### ISSUE THREAD

**Issue by yoyo-danielc** [YoYoGames/GameMaker-Bugs#7234]
### Description

When running on a machine that isn't using PulseAudio (I'm using plain ALSA here), the runner segfaults during initialisation:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000dbcd3b in yyal::log::error<>(char const*) (format=0xf6259e "Error: PulseAudio context is in a failed state\n") at /tmp/YYAL/src/YYAL_Internal.h:204
#2  0x0000000000df71b6 in PulseAudio::ContextStateCallback (context=0x162b7a0, userdata=0x0) at /tmp/YYAL/src/YYOpenAL/PulseAudio/ALCdevice_pulseaudio.cpp:215
#3  0x00007ffff700ee77 in ?? () from  <appimage>/usr/bin/../lib/libpulse.so.0
#4  0x00007ffff700f7ef in ?? () from  <appimage>/usr/bin/../lib/libpulse.so.0
#5  0x00007ffff700fa5b in ?? () from  <appimage>/usr/bin/../lib/libpulse.so.0
#6  0x00007ffff701035a in pa_context_connect () from  <appimage>/usr/bin/../lib/libpulse.so.0
#7  0x0000000000df71fb in PulseAudio::ContextConnect (context=0x162b7a0, server=0x0, flags=PA_CONTEXT_NOFLAGS, api=0x0)
    at /tmp/YYAL/src/YYOpenAL/PulseAudio/ALCdevice_pulseaudio.cpp:238
#8  0x0000000000df64bb in PulseAudio::PulseAudio (this=0x15eb470 <s_pulseAudio>) at /tmp/YYAL/src/YYOpenAL/PulseAudio/ALCdevice_pulseaudio.cpp:158
#9  0x00000000004156c7 in __cxx_global_var_init () at /tmp/YYAL/src/YYOpenAL/PulseAudio/ALCdevice_pulseaudio.cpp:583
#10 0x0000000000415799 in _GLOBAL__sub_I_ALCdevice_pulseaudio.cpp () at /tmp/YYAL/src/YYOpenAL/PulseAudio/ALCdevice_pulseaudio.cpp:763
#11 0x0000000000e2707d in __libc_csu_init ()
#12 0x00007ffff6e462df in __libc_start_main_impl (main=0xd9bb20 <main(int, char**)>, argc=1, argv=0x7fffffffe278, init=0xe27020 <__libc_csu_init>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe268) at ../csu/libc-start.c:343
#13 0x0000000000416b85 in _start ()
```

### Steps To Reproduce

1. Configure a Linux machine using ALSA rather than PulseAudio
2. Run a game on it

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Ubuntu

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Note that pulseaudio is already documented as being required as of Aug 2024 Betas, due to the comment https://github.com/YoYoGames/GameMaker-Bugs/issues/6317#issuecomment-2217995288

https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu

**Comment by stuckie** [comment]
Should also ensure that it's marked as a dependency on the IDE .deb

**Comment by toby-yoyo** [comment]
- Moved PulseAudio init from global init to device init, fixing the crash here.
- Also added the old OpenAL device as a fallback for when PulseAudio fails to initialise.
- If the OpenAL device also fails, we will fallback to the null device, which outputs no audio.

**Comment by yoyo-danielc** [comment]
Happy to confirm beta runtime v2024.800.0.635 doesn't crash on my Linux PC any more and has sound!
