### ISSUE TITLE
Add a feature for GX.games team to hook the unhandled exception handler at the browser Javascript level

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#7235]
### Is your feature request related to a problem?

GX games just die with an alert box that is unsightly and game developers do not know how often their game is failing.

### Describe the solution you'd like

Allow the GX.games team to provide an unhandled exception handler so they can display something nicer to the user AND they can record the information to expose the information to the developer (to see crash rates and call stack).

Ideal interface would be to expose a JS function that tells the Runner to pass a JS object to a JS callback function with the exception struct (as described in https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Debugging/exception_unhandled_handler.htm ).

So something like `gx_set_default_unhandled_exception_handler( _callbackFunction )` where the `_callbackFunction` will take a single parameter that is the JS object.

Question: Would GX team like to pass in a context object that would also be passed to the `_callbackFunction`???

**Comment by emoller** [comment]
> Question: Would GX team like to pass in a context object that would also be passed to the _callbackFunction???

No I don't think we need this. It would be the game wrapper that both sets the handler and use the data and it should have what it needs (i.e. game id etc). That said, if it's easy to add it really wouldn't hurt and could save us some time down the line if requirements change.

**Comment by rwkay** [comment]
Fixed in 2024.8 it should be in next weeks Beta

**Comment by YYDan** [comment]
@emoller Everything okay with this change as far as you're concerned?

**Comment by emoller** [comment]
Sorry about the extremely late answer, I only just got around to testing it. It does work. Question is if we could make the output more structured or get some more explanations of the data. This is the output:
```
{
  "line": 0,
  "stacktrace": [
    "gml_Script_do_something@gml_Object_test_object_Create_0 (line -1)",
    "gml_Object_test_object_Step_0"
  ],
  "message": "Variable <unknown_object>.do_crash(100004, -2147483648) not set before reading it.",
  "longMessage": "ERROR in action number 1\nof  Step Event0 for object test_object:\nVariable <unknown_object>.do_crash(100004, -2147483648) not set before reading it.\nat gml_Script_do_something@gml_Object_test_object_Create_0\n",
  "script": "gml_Script_do_something@gml_Object_test_object_Create_0"
}
```

So, in the stacktrace components are separated by _ but function names and objects can also contain _ so question is if this is always parseable?

`gml_Script_do_something@gml_Object_test_object_Create_0 (line -1)`

It's a `gml_Script` called `do_something` on the `gml_Object` called `test_object`. If that's available as structured data it would be nice to output it that way. What is the `Create_0 (line -1)` bit about?

What do the numbers in here mean `Variable <unknown_object>.do_crash(100004, -2147483648) not set before reading it.` ?
