### ISSUE TITLE
In-Game: [Windows] TCP max connections cannot exceed 64 since 2024.4, despite the manual saying 1024

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#7236]
### Description

Hello, we are running a game service and we were told that Windows allows 1024 connections to the socket as described in the manual.

However, I've noticed that the April and June versions are currently disconnecting after 64 seconds.

This is a critical issue for our games already in service, and we are reporting this as a matter of urgency.

Please see the 

https://github.com/YoYoGames/GameMaker-Bugs/issues/2661

where I read something similar to this, but now it's the other way around and Windows is limiting access to 64.

We've already decided that there's nothing wrong with the manual, so we've pushed the version and can't revert it.

operating systems we tested for this issue are Windows 10 and Windows Server 2019.

### Expected Change

windows can connection 64 -> 1024

### Steps To Reproduce

1. Download https://github.com/YoYoGames/GameMaker-Bugs/issues/2661 Project Server & Client
2. Start GameMaker
3. Open Client and Copy more instance 64+
4. Open Server
5. Run Server
6. Run Client
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fix merged to the 2024.10 branch, this looks to be a regression from 2024.04.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.611  Runtime v2024.800.0.635
