### ISSUE TITLE
Add a new constant "GM_project_folderpath" to get the just path to the project, not the project file name also

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7238]
### Is your feature request related to a problem?

In order to make Live Reload work for my UI library, I need to be able to get the local project folder path. Currently the best way I know how to do this is via the `GM_project_filename` constant, which gives the full filepath including the project filename. My previous solution was to then trim the project name off the end by accessing `game_project_name`. However I recently discovered that certain characters in the actual project name will be replaced with underscores, e.g. `.` and ` `.``

### Describe the solution you'd like

Given that what I really want (and anyone else making a live reload system, of which I know multiple) is just the folder path, I would like a macro that just gives us the folder path

### Describe alternatives you've considered

Currently my best solution is to mimic the string replacement logic:
```gml
		var sanitized_name = string_trim_end(GM_project_filename, [".yyp"]);
		sanitized_name = string_replace_all(sanitized_name, " ", "_");
		sanitized_name = string_replace_all(sanitized_name, ".", "_");			
		
		// get the datafiles folder path from the project file path
		var project_folder = string_trim_end(sanitized_name, [game_project_name]);
```
The problem with this is that I don't know what all characters actually get replaced by the internal GM logic so this code is liable to break as soon as anyone uses a character in their project name that my code is not expecting.

**Comment by rwkay** [comment]
Just use the function https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/File_Handling/File_System/filename_path.htm

`filename_path( GM_project_filename)`

**Comment by YYDan** [comment]
Was about to say the same thing ;)

**Comment by stuckie** [comment]
Closing as above
