### ISSUE TITLE
In-Game: window_center() does not work correctly after exiting fullscreen if the window size was changed while in fullscreen

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7240]
### Description
If you call window_set_size to change the window size while currently in fullscreen, then turn off fullscreen, and then call window_center 1 frame later, the window will not actually get centered. The documentation for window_center says it needs to be called at least 1 frame later, but I am needing to set my alarm to as high as 10 frames to get it to consistently center after exiting fullscreen, even 5 frames is inconsistent on if it will center properly or not.

This issue does NOT happen when I test with GMRT, so I believe it is a GMS2 runtime issue and not something weird with my PC. It happens for both GMS2 VM and GMS2 YYC.
My monitor resolution is 1920x1080, it does seem to be off-center in different ways depending on if the window resolution is smaller or larger than my monitor resolution.

https://github.com/user-attachments/assets/3d17d344-ad54-46eb-abe4-b7c2f863346d

### Steps To Reproduce
Open the sample project, and then follow these steps:
1. Run the game
2. Press the up arrow key to set resolution to 1366, 768
3. Press space to toggle fullscreen off
4. The "Centered" debug message will appear, but the window will not be centered.
5. Press the down arrow and then up arrow to change the window size twice and center it twice, it will center properly
6. Press space again to fullscreen while the resolution is 1366, 768
7. Press the down arrow key to set the resolution to 1920, 1080 while fullscreen
8. Press space again to exit fullscreen. The window will not be centered

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[2a42e442-83b8-4058-9769-fd1a9458bd7d](https://api.gamemaker.io/api/github/downloads/2a42e442-83b8-4058-9769-fd1a9458bd7d)

**Comment by DragoniteSpam** [comment]
the word "window" no longer sounds like a real word

**Comment by stuckie** [comment]
We should document that for the current GMS2 Runtime, users will need to wait 10 frames for the device to settle before calling window_center.

**Comment by alicemoretti** [comment]
Verified that a note has been added to the manual page for window_centre() in the newest build of the Beta Manual. Thank you.
