### ISSUE TITLE
In-Game: audio_group_load() on a group that isn't unloaded prints an error message which failed to retrieve the audio group name

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7241]
### Description
Note: This is already fixed.

When calling `audio_group_load` on a group which isn't unloaded, an error message is printed:
```
audio_group_load() -> Group '(null)' is not unloaded
```

In that message, `(null)` should be replaced by the audio group's name.

### Steps To Reproduce
- Open and run the example project.
- Observe the error message in the console.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[7c6d27bb-ecd2-47b1-b015-111f199b51e3](https://api.gamemaker.io/api/github/downloads/7c6d27bb-ecd2-47b1-b015-111f199b51e3)

**Comment by toby-yoyo** [comment]
- Fixed the retrieval of the audio group name.
- Clarified the current state of the audio group in the message ('currently loading/unloading/already loaded' as opposed to 'not unloaded').

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.615  Runtime v2024.800.0.638
