### ISSUE TITLE
Redefine Keys: Remapping a hotkey does not update the display for all menu entries sharing the hotkey

### ISSUE THREAD

**Issue by SmithTom6304** [YoYoGames/GameMaker-Bugs#7244]
### Description

In redefine keys, hotkeys used in multiple locations will have a separate menu entry for each location. Remapping one of these should update the display for all of them, but this is not the case in  IDE v2024.6.0.157  Runtime v2024.6.0.205.

### Expected Change

All menu entries displaying the hotkey should be updated, including while the combo is entered.

### Steps To Reproduce

1. Open Redefine Keys
2. Search for "Add Frame"
3. See two entries, one for Sprite Editor and one for Image Editor
4. Begin remapping one, and see the other is not updated
5. Finish remapping one, and see that the other is still not updated

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
Should now be fixed. This affects remapping an entry, an entry being a conflict and getting reset, and finally clearing an entry.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.800.0.613  Runtime v2024.800.0.636, thanks.
