### ISSUE TITLE
Room Editor: Editing inherited layers in a child room causes the IDE to go unstable

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7246]
### Description

Original issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/1856. 

Manipulating inherited layers from a child room causes the IDE to go unstable as shown in the video: 
https://youtu.be/vDVPP9Ve9kw?si=na1k26yehlB-rydM 

### Steps To Reproduce

1. Start GameMaker
2. Import the attached project
3. Open the parent room 
4. Add a new layer
5. Go to the 'Game' layer and delete the chest instances
6. Create a new parent layer and paste the chest instances
7. Go to one of the child rooms, click on 'inherit' to inherit the layers of the parent room 
8. Observe the layers will be pushed to the bottom
9. Reorganise the layers 
10. See the issue

Project link: https://api.gamemaker.io/api/github/downloads/24ad35e0-3d11-4ed2-ae26-9b962f825f7a

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment]
The unstable error is caused by same problem as fixed for https://github.com/YoYoGames/GameMaker-Bugs/issues/7242 - the child items still reference deleted parent item when that is deleted. So this should fix the unstable error.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.800.0.612  Runtime v2024.800.0.636
