### ISSUE TITLE
Preferences: Restoring defaults will fail to restore default Path to HTML5 Runner in Preferences>Platform Settings>HTML5 in 2024.800 Betas

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7255]
### Description

In Preferences>Platform Settings>HTML5, when a non-default Path to HTML5 Runner is set, pressing the "Restore defaults" button will appear to reset it to it's default value of `${html5_runner_path}`, but if you come out of the preferences menu and go back in, it seems to go back to the previously inputted value.

_Note that this does not happen in 2024.6, so is a recent break only in 800 Betas._

![image](https://github.com/user-attachments/assets/d9b96bd0-5b95-4b13-af18-ac9f8cf66cd0)

https://api.gamemaker.io/api/github/downloads/87a7c47c-0225-4831-b8c2-b75ab0b1f608

### Expected Change

The "Restore defaults" button should restore "Path to HTML5 Runner" to a default value of `${html5_runner_path}` 

### Steps To Reproduce

1. Start GameMaker
2. Open Preferences>Platform Settings>HTML5
3. Change "Path to HTML5 Runner" to a valid path to a new HTML5 runner (This can be cloned from [here](https://github.com/YoYoGames/GameMaker-HTML5))
4. Press Apply
5. Press Restore defaults
6. Close Preferences
7. Re-Open Preferences>Platform Settings>HTML5
8. Observe "Path to HTML5 Runner" being reverted to the previously inputted value

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Was actually due to a leak in preferences where the previous gadget was still active, and therefore overwriting the value.

**Comment by YYDan** [comment]
Note that the fix here applies to far more than just this one field documented in the repro steps - modifying potentially any text field Preference, saving the change, resetting to defaults, then modifying it with a different value, attempting to save the second value could restore the _first_ one.

We need to test a wide variety of different Preferences fields and make sure all is well when repeatedly resetting to defaults and changing values before we confirm that this is fixed.

**Comment by cameron-home** [comment]
Checked in multiple different Preferences and all of them reset as we would expect so verifying as fixed in IDE v2024.8.0.168  Runtime v2024.8.0.215
