### ISSUE TITLE
[iOS] draw_rectangle(0, 0, gui_width, gui_height) is offset in portrait mode, and possibly in landscape mode too

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7256]
### Description
The sample has a background layer of blue color and it calls draw_rectangle(0, 0, gui_width, gui_height) to draw a black recangle to cover the entire GUI. However, on iOS in portrait orientation, the top of the GUI is not covered and still show the blue background. This does not happen on Android.

### Steps To Reproduce
1. Run the sample on Android VM. See that when you flip the phone between portrait and landscape orientation, the entire screen is black.
2. Run the sample on iOS VM. See that in landscape orientation, the entire screen is black, but in portrait mode, there is a blue line on the screen

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
iOS

[f6abaad9-4327-45a6-a748-28f35d37f880](https://api.gamemaker.io/api/github/downloads/f6abaad9-4327-45a6-a748-28f35d37f880)

**Comment by shichen85** [comment]
![image](https://github.com/user-attachments/assets/ec7bce31-22e6-4a4c-b074-bbed5e36bb43)

**Comment by shichen85** [comment]
Possibly related: in Crashlands 2, we are observing that when we try to draw a black rectangle that's meant to cover the entire screen on the GUI layer, the rectangle is also offset a little. However, it behaves differently on iPhone versus on iPad. On iPhone, the offset occurs on the top of the GUI, similar to the sample where the blue line is on the top of the GUI. On iPad, the offset occurs on the left of the GUI.
![ApplicationFrameHost_cbxv834H8o](https://github.com/user-attachments/assets/54cf61f0-34fc-4df2-b85a-41e822031b27)
![ApplicationFrameHost_p8Nayx77N9](https://github.com/user-attachments/assets/12a76641-23de-4370-9cb2-9c4570c14745)

**Comment by SamTHodson** [comment]
Verified fixed in Beta IDE v2024.800.0.618  Runtime v2024.800.0.642
