### ISSUE TITLE
Manual Content: delta_time()'s page text incorrectly uses the word "so" instead of "to"

### ISSUE THREAD

**Issue by Douglas711** [YoYoGames/GameMaker-Bugs#7270]
### Description

At the end of the page there is a small typo, I believe. The word "so" should be "to".

_Original text:_ "The above code will set the speed of the instance using delta-time to correct for lag. The variable "_dt" would be used to hold the previously calculated delta time value so that the ratio can be used to multiply the base speed value (held in the variable "spd") and **so** get a consistent speed for the instance."

_Corrected text:_ "The above code will set the speed of the instance using delta-time to correct for lag. The variable "_dt" would be used to hold the previously calculated delta time value so that the ratio can be used to multiply the base speed value (held in the variable "spd") and **to** get a consistent speed for the instance."

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Maths_And_Numbers/Date_And_Time/delta_time.htm

**Comment by Douglas711** [comment]
*...incorrectly uses the word "so" instead of "to"

**Comment by gurpreetsinghmatharoo** [comment]
Thank you

**Comment by alicemoretti** [comment]
Verified fixed in the latest Manual Beta build. Thank you.
