### ISSUE TITLE
Manual Content: Example for how the "self" keyword differs from "id" is nonsensical 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7274]
### Description

![image](https://github.com/user-attachments/assets/cc852f02-d562-4273-aa97-5874aee21d5d)

This code is a lot of extra steps that ultimately is just `// do something`, and doesn't really demonstrate the difference between `id` and `self`. Additionally, it says you need to use `self.id`, without specifying that `self.id` and just `id` by itself are functionally the same, which could be misleading. It's the second example under the "self" section on the linked page.

On another note related to self, I think it would be good to explain the fact that `self` for an instance is a struct, and that `self` stored in a variable on a different instance will continue existing even after instance_destroy is called on the instance the `self` belongs to. That means you could keep accessing the variables of the destroyed instance, which could lead to some unexpected results if you don't know about self being a struct.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Overview%2FInstance_Keywords.htm

**Comment by gurpreetsinghmatharoo** [comment]
Removed the example and added a note for `self` staying alive with references.

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
