### ISSUE TITLE
Manual Content: GX.games preferences doesn't mention Game Strips as an option for default packaging type

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7279]
### Description

In the GX.games preferences page on the Default packaging type option definition only mentions Game or Live Wallpapers.

### Manual Link

https://manual.gamemaker.io/monthly/en/Setting_Up_And_Version_Information/Platform_Preferences/GX_Games_Preferences.htm

**Comment by alicemoretti** [comment]
Verified fixed in the latest Manual Beta build. Thank you.
