### ISSUE TITLE
In-Game: Revert new 2024.800 Betas behaviour of throwing code errors for bad audio indices

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7284]
### Description
The recent audio library error changes included starting to throw for easily verifiable indices, i.e. those that are either permanent (assets) or whose lifetimes are within the full control of the user (emitters/dynamic assets etc).

Unfortunately this seems like it will be a high-impact change, and so we should probably move to printing a console message for 2024.8 and instead add an option to throw via a new audio function in 2024.10, as raised by https://github.com/YoYoGames/GameMaker-Bugs/issues/7285.

### Steps To Reproduce
- Open and run the example project.
- Observe that the game throws
- Expected behaviour is that the error should just be printed to the console.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[ca4de6e8-80bb-4fd6-80c2-21a0ed0553d0](https://api.gamemaker.io/api/github/downloads/ca4de6e8-80bb-4fd6-80c2-21a0ed0553d0)

**Comment by toby-yoyo** [comment]
Relates to, but is not the same as https://github.com/YoYoGames/GameMaker-Bugs/issues/7253

**Comment by toby-yoyo** [comment]
The new errors should just be printed to the console now.

**Comment by scott-dunbar** [comment]
Verified it now sends to output

Beta IDE v2024.800.0.613 Beta Runtime v2024.800.0.636
