### ISSUE TITLE
Add a function to toggle strict error handling for audio functions

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7285]
### Is your feature request related to a problem?

In 2024.8 we had intended to begin throwing for certain types of audio errors, but this has turned out to be a high-impact change (see https://github.com/YoYoGames/GameMaker-Bugs/issues/7284).

### Describe the solution you'd like

We should add an option to toggle stricter handling of audio errors via a new audio function. This will throw for:
- Bad indices passed to functions (e.g. an asset that doesn't exist).
- Bad values passed to functions (e.g. attempting to set an invalid falloff model, such as `-1`).
- Bad operations (e.g. attempting to record using an already active input device).

**Comment by jackerley** [comment]
I think the default should be for stricter handling of errors

**Comment by toby-yoyo** [comment]
Added the function `audio_throw_on_error`, which should toggle throwing behaviour for the error types in the description. The default behaviour will be to throw for these error types, and this can be suppressed by passing `false` to the function.

Note that 'bad sound instance' is a separate error type from a 'bad index', and will not be thrown for until we can make certain guarantees about their behaviour in the engine. Any error types not thrown for (including those suppressed by the new function) will have their error messages printed to the console.

Example project: [gmb-7285-x.zip](https://github.com/user-attachments/files/17016028/gmb-7285-x.zip)

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1100.0.626  Runtime v2024.1100.0.652. 

Thank you.
