### ISSUE TITLE
Manual Content: Do/Until page's final block of code has a couple of small typos

### ISSUE THREAD

**Issue by Douglas711** [YoYoGames/GameMaker-Bugs#7286]
### Description

The final block of code declares 2 local variables. However, inside the loop the "y" variable is used in an if statement, instead of the local var "_y".

_Original Code:_ 
```
do
{
    var _x = random(room_width);
    var _y = random(room_height);
    if (instance_position(_x, y, obj_Enemy)
    {
        continue;
    }
    instance_create_layer(_x, _y, "Instances", obj_Enemy);
}
until (instance_number(obj_Enemy) >= 10);
```

_Corrected Code:_
```
do
{
    var _x = random(room_width);
    var _y = random(room_height);
    if (instance_position(_x, _y, obj_Enemy)
    {
        continue;
    }
    instance_create_layer(_x, _y, "Instances", obj_Enemy);
}
until (instance_number(obj_Enemy) >= 10);
```

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2Fdo___until.htm

**Comment by jackerley** [comment]
Also missing a closing ) on the instance_position call

**Comment by gurpreetsinghmatharoo** [comment]
Thank you!

**Comment by alicemoretti** [comment]
Verified fixed on the newest Beta Manual build. Thank you.
