### ISSUE TITLE
Building Projects: [HTML5] Dynamic texture groups and alternate texture group formats do not work, images are always just regular .png

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7288]
### Description

When targeting HTML5, texture groups will always be formatted as PNGs, regardless of the format they are set to be saved as in Tools>TextureGroups>Texture Group Format, and cannot be loaded dynamically, regardless of whether they are set as Dynamic or not in Tools>TextureGroups>Texture Group Type

### Texture Group Format difference
**When Texture Group Format is set to BZ2 + QOI**

![image](https://github.com/user-attachments/assets/4ff9db1a-c3dd-47c6-8daf-dedf2ab082ba)

**Targeting Windows results in:**
![image](https://github.com/user-attachments/assets/4d571a40-c6d5-44ea-b3c5-49b805a33600)

**Targeting HTML5 results in:**
![image](https://github.com/user-attachments/assets/079319ab-8f66-4424-b4fb-6adb67883e90)

### Texture Group Type difference
**When Texture Group Type is set to Dynamic**

![image](https://github.com/user-attachments/assets/868f981e-07b5-48f3-884d-96d1eb594076)

**Targeting Windows results in: (The green texture is set to be used as a fallback when a texture group is unloaded)** 
![image](https://github.com/user-attachments/assets/b6edf00d-3c75-4200-b2f9-6ae40a5a9009)

**Targeting HTML5 results in: (unable to unload texture groups)**
![image](https://github.com/user-attachments/assets/1cf68376-ed15-441c-8323-683746fbefb1)

https://api.gamemaker.io/api/github/downloads/143aefe1-8513-43a5-a3de-f70f2d82a37d

### Expected Change

Either HTML5 builds should be able to have non-PNG and dynamically loadable texture groups, or documentation/UI should be updated to take into account this lack of functionality.

### Steps To Reproduce

1. Start GameMaker
2. Open sample project
3. Go to Tools>Texture Groups
4. Observe the Texture Group Format being Different for each Texture Group and Texture Group Type being Dynamic for all Texture Groups
5. Run the project while targeting Windows
6. Press space to spawn a pink sprite, the Enter to unload its texture
7. Observe how it becomes green (this is the fallback texture set for when a texture can't be loaded)
8. Observe how the texture files (in C:\Users\[user]\AppData\Local\[GameMaker version]\GMS2TEMP\HTML5_Testing_[various numbers and letters]_VM) are all .yytex files (except the one in the Pink folder, which can be modified then reloaded with Enter to see it dynamically change)
9. Now close and re-run the project while targeting HTML5
10. Press space to spawn a pink sprite, then Enter to unload its texture
11. Observe how it doesn't become green, meaning that the texture couldn't be unloaded
12. Observe how the texture files (in C:\Users\[user]\AppData\Local\[GameMaker version]\GMS2TEMP\HTML5_Testing_[various numbers and letters]_Javascript\html5testgame) are all .png files (also no Pink folder exists, and modifying the pink texture will not cause it to dynamically change upon pressing Enter)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
HTML5 only supports png, sorry
