### ISSUE TITLE
In-Game: Re; Incrementing a constructor's static variable directly via operators gives an error

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#7295]
### Description
Statics are still broken in 2024.8 Beta 5. As previously seen in this previously closed report https://github.com/YoYoGames/GameMaker-Bugs/issues/7173 it seems only the ++ and -- operators were fixed. I opened a new report because more operators were found to be broken, which include the *= and /= operators.

Given this constructor:
```
function Hello() constructor
{
    static variable = 0;
    
    static add = function() {
        Hello.variable++;
    }
}
Hello();

//Hello.variable++; //works
//Hello.variable--; //works
//Hello.variable = Hello.variable + 1; //works
//Hello.variable = Hello.variable - 1; //works
//Hello.variable = Hello.variable * 2; //works
//Hello.variable = Hello.variable / 2; //works, even with 0
//Hello.variable -= 1; //broken
Hello.variable += 1; //broken
//Hello.variable *= 2; //broken
//Hello.variable /= 2; //broken

show_debug_message(Hello.variable);
```

The ones that show as broken are still broken.

### Steps To Reproduce
- Run the shown code or included project
- Uncomment each line that says broken
- Observe the errors

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.609 Runtime v2024.800.0.633

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[e802cbe0-cc1d-4a5e-8f72-3e7daf49c961](https://api.gamemaker.io/api/github/downloads/e802cbe0-cc1d-4a5e-8f72-3e7daf49c961)

**Comment by YYDan** [comment]
Reopened the original and added the new info.
