### ISSUE TITLE
Manual Content: Typo in access key build command on Building via Command Line page

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7299]
### Description

On the [Building via Command Line](https://manual.gamemaker.io/monthly/en/Settings/Building_via_Command_Line.htm) manual page, in the Access Key section, the command `igor runtime FetchLicences -ak=<KeyFromSite> -of=<OutputFileName>` has a typo, and should be `igor runtime FetchLicense -ak=<KeyFromSite> -of=<OutputFileName>`

![image](https://github.com/user-attachments/assets/e8ff30f9-afe8-49ac-b12d-4c8820e5167f)

### Manual Link

https://manual.gamemaker.io/monthly/en/Settings/Building_via_Command_Line.htm

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
