### ISSUE TITLE
audio_is_playing() returns true forever on Linux when audio isn't available

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#73]
GM-7098

If libopenal.so isn't available on Linux, audio_play_sound() returns an ID as normal, but audio_is_playing() will keep returning true, so if your project is waiting for the audio to finish it will hang.

Test project attached (press space to play sound).

**Comment by toby-yoyo** [comment]
The [original issue](https://bugs.opera.com/browse/GM-7098) was closed and verified and appears in the [release notes](https://gms.yoyogames.com/release-notes-runtime.html) for 2023.8.
