### ISSUE TITLE
Manual Content: No mention of lack of support for Dynamic Textures or non-PNG Texture Group Formats in HTML5 builds

### ISSUE THREAD

**Issue by Indibulous** [YoYoGames/GameMaker-Bugs#7301]
### Description

The manual pages for [Dynamic textures](https://manual.gamemaker.io/monthly/en/Settings/Texture_Information/Dynamic_Textures.htm) and [Texture Groups](https://manual.gamemaker.io/monthly/en/Settings/Texture_Groups.htm) do not mention anywhere that Dynamic Textures or non-PNG Texture Group Formats are not supported in HTML5 builds. 

The Dynamic Textures page should have a note mentioning the lack of support for the feature in HTML5, as well as a note where it is mentioned in the Texture Groups page:

![image](https://github.com/user-attachments/assets/3a59daf2-8739-485d-8657-739f5799551a)

![image](https://github.com/user-attachments/assets/0a3abd4e-2129-4a15-bd8e-3e5aea2f5ca3)

And the Texture Groups page should feature a note mentioning the lack of support for non-PNG formats when describing the Texture Group Format option:

![image](https://github.com/user-attachments/assets/7d718faf-4aee-40cc-866e-87602fd690ff)

### Manual Link

https://manual.gamemaker.io/monthly/en/Settings/Texture_Information/Dynamic_Textures.htm and https://manual.gamemaker.io/monthly/en/Settings/Texture_Groups.htm

**Comment by alicemoretti** [comment]
Verified that a note has been added to both pages in the newest build of the Beta Manual. Thank you.
