### ISSUE TITLE
In-Game: audio_destroy_sync_group() causes crash with "OpenAL Error: 40961 (Invalid name)" in 2024.800 runtimes

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#7305]
### Description

On IDE v2024.800.0.609 Runtime v2024.800.0.633, using audio_destroy_sync_group() will cause any project to crash, even though the sync group exists. The output log states an OpenAL error,  this is also attached below.
[SyncGroupTest.zip](https://github.com/user-attachments/files/16627410/SyncGroupTest.zip)
[output log.txt](https://github.com/user-attachments/files/16627439/output.log.txt)

### Expected Change

audio_destroy_sync_group() should not crash the game

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. In Create event, create a sync group with audio_create_sync_group()
4. Destroy the sync group with audio_destroy_sync_group()
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
- Fixed an issue where sync group sub-channels could attempt to clean up using an invalid source handle.

**Comment by scott-dunbar** [comment]
verified fixed in Beta IDE v2024.800.0.613 Beta Runtime v2024.800.0.636
