### ISSUE TITLE
Debugger: Breakpoints do not persist between IDE sessions

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#7306]
### Description

The serialization of breakpoints errors due to cyclic reference within the project structure. This error is logged to the `ui.log` as "BreakpointManager:Error saving data:..." (if the log level is high enough).

### Steps To Reproduce

1. Start GameMaker
2. Assign some breakpoints in any script, or object
3. Close the project by closing GameMaker
4. Restart GameMaker and open the project
5. Observe that the breakpoints are no longer present

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
This issue is fixed, it was discovered incidentally while addressing https://github.com/YoYoGames/GameMaker-Bugs/issues/5578
File for tracking purposes.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650
