### ISSUE TITLE
Manual Content: os_is_paused() documents incorrect effects on audio playback when resuming games

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7313]
### Description
The page for `os_is_paused` states:
```
NOTE: On mobile devices, sounds and music will be stopped when the os is paused.
They will not restart again unless you specifically start them with the appropriate function.
```
This is incorrect - for platforms which can lose focus in this way (Android/iOS/tvOS), the runner will pause the audio device when losing focus and resume it when regaining focus. The states of all sounds after regaining focus should be the same as they were before losing it.

Relevant forum thread: https://forum.gamemaker.io/index.php?threads/handling-music-with-os_is_paused-on-phones.114929/

### Manual Link
https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/OS_And_Compiler/os_is_paused.htm

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.609 Runtime v2024.800.0.633

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[3fd720c1-73ae-4098-90a0-b49016d02dd8](https://api.gamemaker.io/api/github/downloads/3fd720c1-73ae-4098-90a0-b49016d02dd8)

**Comment by Patchy-DaYo** [comment]
Confirmed. Audio always seems to resume properly.

**Comment by alicemoretti** [comment]
Verified that the note has been removed in the newest version of the Beta Manual. Thank you.
