### ISSUE TITLE
Code Editor 2: Restoring layout duplicates Document Windows each session, resulting in progressive performance impact and strange behavior

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#7318]
### Description

This is directly related to the workspace serialization for a fix to https://github.com/YoYoGames/GameMaker-Bugs/issues/5449.
The deserialization of the layout xml results in a duplicate window being produced for the (0, 0) cell of the restored `DocumentWorkspace`. This duplicated `DocumentWindow` is not visible, but _is_ linked to the same underlying in-memory `Document`. This results in both increasingly worse performance when closing and reopening the same project, and in strange behavior with `Document`-level operations reflected in satellite systems (e.g. Breakpoint, Bookmarks shift around strangely when lines are added or deleted due to the same change event being dispatched to the Document multiple times from each `TEP`).

Verification of this issue is checked against the saved layout.xml. The following is erroneous as the `x`/`y` (0, 0) is serialized twice instead of once.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ActiveConfig="Default" Platform="Windows" Runtime="VM" Device="Default">
	<Desktop x="0" y="23" width="1920" height="1137" id="19" title="TestProject - GameMaker-Dev" windowState="Maximized">
		<Workspaces>
			<Workspace active="False" chain="True" title="Workspace 1" localise_title="Workspace_TabTitle" localise_arguments="[&#xD;&#xA;    &quot;1&quot;&#xD;&#xA;]" workspace_offset="[0, 0]" workspace_scale="1" />
			<Workspace active="True" chain="False" title="Script1 Code" localise_title="DocumentWindow2_Title" localise_arguments="[&#xD;&#xA;    &quot;Script1&quot;&#xD;&#xA;]" workspace_offset="[0, 0]" workspace_scale="1">
				<Module Command="DocumentWindow2_RestoreLayout">
					<DocumentWorkspace resource="Script1">
						<Grid stylename="fullscreen_editor_window2" ...>
							<Cell row="0" column="0" stylename="fullscreen_editor_window2_panel" flow_index="0" />
						</Grid>
						<DocumentWindow x="0" y="0" vscroll="0.00" hscroll="0.00">
							<Editor resource="C:\[REDACTED]\TestProject\scripts\Script1\Script1.gml" cursorLine="11" cursorColumn="22" isFocused="True" />
						</DocumentWindow>
						<DocumentWindow x="0" y="0" vscroll="0.00" hscroll="0.00">
							<Editor resource="C:\[REDACTED]\TestProject\scripts\Script1\Script1.gml" cursorLine="11" cursorColumn="22" isFocused="False" />
						</DocumentWindow>
					</DocumentWorkspace>
				</Module>
			</Workspace>
		</Workspaces>
		<!-- ...Trunacted... -->
	</Desktop>
</Project>
```

### Steps To Reproduce

1. Start GameMaker
2. Open any project with CE2 enabled
3. Open any Script
4. Close project
5. Reopen project
6. Close project
7. Open the associated project's layout.xml file
8. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
This is already fixed, but was filed for tracking purposes (especially considering its severity).

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.626  Runtime v2024.1100.0.652
