### ISSUE TITLE
The example on the flexpanel_node_style_set_position page uses the wrong function

### ISSUE THREAD

**Issue by James-Dolinar** [YoYoGames/GameMaker-Bugs#7329]
### Description

The example on the manual page for [flexpanel_node_style_set_position()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position.htm&rhsearch=flex%20panels) uses the function [flexpanel_node_style_set_position()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position.htm&rhsearch=flex%20panels) to set the position type of the node when it should be using [flexpanel_node_style_set_position_type()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position_type.htm&rhsearch=flex%20panels).

![flexpanel_node_style_set_position_example](https://github.com/user-attachments/assets/c2cc377c-0d1d-487d-b03c-c470ad51c320)

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position.htm&rhsearch=flex%20panels

**Comment by gurpreetsinghmatharoo** [comment]
Thank you for the report. This is already fixed.
