### ISSUE TITLE
The example on the flexpanel_node_style_set_position_type page uses the wrong function

### ISSUE THREAD

**Issue by James-Dolinar** [YoYoGames/GameMaker-Bugs#7330]
### Description

The example on the [flexpanel_node_style_set_position_type()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position_type.htm&rhsearch=flex%20panels) page uses the [flexpanel_node_style_set_position_type()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position_type.htm&rhsearch=flex%20panels) function to set the position of the node when it should be using [flexpanel_node_style_set_position()](https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position.htm&rhsearch=flex%20panels)

![flexpanel_node_style_set_position_type_example](https://github.com/user-attachments/assets/12669e60-35cc-4438-879f-abe1c009b5b3)

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FFlex_Panels%2FFunction_Reference%2FStyling_Functions%2Fflexpanel_node_style_set_position_type.htm&rhsearch=flex%20panels

**Comment by gurpreetsinghmatharoo** [comment]
Thank you

**Comment by alicemoretti** [comment]
Verified fixed on the newest build of the Beta Manual. Thank you.
