### ISSUE TITLE
Macro comments when hovered

### ISSUE THREAD

**Issue by Ryuhouji** [YoYoGames/GameMaker-Bugs#7331]
### Is your feature request related to a problem?

It's not a problem, just a lacking functionality that can be annoying if you expect it.

### Describe the solution you'd like

I know that macros can be used for more than single word expressions or whatever and that this might by WHY it doesn't behave this way, but 

I would like to see the code editor display the comment that immediately comes after the macro definition when hovering over any use of the macro. For example, for my custom cutscene scripting system, i use macros as shorthand to make it faster to use. 

the full macro for SCRIPT.APPLYMOVEMENT looks like:
```
#macro move SCRIPT.APPLYMOVEMENT // 10 (npcId, moveArray) Send a provided movement array to a given object with the provided npcId.
```
When I use this macro somewhere else, and hover over it, it just says 
```
#macro move SCRIPT.APPLYMOVEMENT
```

I would like for it to show:

```
#macro move SCRIPT.APPLYMOVEMENT
10 (npcId, moveArray) Send a provided movement array to a given object with the provided npcId.
```

### Describe alternatives you've considered

Alternatively, allow JSDOCS to be provided to macros for the same experience.

**Comment by YYDan** [comment]
You already requested _basically_ this yourself: https://github.com/YoYoGames/GameMaker-Bugs/issues/6721

**Comment by Ryuhouji** [comment]
Sorry about that, i had _completely_ forgotten I already posted this. That's on me.
