### ISSUE TITLE
Add user events to an object's methods

### ISSUE THREAD

**Issue by arrosev** [YoYoGames/GameMaker-Bugs#7333]
### Is your feature request related to a problem?

If there are two different objects, I added the user event 0 to the first object, the instance of the first object is then created in the creation event of the second object. 
If I want to call the user event of an instance of the first object in the second object:
`duck = instance_create_layer(10, 10, "Instances", DucksObject);`
`with(duck) {
	event_user(0);
}`
It works, but it's too cumbersome.

### Describe the solution you'd like

Is it possible to have user events added to an object as a method with a certain name? For example, call user event 0 by "instance.event_user_test();", instead of the complex code above.

### Describe alternatives you've considered

I wish there was a way to add custom methods directly to the object so that I didn't need to use user events.
Then I call the instance method directly like this: 
`instance.event_user_test();`

**Comment by tabularelf** [comment]
You can just do that. Use the variables definition struct at the end of the `instance_create_*`functions.

**Comment by stuckie** [comment]
Closing as above.
We have no plans to expand on this further.
