### ISSUE TITLE
Live Wallpapers - Live wallpaper config menus not appearing on latest GX verisons

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#7342]
### Description
Cannot use the live wallpaper configurator on new projects in the latest GX Broswer.

### Steps To Reproduce
1. Update Opera GX To latest version -> (enable early bird in settings and go to opera://about to update) [LVL6 (core: 112.0.5197.74)]
2. Create new blank live wallpaper from live wallpaper template
3. Upload to GX.Create as a mod and download the mod
4. Cannot access or use live wallpaper configurator

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[e7897cfe-4e74-41cd-92bd-ada6e1f6ce74](https://api.gamemaker.io/api/github/downloads/e7897cfe-4e74-41cd-92bd-ada6e1f6ce74)

**Comment by ash0verride** [comment]
https://github.com/user-attachments/assets/0b9a4d1b-5bac-4095-b643-a56a212977ec

**Comment by ash0verride** [comment]
Disabling early bird seems to fix the issue it seems!

**Comment by ash0verride** [comment]
https://github.com/user-attachments/assets/f75189b8-ca1b-4a7c-8e7d-a0cda0557ac7

Issue is also present on other wallpapers with config reset being called

**Comment by jackerley** [comment]
Closing as confirmed on Slack to be a GX issue
