### ISSUE TITLE
Code Editor 2: "Visual" toolbox is not displayed at all (converting from Code or creating asset from scratch)

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#7343]
### Description

It makes no difference whether the user converts GML to visual or Visual is selected from the start. The Visual toolbox is not being displayed and there appears to be no way of displaying it.

### Expected Change

The Visual Toolbox should be displayed

### Steps To Reproduce

1. Start GameMaker and create a new project
2. Add an object
3. Add an event
4. Choose Visual
5. See the issue

The same happens if user starts off with selecting GML and then converts the event to Visual

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.800.0.610  Runtime v2024.800.0.634

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
Fixed, this was a regression due to refactor addressing https://github.com/YoYoGames/YoYoStudio/issues/9858
