### ISSUE TITLE
[GameMaker Marketplace] GOG Ext GOG_Friends_GetFriendAvatarImageID returns 0 or 1 instead of sprite id

### ISSUE THREAD

**Issue by mmrnmhrm** [YoYoGames/GameMaker-Bugs#7351]
### Which Extension are you reporting this issue for?

GoG

### Description

Hello.

I was trying to get a sprite for default user's avatar with GOG_Friends_GetFriendAvatarImageID method, but it was only returning 1 for medium and small ones, and 0 for a large one. I checked the GOG_GetError, and there's no error for small and medium avatar, and { Type : 1, Msg : "Wrong avatar type; avatarType=3", Name : "GalaxyInvalidArgumentError" } for large one.
So, it looks like it works more like a "success" message instead of returning the sprite id how the documentation suggests.

And what needs to be done to get rid of the error when requesting the large avatar?

### Expected Change

GOG_Friends_GetFriendAvatarImageID returns sprite id if successful and -1 otherwise

### Steps To Reproduce

If the operation is async, we're assuming that it has completed before going to the next step.
1. GOG_User_SignInGalaxy(false)
2. global.network_user = GOG_User_GetGalaxyID();
3. GOG_Friends_RequestUserInformation(global.network_user, GOG_AVATAR_TYPE_LARGE);
4. Haw some object named obj on the screen that tries to draw itself
5. obj.sprite_index = GOG_Friends_GetFriendAvatarImageID(global.network_user, GOG_AVATAR_TYPE_LARGE);
6. Observe that obj.sprite_index is either 0 or 1
7. show_debug_message(GOG_GetError());
8. Observe that there's an error message when requesting GOG_AVATAR_TYPE_LARGE, and the error message is empty in case of GOG_AVATAR_TYPE_SMALL and GOG_AVATAR_TYPE_MEDIUM
[contactus.zip](https://github.com/user-attachments/files/16674184/contactus.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out to us! After reviewing your code, it seems there’s a misunderstanding with the documentation. To clarify, the function [GOG_Friends_GetFriendAvatarImageID](https://github.com/YoYoGames/GMEXT-GOG/wiki/friends#gog_friends_getfriendavatarimageid) does not return an image index as used in GM. The extension does not manage or create assets for you. What you're looking for is [GOG_Friends_GetFriendAvatarImageRGBA](https://github.com/YoYoGames/GMEXT-GOG/wiki/friends#gog_friends_getfriendavatarimagergba), which provides a `buffer` that you can write to a surface. Alternatively, you might want [GOG_Friends_GetFriendAvatarUrl](https://github.com/YoYoGames/GMEXT-GOG/wiki/friends#gog_friends_getfriendavatarurl), which gives you the URL of the image. You can then use this URL with [sprite_add](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Sprite_Manipulation/sprite_add.htm) to create a new sprite.

> [!WARNING]
> When working with buffers make sure to always correctly manage them (you will need to dispose of them when they are no longer needed).

> [!WARNING]
> Sprites added with [sprite_add](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Sprite_Manipulation/sprite_add.htm) need to be manually managed, meaning you will need to free them when you no longer need them.
