### ISSUE TITLE
Output Window: If "Show the compile window during compilation" Preference is unchecked, the log will not scroll automatically in 2024.800 Betas until after you click the dock

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7354]
### Description
When the "Show the compile window during compilation" option in General Settings > Compiling is disabled, if you run the game without opening the output tab and then click on it after, the output window will still be scrolled all the way to the top. If you then run the game again while not looking at output, it WILL be scrolled to the bottom when you next click it, so it's only an issue the first time you click the output tab after opening GM.

### Steps To Reproduce
1. Disable "Show the compile window during compilation".
2. Re-open GM. Leave the lower dock on whatever it selects by default (feather messages for me)
3. Run the game without ever clicking the output tab
4. Click on the output tab. It will be scrolled all the way to the top instead of the bottom as it usually is.
5. Click on some other tab again
6. Run the game again
7. Click on output again, and it will be scrolled to the bottom

GM will have to be restarted fresh each test, since it only happens the first time.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.609 Runtime v2024.800.0.633

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0084528a-f8e9-4af1-9bf4-a637726b5581](https://api.gamemaker.io/api/github/downloads/0084528a-f8e9-4af1-9bf4-a637726b5581)

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637
