### ISSUE TITLE
create object from sprite

### ISSUE THREAD

**Issue by busymaan** [YoYoGames/GameMaker-Bugs#7355]
### Is your feature request related to a problem?

when i'm making a game, i find it a little bit annoying that you have to right click on objects, go to create > object, and assign a sprite to that object, it just feels inconvienent and slow.

### Describe the solution you'd like

when you right click on a sprite, there should be an option to "create object from sprite", so it makes it quick and easy to make sprites assigned to objects.

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/3714
