### ISSUE TITLE
layer_element_move argument 2 incorrect type (string) expecting a Number (YYGI32)

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7357]
### Description
`layer_element_move` seems to not work with string name of layers, though both docs and Feather says it should take either `ID.Layer` or `String`.

However, when using string it crashes:
```
layer_element_move argument 2 incorrect type (string) expecting a Number (YYGI32)
```

Example code from attached project:
```gml
var _from = "Assets", _to = "instances";
	
	var a = layer_get_all_elements(_from);
	for (var i = 0, n = array_length(a); i < n; i++;)
	{
	    layer_element_move(a[i], _to);
	}
```

### Steps To Reproduce
1. Run attached project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.609 Runtime v2024.800.0.633

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[e88a8d47-aaf2-4b59-8e97-44bd9c1ca0e5](https://api.gamemaker.io/api/github/downloads/e88a8d47-aaf2-4b59-8e97-44bd9c1ca0e5)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.626  Runtime v2024.1100.0.652
