### ISSUE TITLE
Sprite Editor [Spine/SWF]: Able to assign disabled Collision Mask Types 

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#7370]
### Description
On IDE v2024.800.0.613  Runtime v2024.800.0.636, in the Sprite Editor for Spine and SWF assets, it is possible to assign disabled (greyed out) collision mask types this are: 

For Spine: Rectangle with rotation, Ellipse, Diamond, Precise and Precise per Frame

For SWF: Spine Collision Mesh

The issue does not appear in the released monthly build ( IDE v2024.6.2.162  Runtime v2024.6.1.208 )

### Steps To Reproduce
1 - Launch the Beta build
2 - Import the project attached
3 - Open the two sprites
4 - Assign the greyed out collision mask types to the sprites

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.613 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[fb437e1a-22f6-4918-8cc4-e9702ba3d3e8](https://api.gamemaker.io/api/github/downloads/fb437e1a-22f6-4918-8cc4-e9702ba3d3e8)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.614  Runtime v2024.800.0.638
