### ISSUE TITLE
In-Game: default audio group is falsely flagged as not loaded by audio_group_is_loaded()

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#7371]
### Description

On IDE v2024.800.0.612 Runtime v2024.800.0.636, calling audio_group_is_loaded() on the default audio group, will return false, despite it being loaded. Sounds that belong to the default audio group are playable as well, without a problem, and calling audio_group_load_progress() on the default audio group will return 100% as well.

The function works as expected on user created audio groups.

[audiogroup_test.zip](https://github.com/user-attachments/files/16707646/audiogroup_test.zip)

### Expected Change

audio_group_is_loaded() to return true on the default audio group

### Steps To Reproduce

1. Start GameMaker
2. Use audio_group_is_loaded() on the default audio group
3. See that it returns 0
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
Fixed the default audio group's load state not being updated after it is automatically loaded during startup.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1100.0.625  Runtime v2024.1100.0.651
