### ISSUE TITLE
In-Game: Crash possibly related to OpenAL Error in both VM and YYC in runtime 2024.800.0.636 

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7377]
### Description
We are still getting the OpenAL Error followed by silent crash in runtime 2024.800.0.636. We haven't been able to narrow it down to a smaller sample, but the attached project can consistently replicate the issue:

```
OpenAL Error: 40963 (Invalid value)
    After: Unqueueing source buffer
    In file: D:\a\GameMaker\GameMaker\GameMaker\Runner\GMS2-Runner-Main\VC_Runner\YYAL\src\OggThread.cpp
    In function: ogg_seek_stream
    On line: 486
```

This seems to relate to sound resources being set to `Compressed-Not Streamed options`, as we do not see this error when all sound files are set to `Uncompressed-Not Streamed`.

### Steps To Reproduce
1. Ensure that the save area at `%localappdata%\<Game Name>` does not contain any previous data
2. Run the project for Windows VM under the `gamepipe_test_dev`config, which will put the game into automatic testing mode that requires no further input
3. Wait for about 5 minutes and observe in the output logs that after `[passed] go_back_to_main_menu `, the `OpenAL Error` shows up and the runner exits with non-zero status (-1073741819)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.612 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[c66332fd-11ee-4968-a964-6a61d989b362](https://api.gamemaker.io/api/github/downloads/c66332fd-11ee-4968-a964-6a61d989b362)

**Comment by toby-yoyo** [comment]
Thank you for the report.

The bug can also be reproduced in this test project, which should crash more or less instantly: [gmb-7377-x.zip](https://github.com/user-attachments/files/16709058/gmb-7377-x.zip)

**Comment by toby-yoyo** [comment]
Fixed a possibility of some stack corruption when seeking around a compressed audio stream.

**Comment by shichen85** [comment]
Thank you. Can confirm that when commenting out the `audio_sound_set_track_position()` call, the project will not crash. And thanks for the repro sample!

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.614  Runtime v2024.800.0.638
