### ISSUE TITLE
Manual Content: Variables listed in struct forbidden variables are not actually forbidden and do work

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7381]
### Description
The struct forbidden variables page lists a bunch of built in variables that can't be used as struct members, but they actually do work. I tried all of the variables listed and they all compiled and worked both when declaring the struct and accessing it.
The exception is true/false when using GMRT only, see #7382

### Manual Link
https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Overview%2FStruct_Forbidden_Variables.htm

### Steps To Reproduce
Define a struct that uses any of the forbidden variables. It will compile and set the variables just fine.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.613 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d99b390a-1938-490a-88b5-83843dd6176f](https://api.gamemaker.io/api/github/downloads/d99b390a-1938-490a-88b5-83843dd6176f)

**Comment by gurpreetsinghmatharoo** [comment]
Fixed
