### ISSUE TITLE
GMRT: Using true/false as struct members works in GMS2 runtime but not GMRT

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7382]
### Description
Using true/false as struct members will compile and work in GMS2 runtime, but not compile in GMRT.
It's possible this is unintended to work in the GMS2 runtime since feather does give an error when using true/false as struct members, but figured I'd report the difference and you guys can decide which one is wrong lol

### Steps To Reproduce
```
test = {
    true : 0,
    false : 0,
}
show_message(test);
```
This will compile and work in GMS2 runtime, but will not compile in GMRT. It gives feather errors, so it working in GMS2 runtime might be the actual bug.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.613 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b49e2caf-1ab1-41a9-ba94-05db1abb5f2d](https://api.gamemaker.io/api/github/downloads/b49e2caf-1ab1-41a9-ba94-05db1abb5f2d)

**Comment by gnysek** [comment]
If strings that contains numbers only aren't valid for structs, then true/false (which can be typecasted to integer) shouldn't be even more not possible...

https://github.com/YoYoGames/GameMaker-Bugs/issues/7442

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1112  Runtime v2026.100.0.1076 gmrt 0.22.31
