### ISSUE TITLE
Manual Content: Incorrect syntax in example on static variables page

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7383]
### Description

The example for static methods puts the arguments after `function` instead of after the name of the function 
![image](https://github.com/user-attachments/assets/ae1202fd-51b9-4684-be8c-d4947030ad3f)

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=GameMaker_Language%2FGML_Overview%2FFunctions%2FStatic_Variables.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, thanks
