### ISSUE TITLE
In-Game: queue_shutdown key has wrong value when audio queue isn't cleared with audio_free_play_queue()

### ISSUE THREAD

**Issue by AdamBorek** [YoYoGames/GameMaker-Bugs#7390]
### Description

According to the [manual](https://manual.gamemaker.io/beta/en/The_Asset_Editors/Object_Properties/Async_Events/Audio_Playback.htm), queue_shutdown should have the value 0, unless the queue is cleared by audio_free_play_queue(). On IDE v2024.800.0.612 Runtime v2024.800.0.636, when the audio queue is finished playing all the sounds, and is not cleared by audio_free_play_queue(), queue_shutdown will have the value 1. 

[audio_buffer_queue_test.zip](https://github.com/user-attachments/files/16711791/audio_buffer_queue_test.zip)

### Expected Change

queue_shutdown to have the correct value

### Steps To Reproduce

1. Start GameMaker
2. Create audio buffer queue
3. Play the queue
4. Check the value of queue_shutdown inside the Async - Audio Playback event once the queue runs out
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
`queue_shutdown` should now only be `1` if the queue was stopped using `audio_free_play_queue`, as described in the manual.

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.1100.0.626  Runtime v2024.1100.0.652, thanks.
