### ISSUE TITLE
[LTSr3] script_execute_ext doesn't respect built-in function optional arguments

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7397]
### Description
`script_execute_ext` in Monthly has been fixed a long time ago to ensure that functions that have optional arguments, will be passed correctly.

However even with LTSr3, it still seems like that `script_execute_ext` doesn't work with any optional arguments passed through.

I have a sample snippet right here `script_execute_ext(max, [-9, 0, 2, 4, 2, 1,5 ,5, 252, 525, 15152])` that works fine in Monthly. The value it returns is `15152`. On LTS, this returns `-9`, as the first argument in `max` is not an optional argument.

### Steps To Reproduce
1. Run project
2. A popup window will appear with the value `-9`.

### Which version of GameMaker are you reporting this issue for?
IDE v2022.0.3.64 Runtime v2022.0.3.76

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[ab01a299-5c34-44f4-930c-e0a961ceab18](https://api.gamemaker.io/api/github/downloads/ab01a299-5c34-44f4-930c-e0a961ceab18)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2022.0.3.65  Runtime v2022.0.3.78
