### ISSUE TITLE
game_restart causes a memory leak if you have a persistent object in the first room

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7402]
### Description
It appears that there is a memory leak in game_restart related to persistent objects.

https://github.com/user-attachments/assets/27ef394b-4992-46a7-b777-6b2f5f38d974

### Steps To Reproduce
Place a persistent object in the first room, and call game_restart repeatedly. The memory usage is automatically printed into output, and will steadily climb.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.613 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[0d91dba9-f055-478d-9d7e-12e94876a7d3](https://api.gamemaker.io/api/github/downloads/0d91dba9-f055-478d-9d7e-12e94876a7d3)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.625  Runtime v2024.1100.0.651
