### ISSUE TITLE
Room Editor + Project Tool: Opening a 2024.8 project in 2024.6 permanently corrupts all asset layers in a room that had text placed on them

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7404]
### Description
If you add some text to a room in 2024.8 and then open the project in 2024.6, all text placed in rooms will be corrupted. It will no longer appear in the room, and you can't even select it in the instance list to delete it. The only way to get rid of the corrupt text is to delete the entire layer it's on.

 I checked the room yy file, and in 2024.8 a text item looks like this:
```
{"$GMRTextItem":"v1","%Name":"text_454E1F15","alignment":0,"charSpacing":0.0,"colour":4294967295,"fontId":{"name":"Font1","path":"fonts/Font1/Font1.yy",},"frameH":334.0,"frameW":427.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_454E1F15","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Lorem Ipsum","wrap":true,"x":300.0,"xorigin":0.0,"y":278.0,"yorigin":0.0,},
```
But a text item from 2024.8 imported into 2024.6 looks like this:
(Not the exact same text item as above)
```
 {"$GMRItem":"","%Name":"text_13F09127","frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"text_13F09127","resourceType":"GMRItem","resourceVersion":"2.0","x":350.0,"y":389.0,},
```
So it appears a bunch of the info about the text has been removed.

![image](https://github.com/user-attachments/assets/6698e16c-fc54-41a5-af72-611b38e61972)

![image](https://github.com/user-attachments/assets/411ee833-f85f-4a23-ad5d-a812338c3447)

Edit: it appears this actually corrupts the entire asset layer, as sprites placed above the text will also disappear. Moving them will make them reappear, but deleting them does not actually delete them, leaving you with ghost sprites.

https://github.com/user-attachments/assets/094f62a5-522d-48e8-b3d2-9ad269cdce7e

### Steps To Reproduce
Add some text to a room in 2024.8. Open the project in 2024.6. The text will now be corrupted, and you won't be able to see it or select it. Open the project in 2024.8 again. It will still be corrupted.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[8aa91863-17dc-40f9-b0dd-f963d10f76d8](https://api.gamemaker.io/api/github/downloads/8aa91863-17dc-40f9-b0dd-f963d10f76d8)

**Comment by stuckie** [comment]
Newer versions of the IDE - starting with November 2024 - will have ProjectTool deployed as a separately upgradable package, rather than bundled in as part of the runtime.
This means we should not be able to get into this situation again, as if you stick on an older IDE ( from November! ) you'd still be able to update and use a newer ProjectTool.

In this case, you'll need to ensure you use a later ProjectTool to convert your project down as required... and there unfortunately isn't anything we can do about the project having been corrupted already.
