### ISSUE TITLE
In-Game: string(undefined) returns "-6"

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7412]
### Description
This is related to #7185, using string() on undefined gives "-6".

### Steps To Reproduce
`show_debug_message(string(undefined));`
Prints -6

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.613 Runtime v2024.800.0.636

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[d27c9735-5812-40c5-a365-a5803f24da86](https://api.gamemaker.io/api/github/downloads/d27c9735-5812-40c5-a365-a5803f24da86)

**Comment by rwkay** [comment]
Fixed in 2024.8
