### ISSUE TITLE
[Ubuntu] Installing `2024.800.0.613` IDE fails due to lacking dependency, despite having a similar one.

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7424]
### Description

Recently tried to update the Ubuntu IDE, and came across a problem with installing the latest version (via Pop!_OS). With Eddy exiting out on `Child process exited with code 100`.

Upon using `sudo dpkkg -i GameMaker-Beta-2024.800.0.613.deb`, I've got informed that `pulseaudio` wasn't found.

```
Selecting previously unselected package gamemaker-beta.
(Reading database ... 265083 files and directories currently installed.)
Preparing to unpack GameMaker-Beta-2024.800.0.613.deb ...
Unpacking gamemaker-beta (2024.800.0.613) ...
dpkg: dependency problems prevent configuration of gamemaker-beta:
 gamemaker-beta depends on pulseaudio; however:
  Package pulseaudio is not installed.

dpkg: error processing package gamemaker-beta (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for shared-mime-info (2.1-2) ...
Errors were encountered while processing:
 gamemaker-beta
 ```
 
 Which at this point, `pulseaudio` is *technically* installed, but under a different name. Attempting to install it via ` sudo apt-get install pulseaudio` yields
 ```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pipewire-alsa : Conflicts: pulseaudio
                 Conflicts: pulseaudio:i386
 pop-pipewire : Conflicts: pulseaudio
                Conflicts: pulseaudio:i386
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

This I could potentially resolve myself, but as this is affecting more than myself at the same time (as I was also assisting another user with this), I am reporting this to *hopefully* have this remedied.

Additional note: As I cannot really attach a Contact Us package, I'm noting here that there is no Contact us Package (This is to do with the installer anyway)

### Steps To Reproduce

1. Download and install GameMaker-Beta-2024.800.0.613.deb (on Pop!_OS or similar)
2. See results

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Removed pulseaudio as a dependency since we have a fallback anyway

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.800.0.618  Runtime v2024.800.0.642.
