### ISSUE TITLE
The sprite trembles, shakes, and flickers as it moves along its path

### ISSUE THREAD

**Issue by arrosev** [YoYoGames/GameMaker-Bugs#7452]
### Description

I've been Googling for three days before this. When I create a path in my project and have my object move along the path in a loop, the object's sprite keeps jiggling while it's moving. 

https://github.com/user-attachments/assets/d5112a17-4e8d-46fa-8617-1d9029bd94bb

[Contact Us Package.zip](https://github.com/user-attachments/files/16778351/Contact.Us.Package.zip)

### Expected Change

Sprites don't shake when moving

### Steps To Reproduce

1. Start GameMaker
2. Run the project
3. ALT + ENTER to launch full screen
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Hi, I believe this is just a problem with the built in Windows video recorder, by default it records 30fps low quality videos. If you go to Settings->Gaming->Captures and choose 60fps, high quality video then you'll see a much smoother video recorded. You can also log out the deltas from your moving object and you will see that it is moving correctly. One thing to note is that you are moving the object by sub-pixel amounts but you don't have "interpolate colours between pixels" set so you will get a lack of smoothness as your object will effectively be limited to full pixel movements. 

With these two changes here's the video that I see...  


https://github.com/user-attachments/assets/a206c1ae-6de8-4edd-a927-820d01211660

**Comment by arrosev** [comment]
> Hi, I believe this is just a problem with the built in Windows video recorder, by default it records 30fps low quality videos. If you go to Settings->Gaming->Captures and choose 60fps, high quality video then you'll see a much smoother video recorded. You can also log out the deltas from your moving object and you will see that it is moving correctly. One thing to note is that you are moving the object by sub-pixel amounts but you don't have "interpolate colours between pixels" set so you will get a lack of smoothness as your object will effectively be limited to full pixel movements.
> 
> With these two changes here's the video that I see...
> 
>  Created.with.GameMaker.2024-08-28.14-24-18.mp4

Hi, Thank you for your reply. I don't think it has anything to do with recording, the recorded video is just to demonstrate the jitter when moving. If you can run the test project I've provided, you can clearly see that the object jiggles when it moves. I can't use ‘interpolate colours between pixels’ because it makes everything blurry! I tried a lot of things from google before this, such as limiting the coordinates when drawing sprites by round, so that each time a sprite is drawn the coordinates are integers, but that didn't help.
When I set the camera size in the room to 320 * 180 (my room size is 320 * 180) and the viewport to 1280 * 720, this jitter becomes slightly less noticeable, but this can lead to more difficult GUI layouts for multiple resolutions.

**Comment by arrosev** [comment]
I'm just going to say what I ended up compromising on, because there may be others who have the same problem as me as well.
`surface_resize(application_surface,1920,1080)
display_set_gui_size(320, 180);`
You can also use other resolutions for surface. I gave the gui layer a resolution of 320 * 180 (Same size as my room) because I wanted to use a fixed pixel size UI control, this way the UI controls get the same zoom as the sprites when going fullscreen.
