### ISSUE TITLE
Building Projects: [GX.games] Add a "save as .zip" output type which avoids uploading to the GXC

### ISSUE THREAD

**Issue by Sidorakh** [YoYoGames/GameMaker-Bugs#7454]
### Is your feature request related to a problem?

I'd like to use the web assembly runner on websites other than GX Games

### Describe the solution you'd like

An ability to export a WASM build outside of the GX Games website

### Describe alternatives you've considered

Written an extension to handle this for me

**Comment by gnysek** [comment]
Also, this should mark sunset of "old" HTML5 exporter, even for GMS2, as WASM should give better results.

**Comment by Sidorakh** [comment]
That'd also need some extension support in the WASM runner, wouldn't it? Currently only has GML, can't call native JS from it via an extension yet, that probably needs a separate FR

**Comment by rwkay** [comment]
> Also, this should mark sunset of "old" HTML5 exporter, even for GMS2, as WASM should give better results.

No it would not, on current runtime we would continue supporting both... GMRT will NOT have a Javascript runner though

**Comment by tabularelf** [comment]
> > Also, this should mark sunset of "old" HTML5 exporter, even for GMS2, as WASM should give better results.
> 
> 
> 
> No it would not, on current runtime we would continue supporting both... GMRT will NOT have a Javascript runner though

I think that's the point... HTML5 is going to be phased out for GMRT, so it just opens up a transitional period this way

**Comment by gnysek** [comment]
As tubularelf says - maybe "sunset" was too much (as that means even no bugfixes at some point), but adding "deprecated" or some other word which fits should be a good warning for people, that this exporter won't keep up with new GMRT era.

**Comment by jack27121** [comment]
very needed, i know many whose had  to go through several hoops and do their own  workarounds to be able to have a stable wasm build on their own websites of choice. This really  shouldn't be the case. Last i heard there was DRM involved, which i don't see any benefit in having for browser exporting

**Comment by rwkay** [comment]
> very needed, i know many whose had to go through several hoops and do their own workarounds to be able to have a stable wasm build on their own websites of choice. This really shouldn't be the case. Last i heard there was DRM involved, which i don't see any benefit in having for browser exporting

No DRM is involved on the WASM export at all these days - it should work on all browsers (desktop and mobile)

**Comment by sofycat** [comment]
Meow :3

**Comment by FoxyOfJungle** [comment]
I would love to have this functionality, especially for uploading to Itch.io to post demos of some projects, for example. In addition to being able to publish a game on your own host as well

**Comment by rwkay** [comment]
![image](https://github.com/user-attachments/assets/c720c47e-062f-40a5-af20-b40c0d1029b6)

Added an export option to create a ZIP file with all the files for the WASM export

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by scott-dunbar** [comment]
Export of the WASM target to zip will prompt you for a sign in. This seems unnecessary and it would be good if we could skip that requirement

Tested in  IDE v2024.1100.0.629  Runtime v2024.1100.0.654

Reopening issue to have this addressed
![GXZip](https://github.com/user-attachments/assets/b496d19a-1a18-4044-9dc1-4cb09cf0ea79)

**Comment by YYBartT** [comment]
Manual page (and screenshot) for this will be updated after the fix for https://github.com/YoYoGames/GameMaker-Bugs/issues/7964.

**Comment by YYBartT** [comment]
Updated the screenshot and description on the Compiling manual page.

**Comment by scott-dunbar** [comment]
Verified in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666

**Comment by jack27121** [comment]
i do not see any save as zip version on GX.games, there may be more requisite steps i dont know, but it is atleast not clear to me

**Comment by gnysek** [comment]
@jack27121 most recent monthly .08, or .1100 beta? :) there are two "recent" versions.

**Comment by jack27121** [comment]
> [@jack27121](https://github.com/jack27121) most recent monthly .08, or .1100 beta? :) there are two "recent" versions.

08. Is this thing still in beta? If so my bad!

**Comment by gnysek** [comment]
No, .1100 is beta (of .11 monthly), and feature seems to be there, while it's not in 2024.08.
