### ISSUE TITLE
Different outcomes on different runtimes

### ISSUE THREAD

**Issue by Vivalzar** [YoYoGames/GameMaker-Bugs#7458]
### Description

I'm trying to use macros to implement a wrapper. But I have different outcomes on different runtimes.

I have the following function:
```
function dispatch(f)
{
    f();
}
```
And a couple of macros:
```
#macro wrap function() { dispatch( function
#macro done )}
```
I use them like that:
```
foo = wrap() {
    show_debug_message("foo()");
} done

bar = wrap() {
    show_debug_message("bar()");
} done
```
On the click of my test object, I call `foo()`. And in the output window, `bar()` is incorrectly printed. It can be reproduced with the runtime _2024.6.1.208_ but **not** with the _2024.4.1.202_.

Here is the Contact Us Package:
[package.zip](https://github.com/user-attachments/files/16787174/package.zip)

And here is the sample project:
[Wrapper.zip](https://github.com/user-attachments/files/16787228/Wrapper.zip)

### Steps To Reproduce

1. Start GameMaker
2. Run the sample project
3. Click the red square
4. See the issue
5. Switch runtime
6. It works

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Suspect this is https://github.com/YoYoGames/GameMaker-Bugs/issues/6525 - will need to confirm if it's fixed in Aug Betas already

**Comment by YYDan** [comment]
Yes, it is - Beta IDE v2024.800.0.618  Runtime v2024.800.0.642

![image](https://github.com/user-attachments/assets/ea0813e0-a3cf-4ddf-a000-752fc6fae79c)

**Comment by Vivalzar** [comment]
Thanks for the information. And sorry for the duplicate.
