### ISSUE TITLE
Command Line Builds: Add a way for the RUN command to specify the output directory for the BIN and only build if not newer

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7460]
### Is your feature request related to a problem?

When you need to run a game multiple times - due to a crash - and you want to NOT rebuild the game, you just want to run on the target platform, this ends up being important.

### Describe the solution you'd like

Allow to specify an output folder which I think IS already possible. So I think the only thing missing is the "only build it not newer" portion of the logic.

**Comment by DiasFranciscoA** [comment]
The solution went through creating a `nobuild` flag that will skip build, it should be used in conjunction with Run command after a Package has been created.

**Comment by Emc1923** [comment]
Verified  `--nb, --nobuild` flag added as of  Runtime v2024.1100.0.653
