### ISSUE TITLE
[HTML5] Method execution scope is set incorrectly when returning from a function

### ISSUE THREAD

**Issue by BenjaminHalko** [YoYoGames/GameMaker-Bugs#7468]
### Description

In the HTML runtime, when a struct is returned from a function, and a **static** method is immediately used, it will be executed in the instance's scope instead of the struct's scope.

I first discovered this issue when using the Realtime Database extension.
```gml
listener = FirebaseRealTime().Path("/").Listener();
```
- `FirebaseRealTime` returns a new copy of `Firebase_RealTime_builder`
- The static function `Path` is getting incorrectly executed in the instance's scope
- `Path` returns `self`, and instead of returning a reference to the struct, it returns a reference to the object that executed this code
- `Listener` crashes the game, as the calling object does not have a variable named `Listener`

Strangely, if the returned struct is assigned to a variable, then the static method is called, there is no issue.
```gml
var _firebase = FirebaseRealTime();
listener = _firebase.Path("/").Listener();
```

This bug is present in the 2024.6.x runtime onwards. This bug does not occur in 2024.4.x.

### Expected Change

Static methods should execute in the correct scope

### Steps To Reproduce

TestScript:
```gml
function __Test() constructor {
	PrintSelf = function() {
		show_debug_message("---");
		show_debug_message($"Instance of: {instanceof(self)}");
	}
	
	static PrintSelf_Static = function() {
		show_debug_message("---");
		show_debug_message($"Instance of: {instanceof(self)}");
	}
}

function Test() {
	var _test = new __Test();
	return _test;	
}
```
oTest:
```gml
new __Test().PrintSelf(); // __test
new __Test().PrintSelf_Static(); // __test
Test().PrintSelf(); // __test
Test().PrintSelf_Static(); // instance - this is the one that fails
var _test = Test();
_test.PrintSelf(); // __test
_test.PrintSelf_Static(); // __test
```

[Sample Project](https://github.com/user-attachments/files/16803871/HTML.Static.Bug.zip) - Just run this in the HTML5 export.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
I cannot replicate this on the current 2024.10 HEAD but we should check it against the 2024.8 Beta

**Comment by YYDan** [comment]
Yeah, am I not seeing any difference either in Beta IDE v2024.800.0.618  Runtime v2024.800.0.642

HTML5
![image](https://github.com/user-attachments/assets/c34a6af0-d5fd-420a-9eaa-f38a86e07ab5)

Windows
![image](https://github.com/user-attachments/assets/ed4263ce-34d1-4726-adb5-50f430e5fe8b)

**Comment by YYDan** [comment]
The older Runtime v2024.800.0.618 from way back in Aug Betas gives the same results, so this has been fixed for a while.

However, yes, 2024.6.2 Monthly gave the problem:
![image](https://github.com/user-attachments/assets/d8237de9-45b5-4b23-b741-28f1dce6d8f3)

Closing as Fixed,
