### ISSUE TITLE
GMRT: Using an empty string as a struct key is valid

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7474]
### Description
In GMS2 runtime, using an empty string `""` as a struct key crashes. In GMRT, it works, but it feels like it probably shouldn't, since it'd be easy to do this on accident if you use an empty string as a default and then not realize why things are broken.

### Steps To Reproduce
```
var struct = {};
struct[$ ""] = 0;

show_debug_message(struct[$ ""]); //works just fine
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[831b084b-26a3-49da-a603-867e84930bb0](https://api.gamemaker.io/api/github/downloads/831b084b-26a3-49da-a603-867e84930bb0)

**Comment by stuckie** [comment]
This is for managing inter-op with other languages (JavaScript for instance)
