### ISSUE TITLE
My room order are broken

### ISSUE THREAD

**Issue by rcnzbr** [YoYoGames/GameMaker-Bugs#7484]
### Description

Wen I write the code "room_goto_next()" the room _do not_ go to the next one, it skips **two** rooms. I don't saw any tutorial related to this problem, so I don't know if its only happened to me

### Steps To Reproduce

1. Start GameMaker
2. write the code
3. start the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rcnzbr** [comment]
My problem was magically solve :D

**Comment by YYDan** [comment]
Glad you got it sorted. I'll close the issue now.

Just as a note, though, we don't offer coding support anyway, but also anyone who wanted to help would have needed to see some code first, so there was nothing we could do here. In future, for all coding/development help create yourself a thread on https://forum.gamemaker.io/index.php?forums/tech-support.24/ and ask there instead, and I am sure someone will offer a hand.
