### ISSUE TITLE
In-Game: [Ubuntu] Memory leak over time

### ISSUE THREAD

**Issue by AIO1** [YoYoGames/GameMaker-Bugs#7485]
### Description

Doing on linux for a game compiled as YYC peridocially (for example each 5 seconds:
`var _returnedDumpMem=debug_event("DumpMemory",true);`
Will slowly increase the amount of memory used.

See "obj_server" alarm9 of the contact us package.
To test it you need to build as "Default" configuration, you don't need clients to connect to. Periodically look the generated log file (see function v_writeToLog to see were it writes to) and you will see that the memory increases.

Contact us package: [WorldWidePainters.zip](https://github.com/user-attachments/files/16824045/WorldWidePainters.zip)

### Expected Change

Leak should be fixed.

### Steps To Reproduce

See above

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yoyo-danielc** [comment]
I couldn't see any memory leak specific to calling `debug_event("DumpMemory",true);` - removing the call from your demo project didn't affect the leak I measured.

I did however find a leak which applies to all projects (even empty ones), which will vary depending how many input devices you have, but on my machine it continuously leaked approx 110kB per minute, fixed on 2024.10 branch.

**Comment by Emc1923** [comment]
Verified that the leak when connecting multiple input devices does no longer occur, as of  IDE v2024.1100.0.627  Runtime v2024.1100.0.653.
