### ISSUE TITLE
Project Tool: Importing a .gmx/.gmz causes the project to load indefinitely in 2024.8 Betas

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#7497]
### Description

When importing a .gmx/.gmz, the Project Tool window will state it was succesful however the loading bar will get stuck half way, causing the IDE to become unusable.

![image](https://github.com/user-attachments/assets/809f9715-db1e-439f-a448-44cc2a0d6230)

Tested using IDE v2024.8.0.168  Runtime v2024.8.0.215

[Contact Us Package](https://api.gamemaker.io/api/github/downloads/28dc90b7-2b9b-4646-b702-8bde6b5b474b)

### Steps To Reproduce

1. Start GameMaker
2. Import a .gmx/.gmz by dropping it on to the Start Page
3. Observe the loading bar never finishes despite the Project Tool window saying the import was successful

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Both of the GMZ and GMX projects import just fine now in  IDE v2024.8.1.171  Runtime v2024.8.1.218.

Note that the sound asset is missing its audio source file inside both of the GMZ/.zip for some reason, and so this obviously results in a compile error that the source file cannot be found. The project runs fine if you remove the sound asset.
