### ISSUE TITLE
Ubuntu monthly-safe betas

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7501]
### Is your feature request related to a problem?

For ubuntu, there's only "beta" version of GameMaker available.

However, after every monthly release, each of released beta comes with preview of new features which might be buggy, and have some bugfixes which somestimes causes regressions.

There's high chance, that earlier betas of each minor version have more bugs, while last 2-3 betas of month are best ones to download.

However, there's still chance that between last beta of month and monthly release, there's fix or two which wouldn't be in betas until next minor beta release. Even if monthly is equal with latest beta, often it's only few days until next minor beta is released, and Ubuntu download links will be replaced - so **users have only few days to download version most similar to monthly**, then they will be served with another beta - and while using direct link it's possible to download any past beta, release notes for previous beta would be removed and replaced with newer ones, so there's no direct links. So, if they aren't aware of release cycle, what they got depends on a day on which they visit gamemaker.io / release notes .

### Describe the solution you'd like

When monthly release is done, there should be done beta release with identical code only to serve it as Ubuntu "best quality" version of beta.

Or, at least offer links to "last" beta of 2-3 previous monthly betas.

**Comment by stuckie** [comment]
We have no plans on doing this at the moment.
