### ISSUE TITLE
In-Game: Filters and Effects are not correctly applied to cropped surfaces which are bigger than the application_surface

### ISSUE THREAD

**Issue by TrianglyRU** [YoYoGames/GameMaker-Bugs#7513]
### Description
See Title and Steps To Reproduce

### Steps To Reproduce
- have an active application_surface
- have a camera wider the application_surface
- have a surface assigned to the camera the same resolution as the camera
- crop the surface's sides and shift it to display the camera correctly on the screen
- apply any filter or effect

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.0.169 Runtime v2024.8.0.216

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

### Attached Files
![Безымянный](https://github.com/user-attachments/assets/675859a7-d529-4536-8202-40b8bef05cc1)

**Comment by YYDan** [comment]
Presumably a knock-on from the fix in https://github.com/YoYoGames/GameMaker-Bugs/issues/7252

**Comment by TrianglyRU** [comment]
Here's RenderDoc draw call in case that would help, EID 170. Also, the background is rendered twice for some reason, I think there are some internal surface shenanigans going on
[background_capture.zip](https://github.com/user-attachments/files/16873356/background_capture.zip)

**Comment by TrianglyRU** [comment]
From my observation, what it does is:
- it draws the background on a surface
- then it copies the surface onto a separate buffer and applies a filter
- it then draw that very buffer ontop of the said surface without cleaning the surface itself

The problems here goes way, way deeper than it looks

**Comment by JonnoRobson** [comment]
I'm having some trouble reproducing the problem you're seeing just based off the steps to reproduce in the issue description. The RenderDoc capture is appreciated but without the context of the associated project it's difficult to parse what is going on vs what should be happening. Could you attach a project with the minimum steps to consistently reproduce the issue?

**Comment by TrianglyRU** [comment]
Sure, here's the blank project I set up to reproduce the issue. It is a pink background with a colour tint filter is applied to it so it appears purple. You will notice the black strip on the right, 8px wide, the same as the H_BUFFER macro used to extend the camera.
 
[EffectBug.zip](https://github.com/user-attachments/files/17228398/EffectBug.zip)

**Comment by JonnoRobson** [comment]
I've pushed a fix for this issue that should be available in the upcoming 2024.11 release. The issue here was that the scissor rect for the surface set through `view_surface_id[0]` was not being applied when rendering the filter and instead the original viewport dimensions for the room were being used. We already handle viewport dimensions differently when using a surface set through `view_surface_id[0]` so making sure that same logic is applied to the scissor rect when rendering a filter fixes this issue.

**Comment by TrianglyRU** [comment]
Thank you for your work! Hope this makes it to the LTS release, you're a lifesaver.

**Comment by Emc1923** [comment]
Verified fixed in IDE v2024.1100.0.639  Runtime v2024.1100.0.662.
