### ISSUE TITLE
 Instance place returns a different value for "no collision" in Windows and HTML5

### ISSUE THREAD

**Issue by TheAtrxcity** [YoYoGames/GameMaker-Bugs#7519]
### Description

instance_place(x, y, [tilemap_id]); will return -4 on windows and return -1 on HTML5.

### Steps To Reproduce

Create a variable holding a tilemap_layer_id.
Use instance_place(x, y, [tilemap_id_variable]);
Check what values it returns on both platforms when there is no instance at x and y. 

YZZ by Jon Peterson at uploaded by me:
https://easyupload.io/lrw7wj

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows, HTML5

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1100.0.625  Runtime v2024.1100.0.651
