### ISSUE TITLE
In-Game: Comparing a null string to an empty string causes a crash in 2024.8.0 runtime

### ISSUE THREAD

**Issue by grif-on** [YoYoGames/GameMaker-Bugs#7520]
### Description

Previously (prior to Runtime 2024.8.0.216) `var parameter_value = parameter_string(parameter_count())` returns an empty string on Windows runner . This string was been OK to compare like this `if (parameter_value == "") {}` .

Now on new runtime such comparasion silently crashed game runner:
![Image](https://github.com/user-attachments/assets/bc7346df-c5c4-4667-ab90-eec6f27ced7b)

Sample -
https://api.gamemaker.io/api/github/downloads/8f473145-8071-4d96-b6a4-c05904773f0f

### Expected Change

Game should not silently crash .

### Steps To Reproduce

1. Start GameMaker
2. Compile attached sample project
4. See that room creation code caused silent crash of runner

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Works fine again in IDE v2024.8.1.171  Runtime v2024.8.1.218. Verifying.

![Image](https://github.com/user-attachments/assets/b24b0863-891a-4c2d-b181-14eb69098027)
