### ISSUE TITLE
Manual Content: sprite_get_info() page has a typo "atlas_texture" instead of "atlas_textures"

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#7522]
### Description

Manual:
![image](https://github.com/user-attachments/assets/2cf6781c-ca4c-41f2-af90-c78db383ca83)

Runtime:
![image](https://github.com/user-attachments/assets/b5511331-98b7-4097-837f-ec1441006ff4)

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSprites%2FSprite_Information%2Fsprite_get_info.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, thanks
