### ISSUE TITLE
network WSAENOTSOCK error

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#7524]
### Description

![image](https://github.com/user-attachments/assets/cfb11c93-b143-4e55-a4ed-fae7af08c499)

In an environment with multiple users connecting and disconnecting from the network, network transfers fail after a period of time with a corresponding error.

2024.2 : Working fine
2024.4 - 2024.6 : Window cap 64 connection bug but working fine
2024.8 : 64 connection bug fixed, but above bug appear

### Expected Change

Network should work as normal.

### Steps To Reproduce

1. Start Game Maker Based Server (RAW + TCP)
2. Normal client connections, communications, and disconnections.
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed on the 2024.10 branch, test project attached: [gm7524.zip](https://github.com/user-attachments/files/16961386/gm7524.zip)

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1100.0.626 Beta Runtime v2024.1100.0.652
