### ISSUE TITLE
`room_get_info` Instances Array Returning Extremely Large and Ids

### ISSUE THREAD

**Issue by danieltjewett** [YoYoGames/GameMaker-Bugs#7526]
### Description

See #6663 

This got interpreted as a debugger issue.  It is not.  I updated notes and info below.

When using `room_get_info(roomIndex, false, true, true, true, false)`, we get extremely large instance ids, as shown below:
![image](https://github.com/user-attachments/assets/e99c13e1-b152-4155-af11-183a19de35a8)

The element array which references the instance also contains this large, incorrect id (but at least they are referencing each other). Scrolling through some of the data, I noticed that there were some other large ids (like Shader on the layer), but that info isn't pertinent to our needs, and haven't verified this one way or another.

### Expected Change

The ids should be correct references to the instance names in the room editor.

### Steps To Reproduce

1. Start GameMaker
2. Create an object
3. In the create event, add the code:
```
var data = room_get_info(room, false, true, true, true, false);

var instances = data.instances;
var instancesLength = array_length(instances);
for (var i=0; i<instancesLength; i++)
{
	var inst = instances[i];
	show_debug_message("ID ");
	show_debug_message(inst.id);
}
```
4. Add the object to the instances layer
5. Run the game in debug mode
6. See the issue

The zip can be found here:
https://api.gamemaker.io/api/github/downloads/f93b967c-9020-4140-a923-84d57306826c

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.10 - also fixed a few more references within the room_get_info structure

**Comment by danieltjewett** [comment]
For those who need to have this before 2024.10, a solution for now is to take the `id` from `room_get_info(room, false, true, true, true, false)` and subtract `288230380446679040`.  Based on this integer value, it seems to be representing a 2GB value somewhere.

**Comment by rwkay** [comment]
> For those who need to have this before 2024.10, a solution for now is to take the `id` from `room_get_info(room, false, true, true, true, false)` and subtract `288230380446679040`. Based on this integer value, it seems to be representing a 2GB value somewhere.

A better way to do this would be to just get the value and use `& $ffffffff` as that will isolate the index component of the value.
