### ISSUE TITLE
Building Projects: [Ubu IDE] Failure to convert .mp3 audio files using 2024.8 when they are set to either "compressed" type

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7544]
### Description
I've updated my Ubuntu settings for 2024.8(00), including installing `ffmpeg 6.1.2` as per helpdesk article. I've found out, that while some sounds are working, some not.
After some longer investigation using diffs on .yy files, I've found out that I have issues with sounds that are marked as:
- Compressed - Not Streamed
- Uncompress on Load - Not Streamed
- Compressed - Streamed

So only default setting (Uncompressed - Not Streamed) is working.

Also, on Ubuntu 22.04 audio preview is not working anymore.

### Steps To Reproduce
1. Import .mp3 sound (I've used `snd_game_win.mp3` from Match 3 template)
2. Change Attributes to "Compressed"
3. Try to compile on Ubuntu
4. Compilation fails:

`Error : Failed to convert audio file 'snd_game_win' - check source file '/home/gnysek/GameMakerProjects/bug_ubuntu_22_04_mp3/sounds/snd_game_win/snd_game_win.mp3'`

```
Converting snd_game_win to Ogg with bit rate 128, quality 2, mono @ 44100Hz


Failed conversion - retrying
Converting snd_game_win to Ogg with bit rate 128, quality 2, stereo @ 44100Hz


Error : Failed to convert audio file 'snd_game_win' - check source file '/home/gnysek/GameMakerProjects/bug_ubuntu_22_04_mp3/sounds/snd_game_win/snd_game_win.mp3'
[mp3 @ 0x61fd5f6e5d00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/home/gnysek/GameMakerProjects/bug_ubuntu_22_04_mp3/sounds/snd_game_win/snd_game_win.mp3':
  Metadata:
    date            : 2023
    track           : 1
  Duration: 00:00:05.98, start: 0.000000, bitrate: 320 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
System.IO.FileNotFoundException: Could not find file '/home/gnysek/.config/GameMakerStudio2-Beta/Cache/GMS2CACHE/bug_ubuntu_3D754DFB_F6CD8F8B/bug_ubuntu_22_04_mp3/Default/Audio/snd_game_win.ogg'.
File name: '/home/gnysek/.config/GameMakerStudio2-Beta/Cache/GMS2CACHE/bug_ubuntu_3D754DFB_F6CD8F8B/bug_ubuntu_22_04_mp3/Default/Audio/snd_game_win.ogg'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/FileIO/FileIO.cs:line 260
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 22.04.4 LTS kernel 6.8.0.40

### Which platform(s) are you seeing the problem on?
Ubuntu

[b9c94bf9-3f1c-40fa-8f09-59eeeff0fb61](https://api.gamemaker.io/api/github/downloads/b9c94bf9-3f1c-40fa-8f09-59eeeff0fb61)

**Comment by gnysek** [comment]
Might be connected with #7531 .

**Comment by chaslinux** [comment]
While compiling for Ubuntu works with Uncompressed sound, compiling for HTML seems to have an issue, even with sounds marked as Uncompressed. But I suppose this is already fixed for the next patch?

**Comment by stuckie** [comment]
I'm going to close this now, as the helpdesk article has been updated... specifically, it seems that you need to explicitly enable support for mp3 and ogg for it to work, so those have been added.
The HTML5 issue above is likely that the compiled ffmpeg does not have mp3 support, as some browsers expect mp3 over ogg.

We'd still recommend upgrading to 24.04 as it provides the version of ffmpeg we're expecting, without having to compile manually.
