### ISSUE TITLE
Обновления

### ISSUE THREAD

**Issue by Kustars** [YoYoGames/GameMaker-Bugs#7548]
### Description

Yesterday he encountered a problem, a new update of GameMaker Studio 2 came out and produced an error in the console Object: OBjFntScene10 Event: Drawing on line 8: Unknown type of parameter 0 in the optimization call for the line method, although it used to run with the same code, but after the September updates this problem appeared

### Expected Change

решить проблему с компиляцией

### Steps To Reproduce

1. Start GameMaker
2. Open the attached project: 
3. Run the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Your project does not compile in June either - this is not a new thing broken by the August release.

 IDE v2024.6.2.162  Runtime v2024.6.1.208
![image](https://github.com/user-attachments/assets/5e7d8384-0480-4a01-bbc6-3666ac149883)

**Comment by bsabiston** [comment]
I have this same bug today after updating to the new version
