### ISSUE TITLE
In-Game: audio_play_sound_ext() function absent in LTSr3 builds

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GameMaker-Bugs#7550]
### Description

The audio_play_sound_ext() function is absent in LTSr3 builds, but present in the LTS manual. When running a project that uses this function, the following error is returned in Output:
`Variable <unknown_object>.audio_play_sound_ext(100018, -2147483648) not set before reading it.`

https://api.gamemaker.io/api/github/downloads/a9655135-1072-4dc1-b73f-f323e8940ea1

### Expected Change

It is expected that the audio_play_sound_ext() function is present in LTS, to match its presence in LTS manual

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Run game
4. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
I think this one is a docs bug rather than a runner bug, `audio_play_sound_ext` was added in 2023.1 so it shouldn't be in LTS (whose feature set is based on 2022.9).

**Comment by jackerley** [comment]
@gurpreetsinghmatharoo  this isn't in LTSr3 so shouldn't be in the docs

**Comment by cameron-home** [comment]
I've updated the bug to reflect that this is a manual issue, not a build one. Thanks!

**Comment by gurpreetsinghmatharoo** [comment]
Fixed

**Comment by alicemoretti** [comment]
The function is not present in the latest version of the LTS manual (unpublished). 

Setting to verified. Thank you.
