### ISSUE TITLE
[Ubuntu IDE] ffmpeg installation - additional param to prevent audio issues

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7574]
### Description

According to my research for #7544 it seems, that for Ubuntu 22.04 `ffmpeg` need to be configured with `--enable-libvorbis` so sound conversion for compressed audio works.

So, on https://help.gamemaker.io/hc/en-us/articles/20724217655453-Ubuntu-IDE-Updating-FFmpeg-to-the-latest-version-if-you-re-using-Ubuntu-22-04-LTS, on **STEP 5**:
> Type `./configure` to create the configuration. 

Should be replaced with:

> Type `./configure --enable-libvorbis` to create the configuration.

And this should fix potential Ubuntu audio issue.

Edit, 10.09.2024:
Also, `sudo apt-get install libvorbis-dev` might be required in that case.

### Manual Link

https://help.gamemaker.io/hc/en-us/articles/20724217655453-Ubuntu-IDE-Updating-FFmpeg-to-the-latest-version-if-you-re-using-Ubuntu-22-04-LTS

**Comment by YYDan** [comment]
I can see that the changes have been made now.

**Comment by gnysek** [comment]
Great, I see that it have few additional requirements mentioned, which I didn't applied, so in case of any issues I would try reinstalling ffmpeg with newest instructions first (but as for now, even 2024.1000 runtime seems to work).
