### ISSUE TITLE
Sound Mixer: Play/Pause All button still shows as paused if current group is changed during playback, even though playback is actually stopped

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#7575]
### Description

IF the sound mixer is open and playing a group then the loaded group change, the audio will stop but the play/pause button will still show pause.

The button will then need to be pressed twice to restart play. The button will look correct at this point.

Additionally all the other play/pause buttons in the group will show this

### Expected Change

the button will represent the correct state

### Steps To Reproduce

1. Start GameMaker and import the attached project
2. open the sound mixer and load "audiogroup1"
3. press play, notice the symbol turn to the pause icon
4. while the music still plays, changed to "audiogroup2"
5. notice the music has stopped but the "all" play/pause buttons still shows pause
6. press the "all"pause
7. it will still show pause, the other play/pause will have flash but still show "play"
8. press the "all"pause
9. the group will play as intended and the "all" button will now show play as expected

[sound mixer play-pause on group change issue.zip](https://github.com/user-attachments/files/16929380/sound.mixer.play-pause.on.group.change.issue.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly), 2022.0.2 (LTS), 2024.800 (Betas)

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
The group's play state should now update whenever the loaded group is changed.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
