### ISSUE TITLE
Manual Content: "particleSystemIndex" key found in sequence keyframe data struct is undocumented

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7584]
### Description
If you place a particle system asset in a sequence, this immediately presents the issue of "how do I clean this up?" The documentation for the sequence struct has no mention of particle system assets at all. Digging through the sequence struct with debug messages, a `particleSystemIndex` value can be found, but it's a number, not one of the new ref values, so it won't reliably work. It appears that the system is destroyed too when the sequence is destroyed, but this is difficult to verify. I don't know if it being destroyed automatically is documented or not since I'm not sure where it'd be located if it was.

### Steps To Reproduce
Place a particle system asset into a sequence, and then add this as a moment:
```
function Sequence1_Moment()
{
	var index = self.activeTracks[0].track.keyframes[0].channels[0].particleSystemIndex;
	show_debug_message(index);
}
``` 
It will show a number, not a ref value.

For documentation, see the lack of the particleSystemIndex value here:
https://manual.gamemaker.io/monthly/en/index.htm?#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FSequences%2FSequence_Structs%2FThe_Keyframe_Data_Struct.htm

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.0.169 Runtime v2024.8.0.216

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[89186570-8520-46ff-adf4-d43d52e6cfef](https://api.gamemaker.io/api/github/downloads/89186570-8520-46ff-adf4-d43d52e6cfef)

**Comment by jzavala-YYG** [comment]
Hey @gurpreetsinghmatharoo or @YYBartT talking with @patrickrocheyoyo decided this ticket will be closed as no planned, but we need document the key **_particleSystemIndex_**.

**Comment by mgeddesGM** [comment]
manual update verified
