### ISSUE TITLE
In-Game: room_next() and room_previous() return numbers, not asset references

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#7587]
### Description

`room_next()` and `room_previous()` are supposed to return asset references, but instead they return numbers as before

### Steps To Reproduce

`show_message(typeof())` with either function will display `"number"`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYBartT** [comment]
The manual pages for [room_previous()](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/room_previous.htm) and [room_next()](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Rooms/room_next.htm) already refer to the return value as "Room Asset". No change is needed.

**Comment by cameron-home** [comment]
Verified fixed in  IDE v2024.1100.0.626  Runtime v2024.1100.0.652
