### ISSUE TITLE
More than one injection tag in extension code injection panel will show a false error message in the editor

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7604]
### Description

In the IDE extension code injection panel if you have more than on injection tag the XML parser will complain about "more than one root node found" even though the code is correct. And there shouldn't be any error messages displayed.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/4416116a-0946-432a-a41a-2e5779c3d2ae">

### Expected Change

Fix the XML parser to not show this false positive error.

### Steps To Reproduce

1. Start GameMaker
2. Open project go to the extension code injection panel (iOS or Android)
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.650  Runtime v2024.1100.0.670
