### ISSUE TITLE
In-Game: [Android] video_set_volume() crashes the runner

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7615]
### Description
Calling `video_set_volume()` crashes the android runner.

### Steps To Reproduce
1. Run the project for android vm export under the dev config
2. This will spawn the `grc_o_video_function_test` object, which calls `video_set_volume()`
3. Observe crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android

[38069e69-1845-47dd-b99d-aef521f52037](https://api.gamemaker.io/api/github/downloads/38069e69-1845-47dd-b99d-aef521f52037)

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.639  Runtime v2024.1100.0.663.
