### ISSUE TITLE
In-game: [iOS Runtime] Game crashing on startup (iPhone 6 Plus iOS 12.5.7)

### ISSUE THREAD

**Issue by yevhenii-sir** [YoYoGames/GameMaker-Bugs#7630]
### Description

When building (even an empty project) for iOS, the app just closes on startup. On iOS versions above 12.5.7 (I tried IOS 17.6 and 18.0 everything works fine).

![AnyDesk_p0RQAD50Hu](https://github.com/user-attachments/assets/3e312c38-b39b-4516-8658-c5bbfd606499)

![AnyDesk_eYnLqlJ8Fr](https://github.com/user-attachments/assets/9b0196c4-a144-4590-a9e8-776275f47fcc)

Log: 
```
2024-09-13 12:39:35.428977+0300 TestRunIOS[4373:999566] [DYMTLInitPlatform] platform initialization successful
2024-09-13 12:39:35.569002+0300 TestRunIOS[4373:999473] Metal GPU Frame Capture Enabled
2024-09-13 12:39:35.572518+0300 TestRunIOS[4373:999473] Metal API Validation Disabled
2024-09-13 12:39:35.768809+0300 TestRunIOS[4373:999473] Screen size is 1125.000000,2001.000000
2024-09-13 12:39:35.824477+0300 TestRunIOS[4373:999473] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x1be157180 0x1bd32f9f8 0x1be0d0bec 0x1be0418ac 0x1eafc23ac 0x10139a6f4 0x1ea581dcc 0x1ea7ea1b4 0x1ea7ea9dc 0x1eab2f2b4 0x1eab2f890 0x1eab2def4 0x1ea3f12a4 0x1ea3f983c 0x1ea3f0f28 0x1ea3f1818 0x1ea3efb64 0x1ea3ef82c 0x1ea3f436c 0x1ea3f5150 0x1ea3f4224 0x1ea3f8f24 0x1eab2c5e8 0x1ea728e04 0x1c0ad49fc 0x1c0ade40c 0x1c0addc14 0x102334c78 0x102338840 0x1c0b0f040 0x1c0b0ecdc 0x1c0b0f294 0x1be0e8f1c 0x1be0e8e9c 0x1be0e8784 0x1be0e36c0 0x1be0e2fb4 0x1c02e579c 0x1eab2fc38 0x1016d1064 0x1bdba68e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Package (make in beta but in release runtime is same):
https://api.gamemaker.io/api/github/downloads/c0f7d386-ec1e-4752-9130-237a3dd4f9b5

### Expected Change

When launching the application, it will not crash.

### Steps To Reproduce

1. Start GameMaker
2. Create Project
3. Build on IOS
4. Build on device with IOS 12.5.7
5. Launch game
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Yup ;)

No worries.
