### ISSUE TITLE
Accessing an extension option of an extension that doesn't have included files results in a runtime crash

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7631]
### Description

Trying to access an extension option of an extension that doesn't have included files creates a runtime crash.

### Expected Change

This should not crash if the extension exports to the target its extension options should be always available

[ext_opt_crash.zip](https://github.com/user-attachments/files/16994817/ext_opt_crash.zip)

### Steps To Reproduce

1. Start GameMaker
2. Run the attached demo
3. See the issue (crash)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652, thanks.
