### ISSUE TITLE
Extension options are not being preserved whenever you import a new version of the extension

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7634]
### Description

Whenever you have an extension in your project lets say Steamworks, edit the extension options and save and then reimport the Steamworks from the marketplace or local library the extension options get reset to the defaults.
The happens after Jan 2024 with some of the file format changes

### Expected Change

The user extension options should be preserved accross updates

### Steps To Reproduce

1. Start GameMaker
2. Import Steamworks extension (from marketplace library for example)
3. Go into options and change some values
4. Reimport Steamworks extension (from marketplace library for example)
5. See the issue (the options got reset)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by cameron-home** [comment]
@DiasFranciscoA Do you have a test project for this?

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.627  Runtime v2024.1100.0.653
