### ISSUE TITLE
[IDE] Adding or removing a file in datafiles requires the project to reload

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7635]
### Description
I'm aware that the project file needs to keep track of files, but I've been noticing it nonstop in my own project that adding or removing a file from datafiles just causes the whole project to reload. I can confirm this by turning off "Automatically reload changed files", which will prompt me to *reload or save the project*. This might be ok on smaller projects, but as mine is mainly involving my entire game being exposed in datafiles, and my project isn't necessarily small, it gets tremendously annoying. Especially when I leave my IDE open for long periods at a time.

### Steps To Reproduce
1. Open up project
2. Add a new text file.
3. IDE will now automatically reload the project (or prompt to reload/save)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files
* GameMaker-Beta_2024-09-14_02-27-49.png

[07db0855-0166-4637-a112-f8cc075edbee](https://api.gamemaker.io/api/github/downloads/07db0855-0166-4637-a112-f8cc075edbee)

**Comment by Grisgram** [comment]
I've noticed this too in larger projects, had one 1.5GB monster running through the summer with several hundred included files, and it is really noticable when it reloads.

I'd also like to add, that it would really be cool (aside of CE2, which allows direct editing afaik), when a double-click on an entry of the included files would just launch the default associated app, just as if you would double-click the file in the file explorer

**Comment by stuckie** [comment]
This ended up being an external tool modifying the YYP, so this was working as intended.
