### ISSUE TITLE
[IDE] Included Files Window: DoubleClick on a file shall open default associated program

### ISSUE THREAD

**Issue by Grisgram** [YoYoGames/GameMaker-Bugs#7636]
### Is your feature request related to a problem?

It's just, that this additional explorer, that opens when you click the "Show in Explorer" buttons tends to become a pack animal, they are getting more and more because, _of course_, you forget to close the explorer after you double-clicked your file there.

### Describe the solution you'd like

Why not launch the associated app for the extension directly from the IDE? It's written in C# as far as I know, it's no black magic, to run/launch a process from C# (I mean, you can start an explorer, so you can start anything else too ;-)).

This would be a great QoL thing, really. GMS opens so many explorers, after packages, exports, templates... some of them are good to be opened -- but this one from the included files is not.

Thanks for reading,
kind regards
Gris

**Comment by stuckie** [comment]
This is already implemented.
You can right click and select to open in external editor:
![image](https://github.com/user-attachments/assets/97e48625-617e-4ce9-9add-1f6fd47a9274)

Additionally, you can change the defaults in Preferences:
![image](https://github.com/user-attachments/assets/82839154-7790-45dc-8663-90dd91b9567b)

**Comment by Grisgram** [comment]
oops...

thanks for taking the time to explain -- I really missed that one! ❤
