### ISSUE TITLE
Stability: [Mac IDE] GM crash due to internal error trying to open a window on the wrong thread

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#7648]
### Description
When editing a note in the code editor 2 with an open preview, an error suddenly occurred.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Mac 14.6.1

### Attached Files
* ui.log

[849c02b1-5e93-4870-828a-8c5926adf1d1](https://api.gamemaker.io/api/github/downloads/849c02b1-5e93-4870-828a-8c5926adf1d1)

**Comment by zreedy** [comment]
Initial investigation seems to reveal that the crash occurring while editing Notes in CE2 is incidental and not the true cause.
The stack trace seems to indicate that internet access was lost, a callback was attempted to be raised but an exception occurred at the .NET level and was subsequently caught by the `UnhandledException` handler. Unfortunately, the exception was caught on a background thread and attempted to show an "IDE has become unstable" message on this bg thread which ironically CTDs instead.

Unfortunately, the ui.log contains incomplete information and the .dmp files don't want to open in WinDbg or Visual Studio on Windows so this ticket is being given to Steven who has access to Mac OS X in an attempt to make sense of the .dmp file.

**Comment by stuckie** [comment]
Unfortunately, the dump file causes the .NET tools to fail as well, so I can't see what is in it.
We'll fix this as above, that a window tried to be spawn off the UI thread and caused a crash to desktop, rather than anything to do with Code Editor 2.

Thanks

**Comment by stuckie** [comment]
The Fatal Error dialog could sometimes appear off the main thread.
This should now be fixed.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.687  Runtime v2024.1100.0.708
