### ISSUE TITLE
Performance: GM hangs when closing a large number of editor windows at once in a workspace

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7654]
### Description
If you have a bunch of windows open in a workspace, and then either close that workspace tab or do right click --> windows --> close all, GameMaker will freeze  while the windows are being closed, and Windows will mark the program as not responding.

It's also notable that it seems to take about 3x as long to mass-close windows in the workspace compared to mass-opening windows.

https://github.com/user-attachments/assets/b5186d1f-0c32-4631-8eed-868ebde288f5

### Steps To Reproduce
Open a large number of assets (50-80+) in a workspace, and then close it. Sprite assets work well for reproducing the issue, since they seem to be slower to open/close than something like an empty object.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[66164a57-a86f-46e6-a771-7034871f884d](https://api.gamemaker.io/api/github/downloads/66164a57-a86f-46e6-a771-7034871f884d)

**Comment by KormexGit** [comment]
Out of curiosity, I tested this same thing in LTS, and LTS closes hundreds of workspace windows in just a few seconds, so it is a newer issue

**Comment by KormexGit** [comment]
I just confirmed this does not happen in 2024.6 either, so this is a new issue to 2024.8

**Comment by stuckie** [comment]
Adding a project layout with everything open ( which similarly takes some time to open in the first place. )
Looks to be an issue with cleaning up delegates.

[project_layout.zip](https://github.com/user-attachments/files/17028251/project_layout.zip)

**Comment by stuckie** [comment]
This should now be resolved from various optimisations that have been made.

**Comment by scott-dunbar** [comment]
This appears to be substantially better in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
