### ISSUE TITLE
Text - string_height returns non-useful value if there are line breaks in a string

### ISSUE THREAD

**Issue by patrickrocheyoyo** [YoYoGames/GameMaker-Bugs#7662]
### Description

string_height doesn't take line breaks into account. It counts the height of a single line rather than the entire block text that's being shown.

### Expected Change

For string_height to give the height of the string, even across line breaks in the string

### Steps To Reproduce

1. Start GameMaker
2. Add a string with a line break
3. Add a string_height measure to it
4. Notice that it's only getting the height of the base string, not the height when shown in game
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by attic-stuff** [comment]
according to the manual [it does](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Strings/string_height.htm) and a quick test here shows that it seems to be working fine in the 2024.8:

![Capture](https://github.com/user-attachments/assets/aba230bc-cf23-4752-8e3c-20f2b9d4e624)

if you're using draw_text_ext make sure you use string_height_ext. also in the future you should include a project demonstrating the bug

**Comment by gnysek** [comment]
According to HTML5 source, it returns height of highest gylph (multiplied by number of lines):

https://github.com/YoYoGames/GameMaker-HTML5/blob/develop/scripts/functions/Function_Font.js#L333
https://github.com/YoYoGames/GameMaker-HTML5/blob/develop/scripts/yyFont.js#L413

**Comment by stuckie** [comment]
Closing as above. Thanks!
