### ISSUE TITLE
[Android] Enabling Dynamic Asset Delivery makes audio files in accessible

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7668]
### Description
We are getting the following errors when trying to play audio assets in an android export that has Dynamic Asset Delivery enabled and downloaded through Google Play Internal app sharing:

```
09-16 23:43:12.843  6100  6144 I yoyo    : attempting to return GetAssetManager()
09-16 23:43:12.843  6100  6144 I yoyo    : asset assets/audiogroup1.dat reports size 142996
09-16 23:43:12.843  6100  6144 I yoyo    : Audio group 1 -> Loading...
09-16 23:43:12.858  6100  6144 I yoyo    : Audio group 1 -> Loaded
09-16 23:43:12.858  6100  6144 I yoyo    : attempting to find dynamic asset:assets/grc_snd_silence_for_dynamic_asset.ogg
09-16 23:43:12.859  6100  6144 I yoyo    : attempting to find dynamic asset:assets/grc_snd_silence_for_dynamic_asset2.ogg
09-16 23:43:12.867  6100  6196 I yoyo    : Unable to get JNIEnv
09-16 23:43:12.868  6100  6197 I yoyo    : Unable to get JNIEnv
09-16 23:43:12.875  6100  6144 I yoyo    : Error: Failed to open file stream
09-16 23:43:12.875  6100  6144 I yoyo    : Error: Failed to open file stream
09-16 23:43:12.875  6100  6144 I yoyo    : Error: Could not find decoding task for sound with id 400002
09-16 23:43:12.964  6100  6144 I yoyo    : Warning: Index did not map to an existing sound instance
09-16 23:43:12.964  6100  6144 I yoyo    : User defined non-struct error
```

### Steps To Reproduce
1. Build for Android YYC export in the AAB format under the dev config 
2. Upload the AAB file to Interal App Sharing https://play.google.com/console/u/0/internal-app-sharing/
3. Download the app on an Android device through internal app sharing
4. Launch the app and see error above, which indicates that the game cannot access the the audio resources.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1000.0.621 Runtime v2024.1000.0.647

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android

[be989533-399d-464e-ab3e-6cf4761c4464](https://api.gamemaker.io/api/github/downloads/be989533-399d-464e-ab3e-6cf4761c4464)

**Comment by toby-yoyo** [comment]
Fixed an issue where the decoding threads were not assigned a JNI env.

**Comment by mgeddesGM** [comment]
verified  IDE v2024.1100.0.627  Runtime v2024.1100.0.653
