### ISSUE TITLE
Feather: Need to reflect new global function scoping rules

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#7680]
### Description

A change in the behavior of named function scoping has recently been made in 2024.10. The details of which are in https://github.com/YoYoGames/GameMaker-Bugs/issues/7125. Feather needs to be updated to reflect this change in behavior.

```gml
/// oPlayer : Create
global.player = id;
function speak() {
    show_debug_message("wow");
}

/// oPlayer : Key Pressed <Space>
speak(); // Good!

/// oMob : Key Pressed <Space>
oPlayer.speak(); // Good! This is the relevant change
global.player.speak(); // Good!
```

This is a linked ticket for tracking purposes.

### Steps To Reproduce

The repro sets are detailed above, and in further detail in the linked ticket.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gnysek** [comment]
From what I understand:
```gml
/// oMob : Key Pressed <Space>
oPlayer.speak(); // Good! This is the relevant change
global.player.speak(); // Good!
```
can be executed only if at least one instance of `oPlayer` exists, and as such it could be warning too, as it might crash game in some situations...

Another example:
```gml
/// oPlayer : Create
global.player = id;
function speak() {
    show_debug_message("wow");
}
global.player_speak = speak; // handle

/// wherever
global.player_speak.speak(); // Good!
```
Seems to be valid too.

**Comment by zreedy** [comment]
I tested against all linked tickets and it appears that Feather already reflects the expected behavior.

**Comment by rwkay** [comment]
**** IMPORTANT ****

Most of this feature has been backed out from 2024.11 as we have discovered - functions that are declared within an event will still be available through the `asset_` functions, but the optimisation that meant they were called directly (like a function) which would speed up execution as this only worked in cases where object inheritance had been used, and the method for the function was being relied upon.

This was incompatible with the optimisation and so reluctantly we have removed this - we will revisit how this works in GMRT and look to improve the performance of these types of function calls at that point.

**** IMPORTANT ****

**Comment by YYDan** [comment]
So, has this one also been fully reverted now and this issue should actually just be closed as Not Planned? Or is there still a change here to be verified?

**Comment by rwkay** [comment]
I suspect I need to talk to Zach - but I suspect that we do not need to change anything

**Comment by YYDan** [comment]
Yes, no change remains. Closing as Not Planned.
