### ISSUE TITLE
Manual Content: buffer_set_surface() page has unhelpful documentation

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7683]
### Description

This is a completely unhelpful example, and the page does not give enough information about how this is handled with surface formats and what their standards should be.
Ideally a look up table / referencewould be better hear to compare the format, the buffer, and how that looks in hex.

![image](https://github.com/user-attachments/assets/b0cbd33b-22ec-4f6b-8315-12d7fa1cc879)

Additionally `surface_create` is a much more helpful page however it still does not really give much information as to how to make use of formats and buffers.

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FBuffers%2Fbuffer_set_surface.htm

**Comment by gurpreetsinghmatharoo** [comment]
Updated examples on `buffer_set_surface` and `buffer_get_surface` to mention formats for 2024.10 manual.

Thank you

**Comment by tinkerer-red** [comment]
Gamer, thank you
