### ISSUE TITLE
`real("infobar")` returns `infinity` at runtime only (and similar for `NaN`)

### ISSUE THREAD

**Issue by shdwcat** [YoYoGames/GameMaker-Bugs#7685]
### Description

According to the manual, calling `real()` on a string with letters on it will throw an error:
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Freal.htm
> When using this function on a string, numbers, minus signs, decimal points and exponential parts in the string are taken into account, while other characters (**such as letters**) will cause an error to be thrown

(emphasis added)

It's pretty common when writing parsers to use `real(some_string)` (inside a try/catch) to check if the string should be decoded as a number. In this case, a user of my code was triggering a call to `real("infobar")` which was returning `Infinity` which is obviously both a nonsense result and invalid according to the behavior described in the manual. In fact, if you simply type `real("infobar")` into plain gml the compiler will complain that it cannot perform the conversion when it tries to optimize at compile-time.

The same is also true for `NaN` (try `real("nano")`). I'm not sure if there are any other numeric constants.

It's also true for `real("42 apples")` at runtime. This was previously raised in [another issue](https://github.com/YoYoGames/GameMaker-Bugs/issues/6396) and closed, but given that the manual says this is invalid AND the compile-time version will also throw an error in this case, I think this should officially be considered a bug and fixed.
[report.zip](https://github.com/user-attachments/files/17034628/report.zip)

### Expected Change

When called at runtime `real()` should follow the behavior described in the manual and error if there are any letters in the string

### Steps To Reproduce

1. Start GameMaker
2. Create a script with the following code:
```
var arr =["infobar"];
var inf = real(arr[0]);
show_debug_message("is infinity: " + string(inf == infinity));
```
3. Run the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11 - now throws an error when there are trailing characters on a REAL

**Comment by scott-dunbar** [comment]
Confirmed issue no longer present - error occurs as described in  IDE v2024.1100.0.629  Runtime v2024.1100.0.654

Awaiting confirmation from Docs before closing issue

**Comment by gurpreetsinghmatharoo** [comment]
No docs changes needed

**Comment by scott-dunbar** [comment]
Verified in  IDE v2024.1100.0.631  Runtime v2024.1100.0.656
