### ISSUE TITLE
GMRT: Putting an anonymous function in show_debug_message prints a blank line 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7689]
### Description
If you do `show_debug_message(function() {});` in GMS2 runtime, you'll get something like `function gml_Script_anon@15@gml_Object_Object2_Create_0`. If you do it in GMRT, you instead get a completely blank line.

### Steps To Reproduce
```
myCoolMethod = function() {}

show_debug_message(myCoolMethod);
show_debug_message(function() {});
```
Both of these will print a blank line in GMRT

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.800.0.642

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[27e3bd75-603b-48dd-bc43-c2f35721566e](https://api.gamemaker.io/api/github/downloads/27e3bd75-603b-48dd-bc43-c2f35721566e)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1151  Runtime v2026.100.0.1101 gmrt 0.22.78
