### ISSUE TITLE
[IDE] Please add an option to disable bookmarks

### ISSUE THREAD

**Issue by caroparo** [YoYoGames/GameMaker-Bugs#7700]
### Is your feature request related to a problem?

Sometimes when switching language IMEs, ctrl-shift must be held and the code bookmarks functionality would be triggered by accident. When it happens, these bookmarks somehow cannot be removed by pressing the "ctrl-shift-[0-9]" keys; perhaps because the code position is off due to active IME. Then I have to shutdown the whole IDE just to clear this bookmark.

Preferrably this failure to clear issue can be solved. However, I'd accept an easy alternative of disabling bookmarks since I don't use them at all.

### Describe the solution you'd like

An options exists in the IDE to disable the whole code bookmarking feature.
https://manual.gamemaker.io/monthly/en/IDE_Navigation/Bookmarks.htm

### Describe alternatives you've considered

The bookmark clearing bug is fixed, so it's always possible to clear the accidental bookmarks.

**Comment by KormexGit** [comment]
![image](https://github.com/user-attachments/assets/22cd662e-461e-47f0-ad7a-a837884a2fa9)
You could unbind all of the bookmark keybinds to disable them

**Comment by stuckie** [comment]
Closing as above. Thanks.
