### ISSUE TITLE
Building Projects: Compiler optimisation for mod operator % is not correct, causes "Modulo by 0" errors

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#7705]
### Description

```
show_debug_message( 2.2 % 0.5 );
```

does not output 0.20 has expected but errors with "Modulo by 0" at the compiler level

### Expected Change

should not error at compile time

### Steps To Reproduce

1. Start GameMaker
2. Start New project
3. Paste in the code above... and compile.
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.639  Runtime v2024.1100.0.662
