### ISSUE TITLE
In-Game: [YYC] Cannot find static variable "self.useChunks" if built using 2024.8 runtimes

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7732]
### Description

The following code `FallingSandJavaPort/CellularAutomaton/line 89 - line 100` fails in some use cases but not others when using yyc compile.

![image](https://github.com/user-attachments/assets/ef7062f3-d137-4ffc-9d10-120947fd0576)
results in
![image](https://github.com/user-attachments/assets/3666ac13-3880-4926-8754-91b0832a59ce)

Oddly enough there are many other static variables which have no problem being read in any of the three formats listed here, it is literally just this one, and only for two of the formats.

Private Project Link:
https://api.gamemaker.io/api/github/downloads/719f5a1a-169b-47d7-b794-409e5db70183

### Steps To Reproduce

1. Start GameMaker and import the attached project
2. Run it using YYC
3. Observe the code error which appears immediately after startup (see above)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
I cannot repro this in 2024.11 - I presume earlier fixes have fixed this

**Comment by YYDan** [comment]
Reproduces just the same in IDE v2024.1100.0.629  Runtime v2024.1100.0.654 for me:

![image](https://github.com/user-attachments/assets/d616e34b-48b8-4e45-b301-6eecb520a5ee)

Reopening.

**Comment by rwkay** [comment]
OK This project has lots of issues, though there is a YYC bug in there as well that makes it worse...

The main issue in the project (that contributes to the issue) is that references to the static variable `useChunks` is done in many ways (it is read as the static variable `CellularAutomaton.useChunks` by the `self.useChunks` and by `useChunks`, this is confusing to the compiler as it thinks of these as different things - it is also written to using `useChunks = <expr>`, this actually means that a local variable `useChunks` is written to and not the static variable, so it is not doing what you think... you should be using `CellularAutomaton.useChunks = <expr>` to ensure the static variable is being written to and not a local struct / instance variable is written to).

The code is full of these sort of mistakes and I have had both VM and YYC crash in the project (I am not debugging it any further).

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by mgeddesGM** [comment]
verified issue on line 91 now solved in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666

issue on line 94 solved via change mentioned in @rwkay's comment

**Comment by tinkerer-red** [comment]
Oh I see, from the syntax highlighting I presumed that a variable declared as a static (assuming the highlighting permits) would be written to as a static, the same way `var` and `globalvar` would do. The project has been on hold for a while but after resolving those issues when monthly comes out, if there is any other compile issues ill open a new ticket. Thank you for the support!
