### ISSUE TITLE
Manual Content: Manual incorrectly says that precise per frame collision masks have a different bounding box per subimage 

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7735]
### Description

On the manual page for the sprite editor, under the collision mask section, is the following:
"Finally you can set the Bounding Box limits for the mask. The bounding box is the name given to the rectangular area that the sprite mask fits in. Only pixels inside this bounding box are used for the mask and will be involved in collision checking, and by default this is automatically computed, taking the alpha tolerance into account. _**If you have "precise (per frame)" checked then this will be separate for each sub-image too.**_"

The bolded part is not actually true, manual mode precise per frame masks use the same bounding box for every subimage.

https://github.com/user-attachments/assets/b9b40fbf-6ab9-49dc-91ff-369803af29c1

Even if you use automatic mode so that each subimage has a different mask, bounding box values are still the same between all frames in-game.

### Manual Link

https://manual.gamemaker.io/monthly/en/index.htm#t=The_Asset_Editors%2FSprites.htm

**Comment by gnysek** [comment]
> Only pixels inside this bounding box are used for the mask

For me:
- precise = pixels in bounding box in FIRST frame
- precise per pixel = pixels in bounding box in CURRENT frame
