### ISSUE TITLE
UI/UX: Language Server errors do not display the full path if it contains spaces

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#7739]
### Description

Language Server notification will not display full path if it contains spaces

If the project path contains a space (project name is "Blank Game_10"
![image](https://github.com/user-attachments/assets/e05ab958-3685-44cf-85cb-e8fd8a5297bd)

or in directory
![image](https://github.com/user-attachments/assets/92b8de6c-aa1a-4def-b4e6-e93f15d7cbaf)

If the project path contains no spaces it works fine
![image](https://github.com/user-attachments/assets/05055bdc-6266-46e0-8c46-1751c7e93b4c)

### Steps To Reproduce

1. Start GameMaker
2. Create a new project witha  space in the name (or use a directory with a space
3. due to https://github.com/YoYoGames/GameMaker-Bugs/issues/5251 you will get this error (if it is fixed in the meantime you will have to trigger this error a different way)
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by gnysek** [comment]
Also, if path is very long, it won't fit on screen (except that's already fixed, as from your screenshots it looks there's no such problem anymore).

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1300.0.721  Runtime v2024.1300.0.734
