### ISSUE TITLE
GMRT: Clean up event is not called for deactivated instances when changing rooms

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7744]
### Description
The attached project is a modified version of Windy Woods, where the player starts next to the end gate.

When going back to the main menu from this point (which calls `room_goto`), the Clean Up event for `obj_end_gate` is not called. This differs from the GMS2 runtime, on which it is called.

Below are the logs from each runtime, showing the difference:

**GMS2**
```
In obj_end_gate: Create
Going back to rm_menu...
In obj_end_gate: Clean Up
```

**GMRT**
```
In obj_end_gate: Create
Going back to rm_menu...
```

### Steps To Reproduce
- Open and run the attached project.
- Press 'Play'.
- Press 'Esc' and click 'Back to Menu'.
- Observe in the log that the clean up event for `obj_end_gate` was not called.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.795 Runtime v9.9.1.957

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[89cd981d-6501-4f8e-8ac8-79dc61670329](https://api.gamemaker.io/api/github/downloads/89cd981d-6501-4f8e-8ac8-79dc61670329)

**Comment by toby-yoyo** [comment]
Attached is a more minimal example of the issue: [gmb-7744-x.zip](https://github.com/user-attachments/files/17134924/gmb-7744-x.zip)
- Open and run the project. You should hear some counting.
- Press `Esc` to deactivate instances.
- Press `1` to change room.
- The counting should stop.
- The log should read as below:
```
In obj_emit: Create
Going to rm_2...
In obj_emit: Clean Up
```

**Comment by toby-yoyo** [comment]
Clean-up events will now be called for deactivated instances, as in the current runtime.

**Comment by mgeddesGM** [comment]
verified for  IDE v2024.1300.0.720  Runtime v2024.1300.0.733 using  0.15.7
