### ISSUE TITLE
Hidden object rollback event handlers

### ISSUE THREAD

**Issue by betofloresbaca** [YoYoGames/GameMaker-Bugs#7746]
### Description
When trying to add an event handler to any object the following events are not in the dropdown:
* Rollback Start
* Rollback End

### Steps To Reproduce
* Create a project
* Create an object
* In the object go to: Events -> Add Event -> Other
* The rollback envents section is empty

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files
* Screenshot 2024-09-23 094928.png

[7a26f954-3bd7-4d68-8d1a-024eaa60f188](https://api.gamemaker.io/api/github/downloads/7a26f954-3bd7-4d68-8d1a-024eaa60f188)

**Comment by stuckie** [comment]
The rollback is only fully available in Beta releases.
