### ISSUE TITLE
LTS IDE 2022.0.3.71 imports 2024.8.1.171 project and becomes read-only

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7750]
### Description
Our project is IDE 2024.8.1.171 compatible, but when opening it with LTS IDE 2022.0.3.71, the project becomes read-only.

### Steps To Reproduce
1. Open the sample in  LTS IDE 2022.0.3.71
2. See that it is read-only

### Which version of GameMaker are you reporting this issue for?
IDE v2022.0.3.71 Runtime v2022.0.3.83

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[37fc1f1c-3a44-4049-9db6-58c5490fc62c](https://api.gamemaker.io/api/github/downloads/37fc1f1c-3a44-4049-9db6-58c5490fc62c)

**Comment by stuckie** [comment]
That is correct.. if you need to be able to edit it, you'll need to use a *recent* ProjectTool to export down to the correct LTS-22 format.
