### ISSUE TITLE
Remove Code Unfolding After PASTE

### ISSUE THREAD

**Issue by digwallace** [YoYoGames/GameMaker-Bugs#7751]
### Is your feature request related to a problem?

This is a follow-up to ticket #4441 , which I _think_ was eventually merged into the recent memory leak fix, though I've been unable to follow it. However this is still present in IDE v2024.8.1.171 and unrelated to the leak, though memory/cache misses do seem to worsen it.

Currently, when using PASTE in folded code, seemingly in a single statement or declaration, the rest of said statement or declaration will unfold. This doesn't happen while regularly deleting and editing the line of code, only when using PASTE.

This can propagate to different statements and declarations beneath the change, presumably due to the aforementioned memory/cache misses, and this can result in the remaining code block to unfold, or in some cases the entire rest of the file. Note that while I don't have footage of the latter, I can confirm it still occurs.

### Describe the solution you'd like

I'd like to disable this specific unfolding, as I do not want code folded or unfolded unless I choose to.

Note that I would like to keep the auto-unfolding that exists when clicking a line in the Search Results or Compile Errors tabs, however if I had to pick between the two, I'd rather not have any auto-unfolding.

### Describe alternatives you've considered

As mentioned in #4441 I'm aware of the feature and shortcut for folding all regions, however in long-term development, this is still inconvenient as there's no replacement for keeping things folded in a specific manner.

### Additional context

I'm attaching a video which will show me using PASTE many times, folding them afterward, followed by me editing the same lines manually without them folding.

![GM08cef2d0c8](https://github.com/user-attachments/assets/19f5ab4c-6195-4e8d-9835-f0b396cc9077)

**Comment by digwallace** [comment]
Uploading GameMaker_SfdcAIn9wt.mp4…

**Comment by YYDan** [comment]
#4441 is still open and was not part of any recent memory fixes, so I have just taken the extra info here and slipstreamed it into your original issue.
