### ISSUE TITLE
IDE Prompts: Switching to CE2 with unsaved changes show a prompt stating the user will be prompted to save, the prompt never appears

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#7755]
### Description

Switching to CE2 after making unsaved changes displays a prompt to the user that the IDE needs to be restarted, the user has unsaved changes and they will be prompted to save. The user then clicks OK, the save prompt never appears and the IDE restarts losing all unsaved changes.

Bug found in Beta: IDE v2024.1100.0.626  Runtime v2024.1100.0.652

https://github.com/user-attachments/assets/79f90b12-d329-4862-b7c9-8ac750ff1527

### Expected Change

The prompts to allow the user to save an unsaved changes to be displayed.

### Steps To Reproduce

1. Start GameMaker
2. Create a new project with an object
3. Don't save
4. Switch to CE2 via the prefs menu
5. See the prompt
6. Click OK
7. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by CalumLaverock** [comment]
This was actually a problem with all restart prompts of this nature (CE2 enabling, DPI change, etc) but they should all now give a save prompt after the restart prompt. As part of this some code was cleaned up and thee "end_session" analytic event was given a "restart" key to say if the session was ended due to an IDE restart or not

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.631  Runtime v2024.1100.0.656.
