### ISSUE TITLE
Debugger: Can add/delete events while paused if using Code Editor 2

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7758]
### Description
With the debugger now displaying with CE2, I discovered that the buttons to add or delete events still work while running the debugger. If you delete an event that currently has breakpoints, the breakpoints will keep triggering, but are unable to show the code since you deleted the event in the IDE. In this video I delete the event using the navigation panel's X button, but you can also right click on the event headers and delete the event that way, or use the inspector.

https://github.com/user-attachments/assets/ce8a0157-537c-4c78-8ab1-08cbde67d498

When combined with #7760, you can make this completely blank tab appear:

https://github.com/user-attachments/assets/56e30f8e-59f6-40b9-9176-0aa979a0731c

### Steps To Reproduce
Set a breakpoint, run the debugger, and then delete events while the game is paused.
To reproduce the blank tab, re-add a deleted event from the debugger, add a new breakpoint on the same line as before, and hit play.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.626 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b972c79a-0816-49a5-aa55-a52fae9e41c2](https://api.gamemaker.io/api/github/downloads/b972c79a-0816-49a5-aa55-a52fae9e41c2)

**Comment by zreedy** [comment]
Fixed

**Comment by scott-dunbar** [comment]
Verified fixed in 

 IDE v2024.1100.0.646  Runtime v2024.1100.0.666
