### ISSUE TITLE
Debugger: Closing the workspace tab creates a broken "Edit" menubar item each time if CE2 is enabled

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7759]
### Description
Running the CE2 debugger and then closing the debugger tab creates the ol' classic glitchy edit menus. You can re-run the debugger and re-close the tab as many times as you like for unlimited edit menus.

https://github.com/user-attachments/assets/d532295e-beab-43a6-a3c1-9b1bf6ab9880

### Steps To Reproduce
Run the debugger, then close the debugger tab. Doesn't seem to matter when you close it.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.626 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[41fa9953-3a89-4b91-936d-d6be63361e89](https://api.gamemaker.io/api/github/downloads/41fa9953-3a89-4b91-936d-d6be63361e89)

**Comment by zreedy** [comment]
Fixed.

**Comment by scott-dunbar** [comment]
Unable to repro in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666

Closing
