### ISSUE TITLE
Code Editor 1 and 2: Deleting an event does not clear breakpoints assigned to it

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7760]
### Description
If you add some breakpoints to an event and then delete it, the breakpoints will keep existing even though the line of code they were added to no longer exists. Re-creating the event allows you assign breakpoints to the same line multiple times. This applies to both CE1 and CE2.

https://github.com/user-attachments/assets/575a1dda-47cf-44e2-823d-51edc043c938

https://github.com/user-attachments/assets/6894d713-fb3b-4f48-a234-398439cc4076

### Steps To Reproduce
Add some breakpoints to an event, then delete it. Re-add the same event and same breakpoints.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.626 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4738691c-a396-4739-868b-ce79e424149d](https://api.gamemaker.io/api/github/downloads/4738691c-a396-4739-868b-ce79e424149d)

**Comment by zreedy** [comment]
Fixed.

**Comment by sihammill** [comment]
Verified in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
