### ISSUE TITLE
[GameMaker HTML5] "Unable to obtain a valid license, please check the License Key and retry!" on all license keys

### ISSUE THREAD

**Issue by LiEnby** [YoYoGames/GameMaker-Bugs#7763]
### Description

Attempting to use a original license key for GM:HTML5 gives :

"Unable to obtain a valid license, please check the License Key and retry!"
![image](https://github.com/user-attachments/assets/311da7a5-d1e3-43bf-b8ec-ffef2f68e6a8)

this happens regardless of if you enter an original license key or not, it will always give this error.

### Expected Change

be able to use gamemaker html5 again 

### Steps To Reproduce

1. Install GameMaker HTML5
2. Enter license key
3. See the issue "Unable to obtain a valid license, please check the License Key and retry!"

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by LiEnby** [comment]
had a look in fiddler web proxy to see what it's actually getting sent to the server ..
![image](https://github.com/user-attachments/assets/7a45e593-8419-4e69-931d-f866ea227fb0)

and the server actually is giving a license,
but think this might be the problem :
```
	<key>Product</key>
	<string>GameMaker:Studio</string>
```
im pretty sure that should be something like "GameMaker HTML5" not "studio"

**Comment by stuckie** [comment]
This product is no longer supported.
Our current GameMaker is available for free - https://gamemaker.io
