### ISSUE TITLE
In-Game: Constructor inheritance is also broken for YYC in internal 2024.1100 Beta

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7765]
### Description
This is related to https://github.com/YoYoGames/GameMaker-Bugs/issues/7752, but this  code also throws the same error in YYC export:

```gml
			function Hello() constructor
			{
			    static variable = 0;
    
			    static add = function() {
			        Hello.variable++;
			    }
			}
			Hello();

			Hello.variable++; //works
			Hello.variable--; //works
			Hello.variable = Hello.variable + 1; //works
			Hello.variable = Hello.variable - 1; //works
			Hello.variable = Hello.variable * 2; //works
			Hello.variable = Hello.variable / 2; //works, even with 0
			Hello.variable -= 1; //broken
			Hello.variable += 1; //broken
			Hello.variable *= 2; //broken
			Hello.variable /= 2; //broken
```
			show_debug_message(Hello.variable);

### Steps To Reproduce
1. Run the project in Windows YYC

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.624 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[68420a34-f573-4b78-aad3-694a02c850f2](https://api.gamemaker.io/api/github/downloads/68420a34-f573-4b78-aad3-694a02c850f2)

**Comment by GameDevTosh** [comment]
I think this one would be more related to the requirement that we now have to use **new**, even to initialize the statics, so the previous code should now use:
`new Hello();`

To function properly, according to discussions with Russell in the discord beta channel. So the error makes sense. Its just constructor inheritance that's actually busted.

**Comment by GameDevTosh** [comment]
Okay I just verified this. Doing Hello(); in VM works 100% to initialize statics still, but for YYC you have to use new Hello() in 2024.11.

**Comment by rwkay** [comment]
Unable to replicate - this is working as expected when https://github.com/YoYoGames/GameMaker-Bugs/issues/7752 is fixed - you need to ensure that the call to `Hello()` is changed to `new Hello()`

**Comment by YYDan** [comment]
Confirmed that all is well in IDE v2024.1100.0.629  Runtime v2024.1100.0.654, following the other fix.
