### ISSUE TITLE
Code Editor 2: Add support for GML Visual

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#7769]
### Description

If you open a GML Visual document which contains a GML Code node, upon initial open there is no color coding applied. This can be severe enough that entire lines of code are invisible despite the contents existing and editable.

### Expected Change

Color coding should apply upon open, and all text should be visible

### Steps To Reproduce

1. Start GameMaker
2. Open an or create an Object with a GML Visual document which has a GML Code node
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by cameron-home** [comment]
All of the points above now verified in IDE v2024.1100.0.635  Runtime v2024.1100.0.659
