### ISSUE TITLE
Project Import: Since 2024.1100 Beta 1 shows redundant GMSC "polymorphism" error when importing LTSr3 .yyzs

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#7771]
### Description

Importing my sample off 7701 into 2024.1100 Beta 1 showed an unexpected project failure dialog and an error:
![image](https://github.com/user-attachments/assets/5895b172-883f-4935-8f52-30e2ca97d96c)

However, this did not actually appear to stop the project having loaded fully (as far as I can tell) and even building/running just fine.

_2024.8.1 has no such issue, so this is new._

[LTSStructTest-Dan.zip](https://github.com/user-attachments/files/17129709/LTSStructTest-Dan.zip)

https://api.gamemaker.io/api/github/downloads/e245884f-f506-4dd8-b88e-76d5bd8dbafd (including ProjectTool output)

### Expected Change

This error to not be shown

### Steps To Reproduce

1. Start GameMaker 2024.1100
2. Drag the project attached above onto the Start Page and import it that way
3. See the issue when the project has loaded

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by gnysek** [comment]
I have same issue when trying to open https://github.com/DragoniteSpam/GMBenchmark in 2024.8.0 monthly and 2024.1100 betas.

**Comment by stuckie** [comment]
This would have affected all "2.3" projects - so that sweet spot between the new current format, and the older 2.2.5 projects.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664
