### ISSUE TITLE
Texture Group Manager: Fails to load correctly Texture Groups/becomes unresponsive on projects with more than one Texture Group

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7788]
### Description

When using the texture group manager on Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652, sometimes stops responding/loading all the texture groups available on that project. Closing and reopening the Editor doesn't seem to make any difference. Potentially it gets worse if different texture groups have different settings.

The below examples are the same project:
![texturegroupeditor](https://github.com/user-attachments/assets/49bf490b-2e4e-4a0c-b685-e50368191efa)

![image](https://github.com/user-attachments/assets/1783b85e-a2e6-4cf9-8ab8-931d1d3845e3)

### Steps To Reproduce

1. Start GameMaker
2. Create/open a new start game template or any other project that uses different texture groups
3. Go to the Texture Group manager (Tools>Texture groups)
4. Attempt to change the Current Group using the dropdown
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This was actually a focus issue, as clicking away and back into the window "fixed" it
