### ISSUE TITLE
In-Game: audio_play_sound() and audio_play_sound_at() are not covered by audio_throw_on_error()

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7790]
### Description
Bad index errors from `audio_play_sound` and `audio_play_sound_at` are not  currently suppressed by `audio_throw_on_error(false)` as the asset references are handled by the runner.

For `audio_play_sound_on` and `audio_play_sound_ext`, the handling of refs happens to be less strict and this allows the audio library to handle the error itself.

We should bring `audio_play_sound` and `audio_play_sound_at` into line with `audio_play_sound_on` and `audio_play_sound_ext`, so that there aren't exceptions to the kinds of errors handled by `audio_throw_on_error`.

### Steps To Reproduce
- Open and run the attached project.
- Observe that the game throws, despite `audio_throw_on_error(false)` being called.
- Expected behaviour is that none of the subsequent erroneous calls should throw.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[a3ead3bc-d98a-4a72-a473-bbb082740951](https://api.gamemaker.io/api/github/downloads/a3ead3bc-d98a-4a72-a473-bbb082740951)

**Comment by toby-yoyo** [comment]
Prevented the runner from throwing for bad asset refs passed to `audio_play_sound` and `audio_play_sound_at`, so that the audio layer can handle the error.

**Comment by Emc1923** [comment]
Verified done, awaiting documentation changes. Added: https://github.com/YoYoGames/GameMaker-Bugs/issues/7871

**Comment by toby-yoyo** [comment]
Just to clarify - it shouldn't be expected for this to behave in the same way on HTML5.

The audio library that the new audio errors (and the accompanying `audio_throw_on_error` function) relate to is only used in the C++ runner. The HTML5 runner has an entirely different audio system and does not have any of that functionality, so `audio_throw_on_error` won't be supported. Like all unsupported functions on HTML5, when called they will print out a message to the console of the format:
```
Error: function audio_throw_on_error() is not supported.
```
