### ISSUE TITLE
In-Game: [Android] "Failed to get JVM from main thread" is always printed to the console when not using Dynamic Asset Delivery

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7792]
### Description
On Android, when not using Dynamic Asset Delivery, at game start you will see a number of errors in the console stating:
```
Failed to get JVM from main thread
```
This should only be printed if the game is using Dynamic Asset Delivery, and the JVM failed to be passed across to the decoding threads.

### Steps To Reproduce
- Open and run the attached project on Android.
- Note the instances of the error message in the console.
- Expected behaviour is that they should not be printed.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Android

[bbc78bc8-1da1-45ba-8adb-9d5062018e79](https://api.gamemaker.io/api/github/downloads/bbc78bc8-1da1-45ba-8adb-9d5062018e79)

**Comment by toby-yoyo** [comment]
The error should now never be printed when not using Dynamic Asset Delivery.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.646  Runtime v2024.1100.0.666.
