### ISSUE TITLE
Building Projects: [Android] Gradle daemons are not stopped after failed builds

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#7794]
### Description

If a user clean a build the relevant OpenJDK Platform binary can be seen in the task manager during the clean. This is then stopped and removed on the clean finishing.

If a build is attempted and then failed the OpenJDK Platform binary will remain until a clean is ran

### Expected Change

OpenJDK Platform binary stops on build failed

### Steps To Reproduce

1. Start GameMaker and log in with an account that has the android access
2. go to preferences - Platform settings - android
3. complete the paths section
4. add this KeyStore file [CertCert.zip](https://github.com/user-attachments/files/17148859/CertCert.zip) to the Filename field
5. press apply
6. create a blank project or open a pre-populated ones
7. open task manager, see no OpenJDK Platform entry
8. press clean, notice OpenJDK Platform appears then disappears
9. target an android device and press build
10. see in taskmanager OpenJDK Platform appears but does not disappear on build fail
11. press clear, all OpenJDK Platform entries disappear

 [bug package](https://api.gamemaker.io/api/github/downloads/8130ff9e-7d40-4757-b8eb-574f1950af42)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Gradle daemons are reused by the next build, so stopping them unnecessarily will lead to longer build times. We stop them on a clean to prevent any potential issues, but shouldn't do this if the build just fails?
