### ISSUE TITLE
In-Game: Calling a constructor from within another constructor causes runtime error to occur in VM and YYC

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#7795]
### Description

Trying to call a constructor from within another constructor in VM and YYC causes a runtime error

Error displayed to user:
![image](https://github.com/user-attachments/assets/32ee7abc-a9eb-4d6d-85d2-815a5b63240e)

Code example:
```
function Cas() constructor {
    show_debug_message("Calling Cas");
    var BCas = new Bee();
}

function Bee() constructor {
    show_debug_message("Calling Bee");
}

var bee = Cas();
show_message(instanceof(bee)); // Bee
```

### Expected Change

Both Cas and Bee constructors should be called without fail

### Steps To Reproduce

1. Start GameMaker
2. Add the given code example to a project
3. Run project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
The error is caused by the line `var bee = Cas();` it needs to be `var bee = new Cas();`

**Comment by sihammill** [comment]
Originally my code did call the Cas() constructor using the 'new' keyword when testing and this was fine, it was this line within the Cas() constructor that was causing the issue:

`var BCas = new Bee();`

I discussed this with @kat-fl, who was in agreement that there was most certainly a bug there. However, I have now retested this and it is working as expected in IDE v2024.1100.0.639  Runtime v2024.1100.0.662
