### ISSUE TITLE
In-Game: audio_pause_all() does not update sync group states

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7797]
### Description
While `audio_pause_all` now correctly pauses sync group tracks, `audio_sync_group_is_paused` will incorrectly return `false` when a sync group has been paused that way.

### Steps To Reproduce
- Open and run the attached project.
- Press `1` to pause all sounds.
- Note that the sync group state does not indicate that it is paused.
- Press `2` to resume all sounds.
- This should clear the paused state of the sync group.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[92e91f18-8a7e-489d-91bc-2aa344c3d232](https://api.gamemaker.io/api/github/downloads/92e91f18-8a7e-489d-91bc-2aa344c3d232)

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.631  Runtime v2024.1100.0.656
