### ISSUE TITLE
In-Game: "event_object" still returns a number, not an object reference

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#7800]
### Description

`event_object` should be returning an object asset reference, as the manual states it should

### Steps To Reproduce

1. Start GameMaker and import [event_object.zip](https://github.com/user-attachments/files/17161142/event_object.zip)
2. Run it (e.g., Win VM)
3. Observe the two values drawn on-screen are reals, not references

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
The manual does not say this has been changed to be a reference yet, so it's expected to still be the object index, as documented: 

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FAsset_Management%2FObjects%2Fobject_get_name.htm

**Comment by YYDan** [comment]
Hehe, copy-paste error there - that IS the page I meant to link to ;)

**Comment by Emc1923** [comment]
The HTML5 target is still returning an integer as of  IDE v2024.1100.0.631  Runtime v2024.1100.0.656. Reopening for now, thanks.

**Comment by stuckie** [comment]
Closing as HTML5 does not support references for all things.

**Comment by Emc1923** [comment]
Verified as per comment above.
