### ISSUE TITLE
In-Game: [HTML5] Calling audio_sound_loop_end() on a decoding streamed sound will cause a crash

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7805]
### Description
If a streamed sound is currently decoding, and `audio_sound_loop_end` is called on it, the runtime will crash due to an attempt to access the data buffer which hasn't been decoded yet.

This will produce the following error:
```
Uncaught TypeError: this.pbuffersource is null
```

### Steps To Reproduce
- Open and run the attached project on HTML5.
- Open the console.
- Interact with the page to start the test. The game should immediately crash.
- In the console, scroll all the way to the top and inspect the first error to be thrown. It should be the one from the description.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[96ffc6d9-8f23-4c01-9f73-6f973da6c875](https://api.gamemaker.io/api/github/downloads/96ffc6d9-8f23-4c01-9f73-6f973da6c875)

**Comment by toby-yoyo** [comment]
Avoided refs to the voice's audio buffer when setting the loop-end bound on a decoding voice.

**Comment by scott-dunbar** [comment]
Verified fixed in IDE v2024.1100.0.631  Runtime v2024.1100.0.656
