### ISSUE TITLE
Building Projects: [HTML5] Streamed sound in included files is not exported in attached project

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7806]
### Description
As in the title, the attached project does not export the sound in the included files directory that is used to create a runtime audio stream. This leads to requests for the sound returning `404` at runtime.

### Steps To Reproduce
- Open and run the attached project on HTML5.
- Open the console.
- Interact with the game to start the test.
- Observe that no sound plays as all the requests for the stream return `404`.
- Go to the exported game directory and note the lack of the file there.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[71ff41d8-16dd-4a02-93c4-fa2f144e28e4](https://api.gamemaker.io/api/github/downloads/71ff41d8-16dd-4a02-93c4-fa2f144e28e4)

**Comment by toby-yoyo** [comment]
The issue here was that because the `Automatically remove unused assets when compiling` option now seems to be enabled by default, all included files were being stripped out on HTML5 as there is no way of referencing them in a game other than through a string (see https://github.com/YoYoGames/GameMaker/issues/3749#issuecomment-2032431321).

The compiler for other platforms does not check included files for being unused, so the changes here have aligned the HTML5 compiler with that behaviour. In addition, included files will no longer be reported as 'unused' in the console during compilation to any platform.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.631  Runtime v2024.1100.0.656
