### ISSUE TITLE
In-Game: Async HTTP "status" is -1 (as if an error) when successful requests result in an empty string being returned

### ISSUE THREAD

**Issue by YYBartT** [YoYoGames/GameMaker-Bugs#7811]
### Description

If the result of an HTTP request is an empty string `""`, the `async_load[? "status"]` variable in the [Async HTTP Event](https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Object_Properties/Async_Events/HTTP.htm) will hold the value `-1`, indicating that an error occurred. However, an empty string as the result doesn't necessarily mean that an error occurred. The request is still successful if the HTTP status code (`async_load[? "http_status"]`) is a valid one.

Issue encountered while looking into the Twitch extension with @DiasFranciscoA.

### Expected Change

The status variable equals 0 (i.e. success) if the HTTP status is a valid and the result is an empty string

### Steps To Reproduce

1. Start GameMaker
2. Add code that performs an HTTP request which returns an empty result (`""`)
3. Check the `"status"` and `"http_status"` members of the `async_load` DS map in the Async HTTP event
4. `"http_status"` contains a code that indicates that the request was successful, while `"status"` holds the value `-1`, indicating that an error occurred

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by yoyo-danielc** [comment]
Fixed on 2024.11 branch, test project follows:

[gm-bug-7811.zip](https://github.com/user-attachments/files/17202707/gm-bug-7811.zip)

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1100.0.641  Runtime v2024.1100.0.663
