### ISSUE TITLE
Trying to create a anonymous constructor is broken in Beta Runtime v2024.1100.0.652

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#7827]
### Description
in the new beta my game is no longer working.

### Steps To Reproduce
1) Open project attached
2) See how it crash when trying to make an a anonymous constructor.
3) Is in dark_database script, line 191

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.626 Runtime v2024.1100.0.652

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Android, GX.games, HTML5, iOS, macOS, tvOS, Ubuntu, Windows

[b9b8a473-1cb3-4592-bbc9-4bf02abd56c7](https://api.gamemaker.io/api/github/downloads/b9b8a473-1cb3-4592-bbc9-4bf02abd56c7)

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by scott-dunbar** [comment]
As far as i can tell with the attached project and testing based off the code at that failure point this issue is resolved in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
