### ISSUE TITLE
[Android] Threading problem caused by loading files from the apk as a zip file causes freeze

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7839]
### Description

We are observing a problem for Android export that put the app into a frozen state.

### Steps To Reproduce
1. Run the project for Android VM under the `gamepipe_test_dev` config
3. After login, the game should automatically starts loading into a gameplay session
4. After gameplay is loaded, the game will automatically go back to the main menu
5. The game will then again load into gameplay session
5. This automatic process will continue endlessly until the game freezes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.627 Runtime v2024.1100.0.654

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android

[e16e08a4-9898-4fe9-a11b-df64f09bff7b](https://api.gamemaker.io/api/github/downloads/e16e08a4-9898-4fe9-a11b-df64f09bff7b)

**Comment by shichen85** [comment]
Again, we have requested the expedited fixing for this issue per https://help.gamemaker.io/hc/en-us/requests/217849 as we are gearing up for a delivery deadline. Please let us know if you need any more information. Thanks!

**Comment by shichen85** [comment]
Tested against runtime 2024.1100.0.677 and the issue is much improved. Much appreciated!

**Comment by jackerley** [comment]
Hi @shichen85 that's a full fix now implemented if you could check & confirm in the latest Beta? Runtime 2024.1100.0.696 should have the fix in.

Thanks,
Fritz

**Comment by shichen85** [comment]
Just tested it, has been going on for a good hour without any issues! Thanks a ton for the fix.

Unfortunately, I also found a font rendering issue in https://github.com/YoYoGames/GameMaker-Bugs/issues/8324. Please see that ticket for replication steps.

**Comment by scott-dunbar** [comment]
Closing issue , i also could not repro. 

Tested in beta  IDE v2024.1100.0.680  Runtime v2024.1100.0.702
