### ISSUE TITLE
Ignore region name text in search results when "ignore comments" is checked

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#7842]
### Is your feature request related to a problem?

These should be treated as comments as far as code search is concerned:

![image](https://github.com/user-attachments/assets/ff943500-1f06-45d6-aba8-0974f3df7f3a)

### Describe the solution you'd like

Region text is treated like comment texct

**Comment by YYDan** [comment]
Duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/5883
