### ISSUE TITLE
[iOS] Crash on bootup

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7857]
### Description
The sample project crashes on boot for iOS export.

### Steps To Reproduce
1. Run the project for iOS VM under the config `dev`
2. See crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.627 Runtime v2024.1100.0.656

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
iOS

[d200b395-e776-4e4c-b6be-d8fecf198c09](https://api.gamemaker.io/api/github/downloads/d200b395-e776-4e4c-b6be-d8fecf198c09)

**Comment by shichen85** [comment]
This is for runtime 2024.1100.0.656 even though the IDE listed is 2024.1100.0.627

**Comment by shichen85** [comment]
Hello, I am seeing this getting triaged to Backlog, but I would think that the issue is critical. Please let us know if the assignment is intentional. 

Also, for more details on the crash, the issue seemed to be related to `YYAL_AudioResumeAll`:
<img width="2291" alt="Screenshot 2024-10-02 at 10 08 06 AM" src="https://github.com/user-attachments/assets/6d14eb5a-293c-4132-9260-86de2d1b62cb">

**Comment by jackerley** [comment]
@shichen85 I believe this is already fixed, it's been put to the backlog to confirm the fix in the next beta once it's built

**Comment by shichen85** [comment]
Still getting this in `2024.1100.0.658`

**Comment by toby-yoyo** [comment]
Fixed a call into the audio library which could happen before it had been initialised.
