### ISSUE TITLE
Manual Content: "Glossary" column uses unreadable text colour values on Monthly and Beta sites

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#7858]
### Description

The "Glossary" column text color is unreadable, nearly the same color as the background.
This is true in the "monthly" and "beta" manuals, but the LTS manual is OK.

![image](https://github.com/user-attachments/assets/3c4baca1-44f9-4f5e-9276-b97ea9c90728)

### Manual Link

https://manual.gamemaker.io/monthly/en/

**Comment by gurpreetsinghmatharoo** [comment]
Should be fixed on the monthly manual site soon
