### ISSUE TITLE
In-Game: Anon constructor parent throws "Error on load" with little other debugging info in 2024.8.1

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7862]
### Description

This should just have a better error message, it's not all that useful, as it doesn't list the line, or the line's text.
![image](https://github.com/user-attachments/assets/435b72df-c758-4097-a947-b508f295f057)

### Steps To Reproduce

```gml
a = function() constructor {}
b = function() : a() constructor {}
c = function() : b() constructor {}
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
This is not a bug as `b` it is a variable is not a script and only scripts can be called as base constructors.

the example would need to be 

```
function a() constructor {
}

function b() : a() constructor {
}

function c() : b() constructor {
}
```

**Comment by tinkerer-red** [comment]
The main issue is that is doesn't throw an error.
Specifically in the use case where you have used JSDocs to define a constructor expression, then the highlighting would show as if it were a declarative function. Which can easily lead to people trying to parent it, then when getting an error like the one shown in the initial message they will have no knowledge as to **where** the bug happened, **what** the bug is.

**Comment by rwkay** [comment]
The colouring (within the IDE) is showing you that `b` is an instance variable - it is trying to tell you that there is an issue

**Comment by tinkerer-red** [comment]
in expansive projects and libraries this could still be an issue, as stated above when using JSDocs this still produces what appears to be valid coloring. despite having any issues.
![image](https://github.com/user-attachments/assets/f0eea679-66b5-4bcd-87e3-6da9425ac8d7)

The suggested change really would just to expand on the error message thrown, as it's really brief as to the issue. Does not include script file, line, or any other useful information. if it at least stated which constructor was trying to reference `b` then that would be a big improvement to attempting to fix errors.
![image](https://github.com/user-attachments/assets/a5af2d56-5f96-438b-997f-96d03101e828)

**Comment by rwkay** [comment]
unfortunately the compiler cannot tell until load time to resolve the issue

**Comment by tinkerer-red** [comment]
Does load time not support throwing an error with script/object event, line number, and line string?
