### ISSUE TITLE
In-Game: Non-anonymous functions declared in an event are not accessible globally in 2024.1100 Beta 1

### ISSUE THREAD

**Issue by gurpreetsinghmatharoo** [YoYoGames/GameMaker-Bugs#7865]
### Description

According to YoYoGames/GameMaker-Bugs#7125:

> any function that is declared in an event with the syntax
function FUNCNAME( /* args */ )
{
}
> will now be accessible as a function name everywhere...

In the attached project this does not work:

![image](https://github.com/user-attachments/assets/f82ca7c4-4c26-49fd-a60e-7eaada80cc46)

Project: https://api.gamemaker.io/api/github/downloads/8d6779a0-0e3e-4035-8f9b-a374924fa32e
Function is declared in obj_player Create - `debug`
Function is called in obj_enemy Alarm 0 - as `debug()`

### Expected Change

There is no need to perform step 3 below in order to fix the project.

### Steps To Reproduce

1. Import project
2. Run game and see error appears a couple of seconds after startup
3. Change obj_enemy Alarm 0 call to `obj_player.debug()`
4. Run game and see it now works

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1000.0.619  Runtime v2024.1000.0.644

### Compiler Log File

- [ ] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by YYDan** [comment]
Note that there are a number of important comments about how this feature works on the original issue - https://github.com/YoYoGames/GameMaker-Bugs/issues/7125

**Comment by rwkay** [comment]
**** IMPORTANT ****

Most of this feature has been backed out from 2024.11 as we have discovered - functions that are declared within an event will still be available through the `asset_` functions, but the optimisation that meant they were called directly (like a function) which would speed up execution as this only worked in cases where object inheritance had been used, and the method for the function was being relied upon.

This was incompatible with the optimisation and so reluctantly we have removed this - we will revisit how this works in GMRT and look to improve the performance of these types of function calls at that point.

**** IMPORTANT ****
