### ISSUE TITLE
Manual Content: Indicate that audio_throw_on_error() is not supported on HTML5

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7871]
### Description

The function `audio_throw_on_error()` is not supported on HTML5, this should be included as a note/warning on its page. 

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Asset_Management/Audio/audio_throw_on_error.htm

**Comment by gurpreetsinghmatharoo** [comment]
Fixed in https://github.com/YoYoGames/GameMaker-Manual/pull/177
