### ISSUE TITLE
Matrix transformations on the CPU (for draw_sprite)

### ISSUE THREAD

**Issue by KitsuneFaroe** [YoYoGames/GameMaker-Bugs#7873]
### Is your feature request related to a problem?

This comes from the desire of rotating a default `draw_sprite` on the Z axis, this would also enable easy skewing of sprites. Without the need breaking the vertex batches for every sprite draw as it would occur by using `matrix_set()`.

 Currently the `draw_sprite_*` functions don't enable for such freedom transformations.

The current alternatives (other than using `matrix_set()`) would be reinventing the`draw_sprite` function to transform the vertex myself, or... doing hacky things like encoding relevant data on the default atributes of the vertices like **blend_color**.

### Describe the solution you'd like

A new draw sprite function that uses a matrix as an input for transformations.
A bit unrelated but passing custom atributes to vertex with the default function would work too.

### Describe alternatives you've considered

A draw_sprite_pos that works in 3D. Though still manually placing the vertices relative to the origin could be an annoyence to calculate.

**Comment by stuckie** [comment]
This is not something we're planning on doing.
