### ISSUE TITLE
Ability to apply nine slice to sprites distorted with draw_sprite_pos

### ISSUE THREAD

**Issue by MkfShard** [YoYoGames/GameMaker-Bugs#7874]
### Is your feature request related to a problem?

When using nineslice to simulate walls and floors in an isometric environment, the way I've found to simulate a 'nine slice' style look is a complex set of vertex buffer code that slows down my game.

### Describe the solution you'd like

I'd like draw_sprite_pos to work as expected with nine-sliced sprites, or else have a similar function (draw_sprite_pos_9_slice, maybe) that handles this behavior.

### Describe alternatives you've considered

The vertex method I mentioned above does work, but it causes performance issues on weaker hardware, and becomes more complex to manage the more I want to affect walls (moving platforms, spawning or disappearing or breaking platforms)

**Comment by stuckie** [comment]
The vertex code that you are using is the best way of doing this, as it gives you complete control over what you want to do with it.
