### ISSUE TITLE
IDE: -  Better IDE Update Process - Update check occurs if starting offline and doesnt stop

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#7876]
### Description

Part of https://github.com/YoYoGames/GameMaker-Bugs/issues/3157 is a check for any IDE updates on start up.

This occurs even if the user is offline when the IDE is started. This results in the status bar displaying "update check" and having the
 loading spinner and mouse icon showing. This update check will not stop even after 5 minutes or the "check for updates" button is pressed and no errors will show in the UI.log.

### Expected Change

the update check wont happen if IDE knows its offline

### Steps To Reproduce

1. Start GameMaker and log in with an internal account that can see the new update process
2. close the ide and go offline
3. restart the ide
4. See check starts but doesn't stop after a long wait or trying the "check for updates" button is pressed

[ui.log](https://github.com/user-attachments/files/17242142/ui.log)
![image](https://github.com/user-attachments/assets/b9157e4e-6430-4e06-8b67-5dd949db5189)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.629 

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.639  Runtime v2024.1100.0.663
