### ISSUE TITLE
UI/UX: Unable to open Preferences in latest 2024.1100 beta build

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#7880]
### Description

In the latest Beta build. Preferences cannot be opened via the hotkey or the File menu.

![image](https://github.com/user-attachments/assets/9c936397-5ef3-48fe-bebc-23dd339b94af)

Tested using IDE v2024.1100.0.632  Runtime v2024.1100.0.658

[Sample Package](https://api.gamemaker.io/api/github/downloads/a8f302e0-0de9-4ae1-a7ea-638d5710e691)

### Steps To Reproduce

1. Start GameMaker
2. Go to File > Preferences or press Ctrl+Shift+P
3. Observe Preferences does not open

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Closing as per comment.
