### ISSUE TITLE
UI/UX: Unable to open Game Options in latest 2024.1100 beta build

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#7881]
### Description

In the latest Beta build. none of the Game Options for any target can be opened via the Asset Browser or the main toolbar

![image](https://github.com/user-attachments/assets/a8603a6f-55ae-4594-af0b-71ad47ba7dea)

Tested using IDE v2024.1100.0.632  Runtime v2024.1100.0.658

[Sample Package](https://api.gamemaker.io/api/github/downloads/7f92c47f-ee6e-483d-a089-cd52711c891f)

### Steps To Reproduce

1. Start GameMaker
2. Create/Open a project
3. Attempt to open any of the Game Option windows via the Asset Browser
4. Attempt to open any Game Options > Main via the menubar button
5. Observe they do not open

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SamTHodson** [comment]
Most likely the same issue as #7880

**Comment by stuckie** [comment]
This was fixed as part of https://github.com/YoYoGames/YoYoStudio/pull/10667

**Comment by Emc1923** [comment]
Closing as per comment.
