### ISSUE TITLE
Startup: Menubar buttons are visible too early during start of 2024.1100 Betas since Start Page became a plugin

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7884]
### Description

As of  IDE v2024.1100.0.629  Runtime v2024.1100.0.654 the menu bar buttons are visible every time the IDE is launched. They will disappear once the start page is reached.

![image](https://github.com/user-attachments/assets/60c0a9ae-ae1b-4261-9c82-a54eb212b777)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.629  Runtime v2024.1100.0.654

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685
