### ISSUE TITLE
Code Editor 2: debugger opens on first line

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#7885]
### Description
When using debuger, when it stops anywhere on first time, CE2 is scrolleed up to 1st line.
On further stops on same breakpoint, it's actually scrolling where breakpoint is, as long as editor for script/object remains opened. If it's closed when debugger works, it would open that resource again and again scroll to top.

### Steps To Reproduce
1. Put some breakpoint , CE2 enabled
2. Run game, when it came to breakpoint, it would open object code, but would scroll up to 1st line
3. Press F5 to continue, on next breakpoint stop, it would work ok
4. You can change place where breakpoint is, and it would still work
5. Close that object/script in debugger (but not close debugger!)
6. On next breakpoinst stop, it would be again on 1st line, but then would work as expected

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4895f401-69e7-4f49-8436-59ddfb863a14](https://api.gamemaker.io/api/github/downloads/4895f401-69e7-4f49-8436-59ddfb863a14)

**Comment by zreedy** [comment]
The view will now center the active debug line when it is out of view and the code is stepped in some way, including when the debugger is initially opened as documented in the original ticket. Otherwise the scroll window will remain unchanged.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1300.0.714  Runtime v2024.1300.0.727
