### ISSUE TITLE
In-Game: [GX.games] Once exported as zip, the game cannot be run normally

### ISSUE THREAD

**Issue by yunzlp** [YoYoGames/GameMaker-Bugs#7889]
### Description

![image](https://github.com/user-attachments/assets/6aeeddda-6d40-45bd-b83e-e1bf67c4dad2)

Premade copy of the game .zip package: [柔性面板测试.zip](https://github.com/user-attachments/files/17248400/default.zip)

### Steps To Reproduce

1. Download the game package above
2. Add it to a webhost
3. Try to run the game

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
It needs to be run from a web server - you cannot just double click on the index HTML file in explorer.

**Comment by yunzlp** [comment]
This is a classic mistake, but I won't make it. I use vscode's golive to access port 5000 to ensure that there will be no cross-domain issues.

**Comment by yunzlp** [comment]
![image](https://github.com/user-attachments/assets/ddf2d28f-2426-49b3-929a-9dbb14699743)
Just in case I tried it on another computer

**Comment by YYDan** [comment]
The .zip attached is a GX.games output package, not the project itself. Have changed the repro steps to match the report (not confirmed the issue yet).

**Comment by rwkay** [comment]
Fixed in 2024.11 - uses the runner.html now (renamed to index.html) - this may not be the best in the long run - we should look at investing in this default html file so it looks more presentable.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.639  Runtime v2024.1100.0.662
