### ISSUE TITLE
Code Editor 2: Converting back and forth between GML code and GML visual can display an empty window until reopened or completely delete  the code

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7890]
### Description
If you convert back and forth between GML code and GML visual, you will get a blank code window after the conversion. Sometimes closing and re-opening the window will make the code appear, but other times the code will not come back and is permanently deleted.

https://github.com/user-attachments/assets/747336ec-fb73-4136-8c89-07db4901bb28

https://github.com/user-attachments/assets/16a31cd3-1f5a-49c7-97a0-0ce245f85ae4

The following one only happened once and I can't reproduce it on command, but it added some DnD comments that disappeared after I reopened the window:

https://github.com/user-attachments/assets/a08927d0-b6fb-45e5-ac90-598e94b4f5b9

### Steps To Reproduce
Swap back and forth between visual and code while having at least one block or line of code in the event

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[30b8d67f-d392-4537-9963-8ac1256705c7](https://api.gamemaker.io/api/github/downloads/30b8d67f-d392-4537-9963-8ac1256705c7)

**Comment by zreedy** [comment]
This bug has multiple ways to be invoked and some of these behaviors are only observable through the starting point:
- Convert unsaved GML -> GMLv
- Convert unsaved GMLv -> GML
- Convert saved GML -> GMLv
- Convert saved GMLv -> GML

Also it matters if you close and reopen the Asset in-between saves.
Conversion from GMLv -> GML is now fixed, including the last issue with the DnD metadata comments persisting.

Pending a fix on the GML -> GMLv conversion not functioning after 1 cycle now.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.653  Runtime v2024.1100.0.679

**Comment by zreedy** [comment]
I'm able to reproduce the bug shown in the video.
I was testing against the context menu, right click on the Event header -> Convert to GML Visual, which does work.
Will address this alternative repro.
