### ISSUE TITLE
Live Wallpapers: High CPU/power usage when a wallpaper is hidden behind other apps

### ISSUE THREAD

**Issue by Level5Fish** [YoYoGames/GameMaker-Bugs#7897]
### Description

I am having a bug with gx wallpaper app where only when my laptop screen is on 60hz and a tab is full screened in front of the wallpaper the cpu usage skyrockets to like 5 or 6 percent when normally it is around .3 or lower. With any other conditions other than the ones I just described, when another tab is fullscreen the usage is zero; I think it's some sort of error thats happening when it is trying to pause the background. I have also tested other wallpapers other than mine and the issue still happens. I spent alot of time making a cool live wallpaper for myself and now I can't use it on my computer because it causes significant battery drain when it shouldn't so if you guys could fix this rq it would be really cool!

### Expected Change

When I fullscreen another app while in 60 hz screen mode the power usage should drop to zero and the background should pause correctly.

### Steps To Reproduce

1. Start the gx live wallpaper app
2. Set the screen refresh rate to 60 hz (might only happen on screens that normally have a higher refresh rate idk)
3. Fullscreen another app or drag a window of another app to the top so that it covers the whole screen
4. Check task manager and see the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1300.0.770  Runtime v2024.1300.0.777, closing.
