### ISSUE TITLE
Code Editor 2: When the nagivation panel is on the side, you can open a code window for a group

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7901]
### Description
When navigating the asset list using the navigation panel in side view, clicking on a group to open it will actually change the code window to be focused on that group, even though groups cannot have code. When using the top or bottom navigation panel, this does not occur.

https://github.com/user-attachments/assets/2ad30cff-a714-41fc-8fed-60ad28431704

### Steps To Reproduce
Set the navigation panel to side view, and then click on a group in the asset list.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a622cbdd-8064-4370-8a93-c86877d55f47](https://api.gamemaker.io/api/github/downloads/a622cbdd-8064-4370-8a93-c86877d55f47)

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.654  Runtime v2024.1100.0.680.
