### ISSUE TITLE
move_and_collide / slope problem

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#7905]
### Description
Hi,

I can't get move_and_collide to work correctly. 
Concretely I'm trying to make a game of platforms with slopes
I use move_and_collide for my character's movements
But I'm having lots of problems. 
- When the player  turns and he is at the bottom of a slope, he often gets stuck
- During a long jump, it may get stuck
- If the slope is too steep, it cannot climb

I have tested many tutorials on the internet and it regularly happens that my character gets stuck, especially when he turns around

I can't seem to find a simple tutorial with moving a character on slopes and using move_and_collide. I regularly manage to get the character stuck in the scenery

### Steps To Reproduce
Test the attached project. Use the arrows to move the player

[0889f4c0-9ecc-4dbf-92d0-edf52ce2ebb6](https://api.gamemaker.io/api/github/downloads/0889f4c0-9ecc-4dbf-92d0-edf52ce2ebb6)

**Comment by stuckie** [comment]
We will check to see if this is a bug, but for coding support issues in general, please visit the [GameMaker Community](https://forum.gamemaker.io/index.php) forum and create a thread there, asking for advice.

**Comment by scott-dunbar** [comment]
Similar to the issue causing the reopen of  https://github.com/YoYoGames/GameMaker-Bugs/issues/8146, there definitely appears to be issues when moving in particular directions causing sticking.

As there is an open issue for this i will hold on verifying this til the above is confirmed fixed

**Comment by scott-dunbar** [comment]
Further fixes for this issue have been moved to the 2025.1 milestone. Reassigning this issue for retest when that build is available
