### ISSUE TITLE
Code Editor 2: Feather messages will not disappear when the object they come from is deleted, allowing you to open the code tab of a non-existant object

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7907]
### Description
If you trigger some feather messages in an object or script and then delete it, the messages will still appear in the diagnostics tab. You can then double click those messages to open a code window for the deleted object.

https://github.com/user-attachments/assets/1d1f40c7-05b8-48ba-986a-572cf78a6ec0

### Steps To Reproduce
1. Create an object
2. Type some gibberish to trigger feather messages
3. Delete the object
4. Double click one of the messages in the diagnostics tab
5. You now have a code window for an object that doesn't exist

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[94793403-b5fc-40c4-b7f0-9677730cceaa](https://api.gamemaker.io/api/github/downloads/94793403-b5fc-40c4-b7f0-9677730cceaa)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
