### ISSUE TITLE
"constructors should only be called using new" error ignores try/catch

### ISSUE THREAD

**Issue by nommiin** [YoYoGames/GameMaker-Bugs#7915]
### Description

Using the latest version of the GameMaker Beta, using a constructor without the `new` keyword will throw an exception that **is not** caught by `try/catch`

![image](https://github.com/user-attachments/assets/adfaecdc-ca36-430b-9b06-21b865fc35ec)

Example Package: https://api.gamemaker.io/api/github/downloads/61ff5d15-1ecc-49c5-9361-37671801abd8

### Expected Change

This error should be caught

### Steps To Reproduce

1. Start GameMaker
2. Open example project
3. Run the game, replication code is within global scope
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.639  Runtime v2024.1100.0.662
