### ISSUE TITLE
Truthiness of empty string changed in 2024.1100 beta runtime

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7922]
### Description
Starting in the 2024.1100 beta runtime, the truthiness of empty string `""` have changed:

1. Calling `if ""` used to throw an exception, now it does not
2. `''' == 0` used to evaluate to false, now it evaluates to true
3. `"" == false` used to evaluate to false, now it evaluates to true

 ```gml
try{
	if ""{
		show_debug_message("this used to crash");
	}
}
catch(err){
	show_debug_message(err);
}

if "" == 0 {
	show_debug_message("this used to be false");
}

if "" == false {
	show_debug_message("this used to be false");
}
```

If this behavior is intended, please specify in the change log.
If not, please restore to the old behavior.

### Steps To Reproduce
1. Run the sample in VM in 2024.800 runtime, see the exception being thrown and that comparisons evaluate to false
2. Run in 2024.1100 runtime, see no exception and evaluation to be true

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.1100.0.659

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[a9b778ce-ff52-4c71-96b4-e4d97aff8022](https://api.gamemaker.io/api/github/downloads/a9b778ce-ff52-4c71-96b4-e4d97aff8022)

**Comment by rwkay** [comment]
Fixed in 2024.11 - apologies changes were unintentional but the fix for converting a string to a number had an unintended consequence for empty strings.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.639  Runtime v2024.1100.0.663.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.643  Runtime v2024.1100.0.664
