### ISSUE TITLE
`method_call()` with an incorrect first argument throws no error, and silently skips

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7924]
### Description

Accidently just wrote `method_call(_args)` which ran the program just fine, no errors at all, the `method_call` was even being ran through, yet nothing happened, no errors at all. This seems like unexpected results.
Additionally, `method_call(_method)` with out arguments provided seems like it would run, and just take no arguments, however this is also no the case, it simply doesnt run and throws no errors.

### Expected Change

Throw errors

### Steps To Reproduce

```gml
var m = method({}, function(a0){show_debug_message("It's running!"); show_debug_message(a0)})
var args = [42]
show_debug_message("About to run First::")
method_call(m)
show_debug_message("About to run Second::")
method_call(args)
show_debug_message("About to run Third::")
method_call(m, args)

////// output:
//About to run First::
//About to run Second::
//About to run Third::
//It's running!
//42
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by tinkerer-red** [comment]
As a note, `method_call` does support no argument array. so that part of the bug report can be ignored.

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by YYBartT** [comment]
As confirmed by @rwkay, the second parameter `array_args` is now optional. Updated the `method_call()` manual page with this info. However, this hasn't been updated in fnames and gmlspec yet.

**Comment by rwkay** [comment]
Updated the docs in `fnames` and `GmlSpec.xml` and updated the HTML5

**Comment by cameron-home** [comment]
Attached code in project failing with error, as expected in  IDE v2024.1100.0.639  Runtime v2024.1100.0.662
