### ISSUE TITLE
Code Editor 2: Autocomplete scroll bar cannot be clicked or dragged

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7926]
### Description
The autocomplete window has a scroll bar that looks like you can click and drag it, and it highlights when you hover it. However, trying to click it instantly closes the autocomplete window. Using the scroll wheel or the arrow keys does work to scroll down.

This same bar CAN be clicked and dragged in CE1.

https://github.com/user-attachments/assets/d54261cb-4e33-4aa8-acdd-1b0894627e52

### Steps To Reproduce
Type something, then try to click the autocomplete scroll bar.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[22a33e6d-cee2-49bc-bc50-139d14f1ad72](https://api.gamemaker.io/api/github/downloads/22a33e6d-cee2-49bc-bc50-139d14f1ad72)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
