### ISSUE TITLE
Manual Declaration of Texture Page Sizes

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#7930]
### Is your feature request related to a problem?

Hi YYG. Sorry to bother you again, but I've just encountered the _oddest_ little behavior, and it briefly wrecked my game, lol.

It's pretty simple, really. The Texture Group size designated in the Tools-->Texture Groups UI is, apparently not a command, but a polite suggestion. 

The actual size of any given Texture Group, when built, may be any power-of-two up to the number set, but it behaves dynamically to conserve texture space used.

So, for example, if you set the size of the Default Texture Group to 4096, but only have a single 35X35 Sprite in your game, GMS is setting the size of the Default Texture Group to 64. If that Sprite is 100X 35, then the size is 128X64.

You can confirm that this behavior is happening by bringing up the Debug Console and looking at the Texture Groups there during runtime.

Having this size change dynamically like this is clever and useful. Why waste memory?

However, having it change from square to _any other rectangle type_ can cause problems, because that can wreck shaders expecting square texture coordinates to function properly.

I accidentally ruined half of the shaders in my game by taking a bunch of Sprites out of the Default Texture Group and putting them elsewhere. I was finally starting to run out of room and thought it might be time for some cleanup. Moved them to a new Texture Group and... er... most of my FX shaders broke, lol.

After a bit of puzzling, I figured out what had caused this, chuckled a bit, and did the _kludgiest thing_ I think I've ever done in GMS; I made two "sprites" that are 1 pixel by 2049 pixels. I then stuck them into each Texture Group where I absolutely must know with certainty that the textures will be squares of exactly 4096 pixels. It _works_, but it's a classic kludge.

### Describe the solution you'd like

I would like a way to force GMS to use specific power-of-two dimensions for a given Texture Group, or force it to _always_ be square, even when this would "waste VRAM or memory".

### Describe alternatives you've considered

There is probably a way to get the height / width ratio of a Texture Group and feed it into shaders via a uniform, but I don't think it's a great alternative, since that costs a bit of math and a context switch.

### Additional context

As a simpler alternative to re-writing your code to accommodate what is admittedly not a common problem, you could simply document the process described above for forcing a Texture Group to be a square of a given power-of-two size by importing a "sprite" that's one pixel larger than the next-smallest power-of-two in one dimension. In my case, that cost me only 20,530 pixels, with padding, which isn't a really big deal.

**Comment by DragoniteSpam** [comment]
if your shaders break depending on the dimensions of your texture page, you should probably fix your shaders - one of the main points of UVs being normalized 0 to 1 is that you don't have to worry about the size of the texture you're sampling from as long as the UVs are correct

allowing people to blow up the size of their texture pages in exchange for not handling their shaders correctly isn't *really* a winning trade-off

> There is probably a way to get the height / width ratio of a Texture Group and feed it into shaders via a uniform, but I don't think it's a great alternative, since that costs a bit of math and a context switch.

[texture_get_uvs()](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FTextures%2Ftexture_get_uvs.htm) and [texture_get_texel_width() and height](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FTextures%2Ftexture_get_texel_width.htm)

**Comment by mistletoe** [comment]
Sure, you can use texture_get_texel_width() / texture_get_texel_height to arrive at non-square ratios and then do some additional math in the shader. But that's one more thing that has to be assigned via a uniform each time the shader operates, and, if not done with some care, it's precious CPU wasted during rendering. 

For some shaders, I prefer to have a constant for the known pixel scale of something I'm using (say, some Perlin noise I'm sampling, or whatever) and the only thing I'm carrying over to the shader during runtime is a uniform for the UV origins. 

Here's a little bit from a fragment shader that does scaling and scrolling of a texture in the vertex shader.

```
uniform vec2 posOfTexture;//UV Coordinates of top-left pixel, it's #macro'd at the beginning of time so there's no computation other than assigning it
const vec2 sizes = vec2(128.0/4096.0,128.0/4096.0);//literal sprite size / atlas size.

void main()
{
/*note that v_TexCoord4, disCoord4 are both coming from the vertex shader- in this case, I'm using distCoord4 as a scroller, and v_TexCoord4 is a scalar.*/
vec2 movedScaledCoord = posOfTexture + (fract(v_TexCoord4+distCoord4)*sizes);
vec4 finalRead = texture2D(gm_BaseTexture, movedScaledCoord );
gl_FragColor = finalRead ;
}

```
**fract()** is the magic sauce here. Because I already know the value of sizes and the position of posSize, I can, in this case, scale and scroll the texture freely; **fract(location)*sizes** ensures a value that's normalized between posOfTexture and its edge. 

This is by far the best way to do, say, a shader that requires several reads via texture2D, because _all_ of those textures can be efficiently stored within one Texture Page's atlas. For a lot of things we do in GMS, one 4096X4096 atlas could store all of the textures used by every special effect shader in a game pretty easily. 

I don't understand why people still use a separate Texture Page for, say, a bit of Perlin Noise, when it's 100% not necessary- setting a uniform is super-cheap, using a texture is not. But perhaps they're not aware of the technique outlined above; feel free to give that to others :-)

I think all of the fancy textures I'm using take up maybe 1024X1024, and I'm doing stuff like distortion, dynamic flames, wind / weather systems, etc.

But it only works if the size of the Texture Page is a known constant, and won't suddenly get borked by administrative changes you're doing for other reasons, lol. Anyhow... my kludge works, lol. I just begrudge the 20K pixels wasted to force GMS to keep the Texture Page exactly the right size and ratio, lol.

**Comment by DragoniteSpam** [comment]
> I don't understand why people still use a separate Texture Page for, say, a bit of Perlin Noise, when it's 100% not necessary- setting a uniform is super-cheap, allocating a texture is not

[Trust me, it's not](https://www.youtube.com/watch?v=VnuWurbOrBo). On desktop the days when a single noise texture is likely to make the user overflow their vram buffer has gone the way of video cards with sub-1 GB of VRAM.

> allowing people to blow up the size of their texture pages in exchange for not handling their shaders correctly isn't really a winning trade-off

In any case, how much VRAM you have is irrelevant. Forcing GM to allocate a 4k texture so that you can atlas a (for example) 256² noise texture when the rest of the atlas only takes up 1024² **will cause you to use almost 4x more vram than you would have if you'd just left it alone,** with a majority of that texture being empty space. By trying to be clever you're causing the system to *waste* memory. There's a reason the GM texture packer attempts to minimize the area needed for each atlas.

> But it only works if the size of the Texture Page is a known constant

Shaders breaking if you use a different texture size is a sure sign that you need to re-evaluate what you're doing.

**Comment by mistletoe** [comment]
@DragoniteSpam No texture space will be wasted, rest assured :-) The space being freed up will be filled with more game art. 

I'm 100% aware that GMS statically allocates textures into VRAM at runtime, etc., other than Dynamic Textures and Surfaces, so using 1000 tiny textures _should be fine_, other than tiny amounts of time used for the assign operations and the time spent on the GPU side finding them in memory, etc., which is all very quick. I'm doing my little trick for some other reasons.

Your video was great educational content, but I think you might have missed that you _never_ really saturated the GPU. What you're seeing there is just how quickly the CPU's able to process and provide the tiny amounts of data across the bus. GMS is 99.99% CPU-bound; it's why I and others have asked for some way to implement multithreading (or, heck, just have Draw and Physics run on their own threads, like most modern engines do).

Anyhow, I'd like to recommend that you revisit your experiment, scaling the number of vertexes up; at least a couple of orders of magnitude (100K tris). 

It will become completely obvious that vbatches=100000 and vbatches=1, for frozen Vertex Buffers, is not the same animal. Trying it with un-frozen ones is also educational.

To start seeing saturation of the AGP _bus_, you'd have to get into truly gargantuan numbers of triangles. This is why a AAA game is casually throwing around so much geometry. It's really not that big of a deal... so long as it's batched well. Where AAAs typically struggle is other areas, like implementing texture streaming to keep from running out of VRAM.

Then try an experiment where it's just one triangle, but write an _absolutely insane_ shader whose iterations can be controlled via a uniform. Hit it with iterations until fps_real sinks to less than game_speed, and voila, you've _finally_ managed to saturate the GPU. I can assure you that the amount of math it'll take is a little mind-blowing.

Then try it with a batch of 100000 triangles in a frozen vertex buffer. While this sounds like a linear load test, because of how shaders are parallelized, it's not as linear as it first appears.

Also, what I think you might find educational is looking at situations where, over time, frozen vs. unfrozen buffers make the most sense. I have a custom particle system, and it was an interesting finding, because it's not as simple as yes / no, because of the time-cost to freeze them.

**Comment by mistletoe** [comment]
> don't hard-code texture coordinates into your shader

My apologies, something must have gotten lost in translation. The top-left corner of the Sprite's UVs are sent as a uniform vec2; _that_ was computed in a macro at runtime. It's not like I was hand-coding those coordinates; that _would_ be silly. What got borked was the relative texel dimensions, because the texture being referenced was no longer square, and no longer 4096^2.

Is doing that _dumb?_ Well... my kludge _works_, so I probably know _what_ I'm doing and wanted to _keep it that way_ enough to make the kludge in the first place, lol.

Here's a thought, though. What if, when users change enough in a Texture Page that it's about to change dimensions, that GMS _informed the user through the log?_ That'd be a cheap change to implement; I presume that GMS has a big, snazzy system doing all of that wonderful texture-atlas magic, and I also presume that talking to the Log is readily available. So that'd be a 5-minute fix, maybe? 

Heck, just pushing the real dimensions of each Texture Page into the build log would be fine, too; I caught this happening via Debug Console, but if anybody _else_ has this issue, and doesn't know why, it'll be fairly obscure.

Anyhow, this is clearly getting into really, _really_ silly territory, even by the low standards of Nerds Online, so I'll close it out.
