### ISSUE TITLE
ASTC compressed textures not supported on Android devices that support certain extensions

### ISSUE THREAD

**Issue by JonnoRobson** [YoYoGames/GameMaker-Bugs#7931]
### Description

There is a subset of Android devices that do not correctly create/render textures using the ASTC compressed texture format and instead just display a black square. These devices should be able to load and display ASTC compressed textures as they support the `GL_KHR_texture_compression_ldr` extension which provides the necessary hardware support that GameMaker needs. Currently however, GameMaker expects the device to support the `GL_OES_texture_compression_astc` extension before it will allow the device to create ASTC textures. 

This extension provides extra features that are not currently needed by GameMaker so we should instead be checking for the extension that provides the minimum viable support to ensure maximum compatibility for ASTC textures.

### Expected Change

Android devices that support ASTC textures but do not support GL extension GL_OES_texture_compression_astc should not fail to load ASTC compressed textures.

### Steps To Reproduce

1. Open the GPU texture compression sample (https://github.com/YoYoGames/GM-GPUTextureCompression)
2. Select the ASTC project configuration
3. Run using an Android device that supports the GL extension `GL_KHR_texture_compression_ldr` but not `GL_OES_texture_compression_astc` (can usually be checked here https://opengles.gpuinfo.org/ by finding the device and searching for "astc" in the "GL Extensions" section)
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JonnoRobson** [comment]
Support for `GL_KHR_texture_compression_astc_ldr` but not `GL_OES_texture_compression_astc` seems to be particularly prevalent on Android devices with a PowerVR GPU.

**Comment by JonnoRobson** [comment]
As outlined in the issue description, the problem was that we were checking if a device supported `GL_OES_texture_compression_astc` before allowing it to create ASTC format textures. `GL_KHR_texture_compression_astc_ldr` should provide sufficient support for ASTC textures and certain devices only support that extension so I've updated the check to allow creating ASTC format textures as long as that extension is supported. As it is a change to the GameMaker runtime it will be available in the upcoming 2024.11 release.

**Comment by scott-dunbar** [comment]
No available devices for testing this completely. Confirmed that fix was brought to Nov. 

Closing issue for now. 

Any user encountering an issue with rendering should check if their device falls into the mentioned brackets of devices and provide us information on their device and the example project
