### ISSUE TITLE
Code Editor 2: Renaming an object breaks highlighting and autocomplete for it until the project is reloaded

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#7932]
### Description
If you rename an object at any point, it's code tab will have broken syntax highlighting and no autocomplete until the project is reloaded. Closing the tab and reopening it does not fix it.

https://github.com/user-attachments/assets/beaee956-a6b8-45f1-b432-44c7c2e07a45

### Steps To Reproduce
Rename an object with CE2 active

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[d6a3cafc-bce3-4002-a14e-088f01ea339b](https://api.gamemaker.io/api/github/downloads/d6a3cafc-bce3-4002-a14e-088f01ea339b)

**Comment by zreedy** [comment]
This is fixed by https://github.com/YoYoGames/YoYoStudio/issues/10767
