### ISSUE TITLE
Manual Content: Document that static_get() will return the static struct of a method's function rather than its struct

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#7934]
### Description
Russell has informed me the prior report was inaccurate. `static_set(_method)` does set the method's statics, but `static_get(_method)` will return the inner function's statics instead. Presumably this is because of function declared in objects become methods, and this is much more reasonable to use then `static_get(method_get_index(_method))`.

![image](https://github.com/user-attachments/assets/10a81174-d306-47fc-bac5-a454815ce96e)

As an update to this, here is proof of his statement:
![image](https://github.com/user-attachments/assets/69635869-b839-43ca-9520-e96524d0d27b)

### Expected Change

Docs just need updating for `static_get`

### Steps To Reproduce

Example of this working as intended.
```gml
var s = {}
var f = function(){static foo = "bar"}
f()
var m = method(s, f)
static_set(m, {toString: function(){return "This is the method's string"}})
show_debug_message(s)
show_debug_message(f)
show_debug_message(m)
show_debug_message(static_get(s))
show_debug_message(static_get(f))
show_debug_message(static_get(m))
```

original test code before edits:
```gml
var s = {}
var f = function(){}
var m = method(s, f)
static_set(m, {foo: "bar"})
log(s)
log(f)
log(m)
log(static_get(s))
log(static_get(f))
log(static_get(m))
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
This is not a bug as you will always get the static for the function that the method is referencing... this cannot be changed (so static_set is not changing it) - it is silently ignoring it.

Currently static_set does not return anything to specify success or failure - we should probably add this to the documentation though that `static_get` will always retrieve the function static that the method is referring too.

**Comment by tinkerer-red** [comment]
updated report, could this be tagged for a Docs issue?
