### ISSUE TITLE
In-Game: Assigning an audio effect to a bus will incorrectly throw

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7948]
### Description
If you attempt to set an audio effect to an effect slot on an audio bus, you will see an error thrown:
```
Attempted to clear an empty bus slot
```

This is likely an issue with how the runtime is interacting with the audio library.

### Steps To Reproduce
- Open and run the attached project.
- The game will immediately throw.
- Expected result is that audio should be heard with a reverb effect applied.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.806 Runtime v9.9.1.965

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[23c37910-8df0-44fc-b0e7-59dc85d467ee](https://api.gamemaker.io/api/github/downloads/23c37910-8df0-44fc-b0e7-59dc85d467ee)

**Comment by toby-yoyo** [comment]
Fixed an issue with how the runtime swapped out effects on a slot.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664

**Comment by scott-dunbar** [comment]
It has not been released. the latest versions are always available https://releases.gamemaker.io/

Keep an eye on there and our social pages to know when the next update is released
