### ISSUE TITLE
Code Editor 2: deleted included files are listed in the root of the asset navigation panel

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#7950]
### Description

After deleting files from the datafiles folder, reloading the project will display them in the Assets Navigation Panel of Code Editor 2, where they can be opened and edited as though they were script files

https://github.com/user-attachments/assets/6421824c-320e-460b-a51a-85981999dce5

![image](https://github.com/user-attachments/assets/787335ac-f617-494d-88b9-5aa3385fdd18)

![image](https://github.com/user-attachments/assets/9c5cc0f9-2cf6-4fe9-ba51-599f468ff90e)

https://api.gamemaker.io/api/github/downloads/77148bab-2a8c-484f-8bd8-80ebefd74643

### Expected Change

That should not happen

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Create a script asset
4. Open the datafiles folder
5. Add files to a subfolder 
6. Delete that subfolder with the files inside 
7. Reload the project
8. open the script
9. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by zreedy** [comment]
Fixed. Included Files which are not valid will no longer display.
Additionally fixed an issue where valid Included Files were being filtered incorrectly (e.g. json files) + a missing string key for the Documents label in Left/Right Navigation docking.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
