### ISSUE TITLE
[iOS] Support .m files

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#7952]
### Which Extension are you reporting this issue for?

Facebook

### Description

Facebook iOS SDK was build on Swift and contains ObjC symbols to be compatible, and that's ok due we can use Swift files now, the problem starts when the classes contains Delegates or if you want use ObjC references from Swift frameworks.

It's necessary be able to use .m files, but why we cant use it right now? when you create a .m files lof of errors Ref.h appear related to YYObjectBase.

basically .mm it's good for ObjC and C++ comaptibility but bad for Swift compatibility, we need .m files

[Facebook.zip](https://github.com/user-attachments/files/17299073/Facebook.zip)

### Expected Change

Allow .m compatibility

### Steps To Reproduce

1. Start GameMaker
2. Open the attached project
3. Build the Xcode project
4. if you try run it will see the issue with the delegate
5. if you change the file to **_FacebookEtension2..mm_** to **_FacebookEtension2.m_** you will see the issue in the ref.h file

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jzavala-YYG** [comment]
Fixed Updating Xcode

**Comment by Emc1923** [comment]
Verified working on Xcode 16.1 as of  IDE v2024.1100.0.681  Runtime v2024.1100.0.703 with an updated sample
