### ISSUE TITLE
In-Game: Runner attempts to clear audio emitters from the main bus

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7955]
### Description
In the attached project (Little Town). an error is returned by yyal as the runtime attempts to clear emitters from the main audio bus at the end of a sequence. This is considered a bad op in yyal.

Similar code exists in GMRT so a fix for both runtimes will be needed.

### Steps To Reproduce
**GMS2**
- Run the attached project on GMS2.
- Complete the game, giving each item to the person that needs it.
- After the game is completed, an error will be thrown:
```
Cannot clear emitters on the main audio bus
```

**GMRT**
- Open and run the attached project on GMRT.
- Pick up the rolling pin and give it to the baker.
- After the sequence plays an error will be thrown: 
```
Unhandled exception Error : Cannot clear emitters on the main audio bus
```

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.806 Runtime v9.9.1.965

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4e01b1e3-6d88-489d-9f33-e74e57ea465b](https://api.gamemaker.io/api/github/downloads/4e01b1e3-6d88-489d-9f33-e74e57ea465b)

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.643  Runtime v2024.1100.0.664
