### ISSUE TITLE
UI/UX: Add a minimum size to the 'report a bug' window to prevent it from appearing collapsed

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7956]
### Description

When experiencing issues with start up plugins in the most recent beta, the 'report a bug' window appeared collapsed hiding all its text, having to be reopened manually. This could be prevented by adding a minimum size to the window.

![image](https://github.com/user-attachments/assets/0dbb253a-fe10-49e1-bbdd-3558f851d515)

### Steps To Reproduce

1. Start GameMaker
2. Go to _help>report a GM bug_
3. Observe you can collapse the window until all the text is hidden

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly), 2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1100.0.685  Runtime v2024.1100.0.707. 

Thank you
