### ISSUE TITLE
Please Consider Adding BC7/ATSC Compression

### ISSUE THREAD

**Issue by mistletoe** [YoYoGames/GameMaker-Bugs#7958]
### Is your feature request related to a problem?

I've run into some unexpected behaviors with the default Texture Page compression algorithm (BZ2-QOI). It's not compressing one-bit alphas quite as expected (they _look_ one-bit, but aren't, when tested in Sprite Editor, using the Magic Wand). 

After observing some odd behaviors in a shader, I have finally tracked this down, lol. 

For now, I've returned to good ol' PNG for the use case in question, because I absolutely require one-bit alphas made in Photoshop to remain one-bit in GMS. 

While BZ2-QOI offers slightly-smaller filesize and presumably unzips more quickly than PNG, this compression schema does not actually help with VRAM use, which is, imo at least, the main argument for using anything but lossless PNG, other than tiny changes in how quickly the game loads these things into RAM the first time.

As I'm sure you're aware, DDS does help with VRAM considerably, whereas BZ2 does not, so far as I'm aware.

BC7 is the most modern DDS format supported by all modern GPUS (basically, everything that supports DirectX 11+, which is 99.6% of PCs or so nowadays), and imo, might look good-enough for many GMS users to consider using:

https://www.ultraengine.com/community/blogs/entry/2412-new-texture-compression-formats/

I'd like to also advocate for ATSC 3.0, but I could not 100% confirm that AMD / Intel GPUs support them properly in their drivers. 

nVidia has been supporting ATSC 3.0 for years now, it's an open format, and ATSC (in theory) offers a really great tradeoff between bits-per-block and relative compression quality. I think the industry's mainly using DDS out of sheer inertia, because ATSC looks like a compelling format for a lot of use-cases.

After doing some homework, it appears that GMS would not incur any patent-license fees for using BC7 or ATSC, so this is "merely" the time-cost to support it.

### Describe the solution you'd like

I'd like to see GMS support at least one modern compression algorithm to reduce VRAM use with minimal artefacts.

### Describe alternatives you've considered

There aren't any practical options, other than official support.

**Comment by L-Clouds** [comment]
BC7 and ASTC **are** supported.  Here is where it is in the manual: https://manual.gamemaker.io/monthly/en/#t=Settings%2FTexture_Information%2FTexture_Compression.htm&rhsearch=BC7&rhhlterm=BC7
Here is the official extension: https://github.com/YoYoGames/GM-GPUTextureCompression

> While BZ2-QOI offers slightly-smaller filesize and presumably unzips more quickly than PNG

QOI by itself does, while BZ2 is much slower (to the point that people publishing to weaker Android phones often ask, "why does my game take several seconds to launch?").

> It's not compressing one-bit alphas quite as expected (they look one-bit, but aren't

That's odd, considering QOI is supposed to be lossless.  Maybe this deserves its own separate bug report?

**Comment by mistletoe** [comment]
@L-Clouds Wow, that's fantastic, other than having to install the extension. I will totally play with BC7, and if it's all right for my use case (which it probably is, very little of my translucency will be borked by a little banding in the real world), try out ATSC.

As for BZ2-QOI, I wasn't going to document that as a "bug", per se, more like, "compression algo behavior that users might not expect". I only saw it happen because of some Fancy Shader Magic stuff I'm doing; I presume 99.9% of users will not notice that apparently transparent pixels (and transparent in Photoshop before import) become slightly-translucent in GMS.

**Comment by mistletoe** [comment]
Closed, this can be done through third-party Extension per answer.
