### ISSUE TITLE
Using audio_exists on a non-existing audio asset sends "vector" to output

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7963]
### Description
Seems that if you use `audio_exists(num)` and the audio asset doesn't exist, it'll spit out either `invalid vector subscript` on Windows or `vector` on MacOSX in the output window. The function doesn't break, as it still returns `false`.

### Steps To Reproduce
1. Run Project
2. See results for `invalid vector subscript` or `vector` between `==========`

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.634 Runtime v2024.1100.0.658

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
macOS, Windows

[4443133a-8e76-4fbc-9ab9-0708cbc1d435](https://api.gamemaker.io/api/github/downloads/4443133a-8e76-4fbc-9ab9-0708cbc1d435)

**Comment by toby-yoyo** [comment]
Removed some old logging when failing to find audio assets using an internal function. The audio library functions that call into that should generate errors of their own if necessary.

**Comment by mgeddesGM** [comment]
verified for both win and mac  IDE v2024.1100.0.646  Runtime v2024.1100.0.666
