### ISSUE TITLE
No ui

### ISSUE THREAD

**Issue by internettyspaghetti** [YoYoGames/GameMaker-Bugs#7990]
### Description

![image](https://github.com/user-attachments/assets/0af7e2f3-593a-475f-930f-2fcdd7fa8a8e)
When I try  to open Gamemaker IDE v2023.1.1.62  Runtime v2023.1.1.81  (before you tell me to switch versions I'm not in a good position to do that rn) the UI is just, gone
when I try opening a project file via my downloads it just opens up for a second and then immediately closes

sorry if this is vague or unprofessional, I'm just really mad and also haven't reported anything like this before
for extra info, I do have multiple game maker versions installed at once if that changes anything, I have this version, the Steam version, and an LTS version

### Expected Change

the ui loading and being able to run project files

### Steps To Reproduce

1. Start GameMaker
2 See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
Your log files show you are using an older version of GameMaker. This issue should already be fixed in the current GameMaker version, so please update and retest your problem, then let us know here if it is fixed or not.

If you still have this problem, please use the in-IDE reporter so that we get the log files as well.
