### ISSUE TITLE
In-Game: variable_clone() gives incorrect results for methods that have variables bound

### ISSUE THREAD

**Issue by Hmmmpf** [YoYoGames/GameMaker-Bugs#7994]
### Description

1. directly using `variable_clone` on a method will result in a clone that retains all bound variables correctly, but attempting to call it will result in a hard crash.

2. using `variable_clone` on a struct which contains a method that has a variable scoped to it loses the variables scoped to the clone's method

3. using `variable_clone` on an array which contains a method that has variables scoped to it results in a perfect copy, but the original method stored in the array will lose the variables scoped to it.

https://api.gamemaker.io/api/github/downloads/f895dfcc-bf0c-47ea-a140-79b192a2b229

### Expected Change

I would expect to not lose variables scoped to methods when cloning containers. I dont know what I expect on point 1. but it wasnt this.

### Steps To Reproduce

1. Start GameMaker
2. Scope a variable to a method
3. Store the method in a container
4. Clone the container
5. Try accessing the original and the clone's variables.
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Here is a test project that can be used to test the fixes:

[how_variable_clone_should_work.zip](https://github.com/user-attachments/files/17394683/how_variable_clone_should_work.zip)

**Comment by mgeddesGM** [comment]
@gurpreetsinghmatharoo after speaking to @DiasFranciscoA, could you message him about making the documentation more explicit?

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.671  Runtime v2024.1100.0.696

**Comment by jackerley** [comment]
GMRT output differs you get 
```
-----Test Case 1------
[ "length","name","prototype","constructor","example" ]
[ "length","name","prototype","constructor","example","here" ]
[ "length","name","prototype","constructor","example" ]
I am a working method: 12
I am a working method: 22
```

when GMS2 runtime gives you 
```
-----Test Case 1------
[ "example" ]
[ "example","here" ]
[ "example" ]
I am a working method: 12
I am a working method: 22
-----Test Case 2------
```
