### ISSUE TITLE
In-Game: [macOS] Game crashes immediately after building, due to not able to get the renderer info string on Sequoia

### ISSUE THREAD

**Issue by Brushguy** [YoYoGames/GameMaker-Bugs#7999]
### Description

I've just installed GameMaker on a brand new Mac Mini, got my Apple Developer account, installed XCode, and checked out my GMS2 project from Git. I followed [these instructions](https://help.gamemaker.io/hc/en-us/articles/235186128-Setting-Up-For-macOS) pretty closely but the game crashes immediately after compiling. I've also tried compiling a fresh copy of the default "Space Rocks" tutorial to start with something simpler, but I get a similar crash report from that game too. I've also tried building with GMS2 VM and GMS2 YYC and get the same crash in both cases.

GameMaker version: IDE v2024.8.1.171, Runtime v2024.8.1.218
macOS version: Sequoia 15.0
XCode version: 16.0 (I realize that the GameMaker compatibility [only mentions XCode 15 on this page](https://help.gamemaker.io/hc/en-us/articles/227860547-GameMaker-Required-SDKs#h_01GF3MENBN83SSMQADJ5RJY84X). I'm willing to manually downgrade XCode to an older version if that's the route I need to explore)

[Crash Report in Pop-up Window](https://github.com/user-attachments/files/17367290/GM_Crash_Report.txt)
[Bug Package](https://api.gamemaker.io/api/github/downloads/d19997a7-eca2-4199-b401-fb921ca432b2)

### Steps To Reproduce

1. Start GameMaker
2. Open any project
3. Set target platform to macOS
4. Build > Run
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

macOS

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Hmm, this is running fine on my M2 Macbook Air running Sequoia 15.0.1, could be a problem with x86 Mac Mini's on Seqouia?

**Comment by sihammill** [comment]
On my X86 Mac Mini on Sequoia 15.0.1, I tested a project that I made, just something basic on both VM and YYC and then I ran the users project which was supplied in this bug report. In both cases, VM and YYC compiled the projects absolutely fine.

**Comment by Brushguy** [comment]
These are my Mac Mini's machine specs:

Model Year: 2018
Processor: 2 x 3.04 GHz
Graphics: Display 128 MB
Memory: 8 GB DRAM
Startup disk: Macintosh HD
macOS: 15.0.1

I'm not sure if it's relevant, but it might also be worth mentioning that I'm using a Mac cloud service called MacinCloud and am virtually remoted into the machine... I'm not sure whether that wouldn't impact the GameMaker runner.

**Comment by jackerley** [comment]
Hi, this is something you are going to have to take up with MacinCloud, it looks like they don't support openGL properly. This isn't something we can fix.
