### ISSUE TITLE
struct_foreach featherdoc is partially copied from struct_exists

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8003]
### Description

the function parameter description should probably say something more like "[the function to execute on each member of the struct; the callback function to pass into this function should take the following arguments: `member_name` and `value`](https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FVariable_Functions%2Fstruct_foreach.htm)"

![image](https://github.com/user-attachments/assets/ab1862f3-f9e3-4063-8ab4-b1745259e6ef)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly), 2024.1100 (Betas)

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.647  Runtime v2024.1100.0.667

it now says
"the function to execute on each member of the struct; the callback function to pass into this function should take the following arguments: key and value (in this order).
