### ISSUE TITLE
Code Editor 2: Warning Banner does not span properly when in Left/Right Navigation Orientation

### ISSUE THREAD

**Issue by zreedy** [YoYoGames/GameMaker-Bugs#8007]
### Description

The warning banner for when a script is an unknown language such as JavaScript without the proper GMPM packages installed does not render correctly if the Navigation is in Left or Right mode. Currently it bunches up in the left (in left orientation), or does not fully cross the length (in the right orientation).

### Steps To Reproduce

1. Start GameMaker
2. Install JavaScript GMPM package
3. Create a JavaScript script
4. Save your project
5. Uninstall JavaScript GMPM package
6. Restart the Editor
7. Open your Script
9. See the issue when in Left or Right Navigation Orientation

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.653  Runtime v2024.1100.0.679.
