### ISSUE TITLE
New Project should include an object which is already in the default room

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8020]
### Is your feature request related to a problem?

Given that the primary focus of gamemaker is to use objects to run code its always felt odd that to initialize a project you need to always create an object and place it into the room.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/c5338800-6315-40bd-99fc-945778ebc033)
what else is there to say

**Comment by attic-stuff** [comment]
you dont need to put an object in a room for the project to run. you do have to have a room but no objects are required.

**Comment by tinkerer-red** [comment]
An excellent point was brought up to me which has lead to my mind being changed, but leaving the request still open for discussion/consideration.

> There’s already cases of people following tutorials, creating a new room as the tutorial tells them to, and then running the game into the default empty room and not knowing why their game isn’t working
> So I think if a default object was added, people wouldn’t edit that object, they’d just make a new one anyways like the tutorials say to

**Comment by stuckie** [comment]
This is not something we are planning.
You should be able to save this as a Project Template to have an initial project setup you can use.
