### ISSUE TITLE
Code Editor 2: Changing workspace tabs while debugger is still open can cause a second Edit Menu to appear

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8032]
### Description

When using Code Editor 2 and debugging, closing the debugger tab as per https://github.com/YoYoGames/GameMaker-Bugs/issues/7759 no longer causes another Edit Menu to appear. However, keeping the debugger open and changing to another open CodeEditor 2 workspace will cause a second Edit Menu to appear

![EditTab](https://github.com/user-attachments/assets/6a51c709-4d6a-47ca-8238-2554fa3d2bee)

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Open a script that will run
4. Add a breakpoint to a scirpt
5. Debug run
6. keep the debugger tab open and select another of the script workspace tabs
7. observe the second Edit Menu is added

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed and merged

**Comment by Emc1923** [comment]
Verified fixed in IDE v2024.1100.0.680  Runtime v2024.1100.0.702
