### ISSUE TITLE
Building Projects: Projects containing new Facebook extension now give "-stack_size option can only be used when linking a main executable" error

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#8038]
### Which Extension are you reporting this issue for?

Facebook

### Description

Updating Facebook to the last versino on iOS I had to to use convert the current ObjC extensions to Swift, for some reason I start getting this error:

 Showing All Messages -stack_size option can only be used when linking a main executable

it's fixed deleting the flag **_-stack_size,1000000_** from **_Build Settings_** ->  **_Other Linker Flags_**

Project:
[Facebook.yyz.zip](https://github.com/user-attachments/files/17413832/Facebook.yyz.zip)

### Expected Change

Delete the flag stack_size

### Steps To Reproduce

1. Start GameMaker
2. Build an Xcode project with the attached project 
3. Try run the project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.689  Runtime v2024.1100.0.710 / Xcode 16.1
