### ISSUE TITLE
Add a Flexpanel editor in IDE

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8039]
### Is your feature request related to a problem?

Flexpanels as a code only feature is terrible

If there is a task or feature request already for this, I cannot find it with GitHub search, link it here before you close this as a dupe

### Describe the solution you'd like

An in IDE editor to organise and create the flexpanel layouts

https://wiki.opera.software/display/GM/FSD+-+Flex+Panel (Staff only)

### Additional context

https://github.com/YoYoGames/GameMaker-Bugs/issues/6917#issuecomment-2255387412

Im basically readding this because i cannot find a task for this - im sure one must exist for it but github search is not yielding results

**Comment by iampremo** [comment]
#3159 is the IDE side of flexpanels

**Comment by scott-dunbar** [comment]
They have separate design docs - might need someone in ui/ux/design to go through and make sure the correct information is present in the appropriate one. One is for rooms and sequences and the other is just for room layers.

**Comment by stuckie** [comment]
As above, #3159 is the main ticket for tracking this.
