### ISSUE TITLE
IDE: Close Assets in the background

### ISSUE THREAD

**Issue by AvioxArcade** [YoYoGames/GameMaker-Bugs#8045]
### Is your feature request related to a problem?

closing rooms, objects, or other assets can cause the IDE to freeze for a few/several seconds. This is especially bad when:
- there are a lot of assets open
- closing "everything but this" in a workspace
- closing a room with a lot in it. 

### Describe the solution you'd like

When closing assets, instead of processing it all "in the foreground", the IDE should just hide those assets and do what needs to be done to close them in the background.

**Comment by stuckie** [comment]
There was an issue with 2024.8 that did slow things down, this should be resolved for the upcoming 2024.11 which you can test in beta just now, to confirm that it works for you.

If you still have problems, please file a bug with a problematic project and a project layout, so we can take a look.
