### ISSUE TITLE
Please implement tuples as a structure type!

### ISSUE THREAD

**Issue by PGtheVRguy** [YoYoGames/GameMaker-Bugs#8046]
### Is your feature request related to a problem?

Sometimes I really wish I was able to not have to write everything into an array or several variables when adding or storing a position. It'd just make my code so much cleaner!

### Describe the solution you'd like

I'd love to see tuples (a way of storing x,y positions) implemented as a datatype so I can easily store positions into a single variable without arrays.

### Describe alternatives you've considered

An alternative is setting up an array with
pos = [oPlayer.x, oPlayer.y] 
or
pos[0] = oPlayer.x
pos[1] = oPlayer.y

### Additional context

This is just a datatype in Python that I'd like to see transitioned over as it'd make jumping between the two workflows a lot easier! I understand this isnt very high priority but it'd just be really nice if we also had functions support it to!

**Comment by stuckie** [comment]
We have no plans on doing this just now.
The alternative you have, is effectively what it is anyway.
