### ISSUE TITLE
YYRunnerInterface: Add a way to get a CInstance pointer from an instance ID

### ISSUE THREAD

**Issue by jarrrodnb** [YoYoGames/GameMaker-Bugs#8051]
### Is your feature request related to a problem?

Certain functions in the YYRunnerInterface like Script_Perform() allow for selfinst and otherinst arguments in the form of CInstance* pointers.

This is fantastic but is generally limited to the self/other provided automatically by the calling function. (ie whichever instance calls the ext function).

There appears to be no way inside the YYRunnerInterface to convert an instance ID integer to a CInstance pointer for use with such functions.

**EDIT**: 

After poking around in the YYGML.h header, I found this on line 185:

`YYCEXTERN	CInstance*  	YYGML_FindInstance(int _ind);`

This appears to point to the exact function I would like to be exposed to the YYRunnerInterface.

### Describe the solution you'd like

Allow the use of the function mentioned above in the YYRunnerInterface.

### Additional context

Were this to be implements, I could finally realize my dream of making super performant functions like instance_list_witheach() that loops through an array of instances, automatically setting scope to each one :D

**Comment by stuckie** [comment]
This is undocumented so that we can safely change things under the hood as necessary, without officially breaking user projects.
Please do not use this.
