### ISSUE TITLE
IDE autosaves the project when deleting an asset

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#8071]
### Description
If it not were for Git...

I was working on one of my libraries and, in order to update a dependency, I always delete the folder, then import the new version of the library right away. However, this time, by mistake I deleted the wrong folder in my project... So I decided to try to close Gamemaker hoping a "Do you want to save your changes?" message appeared. However, it didn't. As you can imagine, the assets were still gone when the project was reopened. Fortunately, I had just committed a change in Git a few days ago and I was able to discard the changes and get back to the last commit.

However, I really think that deleting assets should be marked as a change in the IDE, that could be revertible by not saving.

Additionally, there's no CTRL-Z available.

I'm not sure if this is an intended behavior or not, but for more inexperienced developers that do not use version control, it can be heartbreaking to delete a group of assets and not have the chance to undo/recover those. For this reason, I really think deleting assets should be marked as a change in the project and be saved until you explicitly do so, instead of being autosaved whenever you delete it.

### Steps To Reproduce
1. Create an empty project
2. Create two assets and save
3. Close Gamemaker
4. Reopen the project in Gamemaker and delete one of them
5. Close Gamemaker (no "Do you want to save changes?" prompt is shown)
6. Reopen the project in Gamemaker to find the asset is still gone, even though you never explicitly saved

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[1bb6612c-a446-43d9-a262-cd4aefb2e5ee](https://api.gamemaker.io/api/github/downloads/1bb6612c-a446-43d9-a262-cd4aefb2e5ee)

**Comment by stuckie** [comment]
Correct, this is why we advocate for source control use.
When any reference gets updated/deleted we have to save the project to ensure that what is on disk can be loaded again, as if we only save part of the project, and a crash happens, then that project is equally destroyed.
