### ISSUE TITLE
Is xbox GDKextension really necessary?

### ISSUE THREAD

**Issue by gsrainforest** [YoYoGames/GameMaker-Bugs#8077]
### Which Extension are you reporting this issue for?

App Tracking Transparency

### Description

Hi, I'm creating a build for xbox and I'd like to know if it's really necessary to use the xbox GDK extension.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Xbox (GDK)

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
the https://github.com/YoYoGames/GDKExtension is only for use with the Windows Target it is not needed for XBox target

**Comment by stuckie** [comment]
Closing as above
