### ISSUE TITLE
Error 0x80832003

### ISSUE THREAD

**Issue by gsrainforest** [YoYoGames/GameMaker-Bugs#8078]
### Description

Hello, when I start the game with a logged in profile I get the following error: 0x80832003. When I start the same game without a logged-in profile, the game runs without giving me any error. I'd like to know if I'm doing something wrong.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Xbox (GDK)

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Hi - there's no project attached, so we can't offer advice anyway, but be aware that as a general rule we do not offer coding support on this bug-reporting service.

If you're confident there is a bug here, or you have a very specific question, then please report this as a new issue and ensure you allow GM to attach a small sample project which shows just your sign-in code and therefore causes this error. Thanks.
