### ISSUE TITLE
Error 0x80832003

### ISSUE THREAD

**Issue by gsrainforest** [YoYoGames/GameMaker-Bugs#8079]
### Description

i'm creating a new project and sending it to xbox S|X with gamemaker studio 2 but when i send it i get the error: 0x80832003. Do I need to use an extension or can gamemaker export to xbox S|X without an extension?

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you having trouble building this project for?

Xbox (GDK)

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Same ultimate reply as on https://github.com/YoYoGames/GameMaker-Bugs/issues/8078

Again, we do not have your game to know what it requires, so we can't answer this exactly - but in general, no, you do not need to use any extensions to deploy to an Xbox.
