### ISSUE TITLE
Building Projects: [GX.games YYC] All projects fail to build in LTSr3 EL RT 87

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#8083]
### Description
GX.games YYC has an issue and all projects fail to build in LTSr3 EL RT 87 - including a brand-new single-room project

Can see lots of these lines:
```
wasm-ld: error: C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.3.87/yyc/operagx/libyoyo_yyc-wasm.a(Audio_Main.o): undefined symbol: std::__2::__vector_base_common<true>::__throw_length_error() const
wasm-ld: error: C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.3.87/yyc/operagx/libyoyo_yyc-wasm.a(Audio_Main.o): undefined symbol: std::__2::__vector_base_common<true>::__throw_length_error() const
```

and then finally

`C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.3.87/bin/assetcompiler/windows/x64/GMAssetCompiler.dll exited with non-zero status (1)`

### Steps To Reproduce
1. Start the LTS early look
2. Create a new blank template
3. Switch to GX.games > YYC
4. Run
5. Observe the build fails with no error specified in Compile Errors
6. Switch to the Output tab for more info

### Which version of GameMaker are you reporting this issue for?
IDE v2022.0.3.75 Runtime v2022.0.3.87

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
GX.games

[0862eb38-9a6e-4bba-b2b5-8d7ac8ed12e0](https://api.gamemaker.io/api/github/downloads/0862eb38-9a6e-4bba-b2b5-8d7ac8ed12e0)

**Comment by jackerley** [comment]
This is building fine for me. I think it might be down to which version of the Emscripten SDK you have installed? @YYDan

**Comment by alicemoretti** [comment]
This is still not compiling for me on IDE v2022.0.3.77  Runtime v2022.0.3.88. 

I'm using version 3.1.47 of Emscripten SDK., which is the one required for 2023.11 and newer here: https://help.gamemaker.io/hc/en-us/articles/227860547-GameMaker-Required-SDKs#h_01GF3MF7FPPX7A3J8RT2253M6G.

**Comment by YYDan** [comment]
Might be my setup at fault, then - will confirm before any discussion takes place about changing Emscripten needlessly ;)

**Comment by YYDan** [comment]
Yup, my fault. Closing as not a bug.
