### ISSUE TITLE
In-Game: string_concat_ext() uses incorrect name "string_build_ext" in error dialogs

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8089]
### Description

running `string_concat_ext` with out any arguments will throw an error referencing the incorrect name of the function.
![image](https://github.com/user-attachments/assets/cf7e8212-c065-4d77-90b7-c29d83710f3e)

### Expected Change

`string_build_ext` should be replaced with `string_concat_ext`, or if it's an internal function, then it should catch the error higher up.

### Steps To Reproduce

Running the following code (as is) will throw an error referencing the wrong name: `string_build_ext`
```gml
var test = string_concat_ext();
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

https://api.gamemaker.io/api/github/downloads/fee39510-4b95-4a0f-bad6-d9c8f17d17c8

**Comment by cameron-home** [comment]
Verified in IDE v2024.1100.0.654  Runtime v2024.1100.0.680
