### ISSUE TITLE
Code Editor 2: matching brackets in CE2 are highlighted in a very subtle way compared to CE1

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8096]
### Description

In CE1, matching brackets are highlighted with cyan bg:

![obraz](https://github.com/user-attachments/assets/e40ba675-4db5-4e91-a28e-51fa18ef6fb4)

In CE2, if "Rainbow brackets" are turned off, it's nearly not visible where matching bracket is, they have some gray bg:

![obraz](https://github.com/user-attachments/assets/91e8c8a6-ea52-4a80-a152-591cbbbe0134)

### Steps To Reproduce

1. Start GameMaker
2. Put cursor after `{, }, (` or `)`
3. Compare differences between CE1 and CE2 in that case, as on images above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

**Comment by KormexGit** [comment]
This color is also missing from themes, you can change the main selection color and the line selection color, but not the selection match color:

![image](https://github.com/user-attachments/assets/90f3b38f-041a-45df-83bc-bb078cceaed0)

**Comment by skud92** [comment]
CE1 is more readable, we should use this and have the option to change in preferences if the user wishes

**Comment by gnysek** [comment]
Yes, it's more readable in CE1, with selected text and default colors, it's even hard to notice that brackets are highlighted in CE2:
![obraz](https://github.com/user-attachments/assets/7ae6ea84-0517-4d64-97b1-6bdf73a64607)

**Comment by zreedy** [comment]
This was fixed with https://github.com/YoYoGames/GameMaker-Bugs/issues/5215
Please see final comment for details.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1300.0.714  Runtime v2024.1300.0.727
