### ISSUE TITLE
CE2: [Windows] Debugger step though is still visible after all code has been executed

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8100]
### Description

There appears to be an issue with the debugger in CE2, if you put a breakpoint in your code then step through it with F10, the debugger doesn't allow you to leave the last line of code, just gets stuck.

![image](https://github.com/user-attachments/assets/1334122a-77b2-4724-b7d7-0025c352b193)

### Steps To Reproduce

1. Start GameMaker
2. Create or open a project
3. Add in a breakpoint
4. Step through the code until the last line
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Fixed as apart of https://github.com/YoYoGames/GameMaker-Bugs/issues/8200

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1300.0.721  Runtime v2024.1300.0.734
