### ISSUE TITLE
Building Projects: [GX.VM] Project targeting GX VM, when Opera GX is not installed will be ran in default browser

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8102]
### Description

If a user does not have Opera GX installed but runs a working project when targeteting GX.games VM, then the project will be opened and ran in the user's default browser.

### Expected Change

An alert or error of some kind will show like when  an SDK hasnt been set or a device is not connected 

### Steps To Reproduce

1. uninstall Opera.GX
2. start Gamermaker
3. open a working or blank project
4. target GX.games VM
5. run the project
6. the default browser will open a new tab and run the project

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas), 2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package
[ui.zip](https://github.com/user-attachments/files/17492353/ui.zip)

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
This is correct behaviour and was explicitly added - we are no longer tied to using Opera GX browser... this is not a bug and is intentional

the WASM target runs on any browser now.

**Comment by mgeddesGM** [comment]
closing as is correct behaviour as noted by @rwkay
