### ISSUE TITLE
problems with xbox s|x

### ISSUE THREAD

**Issue by Edimar2077** [YoYoGames/GameMaker-Bugs#8106]
### Description

I'm looking for a comprehensive tutorial on creating an Xbox Series S|X build with achievements.

I created a new project and tried to run it on the console, but I get an error when logging in with my account. The project is empty, and the same happens with a more complete project.

Do I need to add any specific files, like a Microsoft.config, or configure the game options? The GameMaker tutorial for Xbox export is quite vague on this point.

It would be great to find someone who speaks Portuguese and can help us with this issue. We've been trying to export for over two months without success.

**Comment by gurpreetsinghmatharoo** [comment]
Please [follow this guide](https://help.gamemaker.io/hc/en-us/articles/19952625313693-Accessing-the-GitHub-Repositories-for-Console-Runtimes-and-their-Wikis) to get access to the Xbox repo and recreate this issue there so we can continue discussion. When you make the issue there, please give detailed information on the error you get.

Thanks
