### ISSUE TITLE
Unable to run game because of permission errors (Mac)

### ISSUE THREAD

**Issue by tymime** [YoYoGames/GameMaker-Bugs#8109]
### Description

I've downloaded an engine to help me get started making a game, but when I try to run it or debug it, I keep getting the same error saying "FAILED: Run Program Complete" and "Access to the path '*audio file*' is denied."
I've tried changing the permission settings to "Read & Write" several times, but it keeps reverting back to "Read only" whenever I try to run the game. It's only three files with this problem, as far as I can tell.
https://drive.google.com/file/d/1eHnyK663nKjkKdwvhFlq3kU3A_faz_mq/view?usp=sharing

### Expected Change

I just want to RUN THE GAME.

### Steps To Reproduce

1. Start GameMaker
2. Open FoxeyPlatform_1.3.1 engine
3. Hit "Run"
4. Output says "FAILED: Run Program Complete"

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
It looks like GameMaker is being blocked on your system, which isn’t something we can fix. I will close this issue now, but please see [our guide](https://help.yoyogames.com/hc/en-us/articles/360022953052) on what permissions and antivirus settings are required for GameMaker to work properly.

As this is macOS, you may also have your project in a protected folder, try keeping your project in your home directory, outside of Documents, Downloads, etc...
