### ISSUE TITLE
Code Editor 2 :CE2 Full-width characters may damage highlights

### ISSUE THREAD

**Issue by yunzlp** [YoYoGames/GameMaker-Bugs#8111]
### Description

rt
![Image](https://github.com/user-attachments/assets/3a8ab1c8-9b09-4fbf-b967-cf4a759704e5)

### Steps To Reproduce

1. Start GameMaker
2.input draw_text(x,y,"微软中国");show_debug_message("123")
3. done

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Related https://github.com/YoYoGames/GameMaker-Bugs/issues/8097 and https://github.com/YoYoGames/GameMaker-Bugs/issues/8111 and https://github.com/YoYoGames/GameMaker-Bugs/issues/8097

**Comment by zreedy** [comment]
Fixed. These tickets share the same underlying issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/6456 https://github.com/YoYoGames/GameMaker-Bugs/issues/8112 https://github.com/YoYoGames/GameMaker-Bugs/issues/8111

The char offset was converted to a byte offset in the UTF-8 when passed to the Regex library, but was not converted from byte offset to char offset when returned to the TextMate Grammar Tokenizer which caused the tokenizer to incorrectly parse the string by skipping characters.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1300.0.714  Runtime v2024.1300.0.727

![Image](https://github.com/user-attachments/assets/f7b12a18-29af-4bcd-91b8-e95747a16eff)
