### ISSUE TITLE
In-Game: [HTML5] Recycling a voice which is requesting data does not abort the request

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#8121]
### Description
Voices which are waiting on data (e.g. audio streams) do not have their requests aborted if the voice is suddenly recycled. Once the request completes the voice plays the requested sound even if it was stopped via GML. This can also lead to some of the voice subcomponents being overwritten.

### Steps To Reproduce
- Open and run the example project on HTML5.
- Note that two instances of the same sound play
- Expected behaviour is that only one should play.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.827 Runtime v9.9.1.981

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[d982ed02-2a3c-4149-ba2d-faf63c702fa4](https://api.gamemaker.io/api/github/downloads/d982ed02-2a3c-4149-ba2d-faf63c702fa4)

**Comment by toby-yoyo** [comment]
Stopping a sound should now abort any pending requests for data.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685
