### ISSUE TITLE
draw_set_swf_aa_level doesn't work for vector SVG

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8125]
### Description
`draw_set_swf_aa_level` seems to not work for vector SVG introduced in latest beta.

Only `display_reset(4, false);` and `display_reset(8, false);` seems to give good enough effects (aa level = 2 is still not smooth enough)

### Steps To Reproduce
1. Check attached example
2. Comment `swf` functions in Script1 (line 1+2) and uncomment line 4 with `display_reset`.
3. See the changes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.654 Runtime v2024.1100.0.680

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[72fc9e69-d50d-420e-bf6f-6e950634a3b2](https://api.gamemaker.io/api/github/downloads/72fc9e69-d50d-420e-bf6f-6e950634a3b2)

**Comment by gnysek** [comment]
(That's for [#5895](https://github.com/YoYoGames/GameMaker-Bugs/issues/5895) feature)

**Comment by L-Clouds** [comment]
Why would it?

**Comment by gnysek** [comment]
> Why would it?

Because it's rendered in same way .

**Comment by gnysek** [comment]
According to this comment ( https://github.com/YoYoGames/GameMaker-Bugs/issues/5895#issuecomment-2452210827 ), it was added in Runtime v2024.1100.0.691 (Beta 5) - the difference is that SVG have it's own functions and is not using SWF functionality (so both can different AA from what I understand).

I've made tests on mentioned runtime, and indeed, it works (by default aa_level = 1).

 I'm closing this ticket, as this seems to be resolved as part of #5895 .
