### ISSUE TITLE
In-Game: [GX.games] asset_get_index() and asset_get_type() incorrectly return "-1" for built-in assets

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8128]
### Description

`asset_get_index` and `asset_get_type` incorrectly returns `-1` for built in assets.

If you need to dynamically fetch an asset based off an arbitrary string on GX games, currently you need to `asset_get_ids(asset_*)` then `*_get_name(ids[i])` and cache all of that information into a look up table at runtime.

### Expected Change

Should return accurate information

### Steps To Reproduce

Test Project:
https://api.gamemaker.io/api/github/downloads/46ae564a-974d-44c7-8d44-4f64c9803baf

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by jackerley** [comment]
No project in attached bug report, unable to reproduce

**Comment by tinkerer-red** [comment]
@jackerley I did link a project under steps to reproduce

**Comment by jackerley** [comment]
@tinkerer-red There's no project in the attachement, just output files and logs?

**Comment by tinkerer-red** [comment]
Was under the impression "Privately attach this project" meant selecting 'no' would allow the project to be publicly available. My apologies. I've updated the ticket above and here is the new example project:
https://api.gamemaker.io/api/github/downloads/46ae564a-974d-44c7-8d44-4f64c9803baf

**Comment by jackerley** [comment]
Hi, I've just been taking a look at your sample. I think the problem is that asset_get_index only takes a string, not an Asset. If you change your code to asset_get_index("obj_gml_compiler_new") it will correctly return "ref object 1".  asset_get_type I can't see any problem with? Your asset_get_type(obj_gml_compiler_new) call is returning 0 (asset_object) on both gx and Windows?

I'll fix up asset_get_index to allow an Asset to be passed, but I think that's all there is to be fixed?

Thanks,
Fritz

**Comment by scott-dunbar** [comment]
Confirmed as fixed based on above comment in  IDE v2024.1300.0.714  Runtime v2024.1300.0.727

**Comment by tabularelf** [comment]
`asset_get_type` is meant to return the asset type from an asset reference as per #2957. But I don't really get the purpose out of returning an asset ref out of `asset_get_index`, from an asset ref?
