### ISSUE TITLE
script_execute errors on YYC with constructor functions

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#8137]
### Description
As per of this issue YoYoGames/GameMaker-Bugs/issues/7995, constructor functions can now be called without specifying new, via `script_execute` and `script_execute_ext`, treating the current scope as a constructor instance.

This works as intended in VM, but in YYC it crashes with `calling a constructor directly - constructors should only be called using new`

### Steps To Reproduce
1. Run project in YYC
2. See results

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.654 Runtime v2024.1100.0.680

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[a8bc3b45-f669-4026-a319-aa6b0a0d36ba](https://api.gamemaker.io/api/github/downloads/a8bc3b45-f669-4026-a319-aa6b0a0d36ba)

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685
