### ISSUE TITLE
Game Options: Add options for toggling legacy behaviours for string-to-number conversion, treatment of "other", and strict audio errors

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#8138]
### Description

Add IDE options to control the runtime options added in https://github.com/YoYoGames/GameMaker/issues/4463 and to control the default behaviour for audio errors (audio_throw_on_error) default them to on for new projects and off for existing projects.

(As per the existing Game Option for the newer collisions behaviour.)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

runtime 2024.1100.0.670

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

**Comment by YYBartT** [comment]
Added the new options on the Game Options manual page under "Deprecated Behaviours" and documented the legacy `other` behaviour on the `other` keyword page.
