### ISSUE TITLE
Manual Content: Clean Up Event page should have an explicit mention that User Events will not be triggered if called here

### ISSUE THREAD

**Issue by OnlookerRs** [YoYoGames/GameMaker-Bugs#8144]
### Description
Event User Not Triggered During Clean Up Event
But, Works correctly with Destroy event.

Tested Runtime Version
2024.2 ~ 2024.8.1.218

### Steps To Reproduce
1. Run the project.
2. Press the spacebar to move to the next room, triggering the Clean Up event, and check the Output.
3. Press F1 to trigger the Destroy event and check the Output.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[0119855b-a9d5-4767-a247-74ce6064b413](https://api.gamemaker.io/api/github/downloads/0119855b-a9d5-4767-a247-74ce6064b413)

**Comment by YYDan** [comment]
The manual says the Cleanup event happens after the instance is gone, so there would be no user event able to be performed; however, the Destroy event will let you do this (as you know).

https://manual.gamemaker.io/monthly/en/#t=The_Asset_Editors%2FObject_Properties%2FObject_Events.htm&rhsearch=cleanup

`It is designed for you to use to "clean up" any dynamic resources that you may have in your game (like surfaces, data structures, etc...) or to perform any task that you need performed once when the instance is removed from the game in any way.`

**Comment by Emc1923** [comment]
Verified changes are in the monthly manual, closing.
