### ISSUE TITLE
In-Game: Self/Other behaviour in 2024.1100 is incorrectly bound to "legacy number conversion" Game Option and is accordingly not working properly

### ISSUE THREAD

**Issue by Shibohi** [YoYoGames/GameMaker-Bugs#8151]
### Description
run the sample and see that self in call is set to objA instead of objB.
if u want to switch to legacy mode and u check "Legacy Other Behaviour" nothing happens. if check "Legacy Number Conversion" instead the behaviour changes.

### Steps To Reproduce
just run the program and see the output.
Self should be objB not objA.
check the "Legacy Other Behaviour" 
jun the game again - nothing changes
check "Legacy Number Conversion"
jun the game again - other should be objA now

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.654 Runtime v2024.1100.0.680

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[792c856d-eb0b-40b8-acdc-5c6f01568f49](https://api.gamemaker.io/api/github/downloads/792c856d-eb0b-40b8-acdc-5c6f01568f49)

**Comment by mgeddesGM** [comment]
fails as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685 for Win YYC with and without those legacy options

**Comment by jackerley** [comment]
This is fixed, in that the options now work properly. There is still a bug in that yyc will crash if  you aren't using Legacy Other Behaviour. This should be logged as a separate issue.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.664  Runtime v2024.1100.0.690
