### ISSUE TITLE
keyboard_unset_map() shows wrong example

### ISSUE THREAD

**Issue by TheouAegis** [YoYoGames/GameMaker-Bugs#8152]
### Description

The example is keyboard_get_map(); and that's not even the correct usage of keyboard_get_map()! Minor typo, but felt you should know.

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/Game_Input/Keyboard_Input/keyboard_unset_map.htm

**Comment by mgeddesGM** [comment]
verified in latest beta manual
