### ISSUE TITLE
Bug Reporter: "Privately attach this project" should be reworded to again state all files are uploaded privately

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#8173]
### Description

From a recent report, it only just occurred to me that when submitting a ticket from ide, the option "Privately attach this project" is not a boolean for if it's private or public, but a boolean for attach or dont attach.
![Image](https://github.com/user-attachments/assets/8b610504-043f-413e-808e-9223254676b7)
![Image](https://github.com/user-attachments/assets/880350bd-04f6-46cd-aacf-802e9d79aceb)

### Expected Change

Change "Yes" -> "Attach privately"
Change "No" -> "Do not attach"

### Steps To Reproduce

![Image](https://github.com/user-attachments/assets/2076b6f1-ea33-4064-a15a-1529d35a6dbb)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly), 2022.0.2 (LTS), 2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by iampremo** [comment]
This is a good suggestion 
![Image](https://github.com/user-attachments/assets/5d8e1a7e-b105-498a-9d62-5e1acfb8db30)

**Comment by YYDan** [comment]
For 2024.11 this will be changed just for the dropdown labels, as suggested in the comment above. A slightly larger change will be written up and scheduled separately.

I have edited the Expected Change accordingly.

**Comment by YYBartT** [comment]
Updated the wording on the manual page to the suggestion given above.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.688  Runtime v2024.1100.0.709.
