### ISSUE TITLE
Store the audio files duration in the asset cache file to for faster building and less build spew

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#8177]
### Is your feature request related to a problem?

Currently if you have a project with audio files in it every time you build the project you get output from the audio duration calculation, even if the audio file has already been converted and is cached.

Input #0, wav, from 'F:\Source\Games23\VHR_Source2\sounds\snd_Chief_Here_Radio\snd_Chief_Here_Radio.wav':
  Duration: 00:00:00.68, bitrate: 3072 kb/s
  Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 2 channels, flt, 3072 kb/s
  Duration: 00:00:00.67, bitrate: 3133 kb/s
  Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 2 channels, flt, 3072 kb/s

We should save this information in the cache file and retrieve it from there to reduce build time and reduce build output.

### Describe the solution you'd like

as above

### Describe alternatives you've considered

Putting a flag in to mute the audio output for the duration calculation.

**Comment by toby-yoyo** [comment]
The audio duration output from ffmpeg only appears if `Show verbose compiler output` is enabled in General Settings -> Compiling. As this could be useful debug info, I'm going to leave that unchanged.

The calculated duration of audio assets will now be cached alongside the converted audio itself in a metadata file. This will only contain the duration at this point, but can be used to store other data going forward. If the metadata file is present in the cache, the duration will be read from there and the ffmpeg-based calculation will not be performed unless the cache read failed for some reason.

Example project: [gmb-8177-x.zip](https://github.com/user-attachments/files/17615958/gmb-8177-x.zip)

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.680  Runtime v2024.1100.0.702
