### ISSUE TITLE
In-Game: [Ubuntu] application_surface / window size is set incorrectly at game start in 2024.1100 RTs

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8178]
### Description
I've created simple example, in which there's room, 1366x768, with background image stretched to full. There's no any other code, nor instances.
- no views
- no camera changes
- no other rooms
- no window size changes.

On Ubuntu, in 1100 runtimes it's shown in a wrong way.

When using "Keep aspect ratio", there's border on top+right+left (this image should be stretched to whole room):
![Image](https://github.com/user-attachments/assets/73992a94-e92d-44cc-b0a2-2c5cf8306e2a)

When using "Full Scale", right side is black (again, should be stretched):
![Image](https://github.com/user-attachments/assets/c9b14d73-6bce-4be6-92eb-f34d757d0db4)

_Update_

Seems that setting room size to 4:3 ratio (like 1024x768) solves this issue, so might be that runtime forces 4:3 initially. Also `application_get_posotion()` returns funny values until it works.
Also going fullscreen (no matter if going back or not) solves it.

### Steps To Reproduce
1. Create a game on Ubuntu, use 2024.1100 runtime, set some background in room (can be just color change)
2. Run game, there are black borders
3. Change "scaling" in Game Options
4. Run game, it's again wrong, bit this time right side only

It works ok on 2024.8(00) runtime.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.618 Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 22.04.5 LTS kernel 6.8.0.47

### Which platform(s) are you seeing the problem on?
Ubuntu

[4103cd8a-0376-4c0a-a1dc-e219dc5ea5fd](https://api.gamemaker.io/api/github/downloads/4103cd8a-0376-4c0a-a1dc-e219dc5ea5fd)

**Comment by yoyo-danielc** [comment]
Fixed on 2024.11 branch.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.1100.0.680  Runtime v2024.1100.0.702.
