### ISSUE TITLE
Multiple Issues with GameMaker encountered

### ISSUE THREAD

**Issue by KillshotELOx** [YoYoGames/GameMaker-Bugs#8182]
### Description

Hello, I would like your assistance in regards to these issues I have been experiencing while using the desktop application while using GameMaker. Specifically, I have encountered:

Unhandled Exceptions: The IDE crashes when it encounters unexpected conditions without proper error handling. For instance, when specific game events occur in unexpected sequences or when invalid user inputs are provided during game development, the IDE fails to handle these scenarios gracefully, resulting in crashes.

Memory Leaks: The application does not release memory when it is no longer needed, leading to increased memory usage and eventual crashes. This typically happens during prolonged development sessions within the IDE or when using resource-intensive features, such as complex animations and large asset files, causing the system to run out of available memory over time.

Critical Errors: Severe bugs causing the entire system to become unresponsive and require a reboot. These errors often arise during high-load operations within the build process, such as compiling large projects or testing games with intensive graphical elements, leading to system crashes and requiring a restart.

Functional Errors: The software behaves differently than expected, producing incorrect results due to logic errors. For example, game mechanics implemented in the IDE may not function as designed, collision detection may fail, or events may trigger incorrectly during the build process, leading to unexpected gameplay behavior and erroneous outcomes.

Control Flow Errors: The program's flow does not follow the intended path, causing unexpected behavior. This can occur during game development in the IDE when user inputs are not properly managed, leading to unintended game states, or when certain scripts or functions do not execute in the correct order, disrupting the overall flow of the game.

Hardware Usage Errors: The application does not properly interact with hardware, leading to crashes or malfunctions. For instance, issues may arise during the build process when using specific graphics cards, causing rendering problems or crashes, or when utilizing peripherals such as game controllers, leading to input recognition failures.

Acknowledgment Message Errors: The software fails to properly acknowledge or respond to user actions or system events. This includes instances within the IDE where the application does not provide feedback when tasks are completed, such as saving progress or exporting files, leading to confusion and uncertainty about the success of these actions.

### Steps To Reproduce

Unhandled Exceptions:

Start GameMaker Studio.

Create a new project or open an existing one.

Add game events that occur in unexpected sequences or provide invalid user inputs.

Run the game to see if the IDE crashes due to unhandled exceptions.

Memory Leaks:

Start GameMaker Studio.

Create a new project or open an existing one.

Work on the project for an extended period, using resource-intensive features such as complex animations and large asset files.

Monitor memory usage over time to see if the application crashes due to memory leaks.

Critical Errors:

Start GameMaker Studio.

Create a new project or open an existing one.

Compile a large project or test a game with intensive graphical elements.

Observe if the system becomes unresponsive and requires a reboot due to critical errors.

Functional Errors:

Start GameMaker Studio.

Create a new project or open an existing one.

Implement game mechanics, collision detection, and events.

Run the game to see if it behaves differently than expected, producing incorrect results.

Control Flow Errors:

Start GameMaker Studio.

Create a new project or open an existing one.

Add user inputs and ensure scripts or functions execute in the correct order.

Run the game to check if the program's flow follows the intended path or causes unexpected behavior.

Hardware Usage Errors:

Start GameMaker Studio.

Create a new project or open an existing one.

Utilize specific graphics cards or peripherals such as game controllers.

Run the game to see if it properly interacts with the hardware or leads to crashes or malfunctions.

Acknowledgment Message Errors:

Start GameMaker Studio.

Create a new project or open an existing one.

Complete tasks such as saving progress or exporting files.

Check if the application provides feedback or if there is confusion about the success of these actions.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
OK a wall of issues does not help anyone as you are not giving enough detail to allow us to fix any of them.

Please file issues separately and include projects that show the problems - talking about things as if they happen within every project is not helpful as issues happen because of many factors, the majority of them may well be problems with the software but you are not giving us a chance to actually find the problems, help us out here and give the information.

Many of theses are unclear if they are happening in game or within the IDE (they are very different pieces of software) - many of these issues are covered in other filed issues on the repo here - many of them are being addressed.

Please help us to help you... take one at a time and file an issue with a project (and / or  replication steps) that show the issue to us.
