### ISSUE TITLE
iOS Launch Options

### ISSUE THREAD

**Issue by jzavala-YYG** [YoYoGames/GameMaker-Bugs#8183]
### Which Extension are you reporting this issue for?

Firebase

### Description

Firebase Check App Extension need attach FIRDebugEnabled option at launch as described here: https://firebase.google.com/docs/app-check/ios/debug-provider#simulator
**_In the Arguments Passed on Launch section, add -FIRDebugEnabled._**

### Steps To Reproduce

1. Start GameMaker
2. Build the project targeting to iOS 
3. Open Product > Scheme > Edit scheme. Select Run from the left menu, then select the Arguments tab. In the Arguments Passed on Launch section, confirm if -FIRDebugEnabled it's there.

[BLANK GAME.zip](https://github.com/user-attachments/files/17560763/BLANK.GAME.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by YYDan** [comment]
Just to be clear, should this flag be there for _every_ project, regardless of whether the Firebase extension is included? (That's how the wording above reads and the fact that he sample project is called "blank" suggests the same.)

**Comment by jzavala-YYG** [comment]
Ah sorry for the project name, the flag FIRDebugEnabled or any other launch option should be included only when it's requested by any extension. The attached project contain an extension that insert FIRDebugEnabled in the launch options

**Comment by gurpreetsinghmatharoo** [comment]
@jzavala-YYG Is this flag needed for any iOS projects that use Firebase? Or only for specific Firebase features?

**Comment by jzavala-YYG** [comment]
> [@jzavala-YYG](https://github.com/jzavala-YYG) Is this flag needed for any iOS projects that use Firebase? Or only for specific Firebase features?

Specific for Firebase "Check App" Extension

**Comment by YYBartT** [comment]
Added `YYIosLaunchActionCommandLineArguments` and `YYIosBridgeHeader` tags on the iOS / tvOS Extensions page under the "Code Injection" section.

**Comment by Emc1923** [comment]
Verified working with the attached project as of Beta IDE v2024.1100.0.713  Runtime v2024.1100.0.726

<img width="615" alt="Image" src="https://github.com/user-attachments/assets/c702486c-3a3d-4bcf-a604-db4055cea74a" />
