### ISSUE TITLE
Updater: When selecting Update Now while in a project with unsaved changes you are not being given the prompt to save the project before closing

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8191]
### Description

The updater will not prompt to save the project (or save automatically) when selecting the Restart Now option

According to the design doc it should save and close the IDE
![Image](https://github.com/user-attachments/assets/7e331889-8898-48eb-a94e-559cf2bf8d30)

### Expected Change

Either prompt the user with the usual exit flow or just save regardless

### Steps To Reproduce

1. Start GameMaker
2. Start the update flow
3. Make changes to your project (edit a script/object code) but do not save
4. Once the update is ready select Update Now
5. Restart your poject
6. Observe previous changes are no longer present

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.668  Runtime v2024.1100.0.694
