### ISSUE TITLE
Updater: "File In Use" warning when moving the installer to the bin after updating

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#8193]
### Description

Updater warns about not being able to delete installer because it is in use.

This will occur for ~10 seconds on my system after updating, where the retry button will bring back the same warning before eventually continuing.

![Image](https://github.com/user-attachments/assets/97b4af61-0de9-4da4-b1a5-8969db351e9c)

### Expected Change

Installer moved to bin without a warning

### Steps To Reproduce

1. Start GameMaker
2. Go through the new update process
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.659  Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

**Comment by rwkay** [comment]
Fixed in 2024.11
