### ISSUE TITLE
Stripping Unused Assets From Your Export Packages seems to be enabled since 2024.4

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8199]
### Description

2024.1100 beta 4 mentions, that there's new feature:

> New Game Option For Stripping Unused Assets From Your Export Packages
> - You can now enable whether during builds GameMaker should automatically ignore any unused assets in your projects, so these are not added into your game packages
> - Game Options > Main > “Automatically remove unused assets when compiling”
> - **Note that this defaults to ON when creating a new project**, but you will need to enable it yourself in your existing projects
> - [#3597](https://github.com/YoYoGames/GameMaker-Bugs/issues/3597)

And while it says that it's ON by default for new projects I've found out, that it's on for my 2024.4.0.137 project, that it's enabled by default in all monthly and betas from that moment.

### Expected Change

This might affect existing projects and people might be unaware it's enabled for them.
When opening pre 2024.11 project, and `"option_remove_unused_assets":` is set to `true,` there could be a warning message, if we want to keep it "on".

### Steps To Reproduce

1. Check some older project from disk
2. Open .yyp to check IDE
3. Open `/options/main/options_main.yy` to check for `"option_remove_unused_assets":true,`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Ubuntu 22 LTS

**Comment by stuckie** [comment]
This should only have affected *new* projects since 2024.04 - any existing ones that were created from before should still have this off by default.

It isn't something we can easily go back and change now, and preferably if there are problems, we'd like to know so we can fix them rather than turning it back off.

What has happened is that now the feature flag has been set on it's triggering the code to use it, but not everything was feature flag aware to begin with. This is something we'll work on in future, but again, this won't affect already released versions.

**Comment by gnysek** [comment]
@stuckie 
> It isn't something we can easily go back and change now

It can be easily fixed. Just rename `option_remove_unused_assets` to something else, then this preference for 2024.4+ projects won't be used, and it will be available since 2024.11 :)

**Comment by tinkerer-red** [comment]
You could just check the version of settings, and update it if that feature never had any impact before.

**Comment by stuckie** [comment]
We have now fixed this for the next beta where *all* previous projects will have this set to false, and any new projects from the next beta onwards, will have it on by default.
There will be other details as well on the changes, so please be sure to read the release notes.
