### ISSUE TITLE
Debugger: Animation curve assets show up as <ref shader>

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8201]
### Description
This applies to both CE1 and CE2, so it seems to be a debugger issue rather than an editor specific issue. Animation curve assets show up as ref shader instead of ref animcurve.

![Image](https://github.com/user-attachments/assets/d5938b43-9165-4127-b00c-fb8ba8b86e6c)

![Image](https://github.com/user-attachments/assets/13da40c2-e555-47c1-b9b3-cf54a294b526)

### Steps To Reproduce
1. Set a variable to an animation curve asset
2. Set a breakpoint on that line
3. Step past the line
4. Mouseover the variable and see it says ref shader

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.659 Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[21ac97ad-4c74-4fc1-9acd-0aef70736826](https://api.gamemaker.io/api/github/downloads/21ac97ad-4c74-4fc1-9acd-0aef70736826)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.668  Runtime v2024.1100.0.694
