### ISSUE TITLE
In-Game: [YYC] Crash when not using legacy "other" behaviour in attached project built using 2024.1100 RTs 

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#8202]
### Description

From looking at https://github.com/YoYoGames/GameMaker-Bugs/issues/8151 run the project attached there in YYC with legacy other behaviour deselected and it will crash with no error.

VM works fine.

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11 with https://github.com/YoYoGames/GMS2-Runner-Main/pull/222

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.664  Runtime v2024.1100.0.690
