### ISSUE TITLE
TestFramework: "min_test" in BasicMathTestSuite fails, saying int64 const parameters results in incorrect output value

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8206]
### Description

Workflow artefact: https://github.com/YoYoGames/GM-TestFramework/actions/runs/11589645099#artifacts

Test code from Test Suite:
```
//#20 min( int64 const , int64 const , int64 const , int64 const )
_result = min(0x1122334455667788, 0x8877665544332211, 0x7FFFFFFFFFFFFFFF, 0x5566778811223344);
assert_equals(_result, 0x1122334455667788, "#20 min( int64 const , int64 const , int64 const , int64 const )");
```
_You can jump directly to the current location of this code via this [link](https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/BasicMathTestSuite/BasicMathTestSuite.gml#L3126)_

Logged result:
```
Testsuite Name: BasicMathTestSuite
Test Name: min_test
description: #20 min( int64 const , int64 const , int64 const , int64 const )
title: Assert values to be equal
stack: gml_Script_anon@103508@BasicMathTestSuite@BasicMathTestSuite:3129
actual: "@i64@8877665544332211$i64$"
expected: "@i64@1122334455667788$i64$"
```

### Steps To Reproduce

No repro steps available, this is a test run from the test suite stated above.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
The number 0x8877665544332211 is a negative number as bit 63 is set, so this is the minimum number as expected - the test is incorrect....
