### ISSUE TITLE
[YYC] Incorrect variable value resolution

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#8207]
### Description

The variable value is incorrectly resolved when using:

```gml
_obj[$ _parts[_parts_count - 1]] = _struct[$ _key];
```

versus when using:

```gml
var _nested_key = _parts[_parts_count - 1];
var _value = _struct[$ _key];
_obj[$ _nested_key] = _value;
```

you can check this in the Room Creation Code, and enable|disable it using the macro note that YYC fails to produce the correct output while VM works fine.

[struct_unflatten_error.zip](https://github.com/user-attachments/files/17576293/struct_unflatten_error.zip)

### Expected Change

YYC should work the same as VM

### Steps To Reproduce

1. Start GameMaker
2. Run the demo
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by rwkay** [comment]
Unable to repro on the current HEAD of 2024.11
