### ISSUE TITLE
No images on Italian translated version of page

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#8212]
### Description

Check https://manual.gamemaker.io/beta/it/#t=IDE_Tools%2FSound_Mixer.htm in Italian, there is no image

### Manual Link

https://manual.gamemaker.io/beta/it/#t=IDE_Tools%2FSound_Mixer.htm

**Comment by gurpreetsinghmatharoo** [comment]
Should be fixed in next release
