### ISSUE TITLE
[Manual Layout] Tooltips aren't translated for custom buttons

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#8213]
### Description

![Image](https://github.com/user-attachments/assets/6de246ff-e2f7-4e3f-8701-289ad055d244)

### Manual Link

https://github.com/YoYoGames/GameMaker-Bugs/issues/8212

**Comment by gurpreetsinghmatharoo** [comment]
Fixed on github, will be visible in next beta builds
![Image](https://github.com/user-attachments/assets/9d9a0dd3-1887-4689-b3f1-acf1c822c6e4)
