### ISSUE TITLE
Code Editor 2: Deleting an instance's creation code will bring up a "changes detected in project directory" popup. Clicking reload will crash gamemaker

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8216]
### Description
If you delete an instance's creation code when it has code inside that's been saved, a "changes detected in project directory" popup will appear for the room the instance was in. Clicking reload will freeze the IDE for a few moments, and then it will close with no error message.

https://github.com/user-attachments/assets/97108067-31c4-4ddd-b7a9-cb588b609046

(The other gamemaker at the end of the video is an instance of monthly I had open)

### Steps To Reproduce
1. Place an instance in a room.
2. Open it's creation code.
3. Type any code inside.
4. Save the project.
5. Delete the creation code.
6. Click reload on the popup.
7. Gamemaker will silent crash.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.659 Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[c6b40a72-341f-49cc-aa19-83c7378db944](https://api.gamemaker.io/api/github/downloads/c6b40a72-341f-49cc-aa19-83c7378db944)

**Comment by scott-dunbar** [comment]
Issue confirmed fixed in  IDE v2024.1100.0.685  Runtime v2024.1100.0.707
