### ISSUE TITLE
Building Projects: [Android] Extensions with conditional code-injection only injects the nested part of the expected result

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#8219]
### Description

for example:

```
<toExpand condition='${YYEXTOPT_YYFirebaseAuthentication_mode}' match='SDKs Only'>
implementation 'com.google.firebase:firebase-auth'
<A>
123
</A>
</toExpand>
```

this is expected to inject the code:

```
implementation 'com.google.firebase:firebase-auth'
<A>
123
</A>
```
to the gradle IF the condition is met, but apparently is only injecting the nested tagged elements:
```
<A>
123
</A>
```

and is leaving out the 

```
implementation 'com.google.firebase:firebase-auth'
```

This is a bug that will have impact in the next update of Firebase Extension which is a major fix for a lot of bugs.

[bug_conditional_code_injection.zip](https://github.com/user-attachments/files/17587641/bug_conditional_code_injection.zip)

### Steps To Reproduce

1. Start GameMaker
2. Open the included project and run for Android
3. Now go to the temp build folder and locate the build.gradle file: 

example path:
`E:\GameMaker\Cache\GMS2CACHE\BLANK_GAME_1DA02764_3C5F8159\Android\Default\com.company.game\build.gradle`
 
4. Look near the end of the file:

![Image](https://github.com/user-attachments/assets/f72da93b-f591-4049-a81f-54cd957b8ddd)

These lines won't be there (BUT SHOULD!)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Updated the title to be accurate and fixed that the platform was reported as Windows, not Android.
