### ISSUE TITLE
Manual: window_mouse_set_locked states its only usuable for Desktop Platforms

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8229]
### Description

window_mouse_set_locked states its only usuable for Desktop Platforms, but it does work on browser targets as well (HTML5 and WASM), the Note should be updated to include that information

![Image](https://github.com/user-attachments/assets/45f8653a-33c4-4b14-ac50-587ae211deb4)

### Manual Link

https://manual.gamemaker.io/beta/en/#t=GameMaker_Language%2FGML_Reference%2FCameras_And_Display%2FThe_Game_Window%2Fwindow_mouse_set_locked.htm

**Comment by YYBartT** [comment]
Updated the note on the manual page.
