### ISSUE TITLE
TestFramework: "string_ext_test #4.1" in BasicStringTestSuite string_ext(), failed to correctly format a string with repeated placeholders

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8240]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11610157668#artifacts

### Test Code

```
addFact("string_ext_test #4.1", function() {
			
	// Check that repeating placeholders works correctly
	var _format = "{0} {1} {2} {0} {1} {2}";
	var _result = string_ext(_format, [12, "hello", []]);
	assert_equals(_result, "12 hello  12 hello ", "string_ext(), failed to correctly format a string with repeated placeholders");
}, {
	test_filter: runtime_not_gmrt
})
```

### Output From The Test

```
Testsuite Name: BasicStringTestSuite
Test Name: string_ext_test #4.1
description: string_ext(), failed to correctly format a string with repeated placeholders
title: Assert values to be equal
stack: gml_Script_anon@157498@BasicStringTestSuite@BasicStringTestSuite:3642
actual: "12 hello [  ] 12 hello [  ]"
expected: "12 hello  12 hello
```

### Runtime Version

2024.1100.0.689

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/BasicStringTestSuite/BasicStringTestSuite.gml#L3636

### Which platform(s) are you seeing the problem on?

Windows

**Comment by DiasFranciscoA** [comment]
This was a GMRT test that incorrectly ran on the Beta build for Nov24 (false positive, wil be closed)

**Comment by sihammill** [comment]
Verified as per Francisco's comment above
