### ISSUE TITLE
TestFramework: "Audio buffer freeing test #1" in ResourceAudioBuffersTestSuite failed, audio_free_buffer_sound should make audio buffer unplayable

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8244]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11610157668#artifacts

### Test Code

```
addFact("Audio buffer freeing test #1", function() {
		
	// Free the buffer and test that it cannot play the sound afterwards
	assert_throw(function() {
		
		var bufferSoundId = GetInterpolatedPitchAudioBuffer(220, 880, 44800, 1, false);
	
		var soundId = audio_create_buffer_sound(bufferSoundId, buffer_u8, 44800, 0, 44800, audio_mono);
		
		audio_free_buffer_sound(soundId);
		
		audio_play_sound(soundId, 1, false);
		
	}, "audio_free_buffer_sound should make audio buffer unplayable");
	
});
```

### Output From The Test

```
Testsuite Name: ResourceAudioBuffersTestSuite
Test Name: Audio buffer freeing test #1
description: audio_free_buffer_sound should make audio buffer unplayable
title: Asserted function call to throw an error
stack: gml_Script_anon@1630@ResourceAudioBuffersTestSuite@ResourceAudioBuffersTestSuite:49
actual: null
expected: null
```

### Runtime Version

2024.1100.0.689

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/ResourceAudioBuffersTestSuite/ResourceAudioBuffersTestSuite.gml#L45

### Which platform(s) are you seeing the problem on?

Windows

**Comment by toby-yoyo** [comment]
Disabled the 'Hide audio errors' deprecated behaviour in the project, as this was suppressing a thrown exception for a test that was anticipating having to catch one.

**Comment by sihammill** [comment]
Verified in IDE v2024.1100.0.672  Runtime v2024.1100.0.698, this test no longer fails in the Test Framework
