### ISSUE TITLE
Updater: There is an extra / unnecessary dialog between selecting Restart Now and the Save and Close prompt

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8246]
### Description

After succesfully downloading the update the user is prompted to either "Update on Close IDE" or "Restart Now"

If the user selects "Restart Now" another prompt is given that tells them that a Restart has been requested, with an OK/Cancel option

If they select OK and the user has unsaved changes they will get another prompt to Save changes Yes/No

![Image](https://github.com/user-attachments/assets/e3961c7e-69a8-4ea9-8350-435012871d65)

This middle prompt seems uneeded, the user has selected Restart Now and are interupted if they have unsaved changes. If they dont have unsaved changes they are still given that superflous 2nd prompt.

### Steps To Reproduce

1. Start GameMaker
2. Start teh update process
3. Click Restart Now
4. See you are prompted again
5. Click OK
6. See that you now restart

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Would resolve https://github.com/YoYoGames/GameMaker-Bugs/issues/8247 at the same time

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.669  Runtime v2024.1100.0.698
