### ISSUE TITLE
Updater: Update attempted on closing IDE if user selected to restart now but then cancelled restart

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8247]
### Description

If the user downloads an update via the updater and presses "restart now" there is now a modal asking the user to confirm the restart. If they press cancel then when the IDE is closed the update will attempt to run
![Image](https://github.com/user-attachments/assets/2e94c298-9b6d-456a-8aee-c35a64d392cb)

### Expected Change

the updater does not start if cancelled

### Steps To Reproduce

1. Start GameMaker with a version that has an update available eg  IDE v2024.1100.0.664
2. go to help -> check for updates
3. the updater will find the latest update
4. download then press the "restart now" option
5. the ide will ask the user if they want to restart
![Image](https://github.com/user-attachments/assets/bf86ec60-93dc-4c23-8e06-e9f27ddb857e)
6. press cancel then close the IDE
7. the update will start up and windows will ask the user if they wish to proceed

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by CalumLaverock** [comment]
This issue should now be fixed as the "are you sure" dialog, after clicking restart, will no longer be shown so the IDE will either restart when you click "Restart Now" or go straight to the save check dialog if there are unsaved changes

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.668  Runtime v2024.1100.0.694

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.672  Runtime v2024.1100.0.698
