### ISSUE TITLE
Updater: Uninstalled GM, but never reinstalled it

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8249]
### Description
I opened up beta and said yes to updating. I waited on the start screen for it to finish, then hit "restart now". GM closed, and then shortly after the floating loading bar appeared, but only for a moment. It disappeared after less than a second and nothing further happened. My shortcuts for GM beta disappeared or became invalid. When I went to install GM beta again manually, it didn't give the usual prompt to uninstall, so I believe the updater just uninstalled GM and never reinstalled it. If I manually install the latest beta from the website instead of using the updater, it works fine.

Edit: I just tried updating on closing IDE instead of restart now, and got the exact same results. Windows asks to give the auto updater permission to make changes on my computer, I say yes, load bar appears for a second and then vanishes and nothing happens after that.

Additionally, since it's already downloaded the new version and just not installed it, every time I reinstall the previous beta the window pops up again with the options to on IDE close or restart now, without needing to download it first.

Edit2: Tried disabling the UAC permission popup and no difference

Edit3: Looked at windows log files at iampremo's suggestion, and didn't find anything. I also tried closing every other app on my computer before running the updater and no change.

### Steps To Reproduce
First I click restart now:

![Image](https://github.com/user-attachments/assets/8aaac510-92ea-4e71-8ae5-e9bd91277ae5)

Then the floating load bar appears for just a moment. After less than a second GM Beta disappears from my desktop, the load bar disappears, and nothing else happens after. GM Beta no longer exists on my PC, and reinstalling manually gives no prompt to uninstall the old version first.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.659 Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[22cde17d-a5ed-4434-9006-11452a235a14](https://api.gamemaker.io/api/github/downloads/22cde17d-a5ed-4434-9006-11452a235a14)

**Comment by rwkay** [comment]
Within the ui.log there should be an entry that will tell you the command line that is used when the `WindowsAutoUpdater` is started - it would be good to try that on your system to see what is happening...

**Comment by KormexGit** [comment]
https://api.gamemaker.io/api/github/downloads/94377c5a-4042-46ba-a0f0-1c725a10e07c](https://api.gamemaker.io/api/github/downloads/94377c5a-4042-46ba-a0f0-1c725a10e07c)

Here's the UI log immediately after it fails to reinstall

**Comment by jackerley** [comment]
This happened once for me, on my first use of the updater but I've not had it again since, and nothing of note was logged in my ui.log

**Comment by KormexGit** [comment]
For me it happens every time, I've tried it at least 10 times in the process of trying to narrow down what's causing it not to work

**Comment by rwkay** [comment]
I have added extra logging to the Updater and changed how the IDE invokes it, to see if this makes any difference.

I am going to Close this one just now - but if there are more issues, please attach the current UI.log to this and I will reopen.

**Comment by KormexGit** [comment]
It failed again updating to .686, but I guess the changes won't be testable until another update comes out since I assume this version has the changes
