### ISSUE TITLE
Updater: [Mac/Ubu IDEs] Help menu item for checking for updates should be hidden on these IDEs

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#8255]
### Description

The new Help menu item in 2024.1100 Betas for checking for updates should be hidden on Mac and Ubuntu IDEs, as they do not have the new updater functionality.

Accordingly, if someone clicks the menu item in these IDEs nothing will happen.

### Expected Change

Mac and Ubuntu Beta IDE users cannot see the Help menu command

### Steps To Reproduce

1. Start GameMaker using Mac or Ubuntu
2. Open the Help menu
3. Observe the command is there
4. (Optional) Click it and observe nothing will happen

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sequoia, Ubuntu 24 LTS

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.675  Runtime v2024.1100.0.701
