### ISSUE TITLE
GMRT: Trying to pass an array of objects/instances to any collision function crashes the game with no error message

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8266]
### Description
If you try to do `place_meeting(x, y, [Object1, Object2])` in GMRT, the game will crash with no error in output.

### Steps To Reproduce
Use any collision function and pass it an array of objects/instances/tilemaps.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[f7ed5eab-f765-47d6-a438-7a1209ecfe0e](https://api.gamemaker.io/api/github/downloads/f7ed5eab-f765-47d6-a438-7a1209ecfe0e)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1114  Runtime v2026.100.0.1076 gmrt 0.22.31
