### ISSUE TITLE
In-Game: SVGs with higher precision cause arcs to become concave and wiggly in 2024.1100 Betas

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8272]
### Description
When setting higher precision for SVG, rounded parts are becaming convate and jiggly:
![Image](https://github.com/user-attachments/assets/d3199db1-770d-4b1b-adcd-061db844f391)

![Image](https://github.com/user-attachments/assets/6e1ca5be-e8cc-4fd3-83ad-7b573ae5e263)
![Image](https://github.com/user-attachments/assets/3a2fe3da-56e4-41bb-8eeb-7903fdaee592)

### Steps To Reproduce
1. Import SVG which contains rounded shape (in my case it's text saved as curve)
2. Drag precision bar to hightest
3. Enable AA ( `draw_enable_svg_aa(true)`
4. See that shapes looks like cheese with holes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[cdf21e70-db1b-48b8-83cb-5e46d5551671](https://api.gamemaker.io/api/github/downloads/cdf21e70-db1b-48b8-83cb-5e46d5551671)

**Comment by yymrennie** [comment]
Fixed in 2024.11

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.693  Runtime v2024.1100.0.712
