### ISSUE TITLE
Inspector: SVG images need a "precision" setting to be added

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8273]
### Description
Inspector doesn't have "precision" setting for SVG images, it's only available by editing sprite in classic Sprite window.

![Image](https://github.com/user-attachments/assets/15599ea4-30fc-4f68-b752-193ee9aa9764)

I'm not sure if it's a bug, or Feature Request, feel free to correct it's category.

### Steps To Reproduce
1. Import SVG imge
2. Select it in Asset Browser
3. See that there's ni precision setting

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[27b1b6b8-9874-4b7c-9ef7-4ccedc581c68](https://api.gamemaker.io/api/github/downloads/27b1b6b8-9874-4b7c-9ef7-4ccedc581c68)

**Comment by mgeddesGM** [comment]
in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708 using the attached file, it was found that the precision UI did show but the up/down arrows moved the user in 0.99![Image](https://github.com/user-attachments/assets/d92c022a-028f-422d-843a-f1d66fc084aa)

**Comment by SamTHodson** [comment]
Testing on IDE v2024.1100.0.688  Runtime v2024.1100.0.709 on Mac, changing the precision value multiple times triggers the Project Directory Modified pop-up. Is this intended? As it does not appear to happen on Windows

![Image](https://github.com/user-attachments/assets/322066dc-8cbd-4826-b425-cabcb2640679)

**Comment by yyalansavage** [comment]
Added fix for arrow precision increments

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.693 Beta Runtime v2024.1100.0.707
