### ISSUE TITLE
Building Projects: [Windows] Add a native ARM64 export

### ISSUE THREAD

**Issue by rwkay** [YoYoGames/GameMaker-Bugs#8277]
Add support for creating a game that targets the ARM64 Windows platform.

- [x] ARM64EC Runner VM Target
- [x] ARM64EC Runner YYC library created
- [x] ARM64EC Igor / Asset Compiler building handling VM
- [x] ARM64EC Igor / Asset Compiler building handling YYC
- [x] Add Create Executable option for building on ARM64
- [x] Igor handling ARM64 runner when being run on an arm64 machine - autoselect on Test...

**Comment by gurpreetsinghmatharoo** [comment]
The options for these don't have proper strings yet:
![Image](https://github.com/user-attachments/assets/1e456a1f-d3dd-428a-ae86-85ceba4aaa32)

**Comment by Emc1923** [comment]
Found an issue creating ARM64 exe : https://github.com/YoYoGames/GameMaker-Bugs/issues/8320

**Comment by sihammill** [comment]
An issue has been found when trying to create an Arm64 executable, it produces a zip file that can't be extracted instead of creating a single executable as stated in the manual update #8446

**Comment by rwkay** [comment]
Closing as this feature is added - bugs have been addressed separately

**Comment by sihammill** [comment]
Feature verified and working as expected in Beta IDE v2024.1100.0.693  Runtime v2024.1100.0.712
