### ISSUE TITLE
TestFramework: "string_join_ext_test #4." in BasicStringTestSuite failed, to correctly join a string with mixed types, using a non-latin

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8282]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11624222653/artifacts/2131805916

### Test Code

```
addFact("string_join_ext_test #4.1", function() {
			
	// Check that using a non-latin delimiter works correctly
	var _result = string_join_ext("道", [12, "hello", []]);
	assert_equals(_result, "12道hello道", 
	"string_join_ext(), failed to correctly join a string with mixed types, using a non-latin character.");
}, {
	test_filter: runtime_gmrt
})
```

### Output From The Test

```
Testsuite Name: BasicStringTestSuite
Test Name: string_join_ext_test #4.1
title: Assert values to be equal
stack: gml_Script_anon@169933@BasicStringTestSuite@BasicStringTestSuite:3954
description: string_join_ext(), failed to correctly join a string with mixed types, using a non-latin character.
actual: "12道hello道[  ]"
expected: "12道hello道"
```

### Runtime Version

2024.1100.0.691

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/BasicStringTestSuite/BasicStringTestSuite.gml#L3949

### Which platform(s) are you seeing the problem on?

Windows

**Comment by DiasFranciscoA** [comment]
This was a GMRT test that incorrectly ran on the Beta build for Nov24 (false positive, wil be closed)
