### ISSUE TITLE
TestFramework: "string_concat_ext_test #1.1" in BasicStringTestSuite failed, to correctly concat a string with mixed types

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8285]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11624222653/artifacts/2131805916

### Test Code

```
addFact("string_concat_ext_test #1.1", function() {
			
	// Check that concatenating various data types works correctly
	var _result = string_concat_ext([12, "hello", []]);
	assert_equals(_result, "12hello", "string_concat_ext(), failed to correctly concat a string with mixed types");
}, {
	test_filter: runtime_gmrt
})
```

### Output From The Test

```
Testsuite Name: BasicStringTestSuite
Test Name: string_concat_ext_test #1.1
title: Assert values to be equal
stack: gml_Script_anon@161122@BasicStringTestSuite@BasicStringTestSuite:3734
description: string_concat_ext(), failed to correctly concat a string with mixed types
actual: "12hello[  ]"
expected: "12h
```

### Runtime Version

2024.1100.0.691

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/BasicStringTestSuite/BasicStringTestSuite.gml#L3729

### Which platform(s) are you seeing the problem on?

Windows

**Comment by DiasFranciscoA** [comment]
This was a GMRT test that incorrectly ran on the Beta build of the last Nov24 (fall positive wil be closed)
