### ISSUE TITLE
TestFramework: "string_test #4.1" in BasicStringTestSuite failed, to correctly format a string with repeated placehold

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8287]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11624222653/artifacts/2131805916

### Test Code

```
addFact("string_test #4.1", function() {
			
	// Check that repeating placeholders works correctly
	var _format = "{0} {1} {2} {0} {1} {2}";
	var _result = string(_format, 12, "hello", []);
	assert_equals(_result, "12 hello  12 hello ", "string(), failed to correctly format a string with repeated placeholders");
}, {
	test_filter: runtime_gmrt
})
```

### Output From The Test

```
Testsuite Name: BasicStringTestSuite
Test Name: string_test #4.1
title: Assert values to be equal
stack: gml_Script_anon@154344@BasicStringTestSuite@BasicStringTestSuite:3564
description: string(), failed to correctly format a string with repeated placeholders
actual: "12 hello [  ] 12 hello [  ]"
expected: "12 hello  12 hello 
```

### Runtime Version

2024.1100.0.691

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/85e03a71e87b23cffb3b93b42b18081307cf2f09/projects/xUnit/scripts/BasicStringTestSuite/BasicStringTestSuite.gml#L3558

### Which platform(s) are you seeing the problem on?

Windows

**Comment by DiasFranciscoA** [comment]
This was a GMRT test that incorrectly ran on the Beta build of the last Nov24 (fall positive wil be closed)
