### ISSUE TITLE
In-Game: [Windows] buffer_save() does not reliably block other code until after the save has finished

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8289]
### Description

Using the below code can intermittently cause the project to fail as the buffer_save function hasn't finished saving before the next line of code is executed. 

```
buff0 = buffer_create(1000, buffer_grow, 1);
buffer_seek(buff0, buffer_seek_start, 0);

artifact_path = game_save_id + "new_data/";
buffer_save(buff0, artifact_path + "summary.zip");
buffer_delete(buff0); // Clean up buffer
```
![Image](https://github.com/user-attachments/assets/40a3bdbd-7dc7-4c0e-a1dd-115f97d61369)

Error in output tab:
```
ERROR!!! :: ############################################################################################
ERROR in action number 1
of Async Event: HTTP for object obj_JSON_Parser:
Cannot delete buffer, it's in use by 1 others
 at gml_Object_obj_JSON_Parser_Other_62 (line 40) -         buffer_delete(buff0); // Clean up buffer
############################################################################################
gml_Object_obj_JSON_Parser_Other_62 (line
```

Project:
[buffer_save_bug.zip](https://github.com/user-attachments/files/17618244/buffer_save_bug.zip)

### Expected Change

I would expect the buffer_save() to finish saving before the next line of code is executed, since buffer_save() is not an async function like buffer_save_async().

### Steps To Reproduce

1. Start GameMaker
2. Load the attached project
3. Depending on the file size you are saving will depend on if this works or not, though my filesize was only about 120kb
4. See the issue

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by jackerley** [comment]
Hi, you are triggering two http_requests in the async http request event, but you aren't dealing with the case that b completes before a. What you need to do is to check the returned id in the async http event.  So 

var httpid = async_load[? "id"];

Then instead of checking a!=-1 you need to check if (a ==httpid) //This is the response from request "a" or if (b==httpid) //This is the response from request b.

Hope this helps,
Fritz

**Comment by sihammill** [comment]
Thanks Fritz,
I can confirm that implementing the change as you suggested appears to have sorted the issue out.
