### ISSUE TITLE
Command Line Builds: [HTML5] Custom runtime path value is ignored

### ISSUE THREAD

**Issue by sp202** [YoYoGames/GameMaker-Bugs#8292]
### Description

I'm trying to build the game with a custom HTML5 runtime from CLI, but Igor doesn't seem to be using the runner path provided in `local_settings.json`.

I've set `machine.Platform Settings.HTML5.runner_path` to the location of the custom runtime's scripts folder, but I can see that Igor is still using the standard runtime `/HTMLRunner="/workdir/runtimes/runtime-2024.1100.0.680/html5/scripts.html5.zip`

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Ubuntu 24 LTS

### Which platform(s) are you having trouble building this project for?

HTML5

**Comment by DiasFranciscoA** [comment]
Hello there @sp202, thank you for reaching out.
We would ask you to please provide the command line you are using so we can better replicate the issue on our side.

**Comment by sp202** [comment]
Hey, this is the command I'm using:

$RUNTIME_DIR/bin/igor/linux/x64/Igor --j=12 --rp=$RUNTIME_DIR --project=$CI_PROJECT_DIR/$YYP_FILE --uf=$PROFILE_DIR --tf=$CI_PROJECT_DIR/build_html5.zip --config=${CONFIG_NAME:-Default} --cache=$CI_PROJECT_DIR/gm_tmp/cache -- HTML5 zip || true

**Comment by sp202** [comment]
Any idea when this fix will make it into a release?

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1300.0.784  Runtime v2024.1300.0.789
