### ISSUE TITLE
Make "Automaticaly remove unused assets" less agressive.

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8305]
### Is your feature request related to a problem?

New option "Automaticaly remove unused assets is active by default for any projects created in 2024.4+ (including 2024.400 betas, so maybe even since February).

Issue is, that this setting ignores assets referenced by string (especially concatenated), and by tags. Many games might break, and people can be unaware, that **their projects already have enabled such option for half year**.
Assets referenced this way would be purged for 2024.4(00)+ projects if 2024.11 would be released without changes:
```gml
asset_get_index("asset_" + _variant);
tag_get_assets("my_selection")[0];
```
While (theoretically) assets mentioned using literal strings could be included when asset_get_index/tag_get_assets is in use (by stripping quotes around), there's still issue with using concatenated strings and variables.

### Describe the solution you'd like

In my opinion:
- by default, this setting should be set to undetermined state (`null` ?), which means **it's disabled**, same as when it's set to false - **including new projects** (but this could be still enabled/disabled from now on in `Game Options > Main`).
- when importing FIRST package/prefab to project, it should ask to enable/disable automatic removal of assets, and remember that choice (since it won't be undetermined anymore, it would know, that there's no need to ask for it again; user could change this setting now if needs in `Game Options > Main`)
- it should be renamed from `option_remove_unused_assets` to something else in `options/main/options_main.yy`, so 2024.4+ projects aren't affected and this setting won't be automatically enabled for projects made in last 6 months. My proposal is to name it `option_purge_unused_assets`, and remove previous config value on project load in 2024.11+, so none of existing projects would be affected.

This would make it optional, would cause less errors for newcomers, and people would be aware that they enabled it because of that pop-up (and maybe would read more about it in manual in that case, as while it's in release notes, when skipping 2024.11 and downloading 2025.x it won't be there anymore, and not everyone are reading all past release notes).

### Additional context

#8199
#8304
#8312

**Comment by Grisgram** [comment]
I think, one possible way to handle this more transparent for the user, would be a new menu item in the "Build" menu, where all the "Clear...." items reside.

Something like "Dry run unused asset removal". This runs the build but instead of removing assets, it presents a list of assets that _would be removed_ and you can pin assets as "keep" to prevent them from being removed (because you _know_, you reference them by string/concat/whatever.

gradle (google/android build system) also has options to prevent specific functions/classes/assets from being purged by setting.

**Comment by gnysek** [comment]
Having an option to "preview" what would be stripped sounds good.

**Comment by gnysek** [comment]
There's no deletion! Assets remain in project, this is only about executable.
And assets are protected by just me turning them in code - even in part which would be removed by compiler optimizations, as assets are compiled by different system.

**Comment by rwkay** [comment]
Behaviour of Remove unused has been subtly changed see https://github.com/YoYoGames/GameMaker-Bugs/issues/8312
