### ISSUE TITLE
Code Editor 2: Object Duplication Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by lcizzle** [YoYoGames/GameMaker-Bugs#8306]
### Description
When duplicating an object and then opening it syntax highlighting and autocomplete are busted.

### Steps To Reproduce
Create an object.
Create Create Event
Create Step Event
Create Draw Event
Add sample code to each event.
Duplicate the object.
In the duplicated object syntax highlighting and autocomplete are busted until one event is deleted.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[d0a2a6ea-9433-4135-b1a1-6dfe78ba2f53](https://api.gamemaker.io/api/github/downloads/d0a2a6ea-9433-4135-b1a1-6dfe78ba2f53)

**Comment by stuckie** [comment]
This should be fixed as part of https://github.com/YoYoGames/GameMaker-Bugs/issues/6751

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708.
