### ISSUE TITLE
Improve phrasing of output message for removing an unused asset

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8307]
### Is your feature request related to a problem?

I was curious if unused assets that got removed were listed in output when compiling, and sure enough they are. However, the message is a little unclear, since it just says "unused asset x". Additionally, the first one is on the same line as "Final Compile..."

![Image](https://github.com/user-attachments/assets/5aba9823-f78c-4b41-b0e0-c19b1769622f)

### Describe the solution you'd like

Change the message from "unused asset x" to something like "Removed unused asset x". Also, add a linebreak so the first one isn't on the same line as "Final Compile..."

**Comment by rwkay** [comment]
Behaviour of Remove unused has been subtly changed see https://github.com/YoYoGames/GameMaker-Bugs/issues/8312

**Comment by rwkay** [comment]
Behaviour of Remove unused has been subtly changed see https://github.com/YoYoGames/GameMaker-Bugs/issues/8312

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.675  Runtime v2024.1100.0.702
