### ISSUE TITLE
Code Editor 2: When typing an enum, autocomplete pops up with a suggestion for #endregion after every comma

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8318]
### Description
When typing out a new enum, it's fairly standard to put each new enum entry on a new line. However, every time you type a comma inside an enum and then try to hit enter to go to the next line, it instead autocompletes in #endregion. This means you need to manually close autocomplete each and every time.

https://github.com/user-attachments/assets/2ca4448b-0281-49a6-8d8f-fead681ce4cc

### Steps To Reproduce
Declare an enum, add some new entries, and try to add a new line between each one.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[12da6d18-6c26-402f-b663-84c35fdc2ee4](https://api.gamemaker.io/api/github/downloads/12da6d18-6c26-402f-b663-84c35fdc2ee4)

**Comment by scott-dunbar** [comment]
This specific issue has been fixed

 IDE v2024.1100.0.688  Runtime v2024.1100.0.709
