### ISSUE TITLE
Code Editor 2: Renaming a macro or enum using global search replace makes it show up as unset color until project is reloaded

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8319]
### Description
If you change the name of a macro or enum using global search replace while the script they are defined in isn't open, it'll make them appear in unset grey color until project reload. Additionally, the previous name of the macro or enum will keep getting colored red even though it doesn't exist anymore.

https://github.com/user-attachments/assets/b4888883-26f2-41de-91c1-4fd62b6f3a79

### Steps To Reproduce
1. Define a macro and an enum in a script.
2. Close the script you defined them in.
3. Use the macro and enum in an object.
4. Use the ctrl + shift + f search replace menu to change the name of the macro and enum.
5. See that they're both grey in the object, despite being red in the script.
6. Change them back to the previous name in the object. They will turn red again even though the old macro/enum no longer exist.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[10e2d1ac-7fb6-4207-b5bc-69bcd47d621e](https://api.gamemaker.io/api/github/downloads/10e2d1ac-7fb6-4207-b5bc-69bcd47d621e)

**Comment by zreedy** [comment]
The following are now fixed:
 - The issue as reported in the original ticket. Ensure that Object1 is open and Script1 is NOT open for the behavior to be observed.
 - After replacing text with Replace All attempting to Undo the change in an already opened file would corrupt that file's text

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.688  Runtime v2024.1100.0.709
