### ISSUE TITLE
Tutorials: Articles related to GX.games need updated to reflect the changes in the new Dev GX page

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#8321]
### Description

As the old [GX.create page ](https://create.gx.games/) is going to be replaced by a newer design in [GX.dev](https://dev.gx.games/), some of the GM tutorial pages need to be updated to reflect the changes. These are the following:

https://gamemaker.io/en/tutorials/gxgames-challenges
https://gamemaker.io/en/tutorials/gxgames-get-noticed

And the help page:

https://help.gamemaker.io/hc/en-us/articles/14637974730653-How-To-Create-Game-Strips-With-GameMaker

**Comment by gurpreetsinghmatharoo** [comment]
Both blogs have been updated.

The helpdesk page can't be updated because Mods (Game Strips) are still using the old GX Create site. Could you please create a separate bug for that?

Thanks
