### ISSUE TITLE
Prefab Library: Top level root shows everything, rather than just the collections

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8331]
### Description

if you expand something in the explorer window in the prefab library and then go back to the top level, instead of seeing the list of installed prefabs like you started out with you see what (i believe) is just a list of every folder in every sub-directory

![Image](https://github.com/user-attachments/assets/97c2a49b-ae33-4d49-ae53-04d17988e31c)

### Expected Change

you should see the list of installed prefabs

### Steps To Reproduce

1. Start GameMaker
2. prefab library
3. click around
4. go back to the top level
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.680  Runtime v2024.1100.0.702.
