### ISSUE TITLE
Improve `event_perform_*` with optional parameter

### ISSUE THREAD

**Issue by iconstudio** [YoYoGames/GameMaker-Bugs#8337]
### Is your feature request related to a problem?

For now `event_perform_async` is a just another copy of `event_perform`. Actually they have same features, but async one has `ds_map`.

We have 3 problems.
First bad consistent in codes. Looks bad.
Second, there is no integrated event invoker. If we make some calls of event and they are mixed of multiple type of events, we have to make some branches. E.g. `switch` with `ev_*`, `ev_async_*` constants, or tons of `if`s, whatever.
Last, the `ds_map` that passed into `event_perform_async` will be destroyed automatically, but we still have to create a `ds_map` manually.

#### Update `event_perform_async`
```gml
/// @param { Constant.AsyncEventType } type
/// @param { Id.DsMap } [ds_map]
/// @return Id.DsMap
event_perform_async(type, [ds_map = ds_map_create()]) -> ds_map
```
The `ds_map` would be created automatically, and `event_perform_async` will return id of `ds_map`.

#### Promote `event_perform`
```gml
/// @param { Constant.EventType|Constant.AsyncEventType } type
/// @param { Constant.EventNumber|Asset.GMObject|Constants.VirtualKey|Real } number
/// @param { Id.DsMap } [ds_map]
event_perform(type, number, [ds_map = undefined]) -> undefined
```
1. Add a optional parameter `[ds_map]` to `event_perform` at last.
3. `[ds_map]` will be ignored in case of non-asynchronous events.
2. Anyway if a `[ds_map]` is passed into `event_perform`, the `[ds_map]` will be destroyed automatically.

In this case we still need to create `ds_map` manually.

#### Make a integrated function
```gml
/// @param { Constant.EventType|Constant.AsyncEventType } type
/// @param { Constant.EventNumber|Asset.GMObject|Constants.VirtualKey|Real } number
/// @param { Id.DsMap } [ds_map]
/// @return Id.DsMap
event_perform_ext(type, number, [ds_map = undefined]) -> ds_map
```
I think it is not cool. We already have so many `*_ext` functions.

#### Add`ev_async`
Could there be `ev_async` to `event_type` and change the type of `ev_async_*`s to `Constant.EventNumber`?

**Comment by stuckie** [comment]
This is not something we are planning.
