### ISSUE TITLE
[HTML5] structs with a key named "image_index" return undefined when that key is read

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#8338]
### Description
This is a weird one. If you create a struct and one of the keys is named "image_index", when you try to access the key, it will yield undefined instead of the actual value.

Strangely enough, this does NOT happen with other instance variables or even with the built-in (deprecated) global variables. It only seems to happen specifically with "image_index".

This does not happen in any other platform.

### Steps To Reproduce
Sample project included, but
1. Create room and object, place object in room
2. Create a struct that contains a key named "image_index"
3. Try printing the value of that key (struct.image_index or struct[$ "image_index"]) and it will yield undefined

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Which platform(s) are you seeing the problem on?
HTML5

[1d2e2812-add4-4cb5-8a2b-75543cefa4ef](https://api.gamemaker.io/api/github/downloads/1d2e2812-add4-4cb5-8a2b-75543cefa4ef)

**Comment by jackerley** [comment]
Unable to reproduce, correctly prints 75 for me in runtime 2024.1100.0.701![Image](https://github.com/user-attachments/assets/3d6bf93d-aacc-40be-ad1e-5f17da2395d5)

**Comment by biyectivo** [comment]
> Unable to reproduce, correctly prints 75 for me in runtime 2024.1100.0.701![Image](https://github.com/user-attachments/assets/3d6bf93d-aacc-40be-ad1e-5f17da2395d5)

Ok, seems you somehow fixed it between .700 and .701 Betas. Will reconfirm once you release the .701 Beta. Thanks

**Comment by biyectivo** [comment]
Please reopen. I just retested on IDE .686 / Runtime .707 and it does not work.

**Comment by Grisgram** [comment]
Interestingly, we have reported this already about half a year ago and it got "fixed and verified"
#5968

so it's back now?
