### ISSUE TITLE
[Prefabs] Building Projects: Builds will fail if a prefab collection is uninstalled while prefab instances are still used in a project

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#8339]
### Description

As of  IDE v2024.1100.0.672  Runtime v2024.1100.0.698, when uninstalling a prefab collection while there is prefab instances from that collection still present in a room the builds will fail with the message attached. Attempting to delete a prefab collection that is in use should show a warning alerting the user first.

[outputlog.txt](https://github.com/user-attachments/files/17659847/outputlog.txt)

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Open the Prefab Library
4. Drag some prefab assets to a room
5. From the Package Manager, uninstall the Prefab collection 
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.672  Runtime v2024.1100.0.698

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

**Comment by stuckie** [comment]
This could happen if you had downloaded the original Prefab Collections, as we've had to update them.
We'll have functionality to upgrade Prefabs coming in future, but we don't have that yet, so we do apologise for the hiccup here.
As per the release notes - https://releases.gamemaker.io/release-notes/2024/1100 - if you uninstall them and reinstall them, they should link up fine in future.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708.
