### ISSUE TITLE
self / other still buggy?

### ISSUE THREAD

**Issue by Shibohi** [YoYoGames/GameMaker-Bugs#8344]
### Description
the self and other is always the same in chained functions

### Steps To Reproduce
run the project and see the output

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[57bb35fc-d988-4631-ba42-045c0d6f0047](https://api.gamemaker.io/api/github/downloads/57bb35fc-d988-4631-ba42-045c0d6f0047)

**Comment by rwkay** [comment]
This is not a bug as within an object event then the syntax

```
function Foo() { }
```
 and

```
Foo = function() {}
```

are exactly the same and result in a bound method that is bound to the `self` at the declaration point.

**Comment by Shibohi** [comment]
@rwkay thx for the response and sorry to ping u

I'm fine with the behavior of "self" what I don't understand is that "other" in this case is also objB, even though we are making the call from objA.

objA.inst_obj_b.do_something()

in the do_something function, "self" should be set to objB because the function is bound, which is currently the case, but "other" should reference objA because we made the call from that instance.

or am I seeing something wrong here?
