### ISSUE TITLE
In Game: Silent Crash starting in runtime 2024.1100.0.700

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#8347]
### Description
We are observing silent crash for YYC exports starting in beta 6 runtime 2024.1100.0.700 that was not in beta 5 runtime 691.

### Steps To Reproduce
1. Remove any existing save data at ` %localappdata%\BscotchPack`
1. Run the sample project for windows YYC export under the `gamepipe_test` config
1. See that the game silently crashes with the exit code  (-1073741819)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Android, iOS, Windows

[eff22a9d-fd66-44b7-8839-8fff0d873041](https://api.gamemaker.io/api/github/downloads/eff22a9d-fd66-44b7-8839-8fff0d873041)

**Comment by stuckie** [comment]
This should be fixed in .701 if you are able to verify this.

Thanks.

**Comment by shichen85** [comment]
Thank you. Verified.

**Comment by shichen85** [comment]
Thanks for looking into it!
