### ISSUE TITLE
weird behavior of array, is this feature or bug? (also found Inconsistency between YYC and VM)

### ISSUE THREAD

**Issue by HoyongNyong** [YoYoGames/GameMaker-Bugs#8352]
### Description
when you create an array ( like var a = [b, c, d]; ), I found out that function or unary operation inside of array excuted backwards.

for example, 

var a = 0;
show_debug_message([a++, a++]);

output will show you "[1, 0]"

I'm using MacOS and VM.

![Image](https://github.com/user-attachments/assets/65228581-9c0a-4da5-bad1-71f121daaa47)
![Image](https://github.com/user-attachments/assets/b52dc4db-9626-4d11-953a-6964136953eb)
![Image](https://github.com/user-attachments/assets/e8dc0a85-d392-48f7-9655-1ae9de9ad87b)

I also tested it on windows, VM and YYC.
Windows VM also reproduced it, but with Windows YYC did not reproduced it.

![Image](https://github.com/user-attachments/assets/3ee84235-ee04-4d16-9b35-29fe0736b106)
I tested this code on Window.

![Image](https://github.com/user-attachments/assets/bb084c6b-95b1-44bd-8eab-fbab62d56e85)
with YYC

![Image](https://github.com/user-attachments/assets/3fa8f593-eb1c-4c7a-b6e4-5293d064a5c8)
with VM

It's inconsistent.

### Steps To Reproduce
1. Open Gamemaker

2. Create new blank project

3. Create an object.

4. Put this code below in create event.
//test_case 1
show_debug_message("test case 1");
function foo() {
	static a = 0;
	return a++;
}

for(var i = 0; i < 10; i ++) {
	show_debug_message([foo(), foo()]);
}

//test_case 2
show_debug_message("test case 2");
var a = 0;
for(var i = 0; i < 10; i ++) {
	show_debug_message([a++, a++]);
}

5. Place the object in room and Run the project (with VM).

6. Output Shows Results of test cases.

7. Change the compiler to YYC and then Run again, Compare the result.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Mac 15.0.1 
+) Windows 10

### Which platform(s) are you seeing the problem on?
macOS
+) Windows

### Attached Files
* test_case_code.png
* test_case_1.png
* test_case_2.png

[4860c44a-2066-40f8-8c6b-4657250c6610](https://api.gamemaker.io/api/github/downloads/4860c44a-2066-40f8-8c6b-4657250c6610)

**Comment by attic-stuff** [comment]
this is intentional behavior

**Comment by KormexGit** [comment]
If it is intended, it should probably be documented in the manual, since as far as I can tell the array initialization order being inconsistent across platforms isn't documented like it is for function arguments.

**Comment by HoyongNyong** [comment]
> this is intentional behavior

that's interesting, but I tested it on window with YYC, it shows "[0, 1]". It's inconsistent.

**Comment by stuckie** [comment]
Closing as above.

Manual link here: https://manual.gamemaker.io/lts/en/GameMaker_Language/GML_Overview/Evaluation_Order.htm#:~:text=When%20programming%20your%20game%20using,them%20in%20an%20explicit%20manner 

Thanks.

**Comment by attic-stuff** [comment]
> That link only mentions functions though, it doesn't mention arrays

for sure yeah; the evaluation order page could stand to have a specific paragraph on array literals
