### ISSUE TITLE
YYC: Instant silent crash when compiling in YYC on latest beta

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8355]
### Description
On the latest beta, my game silent crashes on launch when compiling for YYC. It appears this is happening for other people as well, and a visual studio debug shows it's some kind of GC related issue.

### Steps To Reproduce
1. Run the attached project in YYC.
2. See that it silent crashes immediately on launch.
3. If desired, run on VM, monthly, or an older beta and see that it runs just fine.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[622a3b03-28b7-4f18-88ca-35879faff8eb](https://api.gamemaker.io/api/github/downloads/622a3b03-28b7-4f18-88ca-35879faff8eb)

**Comment by stuckie** [comment]
This should be fixed in the next Beta release.
