### ISSUE TITLE
Prefab Overrides: Erroneously operating on adding Prefabs

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8360]
### Description

this is apparently not intentional, or at least, part of a feature that isn't finished yet

![Image](https://github.com/user-attachments/assets/6e7473a6-474b-4bbc-b0af-a89faadbe1ef)

(the asset in question is `Music Tracks - Natural World/Sounds/Soundscapes/MP3_SND_Forest_At_Night`)

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Reproduction Steps:
- Create a new project
- Open the room
- Select the background layer
- Open the Prefab Library
- Drag any sprite to the background layer to use it
- Save the project
- See the "overrides" folder appear in the project's directory

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708
