### ISSUE TITLE
In-Game: draw_sprite() causes crash in attached project when using 2024.1100 Beta 6

### ISSUE THREAD

**Issue by protogenposting** [YoYoGames/GameMaker-Bugs#8362]
### Description

For some reason, calling draw_sprite causes this error in my project

ERROR!!! :: ############################################################################################
ERROR in action number 1
of Draw Event for object obj_song_select:
Unknown Function argument 1 invalid reference to (sprite) - requested -1 max is 5############################################################################################

I am not sure what is causing this, as I created another project with similar code and the issue did not persist. 

Here's the package https://api.gamemaker.io/api/github/downloads/79b4d64b-5346-46af-9086-08c8ac123dda

### Steps To Reproduce

1. Start GameMaker
2. Run the game
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Ubuntu

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by protogenposting** [comment]
tested it out, commenting both the draw_sprite does not fix the issue

**Comment by protogenposting** [comment]
did not mean to close that oops

**Comment by jackerley** [comment]
Hi @protogenposting  in your project something has happened to the dots filter in your select room. If you delete this filter and recreate it, your project should run fine. We're going to add some fixes in for the IDE to detect and fix if this happens again, but this should get you up and running quickly.

Thanks,
Fritz

**Comment by protogenposting** [comment]
thank you it works!

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708

For users encountering this issue:  You need to open the room and select the layer to apply the fix.

**Comment by mgeddesGM** [comment]
the issue seemed to be resolved if "Effect_1" was renamed but still has the same values
