### ISSUE TITLE
Building Projects: Builds with no assets to strip will still log a line that 1 asset is stripped, regardless of setting in Game Options

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8366]
### Description

builds with no assets to strip are outputting information that an asset is being stripped but provides no details. This happens regardless of option set and occurs even if there are no unused assets

-------------------------------------------------------
NOTE: 1 Unused Assets found (and will be removed) - 

-------------------------------------------------------

https://github.com/user-attachments/assets/90189e12-3da1-4fd6-b73b-ac3363e64e1e

### Steps To Reproduce

1. Start GameMaker
2. Create a new project
3. Build the project
4. Check output
5. Toggle setting to off in Main->Automatically remove unused assets when compiling
6. Check output

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.673  Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.675  Runtime v2024.1100.0.702
