### ISSUE TITLE
Project Saving: Dropping SVGs onto blank space in the Workspace to import the image converts them into PNGs

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#8370]
### Description

On IDE v2024.1100.0.667  Runtime v2024.1100.0.693, when a user drops a SVG image from explorer into the GM workspace, the image is converted into PNG.

### Expected Change

The image is imported as a SVG

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Drop the image attached into the workspace
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.667  Runtime v2024.1100.0.693

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Download URL

https://drive.google.com/file/d/1yUqcC-q6Lx5ipNQvL-PlNa6gWEs8kn9T/view?usp=sharing1

**Comment by stuckie** [comment]
Following the same existing logic as SWF and Spine, it'll import directly as SVG

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1100.0.693  Runtime v2024.1100.0.712. 

Thank you.
