### ISSUE TITLE
In-Game: [HTML5] draw_sprite_pos(), draw_sprite_tiled() and draw_sprite_tiled_ext() will throw if the given sprite is on an unloaded texture page

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#8371]
### Description
On HTML5, `draw_sprite_pos`, `draw_sprite_tiled` and `draw_sprite_tiled_ext` will not bail if the texture page of the sprite is not loaded. This will lead to an exception being thrown in the WebGL wrappers.

### Steps To Reproduce
- Open and run the attached project on HTML5.
- Open the console.
- Press '2' to draw sprites using different functions
- Observe that there is an exception thrown in `draw_sprite_pos`
- Expected behaviour is that each of the functions should print an error in the console (after https://github.com/YoYoGames/GameMaker-Bugs/issues/235)

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.847 Runtime v9.9.1.995

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[5adcd2b6-8387-4b4e-a74f-ca4dcffd5adc](https://api.gamemaker.io/api/github/downloads/5adcd2b6-8387-4b4e-a74f-ca4dcffd5adc)

**Comment by toby-yoyo** [comment]
Fixed by https://github.com/YoYoGames/GameMaker-Bugs/issues/235

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.896  Runtime v9.9.1.1041
