### ISSUE TITLE
In Game: [YYC] Chained accessor referring to the wrong reference as of 2024.1100 Beta 6

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#8375]
### Description
We are observing Chained accessor notation not finding the right reference for YYC exports starting in beta runtime 2024.1100.0.702 that was not in beta 5 runtime 691.

### Steps To Reproduce
1. Run the project in Windows YYC under the config `gamepipe_test_dev`
2. See the exception being thrown referring to `particle_get_info()` while the function is not called.
3. Run the project in VM and see no error.
4. Run the project in YYC in runtime 691 and see no error.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.679 Runtime v2024.1100.0.703

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

### Which platform(s) are you seeing the problem on?
Windows

[15625b49-7e37-44fa-95d4-0dd009e4d531](https://api.gamemaker.io/api/github/downloads/15625b49-7e37-44fa-95d4-0dd009e4d531)

**Comment by rwkay** [comment]
Fixed in 2024.11 - but I had to remove the fixes that were added for https://github.com/YoYoGames/GameMaker-Bugs/issues/8203 and https://github.com/YoYoGames/GameMaker-Bugs/issues/7082 - as they did not work in the general case

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1100.0.685  Runtime v2024.1100.0.707.
Thank you.
