### ISSUE TITLE
Persistent instances do not preserve layer order when being transferred to a new room

### ISSUE THREAD

**Issue by yoshikins** [YoYoGames/GameMaker-Bugs#8379]
### Description
This bug occurs because of how persistent objects are handled when being transferred over to a new room. When they're moved over to a new room, they're placed into whatever layer the runtime decides is appropriate to put them in, in the reverse order that they were in in the previous room... for some reason.

I encountered this bug when I realized that my global menu instances were being drawn in reverse order, but only in every other room. This is incredibly odd behavior and I know that we've been told to not rely on layer instance order, but this behavior seems incredibly easy for for GM newcomers to encounter, and very hard to debug unless the user is familiar with the inner workings of the current GM runtime.

Also considering that users are given the ability to explicitly define the order that instances are created in and layered in the room editor, it seems a little silly that said user-defined configuration would not be preserved in-game, or sporadically preserved at best.

### Steps To Reproduce
In the Room Editor, place down multiple persistent objects into a single layer. In game, call the function `room_goto` and observe that in every other room, their draw order is reversed.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[6895dab4-be9e-42b6-bd0d-64b4360e8de7](https://api.gamemaker.io/api/github/downloads/6895dab4-be9e-42b6-bd0d-64b4360e8de7)

**Comment by stuckie** [comment]
As you've stated yourself, you should not rely on instance order within a layer as this can change for a variety of reasons.
