### ISSUE TITLE
Sound Inspector: Playback position does not always reset after asset playback ends

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#8384]
### Description
When playing an audio asset from the sound inspector, the indicated playback position does not always reset to zero after playback reaches the end.

### Steps To Reproduce
- Open the attached project.
- Open the sound `_157` in the inspector.
- Play the sound several times.
- Observe that the playback position does not always reset to zero after it finishes.

### Which version of GameMaker are you reporting this issue for?
IDE v99.99.99.99 Runtime v9.9.1.996

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[8b0a4bb2-b3c7-4c0c-8d1f-046d528453b2](https://api.gamemaker.io/api/github/downloads/8b0a4bb2-b3c7-4c0c-8d1f-046d528453b2)

**Comment by toby-yoyo** [comment]
The playback position displayed on the sound inspector should now consistently reset after the asset has finished playing.

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
