### ISSUE TITLE
Blog post "The Basics Of Scaling - The GUI Layer" is missing two graphics and has one code mistake

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GameMaker-Bugs#8387]
### Description

This is not about the manual but about one of the old GM Blog posts from 2019 called "The Basics of Scaling - The GUI Layer". I often refer people to this article because it gives a great overview over the basics of scaling.

The article is missing two pictures that illustrate different kinds of scaling. One where it says "Keep Aspect Ratio Examples" and one where it says "Full Scale Stretched GUI Layer".

The article is usable without these graphics but if they're still lying around somewhere it would be great if you could add them back in because this article is really a great foundation for learning about scaling in GameMaker.

----

In addition the code example under the headline "Maximising the GUI" contains the line

if (aspect & gt; 1)

which should be changed to

if (aspect > 1)

### Manual Link

https://gamemaker.io/de/tutorials/the-basics-of-scaling-the-gui-layer

**Comment by Kev-Brown** [comment]
Thank you for reporting these issues, they have now been resolved.
