### ISSUE TITLE
IDE Updater: [Light Skin] Important text on "IDE Update" dialogs is hard to read because light-green on light-grey background

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8389]
### Description
Some of the key details are unreadable in the new [IDE Updater](https://github.com/YoYoGames/GameMaker-Bugs/issues/3157) when using the light IDE skin.  

Update Available
![Image](https://github.com/user-attachments/assets/c8173082-3d33-4ba2-867c-a49da19f7024)

Restart IDE to Update
![Image](https://github.com/user-attachments/assets/a04376fc-ab26-43aa-ae12-fe5f0baf55a1)

### Expected Change

The text at these two points now has a colour that is readable when using the light skin

### Steps To Reproduce
1. Install  Beta IDE v2024.1100.0.682  or a new version that's not the newest
2. change the IDE skin to "light"
3. go to "help - check for update" if the update modal does not show on IDE restart
4. notice the update text is almost unreadable
5. press download and wait to complete
6. notice the update text is almost unreadable

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
Should now look like this:

![Image](https://github.com/user-attachments/assets/0ab8e068-fdfe-42e0-9f92-cfbecf834a59)

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.688  Runtime v2024.1100.0.709
