### ISSUE TITLE
If more than two duplicate resources are polluted by git within .yyp, issues in code that uses the object_index

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#8406]
### Description
This issue sometimes occurs during collaboration through git.

A simple way to check if this issue is occurring is to look for warnings during the yyc build.

This problem was identified when code handling object assets produced different IDs for the same asset, and this was the cause.

Note. The test project has five identical assets duplicated as an extreme example for easy verification.

Solution
When opening the project, duplicate resources should be removed except for one.
and should inform about the removed duplicated.

### Steps To Reproduce
1. run project
2. see same name, diffrent object_index

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[4356f8b4-b74b-4552-a160-4a78cffb7f13](https://api.gamemaker.io/api/github/downloads/4356f8b4-b74b-4552-a160-4a78cffb7f13)

**Comment by stuckie** [comment]
The attached project definitely has errors, but it's not showing what you're meaning here as the object you've duplicated in the yyp does not actually have it's .yy file, so the project cannot be opened.

**Comment by stuckie** [comment]
That project is still broken.
If you extract that yourself you can see that objects/obj_target/obj_target.yy is missing so the project will not load.

**Comment by stuckie** [comment]
Perfect, that works now ( well, works as in showcases the original bug! )
I suspect the export functionality probably attempted to fix the brokenness and messed it up further.

**Comment by jonathan-markland** [comment]
https://github.com/YoYoGames/CoreResources/pull/368

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.775  Runtime v2024.1300.0.781
