### ISSUE TITLE
Take gxc_input_playback, gxc_record_input_playback and gxc_save_input_playback from behind feature flag

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#8409]
### Is your feature request related to a problem?

Right now we are using the input record, save and playback to automate some playtests to gather performance stats and evaluate performance changes across new builds. The function describe in this ticket were kept behind a feature flag and are important for this task, making them widely available can prove to be useful in some cases.

Keeping in mind that these are debug functions and their purpose is not to be used in production games.

### Describe the solution you'd like

The solution here will pass throw the series of tasks:

- [x] Remove the `gxc_` from this set of functions (asset compiler)
- [x] Remove them from the feature flag (asset compiler)
- [x] Make the respective changes in the runner side

Even though they were named `gxc_` they are not actually platgform specific and should work across all platforms.

**Comment by YYBartT** [comment]
Added a page for each of the new functions (`debug_input_record()`, `debug_input_save()` and `debug_input_playback()`) to the manual.

**Comment by scott-dunbar** [comment]
Verified in  IDE v2024.1300.0.775  Runtime v2024.1300.0.781

see attached project for example usage https://api.gamemaker.io/api/github/downloads/8fd52705-b7df-4659-a56a-c612d504336b
