### ISSUE TITLE
Building Projects: [GX.games] Zip package builds do not open the destination folder in a file explorer when successful

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8410]
### Description

For the uninitiated, this month's betas let you build the GX wasm runner as a regular HTML5(-like) game, meaning you can upload it anywhere. It's pretty cool.

![Image](https://github.com/user-attachments/assets/39301f80-cc73-4501-8bed-f4928309f11b)

However, when you finish doing that

        Igor complete.
        Igor complete.
        elapsed time 00:00:15.6761219s for command "C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.1100.0.707/bin/igor/windows/x64/Igor.exe" -j=8  -options="F:\GameMaker\Temp\GMS2TEMP\build.bff" -v -- OperaGX Package started at 11/14/2024 12:36:23
        SUCCESS: Package Program Complete
        Finished ZIP saved to F:\GameMaker\Projects\PlantSim\PlantSim.zip

it doesn't open the file in the file explorer like it does for pretty much every other build target.

### Expected Change

Open the destination folder in the file explorer

### Steps To Reproduce

1. Start GameMaker
2. Build something as a zip using the GX target
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
blocked testing by https://github.com/YoYoGames/YoYoStudio/issues/10942

**Comment by scott-dunbar** [comment]
Verified fixed
