### ISSUE TITLE
Building Projects: [GX.games] WASM zip packages duplicate audio files into a "runner" folder that isn't needed

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8411]
### Description

All of the files you need for the wasm build are in the root of the build folder, including whatever ogg or mp3 files the game needs to play sound:

![Image](https://github.com/user-attachments/assets/e722375f-838e-4c15-8002-c97c5956b08b)

But for whatever reason, they're also duplicated to the `runner/` folder:

![Image](https://github.com/user-attachments/assets/fb49b3ad-aa3b-4d9a-8c52-c15444067058)

If you delete that folder, the game still seems to work fine when you upload it to itch or some other host.

Since audio is usually one of the biggest contributors to GameMaker file size, this means that the zip you build can be almost twice as big as it has to be.

### Expected Change

Don't duplicate audio files

### Steps To Reproduce

1. Start GameMaker
2. Build something as a zip using the GX target
3. Open the zip
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

GX.games

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1300.0.718  Runtime v2024.1300.0.730.
