### ISSUE TITLE
part_system_drawit ignores the current matrix transform, but this isn't documented

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8415]
### Description

[from what I can tell this is so that the system can be rotated without the transform behaving in unexpected ways](https://github.com/YoYoGames/GameMaker-HTML5/blob/5a446d21a769ce18dc482f41d18473b30ec2940c/scripts/functions/Function_Particles.js#L507), but this isn't documented anywhere

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FParticles%2FParticle_Systems%2Fpart_system_drawit.htm

**Comment by stuckie** [comment]
This may have been changed recently.

**Comment by jackerley** [comment]
I believe this will have been fixed by https://github.com/YoYoGames/GameMaker-Bugs/issues/7561

**Comment by YYBartT** [comment]
No manual changes needed for this.
