### ISSUE TITLE
Non-gamepad devices require filtering on Android platform

### ISSUE THREAD

**Issue by offalynne** [YoYoGames/GameMaker-Bugs#8427]
### Description

*Filing issue per Russel's request for LTS2025*

In Android, many devices that are not gamepads are registered as gamepads. Extensive testing across myriad mobile GM titles and devices has produced a list of strings against which a lowercase `gamepad_get_description()` can be used to filter out non-gamepad devies on Android. List follows:

```
trackball
button jack
headphones
jabra
transceiver
usb receiver
surface type
touchscreen
touchpad
digitizer
multitouch
headset
sennheiser
blackwire
tv remote
smart tv
ir receiver
jvc rc10
virtual-search
multimedia remote
corsair
bt kb
uinput-fpc
joy-con charging grip
logitech mx master
logitech unifying device 
```

In case of lowercased `gamepad_get_description()` containing any of the above strings, the gamepad index should behave as if none is connected, so:
1. The `Async - System` gamepad discovery event should not be registered
2. The `Async - System` DS map `async_load`  should not push `"gamepad discovered"` or `"pad_index"` to `async_load`
3. The index should return `false` from `gamepad_is_connected()`
4. The index should return "none" from `gamepad_get_guid()`
5. The index should return "" from `gamepad_get_description()`

If anyone assigned to this lacks a device to test, I suggest testing another device on hand (eg. PlayStation controller) to confirm the implemented blocking method works. Upon follow up I am glad to confirm a working solution locally with a relevant device from the list.

See also #8425, #8426, #8427, #8428

### Steps To Reproduce

Connect gamepad, observe issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fix added to internal `develop` version should be in 2024.13 Beta

**Comment by scott-dunbar** [comment]
I lack devices suitable for testing but can confirm the changes are present

Closing issue - should you continue to have issues please do get back in touch
