### ISSUE TITLE
Wacom tablets require filtering from gamepad devices on desktop platforms

### ISSUE THREAD

**Issue by offalynne** [YoYoGames/GameMaker-Bugs#8428]
### Description

*Filing issue per Russel's request for LTS2025*

Wacom tablets show up as joysticks, which interferes with normal gamepad behaviour. All Wacom devices should be blocked from regisering as gamepads, identifiable by the Vendor ID `0x0531`. 

If a gamepad GUID begins with `030000003105...` or `050000003105...`, the gamepad index should behave as if none is connected, so:

1. The `Async - System` gamepad discovery event should not be registered
2. The `Async - System` DS map `async_load`  should not push `"gamepad discovered"` or `"pad_index"` to `async_load`
3. The index should return `false` from `gamepad_is_connected()`
4. The index should return "none" from `gamepad_get_guid()`
5. The index should return "" from `gamepad_get_description()`

If anyone assigned to this lacks a device to test, I suggest testing another device on hand (eg. PlayStation controller) to confirm the implemented blocking method works. Upon follow up I am glad to confirm a working solution locally with a relevant device.

See also #8425, #8426, #8427, #8428

### Steps To Reproduce

Connect tablet, observe issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fix added to internal `develop` version should be in 2024.13 Beta
