### ISSUE TITLE
skeleton_skin_create silently crashes game but function with static declaration makes it work

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#8433]
### Description
I'm updating the engine from 2024.2 and I had the game silently failing at startup, no obvious error message in the output.
After doing breakpoints, I narrowed it down to skeleton_skin_create call on line 238 in the scripts>Skin script asset.
Weirdly using my custom "log" function made the game actually run.
After a few test, it seems that calling a function that declares a static is all that is needed for the game to run, as demonstrated by the "do_nothing" function call on line 237.

This looks most likely to be an error in my code that's not caught by GM.

### Steps To Reproduce
1. Launch the game to see silent fail
2. Comment out "do_nothing" on line 237 call to see game run

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[4460161f-53a8-4ff3-af2d-9a99a11e1cff](https://api.gamemaker.io/api/github/downloads/4460161f-53a8-4ff3-af2d-9a99a11e1cff)

**Comment by jackerley** [comment]
Turned out this was a problem with audio_sound_get_loop_end

**Comment by patchuby** [comment]
> Turned out this was a problem with audio_sound_get_loop_end

Could you be a bit more specific ? Is it a problem with the function itself or the way it was used ? Using a non valid audio id ?

**Comment by jackerley** [comment]
Our implementation of audio_set_get_loop_end had a null check the wrong way around, so if you passed it an invalid audio index it would crash and if you passed it a valid index it would say it was invalid. Fixing this meant that your project ran fine for me (it was crashing every time with the incorrect check in)

**Comment by patchuby** [comment]
Ok thanks for the explanation

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.703  Runtime v2024.1100.0.719
