### ISSUE TITLE
Updater: Always accepts installer defaults such as file associations and shortcuts

### ISSUE THREAD

**Issue by OnlookerRian** [YoYoGames/GameMaker-Bugs#8435]
### Is your feature request related to a problem?

In Beta v2024.1100.0.686, there is an issue where the Updater forcibly resets the .yyp extension. It overwrites the settings of the official version's yyp without consent.

This problem is likely to worsen as the LTS version is released in the future.

### Describe the solution you'd like

A choice should be provided to prevent overwriting the settings, or the existing settings should be retained as they are.

**Comment by gnysek** [comment]
So "updater" installer forces .yyp extension to be used by beta? It should not touch it at all (which would result with current setting). Beta, monthly and LTS still need to be first installed using normal installer, so we can assume that user already selected which version have .yyp assignment.

**Comment by rwkay** [comment]
This should be fixed in 2024.11 now - but in silent mode it no longer creates the desktop icon, or the file associations... we may need a better way of doing this.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.695  Runtime v2024.1100.0.713.
