### ISSUE TITLE
Building Projects: [tvOS] Default Xcode project should not enable the Extended Gamepad permission, as this causes fails when Archiving

### ISSUE THREAD

**Issue by peardox** [YoYoGames/GameMaker-Bugs#8436]
### Description

When building a release for tvOS it will fail the final step with a complaint about an unsupported game controller profile 100% of the time

![Image](https://github.com/user-attachments/assets/cbaa3405-795c-48ce-bb95-ad7840ae3850)

![Image](https://github.com/user-attachments/assets/9ed6bb3e-1691-4995-ae4e-a58e0bb26efc)

### Expected Change

Don't include the Extended Gamepad permission

### Steps To Reproduce

1. Start GameMaker
2. Build a bank project for tvOS
3. In XCode try to Project -> Archive
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

tvOS

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by peardox** [comment]
As this is just another permission...
Can you also add the ITSAppUsesNonExemptEncryption to No as you already do on iOS (hasve to manually do this for tvOS but not iOS)

**Comment by jackerley** [comment]
Note for QA, this error only shows when you attempt to update to App Store Connect

**Comment by Emc1923** [comment]
Closing as done. Please do let us know if you experience any issues after installing the 24.13 Betas or the upcoming monthly version.
