### ISSUE TITLE
Sprite Editor:  Nine slice preview only animates on cursor movement

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#844]
GM-8032

{quote}
When opening the sprite editor a 9-slice only animates when moving the mouse cursor within the IDE. Hovering on the Window border does not allow for the 9-slice preview to animate.
{quote}

*Steps*
- Open a project that contains a sprite with more than one frame or the sample provided
- Click on the sprite and from the editor open the nine slice menu
- Play the frame sequence
- Observe that it only animates when the cursor is moving- doesn't matter if in or outside the editor window (workspace)

Note: LTS is working fine

Repro: 100%

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.449  Runtime v2023.1100.0.458
