### ISSUE TITLE
Source Control: Dock tab gets corrupted when discarding changes/editing files in an external app

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#8443]
### Description

When reloading a project after discarding changes in an external app the source control output tab will appear empty. If you close the tab you won't be able to bring it back.

![Image](https://github.com/user-attachments/assets/1fb663b8-7724-4080-8c70-9cc40a3d3a4a)

https://api.gamemaker.io/api/github/downloads/09f6eb5b-3e8d-44b3-8b35-7c2208b5c35d

### Steps To Reproduce

1. Start GameMaker
2. Open a project that uses source control
3. Add some changes to the project
4. Discard the changes from an external app (e.g. GitHub)
5. Reload the project
6. See the issue
7. Close the tab
8. Go to _Windows>Source Control Output_
9. Observe that nothing happens after selecting the option

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
The Source Control Output command was set wrong, so this wasn't actually opening properly at all.

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.693  Runtime v2024.1100.0.712.
