### ISSUE TITLE
Building Projects: [Win ARM64] Selecting the Installer package type results in a Zip package

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8446]
### Description

Attempting to create exe and pick an installer package for Windows Arm64 results in the output file being a zip file containing the lose game files, and in a file type that Windows say is invalid if you try to view it in Explorer.

No option to output as an executable file:
![Image](https://github.com/user-attachments/assets/5aaf5a3c-ebfb-4080-a946-25271565ff87)

Error when attempting to view the zip file in Windows Explorer's native .zip handling functionality - you must use 7zip to view/extract the .zip GameMaker makes:
![Image](https://github.com/user-attachments/assets/77b0ca4c-16ae-4330-bf2c-380ac7283698)

Zip file contents when choosing the installer for Arm64:
![Image](https://github.com/user-attachments/assets/c860155c-667e-43f1-a3ab-29aab078a11d)

Note that the latest 2024.1100 Beta manual update for this states that a single .exe will be created - if a .zip is expected (due to building on the wrong CPU architecture, etc.), then the manual needs to be fixed:
![Image](https://github.com/user-attachments/assets/79c19912-ff90-4df0-8368-bfb9e508cba0)

### Expected Change

A single NSIS executable file should be generated, just like the non-ARM64 installer package makes

### Steps To Reproduce

1. Start GameMaker
2. Load a project (any) and ensure you're set to Windows target
3. Click 'Create an Executable' from the top menu
4. Select 'Package as Installer for Arm64'
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by sihammill** [comment]
Fixed verified in Beta IDE v2024.1100.0.689  Runtime v2024.1100.0.710
