### ISSUE TITLE
Package Manager: GM forgets JavaScript package is installed each time the IDE is restarted

### ISSUE THREAD

**Issue by Lukanibal** [YoYoGames/GameMaker-Bugs#8448]
### Description
I have to reinstall the JS package every time I reopen the IDE.
The dropdow in the code editor only shows GML and Visual.

### Steps To Reproduce
Install JS package
Close IDE
Open IDE
Try to make a JS script in a project

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Attached Files
* Screenshot 2024-11-18 085853.png

[06d1771d-08d8-49db-a1fe-477c050fe46c](https://api.gamemaker.io/api/github/downloads/06d1771d-08d8-49db-a1fe-477c050fe46c)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.715  Runtime v2024.1300.0.727
