### ISSUE TITLE
In Game: [Windows] MP4 video playback freezes

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#8451]
### Description
Might be related to what's going on in https://github.com/YoYoGames/GameMaker-Bugs/issues/8450, but this is for the Windows export.

We are noticing that the MP4 video we have is freezing in the latest runtime 2024.1100.0.708.

### Steps To Reproduce
1. Run the project for Windows VM under the `gamepipe_test` config
2. Start a new save, select any difficulty, and it will play the opening cutscene, which is the included file `opening.mp4`
3. Export built with runtime `2024.800.0.642` plays fine, but with runtime `2024.1100.0.708`, the video plays with choppy start and then freezes.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.687 Runtime v2024.1100.0.708

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[238197fb-3246-4a62-9b44-5cec6f9d898f](https://api.gamemaker.io/api/github/downloads/238197fb-3246-4a62-9b44-5cec6f9d898f)

**Comment by shichen85** [comment]
https://github.com/user-attachments/assets/b42eba1e-b0ed-4a87-95f3-46f3ecf81079
This video shows that the playback starts freezing at the 00:12 mark

**Comment by jackerley** [comment]
Hi @shichen85  I can't reproduce this, it plays just fine in Windows VM and YYC for me. What are the machine specs that you are running it on?

**Comment by shichen85** [comment]
Running the YYC through Visual Studio, I can see that shortly before the freeze, the Output logs shows the following message:
`Exception thrown at 0x00007FF9E81D2BDC (KernelBase.dll) in Crashlands2.exe: WinRT originate error - 0xC00D4A3E : 'The sample allocator is currently empty, due to outstanding requests.'.`

The full log is attached. [video_debug.txt](https://github.com/user-attachments/files/17818687/video_debug.txt)

**Comment by shichen85** [comment]
This is from another coworker:
```
Windows 11 64-bit
GPU: Nvidia RTX 3080
Driver 565.9
CPU: 12 Gen Intel Core i7 12700KF
RAM: 64gb Installed, 45.9gb available
```

For them, running the project from the IDE for Windows VM run also plays video with decreased speed, but it does not freeze. For YYC run, the video plays at normal speed when the game window is focused, but if it is in the background, it plays with decreased speed.

**Comment by BscotchSeth** [comment]
@jackerley We've found the reason for different people getting different results! Video playback seems tied to the **frame rate** the game is running at. We got the following results on my 144hz monitor, while using game_set_speed() to control the game's FPS:

- 20 FPS: Video crashes the game.
- 30 FPS: Video crashes the game.
- 60 FPS: It runs largely smoothly with the occasional small stutter.
- 144 FPS: It stutters constantly and runs slower, but doesn't crash.

**Comment by jackerley** [comment]
Thanks @BscotchSeth that helps a lot. I have some changes that I was working on and it's nice to be able to confirm they fix this issue under these circumstances.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.703  Runtime v2024.1100.0.719

**Comment by shichen85** [comment]
> I am having this same issue ... anytime I play video it freezes the game randomly and crashes after a few seconds ... could be 3 secs, could be 10 secs ... but freezes every time. Changed frame rates from 30 up to 120fps ... made no difference. Using latest runtime.
> 
> Has this been logged as fixed ? I find the Github bug listings to be very confusing.

what platform are you having issues with?

**Comment by Heathenlamb** [comment]
> > I am having this same issue ... anytime I play video it freezes the game randomly and crashes after a few seconds ... could be 3 secs, could be 10 secs ... but freezes every time. Changed frame rates from 30 up to 120fps ... made no difference. Using latest runtime.
> > Has this been logged as fixed ? I find the Github bug listings to be very confusing.
> 
> what platform are you having issues with? And what is the runtime version?

Windows
Runtime - 2024.11.0.226

**Comment by shichen85** [comment]
> > > I am having this same issue ... anytime I play video it freezes the game randomly and crashes after a few seconds ... could be 3 secs, could be 10 secs ... but freezes every time. Changed frame rates from 30 up to 120fps ... made no difference. Using latest runtime.
> > > Has this been logged as fixed ? I find the Github bug listings to be very confusing.
> > 
> > what platform are you having issues with? And what is the runtime version?
> 
> Windows
> Runtime - 2024.11.0.226

We are not encountering the issue anymore in the latest runtime, so this ticket's sample provably does not cover your case. I would recommend you to file a new report with your replication sample and reference this ticket, if you haven't done so already.

**Comment by Heathenlamb** [comment]
> > > > I am having this same issue ... anytime I play video it freezes the game randomly and crashes after a few seconds ... could be 3 secs, could be 10 secs ... but freezes every time. Changed frame rates from 30 up to 120fps ... made no difference. Using latest runtime.
> > > > Has this been logged as fixed ? I find the Github bug listings to be very confusing.
> > > 
> > > 
> > > what platform are you having issues with? And what is the runtime version?
> > 
> > 
> > Windows
> > Runtime - 2024.11.0.226
> 
> We are not encountering the issue anymore in the latest runtime, so this ticket's sample provably does not cover your case. I would recommend you to file a new report with your replication sample and reference this ticket, if you haven't done so already.

I think it's related. If I change the game_set_speed - it prolongs the freeze and crash abut its still happens. I've lodged a new issue either way.
