### ISSUE TITLE
Code Editor 2: using the word "end" in an enum causes the formatting and autocomplete to stop functioning correctly

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8456]
### Description

Attempting to use the word end in an enum causes things like autocomplete to think it is no longer in an enum declaration. Rainbow brackets and code highlighting in general also becomes confused

![Image](https://github.com/user-attachments/assets/23c72b3e-9799-4e13-ad29-ef5237c17048)

https://api.gamemaker.io/api/github/downloads/45db4609-3d7e-4ddc-8e22-97e6667b45de

### Steps To Reproduce

1. Start GameMaker
2. Create a script
3. Add an enum
4. enter "end" without quotes as one of the enum entries
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
end is a GM keyword - you cannot use keywords in an enum

**Comment by scott-dunbar** [comment]
Only the keyword end shows this behaviour - the others should match or it should match them

![Image](https://github.com/user-attachments/assets/cb538461-a051-42bf-a4a8-79f7a3c92dd8)

**Comment by stuckie** [comment]
Closing as above
