### ISSUE TITLE
In-Game: draw_sprite() causes crash in attached project when using 2024.1100 Beta 6 with effect layer using default value

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8457]
### Description
This project was working recently on both version beta/green. Now in  IDE v2024.1100.0.688  Runtime v2024.1100.0.709 the game will show an error as soon as "new game" button is pressed. This will say "Unknown Function argument 1 invalid reference to (sprite) - request -1 max is 99". 

The tested green version is  IDE v2024.8.1.171  Runtime v2024.8.1.218

![Image](https://github.com/user-attachments/assets/e8db4bd2-f1b9-46eb-ba53-afc83c4b1ee6)

### Steps To Reproduce
1. import the attached project
2. run the project
3. press "new game"
4. The error will show

! - update -!
5. open the room "rm_menu"
6. rename the effect layer "Effect_1"
7. the project will run without error
8. rename the layer back
9. rerun the project and the error is back, this i will still happen even if the project is cleared 

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.688 Runtime v2024.1100.0.709

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[9594179e-d1ec-4dd7-8a43-c581f9de2794](https://api.gamemaker.io/api/github/downloads/9594179e-d1ec-4dd7-8a43-c581f9de2794)

**Comment by mgeddesGM** [comment]
i have checked the "rm_menu" room where there is an effects layer "EEffect_1" but this is currently set to none.

If this layer is deleted the issue i solved.

I then added a brand new effect layer with default "none" type and depth the default "0" and the issue returned.

Changing this effect to contrast, distort or desaturate has the same error.


the issue seemed to be resolved if "Effect_1" was renamed but still has the same values

**Comment by stuckie** [comment]
There is a timeline moment ( tl_unloadmenu : 30 ) that creates a large blur filter and applies it over Effect_1 in rm_menu.
This is what is causing the problem, as it has no texture sampler setup for g_NoiseTexture, so it is actually the root cause of #8362 as a null texture should be whatever the filter default is.

Investigating further as to what's changed.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.701  Runtime v2024.1100.0.719
