### ISSUE TITLE
Make "z" a keyword

### ISSUE THREAD

**Issue by Voidymite** [YoYoGames/GameMaker-Bugs#8462]
### Is your feature request related to a problem?

The pair "x, y, z" all having the same color would be more appeasing. In the context of "keyword" I moreso mean how the variables "message" and "longMessage" are—they're green like the "x" and "y" variables but do not do anything special

### Describe the solution you'd like

Turn the letter z into a keyword variable. 

### Additional context

In summary what I would like to see in the coming future is something similar to this:

![Image](https://github.com/user-attachments/assets/300f6424-78d3-47e4-ae74-834eeddcba65)

**Comment by stuckie** [comment]
'z' is not a built-in instance variable
