### ISSUE TITLE
A bad HTTP request should not trigger an ASync HTTP event

### ISSUE THREAD

**Issue by peardox** [YoYoGames/GameMaker-Bugs#8463]
### Description

In the attached example change the URL in the url to something non-sensical that can't succeed like http://fakesite.example.com/

This will show a HttpError in the console BUT we'll still get a phantom ASync - HTTP event

No event actually happened though

### Steps To Reproduce

1. Import Project
2. Run In Debug
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GMRT are you reporting this issue for?

2024.8.1.171

### Contact Us Package Attached?

- [x] I have attached my Contact Us Package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by peardox** [comment]
Forgot package
[com.peardox.wsock.zip](https://github.com/user-attachments/files/17827502/com.peardox.wsock.zip)

Also...

Contact Us Package Attached?
This .zip file is essential for all bug reports. Please build your project, so that you have a compiler log inside GameMaker, then open the Help menu inside GameMaker and run the "Create Your Contact Us Package" tool. Attach the .zip file GameMaker makes for you to this report (or upload it somewhere you trust and put the download link into your Description text - make sure the file is shared!).

Help menu has no such option...

**Comment by jackerley** [comment]
The http request creates an async event with a status of -1 which indicates failure. It is necessary so that you can know when your http request fails and allows you to deal with it by retrying or however you wish to deal with it.
