### ISSUE TITLE
Install: [Mac IDE] Installing puts the old version's .app in the trash with a "copy" label appended, should use the version number instead

### ISSUE THREAD

**Issue by yerumaku** [YoYoGames/GameMaker-Bugs#8467]
### Description

There is a problem when installing the Beta version, with each installation a file is placed in the trash and is not cleared from it.

![Image](https://github.com/user-attachments/assets/e9c2e267-1ad8-4e04-ba6d-bb769bd56f7f)

### Steps To Reproduce

1. Download GameMaker
2. Install GameMaker
3. Reinstall GameMaker
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sequoia

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
The mac way is to clean out your trash every so often... you do empty your trash don't you??

If mac requires disk space it will prompt you to empty the trash yourself - in extreme circumstances it may well scavenge space from the trash can

**Comment by rwkay** [comment]
Fixed in 2024.11 - I have removed the copy of the old app to the trashcan completely - not sure exactly why we did that.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.701  Runtime v2024.1100.0.719
