### ISSUE TITLE
video_get_status always returns video_status_preparing

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#8474]
### Description
Updating the engine from 2024.2
Video playback doesn't seem to work anymore. I'm pretty much using the exemple code for video playback in the manual (Draw Gui event for obj_sceneManager starting at line 13.
The video_get_status() calls always return video_status_preparing so nothing gets drawn to the surface.

### Steps To Reproduce
1. Select DevMode as config and add attached save file in "C:\Users\[user]\AppData\Local\Chronique_des_Silencieux" to save time.
2. Launch game and CTRL+MAJ+C to bring up console
3. Type "movie_play blancheEnquete", it should normally play the included file "movies>blancheEnquete.mp4"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

### Attached Files
* Chapter 0.sav

[ca066926-6a6d-4b2d-8836-43191d4dbd6c](https://api.gamemaker.io/api/github/downloads/ca066926-6a6d-4b2d-8836-43191d4dbd6c)

**Comment by jackerley** [comment]
Unfortunately not related. I have put a fix in and I'll include a simpler sample for QA to reproduce in - Note for QA - video should play automatically in the enclosed project, it will stick with a status of 1 in current runtime and not play the video.

https://drive.google.com/file/d/189t9ihk7OqJuWueDTOtDQjDUV88drrjb/view?usp=sharing

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.703  Runtime v2024.1100.0.719
