### ISSUE TITLE
Code Editor 2 - Allow more than one object to be open at a time when splitting the code view.

### ISSUE THREAD

**Issue by Manukineko** [YoYoGames/GameMaker-Bugs#8484]
### Is your feature request related to a problem?

When I drag the split view icon, I can't have two different code asset displayed side-by-side.
![Image](https://github.com/user-attachments/assets/6cc017b9-853a-416b-a566-1164c175ba1c)

### Describe the solution you'd like

Basically, I would like to be able to assign a code asset to one of the side view I created when draging the split view icon, or the option to split the editor view in 2 columns with the righ-click menu like the old Code Editor.

**Comment by stuckie** [comment]
This is not currently planned.
The split is for views within that file only.

**Comment by attic-stuff** [comment]
> This is not currently planned. The split is for views within that file only.

this functionality exists in the current code editor, and is how it works in many very cool and well loved ides, and not having an equivalent behavior in code editor 2 is a huge step back. how is there no plan to add this?

**Comment by Manukineko** [comment]
> This is not currently planned. The split is for views within that file only.

So is there another solution planned in the future ? I've been told it would probably be resolved with the next Windows Paradigm feature, but it has been push back to YoYo only knows.
