### ISSUE TITLE
Help Pages/Tutorials: How To Make/Upload Mods to GX.games needs to be updated

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#8492]
### Description

The help pages to create and upload mods to GX.games need to be edited as well to reflect the recent changes made at the https://dev.gx.games/mods page.

https://help.gamemaker.io/hc/en-us/articles/14637974730653-How-To-Create-Game-Strips-With-GameMaker 

https://help.gamemaker.io/hc/en-us/articles/10070287968285-How-To-Make-Live-Wallpapers-With-GameMaker

**Comment by gurpreetsinghmatharoo** [comment]
Both should be good now
