### ISSUE TITLE
In-Game: #7913 regressed

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8514]
### Description
I am seeing the exact issue from #7913 in the latest public beta, it appears it got un-fixed at some point. Correct results on YYC, incorrect results on VM, same as the previous report. I'm doing a new report since comments on closed + verified issues often don't get seen, feel free to close this one if the previous one is reopened.

### Steps To Reproduce
See #7913

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[b5ec68a8-6355-4833-804f-780a7ed916f5](https://api.gamemaker.io/api/github/downloads/b5ec68a8-6355-4833-804f-780a7ed916f5)

**Comment by rwkay** [comment]
We added in the Deprecated behaviours section on the Main options - and because this was not a new project the Legacy Other Behaviour was enabled

![Image](https://github.com/user-attachments/assets/e45622b0-8643-4d5a-9895-1fe6dcec1e55)

If that is disabled then everything works as it should

**Comment by KormexGit** [comment]
In that case, it is likely that the legacy behavior is not applying to YYC

**Comment by rwkay** [comment]
I have just checked and there is indeed a regression when `Legacy other behaviour` is on in VM.
