### ISSUE TITLE
Restore the IDE window's last position and resolution on start up

### ISSUE THREAD

**Issue by Retrific** [YoYoGames/GameMaker-Bugs#8516]
### Is your feature request related to a problem?

I got a new screen where I dont want to use GM at fullscreen. But for some reason the IDE always open up in fullscreen, spanning across the entire screen, which is very annoying for me, because I have to then manually resize the window to my desired resolution and location.

Other software, like Steam, Spotify or Google Chrome know exactly where I had them positioned and at what size and after shutdown and restart open up the exactly how they were when I closed them. This is very comfortable and something that I also wish Game Maker was capable of.

### Describe the solution you'd like

Save Game Maker's IDE resolution and position on screen and restore it when Game Maker starts instead of opening up spanning across the entire screen.

### Additional context

It would also be cool to be able to disable the IDE's window's border (optionally) and integrate the close/fullscreen buttons into the top bar where File, Edit etc. is insead - So that I can use more of my vertical screen space. But I understand that this would be quite a big change so it's just something I'd like to put out there as a sidenote.

**Comment by Grisgram** [comment]
duplicate of #7810 ?

**Comment by Retrific** [comment]
Yes true thats a duplicate.
I guess we wont see this fixed any time soon :(
