### ISSUE TITLE
Audio Groups not loading in specific circumstances

### ISSUE THREAD

**Issue by Lukanibal** [YoYoGames/GameMaker-Bugs#8518]
### Description
I have a game that works in the current Monthly just fine, but in the Beta the audio groups do not load and throw an error saying the audio groups don't exist.

### Steps To Reproduce
I have included a demo, simply run it via the IDE with GX.Games(VM or YYC) targeted, click the mouse to play a sound and the project will error.

Alternatively:
Add an audio group to a project
Add sounds to audio group
Try to load audio group on GX.Games

You can see in the code that these audio groups should be loaded.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Which platform(s) are you seeing the problem on?
GX.games

[f2791e23-5bf0-4cde-bf7f-e78cc7d33917](https://api.gamemaker.io/api/github/downloads/f2791e23-5bf0-4cde-bf7f-e78cc7d33917)

**Comment by toby-yoyo** [comment]
- Fixed an issue where audio groups that were removed during compilation were offsetting group indices at runtime.
- Fixed an issue where audio and texture groups could be removed during compilation even if the unused asset removal option was turned off.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.708  Runtime v2024.1100.0.725
