### ISSUE TITLE
Sequence Editor: Cannot rename track in track panel

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#852]
GM-7994

When a user tries to rename a track within the sequence editor's track panel, the name will change back to the original name once the user is done renaming. A track rename will only stay present if done in the inspector.

 !GameMaker-Beta_7e4j5tGyTg.gif! 

*Expected*
It is expected that if the user selects 'Rename' for a track that the track will be renamed with their input, and not reset back to the original name.

*Steps*
- Open attached project
- Open Sequences folder in Asset Browser
- Select seq_menu
- Right mouse click on one of the tracks
- Choose 'Rename'
- Rename track to "Test"
- Press Enter
- Observe that name has reset to the original name
Repro: 100%

**Comment by ParodyKnaveBob** [comment]
Has this been silently fixed?

In monthly 2023.8.2.106, I can rename a track from within the sequence editor (using context menu or F2) with no problem.

**Comment by YYDan** [comment]
Yeah, can see this is an unwanted export from the old DB, as it was already fixed for August as you say.

It's in the release notes:
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/8bad6515-3ab7-41a8-beca-8343414a6637)
