### ISSUE TITLE
Feather - Looses correct context on methods used within creating a function

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#853]
GM-7988

A user has found that Feather is loosing context when a method is used within creating a function in a script.

Steps
- import the project with feather enabled
- open the object oCoGabi
- go to line 34
- hover over "animations" notice feather says it is a struct
- hover over "current()", notice feather will say it is a function returning the prior mentioned struct
- repeat for line 39, notice animations is var type Any* and current() is Any
- this can also be seen in the gif

**Comment by YYDan** [comment]
Duplicate of #910
