### ISSUE TITLE
In-Game: surface_free() gives an exception when passed "undefined", should allow this

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8532]
### Description
If you do 
```
surf = -1;
//clean up
surface_free(surf);
```
It will do nothing. If you instead do
```
surf = undefined;
//clean up
surface_free(surf);
``` 
It gives an exception. 
It was recently changed so that the various _exists functions would do nothing when passed undefined, so that undefined can be used as a default value for more things. It feels like surface_free should also work this way, so that undefined can be the ideal default value for variables that might hold a surface instead of -1 still being advantageous.

### Steps To Reproduce
```
surf = -1;
surface_free(surf); //no crash

surf = undefined;
surface_free(surf); //crash
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.686 Runtime v2024.1100.0.707

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[ec11587e-e905-4cc1-b86e-871741ee6ecf](https://api.gamemaker.io/api/github/downloads/ec11587e-e905-4cc1-b86e-871741ee6ecf)

**Comment by DiasFranciscoA** [comment]
This will be changed for both current runner and GMRT:

- [ ] Current Runner, https://github.com/YoYoGames/GMS2-Runner-Main/pull/267
- [ ] GMRT

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.896  Runtime v9.9.1.1041
