### ISSUE TITLE
Manual: Image Editor Preferences - Tool section missing details for color select section

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8534]
### Description

in the IDE  IDE v2024.1100.0.699  Runtime v2024.1100.0.717's preferences the number of colour swatches can be set between 78-256. The relevant manual page is missing any reference to this section and any input limitations.

The screenshot needs to be updated as well

This is what is currently in the IDE
![Image](https://github.com/user-attachments/assets/9cc9b3ce-432c-4f6a-a4c5-0e62f2f30283)

### Manual Link

https://manual.gamemaker.io/beta/en/#t=Setting_Up_And_Version_Information%2FIDE_Preferences%2FImage_Editor_Preferences.htm&rhsearch=prefrences%20image%20editor&rhhlterm=prefrences%20image%20editor

**Comment by YYBartT** [comment]
Updated the screenshot and added the preference, including its limitations.
