### ISSUE TITLE
Docs Integration: Help > Required SDKs menubar option link/redirect breaks when using Firefox as default browser

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#8536]
### Description

When selecting Required SDKs under the Help menu, a broken page will be displayed of the user is using Firefox.
![Image](https://github.com/user-attachments/assets/cb12cf7d-deb4-4a69-8da9-6ceba6d83728)

Tested using IDE v2024.1100.0.699  Runtime v2024.1100.0.717

[Sample Package](https://api.gamemaker.io/api/github/downloads/9b1e193b-043f-4ff7-948d-fe9c3cf7be35)

### Steps To Reproduce

1. Start GameMaker
2. Open Help > Required SDKs
3. See the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Okay, so the issue is actually that Firefox won't follow the redirect because the originating protocol is http, not https as it ends up.

We should just change the link inside the IDE to be "https://help.gamemaker.io/hc/en-us/articles/227860547" and avoid the protocol issue and the redirect going forward.

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.1100.0.702  Runtime v2024.1100.0.719
