### ISSUE TITLE
Feather: Issues with automatic type deduction of functions and their inner static functions

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#856]
### Description

Calling a function in a single object will permanently make the @context/@self binding that of the object which called it. This also gets applied to any and all functions that are inside of the function that is bound. What makes this peculiar is that if you explicitly define a context on this inner function, is that it still is interpreted as having the context of the outer function it is declared in. The only way to "fix" this is to declare a context for the top level function, but this then makes it show up as having no bound context as if the function were being called in multiple objects already. When not using the 'fix' this issue sometimes leads to a GM1013 error as the variable hasn't been declared in the context it believes it belongs to...but this then leads to odd behaviour which only appears to occur intermittently.

Sometimes, just modifying the offending file where the function exists causes the GM1013 to erroneously disappear. It won't reappear until you turn feather off/on or strict mode off/on. I have managed to reproduce this fairly reliably on my system so I will include a project also demonstrating this behaviour.

Sometimes, the error won't appear at all even though the @context of the function says it is something which definitely does not have the offending error. I have not managed to reliably figure out how to reproduce this behaviour... but based on the fact the first issue occurs based on project state when the project first opens, it may be related to that somehow.

### Steps To Reproduce

I am including a project that demonstrates the modifying of the file causing the error to disappear, as I have reliably figured out how to replicate that aspect on my end; it appears that how feather behaves is linked to the initial project state when you OPEN that project. So in the project I have a call to a function in an object, and extracting a static function of that function to bind as a method immediately after. This leads to the error disappearing the moment you modify the function, and reappearing when you turn feather back on. Do note, that if you remove the second line in the object's create event, this behaviour doesn't occur when you first launch the project on my system.

1. Start GM and load attached project
2. Observe Function in Script

[Feather Scoping Bug.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/12866843/Feather.Scoping.Bug.zip)

**Comment by mgeddesGM** [comment]
verifying as not able to replicate as of  IDE v2023.1100.0.418  Runtime v2023.1100.0.438
