### ISSUE TITLE
When passing a layer that doesn't exist to instance_create_layer, passing a string gives an exception, while passing a layer id does not

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8570]
### Description
If you do this `instance_create_layer(x, y, "a", Object2);` when no layer canlled "a" exists, you will get an exception, "instance_create_layer :: specified layer "a" does not exist".
However, if you instead do this
```
instance_create_layer(x, y, layer_get_id("a"), Object2);
```
It does NOT give an exeption. A "Specified layer does not exist" message is printed in output, and the instance is not created. The same thing happens if you do `instance_create_layer(x, y, layer, Object2);` when the object running the code has had it's depth changed so it is no longer on a layer.

The existing output message isn't very helpful since it doesn't say what line it came from, and having instance_create_layer straight up not create an instance at all can lead to a frustrating debugging process. I think that, same as passing a string for an invalid layer, passing an invalid layer id should also give an exception.

If making it a full exception isn't feasible for whatever reason, then it'd be nice if the output message was at least more descriptive. Even if it just said that the error came from instance_create_layer and not some other function that'd be an improvement.

### Steps To Reproduce
```
//create
depth = 123;

//step
instance_create_layer(x, y, layer_get_id("a"), Object2); //doesn't crash, probably should
instance_create_layer(x, y, layer, Object2); //doesn't crash, probably should
instance_create_layer(x, y, "a", Object2); //crashes
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.700 Runtime v2024.1100.0.718

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[3eaad729-d27f-4a1f-82f7-1ae00d668314](https://api.gamemaker.io/api/github/downloads/3eaad729-d27f-4a1f-82f7-1ae00d668314)

**Comment by mgeddesGM** [comment]
verified as of  IDE v9.9.1.896  Runtime v9.9.1.1041
