### ISSUE TITLE
Manual Content: surface_reset_target() page wording could be made more accurate

### ISSUE THREAD

**Issue by Bearman18** [YoYoGames/GameMaker-Bugs#8573]
### Description

The entry states that "This function resets all further drawing from the target surface back to the screen."
More accurately, surface_reset_target resets the target surface to either the last target set with surface_set_target, or to the application surface.
The [surface_set_target](https://manual.gamemaker.io/lts/en/GameMaker_Language/GML_Reference/Drawing/Surfaces/surface_set_target.htm#h) entry defines this behavior correctly.

### Manual Link

https://manual.gamemaker.io/lts/en/GameMaker_Language/GML_Reference/Drawing/Surfaces/surface_reset_target.htm

**Comment by YYBartT** [comment]
Clarified that `surface_reset_target()` resets to the "previous" draw target and listed the possible options. Also added a new section "Draw Targets" on the Drawing page, listing all possible draw targets in greater detail.

**Comment by mgeddesGM** [comment]
verified
