### ISSUE TITLE
Licensing: "Forgotten Password" on Legacy Account dialog opens a 404 page in your browser

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#8588]
### Description

Clicking on the link "forgotten password" from the legacy sign in dialog opens the following webpage: https://accounts.yoyogames.com/reset 

and the page is empty. Please see the screenshot below. 
![Image](https://github.com/user-attachments/assets/792f2ce7-0c68-4bb9-bb10-21a6b001f521)

### Expected Change

The link the IDE tries to open is changed to be https://id.gamemaker.io/account

Note that this will not take users directly to the same password reset page as before, as the site no longer supports that. They will hjave to click Legacy and "Forgotten Password" themselves.

### Steps To Reproduce

1. Start GameMaker
2. Open the legacy Sign in dialog 
3. Click on "Forgotten Password?"
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly), 2022.0.3 (LTS), 2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
LTS IDE 85 is fixed now - 

![Image](https://github.com/user-attachments/assets/7c86e9c4-a780-4e18-9761-e5bd76ab720a)

**Comment by mgeddesGM** [comment]
verified in https://github.com/YoYoGames/GameMaker-Bugs/issues/8619
