### ISSUE TITLE
Start Page: Carousel shows moving images at side of banner on larger screens

### ISSUE THREAD

**Issue by mgeddesGM** [YoYoGames/GameMaker-Bugs#8606]
### Description
If a user views the start page banner on larger screen then there is a strip of moving image on both sides of the banner

### Steps To Reproduce
1. open the IDE using a screen that is larger than 16 inches*
2. watch the banner rotate
3. there will be a strip at either side of the main image
4. these strips will be moving

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.702 Runtime v2024.1100.0.719

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files
* Start Page - GameMaker-Beta 2024-12-03 16-11-22.mp4

[d9c3814c-e8c3-4b8c-85f7-c579617f29fc](https://api.gamemaker.io/api/github/downloads/d9c3814c-e8c3-4b8c-85f7-c579617f29fc)

**Comment by YYDan** [comment]
Probably cos we load and show 3 images always (even though there are apparently only 2 carousel items available right now) - on my 4K I get 3 full images and they are occasionally scrolled to all take a turn being the middle one.

**Comment by stuckie** [comment]
Closing in favour of new start page.
