### ISSUE TITLE
In-Game: Using a filter/effect on an instances layer makes its instances draw in GUI space

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#8613]
### Description
If I have an instance drawing a surface to the regular draw event at that instances x and y, it draws fine. However, if I enable a filter/effect on that instances layer, the surface/instance begins drawing the surface, and itself, to gui space, even if the instance doesn't have a draw gui event.

How it looks normally drawn:
![Image](https://github.com/user-attachments/assets/ce787130-493b-4d6c-a7aa-e62afea50453)

How it looks with a filter/effect on it:
![Image](https://github.com/user-attachments/assets/23f788ba-08d5-4252-b7bd-642ed33693d7)

### Steps To Reproduce
- Run the included project
- Observe that the instance in Room1 on the "No_Effect" layer runs correctly.
- Hide the "No Effect" layer, and make the "With_Effect" layer visible in the room. This layer has the exact same instance as the other layer, only it has the "Old Film" effect enabled.
- Observe it is now in gui space, and drawing in the wrong place (top left)
- If you add draw_self() to the draw_regioned_sign() method at the very end, it will also draw the assigned instances sprite in gui space.
- You can add draw_self() to a draw_gui event to confirm this as well, as it will draw in the exact same spot.
- The final layer called "Billboards", is what has to be done to make it work with the effect on, by converting regular coordinates to gui coordinates, and scaling the surface by 4.

P.S: This happens in both monthly and latest beta.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.700 Runtime v2024.1100.0.718

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[e6ceac2f-333f-4ff8-ab5d-4de053046153](https://api.gamemaker.io/api/github/downloads/e6ceac2f-333f-4ff8-ab5d-4de053046153)

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.1300.0.717  Runtime v2024.1300.0.729
