### ISSUE TITLE
[HTML5] Issue with struct key named "image_index" persists in latest Beta

### ISSUE THREAD

**Issue by biyectivo** [YoYoGames/GameMaker-Bugs#8617]
### Description
Please refer to previous different tickets, e.g.:

https://github.com/YoYoGames/GameMaker-Bugs/issues/8338
https://github.com/YoYoGames/GameMaker-Bugs/issues/5968
https://github.com/YoYoGames/GameMaker-Bugs/issues/4874
https://github.com/YoYoGames/GameMaker-Bugs/issues/4488

The issue is that a variable named `image_index` in a struct will cause the build to fail in HTML5.

The detail is that, in previous versions of the issue, apparently having the obfuscator ON was causing the problem (see Russell Kay's comments on issue #5968:  https://github.com/YoYoGames/GameMaker-Bugs/issues/5968#issuecomment-2147852488)

However, it now appears that the issue pops up when the obfuscator is OFF - if I turn the obfuscator ON, it does not crash and reports the correct value.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.700 Runtime v2024.1100.0.718

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Which platform(s) are you seeing the problem on?
HTML5

[9802d27c-a845-447d-9fcc-07a75bd2c7f8](https://api.gamemaker.io/api/github/downloads/9802d27c-a845-447d-9fcc-07a75bd2c7f8)

**Comment by Grisgram** [comment]
Please please please make sure, when you fix this, that BOTH scenarios can be verified afterwards (with and without obfuscator), to avoid the pingpong effect (you fix this and then the obfuscator bug comes back)

**Comment by rwkay** [comment]
Fixed in 2024.13

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727
