### ISSUE TITLE
Manual Content: ini_close() and ini_open() pages do not document current behaviours for when errors will be shown

### ISSUE THREAD

**Issue by misternebula** [YoYoGames/GameMaker-Bugs#8642]
### ini_open
Docs state:
> Please note that you can only have one ini file open at any one time and remember to use ini_close() once you're finished reading/writing from the .ini file

However, it does not mention that calling ini_open() without calling ini_close() will automatically call ini_close() first, as shown in the HTML runner: https://github.com/YoYoGames/GameMaker-HTML5/blob/be30ece4abbde24d6bfc5deb679d9ce3b64f094c/scripts/functions/Function_ini.js#L55-L58
This means the ini file is saved correctly either way.

### ini_close
Docs state:
> If you try to open an ini without having previously closed another one (or the same one) you will get an error too.

In the HTML runner (and I'm pretty sure the C++ runner, but I will have to double check), ini_close() actually just does nothing when called with no open ini file, and does not throw an error:
https://github.com/YoYoGames/GameMaker-HTML5/blob/be30ece4abbde24d6bfc5deb679d9ce3b64f094c/scripts/functions/Function_ini.js#L83

### Manual Link

https://manual.gamemaker.io/beta/en/GameMaker_Language/GML_Reference/File_Handling/Ini_Files/Ini_Files.htm

**Comment by YYBartT** [comment]
Clarified the behaviour of `ini_open()` and `ini_close()` and updated the related manual pages a bit.

**Comment by mgeddesGM** [comment]
verified
