### ISSUE TITLE
Feather: move_and_collide() throws incorrect error if "undefined" passed as arguments

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#8643]
### Description

Right now feather complains about undefined arguments being passed into `move_and_collide` it shouldn't and this function is actually used in official YouTube video tutorials it would be nice if the warning didn't show.

### Steps To Reproduce

1. Start GameMaker
2. Try use `move_and_collide` and pass `um_iterations` and `x/yoff` the undefiend value.
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.710  Runtime v2024.1100.0.726
