### ISSUE TITLE
Building Projects: [Ubuntu] Can't compile my game as an .AppImage file, due to unshare error on opt/steam-runtime folder

### ISSUE THREAD

**Issue by Paulprojects8711** [YoYoGames/GameMaker-Bugs#8644]
### Description

When I am trying to compile my game for Ubuntu this happens: 
ERROR: Could not find icon executable for Icon entry: Shadow_Dash_Demo 
System.Exception: command 'unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin"  chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'  -- GameMakerStudio2/yyc/Shadow_Dash_Demo /opt/steam-runtime' failed with exit status 1
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.BuildAppImage(String work_dir, String exe_path, String assets_zip_path, String projectName, Boolean package)
   at Igor.LinuxBuilder.Package()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Igor complete.
elapsed time 00:01:48.9721810s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Paul_Juranitsch\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Linux Package started at 12/09/2024 16:52:07
FAILED: Package Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

Here is my Bug Sample: https://api.gamemaker.io/api/github/downloads/91b02ba8-5c91-4da4-ac20-e7d0b468b42b

### Steps To Reproduce

1. Start GameMaker
2. Try to create executable for Ubuntu
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

Yes

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Hello @Paulprojects8711,

thank you for reaching out to us. We are currently looking at your bug report and we are trying to replicate it locally.

We would request you though to try and update the IDE to version 2024.11 and make a change in the Device Editor panel, change the install folder to be the default one:

```
~/GameMakerStudio2
```

as displayed in the image below:

![Image](https://github.com/user-attachments/assets/24feedb3-efad-448d-9322-50be917a9a75)

Also make sure to **test the connection** and **clean the project** before rebuild.
Let us know if this solves the issue, or what is the new error.

**Comment by Paulprojects8711** [comment]
thank you, this fixed it, turns out that the install folder was set without the ~/ before it
