### ISSUE TITLE
Marketplace Website: Error when trying to add any assets to your account

### ISSUE THREAD

**Issue by AprendeGM** [YoYoGames/GameMaker-Bugs#8645]
### Description
Error in Marketplace, any asset.

### Steps To Reproduce
Click Button (Add to Account (Free))

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.1.171 Runtime v2024.8.1.218

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Attached Files
* Captura.PNG

[c65076b1-d75a-43c7-a7fa-af43ca3bd3f1](https://api.gamemaker.io/api/github/downloads/c65076b1-d75a-43c7-a7fa-af43ca3bd3f1)

**Comment by YYDan** [comment]
Our Web team are looking into this just now, as it's an issue on the website, not a GameMaker bug.

**Comment by Kev-Brown** [comment]
A web fix has been released for this issue
