### ISSUE TITLE
Can't run my game on phone

### ISSUE THREAD

**Issue by Paulprojects8711** [YoYoGames/GameMaker-Bugs#8668]
### Description

When I try running my game on my phone I get this error: Error : The selected Architecture options do not support this device. Please add x86_64
https://api.gamemaker.io/api/github/downloads/64a779e5-db05-4734-9d87-05440a4b2fe0

### Steps To Reproduce

1. Start GameMaker
2. Press run with the Android export option selected
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Android

### Are you running GameMaker from inside your Steam library?

Yes

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by iampremo** [comment]
Have you ensured that the Build for x86_64 option is check in game options?

https://manual.gamemaker.io/lts/en/Settings/Game_Options/Android.htm

**Comment by Paulprojects8711** [comment]
sorry, i just did that and it works now. 🤦‍♂️
