### ISSUE TITLE
New updater is not visible in taskbar

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8678]
### Description

Same as initial steps of normal Installer (at point where it says that GM is already installed and if you want to unistall it), when new Updater runs, it's not visible in taskbar, so any app would cover it and only way to get back to it is to either Alt+Tab, or minimize apps one by one.

![Image](https://github.com/user-attachments/assets/32db99b6-f97c-4234-b495-9ad09d720b17)

That's low priority suggestion of course :)

### Steps To Reproduce

1. Update GameMaker on Windows using new updater (restart)
2. Open any other app
3. Notice that it's hard to see in taskbar that it's actually updating

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

**Comment by gnysek** [comment]
Connected to #2184 (for normal installer).

**Comment by rwkay** [comment]
This is intentional - we do not want the new updater to appear on the taskbar...

**Comment by stuckie** [comment]
Closing as above
