### ISSUE TITLE
Installing Runtime taking forever

### ISSUE THREAD

**Issue by st4rdog** [YoYoGames/GameMaker-Bugs#8693]
### Description

IDE v2024.8.1.171

It says Installing in the top-right for a long time. The bar moves very slowly and eventually stops 75% of the way through.

Already downloaded runtime manually from website and put into runtime-2024.8.1.218\download folder. Didn't speed anything up.

It keeps building this other large file (51d67e8d-1770-4b2d-af36-8921e1d328d4.zip) which is currently 215mb+ and counting.

If you close IDE and restart. It will continue adding to this file size. The progress bar restarts at zero.

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
We will need the ui.log to see what is going on here as there are several reasons that this could be stalled.
