### ISSUE TITLE
Manual Content: Flexpanel needs note that reusing structs when creating nodes will modify the original struct rather than the flexpanel

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#8708]
### Description
If you create a flexpanel node from a variable that contains a struct, then edit the node, the original struct will have those changes.

The new node seems to use the struct to store its data so all nodes will use the same.

### Steps To Reproduce
Debug sample
Notice that the 3 panels say "something else 3"
Pause debugger
Inspect "template_struct"
Notice that the data.text value is "something else 3"

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.711 Runtime v2024.1100.0.726

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[7b2df5ed-f41d-403a-be6d-a473c57f2ded](https://api.gamemaker.io/api/github/downloads/7b2df5ed-f41d-403a-be6d-a473c57f2ded)

**Comment by rwkay** [comment]
This is not a bug in the engine but you need to ensure that the data struct from your template is unique for each node that is created from it - as it stands they will all  point at the same struct.

you need to add this line after your `flexpanel_create_node` call

```
	flexpanel_node_set_data( _new_node, variable_clone( flexpanel_node_get_data(_new_node) ) );
```

**Comment by YYDan** [comment]
We'll verify the manual changes.

**Comment by YYDan** [comment]
Can see that the manual change documents the problem and the correct workaround to add into your code. All seems correct to me.

Verifying.
