### ISSUE TITLE
[macOS] build fails when using YYC export

### ISSUE THREAD

**Issue by Dragonboi1324** [YoYoGames/GameMaker-Bugs#8715]
### Description

build fails whenever I use the macOS YYC export, even in blank games (VM works fine)

the error should be in the bug package
https://api.gamemaker.io/api/github/downloads/a813f8b5-a27d-4e05-8dcc-b8737b86be44

I have already tried reinstalling GameMaker following the guide but it didn't help

### Steps To Reproduce

change the export to GMS2 YYC and run

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
From your included output log it looks like Xcode is failing on your Mac. Can you try opening the generated Xcode project on your Mac and try running directly from there? The Xcode project has been generated at /Users/stupidbobo/gamemakerstudio2/GM_MAC/BLANK_GAME/BLANK_GAME on your Mac. This should at least give some indication of what the error is.

**Comment by Dragonboi1324** [comment]
I ran it through the Xcode project and it seems to run completely fine.
