### ISSUE TITLE
In-Game: Crash when running in debug mode if removal of unused is assets enabled on attached project

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-Bugs#8736]
### Description
The game isn't starting at all and yields an accesss violation `Runner.exe exited with non-zero status (-1073741819)` error.

Running in the normal run is working. Running as YYC is working.

I thought that that may be related to removed resources actually being used in the code but referenced unusually, like in my #8735, but it seems that there's something more to it as I added all of the potentially removable assets in `KEEP_ASSETS` script but it's still not running. The list of removable assets was obtained from the log info of the automatic removal process, maybe it is not full and something more is being removed.

**Another interesting observation**: just closing the game even in the working run (in non-Debug mode or with automatic removal disabled) is also causing the Runner to crash with the same -1073741819 status. It's not influencing the gameplay experience as it happens right on a program end but still concerning as other projects seem to end normally. Not sure if it is a related issue or I should report another one.

### Steps To Reproduce
1. Open the attached project
2. Make sure that the `Automatically remove unused assets when compiling` option is enabled
3. Run in Debug mode
4. Experience the crash

### Which version of GameMaker are you reporting this issue for?
IDE v2024.11.0.179 Runtime v2024.11.0.226

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[4d3f5a5a-7313-406f-8402-60d6f27c8260](https://api.gamemaker.io/api/github/downloads/4d3f5a5a-7313-406f-8402-60d6f27c8260)

**Comment by rwkay** [comment]
Unable to replicate on 2024.13 HEAD after https://github.com/YoYoGames/GameMaker/pull/4611 was merged
