### ISSUE TITLE
Instance variable definition in instances can reset when reloading assets modified externally

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#875]
GM-7647

When an object with a variable definition is being used in a room, and that variable is being modified in the inspector for instances in the room, if the user changes the .yy file of the object and then clicks on "Reload" on the Project Directory Modified dialog, the variable definition is reset in the inspector for the instances but the change is not reflected in game. 

Please note that this only happens if the instance in question is NOT open in the inspector and it does not happen if the user clicks on "Save" instead of "Reload" in the Project Directory Modified dialog. 

*Steps to reproduce*
- Import the project attached
- Open the Room Editor
- Open the Instance of the Object in the Inspector
- Change the variable definition
- Select anything else in the room to change the focus of the inspector
- Open the Object's .yy file in an external editor
- Make a change to the file in the external editor
- In the IDE, click on "Reload" on the Project Directory Modified dialog
- Select the instance of the object again in the inspector
- Observe that the value of the variable has been reset to the original value in the object

**Comment by yyalansavage** [comment]
This occurs because - when GMObject is reloaded, all its GMObjectProperty are recreated as new objects; all room instances are still referencing the original GMObjectProperty, and so fail to find on the updated GMObject.
