### ISSUE TITLE
Cannot index anonymous arrays

### ISSUE THREAD

**Issue by python-b5** [YoYoGames/GameMaker-Bugs#8759]
### Description

When trying to create an array and index from it in the same expression, the index appears to be ignored (so, `[a, b, c][i]` compiles as if it were `[a, b, c]`). The index does not seem to be evaluated at all. Using parentheses, like `([a, b, c])[i]`, causes the same behavior, though if that code is placed inside a function call it will refuse to compile entirely. This behavior is new since 2024.8.

https://api.gamemaker.io/api/github/downloads/3f4e351d-6b15-49a4-a8de-41ba6b160dc5

### Expected Change

The behavior should be the same as it was in previous versions.

### Steps To Reproduce

1. Start GameMaker
2. Attempt to index from an anonymous array (so something like `show_debug_message([1, 2, 3][1])`)
4. Notice that the full array is printed instead of the number `2`, as expected

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by stuckie** [comment]
This should be fixed as part of #8746
