### ISSUE TITLE
Xbox Wireless: gp_shoulderrb not detectable, but affects gp_shoulderlb

### ISSUE THREAD

**Issue by Zyl9393** [YoYoGames/GameMaker-Bugs#8762]
### Description

The following ill behavior is present when using [Xbox Wireless Controller Carbon Black](https://www.amazon.de/dp/B07SDFLVKD) with Runtime v2024.11.0.226 via [TP-Link UB500 Plus Mini](https://www.amazon.de/dp/B0DFPZSVYC).

Functions `gamepad_button_check()`, `gamepad_button_check_pressed()` and `gamepad_button_check_released()` always return `false` for `gp_shoulderrb`.
For `gp_shoulderlb` the function `gamepad_button_check()` always returns `true`, unless `gp_shoulderrb` is held. When first pressing `gp_shoulderrb`, `gamepad_button_check_released()` returns `true` for `gp_shoulderlb`. `gamepad_button_check_pressed()` returns `true` for `gp_shoulderlb` when releasing `gp_shoulderrb`.

Upon further inspection, connecting the gamepad in the manner specified causes GameMaker to detect two gamepads. First with index `0`, GUID `none` and description `XInput STANDARD GAMEPAD` works fine. Second with index `4`, GUID `030000005e040000130b000000000000` and description `Xbox Series Controller` has the issue detailed above.

### Expected Change

Report no more than exactly one functioning gamepad via Async System events and `is_gamepad_connected()` per connected physical gamepad.

### Steps To Reproduce

1. Start GameMaker
2. Open [attached project](https://github.com/user-attachments/files/18188807/debug_gamepad.zip). (Upload from within IDE currently fails with 401 Unauthorized despite being logged in)
3. Connect specified gamepad using specified BlueTooth adapter.
4. Disconnect any other gamepads.
5. Launch project.
6. Observe Gamepad causing to re-register with device index 4, replacing 0.
7. Observe failure to register any input from `gp_shoulderrb`.
8. Observe `gp_shoulderrb` affecting behavior of input detection from `gp_shoulderlb`.
9. Press spacebar to re-detect gamepad. (It will choose the one with smallest index, i.e. go from ID 4 to ID 0)
10. Input works correctly, but as developer, I have no way to help the player figure this out.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0.226 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.13 as the second entry has been removed from the list of gamepads...

**Comment by Zyl9393** [comment]
@rwkay Ok. Where may I check next time? I'd like to avoid obsolete reports as well.

**Comment by rwkay** [comment]
you will be able to check the 2024.13 Beta which will be released early in Jan 2025

**Comment by cameron-home** [comment]
@rwkay Do you have the project for this?

**Comment by rwkay** [comment]
> [@rwkay](https://github.com/rwkay) Do you have the project for this?

It is linked in step 2 - I have sent it to you on Slack

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.13.0.190  Runtime v2024.13.0.238
