### ISSUE TITLE
In-Game: string(self) returns "-1"

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8770]
### Description
If you do this `show_debug_message(self)` it will show you a struct with the instance's variables. But if you instead do this `show_debug_message("String self: " + string(self))` it gives you "String self: -1". This means self doesn't print out in any kind of useful way if you want to also include some other string content in your debug message.

In GMRT it also gives you different results when stringed, but instead of "-1" you get "[[GMInstance]]"

### Steps To Reproduce
```
show_debug_message(self);
show_debug_message("String self: " + string(self));
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.713 Runtime v2024.1100.0.726

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[6f18b3f3-8c2d-4b1d-adfd-2b7c98667086](https://api.gamemaker.io/api/github/downloads/6f18b3f3-8c2d-4b1d-adfd-2b7c98667086)

**Comment by rwkay** [comment]
This is a legacy part of  GML and not something that will change on the current runtime, it is unlikely to be changed in GMRT (for compatibility reasons) but gmlv3 will address annoyances like this.
