### ISSUE TITLE
Manual Content: Draw Stacked Sprites page has incorrect usage of "sprites" in its function description

### ISSUE THREAD

**Issue by pdseventyeight** [YoYoGames/GameMaker-Bugs#8780]
### Description

"This action will draw a sprite a given number of **sprites** one after another at a given position within the room." 

### Manual Link

https://manual.gamemaker.io/monthly/en/#t=Drag_And_Drop%2FDrag_And_Drop_Reference%2FDrawing%2FDraw_Stacked_Sprites.htm

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1300.0.722  Runtime v2024.1300.0.735
