### ISSUE TITLE
Code Editor 2: Suggestions for improvements

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#8794]
### Is your feature request related to a problem?

I don't wanna make every new issue for every suggestion i have, so i will just clamp it in one. Basically, i will write all of my answers after describing my problems! So let's start!

1. Creating strings, brackets and stuff like that in a selection
2. More visible syntax error
3. Brick back F4 key from old code editor
4. Clickable functions and assets when holding control key

### Describe the solution you'd like

1. Creating strings, brackets and stuff like that in a selection
Basically, this is a nice thing from Visual Studio which i think it would be nice in new code editor. Here's a GIF example of what i mean:
![Image](https://github.com/user-attachments/assets/ca58953a-3584-43ee-b07c-5711350b57a1)

2. More visible syntax error
I personally think that syntax error is barely visible in the new code editor, like i wouldn't notice it until the game compiles itself, my solution for this is simply to make a red line on the line where syntax error is located at, here's a mock-up example:
![Image](https://github.com/user-attachments/assets/4bc73f76-1b6d-453a-9545-7260290da3d6)
[NOTE: This is a bug with CE2 as well in the screenshots, sometimes variables will be incorrectly coded for whatever reason, state is colored after global variable and `hold_action` is gray colored like it doesn't exist]

3. Brick back F4 key from old code editor
For whatever reason this feature is removed, it really messes up my muscle memory when i need to do a for loop for example, because it was faster to do it that way, and i'm probably not alone on that one.

4. Clickable functions and assets when holding control key
Another feature from Visual Studio that i think would be cool, basically in Visual Studio when you hold control key you can click on the function to open from what file it came from, and honestly i think that would be nice, Here's a gif example of what i mean:
![Image](https://github.com/user-attachments/assets/089c48d9-09ef-4b9f-b90b-12c91bbd93c6)

**Comment by KormexGit** [comment]
For #3, snippets are actually part of autocomplete now, so if you type `for` and hit enter it will fill out the for snippet

**Comment by jackerley** [comment]
Please submit only one feature per issue, otherwise it is impossible for us to allocate them to be fixed\approved\rejected.

Thanks
