### ISSUE TITLE
Code Editor 2: Few bug reports in one

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#8795]
### Description

These are small bugs that weren't present in previous code editor, so instead of making multiple of issues i will just cramp them into one.

1. Making new lines in indented spaces doesn't indent the line
Basically for some odd when i make a new line in indented spaces, that line of code doesn't indent like it used to in CE1
![Image](https://github.com/user-attachments/assets/a35aff15-16ba-4404-95f3-2fd7baf76db5)

2. Variables being incorrectly color coded
There were multiple instances of variables and global variables using wrong color, and the outcome of that bug seems to be very random, Here are some example images:
![Image](https://github.com/user-attachments/assets/480c08ae-52d2-4fea-903b-ad9a5bcc28e7)
![Image](https://github.com/user-attachments/assets/25faa8ef-a2b5-473f-865c-ef1228d1852e)

Honestly i hope these issues get fixed quickly in a patch or in next update or something, because this code editor has so much potential and i like it so far!

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Please submit only one feature per issue, otherwise it is impossible for us to allocate them to be fixed\approved\rejected.

Thanks
