### ISSUE TITLE
Code Editor 2: Three problems found

### ISSUE THREAD

**Issue by Freeflip** [YoYoGames/GameMaker-Bugs#8805]
### Description

In the new code editor (beta) I found the following 3 errors:

- when you reopen a project, if there were open notes, the window with the formatted code is always empty, you have to close the note and open it again.
- the words written after #region are colored in green and not in blue (as it should be)... the color is correct in the settings must be kept the color of the comments.
- sometimes, in the "text" the symbol \n does not color correctly red but colors only the "n" and the next letter.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
3 errors means 3 reports required ;)

**Comment by jackerley** [comment]
Please submit only one feature per issue, otherwise it is impossible for us to allocate them to be fixed\approved\rejected.

Thanks
