### ISSUE TITLE
Debugger: Breakpoint are able to be added to blank lines

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8811]
### Description

In the code editor breakpoints are currently allowed to be added to lines that contain no code, this shouldn't be allowed, breakpoints should only be added to lines that contain code/

![Image](https://github.com/user-attachments/assets/f0ef0f6e-f014-41e3-abe5-a9a6277bafe1)

### Steps To Reproduce

1. Start GameMaker
2. Create a project with an object/script
3. Hit enter a few times to create empty lines
4. Now add in breakpoints
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly), 2022.0.3 (LTS), 2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
This is as per Visual Studio, then as long as it breaks on the next valid line then this should be ok?
