### ISSUE TITLE
Errors from built .exe's always show "(line -1)"

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#8817]
### Description
I've noticed that when i've sent builds to testers, any time they get an error it never gives the actual line numbers - always "-1". I've spoken with other developers, and played their test builds, and they also are not getting line numbers with their errors.

### Steps To Reproduce
In a new project, create a script and write 
```gml
sprite = error
```
Running the project, it will create an error message with "line 1". However, if you build an exe (attached in this report) it will always show -1. No matter what the error, -1 will always appear in the callstack.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.11.0.179 Runtime v2024.11.0.226

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

### Which platform(s) are you seeing the problem on?
Windows

### Attached Files
* BLANK GAME_25.zip

[a694542f-8a39-4a4a-ae39-d5df9e75b59c](https://api.gamemaker.io/api/github/downloads/a694542f-8a39-4a4a-ae39-d5df9e75b59c)

**Comment by backYard321** [comment]
Even this screenshot from Toby Fox's twitter shows "(line -1)" in an error message, so i imagine this is a widespread problem.

![Image](https://github.com/user-attachments/assets/67ff80c4-6ca7-4a07-9041-9d33026b621f)

**Comment by rwkay** [comment]
Final executables do not have the debug information (which contains all the source to the game) so that you are not shipping the source of the game.

You can distribute a debug build of your game if you want to get line numbers.

**Comment by backYard321** [comment]
Okay, sounds good. Can you point me to a resource explaining how to create a distributable debug build?

**Comment by jarrrodnb** [comment]
You can compile the final build as YYC, the error messages are often less descriptive but you'll get line numbers.

**Comment by backYard321** [comment]
> You can compile the final build as YYC, the error messages are often less descriptive but you'll get line numbers.

Thank you! I'm new to YYC (bugs prevented me from implementing it prior to 2024.11), but knowing it has this functionality is a relief. Seems like a valid tradeoff.
