### ISSUE TITLE
Code Editor 2: Clickable functions and assets when holding control key

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#8820]
### Is your feature request related to a problem?

Another nice feature from Visual Studio that would be nice in the editor

### Describe the solution you'd like

Another feature from Visual Studio that i think would be cool, basically in Visual Studio when you hold control key you can click on the function to open from what file it came from, and honestly i think that would be nice, Here's a gif example of what i mean:
![Image](https://github.com/user-attachments/assets/f7a3d08d-1ec7-4ef3-b6e5-2119219cb0cc)

**Comment by KormexGit** [comment]
You can do this in GM already with middle click or pressing F1

**Comment by jackerley** [comment]
Closing as above
