### ISSUE TITLE
Code Editor 2: Variables being incorrectly color coded

### ISSUE THREAD

**Issue by DarkD04** [YoYoGames/GameMaker-Bugs#8822]
### Description

There were multiple instances of variables and global variables using wrong color, and the outcome of that bug seems to be very random, Here are some example images:
![Image](https://github.com/user-attachments/assets/976ebe1b-1ed0-4c96-9e1f-ac111cd30a12)
![Image](https://github.com/user-attachments/assets/08295cb0-d4fe-4e9b-ace6-dfb7afd88d85)

### Steps To Reproduce

1. Just type a variable name or something and see if it happens

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by DarkD04** [comment]
For an issue that happens randomly and fixes itself when it feels like it/when ide resets? I'm absolutely not sending any projects.
