### ISSUE TITLE
Line breaks are removed from <pre> contents if the search highlights text within it

### ISSUE THREAD

**Issue by L-Clouds** [YoYoGames/GameMaker-Bugs#8832]
### Description

If you perform a search in the manual and visit one of the results, if the search highlights text that's inside a `<pre>` tag, new lines are stripped from the `<pre>` tag's contents - not that the CSS stops preserving line breaks, but the line breaks are actually absent from the HTML text content.  The "Remove Highlights" button does not bring them back.

Examples:
First shader code example is missing line breaks: https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FVideos%2FYUV_Videos.htm&rhsearch=sampler2d&rhhlterm=sampler2d
![Image](https://github.com/user-attachments/assets/5a83876c-bb8a-4a0a-bb50-9ae4d12311fb)

Same page, but with a different search having been performed, first shader code example is OK, second shader code section is missing line breaks: https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FDrawing%2FVideos%2FYUV_Videos.htm&rhsearch=video_get_format&rhhlterm=video_get_format
![Image](https://github.com/user-attachments/assets/841ea138-7a64-4025-b840-84a35660ee13)

**Comment by gurpreetsinghmatharoo** [comment]
This was an issue on just the YUV Videos page, the code blocks weren't formatted properly. I've fixed that in the source.

**Comment by mgeddesGM** [comment]
verified
