### ISSUE TITLE
bring back the function viewer in the new code editor

### ISSUE THREAD

**Issue by MilkshakeDev** [YoYoGames/GameMaker-Bugs#8887]
### Is your feature request related to a problem?

im not really sure what to call it, but the new code editor is lacking the old function viewer, which i use all the time when writing code in gamemaker. im specifically refering to this
![Image](https://github.com/user-attachments/assets/bf666d05-56b5-4199-b755-da1d8391a481)

### Describe the solution you'd like

the solution would to just add it back

**Comment by bocoboc** [comment]
Hi, more people want this feature in CE2. Issue #7688 already exists.

**Comment by alicemoretti** [comment]
Closing as a duplicate of #7688 . 

Thank you
