### ISSUE TITLE
Image Editor: Old images remain in project's sprite folder when using Import Strip Image command

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#893]
GM-7491

When replacing a sprite's image using the Import Strip Image command, the old images remain in the project's sprite folder as well as the new images, which can quickly bloat a project on disk.

*Expected:* The only images saved in the project's sprite folder are the active images, not the replaced images.

*Steps:*
1. Start GM and create a new project.
2. Create a new sprite and jump into the image editor.
3. At the top of the window, click Image > Import Strip Image and upload ANY image.
4. Use any combination of values, (eg., 9 frames over 3 rows) and press convert.
5. Save project and then repeat steps 3 and 4 again with another image.
6. Save project again and then go into the project's sprite folder to see images from both uploads in there.

**Comment by iampremo** [comment]
fixed with https://github.com/YoYoGames/YoYoStudio/pull/8723

**Comment by mgeddesGM** [comment]
verified as of  IDE v2023.1100.0.450  Runtime v2023.1100.0.459
