### ISSUE TITLE
Code Editor: [Mac IDE] Unable to toggle Search in Replace button

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#899]
GM-7470

When Mac users in script editor press CMD+F to bring up the Find box, the Replace toggle appears to be greyed out. The hotkey for Search in Replace on Windows is Ctrl+H, but CMD+H on Mac appears to be intercepted by Mac itself and tabs out of Gamemaker.

*Expected:* Mac users should be able to toggle the Search in Replace button through a hotkey and by pressing the button in Search in Find.

*Steps:*
1. Start GM and open any project on Mac.
2. Open a script.
3. Press CMD+F.
4. Press CMD+H.
5. Try to interact with Search in Replace button.

**Comment by SmithTom6304** [comment]
Fixed. Have changed the Open Replace in Script hotkey on mac from `Command + H` to `Command + Shift + H`.

**Comment by YYDan** [comment]
Updated the info and the steps.

This is a very old report originally, and so I am not sure what the situation was at the time it was first filed as a ticket, but I see no issues with clicking the replace button in 2023.8.2 and some older Beta versions, so I left that out of of the repro steps for verifying this fix.
