### ISSUE TITLE
IDE - IDE pauses startup when moved to second monitor (On Macbook pro)

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#915]
GM-7146

In the latest release build  IDE v2023.2.0.71  Runtime v2023.2.0.87

*On Mac*
During startup, If the IDE opens on the main display and is moved to a secondary display with a different resolution (lower in this instance), the launch of the programme is paused and the splash screen disappears.

The IDE only resumes launch, once moved back to the main display.

This never happened in the previous release.

*Steps to reproduce in this particular example:*
Main display of (3840x2160) scaled to display at 2560x1440
Start up Gamemaker, see splash screen
During startup, move IDE to secondary monitor 1920x1080
Start screen disappears and startup pauses.
Move IDE back to main display
Splash screen re-appears and startup resumes.

Current IDE DPI settings: (for best display on a 1920x1080 monitor for Macbook Pro)
94% of native dpi 
96 Raw DPI value

**Comment by YYDan** [comment]
Old issue with no extra info, but ultimately this is waiting on https://github.com/YoYoGames/GameMaker-Bugs/issues/3196 so closing.
